### ISSUE TITLE
Setting the listen interfaces fails

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#1020]
libtorrent version (or branch): master
platform/architecture: windows
compiler and compiler version: VS2015

If I try to set the listen interfaces (settings_pack::listen_interfaces) for ipv4 and ipv6 right after the session is created the tcp sockets seem to get closed immediately (udp sockets work as expected). I did some debugging and the tcp sockets are open in reopen_listen_sockets() but they get closed from somewhere else, it seems.
Further attempts to set the listen_interfaces succeed.
Could there be a race condition between setting the defaults at session startup and calls to settings_pack::listen_interfaces?
Might it be necessary to wait for listen_succeeded_alert alerts before you can set a new one?

**Comment by arvidn** [comment]
I would not expect it to be a problem to update listen interfaces. Could you post the alerts you get? You may even want to enable session log alerts to see if there are any hints in there of what's going in.

**Comment by MassaRoddel** [comment]
I figured it out. In my client I tried to set the same listen interface twice (1. load_state(), 2. set_settings()) which fails. I guess it fails because setting the reuse option fails. Below are logs.

start session
config: ipv6_deprecated_ version: 1.2.0.0 revision: 62cdec8
   max connections: 200
   max files: 10000
 generated peer ID: 
 done starting session
update listen interfaces: 0.0.0.0:6881,[::]:6881
open listen port
closing all listen sockets
attempting to to open listen socket to: 0.0.0.0:6881 on device:  flags: 0
failed enable reuse-address on listen socket: Ein ungültiges Argument wurde angegeben
 listening on: 0.0.0.0 TCP port: 6881 UDP port: 6881
attempting to to open listen socket to: [::]:6881 on device:  flags: 0
failed enable reuse-address on listen socket: Ein ungültiges Argument wurde angegeben
 listening on: :: TCP port: 6881 UDP port: 6881
not starting DHT announce timer: m_dht == nullptr
update listen interfaces: 0.0.0.0:1032,[::]:1032
open listen port
closing all listen sockets
attempting to to open listen socket to: 0.0.0.0:1032 on device:  flags: 0
failed enable reuse-address on listen socket: Ein ungültiges Argument wurde angegeben
 listening on: 0.0.0.0 TCP port: 1032 UDP port: 1032
attempting to to open listen socket to: [::]:1032 on device:  flags: 0
failed enable reuse-address on listen socket: Ein ungültiges Argument wurde angegeben
 listening on: :: TCP port: 1032 UDP port: 1032
UDP error: 0.0.0.0:0 (995) Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen
UDP error: 0.0.0.0:0 (995) Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen
update listen interfaces: 0.0.0.0:1032,[::]:1032
>>> SET_TOS [ tcp (0.0.0.0 1032) tos: 0 e: Der Vorgang wurde erfolgreich beendet ]
>>> SET_TOS [ udp (0.0.0.0 1032) tos: 0 e: Der Vorgang wurde erfolgreich beendet ]
>>> SET_TOS [ tcp (:: 1032) tos: 0 e: Beim Aufruf von getsockopt oder setsockopt wurde eine nicht unterstützte Option bzw. Ebene angegeben ]
>>> SET_TOS [ udp (:: 1032) tos: 0 e: Beim Aufruf von getsockopt oder setsockopt wurde eine nicht unterstützte Option bzw. Ebene angegeben ]
not starting DHT announce timer: m_dht == nullptr
update listen interfaces: 0.0.0.0:1032,[::]:1032



update listen interfaces: 0.0.0.0:1033,[::]:1033
open listen port
closing all listen sockets
attempting to to open listen socket to: 0.0.0.0:1033 on device:  flags: 0
failed enable reuse-address on listen socket: Ein ungültiges Argument wurde angegeben
 listening on: 0.0.0.0 TCP port: 1033 UDP port: 1033
attempting to to open listen socket to: [::]:1033 on device:  flags: 0
failed enable reuse-address on listen socket: Ein ungültiges Argument wurde angegeben
 listening on: :: TCP port: 1033 UDP port: 1033
UDP error: 0.0.0.0:0 (995) Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen
UDP error: 0.0.0.0:0 (995) Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen
: set_external_address(93.207.221.215, 2, 73.80.18.214)
  external IP updated

**Comment by MassaRoddel** [comment]
Just to be clear, from the logs I cannot tell what the actual problem is. I just found a fix  for my client.

**Comment by MassaRoddel** [comment]
After some more debugging I found the problem.:
session_impl::update_force_proxy() closes the tcp sockets regardless of the setting force_proxy. Whenever a settings pack has the force_proxy entry the tcp sockets get closed.
What I did until now was:
call session::get_settings()
modify some entries
call session::apply_settings()
and so I got a force_proxy entry into the settings (although I never set it[ to true])

**Comment by arvidn** [comment]
Here's a patch against RC_1_1. It should apply cleanly against master too. Would you mind testing it?
https://github.com/arvidn/libtorrent/pull/1027

**Comment by MassaRoddel** [comment]
That patch works for me.

**Comment by arvidn** [comment]
This has been pushed to RC_1_1 and will be merged into master shortly
