### ISSUE TITLE
Question about how to persist DHT's stored items

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#103]
Hi @arvidn, I want to ask first if this is something that you are open to incorporate in the library.

My motivations is that in mobile devices, the process can be destroyed aggressively, and losing all the stored items (mutable and inmutable) does not help to the network. Also, this could open the door to very big tables without RAM penalty.

My idea is: some how provide a "dht_item_table_storage" whose default (and only) implementation is a RAM std::map as it is now. If you think this is a good idea, a will appreciate your tips about I should start passing this parameter.

**Comment by arvidn** [comment]
It does sound like a good idea to be able to customize how DHT values are stored (and maybe not just blobs, but peers too). I would imagine something like an interface that can be implemented and passed to the session, similar to storage_interface (but presumably a lot simpler). I would imagine the main implementation (other than a default std::map) would sit on top of sqlite. The interface should probably make it simple to wrap a sqlite table.

It would probably not be appropriate to configure this via the settings_pack, since it's an irregular value (i.e. pointer to an object). The only think I can think of off hand would be a separate member function on session to pass a boost::shared_ptr<dht_storage_interface>.

One potential issue is performing blocking I/O in such extension. I wonder if there would be an easy way to make this part of the DHT asynchronous, and issue the calls in a separate thread. It may be a bit heavy weight too.

**Comment by aldenml** [comment]
Thank you for your comments. I will try to work in a PR with a narrow scope. I just want to provide the extension point, an actual implementation different from std::map is far from trivial, the asynchronous feature and a possible memory cache being two important issues. I will keep this issue around and close it when the PR gets merged.

**Comment by aldenml** [comment]
@arvidn I'm looking for the necessary bits for the change and the first one I would like to have your opinion is the iterator interface (I rather not divert from the current code one). I see `list_iterator` and `tailqueue_iterator` as posible examples, but they are different to boost, std, java, etc.

If you want to follow this style, how do you think I should deal with the begin and end in the map-style interface? With a pointer to the pair, the element or the key?

**Comment by arvidn** [comment]
I would expect a higher level interface. All lookups are "hash"-style. There's no operation the requires actual iteration of items. So, I imagine an interface something like:

    dht_item get_item(sha1_hash);
    void store_item(sha1_hash, dht_item);
    std::vector<peers> get_peers(sha1_hash);
    void add_peer(sha1_hash, endpoint);

something along those lines. For traditional peers, perhaps there need to be some ticking to expire peers as well. I think exposing an iterator-like interface would be very complicated and ideally we could avoid that.

**Comment by arvidn** [comment]
btw. those other iterators you mentioned are not meant to be examples of good coding practice :) they're just quick hacks.

**Comment by aldenml** [comment]
@arvidn What do you think about this interface? https://github.com/aldenml/libtorrent/commit/66eeac26e21847917ff577669e05df4d135967c5

**Comment by aldenml** [comment]
Answering myself: No, I don't think its a good interface, torrent_entry, dht_immutable_item, dht_mutable_item seems like internal structures of a particular implementation.

**Comment by aldenml** [comment]
Hi @arvidn, I appreciate if you have some time to review this PR https://github.com/arvidn/libtorrent/pull/123

Thanks

**Comment by aldenml** [comment]
Well, it's merged the first part (https://github.com/arvidn/libtorrent/pull/123). Now, I think the next two steps are:

1- Async operations.
2- Final exposition of API

@arvidn If you have some entry points (or lines of code) that I can take a look for point 1. It will be helpful.

**Comment by arvidn** [comment]
I don't really have any solid thoughts about (1). I think it's probably fine to punt on it for a while. In my mind, the most likely use case would be to store data in a sqlite3 database, and the cache misses you get there are probably not too dissimilar to what you would get with a page fault that needs to pull in a page from swap. It's still not great given the main network loop get halted.

What I can imagine off the top of my head is to incorporate an asio::io_service and have the storage post callbacks when done. But then a lot of the DHT message handling logic would need to be changed to support async. operations too.

**Comment by thomas-yuan** [comment]
＠aldenml, one question, if the total memory usage by items (mutable/immutable) is only about 2M, why would we need a storage interface?

**Comment by aldenml** [comment]
Hi @thomas-yuan, glad you ask. I think the explanation is pretty much in the opening of the issue. Also, the amount of items is configurable, not necessarily about 2MB.

**Comment by aldenml** [comment]
To document, these PRs improve the default dht storage: https://github.com/arvidn/libtorrent/pull/152, https://github.com/arvidn/libtorrent/pull/163 and https://github.com/arvidn/libtorrent/pull/163.

Now is the time for final exposition of the API. At the beginning I was thinking of passing the function constructor as a parameters in the session constructor (similar to the add_torrent_params) but I'm not sure if it's a desired path. If we pass it as a method (setter in session), I'm a cautious about how to deal with the timing of the dht start. @arvidn I appreciate your comments here.

**Comment by arvidn** [comment]
right. fundamentally, in master (as opposed to previous releases) I've been trying to more strictly follow the pattern of not having half-constructed objects. with regards to the session, that means being able to construct and configure it in a single step. This is why the constructor now takes the settings_pack.

The two options I see of the top of my head are:
1. a session parameter
2. an entry in settings_pack (which would also require a new category of types in there, and might be a bit messy)

I'm not really a big fan of either. (1) makes it messy when building with DHT disabled and clutters the top level of the session (something I've been working hard to clean up and simplify). (2) will either have cery specialized members in the settings_pack, or there will be a type safety compromise.

given that you're unlikely to start storing keys immediately as you bootstrap, perhaps it's OK to change the storage after the DHT has been started. It wouldn't be a very elegant solution either though, but maybe the best one.

**Comment by aldenml** [comment]
I settled for a session method but with the restriction that the dht can't be running: https://github.com/arvidn/libtorrent/pull/189

**Comment by aldenml** [comment]
Closed with this: https://github.com/arvidn/libtorrent/pull/189
