### ISSUE TITLE
Can't compile latest master (1.2.0)

### ISSUE THREAD

**Issue by RDgiuliom** [arvidn/libtorrent#1031]
**Please provide the following information**

libtorrent version (or branch): master (1.2.0)

platform/architecture: armhf (Lemaker BananaPi)

compiler and compiler version: gcc 4.9.2

Hi, I'm having troubles compiling latest master of LT, I'm getting this error:

`../include/libtorrent/entry.hpp:283:8: error: 'aligned_union' in namespace 'std' does not name a template type`

even tough I'm using `CXXFLAGS= -std=c++11`

Here my config.log: http://pastebin.com/RVPyFbZU

Here my configure report: http://pastebin.com/sRpNFLew

Here the complete make log: http://pastebin.com/ybvRBs3d

Is there something I'm missing?

Thanks!

**Comment by aldenml** [comment]
You need a fully c++11 compiler, like gcc 5.X, take a look at https://github.com/arvidn/libtorrent/blob/master/.travis.yml#L93

**Comment by RDgiuliom** [comment]
Guess I have to compile gcc from scratch then... :\

**Comment by aldenml** [comment]
Can't you use one from linaro?

**Comment by RDgiuliom** [comment]
All linaro's software seems to be compiled for armv8, I'm on armv7... and to be completely honest I don't know how I could use the linked package...not too skilled with compilers :|

**Comment by aldenml** [comment]
Well, if that's the case, I guess it's a lot easier to figure out how to use a toolchain than build a new one :)

None of the linaro toolchains will work in your platform, all of them are for cross compiling. Have you tried that?

**Comment by RDgiuliom** [comment]
Took the easy way...setup a chroot with Debian Testing having gcc 6 in its repo, compiled and created the .deb package...

Thanks for your hints!
