### ISSUE TITLE
Building 1.0.6 on Visual Studio 2015 with Boost 1.59

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#104]
<addr>BOOST_ROOT = C:\Boost-1.59-(vs2015)\boost_1_59_0
CXXFLAGS =
LDFLAGS =
OS = NT
Performing configuration checks

    - 32-bit                   : yes
    - arm                      : no
    - mips1                    : no
    - power                    : no
    - sparc                    : no
    - x86                      : yes
    - symlinks supported       : yes
...patience...
...patience...
...found 2279 targets...
...updating 117 targets...
common.mkdir bin
common.mkdir bin\msvc-14.0
common.mkdir bin\msvc-14.0\release
common.mkdir bin\msvc-14.0\release\boost-source
common.mkdir bin\msvc-14.0\release\boost-source\link-static
common.mkdir bin\msvc-14.0\release\boost-source\link-static\runtime-link-static
common.mkdir bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi
common.mkdir bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\alert.obj
alert.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\alert_manager.obj
alert_manager.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\allocator.obj
allocator.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\asio.obj
asio.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\assert.obj
assert.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\bandwidth_limit.obj
bandwidth_limit.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\bandwidth_manager.obj
bandwidth_manager.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\bandwidth_queue_entry.obj
bandwidth_queue_entry.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\bloom_filter.obj
bloom_filter.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\chained_buffer.obj
chained_buffer.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\connection_queue.obj
connection_queue.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\create_torrent.obj
create_torrent.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\disk_buffer_holder.obj
disk_buffer_holder.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\entry.obj
entry.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\error_code.obj
error_code.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\file_storage.obj
file_storage.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\lazy_bdecode.obj
lazy_bdecode.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\escape_string.obj
escape_string.cpp
src\escape_string.cpp(75): warning C4146: unary minus operator applied to unsigned type, result still unsigned
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\string_util.obj
string_util.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\file.obj
file.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\gzip.obj
gzip.cpp
src\gzip.cpp(214): warning C4101: 'e': unreferenced local variable
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\hasher.obj
hasher.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\http_connection.obj
http_connection.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\http_stream.obj
http_stream.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\http_parser.obj
http_parser.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\identify_client.obj
identify_client.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\ip_filter.obj
ip_filter.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\ip_voter.obj
ip_voter.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\peer_connection.obj
peer_connection.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\bt_peer_connection.obj
bt_peer_connection.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\web_connection_base.obj
web_connection_base.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\web_peer_connection.obj
web_peer_connection.cpp
src\web_peer_connection.cpp(878): warning C4244: '=': conversion from 'libtorrent::size_type' to 'int', possible loss of data
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\http_seed_connection.obj
http_seed_connection.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\i2p_stream.obj
i2p_stream.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\instantiate_connection.obj
instantiate_connection.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\natpmp.obj
natpmp.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\packet_buffer.obj
packet_buffer.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\piece_picker.obj
piece_picker.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\policy.obj
policy.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\puff.obj
puff.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\random.obj
random.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\rss.obj
rss.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\session.obj
session.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\session_impl.obj
session_impl.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\settings.obj
settings.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\socket_io.obj
socket_io.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\socket_type.obj
socket_type.cpp
src\socket_type.cpp(72): warning C4800: 'const libtorrent::utp_stream *': forcing value to bool 'true' or 'false' (performance warning)
src\socket_type.cpp(82): warning C4800: 'const libtorrent::i2p_stream *': forcing value to bool 'true' or 'false' (performance warning)
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\socks5_stream.obj
socks5_stream.cpp
src\socks5_stream.cpp(232): warning C4267: 'argument': conversion from 'size_t' to 'uint8_t', possible loss of data
src\socks5_stream.cpp(234): warning C4267: 'argument': conversion from 'size_t' to 'uint8_t', possible loss of data
src\socks5_stream.cpp(332): warning C4267: 'argument': conversion from 'size_t' to 'uint8_t', possible loss of data
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\stat.obj
stat.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\storage.obj
storage.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\torrent.obj
torrent.cpp
src\torrent.cpp(254): warning C4800: 'uint64_t': forcing value to bool 'true' or 'false' (performance warning)
src\torrent.cpp(1659): warning C4244: 'argument': conversion from 'libtorrent::size_type' to 'int', possible loss of data
src\torrent.cpp(1819): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(1836): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(1899): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(1915): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(2739): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(2894): warning C4244: '+=': conversion from 'libtorrent::size_type' to 'int', possible loss of data
src\torrent.cpp(2978): warning C4244: 'argument': conversion from 'libtorrent::size_type' to 'int', possible loss of data
src\torrent.cpp(3220): warning C4244: 'initializing': conversion from 'const libtorrent::size_type' to 'int', possible loss of data
src\torrent.cpp(3915): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(4626): warning C4244: '+=': conversion from 'libtorrent::size_type' to 'uint32_t', possible loss of data
src\torrent.cpp(4627): warning C4244: '+=': conversion from 'libtorrent::size_type' to 'uint32_t', possible loss of data
src\torrent.cpp(4630): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(5263): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(5266): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(5269): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(5272): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(5275): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(5278): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(5279): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
src\torrent.cpp(5281): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(5282): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
src\torrent.cpp(5284): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(5285): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
src\torrent.cpp(5287): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(5295): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(5296): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
src\torrent.cpp(5297): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(5298): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
src\torrent.cpp(5299): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(5300): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
src\torrent.cpp(5370): warning C4244: '=': conversion from 'int64_t' to 'unsigned char', possible loss of data
src\torrent.cpp(5926): warning C4244: '=': conversion from 'int64_t' to 'uint16_t', possible loss of data
src\torrent.cpp(6086): warning C4800: 'libtorrent::peer_connection *': forcing value to bool 'true' or 'false' (performance warning)
src\torrent.cpp(6278): warning C4018: '>': signed/unsigned mismatch
src\torrent.cpp(6318): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(8629): warning C4018: '>': signed/unsigned mismatch
src\torrent.cpp(8955): warning C4244: '=': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(9090): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data
src\torrent.cpp(9503): warning C4800: 'uint32_t': forcing value to bool 'true' or 'false' (performance warning)
src\torrent.cpp(9529): warning C4244: 'argument': conversion from 'int64_t' to 'long', possible loss of data
src\torrent.cpp(9600): warning C4244: '=': conversion from 'libtorrent::size_type' to 'int', possible loss of data
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\torrent_handle.obj
torrent_handle.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\torrent_info.obj
torrent_info.cpp
src\torrent_info.cpp(527): warning C4244: 'return': conversion from 'int64_t' to 'int', possible loss of data
src\torrent_info.cpp(530): warning C4244: 'return': conversion from 'int64_t' to 'int', possible loss of data
src\torrent_info.cpp(895): warning C4800: 'uint32_t': forcing value to bool 'true' or 'false' (performance warning)
src\torrent_info.cpp(896): warning C4800: 'uint32_t': forcing value to bool 'true' or 'false' (performance warning)
src\torrent_info.cpp(897): warning C4800: 'uint32_t': forcing value to bool 'true' or 'false' (performance warning)
src\torrent_info.cpp(949): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\torrent_info.cpp(1088): warning C4800: 'int64_t': forcing value to bool 'true' or 'false' (performance warning)
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\time.obj
time.cpp
src\time.cpp(63): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\tracker_manager.obj
tracker_manager.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\http_tracker_connection.obj
http_tracker_connection.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\udp_tracker_connection.obj
udp_tracker_connection.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\sha1.obj
sha1.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\timestamp_history.obj
timestamp_history.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\udp_socket.obj
udp_socket.cpp
src\udp_socket.cpp(1166): warning C4267: 'argument': conversion from 'size_t' to 'uint8_t', possible loss of data
src\udp_socket.cpp(1168): warning C4267: 'argument': conversion from 'size_t' to 'uint8_t', possible loss of data
src\udp_socket.cpp(1469): warning C4244: '+=': conversion from 'uint64_t' to 'int', possible loss of data
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\upnp.obj
upnp.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\utf8.obj
utf8.cpp
src\utf8.cpp(61): error C2039: 'back_inserter': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\string(17): note: see declaration of 'std'
src\utf8.cpp(61): error C3861: 'back_inserter': identifier not found
src\utf8.cpp(78): error C2039: 'back_inserter': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\string(17): note: see declaration of 'std'
src\utf8.cpp(78): error C3861: 'back_inserter': identifier not found

    call "C:\Users\Admin\AppData\Local\Temp\b2_msvc_14.0_vcvarsall_x86.cmd" >nul
cl /Zm800 -nologo @"bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\utf8.obj.rsp" 

...failed compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\utf8.obj...
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\utp_socket_manager.obj
utp_socket_manager.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\utp_stream.obj
utp_stream.cpp
src\utp_stream.cpp(2166): warning C4244: '=': conversion from 'int64_t' to 'int32_t', possible loss of data
src\utp_stream.cpp(3239): warning C4244: '=': conversion from 'int64_t' to 'int32_t', possible loss of data
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\logger.obj
logger.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\file_pool.obj
file_pool.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\lsd.obj
lsd.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\disk_buffer_pool.obj
disk_buffer_pool.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\disk_io_thread.obj
disk_io_thread.cpp
src\disk_io_thread.cpp(696): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data
src\disk_io_thread.cpp(697): warning C4244: '+=': conversion from 'int64_t' to 'uint32_t', possible loss of data
src\disk_io_thread.cpp(1336): warning C4101: 'e': unreferenced local variable
src\disk_io_thread.cpp(1389): warning C4244: 'return': conversion from 'libtorrent::size_type' to 'int', possible loss of data
src\disk_io_thread.cpp(1464): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
src\disk_io_thread.cpp(1476): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
src\disk_io_thread.cpp(1710): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data
src\disk_io_thread.cpp(1711): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data
src\disk_io_thread.cpp(1712): warning C4244: '+=': conversion from 'int64_t' to 'uint32_t', possible loss of data
src\disk_io_thread.cpp(1713): warning C4244: '+=': conversion from 'int64_t' to 'uint32_t', possible loss of data
src\disk_io_thread.cpp(1765): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data
src\disk_io_thread.cpp(1835): warning C4244: '=': conversion from 'uint64_t' to 'int', possible loss of data
src\disk_io_thread.cpp(2085): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data
src\disk_io_thread.cpp(2086): warning C4244: '+=': conversion from 'int64_t' to 'uint32_t', possible loss of data
src\disk_io_thread.cpp(2181): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data
src\disk_io_thread.cpp(2182): warning C4244: '+=': conversion from 'int64_t' to 'uint32_t', possible loss of data
src\disk_io_thread.cpp(2273): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data
src\disk_io_thread.cpp(2274): warning C4244: '+=': conversion from 'int64_t' to 'uint32_t', possible loss of data
src\disk_io_thread.cpp(2428): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\disk_io_thread.cpp(2443): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data
src\disk_io_thread.cpp(2444): warning C4244: '+=': conversion from 'int64_t' to 'uint32_t', possible loss of data
src\disk_io_thread.cpp(2516): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data
src\disk_io_thread.cpp(2517): warning C4244: '+=': conversion from 'int64_t' to 'uint32_t', possible loss of data
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\enum_net.obj
enum_net.cpp
src\enum_net.cpp(988): warning C4018: '<': signed/unsigned mismatch
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\broadcast_socket.obj
broadcast_socket.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\magnet_uri.obj
magnet_uri.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\parse_url.obj
parse_url.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\ConvertUTF.obj
ConvertUTF.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\thread.obj
thread.cpp
src\thread.cpp(123): warning C4244: 'argument': conversion from 'int64_t' to 'DWORD', possible loss of data
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\xml_parse.obj
xml_parse.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\metadata_transfer.obj
metadata_transfer.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\ut_pex.obj
ut_pex.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\ut_metadata.obj
ut_metadata.cpp
src\ut_metadata.cpp(219): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\ut_metadata.cpp(223): warning C4244: 'initializing': conversion from 'int64_t' to 'int', possible loss of data
src\ut_metadata.cpp(333): warning C4244: 'initializing': conversion from 'const libtorrent::entry::integer_type' to 'int', possible loss of data
src\ut_metadata.cpp(334): warning C4244: 'initializing': conversion from 'const libtorrent::entry::integer_type' to 'int', possible loss of data
src\ut_metadata.cpp(374): warning C4244: 'argument': conversion from 'libtorrent::entry::integer_type' to 'int', possible loss of data
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\lt_trackers.obj
lt_trackers.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\smart_ban.obj
smart_ban.cpp
common.mkdir bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\ed25519
common.mkdir bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\ed25519\src
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\ed25519\src\add_scalar.obj
add_scalar.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\ed25519\src\fe.obj
fe.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\ed25519\src\ge.obj
ge.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\ed25519\src\key_exchange.obj
key_exchange.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\ed25519\src\keypair.obj
keypair.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\ed25519\src\sc.obj
sc.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\ed25519\src\seed.obj
seed.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\ed25519\src\sha512.obj
sha512.cpp
...on 100th target...
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\ed25519\src\sign.obj
sign.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\ed25519\src\verify.obj
verify.cpp
common.mkdir bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\kademlia
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\kademlia\dht_tracker.obj
dht_tracker.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\kademlia\find_data.obj
find_data.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\kademlia\get_item.obj
get_item.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\kademlia\get_peers.obj
get_peers.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\kademlia\item.obj
item.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\kademlia\logging.obj
logging.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\kademlia\node.obj
node.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\kademlia\node_id.obj
node_id.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\kademlia\refresh.obj
refresh.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\kademlia\routing_table.obj
routing_table.cpp
src\kademlia\routing_table.cpp(472): warning C4018: '>': signed/unsigned mismatch
src\kademlia\routing_table.cpp(871): warning C4018: '>': signed/unsigned mismatch
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\kademlia\rpc_manager.obj
rpc_manager.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\kademlia\traversal_algorithm.obj
traversal_algorithm.cpp
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\mpi.obj
mpi.c
compile-c-c++ bin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi\src\pe_crypto.obj
pe_crypto.cpp
...skipped <pbin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi>libtorrent.lib for lack of <pbin\msvc-14.0\release\boost-source\link-static\runtime-link-static\threading-multi>src\utf8.obj...
...failed updating 1 target...
...skipped 1 target...
...updated 115 targets...
</addr>

**Comment by aldenml** [comment]
Keep in mind that boost >= 1.56 in Windows + libtorrent seems to have a lot of performance problems.

**Comment by arvidn** [comment]
this was fixed right after the 1.0.6 cut. it should work in RC_1_0. hopefully I can cut 1.0.7 soon.
@aldenml what kinds of performance problems do you see with boost >= 1.56?

**Comment by aldenml** [comment]
@arvidn It's a network IO problem, see this thread: https://github.com/qbittorrent/qBittorrent/issues/2003#issuecomment-65486312

Unfortunately, we weren't able to determine what's the reason.

**Comment by Chocobo1** [comment]
Bumped into this too.
@Col-blimp 
see: https://github.com/arvidn/libtorrent/commit/f01a9bd8d056d47925056a5c32458be12cc0f570

**Comment by Col-blimp** [comment]
Thanks folks............
