### ISSUE TITLE
undefined reference to boost::chrono::steady_clock::now 

### ISSUE THREAD

**Issue by 1920x1080p** [arvidn/libtorrent#1058]
**Please provide the following information**

libtorrent version (or branch): 1.1.1

platform/architecture: Ubuntu 16.04.1 x86_64

compiler and compiler version: g++ 5.4.0

I build libtorrent from the following configure to build a static libtorrent only:

./configure --disable-shared

When linking my application i get the following link errors:

//usr/local/lib/libtorrent-rasterbar.a(alert.o): In function `libtorrent::alert::alert()':
libtorrent-rasterbar-1.1.1/src/alert.cpp:55: undefined reference to boost::chrono::steady_clock::now()'
//usr/local/lib/libtorrent-rasterbar.a(alert.o):libtorrent-rasterbar-1.1.1/src/alert.cpp:55: more undefined references to `boost::chrono::steady_clock::now()' follow

//usr/local/lib/libtorrent-rasterbar.a(random.o): In function `libtorrent::random()':
libtorrent-rasterbar-1.1.1/src/random.cpp:81: undefined reference to `boost::random::random_device::operator()()'
libtorrent-rasterbar-1.1.1/src/random.cpp:80: undefined reference to `boost::random::random_device::random_device()'
libtorrent-rasterbar-1.1.1/src/random.cpp:80: undefined reference to `boost::random::random_device::~random_device()'

If I build libtorrent without disabling shared my application link successfully against libtorrent.

**Comment by 1920x1080p** [comment]
libtorrent is built using the stock Ubuntu 16.04.1 boost libraries - v1.58

**Comment by arvidn** [comment]
you need to link against boost.chrono and boost.random. They won't be included in libtorrent since it's built as a static library. When building libtorrent as a shared library, its dependency on those boost libraries will be encoded in the DSO itself, but not when built as an archive.

**Comment by arvidn** [comment]
I would imagine you'd have the same issue with boost.system btw, ``error_code``.

**Comment by 1920x1080p** [comment]
Sorry I should have included in my original post - I am linking my application against boost_chrono and boost_random (and boost_system but I'm not seeing any undefined reference errors for boost_system).

g++ -m64 -Wl,-O1 -o myapp main.o work_config.o work_logger.o file_work_source.o sql_work_results.o sql_work_source.o sqs_work_source.o work_consumer.o work_producer.o work_results.o dht_work_source.o   -lboost_system -lboost_date_time -lboost_filesystem -lboost_thread -lboost_chrono -lboost_random -lglog -lconfig++ -ltorrent-rasterbar  -lcurl -lmysqlcppconn -lpthread -lssl -lcrypto 

I will put together a clean Ubuntu 16.04.1 VM and try building on that to rule out any old libs contaminating my build.

Thanks for the reply!

**Comment by 1920x1080p** [comment]
I installed a clean ubuntu 16.04.1 LTS VM and attempted to build my app which failed with the same undefined reference issue for:
boost::chrono::steady_clock::now()
boost::random::random_device::operator()()
boost::random::random_device::random_device()
boost::random::random_device::~random_device()

**Comment by arvidn** [comment]
look at what symbols your boost libraries export (the mangled names) and compare them to the mangled names libtorrent is looking for. It could be an ABI issue. If libtorrent was built with a different version of GCC than boost was, or perhaps with a different ABI version.

Also, make sure that you're not encountering the link command line order issue.

http://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc

**Comment by 1920x1080p** [comment]
Issue was a library ordering thing.

Thanks for the help.
