### ISSUE TITLE
"simple_client.cpp": Assertion failed: m_buckets.size() <= 50

### ISSUE THREAD

**Issue by cr33at** [arvidn/libtorrent#107]
I just compile and run the "examples/simple_client.cpp"(links to libws2_32 and libwsock32), and the console prints:

Assertion failed: m_buckets.size() <= 50, file src\kademlia\routing_table.cpp, line 458

I have tried to use "p.save_path = "E:\\";" instead of "p.save_path = "./";", but it doesn't work.
Another example "client_test.cpp" also get same assertion failed.
Thanks!

Environment:
os: windows (window 7)
compiler: gcc (tdm-gcc4.5.2)
libtorrent: 1.0.6 (use "b2 --toolset=gcc variant=debug" to compile)
boost: 1.59.0 (use "b2 --toolset=gcc variant=debug stage" to compile)

**Comment by arvidn** [comment]
this assert is incorrect. it has been removed from the code in the repository. I will make sure it's removed from the RC_1_0 branch too (for 1.0.7)

**Comment by arvidn** [comment]
fixed in https://github.com/arvidn/libtorrent/commit/e7b8b6da491f5ec27cf88b768191c79ebdcbf48a in master and https://github.com/arvidn/libtorrent/commit/a743f9706192d70aa596949374a672e9e623d279 in RC_1_0

**Comment by cr33at** [comment]
Thanks.
