### ISSUE TITLE
Crash with deluged on linux

### ISSUE THREAD

**Issue by ctag** [arvidn/libtorrent#1071]
**Please provide the following information**
- libtorrent version (or branch):

local/libtorrent-rasterbar 1:1.1-3
- platform/architecture:

Archlinux x64, kernel 4.7.2
- compiler and compiler version:
- please describe what symptom you see, what you would expect to see instead and
  how to reproduce it.

Deluged crashes after a few hours with the following backtrace.

```
*** Error in `/usr/bin/python2': free(): invalid next size (fast): 0x00007fed8d10eb60 ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x70c4b)[0x7fed99409c4b]
/usr/lib/libc.so.6(+0x76fe6)[0x7fed9940ffe6]
/usr/lib/libc.so.6(+0x777de)[0x7fed994107de]
/usr/lib/libtorrent-rasterbar.so.9(+0x2f97c0)[0x7fed922727c0]
/usr/lib/libtorrent-rasterbar.so.9(+0x2f9dce)[0x7fed92272dce]
/usr/lib/libtorrent-rasterbar.so.9(+0x2fa425)[0x7fed92273425]
```

http://dev.deluge-torrent.org/ticket/2876

**Comment by arvidn** [comment]
please build a debug version of libtorrent to get more useful output.

**Comment by ctag** [comment]
I apologize for the stagnation on my end. I've just gotten deluge running again and cannot reproduce the behavior here; it appears a package update somewhere along the way has solved this issue.
