### ISSUE TITLE
setup.py needs modification to correctly compile python bindings

### ISSUE THREAD

**Issue by RDgiuliom** [arvidn/libtorrent#1076]
libtorrent version (or branch): 1.2.0 master

platform/architecture: Ubuntu Xenial Arm64

compiler and compiler version: gcc 5.4 - distutils

Hi, compiling the master branch with `--enable-python-binding` generates this error:

`Traceback (most recent call last):
  File "./setup.py", line 117, in <module>
    os.environ["CC"] = os.environ['CXX']
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'CXX'
Makefile:527: recipe for target 'all-local' failed
`

The problem seems to be solved after I've modified `bindings/python/setup.py` at line 117 with:

`os.environ["CC"] = "gcc -std=gnu++11"
 os.environ['CXX'] = "gcc -std=gnu++11"`

Now I'm able to correctly compile even tough I'm not sure this causes any problems.

P.S. = I'm already using `-std=c++11` in `CXXFLAGS`

**Comment by arvidn** [comment]
it the underlying problem that the ``CXX`` environment variable isn't set? if so, do you know why it isn't set? I was under the impression the makefiles would set it

**Comment by RDgiuliom** [comment]
CXX wasn't set, now works ok. Thanks for the input.

Closing.
