### ISSUE TITLE
multi-home support and BEP 45

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#1081]
Hello, I want to create a solution to pass a "dht state" while creating the session. This allows for a more direct DHT bootstrap and avoids the double DHT recreation in libtorrent. This state is just a couple of ids and a set of endpoints. Now is when things start to get tricky (at least for me).

The couple of ids means an id for IPv4 and other for IPv6, and the set of endpoints are easy to discriminate by protocol to bootstrap the two DHTs. This assumes a complete implementation of BEP 32.

Now, from an architectural point of view, an easy solution is to have a table of DHTs and having them identified by some sort of key (protocol id, iface, etc). This in turns allows for a smooth transition for an eventual implementation of BEP 45.

The question at this moment is: How I deal with the `want` field?

Thanks

**Comment by aldenml** [comment]
Hi @ssiloti, maybe you thought about this problem when you added the field `dht_tracker::m_nodes`

**Comment by arvidn** [comment]
forgive my ignorance. the ``want`` field is how you tell people about whether you want IPv6 or IPv4 nodes in ``findnodes`` requests, right? How is that related to the startup state to initialize node id and the routing table from?

Perhaps node IDs should be in a map from IP address -> node_id, where the IP is the external IP address that node ID was associated with. If we still have one of those external IPs, we keep using the same node id.

Should this state contain storage too? i.e. peer lists and data blobs stored on our node?

**Comment by aldenml** [comment]
Yes, that's the field to do that. There is actually no theoretical relationship, I just wanted to document the practical path I'm following. I see in the revamp of the "dht state", a good opportunity to generalize the concept of multiple DHTs in `dht_tracker`. (I have other ideas for the storage, but for later).

My problem is that BEP 32 clearly documents how to use the `want` field in the context of only two DHTs (v4 and v6), but I can't see how to translate/extend that idea to more than two (as in BEP 45).

**Comment by arvidn** [comment]
well, regardless of how many external IPs you have, you won't have more than two *address families*. My understanding is that that's all the ``want`` field indicates. Which address families you support.

**Comment by aldenml** [comment]
hmm...so, if I have for example: five DHT IPv4 and other three DHT IPv6, then if a `want` from an IPv4 request from IPv6, do I need to iterate all of them to return the nodes? If this is correct, how I select the subset, random, shuffle, bias?

**Comment by arvidn** [comment]
@the8472 do you have any thoughts?

**Comment by the8472** [comment]
Those concerns are orthogonal.

----

`want` only specifies the address family:

dictionary key not present -> address family is implicit, derived from *\<insert socket API magic here\>* corresponding to the received packet
[n4] -> only return ipv4
[n6] -> only return ipv6
[n4,n6] -> both

In practice you should only be requesting both when bootstraping or doing routing table maintenance if you need cross-seeding, i.e. if one address family has underpopulated routing tables.

----

About the selection:  The general rule is that you always pick the N nodes closest to the target ID. It has always been this way for kademlia, multi-address operation does not change that.
The only wiggle room here is *N out of which set*?

You have the following options:

a) use a [shared routing table](http://bittorrent.org/beps/bep_0045.html#shared-routing-table) for all socket addresses of the same address family. Shared means there is only one per address family.... which means that's the only one you can pick.
b) use one routing table per socket address, then iterate over all routing tables of the same address type and build an N-closest set by... well... picking the N closest out of all routing tables.
c) use one routing table per socket address, only query the one corresponding to the socket on which the request was received.

c) is no worse than single-address operation, a) and b) can be considered an optimization in terms of result quality.

Does that answer it?

**Comment by aldenml** [comment]
I think that at least clarify me a lot of things, especially since I like the option b). But I don't quite understand the option c), what do you mean by "query". Thanks

**Comment by the8472** [comment]
query just means to ask/search for. in this context it means searching for the N closest routing table entries.

**Comment by aldenml** [comment]
Thanks again, I think i have enough info to continue

**Comment by aldenml** [comment]
Hi @arvidn @the8472 I appreciate if you give me some review here
```cpp
		string_view protocol_family = wanted.string_value();
		std::vector<node_entry> nodes;
		constexpr int max_nodes = 50;

		// find in all nodes of the same protocol family, taking at most N
		for (auto const& n : m_nodes)
		{
			if (n->protocol_family_name() != protocol_family)
				continue;

			n->m_table.find_node(info_hash, nodes, 0, max_nodes);
		}

		// sort all the nodes to take the first N
		std::sort(nodes.begin(), nodes.end()
			, [&info_hash](node_entry const& lhs, node_entry const& rhs)
				{ return compare_ref(lhs.id, rhs.id, info_hash); });
		if (nodes.size() > max_nodes) nodes.resize(max_nodes);

		// TODO: improve this comparision
		auto protocol_nodes_key = protocol_family == "n4" ? "nodes" : "nodes6";
		write_nodes_entry(r[protocol_nodes_key], nodes);
```

**Comment by arvidn** [comment]
``if (n->protocol_family_name() != protocol_family)`` that has to be a ``find()``, doesn't it? ``protocol_family`` can indicate both IPv6 and IPv4, so you need to look if ``n->protocol_family()`` is part of it.

**Comment by aldenml** [comment]
sorry, can you elaborate a little more your idea?

**Comment by arvidn** [comment]
If I understand correctly, you need to do this: ``if (protocol_family.find(n->protocol_family_name()) 
!= std::string::npos)``. Since ``wanted`` can include both IPv6 and IPv4, but the specific protocol family of a node will always be only be one of them

**Comment by arvidn** [comment]
I guess you have the check the other way, ``if (protocol_family.find(n->protocol_family_name()) == std::string::npos)``

**Comment by aldenml** [comment]
yes yes, you are right, that's the loop just surrounding this code (one iteration per family). I wanted to check if this way of selecting the first N nodes is a reasonable solution.

**Comment by the8472** [comment]
> constexpr int max_nodes = 50;

That may not fit into a single packet, especially on responses other than to find_node, i.e. when some payloads may be present.

You may have to shorten the list to fit everything into the MTU.

**Comment by aldenml** [comment]
true, actually I was clueless when I picked that number.

One thing that I see is that this solution does not scale very well for hundred of DHTs, to quote the BEP

> In large parts it is based on practical experience operating such a node with 256+ IPv4 and IPv6 addresses.

but I don't know if this is something that requires a more specialized library

**Comment by the8472** [comment]
I have outlined a N-closest node finding altorithm that does not require a linear scan of the routing table in [this SO answer](http://stackoverflow.com/a/30655403/1362755). At least in Big-O terms it should be faster, whether it actually is in practice might depend on cache effects.

**Comment by aldenml** [comment]
@the8472 I will need more time to fully grasp your algorithm, but for what I see, this is tailored to one DHT node's buckets. What happens if you have, let's say 500 DHTs, each one short enough to even do a linear scan without problems. How to handle a potential expensive and memory intensive  operation of doing 500x `n->m_table.find_node(info_hash, nodes, 0, max_nodes);`?

**Comment by the8472** [comment]
1. sort the routing tables by the distance of their ID relative to the target key
2. fill the result set from the closest table
3. pick one bucket at a time from the remaining routing tables and see if they actually improve the result set, that way you will most likely be able to abort my algorithm after the first bucket.

Let 𝑚 be the number of routing tables, 𝑛 the result set size and 𝐾 the bucket size, then you will need to scan approximately 𝑚 + 𝑛/𝐾 buckets. You can reduce the runtime further by simply bailing out at some point or using a shared routing table layout (e.g. by coalescing buckets with the same prefixes or using the natural distance order).

Anyway, this is all fairly theoretic. libtorrent is in C++ which allows you to have densely packeed data and vectorized loops anyway and you would probably only run with that many IPs on some beefy server. So avoid premature optimizations and see how many cycles such a scan would actually take.

**Comment by aldenml** [comment]
Thanks!  :)

**Comment by aldenml** [comment]
I think this morphed into a good discussion about how to support BEP 45, at this moment I can't give priority to this issue, and my main motivation was provide a good design for a "dht state" in `session_params`. Good news all the pieces are there, just in need of some plumbing.

**Comment by the8472** [comment]
Just make sure to never bind to the wildcard address if you're going to support ipv6. That's also part of bep32, not just 45

**Comment by aldenml** [comment]
@ssiloti do you agree that this can be closed now?

**Comment by ssiloti** [comment]
Yes
