### ISSUE TITLE
simple_client.cpp small error "failed to open listen socket"

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#1097]
https://github.com/arvidn/libtorrent/blob/master/examples/simple_client.cpp#L55
.....
       settings_pack sett;
	sett.set_str(settings_pack::listen_interfaces, "0.0.0.0:6881");
	lt::session s(sett);
	error_code ec;
	if (ec) **<--- if (ec) always false!**
	{
		std::fprintf(stderr, "failed to open listen socket: %s\n", ec.message().c_str());
		return 1;
       }
....

**Comment by arvidn** [comment]
thanks. This is a problem in the RC_1_1 branch as well. would you mind submitting a PR deleting that whole if-statement? (and maybe ``ec`` too, unless it's used somewhere else), against the RC_1_1 branch?

**Comment by arvidn** [comment]
fixed here: https://github.com/arvidn/libtorrent/pull/1110
