### ISSUE TITLE
ed25519 - strange loop i < 1

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#1098]
https://github.com/arvidn/libtorrent/blob/master/ed25519/src/fe.cpp#L381

    for (i = 1; i < 1; ++i) {
        fe_sq(t0, t0);
}
https://github.com/arvidn/libtorrent/blob/master/ed25519/src/fe.cpp#L395

    for (i = 1; i < 1; ++i) {
        fe_sq(t2, t2);
    }

**Comment by aldenml** [comment]
see here https://github.com/arvidn/libtorrent/issues/560

**Comment by arvidn** [comment]
This is one reason why I would be inclined to include this code via a submodule reference. It could still be packaged in the tarfile and built by the build files in libtorrent, but upgrading to new versions would be greatly simplified.

**Comment by pavel-pimenov** [comment]
Thanks.
