### ISSUE TITLE
IPv6 DHT support

### ISSUE THREAD

**Issue by ssiloti** [arvidn/libtorrent#110]
Since IPv6 is finally being deployed widely it seems like a good time to implement support for it in the DHT. I'm creating this issue to document my plans and open them up to feedback. My current plan is to handle dual-stack operation by creating two instances of dht::node in dht_tracker. Maintaining BEP 42 compliance means IPv4 and IPv6 nodes can't share the same ID so most members in dht::node cannot be shared. In theory they could share storage but with different IDs it wouldn't do much good. If an extension API is added for DHT storage we'll probably want to have it be shared anyways.

Having separate nodes means no major changes are required to traversal_algorithm and its descendants. There will be additional logic in dht_tracker to make dual-stack traversals transparent to clients. For get_peers and announce, dht_tracker will simply issue separate requests to each node with the same callback. Get/put requests will need a bit of shared state passed to the callback wrappers so that they can merge the results of each traversal to produce a single authoritative result.

In general node and traversal_algorithm instances will be restricted to operating on addresses of a single type, with the exception of bootstrap which will send queries to any address and set the `want` key as appropriate.

There will be a shared std::map of strings to routing_table* so that nodes can reach into each other's routing tables to satisfy cross-namespace queries using the `want` key.

**Comment by aldenml** [comment]
> Get/put requests will need a bit of shared state passed to the callback wrappers so that they can merge the results of each traversal to produce a single authoritative result.

How do you think this could be achieved?

**Comment by ssiloti** [comment]
The handlers in dht_tracker will hold a shared_ptr to a count of the number of traversals still outstanding for the particular request. In the case of mutable get requests the callback also holds a copy of the latest item which gets passed to the next level callback once there are no more outstanding traversals.

**Comment by ssiloti** [comment]
I've pushed a preview of my code for this to https://github.com/ssiloti/libtorrent/commits/dht-ipv6. It's feature complete but needs more testing.

**Comment by aldenml** [comment]
Hi @ssiloti, do you have plans to rebase or keep it as it is? Thanks

**Comment by ssiloti** [comment]
For now I'll just be committing fixes. The branch will likely need rebasing before it's merged though.

**Comment by aldenml** [comment]
Thanks, then I will to do it myself (it's better for review), and maybe it will be more clear to me the TORRENT_USE_IPV6 question.

**Comment by arvidn** [comment]
TORRENT_USE_IPV6 is used in libtorrent to simply disable any mention of IPv6 specific types and functions. The purpose is to be able to build on systems that do not support IPv6.

**Comment by aldenml** [comment]
100% clear on that, I made my comment out of context. It's related to a (minor) question I made in @ssiloti branch (https://github.com/ssiloti/libtorrent/commit/4bbdf9093823046f4d86f20742de7d686ca19892#diff-8775d2d9460d9b7a42d64f06511742d7R6607)

**Comment by txtsd** [comment]
@ssiloti Pardon the impatience, but how close is it to being done?

**Comment by ssiloti** [comment]
As you can see in #268, the code is feature complete but in need of further testing. One of these days I'm hoping to get an IPv6 test environment set up so that I can run multiple clients locally each with their own IPv6 address.

**Comment by txtsd** [comment]
What sort of testing? Very specific tests, or the use it in a client and report when something goes wrong kind?

**Comment by arvidn** [comment]
There's some IPv6 support in the simulator (multi-homed is still lacking some features). but test_transfer.cpp is now testing regular bittorrent over IPv6. It's on my TODO list to add a better (sim based) test framework for the DHT, which hopefully can be parameterized on address family.
