### ISSUE TITLE
What are required functions provided by OpenSSL/Crypto?

### ISSUE THREAD

**Issue by lyssdod** [arvidn/libtorrent#1109]
Hi,

I'm using libtorrent 1.0.9. I had to downgrade to that release because I have to ship binaries to client machines which doesn't have recent runtime (I have to be compatible with Ubuntu 14.10+). I'm also using CMake for building (thanks for providing CMakeLists!).

The problem is, I'm embedding libtorrent and don't have access to host's OpenSSL/Crypto. Thus I have only two options — bundling a separate OpenSSL package exclusively for libtorrent (would like to avoid that), or make a separate library with just a few functions which libtorrent need for encryption (preferred way).

CMake enables OpenSSL exclusively when `encryption` is set (default): https://github.com/arvidn/libtorrent/blob/master/CMakeLists.txt#L208

PS. When compiling for OSX (with Clang), I also got a bunch of warnings that RC4 in OpenSSL is deprecated — maybe this will help.

Thanks!

**Comment by aldenml** [comment]
I believe all this problems are somehow solved in `master` with the separation of `crypto` and `ssl` options. I doubt further work related to this will be made on `RC_1_0`, if you are supporting only x86/x64 architectures, my recommendation is: just grab the best assembly sha1 implementation and replace the embedded `sha1.cpp` and disable `ssl`, unless you are using torrents over ssl. Do you?

**Comment by lyssdod** [comment]
So `encryption` without `ssl` is only about hashing? I thought there were any other uses for it. I'm also not sure about torrents over ssl, I'm trying to make a best default build (are these torrents over ssl actually used by anyone?). Also, does `RC_1_0` require C++-11 capable compiler?

**Comment by aldenml** [comment]
The problem is that in `RC_1_0`, the cmake `encryption` option means libcrypto hashing + torrents over ssl. No, it does not requires C++11?

**Comment by lyssdod** [comment]
@aldenml I see. I will try to make a PR for this to separate encryption from hashing. Also, do torrents over ssl mean this https://en.wikipedia.org/wiki/BitTorrent_protocol_encryption? I'm just trying to do my best to find out the real need of this feature in my application (DHT-enabled torrent client)

**Comment by aldenml** [comment]
The bittorrent over ssl is much better, and at the same time very different from BT protocol encryption. See http://blog.libtorrent.org/2012/01/bittorrent-over-ssl (@arvidn the domain seems to be down). I would like to hear of someone using the feature.

**Comment by lyssdod** [comment]
Thank you! I will try to disable this functionality for now, with plans to enable it in the future

**Comment by aldenml** [comment]
Now I remember, that I think the SSL support is necessary if you want to allow https requests.
