### ISSUE TITLE
error in src/session.cpp:660:49: error: 'get_dht_settings' 

### ISSUE THREAD

**Issue by TeLLie** [arvidn/libtorrent#111]
Hello

I tried to compile it to OS2 using gcc 492 but make gives error with:
src/session.cpp:660:49: error: 'get_dht_settings' is not a member of 'libtorrent::session'
         .def("get_dht_settings", allow_threads(&session::get_dht_settings))
                                                 ^
I run configure like:
--with-boost-libdir=c:/extras/lib --with-boost=c:/extras --with-boost-system=boost_system-gcc-mt --disable-shared --enable-static --prefix=/extras --enable-python-binding

Any fix for the error...

**Comment by arvidn** [comment]
are you building master?

**Comment by TeLLie** [comment]
Hello,
Jjust downloaded from:
https://github.com/arvidn/libtorrent/releases/download/libtorrent-1_0_6/libtorrent-rasterbar-1.0.6.tar.gz

**Comment by arvidn** [comment]
is that the only error you get? that function is definitely there, but if you encounter another error parsing the header file it could explain this failure too.

**Comment by TeLLie** [comment]
Hi 
afaik the only error, but at the end i see also this error:

error: command 'i386-pc-os2-emx-gcc' failed with exit status 1
make[2]: *** [all-local] Error 1
make[2]: Leaving directory `G:/libtorrent-rasterbar-1.0.6/bindings/python'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `G:/libtorrent-rasterbar-1.0.6/bindings'
make: *** [all-recursive] Error 1

**Comment by arvidn** [comment]
It's not at all clear why gcc would think this member doesn't exist. It could be some subtle bug in the gcc front-end. what version of GCC are you using?

**Comment by arvidn** [comment]
4.9.2?

**Comment by arvidn** [comment]
travis-ci is building the python bindings with gcc 4.8 under boost-build, and that works.

**Comment by TeLLie** [comment]
Hihi

Yes Gcc 4.9.2 and boost v1.57

On 29-08-15 22:45, Arvid Norberg wrote:
> 4.9.2?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arvidn/libtorrent/issues/111#issuecomment-136048473>.
>

-- 
With kind regards from the Netherlands,
                     Elbert & Nicole Pol

**Comment by arvidn** [comment]
I don't know what else to do here. Clearly this builds under some common configurations on windows, linux and osx. Are you passing in any special build configuration options? Is is possible that the os/2 version of gcc is neglected and has some error causing this?

**Comment by TeLLie** [comment]
Hihi

On  7-09-15 17:00, Arvid Norberg wrote:
> I don't know what else to do here. Clearly this builds under some common
> configurations on windows, linux and osx. Are you passing in any special
> build configuration options? Is is possible that the os/2 version of gcc
> is neglected and has some error causing this?


See config.log @ pastebin.com/RqwcN3m3

>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arvidn/libtorrent/issues/111#issuecomment-138319194>.
>

-- 
With kind regards from the Netherlands,
                     Elbert & Nicole Pol

**Comment by arvidn** [comment]
I don't believe there's anything wrong with the code, and I can't come up with a work-around without having that compiler. If you can come up with one, please submit a pull request.
