### ISSUE TITLE
Duplicate m_state == torrent_status::downloading

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#1113]
https://github.com/arvidn/libtorrent/blob/master/src/torrent.cpp#L7420
https://github.com/arvidn/libtorrent/blob/master/src/torrent.cpp#L7417

**Comment by arvidn** [comment]
interesting. I wonder why no compiler is warning about this...

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/1116
