### ISSUE TITLE
Problem with recognition of already downloaded and resume data

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#1136]
libtorrent version: master

platform/architecture: macOS

compiler and compiler version: clang

I created the same code in the client to be able to switch between 1.1 and 1.2, but using 1.2 downloads again all the data, ignoring resume and data in disk. Launching the program with 1.1 recognize the data in disk and go immediately to seed.

Any clues or hints of where I can look? Thanks

**Comment by arvidn** [comment]
do you get any errors from ``read_resume_data()``?

**Comment by arvidn** [comment]
I suppose there must be two problems here. the resume data fails or is ignored, and also the files are not rechecked. perhaps the resume data is loaded and fails in a way saying there aren't any files

**Comment by aldenml** [comment]
no, it reads fine (no errors), but even ignoring the resume data, I don't understand why it fails to just hash-check the data in disk

**Comment by aldenml** [comment]
hmm...your last comment makes sense

**Comment by arvidn** [comment]
if you have a chance, you can see if ``has_any_file()`` is called on the storage

**Comment by aldenml** [comment]
you were right in your starting point, the problem seems to be rooted in this commit: https://github.com/arvidn/libtorrent/commit/06b648203fd4d525eeda3a5f0cfa4b8083caa7ff and then using ifs like this `if (err && err != boost::system::errc::no_such_file_or_directory)` in this other commit https://github.com/arvidn/libtorrent/commit/660647b5906e8246e3e1b98e35f530b4782f0ffb

Just changing back to `generic_category()` in `stat_file` fix the check problem. The `!=` operator change the enum code to `error_code` using the internal boost:
```cpp
//  explicit conversion:
      inline error_code make_error_code( errc_t e ) BOOST_SYSTEM_NOEXCEPT
        { return error_code( e, generic_category() ); }
```
using `generic_category()`.

Now I need to figure out a good PR :)

**Comment by aldenml** [comment]
Well, at this moment I don't understand what's happening, this simple test pass fine:
```cpp
TORRENT_TEST(stat_file)
{
	file_status st;
	error_code ec;
	stat_file("no_such_file_or_directory.file", &st, ec);
	TEST_CHECK(ec);
	TEST_EQUAL(ec, boost::system::errc::no_such_file_or_directory);
}
```

**Comment by arvidn** [comment]
I've seen strange issues with ``error_code`` before. They always ended up being link compatibility issues. I can't recall the detail, but I think the layout may have changed in different versions of boost perhaps, or perhaps some side is using ``std::error_code`` and the other ``boost::system::error_code``.

**Comment by arvidn** [comment]
the underlying category is compared by pointer iirc, perhaps there's an ODR violation where different parts of the program sees different pointers for the category. I seem to recall the problems I've seen was something along these lines

**Comment by aldenml** [comment]
I'm lost in the sea of code here :)

posting some log in case it helps
```
: creating torrent: Honey_Larochelle_Hijack_FrostClick_FrostWire_MP3_May_06_2016 max-uploads: 16777215 max-connections: 16777215 upload-limit: -1 download-limit: -1 flags: apply-ip-filter update-subscribe sequential-download override-trackerssave-path: /Users/aldenml/FrostWire/Torrent Data
: *** set-max-uploads: 16777215
: *** set-max-connections: 16777215
: add_peer() 107.130.90.222 connect-candidates: 1
: add_peer() 66.87.80.180 connect-candidates: 2
.....more add_peers calls.....
: *** UPDATE LIST [ torrent_want_tick : 1 ]
: init torrent: Honey_Larochelle_Hijack_FrostClick_FrostWire_MP3_May_06_2016
: init, async_check_files
.....more add_peers calls.....
: resume added peers (100)
: fastresume data accepted
: set_state() 3
: *** UPDATE LIST [ torrent_want_peers_download : 1 ]
: *** tracker: "http://tracker.frostwire.com:6969/announce" [ tiers: 0 trackers: 0 i->tier: 0 tier: 2147483647 working: 1 fails: 0 limit: 0 upd: 0 can: 1 sent: 0 ]
: ==> TRACKER REQUEST "http://tracker.frostwire.com:6969/announce" event: started abort: 0
: ==> TRACKER_REQUEST [ url: http://tracker.frostwire.com:6969/announce?info_hash=%83%e3z%ea4X%1c%e1%05%af%93%c0%95%5e%7c%7dA%94%aeG&peer_id=-LT1200-RZ3R3Fz8r-Xo&port=60148&uploaded=0&downloaded=0&left=43786315&corrupt=0&key=CA099249&event=started&numwant=200&compact=1&no_peer_id=1&supportcrypto=1&redundant=0 ]
: *** tracker: "http://tracker.frostwire.com:6969/announce" [ tiers: 0 trackers: 0 found: 0 i->tier: 0 tier: 2147483647 working: 1 fails: 0 limit: 0 upd: 1 ]
: *** update tracker timer: next_announce < now 0 m_waiting_tracker: 0 next_announce_in: -632640442
```

**Comment by aldenml** [comment]
I removed the resume data from the equation. libtorrent seems to ignore any data in disk

**Comment by aldenml** [comment]
sorry for the panic, it seems to be a problem on my side with my new "posix layer" wrap with clang.
