### ISSUE TITLE
session won't work when takes an external io_service.

### ISSUE THREAD

**Issue by thomas-yuan** [arvidn/libtorrent#114]
Testing DHT with tools/dht_put.cpp, apparently it's broken. Try to figure out the root cause, so I minimize thread by pass in a io_service object. Then it's blocked forever. 

Code looks like this:
```c++
using namespace libtorrent;

boost::asio::io_service ios;
settings_pack sp;
sp.set_int(settings_pack::aio_threads, 0);
session s(sp, ios);

dht_settings ds = s.get_dht_settings();
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ BLOCKS HERE!
ds.ignore_dark_internet = false;
s.add_dht_router(std::pair<std::string, int>("xxx.xxxxxx.xxx", 6881));
s.set_dht_settings(ds);
...
ios.run();
```

Apparently, get_dht_settings call io_service.post() and then waiting on another thread to finish the task and wake it up. But if there is only one thread, it will be blocked there forever.

**Comment by arvidn** [comment]
ah, that should probably be a dispatch() instead of post(). would you mind trying that out and maybe submit a pull request?

**Comment by arvidn** [comment]
I'm not sure dispatch() will work either though, since the io_service isn't running at the time. it might though.

**Comment by thomas-yuan** [comment]
I thought it's caused by multi-thread, but I was wrong. As @arvidn said, it's caused by io_service isn't running. Code should looks like this:

```c++
using namespace libtorrent;

boost::asio::io_service ios;
settings_pack sp;
sp.set_int(settings_pack::aio_threads, 0);
session s(sp, ios);

boost::asio::deadline_timer t(ios, boost::posix_time::seconds(1));
t.async_wait([&s](const boost::system::error_code&) {
    dht_settings ds = s.get_dht_settings();
    ds.ignore_dark_internet = false;
    s.add_dht_router(std::pair<std::string, int>("xxx.xxxxxx.xxx", 6881));
    s.set_dht_settings(ds);
});

ios.run();
....
```

And actually the original code using dispatch, not post. And I also tested that, even it's post, it still works.

If settings_pack can set dht_settings, then it will be more convenient.
