### ISSUE TITLE
Interest in .NET bindings

### ISSUE THREAD

**Issue by vktr** [arvidn/libtorrent#116]
I'm opening this to see if there is any interest in a future pull request to add the .NET bindings alongside the Python and C bindings. The bindings are written in C++/CLI and are more done than not. There are some things missing but the general concept is there, and they are quite usable already.

You can review the code here, https://github.com/vktr/libtorrent-net. It builds against MSVC 14.0 and libtorrent 1.0.6 and is usable from any .NET language on Windows (i.e Mono and CoreCLR is not supported).

For example, here is the `create_torrent` example in C#,

``` csharp
using(var fs = new file_storage())
{
    create_torrent.add_files(fs, "./my-torrent");

    using(var t = new create_torrent(fs))
    {
        t.add_tracker("http://my.tracker.com/announce");
        t.set_creator("libtorrent example");

        create_torrent.set_piece_hashes(t, ".");

        using(var entry = t.generate())
        {
            File.WriteAllBytes("my_torrent.torrent", util.bencode(entry));
        }
    }
}
```

You can also use the `set_alert_dispatch` with a .NET lambda,

``` csharp
var session = new lt.session();
session.set_alert_dispatch(alert =>
{
    using(alert)
    {
        Console.WriteLine(alert.message());

        if(alert.GetType() == typeof(add_torrent_alert))
        {
            // react to the add_torrent_alert.
        }
    }
});
```

Some notes,
- I've tried to stay as close to the libtorrent API as possible so one can utilize the already existing libtorrent documentation. I'm also planning to add XML documentation comments (as is standard in .NET), which makes Visual Studio show inline documentation in the intellisense.
- Since C# does not support non-member functions, free functions are put in classes (for example `add_files,`set_piece_hashes`and`bencode`).
- To properly dispose and delete pointers it is recommended to wrap the managed-to-unmanaged classes in `using` statements.

My C++ is not super-strong so any opinions or critique is highly appreciated!

**Comment by aldenml** [comment]
Any reason you decided to build against 1.0.6 and not master? Check the changelog (https://github.com/arvidn/libtorrent/blob/master/ChangeLog) which I think does not contains everything.

**Comment by vktr** [comment]
I picked 1.0.6 to have a stable target, but if you think master is stable enough I can rewrite it.

**Comment by romanvm** [comment]
Sounds interesting.

**Comment by vktr** [comment]
A small update - I've wrapped the `master` branch here, https://github.com/vktr/libtorrent-net-master.

It is not as complete as the 1.0.6 wrapper (no alerts yet), but the idea is there.

**Comment by arvidn** [comment]
neat
