### ISSUE TITLE
Question about possible cleanup in DHT code

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#1165]
libtorrent version (or branch): master

Hi @ssiloti, I see you added an `if` here: https://github.com/aldenml/libtorrent/commit/2abd9867cea6ca2fd6cca7877147751814087b1d#diff-28802f8586db5ee75823f41d2de10726R290, but I can't understand why.

If by any chance, it's not necessary, what do you think about removing all the associated code?

Thanks

**Comment by ssiloti** [comment]
Incoming DHT messages are broadcast to all nodes to support cross-protocol bootstrapping. That if condition is to prevent lots of spurious "unknown transaction id" messages from being logged due to one node seeing responses to the other node's queries.

**Comment by aldenml** [comment]
Thanks!
