### ISSUE TITLE
Libtorrent crashes at listen_on if there are more than 6 network adapters enabled

### ISSUE THREAD

**Issue by overfl0** [arvidn/libtorrent#1167]
*Note: this may be the same issue as #843*

Reproducible: on windows, always
Tested on Windows 7, 8.1; with python-libtorrent 1.0.9 (the last release with an available .msi file)

Libtorrent crashes if there are more than 6 network adapters enabled. An easy way to create those is to install VirtualBox and then do File->preferences->Network->Host-only Networks->Click "add" a few times.

Here is the output of a user running simple_client.py while troubleshooting the problem:
```
c:\Users\cybrnyte\Desktop>python -m pdb simple_client.py nas.torrent
c:\users\cybrnyte\desktop\simple_client.py(5)<module>() -> from future import print_function (Pdb) n
c:\users\cybrnyte\desktop\simple_client.py(7)<module>() -> import libtorrent as lt (Pdb) n
c:\users\cybrnyte\desktop\simple_client.py(8)<module>() -> import time (Pdb) n
c:\users\cybrnyte\desktop\simple_client.py(9)<module>() -> import sys (Pdb) n
c:\users\cybrnyte\desktop\simple_client.py(14)<module>() -> ses = lt.session() (Pdb) n
c:\users\cybrnyte\desktop\simple_client.py(15)<module>() -> ses.listen_on(6881, 6891) (Pdb)
This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information.
```

It looks like it doesn't matter what type of network adapter there is as long as there are more than 6 of these and they are enabled (maybe need IP assigned but VBox already does that by default).

*Also please add .msi files to the latest releases :).*

**Comment by arvidn** [comment]
thanks for the report! do you know if there's an easy way to add adapters to a physical windows machine?

**Comment by overfl0** [comment]
You can do so very easily with VirtualBox.
Doing the thing I wrote above will add virtual adapters to your **physical** windows machine.

After they are created they can be bound to VMs, but it's optional (and not needed at all, in this case). The adapters will be created on the physical machine and will receive an IP address (probably from the ranges 192.168.5x.*). You don't need to run any VMs nor do anything else for this to work.

Just create those adapters and then run libtorrent in your physical machine.

Also, just to make it clear: the python-libtorrent 1.0.9 library was the one from the release page. It was *not* self-compiled (#843 states compilation flags or defines may affect the bug).

**Comment by arvidn** [comment]
fixed here: https://github.com/arvidn/libtorrent/commit/bc83f0e3a8ffa7aa9277a03616a8ea45fa730795
