### ISSUE TITLE
Poor upload utilization with default choking algorithm

### ISSUE THREAD

**Issue by ssiloti** [arvidn/libtorrent#1171]
libtorrent version (or branch): RC_1_1, master

For a long time I've noticed that libtorrent often doesn't make full use of my available upload throughput. I've been ignoring it because the rate is usually within 80% and it's hard to tell if it's libtorrent's fault or just my ISP being crappy.

Today I had a particularly bad session where the upload rate was persistently around 60% of the limit[0] and I finally decided to look into it. After capturing some logs I've concluded that the problem is with the default round robin seed choking algorithm. Because the quota is set in terms of bytes uploaded, faster peers hit it sooner than slower ones. This tends to result in most upload slots being taken by slow peers who take a long time to hit the quota. At any given time there are typically only one or two fast peers unchoked.

To test this theory I changed the seed choking algorithm to fastest upload and saw an obvious improvement. Many fast peers were unchoked keeping the connection consistently saturated as you would expect. I noticed qBittorrent has hard coded the use of fastest upload since December 2014[1].

I thought I should allow for some discussion before going off and working on a fix. One possible way to improve the behavior of round robin would be to set the quota in time rather than bytes uploaded to remove the bias towards slow peers.

[0] Note that I do not set any rate limits in libtorrent, I enforce the limit at my router.
[1] https://github.com/qbittorrent/qBittorrent/commit/b46a0ea9b22e5707462f1006b84599e26da00e31

**Comment by arvidn** [comment]
yeah, round-robin over time instead of bytes seems like a good idea. I have a feeling that the byte counter was the easiest way of implementing the comparison function.

**Comment by ssiloti** [comment]
Thinking about this some more. A downside with using time based quota is that we would no longer be making any attempt to ensure we upload complete pieces before choking. A peer with a slow connection on a torrent with large pieces may never upload a full piece within the quota time.

I think a better solution would be to say that when an unchoked peer hits the quota limit, any peers which have been unchoked for longer than say 2x the time that the quota hitting peer has been get choked. That way at least the peers with above average download speed have a good chance to receive at least one complete piece.

**Comment by arvidn** [comment]
yeah, if we keep track of how much "over-time" a peer gets, we could just make it take longer to come back to that peer to compensate.

**Comment by ssiloti** [comment]
It turns out the problem here is not what I originally thought it was. The main problem with the round-robin choker is that it sorts both choked and unchoked peers by time of last unchoke. This renders optimistic unchoking ineffective since the optimistically unchoked peer will almost always be the most recently unchoked and thus get choked again after just one round. Unchoked peers which have not completed their quanta need to be sorted by upload rate so that optimistic unchoking works as intended.

I also think the minimum quanta should be set to 1 minute rather than 256KB since the latter may still be absurdly small for fast seeders.
