### ISSUE TITLE
Feature request: per torrent DHT settings

### ISSUE THREAD

**Issue by dkasak** [arvidn/libtorrent#1174]
A feature that allows you to set whether DHT is used or not for a particular torrent would be nice. A rationale for this feature can be found [in this Deluge issue](http://dev.deluge-torrent.org/ticket/185) where a developer commented the feature has to be supported in libtorrent first.

**Comment by arvidn** [comment]
I don't really see a rationale in that ticket. just a feature request.

The ticket mentions the private flag. Torrents with the private flag set won't be using the DHT as it is already. What's the use case to disable the DHT for non-private torrents?

**Comment by dkasak** [comment]
Ah, I wasn't aware that torrents with the private flag won't use DHT. The rationale was then that you should be able to disable DHT for torrents on ratio counting trackers, but those probably already set the private flag so the issue is solved.

Thanks and sorry for the noise!
