### ISSUE TITLE
 Possible duplicates: std::vector<announce_entry> m_trackers

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#1182]
libtorrent version (or branch): master
Example tracker:
http://kino-tor.org/torrent/403102/lake-of-tears-by-the-black-sea-2014-mp3
Copy and open magnet:
magnet:?xt=urn:btih:0099d4cbf3b027f8f6e0d9bac7c57a16a56f7458&dn=rutor.info_Lake+Of+Tears+-+By+The+Black+Sea+%282014%29+MP3&tr=udp://opentor.org:2710&tr=udp://opentor.org:2710&tr=http://retracker.local/announce

![libtorrent-trackers-dup](https://cloud.githubusercontent.com/assets/920705/19083814/84ce85b6-8a6c-11e6-8369-9c9a8ac221ac.png)

**Comment by sledgehammer999** [comment]
You do realize that the magnet URI you're using contains the duplicate trackers, right?
It is as if you loaded a .torrent file that had duplicate trackers inside it.

**Comment by pavel-pimenov** [comment]
Parser auto-remove duplicates + warning/assert ?

**Comment by arvidn** [comment]
yeah, there's no point in allowing duplicates internally. It should probably be fixed in torrent creation, to filter out duplicates.

**Comment by arvidn** [comment]
I'm not sure why you closed this. you don't think this is an error?
Perhaps I was a bit ambiguous in my post. by "torrent creation", I meant the constructor of ``libtorrent::torrent``

**Comment by arvidn** [comment]
sorry about that. I will take a look at this in a while, maybe a week or two. I'm in the middle of a bunch of other things right now. (if you're up for it, feel free to submit a PR :) )
