### ISSUE TITLE
End-user mini-dump: verify_message_impl

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#1187]
libtorrent version (or branch): master
platform/architecture: x64 + Windows 7 SP1 
VC++ 2015u3
https://drdump.com/Problem.aspx?ProblemID=239163

flylinkdc_x64!libtorrent::dht::verify_message_impl+0x280
flylinkdc_x64!libtorrent::dht::node::incoming_request+0x34f
flylinkdc_x64!libtorrent::dht::node::incoming+0x551
flylinkdc_x64!libtorrent::dht::dht_tracker::incoming_packet+0x377
flylinkdc_x64!libtorrent::aux::session_impl::on_udp_packet+0x4a9
flylinkdc_x64!boost::asio::detail::win_iocp_null_buffers_op<std::_Binder<std::_Unforced,void (__cdecl libtorrent::aux::session_impl::*)(std::weak_ptr<libtorrent::udp_socket> const & __ptr64,bool,boost::system::error_code const & __ptr64) __ptr64,libtorrent::aux::session_impl \* __ptr64 const,std::weak_ptrlibtorrent::udp_socket const & __ptr64,bool const & __ptr64,std::_Ph<1> const & __ptr64> >::do_complete+0x157
flylinkdc_x64!boost::asio::detail::win_iocp_io_service::do_one+0x25d
flylinkdc_x64!boost::asio::detail::win_iocp_io_service::run+0xba
flylinkdc_x64!std::_LaunchPadstd::unique_ptr<std::tuple<<lambda_b36f97b57e062a41dc0986f1cc6f4630 >,std::default_deletestd::tuple<<lambda_b36f97b57e062a41dc0986f1cc6f4630 > > > >::_Run+0x91
flylinkdc_x64!std::_Pad::_Call_func+0x18
flylinkdc_x64!wcsftime+0x79
kernel32!BaseThreadInitThunk+0xd
ntdll!RtlUserThreadStart+0x1d

Crash point: 
![libtorrent-crash](https://cloud.githubusercontent.com/assets/920705/19141818/512a51f0-8ba1-11e6-8d59-17b2adf5dfaa.png)

desc.size() != ret.size() ?

**Comment by arvidn** [comment]
would it be possible for you to extract the actual message causing this error?

**Comment by pavel-pimenov** [comment]
No, user posted mini-dump (only stack)

**Comment by arvidn** [comment]
minidumps normally contain context. like, all stacks, thread information blocks and heap blocks. The message should be pretty close to the context in this case.

**Comment by pavel-pimenov** [comment]
pdb+src+dmp:
https://yadi.sk/d/AANnfTu2wPk4g
open compiled/flylinkdc-x64_7.7.503.19978_20161004_163502.mini.dmp
