### ISSUE TITLE
Alternative to the fingerprint class?

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#1190]
We are trying to fully transition to 1.1.x by not using deprecated stuff.
Today, I discovered that the fingerprint class is deprecated.
The docs about `settings_pack::peer_fingerprint` don't mention an alternative.

We have documented for trackers how to decode id to get version numbers of qBittorrent, based on the way libtorrent encoded it up until now. But now, you have dropped every versioning scheme for arbitrary strings.

I agree that that gives much more freedom, but there should be a utility function too. And maybe, mention in the docs what is the de facto way of communicating version numbers.

Finally I think there is an error in the docs for `peer_fingerprint`:

> this is the fingerprint for the client. It will be used as the prefix to the peer_id. If this is 20 bytes (or longer) it will be used as the peer-id

But according to [this](https://wiki.theory.org/BitTorrentSpecification#peer_id) the peer_id is 20 bytes long. Not longer.

**Comment by aldenml** [comment]
Just to document, that if `peer_fingerprint` is longer than 20 bytes, it considers the first 20 and ignore the rest, if it's less, it pads with random.

**Comment by arvidn** [comment]
yeah, it should say it uses it as a prefix but no more than 20 bytes

**Comment by arvidn** [comment]
@sledgehammer999 does this make sense? https://github.com/arvidn/libtorrent/pull/1249

**Comment by sledgehammer999** [comment]
Closing since #1249 got merged.
