### ISSUE TITLE
Magnet metadata download stuck

### ISSUE THREAD

**Issue by lyssdod** [arvidn/libtorrent#1202]
Hi, I'm using libtorrent 1.0.9 and custom bindings (reproducible with python). Sometimes I can not download magnets because they're stuck without metadata (while there're >200 DHT nodes available). I'm able to reproduce the issue with this magnet:

```
magnet:?xt=urn:btih:565DB305A27FFB321FCC7B064AFD7BD73AEDDA2B&dn=bbb_sunflower_1080p_60fps_normal.mp4&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a80%2fannounce&tr=udp%3a%2f%2ftracker.publicbt.com%3a80%2fannounce&ws=http%3a%2f%2fdistribution.bbb3d.renderfarming.net%2fvideo%2fmp4%2fbbb_sunflower_1080p_60fps_normal.mp4
```

Meanwhile in other torrent clients (qBittorrent, Vuze) it gets the metadata very quickly. 

What I'm doing wrong? The code:

```python
import libtorrent as lt
import time

session = lt.session()
session.listen_on(6881, 6891)
session.add_extension('ut_metadata')
session.add_extension('ut_pex')
session.add_extension('metadata_transfer')
session.add_dht_router("router.utorrent.com", 6881)
session.add_dht_router("router.bittorrent.com", 6881)
session.add_dht_router("dht.transmissionbt.com", 6881)
session.add_dht_router("dht.aelitis.com", 6881)
session.start_dht()
session.start_lsd()
session.start_upnp()
session.start_natpmp()

params = { 'save_path': '/tmp/'}
link ="magnet:?xt=urn:btih:565DB305A27FFB321FCC7B064AFD7BD73AEDDA2B&dn=bbb_sunflower_1080p_60fps_normal.mp4&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a80%2fannounce&tr=udp%3a%2f%2ftracker.publicbt.com%3a80%2fannounce&ws=http%3a%2f%2fdistribution.bbb3d.renderfarming.net%2fvideo%2fmp4%2fbbb_sunflower_1080p_60fps_normal.mp4"
handle = lt.add_magnet_uri(session, link, params)

print('downloading metadata...')
while (not handle.has_metadata()):
    status=session.status()
    print('dht nodes: ', status.dht_nodes)
    time.sleep(1)
print ('got metadata, starting torrent download...')
while (handle.status().state != lt.torrent_status.seeding):
    print('%d %% done' % (handle.status().progress*100))
    time.sleep(1)
```

**Comment by lyssdod** [comment]
For this release I'm using amd64 Linux (Gentoo) and gcc 4.9.3

**Comment by arvidn** [comment]
I imagine you experience the same problem with ``client_test``, do you?

**Comment by lyssdod** [comment]
Haven't tried it yet, will compile now

**Comment by lyssdod** [comment]
I'm getting this
![screenshot-lyssdod lynn -storage-work-node-libtorrent-build-examples](https://cloud.githubusercontent.com/assets/2615950/19255039/9840b222-8f62-11e6-9968-e283b188ef98.png)

**Comment by lyssdod** [comment]
After hitting `g`:
![screenshot-lyssdod lynn -storage-work-node-libtorrent-build-examples-1](https://cloud.githubusercontent.com/assets/2615950/19255075/e663ba4e-8f62-11e6-82d9-18494378aad4.png)

**Comment by lyssdod** [comment]
I'm getting this (DHT, UTP and alerts view toggled):
![2](https://cloud.githubusercontent.com/assets/2615950/19255121/31537562-8f63-11e6-881b-e23e346deb7b.png)

**Comment by arvidn** [comment]
My suspicion is that the torrent tries to announce to the DHT before it has heard back from the bootstrap node, or loaded the routing table or started the node itself. If you wait 15 minutes, does it announce again and succeed?

**Comment by arvidn** [comment]
specifically, updating the IP and restarting the DHT node with a new node ID seems to cause cancelling of all outstanding announces, hence aborts the torrent's announce more or less immediately

**Comment by arvidn** [comment]
could you give this a shot? https://github.com/arvidn/libtorrent/pull/1205

**Comment by lyssdod** [comment]
Tried it on public wifi with no success (maybe they have some ports blocked), will try again from home

**Comment by lyssdod** [comment]
Tried on another public wifi, it gets the metadata successfully, but the speed is very low. qBitTorrent quickly speeds up to 1.5MB/s

![screenshot-lyssdod lynn -storage-work-libtorrent-build-examples](https://cloud.githubusercontent.com/assets/2615950/19356506/bbd2de34-9176-11e6-8a86-762696110be0.png)

**Comment by arvidn** [comment]
merged https://github.com/arvidn/libtorrent/pull/1205

**Comment by modz2014** [comment]
i get the same issues as well

**Comment by SoloLeveling7seven** [comment]
Did anyone find any solutions?
