### ISSUE TITLE
.gitignore:  examples  tools/fuzz_torrent

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#1204]
Ubuntu 16.04.1 x64

./configure --enable-debug --enable-tests --enable-examples
.....
~/src/libtorrent$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

```
    examples/bt_get
    examples/bt_get2
    examples/client_test
    examples/connection_tester
    examples/dump_torrent
    examples/make_torrent
    examples/simple_client
    examples/stats_counters
    examples/upnp_test
    tools/fuzz_torrent
```

nothing added to commit but untracked files present (use "git add" to track)

**Comment by arvidn** [comment]
I don't understand what you're trying to say. If you think there should be something added to the .gitignore file, you could submit a pull request
