### ISSUE TITLE
[Crash] node::incoming_request

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#1213]
libtorrent version (or branch): master
https://drdump.com/Problem.aspx?ProblemID=240398&Login=Guest

	string_view query = top_level[0].string_value();

	if (m_observer && m_observer->on_dht_request(query, m, e))
		return;

	if (query == "ping")
	{
		m_counters.inc_stats_counter(counters::dht_ping_in);
		// we already have 't' and 'id' in the response
		// no more left to add
	}
	else if (query == "get_peers") // **crash point** https://drdump.com/Problem.aspx?ProblemID=240398&Login=Guest
	{
		key_desc_t const msg_desc[] = {
			{"info_hash", bdecode_node::string_t, 20, 0},
			{"noseed", bdecode_node::int_t, 0, key_desc_t::optional},

**Comment by aldenml** [comment]
This is very strange, any memory problems in this line should be manifested above in `if (query == "ping")` and I'm testing master for a few days now with no crash here.

**Comment by pavel-pimenov** [comment]
ok. close issue
string_view bdecode_node::string_value() const
...
return string_view(m_buffer + t.offset + t.start_offset(), size);

char const* m_buffer;

**Comment by arvidn** [comment]
I don't understand. how is the code you posted relevant? Did you resolve the issue? Does libtorrent need to be patched?
