### ISSUE TITLE
call to 'abs' is ambiguous (FreeBSD 11)

### ISSUE THREAD

**Issue by nrosier** [arvidn/libtorrent#1224]
libtorrent version (or branch): 1.1.1

platform/architecture: FreeBSD 11.0-RELEASE-p1 amd64

compiler and compiler version: 

FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0)
Target: x86_64-unknown-freebsd11.0
Thread model: posix
InstalledDir: /usr/bin

Configured with following options:

$ ./configure --disable-static  --enable-dht  --enable-encryption  --enable-pool-allocators  --enable-deprecated-functions  --with-boost=/usr/local  --with-boost-system=boost_system  --with-libiconv  --with-openssl=/usr/local --disable-debug --disable-tests --disable-python-binding --prefix=/usr/local

Applied FreeBSD-patch for iconv:
[freebsd-iconv-patch.txt](https://github.com/arvidn/libtorrent/files/535863/freebsd-iconv-patch.txt)

Compilation gives following error:

Making all in src
  CXX      mpi.lo
mpi.cpp:6711:21: error: call to 'abs' is ambiguous
    d = ((mp_digit) abs (MP_GEN_RANDOM())) & MP_MASK;
                    ^~~
/usr/include/stdlib.h:83:6: note: candidate function
int      abs(int) __pure2;
         ^
/usr/include/c++/v1/stdlib.h:115:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
                                           ^
/usr/include/c++/v1/stdlib.h:117:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {return llabs(__x);}
                                           ^
mpi.cpp:6723:41: error: call to 'abs' is ambiguous
    if ((res = mp_add_d (a, ((mp_digit) abs (MP_GEN_RANDOM())), a)) != MP_OKAY) {
                                        ^~~
/usr/include/stdlib.h:83:6: note: candidate function
int      abs(int) __pure2;
         ^
/usr/include/c++/v1/stdlib.h:115:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
                                           ^
/usr/include/c++/v1/stdlib.h:117:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {return llabs(__x);}
                                           ^
2 errors generated.

**Comment by arvidn** [comment]
thanks for the report! does this fix it? https://github.com/arvidn/libtorrent/pull/1228

**Comment by nrosier** [comment]
net-p2p/libtorrent-rasterbar port just got updated to version 1.1.1. It contains a patch which fixes this issue

[patch_include_libtorrent_tommath.h.txt](https://github.com/arvidn/libtorrent/files/539249/patch_include_libtorrent_tommath.h.txt)

Credit to maintainer of this port.

**Comment by arvidn** [comment]
aha! this was my second guess :) the PR against 1.1 performs this cast. once it's green I'll land it

**Comment by arvidn** [comment]
this has been merged now
