### ISSUE TITLE
Version 1.1.1 breaks compatibility

### ISSUE THREAD

**Issue by athei** [arvidn/libtorrent#1258]
libtorrent version: 1.1.1
platform/architecture: freebsd
compiler and compiler version: clang-3.8.0

Since I upgraded libtorrent-rasterbar and py27-libtorrent-rasterbar from 1.1.0 to 1.1.1. I get the following error when starting deluged. I recompiled  py27-libtorrent-rasterbar and deluged. This patch version should not break ABI compatibility.

`[ERROR   ] 21:24:05 main:245 /usr/local/lib/python2.7/site-packages/libtorrent.so: Undefined symbol "_ZNK10libtorrent14announce_entry12can_announceEN5boost6chrono10time_pointINS2_12steady_clockENS2_8durationIlNS1_5ratioILl1ELl1000000000EEEEEEEb"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/deluge/main.py", line 238, in start_daemon
    Daemon(options, args)
  File "/usr/local/lib/python2.7/site-packages/deluge/core/daemon.py", line 141, in __init__
    from deluge.core.core import Core
  File "/usr/local/lib/python2.7/site-packages/deluge/core/core.py", line 36, in <module>
    from deluge._libtorrent import lt
  File "/usr/local/lib/python2.7/site-packages/deluge/_libtorrent.py", line 59, in <module>
    import libtorrent as lt
ImportError: /usr/local/lib/python2.7/site-packages/libtorrent.so: Undefined symbol “_ZNK10libtorrent14announce_entry12can_announceEN5boost6chrono10time_pointINS2_12steady_clockENS2_8durationIlNS1_5ratioILl1ELl1000000000EEEEEEEb”` 

I also reported this error to deluged but it got closed stating that I should report it here: http://dev.deluge-torrent.org/ticket/2908

**Comment by athei** [comment]
It just got fixed in freebsd. The problem was that they did not build the python bindings with c++11 support. For reference:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=213739

**Comment by XRevan86** [comment]
How about this:
```diff
--- a/bindings/python/setup.py
+++ b/bindings/python/setup.py
@@ -114,7 +114,10 @@ else:
 
 		# for some reason distutils uses the CC environment variable to determine
 		# the compiler to use for C++
-		os.environ["CC"] = os.environ['CXX']
+		if 'CXX' in os.environ:
+			os.environ['CC'] = os.environ['CXX']
+		if 'CXXFLAGS' in os.environ:
+			os.environ['CFLAGS'] = os.environ['CXXFLAGS']
 
 		ext = [Extension('libtorrent',
 			sources = source_list,
```

**Comment by arvidn** [comment]
This looks similar to this fix in master. perhaps it should be back-ported too.

https://github.com/arvidn/libtorrent/commit/30873e9c9118bcf0f0755e7eb4a81fefcb19d9b7

**Comment by arvidn** [comment]
oh, sorry.. it's based on it..

**Comment by XRevan86** [comment]
@arvidn, yeah. Well, backporting this and not 30873e9 would practically only mean not making a change in .travis.yml :-).

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/1394
