### ISSUE TITLE
(Win) Crash libtorrent::aux::random_engine 

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#1262]
libtorrent version (or branch): master
platform/architecture: windows
compiler and compiler version: VC++2015

Crash stack:
https://drdump.com/DumpGroup.aspx?DumpGroupID=640982&login=guest

![libtorent-rand_s-crash](https://cloud.githubusercontent.com/assets/920705/19738216/3c75ff38-9bbf-11e6-9cf2-fddeb2d34389.png)

a similar crash sqlite:
https://drdump.com/Problem.aspx?ProblemID=215687&login=guest
https://drdump.com/DumpGroup.aspx?DumpGroupID=527489&login=guest

abort() point:
https://github.com/DinrusGroup/DinrusUcrtBased/blob/5ac78908caa4536c8e3a359744b204512e80af41/Binding/ucrt_src/internal/winapi_thunks.cpp#L719

Any idea?

**Comment by arvidn** [comment]
This is the ``random_device`` failing to be constructed. Presumably it *should* throw an exception, but for some reason it aborts instead. Perhaps there is no try block to catch it up the callstack. You could either catch the exception, or look at standard error to see if it prints any useful information. Normally I would expect ``abort`` to indicate an assert firing.
