### ISSUE TITLE
Torrent status time_since_upload & time_since_download showing same value as active_time

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1263]
As per title but also no torrents ever show `-1` value which I wonder is what `time_since_upload` and `time_since_download` should be after more than 18hours...

libtorrent version (or branch): 1.0.9 (python bindings)

**Comment by arvidn** [comment]
Looking over the code, it all looks correct. Those counters are never supposed to return -1. They are incremented by 1 each second, and every time a piece passes the hash-check the download counter is reset to 0, and every time an asynchronous send comes back and some actual payload was sent, the upload counter is reset to 0. They fit 24 bits internally, which ends up being thousands of hours, but they do wrap after that.

You say you only ever see them report the same as the ``active_time``, despite (I assume) downloading or seeding payload to/from those torrents, right?
Is the ``active_time`` field correct?
Fundamentally it's treated the same way, but it's never reset to 0.

**Comment by arvidn** [comment]
it looks like for paused torrents, these counters are not updated correctly though. is this the case where you see the problem as well?

**Comment by cas--** [comment]
I shall look into those details but the question about -1 is from the docs and it states the values never go beyond 18hrs. So perhaps docs need corrected?

**Comment by arvidn** [comment]
another issue is that torrents that don't have any activity will not cause an update to be triggered, i.e. a ``state_update_alert`` won't be posted every second just because these counters are incremented. I don't really want to do that though, and these relative counters should probably be superseded by fixed timestamps.

**Comment by arvidn** [comment]
I'm looking at the docs at the head of the RC_1_0 branch, which doesn't say that for these two fields. It's possible 1.0.9 said that though.

**Comment by arvidn** [comment]
Here's a fix for the paused torrent issue: https://github.com/arvidn/libtorrent/pull/1270
please let me know if that helps or appears to work.

**Comment by cas--** [comment]
Ah it was the [1.1 docs](http://libtorrent.org/reference-Core.html#session)

Thanks I'll check that out
