### ISSUE TITLE
1.1 docs for deprecated methods

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1273]
I have found a few inconsistencies in the online docs while migrating python code to 1.1 with no deprecated methods.
- In [settings_pack](http://libtorrent.org/reference-Settings.html#settings_pack) there is reference to the `listen_on()` method but as it is deprecated now it is a bit confusing. I assume `settings_pack::listen_interfaces` now performs the same action.
- In the session [section](http://libtorrent.org/reference-Core.html#session) there is the text below. I assume it needs reworded to refer to `settings_pack::listen_system_port_fallback`.

> It is possible to prevent libtorrent from binding to port 0 by passing in the flag session::no_system_port in the flags argument.
- In addition there is the `listen_reuse_address` flag which I can find no reference to in settings_pack.
- It looks like [`outgoing_ports`](https://github.com/arvidn/libtorrent/blob/RC_1_1/bindings/python/src/session.cpp#L776) has been missed being marked `TORRENT_NO_DEPRECATE`.

**Comment by arvidn** [comment]
thanks. Does this look reasonable? https://github.com/arvidn/libtorrent/pull/1274

**Comment by cas--** [comment]
Looks good, although perhaps clarify that libtorrent will attempt reuse the port?

I just found `settings_pack::dht_bootstrap_nodes` does this mean that `add_dht_router()` also needs deprecated?

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/1275 ?

**Comment by arvidn** [comment]
I'm a bit hesitant to document the ability to bind to a device name. I don't feel too confident about it and I would need to discover its limitations. the socket binding logic was overhauled and simplified in master, specifically to support arbitrary/multi-homed binding and binding to device.

**Comment by cas--** [comment]
Those changes look great, I missed seeing `max_retry_port_bind` :)

That makes sense about device name binding. Did you want to remove the reference to it under outgoing ports in 1.1 docs?

**Comment by cas--** [comment]
Not a documentation issue but related to deprecation, the replacement [`tracker_error_alert.error_message`](https://github.com/arvidn/libtorrent/blob/RC_1_1/bindings/python/src/alert.cpp#L312) has been defined as `def` rather than `def_readonly`, is this a typo?
