### ISSUE TITLE
Use add_property instead of def for replacement of def_readonly in python bindings

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1278]
I was looking at the 1.1 deprecated attributes and in [alert.cpp](https://github.com/arvidn/libtorrent/blob/RC_1_1/bindings/python/src/alert.cpp#L312) found that the old attributes with `def_readonly` had been replaced with new ones, except were now using `def`. There was no associated commit message as to the reason for this change. 

I did find one reference to a potential issue building with [VS2013](https://github.com/OpenImageIO/oiio/issues/1516) and after a bit of digging around I found that [`error_message`](https://github.com/arvidn/libtorrent/blob/d1e916ec9ec5526f2faa7ee6f7c10f8eaded8035/include/libtorrent/alert_types.hpp#L447) is a function whereas `times_in_row` is a member of `tracker_error_alert` so I believe the actual fix for [exposing](http://www.boost.org/doc/libs/1_61_0/libs/python/doc/html/tutorial/tutorial/exposing.html) these in python bindings should be to replace `def_readonly` with `add_property`.

**Comment by arvidn** [comment]
I'm not sure I understand the problem. I imagine ``def_readonly`` is meant to indicate that these members aren't really supposed to be mutable (in fact, @aldenml has started to patch some member in the C++ code to be ``const``).

Some accessors on alerts are functions because they are backed by a special allocator (strings like the error code for instance). I would imagine this is exposed uniformly in python though.
I would imagine that all fields really should be marked read-only.

**Comment by cas--** [comment]
At first I thought it was just good practice to use the correct one however some quick testing show it could well cause an issue because you can set an object value that should be read-only:

.def("dht_state", allow_threads(&lt::session::dht_state))
```
>>> session = lt.session()
>>> session.dht_state
47: <bound method session.dht_state of <libtorrent.session object at 0x7f30a4e47680>>
>>> session.dht_state()
48: {'node-id': 'hU7\xfc7\x9c~\xec\x96~j\xdc\xf2\xa1\x82\xac\xe31s['}
>>> session.dht_state = 5
>>> session.dht_state()
Traceback (most recent call last):
  File "<pyshell#83>", line 1, in <module>
    session.dht_state()
TypeError: 'int' object is not callable
>>> session.dht_state
49: 5
```
At this the session object is corrupt so you cannot get dht_state without creating a new session object.

Compared with `add_property` and `def_readonly`:

`.add_property("utp_stats", &get_utp_stats)`

```
>>> s_status = session.status()
>>> s_status.utp_stats
51: {'num_close_wait': 0,
 'num_connected': 0,
 'num_fin_sent': 0,
 'num_idle': 0,
 'num_syn_sent': 0}
>>> s_status.utp_stats = 5
Traceback (most recent call last):
  File "<pyshell#91>", line 1, in <module>
    s_status.utp_stats = 5
AttributeError: can't set attribute
```
`.def_readonly("unchoke_counter", &session_status::unchoke_counter)`

```
>>> status.unchoke_counter
45: -6919
>>> status.unchoke_counter =6
Traceback (most recent call last):
  File "<pyshell#76>", line 1, in <module>
    status.unchoke_counter =6
AttributeError: can't set attribute
```

**Comment by arvidn** [comment]
I recently learned that custom converters only work for ``add_property`` and not for ``def_readonly``. so I've updated the bindings for types that need conversion.

**Comment by cas--** [comment]
Ah ok, what about the use of `def`s where they should be read only?

**Comment by arvidn** [comment]
I'm under the impression that ``add_property`` can be made to be read-only too.. I think most of them are currently. Is your example above showing that on the python side one can still replace the whole property with something else?

**Comment by cas--** [comment]
Yeah that's the issue, it's not the replacing `def_readonly` with `add_property` that I'm referring to. It's all the `def()`s that replaced `def_readonly` in recent commits that need to be `add_property`

**Comment by cas--** [comment]
I have got a bit confused here, too much jumping around different code. My code example is a bit wrong...

The use of `add_property` would mean we could access alert details as class properties without a method call but that would contradict documentation.

I'll close this ticket for now. It's good at least potential conversion issues were picked up. :)
