### ISSUE TITLE
1.1 deprecated enum key in python bindings missing dummy replacement 

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1279]
[queued_for_checking](https://github.com/arvidn/libtorrent/blob/RC_1_1/bindings/python/src/torrent_status.cpp#L125) is missing the equivalent [unused_enum_for_backwards_compatibility](https://github.com/arvidn/libtorrent/blob/6148984426e3e12371dd5faadf59e86608da021e/include/libtorrent/torrent_status.hpp#L77)

**Comment by arvidn** [comment]
interesting, I wouldn't expect python to need that. you think that name should be replicated in the python binding?

**Comment by cas--** [comment]
From what I can tell it will the affect the indexing lookup, I don't think it's a big issue but a deprecated vs non-deprecated build would return different values.

**Comment by arvidn** [comment]
but the underlying values are tied to the values of the C++ enum.. no?

**Comment by cas--** [comment]
ah I don't have a build to test that theory :)

**Comment by arvidn** [comment]
the second argument to ``.value()`` is the C++ enum, and should be defining the value for the python enum

**Comment by cas--** [comment]
I see now, good point, was worth checking ;)
