### ISSUE TITLE
Subtitute #if !defined for #ifndef TORRENT_NO_DEPRECATE in python bindings

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1280]
This is a fairly trivial change but I had been using a file search for `#ifndef TORRENT_NO_DEPRECATE` but then noticed that in [`torrent_info.cpp`](https://github.com/arvidn/libtorrent/blob/6751a1eeb1dd79bdc90dbf57cc965a6d1313f82f/bindings/python/src/torrent_info.cpp#L294) a different convention of `#if !defined TORRENT_NO_DEPRECATE` being used which was a bit confusing and meant I missed them initially...

**Comment by arvidn** [comment]
fixed in RC_1_1
