### ISSUE TITLE
Add magnet uri support for tr.x tracker

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1302]
Do you think libtorrent could add support for tracker tiers included in some magnets. I am in the middle of adding support for it to our code but realised it would be useful for libtorrent to also have it.

The specs are outlined in this Deluge ticket: http://dev.deluge-torrent.org/ticket/2716

I am not sure whether creating magnet uris should contain the `tr.x=` param or simply stick with `tr=` as default. Alternatively only use `tr.x=` if trackers share a tier...

**Comment by arvidn** [comment]
I don't have time doing this myself right now, but patches are welcome. (along with tests of course)

**Comment by cas--** [comment]
That's ok, I've not got around to implementing in Deluge yet either but i thought I should mention it

**Comment by cas--** [comment]
Fixed via: #3647
