### ISSUE TITLE
Trackers from magnet uris in distinct tiers

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1303]
I realised that libtorrent is adding all trackers in a magnet uri to the same tier. We currently do the same in Deluge but this does not make sense as most magnets specify distinct trackers and so should be one tracker per tier.

This would apply to all versions of libtorrent.

**Comment by arvidn** [comment]
does this look reasonable? https://github.com/arvidn/libtorrent/pull/1304

**Comment by cas--** [comment]
Looks good, though I was just reading the multi-tracker spec again... Have I interpreted tiers correctly and does this change make sense from your understanding?

**Comment by arvidn** [comment]
well.. I don't really think anyone creating torrents ever honored or understood the multitracker spec. In some sense, the trackers people add to torrents/magnet links are basically guaranteed to be independent. I don't know of a tracker that implements shared state across multiple endpoints. So, in that sense this patch makes sense.

On the other hand, this will definitely cause a lot more tracker traffic for existing magnet links.

**Comment by arvidn** [comment]
pushed to RC_1_1 and master
