### ISSUE TITLE
[Crash] libtorrent::aux::session_impl::on_tick

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#1329]
libtorrent version (or branch): master
platform/architecture: x86 Visual C++ 2015 up3
compiler and compiler version:

https://drdump.com/Problem.aspx?ProblemID=247801&login=guest

![libtorrent-2016-11-16_09-40-46](https://cloud.githubusercontent.com/assets/920705/20337334/977109aa-abe1-11e6-9c04-086f6dd0b31b.png)

**Comment by Falcosc** [comment]
@pavel-pimenov do you have an idea to reproduce it?
I'm not sure about the possibilities to guess what did case an Access Violation there.

**Comment by pavel-pimenov** [comment]
No:-( only 4 crash dump from anonymous user.
