### ISSUE TITLE
Default piece priority changed from 1 to 4 in libtorrent 1.1

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1334]
It seems the default piece priority has been changed to 4 in [libtorrent 1.1](https://github.com/arvidn/libtorrent/commit/097d5b484d124c82801dfbed53acda3b42b13c5c)

I saw no mention in the changelog about this and only just noticed due to tests running with lt 1.1 that started failing on priority comparison. For reference we have mapped the priorities in our code based on this spec for lt<=`1.0`: 
```
There are 8 different priority levels:

        piece is not downloaded at all
        normal priority. Download order is dependent on availability
        higher than normal priority. Pieces are preferred over pieces with the same availability, but not over pieces with lower availability
        pieces are as likely to be picked as partial pieces.
        pieces are preferred over partial pieces, but not over pieces with lower availability
        currently the same as 4
        piece is as likely to be picked as any piece with availability 1
        maximum priority, availability is disregarded, the piece is preferred over any other piece with lower priority
```
I don't expect it to cause any breakage for the application but it will require future UI changes. The main problem is that priority tests are failing and will now need to verify which version of libtorrent before comparing priority changes.

I think it would be useful to have a document that details deprecated methods and changes such as this from version to version.

**Comment by arvidn** [comment]
yes, this should definitely be in the Changelog. that was an oversight.

**Comment by arvidn** [comment]
I updated the Changelog at the point where this was changed, which was in the 1.1.0 release

**Comment by arvidn** [comment]
btw, an alternative to checking the libtorrent version would be to unconditionally set the priority to whatever you want it to be.

**Comment by cas--** [comment]
That's a great idea, we don't actually use level 4 in Deluge so will make it easier, thanks :-)
