### ISSUE TITLE
Encryption settings per torrent

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#1339]
Is there a way to set the encryption level per torrent in master?
From my observation, metadata downloads use an unexpected high amount of cpu (to establish connections to peers).
Therefore, I would like to disable encryption until metadata was received.

**Comment by arvidn** [comment]
that's an interesting idea. I have also observed the cost of the DH handshake being surprisingly high. I would expect it to be equally high after receiving metadata too though. What do you see to think cutting down on it before metadata would help? is the connection rate higher?

**Comment by MassaRoddel** [comment]
More investigations showed that the problem is a bit worse to handle.
Actually, I do not see a difference between before and after metadata was received for a torrent.
My DHT scanner creates a high number of short-lived (5min) torrents for metadata download only (up to ~300).
After some time, there is the problem of many incoming connections for no longer existing torrents.
Disable encryption for specific torrents would only solve a part of the problem. Only completely disabled encryption should keep the cpu load low.

snip from profiler
 - libtorrent::peer_connection::on_receive_data	44,53%	0,01%	32296	7	MooPolice.exe
   - libtorrent::bt_peer_connection::on_receive	43,99%	0,01%	31903	8	MooPolice.exe
     - libtorrent::bt_peer_connection::on_receive_impl	43,98%	0,03%	31894	19	MooPolice.exe
       + libtorrent::dh_key_exchange::compute_secret	25,15%	0,00%	18241	0	MooPolice.exe
       + libtorrent::bt_peer_connection::write_pe1_2_dhkey	18,16%	0,00%	13167	0	MooPolice.exe
       + libtorrent::peer_connection::attach_to_torrent	0,30%	0,00%	216	3	MooPolice.exe
       + libtorrent::peer_connection::disconnect	0,12%	0,00%	87	3	MooPolice.exe
       + libtorrent::bt_peer_connection::dispatch_message	0,06%	0,00%	46	1	MooPolice.exe

compute_secret() + write_pe1_2_dhkey() means incoming connection, right?

**Comment by Falcosc** [comment]
@MassaRoddel if I do understand it correctly your investigation did show that only a completely disabled encryption reduce the cpu load.

Is there now still any advantage to have encryption settings per torrent? Or would you just disable it at all?

**Comment by MassaRoddel** [comment]
For my case there would be no advantage because most cpu goes to incoming connections for nonexisting torrents.
(you have to receive the info hash before you can check if a torrent is in the session)
I would disable all encryption. I could disable encryption for incoming and enable it for outgoing connections but that does not seem to make much sense.

**Comment by Falcosc** [comment]
Sounds comprehensible. Could we close the issue with disable SSL as solution?

**Comment by arvidn** [comment]
SSL is independent from protocol encryption. but disabling protocol encryption would fix the CPU usage issue for incoming connections.
