### ISSUE TITLE
warning C4275: non dll-interface struct

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#1348]
libtorrent version (or branch): master
compiler and compiler version: visual C++2015 u3

warning C4275: non dll-interface struct 'libtorrent::disk_job_fence' used as base for dll-interface struct 'libtorrent::storage_interface' (compiling source file windows\IntegrationPage.cpp)
![2016-11-22_09-10-46](https://cloud.githubusercontent.com/assets/920705/20512915/a2147e62-b093-11e6-96da-ac6d098cbc45.png)

**Comment by arvidn** [comment]
I don't think this is a problem. do you experience any?

**Comment by pavel-pimenov** [comment]
Spam appveyor:
https://ci.appveyor.com/project/pavel-pimenov/flylinkdc-r5xx/build/messages

**Comment by arvidn** [comment]
would you mind creating a pull request marking ``disk_job_fence`` with ``TORRENT_EXPORT``?
