### ISSUE TITLE
autoreconf -fi fails with 1_0_10

### ISSUE THREAD

**Issue by slackhead** [arvidn/libtorrent#1351]
libtorrent version (or branch): 1_0_10

platform/architecture: slackware x86_64 14.2

compiler and compiler version: autoconf 2.69

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

autoreconf -fi fails:
error: required file 'build-aux/config.rpath' not found
./configure fails with: 
config.status: error: cannot find input file: `Makefile.in'

Any help greatly appreciated.

**Comment by arvidn** [comment]
did you run ``./autotool.sh`` ?

**Comment by slackhead** [comment]
No I didn't. That fixed it, thanks.
