### ISSUE TITLE
ImportError when using the Python 3 libtorrent module

### ISSUE THREAD

**Issue by leigh123linux** [arvidn/libtorrent#1365]
libtorrent version (or branch): libtorrent-1.1.1

platform/architecture: Linux Fedora 25 x86_64

compiler and compiler version: gcc-6.2.1

Running the commands below I expect it to return libtorrent version

python3
import libtorrent

Actual results:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError:
/usr/lib64/python3.5/site-packages/libtorrent.cpython-35m-x86_64-linux-gnu.so:
undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE

Bug reproduced locally so I  forwarded it from

https://bugzilla.redhat.com/show_bug.cgi?id=1399390

**Comment by arvidn** [comment]
the module has to be built for python3. for example:

``bjam -j4 libtorrent-link=static boost-link=static python=3.5 stage_module``

**Comment by arvidn** [comment]
python2.x and python3.x have different interfaces to modules

**Comment by Falcosc** [comment]
@leigh123linux would be nice if you could forward the adwise. The lib compilation does not match to python version.

**Comment by leigh123linux** [comment]
@arvidn I located the issue, the code doesn't test the existence boost_python

```
-	--with-boost-python=boost_python%{python3_version} \
+	--with-boost-python=boost_python3 \ 
```

It was blindly linking against -lboost_python3.6, correcting it to -lboost_python3 fixes it

**Comment by arvidn** [comment]
is this patch against boost itself, or something other than libtorrent?

**Comment by leigh123linux** [comment]
It was the change required for the libtorrent spec file needed to link correctly
http://pkgs.fedoraproject.org/cgit/rpms/rb_libtorrent.git/commit/?id=1122f69b8eb00ad301d9d34c20907fc2359a497c
