### ISSUE TITLE
lt1.1 piece_priorities set to 1 not 4

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1372]
Uncovered a bug with piece priorities in RC_1_1.

The `piece_priorities` are all set to `1` when `file_priorities` are set to `4` upon first adding a torrent.

I think there may be a timing issue as it first appeared as failing tests on Travis and not locally. The local tests do show `piece_priorities` set to `1` initially but by the next print statement they are set to `4`...

**Comment by arvidn** [comment]
I'm not sure what might be causing this, perhaps this will fix it: https://github.com/arvidn/libtorrent/pull/1379

**Comment by cas--** [comment]
That fix doesn't seem to do it.

It can be replicated, if you add the following to the binding test.py: 

```diff
diff --git bindings/python/test.py bindings/python/test.py
index 4df6bfb..e594f11 100644
--- bindings/python/test.py
+++ bindings/python/test.py
@@ -29,6 +29,9 @@ class test_torrent_handle(unittest.TestCase):
                ti = lt.torrent_info('url_seed_multi.torrent');
                h = ses.add_torrent({'ti': ti, 'save_path': os.getcwd()})
 
+               self.assertEqual(h.file_priorities(), [4,4])
+               self.assertEqual(h.piece_priorities(), [4])
+
                h.prioritize_files([0,1])
                self.assertEqual(h.file_priorities(), [0,1])
```

**Comment by arvidn** [comment]
great, thanks. I'll do that

**Comment by arvidn** [comment]
one more try: https://github.com/arvidn/libtorrent/pull/1384

**Comment by cas--** [comment]
fyi needs applied to master

**Comment by arvidn** [comment]
this has been merged into master now
