### ISSUE TITLE
Cannot pass configure checks on Debian - libboost marked as missing

### ISSUE THREAD

**Issue by fabiolcf** [arvidn/libtorrent#1374]
libtorrent version (or branch): 1.0.10

platform/architecture: Debian 6 x86

compiler and compiler version: gcc 4.4.5

I have libboost-dev-all loaded (libboost 1.42) - and I compiled the latest libboost-1.62 and put it in /usr/local with no effect. configure halts with:

Checking for boost libraries:
checking for boostlib >= 1.36... configure: We could not detect the boost libraries (version 1.36 or higher). If you have a staged boost library (still not installed) please specify $BOOST_ROOT in your environment and do not give a PATH to --with-boost option.  If you are sure you have boost installed, then check your version number looking in <boost/version.hpp>. See http://randspringer.de/boost for more documentation.
checking whether the Boost::System library is available... no
configure: error: Boost.System library not found. Try using --with-boost-system=lib

I tried with the various --with-boost and --with-boost-libdir parameters to no effect.

Any ideas on what could be going on? /usr/include/boost/version.hpp is there and happily reports 1.42, the libraries are there...

Edited to add: the old 0.15 tree recognises libboost >1.36 and compiles correctly.

Edited to further add: none of the versions still on the page, from 0.16.19 all the way to 1.0.10 , recognise libboost, even with 1.62 correctly installed. Something is... evidently wrong. config.log doesn't seem to contain much of assistance.

**Comment by cas--** [comment]
There is no issue with building 1.0 with those boost versions. It suggests a setup issue on your side.

For Deluge these are the instructions that work up to version 1.0:

http://dev.deluge-torrent.org/wiki/Building/libtorrent#UbuntuDebian

Also from our PPA the debian packaging:

https://launchpad.net/~deluge-team/+archive/ubuntu/ppa/+files/libtorrent-rasterbar_1.0.9-1~precise~ppa4.debian.tar.gz

**Comment by fabiolcf** [comment]
Well, what I can say is that with Debian 7.11 , the build works. With 6.10, 0.15 does, 0.16+ does not.

Thus the question becomes: what changed in the autoconf script between 0.15.10 and 0.16.x ?

**Comment by cas--** [comment]
Afaik there was no issue building libtorrent 0.16 for debian squeeze. It could be the build tools shipped in debian 6 are outdated. However since Feb '16 debian 6 (squeeze) is no longer supported and I don't think arvid will spend any time looking into this especially when wheezy onwards is fine.

**Comment by fabiolcf** [comment]
Tools don't .. outdate themselves. If they worked before, they should work now. But they evidently do not.

I was futzing around in the configure.ac files and noted that, if anything, there are MORE requirements in 0.15.10 then there are in 1.0.x. This is ... interesting.

Be that as it may, you do have a point that squeeze is no longer supported (and I solved my personal issue by crossbuilding on one of the 7 workstations, no you're not supposed to do that but yes, it works - and libtorrent is not exactly a production issue, in my particular case).

Onwards and upwards. Thanks cas.

**Comment by Falcosc** [comment]
I did have the same issue. The problem was that I wasn't able to install the debian 6 compilation of libboost in a way that it got picked by the installation script.

I didn't spend much time with it an did just an update to debian 8 which solved the problem.

**Comment by cas--** [comment]
This ticket should be closed
