### ISSUE TITLE
torrent_handle use_interface deprecated?

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1376]
I assume it is because the method is marked deprecated here:

https://github.com/arvidn/libtorrent/blob/RC_1_1/src/torrent_handle.cpp#L473

but the header file declaration has not been marked deprecated:

https://github.com/arvidn/libtorrent/blob/RC_1_1/include/libtorrent/torrent_handle.hpp#L985

This applies to both `RC_1_1` and `master`

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/1380

**Comment by cas--** [comment]
fyi, this change needs applied to master

**Comment by Falcosc** [comment]
Is applyied since 9 days
https://github.com/arvidn/libtorrent/commit/a2c4e7490e2ae7aecd512715d754202ec4f06995

ticket could be closed
