### ISSUE TITLE
Python bindings methods missing in RC_1_1

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1377]
I found the following missing items from python bindings in RC_1_1

**session_stats**
```
session_stats_metrics 
find_metric_idx
```

**torrent_handle**
```
clear_piece_deadlines
file_status
add_extension
set_pinned
```
I know that `set_pinned` is deprecated in `master` but perhaps for consistency should still exist.
Also not sure if `add_extension` is relevant to python bindings?

**flags_t**:
```
overwrite_existing
```

**save_resume_flags_t**:
```
save_info_dict
only_if_modified
```

**torrent_info**
```
similar_torrents
collections
set_web_seeds
unload
load
ssl_cert
is_valid
is_i2p
is_loaded
parse_info_section
info
swap
is_merkle_torrent
parse_torrent_file
```

**torrent_status**
```
operator==
handle
torrent_file
```

**Comment by arvidn** [comment]
ok, here's a start: https://github.com/arvidn/libtorrent/pull/1444

**Comment by arvidn** [comment]
set_pinned(), load(), unload(), is_loaded() are all going away. I won't add those.

**Comment by arvidn** [comment]
next: https://github.com/arvidn/libtorrent/pull/1448

**Comment by cas--** [comment]
Excellent though the launchpad builds are failing with latest commit to RC 1.1

https://launchpadlibrarian.net/299809585/buildlog_ubuntu-xenial-amd64.libtorrent-rasterbar_1.1.2dev8423+820fd29+201612231726~ubuntu16.04.1_BUILDING.txt.gz

**Comment by arvidn** [comment]
both are merged now. I think that covers the most important parts (i.e. I don't consider this a blocker for 1.1.2 anymore)

**Comment by cas--** [comment]
Did you fix the build issue? 

```
/<<BUILDDIR>>/libtorrent-rasterbar-1.1.2dev8423+820fd29+201612231726~ubuntu16.04.1/bindings/python/src/converters.cpp:93:87: error: ‘>>’ should be ‘> >’ within a nested template argument list
     to_python_converter<std::vector<lt::stats_metric>, vector_to_list<lt::stats_metric>>();
                                                                                       ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Makefile:529: recipe for target 'all-local' failed
```

**Comment by arvidn** [comment]
first attempt: https://github.com/arvidn/libtorrent/pull/1452

**Comment by cas--** [comment]
Looks like correct fix :-)  If it's merged I can refresh RC_1_1 build on launchpad.

Is it master branch that is C++11 only now?

**Comment by arvidn** [comment]
yes

**Comment by arvidn** [comment]
I'm not sure ``swap`` makes sense in python. since everything is passed and held by pointer in python, I would expect it to make more sense to swap objects at the python level

**Comment by cas--** [comment]
Yeah sure, I was looking again at docs and thought that too :-)

**Comment by cas--** [comment]
Need to also fix `string>>` : https://github.com/arvidn/libtorrent/commit/fa7846d1fdfae8715459b4f2ba04d7af52b6d3d3#diff-67fac701f542e4432cd9f371b2408ba8R96

**Comment by arvidn** [comment]
fixed

**Comment by cas--** [comment]
Looks good here: https://code.launchpad.net/~deluge-team/+recipe/libtorrent-1.1-daily

Thanks and merry xmas to you! :D
