### ISSUE TITLE
How can I get web peers download payload and download protocol ?

### ISSUE THREAD

**Issue by ximply** [arvidn/libtorrent#1381]
I find something about payload and protocal stat in _**stat.hpp**_ as follows:
_upload_payload,
upload_protocol,
download_payload,
download_protocol,
upload_ip_protocol,
upload_dht_protocol,
upload_tracker_protocol,
download_ip_protocol,
download_dht_protocol,
download_tracker_protocol._

Now I want to get the payload and protocal about web peers, is there any way to do get it?

**Comment by arvidn** [comment]
web peers don't have separate accounting of bandwidth usage from regular bittorrent peers as far as I know, their bandwidth should be included in the upload and download protocol/payload counters

**Comment by ximply** [comment]
well, I see, but do you have a plan to support it?

**Comment by arvidn** [comment]
if you by "it" refer to session level transfer counters for web seeds, then no. you can query all peers for their stats though, and add it up yourself.

**Comment by ximply** [comment]
well, let me try it.
