### ISSUE TITLE
dht and x.pe arguments from a magnet link are parsed incorrectly by a Python binding.

### ISSUE THREAD

**Issue by vkhorozvs** [arvidn/libtorrent#1386]
- libtorrent version (or branch): 0.9.5, master
- platform/architecture: all
- compiler and compiler version: all

A BEP5 allows to specify `dht` and `x.pe` arguments in a magnet link and they are parsed properly by `parse_magnet_link` function of libtorrent.  However, a Python binding to this function behaves incorrectly:

- for `dht` it adds all DHT nodes into a tracker list.
- `x.pe` argument is simply ignored.

For `dht` case an error is here: ``https://github.com/arvidn/libtorrent/blob/master/bindings/python/src/magnet_uri.cpp#L58``
For `x.pe` case a Python binding didn't implement the logic.

**Comment by arvidn** [comment]
it's not incorrect, it's just not supported

**Comment by vkhorozvs** [comment]
@arvidn I may agree that `x.pe` is not supported by a Python binding (though it's supported by a C++ function).

Regarding DHT part: this code extracted from `https://github.com/arvidn/libtorrent/blob/master/bindings/python/src/magnet_uri.cpp#L58` really looks like a typo in a variable name (`tracker_list -> node_list`) i.e. a bug:

~~~C++
		list nodes_list;
		for (auto const& i : p.dht_nodes)
			tracker_list.append(boost::python::make_tuple(i.first, i.second));
		ret["dht_nodes"] = nodes_list;
~~~

I may prepare a fixing both issues in Python binding if you wish as it's quite trivial.

**Comment by arvidn** [comment]
I see. I forgot that this feature was added to libtorrent. please submit a PR. make sure to add a test for ``parse_magnet_uri()`` to ``test.py`` as well
