### ISSUE TITLE
[Feature Request] Larger and less webseed requests over multiple pieces

### ISSUE THREAD

**Issue by Falcosc** [arvidn/libtorrent#1405]
libtorrent version (or branch): head 3.3
platform/architecture: linux

Hi,
by using webseed feature per http url-list entry I see that libtorrent creates as many request as torrent has pieces. It's not so nice to create 1000's of http requests, especially because http requests creating a lot more load on a http server compared to 1000's bittorrent requests, it’s even worse if there are multiple http servers involved to handle my requests. For that reason it would be very nice to request more than 1 piece per http request like GetRight http://getright.com/seedtorrent.html
Unfortunately GetRight is not usable on a linux environemt without X. That’s the reason why I do use libtorrent.
By connecting to my own http server I did test the current behavior and got for each piece a new request in access log.

### Full Target:
The best solution would be an open http stream of the largest possible range of pieces and collecting pieces direct during stream processing to get the first pieces available before the full http response is done.
### Smaller Target:
I know that piece processing during stream receive does not fit into the current implementation style. If it is easier to implement it would be ok to have the piece processing after the response is done. But than we would need a max range, maybe 1/10 of the torrent size to get the first pieces available after 10% is downloaded.
If needed it would also ok to force the urlseed_pipeline_size to 1 to skip this logic if this makes it easier to implement larger http request ranges.
### Why this could help to improve liborrent:
An advantage of implementing a sequential Webseed processing with piece handling during response stream handling would be the preparation for FTP Webseed support. But don’t talk about FTP support, that’s something for the future. 

I hope you could understand what I would like to see. If not I would like to answer your questions.

Kind Regards
Falco

**Comment by arvidn** [comment]
the default of requesting 1 MiB at a time is hardcoded here:

https://github.com/arvidn/libtorrent/blob/master/src/web_peer_connection.cpp#L84

If you want larger requests, you can try increasing that constant. A patch to make it configurable would be welcome!

**Comment by Falcosc** [comment]
Thank you for your fast response.
I'm ok with changing the hardcoded value.

By such a small max size I guess that pieces are verified after the whole response is back, isn't it?

Example a 1GiB file with 1000 pieces
If I set 100MiB, and my download process is at 180MiB, how many pieces are available for the peers? 100 or 179?

If everthing is working fine I will tell you. 
Unfortunately I didn't have an C++ Development Environment, I could try to create a patch based on previous new settings options. But I could be only a diff file and I can't create tests and I can't test the settings interface, I would just relay on the new default settings value in sessions_pack.cpp.
Would this still help you? Because that would take a lot of effort for just a few new lines in some files because without C++ experience I would have to create the whole long running make process after each test run.

Kind regards,
Falco

**Comment by Falcosc** [comment]
I did a testrun. But there is more than this constant, everything above 4MiB is splittet into 16384 + 4177920 
after a couple of parts there are only 16384 requests

Like this
`4177920 
16384
4177920 
16384 
4177920 
16384 
4177920 
16384 
4177920 
16384 
4177920 
16384 
4177920 
....
16384 
16384
16384
16384
16384
16384
16384
16384 
`


And even with 1MiB there are 16384 requests after a couple of parts. Are these 16384 requests a kind of verificytion? Because after them my parts get accnolaged.
`1048576
1048576
1048576
1048576
1048576
...
16384
16384
16384
16384
16384
`

Is it possible to skip these 16384 requests and do you have an idea why everthing above 4MiB is splittet into 4177920 + 16384?

**Comment by Falcosc** [comment]
I found out that this problem is a little bit older:

https://sourceforge.net/p/libtorrent/mailman/message/34350715/

After reading this I have to add the follow information:
- I don't have bittorent peers for my test webseed file, it's 100% webseed download.

**Comment by Falcosc** [comment]
m_desired_queue_size adjustments did not work and I still have trubble to get the logging on.

**Comment by Falcosc** [comment]
std::uint8_t m_prefer_contiguous_blocks is the problem, that means max 255: (4MiB -16KiB)

**Comment by Falcosc** [comment]
2nd problem is the piecepicker mode. I will force sequential mode on torrents which contains webseed

**Comment by Falcosc** [comment]
Now it is implemented, but I still need to make it configureable and I would like to give the diff to one of you because I'm not an C++ developer.

Do you want to close the issue or do we want to wait for a commit?

Kind Regards
Falco

**Comment by arvidn** [comment]
thanks for looking into this. which version of libtorrent are you using? I expect the ``uint8_t`` problem to exist all the way back to the 1.0.x series, and should be fixed against the RC_1_0 branch.

What is the problem in the piece picker? does forcing sequential mode cause the problem or solve it?

I can see that enabling sequential download may interfere with the ``expand_piece`` that's used to request multiple adjacent pieces for webs seeds.

As for the diff, would you be able to submit a pull request (if so, please make it against RC_1_1 or RC_1_0 and I will merge it forward)?

**Comment by Falcosc** [comment]
I will try. But I don't know how to push my commits to your repo? I guess that I could not commit to your branches. Is it allowed to create branches in your repo or do I have to fork it?

Piece Picker mode may didn't change anything. Before I did analyse the picked pieces I did guess that the picker created gaps by doing his picking logic. But now I know that there is a problem with block finishing. I don't want to mix the bug with this feature, for that reason I did create a new issue.

**Comment by arvidn** [comment]
fork -> branch (in your clone) -> apply patch -> commit + push -> create PR (on github.com on the main repository's page)

**Comment by Falcosc** [comment]
Thanks, it could take a while because I have to test the settings interface with client_test. Currently it is still hardcoded.

**Comment by Falcosc** [comment]
The problem in RC_1_0 is much bigger, there is no contiguous blocks prefer, 1.0 has only whole piece or non whole piece.
I don't want to fix it there.

A configuration would make no sence because the values would not get applied on RC_1_0
