### ISSUE TITLE
libtorrent::fingerprint::name': was declared deprecated

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#1415]
libtorrent version (or branch): master
platform/architecture: win
compiler and compiler version: vc++ 2015

"Spam" libtorrent::fingerprint

https://ci.appveyor.com/project/pavel-pimenov/flylinkdc-r5xx/build/r503-87

Help?

**Comment by aldenml** [comment]
what do you mean with "Spam"? all in `identify_client` and the class `fingerprint` is deprecated

**Comment by pavel-pimenov** [comment]
Hm ok
#define TORRENT_NO_DEPRECATE

10>src\session_impl.cpp(6903): warning C4996: 'libtorrent::identify_client': was declared deprecated
10>  Q:\vc15\r5xx\libtorrent\include\libtorrent/identify_client.hpp(58): note: see declaration of 'libtorrent::identify_client'

Bug?

**Comment by arvidn** [comment]
does this look like a reasonable fix? https://github.com/arvidn/libtorrent/pull/1427
