### ISSUE TITLE
Deprecate h.torrent_info in python bindings?

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1416]
I saw on the mailing list that h.torrent_info is deprecated for h.torrent_file but was a bit confused because it's not marked as so in the bindings. It's not a major issue but is obviously useful keeping the methods the same for documentation and support.

**Comment by arvidn** [comment]
It is marked as deprecated in RC_1_1. perhaps I fixed this after cutting 1.1.0

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/blob/RC_1_1/bindings/python/src/torrent_handle.cpp#L428

**Comment by cas--** [comment]
My bad, I completely missed that deprecated was defined around those methods.

I think it would be really very useful to have the docs generate a deprecated page, I know that it currently removes them when parsing the headers so those deprecated entries could be added to a deprecated rst/html.
