### ISSUE TITLE
tracker_error_alert::message is not in UTF-8

### ISSUE THREAD

**Issue by alervd** [arvidn/libtorrent#143]
Hello,

The original bug report is here:
https://code.google.com/p/libtorrent/issues/detail?id=498

If was fixed, but there is 1 place in LT where it's not fixed yet. 
convert_from_native is not called there. 

It seems that the patch can't be attached here.

It's required to change:

if (error) error_message = error.message();

to this:

if (error) error_message = convert_from_native (error.message());

(see alert.cpp file).

**Comment by arvidn** [comment]
fixed here: https://github.com/arvidn/libtorrent/pull/146
