### ISSUE TITLE
How to build libtorrent for python3.5?

### ISSUE THREAD

**Issue by donitry** [arvidn/libtorrent#1438]
libtorrent version (or branch): libtorrent-1.0.10

boost : 1.6.2

platform/architecture: Linux Centos7 x86_64

compiler and compiler version: gcc-4.8.5

hi,
my question is how to built for python3.5.2 ?  

`bjam -j4 libtorrent-link=static boost-link=static python=3.5 stage_module ` unusefull

could you write a tutorial for it please?  thanks a lot~

**Comment by arvidn** [comment]
that command line is exactly how you would build for python. you run that out of the bindings/python directory, and since you link statically against boost you may need to have the boost (source) package available at ``BOOST_ROOT``, and you may have to add ``boost=source``

**Comment by arvidn** [comment]
you may also need to add a ``using python`` statement in your ``user-config.jam`` for boost-build to know where to pick up the python headers and libraries. As an example, this is what I have in my ``user-config.jam`` on macOS

`using python : 3.5 : /usr/local/bin/python3 : /usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/include/python3.5m : /usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/config-3.5m ;`

as well as the system python

`using python : 2.7 : /usr/bin/python : /usr/include/python2.7 : /usr/lib ;`

**Comment by donitry** [comment]
thank you for your help. then i built it without any error.

however,i got another !
`libtorrent.so: undefined symbol: libiconv_open`

I'm sure for that i had install the libiconv by 'yum'
like this:
`yum -y install libticonv libticonv-devel `
version is 1.1.4

and i try to found it 
`$nm /lib64/libc.so.6 |grep iconv
0000000000022590 T iconv
0000000000022720 T iconv_close
0000000000022220 T iconv_open
`

then i download the source of libiconv and change the command like this:
`bjam -j4 boost.locale.iconv=on libtorrent-link=static boost-link=static python=3.5 stage_module boost=source -sICONV_PATH=/root/examplePy/libiconv-1.14`

at laster, always show me : "libtorrent.so: undefined symbol: libiconv_open"

what i miss somthings befor building?  

thanks ~ and Merry Christmas~

**Comment by donitry** [comment]
thank you for your help And i finish build libtorrent.so by command "bjam -j4 dht=on iconv=on libtorrent-link=static boost-link=static python=3.5 stage_module boost=source" 

note: i update my boost to 1.6.3  so everthing is fine!

however , i got a new problem :(
` >>import libtorrent 

_frozen_importlib:222: RuntimeWarning: to-Python converter for boost::shared_ptr<libtorrent::alert> already registered; second conversion method ignored. `

mybe it's because of boost version.

**Comment by arvidn** [comment]
try building with "deprecated-functions=off". I have that problem on mac too, and I don't fully understand it

**Comment by Falcosc** [comment]
@donitry does deprecated-functions=off solve your issue?

**Comment by cas--** [comment]
RuntimeWarning issue: #1217

**Comment by Falcosc** [comment]
Then we could close this as dublicate
