### ISSUE TITLE
The msvc uses crashes.

### ISSUE THREAD

**Issue by MrPresidentCh** [arvidn/libtorrent#1447]
**Please provide the following information**

libtorrent version (or branch): 1_0_10

platform/architecture: windows

compiler and compiler version: bjam msvc-8.0 msvc-9.0

I use the static compiler libtorrent (MD MDd), at the same time, in the use of asio for the regular http download, the result is always void win_iocp_socket_service_base :: destroy function in the collapse of the crash, as long as there is a code in my Place boost :: asio :: connect method, even if the function is not called, will collapse. I tried a number of libtorrent version, but also tried vs2005 and vs2008, are the same amount of results, is the libtorrent library can not boost :: asio :: connect method works very well?

**Comment by arvidn** [comment]
do you have any more details of the crash? say, a stack-trace and the actual fault?

**Comment by MrPresidentCh** [comment]
>	test.exe!boost::asio::detail::win_iocp_socket_service_base::destroy(boost::asio::detail::win_iocp_socket_service_base::base_implementation_type & impl={...})  行156 + 0xc 字节	C++
 	test.exe!boost::asio::stream_socket_service<boost::asio::ip::tcp>::destroy(boost::asio::detail::win_iocp_socket_service<boost::asio::ip::tcp>::implementation_type & impl={...})  行120	C++
 	test.exe!boost::asio::basic_io_object<boost::asio::stream_socket_service<boost::asio::ip::tcp> >::~basic_io_object<boost::asio::stream_socket_service<boost::asio::ip::tcp> >()  行125	C++
 	test.exe!boost::asio::basic_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >::~basic_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >()  行1456 + 0x38 字节	C++
 	test.exe!boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >::~basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >()  + 0x2b 字节	C++
 	test.exe!boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >::`scalar deleting destructor'()  + 0xf 字节	C++
 	test.exe!libtorrent::socket_type::destruct()  行174	C++
 	test.exe!libtorrent::socket_type::~socket_type()  行289 + 0xf 字节	C++
 	test.exe!libtorrent::http_connection::~http_connection()  行101 + 0xf9 字节	C++
 	test.exe!libtorrent::http_connection::`scalar deleting destructor'()  + 0xf 字节	C++
 	test.exe!boost::checked_delete<libtorrent::http_connection>(libtorrent::http_connection * x=0x01cbf5f0)  行34 + 0x1c 字节	C++
 	test.exe!boost::detail::sp_counted_impl_p<libtorrent::http_connection>::dispose()  行78 + 0xc 字节	C++
 	test.exe!boost::detail::sp_counted_base::release()  行103 + 0xf 字节	C++
 	test.exe!boost::detail::shared_count::~shared_count()  行375	C++
 	test.exe!boost::shared_ptr<libtorrent::http_connection>::~shared_ptr<libtorrent::http_connection>()  + 0x12 字节	C++
 	test.exe!boost::_bi::value<boost::shared_ptr<libtorrent::http_connection> >::~value<boost::shared_ptr<libtorrent::http_connection> >()  + 0xf 字节	C++
 	test.exe!boost::_bi::storage1<boost::_bi::value<boost::shared_ptr<libtorrent::http_connection> > >::~storage1<boost::_bi::value<boost::shared_ptr<libtorrent::http_connection> > >()  + 0xf 字节	C++
 	test.exe!boost::_bi::storage2<boost::_bi::value<boost::shared_ptr<libtorrent::http_connection> >,boost::arg<1> >::~storage2<boost::_bi::value<boost::shared_ptr<libtorrent::http_connection> >,boost::arg<1> >()  + 0xf 字节	C++
 	test.exe!boost::_bi::storage3<boost::_bi::value<boost::shared_ptr<libtorrent::http_connection> >,boost::arg<1>,boost::arg<2> >::~storage3<boost::_bi::value<boost::shared_ptr<libtorrent::http_connection> >,boost::arg<1>,boost::arg<2> >()  + 0xf 字节	C++
 	test.exe!boost::_bi::list3<boost::_bi::value<boost::shared_ptr<libtorrent::http_connection> >,boost::arg<1>,boost::arg<2> >::~list3<boost::_bi::value<boost::shared_ptr<libtorrent::http_connection> >,boost::arg<1>,boost::arg<2> >()  + 0xf 字节	C++
 	test.exe!boost::_bi::bind_t<void,boost::_mfi::mf2<void,libtorrent::http_connection,boost::system::error_code const &,unsigned int>,boost::_bi::list3<boost::_bi::value<boost::shared_ptr<libtorrent::http_connection> >,boost::arg<1>,boost::arg<2> > >::~bind_t<void,boost::_mfi::mf2<void,libtorrent::http_connection,boost::system::error_code const &,unsigned int>,boost::_bi::list3<boost::_bi::value<boost::shared_ptr<libtorrent::http_connection> >,boost::arg<1>,boost::arg<2> > >()  + 0x12 字节	C++
 	test.exe!boost::asio::detail::binder2<boost::_bi::bind_t<void,boost::_mfi::mf2<void,libtorrent::http_connection,boost::system::error_code const &,unsigned int>,boost::_bi::list3<boost::_bi::value<boost::shared_ptr<libtorrent::http_connection> >,boost::arg<1>,boost::arg<2> > >,boost::system::error_code,unsigned int>::~binder2<boost::_bi::bind_t<void,boost::_mfi::mf2<void,libtorrent::http_connection,boost::system::error_code const &,unsigned int>,boost::_bi::list3<boost::_bi::value<boost::shared_ptr<libtorrent::http_connection> >,boost::arg<1>,boost::arg<2> > >,boost::system::error_code,unsigned int>()  + 0xf 字节	C++
 	test.exe!boost::asio::detail::win_iocp_socket_recv_op<boost::asio::mutable_buffers_1,boost::_bi::bind_t<void,boost::_mfi::mf2<void,libtorrent::http_connection,boost::system::error_code const &,unsigned int>,boost::_bi::list3<boost::_bi::value<boost::shared_ptr<libtorrent::http_connection> >,boost::arg<1>,boost::arg<2> > > >::do_complete(boost::asio::detail::win_iocp_io_service * owner=0x01207878, boost::asio::detail::win_iocp_operation * base=0x0120bad8, const boost::system::error_code & result_ec={...}, unsigned int bytes_transferred=0)  行100 + 0xc 字节	C++
 	test.exe!boost::asio::detail::win_iocp_operation::complete(boost::asio::detail::win_iocp_io_service & owner={...}, const boost::system::error_code & ec={...}, unsigned int bytes_transferred=0)  行45 + 0x18 字节	C++
 	test.exe!boost::asio::detail::win_iocp_io_service::do_one(bool block=true, boost::system::error_code & ec={...})  行405	C++
 	test.exe!boost::asio::detail::win_iocp_io_service::run(boost::system::error_code & ec={...})  行161 + 0xe 字节	C++
 	test.exe!boost::asio::io_service::run(boost::system::error_code & ec={...})  行67	C++
 	test.exe!libtorrent::aux::session_impl::main_thread()  行4904	C++
 	test.exe!boost::_mfi::mf0<void,libtorrent::aux::session_impl>::operator()(libtorrent::aux::session_impl * p=0x01206210)  行50	C++
 	test.exe!boost::_bi::list1<boost::_bi::value<libtorrent::aux::session_impl *> >::operator()<boost::_mfi::mf0<void,libtorrent::aux::session_impl>,boost::_bi::list0>(boost::_bi::type<void> __formal={...}, boost::_mfi::mf0<void,libtorrent::aux::session_impl> & f={...}, boost::_bi::list0 & a={...}, boost::_bi::type<void> __formal={...})  行254	C++
 	test.exe!boost::_bi::bind_t<void,boost::_mfi::mf0<void,libtorrent::aux::session_impl>,boost::_bi::list1<boost::_bi::value<libtorrent::aux::session_impl *> > >::operator()()  行21	C++
 	test.exe!boost::asio::detail::win_thread::func<boost::_bi::bind_t<void,boost::_mfi::mf0<void,libtorrent::aux::session_impl>,boost::_bi::list1<boost::_bi::value<libtorrent::aux::session_impl *> > > >::run()  行117	C++
 	test.exe!boost::asio::detail::win_thread_function(void * arg=0x01209868)  行118	C++
 	msvcr80d.dll!_callthreadstartex()  行348 + 0xf 字节	C
 	msvcr80d.dll!_threadstartex(void * ptd=0x01209b18)  行331	C
 	kernel32.dll!7c80b50b() 	
 	[下面的框架可能不正确和/或缺失，没有为 kernel32.dll 加载符号]	
 	kernel32.dll!7c8399f3()
