### ISSUE TITLE
wrong assertion?

### ISSUE THREAD

**Issue by okeatime** [arvidn/libtorrent#1454]
libtorrent branch: RC_1_1 eb5b0e9897b9ff4d08506e257e3201bb56fa923d
platform/architecture: Windows 64 bits
compiler and compiler version:  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24213.1 for x64

I think this assertion is wrong, isn't it?

```
diff --git a/src/storage.cpp b/src/storage.cpp
index 5ea984c..b579c57 100644
--- a/src/storage.cpp
+++ b/src/storage.cpp
@@ -912,7 +912,7 @@ namespace libtorrent
 				}
 				else
 				{
-					TORRENT_ASSERT(file_size == 0);
+					TORRENT_ASSERT(file_size != 0);
 				}
 			}
 #endif
```

**Comment by Falcosc** [comment]
I don't think that your  != 0 is better for an error case.

https://github.com/arvidn/libtorrent/blob/RC_1_1/src/storage.cpp#L909

```
error_code error;
stat_file(fs.file_path(i, m_save_path), &s, error);
if (s.file_size >= 0 && !error)
{
	TORRENT_ASSERT(s.file_size == file_size);
}
else
{
	TORRENT_ASSERT(file_size == 0);
}
```

I guess `TORRENT_ASSERT(file_size == 0);` does match better. That assert tell: if you have an error during stat_file, ignore it if the size was 0, but stop the program if a file with actual content throw an error.

**Comment by Falcosc** [comment]
@arvidn is it save to call stat_file() a second time or would it always fail?

**Comment by arvidn** [comment]
``file_size`` is initialized to 0 on line 869. After that point, it should either be set to a valid size when the file exists, or 0 if the file doesn't exist.
This assert makes sure it's correctly left at 0 when the file doesn't exist (or has some other error). Note that the whole block is wrapped in ``ifdef TORRENT_USE_INVARIANT_CHECKS``, so this is verifying that whatever the ``stat_cache`` returned, matches what's on disk.

In this case, if this assert fails for you, it appears the cache thinks the file is there, but ``stat()`` can't find it.

**Comment by okeatime** [comment]
Hmm. This assertion is triggered after hash check by qBittorent.

```
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.1.1.0-1229491

file: 'src\storage.cpp'
line: 915
function: libtorrent::default_storage::write_resume_data
expression: file_size == 0

stack:
 0: 00007FF9AB83B539 print_backtrace +233  c:\work\qb\libtorrent\src\assert.cpp:173
 1: 00000004E1CFBC80
 2: 0000000000000001
```

**Comment by Falcosc** [comment]
You need to check the error reason, because this assertiation is triggered by every write error and will be not included in the stacktrace.

**Comment by arvidn** [comment]
yes, running this in a debugger and looking at the ``error`` variable would be helpful. This assert was introduced to try to catch an error where sometimes resume data was written incorrectly. This is probably such case

**Comment by Seeker2** [comment]
Could 0-length files be legitimate for some torrents?
...where their filename conveys some information, such as username/password without needing any contents.

**Comment by arvidn** [comment]
yes, this assert is not firing because there's a zero-sized file in the torrent. it's because there's a discrepancy between the files on disk and the stat cache. I believe this has been fixed in RC_1_1

**Comment by arvidn** [comment]
I believe it was fixed here: https://github.com/arvidn/libtorrent/commit/132be5101ff48ecc2831e4171c4f2043b290c6f9
