### ISSUE TITLE
lt 1.0.10 undefined symbol: _ZN5boost4asio2ip10address_v4C1ERKNS_5arrayIhLm4EEE 

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1466]
Forwarding libtorrent 1.0.10 error: http://dev.deluge-torrent.org/ticket/2950

Seems something has broken python bindings in 1.0.10. I have not had a chance to test myself but thought I would open a ticket as users confirm 1.0.9 is fine.

```
ImportError: /usr/lib/python2.7/dist-packages/libtorrent.so: undefined symbol: _ZN5boost4asio2ip10address_v4C1ERKNS_5arrayIhLm4EEE 
```

**Comment by Falcosc** [comment]
I was not able to reproduce it. And now I know why:

kars85:
> Hi Cas,
> 
> I was able to build libtorrent from source from ​http://dev.deluge-torrent.org/wiki/Building/libtorrent now that I found where I was messing up on Step 5, option 1. I was Ctrl+C'ing out of that sudo checkinstall command after entering it and it wasn't building completely. After letting it finish by hitting Enter, libtorrent built successfully and was able to launch Deluge.
> 
> Thanks for the follow-up, nonetheless. Happy New Year!

I guess we could close the ticket.

**Comment by cas--** [comment]
That doesn't explain the other users experiencing the same issue as they mention only using packages. I think there is something going on but without more info it's hard to say and I'm not sure when I will get around to investigating this further so I'll just close this.
