### ISSUE TITLE
How to disable http pipeline ?

### ISSUE THREAD

**Issue by ximply** [arvidn/libtorrent#1470]
I want to disable http pipeline, just set urlseed_pipeline_size to 1 ?

**Comment by Falcosc** [comment]
Yes, that does it.

And you may want to limit the amount of requests per secound because Version 1.1.1 and lower does have a hardcoded 1MiB webseed request size limit. You would need to use head of master (1.2) or head of RC_1_1 (1.1.2) to create less and larger requests https://github.com/arvidn/libtorrent/blob/8adcbdd32bb9501863030df0beda14622934134e/include/libtorrent/settings_pack.hpp#L770

**Comment by ximply** [comment]
Well, thanks.

**Comment by ximply** [comment]
Webseed request size limit is necessary?  But I use 1.0.10 now, and 1.1.2 or 1.2 is compatible to 1.0.10?

**Comment by Falcosc** [comment]
If you care about pipeline then I guess you care about the amount of requests, too.
Keep in mind that webseed response handling is broken in 1.1.1 and lower which cause 1000's of re-requests. We fixed it in 1.1.2 and 1.2

https://github.com/arvidn/libtorrent/pull/1091

**Comment by Jobcrazy** [comment]
I've found an article which has solved this problem, it says that:

> For commercial CDN, it is another story, such as:
>
>1. Does not support long links, it is cut off every time the request is completed, you can think about how long it takes to download a few GB files for only a few 16K at a time.
>
>2. Limit the number of requests in the queue, and the number will be broken.
>
>3. The maximum number of requests to respond is in a long link. For example, nginx only responds to 100 by default.
>
>4. The server does not take a disconnect for the above situation, but stops responding, which causes libtorrent to wait.
>
>What the end user sees is that the download speed is not fast, or sometimes it is not.
>
>After the background information is finished, there are two problems in the end:
>
>1. Each request is too small.
>
>2. Request support for pipelining support on the server side

And the effective solution is:
>1. Change the strategy of taking the block, change it to the order, and take the block equivalent to >10MB each time, this will be many peer_request
>
>2. Before sending the http request, merge the obtained peer_request. Since it is obtained sequentially, basically, there is only one interval after the merge. If it is mapped to a file, it directly contains connection:close. If it is mapped to multiple files, The last one contains conection :close, the other is keepalive. Here is slightly dependent on pipelining, but the worst result is that after the first fragment is received, the server does not return subsequent data, we need to re-request the next link. Second and subsequent shards.
>
>3. After receiving these huge merged requests, decompose the received data according to the peer_request record, and call the original function once in a loop, before handing over the libtorrent's shard receiving logic.
>
>So, in the view of the http server, this client is requesting a 10MB block each time. The server's hard disk and cache no longer have to read several 16KB length requests.
>
>For libtorrent itself, it still works at the slice/block level, using standard seeds.
>
>For the overall transmission, more data is fetched each time with fewer requests. Although there are many tcp reconnections in the middle, the multi-connection feature compensates for the TCP reconnection time.
>
>For the end user, the file that originally took 30 minutes to download, downloaded in 2 minutes, no longer need to watch the speed is in a daze.

Could we use the same solution?

**Comment by arvidn** [comment]
libtorrent *does* make large requests from web seeds. @Jobcrazy do you have a reason to believe it isn't? like, measurements.
