### ISSUE TITLE
Stable version with mmap_cache support ?

### ISSUE THREAD

**Issue by c0mpute** [arvidn/libtorrent#1475]
Is there any stable release that has the mmap_cache feature enabled ? It's removed as of version 1.1.1, and the last version I found with mmap_cache support is 1.0.9, which doesn't work well with deluge and the ltconfig plugin (there seems to be a limit on the total active torrents regardless of the deluge setting, and the ltconfig plugin doesn't work with this version).

I'm also curious to know why this feature was removed in the first place ?

Thanks

```
libtorrent version: 1.1.1

platform/architecture: Linux x86_64

compiler and compiler version: gcc 5.4.0
```

**Comment by arvidn** [comment]
1.1.0 should have this feature as well, and it was not removed in 1.1.1. It has been *deprecated* in the 1.1.x branch though, which will have a new release soon (1.1.2). It should still be working though.

The main reason it was removed was that it added a lot of complexity for seemingly little gains (but perhaps you have some experience of it working really well). It also had no support for windows.

The feature has been removed entirely in the master branch, as I'm preparing for a full mmap-enabled disk subsystem (which still doesn't replace the mmap_cache feature, but it leaves it up to the kernel to manage the cache)

**Comment by c0mpute** [comment]
That's interesting. I did a grep -R -i mmap_cache * on the src directory of versions 1.1.1, 1.1.0, 1.0.10, and 1.0.9 and 1.1.0 was the only one which returned valid results (it was 1.1.0 after all, not 1.0.9, my bad). Maybe the function name was renamed ? In any case, it doesn't show up in the ltconfig plugin for deluge as an option that I can change, and for version 1.1.0 ltconfig doesn't work at all, so I assumed it wasn't present. Given your answer, I guess I will just wait for the 1.1.2 release, which should have this functionality working on its own, without me having to tweak the settings in ltconfig (if I understood you right). 

On another note, I actually had to revert from 1.1.1 to 1.0.7 (the latest version in the Ubuntu 16.04 repo). While 1.1.1 has more stable speeds (in the ~20MB/s range on a gigabit connection and external USB 3.0 HDD), it was severely limiting my speed to the point where downloading to an SSD would give me the same ~20MB/s speeds, while on 1.0.7 I'm getting 70MB/s without any problems. Are you aware of this issue ? I'm curious if I'm the only one experiencing this. Let me know if I should open another issue for this. 
Thanks

```
Deluge version: 1.3.13
libtorrent version: 1.1.1
Cache size (16 kB blocks): 65535
Cache expiry (seconds): 60
```

**Comment by arvidn** [comment]
please do open another issue for the performance problem. also provide as much information as possible about your specific setup. are you using uTP or TCP (or both)?, have you tried disabling mixed-mode? (i.e. blancing bandwidth between uTP and TCP). are you using the same disk cache size? have you tried setting the number of disk threads to 1 or 0 in libtorrent-1.1.1?

**Comment by c0mpute** [comment]
Thanks for the suggestion ! Disabling mixed-mode completely solved the problem for me. I opened a new issue detailing the problem and provided the fix for it, and closed the issue. Maybe it will help someone else too.
