### ISSUE TITLE
ECDSA Trackers refuse to function with Deluge 1.3.12 on 0.16.17

### ISSUE THREAD

**Issue by KyleSanderson** [arvidn/libtorrent#1477]
libtorrent version (or branch):
rb_libtorrent-0.16.17

platform/architecture:
amd64

compiler and compiler version:
Using built-in specs.
COLLECT_GCC=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.4/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/4.9.4/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-4.9.4/work/gcc-4.9.4/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.4 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.9.4 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.9.4/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.9.4/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/include/g++-v4 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/4.9.4/python --enable-languages=c,c++,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo 4.9.4 p1.0, pie-0.6.4' --enable-libstdcxx-time --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-multilib --with-multilib-list=m32,m64 --disable-altivec --disable-fixed-point --enable-targets=all --disable-libgcj --enable-libgomp --disable-libmudflap --disable-libssp --disable-libcilkrts --enable-vtable-verify --enable-libvtv --enable-lto --without-cloog --enable-libsanitizer
Thread model: posix
gcc version 4.9.4 (Gentoo 4.9.4 p1.0, pie-0.6.4)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

ECDSA trackers will refuse to connect with "TrackerName: Error". Changing them to http results in "Announce OK". rTorrent, OpenSSH/OpenSSL do not have this defect.

**Comment by arvidn** [comment]
this is quite minimalistic on information.
does your version of libcrypto support ecdsa?
where do you see the "TrackerName: Error" message?
did you look in wireshark for a better SSL error message?
are you confident the certificate the trackers you've tested with are signed by a trusted source?
if so, what CA certs would you expect to be trusted and where should libtorrent look for them?

**Comment by arvidn** [comment]
oh, also.. 0.16 is very very old. you should try *at least* 1.0, but probably 1.1

**Comment by KyleSanderson** [comment]
Thanks for getting back to me.

>does your version of libcrypto support ecdsa?
Yes.

> where do you see the "TrackerName: Error" message?
In Deluge, I wish it gave more information...

> did you look in wireshark for a better SSL error message?
Negative.

> are you confident the certificate the trackers you've tested with are signed by a trusted source?
Absolutely.

> if so, what CA certs would you expect to be trusted and where should libtorrent look for them?
/etc/ssl/certs

It's possible, if cURL is being used this is a regression in https://github.com/curl/curl/issues/1174 . I can't seem to get deluge to start again without hanging; which is terribly concerning: but this isn't your problem.

As an aside, do you know of any sane lightweight clients using this library? rTorrent (not rasterbar) easily handles 6k torrents but has _really_ bad frontends so I'm shopping...

**Comment by KyleSanderson** [comment]
Just confirmed it isn't cURL.

**Comment by arvidn** [comment]
in fact, I don't think libtorrent 0.16 supports ssl at all.

**Comment by KyleSanderson** [comment]
libtorrent 0.16.17 supports ssl.
