### ISSUE TITLE
How to debug low downloadspeed

### ISSUE THREAD

**Issue by Falcosc** [arvidn/libtorrent#1486]
libtorrent version (or branch):
RC_1_1 head
platform/architecture:
Linux
compiler and compiler version:
gcc 5
boost 1.62

After some hours the download speed is dropping to 5-20kb/s but I did set 100kb/s per torrent but even removing all throttling’s does not solve it. This bug is new after I did update boost, libtorrent and qbittorrent. Only a process restart solve the problem.
Currently I did only have webseed connections, after some hours when the error appear again I will test bittorrent download connections as well.

I would like to know how I could check the throttling calculation or if this is not the error maybe I need to check some general process information.

**Comment by ximply** [comment]
Any logs such as peer_banned? Try to set ban_web_seeds to false in session_settings.

**Comment by Falcosc** [comment]
There was 6 active torrents, each of them had a webseed. (4 different servers)

The problem appeared 3 times in a row without having a slow internet connection. But after an reboot it does not appear anymore. I do run a memory check now. I guess there was something broken after the updates or I have a memory issue. Because now everthing is fine.
