### ISSUE TITLE
About libtorrent memory release

### ISSUE THREAD

**Issue by dafanshu520** [arvidn/libtorrent#1488]
libtorrent version (or branch):  1.0.3

platform/architecture: linux X86

compiler and compiler version:gcc (GCC) 4.8.2

In my service, one file will hold a libtorrent::torrent_handle object, and use libtorrent api add_torrent to add it in the global object m_session, which is a  libtorrent::session object,.The libtorrent::torrent_handle object will be released after no one access its file in 20 mins, I will use remove_torrent to remove it from m_session, if the same file upload or download again in 20 mins, I will reset the torrent_handle object  expiration time to next 20 mins. The libtorrent::session object will never be released except my program exit.

To my confusion,a file transfer every 25 mins, the session will be idle after 20mins, my service will never happen memory leak.But different files transfer every 5 mins will happen memory leak, because the session will never be idle to free its memory ?

Looking forward to your reply!

**Comment by arvidn** [comment]
I don't understand what the question is

**Comment by Falcosc** [comment]
Even if the session will be never in idle the memory of removed torrents would be still released.
