### ISSUE TITLE
Can't upgrade from 1.0.10 to 1.1.1

### ISSUE THREAD

**Issue by banjopotato** [arvidn/libtorrent#1493]
**Please provide the following information**

libtorrent version (or branch): 1.0.10 (working), 1.1.1 (can't install)

platform/architecture: Ubuntu 14.04.5 LTS

compiler and compiler version: gcc 4.8.4

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I'm running Deluge 1.3.13 with libtorrent-rasterbar 1.0.10.

I'd like to upgrade to 1.1.1 but configure fails with 

`configure: error: Boost.Chrono library not found. Try using --with-boost-chrono=lib
`
When I try running it with the suggestion, it fails with this:

`configure: error: Could not link against boost_chrono-lib !
`
If I try this:
`sudo apt-get install build-essential checkinstall libboost-system-dev libboost-python-dev libssl-dev libgeoip-dev`

I get:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version.
libgeoip-dev is already the newest version.
checkinstall is already the newest version.
libssl-dev is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libboost-python-dev : Depends: libboost-python1.54-dev but it is not going to be installed
 libboost-system-dev : Depends: libboost-system1.54-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

`dpkg --get-selections | grep hold`

turns up nothing.

Any help resolving this much appreciated and I apologise in advance if this is really a noob question.

**Comment by Falcosc** [comment]
you have maybe a dependency version missmatch some ware, I did get this by using a mixed sources.list configuration.
For example this message appear if an old repo has a dependency which would downgrade your existing package.

 I don't know how to force the display of the package which is casing the issue. You can resolve the dependencies by hand until you get the causing message.

add "libboost-python1.54-dev libboost-system1.54-dev" to your line and repeat this until you get the causing dependencies version mismatch displayed. And then you could check why you have an missmatch.

**Comment by Falcosc** [comment]
But wait a second, libboost 1.54 is to old anyway. Please do an dist-upgrade to the lässt Ubuntu 16, then you geht libboost 1.55 or later.

**Comment by arvidn** [comment]
also, just to be clear: ``Try using --with-boost-chrono=lib`` *lib* is supposed to be the path to your installed boost chrono .so library.

**Comment by cas--** [comment]
For 1.1 the minimum version of boost should be 1.53 and as referenced in #928 you will need to also install `libboost-chrono-dev` and `libboost-atomic-dev`.

There is no issue with building 1.1 on launchpad for trusty: https://launchpad.net/~deluge-team/+archive/ubuntu/develop/

**Comment by banjopotato** [comment]
Thanks, folks. I took the blunderbuss approach and updated all this to 1.55:

`libboost1.55-doc libboost-atomic1.55-dev libboost-chrono1.55-dev libboost-context1.55-dev libboost-coroutine1.55-dev libboost-date-time1.55-dev libboost-exception1.55-dev libboost-filesystem1.55-dev libboost-graph1.55-dev libboost-graph-parallel1.55-dev libboost-iostreams1.55-dev libboost-locale1.55-dev libboost-log1.55-dev libboost-math1.55-dev libboost-mpi1.55-dev libboost-mpi-python1.55-dev libboost-program-options1.55-dev libboost-python1.55-dev libboost-random1.55-dev libboost-regex1.55-dev libboost-serialization1.55-dev libboost-signals1.55-dev libboost-system1.55-dev libboost-test1.55-dev libboost-thread1.55-dev libboost-timer1.55-dev libboost-wave1.55-dev libboost1.55-tools-dev libmpfrc++-dev libntl-dev
`
It did the trick. Sorry for the noob question but thanks for your help.
