### ISSUE TITLE
autotool.sh failed on Ubuntu 16.10

### ISSUE THREAD

**Issue by okeatime** [arvidn/libtorrent#1494]
libtorrent branch: RC_1_0
platform/architecture: Ubuntu 16.10
compiler and compiler version: g++ 6.2.0

Just a heads up.
https://github.com/arvidn/libtorrent/blob/RC_1_0/autotool.sh#L85
This line is confused by this output:
```
$ libtoolize --version | head -n 1
libtoolize (GNU libtool) 2.4.6 Debian-2.4.6-1
```

I had to do something link this:
```
-                            sed 's/^.*[        ]\([0-9.]*[a-z]*\).*$/\1/'`
+                            sed 's/^.*[        ]\([0-9.]\{1,\}[a-z]*\).*$/\1/'`
```

**Comment by arvidn** [comment]
I believe this should work too: https://github.com/arvidn/libtorrent/commit/518c077b7358e1fe6ade5f4c59c99ef3d372406d

thanks for the report!
