### ISSUE TITLE
python  libtorrent  session_settings have no listen_interfaces  outgoing_interfaces

### ISSUE THREAD

**Issue by NetSharkDon** [arvidn/libtorrent#1513]
HI 
my computer have two netcards,i want to use all of them to DOWNLOAD bt SEED bt 
i see
"_a comma-separated list of IP port-pairs. These are the listen ports that will be opened for accepting incoming uTP and TCP connections. It is possible to listen on multiple IPs and multiple ports. Binding to port 0 will make the operating system pick the port. The default is "0.0.0.0:6881", which binds to all interfaces on port 6881. if binding fails, the listen_failed_alert is posted, potentially more than once. Once/if binding the listen socket(s) succeed, listen_succeeded_alert is posted. Each port will attempt to open both a UDP and a TCP listen socket, to allow accepting uTP connections as well as TCP. If using the DHT, this will also make the DHT use the same UDP ports_"
but python  libtorrent  session_settings have no listen_interfaces  outgoing_interfaces
HELP ME

**Comment by NetSharkDon** [comment]
@Falcosc  Can you help me  
i have two netcards 
192.168.1.3
172.27.35.200
how can i use all of them with libtorrent python

**Comment by Falcosc** [comment]
You need to put the settings from the settings reference into the settings map like the user agent.
http://libtorrent.org/reference-Settings.html

If you need more examples you could use test.py

**Comment by NetSharkDon** [comment]
i am not good at C++ ,Can you tell me  how " put the settings from the settings reference into the settings map " ,where  is  the settings map

**Comment by Falcosc** [comment]
You have to do it in python

https://github.com/Falcosc/libtorrent/blob/89ed3f80b0f1fb843a5c249dd149de80408fa57a/bindings/python/client.py#L196

**Comment by NetSharkDon** [comment]
Thank You Very  Very Very Very Much
_settings={'listen_interfaces':'192.168.235.129:6881,192.168.235.132:6881',,'outgoing_interfaces':'ens38,ens33'}
ses = lt.session(settings)_
it works！
_tcp        0      0 192.168.235.132:6881    0.0.0.0:*               LISTEN     
tcp        0      0 192.168.235.129:6881    0.0.0.0:*               LISTEN     
tcp        0      0 192.168.235.132:45553   1.36.10.235:16881       ESTABLISHED
tcp        0      0 192.168.235.132:46435   27.8.153.32:14545       ESTABLISHED
tcp        0      0 192.168.235.132:42317   182.121.10.179:10405    ESTABLISHED
tcp        0     33 192.168.235.129:40269   49.114.103.76:9337      ESTABLISHED
tcp        0      0 192.168.235.132:37357   153.34.61.78:10440      ESTABLISHED
udp        0      0 192.168.235.129:53843   0.0.0.0:*                          
udp        0      0 192.168.235.132:6771    0.0.0.0:*                          
udp        0      0 192.168.235.129:6771    0.0.0.0:*                          
**udp        0      0 192.168.235.129:6881    0.0.0.0:***                          
udp        0      0 192.168.235.132:48554   0.0.0.0:*_ 
but why only   udp        0      0 192.168.235.129:6881      NOT HAVE  udp        0      0 192.168.235.132:6881

**Comment by NetSharkDon** [comment]
but why only udp 0 0 192.168.235.129:6881 NOT HAVE udp 0 0 192.168.235.132:6881

**Comment by NetSharkDon** [comment]
@Falcosc  Something  Wrong？

**Comment by Falcosc** [comment]
No, nothing is wrong. You could build it with logging and look for UDP errors

https://github.com/arvidn/libtorrent/blob/4ebc344e482d2f28627ca2661486dda7d40e906d/src/session_impl.cpp#L1645

**Comment by arvidn** [comment]
iirc, RC_1_1 does not have multi-home support for UDP. master does though.

**Comment by ssiloti** [comment]
master does not have multi-home UDP support yet. I'm still working on it.

**Comment by arvidn** [comment]
oh, right. it doesn't support multi-homed DHT, but I believe it can do uTP peer connections.

**Comment by ssiloti** [comment]
Not really. Right now all UDP packets are sent using the first socket with the right address family. So while we can receive an incoming SYN on a secondary socket, the ACK will still go out the primary so at best it will have the wrong source IP and be ignored.

**Comment by Falcosc** [comment]
@ssiloti could you give a reference too the ticket, branch or pullrequest to track it?

**Comment by arvidn** [comment]
@Falcosc https://sourceforge.net/p/libtorrent/mailman/message/35489298/
