### ISSUE TITLE
peer_class in python 

### ISSUE THREAD

**Issue by NetSharkDon** [arvidn/libtorrent#1517]
HELLO
There Are Some Evil Bt client ,(i.e Xunlei,It download ,But dont upload)
I want to use peer_class::set_upload_limit in PYTHON  , but How to Use？

**Comment by Falcosc** [comment]
You have only access the settings http://libtorrent.org/reference-Settings.html and some interfaces and some public members of libtorrent. With python you can list the members of libtorrent.

**Comment by arvidn** [comment]
it's possible the peer_class feature hasn't been exposed to python. patches are welcome!
however, peer_class cannot distinguish between client versions, just IPs (and a few other things)

**Comment by NetSharkDon** [comment]
Qbittorrent 3.1.92 with libtorrent 0.16.16 
it calls _"set_peer_upload_limit"_ to "set_upload_limit"  a specific  peer ,and I think it is very GOOD!

**Comment by NetSharkDon** [comment]
but the new version doesnt support it

**Comment by NetSharkDon** [comment]
if  peer_class can distinguish between client versions ,it is very GOOD , that I can _" set_upload_limit"_ specific Bt client (i.e  Xunlei,BitTorrent)

**Comment by Falcosc** [comment]
@arvidn wouldn't this cause the mentioned deadlock issue https://sourceforge.net/p/libtorrent/mailman/message/29959727/ ?

**Comment by arvidn** [comment]
@Falcosc no. ``peer_class`` refers to a specific feature in libtorrent, not the C++ class representing a peer connection.
