### ISSUE TITLE
lt 1.1 fingerprint overwritten by session.load_state

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1519]
With the change to `settings_pack` there is a small issue with setting the session fingerprint followed by loading the session state. It will overwrite the fingerprint used to create the session which did occur in lt versions <= 1.0

```
session = lt.session(lt.fingerprint("DE", *[1, 3, 13, 0]), flags=0)
print(str(lt.client_fingerprint(session.id())))
print(session.get_settings()['peer_fingerprint'])

session.load_state(saved.settings)
print(str(lt.client_fingerprint(self.session.id())))
print(self.session.get_settings()['peer_fingerprint'])

>>> -DE13D0-
>>> -DE13D0-

>>> None
>>> -DE20000-
```

**Comment by cas--** [comment]
I think the fix is that if `peer_id` is set then do not overwrite with `peer_fingerprint` when using `load_state`, this would mirror the behaviour for old lt versions.

**Comment by arvidn** [comment]
thanks! yes, I will fix this. I believe my long-term plan is to remove ``load_state`` in favor of loading everything up-front and passing into the session. that way any setting can be explicitly overridden

**Comment by arvidn** [comment]
actually.. what exactly is the scenario? you save state with lt 1.0 and then you load it with 1.1 and the fingerprint gets loaded from the file?
as far as I can tell, 1.0 should not save the peer-id nor fingerprint in the state. and 1.1 should not update it when loading a state file where that field is not present.

**Comment by cas--** [comment]
1.1 will then put the fingerprint in save state and the next load state contains fingerprint

**Comment by arvidn** [comment]
and you propose to never load the fingerprint from the state, or only load it in certain cases?
It's not obvious to me that it's possible to distinguish the case where it's already set. I suppose if it's an empty string it could be considered not set.

apart from the backwards compatibility issue, do you think it makes sense at all to save and restore the fingerprint from settings?

**Comment by cas--** [comment]
> apart from the backwards compatibility issue, do you think it makes sense at all to save and restore the fingerprint from settings?

No probably not. Currently using non-deprecated code I have to extract the settings_pack from session.state and update versions before passing it to the session constructor so much simpler if it didn't. Oh and we don't want to make it too easy for end-users to modify client version ;) 

That would also apply to `user_agent`.

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/1538

**Comment by arvidn** [comment]
merged
