### ISSUE TITLE
Add AM_MAINTAINER_MODE([enable]) to configure.ac

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1520]
The maintainer mode is enabled by default without the macro. However debian build system passes  `--disable-maintainer-mode` which cannot be acted upon because the macro is missing resulting in this error:
```
configure: WARNING: unrecognized options: --disable-maintainer-mode
```

Adding the following macro with parameter ensures maintainer mode is still enabled by default but can be disabled if requested.
```
AM_MAINTAINER_MODE([enable]) 
```

References: 
https://autotools.io/automake/maintainer.html
https://blogs.gnome.org/desrt/2011/09/08/am_maintainer_mode-is-not-cool/

**Comment by cas--** [comment]
Could this go in 1.1.2 milestone instead?

**Comment by arvidn** [comment]
sure. I was planning on making one last 1.0.x release though, and it seems like a simple patch

**Comment by cas--** [comment]
Oops not applied to 1.0.x yet
