### ISSUE TITLE
python  Can Have Two Session

### ISSUE THREAD

**Issue by NetSharkDon** [arvidn/libtorrent#1522]
_ses1 = lt.session()#settings)
ses1.listen_on(6881,6891,interface='192.168.235.129')
e = lt.bdecode(open("aa.torrent", 'rb').read())
info = lt.torrent_info(e)
params = { 'save_path': '.', 'storage_mode': lt.storage_mode_t.storage_mode_sparse, 'ti': info }
h = ses1.add_torrent(params)
ses2 = lt.session()#settings)
ses2.listen_on(6882,6891,interface='192.168.235.132')
e1 = lt.bdecode(open("bb.torrent", 'rb').read())
info1 = lt.torrent_info(e1)
params = { 'save_path': '.', 'storage_mode': lt.storage_mode_t.storage_mode_sparse, 'ti': info1 }
h1 = ses2.add_torrent(params)
while (True):
        s = h.status()

        state_str = ['queued', 'checking', 'downloading metadata', \
                'downloading', 'finished', 'seeding', 'allocating']
        print 'SESS1 %.2f%% complete (down: %.1f kb/s up: %.1f kB/s peers: %d) %s' % \
                (s.progress * 100, s.download_rate / 1000, s.upload_rate / 1000, \
                s.num_peers, state_str[s.state])
        s = h1.status()
        print 'SESS2 %.2f%% complete (down: %.1f kb/s up: %.1f kB/s peers: %d) %s' % \
                (s.progress * 100, s.download_rate / 1000, s.upload_rate / 1000, \
                s.num_peers, state_str[s.state])
        time.sleep(1)_
**SESS2 0.00% complete (down: 0.0 kb/s up: 0.0 kB/s peers: 0) downloading
SESS1 32.67% complete (down: 630.0 kb/s up: 27.0 kB/s peers: 110) downloading
SESS2 0.00% complete (down: 0.0 kb/s up: 0.0 kB/s peers: 0) downloading
SESS1 32.75% complete (down: 587.0 kb/s up: 24.0 kB/s peers: 109) downloading
SESS2 0.00% complete (down: 0.0 kb/s up: 0.0 kB/s peers: 0) downloading
SESS1 32.83% complete (down: 582.0 kb/s up: 24.0 kB/s peers: 107) downloading
SESS2 0.00% complete (down: 0.0 kb/s up: 0.0 kB/s peers: 0) downloading
SESS1 33.07% complete (down: 565.0 kb/s up: 24.0 kB/s peers: 109) downloading
SESS2 0.00% complete (down: 0.0 kb/s up: 0.0 kB/s peers: 0) downloading
SESS1 33.15% complete (down: 575.0 kb/s up: 26.0 kB/s peers: 108) downl**

it Seems that the second Session doesnt work ,I dont Know Why

**Comment by NetSharkDon** [comment]
@arvidn

**Comment by arvidn** [comment]
try with a single session bound to "192.168.235.132" and see if that works.
also, you may want to make sure they don't have overlapping ports. you really should be printing alerts too, there may be errors there

**Comment by NetSharkDon** [comment]
THANKS
