### ISSUE TITLE
Assertions from http seeding

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#1525]
Assertions from http seeding: http://pastebin.com/qxBNTnuh

Offending torrent: https://download.gimp.org/pub/gimp/v2.8/windows/gimp-2.8.18-setup.exe.torrent

Lots of unsupported url's and unavailable locations, not sure if its the number of errors generated but with url_seed_alert cout can't keep up and crashes.

**Comment by Falcosc** [comment]
I will create a pull request

**Comment by Falcosc** [comment]
https://github.com/arvidn/libtorrent/pull/1526

**Comment by Falcosc** [comment]
@Col-blimp 
plese could you try
`libtorrent/examples/client_test gimp-2.8.18-setup.exe.torrent`
based on the pullrequest to check how it works with default settings?

If this work it would be nice if you could adjust the client_test settings pack until you get your error again to help reproducing it. Thanks

**Comment by Falcosc** [comment]
Pull request is now merged, ticket could be closed

**Comment by arvidn** [comment]
@Col-blimp thanks for the report!
