### ISSUE TITLE
python binding session_stats_metrics returns list of objects

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1532]
The method `lt.session_stats_metrics()` returns a list of objects:
```
[<libtorrent.stats_metric object at 0xb6fbbf2c>,
 <libtorrent.stats_metric object at 0xb6fbbf6c>,
 <libtorrent.stats_metric object at 0xb6fbbfac>,
...
]
```

I think needs converting to a dict or perhaps would an enum work here?

**Comment by arvidn** [comment]
the ``stats_metric`` type is supposed to be bound. did you try accessing its members?

**Comment by cas--** [comment]
Yes but you need iterate the list to access each stats_metrics objects with
name, type and index. It's not easy to lookup via index or name so I'd
probably convert this to a dict in Python straightaway.

On 12 Jan 2017 22:47, "Arvid Norberg" <notifications@github.com> wrote:

the stats_metric type is supposed to be bound. did you try accessing its
members?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/arvidn/libtorrent/issues/1532#issuecomment-272308531>,
or mute the thread

**Comment by arvidn** [comment]
if you want to lookup by name, you can call ``find_metric_idx()`` which takes a name

**Comment by arvidn** [comment]
looking up by index is still not trivial though. I suppose ideally the function would return a bimap, indexed by "name" and "index"

**Comment by cas--** [comment]
Yeah I thought `find_metric_idx` was useful until I realised the list index doesn't match the object index :)

If it can be just the index that's fine, name as well would be a bonus :P

**Comment by arvidn** [comment]
the intention for ``find_metric_idx()`` is to know where to look in the session_stats alert array

**Comment by cas--** [comment]
Ah ok, so it's not really needed for python as session_stats alert is a dict of `key:value`.

Perhaps `value_index` is not needs and only a dict of `name:type` is required?

**Comment by cas--** [comment]
Also is it documented for `type` that `0` is counter and `1` is gauge?

**Comment by arvidn** [comment]
does this looks reasonable? https://github.com/arvidn/libtorrent/pull/1538

**Comment by arvidn** [comment]
doh. wrong thread...

**Comment by arvidn** [comment]
fixed in RC_1_1 now. thanks!

**Comment by cas--** [comment]
What the original issue with session_stats_metric?

**Comment by arvidn** [comment]
In some sense, the python API probably shouldn't diverge too much from the C++ one. But I guess I've already made the stats alert diverge. Perhaps it would make sense if ``session_stats_metrics`` simply returned a ``name`` -> ``type`` dictionary. The actual indices are already abstracted away by the bindings.

**Comment by cas--** [comment]
> In some sense, the python API probably shouldn't diverge too much from the C++ one.
Yeah I agree with that
