### ISSUE TITLE
Docs don't list gauge metric type in Session Statistics section

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1533]
There are no metrics listed as gauges in http://libtorrent.org/manual-ref.html#session-statistics

https://github.com/arvidn/libtorrent/blob/09cbd0a51d5e6713f652bbe956f55b652b4cd1f9/include/libtorrent/performance_counters.hpp#L319

I think there might also be some duplication or paragraphs out-of-sync with tables.

**Comment by arvidn** [comment]
there appears to be a bug in the python script extracting this from the source code

**Comment by arvidn** [comment]
fixed in RC_1_1
