### ISSUE TITLE
force_tracker_request ERROR

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#1535]
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.2.0.0-62cdec8

#: 1
file: 'src\torrent.cpp'
line: 3264
function: libtorrent::torrent::force_tracker_request
expression: tracker_idx >= 0 && tracker_idx < int(m_trackers.size())

stack:
 0: 00007FF7C1C5EE67 print_backtrace +375 

------

Happens with internal Libtorrent tracker scraping/updating.

**Comment by arvidn** [comment]
This is a precondition violation. the call to ``torrent_handle::force_tracker_request()`` passed in an invalid tracker index. this is an assert to help you (the user) debug this issue. In release builds it will simply return without doing anything

**Comment by arvidn** [comment]
improved here: https://github.com/arvidn/libtorrent/pull/1536

**Comment by arvidn** [comment]
wait.. you're saying libtorrent calls this function internally?

**Comment by arvidn** [comment]
I don't see any such calls:

```
$ git grep force_tracker_request
include/libtorrent/torrent.hpp:         void force_tracker_request(time_point, int tracker_idx);
src/torrent.cpp:        void torrent::force_tracker_request(time_point const t, int const tracker_idx)
src/torrent_handle.cpp:         async_call(&torrent::force_tracker_request, aux::time_now()
src/torrent_handle.cpp:         async_call(&torrent::force_tracker_request, aux::time_now() + seconds(s), idx);
```
