### ISSUE TITLE
Overflow session stats alert values with 32-bit python bindings

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1542]
Something is not right with the values returned by session stats alert, could be a 32-bit conversion issue...

```
log.debug(alert.values)
{'peer.num_peers_end_game': 8246211243144146287L, 'utp.utp_timeout': 464996691699040263L, 
'dht.dht_put_out': 8935146468851844191L, 'ses.num_incoming_have_none': 8387231306020646511L,
 'ses.num_queued_download_torrents': 7954892334467216494L, 'utp.utp_payload_pkts_out': 676665895709573132L, 
'utp.utp_redundant_pkts_in': 108930863257026571L, 'dht.dht_announce_peer_out': 8935145459534529396L, 'disk.pinned_blocks': 0L,
...}
```

**Comment by cas--** [comment]
Yep it looks fine on 64-bit

**Comment by Falcosc** [comment]
@arvidn Idid we already have a trick which is forcing the bit-less type definition into a predictable definition?

**Comment by arvidn** [comment]
I wouldn't expect those numbers to actually overflow 32 bits. I think there may be something else going on. Some could though, so it might make sense for the binding to clamp to 32 bits on such builds.

Does python 32-bit mean that the whole binary, including the binding, are built for 32 bit architecture? i.e. ``sizeof(void*) == 4``? If so, that could be used to know whether to clamp or not

**Comment by cas--** [comment]
I wasn't sure how to describe those numbers and overflow seemed close enough :P

Seems so:
```
>>> import ctypes
... print ctypes.sizeof(ctypes.c_voidp)
4
```

**Comment by cas--** [comment]
@Falcosc A simple test:
```
import libtorrent as lt
sess = lt.session()

sess.post_session_stats()
while(1):
    alerts = sess.pop_alerts()
    if alerts:
        for alert in alerts:
            if type(alert).__name__ == 'session_stats_alert':
                print alert.values
```

**Comment by Falcosc** [comment]
Overflow already at session start? Very nice. Now we need only a 32bit environment.

Thanks

**Comment by cas--** [comment]
Closing, cannot replicate on any other OS!
