### ISSUE TITLE
master branch python bindings not building due to missing c++11 flag

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1543]
This is on `master` branch a31ba79

The following from [build logs](https://launchpadlibrarian.net/302365971/buildlog_ubuntu-xenial-i386.libtorrent-rasterbar_1.2.0dev8739+a31ba79+201701131732~ubuntu16.04.1_BUILDING.txt.gz) when trying to build the python bindings:
```
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
```

The rest of libtorrent is building fine and due can see `-std=c++11` and `-DHAVE_CXX11=1` are in the compiler arguments.

**Comment by Falcosc** [comment]
I can't reproduce it with my gcc version because c++11 is already enabled by default. I try to guess something but you may need to apply and test some of my patches.

**Comment by cas--** [comment]
Looks like the `CXXFLAGS` is somehow not setup correctly in the python bindings `Makefile`:

```
CXX = g++ -std=c++11
CXXCPP = g++ -E -std=c++11
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2 -ftemplate-depth=128 -Wno-format-zero-length -fvisibility=hidden -fvisibility-inlines-hidden
```

**Comment by Falcosc** [comment]
Did you try the patch? I did a hardcoded CXXFLAGS change which I did not see in your config.report.txt
But never mind I will change it to CXX anyway because AX_CXX_COMPILE_STDCXX_11 does put it into CXX if your compiler need this option.

**Comment by cas--** [comment]
The patch is a hack and just guessing so no. Obviously if I manually modify the compile flags it works but I think it's `CFLAGS` that needs settings for C++11

**Comment by Falcosc** [comment]
I guess CXX and CXXFLAGS are enoght, python did just not see them.

**Comment by cas--** [comment]
This explains the whole problem: https://github.com/arvidn/libtorrent/issues/870

The fix only was for using `setup.py`...

**Comment by cas--** [comment]
@arvidn does this look ok to add to `configure.ac`

```
AX_CHECK_COMPILE_FLAG([-std=c++11], [
  CPPFLAGS+=" -std=c++11"
], [
  echo "CPP compiler cannot compile C11 code"
  exit -1
])
```

**Comment by Falcosc** [comment]
autotools are already correlty configured because the flags are set and gcc does use them. And you even did confirm it because your non python builds are successfull.

But for the python builds we call python setup.py build, and inside of setup.py we lose the make scope and nothing what you define for autotools would go into this script.
That means we have to pass needed environments to python. We can use export or we define them for the python call.

**Comment by cas--** [comment]
I know exactly what I am doing but thank for your input.

**Comment by arvidn** [comment]
there is a mechanism to pass build options into the python build already, via ``bindings/python/compile_flags.in``. This file has its macros substituted within the autoconf context and should have access to what turns into the ``-std=c++11`` flag

**Comment by cas--** [comment]
That is what I was referring to by modifying `CPPFLAGS`. It certainly works just wanted to be sure that is close to the correct method of fixing this issue.

**Comment by Falcosc** [comment]
Nice
Then I gett it.

Still the questions which solution is more correct
Should we extend compile_flags.in with `CXX` pass
or should we extend `CPPFLAGS`
I don't know the differences of all the compiler option variables to decide what is more correct.

**Comment by arvidn** [comment]
yeah, I feel like it would be more correct to use the output from ``AX_CXX_COMPILE_STDCXX``.. I'm just not sure exactly how that works. it looks like it adds stuff to ``CXX``. I'm not sure whether it makes sense to just add all of ``CXX`` to ``CPPFLAGS`` or somehow extract just the C++11 flag.

**Comment by Falcosc** [comment]
I would just pass CXX because it would not hurt.
I would like to add CXXFLAGS as well for example to get debugging symbols flag for python bindings

**Comment by Falcosc** [comment]
CXX can't be pass via distutils extra_compile_args, It does only work as environment var. Export or commondline or load a file as environment var or we don't use CXX.
I did update my branch.

**Comment by cas--** [comment]
I think supplying `CXX` to `setup.py` via a file is the correct course. So we always set `CC` in setup.py like so: `os.environ['CC'] = (CXX from file)`. This also ensures that we are instructing the python build to use the compiler selected by configure.

Note: There is a `--compiler` option for setup.py but can't see a way of specifying it in the code so setting os.environ is next best thing.

Also should add `CXXFLAGS` to `compile_flags.in`. Should `CPPFLAGS` be in there at all?

**Comment by cas--** [comment]
Alternatively add `CXXFLAGS` to `compiler_flags.in` and put the following to `configure.ac`

```diff
 AX_CXX_COMPILE_STDCXX_11([noext], [mandatory])
+AS_IF([test "${CXX#*std}" != "$CXX"],
+  [CXXFLAGS="$CXXFLAGS $(echo "$CXX" | cut -d ' ' -f 2-)"])
```

@arvidn any thoughts? :D

**Comment by arvidn** [comment]
I would imagine there are other ways to get at the output from that macro, no?

**Comment by cas--** [comment]
I was avoiding modifying the macro if that's what you mean?

**Comment by arvidn** [comment]
in some cases ``AX_CXX_COMPILE_STDCXX_11([noext], [mandatory])`` may add more than 1 argument to ``CXX``. Is there a way to make a copy of ``CXX`` before the macro, and then take the difference?

**Comment by cas--** [comment]
That's why the cut include everything from the space after the compiler cmd onwards.

**Comment by arvidn** [comment]
I see. what about the condition? that seems a bit suspicious to me. couldn't this be done unconditionally?

**Comment by cas--** [comment]
I don't see why not. :)

The condition tests for any string `std` in `CXX` string.

**Comment by cas--** [comment]
Unless modify the macro to add it to CXXFLAGS and not CXX? Because that is the root of this issue...

**Comment by arvidn** [comment]
my guess is that these flags are compiler specific, whereas CXXFLAGS might not be (say, include paths). Now, they're all compiler specific regardless. msvc would not like either.

But to some degree it feels a bit weird to assume that python's distutils will in fact invoke the same compiler as the one configured by autoconf. By passing this flag along, that is the assumption we're making.

I can't think of a more reasonable way of doing it in the short term though

**Comment by arvidn** [comment]
but it's probably best not to modify the macro, to ease updates

**Comment by cas--** [comment]
Ah that's a good point about other compilers... I'll put together a PR for cutting and pasting flags

**Comment by cas--** [comment]
Thanks, building fine now: https://code.launchpad.net/~calumlind/+archive/ubuntu/libtorrent-master-daily
