### ISSUE TITLE
How to debug SIGSEGV?

### ISSUE THREAD

**Issue by Falcosc** [arvidn/libtorrent#1547]
libtorrent version (or branch): RC_1_1 Head

platform/architecture: debian 64bit

compiler and compiler version: gcc 6

If I save more then 1000 fastresume filesat once, I got a SIGSEGV.
How could I work with this stacktrace? I don't know where these numbers point and how to work with them to figure out where it crashes.

```
stack trace:
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x1197ca  [0x7f3a0c24d7ca]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x18bf2d  [0x7f3a0c2bff2d]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x1557cd  [0x7f3a0c2897cd]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x1307ac  [0x7f3a0c2647ac]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x9bc6a  [0x7f3a0c1cfc6a]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x9bda3  [0x7f3a0c1cfda3]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x1301aa  [0x7f3a0c2641aa]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0xa5e5f  [0x7f3a0c1d9e5f]
  /lib/x86_64-linux-gnu/libpthread.so.0 : ()+0x7464  [0x7f3a0b044464]
  /lib/x86_64-linux-gnu/libc.so.6 : clone()+0x5f  [0x7f3a0a4eb9df]

```

Error is easy to reproduce.

**Comment by arvidn** [comment]
you could either user ``addr2line`` or you could reproduce it with a binary which includes debug symbols.
