### ISSUE TITLE
iface.name == name always false

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#1567]
https://github.com/arvidn/libtorrent/blob/df6cb6a48d276c1290b981da6e28d355d7c5c69d/src/enum_net.cpp#L1117

Compare char[64] and const char*

Bug?

**Comment by arvidn** [comment]
that does look like a bug, but it's also in an unused function. I'll remove it: https://github.com/arvidn/libtorrent/pull/1569
