### ISSUE TITLE
rb_libtorrent-1.0.6 fails to build with USE=examples (Gentoo linux)

### ISSUE THREAD

**Issue by Gentookees** [arvidn/libtorrent#157]
1.0.5 also failed to build, see https://bugs.gentoo.org/show_bug.cgi?id=550252
But 1.0.6 still fails to build with USE=examples
Build log: http://pastebin.com/mmS8nWRk

Using gentoo linux, 
gcc x86_64-pc-linux-gnu-4.9.3

**Comment by arvidn** [comment]
I assume USE=examples means to build tools/parse_hash_fails.cpp. I'll just remove that file. It's using functions internal to libtorrent

**Comment by arvidn** [comment]
fixed in RC_1_0 branch.

**Comment by Gentookees** [comment]
Sorry. I don't know anything about code, but I think examples builds just... examples that are not really needed for using the library, but I think the configure script uses it to prepare the makefile and 'use=examples' is the default setting. You need some gentoo professor to explain :-)
Thanks for fixing it!
