### ISSUE TITLE
Remove, or make optional, 1MB packet limit

### ISSUE THREAD

**Issue by bedeho** [arvidn/libtorrent#158]
The following code imposes a hard 1MB limit on incoming messages. It is a problem for a plugin I am working on, which requires big messages.

In a previous post on the mailing list @arvidn said that it was not necessary to strictly enforce, and was open for removal.
(http://sourceforge.net/p/libtorrent/mailman/libtorrent-discuss/?viewmonth=201504&viewday=28)

https://github.com/arvidn/libtorrent/blob/4fd56fd220cec486be516277682db9f91188ad1e/src/bt_peer_connection.cpp#L3514

// don't accept packets larger than 1 MB
if (packet_size > 1024*1024 || packet_size < 0)
{
 // packet too large
received_bytes(0, bytes_transferred);
disconnect(errors::packet_too_large, op_bittorrent, 2);
return;
}

**Comment by arvidn** [comment]
The things I would like to make sure before removing it are:

1. that there's no allocation happening based on the message size
2. that unknown messages abort the connection (i.e. the one or two bytes following the length prefix)
3. that all known messages (including extensions) _do_ have an upper bound on what message sizes they allow (or a check for an exact size)

ideally there would be some spot checking in a test as well.

**Comment by bedeho** [comment]
Sounds very reasonable, but how can you enforce 2. and 3. in libtorrent, given that libtorrent will not be aware of messages and corresponding lengths used by plugins?

**Comment by arvidn** [comment]
I just meant the plugin that ships with it.

**Comment by bedeho** [comment]
Ah, makes sense, will keep that in mind, thank you!

**Comment by Falcosc** [comment]
@arvidn why did nobody else complain about this limit? And why did we not hit this limit?
I would like to remove it if it makes no sense. But I wouldn't if this is something related to the bittorrent protocoll description.

**Comment by arvidn** [comment]
nobody else hit this problem because there are no bittorrent messages that are large enough to trigger it. It only happens if you write a plugin and send a message larger than 1 MiB.

It's a sanity check to make sure it's not possible to trick libtorrent into allocating unreasonable amounts of memory by sending corrupt data.

**Comment by Falcosc** [comment]
Is it really only for messages? Then I did not understand the code or the protocol. Or did you mean that only messages could exceed 1MiB because other protocol communication are limited by design. 
I did guess that all bt connection data goes through `on_receive_impl() `  `if (m_state == read_packet_size)`

**Comment by bedeho** [comment]
We still badly need this, having to keep a patched version of libtorrent to avoid the limit.

The ideal solution for us would allow
a) updating the constraint during runtime.
b) having an individual limit per torrent, not just session wide, as different torrents impose different max message sizes.

To do b), one cannot use the settings pack, so perhaps it could be set through the torrent_handle.
If this is not acceptable, it would still be better to at least get a), using the session settings pack.

**Comment by Falcosc** [comment]
Ok, I can do it, what about this description:

```
Set the allowed incoming bt message packet length. This is used as a sanity check to make sure it’s not possible to trick libtorrent into allocating unreasonable amounts of memory by sending corrupt data. Expected messages are quite small even piece messages are only 16KiB and some clients use 128KiB as Upper limit. But there is one exception which we want to cover: `BEP 14`_ Extension Protocol. To cover the most use-cases of custom extension messages we select 1MiB as default.
max_allowed_message_length = 1024 * 1024;
```

**Comment by bedeho** [comment]
That should read 'BEP10'.

**Comment by Falcosc** [comment]
Here it is:
https://github.com/arvidn/libtorrent/pull/1474

**Comment by the8472** [comment]
Note that message sizes have an impact on latency. bittorrent is not a stream-multiplexed protocol like http2 or sctp. so large messages on a congested or low-bandwidth link will upset any time-based statemachine, e.g. choking algorithms.

**Comment by arvidn** [comment]
yes, the utility of sending extension messages >1 MiB seems questionable. But I guess it's not *my* problem...
