### ISSUE TITLE
is there any way to check if a piece is written to disk completely?

### ISSUE THREAD

**Issue by mianharisali** [arvidn/libtorrent#1581]

**Comment by cas--** [comment]
You can use `torrent_handle.flush_cache` to ensure this happens. And you can query `session.get_cache_info(torrent_handle)`.

**Comment by cas--** [comment]
@arvidn I noticed that cache_status struct is entirely deprecated apart from `pieces` so what does that mean for `get_cache_info`?

**Comment by arvidn** [comment]
most of the counters from that struct have been moved to the ``session_stats`` counters. In the long run I would like to deprecate the ``get_cache_info`` call as well, but probably not until the disk cache gets removed.

**Comment by mianharisali** [comment]
@cas-- what if cache size is zero in the session settings? and we call flush cache.
i think there should be an alert that shows a piece is written to the disk.
