### ISSUE TITLE
udp trackers not functioning

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#1594]
UDP trackers on my setup fail to connect (http work fine) , from `tracker_error_alert` they all fail with `status_code` **-1**.

From the docs it says `tracker_completion_timeout` is 30 although it goes on to say the default is 60 but even changing to 60 still fails to connect.

What other settings are there for udp trackers or what are the debugging steps?

**Comment by arvidn** [comment]
what other error code and error messages to get get from the ``tracker_failed_alert``?
are you going through a proxy? (that's configured in libtorrent)

**Comment by Col-blimp** [comment]
`error_message()` is "" and `error_code` is 36 that I believe is `timed_out`, not using any proxy.

**Comment by arvidn** [comment]
how certain are you that the tracker itself is still up? and do you have any reason to believe your network/ISP firewalls UDP?

If you suspect that the outgoing connect packet is incorrect, you could capture it with wireshark/tcpdump. But that seems pretty far fetched, since it wouldn't work for anyone if that was the case. The UDP tracker protocol is documented on libtorrent.org

**Comment by Col-blimp** [comment]
same torrent in utorrent works fine but I should have said that 1.1.1 version works it's the master I built since the empty bitfield crash bug was noticed that fails udp, been quite a lot of changes between 1.1.1 and then.

**Comment by arvidn** [comment]
I see

**Comment by arvidn** [comment]
There is a test for udp trackers that appears to still be passing in master. ``test_trackers.cpp``. I suppose there's some aspect of those messages it isn't verifying. would it be possible for you to capture a successful announce (with uTorrent or libtorrent 1.1) as well as a failing one?

i.e. the udp_connect, connect_response, announce and announce_response packets. in a wireshark dump.

**Comment by Col-blimp** [comment]
both utorrent and libtorrent successfully communicate with the tracker and data of the same size is sent back both times but libtorrent reports this as a timeout.

utorrent:

`Frame 27: 58 bytes on wire (464 bits), 58 bytes captured (464 bits) on interface 0
    Interface id: 0 (\Device\NPF_{A9C7D9ED-6572-44F9-9777-BF1C13BA82B9})
    Encapsulation type: Ethernet (1)
    Arrival Time: Jan 25, 2017 16:34:46.385171000 GMT Standard Time
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1485362086.385171000 seconds
    [Time delta from previous captured frame: 0.040661000 seconds]
    [Time delta from previous displayed frame: 0.040661000 seconds]
    [Time since reference or first frame: 1.742821000 seconds]
    Frame Number: 27
    Frame Length: 58 bytes (464 bits)
    Capture Length: 58 bytes (464 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: eth:ethertype:ip:udp:data]
    [Coloring Rule Name: UDP]
    [Coloring Rule String: udp]
Ethernet II, Src: ArrisGro_54:35:70 (c0:05:c2:54:35:70), Dst: Winstars_21:37:c8 (80:3f:5d:21:37:c8)
    Destination: Winstars_21:37:c8 (80:3f:5d:21:37:c8)
        Address: Winstars_21:37:c8 (80:3f:5d:21:37:c8)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Source: ArrisGro_54:35:70 (c0:05:c2:54:35:70)
        Address: ArrisGro_54:35:70 (c0:05:c2:54:35:70)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: tracker.coppersurfer.tk (62.138.0.158), Dst: 192.168.0.39 (192.168.0.39)
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
        0000 00.. = Differentiated Services Codepoint: Default (0)
        .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
    Total Length: 44
    Identification: 0x0455 (1109)
    Flags: 0x02 (Don't Fragment)
        0... .... = Reserved bit: Not set
        .1.. .... = Don't fragment: Set
        ..0. .... = More fragments: Not set
    Fragment offset: 0
    Time to live: 50
    Protocol: UDP (17)
    Header checksum: 0x4475 [validation disabled]
    [Header checksum status: Unverified]
    Source: tracker.coppersurfer.tk (62.138.0.158)
    Destination: 192.168.0.39 (192.168.0.39)
    [Source GeoIP: Unknown]
    [Destination GeoIP: Unknown]
User Datagram Protocol, Src Port: acmsoda (6969), Dst Port: 54175 (54175)
    Source Port: acmsoda (6969)
    Destination Port: 54175 (54175)
    Length: 24
    Checksum: 0xb58c [unverified]
    [Checksum Status: Unverified]
    [Stream index: 13]
Data (16 bytes)
    Data: 00000000f1f5c5b8eb6683df68d8cb93
    [Length: 16]
`

libtorrent (reported as timeout:

`Frame 289: 58 bytes on wire (464 bits), 58 bytes captured (464 bits) on interface 0
    Interface id: 0 (\Device\NPF_{A9C7D9ED-6572-44F9-9777-BF1C13BA82B9})
    Encapsulation type: Ethernet (1)
    Arrival Time: Jan 25, 2017 16:35:56.114310000 GMT Standard Time
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1485362156.114310000 seconds
    [Time delta from previous captured frame: 0.025286000 seconds]
    [Time delta from previous displayed frame: 0.025286000 seconds]
    [Time since reference or first frame: 4.520985000 seconds]
    Frame Number: 289
    Frame Length: 58 bytes (464 bits)
    Capture Length: 58 bytes (464 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: eth:ethertype:ip:udp:data]
    [Coloring Rule Name: UDP]
    [Coloring Rule String: udp]
Ethernet II, Src: ArrisGro_54:35:70 (c0:05:c2:54:35:70), Dst: Winstars_21:37:c8 (80:3f:5d:21:37:c8)
    Destination: Winstars_21:37:c8 (80:3f:5d:21:37:c8)
        Address: Winstars_21:37:c8 (80:3f:5d:21:37:c8)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Source: ArrisGro_54:35:70 (c0:05:c2:54:35:70)
        Address: ArrisGro_54:35:70 (c0:05:c2:54:35:70)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: tracker.coppersurfer.tk (62.138.0.158), Dst: 192.168.0.39 (192.168.0.39)
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
        0000 00.. = Differentiated Services Codepoint: Default (0)
        .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
    Total Length: 44
    Identification: 0x34b0 (13488)
    Flags: 0x02 (Don't Fragment)
        0... .... = Reserved bit: Not set
        .1.. .... = Don't fragment: Set
        ..0. .... = More fragments: Not set
    Fragment offset: 0
    Time to live: 50
    Protocol: UDP (17)
    Header checksum: 0x141a [validation disabled]
    [Header checksum status: Unverified]
    Source: tracker.coppersurfer.tk (62.138.0.158)
    Destination: 192.168.0.39 (192.168.0.39)
    [Source GeoIP: Unknown]
    [Destination GeoIP: Unknown]
User Datagram Protocol, Src Port: acmsoda (6969), Dst Port: 6881 (6881)
    Source Port: acmsoda (6969)
    Destination Port: 6881 (6881)
    Length: 24
    Checksum: 0xa634 [unverified]
    [Checksum Status: Unverified]
    [Stream index: 54]
Data (16 bytes)
    Data: 0000000084e2fae2eb6683df68d8cb93
    [Length: 16]
`

**Comment by arvidn** [comment]
fixed here (including fixing the test). https://github.com/arvidn/libtorrent/pull/1632

**Comment by Col-blimp** [comment]
Thanks.
