### ISSUE TITLE
error C2512: 'libtorrent::aux::handler_storage

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#1606]
libtorrent version (or branch): master
compiler and compiler version: vc++2015

2>  session_impl.cpp
2>q:\vc15\r5xx\libtorrent\src\session_impl.cpp(473): error C2512: 'libtorrent::aux::handler_storage<336>': no appropriate default constructor available
2>  q:\vc15\r5xx\libtorrent\include\libtorrent\peer_connection.hpp(930): note: see declaration of 'libtorrent::aux::handler_storage<336>'
2>  peer_connection.cpp
2>q:\vc15\r5xx\libtorrent\src\peer_connection.cpp(144): error C2512: 'libtorrent::aux::handler_storage<336>': no appropriate default constructor available
2>  q:\vc15\r5xx\libtorrent\include\libtorrent\peer_connection.hpp(930): note: see declaration of 'libtorrent::aux::handler_storage<336>'
2>  Generating Code...
4>------ Build started: Project: flylinkdc, Configuration: Debug Win32 ------
4>LINK : fatal error LNK1104: cannot open file 'Q:\vc15\r5xx\vc15\Win32\Debug\libtorrent\libtorrent.lib'
========== Build: 2 succeeded, 2 failed, 10 up-to-date, 0 skipped ==========

**Comment by aldenml** [comment]
this should fix it https://github.com/arvidn/libtorrent/pull/1612

**Comment by aldenml** [comment]
didn't see your PR

**Comment by pavel-pimenov** [comment]
ok
