### ISSUE TITLE
"Torrent not registered" is not an error?

### ISSUE THREAD

**Issue by bezdupel** [arvidn/libtorrent#161]
When torrent deleted from tracker or updated/changed, tracker status remains "Working" without any error or warning messages in qBittorrent and Deluge.

Tracker sends following response (example):
`d8:intervali3438e12:min intervali3438e5:peers6:_\207\217\345\301\27715:warning message22:Torrent not registerede`

Is it libtorrent or client related problem?

libtorrent 1.0.6

**Comment by rend3r** [comment]
I can place pcap dump if need.
bezdupel trying solve https://github.com/qbittorrent/qBittorrent/issues/3101 amirite?

**Comment by arvidn** [comment]
what behavior would you expect from libtorrent?
there should be a tracker_warning_alert posted to the client with that message in it.

**Comment by rend3r** [comment]
>there should be a tracker_warning_alert posted to the client with that message in it.
qb does not show warning until restart in my case. After restart client updates the torrent and show alert in tracker status field.

**Comment by bezdupel** [comment]
@rend3r Yes, this and similar in Deluge.
@arvidn I just want to clarify whether libtorrent handles this error and the problem with the client or libtorrent does not handle this error? Here's the [dump](https://drive.google.com/open?id=0B6uBZNFMeqr-cDI3d0I1MXVBVHc) with tracker warning.

**Comment by Gelmir** [comment]
I don't see "warning message" tracker response described anywhere in official BT specifications.

Closest thing you get is "failure reason" at http://www.bittorrent.org/beps/bep_0003.html

My guess would be that libtorrent only marks trackers as "Not Working" if HTTP result code is not 200 or "failure reason" is present.

> what behavior would you expect from libtorrent?

Probably users expect this to be treated as error (perhaps expose new config "treat tracker warnings as errors"?). But I personally blame the tracker here: if the tracker doesn't know about particular hash it should answer with failure, not warning. Common sense for warning: something happened, but we can continue.

**Comment by rend3r** [comment]
@Gelmir 
>My guess would be that libtorrent only marks trackers as "Not Working" if HTTP result code is not 200 or "failure reason" is present.

tracker have sent "d14:failure reason20:unregistered torrente"  response in packet 8 but qb ignoring that and show working status. Here is [dump](https://dl.dropboxusercontent.com/u/30953076/qb_dump.pcapng)

**Comment by arvidn** [comment]
yes, libtorrent supports it:

https://github.com/arvidn/libtorrent/blob/RC_1_0/src/http_tracker_connection.cpp#L403

That doesn't mean there's no bug in that code though.

**Comment by rend3r** [comment]
@arvidn 
Why did you close the bug?

**Comment by arvidn** [comment]
I was under the impression that there was no longer a bug. There was a question whether libtorrent supports the tracker warning message and I showed that it did.

what's the libtorrent error this ticket would track?

**Comment by rend3r** [comment]
Look at my previous comment. Client does not change status even though "unregistered torrent" message has arrived

**Comment by arvidn** [comment]
right. would you expect it to? I don't think it's reasonable for libtorrent to parse and understand english to try to figure out whether a message should mean to stop the torrent. what if the message is in a different language? how many languages should libtorrent understand? what if there are other trackers that _do_ work, why would a single one cause it to stop? or even if there aren't any other trackers, the DHT or PEX may still be able to provide peers, should libtorrent just assume they won't?

**Comment by rend3r** [comment]
Perhaps I didn't make myself clear. I mean tracker sent "failure reason" in response but client did not change status.
As @Gelmir already said libtorrent should mark trackers as "Not Working" if HTTP result code is not 200  or "failure reason" is present. Pretty straight logic in my opinion. Is it true for now?

**Comment by rend3r** [comment]
1) PEX & DHT are disabled (private torrent). If all trackers are down (could not resolve name/other network problems, http code is not 200, or "failure reason" response) or no tracker present at all - torrent not working.
2) PEX & DHT are disabled. Some trackers are down, some - not. Torrent is working with concurrent statuses (active, inactive, seeding, downloading, etc).
3) PEX & DHT are allowed. Status of trackers does not matter - torrent is working because we can still get peers throu pex&dht. Concurrent statuses applied.
4) PEX & DHT are allowed. Trackerless torrent. Same as 3rd.

Active - seeding or downloading
Inactive - running ("resumed" in terms qbittorrent) and working torrents but no one dl from you or you could not dl (no peers or peers haven't interested pieces)
All torrents = downloading + completed
Completed = resumed (running) + paused (stopped).
Paused torrents couldn't have another statuses.

**Comment by arvidn** [comment]
ah, you mean the status of the *tracker*. which field of the announce_entry are you referring to exactly? it sounds like you expect is_working() to return false, or last_error to be set to libtorrent::errors::tracker_failure? (both are supposed to be true)

**Comment by rend3r** [comment]
>it sounds like you expect is_working() to return false, or last_error to be set to libtorrent::errors::tracker_failure? (both are supposed to be true)

i am expect is_working() to return false either last_error to be set to libtorrent::errors::tracker_failure

**Comment by rend3r** [comment]
@arvidn you can close the issue, it was client bug. For more info check https://github.com/qbittorrent/qBittorrent/issues/3101
