### ISSUE TITLE
Python bindings RC_1_1 invalid values in cache_status on 32bit

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1610]
I think there has been a regression on  RC_1_1, one of the cache test run by Deluge started failing today on my 32bit machine. Likely related to #1542 

```
import libtorrent as lt
sess = lt.session()
cache_status = sess.get_cache_status()
for attr in dir(cache_status):
    if not attr.startswith('_'):
        value = getattr(cache_status, attr)
        if isinstance(value, int) and value != 0:
            print('Fail: %s, %s' % (attr, value))
```

Output on 32bit:
```
Fail: average_hash_time, 371651470
Fail: average_job_time, 915761744
Fail: average_read_time, -1794883444
Fail: average_write_time, -349559961
Fail: blocked_jobs, 1870012448
Fail: blocks_read, 1869181811
Fail: blocks_read_hit, 1953722223
Fail: blocks_written, 1953391986
Fail: cumulative_hash_time, 170470958
Fail: cumulative_job_time, 538976288
Fail: cumulative_read_time, 1633641326
Fail: cumulative_write_time, 1701999215
Fail: pending_jobs, 538976288
Fail: reads, 170488931
Fail: total_read_back, 545005578
Fail: writes, 1852794996
```

**Comment by arvidn** [comment]
can you think of anything that being a 32 bit machine would influence?
do you know if it has to run on a 32 bit OS or is being a 32 bit binary enough?

**Comment by cas--** [comment]
Honestly I am not sure, it is a 32-bit Ubuntu Precise (boost 1.55) on a 32-bit VirtualBox but I imagine 32 bit binary of boost and libtorrent is enough? 

I can check back through recent libtorrent builds to verify it is a regression if that helps. Although the fact that `cache_status` fails is quite relevant since it's an old method and there have been no issues in the previous branches e.g. RC_1_0.

**Comment by arvidn** [comment]
does this test fail too? https://github.com/arvidn/libtorrent/pull/1613

**Comment by cas--** [comment]
All test pass.

Is it possible to build the tests from autotools? This was all I saw with `--enable-tests`:
```
make[1]: Entering directory `/home/ubuntu/Projects/lt-git/test'
  CXX    main.lo
  CXX    test.lo
main.cpp: In function 'int main(int, const char**)':
main.cpp:337:12: warning: ignoring return value of 'int chdir(const char*)', declared with attribute warn_unused_result [-Wunused-result]
  CXX    setup_transfer.lo
  CXX    dht_server.lo
  CXX    udp_tracker.lo
  CXX    peer_server.lo
  CXX    bittorrent_peer.lo
  CXX    make_torrent.lo
  CXX    web_seed_suite.lo
  CXX    swarm_suite.lo
  CXX    test_utils.lo
  CXX    settings.lo
  CXX    print_alerts.lo
  CXXLD  libtest.la
```

Also I ran into an issue building the tests with Jamfile:
```
cc1plus: error: unrecognised command line option ‘-Wc++11-compat’
cc1plus: warning: command line option ‘-Wno-format-zero-length’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: error: unrecognised command line option ‘-Wpedantic’
```

and needed to disable the following flags:
```diff --git Jamfile Jamfile
index dd4133138..6162ad3b5 100644
--- Jamfile
+++ Jamfile
@@ -257,12 +257,12 @@ rule warnings ( properties * )
        {
                result += <cflags>-Wall ;
                result += <cflags>-Wextra ;
-               result += <cflags>-Wpedantic ;
+#              result += <cflags>-Wpedantic ;
 #              result += <cflags>-Wmisleading-indentation ;
                result += <cflags>-Wparentheses ;
                result += <cflags>-Wvla ;
-               result += <cxxflags>-Wc++11-compat ;
-               result += <cflags>-Wno-format-zero-length ;
+#              result += <cxxflags>-Wc++11-compat ;
+#              result += <cflags>-Wno-format-zero-length ;
                result += <cflags>-Wno-long-long ;
```

**Comment by cas--** [comment]
Hmm the mystery deepens, Deluge test still fails but standalone script test now passes!

**Comment by Falcosc** [comment]
I have binary update issues in libtorrent root dir too if I use make and checkinstall which could not be solved by bjam clean or make clean. Sometimes I have to clear the work directory get my changes.

**Comment by cas--** [comment]
This is nothing to do with build process or temp files as libtorrent is built by launchpad. I could replicate outside of Deluge so need to see what changed

**Comment by cas--** [comment]
It is still a problem on my machine but cannot replicate elsewhere so closing. Will also check #1542

**Comment by arvidn** [comment]
perhaps it could be an issue of the counters not being initialized to 0 for some reason. perhaps if there is no 64 bit atomic increment, the mutex version of the counters is used. Maybe that's the distinction
