### ISSUE TITLE
RC_1_1 document cache_status deprecation

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1626]
In RC_1_1 I had to spend a while looking up and converting from `cache_status` to `session_statistics`...

- [ ] new code needs commented with old deprecated.
- [ ] Documentation should use same wording (if still applicable) to [old documentation](http://www.rasterbar.com/products/libtorrent/manual.html#get-cache-status).
- [ ] `disk.write_cache_blocks` and `disk.write_cache_blocks` are incorrectly grouped with `pickers`.
- [ ] some of the descriptions under the table groups seems incorrect or only applicable to one item.

For quick reference these are the changes I have looked up and made:
```
blocks_written -> disk.num_blocks_written
writes -> disk.write_ops
blocks_read  -> disk.num_blocks_read
blocks_read_hit -> disk.num_blocks_cache_hits
reads -> disk.read_ops
cache_size -> disk.disk_blocks_in_use
read_cache_size -> disk.read_cache_blocks
total_used_buffers
average_queue_time
average_read_time
average_write_time
average_hash_time
average_cache_time
job_queue_length
```

**Comment by arvidn** [comment]
here's a start: https://github.com/arvidn/libtorrent/pull/1726

**Comment by cas--** [comment]
Need a bit of help with the following session status keys. Still lacking good descriptions in session statistics to properly understand what the entries are for and what they have deprecated. 

```
session.status.num_peers
session.status.num_unchoked
session.num_connections()
session.num_uploads()
```

**Comment by arvidn** [comment]
does this cover it? https://github.com/arvidn/libtorrent/pull/1827
