### ISSUE TITLE
Documentation navigation and single page

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1627]
1. Please could we have the option of a single page, like in the old days ([manual.html](http://www.rasterbar.com/products/libtorrent/manual.html))... :smiley: 

1. There is no way to navigate back to [http://libtorrent.org/reference.html](http://libtorrent.org/reference.html) from reference links. Perhaps a link above ToC or just below banner.

1. This is no way navigate to home page (e.g. http://libtorrent.org). I am thinking making the banner clickable would suffice.

These are genuine frustrations of referencing the documentation so would be much appreciated!

**Comment by arvidn** [comment]
does this look reasonable? https://github.com/arvidn/libtorrent/pull/1633

**Comment by arvidn** [comment]
so.. people don't like the "back" button in the browser these days?

**Comment by cas--** [comment]
Heh, I mainly navigate to the browser history pages so 'back' doesn't work ;)
