### ISSUE TITLE
Super seeding mode isn't reported for completed torrents

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#1628]
**Please provide the following information**

libtorrent version (or branch): RC_1_0
platform/architecture: Windows 7
compiler and compiler version: msvc2015

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

We use the `super_seeding` field of torrent_status to display the appropriate checkbox when a user-right clicks a torrent.

Apparently super seeding takes effect only for seeds and not for completed and queued torrents.
In qbt "completed and queued" torrents are torrents when this is true:
```c++
torrent_status::paused && torrent_status::auto_managed && (torrent_status::state == torrent_status::finished) || (torrent_status::state == torrent_status::seeding)));
```

And generally in the UI we consider them as seeds. If I set super_seeding on these torrents while in that state and then check `torrent_status::super_seeding` I get that it is false. But if I then resume them and check again the flag is true.

Is this intended behavior or an oversight?
Could you add the ability to report true for those kind of torrents after `torrent_handle::super_seeding(true)` has been called?

**Comment by arvidn** [comment]
I assume the parenthesis in your expression was a typo, and that you meant (state == finished || state == seeding).

as far as I can tell, the field in ``torrent_status`` is updated _just_ by the internal ``m_super_seeding``. However, the member function also checks for the torrent to be seeding.

Would you mind trying this out? https://github.com/arvidn/libtorrent/pull/1629

**Comment by arvidn** [comment]
I made this change in RC_1_1. would you still be interested in it in RC_1_0?

**Comment by sledgehammer999** [comment]
>I made this change in RC_1_1. would you still be interested in it in RC_1_0?

I see that #1629 is targeting RC_1_0, which we continue to officially encourage people to build qbt against.
I'll be able to test tomorrow, but I think the fix is simple enough that it'll work already.

**Comment by sledgehammer999** [comment]
Thanks for the fixes.
