### ISSUE TITLE
need_save_resume_data

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#1637]
`need_save_resume_data()` returns true for seeding/finished torrents, is this expected behaviour?

**Comment by arvidn** [comment]
yes. It does that periodically, to save statistics in its resume data. It's not ideal, since it's kind of up to the client to decide whether that need to be saved. If you're interested, it should be a pretty simple fix:  https://github.com/arvidn/libtorrent/projects/1#card-1374419

**Comment by arvidn** [comment]
to be clear, it's not expected to return true consistently. just once every 15 minutes (assuming you actually save the resume data when it's true)
