### ISSUE TITLE
Question about union_endpoint and union_address

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#1657]
Source code question (`master`): I understand the idea behind `union_endpoint` but I see it's only used for `node_entry::endpoint`, but that field seems to be never used directly. Why not just use `udp::endpoint`?

**Comment by ssiloti** [comment]
IIRC it's a memory space optimization. `udp::endpoint` uses the platform's `sockaddr_in` structure which contains more than just the address and port. Since there typically several hundred instances of `node_entry` at any given time we can save a kilobyte or two by using an optimized struct.

**Comment by aldenml** [comment]
thanks! that makes sense

**Comment by aldenml** [comment]
@ssiloti do you have any argument against putting this optimization with the minimal code/logic necessary inside `node_entry` and remove `union_endpoint` and `union_address`?

My motivation is that I looking for a way to retrieve the `node_entry` info to the client in a possible `session_handle::"dht_get_internal_live_nodes"` and I'm having design problems with the "endpoint" and public API.

**Comment by ssiloti** [comment]
I don't think exposing `node_entry` to the client would be appropriate. Exposing routing table contents to the client at all feels like exposing a bit too much implementation detail. Perhaps DHT crawlers should be implemented as plugins since they will be working more closely with the DHT nodes than a normal client.

**Comment by arvidn** [comment]
I agree, it's risky to expose internal data structures in the public API. Even if they are identical now, it locks in the internals from changing (easily). I made this mistake with ``web_seed_entry`` and ``announce_entry`` (at least the web_seed_entry has been split up since)

**Comment by aldenml** [comment]
Well, I need to figure out an aceptable way of unlock at least the `(node_id, endpoint)` info of nodes, otherwise (plugin or not) it will become useless the `session_handle::dht_sample_infohashes(...)` method.

I will close the issue, but I will be working in a proposal in a PR.

thanks for the feedback!
