### ISSUE TITLE
Unknown clients in peerlist [libtorrent 1.0.6.0]

### ISSUE THREAD

**Issue by txtsd** [arvidn/libtorrent#166]
![Peer list](http://i.imgur.com/2oiJ3K9.png)

qbittorrent/qBittorrent#3802

**Comment by ruslanfedoseenko** [comment]
Some of them may be a libtorrent-based clients with anonimus setting enabled.

**Comment by arvidn** [comment]
what is the problem exactly?

**Comment by txtsd** [comment]
@arvidn The client names are showing up as Unknown[garbled_string]
Is this intended behavior for some sort of anonymity?

**Comment by arvidn** [comment]
those are peer-ids. it's not mandatory to encode client version in them. There's an (optional) extension protocol that has an (optional) client name field too. but none is mandatory.

**Comment by txtsd** [comment]
Thanks for the clarification!
