### ISSUE TITLE
When setting file_priorities to 0 for multiple files but one, download keeps going after the prioritized file is done

### ISSUE THREAD

**Issue by scakemyer** [arvidn/libtorrent#1668]
libtorrent version (or branch): RC_1_1
platform/architecture: ARMv7
compiler and compiler version: gcc 4.9

Note: this probably applies to similar situations besides having only one prioritized file.

I'm not sure if this is a recent regression since it's not something I've relied on before, and only recently began explicitly setting file_priorities.

So basically after adding a torrent and receiving metadata, we set all file_priorities to 0, then if some condition is met the user is asked to choose a file, otherwise it's determined automatically, but either way there's only 1 file index that gets back a file_priority of 4. At which point downloading starts and all goes well. Progress even shows the percentage for that file only which is great. However, once it hits 100%, state doesn't change, downloading keeps going, progress gets back down to 10% (let's say from a 1GB file out of a 10GB torrent), and doesn't stop until it hits 100% again.

The file priorities work as intended as far as storage is concerned; only 1 file gets written. So while it downloads the remaining 90%, it goes... into nothingness. RAM usage stays pretty much the same.

At first I thought it was something about auto_managed, but after turning it off, behavior remained the same. I'm out of ideas at this point ;)

**Comment by scakemyer** [comment]
Scratch that... Old code was resetting piece priorities on the first 'finished' alert, which came in right after setting those file priorities to 0 and that one file to 4... auto_managed not having any influence on behavior once that was taken care of, and progress showing percentage of the one file only in both cases.

That being said, and the problem fixed on my end, I still think there's something weird with downloading a whole torrent to /dev/null while saving only one file to disk, so maybe there's something to improve there.

**Comment by arvidn** [comment]
do you get a partfile with the downloaded pieces in?

I'm not sure I understand exactly what the problem on your side was. Do you set the file priorities to 0, but then you adjust the piece priorities up?

**Comment by scakemyer** [comment]
Yeah exactly, piece priorities are adjusted up with a certain logic (required initial buffer pieces + end pieces, middle ones at 1) for the same file using offsets. I'm not sure how much it's really needed, and wouldn't call it legacy code either, since it's been working pretty damn well so far for streaming. So basically the only issue is that once I started setting file_priorities also, to prevent other files from slowly coming in when we don't really want them, it started triggering the 'finished' alert, which reset all piece priorities.

What I'm wondering is, if file_priorities are at 0, but piece priorities are not, which should take precedence in that case, and why would it make sense to keep downloading to parts file anyway, answering your question with a yes and a facepalm...

**Comment by arvidn** [comment]
fundamentally there are only piece priorities. file priorities are strictly a higher level concept. When setting file priorities, it ultimately boils down to updating piece priorities. The file priorities must still be kept around to correctly handle updates to file priorities and the pieces that may span multiple files.

However, if you first set file priorities, and then piece priorities, you piece priority updates will overwrite the ones set by the file priorities. If you then update file priorities, I believe only pieces overlapping with a file whose priority actually changed will be updated again.

**Comment by scakemyer** [comment]
That makes a lot of sense. I did find some inconsistencies though. After removing that resetting of piece priorities, which fixed my main issue, I tried removing setting the file priorities, thinking it was redundant to do so. However, unwanted files started to pop up again on disk, even though their piece priority was set to 0, until I re-added setting their file priorities to 0 also. So even if it's just a higher level concept, it does seem to flag files to be written or not, which also makes sense, but also means its purpose is more than to just set underlying piece priorities.

I also think resetting piece priorities should trigger something in its "parent" file priorities to make sure downloaded pieces do get written to disk, and not just in partfiles.

**Comment by arvidn** [comment]
right, the file priorities do affect the disk I/O subsystem. It determines whether the file should be written to the part file or to the file specified in the torrent. I've considered many ways of having the piece and file priorities interact, and I'm still leaning in favor of keeping the interactions simple. Normally, clients only deal with either file priorities or piece priorities, not both at the same time. And in those cases the current behavior works intuitively.

The case of setting all file priorities to 0 and setting a few pieces back to 4 still makes sense. You won't (easily) be able to get at the data straight from disk, but you can still use ``torrent_handle::read_piece()``

**Comment by scakemyer** [comment]
Yeah we're good on that front, using golang's File.Seek and changing the current file's piece priorities on-the-fly if needed, but that's another story, and it's already working pretty well without major issues.

I understand that adding interactions between piece priorities and file priorities might not be desirable, and the overhead could be too big to be worth it. So I'll just try to keep in mind what happens when you deal with both and forget that something is resetting piece priorities ;) Thanks for everything!
