### ISSUE TITLE
enhancement request: specifying named interface not supported under Windows

### ISSUE THREAD

**Issue by bluenote73** [arvidn/libtorrent#1669]
libtorrent does not appear to support addressing windows network devices by name for listen or outgoing.
Using the assigned IP address in these fields works as expected.
Using the friendly name returns 'no such device'.

Could some sort of friendly name addressing be added if indeed there is no current functionality to use a name under windows?

This would be particularily useful in scenarios that involve a VPN, (no possibility of traffic leaks, no killswitches needed).

**Comment by arvidn** [comment]
according to the Changelog, this functionality was added in the 1.1 release. It has been improved further in master and made more reliable. However, the names of devices on windows are UUIDs iirc, so I wouldn't call them particularly friendly names.

Are there different names of network interfaces on windows, that can be mapped to their UUID?

**Comment by arvidn** [comment]
specifically:

https://github.com/arvidn/libtorrent/blob/RC_1_1/src/session_impl.cpp#L1783

and

https://github.com/arvidn/libtorrent/blob/9e4045ed425a881508c30bdb1bae0f4d39335d40/src/session_impl.cpp#L4914

**Comment by bluenote73** [comment]
Hi arvidn

Thank you, I didn't know about that.  I assume you mean the windows GUID associated with the interface.  There is also a friendly name associated with the GUID.   I am getting a 'no such device' error trying to use the GUID, but I will play around with it a bit.  As far as friendly names, yes there are friendly names associated with the interfaces.  Here is an example (see 'name' field).
https://postimg.org/image/3s8mi04an/

thanks

**Comment by bluenote73** [comment]
Actually it appears that UUID/GUID has some trouble on more than just windows, as I have a report of similar behaviour under linux using libtorrent RC_1_1. thx  (no such device)

**Comment by arvidn** [comment]
I was looking through the code last night, and as far as I can tell, there's no way to bind a socket to a specific interface/adapter/device on windows, is there?
Something like ``SO_BINDTODEVICE`` on linux. I believe the code that's in libtorrent right now just enumerates adapters, looks for the specified name, pulls out the IP associated with that adapter and does a regular ``bind()`` to it.

**Comment by bluenote73** [comment]
I'm afraid I don't know the answer to this, sorry.   Even if it's doing that kludge under the covers, that would still be more useful than having to specify the IP manually and change it every time a tunnel connects though.  Obviously we would both prefer a real bind to interface rather than to IP though..

**Comment by bluenote73** [comment]
Actually I think you are correct, that there is no way to bind to device under windows, only to iterate through the names, pull the IP and then bind to the IP.  And then, if the IP changes (tunnel reconnect for example), an error will be thrown, which should trigger another iteration/bind sequence.

Should I open another ticket for the existing device/GUID binding not working so it's separate from this request for a friendly name?

**Comment by ajax16384** [comment]
@bluenote73 to specify bind by GUID it must be supplied in following form:
````c++
libtorrent::settings_pack pack;
pack.set_str(libtorrent::settings_pack::listen_interfaces, "{E4F0B674-0DFC-48BB-98A5-2AA730BDB6D6}:6881");
````
unlike "netsh lan show interfaces" output it should contain:
- upper case guid string
- curly brackets

**Comment by arvidn** [comment]
patches to improve the documentation are welcome! :)

**Comment by bluenote73** [comment]
Thanks for the education on the format :)  I still see some, what looks to me, completely incorrect behaviour though.  (note bind to 0:0:0:0, then fail on device, then correctly bind to IP of the device)
![image](https://cloud.githubusercontent.com/assets/6239498/22706561/9cea4822-ed24-11e6-87ef-cd17120afaeb.png)

**Comment by ajax16384** [comment]
Network adapter enumeration with GUID names is enabled for (_WIN32_WINNT >= 0x0501). Are you sure that your libtorrent.dll build has greater or equal win version?

**Comment by bluenote73** [comment]
@ajax16384 it must, since it does settle on the correct device IP in the end, otherwise where would it get that information?     

One further note though, besides the funny reporting (listening on 0:0:0:0:6881..) I do not see any incorrect ports listening in a netstat -a -b -n , so this may just be a funny artifact of the operations it goes through?  I leave that to your judgement..

**Comment by ajax16384** [comment]
oh, _WIN32_WINNT definitly not a problem, it' really called adpater enumeration with GUID names.

**Comment by ajax16384** [comment]
do you use ipv6 enabled build? cause it may ignore AF_INET6 part of adapter address and add it as "0.0.0.0" ipv4.

**Comment by arvidn** [comment]
do you construct the session object with a settings pack where you set the listen_interfaces/outgoing_interfaces?

If not, the default is to bind to 0.0.0.0, and it will do that until you call ``apply_settings()``

**Comment by ajax16384** [comment]
@arvidn 
 this enumeration https://github.com/arvidn/libtorrent/blob/master/src/enum_net.cpp#L630 should really looks like:
````c++
while (unicast)
{
    int family = unicast->Address.lpSockaddr->sa_family;

    if (family == AF_INET
#if TORRENT_USE_IPV6
        || family == AF_INET6
#endif
        )
    {
        r.interface_address = sockaddr_to_address(unicast->Address.lpSockaddr);
        ret.push_back(r);
    }

    unicast = unicast->Next;
}
````

**Comment by ajax16384** [comment]
if i am right with disabled ipv6 build then this patch should fix issue

**Comment by arvidn** [comment]
makes sense

**Comment by ajax16384** [comment]
ok, will make PR

**Comment by ajax16384** [comment]
https://github.com/arvidn/libtorrent/pull/1678
