### ISSUE TITLE
Assertion failure

### ISSUE THREAD

**Issue by LiMinggang** [arvidn/libtorrent#1697]
**Please provide the following information**

libtorrent version (or branch):
Latest 1.0.11

platform/architecture:
Win7 X64

compiler and compiler version:
VC++ 2015
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
Assertion failure
bool routing_table::add_node(node_entry e)
{
	add_node_status_t s = add_node_impl(e);
	if (s == failed_to_add) return false;
	if (s == node_added) return true;

	while (s == need_bucket_split)
	{
		split_bucket();

		// if this assert triggers a lot in the wild, we should probably
		// harden our resistence towards this attack. Perhaps by never
		// splitting a bucket (and discard nodes) if the two buckets above it
		// are empty or close to empty
		TORRENT_ASSERT(m_buckets.size() <= 50);

Any suggestion for this failure? What should I do? The torrent can be downloaded successfully by uTorrent and qTorrent.

**Comment by arvidn** [comment]
yes, my suggestion is to either comment out that assert, or upgrade to a newer version of libtorrent

**Comment by LiMinggang** [comment]
Hi, arvidn, by "upgrade to a newer version of libtorrent", do you mean you've fixed the issue in the latest code in github?

If so, I'll close the issue then.

**Comment by LiMinggang** [comment]
Close it since it was commented out in the latest code
