### ISSUE TITLE
Attempt to reestablish proxy connections (SOCKS, I2P), listeners, etc if went down

### ISSUE THREAD

**Issue by mlt** [arvidn/libtorrent#17]
From what I understand, those connections are established once in the very beginning in session_impl. There has to be a way to detect when tracker and/or peer connection was aborted because of underlying issues and attempt to reestablish it every NN seconds.

**Comment by arvidn** [comment]
I'm pretty sure there is a callback when the proxy/SAM connection goes down to reconnect it. To actually reconnect every peer that relied on it would take a little bit more work.

**Comment by mlt** [comment]
Would you mind pointing me to the place(s) in code? I didn't find anything for SOCKS / I2P. I see `open_new_incoming_socks_connection` and `open_listen_port` but those as I can tell are called from session_impl init & apply_settings_pack_impl. Did I overlook something?

I agree, there is no need to handle individual peers, they'll get back eventually by other means.

**Comment by arvidn** [comment]
if I recall, the sam connection (is the protocol called BOB?), it basically works the same was as SOCKS (but with a different protocol). To receive an incoming connection, you open a connection to the server and indicate that you want to receive one, once you do, you open another connection to the server.

the function that opens this connection is session_impl::open_new_incoming_i2p_connection().

**Comment by mlt** [comment]
I understand that. However, the essence of my question is whether there are means to reestablish connection to a proxy and repeat what you've mentioned as it is usually done at the very beginning, i.e. open a listener.

My concern is that if proxy server dies for whatever reason taking an acceptor (listener @ proxy) along with it, there will be no attempt on libtorrent part to start all that anew.

I'm not sure what boost asio error_code is for lost connection (eof?). I feel like as of now i2p still attempts to use old disconnected socket and all communication attempts will fail. And something tells me that is the case with SOCKS as well.

> is the protocol called BOB

Nope, BOB is an alternative to SAM.

**Comment by arvidn** [comment]
The handler for accepting an incoming i2p connection is session_impl::on_i2p_accept(). If the connection to the SAM server fails somehow, it's also called with an error. Currently, if there is an error, it's logged and an alert is posted and that's it. It won't retry.
If there isn't an error, it will reconnect to wait for another incoming connection (by calling: open_new_incoming_i2p_connection()).

I can imagine two approaches to retrying. Either to track when the last connection attempt was made by the session, and every time there is a failure, set a timer to expire that time + some increasing delay, and retry then. The increase should probably have an upper bound to it and should probably be exponential.

Alternatively, there could be a periodic check in session_impl::on_tick() that checks to see if there is a connection, and if not, retry. There would have to be some time scaler to not try every second probably. Option 1 would probably have the nicest properties.
