### ISSUE TITLE
RC_1_1: Pickling of "libtorrent.error_code" instances is not enabled

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1738]
I am seeing an issue using latest RC_1_1 code when trying to pickle the torrent state. It's a serious error in Deluge because torrents with trackers are not saved on shutdown.

I suspected it's last_error added to trackers that's causing the issue:

```
import libtorrent as lt
import pickle
ae = lt.announce_entry('')
pickle.dumps(ae.fail_limit)
pickle.dumps(ae.last_error)
```

```
Traceback (most recent call last):
  File "<pyshell#8>", line 5, in <module>
    pickle.dumps(ae.last_error)
  File "/usr/lib/python2.7/pickle.py", line 1380, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
RuntimeError: Pickling of "libtorrent.error_code" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
```

I am not sure the best solution yet, we don't really need to pickle that entry but it does need fixed as it breaks backward compatibility. Probably best to have a convertor for `error_code` to dict.

**Comment by arvidn** [comment]
would it be sufficient to have a conversion in one direction? from C++ -> python. I suppose a converter in the other direction could just test a few known categories and fail if it's not known.
I imagine the python version would be the error value and the name of the category.

**Comment by cas--** [comment]
I think a one way conversion should suffice. Offhand I can't think where we would pass back EC but I can look at it properly tomorrow...

**Comment by arvidn** [comment]
don't you un-pickle the objects? wouldn't that require a conversion in the other direction?

**Comment by cas--** [comment]
Hmm I don't think so as it's a dict within a dict of a deluge object rather than libtorrent object

**Comment by arvidn** [comment]
@cas-- would you mind writing a test that I can test a converter against?

**Comment by cas--** [comment]
I can do, did you also want to test pickling or just that the dict is as expected?

**Comment by cas--** [comment]
Could simply add to `test_torrent_info.test_announce_entry`:

```
self.assertEquals(ae.last_error['value'], 0)
```

**Comment by arvidn** [comment]
if possible, making sure pickling works would be ideal I think. partly because I'm not confident that it will just because the converter works

**Comment by cas--** [comment]
To keep backward compatibility will need `last_error` in `torrent_handle.cpp` converted to a dict within the [trackers dict](https://github.com/arvidn/libtorrent/blob/RC_1_1/bindings/python/src/torrent_handle.cpp#L234). This does make sense as the trackers are already being converted from lt.ae object...

**Comment by arvidn** [comment]
do you mean a dict specifically, or just be pickle enabled? I prefer to avoid converting things to dicts and back, and use the boost.python python representations

**Comment by cas--** [comment]
That error in the other post is not from pickling but attempting to rencode the data for sending via RPC so it cannot be an object.

**Comment by cas--** [comment]
I will have to check later but I am not seeing any changes to `torrent_handle` attributes in the python build??

**Comment by arvidn** [comment]
interesting. I was under the impression the pickling support I added would apply to all instances of ``error_code``. If you would add another test (to cover this case) it would be easier for me to fix it

**Comment by cas--** [comment]
The `rencode` module can't match the type to  https://github.com/aresch/rencode/blob/master/rencode/rencode_orig.py#L363

The equivalent builtin module would be json serialize:

```
	def test_serialize_trackers(self):
		"""Test to ensure the dict contains only python built-in types"""
		self.setup()
		self.h.add_tracker({'url':'udp://tracker1.com'})
		import json
		print(json.dumps(self.h.trackers()[0]))
```

**Comment by cas--** [comment]
I can put together a pull request with a better test but that should work for now.

**Comment by arvidn** [comment]
does ``json.dump`` only support dict, list, int and string? If so, it doesn't seem obvious that it makes sense for it to work with arbitrary class objects.

**Comment by cas--** [comment]
It's not about what makes sense it's about how `torrent_handle.trackers()` has been coded in the bindings which is to return a python list of dicts and by introducing the error_code object, it's broken the api.

Adding pickling code doesn't help with this particular issue. 

The quickest and simplest fix would be something like this: 
```
index 66b6bd3..ab38974 100644
--- bindings/python/src/torrent_handle.cpp
+++ bindings/python/src/torrent_handle.cpp
@@ -241,7 +241,7 @@ list trackers(torrent_handle& h)
         d["url"] = i->url;
         d["trackerid"] = i->trackerid;
         d["message"] = i->message;
-        d["last_error"] = i->last_error;
+        d["last_error"] = i->last_error.value();
         d["next_announce"] = i->next_announce;
         d["min_announce"] = i->min_announce;
         d["scrape_incomplete"] = i->scrape_incomplete;
```

**Comment by arvidn** [comment]
I see. thanks for explaining, that makes sense. It's not obvious to me what the best solution is. simply demoting the error_code to a dict would loose some precision in the error reporting. I'll think a bit more about it

**Comment by arvidn** [comment]
yeah, your patch seems reasonable. I think the longer term direction should be to expose the whole tracker structure via boost.python.

**Comment by arvidn** [comment]
makes sense? https://github.com/arvidn/libtorrent/pull/1756

**Comment by cas--** [comment]
Ah of course that's how you add another dict... :D 

Apart from adding message, looks good

**Comment by arvidn** [comment]
are there other blockers for Deluge hiding behind this one? (I'm eager to cut 1.1.2)

**Comment by cas--** [comment]
Yeah I can understand that :-) Not that I'm aware of, I'll check tomorrow with the Ubuntu builds and Deluge 1.3 code

**Comment by arvidn** [comment]
there'll always be a 1.1.3 as well though :)

**Comment by cas--** [comment]
Oh most definitely :D

I didn't get a change to do much testing today but I am happy this is fixed :+1:
