### ISSUE TITLE
Assert want_tick() == m_links[aux::session_interface::torrent_want_tick].in_list()

### ISSUE THREAD

**Issue by Falcosc** [arvidn/libtorrent#1739]
libtorrent version (or branch):
RC_1_1 head

platform/architecture:
debian 64bit

compiler and compiler version:
gcc 6

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

after 30minutes with 3000 inactive torrents and 5 active torrents

```
version: 1.1.1.0-1229491

file: 'torrent.cpp'
line: 9026
function: void libtorrent::torrent::check_invariant() const
expression: want_tick() == m_links[aux::session_interface::torrent_want_tick].in_list()

stack:
1: assert_fail(char const*, int, char const*, char const*, char const*, int)
2:
3:
4:
5:
6:
7:
8:
9:
10: clone

Catching signal: SIGINT
Exiting cleanly


*************************************************************
Catching signal: SIGABRT
Please file a bug report at http://bug.qbittorrent.org and provide the following information:

qBittorrent version: v3.3.10
stack trace:
  /lib/x86_64-linux-gnu/libc.so.6 : gsignal()+0xcf  [0x7fa12e8c6fdf]
  /lib/x86_64-linux-gnu/libc.so.6 : abort()+0x16a  [0x7fa12e8c840a]
  /usr/lib/libtorrent-rasterbar.so.9 : assert_fail(char const*, int, char const*, char const*, char const*, int)+0x9b  [0x7fa13065756b]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x2a3d04  [0x7fa130868d04]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x2e4cec  [0x7fa1308a9cec]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x2ada8d  [0x7fa130872a8d]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x242ade  [0x7fa130807ade]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x20d28f  [0x7fa1307d228f]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x2014e5  [0x7fa1307c64e5]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0xde97f  [0x7fa1306a397f]
  /lib/x86_64-linux-gnu/libpthread.so.0 : ()+0x7464  [0x7fa12f4d5464]
  /lib/x86_64-linux-gnu/libc.so.6 : clone()+0x5f  [0x7fa12e97c9df]

```

Sorry for the missing symbols, I did checkinstall instead of make install.

**Comment by arvidn** [comment]
unfortunately this is basically impossible to diagnose without the symbols.

**Comment by Falcosc** [comment]
Sorry, I can't boot my torrent client anymore with invariant checks because of https://github.com/arvidn/libtorrent/issues/1592

**Comment by Falcosc** [comment]
I did get a new stack for my new debug installation.
Now I have a problem, I don't understand why symbols are still missing.

As you see, the linked binaries do have symbols

> nutzer@server:~/fas/qBittorrent$ which qbittorrent-nox
> /usr/local/bin/qbittorrent-nox
> nutzer@server:~/fas/qBittorrent$ ldd /usr/local/bin/qbittorrent-nox
>         linux-vdso.so.1 (0x00007ffe7eb82000)
>         libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb5dc5a7000)
>         libtorrent-rasterbar.so.9 => /usr/lib/libtorrent-rasterbar.so.9 (0x00007fb5dbef2000)
>         libboost_system.so.1.62.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.62.0 (0x00007fb5dbcee000)
>         libQt5Xml.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5 (0x00007fb5dbab1000)
>         libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007fb5db754000)
>         libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007fb5db018000)
>         libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb5dadfb000)
>         libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb5daa7a000)
>         libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb5da776000)
>         libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb5da55f000)
>         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb5da1c1000)
>         libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fb5d9f60000)
>         libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fb5d9b64000)
>         libboost_chrono.so.1.62.0 => /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.62.0 (0x00007fb5d995d000)
>         libboost_random.so.1.62.0 => /usr/lib/x86_64-linux-gnu/libboost_random.so.1.62.0 (0x00007fb5d9757000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007fb5dcf27000)
>         librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb5d954f000)
>         libicui18n.so.52 => /usr/lib/x86_64-linux-gnu/libicui18n.so.52 (0x00007fb5d913d000)
>         libicuuc.so.52 => /usr/lib/x86_64-linux-gnu/libicuuc.so.52 (0x00007fb5d8dbf000)
>         libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb5d8bbb000)
>         libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fb5d88a7000)
>         libicudata.so.52 => /usr/lib/x86_64-linux-gnu/libicudata.so.52 (0x00007fb5d703a000)
>         libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fb5d6dcc000)
> nutzer@server:~/fas/qBittorrent$ gdb /usr/lib/libtorrent-rasterbar.so.9
> GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
> Copyright (C) 2014 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "x86_64-linux-gnu".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
> <http://www.gnu.org/software/gdb/documentation/>.
> For help, type "help".
> Type "apropos word" to search for commands related to "word"...
> Reading symbols from /usr/lib/libtorrent-rasterbar.so.9...done.
> (gdb) quit
> nutzer@server:~/fas/qBittorrent$ gdb /usr/local/bin/qbittorrent-nox
> GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
> Copyright (C) 2014 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "x86_64-linux-gnu".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
> <http://www.gnu.org/software/gdb/documentation/>.
> For help, type "help".
> Type "apropos word" to search for commands related to "word"...
> Reading symbols from /usr/local/bin/qbittorrent-nox...done.
> (gdb) quit

@sledgehammer999 sorry to bother you, but maybe it's a qbittorent related question. Because from point of installation it does look fine. There are no missing symbol warnings from gdb.

**Comment by sledgehammer999** [comment]
What is the output of:
```
$ file /usr/local/bin/qbittorrent-nox
```
?
same for libtorrent.

**Comment by Falcosc** [comment]
```
/usr/local/bin/qbittorrent-nox: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=90056afabc4e59199aa611431e53a4201abbcaee, not stripped

nutzer@server:~/fas/qBittorrent$ file /usr/lib/libtorrent-rasterbar.so.9
/usr/lib/libtorrent-rasterbar.so.9: symbolic link to libtorrent-rasterbar.so.9.0.0

nutzer@server:~/fas/qBittorrent$ file /usr/lib/libtorrent-rasterbar.so.9.0.0
/usr/lib/libtorrent-rasterbar.so.9.0.0: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), 
```dynamically linked, BuildID[sha1]=e91eacbd2f942bcca9aa1e9dc829c62af504cf73, not stripped

**Comment by Falcosc** [comment]
here it is:

```
version: 1.1.1.0-1229491

file: 'torrent.cpp'
line: 9026
function: void libtorrent::torrent::check_invariant() const
expression: want_tick() == m_links[aux::session_interface::torrent_want_tick].in_list()

stack:
1: assert_fail(char const*, int, char const*, char const*, char const*, int)
2:
3:
4:
5:
6:
7:
8: clone

Catching signal: SIGINT
Exiting cleanly


*************************************************************
Catching signal: SIGABRT
Please file a bug report at http://bug.qbittorrent.org and provide the following information:

qBittorrent version: v3.3.10
stack trace:
  /lib/x86_64-linux-gnu/libc.so.6 : gsignal()+0xcf  [0x7fa8e8f7cfdf]
  /lib/x86_64-linux-gnu/libc.so.6 : abort()+0x16a  [0x7fa8e8f7e40a]
  /usr/lib/libtorrent-rasterbar.so.9 : assert_fail(char const*, int, char const*, char const*, char const*, int)+0xaf  [0x7fa8ead0faaf]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x2b0733  [0x7fa8eaf2b733]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x2bc6ba  [0x7fa8eaf376ba]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x30c5b5  [0x7fa8eaf875b5]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x20a739  [0x7fa8eae85739]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0xe2810  [0x7fa8ead5d810]
  /lib/x86_64-linux-gnu/libpthread.so.0 : ()+0x7464  [0x7fa8e9b8b464]
  /lib/x86_64-linux-gnu/libc.so.6 : clone()+0x5f  [0x7fa8e90329df]

  
nutzer@server:~$ cat trace.log | cut -d' ' -f3,5 | sed 's/()+//g' | xargs addr2line -p -C -f -e

libtorrent::torrent::check_invariant() const at /home/nutzer/fas/libtorrent/src/torrent.cpp:9027
libtorrent::torrent::auto_managed(bool) at /home/nutzer/fas/libtorrent/src/torrent.cpp:9484
boost::asio::detail::gcc_x86_fenced_block::sbarrier() at /usr/include/boost/asio/detail/gcc_x86_fenced_block.hpp:81
boost::asio::detail::task_io_service::work_cleanup::~work_cleanup() at /usr/include/boost/asio/detail/impl/task_io_service.ipp:63
boost::asio::detail::posix_thread::auto_func_base_ptr::~auto_func_base_ptr() at /usr/include/boost/asio/detail/posix_thread.hpp:67
```

**Comment by arvidn** [comment]
I believe this patch may fix this issue: https://github.com/arvidn/libtorrent/pull/1762

**Comment by Falcosc** [comment]
Sorry, that wasn't the reason. Do you want to log something else if the check found the failure?
```

version: 1.1.2.0-6e65851

file: 'torrent.cpp'
line: 9026
function: void libtorrent::torrent::check_invariant() const
expression: want_tick() == m_links[aux::session_interface::torrent_want_tick].in_list()

stack:
1: assert_fail(char const*, int, char const*, char const*, char const*, int)
2:
3:
4:
5:
6:
7:
8: clone

Catching signal: SIGINT
Exiting cleanly


*************************************************************
Catching signal: SIGABRT
Please file a bug report at http://bug.qbittorrent.org and provide the following information:

qBittorrent version: v3.4.0alpha
stack trace:
  /lib/x86_64-linux-gnu/libc.so.6 : gsignal()+0xcf  [0x7fb8065b8fdf]
  /lib/x86_64-linux-gnu/libc.so.6 : abort()+0x16a  [0x7fb8065ba40a]
  /usr/lib/libtorrent-rasterbar.so.9 : assert_fail(char const*, int, char const*, char const*, char const*, int)+0x9b  [0x7fb8083497cb]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x2a6fe4  [0x7fb80855dfe4]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x2b2b94  [0x7fb808569b94]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x300d7c  [0x7fb8085b7d7c]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x2042a5  [0x7fb8084bb2a5]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0xdf53f  [0x7fb80839653f]
  /lib/x86_64-linux-gnu/libpthread.so.0 : ()+0x7464  [0x7fb8071c7464]
  /lib/x86_64-linux-gnu/libc.so.6 : clone()+0x5f  [0x7fb80666e9df]

  
nutzer@server:~$ cat trace.log | cut -d' ' -f3,5 | sed 's/()+//g' | xargs addr2line -p -C -f -e
libtorrent::torrent::check_invariant() const at /home/nutzer/fas/libtorrent/src/torrent.cpp:9027
libtorrent::torrent::auto_managed(bool) at /home/nutzer/fas/libtorrent/src/torrent.cpp:9484
boost::asio::detail::gcc_x86_fenced_block::sbarrier() at /usr/include/boost/asio/detail/gcc_x86_fenced_block.hpp:81
boost::asio::detail::task_io_service::work_cleanup::~work_cleanup() at /usr/include/boost/asio/detail/impl/task_io_service.ipp:63
boost::asio::detail::posix_thread::auto_func_base_ptr::~auto_func_base_ptr() at /usr/include/boost/asio/detail/posix_thread.hpp:67
```

**Comment by Falcosc** [comment]
This does happen during picking up new torrents or already existing torrents.

**Comment by arvidn** [comment]
how do you build libtorrent? (speaking of why you don't get any symbols)

**Comment by Falcosc** [comment]
I have the symbols in pref, gdb and other tools. And I get them with addr2line.

I build libtorrent and qbittorent with make and did configure them with enable-debug
On top of that I did enable `-fno-omit-frame-pointer` for both and did check it with make -n

Installation was done by make install.

And I did move my qbittorent webui command calls to unique timestamps to locate the usecase which did force this assert failure:

> Add a existing torrent over watch dir to add a webseed url

This usecase does trigger the assert failure some times

**Comment by arvidn** [comment]
I see, it's probably a missing "-rdynamic" to the linker. try adding that to your ``LDFLAGS``. It's included in debug builds by the Jamfile

**Comment by Falcosc** [comment]
I don’t know if I need this `–rdynamic`only for libtorrent or for qbittorent too.
I did just build both with `-rdynamic` over LDFLAGS and did check the commands with `make -n`

Should this be included to our make configuration debug target?

I did enable this assert again to find out.

**Comment by arvidn** [comment]
I think it would be good for it to be included in debug builds, yes. It enables looking up symbols from stack traces

**Comment by Falcosc** [comment]
-rdynamic was not what we do miss:

```
version: 1.1.2.0-6e65851

file: 'torrent.cpp'
line: 9026
function: void libtorrent::torrent::check_invariant() const
expression: want_tick() == m_links[aux::session_interface::torrent_want_tick].in_list()

stack:
1: assert_fail(char const*, int, char const*, char const*, char const*, int)
2:
3:
4:
5:
6:
7:
8: clone

Catching signal: SIGINT
Exiting cleanly


*************************************************************
Catching signal: SIGABRT
Please file a bug report at http://bug.qbittorrent.org and provide the following information:

qBittorrent version: v3.4.0alpha
stack trace:
Saving resume data in "/home/nutzer/.local/share/data/qBittorrent/BT_backup/a3031464270b2e5cded17adb85fcb8576f677fda.fastresume"
  /lib/x86_64-linux-gnu/libc.so.6 : gsignal()+0xcf  [0x7f9a2e6c3fdf]
  /lib/x86_64-linux-gnu/libc.so.6 : abort()+0x16a  [0x7f9a2e6c540a]
  /usr/lib/libtorrent-rasterbar.so.9 : assert_fail(char const*, int, char const*, char const*, char const*, int)+0xaf  [0x7f9a30456aaf]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x2b04e3  [0x7f9a306724e3]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x2bc46a  [0x7f9a3067e46a]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x30c415  [0x7f9a306ce415]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x20a4e9  [0x7f9a305cc4e9]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0xe2810  [0x7f9a304a4810]
  /lib/x86_64-linux-gnu/libpthread.so.0 : ()+0x7464  [0x7f9a2f2d2464]
  /lib/x86_64-linux-gnu/libc.so.6 : clone()+0x5f  [0x7f9a2e7799df]

```

Sorry, I did forget addr2line but It should be the same stack anyway.

I did libtorrent make install before I did make qbittorent. And I did check make -n on both of them and could confirm it

libtorrent, one hit:
`echo "  CXXLD   " libtorrent-rasterbar.la;/bin/bash ../libtool --silent --tag=CXX   --mode=link g++  -g -O2 -ftemplate-depth=120 -fvisibility=hidden -fvisibility-inlines-hidden -version-info 9:0:0 -L/usr/lib/x86_64-linux-gnu -rdynamic -fvisibility=hidden -fvisibility-inlines-hidden -o libtorrent-rasterbar.la -rpath /usr/lib web_connection_base.lo alert.lo alert_manager.lo allocator.lo announce_entry.lo assert.lo bandwidth_limit.lo bandwidth_manager.lo bandwidth_queue_entry.lo bdecode.lo bitfield.lo bloom_filter.lo broadcast_socket.lo block_cache.lo bt_peer_connection.lo chained_buffer.lo choker.lo close_reason.lo ConvertUTF.lo cpuid.lo crc32c.lo create_torrent.lo disk_buffer_holder.lo disk_buffer_pool.lo disk_io_job.lo disk_io_thread.lo disk_job_pool.lo entry.lo enum_net.lo error_code.lo escape_string.lo file.lo file_pool.lo file_storage.lo fingerprint.lo gzip.lo hasher.lo hex.lo http_connection.lo http_parser.lo http_seed_connection.lo http_stream.lo http_tracker_connection.lo i2p_stream.lo identify_client.lo instantiate_connection.lo ip_filter.lo ip_voter.lo lazy_bdecode.lo lsd.lo lt_trackers.lo magnet_uri.lo merkle.lo metadata_transfer.lo mpi.lo natpmp.lo parse_url.lo part_file.lo pe_crypto.lo performance_counters.lo peer_connection.lo peer_connection_handle.lo peer_class.lo peer_class_set.lo piece_picker.lo platform_util.lo packet_buffer.lo proxy_base.lo peer_list.lo puff.lo random.lo receive_buffer.lo request_blocks.lo resolve_links.lo resolver.lo rss.lo session.lo session_call.lo session_handle.lo session_impl.lo session_settings.lo proxy_settings.lo settings_pack.lo smart_ban.lo socket_io.lo socket_type.lo socks5_stream.lo stat.lo stat_cache.lo storage.lo session_stats.lo string_util.lo thread.lo torrent.lo torrent_handle.lo torrent_info.lo torrent_peer.lo torrent_peer_allocator.lo torrent_status.lo time.lo timestamp_history.lo tracker_manager.lo udp_socket.lo udp_tracker_connection.lo upnp.lo ut_metadata.lo ut_pex.lo utf8.lo utp_socket_manager.lo utp_stream.lo web_peer_connection.lo xml_parse.lo version.lo file_progress.lo kademlia/dht_storage.lo kademlia/dht_tracker.lo kademlia/find_data.lo kademlia/put_data.lo kademlia/msg.lo kademlia/node.lo kademlia/node_entry.lo kademlia/node_id.lo kademlia/refresh.lo kademlia/routing_table.lo kademlia/rpc_manager.lo kademlia/traversal_algorithm.lo kademlia/dos_blocker.lo kademlia/get_peers.lo kademlia/get_item.lo kademlia/item.lo ../ed25519/src/add_scalar.lo ../ed25519/src/fe.lo ../ed25519/src/ge.lo ../ed25519/src/key_exchange.lo ../ed25519/src/keypair.lo ../ed25519/src/sc.lo ../ed25519/src/seed.lo ../ed25519/src/sha512.lo ../ed25519/src/sign.lo ../ed25519/src/verify.lo  -lboost_system -lssl -lcrypto  -lboost_chrono -lboost_random -lpthread `

qbittorent two hits:
`echo linking qbittorrent-nox && g++ -m64 -rdynamic -o qbittorrent-nox qtsinglecoreapplication.o qtlocalpeer.o application.o filelogger.o main.o tristatebool.o filesystemwatcher.o logger.o settingsstorage.o preferences.o iconprovider.o connection.o requestparser.o responsegenerator.o server.o responsebuilder.o dnsupdater.o downloadmanager.o downloadhandler.o geoipmanager.o portforwarder.o proxyconfigurationmanager.o reverseresolution.o smtp.o geoipdatabase.o infohash.o session.o sessionstatus.o cachestatus.o magneturi.o torrentinfo.o torrenthandle.o peerinfo.o trackerentry.o tracker.o torrentcreatorthread.o speedmonitor.o bandwidthscheduler.o filterparserthread.o statistics.o resumedatasavingmanager.o rssmanager.o rssfeed.o rssfolder.o rssarticle.o rssdownloadrule.o rssdownloadrulelist.o rssfile.o rssparser.o fs.o gzip.o misc.o random.o string.o torrentfileguard.o torrentfilter.o scanfoldersmodel.o searchengine.o webui.o btjson.o prefjson.o webapplication.o abstractwebapplication.o qrc_webui.o qrc_icons.o qrc_lang.o qrc_searchengine.o moc_qtsinglecoreapplication.o moc_qtlocalpeer.o moc_application.o moc_filelogger.o moc_filesystemwatcher.o moc_qinisettings.o moc_logger.o moc_settingsstorage.o moc_preferences.o moc_connection.o moc_server.o moc_dnsupdater.o moc_downloadmanager.o moc_downloadhandler.o moc_geoipmanager.o moc_portforwarder.o moc_proxyconfigurationmanager.o moc_reverseresolution.o moc_smtp.o moc_session.o moc_tracker.o moc_torrentcreatorthread.o moc_bandwidthscheduler.o moc_filterparserthread.o moc_statistics.o moc_resumedatasavingmanager.o moc_rssmanager.o moc_rssfeed.o moc_rssarticle.o moc_rssparser.o moc_torrentfileguard.o moc_scanfoldersmodel.o moc_searchengine.o moc_webui.o moc_abstractwebapplication.o   -L/usr/lib/x86_64-linux-gnu -rdynamic -lz -ltorrent-rasterbar -lboost_system -lQt5Xml -lQt5Network -lQt5Core -lpthread `
