### ISSUE TITLE
Python bindings: ImportError on import libtorrent

### ISSUE THREAD

**Issue by matiasw** [arvidn/libtorrent#1743]
libtorrent version (or branch): RC_1_1

platform/architecture: Debian Linux x64

compiler and compiler version: g++ (Debian 6.3.0-6) 6.3.0 20170205

Hi, and thanks for making libtorrent.
I am trying to build the library for use with Deluge 2.0.0.dev897. I followed the instructions at http://dev.deluge-torrent.org/wiki/Building/libtorrent , namely:

> ./configure --enable-python-binding --with-libiconv
> make
> checkinstall
> ldconfig 

However, this results in the following from `python`:

> Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
> [GCC 6.3.0 20170118] on linux2
> >>> import libtorrent
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: /usr/local/lib/python2.7/dist-packages/libtorrent.so: undefined symbol: _ZTIN5boost6python7objects21py_function_impl_baseE

So that's related to boost::python::objects::py_function_impl_base. `nm -g /usr/local/lib/python2.7/dist-packages/libtorrent.so | grep _ZTIN5boost6python7objects21py_function_impl_baseE` shows that this symbol is, indeed, Undefined.

What's wrong? How do I fix this?

**Comment by arvidn** [comment]
most likely you don't have boost installed, specifically boot.python

**Comment by matiasw** [comment]
I have the `libboost-python-dev` Debian package installed. Do I need something else?

**Comment by arvidn** [comment]
does its .so file define that symbol?

**Comment by arvidn** [comment]
it could also be that your boost.python installation is built for a different version of python as you're building the module for. iirc, py2 and py3 are incompatible

**Comment by matiasw** [comment]
How do I check?

**Comment by cas--** [comment]
There are no issues with building on Ubuntu so it's likely something with your setup needing fixed. Can you try the following.

```
./bootstrap --enable-python-binding
make
```

Now we can test the libtorrent python lib before install:
```
cd bindings/python/build/lib.linux-x86_64-2.7/
LD_LIBRARY_PATH=/home/ubuntu/projects/libtorrent/src/.libs python -c 'import libtorrent as lt; print lt.__version__'
```

**Comment by matiasw** [comment]
Same error.

**Comment by arvidn** [comment]
you may have to add the path to ``libboost_python.so`` to your ``LD_LIBRARY_PATH`` too

**Comment by cas--** [comment]
What is the last commit or tag that works?

**Comment by matiasw** [comment]
I tried:
> LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:/home/appas/code/libtorrent/src/.libs python -c 'import libtorrent as lt; print lt.__version__'

I have `/usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.62.0`, and there are 
>/usr/lib/x86_64-linux-gnu/libboost_python.so -> libboost_python-py27.so
>/usr/lib/x86_64-linux-gnu/libboost_python-py27.so -> libboost_python-py27.so.1.62.0

The last working state was when I had libtorrent installed using the package manager. In other words, I've not managed a working build from source after trying with the (then) latest master, as well as the libtorrent-1_1_1 release tag.

**Comment by arvidn** [comment]
my suspicion is that, when you build, headers from a different version of boost is picked up by the compiler. If, for instance, the function body of the missing symbol used to be defined by the library, but in boost-1.62 it was moved to the headers as inlined, it would no longer be exported by the .so, but the libtorrent bindings (if built against an older set of headers) would still expect it to be
