### ISSUE TITLE
Assert Fail: num_active_finished == m_torrent_lists[torrent_want_peers_finished].size()

### ISSUE THREAD

**Issue by Falcosc** [arvidn/libtorrent#1753]
libtorrent version (or branch):
RC_1_1 head with some skipped invariant checks

platform/architecture:
debian 64bit

compiler and compiler version:
gcc 6

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
6 hours after I did skipped the other assert failures, 3000 aktive torrents and maybe 0-3 downloading and 0-5 uploading torrents

```
version: 1.1.1.0-1229491

file: 'session_impl.cpp'
line: 7206
function: void libtorrent::aux::session_impl::check_invariant() const
expression: num_active_finished == m_torrent_lists[torrent_want_peers_finished].size()

stack:
1: assert_fail(char const*, int, char const*, char const*, char const*, int)
2:
3:
4:
5:
6:
7:
8:
9: clone

Catching signal: SIGINT
Exiting cleanly


*************************************************************
Catching signal: SIGABRT
Please file a bug report at http://bug.qbittorrent.org and provide the following information:

qBittorrent version: v3.3.10
stack trace:
  /lib/x86_64-linux-gnu/libc.so.6 : gsignal()+0xcf  [0x7f0c2e0e2fdf]
  /lib/x86_64-linux-gnu/libc.so.6 : abort()+0x16a  [0x7f0c2e0e440a]
  /usr/lib/libtorrent-rasterbar.so.9 : assert_fail(char const*, int, char const*, char const*, char const*, int)+0xaf  [0x7f0c2fe75aaf]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x24880e  [0x7f0c3002980e]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x26f694  [0x7f0c30050694]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x24c96d  [0x7f0c3002d96d]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x2165f6  [0x7f0c2fff75f6]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x20a699  [0x7f0c2ffeb699]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0xe2810  [0x7f0c2fec3810]
  /lib/x86_64-linux-gnu/libpthread.so.0 : ()+0x7464  [0x7f0c2ecf1464]
  /lib/x86_64-linux-gnu/libc.so.6 : clone()+0x5f  [0x7f0c2e1989df]
  
nutzer@server:~$ cat trace.log | cut -d' ' -f3,5 | sed 's/()+//g' | xargs addr2line -p -C -f -e
libtorrent::aux::session_impl::check_invariant() const at /home/nutzer/fas/libtorrent/src/session_impl.cpp:7213
libtorrent::invariant_checker_impl<libtorrent::aux::session_impl>::invariant_checker_impl(libtorrent::aux::session_impl const&) at /home/nutzer/fas/libtorrent/src/../include/libtorrent/invariant_check.hpp:49
libtorrent::single_threaded::is_single_thread() const at /home/nutzer/fas/libtorrent/src/../include/libtorrent/debug.hpp:178
boost::asio::detail::gcc_x86_fenced_block::sbarrier() at /usr/include/boost/asio/detail/gcc_x86_fenced_block.hpp:81
boost::asio::detail::task_io_service::work_cleanup::~work_cleanup() at /usr/include/boost/asio/detail/impl/task_io_service.ipp:63
boost::asio::detail::posix_thread::auto_func_base_ptr::~auto_func_base_ptr() at /usr/include/boost/asio/detail/posix_thread.hpp:67
```

**Comment by Falcosc** [comment]
Looks like something is missing in stack between
```
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x24c96d  [0x7f0c3002d96d]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x2165f6  [0x7f0c2fff75f6]
```

because `gcc_x86_fenced_block::sbarrier()` does not actually call `libtorrent::single_threaded::is_single_thread()`

Or is the is_sigle_thread() function bound to something which is triggered by `gcc_x86_fenced_block::sbarrier()` ?
Sorry @arvidn to bother you again, but I'm not sure if this stack could be correct or what I could do to improve collection of these unexpected states.

**Comment by arvidn** [comment]
hm.. yeah, that stack trace doesn't look right

**Comment by Falcosc** [comment]
Do you know how something like that could be possible?

**Comment by arvidn** [comment]
probably there's some edge where the number of finished torrents changes that's not covered when updating the torrent lists

**Comment by Falcosc** [comment]
I mean how the stack could be so wired. I just thought that there could be a kind of bind which does call our is_sigle_thread method.

This failure doesn't appear again during the last 3 days, I hope I did not skip to many invariant checks based on perf because the thread can't keep up with the amount of requests. I will push my changes after 8 hours, would be nice if you could check my skipped calls. I will give you a branch link if I'm ready. Maybe you find a importand check invariant call which should not be skipped. Currently I have a little bit of free CPU time for more checks.

**Comment by arvidn** [comment]
I take it you build debug builds?

**Comment by Falcosc** [comment]
It's a little bit off-topic but maybe still important

Here are my debug build adjustments
https://github.com/Falcosc/libtorrent/commit/327383f40395122477cc2d22e183c04c5cfd5dd6

Would be nice if you could tell me if 1 or 2 of these skippet invariant check calls would be very interesting for the project. But I guess I can't enable more then 2 of them at same time.

If you have more ideas how I could improve my error reports, I would like to follow them.
