### ISSUE TITLE
(RC_1_1): exceptions.KeyError: <class 'libtorrent.error_code'>, when adding new torrent into deluge

### ISSUE THREAD

**Issue by barmalej2** [arvidn/libtorrent#1754]
libtorrent version: 1.1.2, RC_1_1 git branch, revision: 3b359ab
deluge: 1.3.13, 1.3 stable git branch, revision: 25150f1
 boost version: 1.63.0
 python version: 2.7.13
 platform/architecture: armv5tel GNU/Linux, kernel 2.6.31.8
 compiler and compiler version: gcc 4.9.2,
 Step to reproduce case. Adding new torrent file to deluge for downloading, causes unexpected error output:

>  Unhandled Error
> Traceback (most recent call last):
>   File "/ffp/lib/python2.7/site-packages/deluge/main.py", line 241, in start_daemon
>     Daemon(options, args)
>   File "/ffp/lib/python2.7/site-packages/deluge/core/daemon.py", line 180, in __init__
>     reactor.run()
>   File "/ffp/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
>     self.mainLoop()
>   File "/ffp/lib/python2.7/site-packages/twisted/internet/base.py", line 1252, in mainLoop
>     self.runUntilCurrent()
> --- <exception caught here> ---
>   File "/ffp/lib/python2.7/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
>     call.func(*call.args, **call.kw)
>   File "/ffp/lib/python2.7/site-packages/deluge/core/rpcserver.py", line 324, in dispatch
>     self.sendData((RPC_RESPONSE, request_id, ret))
>   File "/ffp/lib/python2.7/site-packages/deluge/core/rpcserver.py", line 199, in sendData
>     self.transport.write(zlib.compress(rencode.dumps(data)))
>   File "/ffp/lib/python2.7/site-packages/deluge/rencode.py", line 391, in dumps
>     encode_func[type(x)](x, r)
>   File "/ffp/lib/python2.7/site-packages/deluge/rencode.py", line 338, in encode_list
>     encode_func[type(i)](i, r)
>   File "/ffp/lib/python2.7/site-packages/deluge/rencode.py", line 355, in encode_dict
>     encode_func[type(v)](v, r)
>   File "/ffp/lib/python2.7/site-packages/deluge/rencode.py", line 338, in encode_list
>     encode_func[type(i)](i, r)
>   File "/ffp/lib/python2.7/site-packages/deluge/rencode.py", line 350, in encode_dict
>     encode_func[type(v)](v, r)
> exceptions.KeyError: <class 'libtorrent.error_code'>
> 
Seems like libtorrent related issue, but I am not sure.  If it is unrelated, please close it.

**Comment by cas--** [comment]
@arvidn this is related to #1738 so I shall reply there.

**Comment by barmalej2** [comment]
Closing as solved in RC_1_1 branch commit: 2258b53
