### ISSUE TITLE
settings_pack upload_rate_limit/download_rate_limit 	

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#1773]
On the latest version it seems `upload_rate_limit/download_rate_limit` is not being respected and `set_upload_limit()/set_download_limit()` is being used.

**Comment by arvidn** [comment]
what do you mean by: "and set_upload_limit()/set_download_limit() is being used."?

**Comment by Col-blimp** [comment]
Well say `upload_rate_limit/download_rate_limit` is set to 1mb and the torrents `set_upload_limit()/set_download_limit()` is set to 5mb then the session allows 5mbs download instead of the 1mb global cap.

**Comment by arvidn** [comment]
does it work as expected if you set either the global rate limit or the per-torrent limit?
is it only when you set both it fails to respect the global rate?
does it still respect the per-torrent limit under this condition?
how is your ``settings_pack::rate_limit_utp`` setting set?
do you see a difference if you enable/disable uTP? (if you do, that may be a sign of uTP not being rate limited, by the above setting)

**Comment by Col-blimp** [comment]
`DEPRECATED_SET(rate_limit_utp, false, &session_impl::update_rate_limit_utp),` so its unavailable to me and does not appear in the documents of settings pack.

utp settings:

```
		SET(enable_outgoing_utp, true, nullptr),
		SET(enable_incoming_utp, true, nullptr),
		DEPRECATED_SET(rate_limit_utp, false, &session_impl::update_rate_limit_utp),
		SET(utp_target_delay, 100, nullptr),
		SET(utp_gain_factor, 3000, nullptr),
		SET(utp_min_timeout, 500, nullptr),
		SET(utp_syn_resends, 2, nullptr),
		SET(utp_fin_resends, 2, nullptr),
		SET(utp_num_resends, 3, nullptr),
		SET(utp_connect_timeout, 3000, nullptr),
		SET(utp_delayed_ack, 0, nullptr),
		SET(utp_loss_multiplier, 50, nullptr),
```

With `enable_outgoing_utp/enable_incoming_utp` set to false the behaviour is the same.

I was on a different device at the time I was reporting this, on a faster network both the global rate and the per torrent rate are ignored and libtorrent happily eats up all the bandwidth it can get.

If I make my test client use all default settings the issue is the same.

**Comment by arvidn** [comment]
which version of libtorrent are you using?

**Comment by Col-blimp** [comment]
1.1.2

**Comment by arvidn** [comment]
In a simple test of setting the global download rate, I cannot reproduce this.
when this happens, what's the ``read_state`` and ``write_state`` bits set to for your peers? (call ``torrent_handle::get_peer_info()``).

Have you tested this in ``client_test``? if so, these bitmasks are printed as "dln" in the "dn" and "up" columns when listing peers.

**Comment by Col-blimp** [comment]
read_state: 2
write_state: 0

this does not seem to change for any torrent, this suggests no bandwidth limits but there are global and per torrent, not getting any errors/exceptions here so is there anything else I can try?

**Comment by arvidn** [comment]
ok, the 2 means the limit does not apply. I take it the rate is higher than the limit during this time, so I'll take a look at what can cause it to not apply

**Comment by arvidn** [comment]
do you configure anything that has to do with peer classes?

**Comment by Col-blimp** [comment]
No, haven't touched peer classes, reading up on it just now, I assume I need to set a basic class to begin with.

**Comment by arvidn** [comment]
no, by default there are 3 peer classes, global, tcp-connections, local-network connections. It's possible to set the configuration to opt-out of those though.

Can you reproduce this in a minimal example? or client_test?

**Comment by Col-blimp** [comment]
You know having now built the bundled test client, that I should have done first, I get no issues. I'm not using Libtorrent in the main loop like the examples as I'm doing it like this: http://stackoverflow.com/a/32304103/3687449 and changing my settings function to this:

```
void set_global_upload(int speed) {
	settings_pack pack = this_session->get_settings();
	pack.set_int(settings_pack::upload_rate_limit , speed);
	this_session->apply_settings(pack);
}
```
fixes the problem.

Thanks.

**Comment by arvidn** [comment]
so, what was the problem?

**Comment by Col-blimp** [comment]
From when `settings_pack` arrived until the last build you did not need to `get_settings()` you could just create an object and then apply.
