### ISSUE TITLE
C API?

### ISSUE THREAD

**Issue by rweichler** [arvidn/libtorrent#1778]
I want to use this with LuaJIT. Is there a C API available for this? Or will I have to cdef the mangled symbols instead?

**Comment by arvidn** [comment]
there's no up-to-date C API. I don't think calling "mangled symbols" will be particularly helpful. An ABI is made up by more than just the calling convention and name mangling of symbols.

Please let me know if you get it to work or come up with any bindings.

**Comment by rweichler** [comment]
I ended up using the XML RPC, so I don't believe I will be making any strides toward direct Lua bindings. Sorry.
