### ISSUE TITLE
Question about magnet uri support

### ISSUE THREAD

**Issue by LiMinggang** [arvidn/libtorrent#1779]
**Please provide the following information**

libtorrent version (or branch):
1.1.2
platform/architecture:
Windows 7 X64
compiler and compiler version:
VS 2015
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I tried a magnet URI like below which does not has "tr", "ws", "dht".
magnet:?xt=urn:btih:28ADC238624D5727465ED2FDBEE1D8AD8D726782

So, the parse_magnet_uri returned a add_torrent_params object which url is empty.  When I tried to add it by calling session_impl::add_torrent, an exception was thrown by some function call inside it.

My question is:
Doese libtorrent support such kind of magnet uri? If supported, what extra step should I do with it?

BTW: basic magnet uri support has been tested in my project.

**Comment by Col-blimp** [comment]
Libtorrent works with that link and it downloads a certain file from 2016 at 1080p, something is wrong with your code.

You want something like this:

```
void add_magnet(std::string& magnet, std::string& path) {
	add_torrent_params t;
	error_code ec;

	parse_magnet_uri(magnet , t , ec);
	if ( ec ) {
		return;
	}

	add_torrent_params p;
	p.save_path = path;
	p.url = magnet;
	p.flags = add_torrent_params::flag_duplicate_is_error | add_torrent_params::flag_update_subscribe;
	this_session->async_add_torrent(p);
}
```

**Comment by LiMinggang** [comment]
Hi, Col-blimp, thanks for your response.

I just tried qtorrent and it works with the magnet uri. I found it used async_add_torrent too. I seemed that I should use it instead of add_torrent.

**Comment by arvidn** [comment]
could you provide some more information on the actual error you got?

**Comment by arvidn** [comment]
errors should be reported via alerts, so make sure you pop those and print them

**Comment by LiMinggang** [comment]
The error did be logged but does not make sense. It said an exception was thrown at a specific memory address. 
I have to change the code to use async_add_torrent anyway because the handle returned was invalid/empty while the code rely on the handle.

Will be back if I still meet problem with async_add_torrent.

**Comment by arvidn** [comment]
I doubt async_add_torrent would make a difference, but if it does, I would still like to know why it fails

**Comment by LiMinggang** [comment]
That's also my question. I found that async_add_torrent would call add_torrent finally with the same parameters passed. 

The whole exception message is like below:

Exception thrown at 0x000007FEFD2DA06D in bitswash-win32.exe: Microsoft C++ exception: libtorrent::libtorrent_exception at memory location 0x000000000024AB20.
11:21:10: Error: torrent has no metadata

Which should be thrown at one of the lines of below:

	torrent_handle session_impl::add_torrent(add_torrent_params const& p
		, error_code& ec)
	{
		// params is updated by add_torrent_impl()
		add_torrent_params params = p;
		boost::shared_ptr<torrent> torrent_ptr;
		bool added;
		boost::tie(torrent_ptr, added) = add_torrent_impl(params, ec);

		torrent_handle const handle(torrent_ptr);
		m_alerts.emplace_alert<add_torrent_alert>(handle, params, ec);

**Comment by LiMinggang** [comment]
@arvidn Should I call post_torrent_updates() periodically after async_add_torrent? I found the magnet uri stuck after adding.

**Comment by LiMinggang** [comment]
I found the root cause of the issue. It's a bug in my code. Close it.

**Comment by arvidn** [comment]
I would be interested in making the failure mode better, to make it more clear what the error is. Do you have any recommendations? the add_torrent_alert error just said "torrent has no metadata"?

**Comment by LiMinggang** [comment]
Actually, @arvidn,  I made a stupid mistake to initialize the add_torrent_params correctly but did not pass it to async_add_torrent but another wrong copy of add_torrent_params, which make the add_torrent failed finally with "Error: torrent has no metadata".

Now, I can download the torrent except that I could not get metadata_received_alert or metadata_failed_alert. I can get the download status by call torrent_handle.status(), eg, download_payload_rate, num_peers, num_seeds, etc.
And I also found the .fastresume and the downloaded data at the correct directory.

However, without the alert ---- metadata_received_alert, I don't know the correct time to save the torrent.

**Comment by LiMinggang** [comment]
Any, suggestion? did I made mistake to set the flags? I copied code from qtorrent but can not figure out what's wrong.
Will the flags matter? I tried flag_paused on/off. It make no difference.
		// Forced start
		//p.flags &= ~libtorrent::add_torrent_params::flag_paused;
		p.flags |= add_torrent_params::flag_paused;
		p.flags &= ~libtorrent::add_torrent_params::flag_auto_managed;
		// Solution to avoid accidental file writes
		p.flags |= libtorrent::add_torrent_params::flag_upload_mode;

**Comment by LiMinggang** [comment]
Is it because I set wrong alert category? I copied it from qbittorrent. Will try the config from client_test.
