### ISSUE TITLE
add_files()

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#1784]
Trying to create a torrent with Chinese characters in the file names, torrent structure:

```
这是一个测试字符串 (folder)
这是一个测试字符串.txt (file)
```
path:

`C:\Users\User\Desktop\这是一个测试字符串\这是一个测试字符串.txt`

Is there a bundled function with Libtorrent to get this `wstring` path to an acceptable format for `add_files()`?

I ask as I'm trying various methods from `boost::filesystem::path` and `std::experimental::filesystem::path` and `add_files()` when passed something it does not like simpley hangs and does not return and there is no error or assertion.

**Comment by ajax16384** [comment]
have you tried escpape_string.h convert_from_wstring()  ?

**Comment by Col-blimp** [comment]
Just did and it causes `add_files()` to hang if the source path or any file within the source path has non ascii characters, looking at this: https://sourceforge.net/p/libtorrent/mailman/message/20918181/ it seems `add_file()` has been modified to deal with this case and I dont know if `add_files()` existed at that point to change that as well or not.

I can walk the directory with and use `add_file()` but Im thinking `add_files()` should have an error code and not hang.

**Comment by ajax16384** [comment]
libTorrent master examples
````batch
D:\Test>dir /B /S
D:\Test\这是一个测试字符串
D:\Test\这是一个测试字符串\这是一个测试字符串.txt
````

````batch
cd D:\Test\这是一个测试字符串
.....examples\make_torrent.exe  . -o test.torrent
````
works without hanging

**Comment by Col-blimp** [comment]
alex, thanks, issue was with my file filter.
