### ISSUE TITLE
Encoding of the torrent alert message

### ISSUE THREAD

**Issue by LiMinggang** [arvidn/libtorrent#1790]
**Please provide the following information**

libtorrent version (or branch):
1.1.2/latest revision
platform/architecture:
Any
compiler and compiler version:
Any
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

What's the encoding used in the alert message? If not specified, is it possible to use UFT?

I saw lot of alien characters in the output.

**Comment by LiMinggang** [comment]
And the client in peer_info. Some clients, eg, utorrent, use non ascii characters.

**Comment by Col-blimp** [comment]
`utf8_wchar(peer_info->client)` you get `utf8_wchar` in `utf8.hpp`, most strings do tell you the encoding but that seems to be missing from the docs.

I was looking at the messages last night and it seems they are basic strings so any message with a file or torrent name with non ascii characters is garbled in the console.

**Comment by LiMinggang** [comment]
Thanks for your response. I'll try UTF8 first. I'm working on wxWidgets. So, the encoding issue would be fixed if I know the string encoding.

If the string was from local, it would be OK because wxWidgets would handle it for me and I will convert it to UTF8 before passing it to libtorrent.

**Comment by arvidn** [comment]
strings are supposed to be utf-8 encoded, both being passed into and returned from libtorrent.

**Comment by LiMinggang** [comment]
Thanks for your response!
