### ISSUE TITLE
Getting error while make Libtorrent 

### ISSUE THREAD

**Issue by immishaykh** [arvidn/libtorrent#1796]
**Please provide the following information**

libtorrent version (or branch): lib torrent 1.0

platform/architecture:ubantu 14.04 64 bit

compiler and compiler version:
root@ubuntu:/home/khan/libtorrent# make
Making all in include/libtorrent
make[1]: Entering directory `/home/khan/libtorrent/include/libtorrent'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/khan/libtorrent/include/libtorrent'
Making all in src
make[1]: Entering directory `/home/khan/libtorrent/src'
  CXX      web_connection_base.lo
  CXX      alert.lo
  CXX      alert_manager.lo
In file included from alert_manager.cpp:34:0:
../include/libtorrent/alert_manager.hpp:112:27: error: 'std::shared_ptr' has not been declared
   void add_extension(std::shared_ptr<plugin> ext);
                           ^
../include/libtorrent/alert_manager.hpp:112:37: error: expected ',' or '...' before '<' token
   void add_extension(std::shared_ptr<plugin> ext);
                                     ^
../include/libtorrent/alert_manager.hpp:155:13: error: 'shared_ptr' is not a member of 'std'
   std::list<std::shared_ptr<plugin>> m_ses_extensions;
             ^
../include/libtorrent/alert_manager.hpp:155:13: error: 'shared_ptr' is not a member of 'std'
../include/libtorrent/alert_manager.hpp:155:29: error: template argument 1 is invalid
   std::list<std::shared_ptr<plugin>> m_ses_extensions;
                             ^
../include/libtorrent/alert_manager.hpp:155:29: error: template argument 2 is invalid
../include/libtorrent/alert_manager.hpp:155:35: error: expected unqualified-id before '>' token
   std::list<std::shared_ptr<plugin>> m_ses_extensions;
                                   ^
alert_manager.cpp: In member function 'void libtorrent::alert_manager::maybe_notify(libtorrent::alert*, std::unique_lock<std::mutex>&)':
alert_manager.cpp:96:18: error: 'm_ses_extensions' was not declared in this scope
   for (auto& e : m_ses_extensions)
                  ^
alert_manager.cpp: At global scope:
alert_manager.cpp:116:7: error: prototype for 'void libtorrent::alert_manager::add_extension(std::shared_ptr<libtorrent::plugin>)' does not match any in class 'libtorrent::alert_manager'
  void alert_manager::add_extension(std::shared_ptr<plugin> ext)
       ^
In file included from alert_manager.cpp:34:0:
../include/libtorrent/alert_manager.hpp:112:8: error: candidate is: void libtorrent::alert_manager::add_extension(int)
   void add_extension(std::shared_ptr<plugin> ext);
        ^
make[1]: *** [alert_manager.lo] Error 1
make[1]: Leaving directory `/home/khan/libtorrent/src'
make: *** [all-recursive] Error 1
root@ubuntu:/home/khan/libtorrent# make
Making all in include/libtorrent
make[1]: Entering directory `/home/khan/libtorrent/include/libtorrent'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/khan/libtorrent/include/libtorrent'
Making all in src
make[1]: Entering directory `/home/khan/libtorrent/src'
  CXX      alert_manager.lo
In file included from alert_manager.cpp:34:0:
../include/libtorrent/alert_manager.hpp:112:27: error: 'std::shared_ptr' has not been declared
   void add_extension(std::shared_ptr<plugin> ext);
                           ^
../include/libtorrent/alert_manager.hpp:112:37: error: expected ',' or '...' before '<' token
   void add_extension(std::shared_ptr<plugin> ext);
                                     ^
../include/libtorrent/alert_manager.hpp:155:13: error: 'shared_ptr' is not a member of 'std'
   std::list<std::shared_ptr<plugin>> m_ses_extensions;
             ^
../include/libtorrent/alert_manager.hpp:155:13: error: 'shared_ptr' is not a member of 'std'
../include/libtorrent/alert_manager.hpp:155:29: error: template argument 1 is invalid
   std::list<std::shared_ptr<plugin>> m_ses_extensions;
                             ^
../include/libtorrent/alert_manager.hpp:155:29: error: template argument 2 is invalid
../include/libtorrent/alert_manager.hpp:155:35: error: expected unqualified-id before '>' token
   std::list<std::shared_ptr<plugin>> m_ses_extensions;
                                   ^
alert_manager.cpp: In member function 'void libtorrent::alert_manager::maybe_notify(libtorrent::alert*, std::unique_lock<std::mutex>&)':
alert_manager.cpp:96:18: error: 'm_ses_extensions' was not declared in this scope
   for (auto& e : m_ses_extensions)
                  ^
alert_manager.cpp: At global scope:
alert_manager.cpp:116:7: error: prototype for 'void libtorrent::alert_manager::add_extension(std::shared_ptr<libtorrent::plugin>)' does not match any in class 'libtorrent::alert_manager'
  void alert_manager::add_extension(std::shared_ptr<plugin> ext)
       ^
In file included from alert_manager.cpp:34:0:
../include/libtorrent/alert_manager.hpp:112:8: error: candidate is: void libtorrent::alert_manager::add_extension(int)
   void add_extension(std::shared_ptr<plugin> ext);
        ^
make[1]: *** [alert_manager.lo] Error 1
make[1]: Leaving directory `/home/khan/libtorrent/src'
make: *** [all-recursive] Error 1

**Comment by arvidn** [comment]
that's not libtorrent 1.0

This is the alert_manager.hpp line 112 from libtorrent 1.0:

https://github.com/arvidn/libtorrent/blob/libtorrent-1_0/include/libtorrent/alert_manager.hpp#L112

In fact, ``std::shared_ptr<>`` is a C++11 type and wasn't used until master (and hasn't been part of an official release yet)
