### ISSUE TITLE
VC++ 2017 error C2760: syntax error: expected ')' not ']'

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#1797]
master
![default](https://cloud.githubusercontent.com/assets/920705/23738494/62282dce-04aa-11e7-9e2e-363913ba162e.png)

**Comment by arvidn** [comment]
is there a reason to believe that this is not caused by a bug in visual studio? I take it this is not a final release, right?

**Comment by pavel-pimenov** [comment]
VC++ 2017 release
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.10.25017 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]

Hot fix aux::* operator []

![default](https://cloud.githubusercontent.com/assets/920705/23752088/004adfa8-04e5-11e7-8f0e-b9ba8f304f0e.png)

**Comment by arvidn** [comment]
that change is not correct. ``std::vector<bool>::operator[]`` does not return a ``bool&``.
is this a regression in visual studio then?

**Comment by pavel-pimenov** [comment]
I use std:;vector<bool> 

(https://github.com/pavel-pimenov/libtorrent/commit/38c3a7dea601f0169eb54dab7d36385fddc530dd)

Test for operator [] VC++online
http://webcompiler.cloudapp.net/

#include <iostream>
#include <vector>
using namespace std;
int main()
{
    vector<bool> v;
    v.push_back(true);
    cout << "v[0] = " << v[0] << endl; 
    v[0] = false;
    cout << "v[0] = " << v[0] << endl; 
}
Compiled with  /EHsc /nologo /W4
main.cpp
Compilation successful!
Total compilation time: 31ms
v[0] = 1
v[0] = 0
Total execution time: 750ms

**Comment by arvidn** [comment]
I don't understand what you're saying

**Comment by arvidn** [comment]
try this program, it does not print "bool":

```
#include <iostream>
#include <vector>
#include <typeinfo>

using namespace std;

int main()
{
   cout << typeid(decltype(std::vector<bool>()[0])).name() << endl; 
}
```

**Comment by pavel-pimenov** [comment]
so i temporary replaced `aux::vector<bool, xxx>` to `std::vector<bool>`

**Comment by ajax16384** [comment]
cout << typeid(decltype(std::vector<bool>()[0])).name() << endl; 
prints
````c++
class std::_Vb_reference<struct std::_Wrap_alloc<class std::allocator<unsigned int> > >
````

**Comment by ajax16384** [comment]
BTW boost still not compatible with vs2017 toolset

**Comment by arvidn** [comment]
I'm surprised they actually released vc2017.. I see lots of open source projects failing to build with it.

**Comment by ajax16384** [comment]
i found a way to use vs2017 community (without vs2015 installation) to use "old" toolset(2015) to build boost and libTorrent:
- check "VC++ 2015.3 v140 toolset(x86,x64)" upon VS2017 installation
- manually add HKLM:\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\SxS\VS7 "14.0" "C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\"
- put some stub at "C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\Common7\IDE\wdexpress.exe"

now boost bootstrap.bat can use old "toolset=msvc-14.0"

**Comment by pavel-pimenov** [comment]
@ajax16384 thank you
i build without error:
* Visual Studio 2017 + toolset  Windows XP (v141_xp)
* boost 1.62
* libtorrent-master

https://github.com/pavel-pimenov/flylinkdc-r5xx/commit/00592e72f1063f3b47eb0ed971c5bec3519058d1

**Comment by ajax16384** [comment]
there is another workaround:
before:
````c++
		auto operator[](IndexType idx) const -> decltype(this->base::operator[](underlying_index()))
````
after:
````c++
		auto operator[](IndexType idx) const -> decltype(auto)
````

**Comment by ajax16384** [comment]
will try to make PR to check if it's valid for non msvc

**Comment by arvidn** [comment]
that's a C++14 feature. since I'm trying to stick to C++11 (for now), ideally this workaround would only be enabled for the specific compiler that doesn't support the C++11 version

**Comment by ajax16384** [comment]
ok
