### ISSUE TITLE
Crash on calling torrent_handle APIs

### ISSUE THREAD

**Issue by LiMinggang** [arvidn/libtorrent#1799]
libtorrent version (or branch): 1.1.2
platform/architecture: Window7 X64
compiler and compiler version: VS2015 community

I tried to remove all the deprecated APIs by define TORRENT_NO_DEPRECATED and transfer the old API with new ones.

However, I stuck on using the torrent_handle returned by add_torrent_alert. There was no error, and the handler is valid with the correct information, such as the save path I set before call async_add_torrent.

However, it always crashed at calling API's of torrent_handler, eg, status(torrent_hande::query_save_path) or tried to set the file priorities.
Crash happened in the sync_call_ret. Anything wrong or any suggestion to me?

template <typename Ret>
Ret sync_call_ret(aux::session_impl& ses, boost::function<Ret(void)> f)
{
	bool done = false;
	Ret r;
	ses.get_io_service().dispatch(boost::bind(&fun_ret<Ret>
		, boost::ref(r)
		, boost::ref(done)
		, boost::ref(ses.cond)
		, boost::ref(ses.mut)
		, f));
	torrent_wait(done, ses);
	return r;
}

**Comment by arvidn** [comment]
what is the error in the crash? (segmentation fault?)
which variable or field access is causing it?
what's the call stack to that point?
which thread crashes? your client thread or the internal libtorrent thread?

**Comment by LiMinggang** [comment]
It should be in the internal libtorrent thread because it was called synchronized from the callback function I registered  by set_alert_notify(boost::bind(&BitTorrentSession::HandleTorrentAlert, this));

Will back with more information you queried.

**Comment by arvidn** [comment]
are you calling functions on a torrent_handle from inside the callback?
the ``set_alert_notify`` function is really just meant to notify your main thread, through whatever mechanism your main thread sleeps. (i.e. message to the message queue or an eventfd)

**Comment by LiMinggang** [comment]
Yes. It's not good. I'll change the messy code.

**Comment by LiMinggang** [comment]
Crash does not happen again after changing to notify the thread instead of call the function inside libtorrent thread
