### ISSUE TITLE
boost 1.64: error: string_view from a temporary string

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#1803]
1>q:\vc15\r5xx\libtorrent\src\storage_utils.cpp(266): error C2280: 'boost::basic_string_view<char,std::char_traits<char>>::basic_string_view<std::allocator<char>>(std::basic_string<char,std::char_traits<char>,std::allocator<char>> &&)': attempting to reference a deleted function
1>q:\vc15\r5xx\boost\boost\utility\string_view.hpp(100): note: see declaration of 'boost::basic_string_view<char,std::char_traits<char>>::basic_string_view'
1>q:\vc15\r5xx\boost\boost\utility\string_view.hpp(100): note: 'boost::basic_string_view<char,std::char_traits<char>>::basic_string_view<std::allocator<char>>(std::basic_string<char,std::char_traits<char>,std::allocator<char>> &&)': function was explicitly deleted
1>session_impl.cpp

![default](https://cloud.githubusercontent.com/assets/920705/23820838/920e3b4e-0632-11e7-82ce-bd3bd96b3b44.png)

boost\boost\utility\string_view.hpp:

#if !defined(BOOST_NO_CXX11_RVALUE_REFERENCES) && !defined(BOOST_NO_CXX11_DELETED_FUNCTIONS)
      // Constructing a string_view from a temporary string is a bad idea
      template<typename Allocator>
        basic_string_view(      std::basic_string<charT, traits, Allocator>&&)
          = delete;
#endif

**Comment by arvidn** [comment]
is this new in boost-1.64? is this the only place you get this error?

**Comment by pavel-pimenov** [comment]
yes, only one error.
#define BOOST_NO_CXX11_DELETED_FUNCTIONS - all ok.

i use
https://sourceforge.net/projects/boost/files/boost/snapshots/master/boost_1_64_0-snapshot.zip/download
boost-git-dev
https://github.com/boostorg/utility/blob/00f02167e35861bd11b8a9d6585444e9ef0b5172/include/boost/utility/string_view.hpp#L98

**Comment by SysMan-One** [comment]
Got the same compilation problem.

**Comment by ajax16384** [comment]
https://github.com/arvidn/libtorrent/pull/1814

**Comment by ajw107** [comment]
Just thought I'd add a note for people not used to compiling with boost that to add the `#define BOOST_NO_CXX11_DELETED_FUNCTIONS` to the whole project in one go without editing the files just add `define=BOOST_NO_CXX11_DELETED_FUNCTIONS` to your bjam command line.  For instance mine now looks like this:
`bjam boost-link=static dht=on encryption=on mutable-torrents=on crypto=libcrypto libtorrent-link=static link=static runtime-link=static character-set=unicode iconv=auto i2p=on release optimization=space include=C:\OpenSSL-win32\include linkflags=/LIBPATH:C:\OpenSSL-win32\lib -j%NUMBER_OF_PROCESSORS% define=BOOST_NO_CXX11_DELETED_FUNCTIONS --hash`

**Comment by arvidn** [comment]
my understanding is that boost 1.64 is still in beta, so there is a chance this will be fixed before the final release. Otherwise I suppose there should be a workaround in ``string_view.hpp``, perhaps by using ``boost::string_ref`` for that version of boost.

**Comment by pavel-pimenov** [comment]
boost 1.64 release (https://github.com/arvidn/libtorrent/pull/1814)
