### ISSUE TITLE
Query for new replacement for status().dht_nodes

### ISSUE THREAD

**Issue by LiMinggang** [arvidn/libtorrent#1807]
libtorrent version (or branch):1.1.2
platform/architecture:All
compiler and compiler version:All

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I replaced old APIs with new ones(TORRENT_NO_DEPRECATE). Copied some code snippet from the client_test example, such as dowload/upload rate of the session.
However, I did not found any example for the replacement of status().dht_nodes.

Any suggestions? Should I do a sum up after get the DHT routing table of the session like below?
#ifndef TORRENT_DISABLE_DHT
	if (dht_stats_alert* p = alert_cast<dht_stats_alert>(a))
	{
		dht_active_requests = p->active_requests;
		dht_routing_table = p->routing_table;
		return true;
	}
#endif

**Comment by Col-blimp** [comment]
http://www.rasterbar.com/products/libtorrent/reference-Core.html#session_stats_metrics()

With depreciated functions off you use the above then then get sent_payload_bytes/recv_payload_bytes from the session_stats_alert.

**Comment by LiMinggang** [comment]
Yes. I already did this by using the code snippet from the client_test.cpp. Just don't know how to calculate the number of dht_nodes of the session. I did not find any example from the client_test.cpp.

**Comment by Col-blimp** [comment]
alert dht_peers/dht_nodes in the same way you get sent_payload_bytes/recv_payload_bytes

**Comment by LiMinggang** [comment]
Do you mean dht_stats_alert?
I only found  active_requests and routing_table in it.

**Comment by Col-blimp** [comment]
I'm not doing the dht_stats alert at all as all I'm doing is when I do `session_stats_metrics()` to get up/down rate I get `dht_peers/dht_seeds` as well then on the main stats alert the dht counters are updated.

**Comment by LiMinggang** [comment]
Got you! Thanks!
