### ISSUE TITLE
Question about DHT, want, nodes/nodes6

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#1810]
libtorrent version (or branch): master

Hi @ssiloti, I have a few question about this, in the code `rcp_manage.cpp:L468`
```cpp
node& n = o->algorithm()->get_node();
if (!n.native_address(o->target_addr()))
{
	a["want"].list().push_back(entry(n.protocol_family_name()));
}
```
what I see is that you put only `want` if the target is IPv4 vs IPv6, but how is that possible? don't the DHT communicate only with nodes of the same protocol?

Later in `traversal_algorithm.cpp:L583`
```cpp
bdecode_node const n = r.dict_find_string(nodes_key);
```
what I see is that you get only nodes with the same protocol, with only `libtorrent` nodes, how it's supposed to work?

In `node::write_nodes_entries` you always write nodes, don't you risk always getting a message too big for UDP?

Thanks for your time

**Comment by ssiloti** [comment]
Most requests are only sent to nodes in the same address family, but bootstrap queries can be sent to any address.

I'm not sure what your confusion is with the second question.

The number of nodes entries written should be small enough that the packet never exceeds the typical MTU of UDP over Ethernet (i.e. slightly less than 1500 bytes). This is something which is enforced purely through convention so it's not as robust as it could be.

**Comment by aldenml** [comment]
Right, I missed the bootstrap queries, but looking at the code again, I don't see where a "bootstrap" could mix protocols for the same node. Could you help me here? Is `dht_state` bad designed?

I think I clarified myself my second question/confusion, I just want to confirm that the fact that `node::write_nodes_entries` writes nodes even if `want` **IS NOT THERE** is a key factor. Is that right?

**Comment by ssiloti** [comment]
Yes, if the `want` key is not present then it is implied that the requester wants nodes of the same address family as the request was sent to.

Bootsrap was intended to take nodes of any address family via the `nodes` parameter of `node::bootstrap` but I see that got blocked by 6c31ea3d44.

**Comment by aldenml** [comment]
Do you consider a priority to revert part of that to allow mixing protocols again in the bootstrap?

**Comment by ssiloti** [comment]
It should definitely be fixed, but it's not a big enough deal for me to drop what I'm working on to fix it if that's what you're asking.

**Comment by aldenml** [comment]
no, of course not :) it's for myself, to continue in the other PRs or put some time on this.
