### ISSUE TITLE
To upgrade to travis xcode7.3 image

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#1821]
libtorrent version (or branch): `master`

Finally I discovered the reason `brew` is failing with such a frequency in travis. The relevant documentation is here: https://github.com/travis-ci/travis-ci/issues/7456

Summary:
The `cache` feature uses `md5deep`. That program is not included in all images of old Mac OS (who knows why aren't they all equals). They install it with `brew` and that triggers a `brew update`. But the entire process of downloading the "cache" fails for multiple reasons (size one of them), leaving garbage and locks.

I checked the behavior in my account.

Easy solution is use the next (and default) version xcode7.3, but that requires changing the include of `openssl`, since it's already deprecated in that version. Future versions of xcode simply lack any `openssl` headers.

@arvidn what do you think about that?

**Comment by arvidn** [comment]
thanks for looking into this! I will merge your PR
