### ISSUE TITLE
Negative Amount of Seeds Shown

### ISSUE THREAD

**Issue by Mikaa** [arvidn/libtorrent#1822]
Deluge 1.3.14
libtorrent version : 1.1.2
compiler and compiler version:
boost 1.63.0 python 2.7.13
platform/architecture: 
Slackware x86_64 Linux

I see negative seeds connected [(ex. -3(614))](http://i.imgur.com/CWkWyKe.png)
Errors is gone from negative peers to negative seeds.

 #1640

**Comment by arvidn** [comment]
which field specifically is this?

**Comment by Mikaa** [comment]
Number of Seeders field.

**Comment by arvidn** [comment]
I believe this patch fixes it: https://github.com/arvidn/libtorrent/commit/f95f5b05c268b31c691e31b46b3f86e55f88f7cc
