### ISSUE TITLE
Python bindings issues with parse_magnet_uri

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#1837]
I have found a couple of issues with `parse_magnet_uri` in RC_1_1 (1.1.2).

First a bindings issue where you can't pass the result of `parse_magnet_uri` into `add_torrent` because there is no convertor for `lt.sha1_hash`.
```
import libtorrent as lt
sess = lt.session()
magnet = 'magnet:?xt=urn:btih:C6EIF4CCYDBTIJVG3APAGM7M4NDONCTI'
add_torrent_params = lt.parse_magnet_uri(magnet)
h = sess.add_torrent(add_torrent_params)
```

> Traceback (most recent call last):
>   File "<pyshell#97>", line 5, in <module>
>     h = sess.add_torrent(add_torrent_params)
> TypeError: No registered converter was able to produce a C++ rvalue of type bytes from this Python object of type sha1_hash

The workaround is to update the torrent params info_hash with `str(lt.sha1_hash)` however that results in a second issue where add the details to `add_torrent` returns an invalid info_hash:

```
import libtorrent as lt
sess = lt.session()
magnet = 'magnet:?xt=urn:btih:C6EIF4CCYDBTIJVG3APAGM7M4NDONCTI'
add_torrent_params = lt.parse_magnet_uri(magnet)
add_torrent_params['info_hash'] = str(add_torrent_params['info_hash'])
print(add_torrent_params['info_hash'])
h = sess.add_torrent(add_torrent_params)
print(h.info_hash())
```

> 178882f042c0c33426a6d81e0333ece346e68a68
> 3137383838326630343263306333333432366136

**Comment by arvidn** [comment]
does this look reasonable? https://github.com/arvidn/libtorrent/pull/1838

**Comment by arvidn** [comment]
I think the reason you get an invalid info-hash is because the ``sha1_hash`` constructor that takes a ``char const*`` expects it to be a binary hash, not hex-encoded.

I think this can be closed out, no?

**Comment by cas--** [comment]
I had an incline it was that. Been a bit too busy to test locally but since it passes test yep :-)
