### ISSUE TITLE
libtorrent restores deleted webseeds when add torrent with fastresume data.

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#184]
Expected behavior: use webseeds from fastresume data only. Or maybe there is some flag in ```add_torrent_params``` like ```flag_merge_resume_trackers```.
Related qBittorrent Issue: https://github.com/qbittorrent/qBittorrent/issues/3813.

**Comment by arvidn** [comment]
all webseeds are added from the .torrent file currently. this behaves just like trackers used to, before introducing the flag to specify a preference between the torrent file and the resume data.

Would it make sense to introduce a similar flag for web seeds?

flag_override_web_seeds

**Comment by glassez** [comment]
>Would it make sense to introduce a similar flag for web seeds?

>flag_merge_resume_web_seeds

Yes, please. Our users do not expect to see again those web seeds that they have previously deleted (even after restarting the session).

**Comment by arvidn** [comment]
any chance you could try out this patch?

https://github.com/arvidn/libtorrent/pull/185

**Comment by glassez** [comment]
>any chance you could try out this patch?

Ok. It works as expected. Waiting for release...

**Comment by arvidn** [comment]
merged into RC_1_0 and master

**Comment by glassez** [comment]
Thank you.
