### ISSUE TITLE
SSL Torrent

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#1844]
So with SSL torrents, torrent creates fine and works fine when the needed info is presented to `set_ssl_certificate()` but I think I'm missing something, no SSL info is saved to the resume data and no alert is generated once the needed SSL data is accepted and is valid so there is a loop of needing to enter the SSL info each time the torrent is restarted and upon any error with the `set_ssl_certificate()` info the errors are system errors so its not really a simple thing of using that as a way of knowing that the previous `set_ssl_certificate()` info is not fine to use again without prompting for more info, is this all by design or have I missed something?

**Comment by Col-blimp** [comment]
SSL looks setup as a kind of better private torrent solution but I'm wondering if it has merit to give the option of bundling the private key into the torrent so that the torrent itself is automatically SSL for cases where you just want the SSL protocol but aren't bothered about who has the private key?

**Comment by arvidn** [comment]
I'm not sure I fully follow your question.

Your private key is not saved in the resume data, that's correct. You're expected to save that in a better way, like in a keychain or encrypted. Although, you can provider password when loading it in libtorrent too.

As for error reporting. If loading the private key fails, the torrent will be set to an error state with the SSL error code.

The point of SSL torrents is to provide authentication. If you want to only have a single identity and give it to everyone, you may as well use symmetric crypto.

**Comment by Col-blimp** [comment]
Is there an ssl error category to determine ssl error from other errors?

What I was getting at is after setting all the required SSL details how do you know they are fine to use again for the next time that torrent is added?

**Comment by arvidn** [comment]
If you have a valid certificate (that hasn't expired) for a torrent (and you still have your private key) you should be good. However, in theory it's possible to revoke certificates, so it _could_ become invalid at any time.

**Comment by arvidn** [comment]
you get the ssl category from here: http://www.boost.org/doc/libs/1_63_0/doc/html/boost_asio/reference.html#boost_asio.reference.error__get_ssl_category

**Comment by Col-blimp** [comment]
Thanks.
