### ISSUE TITLE
Create Torrent add_http_seed

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#1852]
```
create_torrent t(...);
t.add_http_seed("http://www.whatever.com/seed.php");
```
Creating a torrent and adding in the http seed then the torrent creates fine but when the torrent is added to Libtorrent it crashes the client with no asserts.log

When trying to debug the issue when you add the torrent the system becomes unstable then after a bit you get this:

http://i.imgur.com/xNdYOiN.png

with no debugging info in the output and svchost.exe running at 100% disc usage.

**Comment by arvidn** [comment]
sounds like a bug in the debugger. you can stop the process?

**Comment by Col-blimp** [comment]
Well when debugging the system locks up till msvsmon.exe crashes, going back to v1.1.0 then the issue is still there,

**Comment by arvidn** [comment]
do you have a minimal program that reproduces this? It sounds like there's really something else causing the problem, especially since your debugger/system hangs.

**Comment by Col-blimp** [comment]
The sample of creating a torrent does it if you choose to add in any http_seed (any url not ending with /) but you know I can't figure it out at all but from the mailing list then the driver/system issue as you mentioned sounds credible when adding in a torrent with http_seed but when just creating one I dont think anything in the system is touched as its just adding in a list of strings.

**Comment by arvidn** [comment]
so the problem appears to be on the loading torrent-end of things then, not creating the torrent. Is that right?
Can you produce a torrent file that causes ``client_test`` or ``simple_client`` to hang? (the examples in libtorrent). If so, please post such torrent file and I'll check it out.

**Comment by Col-blimp** [comment]
It's on both creating and on loading so long as a http_seed is present/added.

I can't create one with libtorrent but here is one created elsewhere that gives the problem once loaded:  https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/debian-8.8.0-amd64-CD-1.iso.torrent

**Comment by arvidn** [comment]
oh, so when you create a torrent, where does things hang specifically? which call?

**Comment by Col-blimp** [comment]
on add_http_seed() is where things become hangy.

**Comment by arvidn** [comment]
how do you build libtorrent, and your client, and how do you link against libtorrent?
This sounds like a link incompatibility issue. Do you specify the same ``TORRENT_*`` defines when building the client as when building libtorrent?

**Comment by Col-blimp** [comment]
`Start-Process "$bjam" -ArgumentList "--hash toolset=msvc-14.0 boost-link=static asserts=production address-model=64 runtime-link=static deprecated-functions=off encryption=on ssl=openssl crypto=libcrypto link=static dht=on logging=off i2p=on variant=release" -RedirectStandardOutput C:\Libtorrent-64.log -NoNewWindow -Wait -WorkingDirectory $LIBTORRENT_ROOT`

and 

`Start-Process "$bjam" -ArgumentList "--hash toolset=msvc-14.0 boost-link=static asserts=production runtime-link=static deprecated-functions=off encryption=on ssl=openssl crypto=libcrypto link=static dht=on logging=off i2p=on variant=release" -RedirectStandardOutput C:\Libtorrent.log -NoNewWindow -Wait -WorkingDirectory $LIBTORRENT_ROOT`


Build and link like above with the debug versions of the same and I have put all Libtorrent features into the client and everything works except `http_seed` and merkle torrents (have another bug report for that) use the same defines.

It's quite an old issue as I've never had `http_seed` working since settings_pack arrived, I take it you had no problem with the sample torrent?

**Comment by arvidn** [comment]
that's right, no problem with that torrent. does client test (built with boost-build and ``link=static``) reproduce the problem for you too?

**Comment by Col-blimp** [comment]
I've got a little progress with this, using the torrent above then with (add_torrent_params):

`p.ti = std::make_shared<torrent_info>(file , std::ref(ec) , 0);
p.flags = add_torrent_params::flag_duplicate_is_error | add_torrent_params::flag_update_subscribe;
this_session->async_add_torrent(p);`

then `add_torrent_alert` goes through but on `pop_alerts()` in the try for the loop after I get "bad allocation" then no further alerts for that torrent however the webseed still keeps downloading the torrent and this is where it starts to hang.

If instead of adding the torrent straight to the session and you load the torrent then save the resume data with `write_resume_data_buf()` and then start the torrent from the resume file things work as expected.

Is it the case maybe that the torrent is put in an error state hence the no more info from `refresh_torrent_status` but the webseed is not being disconnected as the peers are when the torrent is in an error state?

**Comment by arvidn** [comment]
if you get an error that says "bad allocation", that sounds like a ``std::bad_alloc`` exception, i.e. that you're either out of memory, or there's an underflow bug causing an allocation to ask for too much memory. please try that again and make the debugger stop on exceptions being thrown. that should lead you right to where it happens.

Now, this error is also still consistent with my earlier theory of ABI incompatibility. For instance, is it possible that you're accidentally including libtorrent headers from an different version?

and yes, when a torrent ends up in the error state, very few things will make it emit alerts.
