### ISSUE TITLE
Clearing / configuring resolver cache

### ISSUE THREAD

**Issue by jberkel** [arvidn/libtorrent#1862]
**Please provide the following information**

libtorrent version (or branch):

1.1.2

platform/architecture:

iOS / OSX

compiler and compiler version:

Apple LLVM version 8.0.0 (clang-800.0.42.1)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I could not find a way to configure or clear the [resolver cache](https://github.com/arvidn/libtorrent/blob/1f9f588e75384df41beee5bfab58e143d8a38d54/src/resolver.cpp#L45-L45). The concrete use case are network configuration changes: I connect on a Nat64 enabled network, the resolver caches IPv6 addresses, I switch back to a IPv4 network. The next request will be made with the (now invalid) IPv6 address.

Therefore I'd like to disable the resolver cache completely or purge the contents on network config change. It does not seem to be possible to do this without changing the source code at the moment however.

**Comment by aldenml** [comment]
do you really need `1.1.2`? I'm asking because I would like to do something at it, but I'm not using `RC_1_1` anymore.

**Comment by jberkel** [comment]
@aldenml not necessarily. thanks for your offer to help! i also noticed your work on #1792 which is something I'm interested as well (my main platform is iOS).

**Comment by aldenml** [comment]
interesting to hear from someone in iOS, well, that PR still requires serious work

**Comment by jberkel** [comment]
Yes looks like it. I think a simple solution with `SCNetworkReachabilitySetCallback` would be preferable there, even if you don't get fine-grained network configuration details. Separate code paths for iOS / OSX would add substantial complexity.

**Comment by arvidn** [comment]
would it make sense to automatically clear the cache when network changes are discovered?
I recognize that the cache is a bit weird to have at all, but my experience is that it's quite common to have lots of tracker host names that can stall to lookup, and the conventional dns APIs don't really support aborting with a custom (short) timeout. I believe the cache mitigates these problems.

**Comment by jberkel** [comment]
@arvidn yes that would work. but being able to switch the cache off completely (setting max size = 0) would already help, I don't really need it since I run in a trusted environment with good OS caching support.

**Comment by aldenml** [comment]
@jberkel a PR for configuration is merged https://github.com/arvidn/libtorrent/pull/1878, I decided to use the timeout instead the size.

There is an open question about what to do on network changes, but I think that's outside the scope of this issue.

**Comment by jberkel** [comment]
@aldenml great, thanks, i'll give it a go.

**Comment by jberkel** [comment]
Making everything work with the master branch turned out to be a lot more work than expected, so 
I'll postpone testing this for now. Closing the issue anyway. Thanks!

**Comment by arvidn** [comment]
@jberkel if there's anything master is breaking that works in 1.1.x, it may be a compatibility oversight that I should fix. If you think so, please let me know

**Comment by jberkel** [comment]
@arvidn nothing was really breaking per se, just API changes where some deprecated methods have been removed, but that's expected anyway.
