### ISSUE TITLE
Libtorrent/qbittorrent destroys/doesn't save files

### ISSUE THREAD

**Issue by Blackclaws** [arvidn/libtorrent#1868]
**Please provide the following information**

libtorrent version (or branch):

1.0.11.0

platform/architecture:

Linux x86_64

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

See also: https://github.com/qbittorrent/qBittorrent/issues/6577

I think this might be a libtorrent related bug hence why I post here as well.

I use qbittorrent. I use it in the following setup:

qbittorrent saves torrents to an nfs share.

Now this setup has worked quite well for a while. I needed to disable OS disk cache in the beginning due to poor performance, however recently reenabling it has not negatively impacted performance for some reason. 

The problem is that qbittorrent shows a torrent as completed and starts seeding it. However rechecking said torrent yields large gaps in the files. That means that parts of the file have not been saved correctly for some reason. 

This can either take the form of a large contiguous chunk missing or of chunks all over a torrents missing.

Up to 80% of a single torrent have become corrupted this way. 

Reenabling OS disk cache seems to have alleviated the problem. However I also restarted qbittorrent in the meantime. So this might also be related to the program running for a long time.

I would like some help in figuring out what has caused this problem and what might be done to prevent other people from suffering the same fate.

**Comment by cas--** [comment]
I don't have much to add here but I have occasionally seen similar missing pieces after moving torrents around then rechecking and Deluge users have also reported this from time to time. Without being able to replicate it's a hard one to pin down.

**Comment by arvidn** [comment]
is there any chance that this happens at the disk driver or filesystem level?
@Blackclaws if you can reliably reproduce this, could you please try to disable the bittorrent cache (just set the size to 0) to see if that affects things?
Doing that will circumvent a lot of complex logic in libtorrent (which could have a bug like this). If the problem persists, I would be more likely to suspect a lower layer failure.

**Comment by rsgabriel** [comment]
>just set the size to 0

What kind of performance hit can you expect from doing this? Is this a long term solution?

**Comment by arvidn** [comment]
you could try setting the cache size to 1

**Comment by coolio2013** [comment]
Perhaps I can shed some light. I don't think it is related to caching.
A sign like a wide '-' similar to ASCII 196 in the directory can lead to this. It rechecks just fine after completion, but after moving the payload to another directory (same disk, NTFS), libtorrent v1.1.5.0 (from qbt v3.4.b2 onWindows XPSP3-32) shows the content of that directory as 0% (download and move have been done with libtorrent 1.0.x). Payload in that directory is existing and has been properly downloaded and saved.
I am unable to find out the real hex-code of that sign in the name of that directory. I only can tell it isn't ASCII 196. If necessary, I can provide the hash of the torrent.

**Comment by arvidn** [comment]
Are you saying that an oddly named directory will allow downloading, but not rechecking?

**Comment by arvidn** [comment]
Oh, I see. There was a move too. Perhaps it's a Unicode normalization issue. Perhaps the filesystem changes the code points in the name. That's still odd though, if it's the same disk. It should have done that the first time.

**Comment by coolio2013** [comment]
> Are you saying that an oddly named directory will allow downloading, but not rechecking?

Yes. With ASCII 196 (and the other strange character HEX96? in the directory) it doesn't check at all, without moving.

> ...changes the code points in the name

??
