### ISSUE TITLE
Question about removing libboost_system binary dependecy

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#1898]
libtorrent version: master

Hi, at this moment, the only binary dependency is `libboost_system`, but using `BOOST_ERROR_CODE_HEADER_ONLY` should allow for no such need, and that will free `libtorrent` from some building problems under tricky configurations.

Before doing anything about it, I want to ask if using "boost header-only" policy is something reasonable, or it's too much of a restriction?

**Comment by arvidn** [comment]
would it mean every client would have yo build with this macro defined as well?

**Comment by aldenml** [comment]
looking at it again, it seems that that's the case, maybe the right solution is somehow, use `std::error_code` instead and figure out how to translate `boost::asio` errors to `std::`

**Comment by arvidn** [comment]
I looked at that a while ago, but couldn't figure out a way to make asio use std::error_code

**Comment by aldenml** [comment]
Just as a note, I made some progress but it requires boost >= 1.56 (see https://github.com/boostorg/system/commit/2c620a4f3ac378b616b0be97b7c3ccc7d057e35e)

**Comment by aldenml** [comment]
As an update, in boost 1.69 `Boost.System is now header-only.` https://www.boost.org/doc/libs/1_69_0_beta1/libs/system/doc/html/system.html#changes_in_boost_1_69

@arvidn, now that travis support Ubuntu Xenial, do you think it's reasonable to up the minimum to 1.58?

**Comment by arvidn** [comment]
bumping minimum boost version seems reasonable.

regarding boost.system by the way, I've been interested in looking at what it would take to transition from boost.asio to the networking TS library. I think that would naturally transition error_code to be std::error_code too

**Comment by aldenml** [comment]
good, I will take a look at `boost >= 1.58` when I have some time.

Regarding networking TS library, are you talking about the one that I think didn't make it to c++17? or the implementation derived from asio?

**Comment by arvidn** [comment]
the latter. https://github.com/chriskohlhoff/networking-ts-impl

**Comment by aldenml** [comment]
Well, if you really trust using `networking-ts-impl` (and I see no reason not to), I rather integrate/use that than do some hack to get rid of `libboost_system`. My first questions are:

How do you prefer to use it in `libtorrent`, as a git submodule, as a complete copy of the project, or expect users to have it installed? How this impacts `libsimulator`?

**Comment by arvidn** [comment]
I think a submodule would work well. I would just have to make sure it's included in tarballs

**Comment by arvidn** [comment]
I'm tempted to land my free-list patch, which mitigates/hides some of the cost and latency of this, and release libtorrent-1.2.
Any improvements to this can be done in point-releases, as it doesn't affect the API (assuming we can fix this without adding back a switch to enabled the pool)
