### ISSUE TITLE
ses.num_loaded_torrents

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#1900]
`ses.num_loaded_torrents` appears to always be zero but is there a gauge for the paused state? 

Edit, `num_stopped_torrents` seems to be paused.

**Comment by arvidn** [comment]
``num_loaded_torrents`` refer to a deprecated feature where the metadata for a torrent could be evicted from RAM and re-loaded on-demand via a user-supplied load function. This feature is disabled by default and deprecated.

perhaps "stopped" should have been called "paused". There is no distinction between stopped and paused in libtorrent.

**Comment by Col-blimp** [comment]
Ahh, it read like it was the total amount of torrents, thanks.
