### ISSUE TITLE
Rechecking can result in unwanted tracker announce

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#192]
A long time ago we discussed these two issues but I forgot to raise a ticket...

1. When resume_data is lost/bad and torrent files are rechecked on restarting the session, users find that upon completion they announce to tracker as downloading. (I'm assuming originally seeding torrents here) [Deluge Ticket 1601](http://dev.deluge-torrent.org/ticket/1601)

2. A `force_recheck` on paused torrent requires `resume` for the recheck to start, again resulting in an announce before 're-pausing' the torrent. [Deluge Ticket 2376](http://dev.deluge-torrent.org/ticket/2376)

This is seen in all libtorrent versions up to 1.0

**Comment by arvidn** [comment]
Heh, I just discovered this bug in master last night (and fixed it, but the branch is not ready for merging yet).

https://github.com/arvidn/libtorrent/pull/167

**Comment by arvidn** [comment]
could you give this a try? https://github.com/arvidn/libtorrent/pull/195

**Comment by cas--** [comment]
It's late here so Ill have to be brief. I did a quick test and did not work for `force_recheck` and I am not sure I am seeing anything in that branch that fixes the announce issue. 

Just to clarify for the second issue this is what we do for a [force_recheck](https://github.com/deluge-torrent/deluge/blob/1.3-stable/deluge/core/torrent.py#L933):

    self.handle.force_recheck()
    self.handle.resume()
--- wait for [checked alert](https://github.com/deluge-torrent/deluge/blob/1.3-stable/deluge/core/torrentmanager.py#L979) ---

    self.handle.pause()

I think the issue here is that we need to resume the torrent to recheck it.

**Comment by arvidn** [comment]
I see. I thought that was only in master. Can you think of a way to fix that? (I think it's still useful to be able to pause a checking torrent).

**Comment by cas--** [comment]
I agree it's useful to pause a checking torrent however with a force_recheck the user is specifically wanting the torrent checked so libtorrent should be resuming and re-pausing the torrent without any network transfer (at a minimum don't announce to tracker). 

The same with rechecking on startup if the torrent is paused. Although maybe in this scenario the paused torrents are either ignored or kept in paused-checking state until resumed by user.

**Comment by arvidn** [comment]
The way I envisioned this to work in master was to make torrents auto-managed, put them at the end of the queue, recheck them and make sure the download queue is short enough that they won't be started after checking. Now, this does sound like a pretty complicated way of doing something simple.

perhaps I should just add a "latch", pause-after-checking that force-stop the torrent after checking completes (and clear the latch).

**Comment by arvidn** [comment]
I'm leaning towards a flag called "pause_when_ready". When set, any time the torrent transitions from a non-downloading/uploading state into a downloading/uploading state, it force-stops the torrent.

**Comment by arvidn** [comment]
please check this out (master only since it's ABI breaking): https://github.com/arvidn/libtorrent/pull/202

**Comment by arvidn** [comment]
merged into master

**Comment by cas--** [comment]
I've not tested it yet but that looks like a good solution, thanks!
