### ISSUE TITLE
Installing libtorrent Python in Windows

### ISSUE THREAD

**Issue by Mixanologos** [arvidn/libtorrent#1923]
**Please provide the following information**

libtorrent version (or branch):
1.2.0
platform/architecture:
Windows 7 64bit
compiler and compiler version:
Python 3.6
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
Trying to install the python library in windows using the instructions [here](https://github.com/arvidn/libtorrent/blob/master/docs/python_binding.rst#building-using-setup-py) 

After navigating to the setup.py file i use the following commands
```
python setup.py build
python setup.py install
```

In the Cmd window i get the following messages 
```
C:\Users\thomas\Desktop\libtorrent-master>python setup.py build
running build

C:\Users\thomas\Desktop\libtorrent-master>python setup.py install
running install
running build
running install_egg_info
Removing C:\Users\thomas\AppData\Local\Programs\Python\Python36-32\Lib\site-pac
kages\python_libtorrent-1.2.0-py3.6.egg-info
Writing C:\Users\thomas\AppData\Local\Programs\Python\Python36-32\Lib\site-pack
ages\python_libtorrent-1.2.0-py3.6.egg-info

```
What else do i need to do?Because trying to import the libtorrent library comes up with this message
`>>> import libtorrent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'libtorrent'
>>>`

**Comment by arvidn** [comment]
which version of visual studio does one need to use when building modules for python3.6?
it could be an ABI compatibility issue. many years ago it used to be visual studio 2009, but I would be surprised if that's still the official version.

**Comment by Mixanologos** [comment]
I have no idea.Also,tried installing the library in linux where python 2.7 is installed and the installation worked flawlessly using this simple command `sudo apt-get install python-libtorrent`.

Any advice on how to progress in windows?

**Comment by arvidn** [comment]
you could take a look at the ``appveyor.yml`` to see how it's built and run there (on windows).
It's not using ``setup.py`` though. Perhaps there's some opportunity to improve the setup script.

**Comment by happyleibniz** [comment]
there is something wrong...
PS C:\Users\Happyleibniz\Downloads\Compressed\libtorrent-2.0.9_2\libtorrent-2.0.9> python setup.py build
running build
running build_ext
error: [WinError 2] The system cannot find the file specified
PS C:\Users\Happyleibniz\Downloads\Compressed\libtorrent-2.0.9_2\libtorrent-2.0.9>
i am using the attached file:
[libtorrent-2.0.9.zip](https://github.com/arvidn/libtorrent/files/12341043/libtorrent-2.0.9.zip)

**Comment by happyleibniz** [comment]
i also used ubuntu:
happyleibniz@ubuntu:~$ sudo apt-get install python-libtorrent
[sudo] password for happyleibniz: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-libtorrent
happyleibniz@ubuntu:~$

**Comment by hKJGkUs76A7m** [comment]
I first used cmake & ninja to build the entire project, and then used b2 to build the python version of libtorrent. Then I used setup.py to install it normally. So I think I should build the whole project first, then build the python version with b2, and then use setup.py install. Please check if this is the problem.
