### ISSUE TITLE
create torrent files failed but still downloading

### ISSUE THREAD

**Issue by hustshego** [arvidn/libtorrent#1926]
**Please provide the following information**

libtorrent version (or branch):libtorrent_1-1-1

platform/architecture:ios

compiler and compiler version:

If I download a torrent contains multi-files, it works well on iphone simulator(attachment picture)
but fails on device, which can't create file paths and the files.(I have downloaded the container, and see nothing there)
for example, as shown below (created on simulator)
<img width="501" alt="screen shot 2017-04-18 at 10 34 50 pm" src="https://cloud.githubusercontent.com/assets/3444450/25136331/508a3c68-2487-11e7-8e9e-93afc4c43909.png">
and torrent is still downloading the files on device, however no such file or directory, unless i remove the torrent from session

My question is how can I capture this kind of error? file_error_alert report nothing.
or any idea what's happening?

**Comment by arvidn** [comment]
the torrent itself should have an error state reported in torrent_status. I would also expect you to get error alerts, specifically file_error_alert. Are you saying you get those alerts, but the error is "no error" or are you saying you don't get the error alert?

if the latter, do you get any alerts?
did you perhaps accidentally disable error alerts in the alert_mask?

You say the failure on the device is because of "can't create file paths and the files", how do you know that if you don't see any error reporting?

**Comment by hustshego** [comment]
alert_mask:  sett.set_int(settings_pack::alert_mask, alert::category_t::all_categories);
I got no alert.

I know no paths and files created by connecting iphone to Xcode and select Window in Xcode, then Devices->my phone->Installed Apps->Download Containers...

torrent_status like this:
(lldb) p status
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.
(libtorrent::torrent_status) $0 = {
  handle = {
    m_torrent = {
      px = 0x000000013e272220
      pn = {
        pi_ = 0x000000013e272200
      }
    }
  }
  error = ""
  errc = (m_val = 0, m_cat = 0x00000001014843a0)
  error_file = -1
  save_path = "/var/mobile/Containers/Data/Application/23AC98E7-EDAE-4272-84DB-AC1BED60DF70/Library/Caches/Downloads"
  name = "내 여자의 맛있는 불륜 - 엑기스"
  torrent_file = {
    px = 0x000000013ddc45c0
    pn = {
      pi_ = 0x000000013ddc45a0
    }
  }
  next_announce = (__rep_ = 0)
  announce_interval = (__rep_ = 0)
  current_tracker = "udp://tracker.leechers-paradise.org:6969"
  total_download = 9146663
  total_upload = 3293785
  total_payload_download = 9051114
  total_payload_upload = 3187171
  total_failed_bytes = 0
  total_redundant_bytes = 130157
  pieces = {
    m_buf = 0x00000001702981f4
  }
  verified_pieces = {
    m_buf = 0x0000000000000000
  }
  total_done = 8810067
  total_wanted_done = 8810067
  total_wanted = 339690399
  all_time_upload = 3187171
  all_time_download = 9051114
  added_time = 1492565015
  completed_time = 0
  last_seen_complete = 1492565245
  storage_mode = storage_mode_allocate
  progress = 0.0259349998
  progress_ppm = 25935
  queue_position = 0
  download_rate = 67520
  upload_rate = 38197
  download_payload_rate = 63739
  upload_payload_rate = 34273
  num_seeds = 21
  num_peers = 22
  num_complete = 72
  num_incomplete = 15
  list_seeds = 75
  list_peers = 279
  connect_candidates = 248
  num_pieces = 7
  distributed_full_copies = 20
  distributed_fraction = 506
  distributed_copies = 20.5060005
  block_size = 16384
  num_uploads = 1
  num_connections = 24
  uploads_limit = -1
  connections_limit = -1
  up_bandwidth_queue = 0
  down_bandwidth_queue = 0
  time_since_upload = 0
  time_since_download = 1
  active_time = 230
  finished_time = 0
  seeding_time = 0
  seed_rank = 0
  last_scrape = 229
  priority = 0
  state = downloading
  need_save_resume = true
  ip_filter_applies = true
  upload_mode = false
  share_mode = false
  super_seeding = false
  paused = false
  auto_managed = true
  sequential_download = false
  is_seeding = false
  is_finished = false
  has_metadata = true
  has_incoming = true
  seed_mode = false
  moving_storage = false
  is_loaded = true
  announcing_to_trackers = true
  announcing_to_lsd = true
  announcing_to_dht = true
  stop_when_ready = false
  info_hash = {
    m_number = ([0] = 1841572511, [1] = 3327279404, [2] = 3452021907, [3] = 860735480, [4] = 758711127)
  }
}

**Comment by arvidn** [comment]
did you look in this directory?

/var/mobile/Containers/Data/Application/23AC98E7-EDAE-4272-84DB-AC1BED60DF70/Library/Caches/Downloads

**Comment by hustshego** [comment]
yes, there is nothing there.

**Comment by arvidn** [comment]
you could set breakpoints at calls to ``pwritev``, ``pwrite``, and ``write`` in ``storage.cpp`` to see if they are called at all.

Writing to disk is delayed a little bit as blocks are put in the cache first.

It's also possible the data you get from peers is corrupt and pieces fail the hash check. That could also prevent them from being written to disk.

**Comment by hustshego** [comment]
let me describe my question more clearly.

switch to iphone simulator

- for all kinds of torrent/magnet, my code works well on iphone simulator. it'll create torrent files or paths on disk immediately and download them without problem.

switch to iphone device

- for some kinds of torrent/magnet (root path have no sub directories and only files) it will be success too on iphone device. both create file/directory and download are OK.

- for other kinds of torrent/magnet(root path containing sub directories as attached picture above shown or have no root path), no file or paths created on iphone device, file_error_alert not be called.
the torrent downloading is not paused.

I'll debug storage.cpp as you said.

**Comment by hustshego** [comment]
It takes me much effort to track this bug.
if torrent file path or file name contains korean character
In file.cpp->create_directory->int ret = mkdir(n.c_str(), 0777)
ret = 0 however, no directory will be created in device. so I got no alert. it looks like OK.
I've tried russian, japanese, chinese, even 😄 characters as file path, ret = 0, and the directory will be created fine. the same as file name.

maybe you can close this issue.

**Comment by arvidn** [comment]
it doesn't sound like it's resolved though.
Also, I would expect any file to be attempted to be created in this directory to fail, and issue an alert.

**Comment by hustshego** [comment]
std::string n = "/var/mobile/Containers/Data/Application/3E8AEAB3-2438-4C60-9BB7-913C0D6F8CDE/Library/Caches/Downloads/내 여자의 맛있는 불륜 - 엑기스/맛있는 워킹걸.2017.1080P.FHD - 엑기스/"
(lldb) p n.c_str() (const value_type *) $2 = 0x00000001707856f0 "/var/mobile/Containers/Data/Application/3E8AEAB3-2438-4C60-9BB7-913C0D6F8CDE/Library/Caches/Downloads/\xffffffeb\xffffff82\xffffffb4 \xffffffec\xffffff97\xffffffac\xffffffec\xffffff9e\xffffff90\xffffffec\xffffff9d\xffffff98 \xffffffeb\xffffffa7\xffffff9b\xffffffec\xffffff9e\xffffff88\xffffffeb\xffffff8a\xffffff94 \xffffffeb\xffffffb6\xffffff88\xffffffeb\xffffffa5\xffffff9c - \xffffffec\xffffff97\xffffff91\xffffffea\xffffffb8\xffffffb0\xffffffec\xffffff8a\xffffffa4/\xffffffeb\xffffffa7\xffffff9b\xffffffec\xffffff9e\xffffff88\xffffffeb\xffffff8a\xffffff94 \xffffffec\xffffff9b\xffffff8c\xffffffed\xffffff82\xffffffb9\xffffffea\xffffffb1\xffffffb8.2017.1080P.FHD - \xffffffec\xffffff97\xffffff91\xffffffea\xffffffb8\xffffffb0\xffffffec\xffffff8a\xffffffa4/"

when using NSFileManager to create the directory, the bytes sequence is like this:
 (lldb) p [path UTF8String] (char *) $5 = 0x00000001701fd130 "\xffffffe1\xffffff84\xffffff82\xffffffe1\xffffff85\xffffffa2 \xffffffe1\xffffff84\xffffff8b\xffffffe1\xffffff85\xffffffa7\xffffffe1\xffffff84\xffffff8c\xffffffe1\xffffff85\xffffffa1\xffffffe1\xffffff84\xffffff8b\xffffffe1\xffffff85\xffffffb4 \xffffffe1\xffffff84\xffffff86\xffffffe1\xffffff85\xffffffa1\xffffffe1\xffffff86\xffffffba\xffffffe1\xffffff84\xffffff8b\xffffffe1\xffffff85\xffffffb5\xffffffe1\xffffff86\xffffffbb\xffffffe1\xffffff84\xffffff82\xffffffe1\xffffff85\xffffffb3\xffffffe1\xffffff86\xffffffab \xffffffe1\xffffff84\xffffff87\xffffffe1\xffffff85\xffffffae\xffffffe1\xffffff86\xffffffaf\xffffffe1\xffffff84\xffffff85\xffffffe1\xffffff85\xffffffb2\xffffffe1\xffffff86\xffffffab - \xffffffe1\xffffff84\xffffff8b\xffffffe1\xffffff85\xffffffa6\xffffffe1\xffffff86\xffffffa8\xffffffe1\xffffff84\xffffff80\xffffffe1\xffffff85\xffffffb5\xffffffe1\xffffff84\xffffff89\xffffffe1\xffffff85\xffffffb3/\xffffffe1\xffffff84\xffffff86\xffffffe1\xffffff85\xffffffa1\xffffffe1\xffffff86\xffffffba\xffffffe1\xffffff84\xffffff8b\xffffffe1\xffffff85\xffffffb5\xffffffe1\xffffff86\xffffffbb\xffffffe1\xffffff84\xffffff82\xffffffe1\xffffff85\xffffffb3\xffffffe1\xffffff86\xffffffab \xffffffe1\xffffff84\xffffff8b\xffffffe1\xffffff85\xffffffaf\xffffffe1\xffffff84\xffffff8f\xffffffe1\xffffff85\xffffffb5\xffffffe1\xffffff86\xffffffbc\xffffffe1\xffffff84\xffffff80\xffffffe1\xffffff85\xffffffa5\xffffffe1\xffffff86\xffffffaf.2017.1080P.FHD - \xffffffe1\xffffff84\xffffff8b\xffffffe1\xffffff85\xffffffa6\xffffffe1\xffffff86\xffffffa8\xffffffe1\xffffff84\xffffff80\xffffffe1\xffffff85\xffffffb5\xffffffe1\xffffff84\xffffff89\xffffffe1\xffffff85\xffffffb3"

So, the solution is convert_to_native(f), do the convert actually, not just return itself back.

**Comment by arvidn** [comment]
so, the string literal you specify is proper utf-8?
Which of the strings are wrong and what's wrong with it?
I wouldn't expect a string literal to necessarily be utf-8. But macOS uses utf-8 as its locale, and so does libtorrent, so there shouldn't be any conversion necessary as long as the input strings are utf8 consistently

**Comment by hustshego** [comment]
\xffffffe1\xffffff84\xffffff82\xffffffe1\xffffff85\xffffffa2 is the same thing to \xffffffeb\xffffff82\xffffffb4 
both of them are 내
I've found an appropriate way to solve this problem. not changing the libtorrent
on app level, th.rename_file(i, new_name); can avoid this issue.
Thanks arvidn

**Comment by arvidn** [comment]
If you don't mind, I would still like to understand the underlying problem. Is the .torrent file invalid? libtorrent does some amount of validation of UTF-8 encoding to catch at least invalid encoding.

Btw, what you're printing doesn't look quite right, or not printed right. It looks like you're sign-extending 8-bit characters into integers. Assuming all those 0xff prefixes are not supposed to be there, is either of those sequences invalid? or is it the case that iOS is especially strict in expecting normalized utf-8?

**Comment by hustshego** [comment]
FYI
\xffffffe1\xffffff84\xffffff82\xffffffe1\xffffff85\xffffffa2 really is \xe1\x84\x82\xe1\x85\xa2, 
and \xffffffeb\xffffff82\xffffffb4 really is \xeb\x82\xb4
ios only recongize \xe1\x84\x82\xe1\x85\xa2 not \xeb\x82\xb4 ,which libtorrent n.c_str() printed.
however, it's valid. both of the two ways are valid. because korea is combing characters.

**Comment by arvidn** [comment]
so perhaps the filesystem on iOS requires normalized unicode strings then (to expand combined characters), does that sounds plausible?
