### ISSUE TITLE
Questions about tracker connection logic

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#1930]
libtorrent version: `master`

Hi, I'm having a problem with the `session` shutdown in Windows, it blocks for a while (even minutes) in the `session` destructor. I narrowed the problem to the fact that having a non-working tracker in a torrent increase this time significatively.

My questions are:

- Where exactly the destructor waits for the final trackers requests (with `tracker_request::stopped`) to finish?
- Why the partitioning of endpoints in `http_connection::on_resolve` is only done if `m_bind_addr != address_v4::any()`?
- Any idea of why this is happening only in Windows?

Thanks

**Comment by arvidn** [comment]
To have libtorrent print out the outstanding operations it's waiting on when shutting down, build with ``TORRENT_ASIO_DEBUGGING`` defined, or ``asio-debugging=on`` when building with boost-build.

Normally, ``io_service::run()`` blocks until there are no more outstanding operations.

**Comment by aldenml** [comment]
Thanks @arvidn, I can't replicate the issue in every windows btw. Closing this for now.
