### ISSUE TITLE
OpenSSL 1.1.0+ have changed library names in windows

### ISSUE THREAD

**Issue by ajw107** [arvidn/libtorrent#1931]
**Please provide the following information**

libtorrent version (or branch): master

platform/architecture: windows 10 x64

compiler and compiler version: visual studio 2008

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
Since version 1.1.0 OpenSSL have changed their library names from:
libeay32.dll -> libcrypto.dll
ssleay32.dll -> libssl.dll
this can be solved by move/copy/mklink ing the libraries, but thought I should add an issue on here so people can easily find the solution when compiling their own version of libtorrent
The issue is also being discussed here, but I'm not sure if they've solved it yet:
https://github.com/curl/curl/issues/984

**Comment by arvidn** [comment]
perhaps there should be a feature in the Jamfile to specify the openssl version, to make it pick the right names

**Comment by arvidn** [comment]
does this work? https://github.com/arvidn/libtorrent/pull/2147

**Comment by cas--** [comment]
It does not seem to be working with OpenSSL 1.1. I switched to specifying the paths to use Appveyor provided openssl:

![appveyor-openssl](https://user-images.githubusercontent.com/606038/48939379-f3471200-ef0b-11e8-83dd-43f7a3096221.png)
 
And 1.0 works with:

     openssl-include=C:\\OpenSSL-Win64\\include openssl-lib=C:\\OpenSSL-Win64\\lib

But replacing with 1.1 doesn't:

    openssl-include=C:\\OpenSSL-v11-Win64\\include openssl-lib=C:\\OpenSSL-v11-Win64\\lib

```
msvc.link.dll ..\..\bin\ec2084d46409f49ef045c43244e95042\torrent.dll
LINK : fatal error LNK1181: cannot open input file 'crypto.lib'
        call "C:\Users\appveyor\AppData\Local\Temp\1\b2_msvc_14.0_vcvarsall_amd64.cmd" >nul
link /NOLOGO /INCREMENTAL:NO /DLL /MACHINE:X64 /MANIFEST /subsystem:console /out:"..\..\bin\ec2084d46409f49ef045c43244e95042\torrent.dll" /IMPLIB:"..\..\bin\ec2084d46409f49ef045c43244e95042\torrent.lib" /LIBPATH:"C:\OpenSSL-v11-Win64\lib"  /OPT:ICF=5 /OPT:REF @"..\..\bin\ec2084d46409f49ef045c43244e95042\torrent.dll.rsp"
        if %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%
```
https://ci.appveyor.com/project/cas--/libtorrent/builds/20499246#L1109

It seems to be a naming issue i.e. why is it looking for `crypto.lib` not `libcrypto.lib`?

**Comment by arvidn** [comment]
does this solve the problem? https://github.com/arvidn/libtorrent/pull/3490

**Comment by ajw107** [comment]
Yeah, the last fix works great.  Sorry I didn't notice the other messages (ironically just noticed these because I'm trying to compile it again and hit the same error).
