### ISSUE TITLE
API/ABI changes review for libtorrent

### ISSUE THREAD

**Issue by lvc** [arvidn/libtorrent#1947]
The review of API/ABI changes for libtorrent since 0_16_17 version: https://abi-laboratory.pro/tracker/timeline/libtorrent/

Created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker. Hope it will be helpful for users and maintainers of the library.

![libtorrent-1](https://cloud.githubusercontent.com/assets/1517837/25386152/6980f996-29d7-11e7-9bc8-85c9ea0ac15f.png)
![libtorrent-2](https://cloud.githubusercontent.com/assets/1517837/25386648/1e3d2ae8-29d9-11e7-81bc-9e3e4addffc7.png)

## Environment
* Linux x86_64
* GCC 4.9
* libtorrent 0_16_17 and higher

**Comment by arvidn** [comment]
that's really great. Is it hard to set that up to run periodically, either manually (locally) or on travis?
It would be especially useful right before cutting a release obviously

**Comment by lvc** [comment]
The report is automatically updated 3 times a week: https://abi-laboratory.pro/index.php?view=abi-tracker

Also you can set up your local tracker if needed. It's necessary to download and build all versions of the library by the abi-monitor tool (https://github.com/lvc/abi-monitor) and then run the analysis by the abi-tracker tool (https://github.com/lvc/abi-tracker). You need only one simple file to start (libtorrent.json):

    {
    "Name":           "libtorrent",
    "SourceUrl":      "https://github.com/arvidn/libtorrent/tags",
    "Git":            "https://github.com/arvidn/libtorrent.git",
    "Maintainer":     "Arvid N.",
    "MaintainerUrl":  "http://libtorrent.org/",
    "Configure":      "--enable-static=no",
    "Changelog":      "ChangeLog",
    "HeadersDiff":    "Off",
    "Make":           "-j4",
    "MinimalVersion": "0_16_17"
    }

Thank you.

**Comment by lvc** [comment]
Added 'current' version (git master) to the report.

![libtorrent-3](https://cloud.githubusercontent.com/assets/1517837/25552950/22dd6658-2cb8-11e7-8398-0637453c63f3.png)
