### ISSUE TITLE
 dht_put.cpp "get" command not working

### ISSUE THREAD

**Issue by amd128** [arvidn/libtorrent#1957]
libtorrent version (or branch): libtorrent-rasterbar 1.2.0
platform/architecture: linux mint (ubuntu) 64bit
compiler and compiler version: gcc 6.2.1

It seems like I'm able to successfully put something in the dht, but I can't retrieve it.

```
amd@amd-OptiPlex-9020 ~/Documents/libtorrent/tools/bin/gcc-6.2.1/debug/link-static/threading-multi $ ./dht put "testing 123"
load dht state from .dht
bootstrapping
-
bootstrap done.
PUT 71efd557ef258be05bbe924d899d50c176d56c62
-
DHT put commplete (success=0 hash=71efd557ef258be05bbe924d899d50c176d56c62)
amd@amd-OptiPlex-9020 ~/Documents/libtorrent/tools/bin/gcc-6.2.1/debug/link-static/threading-multi $ ./dht get 71efd557ef258be05bbe924d899d50c176d56c62
load dht state from .dht
bootstrapping
|
bootstrap done.
GET 71efd557ef258be05bbe924d899d50c176d56c62
\
<uninitialized>
```

This still happens when I call `rm .dht` in between the two `./dht` calls.

Not sure if this is related to my previously posted issue #1948

**Comment by arvidn** [comment]
try using ``router.utorrent.com:6881`` as your bootstrap node

**Comment by amd128** [comment]
That worked! Thank you!
