### ISSUE TITLE
Handling nested directories

### ISSUE THREAD

**Issue by mtbar131** [arvidn/libtorrent#1958]
Libtorrent provides` file_storage` API to deal with different files inside a torrent. However when a torrent has multiple nested directories there is no way to figure out the original directory structure from `file_storage` API.
For example, given a directory structure as below:

```
img
├── 1.png
├── 2.png
├── 3.png
└── subdir1
      ├── 1.png
      └── 2.png
```

If I create a torrent for directory `img` and then import it using libtorrent then `orig_files()` method of `file_storage` simply returns a list of below 5 files 

> [1.png,2.png,3.png,1.png,2.png].

I would like to read a torrent file and then go through all files/directories inside that torrent and create exactly same directory structure as above at torrent side (directory structure creation part is done by my code hence I will be using libtorrent just to read torrent file). How can I achieve that?

**Comment by arvidn** [comment]
it sounds like you may be getting ``file_storage::file_path()`` mixed up with ``file_storage::file_name``. See [documentation](http://libtorrent.org/reference-Storage.html#file_path()).
