### ISSUE TITLE
QBittorrent crash on startup

### ISSUE THREAD

**Issue by AlexTalker** [arvidn/libtorrent#197]
Because of failed assertion as says output. Please, help me with it!
Backtrace:
https://gist.github.com/34bf88918189d219c4f1
stderr:
https://gist.github.com/86e5fc682a5734a2b9d4

**Comment by arvidn** [comment]
I take it this is with a socks5 proxy configured, right?

**Comment by arvidn** [comment]
could you give this patch a try? https://github.com/arvidn/libtorrent/pull/198

**Comment by AlexTalker** [comment]
@arvidn https://gist.github.com/ec2c27e6399a11b53648
If I did it right...

**Comment by arvidn** [comment]
from that output, it does not look like you've configured a proxy. is that right?

**Comment by AlexTalker** [comment]
@arvidn no, why? As you can see, the service had configure the proxy properly, isn't? ( https://gist.github.com/c5934a536a0378519e51 ) Also, as output of QB says, it has to determine settings of proxy from it's configuration....
![2015-10-02-155532_1366x768_scrot](https://cloud.githubusercontent.com/assets/3531127/10246943/0bdbda5c-691e-11e5-8574-7eff90a294d5.png)

**Comment by arvidn** [comment]
I figured it out. it's the "proxy_peer_connections = false" setting that is broken. I should have a fix shortly.
thanks for your help so far!

**Comment by arvidn** [comment]
I have updated the pull request. my test passes now, so I'm pretty confident it solves the issue

**Comment by AlexTalker** [comment]
@arvidn seems like master changed so far from release, so that I cannot just pick you patch, hah :smile: I'll test your PR, thanks...

**Comment by AlexTalker** [comment]
@arvidn ...seems like I cannot build it because need automake 1.14 while my version of automake is 1.15

**Comment by arvidn** [comment]
yeah. I'm working on merging it into master

**Comment by arvidn** [comment]
what's the problem with automake?

**Comment by ssiloti** [comment]
@AlexTalker you should be able to have multiple versions of automake installed at the same time. Check your distro's documentation for how to install a specific version of automake.

**Comment by arvidn** [comment]
I wouldn't expect the .ac files to rely on an older version though

**Comment by AlexTalker** [comment]
@ssiloti just local PKGBUILD(or, in other words, PKGBUILD for releases of the library) don't call autotool.sh(because AFAIK it's for repo-only usage), I guess. But when I'd just tarball the branch where's @arvidn patch located, and call autotool.sh,  everything just fine.
And yes, @arvidn , now everything fine I guess, thanks. At least GUI is come back :smile:

**Comment by arvidn** [comment]
merged
