### ISSUE TITLE
Methods to detect the first piece that has been downloaded (time-driven --> event-driven)

### ISSUE THREAD

**Issue by MaChengxin** [arvidn/libtorrent#1973]
_libtorrent version (or branch):_
1.1.3.0

_platform/architecture:_
Ubuntu 16.04, x64

_compiler and compiler version:_
gcc (GCC) 5.4.0

_Python version:_
Python 2.7.12

_please describe what symptom you see, what you would expect to see instead and
how to reproduce it._

In my project I need to stop downloading a torrent as soon as the first piece is downloaded. (Downloading the whole torrent isn't necessary and would flood my disk because I am measuring the performance of 100+ torrents.)

The example in the [doc](https://github.com/arvidn/libtorrent/blob/master/docs/python_binding.rst) checks if a torrent has finished downloading in a time-driven manner, i.e., checking if the torrent is seeding every one second.
Base on this example, my current solution is to check `torrent_status.num_pieces` in the while loop and break the loop when this metric isn't zero. However this could lead to a result that the program downloads more than one piece before stopping.

Is it possible to do the detection work in an event-driven way? i.e., as soon as the first piece is downloaded, it triggers some mechanism to terminate downloading.

**Comment by arvidn** [comment]
yes, you can listen for the alert that a piece has passed the hash check.
There are two ways to poll alerts in an event-driven fashion:

1. use wait_for_alert() on the session object. It will return immediately as there are new alerts. Then you can call pop_alerts()
2. set up the alert notify function (session::set_alert_notify()) to have a function be called when there are new alerts. This function is called from within the libtorrent thread, and the only think you should do in there is to notify your main thread that it can call pop_alerts().
