### ISSUE TITLE
Making a client seed without any choking or upload limits

### ISSUE THREAD

**Issue by mtbar131** [arvidn/libtorrent#1975]
**Please provide the following information**

libtorrent version (or branch):
1.1.2

I would like to write a client using libtorrent which will seed the data without any choking or any limits. I have already gone through other issues and already implemented a simple client using 
```
	sett.set_int(settings_pack::choking_algorithm, settings_pack::fixed_slots_choker); 
	sett.set_int(settings_pack::unchoke_slots_limit, -1); 
```
But even after doing this the client seems to stop seeding after some time and then starts again. I want to write a client which will keep on seeding as long as there is a demand.
How can I do it?

**Comment by arvidn** [comment]
you configure it to do so. which configuration option to set depends on what undesirable behavior you see. "stops seeding" is not a precise enough description of what's happening.

does it stop the torrent and start it back up again? are your torrents auto-managed? does it disconnect peers? are the number of peer connections close to the limit? does it choke peers?

**Comment by mtbar131** [comment]
All torrents are `auto-managed`. 
Data collected from torrent_handle::status() shows `0` peers. There is only 1 peer downloading the data so peer connections are not close to the limit. Also `seeder client` shows the incoming piece requests of the leecher. I am not sure how to see if it is choking any peers (I could not see that information in alerts) but I have used above mentioned settings for choking. 
Sometimes it transfers one or two pieces and then stops sending any data while sometimes it does not transfer anything at all. 

Can you please tell me how to get all debugging information (I am already printing all the alerts without filtering) and how to interpret that information? (For example the reason codes in alerts)

**Comment by arvidn** [comment]
you probably want to look at [peer_info](http://libtorrent.org/reference-Core.html#peer-info) on the seeding client. What happens in the ``flags`` field may be especially interesting. You can query peer info via [get_peer_info](http://libtorrent.org/reference-Core.html#get_peer_info()).

**Comment by arvidn** [comment]
if you enable peer-level logging, you should get a log alert every time a peer is choked and unchoked.

**Comment by mtbar131** [comment]
Thanks arvidn for your help. I printed all peer_info messages. It looks like my seeder client has choked my leecher client and my leecher client has also choked my seeder client. I am not sure why this is happening though. Also it keeps showing that connection is in half open state. It never shows connected.
 What setting parameter might have caused this?

**Comment by arvidn** [comment]
you should probably understand the basic protocol specification. A peer is never *unchoked* unless it's *interested*. An as soon as a peer is no longer interested, it's *choked*. You're saying that you set piece priorities to 0, I would expect then that the downloader will sometimes become *not-interested* and hence be choked.

**Comment by mtbar131** [comment]
@arvidn  You are correct, since I am setting the piece priority to 0 it becomes not-interested sometimes and hence chokes the peer but what I want is whenever I set piece priority back to 7 (for a particular piece) then it should change status to interested and then unchoked as soon as possible. I want to know what settings I will have to be done in seeder client and leecher client to achieve that?

**Comment by arvidn** [comment]
I would expect that to be the default behavior, except you loose at least one round-trip each time it happens (to send the interested message and get the unchoke message back) before you can request another piece.

What to do about it depends on which step of this chain fails to happen immediately. The traditional behavior of a bittorrent client is to only consider peers to unchoke every 15 seconds. The ability to unchoke a peer that becomes interested immediately is a libtorrent feature that only kicks in if there are enough unused unchoke slots.

**Comment by mtbar131** [comment]
I already tried setting those values using below functions but that didn't help.

```
sett.set_int(settings_pack::unchoke_interval, 1);                                                                                                 
sett.set_int(settings_pack::optimistic_unchoke_interval, 1);
```
That is why I wanted to know if I need to to any other settings along with this to make it work.

**Comment by arvidn** [comment]
You have to look at your log to figure out what the specific behavior you don't want is.
