### ISSUE TITLE
Adding/removing web seed does not automatically save resume data

### ISSUE THREAD

**Issue by fbriere** [arvidn/libtorrent#1979]
Related qBittorrent issue: qbittorrent/qbittorrent#6419.

Under 1.0, adding or removing a web seed does not automatically cause the resume data to be saved.  I suppose this is due to the lack of setting `m_need_save_resume_data` in either `add_web_seed()` or `remove_web_seed()`.

This has also been reported to be present under 1.1 in https://github.com/qbittorrent/qBittorrent/issues/6419#issuecomment-299654007.  I haven't confirmed this myself, but I do notice that `set_need_save_resume()` is only called in `add_web_seed()`, and not in `remove_web_seed()`.

**Comment by arvidn** [comment]
please give this patch a try! https://github.com/arvidn/libtorrent/pull/1986

**Comment by fbriere** [comment]
Yup, seems to be working.  Thanks!
