### ISSUE TITLE
feature request: boost performance for force_recheck()

### ISSUE THREAD

**Issue by fisherwei** [arvidn/libtorrent#1980]
I am trying to force re-check an 1.7TB torrent by using Deluge 1.3.14(a python client using libtorrent), it needs more than 6 hours to do it.

my CPU is 2x 8 cores Xeon E5, 32G memory, storage is a SSD zfs pool(>2000MB/s read and write).
but, Deluge only use less 3% CPU time, I guessed it is a single threading task.

As I know, a torrent has some blocks and some other blocks, so, maybe, it can be hashed in parallel by multi-threading and use some new CPU features(such as SSE/AVX or something)?

**Comment by arvidn** [comment]
Yes, pieces are hashed in parallell. Specifically they are hashed by the disk I/O subsystem, which is multi-threaded. You can control the number of threads to use via the ``aio_threads`` setting.

However, I don't believe you can affect the number of outstanding pieces to the disk at a time, which may be the limiting factor for fast disks.
