### ISSUE TITLE
windows socket problem

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#1981]
master branch

in session_impl.cpp there is

session_impl::bind_outgoing_socket
..
#ifdef TORRENT_WINDOWS
			s.set_option(exclusive_address_use(true), ec);
#endif
			s.set_option(tcp::acceptor::reuse_address(true), ec);
...

but the definition in WinSock2.h is:
#define SO_EXCLUSIVEADDRUSE ((int)(~SO_REUSEADDR)) /* disallow local address reuse */

so these to lines contradict each other.
The seconds call always fails for me with error 10022 even if I swap them (as expected).

**Comment by arvidn** [comment]
My understanding of ``exclusive_address_use`` is that it complements the ``REUSEADDR`` by making it behave like BSD socket's ``REUSEADDR``.

Perhaps I misunderstood the msdn articles, but here's what I gathered:

``SO_REUSEADDR`` on windows allows another process to bind a socket to the same port *while* it's still bound by the first process. On BSD systems, ``SO_REUSEADDR`` only applies to sockets in ``TIMED_WAIT`` state, i.e. you can't hi-jack someone else's socket with this flag. When microsoft realized that this is a security problem, they introduced this additional flag to restrict ``SO_REUSEADDR`` to only allow reusing addresses that aren't actively used.

**Comment by arvidn** [comment]
I see. perhaps the BSD meaning of ``SO_REUSEADDR`` is the default on windows then. So, do you think the fix is to *just* set the ``SO_EXCLUSIVEADDRUSE`` flag?

**Comment by MassaRoddel** [comment]
I think so too.
