### ISSUE TITLE
High CPU load when shadowsocks SOCKS5 proxy

### ISSUE THREAD

**Issue by kc1212** [arvidn/libtorrent#1987]
**Please provide the following information**

*libtorrent version (or branch):*
1.1.2.0

*platform/architecture:*
Fedora 25

*compiler and compiler version:*
From Fedora repo

*please describe what symptom you see, what you would expect to see instead and how to reproduce it.*

I originally raised the issue on qbittorrent/qBittorrent#6738. 

I use a shadowsocks SOCKS5 proxy with UDP relay enabled. When using qBittorrent or Deluge I experience high CPU load at about 70%, regardless of the number of active torrents. The shadowsocks logs were getting spammed with the message `udp assc request accepted` (I haven't found anything useful regarding that message). Since the proxy feature is from libtorrent, I suspect libtorrent and shadowsocks are not playing nicely when dealing with UDP packets. Disabling uTP or DHT in qBittorrent didn't help.

Is there a minimum example (a test or a python script) that I can run to narrow down the problem?

**Comment by arvidn** [comment]
my suspicion is that the socks5 proxy disconnects the TCP connection immediately after the UDP ASSOCIATE command. As far as I know, it's supposed to keep the connection open until the client closes it (to indicate the udp association can be closed).

The best kind of log would be a (short) wireshark dump of just the TCP connection to the proxy. (make sure to strike out any passwords that may end up in there). Just one or two connection attempts should be enough.

Does it seem like UDP traffic works through the proxy though? i.e. DHT, uTP and UDP trackers?

it may be useful to include some UDP traffic to the proxy as well. Feel free to send it to me directly, arvid@libtorrent.org

**Comment by kc1212** [comment]
It seems UDP traffic is **not** working correctly. I tried adding a magnet link without any http trackers and the download never started, without the proxy the UDP trackers work fine. I must have been under the impression that UDP worked because the download started, but in reality the torrent client was using http trackers and probably no uTP.

I'll try to get a wireshark dump a bit later. Just to clarify, you'd like me to capture the traffic between my host (where SOCKS5 client is running) to the SOCKS5 server, is that right?

**Comment by arvidn** [comment]
As far as I can tell from the wireshark log you sent me, the SOCKS5 server disconnects the TCP connection immediately after libtorrent sends the UDP associate command.

My interpretation of the protocol specification is that the TCP connection is supposed to be left open for as long as the UDP association/forwarding is needed. Once the socks *client* closes the connection, it indicates to the server that the forwarding is no longer necessary.

Since the server closes the connection, libtorrent will attempt to re-establish the UDP association by reconnecting and issuing the same command again.

As far as I can tell, this indicates that the socks5 server does not support UDP. However, libtorrent should probably still not end up reconnecting in a busy loop still.

**Comment by arvidn** [comment]
Do you have any additional log from the socks5 server indicating any kind of error?

**Comment by kc1212** [comment]
I do have some errors, but they might be shadowsocks specific, so not sure how useful they might be.

On the shadowsocks client, I see a single `ERROR: unsupported cmd: 2`, probably [from this line](https://github.com/shadowsocks/shadowsocks-libev/blob/72622a3e3df0d8b66f005717ecc48264275f453c/src/local.c#L513).

On the shadowsocks server, I get a bunch of `ERROR: [udp] sendto_remote: Invalid argument`, probably [one of these](https://github.com/shadowsocks/shadowsocks-libev/search?utf8=%E2%9C%93&q=sendto_remote&type=).

I'm considering to test whether UDP works for other applications, but I'm not sure how. It seems the client need to negotiate a port number with the UDP relay, in this case the shadowsocks client. Are you aware of any tools that can do this?

**Comment by arvidn** [comment]
yes, libtorrent attempts to "bind" over socks5, which is questionable (and has been removed in future versions).

As far as I can tell, the socks5 server deliberately disconnects the client immediately on a udp associate command: https://github.com/shadowsocks/shadowsocks-libev/blob/72622a3e3df0d8b66f005717ecc48264275f453c/src/local.c#L559

That looks wrong to me, at least according to my reading of the RFC

**Comment by arvidn** [comment]
it does look like (as long as it's not running in TCP_ONLY mode) just has an open UDP proxy running though, so the reason UDP doesn't work is probably because libtorrent keeps queueing up packets while re-connecting to the proxy

**Comment by arvidn** [comment]
Here's a reference: https://tools.ietf.org/html/rfc1928#page-7

> A UDP association terminates when the TCP connection that the UDP
> ASSOCIATE request arrived on terminates.

I believe it's a pretty clear bug in the socks5 server.

**Comment by kc1212** [comment]
Thanks Arvid, I certainly didn't expect shadowsocks to deviate away from the RFC on purpose (my related comment [here](https://github.com/shadowsocks/shadowsocks-libev/issues/1502#issuecomment-302730366)), sorry for that. I may need to find another, more compliant socks5 server, in case other applications run into trouble.

**Comment by arvidn** [comment]
I still intend to fix the issue on the libtorrent side though, and have a delay before retrying a udp associate again.

**Comment by arvidn** [comment]
here's a fix btw. please test if you have a chance. https://github.com/arvidn/libtorrent/pull/2011

**Comment by arvidn** [comment]
pushed to RC_1_1
