### ISSUE TITLE
Caught Floating point exception error. 

### ISSUE THREAD

**Issue by orsty3001** [arvidn/libtorrent#1990]
I'm running libtorrent version 0.13.6 on Slackware 64 latest and am getting this error randomly and not sure of it's a rtorrent issue or libtorrent issue. 

Caught Floating point exception, dumping stack:rt: 6931]                                                                    [U 6/6] [D 166/160] [H 0/32] [S 17/386/768] [F 93/128]
rtorrent() [0x4138e3]
rtorrent() [0x44ca7a]
/lib64/libc.so.6(+0x35aa0) [0x7f0883b6eaa0]
/usr/lib64/libtorrent.so.19(_ZNK7torrent8FileList16chunk_index_sizeEj+0x27) [0x7f0885455297]
/usr/lib64/libtorrent.so.19(+0x959f4) [0x7f088549b9f4]
/usr/lib64/libtorrent.so.19(+0x95c80) [0x7f088549bc80]
/usr/lib64/libtorrent.so.19(+0x95d5b) [0x7f088549bd5b]
/usr/lib64/libtorrent.so.19(+0xc429f) [0x7f08854ca29f]
/usr/lib64/libtorrent.so.19(+0xc0dc5) [0x7f08854c6dc5]
/usr/lib64/libtorrent.so.19(+0xc1138) [0x7f08854c7138]
/usr/lib64/libtorrent.so.19(_ZN7torrent9PollEPoll7performEv+0x104) [0x7f0885446a44]
/usr/lib64/libtorrent.so.19(_ZN7torrent9PollEPoll7do_pollEli+0x51) [0x7f0885446ae1]
/usr/lib64/libtorrent.so.19(_ZN7torrent11thread_base10event_loopEPS0_+0x127) [0x7f088547bcc7]
rtorrent() [0x412c49]
/lib64/libc.so.6(__libc_start_main+0xf0) [0x7f0883b596d0]
rtorrent() [0x413359]
Aborted

**Comment by arvidn** [comment]
that's rtorrent. this is the project of libtorrent-rasterbar, they're different
