### ISSUE TITLE
Can't build on arm

### ISSUE THREAD

**Issue by czth** [arvidn/libtorrent#2002]
While build (make) an error has place. For example:

make[1]: Entering directory `/tmp/libtorrent/src'
  CXX      announce_entry.lo
  CXX      assert.lo
  CXX      bandwidth_limit.lo
  CXX      bandwidth_manager.lo
  CXX      bandwidth_queue_entry.lo
  CXX      bdecode.lo
  CXX      bitfield.lo
  CXX      bloom_filter.lo
  CXX      broadcast_socket.lo
  CXX      block_cache.lo
  CXX      bt_peer_connection.lo
bt_peer_connection.cpp: In member function 'void libtorrent::bt_peer_connection::on_extended_handshake()':
bt_peer_connection.cpp:1787:60: error: 'class boost::basic_string_ref<char, std::char_traits<char> >' has no member named 'to_string'
   if (!client_info.empty()) m_client_version = client_info.to_string();
                                                            ^
libtorrent version (or branch): version 1.1.2

platform/architecture: centos 7, arm

compiler and compiler version: gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

Step to reproduce: just try build it on arm

**Comment by arvidn** [comment]
I see, I suppose ``string_ref`` doesn't have that member. you could use a newer version of boost

**Comment by arvidn** [comment]
which version of boost are you using?

**Comment by czth** [comment]
uname -ar
Linux pc-server 4.2.3-200.el7.armv7hl #1 SMP Wed Nov 25 18:01:51 EST 2015 armv7l armv7l armv7l GNU/Linux

Package boost-devel-1.53.0-26.el7.armv7hl already installed and latest version

**Comment by czth** [comment]
And new one errors:

/usr/include/c++/4.8.2/bits/stl_algo.h:214:23: error: could not convert '__pred.libtorrent::create_torrent::add_tracker(libtorrent::string_view, int)::__lambda0((*(const announce_entry*)__first.__gnu_cxx::__normal_iterator<_Iterator, _Container>::operator*<std::pair<std::basic_string<char>, int>*, std::vector<std::pair<std::basic_string<char>, int> > >()))' from 'void' to 'bool'
    if (__pred(*__first))
                       ^

**Comment by czth** [comment]
I try replace to_string() with std::string(), but not sure that good practice

**Comment by arvidn** [comment]
the latest version of boost is 1.64. But anyway, my intention of falling back to boost::string_ref was to make it work with older versions. you should be able to construct the strings like this:

``std::string(ref.begin(), ref.end())``.

Perhaps this should be factored out into a utility function in ``string_view.hpp``, to support older versions of boost. (patches are welcome!)

**Comment by czth** [comment]
Thanks! Will try. Don't close issue please. I thinks that is just beginning.

**Comment by czth** [comment]
Hi! I'm still trying to build. I have a new problem when I try to build with 'python setup.py build':

g++ -pthread -shared -Wl,-z,relro build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/alert.o build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/module.o build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/peer_info.o build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/torrent_info.o build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/session_settings.o build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/magnet_uri.o build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/string.o build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/datetime.o build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/version.o build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/utility.o build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/converters.o build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/ip_filter.o build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/fingerprint.o build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/create_torrent.o build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/torrent_status.o build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/sha1_hash.o build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/torrent_handle.o build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/error_code.o build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/entry.o build/temp.linux-armv7l-2.7/tmp/libtorrent/bindings/python/src/session.o -L../../src/.libs -L/lib -L/lib -L/usr/lib -ltorrent-rasterbar -lboost_system -lpthread -lboost_system -lboost_python -lpthread -lssl -lcrypto -lpython2.7 -o build/lib.linux-armv7l-2.7/libtorrent.so -fvisibility=hidden -fvisibility-inlines-hidden
/usr/bin/ld: cannot find -ltorrent-rasterbar
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1

**Comment by arvidn** [comment]
your problem now seems to be that ``setup.py`` expects libtorrent to have been installed, and you haven't installed it yet.

**Comment by arvidn** [comment]
could you show me the changes you made to get it to build? perhaps in a PR.

**Comment by czth** [comment]
All my changes is manual resolving of all dependecies which needed for building. I prepare PR for you.
