### ISSUE TITLE
file_completed_alert is still not fired

### ISSUE THREAD

**Issue by zzzhr1990** [arvidn/libtorrent#2004]
Hello, when I download a torrent having a couple of files and catch file_completed_alert to watch the downloaded file, file_completed_alert is not fired.

I have noticed this:
https://github.com/arvidn/libtorrent/pull/880
but in my case (libtorrent with python binding 1.1.3.0), this file_completed_alert is event still not fired.

Below is my code

```python
alerts = self.get_libtorrent_session.pop_alerts()
for alert in alerts:
    alert_type = type(alert).__name__
    if alert_type == "file_completed_alert": 
        torrent_handle = alert.handle
        info_hash = torrent_handle.info_hash()
```

And I have tried call torrent_handle::file_progress() before file download completed, but still not working?

**Comment by arvidn** [comment]
which flags do you set in your ``alert_mask``? More specifically, do you set the ``alert::progress_notification`` flag?

**Comment by zzzhr1990** [comment]
I'm sorry, I haven't put 'lt.alert.category_t.progress_notification' in alert_mask setting.
```python
alert_mask = (lt.alert.category_t.error_notification |
                      lt.alert.category_t.port_mapping_notification |
                      lt.alert.category_t.storage_notification |
                      lt.alert.category_t.tracker_notification |
                      lt.alert.category_t.status_notification |
                      lt.alert.category_t.ip_block_notification |
                      lt.alert.category_t.performance_warning |
                      lt.alert.category_t.progress_notification)
```
And this is OK
