### ISSUE TITLE
File priorities inside magnet URI scheme?

### ISSUE THREAD

**Issue by dessalines** [arvidn/libtorrent#2009]
I'm not sure if this standard exists, or not. 

`magnet:?xt=urn:btih:HASH&dn=NAME&tr=...&priorities={[0,1]}`

Basically the idea is that you could add a magnet URI to a torrent client, and choose to not download certain files, or put certain ones on high priority, based on their file index.

**Comment by arvidn** [comment]
I don't believe anyone has suggested such extension. I've been playing with the idea of specifying a file index to have the magnet link refer to, which would imply setting every other file to priority 0.

I would recommend you head over to https://github.com/bittorrent/bittorrent.org/ for discussions and possibly writing up a proposal (BEP)

**Comment by dessalines** [comment]
I'll start writing up the BEP next week, would you mind helping/correcting me where possible?

So far I'm thinking the name of it would be, *Magnet URI extension - Select specific file indices for download*

I realized priorities really doesn't make sense, because when adding a torrent you really only set whether you want to download them at all or not, with most clients.

And I'm thinking this would be best:
`magnet:?xt=urn:btih:HASH&dn=NAME&tr=...&so=1,3,5`

For files 1, 3, and 5.

**Comment by arvidn** [comment]
sure.

**Comment by arvidn** [comment]
just file an issue on the bittorrent.org repo where you make your argument for why you think this would be a good/useful extension, and link to this

**Comment by arvidn** [comment]
you may want to be explicit about whether file indices start at 0 or 1 (and personally I think 0 is the right choice)
