### ISSUE TITLE
error code : metadata too large

### ISSUE THREAD

**Issue by asd567800** [arvidn/libtorrent#2014]
version 1.0.11 
When open a torrent  (24M) , it happened , sometime a few torrents just are so big include 450G data.

**Comment by arvidn** [comment]
what is reporting this error?
libtorrent 1.0.x has an internal limitation of only supporting metadata of 2^24 or less. You may want to upgrade to libtorrent-1.1.x to work around this.
Also, if you construct a ``torrent_info`` object by filename, there's an 8 MiB size limit. To work around this, load the file yourself and pass in the buffer, or bdecode it before constructing the torrent_info.

**Comment by asd567800** [comment]
Thanks arvidn !
I see the function "load_file"  limit 8000000 in 1.0.11  . Can i just change the limit  to 32M (32000000 ) ?

**Comment by asd567800** [comment]
Oh, Thanks a lot . I  upgrade to libtorrent-1.1.13 .   In file decode.hpp ,  I modified the token_limit from  1000000 to 32000000 . It solved.

Another qustion. from 1.1.x to 1.2.0.0  beta, the apis have  changed so much.  what's new in   1.2.0.0 ?

**Comment by asd567800** [comment]
@arvidn 
Oh, Thanks a lot . I upgrade to libtorrent-1.1.13 . And then , In file decode.hpp , I modified the token_limit from 1000000 to 32000000 . It solved.

Another qustion. from 1.1.x to 1.2.0.0 beta, the apis have changed so much. what's new in 1.2.0.0 ?

**Comment by arvidn** [comment]
see the changelog: https://github.com/arvidn/libtorrent/blob/master/ChangeLog

which functions have been removed that you rely on? I believe 1.2 is mostly API compatible with 1.1

**Comment by asd567800** [comment]
@arvidn 
Some functions were moved to namespace aux，before this  it was in libtorrent  namespace.
And some data types were removed.

**Comment by arvidn** [comment]
as far as I know, only functions that either were not part of the public API (and not documented) or functions that were deprecated in 1.1 have been removed or moved.

Do you have any specific examples?
