### ISSUE TITLE
torrent_handle::remap_files()

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#2015]
torrent_handle::remap_files() appears to have vanished and no mention in the change log as to why, I think this is necessary for a rename once a torrent is in the session?

**Comment by arvidn** [comment]
remap files literally maps the torrent storage onto any other set of files, as long as the total size is the same. This operation doesn't make much sense on a ``torrent_handle``. libtorrent wouldn't actually change the data around to make it fit the new file mapping anyway. You can do this before you add the torrent to the session.

To rename a file, just use ``rename_file()``.

**Comment by arvidn** [comment]
I can't see remap_files() ever existing on ``torrent_handle``, only on ``torrent_info``. And I don't see it having disappeared anywhere either. What specifically do you see?

**Comment by Col-blimp** [comment]
I was looking to rename the torrent itself once loaded and was referencing this: https://sourceforge.net/p/libtorrent/mailman/message/34152444/

Is it possible to rename the torrent once loaded? I face the same issue with torrent_file() returning a shared const.

**Comment by arvidn** [comment]
once a torrent is loaded, the corresponding ``torrent_info`` is owned by libtorrent, you can't mutate that. Once the torrent has been loaded your only option is to use the ``torrent_handle`` functions to rename files.

By "rename the torrent itself" mean renaming the root directory, remap files on the ``torrent_info`` object seems like the simplest solution. You could possibly rename every file individually as well, but that could easily get messy. So, you could copy the ``torrent_info`` object, stop the torrent, remap files and then add it back again. If any files started downloading under the original name, those will be lost. You may want to add the torrent with the ``stop_when_ready`` flag.

**Comment by Col-blimp** [comment]
Thanks, stopping is probably a better option with a magnet link anyway as there is a chance parts of files not wanted could be downloaded before the metadata received alert is received so you get a chance to clean that up.
