### ISSUE TITLE
client_test.cpp: 3 bugs

### ISSUE THREAD

**Issue by dcb314** [arvidn/libtorrent#203]
1.

[client_test.cpp:1873]: (error) Width 4096 given in format string (no. 1) is larger than destination buffer 'url[4096]', use %4095s to prevent overflowing it.

                    char url[4096];
                    puts("Enter magnet link:\n");
                    scanf("%4096s", url);

2.

[client_test.cpp:2031]: (error) Width 2048 given in format string (no. 1) is larger than destination buffer 'url[2048]', use %2047s to prevent overflowing it.

                    char url[2048];
                    puts("Enter RSS feed URL:\n");
                    scanf("%2048s", url);

3.

client_test.cpp:1174:16: warning: ordered comparison of pointer with integer zero [-Wextra]

               char* port = (char*) strrchr((char*)peer.c_str(), ':');
                if (port > 0)

**Comment by arvidn** [comment]
thanks! fixed
