### ISSUE TITLE
write_resume_data_buf

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#2030]
```
void test(std::string path) {
	error_code ec;
	add_torrent_params p;
	p.ti = std::make_shared<torrent_info>(path , std::ref(ec) , 0);
	p.save_path = path;
	auto const buf = write_resume_data_buf(p);
	save_file(path + "\\" + to_hex(p.ti->info_hash()) + ".resume" , buf);
	//session->async_add_torrent(p);
}
```

In the above I was expecting the changed path to be saved in to the created resume file but the resume is just the default details, if you `async_add_torrent(p)` then on `add_torrent_alert` the `torrent_info` does have the correct new save path.

How do you save a changed `add_torrent_params` that's not been added to the session?

**Comment by arvidn** [comment]
the ``save_path`` is saved right [here](https://github.com/arvidn/libtorrent/blob/master/src/write_resume_data.cpp#L79).

**Comment by Col-blimp** [comment]
Sorry I thought it was all changes were not being saved so I just used 'save_path' for a small example, my bencode viewer was reading from the wrong file, here is a more detailed function:

`void test(std::string path, std::string resume_path, std::string new_name) {
	error_code ec;
	add_torrent_params p;
	p.ti = std::make_shared<torrent_info>(path , std::ref(ec) , 0);
	p.save_path = path;
	file_storage const fs = p.ti->files();
	file_storage f = fs;
	f.set_name(new_name);
	p.ti->remap_files(f);
	auto const buf = write_resume_data_buf(p);
	save_file(resume_path + "\\" + to_hex(p.ti->info_hash()) + ".resume" , buf);
	//session->async_add_torrent(p);
}`


What's happening is everything is being properly saved except the remapped files (to change the name) but if 'session->async_add_torrent(p);' then the remap has taken effect and the torrent saves to the new root directory and subsequent resume files generated from 'save_resume_data_alert' have the new 'mapped_files' in the resume.

**Comment by arvidn** [comment]
The renamed files are saved [here](https://github.com/arvidn/libtorrent/blob/master/src/write_resume_data.cpp#L177). Are the new names not saved to the file correctly or are they not loaded correctly?
I understand you say the ``save_resume_data_alert`` has the mapped files set correctly, does something go wrong when you pass it to ``write_resume_data()``?

what's the error you see?

**Comment by Col-blimp** [comment]
the `mapped_files` section is missing completely from the resume data but if you add the torrent to the session then save the resume the `mapped_files` is there, its like the remapping is ignored till the torrent is in the session.

**Comment by arvidn** [comment]
I see what you're doing now. The "mapped_file" entry is populated from the ``add_torrent_params::renamed_files`` list. When saving resume data, this is populated from any remapped files in the torrent, when loading, it will issue calls to ``rename_file`` before starting the torrent.

when you remap the files in the .torrent file directly, you update the "internal" state, without going through the middle steps of ``add_torrent_params::renamed_files``, which is why you don't see the changes show up there (unless you round-trip through the session).

I would agree that this is perhaps a bit confusing, and I would welcome any suggestions on how to make it simpler.

**Comment by Col-blimp** [comment]
Bring back `torrent_added_alert` with an additional `params` member, I think it was the case that on `torrent_added_alert` the torrent existed in the session but had not started to connect to any prrers/trackers/url seeds?

**Comment by Col-blimp** [comment]
So Arvidn `atp.renamed_files` is accessible so if you manually set the map:

```
file_storage f = fs;
f.set_name(wchar_utf8(name));
p.ti->remap_files(f);
std::map<file_index_t , std::string> renamed_files;
for ( int i = 0; i < fs.num_files(); i = i + 1 ) {
  renamed_files.insert(std::make_pair<file_index_t , std::string>(( file_index_t ) i , fs.file_path(( file_index_t ) i)));
  std::cout << renamed_files.size() << " : "  << i << " : " << fs.file_path(( file_index_t ) i) << std::endl;
}
p.renamed_files = renamed_files;
```

then even if the map checks out in size and content then the `write_resume_data_buf` still ignores it, looking at `write_resume_data.cpp` then so long as `!atp.renamed_files.empty()` then it should write the list but it does not.

**Comment by arvidn** [comment]
It sounds like you're asking for [add_torrent_alert](https://github.com/arvidn/libtorrent/blob/RC_1_1/include/libtorrent/alert_types.hpp#L1845).

**Comment by Col-blimp** [comment]
Nope, looking to save a complete resume file without adding the torrent to the session, `write_resume_data_buf` is doing the job except for `remap_files` and I can't figure out why it ignores `atp.renamed_files`

**Comment by arvidn** [comment]
Then I don't know what you meant by: https://github.com/arvidn/libtorrent/issues/2030#issuecomment-304452597

if you add a params member to torrent_added_alert, you essentially get the same thing that's currently called ``add_torrent_alert``.

Regarding saving ``add_torrent_params::renamed_files``, did you step through it in a debugger?

**Comment by Col-blimp** [comment]
Well `add_torrent_alert` even with priorities set to zero you still can briefly get data downloaded and trackers connected and a few other alerts triggered but with `torrent_added_alert` there was less of a chance of that.

Anyhow yes with debugging I'm not seeing any errors at all with `write_resume_data_buf` and `atp.renamed_files` checks out in size and content it just never shows up in the end resume file unless its gone through the session.

**Comment by Col-blimp** [comment]
With `add_torrent_alert` then using the `params` to `write_resume_data_buf` after remaping the files it still won't add the `mapped_files` to the resume file, the only way it seems you can do this is adding the torrent to the session then calling `save_resume_data` on the handle after remaping the files but as `save_resume_data` is asynchronous you can end up with folders created and part files created along with peer connections started and web seed connections established.

**Comment by arvidn** [comment]
to avoid the race condition, you can start the torrent paused and not auto-managed. But the fundamental issue is that there are two levels where files can be renamed.

The behavior of load- and save_resume_data are correct in my opinion. They serialize and de-serialize the ``add_torrent_params`` object. Nothing more, nothing less. As for the "ti" field (the torrent itself), it saves the metadata verbatim. It does not consider the *effective* file_storage that may have replaced the files in the metadata.

The ability to remap files on the ``torrent_info`` object is necessary for internal use. When discriminating names that otherwise would collide for instance, and to implement renaming of files. ``remap_files()``is not used internally though. Perhaps that could be deprecated.

**Comment by Col-blimp** [comment]
Hi, you know this was for use with magnet links and for when you want to add a .torrent file and choose what files to download first so I ended up using a derivative of [this](https://stackoverflow.com/questions/6089806/keeping-the-downloaded-torrent-in-memory-rather-than-file-libtorrent) to avoid any files/folders being created, thanks.

**Comment by arvidn** [comment]
I see, so you do need to start the torrent to get the metadata. you can also set all the file priorities to zero to get the effect of not downloading anything.

**Comment by Col-blimp** [comment]
I seen the comment on the mailing list about the zero priority but you end up getting file complete alerts when the files aren't complete (they are as far as Libtorrent is concerned) but doing the initial loading and fetching of the torrent metadata in ram then saving off a resume file and discarding the ram is stopping anything going to disk that shouldn't be or should be a different name.
