### ISSUE TITLE
crash libtorrent::aux::session_impl::on_tick

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#2044]
libtorrent version (or branch): master
platform/architecture: windows x86/x64
compiler and compiler version: VC++2017

https://drdump.com/Problem.aspx?ProblemID=298184&login=guest
https://drdump.com/Problem.aspx?ProblemID=297638&login=guest

steps to reproduse:
1. add sleep std::string entry::to_string()
![default](https://cloud.githubusercontent.com/assets/920705/26599689/28baae36-4582-11e7-9e15-6dff276d3f70.png)

2. start download magnet
3. wait...

![default](https://cloud.githubusercontent.com/assets/920705/26599772/71a0ed36-4582-11e7-8460-d8513aec9f27.png)

_DEBUG_ERROR("vector iterator not incrementable");

![default](https://cloud.githubusercontent.com/assets/920705/26599350/033d71f8-4581-11e7-870e-a446d4205b35.png)

![default](https://cloud.githubusercontent.com/assets/920705/26599401/2c86787a-4581-11e7-899a-188b228eb1b5.png)

**Comment by arvidn** [comment]
that patch doesn't attempt to fix this issue, right?

**Comment by pavel-pimenov** [comment]
yes :(

**Comment by ajax16384** [comment]
````c++
m_iterating_connections == 1
     !assert_fail(const char * expr, int line, const char * file, const char * function, const char * value, int kind) Line 357	C++
>	!libtorrent::torrent::connect_to_peer(libtorrent::torrent_peer * peerinfo, bool ignore_limit) Line 6537	C++
 	!libtorrent::peer_connection::connect_failed(const boost::system::error_code & e) Line 4026	C++
 	!libtorrent::peer_connection::second_tick(int tick_interval_ms) Line 4735	C++
 	!libtorrent::torrent::second_tick(int tick_interval_ms) Line 8998	C++
 	!libtorrent::aux::session_impl::on_tick(const boost::system::error_code & e) Line 3408	C++
.... 	
````

**Comment by arvidn** [comment]
removing peers is deferred already, I suppose adding new peers need to be deferred as well

**Comment by ajax16384** [comment]
some kind of journal of m_connnections changes?

**Comment by ajax16384** [comment]
current quick workaround is to use clone

````c++
	template <typename T, typename IndexType = int>
	aux::vector<T, IndexType> clone(aux::vector<T, IndexType> const& v)
	{
		return v;
	}
...
for (auto p : clone(m_connections))
...
````

**Comment by arvidn** [comment]
does this look like a reasonable fix? https://github.com/arvidn/libtorrent/pull/2068

**Comment by ajax16384** [comment]
it seems ok!

**Comment by arvidn** [comment]
I'm a little bit worried about the complexity, and how many other bugs are lurking in modifying ``m_connections`` at the wrong time.

**Comment by pavel-pimenov** [comment]
@arvidn @ajax16384 thank you
