### ISSUE TITLE
Deprecation messages when TORRENT_NO_DEPRECATE defined

### ISSUE THREAD

**Issue by Krakean** [arvidn/libtorrent#2052]
libtorrent version (or branch): latest master (02.06.2017)

platform/architecture: Windows 8.1, x64

compiler and compiler version: MSVC 2017.2

Trying to compile libtorrent as separate lib (Release, x64), with these preprocessor defines:
WIN32_LEAN_AND_MEAN
_LIB
__USE_W32_SOCKETS
WIN32
_WIN32
_WINDOWS
_WIN32_WINNT=0x0601
NDEBUG
TORRENT_NO_DEPRECATE
TORRENT_USE_OPENSSL
TORRENT_USE_LIBCRYPTO
BOOST_ASIO_HAS_STD_CHRONO
BOOST_ASIO_ENABLE_CANCELIO
BOOST_EXCEPTION_DISABLE
BOOST_NO_EXCEPTIONS
TORRENT_DISABLE_LOGGING

And getting these warnings:
1>..\..\3rdParty\libtorrent\src\alert.cpp(116): warning C4996: 'libtorrent::identify_client': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/identify_client.hpp(58): note: see declaration of 'libtorrent::identify_client'
1>..\..\3rdParty\libtorrent\src\bt_peer_connection.cpp(3260): warning C4996: 'libtorrent::identify_client': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/identify_client.hpp(58): note: see declaration of 'libtorrent::identify_client'
1>..\..\3rdParty\libtorrent\src\fingerprint.cpp(88): warning C4996: 'libtorrent::fingerprint::name': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(90): note: see declaration of 'libtorrent::fingerprint::name'
1>..\..\3rdParty\libtorrent\src\fingerprint.cpp(89): warning C4996: 'libtorrent::fingerprint::name': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(90): note: see declaration of 'libtorrent::fingerprint::name'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(61): warning C4996: 'libtorrent::fingerprint': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(82): note: see declaration of 'libtorrent::fingerprint'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(63): warning C4996: 'libtorrent::fingerprint': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(82): note: see declaration of 'libtorrent::fingerprint'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(69): warning C4996: 'libtorrent::fingerprint': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(82): note: see declaration of 'libtorrent::fingerprint'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(71): warning C4996: 'libtorrent::fingerprint::name': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(90): note: see declaration of 'libtorrent::fingerprint::name'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(72): warning C4996: 'libtorrent::fingerprint::name': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(90): note: see declaration of 'libtorrent::fingerprint::name'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(73): warning C4996: 'libtorrent::fingerprint::major_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(91): note: see declaration of 'libtorrent::fingerprint::major_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(74): warning C4996: 'libtorrent::fingerprint::minor_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(92): note: see declaration of 'libtorrent::fingerprint::minor_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(75): warning C4996: 'libtorrent::fingerprint::revision_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(93): note: see declaration of 'libtorrent::fingerprint::revision_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(76): warning C4996: 'libtorrent::fingerprint::tag_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(94): note: see declaration of 'libtorrent::fingerprint::tag_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(78): warning C4996: 'libtorrent::fingerprint': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(82): note: see declaration of 'libtorrent::fingerprint'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(63): warning C4996: 'libtorrent::fingerprint::fingerprint': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(83): note: see declaration of 'libtorrent::fingerprint::fingerprint'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(83): warning C4996: 'libtorrent::fingerprint': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(82): note: see declaration of 'libtorrent::fingerprint'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(85): warning C4996: 'libtorrent::fingerprint': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(82): note: see declaration of 'libtorrent::fingerprint'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(88): warning C4996: 'libtorrent::fingerprint': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(82): note: see declaration of 'libtorrent::fingerprint'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(94): warning C4996: 'libtorrent::fingerprint': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(82): note: see declaration of 'libtorrent::fingerprint'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(95): warning C4996: 'libtorrent::fingerprint::major_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(91): note: see declaration of 'libtorrent::fingerprint::major_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(96): warning C4996: 'libtorrent::fingerprint::minor_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(92): note: see declaration of 'libtorrent::fingerprint::minor_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(97): warning C4996: 'libtorrent::fingerprint::revision_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(93): note: see declaration of 'libtorrent::fingerprint::revision_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(102): warning C4996: 'libtorrent::fingerprint': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(82): note: see declaration of 'libtorrent::fingerprint'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(103): warning C4996: 'libtorrent::fingerprint::major_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(91): note: see declaration of 'libtorrent::fingerprint::major_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(104): warning C4996: 'libtorrent::fingerprint::minor_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(92): note: see declaration of 'libtorrent::fingerprint::minor_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(105): warning C4996: 'libtorrent::fingerprint::revision_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(93): note: see declaration of 'libtorrent::fingerprint::revision_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(108): warning C4996: 'libtorrent::fingerprint::name': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(90): note: see declaration of 'libtorrent::fingerprint::name'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(109): warning C4996: 'libtorrent::fingerprint::name': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(90): note: see declaration of 'libtorrent::fingerprint::name'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(111): warning C4996: 'libtorrent::fingerprint::tag_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(94): note: see declaration of 'libtorrent::fingerprint::tag_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(112): warning C4996: 'libtorrent::fingerprint': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(82): note: see declaration of 'libtorrent::fingerprint'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(85): warning C4996: 'libtorrent::fingerprint::fingerprint': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(83): note: see declaration of 'libtorrent::fingerprint::fingerprint'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(117): warning C4996: 'libtorrent::fingerprint': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(82): note: see declaration of 'libtorrent::fingerprint'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(122): warning C4996: 'libtorrent::fingerprint': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(82): note: see declaration of 'libtorrent::fingerprint'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(123): warning C4996: 'libtorrent::fingerprint::name': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(90): note: see declaration of 'libtorrent::fingerprint::name'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(124): warning C4996: 'libtorrent::fingerprint::tag_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(94): note: see declaration of 'libtorrent::fingerprint::tag_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(125): warning C4996: 'libtorrent::fingerprint::name': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(90): note: see declaration of 'libtorrent::fingerprint::name'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(125): warning C4996: 'libtorrent::fingerprint::major_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(91): note: see declaration of 'libtorrent::fingerprint::major_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(126): warning C4996: 'libtorrent::fingerprint::minor_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(92): note: see declaration of 'libtorrent::fingerprint::minor_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(126): warning C4996: 'libtorrent::fingerprint::revision_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(93): note: see declaration of 'libtorrent::fingerprint::revision_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(127): warning C4996: 'libtorrent::fingerprint::name': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(90): note: see declaration of 'libtorrent::fingerprint::name'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(128): warning C4996: 'libtorrent::fingerprint': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(82): note: see declaration of 'libtorrent::fingerprint'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(130): warning C4996: 'libtorrent::fingerprint': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(82): note: see declaration of 'libtorrent::fingerprint'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(122): warning C4996: 'libtorrent::fingerprint::fingerprint': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(83): note: see declaration of 'libtorrent::fingerprint::fingerprint'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(295): warning C4996: 'libtorrent::fingerprint': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(82): note: see declaration of 'libtorrent::fingerprint'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(300): warning C4996: 'libtorrent::fingerprint::name': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(90): note: see declaration of 'libtorrent::fingerprint::name'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(315): warning C4996: 'libtorrent::fingerprint::name': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(90): note: see declaration of 'libtorrent::fingerprint::name'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(323): warning C4996: 'libtorrent::fingerprint::name': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(90): note: see declaration of 'libtorrent::fingerprint::name'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(329): warning C4996: 'libtorrent::fingerprint::major_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(91): note: see declaration of 'libtorrent::fingerprint::major_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(329): warning C4996: 'libtorrent::fingerprint::minor_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(92): note: see declaration of 'libtorrent::fingerprint::minor_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(329): warning C4996: 'libtorrent::fingerprint::revision_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(93): note: see declaration of 'libtorrent::fingerprint::revision_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(331): warning C4996: 'libtorrent::fingerprint::tag_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(94): note: see declaration of 'libtorrent::fingerprint::tag_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(334): warning C4996: 'libtorrent::fingerprint::tag_version': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(94): note: see declaration of 'libtorrent::fingerprint::tag_version'
1>..\..\3rdParty\libtorrent\src\identify_client.cpp(404): warning C4996: 'libtorrent::fingerprint': was declared deprecated
1>D:\DevProjects-Cpp\VeronaTorrent\Source\3rdParty\libtorrent\include\libtorrent/fingerprint.hpp(82): note: see declaration of 'libtorrent::fingerprint'

If I understand correctly, when I have TORRENT_NO_DEPRECATE --- I shouldn't see these warnings, no?

P.S. Just to highlight - nothing from libtorrent is used currently in my exe project, I just compile libtorrent, nothing more, so all these warnings related to libtorrent only.

**Comment by arvidn** [comment]
``TORRENT_NO_DEPRECATE`` actually means deprecated functions and types are *not declared* in the interface. It can be used to ensure that you don't use anything that's deprecated.

That said, you're never supposed to see these warnings from *within* libtorrent anyway.

**Comment by arvidn** [comment]
does this solve it? https://github.com/arvidn/libtorrent/pull/2064

**Comment by Krakean** [comment]
Yep, a lot. Thanks :)
