### ISSUE TITLE
move_storage (?) breaks force_recheck

### ISSUE THREAD

**Issue by alervd** [arvidn/libtorrent#2054]
**Please provide the following information**

libtorrent version (or branch): 

#define LIBTORRENT_VERSION "1.1.3.0"
#define LIBTORRENT_REVISION "6afb0fd"

platform/architecture:

Windows 10 x86

compiler and compiler version:

Microsoft Visual C++ 2015

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

1. Create a magnet torrent. Set save_path to some temporary path.
2. Once the metadata is received, call move_storage with libtorrent::dont_replace flag to move to some real path (specified by the user initially).
3. Once storage_moved_alert is received call force_recheck to enable LT to resume downloading of existing files (if any).

What happens: I have 1.4GB file downloaded by 30%. LT sends torrent_checked_alert immediately without actually doing the recheck. The same happens again and again if I continue to call force_recheck (using the following scheme: torrent is paused. I call resume, call force_recheck, and pause it again when torrent_checked_alert is received).
But, once I allow LT to download for a few seconds, force_check starts to work as expected.

**Comment by arvidn** [comment]
I wonder if this is the ``stat_cache`` not being cleared for torrents when they are moved.

**Comment by arvidn** [comment]
would you mind testing this patch? https://github.com/arvidn/libtorrent/pull/2069

**Comment by arvidn** [comment]
@alervd have you had a chance to test my patch?

**Comment by alervd** [comment]
Unfortunately, no. We've switched back to 1.0.11 version of LT temporarily.

**Comment by arvidn** [comment]
I've merged the fix. if the problem persists, please re-open.
