### ISSUE TITLE
Connection to a remote tracker doesn't use the same outgoing port as seeds/peers

### ISSUE THREAD

**Issue by vg8open** [arvidn/libtorrent#2056]
**Please provide the following information**

**libtorrent version (or branch):
qBittorrent v3.3.12 64-bit (libtorrent-rasterbar 1.0.11+git8736a59adc65)

**platform/architecture:
Windows 10 x64

**compiler and compiler version:
Unknown

**please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I think this might be a libtorrent related bug hence why I post here as well.

I am using qBittorrent v3.3.12 64-bit with the Outgoing ports (Min) and Outgoing ports (Max) settings to limit the port range.  The seeds/peers connections does use the specified port range, but the connections to the remote trackers doesn't seem to use the port range set by the outgoing port min/max range limiter.  It's using some random ports instead.

I would like to request that the connections to the seeds/peers and the connections to announce to the remote trackers use the same port range.

Forum thread: https://qbforums.shiki.hu/index.php/topic,5054.0.html
qBittorrent bug report: https://github.com/qbittorrent/qBittorrent/issues/6833

**Comment by arvidn** [comment]
The port range was not intended to apply to anything other than peers. I believe this is a simple way of applying packet priorities at routers to deprioritize bulk data transfers.

Sine this would be a new feature, what is use case for this?

**Comment by vg8open** [comment]
Currently the outbound connection ports are random and the remote trackers doesn't use a standard port, so it is impossible to setup a firewall rule to allow the outbound connections.  I want to limit the outbound connections to a specific port range so that I can setup a firewall rule to allow outbound bittorrent traffic.
