### ISSUE TITLE
Static link libtorrent and boost asio issue

### ISSUE THREAD

**Issue by eskin** [arvidn/libtorrent#206]
If i build libtorrent with link=static boost-link=static and then link it to my app, my app will export asio symbols.
How i can remove the asio export symbols from my executable?

I use asio and boost only for libtorrent.

I think BOOST_ASIO_SEPARATE_COMPILATION - is evil.

**Comment by arvidn** [comment]
yes. I recognize that it was a mistake to try to wrestle boost.asio into building with separate compilation and still not export symbols.

This has been fixed in master, where boost asio is used headers only again.

Could you give this a try? https://github.com/arvidn/libtorrent/pull/208

**Comment by eskin** [comment]
Thanks! This fix is ok!

Now i have only two unwanted exports:
````
class std::_Init_locks & std::_Init_locks::operator=(class std::_Init_locks const &)
std::_Mutex::_Mutex(enum std::_Uninitialized)
````

But i think it's a compiller bug.. (MSVC 2005-2010) And fixed it by this:
````
#include <new>
namespace std { const nothrow_t nothrow = nothrow_t(); }
````

**Comment by arvidn** [comment]
can you think of any ABI incompatibility with this patch? I would expect ABI compatibility to only matter for shared libraries, and this shouldn't affect those.
