### ISSUE TITLE
Magnet: torrent_handle::move_storage does nothing while receiving metadata

### ISSUE THREAD

**Issue by alervd** [arvidn/libtorrent#2072]
libtorrent version (or branch):

#define LIBTORRENT_VERSION "1.1.3.0"
#define LIBTORRENT_REVISION "6afb0fd"

platform/architecture:

Windows 10, x86

compiler and compiler version:

Microsoft Visual C++ 2015

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Add a magnet torrent. Call `torrent_handle::move_storage` _before_ it received the metadata. There will be no corresponding `storage_moved_alert`/`storage_moved_failed_alert` issued by LT. As if I did not call `torrent_handle::move_storage` at all. Once the metadata is received, LT continues to download to old path (not a new one, specified with the call to `torrent_handle::move_storage`).
Worked fine with 1.0.9 version of LT.

**Comment by arvidn** [comment]
there appears to be a copy-paste bug in ``torrent::move_storage``

**Comment by arvidn** [comment]
does this patch fix it? https://github.com/arvidn/libtorrent/pull/2076

**Comment by alervd** [comment]
Yes, it does.

**Comment by alervd** [comment]
1.1.4 - still have the issue. Now it actually moves storage but the corresponding alert (`libtorrent::storage_moved_alert`) is not generated.

**Comment by alervd** [comment]
Arvid, please release some patch for 1.1.4 if possible so I could stay with this version. 
I'll have to roll back to old version again otherwise :(

**Comment by arvidn** [comment]
are you sure you have enabled ``storage_notifications`` in ``alert_mask``?
does [this](https://github.com/arvidn/libtorrent/blob/RC_1_1/src/torrent.cpp#L8963) line not run for you for some reason?

**Comment by alervd** [comment]
1. yes, i'm sure.
2. no, it does not, because valid_metadata() returns true.

**Comment by alervd** [comment]
oops, I forgot to mention that I call move_storage IMMEDIATELY once I get `metadata_received_alert`.

**Comment by alervd** [comment]
`storage_moved_alert` is generated as expected in case I call move_storage with a delay.

**Comment by arvidn** [comment]
could you give this patch a try? https://github.com/arvidn/libtorrent/pull/2352

**Comment by alervd** [comment]
Yes, this fixes the problem.
