### ISSUE TITLE
Cannot build libtorrent with no exceptions

### ISSUE THREAD

**Issue by Krakean** [arvidn/libtorrent#2082]
**Please provide the following information**

libtorrent version (or branch): latest master up to date.

platform/architecture: Windows, x64

compiler and compiler version: MSVC 2017

Trying to compile latest master using MSVC 2017 (solution generated with CMAKE) and got following errors:
2>D:\!GIT\Unsorted\libtorrent_master\src\bdecode.cpp(248): error C2610: 'libtorrent::bdecode_node &libtorrent::bdecode_node::operator =(libtorrent::bdecode_node &&) noexcept': is not a special member function which can be defaulted
2>D:\!GIT\Unsorted\libtorrent_master\src\bdecode.cpp(248): note: exception specification does not match the implicitly declared specification.
2>D:\!GIT\Unsorted\libtorrent_master\_boost\boost/asio/detail/impl/socket_ops.ipp(1987): error C3861: '_alloca': identifier not found (compiling source file D:\!GIT\Unsorted\libtorrent_master\src\alert.cpp)
2>chained_buffer.cpp
2>D:\!GIT\Unsorted\libtorrent_master\_boost\boost/asio/detail/impl/socket_ops.ipp(2196): error C3861: '_alloca': identifier not found (compiling source file D:\!GIT\Unsorted\libtorrent_master\src\alert.cpp)
2>D:\!GIT\Unsorted\libtorrent_master\_boost\boost/asio/detail/impl/socket_ops.ipp(1987): error C3861: '_alloca': identifier not found (compiling source file D:\!GIT\Unsorted\libtorrent_master\src\alert_manager.cpp)
2>D:\!GIT\Unsorted\libtorrent_master\_boost\boost/asio/detail/impl/socket_ops.ipp(2196): error C3861: '_alloca': identifier not found (compiling source file D:\!GIT\Unsorted\libtorrent_master\src\alert_manager.cpp)
2>D:\!GIT\Unsorted\libtorrent_master\_boost\boost/asio/detail/impl/socket_ops.ipp(1987): error C3861: '_alloca': identifier not found (compiling source file D:\!GIT\Unsorted\libtorrent_master\src\announce_entry.cpp)
2>D:\!GIT\Unsorted\libtorrent_master\_boost\boost/asio/detail/impl/socket_ops.ipp(2196): error C3861: '_alloca': identifier not found (compiling source file D:\!GIT\Unsorted\libtorrent_master\src\announce_entry.cpp)
2>choker.cpp
2>D:\!GIT\Unsorted\libtorrent_master\src\error_code.cpp(284): warning C4275: non dll-interface class 'boost::system::error_category' used as base for dll-interface struct 'libtorrent::http_error_category'
2>D:\!GIT\Unsorted\libtorrent_master\_boost\boost/system/error_code.hpp(186): note: see declaration of 'boost::system::error_category'
2>D:\!GIT\Unsorted\libtorrent_master\src\error_code.cpp(283): note: see declaration of 'libtorrent::http_error_category'
2>D:\!GIT\Unsorted\libtorrent_master\_boost\boost/asio/detail/impl/socket_ops.ipp(1987): error C3861: '_alloca': identifier not found (compiling source file D:\!GIT\Unsorted\libtorrent_master\src\block_cache.cpp)
2>D:\!GIT\Unsorted\libtorrent_master\_boost\boost/asio/detail/impl/socket_ops.ipp(2196): error C3861: '_alloca': identifier not found (compiling source file D:\!GIT\Unsorted\libtorrent_master\src\block_cache.cpp)
2>file_progress.cpp
2>lazy_bdecode.cpp
2>D:\!GIT\Unsorted\libtorrent_master\_boost\boost/asio/detail/impl/socket_ops.ipp(1987): error C3861: '_alloca': identifier not found (compiling source file D:\!GIT\Unsorted\libtorrent_master\src\create_torrent.cpp)
2>D:\!GIT\Unsorted\libtorrent_master\_boost\boost/asio/detail/impl/socket_ops.ipp(2196): error C3861: '_alloca': identifier not found (compiling source file D:\!GIT\Unsorted\libtorrent_master\src\create_torrent.cpp)
2>escape_string.cpp
2>string_util.cpp
2>file.cpp
2>path.cpp
2>D:\!GIT\Unsorted\libtorrent_master\_boost\boost/asio/detail/impl/socket_ops.ipp(1987): error C3861: '_alloca': identifier not found (compiling source file D:\!GIT\Unsorted\libtorrent_master\src\string_util.cpp)
2>D:\!GIT\Unsorted\libtorrent_master\_boost\boost/asio/detail/impl/socket_ops.ipp(2196): error C3861: '_alloca': identifier not found (compiling source file D:\!GIT\Unsorted\libtorrent_master\src\string_util.cpp)
2>fingerprint.cpp
2>gzip.cpp
2>D:\!GIT\Unsorted\libtorrent_master\_boost\boost/asio/detail/impl/socket_ops.ipp(1987): error C3861: '_alloca': identifier not found (compiling source file D:\!GIT\Unsorted\libtorrent_master\src\file_progress.cpp)
2>D:\!GIT\Unsorted\libtorrent_master\_boost\boost/asio/detail/impl/socket_ops.ipp(2196): error C3861: '_alloca': identifier not found (compiling source file D:\!GIT\Unsorted\libtorrent_master\src\file_progress.cpp)
2>hasher.cpp

and so on. Removing the "HAS_EXCEPTION=0" fixes issue.

**Comment by arvidn** [comment]
just looking at the first error. why would exceptions being enabled or not affect whether a move assignment operator is a thing?
Is msvc 2017 final, or is this a pre-release?

**Comment by arvidn** [comment]
all other errors seem to refer to ``_alloca``, which I suspect is more of an mavc-14 vs. msvc-15 issue. what do you think?

**Comment by Krakean** [comment]
Problem solved (somehow), thanks anyway Arvid. :)

**Comment by gtumanyan** [comment]
I confrim _alloca not found error when building without exceptions support

libtorrent version 1_2 latest master up to date
platform/architecture: Windows, x64
compiler and compiler version: MSVC 2022 Preview

**Comment by arvidn** [comment]
are you saying you tried to build `RC_1_2` *and* `master`, and both failed with `_alloca` missing?
libtorrent doesn't support building without exception support anymore.

When I build on linux without exceptions I get errors like this:

```
gcc.compile.c++ ../bin/gcc-9.2/debug-mode/exception-handling-off/link-static/threading-multi/src/bdecode.o
../src/bdecode.cpp: In function ‘libtorrent::bdecode_node libtorrent::bdecode(span<const char>, int, int)’:
../src/bdecode.cpp:778:46: error: exception handling disabled, use ‘-fexceptions’ to enable
  778 |                 if (ec) throw system_error(ec);
      |                                              ^
```

If you don't, could you share some more details on how you build?

**Comment by gtumanyan** [comment]
I'm sorry, it was `RC_1_2`
