### ISSUE TITLE
Segmentation fault calling set_piece_deadline with piece index out of range

### ISSUE THREAD

**Issue by keenser** [arvidn/libtorrent#2084]
libtorrent version (or branch):
1.1.3.0

platform/architecture:
x86_64 GNU/Linux

compiler and compiler version:
gcc version 6.3.0 20170516 (Debian 6.3.0-18) 

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
Calling set_piece_deadline with piece index larger than handle.get_torrent_info().num_pieces() causes sefgault
Python code below reproduces error

import libtorrent
s = libtorrent.session()
s.listen_on(6881, 6891)
session_settings = s.settings()
session_settings.strict_end_game_mode = False
s.set_settings(session_settings)
s.add_dht_router("router.bittorrent.com", 6881)
add_torrent_params = {}
add_torrent_params['url'] = torrent_url
add_torrent_params['save_path'] = '/tmp/'
add_torrent_params['auto_managed'] = False
add_torrent_params['paused'] = False
handle = s.add_torrent(add_torrent_params)
handle.set_piece_deadline(handle.get_torrent_info().num_pieces()+1,3000)

**Comment by arvidn** [comment]
does this look reasonable? https://github.com/arvidn/libtorrent/pull/2088

**Comment by keenser** [comment]
patch solved the issue. Thanks
