### ISSUE TITLE
Unable to compile under VS2017

### ISSUE THREAD

**Issue by Krakean** [arvidn/libtorrent#2085]
Hello.
Compiler: VS 2017.2 (15.2), x64.
Win 8.1, x64.
Latest libtorrent master git.

Trying to build separate .dll (wrapper for libtorrent) with libtorrent.lib, this is just sample file:
// C RunTime Header Files
#include <cstdlib>
#include <cstdint>
#include <malloc.h>
#include <memory.h>

// Very common & important C++ stuff
#include <cstring>
#include <vector>
#include <map>
#include <thread>

#include <SDKDDKVer.h>
#include <windows.h>

#include "libtorrent/entry.hpp"
#include "libtorrent/session.hpp" <-- if I DO NOT add this, everything compiles fine. But if I session.hpp, then I get these errors:
....
1>libtorrent.vcxproj -> D:\DevProjects-Csharp\VeronaTorrent\Source\3rdParty\libtorrent-wrapper\Solutions\Win\..\..\..\..\!Objs\Win_libtorrent_Debug_x64\libtorrent.lib
1>Done building project "libtorrent.vcxproj".
2>------ Build started: Project: libtorrent-wrapper, Configuration: Debug x64 ------
2>cl : Command line warning D9030: '/Gm' is incompatible with multiprocessing; ignoring /MP switch
2>libtorrent-wrapper.cpp
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\aux_\typed_span.hpp(94): warning C4003: not enough actual parameters for macro 'max'
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\sha1_hash.hpp(85): warning C4003: not enough actual parameters for macro 'max'
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\sha1_hash.hpp(95): warning C4003: not enough actual parameters for macro 'min'
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\sha1_hash.hpp(85): error C2059: syntax error: '('
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\sha1_hash.hpp(269): note: see reference to class template instantiation 'libtorrent::digest32<N>' being compiled
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\sha1_hash.hpp(85): error C2143: syntax error: missing ',' before '?'
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\sha1_hash.hpp(85): error C2382: 'libtorrent::digest32<N>::digest32': redefinition; different exception specifications
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\sha1_hash.hpp(77): note: see declaration of 'libtorrent::digest32<N>::digest32'
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\sha1_hash.hpp(85): error C2059: syntax error: '?'
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\sha1_hash.hpp(85): error C2059: syntax error: '{'
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\sha1_hash.hpp(85): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\sha1_hash.hpp(95): error C2059: syntax error: '('
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\sha1_hash.hpp(95): error C2143: syntax error: missing ',' before '?'
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\sha1_hash.hpp(95): error C2059: syntax error: '?'
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\sha1_hash.hpp(95): error C2059: syntax error: '{'
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\sha1_hash.hpp(95): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\sha1_hash.hpp(77): error C2333: 'libtorrent::digest32<160>::digest32': error in function declaration; skipping function body
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\sha1_hash.hpp(299): note: see reference to class template instantiation 'libtorrent::digest32<160>' being compiled
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\aux_\vector.hpp(88): warning C4003: not enough actual parameters for macro 'max'
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\aux_\array.hpp(49): warning C4003: not enough actual parameters for macro 'max'
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\aux_\array.hpp(49): error C2589: '(': illegal token on right side of '::'
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\aux_\array.hpp(83): note: see reference to class template instantiation 'libtorrent::aux::array<T,Size,IndexType>' being compiled
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\bitfield.hpp(256): note: see reference to class template instantiation 'libtorrent::aux::unique_ptr<uint32_t [],int>' being compiled
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\aux_\array.hpp(49): error C2062: type 'unknown-type' unexpected
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\aux_\array.hpp(49): error C2334: unexpected token(s) preceding ':'; skipping apparent function body
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\aux_\array.hpp(83): error C2143: syntax error: missing ')' before ';'
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\aux_\array.hpp(83): error C2059: syntax error: ')'
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\aux_\array.hpp(83): error C2238: unexpected token(s) preceding ';'
2>d:\devprojects-csharp\veronatorrent\source\3rdparty\libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\aux_\array.hpp(83): fatal error C1201: unable to continue after syntax error in class template definition
2>Generating Code...
2>Skipping... (no relevant changes detected)
2>dllmain.cpp
2>stdafx.cpp
2>Done building project "libtorrent-wrapper.vcxproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

Something else should be included, to avoid these errors?

**Comment by arvidn** [comment]
something appears to be including ``windows.h`` without the ``WIN32_LEAN_AND_MEAN`` macro defined. This causes that header to poop all over symbol names. specifically, ``min`` and ``max``.

If you feel up for it, either figure out where that include comes from and how windows.h can be curbed and submit a PR with a fix. Or, just defined ``WIN32_LEAN_AND_MEAN`` at your project level.

**Comment by Krakean** [comment]
#define NOMINMAX before Windows.h solved the problem.

P.S. WIN32_LEAN_AND_MEAN was already defined in preprosessor definitions group.
