### ISSUE TITLE
crash disk_buffer_pool::free_multiple_buffers

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#2089]
libtorrent version (or branch): master
platform/architecture: x86
compiler and compiler version: vc++2017

https://drdump.com/Problem.aspx?ProblemID=304135&login=guest

flylinkdc!libtorrent::disk_buffer_pool::free_multiple_buffers+0xb1
flylinkdc!libtorrent::block_cache::evict_piece+0x168
flylinkdc!libtorrent::block_cache::maybe_free_piece+0x73
flylinkdc!libtorrent::disk_io_thread::flush_range+0x1bc
flylinkdc!libtorrent::disk_io_thread::try_flush_hashed+0x5cd
flylinkdc!libtorrent::disk_io_thread::do_flush_piece+0x83
flylinkdc!libtorrent::disk_io_thread::perform_job+0x95
flylinkdc!libtorrent::disk_io_thread::thread_fun+0x2f4
flylinkdc!libtorrent::disk_io_thread::job_queue::thread_fun+0x36
flylinkdc!std::_LaunchPad<std::unique_ptr<std::tuple<void (__thiscall libtorrent::pool_thread_interface::*)(libtorrent::disk_io_thread_pool &,boost::asio::io_service::work),libtorrent::pool_thread_interface *,std::reference_wrapper<libtorrent::disk_io_thread_pool>,boost::asio::io_service::work>,std::default_delete<std::tuple<void (__thiscall libtorrent::pool_thread_interface::*)(libtorrent::disk_io_thread_pool &,boost::asio::io_service::work),libtorrent::pool_thread_interface *,std::reference_wrapper<libtorrent::disk_io_thread_pool>,boost::asio::io_service::work> > > >::_Run+0x50
flylinkdc!std::_Pad::_Call_func+0x14
flylinkdc!wcsftime+0xf5
kernel32!BaseThreadInitThunk+0xe
ntdll!__RtlUserThreadStart+0x70
ntdll!_RtlUserThreadStart+0x1b

**Comment by arvidn** [comment]
most of the useful information to understand what happened here will likely be in that minidump, and only you can look at that, since that requires the original binary and debug information.

Could you look around for hints and post any findings here?

**Comment by aldenml** [comment]
is this crash still happening to you? I think it was solved with https://github.com/arvidn/libtorrent/pull/2440
