### ISSUE TITLE
move_storage breaks rename_file.

### ISSUE THREAD

**Issue by alervd** [arvidn/libtorrent#2092]
libtorrent version (or branch):

#define LIBTORRENT_VERSION "1.0.11.0"
#define LIBTORRENT_REVISION "bbb38a9"

platform/architecture:

Windows 10, x86

compiler and compiler version:

Microsoft Visual C++ 2015

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

1. Create a magnet torrent. Set save_path to some temporary path.
2. Once the metadata is received, call `rename_file` on some of its files. 
3. Immediately after that, call `move_storage` with `libtorrent::dont_replace` flag to move to some real path (specified by the user initially).

What happens: the files remains non-renamed, as if `rename_file` was not called at all. 

Currently I use the following workaround: I call `rename_file`, wait for LT to process the call, and only then I call `move_storage`.

**Comment by arvidn** [comment]
do you see the alert in response to ``rename_file()``?

**Comment by alervd** [comment]
It seems the bug is on our side. I'll report here more details as soon as I finish investigating it.

**Comment by alervd** [comment]
Yes, the problem was on our side: buggy code was renaming file back to original name without me noticing it. Sorry.
