### ISSUE TITLE
1.1 regression - Cannot change queue position when paused

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#2097]
I have noticed with lt 1.1.3 that paused torrents no longer can have their queue position changed. You need to resume the torrent then change queue position.

This works as expected in lt 1.0.

**Comment by arvidn** [comment]
This regression was introduced by https://github.com/arvidn/libtorrent/pull/1617

**Comment by arvidn** [comment]
patch here: https://github.com/arvidn/libtorrent/pull/2104
@Falcosc would you mind taking a look?

**Comment by Falcosc** [comment]
sorry, not soon. During winter I could take more time for github.
