### ISSUE TITLE
Python sha1_hash() broken

### ISSUE THREAD

**Issue by aresch** [arvidn/libtorrent#211]
```
>>> h = lt.sha1_hash('44a040be6d74d8d290cd20128788864cbf770719')
>>> print(h)
3434613034306265366437346438643239306364
>>> h.to_string()
'44a040be6d74d8d290cd'
>>> str(h)
'3434613034306265366437346438643239306364'
```
It looks like it only stores 20 of the 40 bytes..

**Comment by aresch** [comment]
When I print out the sha1_hash from a valid torrent_handle it is valid.
```
>>> print([str(th.info_hash()) for th in core.session.get_torrents()])
['44a040be6d74d8d290cd20128788864cbf770719']
>>> th = core.session.get_torrents()[0]
>>> print(th.info_hash())
44a040be6d74d8d290cd20128788864cbf770719
```

**Comment by arvidn** [comment]
a SHA-1 hash is only 20 bytes (which is 40 hex digits, when printed as hex). The sha1_hash constructor takes a pointer to 20 bytes, when you pass in 40 bytes, it will still just copy the first 20. When you print those bytes, it will give you 20 (raw) bytes, which in this case also happens to be printable ascii characters.

in short, when constructing the sha1_hash object, you have to convert your hex to binary.

**Comment by aresch** [comment]
I tried so many things I wasn't sure what was right :) I think there is still a bug (different) between python 2 and 3.

I got this working in Python 2 now.

```
>>> h = '44a040be6d74d8d290cd20128788864cbf770719'
>>> binascii.unhexlify(h)
b'D\xa0@\xbemt\xd8\xd2\x90\xcd \x12\x87\x88\x86L\xbfw\x07\x19'
>>> print lt.sha1_hash(binascii.unhexlify(h))
44a040be6d74d8d290cd20128788864cbf770719
```

In Python 3, it gives an error presumably because it doesn't like the new 'bytes' type in Python 3.
```
>>> lt.sha1_hash(binascii.unhexlify(h))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Boost.Python.ArgumentError: Python argument types in
    sha1_hash.__init__(sha1_hash, bytes)
did not match C++ signature:
    __init__(_object*, char const*)
    __init__(_object*)
```

**Comment by aresch** [comment]
https://svn.boost.org/trac/boost/ticket/4609

This ticket seems to suggest if we change the 'char const*' to a 'std::string' it should convert the bytes object appropriately.

**Comment by aresch** [comment]
Doing that fixes it for Python 3.

I've got a pull request here: https://github.com/arvidn/libtorrent/pull/214

I imagine it will merge into master fine too.
