### ISSUE TITLE
Some bdecode_node methods are unexpectedly non-const

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#2110]
libtorrent version (or branch): latest RC_1_1

I don't understand why bdecode_node has inconsistent interface: almost all value accessors declared as const but not `list_string_value_at()` and `list_int_value_at()`.

**Comment by arvidn** [comment]
this looks like an oversight

**Comment by arvidn** [comment]
Fixed here: https://github.com/arvidn/libtorrent/pull/2113
