### ISSUE TITLE
flag_override_resume_data flag breaks torrent_handle::file_priorities

### ISSUE THREAD

**Issue by alervd** [arvidn/libtorrent#2124]
libtorrent version (or branch):

#define LIBTORRENT_VERSION "1.0.11.0"
#define LIBTORRENT_REVISION "bbb38a9"

platform/architecture:

Windows 10, x86

compiler and compiler version:

Microsoft Visual C++ 2015

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

1. Add a torrent with several files and prioritize files thus only the last file is chosen to be downloaded.
2. Let it to download something, save fast resume data, exit app.
3. Start app, add the same torrent with the fast resume data saved earlier. Use `flag_override_resume_data` flag when adding the torrent.

What happens: `torrent_handle::file_priorities` returns vector with priorities set to 1 (in the resume data all priorities are set to 0 except the last once set to 4). In the same time, torrent continues to download only the last file.

**Comment by arvidn** [comment]
Just to be clear, you would expect all files to be downloaded, right? since the ``add_torrent_param`` would override the resume data

**Comment by arvidn** [comment]
The simplest way to fix this in RC_1_1 would be to declare that file priorities are not subject to ``flag_override_resume_data``. Would that be a bad idea?

In master the resume data mechanism has been improved to not have this issue, since the resume data is parsed on the client side (``read_resume_data``) before being passed to the session.

**Comment by arvidn** [comment]
@alervd do you have any opinions about my proposed fix?

**Comment by arvidn** [comment]
i.e. this one https://github.com/arvidn/libtorrent/pull/2136

**Comment by alervd** [comment]
I expect `flag_override_resume_data` to not affect priorities at all.

**Comment by arvidn** [comment]
Ok, that's what that patch does. I will add a test to it before merging.

**Comment by arvidn** [comment]
i.e. in your case, the error was that when asking for the file priorities, you got back 1 for all files instead of 0 (except the last one).

**Comment by alervd** [comment]
yes.

**Comment by arvidn** [comment]
I realized you're using 1.0. Here's a patch against RC_1_0. https://github.com/arvidn/libtorrent/pull/2145
Do you think you could give it a try?
