### ISSUE TITLE
Question about safety of async_receive in netlink ip_change_notifier_impl

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#2129]
libtorrent version (or branch): `master`
platform/architecture: linux/android

Hi @ssiloti, maybe this is related to the crashes in the DHT. Do you know if it is possible that calls to `m_socket.async_receive` stack without finishing `reopen_listen_sockets();`, since the later is called after `m_ip_notifier->async_wait`?

**Comment by ssiloti** [comment]
You mean multiple receive calls on a UDP packet? I don't see how `reopen_listen_sockets` could cause that. I'm not sure what `m_ip_notifier` would have to do with it. The ordering of the calls in `session_impl::on_ip_change` shouldn't make a difference, either way the next notification event won't be processed until the current event handler finishes.

**Comment by aldenml** [comment]
The problem I think is that somehow `reopen_listen_sockets` is called rapidly multiple times, and that destroy/re-creates DHT nodes, and some UDP packets are in the process, and when the times come to touch the destroyed node memory, it crash. Does this makes sense?

I'm not sure if this `session_impl::on_ip_change` is called serially within the packets processing thread.

**Comment by ssiloti** [comment]
Incoming packets are forwarded to nodes by iterating `dht_tracker::m_nodes` so they shouldn't be getting forwarded to destroyed nodes regardless of how much socket creation/destruction is going on.

`on_ip_change` runs in the network thread so it gets serialized along with all the other network events.

**Comment by aldenml** [comment]
Thanks, I see it now
