### ISSUE TITLE
b2 doesn't install headers

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#213]
`b2 install` doesn't install the headers. It installs only the .lib file (static build on Windows) even though I have set a prefix `b2 --prefix=<path>`.

After some testing I have found that commit 8f8950538975540 has broken the install. It worked before.

Tested with latest RC_1_0.

**Comment by arvidn** [comment]
I'm guessing it's this attribute: <install-source-root>libtorrent
would you mind putting that back to see if it works?

**Comment by sledgehammer999** [comment]
It works only if I add `<install-source-root>libtorrent` and remove `<install-type>LIB`.

**Comment by arvidn** [comment]
does this patch look good? https://github.com/arvidn/libtorrent/pull/217

**Comment by sledgehammer999** [comment]
I am trying it now. Wait a few minutes.

**Comment by sledgehammer999** [comment]
Confirmed. That PR works.
Totally unrelated: If you add `closes #<number>` anywhere in your commit message github will autoclose the corresponding bug when the commit is merged/pushed into master. Other branches just create a reference in the corresponding bug.

**Comment by arvidn** [comment]
allright, thanks. I'll try to remember that :P
