### ISSUE TITLE
Dislocation of select_platform_config.hpp in boost 1.65

### ISSUE THREAD

**Issue by qzmfranklin** [arvidn/libtorrent#2130]
libtorrent version (or branch):
master
6425cfbc4fbdb509fb131bde3475a10eab4a5af5

platform/architecture:
x86_64
Ubuntu 16.04

compiler and compiler version:
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I pulled in the latest version of the boost library from https://github.com/boostorg/boost (v1.65-dev) and tried building libtorrent with it via the autotools build approach. The problem I saw was that the `boost::config` module changed the location of the `select_platform_config.hpp` file from `boost/config` to `boost/config/detail`.

I already had a fix for it:
```
iff --git a/include/libtorrent/export.hpp b/include/libtorrent/export.hpp
index 87536af..b00b2c6 100644
--- a/include/libtorrent/export.hpp
+++ b/include/libtorrent/export.hpp
@@ -34,14 +34,14 @@ POSSIBILITY OF SUCH DAMAGE.
 #define TORRENT_EXPORT_HPP_INCLUDED
 
 #if !defined(BOOST_COMPILER_CONFIG) && !defined(BOOST_NO_COMPILER_CONFIG)
-#  include <boost/config/select_compiler_config.hpp>
+#  include <boost/config/detail/select_compiler_config.hpp>
 #endif
 #ifdef BOOST_COMPILER_CONFIG
 #  include BOOST_COMPILER_CONFIG
 #endif
 
 #if !defined(BOOST_PLATFORM_CONFIG) && !defined(BOOST_NO_PLATFORM_CONFIG)
-#  include <boost/config/select_platform_config.hpp>
+#  include <boost/config/detail/select_platform_config.hpp>
 #endif
 #ifdef BOOST_PLATFORM_CONFIG
 #  include BOOST_PLATFORM_CONFIG
```

I would like to see libtorrent officially supports building with the new version (v1.65) of the `boost` library.

**Comment by arvidn** [comment]
perhaps it was a mistake to include headers this deep into boost.config. It was just an attempt to distill out just what was needed for the EXPORT macros. It should probably be changed to just include the top-level boost.config header

**Comment by qzmfranklin** [comment]
Thanks a lot for the confirmation and also for adding it to the planned work. Really appreciate it!

**Comment by arvidn** [comment]
pull requests are welcome if you would like to give this a stab! :) (if so, it should go into the RC_1_1 branch to make it into the next stable release)

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/2146
