### ISSUE TITLE
SSL 1.1+ changed API

### ISSUE THREAD

**Issue by qzmfranklin** [arvidn/libtorrent#2131]
libtorrent version (or branch):
branch: `master`
commit: `6425cfbc4fbdb509fb131bde3475a10eab4a5af5`

platform/architecture:
x86_64
Ubuntu 16.04

compiler and compiler version:
`gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609`

please describe what symptom you see, what you would expect to see instead and
how to reproduce it:

I am trying to build the `examples/client_test` binary while linking against the latest openssl (https://github.com/openssl/openssl, commit=`86ba26c80a49aee3c588d286d91eb3843529f7e2`). The following symbols from the `libssl` and `libcrypto` are missing because openssl 1.1+ API removed these symbols:
```
CRYPTO_cleanup_all_ex_data
CRYPTO_num_locks
CRYPTO_set_locking_callback
ENGINE_cleanup
ERR_free_strings
EVP_cleanup
OPENSSL_add_all_algorithms_noconf
SSL_library_init
SSL_load_error_strings
SSLv23_client_method
SSLv23_method
SSLv23_server_method
sk_num
sk_value
```

The 'solution' to get it working, as the openssl wiki (https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes) suggests, is to compile all libtorrent source code with the following macro to pin down the API version to 1.0.0:
```
-DOPENSSL_API_COMPAT=0x10000000L
```

Not sure what's the plan for building with the latest openssl implementation. If would be best if there is active plans to port the usage of openssl API to 1.1.0+. If not, mentioning this caveat somewhere in the `building.rst` or some relevant docs might be useful.

Thanks,
Zhongming

**Comment by arvidn** [comment]
libtorrent does not directly call those functions, but boost.asio does. I think such fix belongs there. Either by having it pin down the OpenSSL version or by use whatever new functions there are instead.

**Comment by qzmfranklin** [comment]
Thanks for mentioning.

**Comment by arvidn** [comment]
it seems appveyor's mingw environment use openssl1.1 now, causing the builds to fail. I tried adding that define you suggested, but it didn't seem to help. Do you have any advice on how to get it to work, despite boost.asio using the 1.0 API?

https://ci.appveyor.com/project/arvidn/libtorrent/build/6784

**Comment by arvidn** [comment]
it seems to have been an unrelated issue
