### ISSUE TITLE
Question about settings_pack::allow_partial_disk_writes

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#2139]
libtorrent version (or branch): `master`
platform/architecture: `all`

Hi @arvidn, this could be trivial or not, but I'm confused by the following (due to poor understanding).

The comment in `disk_io_thread.cpp:L381` is:
```
// at this point, we may enforce flushing full cache stripes even when
// they span multiple pieces. This won't necessarily work in the general
// case, because it assumes that the piece picker will have an affinity
// to download whole stripes at a time. This is why this setting is turned
// off by default, flushing only one piece at a time
```
but the default value is `true` and the documentation in the setting is:
```
// when set to false, the ``write_cache_line_size`` will apply across
// piece boundaries. this is a bad idea unless the piece picker also
// is configured to have an affinity to pick pieces belonging to the
// same write cache line as is configured in the disk cache.
```

My question is: What's the "best" value and is `true=>enable`? Thanks

**Comment by arvidn** [comment]
ah, that name was probably changed to invert its meaning. partial disk writes *should* be allowed. The main reason I added this option to support [btfs](http://blog.libtorrent.org/2014/12/a-bittorrent-filesystem/). Which in hindsight may not have been a great idea given how specialized is need is.

``true`` is the correct default setting.

**Comment by arvidn** [comment]
actually, it looks like the documentation *is* correct.

**Comment by aldenml** [comment]
thanks for the clarification
