### ISSUE TITLE
* added support for sending tracker announces on every network interface

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#2142]
Looking at this I'm left wondering the way to know if the tracker is working/updating or not, prior to this it was either working or not but now you get a vector of endpoints that one entry could be working while others could not.

Say this is what you open as the listen interface:

`pack.set_str(settings_pack::listen_interfaces , "0.0.0.0:0,[::]:0,0.0.0.0:0s,[::]:0s");`

then you get these listen succeed alerts:

```
successfully listening on [TCP] 0.0.0.0:64300
successfully listening on [UDP] 0.0.0.0:52736
successfully listening on [TCP/SSL] 0.0.0.0:64301
successfully listening on [uTP/SSL] 0.0.0.0:52737
successfully listening on [TCP] [fe80::9596:c4b3:8ae4:ddaf%10]:64302
successfully listening on [UDP] [fe80::9596:c4b3:8ae4:ddaf%10]:52738
successfully listening on [TCP/SSL] [fe80::9596:c4b3:8ae4:ddaf%10]:64303
successfully listening on [uTP/SSL] [fe80::9596:c4b3:8ae4:ddaf%10]:52739
```

and that ends you up with four endpoints in the endpoints vector for each tracker on a torrent, now there does not appear to be anything in the public section of `announce_endpoint` to determine what endpoint is referencing what interface so its hard to tell if the tracker is behaving as it should.

In the example above I hove one http tracker on a torrent and it gets the four endpoints, is it the case this tracker is now unnecessarily trying to connect through the upd and ssl interfaces that dont support the tracker?

**Comment by arvidn** [comment]
hm.. torrents should probably only announce over their SSL interface if the torrent itself is an SSL torrent, and vice versa. That would bring down your example to only getting one announce per address family, which would make sense.

@ssiloti does that sound right?

**Comment by ssiloti** [comment]
Yes that sounds right. I confess I forgot about SSL torrents/sockets when writing this code since it is a rarely used feature. INow that I think about it, SSL listen sockets also need to be excluded from having DHT nodes started on them.

**Comment by Col-blimp** [comment]
`std::min_element` was what I needed with determining the state of the tracker then to exclude the endpoints vector from dumping a torrent outside the session and then it all makes sense.

**Comment by Col-blimp** [comment]
https://github.com/arvidn/libtorrent/pull/2143 fixed with that, thanks.
