### ISSUE TITLE
feature request: ssl certificate revocation

### ISSUE THREAD

**Issue by jmpetroske** [arvidn/libtorrent#2153]
I am using SSL torrents, but am needing a way to revoke access to a torrent. I'm thinking we would pass a SSL certificate revocation list to libtorrent somewhere, and libtorrent would then reject any peer using a revoked cert. 

Is there anything like this in libtorrent I missed? I'd be happy to work on this if it doesn't exist

**Comment by arvidn** [comment]
there is no support for this in libtorrent now. A PR with support would be great.
do you think the tracker should be able to send a revocation list, or are you thinking some other (client defined) channel would be better?

**Comment by jmpetroske** [comment]
I think as a start, a client defined channel would be best. I'm not sure if the tracker sending a revocation list makes sense, as I don't know of any tracker that currently does this. 

Do you have any thoughts of where it makes sense to add this to the API? I was thinking adding something like torrent_handle::revoke_ssl_certificates() would make sense, although putting it in the session class could make sense too.

**Comment by arvidn** [comment]
I don't have strong opinions of whether revoking should happen per-torrent or for the whole session. Part of me feel like session-wide revocations may be less error prone. How likely are you to want to effect a revocation in some torrents but not others? I would imagine a revoked certificate is mostly a global state, that everyone everywhere should honor.
