### ISSUE TITLE
BfLLR.dll Causing qBittorrent to crash almost immediately after starting (Re-Post from qBittorrent)

### ISSUE THREAD

**Issue by GhostPratt** [arvidn/libtorrent#2163]
qBittorrent version and Operating System: 3.3.13.0 on Windows 7 Ultimate
Libittorrent version: 1.0.11.0
Boost: 1.63
QT: 5.8

If on linux, libtorrent and Qt version:

What is the problem:

The program crashes within a few minutes of being started. This happens everytime time it runs.
EDIT: The crashes appear to be whenever a download completes.

From the Windows Application Log:

Description:
Faulting application name: qbittorrent.exe, version: 3.3.13.0, time stamp: 0x592f61ed
Faulting module name: BfLLR.dll, version: 8.0.3.11, time stamp: 0x4ffc51c6
Exception code: 0xc0000005
Fault offset: 0x000000000000d288
Faulting process id: 0x21e8
Faulting application start time: 0x01d300af2841f913
Faulting application path: D:\Program Files (x86)\qBittorrent\qbittorrent.exe
Faulting module path: C:\windows\system32\BfLLR.dll
Report Id: 9cf58890-6ca2-11e7-bc8a-8c89a504262d
Event Xml:

1000
2
100
0x80000000000000

107817
Application
Toria

qbittorrent.exe
3.3.13.0
592f61ed
BfLLR.dll
8.0.3.11
4ffc51c6
c0000005
000000000000d288
21e8
01d300af2841f913
D:\Program Files (x86)\qBittorrent\qbittorrent.exe
C:\windows\system32\BfLLR.dll
9cf58890-6ca2-11e7-bc8a-8c89a504262d

What is the expected behavior:

Steps to reproduce:

Open program, wait.

Extra info(if any):

**Comment by aldenml** [comment]
How is this crash related to `libtorrent`? `BfLLR.dll` seems like something used inside qBittorrent

**Comment by GhostPratt** [comment]
They said to post it here, here is the link to the original: 
https://github.com/qbittorrent/qBittorrent/issues/7121

**Comment by aldenml** [comment]
Well...seems like a very quick forwarding...

I'm not familiar with that `1.0.11.0` version, can't say anything else.

**Comment by arvidn** [comment]
at the very least I would need a stack trace to have any hope of understanding why this fails. I cannot make libtorrent create crashdumps, but qBitTorrent could.

Could you build a debug build of everything in qBT and run it in a debugger to provide more information?
