### ISSUE TITLE
clear stat_cache on force-recheck

### ISSUE THREAD

**Issue by nick-s-b** [arvidn/libtorrent#2181]
**Please provide the following information**

libtorrent version (or branch): libtorrent-rasterbar 1:1.1.4-1
platform/architecture: X86_64
compiler and compiler version: whatever Arch compiles libs with... I presume GCC.

After I finished downloading a torrent with qBittorrent, I removed it from qB. Later on, I wanted to seed the file so I double-clicked on the .torrent file, clicked OK to add it ("Start torrent" was selected, "Skip hash check" was deselected.)

qBittorrent just started sending notices that the file has finished downloading and couldn't seed the file because the check was never completed. Checking just oscillated between zero and some random values.

Here is the video of what qB was doing: 600kb, mkv video: http://ge.tt/5uPvQul2

I originally posted this issue on qB tracker but was told this is a libtorrent issue: https://github.com/qbittorrent/qBittorrent/issues/7152

Thanks!

**Comment by arvidn** [comment]
when reporting issues against libtorrent, please report symptoms and interactions with the *libtorrent interface*. For instance, what are the calls made into libtorrent that's causing the issue? are there any alerts or debug logs that may provide hints of what is going on?

I do not think that it's obvious that this is a libtorrent issue. It looks like qBittorrent keeps rechecking files every time the check completes.

**Comment by Seeker2** [comment]
Similar qBitTorrent problem:
Force recheck does nothing if files are updated after adding torrent  https://github.com/qbittorrent/qBittorrent/issues/6124

Vaguely/slightly similar qBitTorrent problem:
Force Recheck not working (qBT restart needed)  https://github.com/qbittorrent/qBittorrent/issues/6557

**Comment by arvidn** [comment]
libtorrent cache the result of ``stat()`` of all files. If it looks for files that aren't there, it won't look again until libtorrent itself writes them. This is clearly not ideal in the case of a *force* recheck.

I'll make sure the cache is cleared in that case

**Comment by Seeker2** [comment]
Something screwy about Force recheck even besides that:
Tracker updates done while torrent paused...if Force Rechecking torrent data  https://github.com/qbittorrent/qBittorrent/issues/6137

I've even seen where the torrent starts downloading while paused because I attempted to force recheck it.

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/2209

**Comment by arvidn** [comment]
merged

**Comment by arvidn** [comment]
@Seeker2 I'll look into tracker announces while checking. The "downloading while paused" may be related to how checking torrents also need to be "unpaused" in order for the checking to start. i.e. it's possible to pause checking torrents, and to re-order the queue of checking torrents. However, if the torrent should not start downloading after checking is complete, the client need to set it into a state to make it pause, or manually pause the torrent once it's done (but that has a race condition and is likely to let an announce out first).
