### ISSUE TITLE
SSL torrents + ut_metadata

### ISSUE THREAD

**Issue by jameskeane** [arvidn/libtorrent#2192]
If already have a valid keypair, could I connect to an SSL swarm and download the metadata?

Looking at the code, it appears that an ssl cert can't be set until `m_ssl_ctx` has been initialized; which currently requires valid metadata.

Is there any reason we couldn't initialize the ssl context earlier, maybe add `ssl_cert` to `add_torrent_params`?

**Comment by arvidn** [comment]
yeah, the only reason I can recall, is that the root cert is in the metadata right now

**Comment by arvidn** [comment]
and I agree, rather than setting up the cert on the torrent_handle, it should be set up as the torrent is added, in ``add_torrent_params``. pull requests are welcome!
