### ISSUE TITLE
Python bindings : have_piece return True for out of range index

### ISSUE THREAD

**Issue by rllola** [arvidn/libtorrent#2193]
libtorrent version (or branch): master

platform/architecture: linux 16.04/x86_64

```
// Sintel torrent
// file_size : 129241752
// piece_size : 131072
// number of piece : 986

piece_index = 986
handle.have_piece(piece_index) // True

piece_index = 987
handle.have_piece(piece_index) // True but expect False or error
```
And when I try `read_piece` I have segment fault or sometimes a null buffer.

**Comment by arvidn** [comment]
calling ``have_piece`` with an invalid index is currently undefined behavior. However, it would make sense to trigger an error.

**Comment by arvidn** [comment]
addressed here: https://github.com/arvidn/libtorrent/pull/3193
