### ISSUE TITLE
Status of BEP 33 in libtorrent

### ISSUE THREAD

**Issue by MaChengxin** [arvidn/libtorrent#2198]
I've seen [this](https://github.com/arvidn/libtorrent/commit/58d723012ae75c0bd66bc6dd89293d5d24fb5c05) and [this](https://github.com/arvidn/libtorrent/blame/c4eb4c8b5f829215a50aaf2722ab19f8bf628ca1/test/test_dht.cpp#L1154) that indicate [BEP 33](http://www.bittorrent.org/beps/bep_0033.html) is already in libtorrent, but it is not in the [feature list](https://github.com/arvidn/libtorrent/blob/master/docs/features.rst).
I am just wondering if it is not fully implemented, or just not documented.

**Comment by arvidn** [comment]
serving scrape results to other DHT nodes requesting it is supported. I don't believe there's any support for making DHT scrape requests.
