### ISSUE TITLE
No error with publicbt.com tracker

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#221]
It seems that the publicbt.com tracker `udp://tracker.publicbt.com:80` is permanently down but it remains in 'announce sent' and never errors-out so libtorrent doesn't switch to other trackers.

**Comment by arvidn** [comment]
is this with 1.0.6?

**Comment by cas--** [comment]
Ah yes

**Comment by arvidn** [comment]
I just tested this in the RC_1_0 with the default settings in client_test, and as far as I can tell it works. I get a timeout on publicbt and it moves on. what settings are you using? specifically, do you announce to all tiers? or all trackers per tier? are all trackers in separate tiers in your example?

**Comment by arvidn** [comment]
I suppose it's possible this has been fixed between 1.0.6 and head of 1.0.x. I'll run the same test from the release tag

**Comment by cas--** [comment]
Oh sorry I made a mess of reporting this, I assumed I'd updated my other server to 1.0.6 but it's actually still 0.16.19! I shall retest with 1.0.6.

For reference the specific issue I am seeing is adding a magnet uri with 3 trackers so all added in `tier 0` and publicbt was first in the list and no other tracker is attempted. The multi-tracker announce settings are default.

**Comment by cas--** [comment]
Just to confirm this is fixed by moving from 0.16.19 to 1.0.6. Apologies again!
