### ISSUE TITLE
Installing libtorrent Python in CentOS 7.x - Python 3.5.2

### ISSUE THREAD

**Issue by fastesol** [arvidn/libtorrent#2211]
Can you please provide the documentation for installing the libtorrent in CentOS7.x and setup using Python 3.5.2 
NOTE: CentOS has Python 2.7 builtin and I installed Python 3.5.2 separately. 

Thank you!

**EDIT 1:**
Well, I followed the instructions [here](https://github.com/arvidn/libtorrent/blob/master/docs/python_binding.rst#building-using-setup-py) and run those two commands 

```
python3 setup.py build
python3 setup.py install 
```

But, when I import libtorrent, it says no module found.
I'm using libtorrent (Latest From Github)

Searching for libtorrent gives

```
$ find . -name *libtorrent*
./usr/local/lib/python3.5/site-packages/python_libtorrent-1.2.0-py3.5.egg-info
```

**Edit 2:**

I'm able to install libtorrent using [these shell commands](https://gist.github.com/fastesol/17e2af8e6eae8a0fc10f39068fe0cc5c) But, it installed for Python 2.7 not 3.5.2

**Comment by arvidn** [comment]
when you say ``python setup.py build`` and ``python setup.py install``, does that ``python`` refer to 3.5? if not, you should probably say ``python3 setup.py build`` etc.

**Comment by arvidn** [comment]
I'm not particularly familiar with python distutils though, or how it picks the version of python to install for. I would just assume it derives it from the currently executing python environment

**Comment by fastesol** [comment]
well, I have python 2.7 installed by default. and when I run the command `./configure --disable-debug --with-boost-libdir=/usr/lib64 --disable-encryption --enable-python-binding` It take Python 2.7 and install the libtorrent for 2.7. Whereas, I want it to be installed for 3.5.2

**Comment by fastesol** [comment]
btw, I run the following command 
`bjam -j4 libtorrent-link=static boost-link=static python=3.5 stage_module`

and got the error

````
Unable to load Boost.Build: could not find "boost-build.jam"
---------------------------------------------------------------
Attempted search from /tmp/libtorrent/libtorrent-rasterbar-1.1.4 up to the root
at /usr/share/boost-build
and in these directories from BOOST_BUILD_PATH and BOOST_ROOT: /usr/share/boost-build.
Please consult the documentation at 'http://www.boost.org'.
````

**Comment by arvidn** [comment]
```
    import libtorrent as lt
ImportError: /usr/local/lib/python3.5/site-packages/libtorrent.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE
```

I think this may be because your copy of ``boost.python`` may be built for python 2. You could try the ``bjam`` approach above (where you specify the python version). To get that to work you need the boost sources though, and set the ``BOOST_ROOT`` environment variable to point to the boost directory.

**Comment by fastesol** [comment]
can you please suggest the steps to fix the above error?

Thank you!

**Comment by arvidn** [comment]
something like this:

```
wget https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.zip
unzip -qq boost_1_64_0.zip
export BOOST_ROOT=$PWD/boost_1_64_0
cd bindings/python
bjam -j4 libtorrent-link=static boost-link=static python=3.5 stage_module
```

**Comment by fastesol** [comment]
Thank you, 
btw, there is no directory bindings/python in boost_1.64.0

**Comment by fastesol** [comment]
I think problem is here  
when I use to run the following command

`./bootstrap.sh --prefix=/home/pool --libdir=/home/pool/lib --with-libraries=python`

It gets the targeted Python Version as 2.7
````
Building Boost.Build engine with toolset gcc... tools/build/src/engine/bin.linuxx86_64/b2
Detecting Python version... 2.7
Detecting Python root... /usr
Unicode/ICU support for Boost.Regex?... not found.
Backing up existing Boost.Build configuration in project-config.jam.3
Generating Boost.Build configuration in project-config.jam...

Bootstrapping is done. To build, run:

    ./b2
    
To adjust configuration, edit 'project-config.jam'.
Further information:

   - Command line help:
     ./b2 --help
     
   - Getting started guide: 
     http://www.boost.org/more/getting_started/unix-variants.html
     
   - Boost.Build documentation:
     http://www.boost.org/build/doc/html/index.html

````

**Comment by arvidn** [comment]
you can declare that you have python 3.5 by adding this line to your ``~/user-config.jam``:
```
using python 3.5 ;
```

(note that the spaces matter)

**Comment by fastesol** [comment]
I did everything. now I thin, I have to stuck with 2.7. :(

**Comment by almereyda** [comment]
As a note for people on the RHEL platforms, Fedora or CentOS, it might be that your particular version also has a package `rb_libtorrent-python3`, which is differently named than on Debian-based distributions like Ubuntu.

Is this maybe worth a follow-up issue that documents the different distribution's package names in an INSTALL file in the root of the repository, somewhere near https://github.com/arvidn/libtorrent/tree/RC_1_2/docs or visibly on http://libtorrent.org/ ?

**Comment by arvidn** [comment]
I'm open to pull requests. I was about to suggest the right place is `building.rst` (vcpkg documentation was recently added there), but it probably doesn't belong under building. maybe `README.rst`
