### ISSUE TITLE
Stuck in the loop while (not h.has_metadata()):

### ISSUE THREAD

**Issue by fastesol** [arvidn/libtorrent#2214]
Hi, I'm trying to get the torrent by passing infohash but the problem is that the code stuck in while loop. I tried with different info hashes and none of them work. below is the code.

can you please help to see if I'm doing anything wrong?

I'm using 
CentOS 7.x
Python 2.7
LibTorrent 1.1.4

```
import libtorrent as lt
import time
import sys

ses = lt.session()
ses.listen_on(6881, 6891)
params = {
	'save_path': '.',
	'storage_mode': lt.storage_mode_t(2),
	'paused': False,
	'auto_managed': True,
	'duplicate_is_error': True
	}

info_hash = "2B3AF3B4977EB5485D39F96FE414729530F48386"
link = "magnet:?xt=urn:btih:" + info_hash

h = lt.add_magnet_uri(ses, link, params)

ses.add_dht_router("router.utorrent.com", 6881)
ses.add_dht_router("router.bittorrent.com", 6881)
ses.add_dht_router("dht.transmissionbt.com", 6881)
ses.start_dht()

while (not h.has_metadata()):
	time.sleep(1)

torinfo = h.get_torrent_info()
```

**Comment by arvidn** [comment]
you're starting (or re-starting) the DHT *after* adding the torrent. When the torrent is first added, presumably the DHT has not bootstrapped and won't have any nodes. Looking up peers for it will likely fail. Even if you restart the DHT with router nodes, the torrent won't try to announce to the DHT until 15 minutes later.

Did you wait longer than 15 minutes?

I would suggest you try reordering restarting the DHT and adding the torrent.

Also, the ``start_dht()`` call is deprecated. There's setting (in ``settings_pack``) to enable DHT, and it's on by default. You can also add the router nodes to the ``settings_pack`` that you pass in to the session, to not have to restart the DHT, but have them available when it starts up with the session.

It's also possible that the DHT bootstrap has not made enough progress by the time you add the torrent, which may also make its first DHT announce fail. You could either wait a few seconds after starting or wait for the alert indicating bootstrapping completed.

**Comment by fastesol** [comment]
I was using an older version. 1.1.4 works well. Sorry for interruption.

**Comment by 11aihua** [comment]
Hi ,
I am a iOS developer, Now I had the same problem now . The libtorrent  version is  libtorrent-1.1.12
I called  async_add_torrent() after the is_dht_running() returns true. 
Setting the dht nodes like this:
NSArray * arr = @[@"udp://tracker.open-internet.nl:6969/announce",
 @"udp://tracker.leechers-paradise.org:6969/announce",
 @"dht.transmissionbt.com:6881",
 @"udp://tracker.opentrackr.org:1337/announce",
 @"http://tracker.internetwarriors.net:1337/announce"];
 NSString * nodes = [arr componentsJoinedByString:@","];
 settings.set_str(lt::settings_pack::dht_bootstrap_nodes, [nodes cStringUsingEncoding:NSUTF8StringEncoding]);

Look for your help!

**Comment by 11aihua** [comment]
Hi ,
I am a iOS developer, Now I had the same problem now . The libtorrent  version is libtorrent-1.1.12
I called  async_add_torrent() after the is_dht_running() returns true. 
Setting the dht nodes like this:
NSArray * arr = @[@"udp://tracker.open-internet.nl:6969/announce",
 @"udp://tracker.leechers-paradise.org:6969/announce",
 @"dht.transmissionbt.com:6881",
 @"udp://tracker.opentrackr.org:1337/announce",
 @"http://tracker.internetwarriors.net:1337/announce"];
 NSString * nodes = [arr componentsJoinedByString:@","];
 settings.set_str(lt::settings_pack::dht_bootstrap_nodes, [nodes cStringUsingEncoding:NSUTF8StringEncoding]);
Look for your help!
