### ISSUE TITLE
High performance transfers on 10 Gbit/s interfaces

### ISSUE THREAD

**Issue by kaazoo** [arvidn/libtorrent#2215]
libtorrent version (or branch): 1.0.9.0 used by Deluge 1.3.15
platform/architecture: CentOS 7 / kernel 3.10.x / x86_64
compiler and compiler version: unknown

I'm using EC2 VMs of instance type 'c3.8xlarge' (32 CPU cores, 60 GB RAM, 2x 320 GB SSD configured as RAID-0) on AWS in a private VPC. The VMs have 10 GBit/s network interfaces.

The VMs (dynamic number in AutoScaling Group) usually download more than 100 GB from S3 and store the data on SSD during boot. However, sometimes S3 is slow and I thought why not re-use the already downloaded data on the running instances when bringing up a new machine.

When sharing data directories as torrents, I'm using mitorrent (https://github.com/da2x/mitorrent) to create torrent files and add the IP addresses from all running VMs as DHT nodes. The torrent files are then copied to S3.
A newly added VM downloads the torrent files from S3 and starts to download from all other already running VMs in parallel. In theory this should give a lot of download bandwidth, as each instance transfers via 10 GBit/s.

So far, I tested with 2 running and 1 booting VM, and I only receive around 150-300 MByte/s. When downloads start, the transfer rates go up until around 200-300 MByte/s and then fall down to less than 150 MByte/s. In order to be a useful alternative for S3, I need to achieve transfer rates of around 500-600 MBytes/s.

Do you have any hints how to optimize for transfer speed on 10 GBit/s network?

I'm already using the ltConfig plugin for Deluge with the 'High performance seed' preset:
```
    "connection_speed": 500, 
    "active_seeds": 2000, 
    "max_failcount": 1, 
    "dht_upload_rate_limit": 20000, 
    "allowed_fast_set_size": 0, 
    "unchoke_slots_limit": 2000, 
    "max_rejects": 10, 
    "allow_multiple_connections_per_ip": true, 
    "read_job_every": 100, 
    "recv_socket_buffer_size": 1048576, 
    "utp_dynamic_sock_buf": true, 
    "active_limit": 2000, 
    "file_pool_size": 500, 
    "cache_expiry": 30, 
    "max_out_request_queue": 1500, 
    "send_buffer_watermark": 3145728, 
    "send_buffer_watermark_factor": 150, 
    "active_tracker_limit": 2000, 
    "request_timeout": 10, 
    "send_buffer_low_watermark": 1048576, 
    "mixed_mode_algorithm": 0, 
    "max_queued_disk_bytes": 7340032, 
    "cache_buffer_chunk_size": 128, 
    "connections_limit": 8000, 
    "write_cache_line_size": 256, 
    "suggest_mode": 1, 
    "listen_queue_size": 3000, 
    "max_allowed_in_request_queue": 2000, 
    "auto_upload_slots": false, 
    "active_dht_limit": 600, 
    "peer_timeout": 20, 
    "inactivity_timeout": 20, 
    "low_prio_disk": false, 
    "max_http_recv_buffer_size": 6291456, 
    "cache_size": 65536, 
    "send_socket_buffer_size": 1048576
```

**Comment by arvidn** [comment]
if you set the ``performance_warning`` alerts (in the alert_mask) on both the seeding and downloading peers, you may see some hints of which settings are causing a bottleneck.

You could also rebuild with stats logging enabled (or in a newer version of libtorrent, enable stats logging in the alert_mask and print the stats alerts to a file). There's a python script under tools/parse_session_stats.py to parse the log output and generate graphs (requires gnuplot). This can also give hints about what the bottleneck is.
