### ISSUE TITLE
Upload - Download Rates Possible Error

### ISSUE THREAD

**Issue by nocos** [arvidn/libtorrent#2216]
libtorrent version (or branch): 1.1.3
platform/architecture: Windows 
compiler and compiler version: MSVC 2013

When the settings_pack::upload_rate_limit is set to 0 (unlimited) the settings works fine
When the settings_pack::download_rate_limit is set to 0 (unlimited) the settings works fine
When the settings_pack::upload_rate_limit is set to 256 or 256 * 1000 or even 256 * 1000000000 
When the settings_pack::download_rate_limit is set to 256 or 256 * 1000 or even 256 * 1000000000 
The torrents that added with other than 0 dont start at all to download the download rate or upload rate
from the status report of each torrent is about 0.2Kb/s with every *100000XXXXX i added.
The same issue occurs also on the add_torrent_params param.upload_limit and param.download_limit
other than 0 regardless the *10XXXXX multiplier the upload and download rate is 0.XXXXXX

On the other hand if i use the torrent_handle and set the handle.upload_limit(256 * 1000); all are working fine and fixes the error.

Is it a general issue or do i have to set something in the settings:pack to work like the handle.upload_limit() when i use other than 0 limits in the upload and donwload ?

**Comment by Col-blimp** [comment]
I dont see any problems with 1.1.3.

`settings_pack::upload_rate_limit/settings_pack::download_rate_limit` <- these are global limits so if you add ten torrents then they will share the limit set here and even if you set the individual torrent speed to be higher it won't ever be higher.

Individual torrents use `set_upload_limit/set_download_limit` functions and they use -1 for unlimited as 0 is zero.

`settings_pack::upload_rate_limit/settings_pack::download_rate_limit uses 0 for unlimited.

**Comment by nocos** [comment]
Howcome and i have problems if i set something not 0 in the global limits ? 
If i use 0 all works fine but if i choose anything from 16 and above is not working at all.
It uses a small ratio of download and upload instead the limit for e.x. of 16Kb/s 
By small ratio i mean that i download in 0.1Kb/s and upload in 0.1Kb/s instead of 16Kb/s in both fields

**Comment by nocos** [comment]
But if i use the same number in set_upload_limit/set_download_limit from the handle of each torrent the limit is set correctly and downloads with around 16Kb/s

Here is an example :
SessionSettings.set_int(settings_pack::upload_rate_limit, 256 *1000);
Session.apply_settings(SessionSettings);
// It downloads around 0.256Kb/s as limit instead of 256Kb/s as limit
// If it was 0 instead of 256 * 1000 it downloads without errors or low Kb/s

If i set this : 
SelectedTorrentHandle.set_upload_limit(256 * 1000);
// It downloads correctly around a limit of 256Kb/s

**Comment by Col-blimp** [comment]
Your problem on the first post was that you said you could not get anything to download because you set the download limit of the torrent to 0, 0 is zero bytes ie: dont download anything.

>  If it was 0 instead of 256 * 1000 it downloads without errors or low Kb/s

What errors?

> // It downloads correctly around a limit of 256Kb/s

Why is it correct? nothing is to say you should be getting any download speed at all as there are to many factors to say you should be getting a specific speed, are you saying with 25600 bytes set it downloads more?

**Comment by nocos** [comment]
Sorry if my english are not so good but i said that when i use 0 (unlimited) all works fine ...
If i use anything other than 0 like 256 or 256 *1000 or 256 *10000 or higher multiplier 
the download or upload speed stays below 0.2Kb/s and it hardly downloads or uploads anything.

**Comment by Col-blimp** [comment]
Its in bytes and 256 and 256 *1000 are not a great deal, what is your results with this:

`magnet:?xt=urn:btih:59066769b9ad42da2e508611c33d7c4480b3857b&dn=ubuntu-17.04-desktop-amd64.iso&tr=http%3A%2F%2Ftorrent.ubuntu.com%3A6969%2Fannounce&tr=http%3A%2F%2Fipv6.torrent.ubuntu.com%3A6969%2Fannounce`

**Comment by nocos** [comment]
i cant open like this a magnet i need to have it from html link like all clients, please provide the page with the magnet uri to post back the result in the specific magnet uri

**Comment by Col-blimp** [comment]
http://releases.ubuntu.com/17.04/ubuntu-17.04-desktop-amd64.iso.torrent?_ga=2.229319580.1607422909.1502128728-2048120638.1502128728

That's a well seeded legit torrent that you will get a few thousand peers and can max out a 50mb connection.

**Comment by nocos** [comment]
I have tried 3 well seeded torrent like yours none of them alone or all together work as it should if i dont use in global settings of rate limits 0 ... 

There must be an error in the global settings of upload and donwload rates.
It downloads at 0.2Kb/s and uploads the same when i set the global settings to have 256 limit.
If i change the global settings to 0 it will download at any speed without error
or if i change the torrent from the handle set upload or download limit to 256 it will be setted correctly at the limit of 256 ...

**Comment by Col-blimp** [comment]
There is no error, the stats report back in bytes are you sure your converting the bytes to speed properly?

**Comment by nocos** [comment]
libtorrent::settings_pack SessionSettings;
libtorrent::session Session(SessionSettings);
SessionSettings.set_int(settings_pack::upload_rate_limit, 256 *1000);
SessionSettings.set_int(settings_pack::download_rate_limit, 256 *1000);
Session.apply_settings(SessionSettings);
/// after that add a torrent with or without setting the upload and download limit with 
Session.async_add_torrent(TorParam);

The download and upload rate limit will be around 0.256Kb/s instead of 256Kb/s
and if you set on runtime from the handle of torrent 
TorHandle.upload_limit(256 * 1000);
TorHandle.download_limit(256 * 1000);
will upload and download correclty with limits of 256Kb/s and not 0.256Kb/s

//////////////
If you start your settings in the above with 0 instead of 256 * 1000 all will work fine

**Comment by arvidn** [comment]
nocos, can you modify one of the ``test_transfer.cpp`` tests to reproduce this issue? i.e. set a rate limit and assert that the completion time is about what one would expect with that rate limit.

**Comment by nocos** [comment]
@arvidn i would like to support fixing some issues that may needed in libtorrent but unfortunately i am a noob in c++ compiling things and too complicated issues.
I am just a regular c++ programmer with not so much experience.

I think is not the time of completion the error but i think settings in settings_pack and add_torrent_param
in upload and download rates treat the values that they get (if they are other than 0 = unlimited) somehow 
else than the upload and download rate from the function inside the torrent handle 
The torrent handle gets the values correct and the other two getting the value in a way of 0.XXXXX KB/s

i tried to multiply them even to PB and higher *1000000000000000 but both get the same result 0.XXXX KB/s as a torrent status (the 0 ofcourse 0*1000 = always 0 thats why they both get correct value only in unlimited settings)

I will try to give a feedback on the issue so you or any dev can understand whats wrong in this or even a small script cause i dont know much about compiling, debuging and things like that in c++

**Comment by nocos** [comment]
I dont get it, the test client in the tests folder of rasterbar with -u 256 and id 256 works fine at the same torrent using the same way to add the upload and download rate e.x. 256 * 1000 in the settings and the same in the add_torrent_param of torrent.

In my client it doenst get the values correct though i just set the rate as above only correct is from the handle.

What can cause such wrong set of values ? Does anyone knows ?

**Comment by nocos** [comment]
I ve checked my code in every download rate i set and before.
Here is a test in values
I set the settings_pack download limit to 256 * 1000 and i check what values it has in settings pack for this
it says correclty 256000 bytes = 256Kb/s set
I set the add_param of added torrent to download limit 256 * 1000 and i check the values and
it says correctly 256000 bytes = 256Kb/s set 
I then check the handle of this torrent and i get thes variable handle.download_limit() and i get a wrong value of only 256/s bytes instead of 256000 bytes/s = 256Kb/s

Thats why when i changed anything from the global settings inside the handles of each torrent it stayed as 256 bytes isntead of 256000 bytes and when i change at the individual torrent the download rate to 256 * 1000 it returned me then the correct value to 256000 bytes = 256Kb/s which is correct.

Now how do i set the handle of the torrent when i add them to the correct values ?
In the add param the values are correct, in the settings are correct, and i need to specifically change the handle values of each torrent to what the globals are cause it stays in bytes

**Comment by nocos** [comment]
It is working fine now but i really dont know why and how.
It had error getting the variables correct somehow inside the handle as far as i checked when the torrent was added (it was taking only in bytes and not with *1000 for kilobytes) and now it stored it correctly.

The key as i see to store the variables correct is to set the 256 * 1000 in a variable and then use that variable into the settings functions and not directly to the functions like this SessionSettings.set_int(settings_pack::upload_rate_limit, 256 *1000); 
but like this
int upRate = 256 * 1000;
SessionSettings.set_int(settings_pack::upload_rate_limit, upRate); 

otherwise when the torrent is added regardless the rates in the add_parameters of torrent the handle gets the value in bytes instead of kilobytes.

I dont know why but this is what i changed and it worked.

Thanks for your time.
And if you like to remove this post tell me to do so.

**Comment by nocos** [comment]
I got the error of bytes after the add where it was coming from.
In the handle allert function it was using the same variable of upRate without the*1000 and it was reseting the values to handle the error and it was adding the value in bytes h.set_upload_limit(upRate) which was 256 bytes thats why it was having wrong values.

Thanks for your time
