### ISSUE TITLE
[Feature Request] Crypto Tracker Extension

### ISSUE THREAD

**Issue by zero77** [arvidn/libtorrent#2217]
Can you please add support for Crypto Tracker extension used by Vuze/Azureus, this was also requested on the uTorrent forum as well and raised some interesting points.

Thanks

uTorrent request:
https://forum.utorrent.com/topic/11398-crypto-tracker-extension

More INFO on Tracker Extension:
https://wiki.vuze.com/mediawiki/index.php?title=Message_Stream_Encryption&action=edit&section=4

**Comment by arvidn** [comment]
I think you mean this link, right? https://wiki.vuze.com/w/Message_Stream_Encryption

Can you be a bit more specific as to what feature you would like libtorrent to support? libtorrent already sends ``supportscrypto`` on HTTP tracker announces. Any client sending ``requirecrypto`` to a tracker enforcing this should still be able to receive libtorrent peers, no?
