### ISSUE TITLE
Encryption Question

### ISSUE THREAD

**Issue by zero77** [arvidn/libtorrent#2218]
What type of encryption are used for instance, Protocol encryption (PE), message stream encryption (MSE) or protocol header encrypt (PHE) or something else?

Also, are these all enabled by default or only some.

Thanks

**Comment by arvidn** [comment]
I'm not sure what you're actually asking. the cipher is RC4 and the handshake is Diffie-Hellman using the info-hash as shared secret. It's documented [here](https://wiki.vuze.com/w/Message_Stream_Encryption). In libtorrent encryption is supported by default, but outgoing connections are not requesting encryption by default (iirc).

**Comment by zero77** [comment]
Hi
I am referring to https://en.wikipedia.org/wiki/BitTorrent_protocol_encryption although I am not sure how accurate it is.

I am trying to gain a better understanding of how BitTorrent traffic encryption works, because when torrenting I notice that only 1 or 2 percent of all pears use encryption and, if there is anything that can be done about this.

**Comment by Col-blimp** [comment]
You can have it on or off and on but allowing non encrypted traffic as well.
