### ISSUE TITLE
magnet link extension

### ISSUE THREAD

**Issue by zugolosian** [arvidn/libtorrent#222]

**Comment by zugolosian** [comment]
It would be really useful for us if the make and parse magnet_uri functions could include size so we can determine of the the torrent should continue up front before the metadata is downloaded.

**Comment by arvidn** [comment]
it would be simple to support a custom field in magnet links, but the utility seems questionable given that you can't trust it

**Comment by zugolosian** [comment]
Our use case is when we'll be providing the magnet link and we want to determine if the filesystem has sufficient space before adding the torrent. Although the `&xl` value isn't enforced in any way it is "nice to have" and shouldn't affect the overall implementation. 

Your call.

**Comment by arvidn** [comment]
I can't think of anything libtorrent itself would use that information for (libtorrent doesn't check for space on the disk). It seems more appropriate for you to parse it out on the client side. libtorrent will ignore any unknown parameters.
