### ISSUE TITLE
Is this decentralized with DHT ? 

### ISSUE THREAD

**Issue by AlexiaChen** [arvidn/libtorrent#2222]
I looked through the wiki of P2P network.    It can be decentralized with DHT.    but this libtorrent (the implementation of bitTorrent) looks need tracker server to store file index(file meta-information ).    Why is it need to tracker server when it includes DHT extension ?

in short, I need to set-up tracker server before I start programming with this library ?

**Comment by AlexiaChen** [comment]
I need this library to build a simple distributed file storage in Enterprise Intranet :)   is this library can meet my needs?

**Comment by arvidn** [comment]
trackers are not mandatory in bittorrent. If you read something on libtorrent.org giving you that impression, please let me know and I'll fix it.

So, you don't need to set up a tracker. Even if your production system use a tracker, for development you can add peers "manually"/hard coded for testing and development.

In an enterprise environment though, I would expect you to use a tracker. Perhaps even an HTTPS tracker and SSL swarms (but perhaps that's overkill). For a small UDP-only tracker that scales pretty well, you could check out [utrack](https://github.com/arvidn/utrack).

If you want to rely on the DHT in an enterprise setting, you may want to run your own DHT [bootstrap server](https://github.com/bittorrent/bootstrap-dht) though.
