### ISSUE TITLE
Settings Question - Cant find in documentation

### ISSUE THREAD

**Issue by nocos** [arvidn/libtorrent#2224]
I have two questions about settings options that i cant find anywhere in documentation.

1. if i set the high_performance_seed() on runtime i need to reassign all the settings ?
and if i want to close high performance and use the normal i set back to min_memory_usage() and i need to reassign all the settings again ?

2. how do i reset to null the seed_time_limit and the share_ratio_limit so i can reset the torrent the way i want to act after it reaches the specific seeding limit goal
for e.x. i use sets.set_int(settings_pack::seed_time_limit, 120); <- and when it reaches this how do i
set it back to normal sets.set_int(settings_pack::seed_time_limit, -1); <- like this ?
do i use the same way for share_ratio_limit ?

Can anyone give an answer to clear my doubts on these settings cause i cant find anywhere in documentation ?

Thanks in advance

**Comment by arvidn** [comment]
I think I answered these questions on the mailing list a few days ago. https://sourceforge.net/p/libtorrent/mailman/libtorrent-discuss/?viewmonth=201708&viewday=3&style=flat

**Comment by nocos** [comment]
thanks for the linik Arvidn cause i didnt recieve the email.
Sorry to bother again with useless questions. 
I will delete the post

**Comment by nocos** [comment]
About the 2. question, about the share and time limitations of torrents
Let say i use for all upload torrents a time limit of 5 minutes.
And when it reaches 5 minutes as from the documentation is says that these torrents will stop after reaching this limit.
If i want instead of stopping them to change the value of upload rate to 16Kb/s 
i need first to stop i assume the time limit so the torrents are enabled again for upload and then set them the new upload rate limit i want instead of just stopping them.

**Comment by arvidn** [comment]
you don't change the seed_time or share_ratio *limits*. Those are shared across all torrents, changing those based on the state of a specific torrent would not make sense.

If you want to adjust the upload rate limit based on seed time or upload ratio, just implement that yourself. Periodically poll ``torrent_status`` and compute the two ratios and adjust the rate limit on the ratio edge.

**Comment by nocos** [comment]
Thanks for your response and time arvid, 
i understood how to make the individual way of limitations if i like to but for the global settings just to make it clear for me if i understand it well and i will remove this post.

The share_ratio_limits and seed_time_limits affects all the torrents so if i set a time limit about 5 minutes 
every torrent that seeds will stop when it reaches the its 5 limitation of seeding and be as queued torrent in the list, the same applies to share_ratio_limit global settings which applies according to each torrent when it reaches this share_ratio_limit (upload/download) of it and according to the global share_ratio_limit it will stop and be queued in the list when reaches that

I am asking this to clear my thoughs cause i am makind the functions of settings to these options and sorry for posting here. 
I will remove the post at the end.
thanks in advance for your time and corrections

**Comment by nocos** [comment]
Arvidn you may delete this post if you like
