### ISSUE TITLE
Seeds lose trackers

### ISSUE THREAD

**Issue by bittaurus** [arvidn/libtorrent#2240]
**Please provide the following information**

libtorrent version (or branch):
rasterbar
deluged: 1.3.15
libtorrent: 1.1.3.0

platform/architecture:
Linux palm host 4.9.20-hardened-whatbox-r1 #2 SMP Sun Apr 9 10:02:56 2017 x86_64 Intel(R) Pentium(R) CPU G850 @ 2.90GHz GenuineIntel GNU/Linux
Gentoo Base System release 2.3

compiler and compiler version:
gcc version 5.4.0 (Gentoo Hardened 5.4.0-r3 p1.3, pie-0.6.5)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I'm running deluged seeding torrents on a single tracker. It intermittently loses the tracker data on the a seed here or there and it has to be added again.  Should I be talking about this with you or deluge devteam?

**Comment by arvidn** [comment]
what does it mean to "loose the tracker data"?

**Comment by bittaurus** [comment]
It means the seed goes from having 1 tracker to no trackers and stops announcing to the tracker.

**Comment by arvidn** [comment]
take a look at the alerts. specifically ``tracker_error_alert``. If there's no error indicating why the tracker was removed, look for ``torrent_log_alert``. A brief look over the code, I don't see any way for libtorrent to remove a tracker, my guess is that deluge calls ``set_trackers()`` which removes it, or it's removed by loading resume data.

**Comment by bittaurus** [comment]
Thanks. Restarting with debug logging and waiting for it to happen again. Will let you know.

**Comment by Seeker2** [comment]
I've seen on multi-tracker torrents with qBitTorrent that if the tracker qBT was using fails, qBT may be very slow to try another. (qBT v3.3.14 with libtorrent v1.0.11)

**Comment by bittaurus** [comment]
I figured out what I was doing to cause it. I opened a ticket with dev-deluge with replication instruction here: http://dev.deluge-torrent.org/ticket/3102#ticket

**Comment by arvidn** [comment]
this may be related to the resume data being re-issued and one of the ``override_resume`` flags may be set by qBT. I'll take a look to see if I can find a problem in libtorrent.

**Comment by arvidn** [comment]
> click "Force Re-check" then "Pause" then "Force Re-check" again, it starts checking immediately as expected, but it loses the tracker data and I have to re-add the tracker.

**Comment by arvidn** [comment]
as far as I can tell, the trackers from resume data only override the trackers from the torrent on initialization (``torrent::init()``). I haven't found a way for ``m_trackers`` to be clobbered by force-rechecking multiple times.
