### ISSUE TITLE
Infinite loop in resolve_duplicate_filenames_slow in torrent_info.cpp

### ISSUE THREAD

**Issue by nervoir** [arvidn/libtorrent#2247]
There is an infinite loop in the resolve_duplicate_filenames_slow. The issue is actually very subtle and is due to the fact that you've implemented your own case insensitive string compare.

Imagine two files with name "\0" and "\0". That is c_str of the strings would be "\0\0" and length would be 1 since \0 is a perfectly valid element in a std::string and bdecode seems to support strings with embedded \0 (eg. `0x31 0x3a 0x00`).

Looking at resolve_duplicate_filenames_slow we see

`if (!files.insert(filename).second)`

Is taken. 

`std::snprintf(new_ext, sizeof(new_ext), ".%d%s", cnt, ext.c_str());`

`filename = base + new_ext;`

so `filename` becomes "\x00\x31", "\x00\x32", "\x00\x33" and so on. Now this would be fine if we consistently used iterators or std::strings. however files is defined as `std::unordered_set<std::string, string_hash_no_case, string_eq_no_case> files;`. Of interest is the string_eq_no_case functor.

`char const* s1 = lhs.c_str();`
`char const* s2 = rhs.c_str();`

`while (*s1 != 0 && *s2 != 0)`

This will not play well with std::strings with embedded \0 since no matter what integer we append we'll wind up with a string that already exists.

The string_hash_no_case function also looks vulnerable to a string hash collision DOS by making sure we provide values that always result in a linear seek of the hash buckets due to each string colliding. But I haven't tested that.

**Comment by arvidn** [comment]
thanks!

**Comment by arvidn** [comment]
I think there are two somewhat separate issues here. One is that the comparison functions don't support zeroes in the strings, despite being used with ``std::string``.

The other one is that filenames don't seem to filter zeroes as invalid filename/path characters.

**Comment by nervoir** [comment]
Yeah it's very hard for me to tell what the implications are when it comes to the wider software. There's a lot of places where std::strings become char const *. Which leads to the situation where two pieces of code that are meant to treat the data the same will actually treat them differently. Best would probably be to use iterators instead but that seems like a MASSIVE amount of work.

**Comment by arvidn** [comment]
in master I'm transitioning away from ``char const*`` in favor of ``string_view``, which I expect will make things more robust too

**Comment by arvidn** [comment]
that addresses the more fundamental issue. next I will fix the filename filter on unix.

**Comment by arvidn** [comment]
actually, as far as I can tell, any zeroes in filenames are already stripped as part of the utf-8 validation (``sanitize_append_path_element()``). I don't see how zeroes could get through that.
I'll add some tests though

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/2250

**Comment by nervoir** [comment]
Here's the fuzz case that made me take a quick look. I'm not 100% sure the issue I cited is the one that's triggered mostly due to unfamiliarity with the code base. It's a messy fuzz output though and hasn't been minimized.

[hang.zip](https://github.com/arvidn/libtorrent/files/1224905/hang.zip)

**Comment by arvidn** [comment]
thanks! There was an issue in the UTF code failing to detect this invalid utf-8 sequence

**Comment by arvidn** [comment]
I'm pretty confident both of these issues have been addressed in both RC_1_1 and master now. thanks again for the report!
