### ISSUE TITLE
why in torrent_handl.hpp using unsigned bytes_progress:15 to limit its size?

### ISSUE THREAD

**Issue by wynelu** [arvidn/libtorrent#226]
Hi, when reading libtorrent code, I found the following :

in  torrent_handl.hpp  line 139:

		// the number of bytes that have been received for this block
		unsigned bytes_progress:15;

		// the total number of bytes in this block.
		unsigned block_size:15;

		// the state this block is in (see block_state_t)
		unsigned state:2;

my question is  why limit this type size ?
thank you...

**Comment by arvidn** [comment]
to save space. you may notice that the bitfield fits exactly in a 32 bit word.

**Comment by wynelu** [comment]
thanks very much !
