### ISSUE TITLE
Potplayer can freezes Windows and spot playing when you download in seqiential order

### ISSUE THREAD

**Issue by DanillaTech** [arvidn/libtorrent#2263]
**Please provide the following information**

libtorrent version (or branch): Qbittorrent , Windows

platform/architecture: x64

compiler and compiler version: 1.0.11.0

It's Potplayer's forum quite, man from qbittorrent forum told to write here

I've asked on potplayer forum, this is answer to add some code...

Q.

    The qbittorrent client has a sequential download option. Use that option, play the video with Potplayer while receiving the torrent. At this time, as soon as the video is seeked, Potplayer is said to be almost down. Actually, I could reproduce it. I took a 12GB video and tested it. When the file being downloaded was 2 GB in size, I played that file in Potplayer.

    I was downloading about 5 minutes of a whole video length (the physical size of a downloading file is about 2GB). At that time, when I seeked the video, Potplayer went down and the system became unresponsive. After some time, I was able to check the file after the deadlock was released, and the file that was 2 GB became 12 GB. Again, I dropped this 12 GB file into Potplayer and I did seeking it to know if there is a same deadlock. I was downloading about 10 minutes, and 10 minutes are from the timeline of Potplayer. As expected, there was no problme to play and seek the video with Potplayer.

    So, while the torrent client initially writes a dummy file to a hard disk until it is reached to the original file size (in this case 12 GB), it will not be able to seek in Potplayer after playing the torrent on downloading (at 2GB as above). I would like to hear from the developer if it is normal.

This seems to be a problem of qbittorrent torrent client (exactly the problem of Windows).
Perhaps if you download files sequentially in qbittorrent, qbittorrent seems to set the file size in advance.
This is similar to a bug in Windows (?).

When the file size is actually set, the size of the file that is visible in the file system will grow. When you try to use it, Windows fills the area. In other words, if you set the file size to 12G and Potplayer accesses the area that qbittorrent does not use, it will cause Windows to initialize to that area resulting in the freezing problem. For this problem, there is a feature that prevents this if the file system is NTFS.

That is, after a file is created in qbittorrent, the problem can be avoided by calling the function to prevent Windows from doing so. In other words, this is not something that should be handled in Potplayer but qbittorrent.

Code: Select all
```
    DWORD dwTemp;
    DeviceIoControl(m_hFile, FSCTL_SET_SPARSE, NULL, 0, NULL, 0, &dwTemp, NULL);
```

This is probably a working code for the problem.

Or it might be better to process it in a way that does not pre-set the size of the file initially, but grows the size of the file gradually. As the size of the file grows larger, Potplayer will be better able to find out and process if the file is being downloaded and to what extent it has been downloaded.

**Comment by arvidn** [comment]
is your assertion that qbittorrent causes too much disk activity, such that this media player cannot read its video from disk fast enough and falls behind or stutter?

Did you try to configure libtorrent to not allocate files up-front? (I believe files are not preallocated by default, on windows that means setting the files to be sparse).

I'm not sure I understand what you're saying with that snippet of code.

**Comment by DanillaTech** [comment]
> is your assertion that qbittorrent causes too much disk activity, such that this media player cannot read its video from disk fast enough and falls behind or stutter?
Potplayer just freezes sometimes. Usually, I can play video normally, but if I use rewind (especially, back) it can freeze.

Another case if bitrate too high like BDRemux ~5mB/sec and download speed ~5MB/sec, download speed can drop to 2mb/sec. May be I can fix it by cache setting on player/torrent client side?

**Comment by DanillaTech** [comment]
>Did you try to configure libtorrent to not allocate files up-front? (I believe files are not preallocated by default, on windows that means setting the files to be sparse).
By default files preallocation is disabled. I tried to enable it, on BDRip (not high bitrate) it's not laggy
