### ISSUE TITLE
Debian 9 linker error

### ISSUE THREAD

**Issue by Denisov39** [arvidn/libtorrent#2277]
Hi !
I try use libtorrent -rasterbar on Debian 9.
I try compile test dump_torrent.cpp and get an error
c++ --std=c++11 dump_torrent.cpp -ltorrent-rasterbar
/usr/bin/ld: /tmp/cc8GEkyw.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.62.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

Regards, Paul.

**Comment by arvidn** [comment]
as the error message says, you need to add the command line option to link against ``libboost_system.so``, to your linker command line.
