### ISSUE TITLE
Question about peers with port 1

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#2284]
libtorrent version (or branch): `master`
platform/architecture: `all`

Hi, in the process of fetching the magnet, I'm getting a lot of these logs:
```
[[IPV6]:1] >>> OUTGOING_CONNECTION [ ep: [2602:30a:2e11:e60:1490:eadc:4fef:7db0]:1 type: uTP
[[IPV6]:1] *** CONSTRUCT [ bt_peer_connection ]
[[IPV6]:1] *** SET_PEER_CLASS [ a: 2602:30a:2e11:e60:1490:eadc:4fef:7db0 ]
[[IPV6]:1] *** CLASS [ global ]
[[IPV6]:1] >>> OPEN [ protocol: IPv6 ]
[[IPV6]:1] >>> BIND [ dst: [::]:49322 ec: Undefined error: 0 ]
[[IPV6]:1] >>> ASYNC_CONNECT [ dst: [2602:30a:2e11:e60:1490:eadc:4fef:7db0]:1 ]
[[IPV6]:1] *** LOCAL ENDPOINT [ e: [::]:49322 ]
[[IPV6]:1] <<< CANNOT_READ [ quota: 112  can-write-to-disk: yes queue-limit: 1048576 disconnecting: no  connecting: yes ]
```
What could be the reason I'm getting (and storing) peers with port `1`?

**Comment by ssiloti** [comment]
I'm able to repro this. The instances I've seen are all IPv6 DHT nodes returning peers with port 1. The responses all look similar. Two or three peers are listed with all or most of them having a port of 1. Some of the offending peers have similar address prefixes and all of them have low interface identifiers, probably issued via DHCPv6. The clients do not identify themselves with a version string.

This looks like buggy and/or malicious nodes.

**Comment by ssiloti** [comment]
Got one from an IPv4 node. This one's a little different. It includes 32 peers with the vast majority having a port of 1. It also does not include a version string. I smell a buggy client.

**Comment by aldenml** [comment]
Can/should we do something about it?

**Comment by the8472** [comment]
you could try probing the corresponding BT port for the peerid if they respond to partial handshakes

**Comment by aldenml** [comment]
@the8472 I was thinking more about banning them, if that's a good idea, but I'm not sure about it. Are you talking about detecting the actual client to notify them?

**Comment by the8472** [comment]
Yes.

I think banning doesn't make sense unless you actually observed them causing problems. There is a lot of noise on the DHTs, this is just another source.

**Comment by aldenml** [comment]
@the8472 I changed the title of this issue, because I realize I can't be 100% sure these nodes are coming in the bootstrap phase. But not once I'm able to connect to these peers, or get any response from them, BT or DHT protocol. The `peer_id` is always all `0` in my logs. Do you still consider there shouldn't be a general ban in the library?

**Comment by the8472** [comment]
Blacklisting valid behavior (announcing port 1) is an absolute last-resort measure in my eyes. Legitimate clients *could* listen on port 1. It would be quite unusual, but there's not much that distinguishes port 1 from the other 65534 ports other than it being in the privileged portrange, but some people run their BT clients on privileged ports too.

So is there a strong reason why that port should be blacklisted in your opinion? Do you observe performance degradations? Is this part of an attack? Are there alternative approaches to detecting buggy behavior without relying on magic port numbers?

> Got one from an IPv4 node. This one's a little different. It includes 32 peers with the vast majority having a port of 1. It also does not include a version string. I smell a buggy client.

If a lot of junk comes from a single source a simple solution is to rotate through sources when trying to create connections. E.g. when you got replies from 10 DHT nodes and 1 node sent 15 junk responses then you should only try 1 junk response and 9 good ones before you try the next junk one etc. This will dilute the impact of buggy behavior without special-casing specific ports.

That is if there is an observable impact at all that needs to be addressed.

**Comment by aldenml** [comment]
Thanks, and I follow your reasoning, I will keep thinking on it

**Comment by aldenml** [comment]
I think I will just block them in my setup via `port_filter`

**Comment by aldenml** [comment]
Actually, I just discovered `no_connect_privileged_ports` :)

**Comment by Seeker2** [comment]
As far as I know, no_connect_privileged_ports prevents outgoing connections to such peers but doesn't prevent peers using port 1 from connecting to your BT client as incoming connections...although if they're using uTP they might still be using port 1 to do it, which might be blocked depending on the libtorrent logic.

**Comment by aldenml** [comment]
true, now that you mention it, I was in fact concerned about outbound connections to those peers, I'm still getting them in the DHTs reply packets. Btw, I didn't use that setting, because that prevents port `80` and `443` for web seeds. I crafted a specific `port_filter`.

**Comment by HanabishiRecca** [comment]
I guess the reason is https://github.com/arvidn/libtorrent/pull/4712
