### ISSUE TITLE
udp tracker issue

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#2286]
libtorrent branch: master

Recently, I see a lot udp tracker error alerts. The cause is the address family mismatch after the host name has been resolved to ipv4 but the listen socket is ipv6. 
I think that this should not be an error nowadays. (you cannot expect everything to support ipv6)
Furthermore, it resolved to ipv4 - it is working.
I am not familiar with libtorrent's name resolving - would it be possible to enforce the address family for the host name lookup to avoid such errors?

**Comment by arvidn** [comment]
you mean the IPv4 tracker should be announced to through a v4 mapped address?
If all you have is a v6 address, it's not obvious to me how the v4 tracker could support you.

**Comment by MassaRoddel** [comment]
I have ipv4 and ipv6 enabled and libtorrent listen on both address family's sockets. What I mean is that libtorrent should not generate an error alert if an tracker url resolves only to a v4 address and therefore cannot announce via the v6 socket while it is working via v4 socket. (or at least have a much more clear error message)

**Comment by arvidn** [comment]
What's the exact error message?

**Comment by ssiloti** [comment]
Is there any particular problem the alerts are causing? It's not trivial to determine when an address family mismatch may-or-may-not be important. IMO failing silently is worse than getting ignorable errors.

Look at the code again, one thing I think we should do is include the failing endpoint in `tracker_error_alert`. This would make is easier for clients to display the information a way which makes it clear that the tracker is in fact working, just not for all listen interfaces.

**Comment by arvidn** [comment]
is [this](https://github.com/arvidn/libtorrent/blob/master/src/udp_tracker_connection.cpp#L282) the message we're talking about?

**Comment by MassaRoddel** [comment]
We are talking about the standard windows socket error 10047: Address family not supported by protocol family
(of course in the locale language)
Source: [here](https://github.com/arvidn/libtorrent/blob/master/src/udp_tracker_connection.cpp#L225)
The error message could include something like:  Tracker does  not support ipv6/ipv4

**Comment by arvidn** [comment]
yeah, maybe that alert should be demoted to a ``tracker_warning_alert`` or a maybe just a log.

**Comment by ssiloti** [comment]
Coming back to this now I realize I already addressed this with #2297 but forgot to mention this issue in that PR. When you see `tracker_error_alert` it only applies to the given listen interface, not the tracker as a whole.

**Comment by MassaRoddel** [comment]
At the beginning I was confused by these error message because they suggest that the tracker urls resolve to my listen interfaces.
