### ISSUE TITLE
Question about link local IPv6 addresses and port mapping

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#2287]
libtorrent version (or branch): `master`

Hi @ssiloti, does it makes sense to filter out link local IPv6 addresses from the port mapping logic?

**Comment by gubatron** [comment]
Q @aldenml how would you route local bittorrent traffic then? IPv4?

**Comment by ssiloti** [comment]
Yes. There's no point in mapping local addresses.

**Comment by aldenml** [comment]
take a look at https://github.com/arvidn/libtorrent/pull/2296, thanks
