### ISSUE TITLE
64bit compile and warnings

### ISSUE THREAD

**Issue by szachara** [arvidn/libtorrent#2288]
I want to ask, if this compile warnings are ok.

I tried to compile `libtorrent-1_0_11` with `boost_1_64_0`, this was my `b2` command:
```
b2 -q --without-python --toolset=msvc-14.0 architecture=x86 address-model=64 variant=debug link=shared runtime-link=shared debug-symbols=on encryption=openssl logging=none geoip=off resolve-countries=off dht=on boost=source character-set=unicode boost-link=shared -sBOOST_ROOT="e:\c\qbittorrent_64\boost_1_64_0" include="e:\c\qbittorrent_64\install_msvc\base\include" library-path="e:\c\qbittorrent_64\install_msvc\base\lib" --prefix="e:\c\qbittorrent_64\install_msvc\base" define=BOOST_ASIO_DISABLE_CONNECTEX -j4
```

I get many compile warnings, almost all are `warning C4267: xx possible loss of data`.

But some are `note: see reference to function template instantiation xx` and I don't get this notes when I compile a 32bit version.

Anyone more skilled will certainly know, only by look at. :)

[libtorrent_output.txt](https://github.com/arvidn/libtorrent/files/1264012/libtorrent_output.txt)

Thank you for check

**Comment by aldenml** [comment]
They are "OK", in the sense that they are meaningful warnings, some of then can be ignored, but during the fix of all those warnings in `master`, a few bugs were uncovered.

btw, `1.0.X` is very very old, you should use minimum `1.1.X`

**Comment by szachara** [comment]
Ok, thx for reply, I'll try

**Comment by szachara** [comment]
I tried recompile qbittorrent with `libtorrent-1_1_4` and get strange output, don't understand where can be a problem.

I changed compile command from ( `libtorrent-1_0_11` ):
```
.\b2 -q --without-python --toolset=msvc-14.0 architecture=x86 address-model=64 variant=debug link=shared runtime-link=shared debug-symbols=on encryption=openssl logging=none geoip=off resolve-countries=off dht=on boost=source character-set=unicode boost-link=shared -sBOOST_ROOT="e:\c\qbittorrent_64\boost_1_64_0" include="e:\c\qbittorrent_64\install_msvc\base\include" library-path="e:\c\qbittorrent_64\install_msvc\base\lib" --prefix="e:\c\qbittorrent_64\install_msvc\base" define=BOOST_ASIO_DISABLE_CONNECTEX
```
to ( `libtorrent-1_1_4` ):
```
.\b2 -q --without-python --toolset=msvc-14.0 architecture=x86 address-model=64 variant=debug link=shared runtime-link=shared debug-symbols=on encryption=on crypto=openssl logging=off resolve-countries=off dht=on character-set=unicode boost-link=shared -sBOOST_ROOT="e:\c\qbittorrent_64\boost_1_64_0" include="e:\c\qbittorrent_64\install_msvc\base\include" library-path="e:\c\qbittorrent_64\install_msvc\base\lib" --prefix="e:\c\qbittorrent_64\install_msvc\base" define=BOOST_ASIO_DISABLE_CONNECTEX
```

Param `boost=source` was removed, may be this has some consequences.? don't know

When I checkout back to `1_0_11` and rebuild, so everything is ok.

[libtorrent-1_1-output.txt](https://github.com/arvidn/libtorrent/files/1268541/libtorrent-1_1-output.txt)
