### ISSUE TITLE
'Too many pieces in torrent' error

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#229]
A Deluge user in the [forum](http://forum.deluge-torrent.org/viewtopic.php?f=7&t=53099) has encountered the 'Too many pieces in torrent' issue with 1.0.6 which I believe was meant to be fixed in 0.16. However my testing with 0.16.19 shows the same issue. The torrent in the user's screenshot has 538219 (2 MiB) pieces.

**Comment by arvidn** [comment]
It looks like libtorrent was built with TORRENT_COMPACT_PICKER, which limits the number of pieces to 524'287, otherwise the limit is 33'554'432 pieces.

**Comment by cas--** [comment]
I simply build libtorrent with default defines (i.e. unspecified) which in this case should not enable it?

**Comment by arvidn** [comment]
I believe in RC_1_0 compact picker is still the default

**Comment by cas--** [comment]
This is what I am seeing in RC_1_0 code:

```
// if set to true, piece picker will use less RAM
// but only support up to ~260000 pieces in a torrent
#ifndef TORRENT_COMPACT_PICKER
#define TORRENT_COMPACT_PICKER 0
#endif
```
https://github.com/arvidn/libtorrent/blob/RC_1_0/include/libtorrent/config.hpp#L474

**Comment by arvidn** [comment]
yeah, that's weird. I can't explain why it would have been enabled, other than explicitly enabling it when building.

**Comment by cas--** [comment]
It doesn't show up in the defs output from configure: 

    Defs: -DPACKAGE_NAME=\"libtorrent-rasterbar\" -DPACKAGE_TARNAME=\"libtorrent-rasterbar\" -DPACKAGE_VERSION=\"1.0.6\" -DPACKAGE_STRING=\"libtorrent-rasterbar\ 1.0.6\" -DPACKAGE_BUGREPORT=\"arvid@libtorrent.org\" -DPACKAGE_URL=\"http://www.libtorrent.org\" -DPACKAGE=\"libtorrent-rasterbar\" -DVERSION=\"1.0.6\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_PTHREAD=1 -DHAVE_BOOST=/\*\*/ -DHAVE_BOOST_SYSTEM=1 -D_FILE_OFFSET_BITS=64 -DHAVE_GETHOSTBYNAME=1 -DHAVE_GETHOSTBYNAME_R=1 -DGETHOSTBYNAME_R_RETURNS_INT=1 -DHAVE_LIBRT=1 -DNDEBUG=1 -DTORRENT_USE_OPENSSL=1 -DHAVE_LINUX_TYPES_H=1 -DHAVE_LINUX_FIEMAP_H=1 -DWITH_SHIPPED_GEOIP_H=1 -DBOOST_ASIO_HASH_MAP_BUCKETS=1021 -DBOOST_EXCEPTION_DISABLE=1 -DBOOST_ASIO_ENABLE_CANCELIO=1 -DBOOST_ASIO_DYN_LINK=1 -DTORRENT_BUILDING_SHARED=1

and I actually can't see a way to enable/disable it using autotools. 

What's the quickest way to determine if it's being defined elsewhere?

**Comment by arvidn** [comment]
you could put a: #error statement in the path you would not expect to be taken. within #ifdef TORRENT_COMPACT_PICKER basically

**Comment by cas--** [comment]
I checked with `#error` in both config.hpp and piece_picker.hpp and TORRENT_COMPACT_PICKER is definitely set to 0.

**Comment by cas--** [comment]
I think the issue is from the change applied here: https://github.com/arvidn/libtorrent/blame/master/include/libtorrent/piece_picker.hpp#L842

**Comment by arvidn** [comment]
fixed in RC_1_0 and master now. I couldn't find any significant containers of this type, so I don't think the space saving there is important. I just widened those fields.

Thanks for figuring it out!
