### ISSUE TITLE
Question about torrent::tracker_response and abort state

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#2290]
libtorrent version (or branch): `master`

Hi, I noticed that I'm receiving log alerts related to tracker logic even after removing the torrent from the session. Does it makes sense to have `if (aborted) return` at the beginning of `torrent::tracker_response`, or is this a situation that warrants a better analysis.

**Comment by gubatron** [comment]
if there a way to flush the alert manager queue filtering by torrent_hash and alert type?
or to ignore alerts related to torrents that are no longer in the session (or to not notify them when they're on the way out, which might be more relevant)

ideally the solution is to find whatever it is that's pushing those alerts long after the torrent has been removed (or somehow keeping them for too long)

**Comment by arvidn** [comment]
removing torrents is asynchronous. I assume these tracker alerts are posted by the ``event=stopped`` announces when stopping a torrent. If there are many dead trackers, requiring many retries to other trackers I suppose there could potentially be minutes between removing the torrent and still receiving tracker alerts for it. I don't think there's anything wrong with libtorrent reporting this though, in fact, it would seem odd to not report on it.
