### ISSUE TITLE
isLegalUTF8 - break

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#2294]
libtorrent version (or branch): master
V796 It is possible that 'break' statement is missing in switch statement. convertutf.cpp 301

https://github.com/arvidn/libtorrent/blob/05b5b4ef4d8bce460bc5e7c6723bddfc79ff1b29/src/ConvertUTF.cpp#L301-L303

**Comment by arvidn** [comment]
can you come up with a case where there needs to be a ``break`` statement there?

**Comment by pavel-pimenov** [comment]
case 4: if ((a = (*--srcptr)) < 0x80 || a > 0xBF) return false; break;
	case 3: if ((a = (*--srcptr)) < 0x80 || a > 0xBF) return false; break;
	case 2: if ((a = (*--srcptr)) < 0x80 || a > 0xBF) return false; break;

**Comment by arvidn** [comment]
@pavel-pimenov I meant a utf8 sequence that would be misclassified without the ``break``
