### ISSUE TITLE
crash std::string portmap_alert::message

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#2301]
libtorrent version (or branch): master

https://drdump.com/DumpGroup.aspx?DumpGroupID=890674&Login=guest

	static char const* const nat_type_str[] = {"NAT-PMP", "UPnP"};
	static char const* const protocol_str[] = {"TCP", "UDP"};

	std::string portmap_alert::message() const
	{
		char ret[200];
		std::snprintf(ret, sizeof(ret), "successfully mapped port using %s. external port: %s/%u"
			, nat_type_str[static_cast<int>(map_transport)]
			, protocol_str[static_cast<int>(map_protocol)], external_port);
		return ret;
	}

**map_protocol = 2**
![default](https://user-images.githubusercontent.com/920705/29993560-4575296c-8fc3-11e7-840b-b9b12a570935.png)

**Comment by pavel-pimenov** [comment]
hot fix:
1. remove static char const* const protocol_str[] = {"TCP", "UDP"};
2. std::string portmap_alert::message() const
	{
		char ret[200];
		std::snprintf(ret, sizeof(ret), "successfully mapped port using %s. external port: %s/%u"
			, nat_type_str[static_cast<int>(map_transport)]
			, map_protocol == portmap_protocol::udp ? "UDP":"TCP"
			, external_port);
		return ret;
	}

**Comment by arvidn** [comment]
fixed [here](https://github.com/arvidn/libtorrent/commit/24d08cdf82ceb2a0fe6e875320b7c3eb5db11a30)
