### ISSUE TITLE
Is dht.libtorrent.org configured to support IPv6 nodes?

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#2304]
libtorrent version (or branch): `master`

I posting this question here, since this is the default router configured since `1.1.1`. I'm not getting any IPv6 node during the bootstrap, is that intentional?

**Comment by the8472** [comment]
```
PING dht.libtorrent.org/104.168.32.188:25401
#1 response time=118ms DEC8AE69 7351FF4A EC29CDBA ABF2FBE3 467CC267 ver:0x4C54000B/LT��
```

probably too old for v6?

**Comment by aldenml** [comment]
btw, I'm able to get IPv6 nodes from `dht.transmissionbt.com:6881`, do you know any other useful bootstrap node?

**Comment by ssiloti** [comment]
I maintain `router.silotis.us:6881` for bootstrapping the IPv6 DHT.

**Comment by aldenml** [comment]
I just noticed I have a typo: `outer.silotis.us` (missing `r`), thanks!

**Comment by aldenml** [comment]
Hi @arvidn, is `dht.libtorrent.org` really working? I'm not getting even IPv4 nodes

**Comment by arvidn** [comment]
it seems to work for me, for IPv4 at least (I believe my host lost its IPv6 interface for some reason).

I test it with: ``python dht_probe.py dht.libtorrent.org 25401`` (the tool from the ``bootstrap-dht`` repository)

**Comment by aldenml** [comment]
This is my output console:
```
MBP:bootstrap-dht aldenml$ python dht_probe.py dht.libtorrent.org 25401
-->  dht.libtorrent.org 25401
router timeout
-->  dht.libtorrent.org 25401
router timeout
-->  dht.libtorrent.org 25401
```
and with `libtorrent`
```
DHT node: adding router node: [2001:41d0:2:599c::5d71:2184]:25401
DHT node: adding router node: 104.168.32.188:25401
....
DHT traversal: [0] not alive: 104.168.32.188:25401
DHT traversal: [0] not alive: [2001:41d0:2:599c::5d71:2184]:25401
```
