### ISSUE TITLE
undefined symbol when compiled with Boost 1.65

### ISSUE THREAD

**Issue by perfect7gentleman** [arvidn/libtorrent#2309]
```~ $ python2 -c 'import libtorrent as lt; print(lt.__version__)' 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/lib64/python2.7/site-packages/libtorrent.so: undefined symbol: _ZN10libtorrent7versionEv
```

**Comment by arvidn** [comment]
which version of libtorrent are you building?

**Comment by perfect7gentleman** [comment]
Sorry,
1.1.4

**Comment by arvidn** [comment]
that's odd. It's defined [here](https://github.com/arvidn/libtorrent/blob/RC_1_1/src/version.cpp#L37), and declared to be exported [here](https://github.com/arvidn/libtorrent/blob/RC_1_1/include/libtorrent/version.hpp#L53).

Can you see it with a tool like ``nm`` or similar? Did it get the wrong mangling?

**Comment by arvidn** [comment]
are you confident the boost version is relevant? does it work with boost-1.64?

**Comment by perfect7gentleman** [comment]
i have ```nm``` installed. what command?
```
dev-libs/boost-1.65.0:0/1.65.0::gentoo  USE="icu nls python threads -context -debug -doc -mpi -static-libs -tools" ABI_X86="(64) -32 (-x32)" PYTHON_TARGETS="python2_7 python3_6 -python3_4 -python3_5"
```
yes, it worked with Boost-1.64

**Comment by perfect7gentleman** [comment]
also, the following patch https://github.com/saahriktu/modified-slackbuilds/blob/master/libtorrent-rasterbar/boost1_65_0.patch was applied to compile it with boost-1.65

**Comment by arvidn** [comment]
ah. please try ``RC_1_1`` (where I just bumped the version number to 1.1.5). I believe it has fixed the build issue. I'm about to cut the 1.1.5 release.

**Comment by perfect7gentleman** [comment]
one moment

**Comment by perfect7gentleman** [comment]
```
 ~ $  python2 -c 'import libtorrent as lt; print(lt.__version__)'
1.1.5.0
```
fixed. thanx
