### ISSUE TITLE
default_storage::release_files keeps part_file opened

### ISSUE THREAD

**Issue by ajax16384** [arvidn/libtorrent#231]
default_storage::release_files should flush and reset m_part_file.
otherwise libtorrent locks *.parts files even for already removed torrent handle.

**Comment by ajax16384** [comment]
void default_storage::release_files(storage_error&)
	{
+		m_part_file.reset();

		// make sure we don't have the files open
		m_pool.release(this);

**Comment by arvidn** [comment]
thanks. fixed: https://github.com/arvidn/libtorrent/commit/e31433d9521c7cbf074520745a2a13881130cdbb
