### ISSUE TITLE
Use of Coverity and/or SonarQube for code analysis

### ISSUE THREAD

**Issue by popcornenthusiast** [arvidn/libtorrent#2318]
About Coverity:

> What is static analysis?
> 
> Static analysis is a set of processes for finding source code defects and vulnerabilities.
> 
> In static analysis, the code under examination is not executed. As a result, test cases and specially designed input datasets are not required. Examination for defects and vulnerabilities is not limited to the lines of code that are run during some number of executions of the code, but can include all lines of code in the codebase.
> 
> Additionally, Coverity's implementation of static analysis can follow all the possible paths of execution through source code (including interprocedurally) and find defects and vulnerabilities caused by the conjunction of statements that are not errors independent of each other. 

Source: https://scan.coverity.com/faq

LibreOffice's case of success after using Coverity:

> https://webcache.googleusercontent.com/search?q=cache:WD0hZEtvR2gJ:www.coverity.com/press-releases/libreoffice-improves-software-quality-coverity-scan/+&cd=2&hl=pt-BR&ct=clnk&gl=br&client=firefox-b
> 
> http://www.infoworld.com/article/2687117/open-source-software/libreoffice-code-ten-times-better-than-proprietary.html
> 
> http://www.ocsmag.com/2014/11/30/libreoffices-coverity-defect-density-is-0-00/

Coverity Scan: https://scan.coverity.com/

What it covers (PDF!): https://www.synopsys.com/content/dam/synopsys/sig-assets/datasheets/CWE-CC-Objective-C.pdf

SonarQube works in pretty much the same way (from what I can tell), but can check for other things: https://sonarcloud.io/

What it covers: https://sonarcloud.io/organizations/default/rules#languages=cpp

**Comment by arvidn** [comment]
I've used coverity scan on libtorrent in the past. The main problem is that ``cov-build`` (iirc, the tool that intercepts calls to the compiler to record build properties) mostly does not work on the latest version of OSX (but one or a few versions behind). This makes it a hassle to run manually.

My impression is that coverity prefers to not set up a coverity analysis to run on each commit, triggered by travis for instance.

as for sonarcube, my experience is a lot better with clang-tidy. I would like to set that up to run on travis. Would you be interested in helping set that up? PRs are welcome!

**Comment by popcornenthusiast** [comment]
> I've used coverity scan on libtorrent in the past. The main problem is that cov-build (iirc, the tool that intercepts calls to the compiler to record build properties) mostly does not work on the latest version of OSX (but one or a few versions behind). This makes it a hassle to run manually.

Oh, didn't know about that. They seemed too big to let something like that happens.

> My impression is that coverity prefers to not set up a coverity analysis to run on each commit, triggered by travis for instance.

Yeah, pretty much all the projects there seem to be "outdated" when it comes to commits analysis.

> Would you be interested in helping set that up?

Well, this is a kinda strange situation. I don't know programming. I'm just curious to see what is being done when it comes to open source projects and then when I discovered Coverity/SonarQube I thought they were... promising and decided to share it - though now I see you already did use at least Coverity, so I didn't bring anything new.

Thank you for your answer.

**Comment by arvidn** [comment]
I think the "free for open source" is new since last time I looked at sonarqube, so I just set that up as well. It was surprisingly complicated.

https://sonarcloud.io/dashboard?id=libtorrent
