### ISSUE TITLE
SOCKS5 support

### ISSUE THREAD

**Issue by h-2** [arvidn/libtorrent#233]
I have tried using qbittorrent or deluge with a SOCKS5 server that is set up to support UDP. Both are setup to use the SOCKS5 for all types of connections, but on both  DHT does not work and even communication to UDP-trackers does not work (http trackers work fine). Deluge says no incoming connections...
Is this a known issue/bug or is it possibly a deficiency of my SOCKS5 server?

Thanks for your help!

**Comment by arvidn** [comment]
do you get any errors from the udp tracker announces? or any other errors, like udp errors? My experience with udp over socks5 is that very few proxies implement it correctly or at all. As far as I can recall, I've only seen one that does (dante). However, I haven't looked in  two years or so.

The most reliable way to know whether this is a bug in the proxy or libtorrent is to get a wireshark dump of the udp traffic to the proxy. I'd be happy to take a look.

**Comment by h-2** [comment]
Thanks your reply!

> do you get any errors from the udp tracker announces? or any other errors, like udp errors?

Well QBittorrent just says that it can't reach the trackers, if they are UDP. Deluge says connecting and then error, but doesn't give a message.

> My experience with udp over socks5 is that very few proxies implement it correctly or at all. As far as I can recall, I've only seen one that does (dante). 

The proxy in question actually is dante...

> The most reliable way to know whether this is a bug in the proxy or libtorrent is to get a wireshark dump of the udp traffic to the proxy.

I have attached a tcpdump log, I hope that counts, too.  The real IPs are excahnged for placeholders . What I did:
  * I start tcpdump and filter for the proxy's IP 
  * I start deluge with an ubuntu torrent that is paused and only has UDP trackers set
  * I wait a bit and unpause the torrent
  * it starts downloading through the proxy, although it can't connect to the tracker (I am guessing this is because it has cached peers from when there was an http tracker -- if I start with only UDP trackers no download ever starts)
   * I quit deluge and quit tcpdump

LOG: http://hannes.hauswedell.net/pub/tcpdump2.log.xz

Thanks for your help!

**Comment by arvidn** [comment]
thanks. that file is just the log from tcp dump. I would need the packet capture itself (.pcap). Also, feel free to filter to only include UDP packets. If you can clear cached peers to minimize the number of packets that get captured, that makes it easier too.

**Comment by h31** [comment]
Hello, Arvid!
The issue is still here, at least for libtorrent 1.0.7.
I've attached a packed capture, filtered by socks protocol. Delegate is used as a SOCKS5 server. As you can see, only one UdpAssociate request was done. A success response follows it, and nothing UDP-related happened after it.
DHT and uTP work fine with SOCKS proxy (they're not presented in the attached capture, as I've disabled them to keep the capture small) and UDP trackers aren't working.
[socks_udp.pcapng.gz](https://github.com/arvidn/libtorrent/files/334001/socks_udp.pcapng.gz)

**Comment by h-2** [comment]
Yes, I am still seeing it, as well. I currently don't have time to debug it, unfortunately, but maybe you can provide the information, @h31 ?

**Comment by arvidn** [comment]
@h-2 which version of libtorrent are you using? Also, please try the latest version of whichever major release you're on. i.e. 1.0.9 or 1.1 (or maybe even RC_1_0 or RC_1_1).
