### ISSUE TITLE
FTBS: c++: error: unrecognized command line option '-R' when compiling python bindings

### ISSUE THREAD

**Issue by Corin-EU** [arvidn/libtorrent#2332]
Source code --  libtorrent-rasterbar  v1.1.4 

Linux Mint 18.2 Sonya i386

autoconf (GNU Autoconf) 2.69
automake (GNU automake) 1.15

g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

As I have a locally installled iconv library, I decided to try building with that option enabled.

     CONFIGURE_OPTIONS="\
     --enable-debug=no                            \
     --enable-disk-stats                          \
     --enable-python-binding                      \
     --with-boost-libdir=/usr/lib/i386-linux-gnu\
     --with-libiconv                              \
     "

libtorrent library compiles and links but then on building the python bindings, the build fails with

     c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time     -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/alert.o build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/big_number.o build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/converters.o build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/create_torrent.o build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/datetime.o build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/entry.o build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/error_code.o build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/fingerprint.o build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/ip_filter.o build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/magnet_uri.o build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/module.o build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/peer_info.o build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/session.o build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/session_settings.o build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/string.o build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/torrent_handle.o build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/torrent_info.o build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/torrent_status.o build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/utility.o build/temp.linux-i686-2.7/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python/src/version.o -L../../src/.libs -L/usr/lib/i386-linux-gnu -L/usr/local/lib -L/usr/lib/i386-linux-gnu -ltorrent-rasterbar -liconv -lboost_chrono -lboost_random -lpthread -lboost_system -lboost_python -lpthread -lssl -lcrypto -o build/lib.linux-i686-2.7/libtorrent.so -fvisibility=hidden -fvisibility-inlines-hidden -R/usr/local/lib
     c++: error: unrecognized command line option '-R'
     error: command 'c++' failed with exit status 1
     Makefile:530: recipe for target 'all-local' failed
     make[2]: *** [all-local] Error 1
     make[2]: Leaving directory '/usr/src/build/libtorrent-rasterbar-1.1.4/bindings/python'

The Makefile in the bindings sub-directory contains

     Makefile:ICONV_LIBS = -L/usr/local/lib -liconv -R/usr/local/lib
     Makefile:LIBS = -L/usr/local/lib -liconv -R/usr/local/lib -lboost_chrono -lboost_random -lpthread  
     Makefile:LTLIBICONV = -L/usr/local/lib -liconv -R/usr/local/lib

(but not the Makefile.in nor Makefile.am)

In the upper directory, the configure script distributed with the tar.gz file contains the erroneous "-R" parameter in several places eg  hardcode_libdir_flag_spec='-R$libdir and LTLIBICONV="${LTLIBICONV}${LTLIBICONV:+ }-R$found_dir" 

The erroneous "-R" is also  present in libtorrent-rasterbar.pc

Libs.private: -L/usr/local/lib -liconv -R/usr/local/lib -lboost_chrono -lboost_random -lpthread   -lpthread  -lssl -lcrypto

However, on changing the "-R" to "-rpath" in libtorrent-rasterbar.pc and after doing an autoreconf -fiv to generate afresh the configure script locally, the "-R" parameter is still present in the configure script.  After running that new configure script, the erroneous "-R" is again present in the bindings directory Makefile.

How can this problem be rectified at the autotools level?

Looking at a similar problem

https://stackoverflow.com/questions/12629042/g-4-6-real-error-unrecognized-option-r

it could be that the problem is arising from a bug in an m4 file, but which one?

Perhaps libtool.m4 which has multiple instances of

_LT_TAGVAR(hardcode_libdir_flag_spec, $1)='-R$libdir'

but how come nobody else has run into this problem and reported a bug against libtool if that is where the problem arises?

**Comment by Corin-EU** [comment]
After modifying the Makefiles (and please note that -R needs to be replaced with -Wl,-rpath [not just -rpath] and relaunching the build process, it again failed with the same error.

Further invesstigation revealed another instaance of -R in the link_flags file generated in the bindings/pything directory

Changing

        -liconv -R/usr/local/lib

to

        -liconv -Wl,-rpath /usr/local/lib

in this file then resulted in a successful linking of object files to the target build/lib.linux-i686-2.7/libtorrent.so

The links_flag script is created by the top level configure script so this is still a autotools related issue.

**Comment by arvidn** [comment]
I wonder if the intention was to say ``-L``. ``-rpath`` doesn't seem quite right, does it?

**Comment by nephaste** [comment]
same problem.. with binding with Python... while cross compiling Deluge.. thanks to point this.. 

share with you, what worked for me

make a first configure
replace in all MakeFile from Top Source and in all subdirectory

 -R/opt/Deluge/lib  to  -Wl,-rpath,/opt/Deluge/lib

also in configure.status and configure.report

and make -j4  all compiling fine... 

issue in 1.1.4 source, and in Master branch as well (but Master wont compile for me due some other errors)
