### ISSUE TITLE
Evaluation to use SHA1 from git

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#234]
Here it is the history of commits (very interesting to read one-by-one): https://github.com/git/git/commits/master/block-sha1

My motivation is that I want to get rid of openssl, but that left me with the common crypto and the internal implementation of sha1 and I don't know how they compare to block-sha1 (supposedly block-sha1 is faster).

Do you think this is something worth of a try?

**Comment by sledgehammer999** [comment]
While we wait for arvidn, I think you're out of luck of dropping openssl dependency. I think openssl is used for encrypted connections between peers and probably HTTP**S** web seeds. In place of openssl you'd need to use another TLS library, and if libtorrent does networking via boost.asio (and I think it does) then you can't use another library.

**Comment by aldenml** [comment]
Hi @sledgehammer999, it is my understanding from the code, that in effect, openssl is used for HTTPS web seeds and ssl streams for ssl-cert based torrents (using boost). But the latter is all about a feature that requires a lot of support from clients (for a proper setup) and regarding HTTPS web seeds, well, I still need to evaluate that.

The clasical encrypted/obfuscation communication between peers is not using openssl (as far as I can see).

**Comment by arvidn** [comment]
right, openssl is only used for actual SSL/TLS connections. That's https trackers and web seeds. *If* openssl/libcrypto is linked in, then its RC4 and SHA-1 implementation is used as well, but there are internal implementations of those also (based on a public domain SHA-1 and libtomcrypt).

My guess is that there could probably be a significant performance improvement of SHA-1 if one were to use intel's assembly implementation. I have considered that in the past, but the build process becomes significantly more complicated including assembly object files. If their implementation could be turned into inline-assembly in a c++ file it would probably be a lot simpler. (iirc, it may be about 20% faster)

Do you have any benchmarks of git's implementation?

**Comment by aldenml** [comment]
I don't have any benchmarks, but I will get some if this idea has some value. I didn't thought about RC4, I suppose I should search for "faster if possible" RC4 implementation.

Is libtomcrypt used for something else? If we find a suitable implementation for RC4, could you consider removing it?

**Comment by aldenml** [comment]
Hi @arvidn, I was looking at the code and I don't see openssl used for RC4. Could you guide me here? Thanks.

**Comment by aldenml** [comment]
Ok, digging a little more, I see that tommath is used only for the key exchange during the setup of the RC4, after that, standard implementation follows. No openssl here and I rather not touch it.

**Comment by aldenml** [comment]
After more reading, I think I will try to use LibreSSL. Closing this issue since the adoption of the sha1 from Linus is not clear to me that it will be optimal in the future due to changes in the compiler.
