### ISSUE TITLE
setting settings_pack::share_ratio_limit does not work

### ISSUE THREAD

**Issue by tientrieu** [arvidn/libtorrent#2356]
**Please provide the following information**

libtorrent version (or branch): 1.1.1

platform/architecture: Windows 10 x64

compiler and compiler version: Microsoft Visual C++ 2015

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

- Add share_ratio_limit setting for sesssion
`settings.set_int(libtorrent::settings_pack::share_ratio_limit, 2);`

- Run the run application for seeding a torrent on dev pc (called PC A)

- Download the torrent from another PC (call PC B) using uTorrent, wait for download complete, delete downloaded torrent with data and repeat this step few times. 

Result: I can download many times the torrent from PC B. I expect it to be **limited to 2 times**.
I have mistake or settings_pack::share_ratio_limit does not work?

**Comment by arvidn** [comment]
yes, you are mistaken of the semantics of that setting. See [queuing](http://libtorrent.org/manual-ref.html#queuing).

I've improved the documentation a bit [here](https://github.com/arvidn/libtorrent/commit/7f4566c694a09905e16c8a86b9687c2c7417ca06).

**Comment by arvidn** [comment]
also, the unit is percent. when you say "2", I imagine you meant "200"
