### ISSUE TITLE
Compilation problem with Xcode 9, temporary solution

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#2364]
libtorrent version: `master`

For those working with the latest macOS Xcode 9 SDK, if you are having a problem like:
```
error: unknown type name 'mach_port_t' mach_port_t __libcpp_thread_get_port();
```
It seems that `cmake` is having problems picking the right sysroot. I don't know what's the right way to solve the problem (and send a PR), but in the meantime, you can solve it by opening the file `cmake-build-debug/CMakeCache.txt` and look for `CMAKE_OSX_SYSROOT:STRING=`. Set it like this:
```
CMAKE_OSX_SYSROOT:STRING=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
```

**Comment by arvidn** [comment]
my impression so far is that this is an issue with the toolchain update from apple

**Comment by aldenml** [comment]
mine is that apple changed something that broke some `cmake` assumption (not necessary a right one), because `bjam` works without problem, and `cmake` (any version I tested) picks the wrong headers. I just wanted to comment about it in case anyone can come up with a reasonable `CMakeList.txt` workaround.

**Comment by arvidn** [comment]
Interesting. When I updated the command line tools yesterday, it broke bjam builds for me too. I made an edit to ``/Library/Developer/CommandLineTools/usr/include/c++/v1/__threading_support``.

Specifically, I added this at the top:

```
#include <sys/_types.h>
typedef __darwin_mach_port_t mach_port_t;
mach_port_t pthread_mach_thread_np(pthread_t);
```

I found it [here](https://github.com/tensorflow/tensorflow/issues/13220#issuecomment-331579775).

**Comment by aldenml** [comment]
Ok, now `bjam` from boost 1.65.1 fails for me

**Comment by smarsching** [comment]
I just had the same problem on a completely different project and I could resolve it by defining the `_DARWIN_C_SOURCE` preprocessor macro. This can either be done by using a compiler flag or by including something like

```
#ifdef __APPLE__
#define _DARWIN_C_SOURCE
#endif
```

at the top of the affected source file.

**Comment by arianitu** [comment]
@smarsching thanks, I had this issue while configuring https://github.com/PowerDNS/pdns and I did:

`export CPPFLAGS="-D_DARWIN_C_SOURCE"`

 to fix it

**Comment by aldenml** [comment]
I just updated the Xcode and command tools from the app store, and it overrides the files. I'm solving adding this line `<cxxflags>-D_DARWIN_C_SOURCE` to my `config.jam`, @arvidn do you think it's better to add it to `Jamfile` and `CMakeLists.txt`?
