### ISSUE TITLE
Possible solution on fast preallocation on Windows?

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#2372]
I had one user propose to use the [SetFileValidData](https://msdn.microsoft.com/library/aa365544.aspx) WINAPI to facilitate fast preallocation.
Basically he wants fast start on big files **and** avoidance of file fragmentation.
He writes that `aria2` uses this trick.

I am in no position to evaluate any of this. I just forward the request here. You decide what happens.
PS: He also mentions that the same trick can be done on linux via falloc.

**Comment by sledgehammer999** [comment]
tagging the user: @pasha-zzz

**Comment by sledgehammer999** [comment]
Also from a bit of searching on aria2 -> Possible security issue: https://github.com/aria2/aria2/issues/583

**Comment by pasha-zzz** [comment]
About this security issue: user must have SE_MANAGE_VOLUME_NAME pivilege.

**Comment by ssiloti** [comment]
libtorrent already tries to call `SetFileValidData`, but by default regular Windows users do not have the `SE_MANAGE_VOLUME_NAME` privilege so the call fails most of the time.

**Comment by pasha-zzz** [comment]
User is in Administrators froup, "Perform volume maintenance tasks" in secpol.msc enabled for Administrators. But qBt allocates space slow.

**Comment by pasha-zzz** [comment]
This code creates file of given size using SetFileValidData.
https://github.com/mzhou/setfilevaliddata/blob/master/setfilevaliddata/main.c

Required calls before calling this function are SetFilePointer or SetFilePointerEx and SetEndOfFile

**Comment by ssiloti** [comment]
Did you try running that program? If you try to run it as a regular user The call to `SetFileValidData` fails with error code 1314 `A required privilege is not held by the client`.

While regular users _can_ launch processes with administrator privileges, that is not the default. A processes can request privilege elevation, which will cause a UAC prompt to appear to the user. If qBittorrent were so inclined they could make such a request, but I imaging most users do not want to get a UAC prompt when they launch the app.

**Comment by pasha-zzz** [comment]
Run this program as admin - it rapidly create file 100 GB (trash content inside, no zeroes). Running qBT as admin - nothing changed.

**Comment by ajax16384** [comment]
By default libtorrent (master) uses "storage_mode_sparse" flag, to use preallocate at start with possibility to use SetFileValidData technique "storage_mode_allocate" should be passed to "add_torrent" params.
As far as i understand qBT also disables preallocate by default:
````c++
    , m_isPreallocationEnabled(BITTORRENT_SESSION_KEY("Preallocation"), false)
....
    if (isPreallocationEnabled())
        p.storage_mode = libt::storage_mode_allocate;
    else
        p.storage_mode = libt::storage_mode_sparse;
````
toggle Preallocation and recheck libtorrent behaviour

**Comment by ajax16384** [comment]
It seems GetCompressedFileSizeW and GetFileInformationByHandleEx never gave a chance to call SetFileValidData. #2374 trying to fix this issue.

**Comment by ajax16384** [comment]
if skip or fail to call SetFileValidData for large file then this WriteFile https://gist.github.com/ajax16384/c0a9b1e50a307bc8f656622f801badea#file-setfilevaliddata-c-L95 will pause for full file space preallocation.

**Comment by arvidn** [comment]
Fixed in RC_1_1 https://github.com/arvidn/libtorrent/pull/2376 and merged into master. Thanks @ajax16384 !

**Comment by libTorrentUser** [comment]
There is just one problem with the SetFileValidData solution. As you already know, the user may not have the required privileges for the call. When that happens the call will fail (as the code already expects) but nothing else is done.

The result, on Windows, is a useless sparse file. The user will think libTorrent is pre-allocating the file because he asked it do it, a not so tech savvy user will think the file was pre-allocated because windows explorer will "lie" and show the make believe size and the original problem pre-allocation was supposed to solve (disk fragmentation) will still happen.

I suggest falling back to the classic SetFilePointer,SetEndOfFile combo when that happens. Yes, it will go back to the write zeros situation, but at least it will be pre-allocating instead of lying to the users.
