### ISSUE TITLE
Error building with Visual Studio 2015

### ISSUE THREAD

**Issue by cocof35** [arvidn/libtorrent#238]
Hi everyone! When i try to build libtorrent with vc14 i get this error:
[ 22%] Building CXX object CMakeFiles/torrent-rasterbar.dir/src/http_connection.cpp.obj
http_connection.cpp
C:\lib\Boost\include\boost-1_59\boost/asio/detail/config.hpp(227): warning C4005: 'BOOST_ASIO_ERROR_CATEGORY_NOEXCEPT' : redéfinition de macro
C:\lib\Boost\include\boost-1_59\boost/asio/detail/config.hpp(213): note: voir la définition précédente de 'BOOST_ASIO_ERROR_CATEGORY_NOEXCEPT'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\include\libtorrent/io.hpp(156): warning C4267: 'return' : conversion de 'size_t' en 'int', perte possible de données
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\include\libtorrent/connection_queue.hpp(69): warning C4267: 'return' : conversion de 'size_t' en 'int', perte possible de données
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(170): error C2668: 'snprintf' : appel ambigu à une fonction surchargée
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\include\libtorrent/config.hpp(328): note: est peut-être 'int snprintf(char *,int,const char *,...)'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1932): note: ou       'int snprintf(char *const ,const size_t,const char *const ,...)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(170): note: lors de la tentative de mise en correspondance de la liste des arguments '(char *, __int64, const char [18], const char *)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(173): error C2668: 'snprintf' : appel ambigu à une fonction surchargée
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\include\libtorrent/config.hpp(328): note: est peut-être 'int snprintf(char *,int,const char *,...)'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1932): note: ou       'int snprintf(char *const ,const size_t,const char *const ,...)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(173): note: lors de la tentative de mise en correspondance de la liste des arguments '(char *, __int64, const char [32], const char *)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(178): error C2668: 'snprintf' : appel ambigu à une fonction surchargée
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\include\libtorrent/config.hpp(328): note: est peut-être 'int snprintf(char *,int,const char *,...)'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1932): note: ou       'int snprintf(char *const ,const size_t,const char *const ,...)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(178): note: lors de la tentative de mise en correspondance de la liste des arguments '(char *, __int64, const char [9], const char *)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(179): error C2668: 'snprintf' : appel ambigu à une fonction surchargée
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\include\libtorrent/config.hpp(328): note: est peut-être 'int snprintf(char *,int,const char *,...)'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1932): note: ou       'int snprintf(char *const ,const size_t,const char *const ,...)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(179): note: lors de la tentative de mise en correspondance de la liste des arguments '(char *, __int64, const char [6], int)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(180): error C2668: 'snprintf' : appel ambigu à une fonction surchargée
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\include\libtorrent/config.hpp(328): note: est peut-être 'int snprintf(char *,int,const char *,...)'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1932): note: ou       'int snprintf(char *const ,const size_t,const char *const ,...)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(180): note: lors de la tentative de mise en correspondance de la liste des arguments '(char *, __int64, const char [3])'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(185): error C2668: 'snprintf' : appel ambigu à une fonction surchargée
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\include\libtorrent/config.hpp(328): note: est peut-être 'int snprintf(char *,int,const char *,...)'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1932): note: ou       'int snprintf(char *const ,const size_t,const char *const ,...)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(185): note: lors de la tentative de mise en correspondance de la liste des arguments '(char *, __int64, const char [26], const char *, const char *)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(186): error C2668: 'snprintf' : appel ambigu à une fonction surchargée
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\include\libtorrent/config.hpp(328): note: est peut-être 'int snprintf(char *,int,const char *,...)'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1932): note: ou       'int snprintf(char *const ,const size_t,const char *const ,...)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(186): note: lors de la tentative de mise en correspondance de la liste des arguments '(char *, __int64, const char [6], int)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(187): error C2668: 'snprintf' : appel ambigu à une fonction surchargée
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\include\libtorrent/config.hpp(328): note: est peut-être 'int snprintf(char *,int,const char *,...)'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1932): note: ou       'int snprintf(char *const ,const size_t,const char *const ,...)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(187): note: lors de la tentative de mise en correspondance de la liste des arguments '(char *, __int64, const char [3])'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(193): error C2668: 'snprintf' : appel ambigu à une fonction surchargée
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\include\libtorrent/config.hpp(328): note: est peut-être 'int snprintf(char *,int,const char *,...)'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1932): note: ou       'int snprintf(char *const ,const size_t,const char *const ,...)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(193): note: lors de la tentative de mise en correspondance de la liste des arguments '(char *, __int64, const char [17], const char *)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(196): error C2668: 'snprintf' : appel ambigu à une fonction surchargée
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\include\libtorrent/config.hpp(328): note: est peut-être 'int snprintf(char *,int,const char *,...)'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1932): note: ou       'int snprintf(char *const ,const size_t,const char *const ,...)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(196): note: lors de la tentative de mise en correspondance de la liste des arguments '(char *, __int64, const char [24])'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(199): error C2668: 'snprintf' : appel ambigu à une fonction surchargée
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\include\libtorrent/config.hpp(328): note: est peut-être 'int snprintf(char *,int,const char *,...)'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1932): note: ou       'int snprintf(char *const ,const size_t,const char *const ,...)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(199): note: lors de la tentative de mise en correspondance de la liste des arguments '(char *, __int64, const char [26], const char *)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(201): error C2668: 'snprintf' : appel ambigu à une fonction surchargée
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\include\libtorrent/config.hpp(328): note: est peut-être 'int snprintf(char *,int,const char *,...)'
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1932): note: ou       'int snprintf(char *const ,const size_t,const char *const ,...)'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(201): note: lors de la tentative de mise en correspondance de la liste des arguments '(char *, __int64, const char [22])'
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(171): warning C4390: ';' : une instruction contrôlée a été trouvée vide ; est-ce ce que vous souhaitiez ?
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(192): warning C4390: ';' : une instruction contrôlée a été trouvée vide ; est-ce ce que vous souhaitiez ?
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(195): warning C4390: ';' : une instruction contrôlée a été trouvée vide ; est-ce ce que vous souhaitiez ?
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(198): warning C4390: ';' : une instruction contrôlée a été trouvée vide ; est-ce ce que vous souhaitiez ?
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(684): warning C4267: 'initialisation' : conversion de 'size_t' en 'int', perte possible de données
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(718): warning C4267: '-=' : conversion de 'size_t' en 'int', perte possible de données
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(743): warning C4267: 'argument' : conversion de 'size_t' en 'int', perte possible de données
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(756): warning C4267: '+=' : conversion de 'size_t' en 'int', perte possible de données
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(845): warning C4267: 'initialisation' : conversion de 'size_t' en 'int', perte possible de données
C:\Users\Coco\Desktop\libtorrent-rasterbar-1.0.6\src\http_connection.cpp(889): warning C4267: 'initialisation' : conversion de 'size_t' en 'int', perte possible de données
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe' : code retour '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : code retour '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : code retour '0x2'
Stop.

**Comment by arvidn** [comment]
ah, this was fixed in master but never back-ported to 1.0.x. I merged it to the RC_1_0 branch. would you mind trying head of RC_1_0? (hopefully soon to become 1.0.7)

**Comment by cocof35** [comment]
I don't have time right now but maybe tomorrow

**Comment by cocof35** [comment]
Ok. tried to build with current master branch and get this error:


[  0%] Building CXX object CMakeFiles/torrent-rasterbar.dir/src/web_connection_base.cpp.obj
web_connection_base.cpp
C:\lib\Boost\include\boost-1_59\boost/asio/detail/config.hpp(227): warning C4005: 'BOOST_ASIO_ERROR_CATEGORY_NOEXCEPT' : redéfinition de macro
C:\lib\Boost\include\boost-1_59\boost/asio/detail/config.hpp(213): note: voir la définition précédente de 'BOOST_ASIO_ERROR_CATEGORY_NOEXCEPT'
C:\Users\Coco\Desktop\libtorrent\include\libtorrent/buffer.hpp(208): warning C4244: '-=' : conversion de '__int64' en 'uint32_t', perte possible de données
C:\Users\Coco\Desktop\libtorrent\include\libtorrent/sha1_hash.hpp(152): warning C4267: '-=' : conversion de 'size_t' en 'int', perte possible de données
C:\Users\Coco\Desktop\libtorrent\include\libtorrent/sha1_hash.hpp(189): warning C4267: '-=' : conversion de 'size_t' en 'int', perte possible de données
C:\Users\Coco\Desktop\libtorrent\include\libtorrent/receive_buffer.hpp(68): warning C4267: 'return' : conversion de 'size_t' en 'int', perte possible de données
C:\Users\Coco\Desktop\libtorrent\include\libtorrent/storage.hpp(642): warning C4267: 'return' : conversion de 'size_t' en 'int', perte possible de données
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/detail/impl/openssl_init.ipp(47): error C2039: 'CRYPTO_set_id_callback' : n'est pas membre de '`global namespace''
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/detail/impl/openssl_init.ipp(47): error C3861: 'CRYPTO_set_id_callback' : identificateur introuvable
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/detail/impl/openssl_init.ipp(64): error C2039: 'CRYPTO_set_id_callback' : n'est pas membre de '`global namespace''
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/detail/impl/openssl_init.ipp(64): error C3861: 'CRYPTO_set_id_callback' : identificateur introuvable
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(58): error C2039: 'RSA_free' : n'est pas membre de '`global namespace''
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(58): error C3861: 'RSA_free' : identificateur introuvable
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(64): error C2039: 'DH_free' : n'est pas membre de '`global namespace''
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(64): error C3861: 'DH_free' : identificateur introuvable
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(83): error C2039: 'SSLv2_method' : n'est pas membre de '`global namespace''
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(83): error C3861: 'SSLv2_method' : identificateur introuvable
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(86): error C2039: 'SSLv2_client_method' : n'est pas membre de '`global namespace''
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(86): error C3861: 'SSLv2_client_method' : identificateur introuvable
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(89): error C2039: 'SSLv2_server_method' : n'est pas membre de '`global namespace''
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(89): error C3861: 'SSLv2_server_method' : identificateur introuvable
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(199): error C2027: utilisation du type non défini 'ssl_ctx_st'
C:\lib\openssl\include\openssl/ossl_typ.h(177): note: voir la déclaration de 'ssl_ctx_st'
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(199): error C2227: la partie gauche de '->default_passwd_callback_userdata' doit pointer vers un type class/struct/union/générique
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(203): error C2027: utilisation du type non défini 'ssl_ctx_st'
C:\lib\openssl\include\openssl/ossl_typ.h(177): note: voir la déclaration de 'ssl_ctx_st'
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(203): error C2227: la partie gauche de '->default_passwd_callback_userdata' doit pointer vers un type class/struct/union/générique
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(205): error C2027: utilisation du type non défini 'ssl_ctx_st'
C:\lib\openssl\include\openssl/ossl_typ.h(177): note: voir la déclaration de 'ssl_ctx_st'
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(205): error C2227: la partie gauche de '->default_passwd_callback_userdata' doit pointer vers un type class/struct/union/générique
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(542): error C2027: utilisation du type non défini 'ssl_ctx_st'
C:\lib\openssl\include\openssl/ossl_typ.h(177): note: voir la déclaration de 'ssl_ctx_st'
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(542): error C2227: la partie gauche de '->default_passwd_callback' doit pointer vers un type class/struct/union/générique
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(543): error C2027: utilisation du type non défini 'ssl_ctx_st'
C:\lib\openssl\include\openssl/ossl_typ.h(177): note: voir la déclaration de 'ssl_ctx_st'
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(543): error C2227: la partie gauche de '->default_passwd_callback_userdata' doit pointer vers un type class/struct/union/générique
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(543): error C2660: 'PEM_read_bio_X509_AUX' : la fonction ne prend pas 2 arguments
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(560): error C2027: utilisation du type non défini 'ssl_ctx_st'
C:\lib\openssl\include\openssl/ossl_typ.h(177): note: voir la déclaration de 'ssl_ctx_st'
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(560): error C2227: la partie gauche de '->extra_certs' doit pointer vers un type class/struct/union/générique
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(562): error C2027: utilisation du type non défini 'ssl_ctx_st'
C:\lib\openssl\include\openssl/ossl_typ.h(177): note: voir la déclaration de 'ssl_ctx_st'
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(562): error C2227: la partie gauche de '->extra_certs' doit pointer vers un type class/struct/union/générique
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(563): error C2027: utilisation du type non défini 'ssl_ctx_st'
C:\lib\openssl\include\openssl/ossl_typ.h(177): note: voir la déclaration de 'ssl_ctx_st'
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(563): error C2227: la partie gauche de '->extra_certs' doit pointer vers un type class/struct/union/générique
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(567): error C2027: utilisation du type non défini 'ssl_ctx_st'
C:\lib\openssl\include\openssl/ossl_typ.h(177): note: voir la déclaration de 'ssl_ctx_st'
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(567): error C2227: la partie gauche de '->default_passwd_callback' doit pointer vers un type class/struct/union/générique
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(568): error C2027: utilisation du type non défini 'ssl_ctx_st'
C:\lib\openssl\include\openssl/ossl_typ.h(177): note: voir la déclaration de 'ssl_ctx_st'
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(568): error C2227: la partie gauche de '->default_passwd_callback_userdata' doit pointer vers un type class/struct/union/générique
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(568): error C2660: 'PEM_read_bio_X509' : la fonction ne prend pas 2 arguments
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(644): error C2027: utilisation du type non défini 'ssl_ctx_st'
C:\lib\openssl\include\openssl/ossl_typ.h(177): note: voir la déclaration de 'ssl_ctx_st'
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(644): error C2227: la partie gauche de '->default_passwd_callback' doit pointer vers un type class/struct/union/générique
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(645): error C2027: utilisation du type non défini 'ssl_ctx_st'
C:\lib\openssl\include\openssl/ossl_typ.h(177): note: voir la déclaration de 'ssl_ctx_st'
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(645): error C2227: la partie gauche de '->default_passwd_callback_userdata' doit pointer vers un type class/struct/union/générique
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(645): error C2660: 'PEM_read_bio_PrivateKey' : la fonction ne prend pas 2 arguments
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(703): error C2027: utilisation du type non défini 'ssl_ctx_st'
C:\lib\openssl\include\openssl/ossl_typ.h(177): note: voir la déclaration de 'ssl_ctx_st'
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(703): error C2227: la partie gauche de '->default_passwd_callback' doit pointer vers un type class/struct/union/générique
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(704): error C2027: utilisation du type non défini 'ssl_ctx_st'
C:\lib\openssl\include\openssl/ossl_typ.h(177): note: voir la déclaration de 'ssl_ctx_st'
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(704): error C2227: la partie gauche de '->default_passwd_callback_userdata' doit pointer vers un type class/struct/union/générique
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(704): error C2660: 'PEM_read_bio_RSAPrivateKey' : la fonction ne prend pas 2 arguments
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(923): error C2027: utilisation du type non défini 'ssl_ctx_st'
C:\lib\openssl\include\openssl/ossl_typ.h(177): note: voir la déclaration de 'ssl_ctx_st'
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(923): error C2227: la partie gauche de '->default_passwd_callback_userdata' doit pointer vers un type class/struct/union/générique
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(925): error C2027: utilisation du type non défini 'ssl_ctx_st'
C:\lib\openssl\include\openssl/ossl_typ.h(177): note: voir la déclaration de 'ssl_ctx_st'
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(925): error C2227: la partie gauche de '->default_passwd_callback_userdata' doit pointer vers un type class/struct/union/générique
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(927): error C2027: utilisation du type non défini 'ssl_ctx_st'
C:\lib\openssl\include\openssl/ossl_typ.h(177): note: voir la déclaration de 'ssl_ctx_st'
C:\lib\Boost\include\boost-1_59\boost/asio/ssl/impl/context.ipp(927): error C2227: la partie gauche de '->default_passwd_callback_userdata' doit pointer vers un type class/struct/union/générique
C:\Users\Coco\Desktop\libtorrent\include\libtorrent/torrent.hpp(1036): warning C4800: 'libtorrent::piece_manager *' : valeur forcée à la valeur booléenne 'true' ou 'false' (avertissement sur les performances)
C:\Users\Coco\Desktop\libtorrent\include\libtorrent/torrent.hpp(1082): warning C4244: '=' : conversion de 'int64_t' en 'int16_t', perte possible de données
C:\Users\Coco\Desktop\libtorrent\include\libtorrent/torrent.hpp(1125): warning C4267: 'return' : conversion de 'size_t' en 'int', perte possible de données
C:\Users\Coco\Desktop\libtorrent\include\libtorrent/block_cache.hpp(363): warning C4267: 'return' : conversion de 'size_t' en 'int', perte possible de données
C:\Users\Coco\Desktop\libtorrent\include\libtorrent/session_handle.hpp(76): warning C4800: 'libtorrent::aux::session_impl *const ' : valeur forcée à la valeur booléenne 'true' ou 'false' (avertissement sur les performances)
C:\Users\Coco\Desktop\libtorrent\src\web_connection_base.cpp(200): warning C4267: 'argument' : conversion de 'size_t' en 'int', perte possible de données
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe' : code retour '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : code retour '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : code retour '0x2'
Stop.

**Comment by arvidn** [comment]
that looks like you're building with openssl enabled, but without having openssl installed (or available in the default link and include path)

**Comment by cocof35** [comment]
i built it without enabling openssl and it works but i had to add the path of some of the needed library with the options /libpath:PATH .
