### ISSUE TITLE
filesize limit issue

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#2394]
master branch

parse_info_section has now:
...
if (files.total_size() >= std::numeric_limits|int|::max()
	- files.piece_length())
{
	ec = errors::too_many_pieces_in_torrent;
	// mark the torrent as invalid
	m_files.set_piece_length(0);
	return false;
}

that limits the size to 2GB, right?
Why?

**Comment by arvidn** [comment]
yes, this was a mistake. brought to my attention here https://github.com/arvidn/libtorrent/pull/2393
it's fixed now.
