### ISSUE TITLE
session peer class count issue

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#2397]
libtorrent version (or branch): master

I am still looking into the ever increasing memory consumption.

Is the session_impl::m_classes count supposed to be greater than 8000 or more after some time with many torrents added and removed? (not more than 400 torrents in the session at the same time)
I saw that each torrent adds a new class with the torrents name but it never gets removed if the torrent is removed.
I placed a breakpoint in peer_class_pool::decref() at
m_peer_classes[c].clear();
but that breakpoint is never reached (not even at session destruction)

Maybe the reason is torrent::setup_peer_class() adding a reference count of two?

**Comment by arvidn** [comment]
interesting. The peer classes are created when you set a per-torrent rate limit. But the torrent object is supposed to hold a handle that should cause the peer class to be removed when the torrent is removed. Do you see the ``torrent`` destructor be called?

**Comment by MassaRoddel** [comment]
The torrent destructor is called and also before torrent::abort which decrements the ref count by one. I think that the problem is in torrent::setup_peer_class() which increments the ref count by two.
And so every class entry is left with a ref count of one after the torrent has been removed.

**Comment by arvidn** [comment]
could you please give this a try? I can't think of a good way to test this, short of adding another performance counter for the number of peer_class objects (which there probably should be a counter for).

https://github.com/arvidn/libtorrent/pull/2402

**Comment by MassaRoddel** [comment]
It works.

**Comment by arvidn** [comment]
This was fixed in RC_1_1 and has been merged into master now.
