### ISSUE TITLE
Add the error_code in the torrent_status

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#241]
Is it possible to have the error_code in the torrent_status? It will be easier to display different status/notifications/whatever based on the error_code type instead of the string explaining the error.

**Comment by arvidn** [comment]
yes, that's something I've meant to add for a long time. In fact, I'm a bit surprised I haven't already.

**Comment by arvidn** [comment]
what do you think about this patch? https://github.com/arvidn/libtorrent/pull/243

**Comment by sledgehammer999** [comment]
I only saw the comments in `torrent_status.hpp`.
2 things:
1. Just to remind you that there are alerts that have error_code but do not result in a paused torrent, like `fastresume_rejected_alert`. In case you wanted to handle that possibility too
2. I imagine that this change will go into master only. So why not change the type of the `error` var from std::string to error_code ?

**Comment by arvidn** [comment]
I considered deprecating the error string member, but while doing so, I realized it's actually non-trivial to reproduce that string on the client side, and it can be quite convenient. For file errors it includes the filename for instance.

**Comment by arvidn** [comment]
I'm hesitant to change any of the semantics around a torrent having an error state. alerts with error_codes are fine I think, as long as it's not a torrent_error_alert. Those are supposed to map 1:1 with this field.

**Comment by sledgehammer999** [comment]
Ok. I may have not thought this through that's why I made that suggestion. Personally I was thinking in terms of "rejected fastreume" alert which I talk on my other bug report. Now, we do record keeping of this event in our torrent class, and I was thinking that it would be better if that error was available through the torrent_status, which we use extensively to update the transferlist(GUI element) and minimize cpu usage for big sessions.

I understand that this may not fit correctly on what torrent_status is supposed to represent. However, regardless of this, the initial request is still valid.

**Comment by arvidn** [comment]
the problem then is that you may miss errors. Since the rejected resume data error is not fatal, it may immediately be replaced by a fatal error, and unless you're lucky or poll frequently enough, you'll never see that the resume data failed. Currently (iirc), a torrent cannot resume until its error is cleared, guaranteeing that it can only have a single error at a time.

**Comment by sledgehammer999** [comment]
>it may immediately be replaced by a fatal error, and unless you're lucky or poll frequently enough, you'll never see that the resume data failed

Are you talking about current RC_1_0 or your patch? Do you mean that we may not get the "rejected fastresume" alert if there is another alert with fatal error after it?

**Comment by arvidn** [comment]
no, I'm referring to the idea of reporting non-fatal errors via torrent_status::error. Which is not done, because of the reason above

**Comment by sledgehammer999** [comment]
Ok. Then I think you can merge your patch.
