### ISSUE TITLE
Do we support piece number >= 4096

### ISSUE THREAD

**Issue by dmxraj** [arvidn/libtorrent#2428]
libtorrent version (or branch):
1.1.4
platform/architecture:
ANDROID ARMEABI-V7A
compiler and compiler version:
NDK r10
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Choose any torrent which has more than 4095 pieces.
It fails during rechecking.

Error:
on_piece_hashed, fatal disk error: (22) Invalid argument
alert type: file_error_alert
[Oct 08 18:06:31] TRRNT Title read (/storage/extSdCard/filepath.mp4) error: Invalid argument

Last piece passed log is:
PIECE PASS [ p: 4095 | block_hash_size: 0 ]

I suspect 4096 and above is not supported by code.

**Comment by dmxraj** [comment]
android NDK r10 pread has some problems.
I disabled TORRENT_USE_PREAD. Now it is working fine.

**Comment by arvidn** [comment]
I suspect the actual issue in this case would be the *file offset* exceeding 2^31 or perhaps 2^32 (so, not strictly speaking the number of pieces, but the number of pieces times the piece size).
My experience is that android has a lot of 32 bit APIs, at least historically it has been necessary to make naked system call to access the 64 bit versions of file APIs. Perhaps the ``pread*()`` calls is an example of a 32 bit API on android.

**Comment by aldenml** [comment]
I thought this was fixed with https://github.com/arvidn/libtorrent/pull/1232 a long time ago, I will double check (at least with `master`).
