### ISSUE TITLE
Check if /MP affects abi

### ISSUE THREAD

**Issue by silverqx** [arvidn/libtorrent#2442]
Personal task, to check if msvc /MP option somehow affects abi.

https://msdn.microsoft.com/en-us/library/bb385193.aspx
https://github.com/arvidn/libtorrent/pull/2437#discussion_r144543647

**Comment by arvidn** [comment]
oh, ``/MP`` only makes the build use multiple threads/processes while building. It shouldn't affect the ABI. As I said in my other comment, I had it mixed up with ``/MD``

**Comment by silverqx** [comment]
So it's clear than, /MP is safe and /MD and /MT are correct in cmake file, /MP doesn't affect linking only compilation:
```
string(REPLACE "/MD" "/MT" ${CompilerFlag} "${${CompilerFlag}}")
```
