### ISSUE TITLE
torrent_status::error_file broken in python bindings

### ISSUE THREAD

**Issue by aresch** [arvidn/libtorrent#2453]
**Please provide the following information**

libtorrent version (or branch): master

platform/architecture: x86_64

compiler and compiler version: gcc7

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

`struct` is a torrent_status object generated from torrent_handle::status().
`key` is 'error_file'.
```
>           value = getattr(struct, key)                                                                                                                                            
E           TypeError: No Python class registered for C++ class libtorrent::aux::strong_typedef<int, libtorrent::aux::file_index_tag, void>   
```

**Comment by arvidn** [comment]
does this work for you? https://github.com/arvidn/libtorrent/pull/2455
