### ISSUE TITLE
Lingering Connections

### ISSUE THREAD

**Issue by doadin** [arvidn/libtorrent#2454]
**Please provide the following information**

libtorrent version (or branch):
1.1.5(RC_1_1) though has been going on with many previous versions.

platform/architecture:
Windows/x86

compiler and compiler version:
python2.7/boost1.63/msvc9.0

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

After downloading some torrent even after pausing the torrent when its finished ~1-3 connections remain open(https://i.imgur.com/L3sKWDI.jpg)(not 100% off the time) it does appear that after some time the connection(s) will close but it shouldn't linger especially when a torrent is paused(?). Not sure how long the connection(s) remain open but its usually long enough for me to see its happneing remote into my proxy machine and then kill the connection(s). In the case shown in the picture its happening with a peer but it also happens with a seed connection as well in which case I really don't see why the connection would remain.(In the case of peers I could see it being open trying to finish sending a piece or something)

The setup this happens under is using a socks5 proxy setting. I know there is no "stop" only a pause(at least in deluge) however keeping a connection open transferring no data seems a bit wrong to me.

**Comment by Seeker2** [comment]
Can you confirm if those lingering connections are outgoing connection attempts that haven't timed out yet?
Such connection attempts may linger for the timeout duration set by the operating system.

**Comment by arvidn** [comment]
do you see the connection in ``netstat`` as well? (to confirm it's not just an accounting issue, but that the connection actually exists).
Do you see the connection in the peer list? (i.e. ``get_peer_info``). If so, what is the ``flags`` field set to?

**Comment by doadin** [comment]
@Seeker2 If you mean whether the connection is "established" or not it is indeed. It is NOT in a "TIME_WAIT" or  "UNREPLIED"  or anything like that.

@arvidn Yes as I noted before the connection does actually exist thats how I am able to kill the connection from the remote system. And yes it lists a peer/seed just like normal in the peer list. The flags im not sure of.
