### ISSUE TITLE
Question about thread issue in default_storage::need_partfile

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#2458]
libtorrent: `master`

I see that `default_storage::need_partfile` do some null checking and reset the field `std::unique_ptr<part_file> m_part_file;`, but I don't see any mutex protecting concurrent execution of `need_partfile`. Is that correct? or I missing something? Thanks

(this in relation to https://github.com/arvidn/libtorrent/issues/2371)

**Comment by arvidn** [comment]
This is a good observation. the part_file is thread safe internally, but as you point out, it can be constructed and destructed by separate threads independently. Some of the places where it is destroyed are in "fenced" disk jobs, which means no other thread will execute a job on the same storage. But even it it all turns out to be thread safe, it's not clear that it is.

**Comment by aldenml** [comment]
What about `default_storage::set_file_priority`, is that job task "fenced" too?

**Comment by arvidn** [comment]
Yes, [set_file_priority](https://github.com/arvidn/libtorrent/blob/master/src/disk_io_thread.cpp#L1999) is fenced. 

so is [async_release_files](https://github.com/arvidn/libtorrent/blob/master/src/disk_io_thread.cpp#L1835), [async_stop_torrent](https://github.com/arvidn/libtorrent/blob/master/src/disk_io_thread.cpp#L1961) and [async_delete_files](https://github.com/arvidn/libtorrent/blob/master/src/disk_io_thread.cpp#L1894).

That covers all the cases where the partfile is destructed. However, it's still constructed in ``readv`` and ``writev``, which definitely can run concurrently. It's not obvious that it could break anything seriously, but it would still be inefficient to construct multiple instances in parallel just to throw all but one out. I think the ``need_partfile`` need some more thought.

**Comment by aldenml** [comment]
The problem I see is that if `writev` runs concurrently, when you get to the line storage.cpp:530 `int const ret = m_part_file->writev(...)`, it fails because `m_part_file` could be destructed. Isn't that possible?

**Comment by arvidn** [comment]
possibly. I kind of expect the ``shared_ptr`` to act a bit like ``std::atomic<part_file*>`` so that it would always point to the most recently constructed object. But I'm not confident and agree that it should be fixed either way.

**Comment by aldenml** [comment]
I'm thinking about putting a simple mutex, but you tell me if you have some preference/idea in mind. btw, its a`unique_ptr`

**Comment by arvidn** [comment]
oh, I see. then there's definitely a race. Can you think of a way to not have to lock a mutex for every 16 kiB block?

**Comment by aldenml** [comment]
will think about it

**Comment by aldenml** [comment]
@arvidn here it is, https://github.com/arvidn/libtorrent/pull/2464, let me know what do you think of it
