### ISSUE TITLE
Listen alerts aren't issued for session constructor

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#246]
`listen_succeeded_alert` and `listen_failed_alert` aren't issued when you pass a network interface to the constructor of the session. These alerts are issued only if you use `listen_on()`.

So there isn't a way to be sure that the listen succeeded and to present the info to the user.

Could this be fixed? For RC_1_0 too?

**Comment by arvidn** [comment]
it is broken in master and RC_1_0 you say?

**Comment by sledgehammer999** [comment]
I can't test master, qbt isn't compatible yet. RC_1_0 is broken.

**Comment by arvidn** [comment]
btw, I would be interested in knowing what API change broke qbt, I've tried to stay backwards compatible with the API (not the ABI though)

**Comment by arvidn** [comment]
also, is it possible that you aren't setting the alert mask in the constructor? If you don't, but set it later, there's a race condition where some alerts may be swallowed.

**Comment by arvidn** [comment]
could you try this patch?

**Comment by sledgehammer999** [comment]
>btw, I would be interested in knowing what API change broke qbt, I've tried to stay backwards compatible with the API (not the ABI though)

Well, it was a docs clarification that showed qbt's broken approach. Until recently the docs told that for the session constructor that didn't take an iface address it wouldn't connect until listen_on() was called. So if we found a configured iface that had disappeared we didn't call listen_on() thinking that it isn't listening to anything and that was good for security purposes.

Then the doc change came. To avoid multiple re-bindings and possibly connecting to non-configured interface briefly I chose to pass the correct interface at construction. And if the configured interface doesn't exist I pass "127.0.0.1".

>also, is it possible that you aren't setting the alert mask in the constructor? If you don't, but set it later, there's a race condition where some alerts may be swallowed.

Oh no. You might be right. Let me check that.

**Comment by sledgehammer999** [comment]
This is the unmodified code snippet:

```c++
libt::fingerprint fingerprint(PEER_ID, VERSION_MAJOR, VERSION_MINOR, VERSION_BUGFIX, VERSION_BUILD);
    const unsigned short port = pref->getSessionPort();
    std::pair<int,int> ports(port, port);
    const QString ip = getListeningIPs().first();

    if (ip.isEmpty()) {
        logger->addMessage(tr("qBittorrent is trying to listen on any interface port: %1", "e.g: qBittorrent is trying to listen on any interface port: TCP/6881").arg(QString::number(port)), Log::INFO);
        m_nativeSession = new libt::session(fingerprint, ports, 0, 0);
    }
    else {
        logger->addMessage(tr("qBittorrent is trying to listen on interface %1 port: %2", "e.g: qBittorrent is trying to listen on interface 192.168.0.1 port: TCP/6881").arg(ip).arg(port), Log::INFO);
        m_nativeSession = new libt::session(fingerprint, ports, ip.toLatin1().constData(), 0);
    }

    logger->addMessage(tr("Peer ID: ") + Utils::String::fromStdString(fingerprint.to_string()));

    m_nativeSession->set_alert_dispatch(boost::bind(&Session::dispatchAlerts, this, _1));

    // Set severity level of libtorrent session
    m_nativeSession->set_alert_mask(
                libt::alert::error_notification
                | libt::alert::peer_notification
                | libt::alert::port_mapping_notification
                | libt::alert::storage_notification
                | libt::alert::tracker_notification
                | libt::alert::status_notification
                | libt::alert::ip_block_notification
                | libt::alert::progress_notification
                | libt::alert::stats_notification
                );
```

And this is the modified one:
```c++
libt::fingerprint fingerprint(PEER_ID, VERSION_MAJOR, VERSION_MINOR, VERSION_BUGFIX, VERSION_BUILD);
    const unsigned short port = pref->getSessionPort();
    std::pair<int,int> ports(port, port);
    const QString ip = getListeningIPs().first();
    int alertMask = libt::alert::error_notification
                    | libt::alert::peer_notification
                    | libt::alert::port_mapping_notification
                    | libt::alert::storage_notification
                    | libt::alert::tracker_notification
                    | libt::alert::status_notification
                    | libt::alert::ip_block_notification
                    | libt::alert::progress_notification
                    | libt::alert::stats_notification
                    ;

    if (ip.isEmpty()) {
        logger->addMessage(tr("qBittorrent is trying to listen on any interface port: %1", "e.g: qBittorrent is trying to listen on any interface port: TCP/6881").arg(QString::number(port)), Log::INFO);
        m_nativeSession = new libt::session(fingerprint, ports, 0, alertMask);
    }
    else {
        logger->addMessage(tr("qBittorrent is trying to listen on interface %1 port: %2", "e.g: qBittorrent is trying to listen on interface 192.168.0.1 port: TCP/6881").arg(ip).arg(port), Log::INFO);
        m_nativeSession = new libt::session(fingerprint, ports, ip.toLatin1().constData(), 0, alertMask);
    }

    logger->addMessage(tr("Peer ID: ") + Utils::String::fromStdString(fingerprint.to_string()));

    m_nativeSession->set_alert_dispatch(boost::bind(&Session::dispatchAlerts, this, _1));
```

With the modified one I don't even get portmap alerts for the initial ports. With the unmodified one I do get them.
As for the original problem: Could it be that setting my alert dispatch function is too late to catch the initial listen alerts?

PS: I discovered another constructor discrepancy. The alert_mask type for one constructor is `boost::uint32_t` while for the other one is `int`

**Comment by sledgehammer999** [comment]
The above were tried with your patch too. Same results.

**Comment by arvidn** [comment]
what about the listen_succeeded_alert and listen_failed_alert?
if you're not popping alerts, but just relying on receiving them through the dispatch function, you're likely to loose alerts posted before you set it. The new API (in master) for this is to have a notification function instead, that's called when there is at least one new alert, and you can post it to your main loop that then pops all alerts.

**Comment by sledgehammer999** [comment]
>what about the listen_succeeded_alert and listen_failed_alert?

Not even those.

>if you're not popping alerts, but just relying on receiving them through the dispatch function, you're likely to loose alerts posted before you set it.

Ok, that could explain why I don't get the listen_succeeded_alert and listen_failed_alert.
However, it doesn't explain why after I pass the new alertmask in the constructor I fail to get portmap alerts.

**Comment by arvidn** [comment]
the portmap alerts are most likely posted in the constructor, and by the time it returns they're already on the alert queue.

actually, I would expect setting the dispatch function to also drain the queue, perhaps that's not working correctly

**Comment by arvidn** [comment]
I don't experience any of these problems in client_test (when patching it to pass in the listen_interface, port range and alert_mask to the session constructor). It's possible it has to do with the alert dispatch function (client test does not use that, but just polls regularly). I looked at the code in alert_manager::set_dispatch_function and it looks right, it should pop all alerts currently queued and pass them to the dispatch function. (maybe you could step into that function and see what happens for you, and maybe set breakpoints in the alert constructors that you'd expect to receive and see if they're constructed at all). If the alerts are not constructed, that implies the alert mask isn't updated early enough.

Can you think of any other distinguishing factor that may be tied to the issues you're seeing?

**Comment by sledgehammer999** [comment]
Later I'll try to break inside alert_manager::set_dispatch_function this is a first for me so I may not succeed.
I can try this on linux too. So, until I try it, if you have instructions for gdb please tell me.

**Comment by arvidn** [comment]
assuming you have libtorrent built with debug symbols (and with the source still present where it was built from).

(gdb) break libtorrent::alert_manager::set_dispatch_function

sometimes the debug information is not perfectly aligned with the code and you may have to set the breakpoint on a file and line instead:

(gdb) break alert_manager.cpp:77

in visual studio you can do the same thing, in the breakpoints pane there's a "new breakpoint" menu and "add function breakpoint" (or something like that) and you can enter the name of the function to break on. You can also just open the file in the IDE and set the breakpoint on the appropriate line.

**Comment by sledgehammer999** [comment]
Tried on linux since it is easier for me to correctly setup the debugger.
Installed dbg symbols of 1.0.6 from Debian's repo.
`break libtorrent::listen_succeeded_alert::listen_succeeded_alert` -> doesn't break
`break libtorrent::listen_failed_alert::listen_failed_alert` -> doesn't break
`break libtorrent::portmap_alert::portmap_alert` -> doesn't break
`break libtorrent::portmap_error_alert::portmap_error_alert` -> doesn't break
`break libtorrent::external_ip_alert::external_ip_alert` -> breaks (just to confirm that my breaks worked).

Also the listen_succeeded_alert actually breaks if while running qbt I tell it to call listen_on() with the same interface.

**Comment by sledgehammer999** [comment]
I am sorry. I hope you didn't see my above comment. Please disregard it. Due to tiredness, I forgot to pass the correct alertmark to the constructor. I'll repeat the test tomorrow and post my results.

**Comment by sledgehammer999** [comment]
Aaaand I made you look at your code baffling yourself for no reason.
Initial problem was that I wasn't passing the correct alert_mask to the constructor. The second problem(and stupidest) was that I was passing it in the wrong sequence. Namely I was passing it in place to the `flags` parameter.
Closing this. Sorry for wasting your time.
Offtopic: I don't know the situation in master but you should consider finetuning the enum for "flags". ie one flag per feature.
