### ISSUE TITLE
How to use torrent_alert correctly?

### ISSUE THREAD

**Issue by Krakean** [arvidn/libtorrent#2460]
**Please provide the following information**

libtorrent version (or branch): master

platform/architecture: Windows 8.1 x64

compiler and compiler version: VS 2017.4

Hello.
I have this code:
```
void TorrentSession::ReadAndHandleTorrentAlerts(const lt::alert *a)
{
    lt::sha1_hash hash = lt::alert_cast<lt::torrent_alert>(a)->handle.info_hash();
    TorrentHandle* torrent = m_torrents[hash];
    if (torrent)
        torrent->HandleAlert(a);
}
```

On this line:
    `lt::sha1_hash hash = lt::alert_cast<lt::torrent_alert>(a)->handle.info_hash();`

But on compile I have an error:
```
1>...libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\alert.hpp(292): error C2039: 'alert_type': is not a member of 'libtorrent::torrent_alert'
1>...libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\alert_types.hpp(73): note: see declaration of 'libtorrent::torrent_alert'
1>...libtorrent-wrapper\torrentsession.cpp(331): note: see reference to function template instantiation 'const T *libtorrent::alert_cast<libtorrent::torrent_alert>(const libtorrent::alert *)' being compiled
1>        with
1>        [
1>            T=libtorrent::torrent_alert
1>        ]
1>...libtorrent-wrapper\3rdparty\libtorrent\include\libtorrent\alert.hpp(292): error C2065: 'alert_type': undeclared identifier
```
What I do wrong? Didn't found any example of torrent_alert usage in examples/tests.

**Comment by arvidn** [comment]
This is a limitation of how ``alert_cast`` is implemented. It only supports casting to concrete types, not base classes. If you were casting to ``torrent_added_alert``, for instance, it would work.

**Comment by Krakean** [comment]
So, how can I get the common torrent_alert then? Or filter all torrent_alert-only related alerts (that belongs to torrent_handle) to send them to my TorrentHandle class?

**Comment by Krakean** [comment]
I wanted to do it this way (via static_cast):
...
TorrentHandle *const torrent = m_torrents.value(static_cast<libt::torrent_alert*>(a)->handle.info_hash());
...

as, at least, libtorrent v1.0 allow to do (and work fine). But it's not possible with v1.2/current master.
So curious how can I get torrent_alert then...

**Comment by arvidn** [comment]
The way to get the ``torrent_alert`` is to either implicitly cast a concrete typed object to it, or use ``dynamic_cast<>``.

Even in libtorrent-1.0 ``alert_cast`` has this limitation, it just compiles and silently fail instead. See [the implementation](https://github.com/arvidn/libtorrent/blob/RC_1_0/include/libtorrent/alert.hpp#L302).

**Comment by arvidn** [comment]
earlier versions of libtorrent implemented ``alert_cast`` as just an alias for ``dynamic_cast``, so it probably worked earlier (perhaps early versions of 1.0, my link is to head of the 1.0 release branch)
