### ISSUE TITLE
Problem with no ignoring ENOBUFS in ip_change_notifier_impl

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#2467]
libtorrent: `master`
platform: `android` (possible `linux` too)

I detected (and experienced) a problem with the fact that `ENOBUFS` is not treated like an error. At one point a phone started to send `ENOBUFS` endlessly, sending the CPU to 100% and making the entire phone unusable.

I discovered the flag `NETLINK_NO_ENOBUFS` but I couldn't find a way to create a custom option for `basic_raw_socket`.

Ideas? @ssiloti? (btw, this is only part of a bigger problem)

**Comment by arvidn** [comment]
can you point to the code that ignores ``ENOBUFS``? I would expect it to try to allocate a larger buffer or something, no?

**Comment by arvidn** [comment]
by "flag", do you mean socket option? the way to set custom socket options is [this](https://github.com/arvidn/libtorrent/blob/master/include/libtorrent/socket.hpp#L124).

**Comment by aldenml** [comment]
This is the code: https://github.com/arvidn/libtorrent/blob/master/src/ip_notifier.cpp#L108
```cpp
		// Linux can generate ENOBUFS if the socket's buffers are full
		// don't treat it as an error
		if (ec.value() == boost::system::errc::no_buffer_space)
			cb(error_code());
		else
			cb(ec);
```
and if I understood correctly, the ENOBUFS problem is not in the buffer client, but in the buffer inside netlink.

And yes, a custom socket option like the one you linked, I don't know what to put in `level` and `name`.

**Comment by ssiloti** [comment]
`level` should be set to `SOL_NETLINK` and `name` should be `NETLINK_NO_ENOBUFS`. See the [man page](http://man7.org/linux/man-pages/man7/netlink.7.html) for netlink, specifically the section on socket options.

**Comment by aldenml** [comment]
thanks, I will use that

**Comment by aldenml** [comment]
See https://github.com/arvidn/libtorrent/pull/2475
