### ISSUE TITLE
A way to get the currently listening interface

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#247]
Now we can query for the listening port, but not the listening interface. Is it possible to add such a feature?

I suppose if the dev passed `0` as interface then you might have ended up listening to multiple interfaces (0.0.0.0 and ::). So I guess the return value should be a list of addresses.

**Comment by Falcosc** [comment]
@sledgehammer999 I don't understand the use of it. Because users could define a specific address over listen_interfaces.

**Comment by sledgehammer999** [comment]
Since we can query which port we use, why not have the possibility to query which interface is used too? It is a minor usability improvement.

Also you might have missed the relevant alert(or  didn't connect at all to alerts).

I admit there isn't a strong use case here. I just thought that interface and port go hand-in-hand.

**Comment by arvidn** [comment]
sorry, I must have missed this back then. I think the alerts are the best way for this. the `listen_interfaces` setting can be queries too, but it's obviously not authoritative.
