### ISSUE TITLE
Overall upload speed in client_test is empty in libtorrent-1_1_5

### ISSUE THREAD

**Issue by dmxraj** [arvidn/libtorrent#2473]
libtorrent version (or branch): 
tag: libtorrent-1_1_5

platform/architecture:
ubuntu

compiler and compiler version:
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

Steps:
1. compile example/client_test.cpp
2. Run client_test.
3. Issue is: As seen below overall upload speed is empty. But torrent upload speed is 13.4kB/s.
```
[all][downloading][non-paused][seeding][queued][stopped][checking][loaded]
 #   Name                                               Progress                            Download          Upload            Peers (D:S) DowL0  
 ABCD.DEFG.HHHHH.PPPPP-TITLE                        downloading (0.3%)                   422kB/s ( 4.6MB) 13.4kB/s (13.5kB)     2:13     4.5MB        S






 fail:        down:  421kB/s ( 4.6MB)   bw queue:   0 |   0 conns:  15  unchoked:  0 /  1                                       
waste:          up:          (      ) disk queue:   0 | 136 cache w:  94% r:   0% size: w:  2.2MB r:  2.3MB total:  4.5MB       
cache: MRU: 1 (0)                                                                                                              |
[▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌]

```

**Comment by arvidn** [comment]
off the top of my head, my guess is that the per-torrent rates includes protocol overhead and possibly IP/TCP/uTP headers, whereas the global rates only count payload transfers.

**Comment by dmxraj** [comment]
Overall download rate is 421kB/s, which is taking download speed of all the torrents (i.e 422kB/s) into account.
Similarly, I think the Overall upload rate should also take upload speed of all the torrents(i.e 13.4kB/s ) into account. But it is empty.

**Comment by arvidn** [comment]
are you suggesting that the total rates should also include protocol overhead?
or are you suggesting that the total and per-torrent be consistent, regardless of which one is chosen?

**Comment by dmxraj** [comment]
I don't know enough to suggesting anything. I think u know better than me.
But I feel that consistency is missing here.

**Comment by arvidn** [comment]
yes, I agree. it should be consistent

**Comment by arvidn** [comment]
addressed here: https://github.com/arvidn/libtorrent/pull/2592
