### ISSUE TITLE
Sync torrent_handle::file_priorities and add_torrent_params::file_priorities

### ISSUE THREAD

**Issue by vktr** [arvidn/libtorrent#2480]
I noticed that the `torrent_handle` works with file priorities as regular `int`s, and the `add_torrent_params` struct has them as `uint8_t`. Is there a reason for this? Or would changing one to match the other be a good idea?

**Comment by aldenml** [comment]
I always I had the same doubt

**Comment by arvidn** [comment]
it would be a good idea. in fact, it's on my todo list to make priority its own type, to strengthen the type safety further
