### ISSUE TITLE
are ARM tests correct?

### ISSUE THREAD

**Issue by arvidn** [arvidn/libtorrent#2485]
**Please provide the following information**

libtorrent version (or branch): master

platform/architecture: arm64
compiler and compiler version: gcc

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

When building and running the tests on arm64 on doozer.io, some arm specific asserts fail.

@aldenml do you have any insight here?

see the [build log](https://storage.googleapis.com/doozer/artifacts/up/Gbe64Wdf/buildlog?GoogleAccessId=buildmaster%40doozer-151515.iam.gserviceaccount.com&Expires=1509062592&Signature=SoSluKQX3cvunK40jgETvTld%2BEKgMwskYU3xvAyZort0F5SBAg9A6cjnQ2sjjGmI6%2FcMq7oJ%2FiVICs5vAD5vUnaMEo50miUIIBd%2FiUuDvKlUZYx0GvISMzERccRQvydZwBX27oX7wrI8LpD3MRikb%2BAeY7AhPIa%2BeHbRAgmG0e5g9L9bAggeo%2BjmTXqAe5kXc30tSkutCPFj1iCDvDojuKlkFK6%2Fn57rEW0OFMgRufu6wlbzBYTrQqIoEOq0LvSVsDqR7rAKM4JRpKwLiuN1j4q95YP%2BUoV3hwBE4pJ8yYKts2WuxSVntfhIlzuWtZyfbVaSpA077AKAEO7Qx0aJEw%3D%3D).

**Comment by aldenml** [comment]
I imagine you mean `master`. For what I see there is no neon support on that emulation environment. Do you know what exactly are they using for arm?

**Comment by arvidn** [comment]
yes, I do mean master. i was confused because [this](https://doozer.io/arvidn/libtorrent/builds) says 1_1_5, not sure why.

There is very little documentation about the arm environment. what I wonder is whether the tests should assert that neon (for instance) is supported in the environment they're run. wouldn't it make more sense to run neon tests *only* if neon is supported?

**Comment by aldenml** [comment]
that code of `neon` and `crc32` were tricky to get it right and test, if you disable them for arm tests when no support in CPU, I'm worried about the actual coverage. I think you should resort to the same hack as in travis with qemu. What do you think?
