### ISSUE TITLE
crash libtorrent::part_file::readv

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#2489]
libtorrent version (or branch): master
platform/architecture: windows
compiler and compiler version: vc++2017

13+16 crash dump :-(
https://drdump.com/Problem.aspx?ProblemID=338340&login=guest
https://drdump.com/Problem.aspx?ProblemID=338265&login=guest

possibly after 
https://github.com/arvidn/libtorrent/commit/1ce3483a9e726e780c155911490799e171869874
help?

![default](https://user-images.githubusercontent.com/920705/32145602-68f42212-bcdc-11e7-97f5-2adf2a4617c1.png)

**Comment by arvidn** [comment]
@aldenml do you think we missed a case of where priority may be set to zero? what about the constructor?

**Comment by aldenml** [comment]
definitely some missing case, looking at it at this moment

**Comment by aldenml** [comment]
@pavel-pimenov I think this issue is already fixed in `master`
