### ISSUE TITLE
Fix travis CI jobs

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#2492]
libtorrent: `master`

Opening this issue just to document that two of them are failing consistently.

For `arch=arm toolset=gcc-arm`, the problem seems in the `debootstrap` first step installation process.

**Comment by arvidn** [comment]
this should fix the ssl test. https://github.com/arvidn/libtorrent/pull/2494

**Comment by aldenml** [comment]
I'm searching for a solution of the `debootstrap` problem, but still nothing

**Comment by aldenml** [comment]
as an update, tried a lot of different things and nothing, there seems to be a problem in the extract phase of `debootstrap`. Using `strace` to debug, but I'm lost in the output.

**Comment by aldenml** [comment]
Now that `doozer` is integrated, I will give it a try and try to move the `neon` tests to there

**Comment by aldenml** [comment]
Fixed with https://github.com/arvidn/libtorrent/pull/2494 and https://github.com/arvidn/libtorrent/pull/2499
