### ISSUE TITLE
Can I use pre-compiled libtorrent deb package?

### ISSUE THREAD

**Issue by Nottt** [arvidn/libtorrent#2493]
[libtorrentbuilding.log](https://github.com/arvidn/libtorrent/files/1433327/libtorrentbuilding.log)
I want to make a docker that is always on latest libtorrent version but I'm struggling to make this and don't have the long wait it takes to compile libtorrent...not only is a waste of bandwidth and disk space when installing the docker.

Is bad if I follow this : http://dev.deluge-torrent.org/wiki/Building/libtorrent

and then give the .deb file to the container to install? What would be the best way to achieve this?

Hope this is in the correct place!

If I create a docker container from ubuntu image, compile and create a .deb file of latest libtorrent, and reuse it in future dockers will I have issues?

Here is the output of my compilation 

[libtorrentbuilding.log](https://github.com/arvidn/libtorrent/files/1433328/libtorrentbuilding.log)

I plan on reusing this .deb package in my docker images... 

If I install : 

`apt install libboost-system-dev libboost-python-dev libboost-chrono-dev libboost-random-dev libssl-dev   -y`  and running `ldconfig`

Just installing my .deb package and running `python -c "import libtorrent; print libtorrent.version"` I get the expected result. Does this means it will work flawless?

**Comment by arvidn** [comment]
I don't see why it wouldn't work. You are suggesting building libtorrent in a docker container, then pack up a debian package of the built libraries (both python module and main library), and then install those binaries in a fresh (empty) docker image, right?

The purpose is to avoid having all the intermediate build files be part of your image I take it.

**Comment by Nottt** [comment]
Yes. I built it inside docker, and I'm reusing the resulting .deb file in
other empty docker images, and they are all both based from Ubuntu.

The purpose is to avoid the long time, and disk space needed to create the
container.

**Comment by Nottt** [comment]
@arvidn If pre-compiled binaries are ok why there aren't any official pre-compiled binaries?

**Comment by arvidn** [comment]
It's not really my expertise to make packages. But there are also quite a few parameters that can make the effort quite large, the binaries are only OK if they are built on/or compatible with the system you run them on. Some important parameters that come to mind:

1. Operating system
2. version of runtime library linked against
3. 32 vs. 64 bits
4. libtorrent features enabled or disabled at build time
5. package manager
6. correctly configuring pkg-config or equivalent
