### ISSUE TITLE
Loss of internet connectivity leads to permanent loss of DHT peers

### ISSUE THREAD

**Issue by waTeim** [arvidn/libtorrent#25]
It appears that under some circumstances including loss of internet causing a client to miss 2 DHT announce periods, the DHT is rendered permanently unavailable.  This happens on version 1.0.3.

**Comment by waTeim** [comment]
An update.  I think the original description is not quite accurate.  I believe it revolves around session::max_failout

>
max_failcount
the maximum times we try to connect to a peer before stop connecting again. If a peer succeeds, its failcounter is reset. If a peer is retrieved from a peer source (other than DHT) the failcount is decremented by one, allowing another try.

What would happen in a scenario in which there is a network loss and peers are collected via the DHT only.  Are failed peers removed entirely or are they kept and reconnection is prevented?

**Comment by waTeim** [comment]
Further update:

Yes, the following code is the cause (from policy.cpp)

                // if this peer has failed before, decrease the
                // counter to allow it another try, since somebody
                // else is appearantly able to connect to it
                // only trust this if it comes from the tracker
                if (p->failcount > 0 && src == peer_info::tracker)
                        --p->failcount;

So if all peers are found through the DHT (there is no tracker), and if the local peer is behind a firewall, then failcount is never increased. Thus once a peer reaches max_failcount it there is no way to increase it afterwards.  Using default values, this takes about 6 minutes 30 seconds of internet interruption before all peers have reached max_failcount.  After that *is_connect_candidate* will return false for all peers forever, and the torrent is essentially dead at that point unless some new peer joins the swarm that has never been seen before.

Changing the code to the following of course "fixes" the problem

                if (p->failcount > 0)
                        --p->failcount;

But this now means that peers from the DHT are also trusted, and that departs from the explicit intention of the above.  So my question is what is the reason for not trusting the DHT and how can this be modified to allow for pruning peers in keeping with the original while at the same time allowing for healing the torrent using *only* the DHT?

**Comment by arvidn** [comment]
Do you have any suggestion of a heuristic to detect this case and perhaps decrement everyones failcount by one and retry?

**Comment by waTeim** [comment]
I'm not sure.  Here are a few thoughts.

1. It's not useful to have a counter on the number of times the DHT has returned a peer as a candidate because you still don't know for sure and it would be too slow, you want to resume immediately upon connectivity return.

2. Loss of connectivity to the DHT root indicates an outage  because the basic assumption to DHT functionality is root availability.  When that happens, save that a general DHT loss has occurred, and then upon connectivity restoration, lift the policy tracker restriction for 30 seconds.  The DHT will be queried immediately and the candidate peer list will be returned.  Decrement will occur to everything and the normal mechanism to increment again will apply.  Outside the 30 second window old rules apply.
