### ISSUE TITLE
Don't allocate more than 2GB when compiled in 32bits

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#250]
Currently qbittorrent when built in 32bit limits the upper bound of cache the user can set to 1800MB. (This will be updated shortly to 1536MB). And leaves the rest of RAM till 2048MB to be used for the rest program memory.

However, when libtorrent cache is set to `-1` it will always try to allocate 1/8 of the available RAM. This is wrong when compiled in 32bit but running on an 64bit OS. The user can have 16GB RAM, so libtorrent tries to allocate 2GB and eventually crashes.

I propose to limit that size to 1536MB too when `-1` is passed.
Hint: We check the `__x86_64__` and `_M_X64` defines.
Hint2(from @Chocobo1): http://nadeausoftware.com/articles/2012/02/c_c_tip_how_detect_processor_type_using_compiler_predefined_macros#x86andx8664

Realted qbt bug: https://github.com/qbittorrent/qBittorrent/issues/4076

**Comment by arvidn** [comment]
Fixed in RC_1_0 and master. thanks!
