### ISSUE TITLE
socks5 failed, download can not stop working

### ISSUE THREAD

**Issue by kslr** [arvidn/libtorrent#2504]
**Please provide the following information**

libtorrent version (or branch):
1.1.5.0
platform/architecture:
deluge2.0 / ubuntu 16.04
compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
hi
I try to force terminate the proxy, deluge can still be downloaded.
force_proxy and anonymous_mode is already open

Very strange 
Is this characteristic or? Can I force to stop working?
thks

**Comment by arvidn** [comment]
did you enable the ``force_proxy`` mode?

**Comment by kslr** [comment]
Yes, I use itconfig enable.

**Comment by arvidn** [comment]
could you post a log of this happening? (enable all alerts and log them to a file)

**Comment by kslr** [comment]
Sorry, I thought of some ways, but none of the logs are available.
But I noticed that if I use “Libtorrent Defaults” there is no speed and it will stop completely.
The use of High Performance Seed, there is speed.
Is there a difference between the settings? For example, local network acceleration?

**Comment by arvidn** [comment]
perhaps ``high_performance_seed`` disables the ``force_proxy`` setting.

**Comment by kslr** [comment]
In fact, I force_proxy off in itconfig to zero speed
I guess plug-ins may have compatibility issues

Given this infrequent situation, I'm going to write a test script to restart the service.
Thank you for your help and thoughts.
