### ISSUE TITLE
Question: What is the C++ version applied in latest code? C++ 17/1x?

### ISSUE THREAD

**Issue by LiMinggang** [arvidn/libtorrent#2507]
**Please provide the following information**

libtorrent version (or branch):
latest
platform/architecture:
windows
compiler and compiler version:
msvc 14
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
I met some compiling errors while compiling libtorrent with VC 2015(MSVC 14) though I can compile 1.1.5 successfully.
Eg.
namespace libtorrent { namespace aux {

	template <typename T, std::size_t Size, typename IndexType = int>
	struct array : std::array<T, Size>
	{
		using base = std::array<T, Size>;
		using underlying_index = typename underlying_index_t<IndexType>::type;

		static_assert(Size <= std::size_t(std::numeric_limits<underlying_index>::max())
			, "size is to big for index type");

		array() = default;
		explicit array(std::array<T, Size>&& arr) : base(arr) {}

		auto operator[](IndexType idx) const ->
#if TORRENT_AUTO_RETURN_TYPES
			decltype(auto)
#else

1>C:\DEV\github\bitswash\libtorrent\include\libtorrent/aux_/array.hpp(49): error C2059: syntax error: '::'

**Comment by arvidn** [comment]
master requires C++11 features (but certain things that GCC 4.9 and msvc-14 don't support are avoided still).

appveyor build libtorrent master with msvc-14. you could look there for an example. To get assistance fixing the compilation error though, you'd probably have to post some more details about how you build, what options and build flags you use.

**Comment by LiMinggang** [comment]
Thanks for your quick response. I'll try to fix the issue by myself before bothering you. I think msvc 14 should support C++ 11.
I added all the source code directly into my VS project combined with OpenSSL 1.1.0d(upgraded to 1.1.0g today). Will give more details if I could not fix the build issue.

**Comment by Krakean** [comment]
Use VS2017.4. It compiles everything related to C++ 11/14 just fine.

**Comment by LiMinggang** [comment]
Thanks @Krakean

**Comment by LiMinggang** [comment]
@Krakean Tried VS 2017 Community, some of the bugs (in this blog http://kaba.hilvi.org/homepage/blog/vs2013.htm ) exposed. I could not fix the compiling error in other project of mine.
I included Astyle's code in my project and can compile it with 2015 but failed with 2017 at the line that vector<bool>::push_back.
	braceBlockStateStack->push_back(true);

3>ASBeautifier.cpp
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\vector(2805): error C3779: 'std::vector<bool,std::allocator<_Ty>>::push_back': a function that returns 'decltype(auto)' cannot be used before it is defined

Tried C++14 switch which didn't help

**Comment by arvidn** [comment]
that error points into the standard library. Either that is not the complete error message, or there is some deeper misconfiguration of your compiler where it's using the wrong library

**Comment by LiMinggang** [comment]
Will try small code snippet to narrow down

**Comment by arvidn** [comment]
there's a comment [here](https://github.com/arvidn/libtorrent/blob/master/include/libtorrent/config.hpp#L112) that may be relevant.

**Comment by LiMinggang** [comment]
Thanks, @arvidn , I also found Astyle has a VS2017 project. So, the issue should be introduced by my project. Will try more on it. However, still no idea about the compiling errors while working on libtorrent.
