### ISSUE TITLE
client_test: how to stop torrent?

### ISSUE THREAD

**Issue by Krakean** [arvidn/libtorrent#2509]
libtorrent version (or branch): master

Hello.
I'm a bit confused. There is ability to resume torrent, and ability to pause torrent. But how to stop it actually? 
For example, in uTorrent when torrent is paused - you do not download anything, but seed if possible. In case of 'Stop' state - no dl/upload happening, everything related to torrent is "unloaded", i.e. it became 'inactive'.
How to set 'Stop' state in libtorrent?

**Comment by arvidn** [comment]
paused in libtorrent means stopped. it will announce ``stop`` to trackers and disconnect peers.
If you want to upload but not download anything, you can set the torrent to "upload_mode"

**Comment by Krakean** [comment]
Thanks for clarification.
