### ISSUE TITLE
Help on compiling libtorrent latest with MSVC

### ISSUE THREAD

**Issue by LiMinggang** [arvidn/libtorrent#2512]
**Please provide the following information**

libtorrent version (or branch):
Latest in github 
platform/architecture:
Windows 7 X64
compiler and compiler version:
MSVC 14(Visual Studio 2015)
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
I added all the source code of libtorrent into my project based on wxWidgets 3.1 and can compile libtorrent 1.1.5 successfully.

However, I met a lot of compiling error while replacing 1.1.5 with latest code. Most of them are feature changes that I can handle without problem. There are several that I've no idea. Please give me some clue or suggestions.

My env.
X64 build
1. boost 1.65, static X64 build libs below
libboost_chrono-vc140-mt-s-1_65.lib
libboost_chrono-vc140-mt-sgd-1_65.lib
libboost_filesystem-vc140-mt-s-1_65.lib
libboost_filesystem-vc140-mt-sgd-1_65.lib
libboost_iostreams-vc140-mt-s-1_65.lib
libboost_iostreams-vc140-mt-sgd-1_65.lib
libboost_regex-vc140-mt-s-1_65.lib
libboost_regex-vc140-mt-sgd-1_65.lib
libboost_system-vc140-mt-s-1_65.lib
libboost_system-vc140-mt-sgd-1_65.lib
libboost_thread-vc140-mt-s-1_65.lib
libboost_thread-vc140-mt-sgd-1_65.lib

2. OpenSSL 1.1.0d, static X64 build with default config---I did not change anything

3. pre-defines, most from libtorrent recommendations
BOOST_ALL_NO_LIB
BOOST_ASIO_ENABLE_CANCELIO
BOOST_ASIO_DISABLE_CONNECTEX
BOOST_ASIO_HASH_MAP_BUCKETS=1021
BOOST_USE_WINAPI_VERSION=0x0601
BOOST_SYSTEM_STATIC_LINK=1
BOOST_THREAD_USE_LIB
BOOST_THREAD_BUILD_LIB=1
BOOST_MULTI_INDEX_DISABLE_SERIALIZATION
TORRENT_USE_I2P=1
TORRENT_USE_TOMMATH
TORRENT_DEBUG
TORRENT_USE_OPENSSL
TORRENT_NO_DEPRECATE
_SCL_SECURE_NO_DEPRECATE
_CRT_SECURE_NO_WARNINGS
UNICODE
_UNICODE
WIN32
_DEBUG
_WINDOWS
WIN32_LEAN_AND_MEAN
_CRT_SECURE_NO_DEPRECATE
_FILE_OFFSET_BITS=64
_WIN32_WINNT=0x0601
__USE_W32_SOCKETS
__WXMSW__
__WXDEBUG__
wxUSE_LIBPNG=1
WXVER=310
GEOIP_STATIC
USE_LIBGEOIP

Build errors:
1. Code: 
  X509_NAME* name = X509_get_subject_name(cert);

1>  session_impl.cpp
1>d:\boost_1_65_0\boost/asio/ssl/impl/rfc2818_verification.ipp(109): error C2065: 'name': undeclared identifier
No idea what's wrong, X509_NAME should be supported in default OpenSSL config

2. 
1>C:\bitswash\libtorrent\include\libtorrent/aux_/typed_span.hpp
			TORRENT_ASSERT(this->size() <= std::size_t(std::numeric_limits<underlying_index>::max()));

C:\bitswash\libtorrent\include\libtorrent/sha1_hash.hpp
		// returns an all-F digest. i.e. the maximum value
		// representable by an N bit number (N/8 bytes). This is
		// a static member function.
		static digest32 max()
		{
			digest32 ret;
			std::memset(ret.m_number, 0xff, size());
			return ret;
		}
1>C:\bitswash\libtorrent\include\libtorrent/aux_/typed_span.hpp(94): warning C4003: not enough actual parameters for macro 'max'
1>C:\bitswash\libtorrent\include\libtorrent/sha1_hash.hpp(85): warning C4003: not enough actual parameters for macro 'max'
1>C:\bitswash\libtorrent\include\libtorrent/sha1_hash.hpp(95): warning C4003: not enough actual parameters for macro 'min'
1>C:\bitswash\libtorrent\include\libtorrent/sha1_hash.hpp(85): error C2059: syntax error: '('
1>  C:\bitswash\libtorrent\include\libtorrent/sha1_hash.hpp(269): note: see reference to class template instantiation 'libtorrent::digest32<N>' being compiled
1>C:\bitswash\libtorrent\include\libtorrent/sha1_hash.hpp(85): error C2143: syntax error: missing ',' before '?'
1>C:\bitswash\libtorrent\include\libtorrent/sha1_hash.hpp(85): error C2382: 'libtorrent::digest32<N>::digest32': redefinition; different exception specifications
1>  C:\bitswash\libtorrent\include\libtorrent/sha1_hash.hpp(77): note: see declaration of 'libtorrent::digest32<N>::digest32'
1>C:\bitswash\libtorrent\include\libtorrent/sha1_hash.hpp(85): error C2059: syntax error: '?'
1>C:\bitswash\libtorrent\include\libtorrent/sha1_hash.hpp(85): error C2059: syntax error: '{'
1>C:\bitswash\libtorrent\include\libtorrent/sha1_hash.hpp(85): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>C:\bitswash\libtorrent\include\libtorrent/sha1_hash.hpp(95): error C2059: syntax error: '('
1>C:\bitswash\libtorrent\include\libtorrent/sha1_hash.hpp(95): error C2143: syntax error: missing ',' before '?'
1>C:\bitswash\libtorrent\include\libtorrent/sha1_hash.hpp(95): error C2059: syntax error: '?'
1>C:\bitswash\libtorrent\include\libtorrent/sha1_hash.hpp(95): error C2059: syntax error: '{'
1>C:\bitswash\libtorrent\include\libtorrent/sha1_hash.hpp(95): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>C:\bitswash\libtorrent\include\libtorrent/sha1_hash.hpp(77): error C2333: 'libtorrent::digest32<160>::digest32': error in function declaration; skipping function body
1>  C:\bitswash\libtorrent\include\libtorrent/sha1_hash.hpp(299): note: see reference to class template instantiation 'libtorrent::digest32<160>' being compiled

3.
		IndexType end_index() const
		{
			TORRENT_ASSERT(this->size() <= std::size_t(std::numeric_limits<underlying_index>::max()));
			return IndexType(static_cast<underlying_index>(this->size()));
		}
		static_assert(Size <= std::size_t(std::numeric_limits<underlying_index>::max())
1>C:\bitswash\libtorrent\include\libtorrent/aux_/vector.hpp(88): warning C4003: not enough actual parameters for macro 'max'
1>C:\bitswash\libtorrent\include\libtorrent/aux_/array.hpp(49): warning C4003: not enough actual parameters for macro 'max'
1>C:\bitswash\libtorrent\include\libtorrent/aux_/array.hpp(49): error C2589: '(': illegal token on right side of '::'

Thanks

**Comment by aldenml** [comment]
do you specify the use of `c++11` as a compiler flag?

**Comment by LiMinggang** [comment]
Nope. I googled a lot but find no way to do so. __cplusplus can't be redefined. Will try it.

**Comment by arvidn** [comment]
the issue with ``max`` is fundamentally that ``windows.h`` defines a macro called ``max`` by default. I've tried to mitigate this in libtorrent headers by making sure all function calls to ``std::max()`` be made like this: ``(std::max)()``, which disables macro substitution (the same thing goes for ``std::numeric_limits<>::max()``). If you see libtorrent headers where this is not done, please submit a pull request to fix them!

There's also the problem of declaring a member function called ``max``, which may be another problem. I don't know off the top of my head how to disable the macro substitution in that case.

**Comment by LiMinggang** [comment]
I may hack on this but not sure if it's a fix. Will let you review if I
made a patch.

**Comment by LiMinggang** [comment]
@arvidn Just tried to undefine the max and it works, so the root cause is just like you said. 
Simple undefine it should not be a fix although adding windows only compiling macro makes it better. 
#ifdef max
#endefine max
#endif

Hope you can find a better way to fix the issue!

**Comment by LiMinggang** [comment]
Do you have any suggestion on the OpenSSL error?

  // No match in the alternate names, so try the common names. We should only
  // use the "most specific" common name, which is the last one in the list.
 * X509_NAME** name = X509_get_subject_name(cert);
  int i = -1;

boost_1_65_0\boost/asio/ssl/impl/rfc2818_verification.ipp(109): error C2065: 'name': undeclared identifier

**Comment by arvidn** [comment]
you could also define ``WIN32_LEAN_AND_MEAN`` before including ``windows.h``. But if you're up for it, I would appreciate a patch to make libtorrent work anyway.

**Comment by LiMinggang** [comment]
Do you want me try this without the patch to undefine max?

**Comment by LiMinggang** [comment]
I tried but it did help on the compiling error related to the "max". Will add it in my project for libtorrent.

**Comment by arvidn** [comment]
I believe something along these lines would solve it too. https://github.com/arvidn/libtorrent/pull/2524

**Comment by LiMinggang** [comment]
The patch is quite simple.
I just added the lines below as a workaround  at the beginning of  libtorrent\include\libtorrent/aux_/typed_span.hpp

#if defined(_MSC_VER) && defined(max)
#undefine max
#endif

If you need a formal patch or pull request, let me know.

**Comment by LiMinggang** [comment]
Will try it

**Comment by arvidn** [comment]
I don't think it's a safe assumption that files that include ``windows.h`` aren't using the ``max`` macro. I don't think it's acceptable to undefine someone else's macro (even though it is a terrible thing to do by ``windows.h``)

**Comment by LiMinggang** [comment]
I also met the error in sha1_hash.hpp for both max and min at function definition.

		static digest32 **max**()
		{
			digest32 ret;
			std::memset(ret.m_number, 0xff, size());
			return ret;
		}

		// returns an all-zero digest. i.e. the minimum value
		// representable by an N bit number (N/8 bytes). This is
		// a static member function.
		static digest32 **min**()

**Comment by LiMinggang** [comment]
Maybe I should try to move the header files of libtorrent before I include windows.h which was introduced by wxWidgets.

**Comment by LiMinggang** [comment]
It don't work, I'm not sure if you can change the function name for max and min in class digest32 or not.

**Comment by LiMinggang** [comment]
After rename the min/max in class digest32 all libtorrent files compiled OK except the one below:
1>  session_impl.cpp
1>d:\boost_1_65_0\boost/asio/ssl/impl/rfc2818_verification.ipp(109): error C2065: 'name': undeclared identifier
1>d:\boost_1_65_0\boost/asio/ssl/impl/rfc2818_verification.ipp(112): error C2065: 'name': undeclared identifier
1>d:\boost_1_65_0\boost/asio/ssl/impl/rfc2818_verification.ipp(114): error C2065: 'name': undeclared identifier

I'm not sure what's wrong with OpenSSL. What's your config for OpenSSL?

**Comment by arvidn** [comment]
I've updated the patch. As for OpenSSL, my suspicion is that you're using a too old version, one that didn't support SNI.

**Comment by LiMinggang** [comment]
Will investigate SNI, however, I don't think my OpenSSL is too old. I used 1.1.0d and tried the latest 1.1.0g.

**Comment by LiMinggang** [comment]
Can't figure out what's happened between boost.asio and OpenSSL, the issue was solved by removed dependency of OpenSSL.
It's weird that I can compile 1.1.5 with OpenSSL but failed with latest one.

**Comment by arvidn** [comment]
one thing to keep in mind is that the .lib files changed name on windows with openssl 1.1 (iirc) to match those used on other systems (libssl and libcrypto). Perhaps you're accidentally still referring to the old files.

**Comment by LiMinggang** [comment]
Actually not. I did not use any OpenSSL api directly in the project with
libtorrent. All are from boost.asio which was introduced by libtorrent. I
disabled OpenSSL from libtorrent now.

**Comment by arvidn** [comment]
I got the impression though that you're making your own project file to build libtorrent, which means you're responsible for resolving link dependencies, such as openssl. regardless of which object file introduces the dependency.

**Comment by LiMinggang** [comment]
Finally fixed the issue. The root cause is that TORRENT_USE_OPENSSL should always work with TORRENT_USE_LIBCRYPTO on windows(not sure about linux). The native crypto would mess with OpenSSL.

**Comment by arvidn** [comment]
should there be a ``#error`` to explain unsupported configurations?
I'd be happy to merge a pull request against ``config.hpp`` to that effect.

**Comment by LiMinggang** [comment]
I don't know if libtorrent should use two macros, ie. TORRENT_USE_OPENSSL and TORRENT_USE_LIBCRYPTO for flexibility or not. Use one to enable or disable the dependency of OpenSSL might be better.

If TORRENT_USE_LIBCRYPTO  was not defined, then libtorrent would use native crypto instead, which will include wincrypt.h under windows in aux_\win_crypto_provider.hpp. wincrypt.h defined some macros, eg, X509_Name, which are conflicted with OpenSSL introduced in asio.

Is it OK to use TORRENT_USE_OPENSSL only? ie, Always use libcrypto  if user choose to use OpenSSL.

**Comment by LiMinggang** [comment]
Another issue that is not related. I used TORRENT_NO_DEPRECATE(together with _CRT_SECURE_NO_DEPRECATE and _SCL_SECURE_NO_DEPRECATE) but still a lot of warnings like below:

It seemed that fingprint is not cleaned up.
1>ip_filter.cpp
1>..\..\..\libtorrent\src\identify_client.cpp(61): warning C4996: 'libtorrent::fingerprint': was declared deprecated
1>C:\bitswash\libtorrent\include\libtorrent/fingerprint.hpp(82): note: see declaration of 'libtorrent::fingerprint'
1>..\..\..\libtorrent\src\identify_client.cpp(63): warning C4996: 'libtorrent::fingerprint': was declared deprecated
1>C:\bitswash\libtorrent\include\libtorrent/fingerprint.hpp(82): note: see declaration of 'libtorrent::fingerprint'
1>..\..\..\libtorrent\src\identify_client.cpp(69): warning C4996: 'libtorrent::fingerprint': was declared deprecated
1>C:\bitswash\libtorrent\include\libtorrent/fingerprint.hpp(82): note: see declaration of 'libtorrent::fingerprint'
1>..\..\..\libtorrent\src\identify_client.cpp(71): warning C4996: 'libtorrent::fingerprint::name': was declared deprecated
1>C:\bitswash\libtorrent\include\libtorrent/fingerprint.hpp(90): note: see declaration of 'libtorrent::fingerprint::name'
1>..\..\..\libtorrent\src\identify_client.cpp(72): warning C4996: 'libtorrent::fingerprint::name': was declared deprecated
1>C:\bitswash\libtorrent\include\libtorrent/fingerprint.hpp(90): note: see declaration of 'libtorrent::fingerprint::name'
1>..\..\..\libtorrent\src\identify_client.cpp(73): warning C4996: 'libtorrent::fingerprint::major_version': was declared deprecated
1>C:\bitswash\libtorrent\include\libtorrent/fingerprint.hpp(91): note: see declaration of 'libtorrent::fingerprint::major_version'
1>..\..\..\libtorrent\src\identify_client.cpp(74): warning C4996: 'libtorrent::fingerprint::minor_version': was declared deprecated
1>C:\bitswash\libtorrent\include\libtorrent/fingerprint.hpp(92): note: see declaration of 'libtorrent::fingerprint::minor_version'
1>..\..\..\libtorrent\src\identify_client.cpp(75): warning C4996: 'libtorrent::fingerprint::revision_version': was declared deprecated

**Comment by arvidn** [comment]
> Is it OK to use TORRENT_USE_OPENSSL only? ie, Always use libcrypto if user choose to use OpenSSL.

Currently it's possible to use ``libcrypto`` without using openssl (i.e. ``libssl``) I think that's a legitimate configuration. i.e. you get a fast SHA-1, but you don't want the SSL stuff.

**Comment by arvidn** [comment]
as for those warnings. are you building master or ``RC_1_1``?

**Comment by LiMinggang** [comment]
Yes. I understand and that's why I said "it's for flexibility". I think the "fix" should be add some warning or note for the native crypto stuff in the documents.

As for the warnings, I'm building master.
