### ISSUE TITLE
Parameters such as save_path are ignored when setting url to a magnet link

### ISSUE THREAD

**Issue by emiax** [arvidn/libtorrent#2520]
Following the first `add_torrent` example at http://www.libtorrent.org/tutorial.html:

If the url set by `atp.url = ...` is a magnet link and the torrent is added using `ses.add_torrent(atp);`,  all params (such as `save_path`) are overwritten in `session_impl.cpp:4832`, by the call to `parse_magnet_uri(params.url, params, ec);`.

The issue boils down to the fact that `void parse_magnet_uri(string_view uri, add_torrent_params& p, error_code& ec)` defined in `magnet_uri.cpp:169` is overwriting p with a new instance, ignoring old parameters.

For me this resulted in torrents always being written to the current working directory.

I noticed that usage of `url` is deprecated. Instead, `parse_magnet_uri()` should be used to acquire an `add_torrent_params` in the first place, like this:

```
libtorrent::add_torrent_params p = libtorrent::parse_magnet_uri(argv[1], ec);
p.save_path = ...;
lt::torrent_handle h = ses.add_torrent(atp);
```

Newcomers (like me) following the tutorial may be confused by this.

Thank you for reading!

libtorrent version (or branch): master as of commit d4864b8b18afeb28be0381d98eebba2b2dd737d4

**Comment by arvidn** [comment]
keep in mind that ``add_torrent_params::url`` is deprecated. The idea is that you would first set up the ``add_torrent_params`` object from ``parse_magnet_uri``, then you would set (or modify) settings.

**Comment by arvidn** [comment]
this fixes the backwards compatibility in the deprecated overload of ``parse_magnet_uri()``, to augment the ``add_torrent_params`` instead. https://github.com/arvidn/libtorrent/pull/2522

**Comment by arvidn** [comment]
and this fixes the examples (in the RC_1_1 branch). https://github.com/arvidn/libtorrent/pull/2523

thanks for the report!

**Comment by emiax** [comment]
Perfect, thank you very much for the quick response and fix!
