### ISSUE TITLE
add #pragma warning(disable:4268)

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#2527]
compiler and compiler version: VisualC++ 2015
2>Q:\vc15\r5xx\libtorrent\include\libtorrent/torrent_status.hpp(146): warning C4268: 'public: static libtorrent::aux::strong_typedef<int,libtorrent::aux::file_index_tag,void> const libtorrent::torrent_status::error_file_ssl_ctx': 'const' static/global data initialized with compiler generated default constructor fills the object with zeros (compiling source file client\ConnectionManager.cpp)

fix:
![default](https://user-images.githubusercontent.com/920705/32714794-817cec8a-c860-11e7-880b-df5e95a79996.png)

warning spam:

![default](https://user-images.githubusercontent.com/920705/32714689-0abe4d78-c860-11e7-850d-4172de9cc2c9.png)

**Comment by ssiloti** [comment]
I don't think we should be disabling that warning. It looks like either a bug in libtorrent or a bug in msvc.

**Comment by arvidn** [comment]
is it the warning that's the bug, or is the compiler actually generating the code the message indicates? i.e. does it initialize it to zeroes even when explicitly initializing it?

**Comment by ssiloti** [comment]
[This](http://lists.llvm.org/pipermail/lldb-commits/Week-of-Mon-20161205/033389.html) commit suggests that the warning itself is a bug.

**Comment by aldenml** [comment]
This was also documented in https://github.com/arvidn/libtorrent/pull/1630#discussion-diff-97934534R279
