### ISSUE TITLE
Increase in memory usage from 1.1.4 to  1.1.5

### ISSUE THREAD

**Issue by vitor-alves** [arvidn/libtorrent#2528]
libtorrent version: 1.1.5 
platform/architecture: Arch Linux x64 8GB RAM
compiler and compiler version: g++ (GCC) 7.2.0
I have installed both versions of libtorrent-rasterbar from Arch Linux repository.

Hi, I have been using libtorrent in my project and noticed a strange increase in memory usage from version 1.1.4 to 1.1.5. Looking the changelog of version 1.1.5 I don't see any change that could be responsibe for this, so decided to ask here.

Using the simple client example from http://www.libtorrent.org/examples.html#simple-client to test I get the following values when using _debian-9.1.0-s390x-netinst.iso.torrent_

Both values are measured after downloading was finished and the torrent was in seeding state. I have run the program a first time to download the torrent, closed it, then ran the program again so the torrent would be rechecked and put into seeding state.  

**In 1.1.4** 
Memory: 7,3 MiB
Shared Memory: 8,8 MiB
Resident Memory: 16,2 MiB

**In 1.1.5**
Memory: 10,4 MiB
Shared Memory: 8,8 MiB
Resident Memory: 19,2 MiB

I tested it enough times to be sure these values are correct. 

A 3,1 MiB increase is not much, but represents a 42% increase in memory consumption. That cant be ignored. I don't know what happens with a large amount of torrents, though. 

What could have caused this memory increase from 1.1.4 to 1.1.5 ?

**Comment by Seeker2** [comment]
Other, possibly related memory problems:
Memory consumption  https://github.com/arvidn/libtorrent/issues/2525
RC_1_1 uses too much memory  https://github.com/arvidn/libtorrent/issues/2251
qBitTorrent Virtual Memory Leak  https://github.com/qbittorrent/qBittorrent/issues/7531

**Comment by arvidn** [comment]
do you have a disk cache configured? If you're seeding, using more memory could be a consequence of being more effective at uploading (and populating the disk cache quicker).

There really isn't a way to tell without running a heap profiler.

**Comment by vitor-alves** [comment]
I will do some tests with disk cache and a memory profiler and report back asap

**Comment by vitor-alves** [comment]
You are right, Arvid. The disk cache was the cause. 
With disk cache disabled the memory usage is exactly the same in 1.1.4 and 1.1.5. The total amount of memory allocations, as expected, is similar with disk cache disabled. With disk cache enabled there are many more allocations in 1.1.5, but nothing to worry about. 
I think a9524550d78a72acd157d16308d41dff976f55ab might be related to this,but I am not sure.

Its just the cache that is behaving differently in 1.1.5, so feel free to close the issue, Arvid.

**Comment by Col-blimp** [comment]
It does not address this https://github.com/arvidn/libtorrent/issues/2525 though as disk cache is removed from master, for whatever reason VS memory diagnostics is failing on Win 10 with Libtorrent and Dr Memory doews not work on Win 10 so anyone know of a decent profiler for Win 10?

**Comment by vitor-alves** [comment]
Try MTuner
https://github.com/milostosic/MTuner

**Comment by arvidn** [comment]
i would have expected visual studio to have an integrated heap profiler

**Comment by Col-blimp** [comment]
It does, was trying it with a 200mb torrent and it fails/crashes, working with a 20mb one though.
