### ISSUE TITLE
Installing python-libtorrent in Ubuntu

### ISSUE THREAD

**Issue by aleksas** [arvidn/libtorrent#2533]
**Please provide the following information**

libtorrent version (or branch):
python-libtorrent (1.0.7-1build1)
python3-libtorrent (1.0.7-1build1)

platform/architecture:
OS: Ubuntu 16.04.3 LTS
CPU: amd64

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Installing libtorrent on ununtu using apt-get does not enable python binding.
`import libtorrent`
causes :
> ModuleNotFoundError: No module named 'libtorrent'

Relevant output for **sudo apt-get install python-libtorrent**
> ...
> The following additional packages will be installed:
>   libboost-python1.58.0 libtorrent-rasterbar8
> Suggested packages:
>   libtorrent-rasterbar-dbg
> The following NEW packages will be installed:
>   libboost-python1.58.0 libtorrent-rasterbar8 python-libtorrent
> 0 upgraded, 3 newly installed, 0 to remove and 95 not upgraded.
> Need to get 0 B/1.462 kB of archives.
> After this operation, 5.597 kB of additional disk space will be used.
> Do you want to continue? [Y/n] Y 
> Selecting previously unselected package libtorrent-rasterbar8.
> (Reading database ... 272662 files and directories currently installed.)
> Preparing to unpack .../libtorrent-rasterbar8_1.0.7-1build1_amd64.deb ...
> Unpacking libtorrent-rasterbar8 (1.0.7-1build1) ...
> Selecting previously unselected package libboost-python1.58.0.
> Preparing to unpack .../libboost-python1.58.0_1.58.0+dfsg-5ubuntu3.1_amd64.deb ...
> Unpacking libboost-python1.58.0 (1.58.0+dfsg-5ubuntu3.1) ...
> Selecting previously unselected package python-libtorrent.
> Preparing to unpack .../python-libtorrent_1.0.7-1build1_amd64.deb ...
> Unpacking python-libtorrent (1.0.7-1build1) ...
> Processing triggers for libc-bin (2.23-0ubuntu9) ...
> Setting up libtorrent-rasterbar8 (1.0.7-1build1) ...
> Setting up libboost-python1.58.0 (1.58.0+dfsg-5ubuntu3.1) ...
> Setting up python-libtorrent (1.0.7-1build1) ...
> Processing triggers for libc-bin (2.23-0ubuntu9) ...

 
Relevant output for **sudo apt-get install python3-libtorrent**

> Get:1 http://lt.archive.ubuntu.com/ubuntu xenial/universe amd64 python3-libtorrent amd64 1.0.7-1build1 [264 kB]
> Fetched 264 kB in 0s (952 kB/s)            
> Selecting previously unselected package python3-libtorrent.
> (Reading database ... 272680 files and directories currently installed.)
> Preparing to unpack .../python3-libtorrent_1.0.7-1build1_amd64.deb ...
> Unpacking python3-libtorrent (1.0.7-1build1) ...
> Setting up python3-libtorrent (1.0.7-1build1) ...

**Comment by arvidn** [comment]
this sounds more like a packaging issue. the python binding builds and is tested on travis.
However, the version you're referring to is quite old, it's possible python 3 wasn't fully supported in it.
