### ISSUE TITLE
part file remains open after remove_torrent()

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#2534]
libtorrent version (or branch): master

Seems the problem is back. Recently, the part file remains open for some time after remove_torrent() has been called so that it cannot be deleted right after the call to remove_torrent().

I would prefer that libtorrent would delete the part file, maybe controlled by a flag for remove_torrent().

**Comment by arvidn** [comment]
all files remain open after ``remove_torrent()`` is called. Removing (including deleting files) is asynchronous.

There is already a flag to ``remove_torrent()`` to remove the partfile, it's called ``session::delete_partfile``. That is also asynchronous though.

**Comment by MassaRoddel** [comment]
Thank you, I didn't know that yet.
