### ISSUE TITLE
Question about LTO and macOS slow binaries

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#2539]
libtorrent: `master`

I'm asking here to see if anyone has experience compiling `libtorrent` as a shared library for macOS + clang with LTO enabled.

My results is that with Xcode 7.3, the binary is extremely slow (downloading, destructing the session, everything). With Xcode 9.1 it's like 5X faster, but still very slow. Thanks

**Comment by arvidn** [comment]
it's slow relative a shared library on macOS built without LTO?

**Comment by aldenml** [comment]
yes, without LTO, it behaves like I always expected (fast and achieving high transfer speeds), but with LTO, it's like unusable, it takes ages to even destruct the session.

**Comment by aldenml** [comment]
Closing this until I have more information about it
