### ISSUE TITLE
Drop std::auto_ptr usage for c++11

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#254]
In qbt we have switched to using c++11 and gcc complains about the deprecated use of `std::auto_ptr` which comes from libtorrent's functions.

Could you eliminate this in git master?

**Comment by arvidn** [comment]
do you have any examples of (non-deprecated) APIs that still use auto_ptr in master?

**Comment by sledgehammer999** [comment]
@ngosang can you grep the includes from libtorrent's master and tell if you can find something non-deprecated using std::auto_ptr ?

**Comment by ngosang** [comment]
I'm using libtorrent 1.0.6 to build qBittorrent. If this warnings are already fixed with libtorrent master branch you can close this issue.
