### ISSUE TITLE
Hang on exiting

### ISSUE THREAD

**Issue by LiMinggang** [arvidn/libtorrent#2541]
**Please provide the following information**

libtorrent version (or branch):
Latest git
platform/architecture:
Windows 7 X64
compiler and compiler version:
VS2017(msvc 14.1 )
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
No exact steps to reproduce it. It happened randomly while exiting the application which is simply a BT client based on libtorrent with GUI. The client code is mostly from the client_test example.

The GUI of the application was destroyed but the process still could be found in process explorer. Furthermore it could not be killed by the process explorer. It would exit only if the computer was shutdown.

Do you have any suggestion for me to dig? I did not try to get the stack trace because it happened randomly on my release build and too many threads running.

**Comment by LiMinggang** [comment]
Someone said in stackoverflow:
To summarise, it's quite possible it is due to unprocessed I/O requests that hasn't been handled properly (by a device driver your program has possibly accessed)
https://blogs.technet.microsoft.com/markrussinovich/2005/08/17/unkillable-processes/

**Comment by arvidn** [comment]
at least historically, a recurring problem I've had is that some asynchronous operations are still outstanding when shutting down (either preventing shutdown or significantly delays it while timing out).

if you build libtorrent with ``TORRENT_ASIO_DEBUGGING`` defined, shutdown will print debug information to ``stdout``, indicating which operations are holding up shutdown.

**Comment by LiMinggang** [comment]
Tried more than 10 times to reproduce but failed. Will keep observing. Close it now.
