### ISSUE TITLE
Question about thread affinity

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#2543]
libtorrent: `master`

I was recently reading about this in more detail, and I was wondering if this is something that could improve somehow the performance under heavy load. Or is it that the data move pattern get in the way to achieve meaningful results? any previous thoughts?

**Comment by arvidn** [comment]
the main purpose of the disk threads (which is the most threaded part of libtorrent) is to not block other parts of the program from making progress while waiting for a blocking disk operation. in this sense I have a hart time seeing how any thread affinity might help. there may be other, deeper architectural changes that may help take advantage of NUMA systems though.

here's my expectation of the ranking of expensive things libtorrent does:

1. sha-1 hash
2. memcopy to/from kernel when reading/writing sockets
3. memcopy to/from kernel when reading/writing files on disk

**Comment by aldenml** [comment]
👍
