### ISSUE TITLE
Asserting when disabled DHT and LSD service to download content uses magnet link

### ISSUE THREAD

**Issue by ishirshov** [arvidn/libtorrent#2547]
version: 1.1.5.0-37ffe99a1

file: '../include/libtorrent/file_storage.hpp'
line: 404
function: int libtorrent::file_storage::num_pieces() const
expression: m_piece_length > 0

stack:
1: assert_fail(char const*, int, char const*, char const*, char const*, int)
2:
3: libtorrent::peer_connection::send_allowed_set()
4: libtorrent::bt_peer_connection::on_interested(int)
5: libtorrent::bt_peer_connection::dispatch_message(int)
6: libtorrent::bt_peer_connection::on_receive_impl(unsigned long)
7: libtorrent::bt_peer_connection::on_receive(boost::system::error_code const&, unsigned long)
8: libtorrent::peer_connection::receive_data_impl(boost::system::error_code const&, unsigned long, int)
9: libtorrent::peer_connection::on_receive_data_nb(boost::system::error_code const&, unsigned long)
10:
11:
12:
13:
14: clone

**Comment by arvidn** [comment]
do you hit this assert consistently under those two conditions you mention?

**Comment by ishirshov** [comment]
yes, every time when I enable this two conditions

**Comment by arvidn** [comment]
I believe this fixes it: https://github.com/arvidn/libtorrent/pull/2557

**Comment by ishirshov** [comment]
seems bug fixed. Thanks!
