### ISSUE TITLE
TORRENT_PRODUCTION_ASSERTS

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#2553]
If you build with:

`"--hash toolset=msvc-14.1 boost-link=static asserts=production address-model=64 runtime-link=static deprecated-functions=off encryption=on crypto=openssl link=static dht=on logging=on i2p=on variant=release"`

you get `asserts.log` available but because `TORRENT_USE_ASSERTS` is not used nor defined as you only want production asserts you are unable to access `char const* libtorrent_assert_log = "asserts.log";` to set the log file path.

**Comment by arvidn** [comment]
is this with master or RC_1_1?

**Comment by Col-blimp** [comment]
Master I'm using but I believe this happens with all branches.

**Comment by arvidn** [comment]
it looks like it would work in RC_1_1, since TORRENT_USE_ASSERTS is set if TORRENT_RELEASE_ASSERTS is set, which is set by <asserts>production.

**Comment by arvidn** [comment]
``TORRENT_USE_ASSERTS`` is defined right [here](https://github.com/arvidn/libtorrent/blob/master/Jamfile#L431).

does it not show up on your compiler command line?

**Comment by Col-blimp** [comment]
The `libtorrent.lib` builds without errors and works as expected but on the project side of things `libtorrent/assert.hpp` is included but `extern char const* libtorrent_assert_log;` is not available because VS does not look beyond line [71](https://github.com/arvidn/libtorrent/blob/ee1f4aa129b27f9231cc8160b500aa7da9d91be5/include/libtorrent/assert.hpp#L71),  if I move [74](https://github.com/arvidn/libtorrent/blob/ee1f4aa129b27f9231cc8160b500aa7da9d91be5/include/libtorrent/assert.hpp#L74) to 69 all is well, I take it Im doing something wrong here?

**Comment by arvidn** [comment]
ah, I see. could it be a missing ``__declspec(dllexport)``?

**Comment by arvidn** [comment]
does this fix it? https://github.com/arvidn/libtorrent/pull/2562

**Comment by Col-blimp** [comment]
It does, ta.
