### ISSUE TITLE
Dynamic loading of torrent files

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#2560]
[Dynamic loading of torrent files](http://www.libtorrent.org/manual-ref.html#dynamic-loading-of-torrent-files) seems to be depreciated in master as `set_load_function` is gone, is there an alternative system for unloading torrents?

**Comment by arvidn** [comment]
yes, you can implement a plugin that gets a chance to add torrents on demand when peers connect.

**Comment by Col-blimp** [comment]
How come it was depreciated?

**Comment by arvidn** [comment]
the feature of unloading of torrents was very complicated and error prone. This was the main reason to deprecate and remove it.

On top of that, it didn't solve the problem it was meant to solve in a particularly efficient way. the problem being able to seed millions of (mostly inactive) torrents, similar to how a web server can host millions of files with no problem.
The problem with unloading torrents was that there was still some state loaded about them. The parts that were unloaded was the disk cache and the meta info file. That's normally is the bulk of the memory used by a torrent, but it's not all of it. There was still the torrent object (which is a bit over 1 kiB). The file_storage mostly works by referencing the meta info file, so there were some special cases in there to store some metadata like the number of files and number of pieces, when unloaded. they were just used in too many places.
