### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by mattias197711** [arvidn/libtorrent#2567]
**Please provide the following information**

libtorrent version (or branch):
RC_1_1 and master

platform/architecture:
Linux media 4.14.0-041400rc6-generic #201710230731 SMP x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 17.04

compiler and compiler version:
gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

i've git clone https://github.com/arvidn/libtorrent and downloaded libtorrent-rasterbar-1.1.5.tar.gz

i have tried alot of diffrent things.

bootstrap.sh / autotool.sh / configure
configure: with varius options.
./configure
--with-libiconv --enable-python-binding
--with-libiconv --with-boost=yes --enable-python-binding --enable-encryption --enable-dht 
--with-boost-python --with-libiconv --enable-python-binding
--enable-python-binding --enable-encryption --enable-dht --enable-logging --with-libiconv --enable-dependency-tracking --enable-deprecated-functions --enable-debug=yes
--enable-python-binding --enable-encryption --enable-dht --enable-logging --with-boost-libdir=/usr/lib/x86_64-linux-gnu --with-libiconv --enable-dependency-tracking --enable-deprecated-functions --enable-debug=yes
--enable-python-binding --enable-encryption --enable-dht --enable-logging --with-boost-libdir=/usr/lib/x86_64-linux-gnu --with-libiconv --enable-dependency-tracking --enable-deprecated-functions --with-boost-random=lib
--enable-python-binding --enable-encryption --enable-dht --enable-logging --with-boost-libdir=/usr/lib/x86_64-linux-gnu --with-libiconv --enable-dependency-tracking --enable-deprecated-functions --with-boost-random=lib

and probably some other variasions.
think one time configure didnt work with on of the tests.

[https://pastebin.com/58rS8yZL](url)

useing bootstrap:
https://pastebin.com/FzZz6Uyc

python setup.py build:
https://pastebin.com/3AizPH7G

tried with b2/bjam
get alot of: "failed gcc.compile"

https://pastebin.com/a82GS6RL

i'm probably missing something very easy.
i have build boostorg-boost and boost_1_65_1
but on configure i see: 
Checking for boost libraries:
checking for boostlib >= 1.53... yes

**Comment by arvidn** [comment]
there are some questionable things I do that broke with the latest version of boost. I will fix them. in the short term, you could try boost-1.64 instead.

**Comment by arvidn** [comment]
you say you're using boost 1.65.1, but this line:

`` typedef io_context io_service;``

does not exist in the ``io_service.hpp`` in boost.1.65.1.

**Comment by arvidn** [comment]
I see, you're building against boost head

**Comment by arvidn** [comment]
could you try this? https://github.com/arvidn/libtorrent/pull/2570

**Comment by LiMinggang** [comment]
boost_1_65_0 is OK with latest on Windows 7 VS 2017

**Comment by mattias197711** [comment]
i'll give it a try. both with 1.64 and 1.65 and see what happens.

i was sure it was more me doing something wrong then anything else :)

**Comment by mattias197711** [comment]
dont get me wrong now. but bak in the 90's there was only 1 source to compile.
been away from this almost 10 years but i'll find my way bak to the new world :)

**Comment by mattias197711** [comment]
i used boost-1.66-compat branch with #define BOOST_LIB_VERSION "1_65"
this try and no errors with libtorrent.

will do some testing with boost-1.66 and 1.55 with master branch just for fun.

thx for the help.

**Comment by arvidn** [comment]
merged into RC_1_1
