### ISSUE TITLE
Implement BEP 53 - Magnet URI extension - Select specific file indices for download

### ISSUE THREAD

**Issue by dessalines** [arvidn/libtorrent#2572]
Here's the [link to the BEP 53](http://www.bittorrent.org/beps/bep_0053.html). 

Libtorrent's `add_torrent_params::parse_magnet_uri` would need to be able to parse file indices in the following format:

`magnet:?xt=urn:btih:HASH&dn=NAME&tr=TRACKER&so=0,2,4,6-8`

**Comment by arvidn** [comment]
In master this would be a fairly simple patch, since file priority is already part of the output add_torrent_params. Patches are welcome!

**Comment by aldenml** [comment]
For review https://github.com/arvidn/libtorrent/pull/2578

**Comment by dessalines** [comment]
dang that was fast!

If you'd liike to test it out with a site I'm building, here's html links:

http://torfiles.ml:4567/#/search;searchTerm=ubuntu

**Comment by arvidn** [comment]
this has been merged into master now
