### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [arvidn/libtorrent#2573]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by arvidn** [comment]
There is an old Conan branch in the repo. The original blocker was that Conan did not support boost build, but I wrote a simple generator which has been merged into Conan now.

The second problem is that I would like to retain the ability to link against dependencies not installed with Conan as well, and it’s not clear how to best do that.

As of a year ago or so, in my mind, the main value of Conan wa to get easy and portable access the OpenSSL and boost (but boost is easy to build, so mostly OpenSSL). However, I don’t get the impression those packages are as easy to find on Conan anymore.

**Comment by ZaMaZaN4iK** [comment]
Now Conan has packages for Boost in Bincrafters public-conan [repo](https://bintray.com/bincrafters/public-conan) . So you can use modular boost packages.

If you want to link with deps from e.g. OS dependency manager, yuo can just avoid step with Conan in your CMakeLists.txt

So i think you can use these packages for making recipe for the library.
