### ISSUE TITLE
write_resume_data.hpp and read_resume_data.hpp not found

### ISSUE THREAD

**Issue by gobne** [arvidn/libtorrent#2575]
**Please provide the following information**

libtorrent version (or branch): 1.1.5

platform/architecture: Linux 64bit

compiler and compiler version: gcc version 5.4.0

Hello, 
I compiled libtorrent on branch 1.1.5 but when I link it in my application, gcc can't find both of the files I mentioned above. 
The curious thing is that if I switch on master branch, I have no problems, gcc find write_resume_data.hpp and read_resume_data.hpp and everything works fine.

Can someone tell me why?

Thanks

**Comment by Col-blimp** [comment]
Its a feature of Master: https://github.com/arvidn/libtorrent/pull/1776
