### ISSUE TITLE
Peer class type filtering applies only on new connections.

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#2587]
**libtorrent version (or branch):**
1.1.5+gitf42b63c7ea

**platform/architecture:**
Windows 7 64bit / Windows XP 32bit
msvc 2017

**please describe what symptom you see, what you would expect to see instead and
how to reproduce it.**

I started debugging issues on our implementation of the old functionality provided by RC_1_0 regarding "ignore limits on lan" and "apply rate limit on μTP".

I think I fixed it for the LAN.
For μTP, I observed that the setting will apply to new connections. Is this a bug of libtorrent or limitation of how peer classes are applied? 
Note: I don't experience the same problem when testing for limiting/unlimiting LAN.

This is how I limit/unlimit μTP:
```c++
void Session::configureLimitsOnUTP()
{
    libt::peer_class_type_filter peerClassTypeFilter;
    peerClassTypeFilter.add(libt::peer_class_type_filter::tcp_socket, libt::session::tcp_peer_class_id);
    peerClassTypeFilter.add(libt::peer_class_type_filter::ssl_tcp_socket, libt::session::tcp_peer_class_id);
    peerClassTypeFilter.add(libt::peer_class_type_filter::i2p_socket, libt::session::tcp_peer_class_id);
    if (isUTPRateLimited()) {
        peerClassTypeFilter.add(libt::peer_class_type_filter::utp_socket
            , libt::session::local_peer_class_id);
        peerClassTypeFilter.add(libt::peer_class_type_filter::utp_socket
            , libt::session::global_peer_class_id);
        peerClassTypeFilter.add(libt::peer_class_type_filter::ssl_utp_socket
            , libt::session::local_peer_class_id);
        peerClassTypeFilter.add(libt::peer_class_type_filter::ssl_utp_socket
            , libt::session::global_peer_class_id);
    }
    else {
        peerClassTypeFilter.disallow(libt::peer_class_type_filter::utp_socket
            , libt::session::local_peer_class_id);
        peerClassTypeFilter.disallow(libt::peer_class_type_filter::utp_socket
            , libt::session::global_peer_class_id);
        peerClassTypeFilter.disallow(libt::peer_class_type_filter::ssl_utp_socket
            , libt::session::local_peer_class_id);
        peerClassTypeFilter.disallow(libt::peer_class_type_filter::ssl_utp_socket
            , libt::session::global_peer_class_id);
    }
    m_nativeSession->set_peer_class_type_filter(peerClassTypeFilter);
}
```
My relevant PR: https://github.com/qbittorrent/qBittorrent/pull/7974

**Testing methodology**
I run the testing build in a VM and the host OS run the official 4.0.2 x64 build. The VM acted as the leecher. I created a new torrent from local files, so I won't get polluted by external peers.
For μTP, I forced the leecher to connect only through μTP.

PS: As you can see from the way my function works, `get_peer_class_type_filter()` would help eliminate adding stuff that I don't want to reconfigure(tcp and i2p sockets).

**Comment by arvidn** [comment]
The currently logic only assign peer classes on socket creation. perhaps there should be a way to re-evaluate which peer classes sockets belong to when updating the filters.

And yes, it would make sense to have a getter for the peer class filters.
