### ISSUE TITLE
Mailing list archive links aren't working

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#2588]
From the main website the archive link correctly loads: http://dir.gmane.org/gmane.network.bit-torrent.libtorrent

But none of the links in that page work for me.
I don't know what the issue is, but in case you can't fix it you can point the initial link to the sf.net archives instead: https://sourceforge.net/p/libtorrent/mailman/libtorrent-discuss/

**Comment by arvidn** [comment]
ah, yes. gmane shut down I believe

**Comment by arvidn** [comment]
if you get a chance, please feel free to submit a PR with a fixed link. Otherwise I'll get around to it, I'm just a bit busy right now
