### ISSUE TITLE
scrape_failed_alert

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#2589]
Master.

If you were to do `hdl.scrape_tracker(-1);` then assuming you don't have an IPV6 address you will always get the  `scrape_failed_alert` and you'll get the `scrape_failed_alert` if you have an IPV6 address but the tracker is not supporting IPV6.

Is it possible to not try to scrape IPV6 if you dont have an IPV6? 

Is there anyway to tell if a tracker is IPV6 or not so you dont try to scrape IPV6 if its not?

**Comment by ssiloti** [comment]
If you know you don't have IPv6 connectivity and don't want to see those alerts you can remove `::` from the `listen_interfaces` setting. Otherwise I think it makes sense to have a consistent rule that you will get either a `scrape_reply_alert` or a `scrape_failed_alert` for each listen interface.

**Comment by Col-blimp** [comment]
IPv6 are funny as the isp does not always assign one.
