### ISSUE TITLE
[crash] libtorrent::entry::operator

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#2605]
libtorrent version (or branch): master
platform/architecture: x64
compiler and compiler version: vc++2017
https://drdump.com/Problem.aspx?ProblemID=349347&login=guest

![default](https://user-images.githubusercontent.com/920705/34072198-0a1097c0-e294-11e7-9f92-505dda258030.png)

![default](https://user-images.githubusercontent.com/920705/34072203-1cfa8904-e294-11e7-8b1a-382bf66fc873.png)

![default](https://user-images.githubusercontent.com/920705/34072205-246b015a-e294-11e7-9097-1c4816b9042e.png)

**Comment by ssiloti** [comment]
I doubt this bug has anything to do with the code in the call stack. That code doesn't depend at all on outside state so if it had a crash bug I would expect it to crash every time. This is most likely a heap corruption or some other non-local failure.

**Comment by LiMinggang** [comment]
Steps to reproduce it? I have the same env. as yours, say, master branch VS vs2017 on winx64 but never saw the issue.

**Comment by aldenml** [comment]
I have random crashes in entry operators too, but everything looks good in an `entry.cpp`'s review. My reports are from android, maybe this is another hard to find subtle bug.
