### ISSUE TITLE
Error when running on windows xp

### ISSUE THREAD

**Issue by kotbrain** [arvidn/libtorrent#2611]
Hello. I'm trying to run a program on Windows XP using libtorrent 1.1.5 (compiled via boost 1.65.1) and get the error "The entry point to the CreateSemaphoreExW procedure was not found in the KERNEL32.dll DLL.". On Windows 7+ this works fine. How can I fix this error? There is some old version with support for XP?

**Comment by kotbrain** [comment]
_WIN32_WINNT=0x0501 solved the problem

**Comment by arvidn** [comment]
just FYI, the days of Windows XP support are numbered
