### ISSUE TITLE
Deluge daemon crash

### ISSUE THREAD

**Issue by MaxKer** [arvidn/libtorrent#2614]
**Please provide the following information**

libtorrent version (or branch): 1.1.4.0-20c1407

platform/architecture:  NAS QNAP

compiler and compiler version:

Deluge installed on a NAS QNAP, QTS v4.3.4

Logs : 

file: '../include/libtorrent/stack_allocator.hpp'
line: 89
function: const char* libtorrent::aux::stack_allocator::ptr(int) const
expression: idx < int(m_storage.size())

stack:
1: assert_fail(char const*, int, char const*, char const*, char const*, int)
2: libtorrent::tracker_alert::tracker_url() const
3: libtorrent::tracker_alert::message() const
4: libtorrent::tracker_reply_alert::message() const
5: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<std::string (libtorrent::alert::*)() const, boost::python::default_call_policies, boost::mpl::vector2<std::string, libtorrent::alert&> > >::operator()(_object*, _object*)
6: boost::python::objects::function::call(_object*, _object*) const
7:
8: boost::python::handle_exception_impl(boost::function0<void>)
9:
10: PyObject_Call
11: PyEval_EvalFrameEx
12: PyEval_EvalCodeEx
13:
14: PyObject_Call
15: PyEval_EvalFrameEx
16: PyEval_EvalCodeEx
17: PyEval_EvalFrameEx
18: PyEval_EvalCodeEx
19: PyEval_EvalFrameEx
20: PyEval_EvalCodeEx
21: PyEval_EvalFrameEx
22: PyEval_EvalCodeEx
23:
24: PyObject_Call
25:
26: PyObject_Call
27:
28:
29: PyObject_Call
30: PyEval_EvalFrameEx
31: PyEval_EvalCodeEx
32: PyEval_EvalFrameEx
33: PyEval_EvalCodeEx
34: PyEval_EvalCode
35:
36: PyRun_FileExFlags
37: PyRun_SimpleFileExFlags
38: Py_Main
39: __libc_start_main
40: _start

**Comment by arvidn** [comment]
This looks like a symptom of keeping a pointer to an alert around and accessing it after the next call to ``pop_alerts()``. Alert pointers are not valid after another call to ``pop_alerts()``
