### ISSUE TITLE
dht_tracker::refresh_timeout() leaks exceptions through the io_service

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#2631]
libtorrent version (or branch): master
platform/architecture: x64 - Windows build 16299
compiler and compiler version: vc++2017

https://drdump.com/DumpGroup.aspx?DumpGroupID=968162&login=guest

kernelbase!RaiseException+0x68
flylinkdc_x64!CxxThrowException+0xc2
flylinkdc_x64!libtorrent::aux::throw_ex<boost::system::system_error,boost::system::error_code>+0x34
flylinkdc_x64!libtorrent::aux::crypt_hash<32772,1>::create+0xa7
flylinkdc_x64!libtorrent::dht::generate_random_id+0x4f
flylinkdc_x64!libtorrent::dht::node::send_single_refresh+0x10c
flylinkdc_x64!libtorrent::dht::node::tick+0x328

![default](https://user-images.githubusercontent.com/920705/34363495-a532f51c-ea8d-11e7-9d9e-4490dca470a0.png)

help?

**Comment by aldenml** [comment]
can you capture the value of `GetLastError()`?

**Comment by arvidn** [comment]
I'm editing the title to be what I expect you to have meant. Please feel free to amend this report with more information if I've misunderstood you.

**Comment by pavel-pimenov** [comment]
@aldenml  no :-( wait next crash-dump
add error_code g_last_error for store value:
https://github.com/pavel-pimenov/flylinkdc-r5xx/commit/17a3ebbfb2921e6a918d57fe79b8a34adec8d5f8
