### ISSUE TITLE
update documentation for anonymous mode

### ISSUE THREAD

**Issue by Piccirello** [arvidn/libtorrent#2663]
libtorrent version (or branch): 1.1.6

platform/architecture: n/a

compiler and compiler version: n/a

I'm attempting to better understand the libtorrent codebase and have been looking into the anonymous_mode feature. I've found various instances of `settings_pack::anonymous_mode` being used to determine user-agents, peer ids, and client versions throughout the code. The settings [reference](https://www.libtorrent.org/reference-Settings.html) also states that when anonymous mode is on:

```
* Trackers will only be used if they are using a proxy server
* The listen sockets are closed, and incoming connections will only be accepted through a SOCKS5 or I2P proxy
* NAT-PMP, UPnP, DHT and local peer discovery are all turned off
```

I haven't been able to find where any of these things happen based on the value of `settings_pack::anonymous_mode`. Could someone please point me to where UPnP, DHT, or local peer discovery are disabled; where the listen sockets are closed; or where any of these other items happen? Thank you.

**Comment by arvidn** [comment]
that documentation is outdated. originally anonymous mode did all those things, but the setting was then split into ``anonymous_mode`` and ``force_proxy``.

**Comment by Piccirello** [comment]
> originally anonymous mode did all those things, but the setting was then split into anonymous_mode and force_proxy.

Do you know what version of libtorrent was responsible for this change?

**Comment by Piccirello** [comment]
It appears the functionality was migrated from `anonymous_mode` to `force_proxy` for the 1.0.0 release. The change was documented in `session_settings.hpp` but alas libtorrent.org hasn't been updated. Should I create an issue for updating the web documentation?

**Comment by arvidn** [comment]
let's just use this ticket

**Comment by mhertz** [comment]
@arvidn 

There's a discussion currently going on in qBittorrent bugtracker, so could you please kindly confirm for me that force_proxy doesn't disable DHT so we can lay this to rest thanks :) (I know the option is deprceated now and "built-in" but nonetheless)

Thanks in advance.

**Comment by arvidn** [comment]
that's right; `force_proxy` doesn't disable DHT. However, if you don't have a proxy that supports UDP (only the socks5 protocol does) it will effectively be disabled, just like uTP and UDP trackers.

Not all socks5 proxy software supports UDP though.

**Comment by Piccirello** [comment]
In `session_impl::update_force_proxy()`, DHT definitely appears to get [disabled](https://github.com/arvidn/libtorrent/blob/RC_1_1/src/session_impl.cpp#L6530).

**Comment by arvidn** [comment]
hm, you're right. I wonder what the rationale for that was. it seems to date back quite a while. The history of it is a bit unclear. I wonder if this was done before libtorrent supported SOCKS5 perhaps.

**Comment by arvidn** [comment]
that piece of code is problematic for more reasons though, because nat-pmp, upnp and local peer discovery aren't turned back on again when force-proxy is disabled. I believe this was fixed in master at some point, but then I removed the force-proxy setting altogether (to just be implied by setting a proxy).

**Comment by arvidn** [comment]
@Piccirello does this look reasonable? https://github.com/arvidn/libtorrent/pull/3251

**Comment by Piccirello** [comment]
That change looks good. There should be some testing to confirm that DHT does indeed only use the proxy connection when a proxy is specified. I would confirm myself but I'm a complete novice regarding the libtorrent codebase.

**Comment by arvidn** [comment]
there are other tests for the udp socket, so it's not critical to test it with the DHT I think.
