### ISSUE TITLE
I noticed some configure issues

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#2668]
I have noticed some issues with configure that I thought I should bring to your attention.
These were observed in RC_1_1:

1. On macOS doing `./configure CPPFLAGS=-std=c++11` fails in the early stages complaining about not finding a working compiler. On Linux this doesn't happen. So I am not sure if you have something wrong in `configure.ac` or this is a macOS quirk.
2. ~I noticed that you require pkg-config but I don't think you use it in the rest of configure. Maybe leftover from older versions?~
3. Does libtorrent code directly use zlib? If yes, you should check for it during configuration. Ideally via pkg-config.

**Comment by sledgehammer999** [comment]
>I noticed that you require pkg-config but I don't think you use it in the rest of configure. Maybe leftover from older versions?

Scratch that. It used by `ax_check_openssl.m4`

**Comment by arvidn** [comment]
libtorrent used to use zlib, but that was a long time ago. now it ships with ``puff.c``. Does the configure script have a dependency on zlib?

**Comment by sledgehammer999** [comment]
@arvidn sorry, the configure doesn't require zlib. I was just wondering if it was a mistake. My bad.

Only the first issue remains.
Plus, there isn't a syncronization on the minimum boost version required by autotools, cmake and `docs/features.rst`.
