### ISSUE TITLE
Priority-0 files are not checked when `resume_data` is used

### ISSUE THREAD

**Issue by fbriere** [arvidn/libtorrent#2674]
libtorrent version (or branch): 1.1.5 and 1.1.6
platform/architecture: amd64

There seems to be a bug when loading from resume data a torrent that was partially selected and downloaded without a part file, where libtorrent will not properly check any file unselected for download.

In other words, under these conditions:

- A torrent is initiated with `resume_data`;
- Some files within that torrent have been set to priority 0;
- Some of those files are present on disk, with (partial) data; and
- No part file is present;

Then libtorrent will not properly check any of the files with priority 0.

I'm guessing this is a common scenario when migrating partially-selected torrents from 1.0 to 1.1, and is probably one of two possible causes for qbittorrent/qBittorrent#7802.

In case this might be of use, I've uploaded (https://gist.github.com/fbriere/ed25285dacd14d842ee98391e8e3866e) a (crappy) Python script and torrent that demonstrates this issue.  Simply run it three times, with `1`, `2` and `3` as respective argument; the third run will not start at 100% like it should.

**Comment by arvidn** [comment]
if the files have priority set to zero, libtorrent will pretend they don't exist and won't check whether they exist. But, as long as they remain having priority set to zero, is that a problem?
Even if their priorities are updated to > 0, will the effect be worse than re-downloading the data?

**Comment by arvidn** [comment]
is it the case that the resume data indicates the edge-pieces exist, even though they don't? i.e. the pieces that would have been written to a partfile.

**Comment by fbriere** [comment]
It is indeed a problem if the torrent was already at 100% and seeding; things will work fine for a while, but as soon as a peer requests a piece that overlaps with one of those files, libtorrent will raise an error.  Re-downloading the (not actually missing) data will temporarily fix the issue, but it will reappear the next time the torrent is loaded.

(I myself eventually resorted to recompiling qBittorrent with 1.0 because of this issue; every partial torrent I was seeding became an "I/O Error" ticking bomb under 1.1.)

As for analyzing the resume data, I currently lack the knowledge and expertise for this.  I'd rather not invest too much time if you can easily recreate this bug for yourself; if not, well, let me know and I'll see what I can do. :smile:

**Comment by fbriere** [comment]
I have to slightly amend my initial description of this issue: the lack of a part file is not actually required to trigger it.  (I was under the misguided impression that unselecting a downloaded file would bring it back into the part file.)  I have amended the example script correspondingly.

**Comment by fbriere** [comment]
(The more I experiment with reproducing this bug, the more confused I become.  Things that seemed to work before no longer do, or vice-versa.  Either this is akin to a race condition, or I am slowly losing my mind.  :confused:)

In any case, I have added an example of a faulty `fastresume` (https://gist.github.com/fbriere/ed25285dacd14d842ee98391e8e3866e#file-bad-fastresume); it checks at 100% with libtorrent 1.0, but not with 1.1.

**Comment by arvidn** [comment]
could you (or someone else) please try this patch? https://github.com/arvidn/libtorrent/pull/2695

I went with the simplest solution to get this to work. If a torrent is resumed that has any (non pad-) files with priority 0, but does not have a partfile, it is set in non-part-file-mode. In this mode it behaves the same as libtorrent 1.0.x. i.e. it keeps reading and writing part pieces in the files they were downloaded into.

However, if a part file is found, the pieces are expected to be found in there.

By default, when not resuming a download, but starting one, part files are enabled.
The only issue with this approach is that downloads cannot trivially be "upgraded" to use a part file. But I expect this to at least solve the immediate problem.

Anyone who can give this a try, please post your experience back on this ticket.

**Comment by fbriere** [comment]
(Sorry for the delay.)

After some quick testing, I have come across two issues with this patch:

- Torrents targeted by this patch have a completion of 0% upon being resumed, and will immediately start downloading if unpaused; a forced recheck is required to bring then back to 100% for that session.  The qBittorrent log shows: "Fast resume data was rejected for torrent '_torrent-name_'. Reason: _root-dir_ fast resume rejected. (): No such file or directory. Checking again..."  (Yes, the parentheses are empty.)

- Some of the torrents targeted by this patch alternate between rechecking as "complete" and "incomplete" from one session to the next.

The latter case warrants an explanation: for affected torrents, after forcing a recheck to 100%, libtorrent will *remove* the `pieces` entry from the resume file.  On the next resume, this causes `default_storage::verify_resume_data()` to return before it has had a chance to set `m_use_part_file`; the torrent is thus deemed incomplete, as it is missing its part file.  Interestingly enough, libtorrent will now add back the `pieces` entry; if qBittorrent is restarted before a new part file has been created (or after deleting it manually), the torrent will again recheck to 100%, bringing us back to the first step and completing the loop.

The strange part is that this only affects *some* torrents; I have three which should behave identically (100% complete with some files unselected), and only two of them are actually affected for some reason.  (They also have the annoying habit of automatically unpausing themselves after a 100% recheck while, again, the third torrent does not.)

I don't see any obvious pattern to explain this discrepancy, but I'll wait a bit before spending too much time looking into it, in hope that you can already figure out the answer on your own.

**Comment by fbriere** [comment]
At first glance, #2812 appears to work correctly, _provided that all files already exist_.  If a file was not created beforehand (due to being unselected and not containing any overlapping pieces), checking apparently stops there, and any remaining files past that point remain stuck at 0%.  After creating the missing dummy files, the torrent properly checks to 100%.

**Comment by arvidn** [comment]
is there an error message when checking stops? I wonder if it's trying to open the partfile, but the partfile was never created

**Comment by fbriere** [comment]
No error message, but your guess appears to be correct nevertheless: the `if()` in storage.cpp, line 348, is entered, and checking stops there.

Interestingly, it seems to be `ec.file = torrent_status::error_file_partfile` that brings the check to a halt; after setting it back to `file_index`, everything is back to normal.

**Comment by fbriere** [comment]
For the record, the second problem I mentioned in https://github.com/arvidn/libtorrent/issues/2674#issuecomment-364246854 is apparently not related to this issue, and affects "normal" torrents with parts files as well.  I'll therefore open a separate issue for that one.

**Comment by arvidn** [comment]
Ok, I just updated https://github.com/arvidn/libtorrent/pull/2812. I added a few more tests, including the scenario you described. I could reproduce it and fix it. When you say "everything is back to normal", do you mean this issue is properly fixed? (except for the unrelated issue you mentioned you will create a separate ticket for).

**Comment by arvidn** [comment]
please let me know if this fixes it

**Comment by arvidn** [comment]
I believe this is fixed in RC_1_1 now. The fix will be included in the upcoming 1.1.7 release

**Comment by fbriere** [comment]
I've only tested it briefly, but it does seem to be the proper fix.  Thanks!

**Comment by arvidn** [comment]
thanks for reporting it and help finding it!
