### ISSUE TITLE
No Python class registered for C++ class libtorrent::aux::strong_typedef<int, libtorrent::queue_position_tag, void>

### ISSUE THREAD

**Issue by aresch** [arvidn/libtorrent#2688]
**Please provide the following information**

libtorrent version (or branch): master

platform/architecture: x86_64

compiler and compiler version: gcc

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

When trying to access the 'queue_position' torrent status key, the follow TypeError is raised:

TypeError: No Python class registered for C++ class libtorrent::aux::strong_typedef<int, libtorrent::queue_position_tag, void>

**Comment by arvidn** [comment]
fixed here: https://github.com/arvidn/libtorrent/pull/2691

**Comment by arvidn** [comment]
thanks for the report!
