### ISSUE TITLE
Fail to connect to IPv6-only tracker

### ISSUE THREAD

**Issue by HenryHu** [arvidn/libtorrent#2689]
libtorrent: v1.1.6
platform: FreeBSD 11.1-STABLE/amd64
compiler: clang 5.0.0

It seems like that changes after v1.1.4 breaks IPv6-only trackers.
I tried a simple torrent with an IPv6-only tracker.
qBittorrent 4.0.3, which uses libtorrent, fails to connect to trackers using this torrent.
In windows/linux, it says "Address family not supported by protocol". In FreeBSD, it says "Invalid argument".

I tried the torrent with examples/simple_client. A ktrace shows the reason:

v1.1.4:

 28391 simple_client CALL  socket(PF_INET6,0x1<SOCK_STREAM>,IPPROTO_TCP)
 28391 simple_client RET   socket 33/0x21
 28391 simple_client CALL  setsockopt(0x21,SOL_SOCKET,SO_NOSIGPIPE,0x7fffdfffd920,0x4)
 28391 simple_client RET   setsockopt 0
 28391 simple_client CALL  ioctl(0x21,FIONBIO,0x7fffdfffd884)
 28391 simple_client RET   ioctl 0
 28391 simple_client CALL  connect(0x21,0x7fffdfffda10,0x1c)
 28391 simple_client STRU  struct sockaddr { AF_INET6, [tracker v6 addr]:80 }
 28391 simple_client RET   connect -1 errno 36 Operation now in progress

v1.1.6:
 27795 simple_client CALL  socket(PF_INET,0x1<SOCK_STREAM>,IPPROTO_TCP)
 27795 simple_client RET   socket 6
 27795 simple_client CALL  setsockopt(0x6,SOL_SOCKET,SO_NOSIGPIPE,0x7fffdfffc720,0x4)
 27795 simple_client RET   setsockopt 0
 27795 simple_client CALL  bind(0x6,0x7fffdfffc980,0x10)
 27795 simple_client STRU  struct sockaddr { AF_INET, 0.0.0.0:0 }
 27795 simple_client RET   bind 0
....
 27795 simple_client CALL  ioctl(0x6,FIONBIO,0x7fffdfffd8b4)
 27795 simple_client RET   ioctl 0
 27795 simple_client CALL  connect(0x6,0x7fffdfffda30,0x1c)
 27795 simple_client STRU  struct sockaddr { AF_INET6, [tracker v6 addr]:80 }
 27795 simple_client RET   connect -1 errno 22 Invalid argument

The new version creates and binds a IPv4 socket, which fails to connect to the IPv6 tracker. The old version creates a IPv6 socket and connects successfully to the tracker.

**Comment by HenryHu** [comment]
It seems like that in session_impl.cpp:1335:
if (!req.bind_ip) req.bind_ip = m_listen_interface.address();
sets the tracker_request's bind_ip to 0.0.0.0
and then, at http_tracker_connection.cpp:230, it is passed into http_connection::get(), which calls start(), then, at http_connection.cpp:358, it calls open() and bind() based on this address.
It seems like that just don't assign the bind address fixes the problem.

**Comment by arvidn** [comment]
thanks for the report. does this patch fix it?
https://github.com/arvidn/libtorrent/pull/2692

**Comment by HenryHu** [comment]
Yes, this fixes it. Thanks!
