### ISSUE TITLE
[Enhancement] torrent_handle.move_storage check_pieces

### ISSUE THREAD

**Issue by awiebe** [arvidn/libtorrent#2693]
It is possible that data exists at the move destination and both source and destination data are partial.  Ideally it would be nice if the two could be merged by piece checking both sides, and keeping only valid pieces form both the destination.

**Comment by arvidn** [comment]
it's complicated and hard to get all the edge-cases right. Can you think of a way to do this that doesn't perform unnecessary work in the common case and is robust?
