### ISSUE TITLE
[Enhancement] torrent_handle.move_storage dry_run

### ISSUE THREAD

**Issue by awiebe** [arvidn/libtorrent#2694]
Move storage `dont_replace` is cited as being used to check if the destination directory contains conflicting files, but on success, storage will still be moved.  It would be nice to be able to check if a move is theoretically possible without actually performing it.

My particular use case is to enhance the Deluge Torrent client's file checking logic to include it's completion move directory.  To do this it is necessary to test whether there are files in both the downloading and completion moved directories, without actually moving them.

**Comment by arvidn** [comment]
off hand, it sounds like it would be pretty simple to add another flag for ``dry_run``
