### ISSUE TITLE
libtorrent cannot compile/link against static openssl

### ISSUE THREAD

**Issue by NikkyAI** [arvidn/libtorrent#2696]
**Please provide the following information**

libtorrent version (or branch):
1.1.6

platform/architecture:
linux_x86_64

compiler and compiler version:
clang version 5.0.1 (tags/RELEASE_501/final)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

```
JOBS=`getconf _NPROCESSORS_ONLN`
SCRIPTDIR=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
UNAME_STR=`uname`
PREFIX=MyLibs

PREFIX="$PREFIX-$UNAME_STR"
mkdir -p "$PREFIX"
PREFIX=`cd "$PREFIX"; pwd`
PREFIX_DEBUG="$PREFIX-debug"

if [ ! -d "$PREFIX/src" ]; then
	mkdir -p "$PREFIX/src"
fi

if [ ! -d "$SCRIPTDIR/download" ]; then
	mkdir -p "$SCRIPTDIR/download"
fi

cd "$PREFIX"/src
wget "https://www.openssl.org/source/openssl-1.0.2n.tar.gz" -O "$SCRIPTDIR/download/openssl-1.0.2n.tar.gz"
echo  Extracting openssl-1.0.2n.tar.gz
tar xfz "$SCRIPTDIR"/download/openssl-1.0.2n.tar.gz
cd openssl-1.0.2n
./config --prefix="$PREFIX" --openssldir="$PREFIX" no-shared 
make clean
make depend
make -j $JOBS
make install

cd "$PREFIX"/src
wget "https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.gz" -O "$SCRIPTDIR"/download/boost_1_66_0.tar.gz
echo  Extracting boost_1_66_0.tar.gz
tar xfz "$SCRIPTDIR/download/boost_1_66_0.tar.gz"
cd boost_1_66_0
./bootstrap.sh --prefix="$PREFIX" --with-libraries=system,chrono,random
./b2 -a --reconfigure -j$JOBS variant=release link=static install

cd "$PREFIX"/src

wget "https://github.com/arvidn/libtorrent/releases/download/libtorrent-1_1_6/libtorrent-rasterbar-1.1.6.tar.gz" -O "$SCRIPTDIR"/download/libtorrent-rasterbar-1.1.6.tar.gz
echo Extracting libtorrent-rasterbar-1.1.6.tar.gz
tar xfz "$SCRIPTDIR/download/libtorrent-rasterbar-1.1.6.tar.gz"
cd libtorrent-rasterbar-1.1.6
./configure --with-boost="$PREFIX" --with-openssl="$PREFIX" --prefix="$PREFIX" --enable-debug=no --enable-shared=no --enable-static=yes
make -j $JOBS
make install
```

fails with openssl
```
Checking features to be enabled:
checking whether encryption support should be enabled... yes
configure: encryption support: now checking for the OpenSSL library...
checking for openssl/ssl.h in /home/nikky/dev/QtProjects/MyLibs-Linux... yes
checking whether compiling and linking against OpenSSL works... no
configure: error: OpenSSL library not found. Try using --with-openssl=DIR or disabling encryption at all.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
```

**Comment by arvidn** [comment]
so, did you try: ``--with-openssl=DIR``?

**Comment by NikkyAI** [comment]
PREFIX is the directory

**Comment by NikkyAI** [comment]
so it ended up compiling when i add
`export LDFLAGS="-L$PREFIX/lib -ldl"`

just complains later about 
```
/usr/bin/ld: /home/nikky/dev/QtProjects/QTM2/../MyLibs/Linux-release/lib//libcrypto.a(dso_dlfcn.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/lib/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

when i try to use it

**Comment by xiaomingzhong** [comment]
hi, I have  same problem

checking whether encryption support should be enabled... yes
configure: encryption support: now checking for the OpenSSL library...
checking for openssl/ssl.h in /home/xiaoming/Desktop/Boost-for-Android/openssl-android/armeabi-v7a/lib... yes
checking whether compiling and linking against OpenSSL works... no
configure: error: OpenSSL library not found. Try using --with-openssl=DIR or disabling encryption at all.
sed: can't read ./config.h: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
cp: cannot stat ‘/home/xiaoming/Desktop/Boost-for-Android/libtorrent/tests’: No such file or directory
make: *** No rule to make target `clean'.  Stop.

**Comment by arvidn** [comment]
@NikkyAI that last error you posted suggest you need to link against ``libdl`` (the dynamic linker). That's where ``dlopen`` and ``dlclose`` are defined, and it looks like openssl needs that.

@xiaomingzhong you can take a look at ``configure.log`` to see exactly what it tried to do to detect openssl that failed. It's supposed to print the compiler command line and the test program. Compare that with the flags you need to link against openssl on your platform and add the appropriate flags.

**Comment by xiaomingzhong** [comment]
thanks, not  find configure.log file , only config.log [https://github.com/xiaomingzhong/logs/blob/master/libtorrent-log/config.log](url)

**Comment by xiaomingzhong** [comment]
thank you very much !

**Comment by xiaomingzhong** [comment]
build bad:grinning:

**Comment by xiaomingzhong** [comment]
build bad:grinning:

**Comment by xiaomingzhong** [comment]
build bad:grinning:

**Comment by xiaomingzhong** [comment]
build bad:grinning:

**Comment by NikkyAI** [comment]
i figured how to fix it on linux i had to make sure to compile every isngle lirary with -ldl AND make sure that is used by qmake
