### ISSUE TITLE
Disable anonymous mode for private torrents

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#2702]
Hey guys,

one tracker operator contacted me saying that anonymous mode is causing problems and they will be forced to ban qbittorrent if no action is taken.

From further discussions, it seems their problem is the obfuscating effects of anonymous mode, which garble the peer-id. They claim that in qbittorrent v3_3_x (which uses RC_1_0) there was no problem.
So I am assuming that this problem targets RC_1_1 only.

They basically need to identify the clients properly in order to keep correct stats and keep cheaters out. This concerns **private** torrents.

My request is to disable anonymous mode for torrents with the private flag set. Is that possible to implement? Is it wise to implement? Will it create other problems?

**Comment by arvidn** [comment]
this only applies to the HTTP user agent, right? or do they think it's important to advertise client version to peers too?

**Comment by sledgehammer999** [comment]
From what I gather their tracker looks at the peer-id, which they see as garbled/random data. eg `&!H"GHJ"`

**Comment by arvidn** [comment]
I realise my question wasn't quite what I meant. As far as you know, do these trackers only look at the HTTP tracker request? (which does include the peer id) or do they also connect back over the bittorrent protocol to look at the peer-id advertised there? (at least back in the day, some trackers would detect if peers were behind NAT by connecting back).

If it's just the HTTP request, it wouldn't be too much of an privacy intrusion.

**Comment by sledgehammer999** [comment]
Hmm, good question. I just emailed the person who contacted me with your question. I'll return with their answer.

**Comment by sledgehammer999** [comment]
From the reply they gave they seem to also analyze the swarm itself too.
They also mentioned that sometimes even when anon-mode is explicitly disabled via the settings, qbt keeps sending random bytes as peer-id. Could this be a bug?

**Comment by arvidn** [comment]
Yes, if you enable anonymous mode, the peer id is clobbered with random bytes. if you disable anonymous mode, it won't be recreated (if you change the client fingerprint setting it will be though).

This is a bug that I'll fix.

As for the main topic of this thread, I found this [related patch](https://github.com/arvidn/libtorrent/commit/e37e4bfe8abccd0af275b9131cf0ddcb9cc15e80).

**Comment by sledgehammer999** [comment]
>As for the main topic of this thread, I found this related patch.

As far as I can tell this patch affects user-agent only and not the peer-id. These people are messaged me about the peer-id.

**Comment by arvidn** [comment]
having thought a bit about this. I'm tempted to do this:

1. always include the client fingerprint (i.e. version) in the peer-id, regardless of the ``anonymous_mode`` setting.
2. generate a unique peer_id for every peer connection (but still with the client fingerprint)

I believe this would simplify the code in general and take care of the peer-id update bug. I don't think there's any reason to keep a session-wide peer id anyway.

**Comment by arvidn** [comment]
However, if the tracker captures the peer-id in the tracker announce, connect back over bittorrent to verify the peer id is the same, it won't be.

This seems like a quite unreasonable thing for a tracker to do though. Nobody has ever actually *used* the peer id for anything. I believe it was a mistake to include it in the first place (but I have sympathy with making it).

**Comment by sledgehammer999** [comment]
1. always include the client fingerprint (i.e. version) in the peer-id, regardless of the anonymous_mode setting.
2. generate a unique peer_id for every peer connection (but still with the client fingerprint)

Aren't those 2 mutually exclusive? Or you talking for the rest of the (20bytes - fingerprint) bytes?

About the usefulness of anon-mode and all things related to it, I am neutral. I have never used private trackers nor vpn/proxies so I am not in a position to properly understand the need of it.

**Comment by Col-blimp** [comment]
arvidn, what about depreciating `anonymous_mode` as it offers no real protection for anything and VPN's and seedboxes are readily available along with proxy s?

**Comment by arvidn** [comment]
anonymous mode is meant to be used together with VPNs. If you're behind a VPN for privacy reasons, but libtorrent advertises facts about you that can be used to deduce your identity, it's kind of pointless. That's what anonymous mode is meant for.

I agree though that the long term goal should be to not leak such information regardless. My proposed patch would be a step in that direction.

**Comment by arvidn** [comment]
@sledgehammer999 by ``peer_id`` I mean the whole 20 byte string. The fingerprint is normally just a few bytes at the beginning, and not particularly unique or sensitive. Tracking and correlation will be less trivial with the remaining bytes being randomly generated for each connection.

The main difficulty is that to detect whether we're connected to ourself, there need to be some complexity. Either look through all other peer connections or encode a secret in there.
