### ISSUE TITLE
Question: deprecated function

### ISSUE THREAD

**Issue by gobne** [arvidn/libtorrent#2704]
Hi, i have this error on my compiler when i try to define: TORRENT_NO_DEPRECATE

void cdecl libtorrent::ipv6nodeprecate(void)" (?ipv6nodeprecate@libtorrent@@YAXXZ) referenced in function "public: cdecl libtorrent::session::session(struct libtorrent::settings_pack const &,int)

but I do not use this function (at least not directly).
What is it?
Thanks a lot

libtorrent version (or branch):
1.1.6 stable
platform/architecture:
Windows x64
compiler and compiler version:
MSVC 2015

**Comment by ssiloti** [comment]
That error indicates that the value of `TORRENT_NO_DEPRECATE` you are using when building your application is different from the value used when building libtorrent. If you are using cmake you can build libtorrent with deprecated functions disabled by setting the `deprecated-functions` option to OFF.

**Comment by gobne** [comment]
It works! Thank you so much :)
