### ISSUE TITLE
test_primitives FAIL

### ISSUE THREAD

**Issue by surfernsk** [arvidn/libtorrent#2707]
libtorrent version (or branch): 1.1.6
platform/architecture: Fedora Rawhide (28) x86_64 and i386
```
./configure \
	--disable-static \
	--enable-examples \
	--enable-python-binding \
	--with-boost-system=boost_system \
	--with-boost-python=boost_python \
	--with-libiconv \
	--enable-export-all
```
[build.log](https://yadi.sk/d/l-bF1WT03RbnVJ)  [
installed_pkgs.log](https://yadi.sk/d/sHZ4ixls3RbnYy)  [
test-suite.log](https://yadi.sk/i/kFkenU933Rbnad)

I'm not sure that the error is in libtorrent, but just in case I'm writing here

**Comment by arvidn** [comment]
unfortunately that output is not very helpful. Is there any chance you could rebuild and rerun it in debug mode?

**Comment by surfernsk** [comment]
```
./configure \
	--disable-static \
	--enable-examples \
	--enable-python-binding \
	--with-boost-system=boost_system \
	--with-boost-python=boost_python \
	--with-libiconv \
	--enable-export-all \
        --enable-debug
...
make V=1 -j4
...
make -j4 check
```
[test-suite.log](https://yadi.sk/d/2njUzrL_3RcfJc)

**Comment by arvidn** [comment]
it looks like this file ``utf8_test.txt`` is missing for you, for some reason. Is it not part of your tarball?

**Comment by surfernsk** [comment]
@arvidn thx. indeed, an error in missing `utf8_test.txt`
For me it's strange that in `fedora {26,27}` tests pass without errors and the file `utf8_test.txt` also missing
