### ISSUE TITLE
V522 There might be dereferencing of a potential null pointer 'p->hash'

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#2709]
libtorrent version (or branch): master

https://github.com/arvidn/libtorrent/blob/3a9861e2374e2959eb2c7d54d5e531d175d72626/src/disk_io_thread.cpp#L351

V522 There might be dereferencing of a potential null pointer 'p->hash'. disk_io_thread.cpp 368

![default](https://user-images.githubusercontent.com/920705/35168847-87f4ec58-fd6b-11e7-9ead-34ad104b1d8c.png)

**Comment by arvidn** [comment]
The analysis there seem wrong. Let's assume ``p->hash`` is ``nullptr``. The first condition on line 353 returns in case ``p->hashing_done`` is false.
The line where the potential null pointer would be dereferenced is conditioned on ``p->hashing_done`` is false. If that was the case, it would have returned already.
