### ISSUE TITLE
torrent_status::next_announce always zero

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#2713]
**Please provide the following information**

libtorrent version (or branch):
RC_1_1

platform/architecture:
win 7 x64

compiler and compiler version:
msvc2017 x64, mingw 7.2.0 x64

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

`torrent_status::next_announce` is always zero.
FYI this is how we convert to seconds:
```c++
libt::duration_cast<libt::seconds>(m_nativeStatus.next_announce).count();
```

**Comment by arvidn** [comment]
I'm a bit surprised that's not a compilation error. ``next_announce`` is not a ``duration``, it's a ``time_point``. If you want to know how long until the next announce (in seconds). You can either call ``next_announce_in()`` or do:

``libt::duration_cast<libt::seconds>(m_nativeStatus.next_announce - lt::clock_type::now()).count()``.

Now, since you get zero, it still looks like there may be some other issue lurking though. But could you try that?

**Comment by sledgehammer999** [comment]
It isn't defined as a timepoint. It is defined as `time_duration next_announce;` and then you have `typedef clock_type::duration time_duration;` and `typedef std::chrono::high_resolution_clock clock_type;`

This
>lt::duration_cast<lt::seconds>(m_nativeStatus.next_announce - lt::clock_type::now()).count()

gives
```
..\..\qBittorrent\src\base\bittorrent\torrenthandle.cpp:1197:84: error: no match for 'operator-' (operand types are 'const time_duration {aka const std::chrono::duration<long long int, std::ratio<1, 1000000000> >}' and 'std::chrono::_V2::system_clock::time_point {aka std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long long int, std::ratio<1, 1000000000> > >}')
     qlonglong lo = libt::duration_cast<libt::seconds>(m_nativeStatus.next_announce - libt::clock_type::now()).count();
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
```

>You can either call next_announce_in() 

Now I get why say time_point. I am talking about `torrent_status::next_announce` not `announce_entry::next_announce`

**Comment by arvidn** [comment]
oh, sorry. I was looking at ``announce_entry``,  not ``torrent_status``

**Comment by arvidn** [comment]
please give this a try: https://github.com/arvidn/libtorrent/pull/2748

**Comment by arvidn** [comment]
that PR has been merged
