### ISSUE TITLE
public API/ABI breakage in 1.1.6

### ISSUE THREAD

**Issue by puiterwijk** [arvidn/libtorrent#2716]
libtorrent version (or branch):
1.1.6

platform/architecture:
x86_64

compiler and compiler version:
clang version 5.0.0 (tags/RELEASE_500/final)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
Between versions 1.1.5 and 1.1.6 the public API and ABI has changed because of 4b467f82aca5a6d8b7c89031e1a7986f20b1dd16.

Example program:
````
#include <stdlib.h>
#include <boost/make_shared.hpp>
#include <libtorrent/aux_/session_impl.hpp>
#include <libtorrent/io_service.hpp>

int main(int argc, char* argv[])
{
  using namespace libtorrent;
  using namespace libtorrent::aux;

  libtorrent::io_service tester;
  
  libtorrent::aux::session_impl *testimpl = new libtorrent::aux::session_impl(tester);
}
````

(Note that I'm not a C++ developer, I had to literally search the internet for how to instantiate a class.)

ABI/API breaking changes should not happen in a minor patch level probably, and ABI changes should probably be accompanied with an soname bump.
I would consider this public API since it's in a header file installed with a standard `make install`, and is an exported symbol (see the [abicheck overview](https://taskotron.fedoraproject.org/artifacts/all/56cf6f64-f469-11e7-a604-525400817a8f/task_output/rb_libtorrent-1.1.6-1.fc27.log)).

**Comment by aldenml** [comment]
you are not supposed to use anything inside `aux`, it's true that a lot of implementation details are distributed and are easy to use, but that's due to the nature of how C/C++ works. You should use `libtorrent::session` instead. Take a look at this https://github.com/arvidn/libtorrent/blob/RC_1_1/examples/simple_client.cpp

**Comment by puiterwijk** [comment]
Right, so this is a place where you should probably be hiding symbols from ending up in the dynamic symbols list, for info on this with GCC see https://gcc.gnu.org/wiki/Visibility, and probably also not reference it in a header file that's installed in the default include path by default.

Note that I'm not trying to build something against the library myself, I just found out about the ABI/API breakage due to the abicheck refusing the update for Fedora to be submitted to stable because it could break user programs linked against those symbols.

**Comment by arvidn** [comment]
as aledenml points out, ``session_impl`` is not a public symbol.

it sounds like an issue with the package. The symbols should be hidden (the libtorrent source code is all annotated to support hiding private symbols). There's a configure check to make sure the compiler supports it (granted, it's GCC specific).

**Comment by puiterwijk** [comment]
Well, https://github.com/arvidn/libtorrent/blob/master/include/libtorrent/Makefile.am#L187 is telling me that this is an nobase_include_HEADERS, i.e. a header that gets installed into `/usr/include`, so maybe you'd want to drop it from there?
