### ISSUE TITLE
Slow transfer rates when the seed initiates the tcp connection

### ISSUE THREAD

**Issue by mkatsevVR** [arvidn/libtorrent#2725]
libtorrent version (or branch): 1.0.11

platform/architecture: centos7-x64

compiler and compiler version: gcc 5

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

tl;dr: if the seed client is started after the leech, the transfer rate is 10x slower than the other way around

0. Host A has the data, host B doesn't.
1. On host S (seed), start client_test -t test.torrent -k -H -X -h -N
2. On host L (leech), start client_test -t test.torrent -k -H -X -h -N
Outcome: logs show L connecting to S, transfer speed is 50MB/s
3. Restart the client on S with the same arguments
Outcome: logs show S connecting to L, transfer speed is only 5MB/s (!)
4. Restart the client on L
Outcome: L connects to S again, transfer speed is back to 50MB/s

Similar behavior happens with 2 leeches and 1 seed. Any leech started before the seed would have significantly reduced transfer rate.

**Comment by arvidn** [comment]
would you be able to dig into this a bit and provide more details?
My suspicion is that, at these rates, the limiting factors are things like buffer sizes and outstanding request queue sizes etc. Some of that is negotiated as part of the extended handshake. Now, obviously it's not supposed to be affected by who connects to whom. But it probably makes sense to start looking there.

If you enable peer logging, you'll get a pretty high rate of log alerts (at those transfer rates). But if you focus on the connection handshake parts. Can you see any differences between the slow and the fast case?

Also, I take it none of your clients (seeds nor downloaders) set any rate limits, is that right?

Another useful thing to look at to trouble shoot these kinds of things is to log the ``session_stats_alert`` and then use ``tools/parse_session_stats.py`` to analyze it and generate graphs (requires ``gnuplot``).

The session stats can hint at what might be the bottleneck. disk I/O, send/receive buffer, request queue, etc.

**Comment by mkatsevVR** [comment]
The problem goes away if I set recv/send_socket_buffer_size to 0 instead of 1MB (from high_performance_seed). The speed actually goes up significantly to 200MB/s. It makes sense that the previous values were too small, but not why it depended on who started the connection. Perhaps there is a bug in libtorrent somewhere that causes these settings to not apply to some connections?

On Jan 25, 2018, at 6:20 AM, Arvid Norberg <notifications@github.com<mailto:notifications@github.com>> wrote:


would you be able to dig into this a bit and provide more details?
My suspicion is that, at these rates, the limiting factors are things like buffer sizes and outstanding request queue sizes etc. Some of that is negotiated as part of the extended handshake. Now, obviously it's not supposed to be affected by who connects to whom. But it probably makes sense to start looking there.

If you enable peer logging, you'll get a pretty high rate of log alerts (at those transfer rates). But if you focus on the connection handshake parts. Can you see any differences between the slow and the fast case?

Also, I take it none of your clients (seeds nor downloaders) set any rate limits, is that right?

Another useful thing to look at to trouble shoot these kinds of things is to log the session_stats_alert and then use tools/parse_session_stats.py to analyze it and generate graphs (requires gnuplot).

The session stats can hint at what might be the bottleneck. disk I/O, send/receive buffer, request queue, etc.

**Comment by arvidn** [comment]
yeah, that seems like a reasonable theory

**Comment by arvidn** [comment]
It just occurred to me that you're using an ancient version of libtorrent. I will ensure that this is not the case in 1.1.x and later though.

**Comment by arvidn** [comment]
I put some updates in #2739
