### ISSUE TITLE
No download progress

### ISSUE THREAD

**Issue by kotbrain** [arvidn/libtorrent#2726]
libtorrent version (or branch): 1.1.6
platform/architecture: Windows 7
compiler and compiler version: CMake (latest)

Hello. My program on libtorrent for most users is working fine. But one user (at the moment) has the problem with the download - it has no progress. Details of the download in the attached document. I also attached my log for an example of normal download.

I noticed the following strange lines:
`[Info] files hash for piece 560 failed`
`[Info] could not map port using UPnP: no router found`

What could be the problem?

https://pastebin.com/95CavkGw

[download_bug.log](https://github.com/arvidn/libtorrent/files/1663870/download_bug.log)
[download_normal.log](https://github.com/arvidn/libtorrent/files/1663874/download_normal.log)

**Comment by arvidn** [comment]
for trouble shooting transfers, you may want to take a look at this: https://www.libtorrent.org/troubleshooting.html

**Comment by arvidn** [comment]
I take it that is your log, not libtorrent alert logs. But yes, it appears as if the last piece is failing hash check.

If you don't believe this is caused by the other end sending corrupt data, my bet would be that this user's firewall has a feature where it detects certain byte sequences and rewrites them into other bytes.

This has caused data corruption before by libtorrent users.

**Comment by arvidn** [comment]
feel free to reopen this if you have more facts or observations.

**Comment by kotbrain** [comment]
I again have the same problem :)

Added the libtorrent alert logs. See attached file. Beginning from 12717 line the progress stopped and  speed gradually fell to almost 0.

[download.log](https://github.com/arvidn/libtorrent/files/1707428/download.log)

**Comment by arvidn** [comment]
from what I can tell, shortly after the last request message being sent, this is printed to the log:
``[Update] downloading | error:  | peers: 12 | seeds: 0 | speed: 4409139 | progress: 763598``

So, there are no seeds. Are you sure the client does not have all the available pieces by the time it stops requesting?
