### ISSUE TITLE
feature request - ability to specify "external listening" port to work with vpn.

### ISSUE THREAD

**Issue by ostapus** [arvidn/libtorrent#2728]
Hello,

  not an issue but feature request :
Some VPN providers provide "port forwarding" service, where they assign external upd/tcp port that will be forwarded to connected client. In this case - local listening port and "assigned port" differs. Having this  situation - no peers are able to connect - seeding is low. Would be nice to have setting like "external_port" that will be announced as listening port. setting also should be reactive as "assigned port" can change over time.

thanks

**Comment by arvidn** [comment]
do you have a reference to any documentation of how this works? who decides which local port packets get forwarded to?
It seems like VPNs could just implement a NAT-PMP service to respond with the external IP and port and things would just work seamlessly.
Do you know if there is some similar query to programatically configure this port?
