### ISSUE TITLE
HTTPS announces perpetually stuck in CLOSE_WAIT

### ISSUE THREAD

**Issue by LaserEyess** [arvidn/libtorrent#2730]
**Please provide the following information**

libtorrent version (or branch): libtorrent-rasterbar 1.1.6 

platform/architecture: GNU/Linux x86-64 (Arch Linux)

compiler and compiler version: gcc 7.2

When used with deluge 1.3.15, libtorrent will not close TCP connections to https trackers. This will continually use file descriptors until nofiles is reached and deluge crashes after not being able to open files. While the particular crash is not libtorrent's fault, I believe not closing the connections is. 

I don't know what else to provide, the relevant deluge bug report is here http://dev.deluge-torrent.org/ticket/3152

here is an example of a crash with too many open files
http://dev.deluge-torrent.org/attachment/ticket/3152/sqnY.thing.txt

I am measuring open files with 
```
# lsof $(pgrep deluged) | grep 'CLOSE_WAIT' | wc -l 
```

**Comment by arvidn** [comment]
@LaserEyess Thanks! how certain are you that these are HTTPS tracker connections specifically?

Does it not happen if you only have HTTP trackers? or did you correlate the endpoints in ``netstat`` with the trackers you use?

Is it possible that it's TCP bittorrent peers?

I'm just curious of how much I should focus on just the HTTPS paths.

**Comment by LaserEyess** [comment]
It is definitely announces, all connections are from `localhost->$tracker_ip` according to `lsof`. It is at least two trackers, both of which are HTTPS announces. Furthermore, I tried to reproduce this on another machine with only HTTP torrents and all the connections close properly. That doesn't mean it's only HTTPS announces I guess, but at the very least there is some difference between trackers that's causing it, the only think in common I know right now is that they're HTTPS announces. I'm going to try and add some HTTPS announced torrents to another machines and see if I can reproduce. That and some varying trackers. 

Another piece of information: it appears downgrading to 1.1.5 did not fix this. I can try going back further I guess. Please let me know anything else I can do to help debug. I'm also in IRC as LaserEyess.

**Comment by LaserEyess** [comment]
@arvidn some updates:

I cannot reproduce on another machine running arch and the latest deluge/libtorrent. Downgrading to 1.1.5 did not work but downgrading to 1.1.4 did. However, this also required downgrading boost/boost-libs so I'm not sure what that means. Someone else on IRC who also uses arch is reporting the same issue, so this could potentially be an arch bug, I'm not sure.

**Comment by arvidn** [comment]
thanks for the update. I haven't had a chance to look into this yet (hopefully this weekend). It's quite possible it could be an issue with an old (or specific version of) boost.asio. The SSL support is all through boost.asio's ssl stream wrapper.

**Comment by ValdikSS** [comment]
I have this problem only with https://mars.apollo.rip tracker, which is behind Cloudflare and uses HTTP/2.
Could it be the root issue?

**Comment by Azelphur** [comment]
Running deluged 2.0b2.dev43 with libtorrent-rasterbar 1.1.6 I too seem to have this issue, I have many CLOSE_WAIT connections open, ALL of which are to cloudflare address ranges. This causes deluge to regularly crash for me, due to too many open files.

**Comment by arvidn** [comment]
Interesting. I'll dig deeper into changes since 1.1.4. In the meantime, could anyone try out this patch?

https://github.com/arvidn/libtorrent/pull/2797

**Comment by arvidn** [comment]
that's the stacktrace. could you include the actual error too? thanks!

**Comment by ValdikSS** [comment]
It segfaults right after the splash screen, without error message.

**Comment by arvidn** [comment]
I see. the error I was interested in was ``SIGSEGV``

**Comment by arvidn** [comment]
I've updated the patch, please test it again!

**Comment by ValdikSS** [comment]
@arvidn does not crash now. I'll let qBittorrent run a day and report back.

**Comment by ValdikSS** [comment]
So far so good, no CLOSE_WAIT connections, and the TCP fd number is very low.

**Comment by arvidn** [comment]
so, what's the verdict?

**Comment by LaserEyess** [comment]
```
# lsof -p $(pgrep deluged) | grep 'CLOSE_WAIT' | wc -l
0
```

I've been running this patch for about 12 hours, no issues so far. I believe that has fixed it.
