### ISSUE TITLE
 ImportError: /usr/local/lib/libtorrent-rasterbar.so.9: undefined symbol: _ZN5boost7atomics6detail8lockpool12get_lock_forEPVKv

### ISSUE THREAD

**Issue by marine1988** [arvidn/libtorrent#2734]
**Please provide the following information**

libtorrent version (or branch): 1.1.6

platform/architecture: arm raspberry pi 3

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

After installit with [this tuturial ](http://dev.deluge-torrent.org/wiki/Building/libtorrent) when runing comand python -c "import libtorrent; print libtorrent.version" I get 1 error 

`
ImportError: /usr/local/lib/libtorrent-rasterbar.so.9: undefined symbol: _ZN5boost7atomics6detail8lockpool12get_lock_forEPVKv
`

**Comment by zzzhr1990** [comment]
It seems you built libtorrent and boost use diffrent C++ standards (like boost use C++98/install from yum, and libtorrent use C++ 11)

**Comment by dcyrille18** [comment]
I have same problem when cross-compiling the libtorrent python binding and libboost with same std flags (I tried std=c++11 and std=c++98 without success) for raspberry pi 3 (arm-rpi-4.9.3-linux-gnueabihf).
When I run an ldd on the generated libtorrent.so, it seems that there is no dependency to libboost_atomic.
Any idea to resolve it ?

**Comment by arvidn** [comment]
it's possible there's some boost library that has recently added a dependency on boost_atomic, or perhaps some boost library depends on it just for arm. Are you building with boost build?

**Comment by dcyrille18** [comment]
Yes, I compile with boost with these commands:

For Boost 1.55.0:
```
bjam toolset=gcc-arm target-os=linux architecture=arm variant=release cxxflags="-std=c++11 -fPIC -I/opt/libpython/include" linkflags="-std=c++11" -s NO_BZIP2=1 -j4
bjam toolset=gcc-arm target-os=linux architecture=arm variant=release cxxflags="-std=c++11 -fPIC -I/opt/libpython/include" linkflags="-std=c++11" -s NO_BZIP2=1 install --prefix=/opt/boost/ -j4
```

For libtorrent 1.1.6 (in folder bindings/python):
```
bjam toolset=gcc-arm target-os=linux architecture=arm variant=release libtorrent-link=static encryption=off cxxflags="-std=c++11 -I/opt/boost/include -I/opt/libpython/include" linkflags="-std=c++11 -L/opt/boost/lib -L/opt/libpython/lib" -j4
```

**Comment by dcyrille18** [comment]
I "resolved" the problem by adding "-lboost_atomic" on linkflags but this link is only dynamic in this manner and it need to install liboost_atomic1.55.0 on the raspberry.

**Comment by cdromas** [comment]
Any news ?

**Comment by arvidn** [comment]
The missing symbol could suggest that the boost library on your target machine is a different version than on your build machine. Are you sure you're copying *all* dependencies over to your target after building?
One thing to test would be to link statically against boost, to avoid any run-time dependencies. When building the python bindings, specify `libtorrent-link=static` and `boost-link=static`.

**Comment by arvidn** [comment]
`/usr/local/lib/libtorrent-rasterbar.so.9` that path suggests that you've "installed" libtorrent. That means you have to be really careful to install all other dependencies too, and not have any of them overwritten by a package manager
