### ISSUE TITLE
Repeating torrent_error_alert

### ISSUE THREAD

**Issue by ruslanfedoseenko** [arvidn/libtorrent#274]
Hi, I'm using libtorrent 1.0.7.
I have some problem with torrent_error_alert. It repeats in some case too many times with same error message(The case will be described below).
From Documentaion to torrent_error_alert:

> This is posted whenever a torrent is transitioned into the error state.

So I consider if a error occured so torrent is transitioned to error state and when error occured again no alert should be posted.
Now the describtion of a test case:
Take any torrent and add to session with save path witch is not writable for current user. You will recive about 3-5 torrent_error_alert and file_error_alert per second.

**Comment by arvidn** [comment]
did you mean to say "not writable"?

**Comment by ruslanfedoseenko** [comment]
yeap. Sorry for typeo.

**Comment by arvidn** [comment]
this seems to be related to #240 . Or at least these issues will probably be dealt with together

**Comment by ruslanfedoseenko** [comment]
I can push an pull request to fix my issue. It is not too complecated.

**Comment by Falcosc** [comment]
Do we still need the change because @ruslanfedoseenko didn't create a pullrequest for his change https://github.com/ruslanfedoseenko/libtorrent/commit/1fe498328fef37a26c9d0737de2d84a182928179

**Comment by ruslanfedoseenko** [comment]
I've created a pull request for this and we discussed that there mey be a more serious bug thet is not covered my this patch
https://github.com/arvidn/libtorrent/pull/282

**Comment by Falcosc** [comment]
@ruslanfedoseenko I would like to analyse why we got multiple alerts. Whould be very nice if you could help to create a test for it or at least a documentation how to force the error.

I think abbout an assert to force crash on this case, but I am not sure if there are valid usecases for repeating alerts in this place. But I guess there are some because of multithreading.

**Comment by ruslanfedoseenko** [comment]
You may use this as a test case.
> Now the describtion of a test case:
Take any torrent and add to session with save path witch is not writable for current user. You will recive about 3-5 torrent_error_alert and file_error_alert per second.

Actually, I don't checked if this behaviour exists in 1.1.x branch.
