### ISSUE TITLE
partfile and updating file priorities

### ISSUE THREAD

**Issue by arvidn** [arvidn/libtorrent#2747]
libtorrent version (or branch): RC_1_1

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Changing the priority of a file that's downloaded to zero, will (most likely) make the disk subsystem expect all its pieces to be in the part file. If any peer requests pieces from it, the disk read will fail.

The scenario is outlined here: https://github.com/arvidn/libtorrent/pull/2695#issuecomment-360316055

@sledgehammer999 Do you have any suggestions for how to handle this?

I can think of two options:

1. Always move files entirely into and out of the part file when changing priorities. This could potentially be a very expensive operation, and more or less unnecessary if the file is completely downloaded.

2. Track whether files have been put in the part file or at its original position on disk separately from its priority. This would probably require additional resume data fields (which is another moving part that can fail) and it may need (complex) logic on startup to detect whether a file is in the partfile or in its original location on disk.

**Comment by sledgehammer999** [comment]
I think those to 2 options are the only ones.
A slight modification to the 2nd-one: If a files seems to have pieces downloaded, take a look at the actual location and if it doesn't match exactly look at the partfile. If it doesn't match the partfile either, then prefer one or the other (I would vote the file on disk).

I wonder what utorrent does in this case? Does it import files back into the partfile when unselected?

**Comment by arvidn** [comment]
I believe this was fixed by https://github.com/arvidn/libtorrent/pull/2812
