### ISSUE TITLE
Building for Debian Jessie on ARM

### ISSUE THREAD

**Issue by veribaka** [arvidn/libtorrent#275]
Hi!

I've been trying unsuccessfully to build this on my A10 1GB board. Tried with both 1.0.6 and 1.0.7. Configuration is not a problem running:

./configure --enable-python-binding --with-libgeoip=system --with-libiconv --prefix=/usr --with-boost-libdir=/usr/lib/arm-linux-gnueabihf

However, make will crash the machine. The process starts alright but after a while it stops using CPU almost entirely, and starts using more and more RAM, until it uses up swap and just crashes the board.
Towards the end I get messages like:

"cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++"

and

'libtorrent::torrent_info::file_iterator libtorrent::torrent_info::end_files() const’ is deprecated

HOWEVER

If I don't include the flag --prefix=/usr, then make runs till the end, and I can do make install (or checkinstall or whichever) without a hitch. 
Problem is, if I run 

'python -c "import libtorrent; print libtorrent.version"'

I the following message:

ImportError: No module named libtorrent

And deluge will use the repos libtorrent.

Some more information:

As I said, I am currently running Debian Jessie on ARM.
Kernel: 4.2.3-sunxi
Proc: ARMv7 Processor rev 2 (v7l)
Memory: 1GB ram

Any hints?
Thanks!

**Comment by arvidn** [comment]
I would recommend trying to build the python binding with bjam. I believe it should be enough to say: "python setyp.py install" in the root. If that doesn't work, you could try the bindings/python directory

**Comment by veribaka** [comment]
This seems to have worked, and now python -c "import libtorrent; print libtorrent.version" returns 1.0.6.0.

Thanks!

However Deluge still says it's using 0.16.18.0, and if I uninstall libtorrent-rasterbar7, it takes deluged with it. Any idea if this is related to missing bindings? Any way I can check all the bindings are in their place?

PS. Could you add /usr/lib/arm-linux-gnueabihf to the default search patterns for libboost? I lost quite some time searching for solutions to that, and I don't think it's something so obvious to people that use ARM. I'm frankly surprised if people didn't come to you with this before :)

**Comment by cas--** [comment]
How did you install Deluge? It should be picking up the new libtorrent if it's being picked up by python unless you install Deluge from source and it built libtorrent itself. Can you try this:

`python -c "from deluge._libtorrent import lt; print lt.version"`

**Comment by veribaka** [comment]
I installed Deluge from repo, with 

sudo apt-get install deluge deluged deluge-common deluge-console deluge-web deluge-webui

python -c "from deluge._libtorrent import lt; print lt.version"

1.0.6.0

Everything seems ok, could it be a problem with ltConfig reporting the wrong libtorrent?

**Comment by cas--** [comment]
I don't know, ltConfig is a third party plugin, maybe picking up your local libtorrent version? The proper way of determining libtorrent version used by Deluge are detailed here: http://dev.deluge-torrent.org/wiki/Troubleshooting#DelugeVersion

**Comment by veribaka** [comment]
It seems deluge isn't installed, just deluged (I don't think I need deluge, do I?), my bad.

Anyway:

deluged --version
deluged: 1.3.10
libtorrent: 1.0.6.0

**Comment by cas--** [comment]
You don't need the main deluge package installed on a server or non-UI enviroment. You can see it is installed properly. I would suggest though you install latest libtorrent 1.0.7 and possibly even update Deluge to 1.3.12. Anyway this is going offtopic for this issue.

**Comment by veribaka** [comment]
Right, I'll attempt to do this, thank you very much for your support cas-- and arvidn! :+1:  
If anything arises I'll open a new thread in github or deluge forum accordingly.

**Comment by arvidn** [comment]
the python binding will report the libtorent version it was built against, not the actual run-time version of libtorrent.so. So, if you switch out the libtorrent main library version without also switching the python binding library, you will still see the old libtorrent version from python

**Comment by veribaka** [comment]
So, how exactly should I do the switch? Sorry, not very versed in this. In the mean time I'll be trying to update libtorrent and deluge to the latest versions like cas-- advised.

**Comment by cas--** [comment]
There is nothing to switch arvid is simply mentioning a possible reason for version mismatch. The best solution is to ensure an old libtorrent files are removed before installing or simply be aware of this when building from source.

**Comment by veribaka** [comment]
Hey! Just to let you know that after compiling latest Deluge and libtorrent, ltConfig reports correct libtorrent.

Thanks for the help from both!
