### ISSUE TITLE
why do I get these errors

### ISSUE THREAD

**Issue by colcrt** [arvidn/libtorrent#2766]
**Please provide the following information**

libtorrent version (or branch): libtorrent-rasterbar-1.1.6 / boost_1_66_0

platform/architecture: windows

compiler and compiler version: visual studio 2013

Hi, I am updating a program in visual studio 2013 and I have some errors that I have not been able to fix
`error C2660: 'libtorrent::session_handle::listen_on' : the function does not accept 1 arguments`
**this is the code the error is in the line**  if (m_pcSession->listen_on(portRange) == false)

```
bool EL_TorrentPatcher::Begin(EL_PatchConfig& stConfig, Earth::EA_CStatus *pcStatus)
{
 MA_SAFE_DELETE(m_pcSession);
 m_pcSession = new session(fingerprint("LT",LIBTORRENT_VERSION_MAJOR,LIBTORRENT_VERSION_MINOR,0,0),session::add_default_plugins);

 m_pcSession->set_alert_mask(alert::error_notification | alert::storage_notification);

 libtorrent::session_settings settings; 
 settings.user_agent = APP_NAME; 
 settings.prioritize_partial_pieces = true;
 settings.min_announce_interval = 30;
 m_pcSession->set_settings(settings);

 m_pcSession->add_extension(&libtorrent::create_smart_ban_plugin);

 m_pcSession->set_max_half_open_connections(stConfig.maxHalfOpenConnections);
 m_pcSession->set_max_uploads(stConfig.maxUploadsPerSession);
 m_pcSession->set_max_connections(stConfig.maxConnectionsPerSession);

 std::pair<int, int> portRange(stConfig.minPort, stConfig.maxPort); 
 if (m_pcSession->listen_on(portRange) == false)//void listen_on(std::pair<int, int> const& port_range, error_code& ec, const char* net_interface = 0, int flags = 0);
 {
  if( pcStatus )
   pcStatus->AddNRf( Earth::EA_STATUS_ERROR, EL_LTEXT("TORRENT_SESSION_LISTEN_ERROR"), portRange.first, portRange.second );
  return false;
 }

 // ¾Æ·¡ ±â´ÉµéÀº listen_on ÀÌÈÄ¿¡ ÇÏµµ·Ï ±ÇÀåÇÏ°í ÀÖÀ½
 m_pcSession->start_upnp();
 m_pcSession->start_natpmp();
 m_pcSession->start_dht();
 m_pcSession->start_lsd();

 return true;
}
```

**Comment by aldenml** [comment]
because you are missing one argument, see: https://github.com/arvidn/libtorrent/blob/master/include/libtorrent/session_handle.hpp#L743

**Comment by colcrt** [comment]
hello, thanks for your help you could give me an example of how the code would be

**Comment by aldenml** [comment]
that function is deprecated, I don't know where it is used or tested, I advice you to use settings

**Comment by colcrt** [comment]
I know that is not much what I have to modify pls a help  https://github.com/colcrt/TorrentPatch-Official
