### ISSUE TITLE
Disable ‘-Wstrict-prototypes’ to prevent cc1plus warning

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#277]
I'm not sure if I mentioned this before but when building the python bindings the following warnings appear throughout the make output:

    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]

Is it possible to disable `-Wstrict-prototypes`?

**Comment by arvidn** [comment]
git grep doesn't show anything. it seems odd that it would be enabled by default for c++ files if it also prints this warning

**Comment by cas--** [comment]
I know that puzzled me however I just found this answer on SO, that I hadn't come across before that could well fit what is being seen: http://stackoverflow.com/a/8106847/175584

I can test some of the suggested solutions.
