### ISSUE TITLE
#define R, etc

### ISSUE THREAD

**Issue by armagedec** [arvidn/libtorrent#2774]
libtorrent version (or branch):
1.1.6
platform/architecture:
Win32
compiler and compiler version:
MSVC141

Defines which cause problems in unbelievable places:
sha1.cpp: #define **R**(x, n)         (((x) &UINT64_C(0xFFFFFFFFFFFFFFFF))>>((u64)n))

Cause problem in boost/type_traits/detail/is_function_ptr_tester.hpp:
template <class **R** > // Here is that "R"
yes_type is_function_ptr_tester(R (*)());

Suggest add #undef for all local #define-s

**Comment by arvidn** [comment]
I can't find that specific define in sha1.cpp in the ``RC_1_1`` branch. Are you sure this is version 1.1.6?

More importantly though, how does boost type traits get included *after* that define?
all includes happen first. Are you concatenating .cpp files or something?

**Comment by armagedec** [comment]
Yeah, sorry, this one is in sha512.cpp.

I'm not sure how did it happen. (complex project)

But, IMHO, leaving such macros not undefined is not the best style.

**Comment by arvidn** [comment]
so, I assume you are referring to the ``master`` branch then, not 1.1.6.

regarding macros, I disagree. these defines don't leak out of this file, they are completely contained.
In your case they appear to have highlighted some shady business, which I can only assume is concatenating .cpp files.

does your compiler not give you an include-backtrace for how you got there? clearly nothing is included after ``R`` is defined in ``sha512.cpp``.

**Comment by armagedec** [comment]
Yes, I found that fastbuild automatically creates .cpp unity files, while building libtorrent:
#include "...blabla1.cpp"
#include "...blabla2.cpp"
