### ISSUE TITLE
Add UDP Trackers

### ISSUE THREAD

**Issue by fastesol** [arvidn/libtorrent#2776]
Hi, is it possible to add trackers? similar to `session.add_dht_router()`.

**Comment by LiMinggang** [comment]
Not sure if this one is OK. bool torrent::add_tracker(announce_entry const& url)

**Comment by arvidn** [comment]
yes. trackers are added to specific torrents though, not the session (as @LiMinggang points out).

you can either add trackers as you add the torrent (in [add_torrent_params](https://libtorrent.org/reference-Core.html#trackers)), or add it to a torrent_handle, with [add_tracker()](https://libtorrent.org/reference-Core.html#add_tracker()).
