### ISSUE TITLE
No download progress (reopen)

### ISSUE THREAD

**Issue by kotbrain** [arvidn/libtorrent#2777]
libtorrent version (or branch): 1.1.6
platform/architecture: Windows 7
compiler and compiler version: CMake (latest)

I'm again with this problem :)
https://github.com/arvidn/libtorrent/issues/2726

Added the libtorrent alert logs. See attached file. Beginning from 12717 line the progress stopped and  speed gradually fell to almost 0.

[download.log](https://github.com/arvidn/libtorrent/files/1707428/download.log)

**Comment by arvidn** [comment]
shortly after the last request message being sent, this is printed to the log:
``[Update] downloading | error: | peers: 12 | seeds: 0 | speed: 4409139 | progress: 763598``

So, there are no seeds. Are you sure the client does not have all the available pieces by the time it stops requesting?

**Comment by kotbrain** [comment]
Yes. On distribution there is a web-seed, on which there are all files. At me loading always reaches the end. But some users have such problems. What information can help find the problem?

**Comment by arvidn** [comment]
maybe you can pull the web server log from just a single peer, one that's failing, and see what it's requesting. Perhaps there's an issue where it stalls and the web server doesn't time out or something.

**Comment by arvidn** [comment]
or maybe there are other alerts from the peer that's failing indicating the web server gets disconnected or banned for some reason

**Comment by kotbrain** [comment]
What types of alerts should I enable to see the disconnect messages from the web server?

At the moment I'm using:
ёlt::alert::status_notification
lt::alert::session_log_notification
lt::alert::torrent_log_notification
lt::alert::peer_log_notificationё

**Comment by kotbrain** [comment]
I noticed that the problem appears if users download some files from another source, and then try to download the remaining ones via libtorrent. Can the problem be because I create a torrent file using third-party programs on Windows, and the distribution files are located on Linux?

**Comment by arvidn** [comment]
you should probably enable ``lt::alert::error_notification`` too
If you're resuming a download, most likely libtorrent will first "check files". i.e. read back everything downloaded so far from disk, and check which parts of it matches the piece hashes, as specified in the .torrent file. For very large files, this may take a while.

Check the state your torrent is in, and the progress indicator (both in ``torrent_status``) should indicate the checking progress.
