### ISSUE TITLE
RC_1_1 libtorrent configure option --with-libiconv is not linking against libiconv as it should

### ISSUE THREAD

**Issue by barmalej2** [arvidn/libtorrent#2780]
libtorrent version (or branch): RC_1_1 branch, version-1.1.6, git revision 91e03c789
boost version: 1.66.0
python version: 2.7.14
platform/architecture: armv5tel GNU/Linux, kernel 2.6.31.8, uClibc-ng 1.0.28 based
compiler and compiler version: gcc-7.20 
Step to reproduce case. Import python libtorrent:
`python -vc "import libtorrent; print libtorrent.version"`
Expected output is only libtorrent version.
Actual output is:

> dlopen("/ffp/lib/python2.7/site-packages/libtorrent.so", 2);
> /ffp/bin/python2.7: symbol 'libiconv': can't resolve symbol
> /ffp/bin/python2.7: symbol 'libiconv_open': can't resolve symbol
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ImportError: unknown dlopen() error

Libtorrent is built natively on arm box using autotools with following configuration:
> ./configure \
>         --prefix=/ffp \
>         --exec-prefix=/ffp \
>         --enable-shared \
>         --disable-static \
>         --disable-logging \
>         --with-libiconv \
>         --enable-python-binding \
>         --with-boost=/ffp \
>         --with-openssl=/ffp

Configure option --with-libiconv should enable linking against system libiconv, but it's not working as expected, even if configure script finds libiconv itself. You can notice, what I am not specifying prefix for  --with-libiconv, because it was working with previous versions of libtorrent without issues.  Attaching compilation log below:
[libtorrent_git.log](https://github.com/arvidn/libtorrent/files/1712303/libtorrent_git.log)

Seems like problem is not related with python bindings library directly, but more likely with main libtorrent library:
`nm -D /ffp/lib/libtorrent-rasterbar.so.9.0.0 | grep libiconv`
>          U libiconv
>          U libiconv_open

`readelf -d /ffp/lib/libtorrent-rasterbar.so.9.0.0 | grep NEEDED`
>  0x00000001 (NEEDED)                     Shared library: [libboost_system.so.1.66.0]
>  0x00000001 (NEEDED)                     Shared library: [libssl.so.1.0.0]
>  0x00000001 (NEEDED)                     Shared library: [libcrypto.so.1.0.0]
>  0x00000001 (NEEDED)                     Shared library: [libboost_chrono.so.1.66.0]
>  0x00000001 (NEEDED)                     Shared library: [libboost_random.so.1.66.0]
>  0x00000001 (NEEDED)                     Shared library: [libc.so.0]
>  0x00000001 (NEEDED)                     Shared library: [libstdc++.so.6]
>  0x00000001 (NEEDED)                     Shared library: [libgcc_s.so.1]

`nm -D /ffp/lib/python2.7/site-packages/libtorrent.so | grep libiconv`
Returns nothing.

`readelf -d /ffp/lib/python2.7/site-packages/libtorrent.so | grep NEEDED`

>  0x00000001 (NEEDED)                     Shared library: [libtorrent-rasterbar.so.9]
>  0x00000001 (NEEDED)                     Shared library: [libboost_chrono.so.1.66.0]
>  0x00000001 (NEEDED)                     Shared library: [libboost_random.so.1.66.0]
>  0x00000001 (NEEDED)                     Shared library: [libc.so.0]
>  0x00000001 (NEEDED)                     Shared library: [libboost_system.so.1.66.0]
>  0x00000001 (NEEDED)                     Shared library: [libboost_python.so.1.66.0]
>  0x00000001 (NEEDED)                     Shared library: [libssl.so.1.0.0]
>  0x00000001 (NEEDED)                     Shared library: [libcrypto.so.1.0.0]
>  0x00000001 (NEEDED)                     Shared library: [libpython2.7.so.1.0]
>  **0x00000001 (NEEDED)                     Shared library: [libiconv.so.2]**
>  0x00000001 (NEEDED)                     Shared library: [libstdc++.so.6]
>  0x00000001 (NEEDED)                     Shared library: [libgcc_s.so.1]

For some reasons python bindings lib is linked to libiconv, but main library libtorrent-rasterbar.so.9.0.0-not.

**Comment by barmalej2** [comment]
Compilation --with-libiconv-prefix=/ffp didn't help either. The same error due to missing linking appeared.
Solved for myself by adding LDFLAGS="-Wl,--as-needed -liconv -Wl,--no-as-needed", but as I mentioned already that wasn't necessary for earlier versions  of libtorrent (at least for 1.1.2 9a63d46).

**Comment by arvidn** [comment]
do you know how to fix the configure script to make this work?

**Comment by barmalej2** [comment]
Unfortunately I don't. That is beyond my knowledge.

**Comment by ssiloti** [comment]
@barmalej2 What happens if you replace `$LIBICONV` on line 499 of `configure.ac` with `$LTLIBICONV` then do a `./bootstrap.sh && configure`?

**Comment by ssiloti** [comment]
Actually that's probably not going to work. While libtorrent does use libtool, it doesn't use it for linking. Basically there's something funky going on because libiconv.so is not in a standard library directory so autotools is trying to use rpath to link with it and failing. I'm not familiar enough with autotools to get any further than that. I don't think this is a regression because the relevant m4 macros haven't changed since long before 1.1.2.

**Comment by ssiloti** [comment]
Last comment I promise. I just noticed that 4923effe23a74b6bafa2c7c4d907c1489791ce28 made the reverse of the change I suggested initially so that might explain the change in behavior.

**Comment by arvidn** [comment]
so this is related to https://github.com/arvidn/libtorrent/issues/2465 then
