### ISSUE TITLE
Individual file hash DHT

### ISSUE THREAD

**Issue by rybazeza** [arvidn/libtorrent#2782]
Hi, as I'm a programmer myself using torrent softwares for years but new to the torrent protocols (excuse me if I used wrong terminology).. 

Problem statement:
One thing I really noticed is how fragmented and redundant torrent swarms have become. Similar file exists in multiple different torrent and seeding one torrent doesn't help another torrent although they have the same file. This leads to the inevitable death of a swarm when seeders eventually leave.

Current solutions:
One solution implemented is swarm merging which users can downloads similar files from different torrent swarms. But this I feel is very clunky and hackish as you'll have to find another torrent with exactly the same file (how to be certain it's the same file? The file could be the same but different name and vice versa) then download it separately. 

Another solution is from bitcomet, which from my experience is wonderful but have it's caveats. Once file is downloaded, the file hash is uploaded to their server (the negative) so if another user downloading the same file based on it's hash, the server sends the user to be used as seed. It's done automatically but the protocol is proprietary and no information is released for that.

Proposed solution:
So what I proposed is using/include file hash using/extending/"creating a separate" DHT to find seeders or peers based on file hash. The current system uses infohash of torrent files to search for peers which in my opinion is pretty outdated and needs updating. Each file hash can easily be included in the torrent file.

Preemptive arguments;
1. Privacy
Some will argue it will publish to much info on what we're downloading but if privacy is concerned, DHT should not be used anyway. Others can still know what you're downloading based on the infohash.

2. Heavy traffic 
It'll be heavier than infohash DHT since publishing individual file hash is more.than single infohash. Yes it will, but current technology have advanced since the time DHT is first introduced and the average Internet speed has increased and become cheaper so why not?

Closing statement:
Torrent scene has become very redundant as many files are placed in different torrents and seeded separately leading to rapid deaths of old torrents. In dead torrents, file can still be found elsewhere in another seeded torrents and this solution gives it a second chance to live. Regarding the downsides of my proposed solution, those who have slow connection can opt out, disabling it similar to DHT, but the up side can reduce redundancy in the torrent swarms. 

Sorry if this is inappropriately posted here but it's something in my head a long time and needed to share it. I can go out make a new client with this new protocol myself but it's pointless if there's no wide user base or big client names adopting it.

Thanks for reading :)

**Comment by arvidn** [comment]
two questions come to mind:

1. I think you may be dismissing the "heavy traffic" argument a bit lightly. There are torrents with tens of thousands of files. Most normal bittorrent clients *break down* announcing that much to the DHT. (as an experiment, try seeding 45000 torrents and see which clients hold up. Now, most torrent UI's will probably break first though). But I'm suggesting that this is a non-trivial challenge, not only because of network traffic, but also from a scalability of client software point of view. There may be some heuristics to mitigate this problem. For instance, one could imagine only files larger than some threshold are announced like this.

2. Let's say you have a way to lookup file-hashes to peers that host them. I take it you would really map them to info-hashes, and then you would look up the peers from there. Otherwise you wouldn't be able to connect to a peer, not knowing what info-hash you're talking about. Anyway, how would you know the file hash of the file you're interested in downloading? All you have are its piece-hashes. And until we have bittorrent v2, piece hashes are likely to overlap with other files. With bittorrent v2, you could use the merkle-tree root of a file as its file-hash. This still requires cooperation from the people creating the torrents though (to create v2 torrents).

**Comment by cathalgarvey** [comment]
Can I just revive this, a bit? :)

I don't think Bittorrent needs to solve this problem alone. There are loads of other DHTs out there that map hashes directly to files or archives: Bittorrent is actually the exception, for mapping hashes to metadata and to pieces, instead.

So, Bittorrent _does not have to have a DHT for hashes_. It only has to _point to stuff in other DHTs by providing hashes_. Someone writing a client for Bittorrent who wants to take advantage of this can then incorporate another DHT if they choose to.

For example: If a torrent file contained an additional metadata block containing `sha1` and `ripemd` sums for the files in the torrent, and the swarm had decayed and no longer had a whole file from the torrent, a client (or even, a capable user) could look up the missing file on IPFS, GNUnet, or Gnutella, significantly improving the odds of successfully repairing the whole swarm.

This would also, if indexed, assist in locating torrents containing the same files, allowing indexers (and clients that might query these indexers) to nudge people seeking torrents to more healthy swarms containing the same files.

If a standard for hashing individual files were adopted, it _should_ also support less concrete systems, like perceptual hashing, which could further assist in keeping the torrent ecosystem healthy and avoiding/identifying duplicates, even when the file hashes are different. Reserving a flag to indicate whether a hash is considered secure, or simply informational, would be helpful for this, and might also be useful for marking broken hash algorithms as merely informational at a later date, such as for `md4` (if used for mirroring to emule, etc.).

**Comment by ssiloti** [comment]
[BEP 47](http://bittorrent.org/beps/bep_0047.html) already defines a way to add attributes to files in the info dict. One of the examples given in the BEP is the file's sha1 hash.

**Comment by cathalgarvey** [comment]
Hi @ssiloti - I'm aware that a new torrent, at time-of-creation, can add metadata to the infodict. Unfortunately, hashing data is rarely included AFAIK. Also, adding this information after the fact, will change the infohash of the torrent, which prevents it from being used to reseed old or incomplete swarms.

Having a format or standard that allowed swarms to exchange hash information (for example, if one user knew the hash of a file from downloading a hash-enabled torrent, but most other swarm users did not know the hash) without changing the infohash would enable the whole swarm to become hash-aware, and then potentially a user might join the swarm who is bridging torrents and (for example) IPFS or similar, allowing the whole swarm to recover the full torrent data via this user. Without requiring the rest of the swarm to know or support any new features.

**Comment by arvidn** [comment]
If clients accept unverified hashes from peers (or untrusted .torrent files), you have to consider what a malicious client can do, and ways to mitigate it

**Comment by latot** [comment]
Hi!, there seems to be several ways, in one part when a torrent complete a file we should be able to get the file-hash and share it, with that info in the network we should be able to check and download or seed with other torrents similar files, but that files should not be available to the user, until is checked with the hash of the original torrent, we should need the rest of the parts but we would be able to optimize this if they are really the same file.

Other idea, when a torrent is completed create again the .torrent file in v2 (i read above they have file-hash) and use that torrent internally, then when we start a new torrent, request to peers the torrent file (like if we don't have the file only the magent link), and found if someone have the v2, and if some peer complete the torrent wait (the torrent need to be created) and request again the torrent file.

Note, when we request the torrent files all data should match except the file-hash (we don't have that info) with out file and between the others.

The malicious clients here can have a negative effect, if not all the clients take a way to check this, ppl can explode this, in that case the network will increase with fake files and attemps to hack, there would be necessary first always check a completed fragment, when a fragment from a client doesn't match, first request to the client check the piece, if say is right and there is the same problem with other pieces or the same piece with other clients for example ban the ip probably a fake file.

Hope this can help in some way.
Bye.
