### ISSUE TITLE
Question - Alerts do not start

### ISSUE THREAD

**Issue by gobne** [arvidn/libtorrent#2783]
libtorrent version (or branch): 1.1.6

platform/architecture: x64

compiler and compiler version: MSVC 2015

Hi,
I've recently switched from an old master to the 1.1.6 one.

Everything works properly but these 3 alerts:
external_ip_alert
dht_bootstrap_alert
listen_succeeded_alert
don't be thrown anymore.
Is it normal or may I miss something important?

Thank you guys :)

**Comment by sledgehammer999** [comment]
Have you included the `status_notification` and `dht_notification` in the alert mask?
List of categories: https://libtorrent.org/reference-Alerts.html#category_t

**Comment by gobne** [comment]
I have this instruction:

session->post_torrent_updates(lt::alert::all_categories);
It was working until I changed branch.

**Comment by sledgehammer999** [comment]
That is wrong.

post_torrent_updates() [docs](https://libtorrent.org/reference-Core.html#post_torrent_updates()):
>void post_torrent_updates (boost::uint32_t flags = 0xffffffff);
>
>This functions instructs the session to post the state_update_alert, containing the status of all torrents whose state changed since the last time this function was called.
>
>Only torrents who has the state subscription flag set will be included. This flag is on by default. See add_torrent_params. **the flags argument is the same as for torrent_handle::status(). see torrent_handle::status_flags_t.**

And `torrent_handle::status_flags_t` can have [these](https://libtorrent.org/reference-Core.html#status_flags_t) values.

Instead you need to do something like this:
```c++
lt::settings_pack pack;
pack.set_int(libt::settings_pack::alert_mask, lt::alert::status_notification | lt::alert::dht_notification);
lt::session ses(pack);
```
(of course use your other categories in the mask too)

**Comment by gobne** [comment]
It works!
Thanks a lot :)

**Comment by arvidn** [comment]
sorry about that. the next major release of libtorrent (1.2) will make that mistake a compilation error!
