### ISSUE TITLE
build python binding for windows

### ISSUE THREAD

**Issue by David-Luis** [arvidn/libtorrent#2784]
Using the command as the documentation say:
`python setup.py build`
seems to do nothing. Adding --bjam at the end of the command tries to do the proper thing...

I'm wrong or the documentation is not ok?

**Comment by arvidn** [comment]
you are correct. windows builds use boost-build. This is because, at least traditionally, python has required a specific version of msvc for compiled modules for ABI compatibility. If you can come up with improvements for the documentation, pull requests are welcome!

**Comment by David-Luis** [comment]
Thx arvidn, since I have it working right now, I will create a pull request with the steps for windows, cheers!
