### ISSUE TITLE
Python 3.3 binding not working in Conda Env

### ISSUE THREAD

**Issue by vaibhav6233m** [arvidn/libtorrent#2785]
**Please provide the following information**

libtorrent version (or branch):
1.1.6
platform/architecture:
Ubuntu 16.04 64-bit
compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
I created a virtualenv using conda and built the libtorrent library on Python 3.3 using the post provided here.
http://dreamingpotato.com/2015/11/21/how-to-install-python-libtorrent-in-virtualenv/

The build was completed successfully. But when I try to run the script I get this 

```
import libtorrent as lt
ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0: undefined symbol: PyClass_Type
```
What could be the reasons for that?

It works flawlessly on python 2.7 though.

I am looking for a proper python 3.3 binding. Anything on this would be so helpful, Thanks.

![screenshot from 2018-02-12 14-01-51](https://user-images.githubusercontent.com/29979122/36088461-6446d952-0ffd-11e8-9beb-38711363ef2b.png)

**Comment by arvidn** [comment]
I'm not a python expert and I'm not intimately familiar with what conda environments do. But I suppose they have their own mirror of all python modules, and presumably all runtime dependencies  of those modules. in the case of libtorrent, that means the main libtorrent library, boost python possibly SSL (libcrypto, libssl), boost.system_error, boost.random (and possibly some other boost libraries). The specific details depend a bit on the version of libtorrent.

**Comment by arvidn** [comment]
in your case, is it possible that boost.1.58 is too old for the python3 module? you may want to try a more recent version of boost. say 1.65

**Comment by zzzhr1990** [comment]
In some case, if you use setup.py, it could not find lboost_python3 on some systems, instead, it build boost pythonbinding as python2 lib (when you configure, you will find lboost_python found but not lboost_python3). so you have to specify lboost_python3 path and version. 
On different systems lboost_python3 have different name, like CentOS7, It's name is lboost_python34.
