### ISSUE TITLE
need openssl1.1.1 fix

### ISSUE THREAD

**Issue by kslr** [arvidn/libtorrent#2791]
**Please provide the following information**

libtorrent version (or branch):
1.1.6
platform/architecture:
amd64
compiler and compiler version:
gcc 5.4 
libboost 1.58
OpenSSL 1.1.0g
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
```shell
 python -c "import libtorrent; print libtorrent.version"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/local/lib/libtorrent-rasterbar.so.9: undefined symbol: SSLv23_client_method
```
try ./configure --enable-python-binding --with-libiconv --with-openssl=/usr/local/openssl-1.0.2n
Compiled by, but can not work.
If downgrade Openssl will bring a lot of trouble
So if there is any upgrade plan?

**Comment by LiMinggang** [comment]
It's most likely an issue of your config for compiling. My C++ version is OK with libtorrent master, boost 1.66, OenSSL 1.1.0g.
SSL is wrapped by asio from boost. libtorrent does not call it directly.

**Comment by kslr** [comment]
@LiMinggang boost OenSSL?

**Comment by LiMinggang** [comment]
Typo, OpenSSL
