### ISSUE TITLE
Duplicate peer resolution broken in the SSL mode

### ISSUE THREAD

**Issue by mkatsevVR** [arvidn/libtorrent#2792]
libtorrent version (or branch): 1.0.11 (although the code looks unchanged, so I suspect the same issue is present in 1.1)

platform/architecture: Linux

compiler and compiler version: gcc 5

Using the SSL mode, I've noticed a occasional (in the sense that it doesn't happen every time, but when it does happen, it persists until restart) occurrence of 2 peers being unable to maintain connection. In the logs on both sides I see this every 1 minute exactly:

```
peer_connect_alert: peer ([hostA]:4433, Unknown) connecting to peer (SSL/TCP)
incoming_connection_alert: incoming connection from [hostA]:51599 (SSL/TCP)
peer_disconnected_alert: peer ([hostA]:51599, libtorrent 1.0.0) disconnecting: [libtorrent error] duplicate peer-id
peer_disconnected_alert: peer ([hostA]:4433, libtorrent 1.0.0) disconnecting: [asio.misc] End of file
```

My theory is that for some reason both clients get in a loop where they retry to connect to each other every minute. The current implementation decides which connection to drop based on the remote port number, which is always the same with SSL, so both ends decide to drop the other connection at the same time thus continuing the loop. https://github.com/arvidn/libtorrent/blob/libtorrent-1_0_11/src/policy.cpp#L1017

I can mitigate this by selecting the SSL listening port randomly on startup instead of using 4433 as default, but there is still a chance of 2 clients picking the same port and being unable to talk to each othe. The comment above this code explicitly mentions only using the listening port instead of outgoing one, but I don't understand why. AFAICT the fact that the outgoing port is different each time is good, since it means the conflict can only be intermittent but not permanent.

**Comment by arvidn** [comment]
actually, the comment suggests the intention was to compare the full endpoint, including the IP. I believe that would actually solve the problem too.

**Comment by arvidn** [comment]
I'm tempted to "fix" this by rolling a die with a 50/50 chance, when the ports are the same. Perhaps there should be a bias against the new incoming connection, in case they aren't happening simultaneously.

**Comment by arvidn** [comment]
here's a fix against RC_1_1 (please feel free to apply it against RC_1_0 and test it). I imagine it would apply by just changing the filename to ``policy.cpp``. https://github.com/arvidn/libtorrent/pull/2796

**Comment by mkatsevVR** [comment]
On 2nd thought, looks like the double disconnects are actually coming from here  https://github.com/arvidn/libtorrent/blob/master/src/bt_peer_connection.cpp#L3193. You're right that it looks at peer id, but the condition is wrong, as both ends close the incoming connection. It should be something like `if ((pid < m_our_peer_id) == is_outgoing())` instead.

Not sure if the changes in peer_list/policy are still needed.

**Comment by arvidn** [comment]
you're right. I'll fix that too.

**Comment by mkatsevVR** [comment]
Did more testing. For me, just the single-line change in bt_peer_connection fixes the issue, the rest is not needed. 

Note that I have `allow_multiple_connections_per_ip` enabled, which seems to affect the logic in peer_list.cpp/policy.cpp and likely prevents the case with equal port numbers from happening. That is to say that I haven't tested the 2nd half of the changes and can't say if they are needed or not in some other configurations.

Related, why do these duplicate connections happen in the first place? I see frequently clients trying to connect to other peers that they already have a connection with. Is this intended?

**Comment by arvidn** [comment]
I think the first fix is an improvement still, so I would like to keep it.
The reason you see an outgoing connection to a peer you're already connected to is that since you allow multiple peers per IP, libtorrent doesn't know for sure that they are the same peer. They may be different peers running on the same IP.

It's not very common to enable that option, so it doesn't get a lot of testing.

**Comment by mkatsevVR** [comment]
> They may be different peers running on the same IP.
But the port is also the same. Is that not sufficient to prevent the connection?

**Comment by arvidn** [comment]
well, for uTP I would expect that to be the case, and at least in theory possible to distinguish from a separate peer. But the source port of an incoming TCP connection is very different from the listen port of that peer.

**Comment by mkatsevVR** [comment]
Ah, right, so if A has connected to B, B would still try connecting to A since the port number is different. Perhaps it could be avoided by caching the peer id after the first connection attempt was rejected due to the duplicate peer? But then you need to invalidate the cache somehow if another client pops up on the same port later... Probably not worth the added complexity if this option is not frequently used.

**Comment by arvidn** [comment]
That's correct, this is why the default is to treat an IP as a single peer by default. It keeps things simple.
This issue has been fully addressed, right?

**Comment by mkatsevVR** [comment]
i've applied the one-line bt_peer_connection change to 1.0 and it solved my problem, so yes as far as I'm concerned.
