### ISSUE TITLE
Not a developer. Need help in finding LIBTORRENT expert

### ISSUE THREAD

**Issue by mmazzilli73** [arvidn/libtorrent#2806]
Hi to everybody.
Sorry if I might be doing this wrong but I am not a developer and I am new to GitHub.
I am looking for somebody that can help me (free or paid) to complete a p2p bit torrent project based on Libtorrent. A freelance that was working got me to some point but the quit as he was encountering problems and also wanted to move on another project so I am stuck in the middle. I can't find specific expertise on websites like UpWork or Freelancer.org so that's why I am here

Is this the right place to post this message? If not please address me where you think is best.
Thanks, Marcello

**Comment by vitor-alves** [comment]
Do you still need it? Im not an expert, but I have been working with libtorrent for some time
