### ISSUE TITLE
C++ Signature mismatch for python bindings of connect_peer

### ISSUE THREAD

**Issue by combecn** [arvidn/libtorrent#2807]
error message:

Traceback (most recent call last):
  File "btfs.py", line 540, in <module>
    b = Btfs(args.torrent_file, args.mount, peers=ip_list)
  File "btfs.py", line 154, in __init__
    self.torrent_handle.connect_peer(peer, flags=0x02)
Boost.Python.ArgumentError: Python argument types in
    torrent_handle.connect_peer(torrent_handle, str)
did not match C++ signature:
    connect_peer(struct libtorrent::torrent_handle {lvalue}, class boost::python
::tuple, int)

libtorrent version (or branch):
1.1.6
boost 1.66
platform/architecture:
Windows 7 64bit
Python 2.7.14 32bit

compiler and compiler version:

my code:
```
        params = {"max_connections": -1, "download_limit": -1,
                  "ti": self.torrent_info,
                  "save_path": os.path.sep.join([mount_point, "__btfs__"])}
        self.torrent_handle = self.session.add_torrent(params)
        for peer in peers:
            self.torrent_handle.connect_peer(peer, flags=0x02)
```
peers is a list contains a lot of seeding ip.

**Comment by arvidn** [comment]
the convention in python (as far as I understand) is to represent endpoints as a tuple of an IP/hostname string and a port integer. The python bindings use this same convention. So, ``connect_peer`` takes a (str, int) tuple.

Please let me know if that doesn't work!

**Comment by combecn** [comment]
I change the code as followings:
`        for peer in peers:
            self.torrent_handle.connect_peer((peer, 6881), 0x02)`
No error prompts.

but if I change code as followings:
`        for peer in peers:
            self.torrent_handle.connect_peer((peer, 6881), flags=0x02)`
Same error prompts.

Anyway thank you for your reply!

**Comment by arvidn** [comment]
could you try this patch? https://github.com/arvidn/libtorrent/pull/2832
note that the argument you're passing there is not "flags" it's "sources". The this patch fixes that.

**Comment by combecn** [comment]
Tried. The patch works. Thanks a lot!
