### ISSUE TITLE
Determine if torrent is added from resume data

### ISSUE THREAD

**Issue by aresch** [arvidn/libtorrent#2809]
libtorrent version (or branch): master

When adding torrents from resume data there is currently no way to determine, from libtorrent, if this torrent was added by resume data or not.  The add_torrent_alert does contain the add_torrent_params, but it does not include the resume_data so that can't be used.  In my case, I use the add_torrent_alert to initiate a save_resume_data() call so that resume data is immediately written for newly added torrents, but this causes unnecessary load on start-up when resume data is loaded (and subsequently rewritten).

Currently, a client program could keep a list of info-hashes added from resume data, but that can involve some race conditions where the alert handler fires before the state is updated (in the case where you append this info-hash after add_torrent()) and some additional management if the torrent fails to add. Not big deals, but not terribly elegant either.

**Proposal:**

Add another field to add_torrent_alert to indicate if torrent was added by resume data.

**Example**
My add_torrent_alert handler would then look as follows:
```python
async def on_add_torrent_alert(self, alert):
    if not alert.from_resume_data:
        alert.handle.save_resume_data()
```

**Comment by Col-blimp** [comment]
You don't need to use the `add_torrent_alert` for initial resume data creation as you can use `write_resume_data_buf()` with an `add_torrent_params` before the torrent hits the session.

```
#include "libtorrent/read_resume_data.hpp"
#include "libtorrent/write_resume_data.hpp"
```

**Comment by aresch** [comment]
Yes, that is another option or I suppose I could just call torrent_handle.save_resume_data() after the add_torrent() although that wouldn't work with add_torrent_async().

**Comment by Col-blimp** [comment]
There is `added_time` from `torrent_status` that's consistent across resumes also so you can get a good idea if its not a new torrent.

**Comment by aresch** [comment]
Writing the resume data without waiting for the add_torrent_alert gets a bit mucky when doing an async add for the same reasons I mentioned (management of state). For example, if the resume data is written (or in the process of) and the torrent fails to add, the client then needs to delete the resume data (and perhaps wait on the initial write to finish). It's beneficial to write the resume data when you know that the torrent has been added successfully since I use the resume data as the only record of which torrents are in the session.

In my case, I am doing synchronous adds, so I can use the method @Col-blimp suggested, but I wonder if there are any other cases where knowing how the torrent as added in add_torrent_alert could be useful.

**Comment by aresch** [comment]
Yes, I thought about using added_time too but I was worried that it wouldn't be the most precise way to determine how it was added.  I could just check if (now - added_time) is greater than a few seconds and that would likely work for virtually all cases, but it would still fail when:

* add a torrent
* quickly save and stop the session
* create session and load resume data

I know this scenario is likely to never occur.. I was just trying to think of a cleaner way to handle this and storing an additional boolean in the alert would do it without too much added cost.

**Comment by ssiloti** [comment]
One way to do this is to use the `userdata` member of `add_torrent_params` to indicate that the torrent was added from resume data.

**Comment by aresch** [comment]
That doesn't appear to be exposed in the Python bindings.

**Comment by arvidn** [comment]
keep in mind that in master, the ``add_torrent_params`` object *is* the resume data (as I'm moving towards parsing resume data before adding the torrent to a session). So the new flow (which I recognise you can't really move to until master is released and support for older versions is dropped) is to ``read_resume_data()`` and get an ``add_torrent_param`` object. You can then put stuff in there that you then recognise when you get it back in the alert. the ``userdata`` field is a reasonable idea, but there may be other fields too.

but it seems reasonable to expose the userdata field as an integer perhaps. it could be treated as a ``uintptr_t`` for the purposes of python

**Comment by aresch** [comment]
I am using the new flow in Spritzle (see https://github.com/spritzle/spritzle/blob/master/spritzle/core.py#L119).

Yes, having the userdata field exposed would be great. Going a bit further, it would be nice if there was a userdata field on the torrent_handle too.. Having it store an arbitrary object would be the most ideal situation, ie, being able to store a python dictionary.  Having that data stored in the resume data would be fantastic. Not sure if that would be easily feasible though.
