### ISSUE TITLE
building libtorrent under python 3.6.4 64bit failed

### ISSUE THREAD

**Issue by combecn** [arvidn/libtorrent#2813]
**Please provide the following information**

libtorrent version (or branch):
1.1.6

platform/architecture:
Windows 10 64bit
Python 3.6.4 64bit
Boost 1.66

compiler and compiler version:
MSVC Community 14.11.25503

STEP 1, change  /setup.py for python 3 compatible:
C:\tmp\libtorrent-rasterbar-1.1.6
line 5:
`execfile('setup.py') `
change to: 
`exec(open('setup.py').read())`

STEP 2, change /bindings/python/setup.py to build a 64bit
C:\tmp\libtorrent-rasterbar-1.1.6\bindings\python\setup.py
line 79
`			toolset = ' msvc-9.0'`
change to:
`			toolset = ' msvc'`

line 85:
`		cmdline = 'b2 libtorrent-link=static boost-link=static release optimization=space stage_module --abbreviate-paths' + toolset + parallel_builds`
change to:
`		cmdline = 'b2 libtorrent-link=static boost-link=static release optimization=space stage_module architecture=x86 address-model=64 --abbreviate-paths' + toolset + parallel_builds
`

STEP3: run following command to build:
`python setup.py install --bjam`

Then build report a lot of link errors:
...patience...
...patience...
...patience...
...found 5450 targets...
...updating 4 targets...
msvc.link.dll bin\msvc-14.1\rls\adrs-mdl-64\archt-x86\bst-lnk-sttc\lbtrn-lnk-sttc\optmz-spc\libtorrent.pyd
   Creating library bin\msvc-14.1\rls\adrs-mdl-64\archt-x86\bst-lnk-sttc\lbtrn-lnk-sttc\optmz-spc\libtorrent.lib and object bin\msvc-14.1\rls\adrs-mdl-64\archt-x86\bst-lnk-sttc\lbtrn-lnk-sttc\optmz-spc\libtorrent.exp
module.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) struct _object * __cdecl boost::python::detail::init_module(struct PyModuleDef &,void (__cdecl*)(void))" (__imp_?init_module@detail@python@boost@@YAPEAU_object@@AEAUPyModuleDef@@P6AXXZ@Z) referenced in function PyInit_libtorrent
error_code.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl boost::python::throw_error_already_set(void)" (__imp_?throw_error_already_set@python@boost@@YAXXZ)
datetime.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl boost::python::throw_error_already_set(void)" (__imp_?throw_error_already_set@python@boost@@YAXXZ)
peer_info.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl boost::python::throw_error_already_set(void)" (__imp_?throw_error_already_set@python@boost@@YAXXZ)
ip_filter.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl boost::python::throw_error_already_set(void)" (__imp_?throw_error_already_set@python@boost@@YAXXZ)
...

Please check details in the attachment.
[build.txt](https://github.com/arvidn/libtorrent/files/1761399/build.txt)

**Comment by ssiloti** [comment]
It seems Boost Python defines different libs for Python 2 and 3. Surprisingly, building `boost_python` against Python 3 silently fails. To make it work references to `boost_python` in `bindings/python/Jamfile` need to be changed to `boost_python3`. I'm still getting some unresolved symbols for some other reason though.

**Comment by arvidn** [comment]
oh, interesting. I've done some hacking by copying the python Jamtarget into the bindings/python Jamfile as well. I wonder if that's breaking anything.

**Comment by arvidn** [comment]
there is a boost-build feature called "python" which can be set to the version, it may be possible to use that and conditionally depend on ``boost_python`` or ``boost_python3``. But I would expect that to be done under the hood by just depending on ``boost_python``.

**Comment by ssiloti** [comment]
Turns out the remaining linker error where due to some stale object files which didn't get re-built. I can build the python bindings successfully now.

Official documentation for using boost with python3 appears to be non-existent. It looks like having to specify the python3 version of boost python explicitly is expected behavior.

Examining the boost python Jamfile shows why the build was silently failing to build boost_python: if a version of python is not available the corresponding target gets stubbed out to an empty alias. The Jamfile also shows how to detect which python version(s) are available which should make this a pretty easy fix.

**Comment by ssiloti** [comment]
@combecn please give #2879 a try
