### ISSUE TITLE
Libtorrent is not compiling with older android sdk version

### ISSUE THREAD

**Issue by alexandre-janniaux** [arvidn/libtorrent#2825]
**libtorrent version (or branch):**

Branch master, commit f98a7f3cf9698de10b721f49d3cf93b9771ef78d

**platform/architecture:**

Android sdk 15 / armv7

**compiler and compiler version:**

arm-linux-androideabi-gcc, generated with sdk version 15

**issue:**

Compiling libtorrent for android doesn't work with old sdk version, although it can. The problem is the config.hpp assume that it should use netlink and cpuid on Android whatever the sdk version is. However, NETLINK_ENOBUFS is not available until sdk21.

Moreover, ``sys/auxv.h`` doesn't exist, so I had to disable TORRENT_HAS_AUXV too but I didn't find if it has been available since a more recent sdk version yet. 

Is it possible to test the android sdk version so as to disable these features if the sdk is too old ? I can manage some time to write the patch if it's ok.

**Comment by aldenml** [comment]
In order to compile `master` you need a toolchain with support for c++11. You will need to migrate to a clang based NDK, there are still some quirks with API 16, but easy to solve

**Comment by alexandre-janniaux** [comment]
I'm sorry, actually it is arm-linux-androideabi-clang, both were available and I got confused. I'm able to build libtorrent with the fix I ask and make it works on android devices. The toolchain is the one generated by google's make_toolchain script with ``--api android-15``.

I don't use API 16 because it defines ``tdestroy`` but doesn't declare it, so I have to patch the configuration file to make it works.

**Comment by aldenml** [comment]
well, never heard of `tdestroy` before :) how is that it works with API 15 and not API 16? (strange). Also, make sure you are using the latest NDK

In order to make it work with API 16, I only need to do this hack:
```
echo "unsigned long int getauxval(unsigned long int type) __attribute__((weak));" >> $PWD/android-toolchain/sysroot/usr/include/sys/auxv.h;
...and...
sed -i 's/using ::fgetpos;//g' $PWD/android-toolchain/include/c++/4.9.x/cstdio;
sed -i 's/using ::fsetpos;//g' $PWD/android-toolchain/include/c++/4.9.x/cstdio;
```

**Comment by alexandre-janniaux** [comment]
Because the symbol is defined but not declared, and autotools is testing that the symbol links. So our compat library doesn't declare tdestroy. In SDK 15 it is neither declared nor defined, so our compat library handles it correctly. Currently, modifying the building scripts are a no-go for us (it could break things) so we are stuck bellow sdk 16.

What I mean in this issue is that libtorrent **works** with at least sdk 13, by disabling auxv and netlink for sdk versions between 13 and 21. As we are in this case, it would be really helpful not to have to patch libtorrent for android builds.

Actually, libtorrent could also emit an error or a warning if SDK < 13, because functions like pread64 don't seem to be implemented before. They have been added as a prerequisite for android since SDK 13.

**Comment by aldenml** [comment]
hmm...I see. What NDK version are you using? Are you targeting sdk 13 only for compilation, or is your device target in deployment that very same (old) API?

**Comment by alexandre-janniaux** [comment]
I'm using NDK version 14b. We currently support devices since (old) sdk 9 and targetting sdk 21, but toolchain depends on the minimum sdk version unfortunately. However, we can reach a sdk 15 toolchain for this module as it is not a core module and will be distributed separately.

**Comment by arvidn** [comment]
@alexandre-janniaux please feel free to propose a change in a pull request, to conditionally disables the features you mention for older versions
