### ISSUE TITLE
Disable unnecessary DNS queries on exit in Libtorrent 1.0 branch

### ISSUE THREAD

**Issue by ghost** [arvidn/libtorrent#2827]
**Please provide the following information**

libtorrent version (or branch):
1.0.11

platform/architecture:
Linux x86_64 & Windows

compiler and compiler version:
gcc 6 & MSVC 2017

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I am using qBittorrent with libtorrent 1.0.11, however it always hangs at exit. I read several issues and found that it is a problem caused by libtorrent and was fixed in the 1.1 branch. Will there be a backport fix to the libtorrent 1.0 branch?

**Comment by arvidn** [comment]
I don't really want to back-port this patch. I have a feeling it would pull a lot of other stuff with it into RC_1_0. I try to stick to no more than one supported stable branch at a time, which is 1.1.x.
