### ISSUE TITLE
Resume error after rechecking a completed torrent where the last file is prio-0

### ISSUE THREAD

**Issue by fbriere** [arvidn/libtorrent#2843]
libtorrent version (or branch): RC_1_1
platform/architecture: Debian/amd64
compiler and compiler version: gcc 7.3

When forcing a recheck on a completed torrent where the last file is set to priority 0, the recheck seems to work fine, but on the next restart, the resume file will trigger a "missing 'slots' and 'pieces' entry" error.

This appears to be due to how libtorrent considers the recheck to be finished once the last piece has been hashed; if the last file is at priority 0, that last piece is never hashed, the recheck is never deemed complete, and the resume data will omit the `pieces` entry.  (It doesn't matter whether that last piece was downloaded or not; as long as its priority is 0, it will be ignored.)

Actually, it seems that most data past the last non-priority-0 piece will be ignored during a recheck.  (In other words, if you download the last N files, and unselect them afterwards, most of them will recheck at 0%.)

(I first described this in https://github.com/arvidn/libtorrent/issues/2674#issuecomment-364246854, before realizing that it was not actually related to that issue.)

**Comment by arvidn** [comment]
Is this related to https://github.com/arvidn/libtorrent/pull/2842 ?

I suspect the checkin of torrents should completely ignore file priority (apart from deciding whether to look in the partfile or not).

Does that sound like a reasonable thing to do? As far as you understand, do you think that would fix the issue?

**Comment by fbriere** [comment]
If you're asking whether they are technically related, I don't really know.  However, the fact that they were both submitted around the same time was a mere coincidence; I was not aware of #2842 when I submitted this one.

**Comment by arvidn** [comment]
if you have the chance, please test this patch: https://github.com/d-komarov/libtorrent/pull/2

It's a pull request against a pull request against ``RC_1_1``. you could test it by just checking out ``d-komarov-test_checking`` from the libtorrent repo

**Comment by fbriere** [comment]
Yup, `d-komarov-test_checking` (d40e46e023b951ec44f07d572679eb0069034096) did the trick.  Thanks!

**Comment by arvidn** [comment]
addressed by: https://github.com/arvidn/libtorrent/pull/2842
