### ISSUE TITLE
Libtorrent seed always thinking peer is uninterested

### ISSUE THREAD

**Issue by Starkist** [arvidn/libtorrent#2845]
libtorrent version (or branch): master
platform/architecture: Windows 7/10, 64-bit
compiler and compiler version: boost-build 1.65_1 / msvc

The issue:

A libtorrent client_test.exe wouldnt connect to a second libtorrent client (a seed and a peer), but it does work in a libtorrent <-> bittorrent configuration in both directions (bittorrent seed -> libtorrent peer, libtorrent seed -> bittorrent peer)

I'm using the same network and computer configuration for all tests, my pc and a AWS virtual machine running windows server base 2016.

It seems that the source does not unchoke the peer looking at the logs, it considers the peer "uninterested", but it does unchoke a bittorrent client as said above. This makes me think that the issue might be some settings in settings_pack, however I'm unsuccessful in finding it in the past few days.. 

Please see attached log file.

Any ideas?

Cheers,
Michael.

[log_seed.txt](https://github.com/arvidn/libtorrent/files/1815999/log_seed.txt)

**Comment by arvidn** [comment]
why did you close this? was it a mistake?
