### ISSUE TITLE
Tuning for streaming in low-latency RT application

### ISSUE THREAD

**Issue by fernando-rodriguez** [arvidn/libtorrent#2847]
**Please provide the following information**

libtorrent version (or branch):
1.1.6
platform/architecture:
Linux/ARM
compiler and compiler version:
GCC 5.4.0

I'm working on an streaming application using realtime scheduling. I have all libtorrent threads running at the lowest realtime priority, then just above that I have the alerts thread and a readahead thread that calls torrent_handle.read_piece() repeatedly and waits for the request to complete. Then I have several high priority threads above that.

The first problem I'm having is that the overhead of the async call to read_piece is too much. Ideally I would love to have a way to bypass the round trip to the main thread entirely and read the piece as fast as possible. Otherwise is there a way to prioritize reads and boost the realtime priority of the IO thread while the request is pending? Perhaps having a dedicated thread IO queue and thread for reads?

The second problem is that when downloading (with libtorrent at the lowest priority) it kills the latency of my higher priority threads so I'm interested in the optimal settings for a low-latency real-time environment (ie. keeping IO syscalls as short as possible).

Thanks in advance.

**Comment by arvidn** [comment]
if you use [set_piece_deadline()](https://libtorrent.org/reference-Core.html#set_piece_deadline()) you can set the flag to get the piece date posted as an alert when it becomes available. that should save you some round-trips at least.

as for the latency introduced by libtorrent, I suspect it's primarily a matter of memory pressure (but I could obviously be wrong about this). I would suggest you profile the libtorrent network thread to see where it's spending a lot of time. If you're lucky there are features you can disable to lower memory pressure/footprint.

I would be interested in any profiles you produce.

**Comment by fernando-rodriguez** [comment]
Thanks for the reply. I remember trying the alert_when_available flag when I started working on this. I moved away from it because it would require some re-ordering of pieces and the round trip was no issue on x86 so I totally forgot about it but I can work with that, thanks. Would that alert be triggered by the same event as piece_finished_alert? Also (OT) what exactly happens when a piece deadline is not met? I've been setting the deadline of the first piece that I want to 250ms and then adding 10ms to the next piece and so on. This seems to work fine, is it ok?

Do you mean memory pressure in the network stack in the kernel? My realtime threads are using pooled memory (no swap and no faults during playback) and once it gets to run it completes in less than 500us but wake up latencies of around 80ms are common while downloading with a worst case of over 500ms. I've managed to tune my code to make it almost inperceptible except for the rare worst cases so the first problem is my priority right now but eventually I will do some proper profiling of the libtorrent threads. I think I noticed by browsing libtorrent's code that all writes are done in block_size chunks but I haven't found yet where it comes from. Is it tunnable? I'm interested in seeing how changing it affects latency.

**Comment by fernando-rodriguez** [comment]
Actually I haven't tried it yet I don't think the alert_when_available flag alone will solve my problem. It happens with pieces that we got long ago (seconds). So it's not really the round trip to your main thread but waiting for the piece to be read. It's a kind of priority inversion because as long as there is work to do on other threads the piece won't be read and then it has to contend with all libtorrent threads for the CPU. I'm very CPU constrained so the result is that many times the piece won't be read until the readahead queue is empty.

What I really need is a way to read the piece synchronously from my own thread. Bypassing your main and IO threads but (if possible) using your cache. What are your thoughts on that?

Or is there a way to tell if the piece has been flushed to disk either synchronously or through alerts? If there is then I can probably use a combination of using the alert_when_available flag to save the pieces directly to my readahead queue when possible, then when a piece needs to be read if I know it's flushed I can just read it myself.

If I disable caching, would the pieces be guaranteed to be flushed to disk when I receive the piece_received_alert? If so what settings do I need to set?

**Comment by arvidn** [comment]
> Would that alert be triggered by the same event as piece_finished_alert?

I believe so, yes.

> Also (OT) what exactly happens when a piece deadline is not met?

The piece deadline is used for two things:

1. As a priority of which piece to get next
2. Deciding to put off making it a priority to get the piece (if the timeout is set far enough in the future)

So, as soon as the deadline is within some reasonable time (based on the average download time of pieces) it will just be used as a priority. pieces with an earlier deadline has higher priority, regardless of whether it has expired or not.

> I've been setting the deadline of the first piece that I want to 250ms and then adding 10ms to the next piece and so on. This seems to work fine, is it ok?

That should be fine. In an ideal world, if you know the bitrate of the media you're streaming you would set the deadline based on that. The more accurately you set the deadline the more opportunities will libtorrent have to download rarest first in between.

> Do you mean memory pressure in the network stack in the kernel?

I mean pressure on the L1/L2/L3 caches as well as the TLB. My experience is that some ARM chips have very small memory caches compared to commodity x86 chips.

> My realtime threads are using pooled memory (no swap and no faults during playback) and once it gets to run it completes in less than 500us but wake up latencies of around 80ms are common while downloading with a worst case of over 500ms.

When you say "wake up", you mean the latency between an interrupt and your process being on-cpu? 500ms sounds very long, much more than what one would expect a RAM cache miss to cost. Are there other, more costly, things a thread can do to mask interrupts or prevent a context switch? A system call would allow de-scheduling a thread, right?

> I've managed to tune my code to make it almost inperceptible except for the rare worst cases so the first problem is my priority right now but eventually I will do some proper profiling of the libtorrent threads. I think I noticed by browsing libtorrent's code that all writes are done in block_size chunks but I haven't found yet where it comes from. Is it tunnable?

The smallest granularity is a block size (16384 Bytes), but reads and writes are done with pread() and pwrite(), so normally more than one block per system call. However, a piece size is the largest write-size, so small pieces will be written in single syscalls.

> [...]
> What I really need is a way to read the piece synchronously from my own thread. Bypassing your main and IO threads but (if possible) using your cache. What are your thoughts on that?

In theory it would be possible to access the cache from another thread. It's accessed by the network thread under the cache mutex. It would require some pretty serious surgery on the code though.

A future version I've been working on for a while (in a branch called new-disk-io) the disk cache is removed and replaced by memory mapped files, so it's relying on the page cache, which would make it easier to access from the outside. This is quite far out though.

> Or is there a way to tell if the piece has been flushed to disk either synchronously or through alerts?

I can't think of a way to tell. But libtorrent doesn't fsync() any data, so it would be possible for the data to not be available immediately after a flush too. But I suppose on linux it would be in the page cache immediately.
>
> If I disable caching, would the pieces be guaranteed to be flushed to disk when I receive the piece_received_alert? If so what settings do I need to set?

No, that alert is posted to the client at the same time as the asynchronous write operation is posted to the disk queue. I don't think there's an alert for when the write operation has completed.

**Comment by fernando-rodriguez** [comment]
On 03/15/2018 08:39 PM, Arvid Norberg wrote:
> That should be fine. In an ideal world, if you know the bitrate of the media you're streaming you would set the deadline based on that. The more accurately you set the deadline the more opportunities will libtorrent have to download rarest first in between.

Thanks, that clears it.

> When you say "wake up", you mean the latency between an interrupt and your process being on-cpu? 500ms sounds very long, much more than what one would expect a RAM cache miss to cost.

Yes, that is what I mean.

> Are there other, more costly, things a thread can do to mask interrupts or prevent a context switch? A system call would allow de-scheduling a thread, right?

AFAIU a thread is de-scheduled when you call a system call that sleeps, when it calls sched_yield() or when the timeslice expires (unless it's on a SCHED_FIFO policy which doesn't expire until a higher priority threads becomes runnable).

A thread cannot disable interrupts while executing on user mode. When you make a syscall the kernel may disable them for an undetermined amount of time that depends on the kernel configuration. I was off-track in looking at the block_size, writing large block would only put your thread to sleep longer (iowait) and mine would get the CPU. But with caching enabled the kernel will have to do a lot of work when it comes time to flush it and it may happen during any thread's timeslice. I will disable the write cache (with the sync and dirsync mount options) and do some profiling tonight. It probably won't be good for my "disk" since it's an SD card or eMMC.

> No, that alert is posted to the client at the same time as the asynchronous write operation is posted to the disk queue. I don't think there's an alert for when the write operation has completed.

Can you offer any pointers on adding one? And are you interested in the patches? I think this would be the simplest way to solve my problem and it may even perform better than accessing your cache directly since Linux can still do read caching with the sync option, once the download gets far enough all reads will be sequential, and once a piece gets to your cache it will likely also be in the OS cache and can stay there longer since it can use all available memory.

**Comment by arvidn** [comment]
>> Are there other, more costly, things a thread can do to mask interrupts or prevent a context switch? A system call would allow de-scheduling a thread, right?
>
> [...]
>A thread cannot disable interrupts while executing on user mode. When you make a syscall the kernel may disable them for an undetermined amount of time that depends on the kernel configuration. I was off-track in looking at the block_size, writing large block would only put your thread to sleep longer (iowait) and mine would get the CPU. But with caching enabled the kernel will have to do a lot of work when it comes time to flush it and it may happen during any thread's timeslice. I will disable the write cache (with the sync and dirsync mount options) and do some profiling tonight. It probably won't be good for my "disk" since it's an SD card or eMMC.

My bet is that the reason you are seeing large latencies on your thread is that the libtorrent disk I/O thread has filled the page cache with dirty pages backed by a slow drive. When it's time for your, high priority, thread to run, it may need another page or two. That would trap into the kernel to get another page, which would be forced to evict a dirty page to free it up. Since it's backed by a slow drive, flushing 4KiB may take a while before the page is cleared and control is handed back to your thread.

My understanding is that modern versions of linux has solved this by preventing creating new dirty pages at a higher rate than they can be flushed.

>>No, that alert is posted to the client at the same time as the asynchronous write operation is posted to the disk queue. I don't think there's an alert for when the write operation has completed.
>
>Can you offer any pointers on adding one? And are you interested in the patches? I think this would be the simplest way to solve my problem and it may even perform better than accessing your cache directly since Linux can still do read caching with the sync option, once the download gets far enough all reads will be sequential, and once a piece gets to your cache it will likely also be in the OS cache and can stay there longer since it can use all available memory.

you may want to look at ``torrent::on_disk_write_complete()``

**Comment by fernando-rodriguez** [comment]
On 03/17/2018 05:33 AM, Arvid Norberg wrote:
> My bet is that the reason you are seeing large latencies on your thread 
> is that the libtorrent disk I/O thread has filled the page cache with 
> dirty pages backed by a slow drive. When it's time for your, high 
> priority, thread to run, it may need another page or two. That would 
> trap into the kernel to get another page, which would be forced to evict 
> a dirty page to free it up. Since it's backed by a slow drive, flushing 
> 4KiB may take a while before the page is cleared and control is handed 
> back to your thread.

That sounds close, but my thread would not need any pages because it's using pooled memory and I only have a couple calls that result on syscall and they complete very fast. Also I'm not seeing any page faults. Am I missing something?

I think that just before my thread becomes runnable libtorrent's IO thread is causing some pages to be flushed causing it to over-extend it's time slice. Anyways, disabling the write cache has greatly improved things. I'm still seeing high latencies sporadically but I'm willing to bet once I get to profiling will find other causes.

> you may want to look at |torrent::on_disk_write_complete()|

Thanks. Will do.

**Comment by fernando-rodriguez** [comment]
On 03/17/2018 05:33 AM, Arvid Norberg wrote:
> you may want to look at |torrent::on_disk_write_complete()|

Hmm, there is an alert posted at the end of that method, `block_finished_alert`, isn't that what I want? If I get that alert `(piece_size + block_size - 1) / block_size` times where `block_size` is the field from the torrent handle it would mean the whole piece has been written, right? Thanks.

**Comment by fernando-rodriguez** [comment]
Well it works, I have to keep track of each block because I get the alert twice for some pieces. However with some torrents I'm seeing corruption. By any chance is the piece written before it passes the hash check?

**Comment by arvidn** [comment]
Blocks in pieces may be written before all blocks are downloaded (because cache space is limited). The disk cache prioritizes writing blocks that the sha1 cursor has passed though, to minimize the need to read blocks back from disk to check the piece hash. Similarly, a piece may pass the hash check before writing it do disk completes

**Comment by fernando-rodriguez** [comment]
Thanks for the help. I have a clean patch to add a new alert, `piece_ready_alert` that is posted after the piece has been written to disk (or the page cache) and passed the hash check. The alert is posted on `peer_connection::on_disk_write_completed()` and on `torrent::we_have()` so if the piece finshes writting before it passes the hash check it will be generated twice, but you're guaranteed to have the piece on disk the first time and that's what matters. You can see the patch [here](https://github.com/avbox/portage/blob/master/net-libs/libtorrent-rasterbar/files/libtorrent-rasterbar-1.1.5-block-written-alert.patch). Please tell me what I need to do to get it merged.

Also I think I found a bug. If you set `aio_threads` to 1 and `aio_max` to 10 (I think the first setting is the one that matters but I haven't investigated yet) then `torrent::we_have()` will never be called for some pieces so the `piece_finished_alert` (as well as my new alert) is not posted and *I think* that the piece doesn't become available until the download is finished.

**Comment by fernando-rodriguez** [comment]
Actually, `torrent:we_have()` is always called, but it's bailing out early due to exceptions on two spots. One is inside the first loop and the other is the call to `state_updated()`. And setting `aio_threads` to 1 only makes it more likelily to happen (or at least more likely that it would affect my application).

**Comment by fernando-rodriguez** [comment]
Here's a [new patch](https://github.com/avbox/portage/blob/master/net-libs/libtorrent-rasterbar/files/libtorrent-rasterbar-1.1.5-piece-ready-alert.patch) were I solved missing alerts problem by moving the alerts towards the top of `torrent:we_have()`. I'm not sure if the exceptions are causing any other problems but this at least fixes the missing alerts.

**Comment by fernando-rodriguez** [comment]
Thanks for the help. Please ignore the last messages. My alerts queue was getting full and I was misled by the log outputs into thinking that we_have() was bailing out early.

**Comment by arvidn** [comment]
to upstream this patch it would need test coverage. Specifically, the piece picker unit test need to cover the new functions (both positive and negative tests) and ideally there would be a test of the session logic as well.

As for the logic itself, your comment says: "This alert may be generated more than once for each piece", is that still the case? If so, do you understand why that is? It doesn't seem right to expose such quirk to the client.

It seems redundant (and a bit expensive) to call ``is_piece_finished()`` at the top of ``is_piece_ready()``. You end up doing a lot of the same lookup twice that way. Is it even necessary? won't your checks cover the case where the piece is not finished anyway?

I would also expect the top of ``is_piece_ready()`` to do some of the same things as ``has_piece_passed()``, to see if we've marked it as the hash check having passed.

If you submit the patch as a pull request against ``RC_1_1`` it would be easier to talk about it
