### ISSUE TITLE
'file_storage' object has no attribute 'file_name'

### ISSUE THREAD

**Issue by David-Luis** [arvidn/libtorrent#2848]
libtorrent version (or branch):
master

platform/architecture:
windows

compiler and compiler version:
python 3.6

while trying to use file_storate::file:_name passing an integer I get:
`'file_storage' object has no attribute 'file_name'`

In the same object `file_size` is working

**Comment by David-Luis** [comment]
Using file_entry path can be used for this :)

**Comment by arvidn** [comment]
Your original ticket is still an issue, right? Or was it a mistake?

**Comment by David-Luis** [comment]
you are right, this is still an issue, reopen!

**Comment by arvidn** [comment]
fixed here https://github.com/arvidn/libtorrent/pull/2850
