### ISSUE TITLE
Assertion when fetching torrents from DHT (using libtorrent 1.0.7)

### ISSUE THREAD

**Issue by devos50** [arvidn/libtorrent#285]
I get an assertion error when fetching torrent information from the DHT. I've compiled libtorrent 1.0.7 and the Python bindings on Windows 10 with the MSVC14 compiler (64-bit).

This is the assertion I get: https://gyazo.com/677435ed6bc51124aadf8d092e96b439.

Anyone knows what could cause this?

**Comment by arvidn** [comment]
do you have a stack trace for the assert? (with a debug build you can click "Debug" to see it). The assert is not directly related to the DHT, but is probably triggered by some behavior of ut_metadata. It's an invariant check that expects the connection to be disconnected when both peers have indicated they aren't interested in each other. It suggests that at some place some state changes without triggering a disconnect.

**Comment by Falcosc** [comment]
Should we close it until we got a stack trace based on current 1.0 versions?
