### ISSUE TITLE
Rewrite the SSL engine part so as to support other SSL libraries, likely GnuTLS

### ISSUE THREAD

**Issue by alexandre-janniaux** [arvidn/libtorrent#2858]
Hi,

I'm currently writing support for gnutls in libtorrent, but as I wrote my patch I was thinking libtorrent would need quite a big rework of the SSL part so as to produce a clean interface.
I open this issue to have feedback from other developers about what should be done.

Here is the problem:

libtorrent uses boost API for the transport part, which only support openSSL library, without abstracting the context (it is actually a SSL_CTX* object), and directly uses openSSL functions for certificate verification and TLS sni extension.

It is handled by adding ``#TORRENT_USE_OPENSSL`` surrounding the SSL code. While it is quite handy and provides an easy way to integrate other SSL library, it means that the whole logic has to be written multiple times, tests has to be written multiple times and the code is starting to look like spaghetti, with defines everywhere.

Moreover, the three files mainly using SSL, namely ``ssl_stream.cpp``, ``torrent.cpp`` and ``session_impl.cpp`` are already more than multiple thousand lines long.

As libtorrent is using ``boost::asio``, it is acceptable to provide a boost-like compatibility wrapper around ``ssl::context`` and ``ssl::stream`` classes and write a ``using gnutls::context;`` or ``using boost::asio::ssl::context;`` when appropriate, but I think a wrapper around session context and session initialization, certificate verification, hostname settings and ssl enabling in libtorrent should be made.

Maybe libtorrent can be linked against many multiple SSL libraries at once and the user could choose the SSL engine he wants to use for a libtorrent session thanks to a template parameter, defaulted to openssl.

If you agree with these change, we can discuss what this abstraction should look like and I can make the patch so as to implement it.

**Comment by aldenml** [comment]
I had similar general ideas a while ago, but at the end I concluded that writing a custom transport for a new SSL library was too much effort for what it's used. Are you actually using the "torrents over SSL" feature? or just to support HTTPS trackers?

**Comment by alexandre-janniaux** [comment]
I'd like to use the torrent over SSL feature, i.e. authenticating peers and tracker with a certificate and use weak encryption for exchanges between peers.

About the transport, it's quite verbose with boost interface but I believe it can be simplified a lot. It is actually the more factorized part of the library.

The core library will also benefit from moving SSL code to an abstraction, because the code will be a lot simpler and shorter. 

I believe it's also needed for the sake of libtorrent regaring the current context of SSL libraries, with Debian wanting softwares to be linked against GnuTLS instead of openSSL and openSSL being relicensed Apache2, which will prevent people from BSD to backport into libreSSL.

**Comment by aldenml** [comment]
interesting, didn't have the relicense problem in mind, agree with your point

**Comment by arvidn** [comment]
The bulk of this effort would for sure be adding support to boost-asio, to use a different backend. I don't think the namespace ``ssl`` refers to the back-end library though, just the protocol.

If boost.asio would support a different back-end, the changes to libtorrent would be fairly simple I believe. The internal context and certificate types would be different, but presumably accessed via the same functions in boost.asio.

If you're serious about doing this work, I think you should look into how openssl is integrated into boost.asio (my impression is that the most complex aspect is the state machine to handling incoming and outgoing messages, and passing them on to the upper layer). Then you should probably chat with Chris, to see what he thinks.

**Comment by alexandre-janniaux** [comment]
Sure, I've already produced a compiling version of libtorrent, including a similar wrapper around ``boost::asio::ssl`` for GnuTLS (albeit neither a complete nor working one) but I'm pretty sure most of the backend for boost can be shared between openSSL and other libraries, as the most difficult part is not manipulating the library itself but -- as you highlighted -- manipulating state and io buffers which seem to be generic across SSL implementations.

But as I said, transport is the less entangled part of openSSL in libtorrent, because ``boost::asio`` already do it just right. In comparison, libtorrent itself relies a lot on openSSL and uses openssl functions. As an example of the changes needed to just make libtorrent compile against GnuTLS, you can look at my WIP branch, and especially this commit : https://github.com/alexandre-janniaux/libtorrent/commit/ccfc5d6f51b3072a00afcaf8e7a1412a9caf374d.

I'll do as you said and see what I can do about the transport part with Chris, but I don't think it prevents us from refactoring the other SSL part in libtorrent. In any case, I believe it will improve and untangle the code and boost its quality.
