### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by fernando-rodriguez** [arvidn/libtorrent#2870]
**Please provide the following information**

libtorrent version (or branch): RC_1_1 and master

platform/architecture: Linux/x86_64

compiler and compiler version: GCC 5.4.0 and 6.4.0

I'm unable to run the tests. Running:

./autotool.sh
./configure
make

succeeds but `make check` fails with the following errors: https://paste.pound-python.org/show/fkenkUPnApCCigqnBIU7/

**Comment by fernando-rodriguez** [comment]
Updated pastebin https://paste.pound-python.org/show/fkenkUPnApCCigqnBIU7/

**Comment by arvidn** [comment]
the tests will run functions that are internal to libtorrent, and normally not exported. When test are enabled libtorrent is supposed to be built with``-DTORRENT_EXPORT_EXTRA``. Perhaps if you build it normally first, and then try to just build the tests, the main library won't be rebuilt with ``TORRENT_EXPORT_EXTRA``
