### ISSUE TITLE
Need help with Windows XP

### ISSUE THREAD

**Issue by Alhimovvv** [arvidn/libtorrent#2891]
Hello. 

I can't run libtorrent on Windows XP SP3 which was built on Windows 10.

ERROR : simple_client.exe is not a valid Win32 application

**Comment by pavel-pimenov** [comment]
![default](https://user-images.githubusercontent.com/920705/38088796-c2f4ed46-3365-11e8-9ef8-ab06c706f31e.png)

**Comment by Alhimovvv** [comment]
I building by bjam

**Comment by Alhimovvv** [comment]
Help is no longer needed. I already built in Visual Studio. Thanks pavel-pimenov
