### ISSUE TITLE
PVS Studio static analyser reports some issues

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#2896]
Online report (#2328)
http://www.fly-server.ru/pvs-studio/libtorrent/

**Comment by pavel-pimenov** [comment]
Update  RC_1_2
http://oracle.fly-server.ru/pvs-studio/libtorrent/

**Comment by arvidn** [comment]
there are quite a few false positives here.

http://oracle.fly-server.ru/pvs-studio/libtorrent/sources/sha1_hash.hpp_0.html#ln196
`v` is a `std::pair<std::uint32_t&, std::uint32_t&>` or something like that. it's clearly *not* uninitialized.

these are also obvious false positives:

http://oracle.fly-server.ru/pvs-studio/libtorrent/sources/upnp.cpp_30.html#ln1389

I made these changes: https://github.com/arvidn/libtorrent/pull/4071

is there anything else you think is actionable in there?
