### ISSUE TITLE
scrape_downloaded is always 0 in UDP trackers

### ISSUE THREAD

**Issue by ngosang** [arvidn/libtorrent#29]
We are trying to implement this in qBittorrent. As you can see in the following screenshot Seeds and Peers are displayed correctly but Downloaded only works in HTTP trackers. I can get Downloaded stats from UDP trackers with other clients.
![](https://camo.githubusercontent.com/8a082949201aa468e0a31c7329fe0677fb5ca880/687474703a2f2f692e696d6775722e636f6d2f6342356a6866772e706e67)
If you want to see some code https://github.com/qbittorrent/qBittorrent/pull/3162/files#diff-6e7c74cc3d4a45c001728c95b3c49f62R295

**Comment by arvidn** [comment]
This is probably because you never asked libtorrent to send a scrape request. http trackers include the scrape data in the regular responses, udp trackers only include seeds and peers in the regular ones. You have to explicitly ask to scrape to get that field filled in. I would expect it to be -1 though

**Comment by ngosang** [comment]
I see it now, but if I do:
```
torrent_handle->scrape_tracker();
```
scrape_tracker() => https://github.com/arvidn/libtorrent/blob/master/src/torrent.cpp#L3208
this only scrapes the last working tracker.

Is there a way to scrape desired tracker? or better ...
Is there a way to automatically scrape all trackers after reannounce? I think this is what other clients do.

**Comment by arvidn** [comment]
unfortunately, no. There isn't. Can you think of an appropriate API to do that?

**Comment by ngosang** [comment]
> Is there a way to scrape desired tracker?

If I'm right we have this methods in torrent_handle.
```
        void force_reannounce (int seconds = 0, int tracker_index = -1) const;
        void scrape_tracker() const;
```
you can use the same syntax for `scrape_tracker`.

> Is there a way to automatically scrape all trackers after reannounce?

I don't know what will be the best API.
We want to add an advanced option in qBittorrent, for example "Do you want to scrape trackers?". If this option is enabled **all trackers** in all torrents should be scraped so we can display full info for all trackers (see the screenshot in the first comment). If you change `scrape_tracker` to allow scrape each tracker we can do it but will be harder.

**Comment by arvidn** [comment]
Here's an attempt to fix this. please test it if you have a chance

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/433
