### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [arvidn/libtorrent#290]
Would you like to [replace any double quotes](https://github.com/arvidn/libtorrent/blob/b45c585a78a582159a534b5bef33da375291cc54/include/libtorrent/session.hpp#L39 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by arvidn** [comment]
I don't think so. Do you have a compelling argument?

The convention I've followed so far is to use double quotes for headers belonging to the same library as the file including it, and angle brackets for including external headers.

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "C++ working draft") in the standard specification for the programming language "C++".
```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```

* How do you think about to avoid "a duplicated file search" here?
* Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Include syntax description") for header files of your software?

**Comment by ssiloti** [comment]
This is a bot Arvid, I wouldn't spend too much time chatting with it :)

**Comment by elfring** [comment]
Are you interested in a more constructive dialogue?
