### ISSUE TITLE
Problem with multiple connection per ip

### ISSUE THREAD

**Issue by Alhimovvv** [arvidn/libtorrent#2901]
Hello. I have a problem with multiple connection per ip in local network. I started one client on PC in my local network, than I started second client on other PC in my local network, with ip-filter settings. My second client can load only from first client. First loading is good. Than I close second client, remove loaded file and start client again. After one minute loading start, but if I try to do it the third time or more, then the download does not start.

**Comment by arvidn** [comment]
to try to understand why your peer is not downloading, please see: https://libtorrent.org/troubleshooting.html

**Comment by Alhimovvv** [comment]
Do you have any peer -> no ( 0 )

Does the torrent have an error -> no

Is the torrent pause -> no

Do you have any trackers in the torrent -> yes

Did any tracker return any peers -> no

Do you know for sure the torrent has peers -> yes

What should I do next? How I need to check it? 
When I run my client first time I have a peer but I any trackers not return peers. And downloading is starting. But when I try to restart my client I have this problem, I can't see peer. But client in my second PC still running.

**Comment by arvidn** [comment]
if the tracker isn't returning any peers, you may have a problem with the tracker. try looking at its log.

**Comment by Alhimovvv** [comment]
What should I see in the logs of the second client?

It is two same application that running in two PC. First client already loaded a torrent and started seeding. The second client has blocked all the IP except the first and than start to download a torrent from first.

**Comment by Alhimovvv** [comment]
I have same problem with client_test example.

**Comment by arvidn** [comment]
> When I run my client first time I have a peer but I any trackers not return peers.

I interpreted this as your tracker not returning any peers, and suggested you may have a problem with your tracker. It seems that was not what you meant though.

The bittorrent client that does not have any peers, where would you expect it to get peers from?
Do you get any peers from there?
if you have blocked IPs to all of internet except one IP, do you expect the tracker to return that one specific address? (if so, why do you expect that?)
If you expect the swarm to have other peers, perhaps the tracker returns some of those peers.

**Comment by arvidn** [comment]
it depends on what the problem is. If you need to be connected to a specific peer, I would suggest you use ``connect_peer()`` to connect to that peer. You may need to make sure that peer "reserves" a connection slot for you as well, so it doesn't fill all its slots with connections to other peers. I believe you can use peer classes to do that.

**Comment by Alhimovvv** [comment]
I will try. Thank you.
