### ISSUE TITLE
Logo proposal for Libtorrent

### ISSUE THREAD

**Issue by baranpirincal** [arvidn/libtorrent#2920]
Hello! I saw that you have no logo design yet, so I wanted to design a logo for Libtorrent. I hope you like it!

If you liked, I will send you editable/original source and .png format files. If there's something you want to change I can do it. Have a nice day!

![bunuat2](https://user-images.githubusercontent.com/37786733/38470491-6a8f59d4-3b6c-11e8-8328-e4bd4799b249.jpg)

**Comment by arvidn** [comment]
nice! That's a lot better than my own attempts in the past :)
Do you have a vector version of it?

**Comment by baranpirincal** [comment]
Of course, I will send it as soon as possible.

**Comment by baranpirincal** [comment]
Here, vectoral and .png version of my logo design:
https://drive.google.com/open?id=1HBJ8XGeGLySnwiSmySwRw7E2JNIiXDzm

**Comment by baranpirincal** [comment]
@arvidn I created pull-request, could you please check it? Thanks in advance
