### ISSUE TITLE
Redo UPnP port forwarding?

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#2922]
This problem comes from a user of qbittorrent.
I don't know much about UPnP port forwarding so this might not be possible.
Or it might be downright stupid. Or out of libtorrent scope.
In any case, you can quickly close this if this isn't feasible.

User reports that he connects through a router that his landlord controls. That router seems to periodically drop port forwarding settings. So the user needs to restart qbittorrent to reapply the port forwarding settings to the router.

Is there any way for libtorrent to detect such a situation and reissue the port forwarding requests?

**Comment by ssiloti** [comment]
Libtorrent always requests uPnP port mappings of "infinite" duration and does not re-request mappings unless a change in the network configuration is detected. I'm not sure what "infinite" is supposed to mean in practice. A logical solution would be for to retain the mapping as long as the DHCP lease for the internal IP remains valid, but I don't know what routers actually do.

I doubt there's any way for libtorrent to detect when the router discards its mappings. It might be reasonable to re-request the mappings periodically, but I'm not what what the criteria for that should be.

**Comment by arvidn** [comment]
iirc, there is a way to list which mappings are currently in effect. So it would be possible to detect it that way. I'm hesitant to add more complexity in the port mapping code though. If anything I would like to use a 3rd party library or the windows API to handle it.

**Comment by sledgehammer999** [comment]
OK. It's your call guys.
I just forwarded the user's problem.

**Comment by aldenml** [comment]
@sledgehammer999 just to document that when you start working with `1.2/master`, there is a new function `reopen_network_sockets(reopen_network_flags_t options = reopen_map_ports)` that could help with this use case.

**Comment by aldenml** [comment]
I mean, that with this new function, you can implement the auto-detection or periodic mapping at the client level.

**Comment by Seeker2** [comment]
"User reports that he connects through a router that his landlord controls. That router seems to periodically drop port forwarding settings. So the user needs to restart qbittorrent to reapply the port forwarding settings to the router."

To save a close-and-reopen cycle for qBitTorrent... (because of slow shutdown issue and potential corruption of DLing files)
You can disable UPnP, click ok, then re-enable UPnP, click ok...and should be good for awhile.

**Comment by Seeker2** [comment]
My disable+reenable UPnP is a poor workaround I admit -- but that's all I can provide.

Your router should not be losing its port forwarding rule/s even if it's turn off and on.
