### ISSUE TITLE
Report move progress?

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#2923]
Using latest RC_1_1.

Currently `torrent_status::progress` reports progress only for checking or downloading files.
But the docs define this field as "represents the progress of the torrent's current task".
Is it possible to extend it to report the progress of a move_storage ?
Moving a big torrent from one disk to another takes time and it would be nice to give some feedback to the user that the procedure progresses and isn't stuck.
If implemented don't forget that `post_torrent_updates()` should consider this torrent as changed and post a new update when asked.

Secondly, and not that important: Something about system performance. I tested a move on a Windows 7 system between HDDs of a 11GB torrent. I did the move twice into/from the "C:" drive (holds the OS installation). During the move, everything came to a crawl. Other apps were very slow to open. Loading pages in a browser/streaming youtube froze, even though nothing else was downloading.

I "fixed" it by setting the qbittorrent process priority to "low".
Is it feasible (or worth it) for you to set a low priority for the move_storage thread?

**Comment by arvidn** [comment]
since moving a torrent is a single disk job, there isn't any obvious feedback channel for the progress. I'm open to ideas of how to do this, I'm just a bit worried about making it a bit too hacky. Maybe just having a single atomic counter in `torrent` whose pointer is passed down to the disk job would be sufficient. Not very pretty, but simple.

**Comment by luzpaz** [comment]
Any chance we can re-open this issue ?

**Comment by luzpaz** [comment]
Note: historically this issue is from Match 2013 per the original ticket  
https://code.google.com/p/libtorrent/issues/detail?id=444&start=100

**Comment by alexx-ftw** [comment]
This would be a hugely useful QoL improvement. Upvoting.

**Comment by mirddes** [comment]
enabling implementation of **some** indication of file movement progression in downstream clients would be greatly appreciated.

**Comment by phanirithvij** [comment]
Not stale
