### ISSUE TITLE
Compile Python Bindings

### ISSUE THREAD

**Issue by doadin** [arvidn/libtorrent#2924]
**Please provide the following information**

libtorrent version (or branch):

RC_1_1

platform/architecture:

Windows7sp1(x64)

compiler and compiler version:

MSVC9.0(x86) Boost 1.63.0 Python 2.7.14(x86)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Error is:
```
error: Unable to find file or target named
error:     '/boost/python//boost_python3'
error: referred to from project at
error:     '.'
```
Im using this batch to compile through jenkins which up @ libtorrent version 1.1.5 worked fine. 

```
FOR /F "TOKENS=1 eol=/ DELIMS=/ " %%A IN ('DATE/T') DO SET dd=%%A
FOR /F "TOKENS=1,2 eol=/ DELIMS=/ " %%A IN ('DATE/T') DO SET mm=%%B
FOR /F "TOKENS=1,2,3 eol=/ DELIMS=/ " %%A IN ('DATE/T') DO SET yyyy=%%C
SET todaysdate=%yyyy%%mm%%dd%
echo %dd%
echo %mm%
echo %yyyy%
echo %todaysdate%

call "c:\program files (x86)\microsoft visual studio 9.0\vc\bin\vcvars32.bat"
cd "C:\Jenkins\jobs\Libtorrent-RC_1_1\workspace"
set INCLUDE=C:\Build-OpenSSL-110-VC-32-Jenkins\include;%INCLUDE%
set LIB=C:\Build-OpenSSL-110-VC-32-Jenkins\lib;%LIB%
set BOOST_ROOT=C:\boost_1_63_0
set BOOST_BUILD_PATH=%BOOST_ROOT%
set PATH=%BOOST_ROOT%;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin;%PATH%

cd "C:\Jenkins\jobs\Libtorrent-RC_1_1\workspace\bindings\python"

b2 libtorrent-link=static boost-link=static release toolset=msvc-9.0 optimization=space runtime-link=static link=static

copy /y C:\Jenkins\jobs\Libtorrent-RC_1_1\workspace\bindings\python\bin\msvc-9.0\release\boost-link-static\libtorrent-link-static\link-static\optimization-space\runtime-link-static\libtorrent.pyd C:\libtorrent\builds\RC_1_1\libtorrent-%GIT_COMMIT%-%todaysdate%.pyd

copy /y C:\Jenkins\jobs\Libtorrent-RC_1_1\workspace\bindings\python\bin\msvc-9.0\release\boost-link-static\libtorrent-link-static\link-static\optimization-space\runtime-link-static\libtorrent.pyd C:\Python27\Lib\site-packages\libtorrent.pyd

cd "C:\libtorrent\builds\RC_1_1"

echo libtorrent version >> buildinfo-%GIT_COMMIT%-%todaysdate%.txt
python -c "import libtorrent; print libtorrent.version" >> buildinfo-%GIT_COMMIT%-%todaysdate%.txt
C:\Build-OpenSSL-110-VC-32-Jenkins\bin\openssl.exe version >> buildinfo-%GIT_COMMIT%-%todaysdate%.txt
echo msvc-9.0 >> buildinfo-%GIT_COMMIT%-%todaysdate%.txt
echo boost 1.63.0 >> buildinfo-%GIT_COMMIT%-%todaysdate%.txt
```

**Comment by ssiloti** [comment]
Do you have multiple versions of python installed? If so you may need to specify `python=2.7` when invoking `b2`.

Also, please post complete error messages instead of truncating them to just the file and error number.

**Comment by doadin** [comment]
I do not have multiple python versions installed. 

The error with boost 1.63 is pretty much the whole thing since it doesnt really do anything it stops at the very begining. The other two boost version errors I thought where completely too large for posting here if needed I can post them to a pastebin or w.e. more trying to find where i've gone wrong.

**Comment by doadin** [comment]
Adding python=2.7 to the b2 options does not clear the error.
Reverting https://github.com/arvidn/libtorrent/commit/e7e5805c56873ddfdcc09c407251185234caafbc makes the build run successfully.

**Comment by doadin** [comment]
Fixed: https://github.com/arvidn/libtorrent/commit/b3faba329d9deba7bf0efba43200fb237756fbd9
