### ISSUE TITLE
"Could not find a version of the library"

### ISSUE THREAD

**Issue by djesys** [arvidn/libtorrent#2943]
I need to get deluge working on debian wheezy.
- Installed Boost 1.67

compiling libtorrent with
`./configure --enable-python-binding --with-libiconv --with-boost-libdir=/usr/local/include/boost/
`
results in 

```
Checking for boost libraries:
checking for boostlib >= 1.36... yes
checking whether the Boost::System library is available... yes
configure: error: Could not find a version of the library!
```

I tried different versions of libtorrent and also tried boost 1.49 

`apt-get build-dep python-libtorrent
`

which results in:
`configure: error: OpenSSL library not found. Try using --with-openssl=DIR or disabling encryption at all.` under 1.0.11

and 

`configure: error: Boost.Chrono library not found. Try using --with-boost-chrono=lib
`
under 1.1.7

I really don´t know anymore what to do, please help

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
I personally tested that the highest supported version of libtorrent-1.0.11 can only be Boost-1.64
