### ISSUE TITLE
python compile error

### ISSUE THREAD

**Issue by 742340082** [arvidn/libtorrent#2946]
**Please provide the following information**

libtorrent version (or branch): 1.1.7

platform/architecture:linux

compiler and compiler version:gcc4:6.3.0

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Boost has been compiled
Compile the following error
```
b2 libtorrent-link=static boost-link=static release optimization=space stage_module --abbreviate-paths address-model=64 -j8
CXXFLAGS = -I/opt/local/include
LDFLAGS = -L/opt/local/lib
OS = LINUX
building boost from source directory:  /media/yyp/projects/dev/boost_1_66_0
using python interpreter at:  /usr/bin/python
WARNING: you cannot link statically against boost-python on linux, because it links against pthread statically in that case, which is not allowed
WARNING: you cannot link statically against boost-python on linux, because it links against pthread statically in that case, which is not allowed
Performing configuration checks

    - 32-bit                   : no  (cached)
    - 64-bit                   : yes (cached)
    - arm                      : no  (cached)
    - mips1                    : no  (cached)
    - power                    : no  (cached)
    - sparc                    : no  (cached)
    - x86                      : yes (cached)
    - symlinks supported       : yes (cached)
...patience...
...patience...
...patience...
...found 7345 targets...
running build
running build_py
package init file 'libtorrent/__init__.py' not found (or not a regular file)
package init file 'libtorrent/__init__.py' not found (or not a regular file)
```
Have not been solved

**Comment by 742340082** [comment]
What is wrong with this?
```
..failed gcc.link.dll bin/gcc-6.4.0/rls/adrs-mdl-64/bst-lnk-sttc/lbtrn-lnk-sttc/lbtrn-pythn-pic-on/optmz-spc/vsblt-hdn/libtorrent.so...
...skipped <p.>libtorrent.so for lack of <pbin/gcc-6.4.0/rls/adrs-mdl-64/bst-lnk-sttc/lbtrn-lnk-sttc/lbtrn-pythn-pic-on/optmz-spc/vsblt-hdn>libtorrent.so...
...failed updating 1 target...
...skipped 1 target...
build failed

```

**Comment by 742340082** [comment]
My operation is
> The first step is to download and unzip boost_1_66_0
> Step 2 Go to the boost_1_66_0 root directory and run bootstrap.sh
> The third part executes the generated b2 file
> Step 4 Go to the tools/build directory under boost_1_66_0 and copy the user-config.jam example to the tools/build directory. Add in user-config.jam
```
using gcc ;
using python : 3.5 : /usr/bin/python3.5 : /usr/include/python3.5 : /usr/lib/python3.5 ;
```
> The fifth step is to add BOOST_BUILD_PATH and BOOST_ROOT in /etc/profile
> The sixth step is to download and unzip libtorrent-libtorrent-1_1_7
> The seventh step is to execute the following command in the libtorrent-libtorrent-1_1_7 directory
```
./autotool.sh
./configure --enable-python-binding
make
```
> The eighth step is to enter bindings/python under libtorrent-libtorrent-1_1_7 and execute the following command
```
python setup.py build --bjam
```

But not successful

**Comment by 742340082** [comment]
Is anyone here to help?

**Comment by arvidn** [comment]
Please post the error you get

**Comment by 742340082** [comment]
The above is the error

**Comment by 742340082** [comment]
Inside the code block is wrong

**Comment by arvidn** [comment]
the only thing the error message you posted above says is that, it failed to stage the python module `libtorrent.so` because the library `libtorrent.so` failed to link. It will have failed to link because at least one object file it depends on failed to build. What you need to do is to find the *first* error, that then caused the cascade of follow-on failures.

Typically you can do this by searching for "error: " from the *start* of the output.

**Comment by 742340082** [comment]
Do not understand, there is a compiled python libtorrent.so

**Comment by 742340082** [comment]
Can't read this error
```
gcc.compile.c++ bin/gcc-gnu-6.4.0/rls/adrs-mdl-64/bst-lnk-sttc/lbtrn-lnk-sttc/lbtrn-pythn-pic-on/optmz-spc/vsblt-hdn/src/peer_info.o
gcc.compile.c++ bin/gcc-gnu-6.4.0/rls/adrs-mdl-64/bst-lnk-sttc/lbtrn-lnk-sttc/lbtrn-pythn-pic-on/optmz-spc/vsblt-hdn/src/ip_filter.o
gcc.compile.c++ bin/gcc-gnu-6.4.0/rls/adrs-mdl-64/bst-lnk-sttc/lbtrn-lnk-sttc/lbtrn-pythn-pic-on/optmz-spc/vsblt-hdn/src/magnet_uri.o
gcc.compile.c++ bin/gcc-gnu-6.4.0/rls/adrs-mdl-64/bst-lnk-sttc/lbtrn-lnk-sttc/lbtrn-pythn-pic-on/optmz-spc/vsblt-hdn/src/'error_code'.o
gcc.compile.c++ bin/gcc-gnu-6.4.0/rls/adrs-mdl-64/bst-lnk-sttc/lbtrn-lnk-sttc/lbtrn-pythn-pic-on/optmz-spc/vsblt-hdn/src/alert.o
gcc.link.dll bin/gcc-gnu-6.4.0/rls/adrs-mdl-64/bst-lnk-sttc/lbtrn-lnk-sttc/lbtrn-pythn-pic-on/optmz-spc/vsblt-hdn/libtorrent.so
common.copy libtorrent.so
...updated 187 targets...
running build
running build_py
package init file 'libtorrent/__init__.py' not found (or not a regular file)
package init file 'libtorrent/__init__.py' not found (or not a regular file)

```

**Comment by 742340082** [comment]
According to your documentation, I have not succeeded

**Comment by 742340082** [comment]
you cannot link statically against boost-python on linux, because it links against pthread statically in that case, which is not allowed，What should this do?
