### ISSUE TITLE
building from source failing on linux

### ISSUE THREAD

**Issue by shinenelson** [arvidn/libtorrent#2950]
* libtorrent version (or branch):
tags : `libtorrent-1_1_{7-1}`

* platform/architecture: `x86_64 GNU/Linux`

* compiler and compiler version:
  * `autoconf` : 2.69
  * `make` : GNU Make 4.1

I'm trying to compile the latest version of @libtorrent to use to compile @qbittorrent. @qbittorrent v3.3.8+ requires @libtorrent v1.1.2+.

When I attempt to compile @libtorrent off of any of the release tags - `libtorrent-1_1_{7-1}`, `make` fails complaining : 
`make[1]: *** No rule to make target 'mpi.c', needed by 'mpi.lo'. Stop.`

When I tried compiling with tag `libtorrent-1_1`, the compilation completed successfully.

After a little bit of digging around, I found that the file that was complaining and failing to build (`src/mpi.c`) became a C++ file in commit 2a36f9015. That happened somewhere in between of tags `libtorrent-1_1..libtorrent-1_1_1`. I'm guessing it was missed to be tagged as a C++ file in the `configure` script or somewhere else where it should've been changed :thinking: ? 

PS : I'm sorry, I'm not well-versed with how `make` works other than using it to compile source code I pull off the internet (github, mostly)

**Comment by arvidn** [comment]
is it possible that you aren't running `./autotool.sh` or `./configure` in between your build attempts? maybe you have build files from an earlier version.

**Comment by shinenelson** [comment]
No. Everytime I `checkout` to a new a branch (or tag, for that matter) for the purpose of building afresh, I make sure to `make clean` before doing anything else. Here are the full list of commands that I run to `make` : 
```
make clean
./autotool.sh
./configure --prefix $HOME/.local
make
```

PS : I'm able to successfully compile the `libtorrent-1_1` tag at which the file in question is a cpp file and everything works just smooth and fine. Unfortunately, @qbittorrent v3.3.8+ won't compile with `libtorrent-1_1` :disappointed:

**Comment by arvidn** [comment]
here's an example of it working: https://travis-ci.org/arvidn/libtorrent/jobs/369709156#L1616

I don't think `make clean` will delete the makefiles themselves, generated by automake, but I suppose `./autotool.sh` would overwrite them. I still think it would make sense to ensure this assumption is correct by testing a fresh clone of the repo

**Comment by shinenelson** [comment]
Ah, you're right. I didn't think of testing on a fresh clone before reporting here.

It appears you're right. I was able to successfully compile `libtorrent` off the `RC_1_1` branch, though I didn't try linking it to @qbittorrent (which is a different matter out of the scope of this issue).

So, it appears that `./autotool.sh` doesn't do the cleaning up either. It probably only changes the existing files with the diff or something. I'll probably have to manually delete all the `Makefile`s and retry on my actual copy of the repository again.

**Comment by manphiz** [comment]
IIRC you need to run `./configure` after `./autotools.sh` to regenerate the `Makefile`s.

**Comment by shinenelson** [comment]
Well, I did mention that I do that too in https://github.com/arvidn/libtorrent/issues/2950#issuecomment-383375029, but unfortunately, that hasn't really resolved this problem for me.

I did some testing over the weekend, but I couldn't get it to work for me on the actual repository that I cloned to.
