### ISSUE TITLE
Should require C++11/14 when building against boost >= 1.66

### ISSUE THREAD

**Issue by manphiz** [arvidn/libtorrent#2966]
Since https://github.com/arvidn/libtorrent/commit/d1a63cd781e79e1e3792a258c0bc7f9455f2272f, building libtorrent-rasterbar with boost >= 1.66 actually requires C++11 or newer standard due to the use of "auto", which seems to be hard to workaround due to different return types from "buffer_sequence_begin". Ideally one can check whether boost version is 1.66 or newer and add "-std=gnu++0x" (or appropriate flag) to ${CXXFLAGS}, but it can be tricky to implement in m4. Since some of the ${CXXFLAGS} (e.g. -ftemplate-depth=n) requires GCC 4.5 which had sufficient support, maybe it's easier to directly enable C++11 all together. I can help with PR if this is acceptable.

This was discovered when building libtorrent-rasterbar 1.1.6 on OpenBSD, which uses gcc 4.9.4 which still defaults to "-std=gnu++98".

**Please provide the following information**

libtorrent version (or branch): master & RC_1_1

platform/architecture: all/OpenBSD

compiler and compiler version: GCC 4.9.4

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

More like a wish list.

**Comment by arvidn** [comment]
right. when building against boost-1.66, C++11 is required. A PR to fix this would be great!
