### ISSUE TITLE
feature request: support connect to peers through different isps

### ISSUE THREAD

**Issue by colinhd8** [arvidn/libtorrent#2979]
Recently there's common case that the client has multi isp connections.But the bt client doesn't support it well and waste the bandwidth of the other isp connections.

Below is what i want it to act:
1.suppose the client computer has 2 ip address, ip1 and ip2.

2.do the load balance at the router, when the source ip is ip1, let it go through isp1, when the source ip is ip2, let it go through isp2.

3.libtorrent fetch the peer list from tracker, for each peer, first use ip1 as source ip to connect it, the use ip2 as source ip to connect it.

4.for the incoming peer, get it's listening port(use it's peerid match with peer list from tracker, or directly exchange the info with peer?), then use ip1 and ip2 as source ip to connect to the peer.

5.for each source ip, may be we should generate different peerid when connect to the peer, as some bt clients don't allow multi connections for the same peerid

really hope it will be implementd.

Thanks.

**Comment by colinhd8** [comment]
So it means that the libtorrent already try to make multiple connections(one connection per ip or interface) to the same peer?

**Comment by arvidn** [comment]
I don’t believe the same peer is connected multiple times, once per interface, no
