### ISSUE TITLE
How to go about this slightly duplicated code refactor in `obfuscated_get_peers_observer::reply` and `find_data_observer::reply`

### ISSUE THREAD

**Issue by gubatron** [arvidn/libtorrent#2991]
### Links
[`find_data_observer::reply`](https://github.com/arvidn/libtorrent/blob/master/src/kademlia/find_data.cpp#L46)
[`obfuscated_get_peers_observer::reply`](https://github.com/arvidn/libtorrent/blob/master/src/kademlia/get_peers.cpp#L298)

1. both `obfuscated_get_peers_observer` and `find_data_observer` extend `traversal_observer`
2. both `obfucated_get_peers_observer` and `find_data_observer` override `reply(msg const& m)` with duplicate code except `find_data_observer`'s implementation [does one extra check for a "token"](https://github.com/arvidn/libtorrent/blob/master/src/kademlia/find_data.cpp#L69) right before its end.

```c++
...
		timeout();
		return;
	}
// Extra code in find_data_observer::replay(msg const& m)
	bdecode_node const token = r.dict_find_string("token");
	if (token)
	{
		static_cast<find_data*>(algorithm())->got_write_token(
			node_id(id.string_ptr()), token.string_value().to_string());
	}
// End of Extra Code, everything before the section above and after is identical in `obfuscated_get_peers_observer::reply(m)`
	traversal_observer::reply(m);
	done();
}
```

3. There exists a [rather different implementation of `reply(m)`](https://github.com/arvidn/libtorrent/blob/master/src/kademlia/traversal_algorithm.cpp#L614) in the base `traversal_observer` class so I can't really invoke the parent's, both derived classes have very similar implementations, what to do in these cases if you want to destroy repeated code shared by sibling classes?

**Comment by aldenml** [comment]
it looks to me like the three of them could be refactored to use some free function
