### ISSUE TITLE
Can not get filehash

### ISSUE THREAD

**Issue by gt945** [arvidn/libtorrent#3002]
can not get filehash here
https://github.com/arvidn/libtorrent/blob/4b368e1cfc8f91e80ec704eb45d08a003c5acd9a/src/torrent_info.cpp#L468

I tried this, and it works
```
bdecode_node const fh = dict.dict_find_string("filehash");
```

**Comment by arvidn** [comment]
Is there a problem here?

**Comment by gt945** [comment]
@arvidn not a big problem.
I want get file hash from torrent_info, but all of them are zero.
but from bendecode data, here is a 'filehash' that I want
can you confirm whether it is a bug?

**Comment by arvidn** [comment]
there is no bug. there is no standard for what to call file hashes and mostly they are not included in torrents, and usually they can't be trusted.

**Comment by gt945** [comment]
got it, thanks!
