### ISSUE TITLE
torrent_info /create_torrent 

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#3010]
```
			torrent_info ti(path);

			file_storage files = ti.orig_files();
			
			create_torrent ct(files);

                        // generate .torrent
```

I'm trying to load a .torrent file and remove the dht nodes that are in it. In the absence of a way to remove dht nodes in the torrent_info I tried the above that will generate a .torrent file but the hash is different to the original, is there anyway to do this with the default libtorrent functions?

**Comment by arvidn** [comment]
does the info-hash always change with this code or have you found a few examples of where it does?

The problem is that the output from `create_torrent` is an `entry`, which holds a bencoded tree. It will keep dictionary keys ordered though, so it won't be able to represent a bencoded structure where keys aren't ordered, which means it can't necessarily represent every possible torrent (i.e. invalid ones).

One way to work around that was to introduce a new kind of node in the `entry` hierarchy representing a pre-formatted bencoded structure. So, if you pass in `true` as a second argument to the `create_torrent` constructor, it will be able to accurately represent the info dictionary.

**Comment by Col-blimp** [comment]
Thanks, I thought the create_torrent boolean was for something like that going by the online docs but in code it's not there and it's not as far as I can see depreciated either, using master.

**Comment by arvidn** [comment]
in master it's used by default. in RC_1_1 the `preformatted` entry node type wasn't introduced in the original 1.1.0 release, so it has to be optional to have the ABI stay backwards compatible.

**Comment by Col-blimp** [comment]
Well it does not seem to matter if the .torrent is single file or multifile.

Here is Ubuntu 18.4 with a hash of e4be9e4db876e3e3179778b03e906297be5c8dbe but after doing the code from post 1 it becomes 8a5a5cb39911c7849588beea738b53665ce5f3b6

[Link To Torrent](http://releases.ubuntu.com/18.04/ubuntu-18.04-desktop-amd64.iso.torrent?_ga=2.52370733.587296255.1525948240-1529227796.1524844236)

Here is the original:

![capture](https://user-images.githubusercontent.com/10984572/39865936-8325cff8-5446-11e8-8d93-f483c3c78e11.PNG)

and the processed:

![capture2](https://user-images.githubusercontent.com/10984572/39865975-a4450cf8-5446-11e8-9f5e-7a83eaddcb1c.PNG)

If you then process a processed .torrent you do end up with the same hash though.

**Comment by arvidn** [comment]
so, your point is that you would have expected the trackers from the `torrent_info` to have been included in the created torrent?

**Comment by arvidn** [comment]
I tried to reproduce this issue in this test, but it works for me. https://github.com/arvidn/libtorrent/pull/3017
did I miss some aspect in my test?

**Comment by Col-blimp** [comment]
I was expecting that create_torrent when passed a file_storage object would create the same torrent but without any trackers/webseeds/comment/creator/dht nodes/collections/similar as it is made just by the info dict and it does create a .torrent as I thought it should but the hash does not match with the original source.

**Comment by arvidn** [comment]
it is supposed to create the same torrent, but the `file_storage` does not contain the verbatim copy of the info dict, so it won't preserve incorrectly ordered keys for instance. what specifically is failing?

**Comment by Col-blimp** [comment]
I think it is just the file storage being non verbatim that's causing the problem.

In `torrent_info` you can get `metadata()` and that looks like it should be a true verbatim info dic so is there anyway I can use this char array with `create_torrent`?

**Comment by arvidn** [comment]
just pass in the `torrent_info` when you construct `create_torrent` instead of the `file_storage` and you should be good. in RC_1_1 you also need to pass `true` as the second argument to get the preformatted output too.

**Comment by Col-blimp** [comment]
Yes that works but it retains all the data I want to delete (trackers/webseeds/comment/creator/dht nodes/collections/similar), webseeds there is a function to clear them and the comment and creator also but everything else you can only add to existing lists.

**Comment by arvidn** [comment]
I see. it might be simpler to just `bdecode()` up the torrent into an `entry` and modify that

**Comment by Col-blimp** [comment]
Arvidn, thanks for you're time with this.

Was looking at `bdecode()` and unless I'm missing the obvious once an entry exists there is no way to remove it with the default library.

I managed to achieve what I needed with this though:

```
torrent_info ti(path);

boost::shared_array<char> buf = ti.metadata();

// bdecode() buf to node
bdecode_node node;

torrent_info _ti(ti.info_hash());

error_code _e;
_ti.parse_info_section(node , _e);

create_torrent ct(_ti);

// ct now has identical info dict with no trackers etc.
```
