### ISSUE TITLE
Download choking algorithm

### ISSUE THREAD

**Issue by jaccc** [arvidn/libtorrent#3019]
libtorrent version (or branch):
1.1.5, qBittorrent

platform/architecture:
Linux

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
I'm using shared Internet connection. Global connection limit in qBittorrent is set to 12 in order to not cause congestion, which is causing that many seeds and peers are ignored if number of seeds and peers is higher than 12. Download choking algorithm could be added, which would be similar to upload choking algorithm if it doesn't exists which means this is qBittorrent bug.

**Comment by arvidn** [comment]
you could just set a download rate limit instead, no?
The download rate limiter is currently using the control flow of the peer connections to signal back-pressure. This is not the most efficient way. It would be better to rate limit requests. (patches are welcome!)

**Comment by jaccc** [comment]
Download speed of Internet connection is random between 500 and 10000 kByte/s. Congestion can happen even if set download rate to 500 kByte/s.

**Comment by arvidn** [comment]
What do you mean by “congestion”? Do you mean the TCP term to mean packet loss or is it more of the uTP term of buffering delays?

But it sounds like disabling TCP may also help.

**Comment by jaccc** [comment]
Web browsing become very slow.

**Comment by arvidn** [comment]
try to disable incoming and outgoing tcp connections (two separate boolean settings). [Here](https://libtorrent.org/utp.html) are some details on utp if you're curious.

**Comment by jaccc** [comment]
It looks like most users including me don't have public IP address. It looks like most users are TCP only.
Number of leechers decreased from 1 to 0 after disabling TCP.

**Comment by jaccc** [comment]
there are options: apply rate to utp protocol, utp-tcp mixed mode algorithm
can any change improve congestion?

**Comment by jaccc** [comment]
I guess global rate limits don't apply for utp when "apply rate limit to utp protocol" is disabled.
It should be possible to limit global number of TCP connections.

**Comment by jaccc** [comment]
ISP isn't probably limiting utp. I shouldn't block TCP only users because of ratio is below 1. Global rate set to 400 kByte/s with unlimited utp seems to improve situation.

**Comment by Seeker2** [comment]
I think it was Vuze or Transmission that limits the number of peers to download from at once to prevent downloading at <0.5 KB/sec if the download max speed is set too low.

**Comment by jaccc** [comment]
It seems Youtube is using 1 connection, which means there is approx. bandwidth split 1:N when libtorrent is using N connections during congestion. Current download speed is about 50 kB/s with 3 connections to 3 seeds and 27 total seeds. 24 seeds are ignored. Current download bandwidth is about 3000 kB/s.

**Comment by jaccc** [comment]
simple partial solution could be limit number of unchoked seeds - download slots
could you tell me name of function where if condition would be located?
there is error in description of version
installed was 1.0.11 instead of 1.1.5, now upgraded to 1.1.7
