### ISSUE TITLE
The 'dont_replace' move flag doesn't work

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#3021]
**Please provide the following information**

libtorrent version (or branch):
1.1.7 @ 8808eb7cdd

platform/architecture:
Windows 7 x64

compiler and compiler version:
msvc2017

Steps to reproduce:
(for simplicity assume single file torrent. A and B are locations on the same partition. I didn't check between partitions/disks)
1. Download torrent in location A
2. Remove torrent from session, but keep the files
3. Copy the files to location B
4. Re-add the torrent in session pointing again at location A
5. While the torrent runs(I think it works if it is paused too), do `move_storage("B", dont_replace)` aka point it to location B and tell it to use the files it finds there.

Undesired result:
The data of the file at location B get lost/deleted.

Desired result:
Schedule a hash recheck. Discard whatever fails.

I don't know if libtorrent just overwrites the file in B with the contents of the file from A, or if it just discards the data in B.

**Comment by arvidn** [comment]
it sounds like you expect a force-recheck as well. that's not implied by `dont_replace`

**Comment by sledgehammer999** [comment]
Well apart from the hash-recheck `dont_replace` doesn't do what it says it will do. Instead of using the file it corrupts it. (or deletes its data). And apart from doing a hash recheck how will you know if the data at the destination are correct?

**Comment by arvidn** [comment]
`dont_replace` is a flag to `move_storage()`. If the torrent is paused and you call `move_storage()` with this flag set, does it still corrupt the existing files?

It sounds like the torrent overwrites the files when it's *downloading*, not necessarily when it's moving.

If you pause the torrent, move the storage with the `dont_replace` flag, issue a force recheck and then resume the torrent, I think you get the behavior you're asking for.

**Comment by arvidn** [comment]
updated the documentation here https://github.com/arvidn/libtorrent/pull/3098

**Comment by arvidn** [comment]
I'm open to suggestions of improved behavior of this flag, but I think it should be possible to get the behavior that you want, to pick up new files. But probably not in the most optimal way, which I suppose would be to recheck *just* the new files. If the target files are supposed to be complete, there's also seed-mode, which would do the checking lazily
