### ISSUE TITLE
torrents are being downloaded to /tmp instead of external hard drive

### ISSUE THREAD

**Issue by fejjj** [arvidn/libtorrent#3035]
**Please provide the following information**

libtorrent version (or branch):
1.1.5-1build1 amd 64

platform/architecture:
ubuntu-mate bionic beaver x86 64 bit.

compiler and compiler version:
binary from ubuntu repository

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

magnet links which are user-set to be saved to an external hard drive, are sending files to /tmp/

i found this using qbittorrent, and a web search turned up that it is an old bug.  maybe there is a regression in libtorrent??  i'm having to use transmission-gtk for now because the writing to /tmp was filling up my little OS hard drive! :(

see also this old issue from qbittorrent: https://github.com/qbittorrent/qBittorrent/issues/994

**Comment by arvidn** [comment]
libtorrent does not mention `/tmp` anywhere. That path most likely comes from qBitTorrent. I think someone familiar with what qbt does would need to figure out whether this is in fact a problem in libtorrent and what it is.

For bug reports against libtorrent, the issue and interaction should be described at the libtorrent API boundary.

**Comment by arvidn** [comment]
This issue does not affect `RC_1_1`, right?

**Comment by fejjj** [comment]
i am not sure, i can test it for you if you tell me where to download it
(new to linux).  i have opened an issue ticket about this at the
qbittorrent git as well.

**Comment by sledgehammer999** [comment]
@arvidn close this. The user has made the same report on our bug tracker and is currenctly resolved.
link: https://github.com/qbittorrent/qBittorrent/issues/8941
