### ISSUE TITLE
Re-upload the file

### ISSUE THREAD

**Issue by Eugene-Ilyushchyts** [arvidn/libtorrent#3037]
**Please provide the following information**

libtorrent version (or branch): Master

platform/architecture: x86

compiler and compiler version: gcc 5.4.0

Such a situation: I have two machines (x86), on'm distributing 20 files, on the other machine download using magnet exile. But, if the host side to delete the downloaded file , and put it back on the download, you can wait a long time before it is downloaded.Please help to solve this problem.

**Comment by MassaRoddel** [comment]
Maybe because libtorrent keeps peer information per torrent and if a peer is known as a seed - another seed wont connect to this peer even this peer is not a seed anymore?
.. long time means .. hours? seconds? days?

**Comment by arraron** [comment]
I waited 1-2 hours.

**Comment by arvidn** [comment]
you can remove the torrent and re-add it to the session. That should clear the state of which peers are seeds and not. I think even if you save fast-resume and use it when re-adding, you will have this effect. Peers are only remembered by their IP and port in the resume data (iirc).
