### ISSUE TITLE
Fast resume isn't rejected when files are missing

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#3045]
**Please provide the following information**

libtorrent version (or branch):
RC_1_1 8808eb7cdd

platform/architecture:
Windows 7 x64

compiler and compiler version:
msvc2017 x64

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I can't always reproduce it. It usually is easier to reproduce with single-file torrents.
1. Download a singlefile torrent
2. Save the fastresume and exit the program
3. Manually remove the downloaded file (eg rename it)
4. Start the program and add the torrent using the fastresume

I should get a `fastresume_rejected_alert` with `error` set to `mismatching_file_size`. Instead most of the time I just get a regular `add_torrent_alert` with no error set.
**NOTE:** When doing the above steps: If I backup the fastresume before doing step 4, and keep repeating step 4 by restoring the backup fastresume, I sometimes get it to throw a `fastresume_rejected_alert`.

Background: Sometimes users save files to external drives that they forget to connect before starting qbittorrent. Or to partitions/network shares that they forget to mount before starting qbittorrent. I am trying to detect the `fastresume_rejected_alert` in order to stop the torrent with an error status and to prevent libtorrent from happily overwriting user data by downloading them again on top of the valid files (after the drives/partitions are connected/mounted).

**Comment by arvidn** [comment]
do you think you would be able to produce a log from a run where it works as expected as well as a run where it doesn't? with session and torrent logging enabled.

**Comment by sledgehammer999** [comment]
Here is something interesting.
If I run a qbt session with only one torrent, I can't reproduce the problem. `fastresume_rejected_alert` seems to alwayes be fired.
If I run a qbt session with multiple torrents(~30), regardless of their state I almost never get a `fastresume_rejected_alert`. For this reason I can't give a log where this alert is fired. I tried it many times but I can't seem to get the alert.

I am posting a log where the alert isn't fired and the torrent wants to start downloading(I had disabled the network interface on this run).
The log goes from older to newer.
In the the torrent_log_alert handler I matched the torrent's hash and then outputed the msg(). Otherwise you would get a lot of noise from the other torrents.
Here's the [log](https://gist.github.com/sledgehammer999/502071ee4c8861efcdd30c88fbe5886e).

**Comment by arvidn** [comment]
That log doesn't seem complete. I don't see any torrent alerts like:

```
added torrent:
creating torrent:
*** UPDATE LIST [ torrent_want_scrape : 1 ]
init torrent:
*** UPDATE LIST [ torrent_want_scrape : 0 ]
loaded resume data:
init, async_check_fastresume
start_announcing(), paused
fastresume data accepted
```

These are the flags I set in the `alert_mask`: 
```
alert::all_categories
 & ~(alert::dht_notification
 + alert::progress_notification
 + alert::stats_notification
 + alert::peer_log_notification
 + alert::dht_log_notification
 + alert::picker_log_notification)
```

Anyway, I could not reproduce this. I get:

```
fast resume rejected. (<path>): mismatching file size
fastresume data accepted
```

For all torrents I add. Are there any specific properties the torrents need to have? Do they need to be seeds for instance?

**Comment by sledgehammer999** [comment]
Yeah, I only logged `log_alert` and `torrent_log_alert`.
Which other alerts do want want logged?

**Comment by arvidn** [comment]
I see. There are `torrent_log_alert`s in your log, but I don't see `loaded resume data:` for instance.

Do you set `add_torrent_params::flag_override_resume_data` by any chance?

But perhaps more importantly, I don't see any `init torrent:` log. This suggests `torrent::init()` doesn't get called for some reason. This is the function that initiates the async checking of the files. Without it, you won't get any response about the fastresume.

The call to `torrent::init()` normally happens from [here](https://github.com/arvidn/libtorrent/blob/master/src/torrent.cpp#L695). Which also logs `creating torrent:` which also is missing from your log. Which suggests `torrent::start()` isn't called.

`start()` is called from [here](https://github.com/arvidn/libtorrent/blob/master/src/session_impl.cpp#L4778). Which is before the torrent is added to the session's list of torrents, [here](https://github.com/arvidn/libtorrent/blob/master/src/session_impl.cpp#L4800).

It's hard for me to understand how these torrents can be added (successfully) and still not make these calls. Are you sure the torrents are successfully added to the session?

Would you be able to trace what's happening?

**Comment by sledgehammer999** [comment]
@arvidn are you sure you're looking at the correct place? You're linking me to master source. I am observing the issue in RC_1_1. (I haven't tested master).

>Do you set add_torrent_params::flag_override_resume_data by any chance?

No. We don't use this flag.

>Are you sure the torrents are successfully added to the session?

I get download speeds and eventually data are written to disk. So yeah they are added successfully.

I am away now. I'll try to run through a debugger and trace the codepath.(I don't have much experience in this though)

**Comment by arvidn** [comment]
oh, I'll update the links. I was looking at RC_1_1 locally though

**Comment by arvidn** [comment]
one possible explanation is that the log alerts, and the resume data rejected alerts, are dropped because the alert queue fills up. Could you try to construct the session with a larger alert queue?

**Comment by sledgehammer999** [comment]
@arvidn I increased the alert queue to 100000 and it seems I got a bit better log.
It seems to call the async_check_fastresume function, but then nothing. I don't know if you have more debug lines after that procedure.
Although it is a bit worrying on why I get a `add_torrent_alert` before the torrent log alerts that show the torrent initialization? Merely a timing issue due to threads?

I also clipped the end of the log, because it seems after some point to only have info about attempted connections to peers and trackers. I can provide it whole if you wish.

Here is the clipped [log](https://gist.github.com/sledgehammer999/fc2ae491eca386724c005248a3dbde8f)

PS: I am currently investigate the codepath after async_check_fastresume(), to see if I can determine some useful info.

**Comment by sledgehammer999** [comment]
I haven't found anything new.
Something that might help: I used the "Process Monitor" utility which monitors API calls. It seems that qbittorrent indeed queries for the missing file and that it gets back a "NAME NOT FOUND" result. (Presumably the API call fails as it should).

Now, why libtorrent doesn't mark it as rejected is beyond me.

**Comment by sledgehammer999** [comment]
It seems I found the reason. And it was one of @arvidn's initial suspicion.
Alert queue size!
While logging, I set it to 1 million. And the log started including what happened with the fastresume:
```
(N) 2018-05-26T00:25:42 - ---> HERE add_torrent_alert is received of the monitored torrent
(N) 2018-05-26T00:25:42 - Torrent Log alert: creating torrent: TORRENT_NAME_OBSCURED max-uploads: -1 max-connections: 80 upload-limit: -1 download-limit: -1 flags: apply-ip-filter paused update-subscribe resume-save-path save-path: G:\
(N) 2018-05-26T00:25:42 - Torrent Log alert: *** set-max-uploads: 16777215
(N) 2018-05-26T00:25:42 - Torrent Log alert: *** set-max-connections: 80
(N) 2018-05-26T00:25:42 - Torrent Log alert: init torrent: TORRENT_NAME_OBSCURED
(N) 2018-05-26T00:25:42 - Torrent Log alert: *** set-max-connections: 80
(N) 2018-05-26T00:25:42 - Torrent Log alert: *** set-max-uploads: 16777215
(N) 2018-05-26T00:25:42 - Torrent Log alert: *** UPDATE LIST [ torrent_want_scrape : 1 ]
(N) 2018-05-26T00:25:42 - Torrent Log alert: loaded resume data: max-uploads: 16777215 max-connections: 80 upload-limit: -1 download-limit: -1 paused: 1 sequential-download: 0 super-seeding: 0 auto-managed: 1
(N) 2018-05-26T00:25:42 - Torrent Log alert: loaded resume data: save-path: G:\
(N) 2018-05-26T00:25:42 - Torrent Log alert: init, async_check_fastresume
(N) 2018-05-26T00:25:42 - Torrent Log alert: add_peer() X.X.X.X connect-candidates: 1
(N) 2018-05-26T00:25:42 - Torrent Log alert: add_peer() X.X.X.X connect-candidates: 2
(N) 2018-05-26T00:25:42 - Torrent Log alert: add_peer() X.X.X.X connect-candidates: 3
(N) 2018-05-26T00:25:42 - Torrent Log alert: add_peer() X.X.X.X connect-candidates: 4
....
....
(N) 2018-05-26T00:25:42 - Torrent Log alert: resume added peers (103)
(C) 2018-05-26T00:25:42 - File sizes mismatch for torrent TORRENT_NAME_OBSCURED, pausing it.
(N) 2018-05-26T00:25:42 - Torrent Log alert: fastresume data accepted
(N) 2018-05-26T00:25:42 - Torrent Log alert: set_state() 3
(N) 2018-05-26T00:25:42 - Torrent Log alert: *** UPDATE LIST [ torrent_downloading_auto_managed : 1 ]
(N) 2018-05-26T00:25:42 - Torrent Log alert: start_announcing(), paused
(N) 2018-05-26T00:25:42 - Torrent Log alert: auto manager starting torrent
(N) 2018-05-26T00:25:42 - Torrent Log alert: *** UPDATE LIST [ torrent_want_scrape : 0 ]
(N) 2018-05-26T00:25:42 - Torrent Log alert: *** UPDATE LIST [ torrent_want_peers_download : 1 ]
(N) 2018-05-26T00:25:42 - Torrent Log alert: *** UPDATE LIST [ torrent_want_tick : 1 ]
```

This line:
```
(C) 2018-05-26T00:25:42 - File sizes mismatch for torrent TORRENT_NAME_OBSCURED, pausing it.
```
means that I got a `fastresume_rejected_alert` with error set to `mismatching_file_size` and that I explicitly pause it.
But the next line:
```
(N) 2018-05-26T00:25:42 - Torrent Log alert: fastresume data accepted
```

seems wrong. Why does libtorrent accept the fastresume data, when it clearly posted an error code?

In any case, with alert queue size set to 1 million I seem to always get the rejected fastresume alert. 
Now how should I proceed? Should I just increase our default alert queue? Or it is possible for you to make `fastresume_rejected_alert` not discardable?

**Comment by sledgehammer999** [comment]
On another note: Is it normal for the default queue size to fill up so quickly? I understand, that we might not have the most efficient alert handling code, but with only 34 torrents in my session, the alerts go over 1000.
Our alert mask:
```c++
const int alertMask = libt::alert::error_notification
                    | libt::alert::peer_notification
                    | libt::alert::port_mapping_notification
                    | libt::alert::storage_notification
                    | libt::alert::tracker_notification
                    | libt::alert::status_notification
                    | libt::alert::ip_block_notification
                    | libt::alert::progress_notification
                    | libt::alert::stats_notification;
```

**Comment by sledgehammer999** [comment]
We use `set_alert_notify()`. During start the first post has about 4-9 alerts. The 2nd one has about 20000 alerts, the 3rd one about 85000 alerts and then it starts going between 1-3.
And that's only with 34 torrents in the queue. Some users have hundreds or even thousands of torrents. At what value should the queue be for those cases?

**Comment by evsh** [comment]
Maybe a narrow alert mask set on startup until all torrents get resumed would help?

**Comment by sledgehammer999** [comment]
I did some more investigating. The vast majority(~106000) of the alerts during startup are `piece_finished_alert` and the 2nd most posted category(~430) is `file_completed_alert`

>Maybe a narrow alert mask set on startup until all torrents get resumed would help?

The above both belong to the `progress_notification` category. From that category we seem to explicitly handle only `file_completed_alert`.
We need to investigate if our flow won't have undesirable sideffects if we disable this category for startup purposes.

**Comment by arvidn** [comment]
thanks for looking into this. these are great finds! @d-komarov had similar observations that were addressed in https://github.com/arvidn/libtorrent/pull/2962

The priority of `fastresume_rejected_alert` should probably be increased.
And perhaps the `progress_notification` category should be split up into smaller categories.

**Comment by evsh** [comment]
> We need to investigate if our flow won't have undesirable sideffects if we disable this category for startup purposes.

Another approach: bind to localhost only until torrents are loaded to decrease alerts count.

**Comment by arvidn** [comment]
Another thing that may be worthwhile would be to not have `piece_finished_alert` and `file_completed_alert` posted as a result of checking files or fast-resume, but only as a result of downloading.

In addition to solving this problem I was thinking about how to make it easier to detect when alerts are being dropped. I'm working on a patch that posts another alert to indicate which kinds of alerts were dropped. That would at least leave some hints in the log.

> Why does libtorrent accept the fastresume data, when it clearly posted an error code?

The resume data contains more information than just what parts of the torrent have been downloaded. Things like lists of peers, banned peers, upload/download counters, download- and seeding time counters, etc. The resume data being accepted means that those things were loaded (iirc).

**Comment by sledgehammer999** [comment]
>Another approach: bind to localhost only until torrents get loaded to decrease alerts count.

I don't think this will improve something. `piece_finished_alert` will still dominate the queue.

>Another thing that may be worthwhile would be to not have piece_finished_alert and file_completed_alert posted as a result of checking files or fast-resume, but only as a result of downloading.

I was wondering the same thing. At least qbittorrent, doesn't need them for startup. We could update the alert mask after the torrents have been loaded as @evsh said, but it is hard to tell when loading has finished. (we do async add torrent)

@arvidn is there any drawback in setting `alert_queue_size` to `std::numeric_limits<int>::max()`?

**Comment by arvidn** [comment]
Does this make sense? https://github.com/arvidn/libtorrent/pull/3064

**Comment by arvidn** [comment]
These are the changes related to this issue:

1. In master the `progress_notification` category was split up into `block_progress_notification`, `file_progress_notification` and `block_upload_notification`.
2. I'm adding an alert notifying of the dropped alerts (to make it more obvious when it happens).
3. In `RC_1_1` we introduced 3 levels of priority for alerts, and reviewed the alerts to make some much less likely to be lost (https://github.com/arvidn/libtorrent/pull/2962 https://github.com/arvidn/libtorrent/pull/3036 )
4. I will raise the priority of `fastresume_rejected_alert` in `RC_1_1` ( https://github.com/arvidn/libtorrent/pull/3065 )

> is there any drawback in setting `alert_queue_size` to `std::numeric_limits<int>::max()`?

The main risk is that you may end up a bunch of memory, and maybe cause some swapping, if there's a hick-up and alerts don't get popped quickly enough. Swapping may exacerbate the issue.

**Comment by sledgehammer999** [comment]
>The main risk is that you may end up a bunch of memory, and maybe cause some swapping, if there's a hick-up and alerts don't get popped quickly enough. Swapping may exacerbate the issue.

But this would happen with many many many torrents in the session, right? Assuming, you have an alert mask for a regular stuff.
What I mean is that even you set the queue size to X, it will not occupy the memory automatically. It does that on demand if alerts are starting to pile up.
So in a hickup you choose to either lose alerts because they're dropped or start swapping. None of the options seems attractive. But I imagine we're talking about extreme situations to have such high alert churn.

**Comment by arvidn** [comment]
That's correct

**Comment by arvidn** [comment]
I landed #3065. I don't think there's much more I can do in `RC_1_1`. I wouldn't really recommend always subscribing to `progress_notification`, but I realise it's difficult with it covering so many kinds of alerts.

Do you think it's reasonable to close this? Or can you think of something else that can be done in `RC_1_1`>

**Comment by sledgehammer999** [comment]
Sorry, I forgot to close this.
I don't think something else can be done for RC_1_1.

Also don't forget to consider:
>Another thing that may be worthwhile would be to not have piece_finished_alert and file_completed_alert posted as a result of checking files or fast-resume, but only as a result of downloading.

If not for RC_1_1, at least for master.

Thanks for all the feedback.

**Comment by sledgehammer999** [comment]
PS: All qbt users watching this bug report: I'll be creating a PR addressing this issue on qbt the coming days.

**Comment by turbodude** [comment]
Guys holly molly, is this still not fixed? My qbittorrent just redownloaded 2 gigs worth of data because of this bug on a private tracker where it's very hard to keep positive ratio

**Comment by arvidn** [comment]
in libtorrent, adding a torrent for the first time, and adding a torrent because it was part of the last session's torrent list (i.e. resuming), is the same thing.

The problem with assuming that the user doesn't want the files to be re-downloaded when they aren't there, is that then they won't be downloaded the first time either, because the files aren't there yet.

**Comment by arvidn** [comment]
I'm not exactly sure I know what you're asking. since this ticket is about treating *new* torrents differently from *old* torrents, it isn't so much their "state" as much as having two different ways of adding them to the session, or rather, two different ways of interpreting the resume data.

I added the flag `no_verify_files` to `torrent_flags`. If this flag is set when *resuming* a torrent, libtorrent won't look at files on disk, but just assume the files are in the same state as when shutting down last. I believe this support the desired behavior. If a peer the requests a piece from those files, it will result in a disk I/O error and the torrent will be stopped.
