### ISSUE TITLE
Hide parts file on Windows too

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#3050]
**Please provide the following information**

libtorrent version (or branch):
Latest RC_1_1

platform/architecture:
Windows 7 x64

compiler and compiler version:
msvc2017 x64

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

On linux, the parts file is automatically hidden because it begins with a dot.
On Windows, you have to explicitly set the `hidden` attribute to the file. This currently isn't happening.

Extra info:
In `part_file::part_file()` I tried to change
```c++
m_file.open(fn, file::read_only, ec);
```
to
```c++
m_file.open(fn, file::read_only | file::attribute_hidden, ec);
```
but it didn't work. Unfortunately the internals of file::open() confused me and I gave up.

**Comment by arvidn** [comment]
the place where the partfile is opened for `read_only` probably won't affect how the file is *created*. So the `attribute_hidden` flag should probably be placed on another call to open of the partfile

**Comment by arvidn** [comment]
does this do what you want? https://github.com/arvidn/libtorrent/pull/3051

**Comment by Col-blimp** [comment]
Would it be possible to have the default file storage give an optional folder to keep all these parts files in?
