### ISSUE TITLE
error LNK2001: unresolved external symbol

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#3052]
Master.

Build: `--hash toolset=msvc-14.1 boost-link=static asserts=production address-model=64 runtime-link=static deprecated-functions=off encryption=on crypto=openssl link=static dht=on logging=on i2p=on variant=release`

Using VS 15.7.1

Error: `error LNK2001: unresolved external symbol "char const * const libtorrent_assert_log" (?libtorrent_assert_log@@3PEBDEB)`

What's happening is asserts.hpp is picking up `TORRENT_USE_ASSERTS` and `TORRENT_PRODUCTION_ASSERTS` and recognising `extern char const* libtorrent_assert_log;` but from my project.cpp If I do this:

```
std::string x = "example_path"
libtorrent_assert_log = x.c_str();
```

then VS recognises `libtorrent_assert_log` as `char const* libtorrent_assert_log` and accepts the change in path but upon build/rebuild it throws the fatal error LNK2001.

Libtorrent master 1.2.0.0 62cdec8 from a week or so ago is working fine though.

**Comment by arvidn** [comment]
please try this patch https://github.com/arvidn/libtorrent/pull/3055

**Comment by Col-blimp** [comment]
Fixed, thank's.
