### ISSUE TITLE
get .torrent from magnet link

### ISSUE THREAD

**Issue by Manu-sh** [arvidn/libtorrent#3060]
libtorrent version (or branch): 1.1.7
platform/architecture: Linux 4.16.4 x86_64
compiler and compiler version: gcc 8.1.0

im unable to find a good way to get `libtorrent::torrent_info` from a `std::string magnet_uri`, i need to get info about torrent and his file using only the _sha1 hash_ contained in the url. That i have do sucks and it's inefficient:

```cpp
std::string magnet_uri{"long magnet"};
tlib::session ses;
tlib::settings_pack sett;
tlib::add_torrent_params minfo;
tlib::error_code ec;

tlib::parse_magnet_uri(magnet_uri, minfo, ec);
minfo.save_path = "/dev/null"; // i don't really want that
minfo.max_uploads  = 1;
minfo.upload_limit = 0;

assert(!ec);

sett.set_str(tlib::settings_pack::string_types::listen_interfaces, "0.0.0.0:5122");
sett.set_bool(tlib::settings_pack::bool_types::enable_upnp, false);
sett.set_int(tlib::settings_pack::int_types::alert_mask, alert_type::all_categories);
ses.apply_settings(sett);
ses.async_add_torrent(minfo);

	for (;;) {

		std::vector<tlib::alert*> alerts;
		ses.pop_alerts(&alerts);

		for (tlib::alert *a : alerts) {

			assert(a);

			if (auto *alert = tlib::alert_cast<tlib::torrent_added_alert>(a)) {

				auto &thandle = alert->handle;
				assert(thandle.is_valid());

				auto tstat = thandle.status();
				cout << tstat.name << " [+]" << endl;

				thandle.auto_managed(false);
				thandle.set_max_uploads(1);
				thandle.set_upload_limit(0);
				thandle.set_upload_mode(false);
				thandle.set_share_mode(false);
				thandle.resume();
			}

			if (auto *alert = tlib::alert_cast<tlib::state_update_alert>(a)) {

				for (auto &tstat : alert->status) {

                                        // copy .torrent information from libtorrent::torrent_stat
					TorrentInfo tinfo{tstat};
					if (!tinfo.is_valid())
						continue;

					cout << tinfo << endl;
					assert(tstat.handle.is_valid());
					tstat.handle.pause();
					ses.remove_torrent(tstat.handle, tlib::session::delete_files); // yes don't make sense
				}
			}

			if (auto *alert = tlib::alert_cast<tlib::torrent_removed_alert>(a)) {
				cout << alert->what() << "\n" << alert->message() << "\nDONE" << endl;
				return 0;
			}

			if (auto *alert = tlib::alert_cast<tlib::torrent_deleted_alert>(a)) {
				cout << alert->what() << "\n" << alert->message() << "\nDONE" << endl;
				return 0;
			}

			if (auto *alert = tlib::alert_cast<tlib::torrent_delete_failed_alert>(a))
				assert(false);

			// cout << a->what() << endl;
			// cout << a->message() << endl;

			std::this_thread::sleep_for(std::chrono::milliseconds(200));
			ses.post_torrent_updates();
		}
	}
```

**Comment by sledgehammer999** [comment]
Something unrelated:

```c++
std::this_thread::sleep_for(std::chrono::milliseconds(200));
ses.post_torrent_updates();
```

I think these should be on your outer for loop. Not in the one that iterates over the alerts.

Also since each alert can only be one type of alert you either do a chain of
```c++
if () {
}
else if () {
}
else if () {
}
...
else {
}
```
or utilize the `switch` statement and do 
```c++
switch(a->type()) {
case libtorrent::state_update_alert::alert_type:
// code
break;
case libtorrent::torrent_removed_alert::alert_type:
// code
break;
default:
}
```

**Comment by Manu-sh** [comment]
>You also need to handle the metadata_received_alert and metadata_failed_alert
You need to run libtorrent::session and let it connect to DHT nodes. The metadata(aka .torrent) are downloaded by peers. The peers are usually found via DHT. When metadata are received correctly you'll get the metadata_received_alert and you can save the torrent_info as shown in the example code in the link.

These alert doesn't work or are received too later (really too later) this is the reason of why i have used `tlib::alert_cast<tlib::state_update_alert>(a)`, because this alert is received first, regard to the `switch` i don't have used because `if` it's shortest and i can simply copy and change only the alert name to test more alert (this it's only a main file to understand what i can do with) but thank's for your suggestion @sledgehammer999.

**Comment by Manu-sh** [comment]
okay @sledgehammer999 all my problem with `metadata_received_alert` was caused by:
```cpp
std::this_thread::sleep_for(std::chrono::milliseconds(200));
ses.post_torrent_updates();
```

in the wrong loop, thank you very mutch !!!

**Comment by sledgehammer999** [comment]
Then close the bug report.

**Comment by XamarinDeveloper** [comment]
@Manu-sh Hey could you give me the complete code for doing this? I really need it. plz
