### ISSUE TITLE
Speed becomes zero

### ISSUE THREAD

**Issue by n0n0n0n0** [arvidn/libtorrent#3074]
**Please provide the following information**

libtorrent version (or branch):
1.0.11.0
platform/architecture:
Windows
compiler and compiler version:
VC
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I have an application with libtorrent included and torrent file with web/torrent seeds.
Some users experiencing problem with speed, when they downloaded huge part of torrent (usually more than 95%) speed becomes zero. They need to relaunch download more and more to download full torrent. Also i noticed that if torrent blocked by ISP with web seed it's impossible to download 100% of torrent.

**Comment by arvidn** [comment]
do you have a reason to believe there's a bug in libtorrent causing this?
if so, what specifically do you see causing the drop of download speed, and what's your theory?

**Comment by n0n0n0n0** [comment]
I've checked everything over the past year and anyway about 5% of users has the problem.
It happen sometimes for random users, now i'm trying to update it to latest version but think everything will be same.
I'm not sure what else can has influence on download speed, i'm not control it and leave it as is.
I think the problem with communicating between webseed and torrent seeds. Noticed also that users with 100% torrent blocked by ISP can't download full files list up to 100% and it's not multithreaded (fill size about 20gb).

Usually it divides to two problems: 
1. When user almost downloaded full pack (99.9+) and needs to put torrent file in uTorrent to download 100%
2. When speed stopped somtimes and user need to restart app (ISP speed checked and usally it's even more than 30-50mbit) more and more times.

**Comment by n0n0n0n0** [comment]
still have this problem.
