### ISSUE TITLE
Clarification on values for outgoing_interfaces

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#3087]
There is a bit of confusion on what to use as values for outgoing_interfaces. As far as I was aware on Unix these are adapter names and on Windows IP addresses as a compromise. Should we be strict about not letting the value be an IP address on Unix and only allow it for Windows? We did encounter errors when the default was set to '0.0.0.0' on Unix.

From the docs:

> Ths parameter must be a string containing one or more, comma separated, adapter names. 

From code: https://github.com/arvidn/libtorrent/blob/RC_1_1/include/libtorrent/string_util.hpp

> // it is a comma separated list of IPs and device names. For example:
// "eth0, eth1, 127.0.0.1"

There is no mention in either place about Windows.

Does libtorrent accept IP addresses for outgoing interface on Unix?
Should it accept '0.0.0.0' as equivalent to empty string?
What happens if the adapter does not exist?

**Comment by arvidn** [comment]
I believe both adaptor/device names and IP addresses are accepted. I don’t think there’s anything special about Windows (except that adapter names are long and ugly)

**Comment by cas--** [comment]
That is strange about Windows because last I read on the mailing list it was not possible to use adapter names? 

This was the issue on Deluge that prompted these questions: https://github.com/deluge-torrent/deluge/pull/180#issuecomment-394018001

**Comment by Col-blimp** [comment]
You can use the 'name' within the {} on windows but that's not the friendly name as the user can edit that.

**Comment by cas--** [comment]
@arvidn Users reported setting '0.0.0.0' on linux stops all network traffic

```
peer_blocked_alert:  - : blocked peer: ip1 [invalid_local_interface]
```

**Comment by arvidn** [comment]
that seems to work as intended. there is no interface with address "0.0.0.0", and so all connections are blocked. No connection will ever have the local IP 0.0.0.0

**Comment by cas--** [comment]
Except that it has been used to denote all interfaces in `listen_interfaces`. I see that the problem now is that the original commit should have used empty string not '0.0.0.0' as in `listen_interfaces`...
