### ISSUE TITLE
SIGABRT - Assert fail in invariant checker

### ISSUE THREAD

**Issue by RicoTilgner** [arvidn/libtorrent#3089]
libtorrent version (or branch): [tags/libtorrent-1_1_7]

platform/architecture: linux x64

compiler and compiler version: gcc (GCC) 7.3.1 20180406

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

running a client with a couple (<100) share_mode only torrents, it consistently crashes after a few hours. Just built a libtorrent with invariant checks enabled and it complains about m_in_use in peer_connection::second_tick.
Full stack trace: [stack.txt](https://github.com/arvidn/libtorrent/files/2074088/stack.txt)

**Comment by RicoTilgner** [comment]
I've been running the fix suggested in #3084 now and it's been running stable for ~15h now.

**Comment by arvidn** [comment]
good to know. that setting is 0 by default at least

**Comment by RicoTilgner** [comment]
sorry, wrong alert, libtorrent this time actually went into an infinite loop. Unfortunately I only realized after I killed it already. :/

**Comment by aldenml** [comment]
@RicoTilgner can you test `master`? there are a lot of improvements (and fixes) there related to iteration and disconnection of `m_connections`

**Comment by RicoTilgner** [comment]
thanks for the tip!
Built from master now, can definitely see a difference in peer management... upload rate is way higher than with 1.1.7. :)
I'll let it run for a while now in debug mode and see if the problem still repros.
