### ISSUE TITLE
Having problems with RAND_bytes in android

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#3103]
libtorrent: `master`
platform/architecture: `android/arm`

Hi, I'm having a very very small occurrence of no enough entropy when calling `RAND_bytes` in `random_bytes`. I have the idea that this could be a problem of faulty devices with occasional no access to `/dev/urandom` used internally to seed the PRNG (it happens). I find a little odd having an exception crash due to a call to `random_bytes` in general.

Since this function is called quite frequently in the DHT logic, I would like to read from `/dev/urandom` directly for better performance, but even with that, I can get errors due to no access at a given moment.

My questions is: It's wise to relax the comment "generates cryptographically random bytes" and fallback to simple `for (auto& b : buffer) b = char(random(0xff));` in case of an error? If the fallback is reasonable, how to detect if the error is happening with high rate?

**Comment by arvidn** [comment]
it does seem reasonable to read from `/dev/urandom` instead.

**Comment by ssiloti** [comment]
There is at least one place where `random_bytes` is used which requires a cryptographically secure PRNG (`ed25519_create_seed`) so falling back to to `random` is not acceptable as-is.

I'm curious about reads from `/dev/urandom` failing on Android. There's really no good reason for such reads to fail on a system like Android where the OS can ensure there is adequate entropy before any application code runs. A quick google doesn't find any evidence that this is a known issue, do you have any references you can share?

**Comment by aldenml** [comment]
Actually, I based my "theory" on https://github.com/square/okhttp/issues/3135 and other native crashes (not related to `libtorrent`) I can see in the developer console. Android as a linux PC has very weird issues.
