### ISSUE TITLE
duplicate peer-id (reason: 0)

### ISSUE THREAD

**Issue by couragecoder** [arvidn/libtorrent#3109]
**Please provide the following information**

libtorrent version (or branch):
libtorrent-libtorrent-1_1_7

platform/architecture:
Linux host-10-196-62-9 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

compiler and compiler version:
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
using example client_test and opentracker can not download file called "boost_1_66_0.7z". Log info below:
[Jun 14 18:44:50] UDP error: Bad file descriptor from: 0.0.0.0
[Jun 14 18:44:50] UDP error: Bad file descriptor from: 0.0.0.0
[Jun 14 18:44:50] UDP error: Bad file descriptor from: 0.0.0.0
[Jun 14 18:44:50] UDP error: Bad file descriptor from: 0.0.0.0
[Jun 14 18:44:50] successfully listening on [TCP] [::]:6881
[Jun 14 18:44:50] successfully listening on [TCP] 0.0.0.0:6881
[Jun 14 18:44:50] successfully listening on [UDP] 0.0.0.0:6881
[Jun 14 18:44:50] added torrent: boost_1_66_0.7z
[Jun 14 18:44:50] boost_1_66_0.7z added
[Jun 14 18:44:50] boost_1_66_0.7z resumed
[Jun 14 18:44:51] boost_1_66_0.7z: state changed to: downloading
[Jun 14 18:44:51] boost_1_66_0.7z checked
[Jun 14 18:44:51] boost_1_66_0.7z (http://10.196.62.9:6969/announce) sending announce (started)
[Jun 14 18:44:51] boost_1_66_0.7z (http://10.196.62.9:6969/announce) received peers: 2
[Jun 14 18:44:51] incoming connection from [::1]:24202 (TCP)
[Jun 14 18:44:51] boost_1_66_0.7z peer ([::1]:24202, libtorrent 1.1.7) disconnecting (TCP) [bittorrent] [libtorrent]: duplicate peer-id (reason: 0)
[Jun 14 18:44:51] boost_1_66_0.7z peer ([::1]:6881, libtorrent 1.1.7) disconnecting (TCP) [sock_read] [asio.misc]: End of file (reason: 0)
[Jun 14 18:44:55] incoming connection from 10.196.62.10:16298 (TCP)
[Jun 14 18:44:55] boost_1_66_0.7z peer (10.196.62.10:16298, libtorrent 1.1.7) disconnecting (TCP) [bittorrent] [libtorrent]: duplicate peer-id (reason: 0)
[Jun 14 18:44:55] boost_1_66_0.7z peer (10.196.62.10:6881, libtorrent 1.1.7) disconnecting (TCP) [sock_read] [asio.misc]: End of file (reason: 0)
[Jun 14 18:45:51] incoming connection from [::1]:61533 (TCP)
[Jun 14 18:45:51] boost_1_66_0.7z peer ([::1]:61533, libtorrent 1.1.7) disconnecting (TCP) [bittorrent] [libtorrent]: duplicate peer-id (reason: 0)
[Jun 14 18:45:51] boost_1_66_0.7z peer ([::1]:6881, libtorrent 1.1.7) disconnecting (TCP) [sock_read] [asio.misc]: End of file (reason: 0)
[Jun 14 18:45:58] incoming connection from 10.196.62.10:11139 (TCP)

**Comment by arvidn** [comment]
as far as I can tell you're the only peer on that swarm. it looks like `10.196.62.10` and `[::1]` is your peer (hence the duplicate peer ID).

Do you have a seed?
How do you expect to find it? Is there a tracker?

**Comment by arvidn** [comment]
you may find this helpful: https://libtorrent.org/troubleshooting.html

**Comment by couragecoder** [comment]
I deployed tracker and client_test of seed mode both located at the same server, another client_test deployed on a different server.

**Comment by couragecoder** [comment]
I recompiled the source, upload and download work well, it must be env problem of myself.

Thank you.
