### ISSUE TITLE
On startup download speed stuck at 0Kbytes/sec for 10 seconds

### ISSUE THREAD

**Issue by dimitriss** [arvidn/libtorrent#3131]
libtorrent version (or branch): RC_1_1
platform/architecture: Linux-arm64
compiler and compiler version: GCC6

New torrent download problems with commit c55bc7dd420f5f79b571e85d0984049a6fa28307. Transfer speed is at 0Kbytes/sec for the first 10 to 15 seconds. 
Same branch, same build, same torrent with this commit reverted works fine.

**Comment by arvidn** [comment]
does this happen consistently? Do you have any instructions on how to reproduce it?

**Comment by arvidn** [comment]
would you be able to produce a log (enable session, torrent and peer logging and print alerts to a file)?

**Comment by dimitriss** [comment]
Here is all log with alerts set to all_categories
[4164790068.zip](https://github.com/arvidn/libtorrent/files/2140598/4164790068.zip)

**Comment by arvidn** [comment]
does this only happen with magnet links? i.e. is it possible the problem is it taking longer to get the metadata from the swarm?

**Comment by arvidn** [comment]
If that commit really is the one causing the problem, presumably it has something to do with file priorities. Are you setting any file priorities? or piece priorities?

perhaps the returned priority vector gets corrupted somehow, and we think all files have priority 0 for a little while, resulting in not being interested in any peer.

**Comment by dimitriss** [comment]
Yes I'm setting both file, piece priorities and using sequential download. Issue occurs only with magnets.

**Comment by arvidn** [comment]
can you describe when and to what you set the priorities to? also how you interleave setting of both piece- and file priorities. Normally they don't mix well, as file priorities overwrite piece priorities.

There's no log emitted for updating priorities so I can't tell from the log

**Comment by dimitriss** [comment]
After getting metadata I'm setting file priority 1 to largest file and 0 to the other files of the torrent

**Comment by d-komarov** [comment]
#3133 might be fixing this issue.

**Comment by dimitriss** [comment]
Yes issue resolved with https://github.com/arvidn/libtorrent/pull/3133
