### ISSUE TITLE
Parts file: allow export in seed mode

### ISSUE THREAD

**Issue by d-komarov** [arvidn/libtorrent#3138]
libtorrent branch: RC_1_1

When torrent enters _seed mode_ it is not possible to change file priorities any more, afterwards any unwanted file within *.parts becomes locked. I.e. there is no way to export them without full recheck, that could be very expensive in terms of time consumption.

Currently there are two known workarounds for this issue:

1. Force recheck and then instantly update file priority. May fail to work from time to time.
2. Remove torrent from session with `delete_partfile` option. Then re-add torrent with new file priorities. Despite it is possible to skip recheck in this scenario, it still doesn't look straightforward.

Some users could find it superfluous, so a simple solution must be introduced.

**Comment by d-komarov** [comment]
Another issue reference https://github.com/qbittorrent/qBittorrent/issues/8122

**Comment by arvidn** [comment]
does this seem like it would work? https://github.com/arvidn/libtorrent/pull/3168

**Comment by d-komarov** [comment]
Yes this should be working, but I would also expect 'torrent_status' to be affected. But at first glance it wouldn't, because piece priorities wouldn't be updated because 'is_seed()' is still there. If 'is_seed()' is ignored for file priorities, why it persists for piece priorities. Perfectly this change should free the client code from separate tracking of 'total_wanted' and 'total_wanted_done' amounts.

**Comment by arvidn** [comment]
the thing with piece priorities is that they're kept by the piece picker. When you're a seed the piece picker is destructed, since none of its state is really necessary anymore. For seeds, pieces are always exposed as having priority 4 (the default).

This is why total_wanted and total_wanted_done isn't updated by just changing the file priorities too. They are just a layer on top of piece priorities, but when you're a seed, the piece priority isn't a thing anymore.

**Comment by arvidn** [comment]
in short, updating `total_wanted_done` and `total_wanted` based on file priorities, when we have all pieces, is non trivial and would require a bigger and more fundamental change.

**Comment by d-komarov** [comment]
Well, at least I would expect the particular alert to be posted when export process is done. Would either 'torrent_finished_alert' or 'cache_flushed_alert' be posted?

**Comment by arvidn** [comment]
yeah, something like that should probably be done in master. I landed this patch for RC_1_1 though
