### ISSUE TITLE
Error state on unregistered torrents not set correctly (tracker_backoff and autodl)

### ISSUE THREAD

**Issue by niayh** [arvidn/libtorrent#315]
Hey there,

I've been trying to get Deluge 1.3.12 + Libtorrent 1.0.7 to work in conjunction with an autodl filter and a watch folder from a private tracker. I've been running around in circles trying to figure out why if when a torrent is added before the tracker has registered it, the client will wait a full 30 minutes until the next announce to refresh.

I found the tracker_backoff setting and was hopeful that this would fix my problem; however, no amount of changing this value would do anything to solve my problem with unregistered torrents. The torrent gets added and if the torrent is not registered, the announce interval is set to 30 minutes.

I started wondering, perhaps a failure isn't being reported properly somehow. Sure enough, I altered the tracker URL to something bogus and suddenly the retry intervals were set according to the tracker_backoff setting ( 7, 15, 27, 45, 95, 127, 165 seconds, etc). This leads me to believe that somehow the error status on unregistered torrents isn't being recognized properly, even though the Announce Status reads: Error: (Unregistered Torrent) and as a result of being able to connect to the tracker, libtorrent decides to announce as if all is normal and set the next refresh to 30 minutes.

This may be a tracker specific issue; however, it's worth noting that the error state is read correctly when using AutoDL with rtorrent.

**Comment by niayh** [comment]
Upon a bit more investigation, this appears to be an issue localized to a single tracker. Is there any way to refine the definition of failure in this circumstance?

**Comment by arvidn** [comment]
I would be interested in seeing an example response from this tracker, if you have one (ideally as a wireshark capture).

I would expect that if the tracker responds with a proper "failure reason" key, libtorrent would treat it as a failure (as opposed to a "warning message" key). However, whether libtorrent treats it as a fatal error or not probably would depend on some other property of the response. i.e. tracker failures aren't necessarily fatal, but could be transient. libtorrent does not implement http://bittorrent.org/beps/bep_0031.html 

However, passing a very large announce interval might work.

**Comment by niayh** [comment]
Thanks for the response. I got you an example output log from deluge when the error occurs and I also grabbed 2 different sets of packets that I received in response from trying to add the torrent to the tracker.

https://www.dropbox.com/s/440db7d65ct64v6/unregistered.log?dl=0

Do you mean increasing the autodl delay? I'm reluctant to do so because even with as large of a delay as 45 seconds, I still miss announces from time to time. Conversely, torrents that announce within 15 seconds, I would miss all or part of the main swarm.

**Comment by niayh** [comment]
Set up a few more autodl tests on other trackers and turns out another one of my trackers performs in the same manner to the one in the test, so that makes 2 trackers now.

**Comment by arvidn** [comment]
by "announce interval" I meant the key the tracker is supposed to return in the tracker response. If the tracker would do that, libtorrent would not try again until that many seconds.

I notice the tracker response in your capture literally just contain a "failure reason" key/value. This is a bit odd and not really how I would read the specification. I would think that it's reasonable to try again 30 minutes later in this case. Is that what you see libtorrent do?

I'm curious, how do other clients behave? Do they simply consider the response invalid and never talk to the tracker again? (for that torrent). If so, I wonder if the reason not to talk to it again is that the response is too broken, or because the "failure reason" message exist in the response.

**Comment by niayh** [comment]
Ahh, I see now, what you mean by announce interval.

Libtorrent is indeed behaving how you think: resetting to 3minutes

When I use rtorrent the behavior is what I am hoping to see in deluge: rtorrent lists the torrent as if it is in error mode and keeps trying to sync with the tracker in small intervals until it manages to do so. At this point, it backs of to regular intervals.

**Comment by arvidn** [comment]
please re-open if there's anything actionable here

**Comment by slaughtermouse** [comment]
I'm also seeing this as well with libtorrent: 1.0.7.0 and deluge 1.3.12, where rtorrent will correctly retry in smaller intervals deluge sets the retry to 30 minutes which means you completely miss the swarm when it eventually announces.

Is it not possible to treat value received per the above captures as an error state that will trigger tracker_backoff ?

**Comment by arvidn** [comment]
my understanding of what you're asking for is the opposite of back-off.. if a tracker fails, you want to try it again _more_frequently_ than you would normally contact it. The obvious risk is that a tracker getting overwhelmed with traffic will receive increasing amount of traffic as clients retry frequently.

Is there something unique about these tracker failures that indicate that the torrent will be available soon?

Do you have an idea of a reasonable behavior to improve the situation?

**Comment by slaughtermouse** [comment]
Yeah, not 100% sure on terminology, I'm just expanding on what the OP posted about.

I guess the unique aspect comes from using something like autodl-irssi which automatically downloads a torrent file that has been announced by a particular trackers bot.

What happens is the download of the torrent file happens so quick, then added to deluge, before the tracker seems to be aware of it so it ends up sitting in an unregistered state until the torrent client announces again. So in a sense the torrent file is definitely valid, just happens too fast.

With autodl-irssi you can set a delay to avoid this but as described above its a fine line between setting the delay for too long or too short that you end up missing the swam.

The way rtorrent handles the exact same tracker is it retries within seconds of the torrent being added in the "unregistered torrent" state, rather than waiting 30 minutes like Deluge

**Comment by arvidn** [comment]
would it be reasonable to perhaps have an exception where, if the torrent was added recently enough, the retry timeout is shorter.

**Comment by niayh** [comment]
This sounds reasonable to me -- even a window as small as 5-10 minutes could be sufficient to avoid the described behavior

**Comment by slaughtermouse** [comment]
I think 5 to 10 minutes is still too long though, it needs to be in seconds
as on competitive trackers 5 to 10 minutes is long enough for 90% of people
to have completed the download which would result in a lower than
acceptable ratio

Can it be a ramping sort of behaviour e.g. Try in 5 seconds then (if failed)10
seconds then 15 seconds and so on?

Obviously the goal is to not smash the tracker so I'm not sure how rtorrent
does it

**Comment by arvidn** [comment]
on the other hand, if the tracker admins incentivize hammering the tracker, and publish the torrent before their tracker whitelist it, perhaps they want people to hammer their tracker.

**Comment by slaughtermouse** [comment]
I'm not really sure what to say other than rtorrent handles it fine

**Comment by ssiloti** [comment]
Personally I'm opposed to making any accommodations for this. The trackers here are broken in at least two ways:

1. They publish torrents before they have been authorized.
2. They enforce a minimum ratio. This is broken because pure ratio is a zero sum so you end up with the degenerate behavior of people jumping on any and all torrents the instant they go up in a desperate bid to find someone to upload to.

These issues should be taken up with the tracker admins, not hacked around in libtorrent.

**Comment by slaughtermouse** [comment]
Probably easier to just stick with adding a delay to the download script.

As you say, it's clearly a tracker issue.

**Comment by arvidn** [comment]
your download script could hammer the tracker until receiving a legitimate response, and then add the torrent. :)

**Comment by slaughtermouse** [comment]
lol, what it does is when it receives the announce from the irc bot it
waits X seconds before downloading the torrent file.. that way nothing gets
hammered

**Comment by slaughtermouse** [comment]
Actually, now that I've had more time to process this wouldn't you just be adding another condition based on the OP's scenario that would use the tracker_backoff function?

Or am I just being ignorant here?

**Comment by arvidn** [comment]
trackers are re-tried with an exponential back-off if we fail to connect to them (and possibly if they return some fatal error at a layer below the bittorrent-tracker protocol, like an HTTP 503).

In this case, we are successful in connecting and talking to the tracker at the bittorrent-level protocol. This means we can be certain the tracker is there and expects to be used as a bittorrent tracker.

At that point, the tracker has a fair amount of control over the client's behavior (for good reasons). If the tracker wants the client to never connect back again, or try again in a few seconds, it can ask the client to do so. In this case, iirc, it returns a somewhat strange and ambiguous response.

(also, currently there's actually a sanity check in libtorrent clamping re-announce intervals to 5 minutes, maybe the tracker should be trusted more than that).

My point is that, yes, it's possible to add a case where this is considered a failure at a lower level, and the tracker is retried. But this is just one tracker. The next tracker will presumably have a slightly different response in this situation. I imagine it would make a lot more sense to tighten up the specification and stay more true to it, than to sprinkle special cases around. The risk is that, at some point you run into a case where the special case causes the opposite effect that you want, and the user/admin is surprised of the behavior because it's undocumented.

**Comment by slaughtermouse** [comment]
Fair call.

Thanks for the explanation, makes more sense now!

**Comment by jmo4114979** [comment]
Hi.  I had the same problem.  I found the following solution and it works.  
http://wiki.bytesized-hosting.com/wiki/index.php/Autodl-irssi
It is the upload-delay-secs parameter.  I tried 27 as stated but it didn't work.  I the tried as 60 and it worked.  I have not fine tuned to find the lowest number of seconds.  This parameter can be set by tracker in the autodl.cfg file, and there is a global Delay parameter on the Filter General tab.  I set 60 on both.  Thanks for identifying this problem, I have been searching for days for a solution.  Jack.

**Comment by jmo4114979** [comment]
Oops I should have said I am using the rutorrent gui for the autodl-irssi configuration and it now works for both rtorrent and deluge so I set the global Delay parameter on rutorrent and I changed the ipt section on the deluge autodl.cfg for the tracker modification.

**Comment by jmo4114979** [comment]
Let me try one more time.  I guess the autodl.cfg is for the audodl-irssi.  On the rutorrent autodl-irssi Filter General tab there is a Delay at the global level and on the Trackers tracker tab there is a Delay at that tracker level.

**Comment by slaughtermouse** [comment]
Yeah, the delay functionality is useful.

The only problem I have setting a delay is there's a chance you might miss
the initial swarm. Unfortunately the tracker in question will announce
within a few seconds or more than a minute so there's quite a variance
there.

In the end I obtained and modified a script which makes use of the Execute
plugin for Deluge and update-tracker.py command from here
https://github.com/s0undt3ch/Deluge/blob/master/deluge/ui/console/commands/update-tracker.py

It loops through looking for the word unregistered and will initiate an
update-tracker command via deluge-console till it gets an Announce OK.

It's not ideal but it gets around the variable announce

**Comment by arvidn** [comment]
another interesting approach would be to remember the peers you typically see early on in swarms on a specific tracker, and optimistically just add those to the swarm. you may be lucky and hit the original seed even before the tracker gets around to whitelisting

**Comment by TacoDelPaco** [comment]
@slaughtermouse could you... post the script you 'obtained'?

Cough... thanks.

**Comment by slaughtermouse** [comment]
`#!/bin/bash
torrentid=$1
torrentname=$2
torrentpath=$3

x=1
while [ $x -le 45 ]
do
sleep 2
echo "Running $x times" >> script.log
echo "TorrentID: $torrentid" >> script.log
line=$(/usr/local/bin/deluge-console "connect 127.0.0.1:<port> <user> <pass>; info" $1 | grep "Tracker status")
echo $line >> script.log
case "$line" in
*unregistered*|*Sent*)
eval /usr/local/bin/deluge-console "connect 127.0.0.1:<port> <user> <pass>\; update-tracker '$torrentid'";;
*)
echo "Found working torrent: $torrentname $torrentpath $torrentid" >> script.log
exit 1;;
esac
x=$(( $x + 1 ))
done
`

Save it to a file of your choice, use the Execute plugin in deluge.

It's crude, some of the things in there are superfluous, but does the job

**Comment by monukoshy** [comment]
slaughtermouse.. thanks for the tips.
I've been having the same issue with a few trackers lately. I am using autodl with deluge.
I am missing the swarm and end up the last leecher thus messing up my ratio for any specific torrent for which i have set manual delay.

With the above work around, please let me know if i did the right thing, or i need to fix the steps.

1. created a scritpt workaround.sh
2. added the code to this script, and edited port and username/password entries for two different locations mentioned in the code.
3. enabled the execute plugin, and in the drop down i choose, "Torrent Added" and in the command line box i type "sh /home/user/.config/deluge/workaround.sh"
4. Hit apply and now wait.

Is this the correct steps?

**Comment by slaughtermouse** [comment]
Yep that's correct

You might need to restart deluge once you've enabled and added the execute
script once started.

When you add a torrent you should get a script.log generated in the same
location as the script

**Comment by plasticspoonn** [comment]
@slaughtermouse , I am pretty new to unix and my seedbox, I'm trying to implement your script using the path and script name monukoshy provided.

This is the correct command and path for execute?  sh /home/user/.config/deluge/workaround.sh

I am also not sure what port I should be putting into the script.

**Comment by slaughtermouse** [comment]
Yes, you have to restart deluge after you've enabled execute and added the
script.. as I've chmod +x'd my script I just call it as /home/user/script

The port refers to the port your deluge instance is listening on, default
is 20000 I think?

**Comment by plasticspoonn** [comment]
@slaughtermouse, Still getting same error, if I manually go into that folder and do a sh workaround.sh I can get it to spit out the script.log.  I think deluge cannot find the path.  This is the path of the file for me

/media/sdj1/<myusername>/.config/deluge/workaround.sh 

I have tried that and the path /home/user/.config/deluge/workaround.sh provided. 

As for the port, is it the server interface port? not the daemon port I assume.

**Comment by slaughtermouse** [comment]
Daemon port yes

Not sure, put the script in /media/sdj1 instead and/or try without sh

**Comment by MutatedHero** [comment]
I've been seeing this issue quite often at multiple trackers and missing the initial swarm in todays competitive enviroment is a hard hit on ones ratio.
@slaughtermouse, Your script looks like the only solution currently but after trying to convert it to batch for Windows, failing I thought I'd hear with you if that is something you've already done?

**Comment by slaughtermouse** [comment]
@MutatedHero, it's not something I've tried on Windows sorry. 

But when I have some time I'll see if I can whip something up

**Comment by fluxcapacitus** [comment]
Heya @slaughtermouse I set up your script by inserting my own info, but this is the error I get when I try to run it through putty on my seedbox.
```
/.config/deluge/delaything.sh: line 5: $'\r': command not found
/.config/deluge/delaything.sh: line 14: syntax error near unexpected token `$'in\r''
'/.config/deluge/delaything.sh: line 14: `case "$line" in
```

Any idea what that's all about?  I have very little programming and linux skills so I can follow along with what the script is basically trying to do but any syntax details go right over my head.

No errors or any other indicators in deluge and no log is created. I'm on latest versions of everything.
Thanks

**Comment by slaughtermouse** [comment]
@fluxcapacitus try editing in nano and remove the \r's from the end of each line in the script

________________________________

**Comment by fluxcapacitus** [comment]
@slaughtermouse I'm not seeing any of those in the script, the only \ I even see is at the end of the second password placeholder but deleting that didn't stop the error.

```#!/bin/bash
torrentid=$1
torrentname=$2
torrentpath=$3

x=1
while [ $x -le 45 ]
do
sleep 2
echo "Running $x times" >> script.log
echo "TorrentID: $torrentid" >> script.log
line=$(/usr/local/bin/deluge-console "connect 127.0.0.1:<port> <user> <pass>; info" $1 | grep "Tracker status")
echo $line >> script.log
case "$line" in
*unregistered*|*Sent*)
eval /usr/local/bin/deluge-console "connect 127.0.0.1:<port> <user> <pass>\; update-tracker '$torrentid'";;
*)
echo "Found working torrent: $torrentname $torrentpath $torrentid" >> script.log
exit 1;;
esac
x=$(( $x + 1 ))
done
```
It's an exact paste of your code snippet with the placeholders replaced with my login and port. Was I supposed to do something with the code from the page you linked? https://github.com/s0undt3ch/Deluge/blob/master/deluge/ui/console/commands/update-tracker.py

**Comment by slaughtermouse** [comment]
Try typing: which deluge-console

The location of your deluge-console might be different to mine being in /usr/local/bin/

Also, probably not required but don't forget to include `#!/bin/bash` at the top of the script

You need to copy update-tracker.py to the following, or relevant to your install, location: /usr/local/lib/python2.7/dist-packages/deluge-1.3.13_dev-py2.7.egg/deluge/ui/console/commands

Failing that, here's the script slightly updated https://drive.google.com/file/d/0B-Mod1AY73DdNTh6N1hiV25MY0E/view?usp=sharing

**Comment by fluxcapacitus** [comment]
The problem was no tracker-update.py and I can't add it because I don't have the permissions for that location with this seedbox provider. 
I wasn't really pleased with the service anyway so this is enough to get me to switch.  Thanks for the help, I'll come back in a month when this term expires. 

On January 17, 2017 1:44:18 AM MST, slaughtermouse <notifications@github.com> wrote:
>Try typing: which deluge-console
>
>The location of your deluge-console might be different to mine being in
>/usr/local/bin/
>
>Also, probably not required but don't forget to include `#!/bin/bash`
>at the top of the script
>
>You need to copy update-tracker.py to the following, or relevant to
>your install, location:
>/usr/local/lib/python2.7/dist-packages/deluge-1.3.13_dev-py2.7.egg/deluge/ui/console/commands
>
>Failing that, here's the script slightly updated
>https://drive.google.com/file/d/0B-Mod1AY73DdNTh6N1hiV25MY0E/view?usp=sharing
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/arvidn/libtorrent/issues/315#issuecomment-273054181

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by orytek** [comment]
Script is working good for me. I initially got errors in both files until I made sure to remove tabs in .py file and and non-unix line endings in script.
Thanks slaughtermouse.

**Comment by HYQ307** [comment]
@slaughtermouse 
  Hi there, i have done everything right but the question is the Script just doesn't work whenever a new torrents added in watch folder with "unregistered torrents" . Any idea how to fix that? Or did it doesn't work any more?
  I have copy the update-tracker.py also enabled the Excute in Deluge, just doesn't work.

**Comment by slaughtermouse** [comment]
Normally you need to restart deluge as the execute plugin doesn't always work off the bat

Also I assume you've added the script to the execute plugin, selecting the "torrent added" event and the command as /home/<user>/trachk or whatever you've called the script

For good measure chmod +x trachk from the command line

**Comment by HYQ307** [comment]
@slaughtermouse 
 I Do did all those. But it still does not work ? May you give a little test to see if it still works?

**Comment by slaughtermouse** [comment]
I have it running all the time

The script runs fine when you manually run it with no arguments?

Try running deluge-web without forking to daemon you might be able to see
an error as to why the script isn't running when the torrent is added

**Comment by HYQ307** [comment]
I manually run the scripte and get this: 
"Running 1 times
TorrentID:
Tracker status: awesome-hd.me: Announce OK Tracker status: awesome-hd.me: Announce OK Tracker status: chdbits$
Found working torrent:"

So i guess the script works fine. But the question is whenever a new torrents added, it just doesn't work to update the tracker. Here is what i set in Deluge Excute:
[img]https://picload.org/image/rcpclcgl/1.png[/img]

And i also reboot to make it apply. But doesn't work when an unregistered torrents added.

@slaughtermouse

**Comment by slaughtermouse** [comment]
Not sure, all I can suggest is you don't need to add bash in front of the
script, it should just be /location/to/script.sh

http://dev.deluge-torrent.org/wiki/Plugins/Execute

**Comment by HYQ307** [comment]
Yeah, this time works. Thansk for helping.

**Comment by slaughtermouse** [comment]
np

**Comment by slaughtermouse** [comment]
did you chmod +x <scriptname> the script?

**Comment by tuga1982** [comment]
Hello yes I did.

**Comment by slaughtermouse** [comment]
can you ls -l <scriptname>

also ensure the location is correct and the user running deluged can
actually access the location

**Comment by tuga1982** [comment]
Hello my problem is I did not copy update-tracker.py but my problem is that the seedbox provider do not share with me this folder.

Any possible solution?

**Comment by tuga1982** [comment]
sh unregistered.sh
Unknown command: update-tracker

**Comment by slaughtermouse** [comment]
You could just ask your hosting provider to place the file in the location
for you, or see if there's an alternate location deluge looks for

**Comment by tuga1982** [comment]
I already asked the provider he told me I should install my own version of deluge.

How to check where deluge looks for the file?

**Comment by adir6** [comment]
Hi, I am facing the same issue but none of the solution worked.

https://i.imgur.com/Chpe18m.png

**Comment by arvidn** [comment]
@adir6 you mean the tracker is not retried at all? are you sure the tracker *is* allowing that torrent?
I think this ticket is old and diluted  enough that it is probably a good idea to be clear with exactly what symptom you're experiencing.

**Comment by adir6** [comment]
> @adir6 you mean the tracker is not retried at all? are you sure the tracker _is_ allowing that torrent?
> I think this ticket is old and diluted enough that it is probably a good idea to be clear with exactly what symptom you're experiencing.

Yes. Of course, 100 People were downloading it. But mine isn't working.

Issue is that, I use autodl-irssi in ruTorrent to download the torrent from RSS. And then I use watch folder of deluge to pick up inside deluge.

When the torrent is added into the deluge, it has this error of unregistered torrent. I have to manually force-check / update tracker to make it run.. else it will stay like this forever.

Please suggest some solution.

**Comment by arvidn** [comment]
@adir6 which version of libtorrent are you using?

the "Next Announce" counter, in your screenshot, appears to be counting down, at 26m 59s. Is that counter moving?
When it gets to zero, what happens? Does it continue counting down with negative numbers?

**Comment by adir6** [comment]
> @adir6 which version of libtorrent are you using?
> 
> the "Next Announce" counter, in your screenshot, appears to be counting down, at 26m 59s. Is that counter moving?
> When it gets to zero, what happens? Does it continue counting down with negative numbers?

1. I am using Deluge 2.0.3 I don't know how to check the libtorrent's version. Could you please tell me?
2. When counter gets to zero, it re-announced and torrent starts downloading. So basically, it sits idle for half hour doing nothing. People at UltraSeedBox's Community Server and some other places on Reddit has given me script to use, but none of them are working. Hmm, If it's possible? Can you help me directly to find the issue? So that we could have fast communication? (Discord Text Chat or if you have a discord server)?

Thanks

**Comment by arvidn** [comment]
I see. So the previous statement should have been:

> else it will stay like this ~forever~ for 30 minutes.

The tracker is asking the client to try again in 30 minutes, so it does. If you want to override this behaviour you can force-reannounce the tracker. I imagine the scripts do that. So, you may have to debug those scripts, or ask whoever wrote them to.

**Comment by adir6** [comment]
> I see. So the previous statement should have been:
> 
> > else it will stay like this ~forever~ for 30 minutes.
> 
> The tracker is asking the client to try again in 30 minutes, so it does. If you want to override this behaviour you can force-reannounce the tracker. I imagine the scripts do that. So, you may have to debug those scripts, or ask whoever wrote them to.

Script does that for hundreds of others. But, I really don't know who made that script and how it came out.

But it's not working for me. That's why I need some help if you could check?

Thanks.

**Comment by arvidn** [comment]
the script talks to Deluge, right? So you should probably ask on a Deluge forum.
