### ISSUE TITLE
[Enhancement] Read pieces from other files and share the same torrent

### ISSUE THREAD

**Issue by latot** [arvidn/libtorrent#3181]
Hi!, basically a way to say to libtorrent where search some pieces in other files, or say an equivalence between files, the bytes 100 to 400 of this files are the same as this other where start in byte 300.

I think this would be great, some times we share files, where the content is very similar, a usual case, videos, big videos, easy 10gb, i remux it (add a sub, but the video and audio is the same), and now i have other 10gb with the sub inside, both files are 99% equals, but from where the data start and end change, i don't wan't keep 20gb only to seed, so, remove the original videos, and with this, say to libtorrent where is the equal data to seed all other 99%, an extra i can make a new torrent with the remux, and seed both torrents, with the same files (one in 99%, the new 100%).

Maybe other way or solution?

Thx.

**Comment by Dobatymo** [comment]
Basically you are asking to calculate binary diff/patch files for two or more similar files. Then being able to seed all of them using only one of the original files and the diff files, right?

One (old) binary diffing library for example is http://www.daemonology.net/bsdiff/

I think that would be a very useful feature (and unique among torrent clients I think). But it's not easy to implement. An alternative would be to use a deduping filesystem.

**Comment by Seeker2** [comment]
Piece sizes often vary from 1 torrent to the next. So even if they contain identical files, if they uses different piece sizes their piece hashes won't match.
If the files are part of a series then usually only the first file starts at the beginning of a piece.
The ends of a file often overlaps with the next file in a single piece, so the edge pieces may not have matching hash values even with identical files in another torrent that uses the same piece size.

Quite often, a small text file is added at the beginning that says "Downloaded from/by/at ___ originally!" ...causing the piece alignments of all the other files in the torrent to be offset.
This can even cause drastic I/O issues:
https://qbforums.shiki.hu/index.php/topic,2627.msg12725.html#msg12725

So to find every possible matching overlap, every file will need to be bit-wise compared with every other file starting at every possible offset.
That can take a very long time even with 100 files of ~100 MB each.

**Comment by latot** [comment]
Hi, the idea of the patch, or match the files is all hashes match, actually there is tools like xdelta where can do this works and very fast, so the alignment of the data or position don't will be a problem.

If we try seed the new files without the patch, only with concordance between files we will can't seed the 100% of the torrent, but we can share all other, with big videos remux easy can be 95%-99%, and i think is very fine.

Using an interpreter for VCDIFF (the xdelta format) we can get exactly the original files, so we would seed all the torrent.

I was thinking, we can make a very simple format for this patch, just search equals parts, and the difference save in a file with the order to construct the original files, don't will be so optimized like xdelta but can be easier to work with it.

Maybe i don't explain very well this, about share two torrents, i download a torrent, and i'm seeding it, but now i change some parts, and i want share it too, how the files are differents i can't share it, but, if we can pick the first torrent, and read the patch from the new files, we should be able to share to differents torrents with the same files, and here don't care the differents between the torrents, because in the end, we can construct in the right way the data of both to seed.

Cya.

**Comment by latot** [comment]
now, i'll try check the vcdiff format (xdelta) to see how read it.

**Comment by latot** [comment]
Hi, i found something useful, in the xdelta headers there is a function for this:

https://github.com/jmacd/xdelta/blob/7508fd2a823443b1f0173ca361620f21d62a7d37/xdelta3/xdelta3-decode.h#L42

**Comment by latot** [comment]
Hi, after think this, i think xdelta should not be the first option, this because the xldeta patches is hard to write, read can be easy, but if want usa the feature we will be unable to write the data, or we should decrypt, add data, write in vcdiff again.

I'm thinking would be very useful a new format for this, like a torrent file (i'll call this c2t), this file will have the data of where is the pieces of the torrent in the new data, and an extra file, where is the rest of the pieces, with that we can read and write pieces, and pass from one files to the new ones, an obtion to disable that file would be useful too, there we only share the actual pieces and avoid have data we don't want, i don't know if the extra file is good idea be inside the c2t file, (just keep all in 1 file), or two files.

Thx.

**Comment by latot** [comment]
Hi, i think a have a concrete idea now how to do this, actually torrents works via pieces, so, if we construct a new torrent file, where all the data of the pieces match with the other torrent this can works, how construct that or optimize it is other problem, but with that is possible use the torrent for this.

But still the problem is how we can declare fragments of file, and use a secondary filesystem can do this more complex (maybe for windows more), so for now i think with a little change in the torrent file this can be done easly, add for every file a "start" param, so, with that we can read fragments of files from start point until the size declared in the torrent.

Then we can add two files, an "InterestedData", and "DisinterestedData", in one will be the data of the pieces we want keep, in other data we want avoid, so adding the torrent and skip the "DisiterestedData" file will avoid all the data we don't want, even if we don't have the file.

Torrents and this file will be read in the same way, except for the "start" extra param.

I would like an opinion of @arvidn or some contributor.

Thx.

**Comment by Seeker2** [comment]
Vuze and probably BiglyBT already has something like this, so go look into how they do it:
https://wiki.vuze.com/w/Swarm_Merging

**Comment by latot** [comment]
Is a nice way, now, thinking libtorrent just as a lib, i think can be better split the concept, in one part, how can we express a new torrent structure, and, how we find the torrent structure, the advantage of this is we can have several, and customize ways to use this, maybe a mix would be find how pass a new "files" section of the torrent to use, and merge some "default" ways to find common data.

One method in vuze is find equal files to share, personally i think would be better some flexible way, like can read fragments of files continuosly (like a torrent), add an start segment to know where start reading the file until the size is for that, i think have a lot of applications, in any way.

Bye.

**Comment by arvidn** [comment]
reading the original description of this ticket, it sounds like you would like *fine grained* de-duplication of data, not just at piece level. The two video files in your example will probably not have a single piece identical to each other, for these reasons:

1. audio and video frames are interleaved, and if you change container or add a subtitle stream, that will also be interleaved. A single piece will contain data from all streams (most likely).

2. changing container will most likely shift offsets of where the duplicate data is located in the file, at a finer granularity that pieces. (a piece is normally a few megabytes; 2, 4 or 8 MiB are common).

libtorrent has a customization point at the storage interface which would make it possible to, given a fine-grained mapping of byte ranges of duplicate data, could pull together pieces from various places when seeding. However, the tool to create such mapping, and to put all the non-duplicated parts in some data structure and access it, would be a non-trivial task.

@Seeker2 I don't get the impression this ticket is about sharing equivalent files across multiple torrents. [bittorrent v2](http://www.bittorrent.org/beps/bep_0052.html) is probably the most practical approach towards that goal (with per-file merkle hash trees)

**Comment by latot** [comment]
Hi, @arvidn i'm actually working in the script, is almost finished the first version, it uses xdelta3, and read the delta file to construct the data for the torrent, but i would like to know what format use for the output.

Actually we would have a torrent file, and the new files, options are a new torrent file with the new structure? (every file will need include a new param to know where start reading the file), an extra file with the special structure?, or put the data in a extra section in the torrent? (in that case i need a format)

The project is here in python:
https://github.com/latot/c2torrent

Bye

**Comment by arvidn** [comment]
If I understand correctly what you're aiming to do, I think your best bet is to implement a custom libtorrent storage class (implementing `storage_interface`) which supports arbitrary mapping of torrent extents to ranges in arbitrary files.

The data structure for those ranges would probably best be a tree structure (say, `std::map`) to efficiently find which extent a read is in.

**Comment by latot** [comment]
Hi @arvidn , sorry the time, i never recive the mail and now see your message, i'll check how do this, thanks for your help to know where start.

An option, like an abstract to cover this in a flexible way, is enable an option where we can pass a custom function to treat the file, but only like read and write.
With that anyone can choose how read/write the file keeping the functions of libtorrent.

Thx!

**Comment by arvidn** [comment]
what you describe sounds very similar to the `storage_interface`. It's a customisation point for disk I/O in libtorrent

**Comment by latot** [comment]
Okis!, so two parts, one, i'll search the docs to learn how use it (https://www.libtorrent.org/reference-Custom_Storage.html#storage_interface).

next, do storage_interface external? obvs keep the default but have an option to define from other program, the docs are great here.

Thx.

**Comment by latot** [comment]
nothing to say, there is already an option for that :D

**Comment by latot** [comment]
Hi!, little question, this is still valid?, i mean, it will execute?:
https://www.libtorrent.org/reference-Custom_Storage.html

Because it uses the function ```read``` while storage uses ```readv```, is only if the function or something change in versions, if not and is only rename the function no problem, or works with ```read```?

Thx!

**Comment by arvidn** [comment]
I just updated the documentation on the website today, with the latest version (1.2). Earlier the website documentation was for 1.1.11. You can still get the previous version's docs from the tarball, locally.

you can still achieve the same thing, but libtorrent-1.2 has a slightly different `storage_interface` than libtorrent-1.1.11

**Comment by latot** [comment]
mm, reading the docs, now from the code and the updated version from the web, seems the example in storage is not updated, some types and names don't match, can be updated plis?

**Comment by arvidn** [comment]
yes, I will update this

**Comment by arvidn** [comment]
how does this look? https://github.com/arvidn/libtorrent/pull/3648

**Comment by arvidn** [comment]
@latot could you confirm that the updated example works?

**Comment by latot** [comment]
Hi, let me check it today and i tell you.

**Comment by latot** [comment]
Hi, @arvidn a little question.

storage_interface have a nice way to do this, but checking all the components of libtorrent it feels like wasting the code, the reason is simple, the only thing this will change is the start point to read the files, all the other function to move, replace, etc will be the same.

Maybe instead of the actual way to do this (implement all in a new storage_interface), implement the start point to read the files inside libtorrent with default value 0, and then externally, from other function to update that data, so we would be able to dinamically change the structure of the torrent (or maybe this in some level is already applied and i don't found the code yet).

This in some way i think would be ideal, out of this there is something i don't know, when we get a magnet link, libtorrent request to some client the torrent data, but if with this sytem we reaplce the file structure maybe there is the posibility of libtorrent send the new data instead of the original torrent data.
Is this possible?, i don't know how libtorrent store the data to send with that request.

Thx.

**Comment by arvidn** [comment]
I don't think I fully understand what you propose. Are you suggesting making it possible to not just rename files, but also map the files in a torrent to a specific offset in a file on the filesystem?

This used to be possible in older versions of libtorrent, as a way to punt a primitive part-file feature to clients. with proper part file support though, what's the use case of this?

The cost is added complexity, maintenance burden and more bugs.

**Comment by latot** [comment]
Hi, the idea is the same as i describe in the main comment, there is a lot of files that have in a high percentage the same data, like videos, put softsubs to a video and the file will be different, but the files will be almost the same, so instead have all that data, can says to libtorrent read/write this file in this way (from this offset and this length) can save a lot of space.

**Comment by latot** [comment]
Hi, i check the posibilities of VFS, in linux easy, but in windows we would need more dependences and i don't like the idea...., maybe just implement an easy custom storage.

**Comment by latot** [comment]
Hi @arvidn , actually i read more code about how works the storage system, custom storage, and file storage, the actual storage system seems to support correctly the file-offset with changes in other place.

This is just an idea, the filestorage add a support for a image and preimage of the files, the preimage of the files is the structure of how we will show the files, while the image would be the real structure of the files, when some app request the list of files to show we can send the preimage, while internally, for storage for example we can use the image. If filestorage in the image support file-offset the default storage should be able to read-write correctly.

I would like to know your opinion.

Thx.

**Comment by arvidn** [comment]
The built-in storage supports remapping the torrent content into any set of files with any size, as long as the sum of all file sizes, and as long as all filenames are unique.

If you want to be able to map individual video packets or GOP, you will need something more sophisticated. Not just to perform the mapping while reading and writing, but to produce the mapping is also non-trivial.
