### ISSUE TITLE
Ship wheels for Python

### ISSUE THREAD

**Issue by techtonik** [arvidn/libtorrent#319]
The PyPI page https://pypi.python.org/pypi/python-libtorrent/ doesn't have any binaries and therefore libtorrent is not installable for Python with `pip`, and it would be nice if it was.

**Comment by arvidn** [comment]
There are binaries here: https://github.com/arvidn/libtorrent/releases/tag/libtorrent-1_0_7
please feel free to add them to pypi.

**Comment by arvidn** [comment]
oh, those are just binaries for windows btw. what binaries do they expect otherwise?

**Comment by techtonik** [comment]
@arvidn these binaries don't work, see https://github.com/arvidn/libtorrent/issues/320

**Comment by stephanepechard** [comment]
Hi,
I would be interested in libtorrent wheels for Linux. Do you think it is possible to get them done?
Thanks

**Comment by ztane** [comment]
There are *no* release files for 1.1.0 on pypi at all

**Comment by arvidn** [comment]
@ztane that's right. please feel free to add it!

**Comment by diman82** [comment]
@arvidn Is it possible to add files to: https://pypi.org/project/python-libtorrent/1.1.0/ when you're NOT the creator/maintainer of the page?

**Comment by arvidn** [comment]
I have no idea. presumably only the maintainer can add update that package

**Comment by arvidn** [comment]
no, it says "robalar"

**Comment by techtonik** [comment]
FWIW  here is how to build wheels on AppVeyor - https://github.com/ogrisel/python-appveyor-demo
