### ISSUE TITLE
Python bindings are broken on Windows

### ISSUE THREAD

**Issue by techtonik** [arvidn/libtorrent#320]
[python-libtorrent-1.0.7.win32.msi](https://github.com/arvidn/libtorrent/releases) is broken.
```
>python -c "import libtorrent"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.
```

Dependency walker shows that boost and libtorrent are not linked statically.

![image](https://cloud.githubusercontent.com/assets/515889/11753858/bae51736-a058-11e5-83e6-89f057e72d61.png)

**Comment by arvidn** [comment]
Here's an attempt to fix this. https://github.com/arvidn/libtorrent/pull/350
Once the appveyor build is done (assuming it succeeds) there should be a new .msi to test

**Comment by techtonik** [comment]
Looks like an attempt is failed. @arvidn did you consider an alternative approach to build bindings? I mean something like https://www.euroscipy.org/2015/schedule/presentation/58/

**Comment by arvidn** [comment]
autoWIG sounds like a fork of SWIG. I'm fairly certain boost.python is more powerful than that. it's certainly more convenient and easier to use. Do you think there are any problems with boost.python?

**Comment by techtonik** [comment]
I think size of binaries. https://shiboken.readthedocs.org/en/latest/faq.html#why-did-you-switch-from-boost-python-to-shiboken

**Comment by arvidn** [comment]
could you try this?
https://ci.appveyor.com/project/arvidn/libtorrent/build/1.0.1341/job/dkrin3f6b093vq70/artifacts

**Comment by techtonik** [comment]
Trying...

**Comment by techtonik** [comment]
```
>>> import libtorrent
>>>
```
Import looks fine.

**Comment by overfl0** [comment]
I had the same problem and file linked in this issue fixed it for me as well.
However, the releases page still contains links to the old broken version. Replace it please.

https://github.com/arvidn/libtorrent/releases

**Comment by arvidn** [comment]
I will replace them when I release 1.0.8
