### ISSUE TITLE
EXDEV errors not handled when renaming files

### ISSUE THREAD

**Issue by oxguy3** [arvidn/libtorrent#3219]
libtorrent version (or branch): Deluge says 1.1.1.0, but `dpkg -s libtorrent-rasterbar9` says 1.1.1-1+b1

platform/architecture: Debian 9 (Linux 4.9.0-6-amd64)

compiler and compiler version: pretty sure gcc but not sure (I'm just using [the version from Debian 9's stable repository](https://packages.debian.org/stretch/libtorrent-rasterbar9))

libtorrent does not seem to handle EXDEV errors (boost::system::errc::cross_device_link) correctly. I'm using a mergerfs filesystem, which can sometimes return EXDEV errors for rename/link commands even if the new and old path are on the same filesystem (see https://github.com/trapexit/mergerfs#rename--link). If an EXDEV error occurs, the file should be moved  (i.e. copied to the new path and then removed at the old path) instead of just renamed.

Unfortunately, I've not been able to verify that my issues are caused by EXDEV errors, because I'm not seeing any errors in any logs even with Deluge configured to highest verbosity. I'll try to rename certain torrents in Deluge, and it'll simply fail silently -- the new name will never appear. However, a workaround I've found is to move the torrent's storage, then rename it. This makes sense if EXDEV errors are the cause -- moving the storage will cause mergerfs to put all the files in one drive, thus resolving the cross device issues and allowing the rename to work.

**Comment by arvidn** [comment]
@oxguy3 could you test this patch? https://github.com/arvidn/libtorrent/pull/3256

**Comment by arvidn** [comment]
@oxguy3 any chance you could test that patch before I land it?
