### ISSUE TITLE
when the torrent_status finished will be fire？

### ISSUE THREAD

**Issue by kingctan** [arvidn/libtorrent#3227]
I use libtorrent and python to download bt file, and check the finished status, but it is never fired after the torrent file is seeding. so when and how to process this.

Thanks a lot.

**Comment by arvidn** [comment]
are you referring to the `torrent_finished_alert`? if you don't receive it, make sure you `alert_mask` is set to include it. also make sure you regularly pop the alerts to not have the alert queue fill up, in which case alerts may be dropped.
