### ISSUE TITLE
default torrent flags not available in python binding (add_torrent_params)

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#3235]
I was writing tests for pausing torrents and found an anomaly where the torrent paused status immediately after adding is set to True when expecting False:

```python
import libtorrent as lt
import os
import time
sess = lt.session()
ti = lt.torrent_info('ubuntu-9.04-desktop-i386.iso.torrent')
handle = sess.add_torrent({'ti': ti, 'save_path': os.getcwd()})
for i in range(4):
    if i == 3:
        print('-delay-')
        time.sleep(0.5)
    status = handle.status()
    print('State: {}, Paused: {}'.format(status.state, status.paused))
```
The output is:
```
State: checking_resume_data Paused: True
State: downloading Paused: True
State: downloading Paused: True
-delay-
State: downloading Paused: False
```

Is this expected behaviour? I was expecting paused status to be False after adding a torrent unless I am forgetting something.

libtorrent version (or branch): rc_1_1

**Comment by aldenml** [comment]
maybe the automanaged?

**Comment by cas--** [comment]
Thanks @aldenml totally forgot that the add torrent flags default to paused and automanaged... So it's both together that result in OP! All good with this change:

```
handle = sess.add_torrent({
    'ti': ti,
    'save_path': os.getcwd(),
    'flags': LT_DEFAULT_ADD_TORRENT_FLAGS
        ^ lt.add_torrent_params_flags_t.flag_auto_managed
        ^ lt.add_torrent_params_flags_t.flag_paused,
})
```

```
State: checking_resume_data, Paused: False
State: checking_resume_data, Paused: False
State: checking_resume_data, Paused: False
-delay-
State: downloading, Paused: False
```

**Comment by cas--** [comment]
@arvid I am not sure that the [default flags](https://github.com/arvidn/libtorrent/blob/RC_1_1/include/libtorrent/add_torrent_params.hpp#L279) are documented? Also can the default flags be available to the python bindings don't have access to add_torrent_params constructor so I have to manually create a default flag constant in python code, which is not ideal.

**Comment by arvidn** [comment]
the default flags aren't really supposed to be exposed other than what the constructor initialise the flags field to. You should be able to access it via something like: `add_torrent_params().flags` (i.e. create a temporary object and pull out the flags).

That said, perhaps it would make sense to have a constant for them, at least in the python bindings to be able to construct the `add_torrent_params` inline.

keep in mind though that when saving resume data, and in the `add_torrent_alert`, you will get the proper c++ type `add_torrent_params`, not a dictionary.

**Comment by cas--** [comment]
There is no `add_torrent_params()` constructor in python bindings in RC_1_1:

```python
lt.add_torrent_params()

Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    lt.add_torrent_params()
AttributeError: 'module' object has no attribute 'add_torrent_params'
```

**Comment by arvidn** [comment]
ah, I'm thinking of master. that's a good point. the default flags should be available somehow.

**Comment by arvidn** [comment]
@cas-- would you mind proposing a patch for this?

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/3300
