### ISSUE TITLE
Is downloading only the last piece, or better, a part of the last piece possible?

### ISSUE THREAD

**Issue by SandroJijavadze** [arvidn/libtorrent#3242]
Hello,
I am looking through documentation, searching through google, but have difficulty finding the exact feature.
I want to be able to download around 100 bytes from the end of the file, or if not possible the last piece only.
Is it possible? Which part should I look at in the documentation?

Thank you

**Comment by latot** [comment]
Hi, looks here: https://libtorrent.org/manual.html

piece_priority() is the function for that, disable all the pieces except what you want.

Bye.

**Comment by SandroJijavadze** [comment]
Thank you, I should have looked better before opening the issue.
