### ISSUE TITLE
Freeze when deleting or pausing a torrent using the cache

### ISSUE THREAD

**Issue by Rootax** [arvidn/libtorrent#3246]
**Please provide the following information**

**libtorrent version (or branch):**

1.1.X

**platform/architecture:**

Windows 10 x64 (1803)

**compiler and compiler version:**

The version used bit Qbittorent ?

Hello. I already opened a issue on the qbittorent git, but it seems that no one cares, or I believe the cause is libtorrent since all is fine with 1.0 branch.

So... 

qBittorrent version and Operating System:
Any version with libtorrent 1.1.x / Windows 10 x64

What is the problem:
When I delete or pause a torrent which use the cache, the application is not responding, and is using a whole cpu thread. The more cache is used, the more time Qbittorent is doing this. In the end, it doesn't crash and the app is responsive again, but during this time, the download and upload stops. It's only doing that with libtorrent 1.1 builds. Whith 1.0 it's ok (but I got much worse upload speeds...)

What is the expected behavior:
Not freezing like that...

Steps to reproduce:
Enable cache (size doesn't matter), download a torrent, then when it's over, deleting it (with or without deleting the file too, doesn't make a difference). Qbittorent will "freeze", using a lot of cpu, and take a long time deleting the files/torrent.

Extra info(if any):
Sorry for my english.

It seems that, when I shutdown qbittorent, It sometimes doing the same thing. Like, I exit it, but in the task manager, I see the process still running, using a lot of cpu, and slowly using less and less memory, until it really shutdown.

And no errors are shown in the log file.

My hardware 
CPU : Intel I3 4010u, 16gb of ram, a Crucial SSD (Sata)
-No error on disk
-Pagefile is enabled; 32gb
-During those cpu spike, the drive does nothing. The only thing working is the cpu (1 thread), and the memory used by qbitorrent cache slowly goes down. When all the useless data in cache is "purged", then qbittorent respond again. And it's not data waiting to be writing on disk, since my cache is mostly a read cache (I seed a lot).

All is ok with libtorrent 1.0, so I guess it's a libtorrent 1.1x bug. I tried various cache settings, but the result is always the same.

For clarity, I showed the problem in this youtube video : https://youtu.be/xeucCbjILP8 By the end of it, you see qbittorrent not responding. The video cut before it's responsive again, but it's ok when the cache is "flushed". Before that, a thread fully used, and qbittorrent not responding or very laggy.

Hope it's clarify things. BTW, If I put a smaller cache, the problem still exist. Of course, the flush is faster, but...

EDIT : I recorded the video after uninstalling Qbittorrent, settings included, and installing it and configuring it from scratch, just in case my settings were corrupted or something. But same result.

Original thread here : https://github.com/qbittorrent/qBittorrent/issues/7714

Thx for what you can do about that.

**Comment by arvidn** [comment]
I believe the issue is that the cache is not very efficient at finding all pieces belonging to a specific torrent and then free them all (i.e. return them to the block allocator). If the cache is large, it need to go through a lot of blocks and return them to the block allocator, and this takes some time.

However, it's not *just* libtorrent's fault. This work is done in the disk thread, and libtorrent's network thread should still be able to run. And even if it isn't, Qbittorrent should (ideally) not make blocking calls into libtorrent, where its own thread is blocked by libtorrent. There are asynchronous versions of almost all calls where Qbt will get the result in an alert. That way the qbt thread would never get blocked and the GUI would still be responsive.

**Comment by Rootax** [comment]
Thx for the answer.

For the record, it's not only a GUI problem, as the network traffic goes down too (and it's not "slower", it just stop all together) when this is happening.

**Comment by arvidn** [comment]
@Rootax what is the newest version of libtorrent you're using exactly?
I haven't been able to reproduce this in the latest version, 1.1.9 on Mac. I'm just using a 1.5 GiB cache though. You're saying you have this problem even for smaller cache sizes?

would you be able to grab the callstacks (of all threads) when the client is in this mode? you would need a release build with debug information for this. you can get call stacks in visual studio or (I think) from task manager

**Comment by Rootax** [comment]
I'm using Qbittorrent 4.1.2, which is using libtorrent 1.1.9.0 , on Windows.

You're saying you have this problem even for smaller cache sizes? => Yes. Of course, less cache = less impact since the "freeze" is shorter.

But I don't know how to obtain a debug release...

**Comment by arvidn** [comment]
@sledgehammer999 do you think any of the qbt devs could help out with testing on windows?

Purely based on code-inspection, here's a theory of what may be causing the expensive flushing of the cache, please try: https://github.com/arvidn/libtorrent/pull/3255

**Comment by Rootax** [comment]
Thx Arvidn for trying to get things moving, as it seems I'm about the only one noticing this...

(and BTW, why is the cache limited to 4gb on x64 computers ? Thx)

**Comment by arvidn** [comment]
I don't think it's limited to 4GiB

**Comment by Rootax** [comment]
Oh ok. It's maybe a qb limitation then, I can't go higher in the gui.

**Comment by ssiloti** [comment]
I am able to repro this on Windows by setting `cache_size` to 1GB. I profiled it and found that nearly all of the time is spent in `RtlFreeHeap`.

I think this is a consequence of disabling the pool allocator by default on 1.1. Without it a multi-gigabyte cache is made up of many 16KB allocations. Apparently Windows is a bit slow at freeing heap allocations.

The simple solution is to not set the cache so large. There's no benefit to having so much data in the cache, libtorrent is just eating up memory the OS could be using for its cache.

**Comment by arvidn** [comment]
the main benefit I can think of is if your network is a lot faster than your drive, you may want to be able to download and seed independent of flushing to disk. I don't have (recent) experience with this though.

**Comment by Rootax** [comment]
Well, I've a SSD, but even with that I found that  writing in and reading from the cache is faster than the disk in some situations, even with coalesce enabled. I've a 1gb fiber link at home, and the application cache make a différence vs Windows own caching on fast torrents.

**Comment by arvidn** [comment]
@Rootax so try setting `settings_pack::use_disk_cache_pool` to true

**Comment by Rootax** [comment]
This setting isn't exposed un qbittorent afaik : /

**Comment by Rootax** [comment]
Ok I'm back, I compiled a new qbt version with this setting to true.

So, yes, problem kind of solved with that.

My test for this, I put the cache at 4096, dl a *nux iso, so cache is full, delete torrent+cache when it's done, boom, cache is freed in less than a second, and the app never "stop". Now, strange this, total buffer size go down in the statistic tab, but the memory use by qbt in windows doesn't....

When I dl another nux iso, the qbt cache goes up again, but not the qbt memory in windows.

So I assume the memory is keep allocated and available to qbt ? Is there a way to tell the OS "hey, you can free the unused ram now" ?

Sorry again for my english :/

**Comment by arvidn** [comment]
yeah, basically the pool allocator allocates a bunch of memory and then manages it internally, and it's quicker than the OS heap. but you then are stuck with a bunch of RAM locked up in the pool

**Comment by Rootax** [comment]
Ok thx for the explanation.

Well, in my case it's the better solution, until freeing heap allocations can be made faster somehow. I guess this can be close now ?
