### ISSUE TITLE
Total_upload reset to zero after torrent completion

### ISSUE THREAD

**Issue by WhiteTrashLord** [arvidn/libtorrent#3248]
I have noticed that the total_upload amount of a torrent was reset to zero after the torrent file completed.

Does it really work like this or did I do something wrong?

**Comment by arvidn** [comment]
do you mean `torrent_status::total_upload`?
which version of libtorrent?

**Comment by arvidn** [comment]
`torrent_status::total_upload` is only reporting the upload in *the current session*. Meaning, if the torrent is paused and resumed, it's a new session and it is reset to 0.

If the torrent is auto managed, it's possible it is stopped soon after it's completed (if there are lots od seeds and there are other torrents that should be seeded instead).

If you see a `torrent_paused_alert` and a `torrent_resumed_alert` in between `total_upload` being reset, then; yes, that is intended. If not, then it smells like a bug.

**Comment by WhiteTrashLord** [comment]
Thank you for your reply. I really paused and resumed the torrent. For me there should be no longer any problems. But I am not sure if the current behaviour is the best for everyone. I think for several users it's important to know how much of a torrent they have uploaded during all sessions. Maybe you can add more fields which won't be reset because of a pause.

**Comment by arvidn** [comment]
there's also `all_time_upload` and `all_time_download`. see https://www.libtorrent.org/reference-Core.html#torrent_status

**Comment by WhiteTrashLord** [comment]
Thanks. How could I miss this :(
