### ISSUE TITLE
Documentation generation issues

### ISSUE THREAD

**Issue by FranciscoPombal** [arvidn/libtorrent#3254]
**Please provide the following information**

libtorrent version (or branch):
master

platform/architecture:
all

compiler and compiler version:
compiler - not applicable
system - ubuntu 18.04.1

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

The main issue is that running `make all` on the `docs folder` produces a lot of warnings/errors (mostly about malformed tables) that cause make to exit unsuccessfully. Is this just due to the rapid pace of development relative to documentation updates, or something of concern?
Most documentation files get generated regardless, I get a working `index.html` file among others.

The other minor issue is that currently, upon documentation generation, 3 files are generated that are not covered by `.gitignore`.
These files are:
-   docs/plain_text_out.txt
-   docs/settings.rst
-   docs/stats_counters.rst

Should I submit a PR to add them?

Also, somewhat related, when is the official website going to get updated with the most recent documentation?

Thank you.

**Comment by arvidn** [comment]
> The main issue is that running make all on the docs folder produces a lot of warnings/errors (mostly about malformed tables) that cause make to exit unsuccessfully. Is this just due to the rapid pace of development relative to documentation updates, or something of concern?

It doesn't for me, and not on travis either. documentation is generated in CI (travis) and each PR is ensured that it still works.

what errors specifically do you get?

If it's rst2html failues, are you perhaps using an old version?

> The other minor issue is that currently, upon documentation generation, 3 files are generated that are not covered by .gitignore.
> These files are:
> 
> docs/plain_text_out.txt
> docs/settings.rst
> docs/stats_counters.rst
> Should I submit a PR to add them?

sure!

**Comment by arvidn** [comment]
oh, I take that back. it's *supposed* to be tested by CI.

**Comment by FranciscoPombal** [comment]
@arvidn 
I installed `rst2pdf` (0.93-6) and `python-docutils` (0.14+dfsg-3) from the Ubuntu (18.04) repositories.

Here is the output I get when running `make clean && make all` on the `docs` directory:
https://gist.github.com/FranciscoPombal/648e32776f85273bde42269c8aaf3a06

**Comment by arvidn** [comment]
fix here: https://github.com/arvidn/libtorrent/pull/3258

**Comment by FranciscoPombal** [comment]
@arvidn The table errors seem to be gone, but `make all` still does not complete succesfully. This time the error seems to be related to the pdf generation.

Output:
https://gist.github.com/FranciscoPombal/4be0b2dd261b0041254b2c01b9eba91c
