### ISSUE TITLE
Build libtorrent with C bindings

### ISSUE THREAD

**Issue by vkpidwlk** [arvidn/libtorrent#326]
Hey all,

I'm trying to figure out how to build libtorrent with the C bindings so I can use libtorrent from a C application.

I've searched almost everywhere for how to do this, but I simply can't find anything.

Any suggestions are appreciated :)

**Comment by arvidn** [comment]
cd into the bindings/c directory and type: "b2"

this assumes you have boost and boost-build installed. The C-bindings have also been neglected for a few years and are due for a bit of a revamp. Some of the operations should really be asynchronous for instance.

**Comment by vkpidwlk** [comment]
Thank you!

I'm excited for the c bindings revamp :)
