### ISSUE TITLE
RPC binding

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#3263]
libtorrent: `master`

Hi @arvidn, I would like to know what do you think about creating an RPC binding based on HTTP. This should open the potential for more integration in other platforms. I perceive there are more developments in this area in other libraries/clients like rTorrent and Transmission.

Specifically, if you are open to it (and I'm not assuming you are), how would you instrument a long development of a new binding in terms of new PRs and reviews of mostly incomplete commits in the `bindings` folder?

**Comment by arvidn** [comment]
I'm a bit interested in picking up development on https://github.com/arvidn/libtorrent-webui, which includes a websocket-based RPC protocol (which I'm quite happy with).

It needs more work to be compatible with master though (there's a branch where I've done most of that, but not all yet).

the libtorrent-webui repo also implements transmission, Deluge and utorrent REST APIs, and perhaps that's a bit too broad of a scope. I think the "native" websocket API is more efficient than the other ones.

**Comment by arvidn** [comment]
here's the protocol specification btw: https://github.com/arvidn/libtorrent-webui/blob/master/docs/libtorrent-webui.rst

**Comment by aldenml** [comment]
Interesting, let me take a look at that.
