### ISSUE TITLE
Another branch of libtorrent

### ISSUE THREAD

**Issue by Vpstr** [arvidn/libtorrent#3265]
Hello!
I don't have an issue, but a question, the answer to which is hidden somewhy.
I read in the Deluge FAQ, that there is an experimental branch libtorrent_aio that is capable of writing pieces of odd files (not selected for download) into a single file, like uTorrent does. This feature is critical to me, I want to use it, but I don't know where to get and how to install that branch. I can't get an answer from Deluge developer and I don't see this branch here, so I redirect these questions to you.

**Comment by arvidn** [comment]
I don't think `libtorrent_aio` is around anymore, I think it landed 5 years ago or so. The latest stable (`RC_1_1`) supports the part-file feature.

**Comment by Vpstr** [comment]
How can the developer not know whether it is around? Was it developed by someone else?
And what library version incorporates this latest stable?

**Comment by arvidn** [comment]
> How can the developer not know whether it is around?

I don't memorise whether I deleted the feature branch after it landed. You could just look in the repo to see whether it's there. But I don't think it's relevant.

> Was it developed by someone else?

nope

> And what library version incorporates this latest stable?

libtorrent 1.1.x (1.1.9 is the latest)
