### ISSUE TITLE
[Feature Request] Swarm Merging

### ISSUE THREAD

**Issue by zero77** [arvidn/libtorrent#3272]
Can you please implement Swarm Merging like Vuze has.

Because, implementing this can help to find new pears and revive older torrents with few seeders.
Thanks

https://wiki.vuze.com/w/Swarm_Merging

**Comment by LordNyriox** [comment]
@arvidn:  ???

**Comment by arvidn** [comment]
I have a lot of stuff on my list ranking higher than this, but patches are welcome!

**Comment by LordNyriox** [comment]
@zero77, @arvidn:  This issue is a **duplicate** of [<https://github.com/arvidn/libtorrent/issues/829>].

**Comment by xavier2k6** [comment]
@arvidn Just wondering on if this option/fix is somewhere in the pipeline?
