### ISSUE TITLE
Sequential download only for selected file

### ISSUE THREAD

**Issue by proninyaroslav** [arvidn/libtorrent#3286]
Hi. I'm trying to implement HTTP streaming for a user-selected file from the torrent. In this case, other files usually have `NORMAL` priority, and for the selected file, after reading byte and for reading the next bytes portion (if pieces not downloaded) I set pieces priority as `SEVEN` and call `set_piece_deadline(1000)`, thereby creating the effect of a consistent and almost uninterrupted download on the HTTP-client side. But this approach does not work and the file download does not succeed sequentially, as if changing the priority to `SEVEN` is ignored. This prioritized pieces are not downloaded first. This only works if I set the priority of all files as `IGNORE`, except for the selected one. Is it possible to implement a sequential download for the selected file or are there pitfalls about which I know little? Is it possible to implement a sequential download for a particular file?

**Comment by ssiloti** [comment]
Are you doing any read-ahead? If you wait until the current high-priority piece finishes before setting the priority of the next one that will leave a window open for libtorrent to start downloading other pieces. A simple one piece read-ahead should be sufficient to ensure sequential download. When setting the deadline of the next desired piece, also set a slightly longer deadline on the next piece, that should ensure that there is always at least one high-priority piece for libtorrent to download.

**Comment by proninyaroslav** [comment]
I wait while the necessary part is loaded, but parts of other files are downloaded much faster, than parts with high priority. I'll try to play with the deadline.

**Comment by arvidn** [comment]
if you don't want to download any other files, you should set their priority to 0. I would recommend more than one piece read-ahead. The read-ahead should ideally be measured in bytes (instead of pieces). The higher the download rate is, the larger read-ahead you need, to compensate for the latencies of being notified and updating deadlines.

Any peer that doesn't have the time-critical pieces will still request other pieces, as long as they have priority > 0.

**Comment by proninyaroslav** [comment]
@arvidn the idea is that the rest of the files should also be downloaded, but only one will have high priority and which will be downloaded sequentially (as far as possible).

**Comment by proninyaroslav** [comment]
I solved this problem, it turned out that I used the wrong piece indexes for have_piece(). Now the problem is that after I check pieces for the availability with have_piece() function, I read available piece from disk, but many pieces contains only zero bytes (by piece index, piece size and file offset I calculate the offset on the disk and read bytes). Does this mean that they are downloaded but not yet flushed to disk? I tried to use flush_cache() and wait an alert, but this didn't work.

**Comment by arvidn** [comment]
yes, data is not flushed to disk immediately, and I don't think there's a reliable way to synchronise with the data hitting the disk. instead, you can use `read_piece()` to get the data back from libtorrent, or pass in a flag to `set_piece_deadline()` to also get the data posted to you when the piece has been received.
