### ISSUE TITLE
upload speed remains low at the beginning of a transmission

### ISSUE THREAD

**Issue by Joshua-Wang** [arvidn/libtorrent#3288]
**Please provide the following information**

libtorrent version (or branch):
1.1.4 release

platform/architecture:
 x86_64 GNU/Linux with 10000Mbps internal network

compiler and compiler version:
compile with boost, python bindings.

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
env setup : Periodicity distribute 24G data from one host to 50 hosts, all hosts have 512G memory and 10000Mbps network.
The symptom is at first, source upload speed will be high， around 300MBps-400MBps, but after 3-4 hours the speed drops down. During one transmission, source upload speed can remain 60-70MBps for a while , and then goes up to 300MBps. 
I was wondering why the upload speed can't reach 300MBps upon start up. The network bandwidth and memory is enough. And I have tried several params in "High Performance Seedings", however it won't work.
Now I am digging into the source code. Could anyone give some hints on why the upload speed remains low at the beginning of a transmission? (It will get faster after quite a while).
Any suggestions will be much appreciated.

**Comment by arvidn** [comment]
I would highly recommend that you enable (in the alert_mask) and log the `session_stats_alert` to a file. This log can then be analyzed by `tools/parse_session_stats.py` (requires `gnuplot`). It will help indicate what's going on and what the bottleneck is.

I'm a bit confused what you see as well. you say: 

> The symptom is at first, source upload speed will be high， around 300MBps-400MBps

Then you say:

> I was wondering why the upload speed can't reach 300MBps upon start up

The first statement suggests that you *do* get high speed on startup.

**Comment by Seeker2** [comment]
A slow upload speed on startup may mean there's problems connecting+handshaking with the peers.

Are the 50 hosts firewalled with respect to each other or the initial seeder?
At 100 MB/sec speeds a 24 GB torrent should complete in 240 seconds (4 minutes).
This requires the 50 hosts to share with each other, but even if they do that inefficiently I'd still expect the task to complete in <20 minutes.
