### ISSUE TITLE
part_file::m_dirty_metadata is never flushed

### ISSUE THREAD

**Issue by ajax16384** [arvidn/libtorrent#3289]
once m_dirty_metadata set true it is never reset, so part_file::flush_metadata_impl trying to write metadata every tick.
````c++
 	part_file::flush_metadata_impl(boost::system::error_code & ec)
 	part_file::flush_metadata(boost::system::error_code & ec)
 	default_storage::tick()
 	disk_io_thread::thread_fun(libtorrent::disk_io_thread::job_queue & queue, libtorrent::disk_io_thread_pool & pool)
 	disk_io_thread::job_queue::thread_fun(libtorrent::disk_io_thread_pool & pool, boost::asio::io_context::work work)
````
may be m_dirty_metadata = false; missed at the end of  flush_metadata_impl(error_code& ec) ?

**Comment by arvidn** [comment]
sounds like it

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/3291

**Comment by ajax16384** [comment]
looks good, will be ported to master?

**Comment by arvidn** [comment]
yes, I merge into master regularly (I haven't yet though)
