### ISSUE TITLE
Compile simple_client.cpp error

### ISSUE THREAD

**Issue by Ty-Chen** [arvidn/libtorrent#3297]
**Please provide the following information**

libtorrent version (or branch):1.19

platform/architecture:VS2017, win10

compiler and compiler version:msvc14.1, VS2017

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I got the libtorrent.lib by setting some preposser definition and include/library file address. And then I try to use the simple_client.cpp in example folder. I build a new project and set all like before, but there are lots of erros such as "namespace 'boost::datetime' has no class member 'gregorian_calendar_base'", 
"namespace 'boost::datetime' has no class member 'months_of_year'", and I have add libtorrent.lib and all the boost lib file in Properity/Linker/Input, but VS stiil tell me something like LNK2001	无法解析的外部符号 "class boost::asio::ip::address __cdecl boost::asio::ip::make_address(char const *,class boost::system::error_code &)" (?make_address@ip@asio@boost@@YA?AVaddress@123@PBDAAVerror_code@system@3@@Z). I don't know how to do with it, please help me, thank you.

**Comment by arvidn** [comment]
it's not clear to me how you can get both compiler errors and link errors. presumably you won't make it to linking. The error you post, is it the first one you get? If so, you may have an incompatible boost version, or perhaps you don't have boost at all.

`client_test.cpp` is built with msvc14 on appveyor [here](https://ci.appveyor.com/project/arvidn/libtorrent/build/9860/job/5x9w3wmvrvgybjvy#L97).

**Comment by Ty-Chen** [comment]
> it's not clear to me how you can get both compiler errors and link errors. presumably you won't make it to linking. The error you post, is it the first one you get? If so, you may have an incompatible boost version, or perhaps you don't have boost at all.
> 
> `client_test.cpp` is built with msvc14 on appveyor [here](https://ci.appveyor.com/project/arvidn/libtorrent/build/9860/job/5x9w3wmvrvgybjvy#L97).

Hi
   Thanks for your reply.
   The problem I met when compiling simple_client.cpp has been found. It is because my VS2017 can't get the specified path of boost asio. I search the web page of boost.asio "https://www.boost.org/doc/libs/1_68_0/doc/html/boost_asio/using.html", and get the solution by adding #include <boost/asio/impl/src.hpp> in simple_test.cpp. And it can also work when I using some other examples like make_torrent.cpp. But client_test.cpp has not passed, I'm stilling trying to find the reason. 
   What's more, when I using the example in https://www.libtorrent.org/tutorial.html (the last one), I find the program blocked in download metadat, and it always prints out "dl meta 0kb/s 0% downloaed". I haven't solved it till now.
   I want to know how the peer wire works and learn how you realize it, I thinks it is interesting and I want to realize it too.
