### ISSUE TITLE
Cannot add very large torrent

### ISSUE THREAD

**Issue by AyrA** [arvidn/libtorrent#33]
There was an error adding a large torrent (23 MB of metadata) into qBittorrent.
The developers claim, this is an issue of libTorrent and not qBittorrent, so I reference this here.

Issue with the torrent file and magnet link in question: https://github.com/qbittorrent/qBittorrent/issues/3360

**Comment by arvidn** [comment]
libtorrent only limits the size of metadata received over the metadata transfer extension (i.e. magnet links). Currently the limit is set to 500 kB. It should probably be configurable (but that is an ABI breaking change so I can only make that in master). There's also a limit set on how large files can be loaded when specifying a filename, but qBitTorrent could easily circumvent that by loading the file themselves, and then pass in the buffer to libtorrent.

**Comment by arvidn** [comment]
In fact, this is fixed in master and configurable by max_metadata_size.

**Comment by AyrA** [comment]
Thanks, will report back to qBittorrent then

**Comment by sledgehammer999** [comment]
@arvidn I think you might want to close this.

**Comment by waTeim** [comment]
Just to be clear.  Is this part of anything released (1.0.6 -- Branch RC_1.0?) or can this only be obtained from master?

**Comment by arvidn** [comment]
configurable limit is only in master. in 1.0.6 the hard coded limit is 4 MiB.
