### ISSUE TITLE
Amount of seeds/peers is zero or very low

### ISSUE THREAD

**Issue by Boulder08** [arvidn/libtorrent#3302]
I'm currently testing qBittorrent v4.1.2 to see if qBt could finally replace uTorrent v2.2.1. However, I still have this one issue of the amount of seeds and peers having an incorrect value. On one private tracker, qBt returns only zeroes even though the torrents are being seeded (and upload is occurring). Also the amount of seeds and peers is often very low compared to what I see with uTorrent (and which is more or less correct when checking through the tracker website).

I've also noticed that paused torrents don't get any results - I don't know how often there is scraping but uTorrent does that every now and then. This causes a problem because I have several torrents waiting for download and I'll download them when I have the HDD space and I do it by checking which torrent has the lowest amount of seeds to avoid a torrent die before I'm able to finish it.

I suspect that this is a libtorrent issue as qBt is supposedly just a fancy GUI. I've already opened a ticket about this in the qBt GitHub but it was closed a while ago with a comment that it was a visual bug (which I very well know it wasn't) that should be fixed by now.

If there's anything you need to check this, just let me know.

**Comment by arvidn** [comment]
is the problem that you actually connect to fewer peers than you would expect, or is it that some counter of seeds and peers are lower than you would expect? If it's the latter, please specify exactly which counters and where they came from (i.e. which libtorrent call returned them)

**Comment by Boulder08** [comment]
The trackers are http, and only one tracker per torrent.

I seem to get a normal amount of connections at least with a Knoppix image as a test torrent (it shows incorrect values as well though not zero) so the problem seems to be that the counters are wrong. Unfortunately I don't know which libtorrent call qBittorrent actually uses.

This is what qBt shows for a common test torrent, a Knoppix image:
![image](https://user-images.githubusercontent.com/11799308/45925541-2c6d0100-bf20-11e8-9703-1fcff96082f0.png)

This is what the tracker list shows:
![image](https://user-images.githubusercontent.com/11799308/45925545-3ee73a80-bf20-11e8-887f-b4b29b0cfc6a.png)

And this is what the truth is:
![image](https://user-images.githubusercontent.com/11799308/45925549-473f7580-bf20-11e8-9e7d-7432bfb9b842.png)


And this is a very positive case because it seems that the values are there but not populated correctly, or returned a bit incorrectly. The worst cases really either return zero or very low values compared to the truth.

**Comment by arvidn** [comment]
the scrape interface to trackers was not part of the original specification and is optional for trackers to implement. It's possible this tracker just doesn't report scrape data. Wiresharking the tracker connection should tell you exactly what it's returning (as a way to determine whether the problem is in the tracker or in libtorrent).

**Comment by Boulder08** [comment]
Thank you, I'll try wiresharking and see if I can find out anything interesting regarding the one tracker which reports zero. What I find strange is that an ancient uTorrent build works but newer builds don't. Of course, it the tracker side specification is not strict enough, it could be that things have just been accidentally broken by some change.

I got this information regarding the libtorrent calls qBittorrent uses:
Seeds = scrape_complete;
Peers = scrape_incomplete;
Downloaded = scrape_downloaded;

qBt doesn't differentiate between no scrape and 0 peers/seeds i.e. it shows 0 for both cases in the qBt version I'm currently using. qBt v4.1.3 fixes this but it's not yet whitelisted on some of the trackers that I use.

**Comment by Boulder08** [comment]
Looks like there is a difference between trackers in the way they provide data to the client. Some of them give it out using the call from announce.php, some (in fact quite many) via scrape.php. So is this something controlled by libtorrent?

**Comment by X-Coder264** [comment]
@Boulder08 The `scrape` endpoint returns just the number of active seeders and leechers and the number of peers that have ever completed downloading (as per http://www.bittorrent.org/beps/bep_0048.html). The `announce` endpoint  is the endpoint which returns the peers with their proper IP address and port so that the client can successfully connect to them. You should also keep in mind that a lot of trackers do not return the seeders from the `annnounce` endpoint if the client that did the announce is a seeder itself (because that data is then unnecessary to the client) which means that in the client you'll see 0 seeders even though the tracker website says there is a lot of seeders on the torrent.

**Comment by arvidn** [comment]
there's actually an extension to return scrape information directly in the announce response as well, but I don't think it's well documented

**Comment by Boulder08** [comment]
> Also, the client can specify the `numwant` parameter when announcing to the `announce` endpoint which indicates to the tracker how many peers the client wants to receive from it. If there is no `numwant` parameter then the trackers usually return 30 or 50 peers by default. So it's possible that some uTorrent versions (compared to qBt) send a bigger `numwant` value to the tracker.

The biggest difference still seems to be that uT 2.2.1 (and apparently uT v3.0 build 26473 is the last one that does) uses scrape in addition to announce to get the information, and it gets it right from all the trackers I've seen. As the method libtorrent uses doesn't, it will get nothing from those who send it out only in scrape. Most of the stuff in my queue have quite a low amount of peers, I'd say usually less than 10 anyway.

Is this something that I can request to change? I find it quite unlikely to see the trackers change the behaviour because not many people seem to need this thing.

I'm also wondering about that scraping of paused torrents. Is it disallowed in libtorrent?

**Comment by X-Coder264** [comment]
> The biggest difference still seems to be that uT 2.2.1 (and apparently uT v3.0 build 26473 is the last one that does) uses scrape in addition to announce to get the information, and it gets it right from all the trackers I've seen. As the method libtorrent uses doesn't, it will get nothing from those who send it out only in scrape.

I don't quite understand what are you saying. The `scrape` endpoint doesn't return the peers IP address and port, it just returns the number of peers on the torrent. That means that even though the `scrape` endpoint says "there is 500 peers on the torrent" and that number gets displayed in the client GUI, the client is gonna be able to connect to only those peers that it received from the `announce` endpoint.
