### ISSUE TITLE
ambiguous call to overloaded function in torrent.cpp

### ISSUE THREAD

**Issue by xanadu42** [arvidn/libtorrent#3303]
libtorrent version (or branch): libtorrent-rasterbar-1.1.9
boost: boost_1_65_1 (the last version that supports my compiler)
platform/architecture: windows xp 32 bit
compiler and compiler version: visual studio 2005 (I can't upgrade because my computer is 15 years old and it won't run windows 10, nor will the latest visual studio install in xp)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it:

1. Downloaded boost 1.65.1 and unpacked it.
2. Downloaded libtorrent-rasterbar-1.1.9 and unpacked it.
3. Created a static library project in visual studio and pointed it at 1 and 2.
4. It compiles fine without any error except the one described below.

Line 11441 in torrent.cpp:

`peers.insert(peers.begin(), ignore_peers.begin(), ignore_peers.end());`

produces the error:

```
C:\Program Files\Microsoft Visual Studio\VC\include\vector(946) : error C2668: 'boost::iterators::advance_adl_barrier::advance' : ambiguous call to overloaded function
  C:\boost/iterator/advance.hpp(68): could be 'void boost::iterators::advance_adl_barrier::advance<_Iter,__w64 int>(InputIterator &,Distance)' [found using argument-dependent lookup]
  with
  [
    _Iter=std::_Vector_iterator<libtorrent::peer_connection *,std::allocator<libtorrent::peer_connection *>>,
    InputIterator=std::_Vector_iterator<libtorrent::peer_connection *,std::allocator<libtorrent::peer_connection *>>,
    Distance=__w64 int
  ]
  C:\Program Files\Microsoft Visual Studio\VC\include\xutility(1581): or 'void std::advance<_Iter,__w64 int>(_InIt &,_Diff)'
  with
  [
    _Iter=std::_Vector_iterator<libtorrent::peer_connection *,std::allocator<libtorrent::peer_connection *>>,
    _InIt=std::_Vector_iterator<libtorrent::peer_connection *,std::allocator<libtorrent::peer_connection *>>,
    _Diff=__w64 int
  ]
  while trying to match the argument list '(std::_Vector_iterator<_Ty,_Alloc>, __w64 int)'
  with
  [
    _Ty=libtorrent::peer_connection *,
    _Alloc=std::allocator<libtorrent::peer_connection *>
  ]
  C:\Program Files\Microsoft Visual Studio\VC\include\vector(866) : see reference to function template instantiation 'void std::vector<_Ty>::_Insert<_Iter>(std::_Vector_iterator<_Ty,_Alloc>,_Iter,_Iter,std::forward_iterator_tag)' being compiled
  with
  [
    _Ty=libtorrent::peer_connection *,
    _Iter=std::_Vector_iterator<libtorrent::peer_connection *,std::allocator<libtorrent::peer_connection *>>,
    _Alloc=std::allocator<libtorrent::peer_connection *>
  ]
  .\torrent.cpp(11441) : see reference to function template instantiation 'void std::vector<_Ty>::insert<std::_Vector_iterator<_Ty,_Alloc>>(std::_Vector_iterator<_Ty,_Alloc>,_Iter,_Iter)' being compiled
  with
  [
    _Ty=libtorrent::peer_connection *,
    _Alloc=std::allocator<libtorrent::peer_connection *>,
    _Iter=std::_Vector_iterator<libtorrent::peer_connection *,std::allocator<libtorrent::peer_connection *>>
  ]

```
I'm no expert programmer, but as I see it all that is needed is a hint to the compiler about which of the two overloads it should use?

**Comment by arvidn** [comment]
it looks like the ADL implementation is wrong, and includes the boost overload even though it shouldn't. the code calling this function is the standard library, so it's not trivial to change it. I believe you can still produce XP compatible binaries with newer compilers, but libtorrent doesn't really support XP anymore.
