### ISSUE TITLE
recipe for target 'bt_peer_connection.lo' failed

### ISSUE THREAD

**Issue by wqh0109663** [arvidn/libtorrent#3304]
Makefile:942: recipe for target 'bt_peer_connection.lo' failed
make[1]: *** [bt_peer_connection.lo] Error 1
make[1]: Leaving directory '/home/wqh/.virtualenvs/torrentscrapy/libtorrent-rasterbar-1.1.9/src'
Makefile:621: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by arvidn** [comment]
so, what's the error message? and which compiler and platform are you on?

**Comment by wqh0109663** [comment]
Making all in include/libtorrent
make[1]: Entering directory '/home/wqh/谷歌浏览器下载/libtorrent-rasterbar-1.1.9/include/libtorrent'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/wqh/谷歌浏览器下载/libtorrent-rasterbar-1.1.9/include/libtorrent'
Making all in src
make[1]: Entering directory '/home/wqh/谷歌浏览器下载/libtorrent-rasterbar-1.1.9/src'
  CXX      bt_peer_connection.lo
In file included from ../include/libtorrent/socket_type.hpp:41:0,
                 from bt_peer_connection.cpp:65:
../include/libtorrent/utp_stream.hpp: In member function ‘void libtorrent::utp_stream::async_read_some(const Mutable_Buffers&, const Handler&)’:
../include/libtorrent/utp_stream.hpp:345:13: error: ‘i’ does not name a type
   for (auto i = buffer_sequence_begin(buffers)
             ^
../include/libtorrent/utp_stream.hpp:346:41: error: expected ‘;’ before ‘i’
    , end(buffer_sequence_end(buffers)); i != end; ++i)
                                         ^
../include/libtorrent/utp_stream.hpp:346:41: error: ‘i’ was not declared in this scope
../include/libtorrent/utp_stream.hpp:346:46: error: ‘end’ was not declared in this scope
    , end(buffer_sequence_end(buffers)); i != end; ++i)
                                              ^
../include/libtorrent/utp_stream.hpp:352:22: error: there are no arguments to ‘buffer_size’ that depend on a template parameter, so a declaration of ‘
buffer_size’ must be available [-fpermissive]
    if (buffer_size(*i) == 0) continue;
                      ^
../include/libtorrent/utp_stream.hpp:352:22: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name i
s deprecated)
../include/libtorrent/utp_stream.hpp: In member function ‘std::size_t libtorrent::utp_stream::read_some(const Mutable_Buffers&, libtorrent::error_code
&)’:
../include/libtorrent/utp_stream.hpp:421:13: error: ‘i’ does not name a type
   for (auto i = buffer_sequence_begin(buffers)
             ^
../include/libtorrent/utp_stream.hpp:422:41: error: expected ‘;’ before ‘i’
    , end(buffer_sequence_end(buffers)); i != end; ++i)
                                         ^
../include/libtorrent/utp_stream.hpp:422:41: error: ‘i’ was not declared in this scope
../include/libtorrent/utp_stream.hpp:422:46: error: ‘end’ was not declared in this scope
    , end(buffer_sequence_end(buffers)); i != end; ++i)
                                              ^
../include/libtorrent/utp_stream.hpp: In member function ‘void libtorrent::utp_stream::async_write_some(const Const_Buffers&, const Handler&)’:
../include/libtorrent/utp_stream.hpp:491:13: error: ‘i’ does not name a type
../include/libtorrent/utp_stream.hpp:492:41: error: expected ‘;’ before ‘i’
    , end(buffer_sequence_end(buffers)); i != end; ++i)
                                         ^
../include/libtorrent/utp_stream.hpp:492:41: error: ‘i’ was not declared in this scope
../include/libtorrent/utp_stream.hpp:492:46: error: ‘end’ was not declared in this scope
    , end(buffer_sequence_end(buffers)); i != end; ++i)
                                              ^
../include/libtorrent/utp_stream.hpp:498:22: error: there are no arguments to ‘buffer_size’ that depend on a template parameter, so a declaration of ‘
buffer_size’ must be available [-fpermissive]
    if (buffer_size(*i) == 0) continue;
                      ^
Makefile:942: recipe for target 'bt_peer_connection.lo' failed
make[1]: *** [bt_peer_connection.lo] Error 1
make[1]: Leaving directory '/home/wqh/谷歌浏览器下载/libtorrent-rasterbar-1.1.9/src'
Makefile:621: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by wqh0109663** [comment]
ubantu16.04

**Comment by arvidn** [comment]
boost-1.68 and later requires C++11. you can either downgrade boost or upgrade your compiler
