### ISSUE TITLE
Simultaneously announcing IPv4 and IPv6 addresses 1.1.9

### ISSUE THREAD

**Issue by lovesyk** [arvidn/libtorrent#3306]
libtorrent version (or branch): 1.1.9

platform/architecture: amd64

compiler and compiler version: Debian package

A while ago I had opened the issue #2255 which was solved by libtorrent in combination with Deluge doing 2 announcements for each IP address family. Right after the final relevant commit (some time before 1.1.6) I compiled a temporary version for myself and kept using it until now. Today, I updated my setup which now includes Deluge 1.3.15 and libtorrent 1.1.9 and saw the following changes which are probably related to libtorrent:
- The IPv6 announcement now says "port=0". This was a bug when the issue mentioned above was still in the middle of being solved but it had been fixed before 1.1.6. It seems to be back.
- Both announcements now include an "ipv6" parameter which contains my internal IPv6 address (ipv6=fd1e...). Is there any reason for this parameter? At the very least it should not be announcing internal IP addresses.

For now, I'll be reverting to my pre-1.1.6 build but can of course do more testing if required.

**Comment by arvidn** [comment]
iirc, there are some private trackers that rely on the `&ipv6` parameter. I believe it should only be included for private trackers for this reason.
regarding the port being 0; do you have a successful listen socket on an IPv6 interface?

**Comment by X-Coder264** [comment]
BEP 7 (http://www.bittorrent.org/beps/bep_0007.html) clearly specifies how and when the `ipv6` parameter should be sent and yes, there are trackers out there that are BEP 7 compliant. NexusPHP isn't one of those since it's like 10+ years old.

**Comment by lovesyk** [comment]
I see. The term "hacks" was not appropriate then.
I'm unsure whether NexusPHP supports the `ipv4` parameter from that spec but if it does and libtorrent supported BEP 7 fully, I imagine NexusPHP would be supported as well.

**Comment by X-Coder264** [comment]
@lovesyk NexusPHP does not support the `ipv4` nor the `ipv6` parameter. It gets the IP address from the PHP superglobal `$_SERVER['REMOTE_ADDR'].` That is the IP address from which the request was sent to the web server.

**Comment by lovesyk** [comment]
You are right. I somehow remember it working before but after testing it definitely doesn't.
Never mind everything I said about NexusPHP then, there's no way past `announce_ip` for it it seems.

And here's the log I probably should've posted right at the beginning: https://pastebin.com/aw31jfg1

**Comment by arvidn** [comment]
that port seems to be set by the response from the port mapping. Could you enable port map notifications too, and post a new log? i.e. the `port_mapping_notification` flag in the `alert_mask`

**Comment by arvidn** [comment]
perhaps Deluge doesn't log those alerts.

**Comment by TigerP** [comment]
I think the port 0 comes from [session_impl.cpp#L1322](https://github.com/arvidn/libtorrent/blob/libtorrent-1_1_9/src/session_impl.cpp#L1322) where the ssl_listen_port() overwrites the valid port in the second announce.

**Comment by TigerP** [comment]
I noticed that during the first announce the `req.ssl_ctx` is not set. But then it is set because of the `req.ssl_ctx = &m_ssl_ctx` line below L1322. (Which I think will still be done in your PR [#3385](https://github.com/arvidn/libtorrent/pull/3385) )

I'll see what happens when I apply your PR and will let you know the result.

**Comment by arvidn** [comment]
that's an excellent point. I hadn't thought of that.

**Comment by arvidn** [comment]
@TigerP Thanks for testing and investigating this! I've updated the patch, and I feel pretty confident this will fix the issue: https://github.com/arvidn/libtorrent/pull/3385

**Comment by TigerP** [comment]
I think you have solved the port=0 issue with [#3385](https://github.com/arvidn/libtorrent/pull/3385).
The logging I see when use deluge to test it is:
alertmanager:135 log_alert: ==> TRACKER REQUEST "http://bttracker.debian.org:6969/announce" event: started abort: 0 ssl: 0x564cb29ced78 port: 28741 force-proxy: 0 bind_ip: 
alertmanager:135 log_alert: ==> TRACKER REQUEST "http://bttracker.debian.org:6969/announce" event: started abort: 0 ssl: 0x564cb29ced78 port: 28741 force-proxy: 0 bind_ip: <my IPv6 address>
alertmanager:135 log_alert: ==> TRACKER REQUEST "http://bttracker.debian.org:6969/announce" event: - abort: 0 ssl: 0x564cb29ced78 port: 28741 force-proxy: 0 bind_ip: 
alertmanager:135 log_alert: ==> TRACKER REQUEST "http://bttracker.debian.org:6969/announce" event: - abort: 0 ssl: 0x564cb29ced78 port: 28741 force-proxy: 0 bind_ip: 
alertmanager:135 log_alert: ==> TRACKER REQUEST "http://bttracker.debian.org:6969/announce" event: stopped abort: 0 ssl: 0x564cb29ced78 port: 28741 force-proxy: 0 bind_ip: 
alertmanager:135 log_alert: ==> TRACKER REQUEST "http://bttracker.debian.org:6969/announce" event: stopped abort: 0 ssl: 0x564cb29ced78 port: 28741 force-proxy: 0 bind_ip: 0.0.0.0

Thank you very much for the fix.

**Comment by lovesyk** [comment]
I can confirm that the PR solves the port=0 issue. Thank you very much and sorry I couldn't be of much help with the logs.

As for the `ipv6` parameter, would it be possible to only send it in case a public IP can be found? Most notably, excluding the fd00::/8 ULA range..

**Comment by TigerP** [comment]
> As for the `ipv6` parameter, would it be possible to only send it in case a public IP can be found? Most notably, excluding the fd00::/8 ULA range..

How would that work when there is a tracker in the local network?
I do not know if they really exists, but it could be a possibilty.

**Comment by lovesyk** [comment]
That would indeed break that case. I do however believe only having an ULA address is more likely than having an ULA address (which is already uncommon) as well as having a local private tracker.
Making this configurable somehow (manually set address to announce or maybe just a switch to enable/disable BEP7) would probably be best but no idea if there's any interest on spending time on this.

I don't know which trackers honor the `ipv6` parameter and how they (or clients) react on private addresses since my main tracker (NexusPHP) doesn't support it at all but it probably shouldn't be kept the way it is.
