### ISSUE TITLE
Can't add download by magnet with several hashes

### ISSUE THREAD

**Issue by ivan386** [arvidn/libtorrent#3319]
libtorrent version (or branch): 1.1.9.0

platform/architecture: Windows XP 64 SP2

compiler and compiler version: don't now

Magnet example:
```
magnet:?xt=urn:ed2k:a0a927b6f044eb27945295d1fc8366c9&xt=urn:btih:953edbe75de612bc966194d2ee60099b3bc1a1aa
```

**Comment by arvidn** [comment]
@ivan386 could you test this patch? https://github.com/arvidn/libtorrent/pull/3322
