### ISSUE TITLE
Examples can't be built under Windows in cmake

### ISSUE THREAD

**Issue by parthibd** [arvidn/libtorrent#332]
I'm trying to build the libtorrent examples with cmake under Windows. I'm using visual studio 2015. I'm getting 3 errors:
1.libtorrentrasterbar_library is not found. 
2.cant include openssl/sha.h
3.cant open file libboost_date_time 

Anyone got a fix for these? I have to run the example programs under msvc debugger for my research project. By the way i successful built the library of the current master branch just now.

**Comment by arvidn** [comment]
I don't have easy access to a windows machine to take a look at this. if somebody figures it out, patches against the cmake files are welcome!

However, you could build with boost-build and still debug in visual studio. Just open the resulting executable as a project. It may help to link statically too.

**Comment by parthibd** [comment]
I never tried to open an executable the way you suggested but I'll  give it a try for sure. I actually need to step through the code at some places to get a more clear picture of what's happening.

**Comment by arvidn** [comment]
the debug information includes the paths to the source files, so that shouldn't be a problem. If you want to set breakpoints though, you'll have to open the files in the debugger to set them (unless you set breakpoints on function names).

you can also launch devenv.exe with the /debugexe switch and specify the binary from the command line.

**Comment by parthibd** [comment]
Thanks ! The workaround you suggested worked . But the cmake file need real fixing for a proper and straightforward solution to this problem.

**Comment by Falcosc** [comment]
@parthibd could you test the head of master? I guess some or even all problem should be fixed now. I did at least remember a sha fix which still did not get a back port to RC_1_1
https://github.com/arvidn/libtorrent/pull/1028
