### ISSUE TITLE
Can't seed merkle torrent

### ISSUE THREAD

**Issue by ivan386** [arvidn/libtorrent#3320]
libtorrent version (or branch): 1.1.9.0

platform/architecture: Windows XP 64 SP2

compiler and compiler version: don't now

I hand made merkle torrent and can't start to seed it.

File and torrent example: [360kb.zip](https://github.com/qbittorrent/qBittorrent/files/2389834/360kb.zip)

**Comment by arvidn** [comment]
what did you try and how did it fail?
to seed a merkle torrent you need the merkle tree as well, not just the torrent. I believe you can rebuild the tree if you're a seed though.
