### ISSUE TITLE
Abort set_piece_hashes() and redownload deleted files

### ISSUE THREAD

**Issue by lunatichai** [arvidn/libtorrent#3323]
libtorrent version (or branch): 1.1.9
platform/architecture: Windows x64
compiler and compiler version: Qt5.11.2+MSVC2017x64+boost1.68

Q1:  tell me how can i abort set_piece_hashes()? 
Q2: how can i redownload manualy deleted files? For example, i choose some files in torrent and downloaded them. Then, i deleted it from HDD. So, if i use force_recheck() nothing happens and status changed to "finished". 
Thank You.

**Comment by arvidn** [comment]
A1: What have you tried? I would expect you could throw an exception.
A2: enable logging to see *what* happens. something happens

**Comment by arvidn** [comment]
I think it goes without saying that you need to catch the exception too. and if you're starting your own threads, you need to communicate with the parent thread yourself.

**Comment by arvidn** [comment]
you can also call `set_piece_hash()` directly, instead of using the higher level function to hash all the file data for you

**Comment by lunatichai** [comment]
For more details, thread with torrent creator connected with button "cancel" by signal. My simple test code with creation torrent:

void TorrentCreator::run()
{
    try {
        lt::file_storage fs;
        lt::add_files(fs, m_path.toStdString(), filter);
        lt::create_torrent t(fs);

        QFileInfo fi(m_path);
        const QString rootFolder = fi.absolutePath();

        try {
        lt::set_piece_hashes(t, rootFolder.toStdString(),
        [this, &t](const int n) {
            if(m_abort) {
                throw;
            }
            emit signalPiecesProgress(n, t.num_pieces());
        });
        }
        catch(...) {
            qDebug()<<"Exception: createTorrent ";
        }

        QByteArray out;
        lt::bencode(std::back_inserter(out), t.generate());
        QFile file("my_torrent.torrent");
        if(file.open(QFile::WriteOnly)) file.write(out);
    }
    catch(const std::exception &e) {
        qDebug()<<"Exception: TorrentCreator::createTorrent "<<e.what();
    }
}

So when button clicked variable m_abort set to true and throw exception, but instead go to catch program crashed. Maybe I'm using it wrong

**Comment by arvidn** [comment]
so, you have to run it in a debugger and understand what's actually happening. "crashing" is not specific enough

**Comment by arvidn** [comment]
btw, your bug is the `throw` statement. you cannot rethrow unless you're currently handling an exception (that can be rethrown)

**Comment by lunatichai** [comment]
I run debugger and it say:
qml: fullProgress= 0.012818532818532818
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.1.10.0-a499ace80

file: 'src\disk_io_thread.cpp'
line: 177
function: libtorrent::disk_io_thread::~disk_io_thread
expression: pieces.first =
= pieces.second

stack:
 0: 00007FF7F75450D9 print_backtrace +233  d:\projects\utorr\3rdparty\libtorrent-rasterbar-1.1.10\src\assert.cpp:173
 1: 0000008FCFCF4FA0
 2: 0000000000000001

**Comment by arvidn** [comment]
could you please test this patch? https://github.com/arvidn/libtorrent/pull/3357
