### ISSUE TITLE
cmake installs include/libtorrent/Makefile.* files

### ISSUE THREAD

**Issue by yurivict** [arvidn/libtorrent#3325]
```
include/libtorrent/Makefile.am
include/libtorrent/Makefile.in
```

They shouldn't be installed.

**Comment by arvidn** [comment]
how do you make them not be installed?

**Comment by yurivict** [comment]
Find the line that installs them and remove it. -)
Or just remove gnu tools.

**Comment by arvidn** [comment]
I don't think there's a line that specifically install those files in the cmake builds. I've added documentation on how to install with boost-build though, which works right.

https://github.com/arvidn/libtorrent/pull/3356
