### ISSUE TITLE
cmake builds a lower library version than gmake

### ISSUE THREAD

**Issue by yurivict** [arvidn/libtorrent#3326]
gmake installs
```
lib/libtorrent-rasterbar.so
lib/libtorrent-rasterbar.so.9
lib/libtorrent-rasterbar.so.9.0.0
```

cmake installs
```
lib/libtorrent-rasterbar.so
lib/libtorrent-rasterbar.so.8
```

Please note that the third library (with ```.0.0```) is also not installed.

**Comment by arvidn** [comment]
does this look good? https://github.com/arvidn/libtorrent/pull/3333
@zeule ^^

**Comment by yurivict** [comment]
That's how I patched it too.
