### ISSUE TITLE
Tests don't build with cmake: test does not contain a CMakeLists.txt file

### ISSUE THREAD

**Issue by yurivict** [arvidn/libtorrent#3327]

**Comment by arvidn** [comment]
did you enable `build_tests`?

**Comment by yurivict** [comment]
> did you enable build_tests?

Yes, but the corresponding CMakeLists.txt is missing in the tests directory.

**Comment by arvidn** [comment]
it's right here: https://github.com/arvidn/libtorrent/blob/RC_1_1/test/CMakeLists.txt
