### ISSUE TITLE
Restarting client causes all files to download

### ISSUE THREAD

**Issue by jd-edwards** [arvidn/libtorrent#3328]
**Please provide the following information**

libtorrent version (or branch): 1.1.9 and 1.1.10

platform/architecture: debian stretch x64

compiler and compiler version: gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

The following happens with deluge 1.3.15. 

1. Add torrent with only certain files selected to download.
2. Files download and everything is working as expected.
3. Restart client
4. All files within torrent will automatically start to download.

Reverting back to 1.1.8 fixes the issue.

**Comment by arvidn** [comment]
so are the file priorities are not preserved between sessions?
what does the resume data look like?

**Comment by jd-edwards** [comment]
The file priorities are preserved but they still start to download once restarted.

How can I look at the resume data?
