### ISSUE TITLE
Undefined symbol "_ZTIN10libtorrent17torrent_log_alertE"

### ISSUE THREAD

**Issue by yurivict** [arvidn/libtorrent#3331]
```deluged``` fails to start:

```
[ERROR   ] 16:05:29 main:248 /usr/local/lib/python2.7/site-packages/libtorrent.so: Undefined symbol "_ZTIN10libtorrent17torrent_log_alertE"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/deluge/main.py", line 241, in start_daemon
    Daemon(options, args)
  File "/usr/local/lib/python2.7/site-packages/deluge/core/daemon.py", line 144, in __init__
    from deluge.core.core import Core
  File "/usr/local/lib/python2.7/site-packages/deluge/core/core.py", line 38, in <module>
    from deluge._libtorrent import lt
  File "/usr/local/lib/python2.7/site-packages/deluge/_libtorrent.py", line 59, in <module>
    import libtorrent as lt
ImportError: /usr/local/lib/python2.7/site-packages/libtorrent.so: Undefined symbol "_ZTIN10libtorrent17torrent_log_alertE"
```

This symbol is missing in ```libtorrent.so```.
```-DTORRENT_DISABLE_LOGGING``` is a workaround.

**Comment by arvidn** [comment]
it looks like the python binding was built without `-DTORRENT_DISABLE_LOGGING` but the main library was built with it defined. That's not meant to work, both need to be built with the same configuration.

**Comment by yurivict** [comment]
> it looks like the python binding was built without -DTORRENT_DISABLE_LOGGING but the main library was built with it defined.

In both cases logging was left to be default. But in ```libtorrent-rasterbar``` it is disabled by default, and in the python binding it is enabled by default.

**Comment by arvidn** [comment]
not when built with boost-build. which build system disables logging by default?

**Comment by yurivict** [comment]
I use cmake and python's distutils. In the FreeBSD port I have to use standard build tools, they don't use boost-build.

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/3337
