### ISSUE TITLE
how to set the interval that libtorrent reports to tracker

### ISSUE THREAD

**Issue by Joshua-Wang** [arvidn/libtorrent#3343]
**Please provide the following information**

libtorrent version (or branch):

platform/architecture:

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I was wondering how to set the interval that libtorrent reports to tracker. Also I did not find the default interval that libtorrent interact with tracker.
could it be settings_pack::min_announce_interval or settings_pack:: local_service_announce_interval ?

Thanks a lot.

**Comment by arvidn** [comment]
it's determined by the tracker. it responds with an "announce_interval" field
