### ISSUE TITLE
unable to use torrent_info.creation_date() from python bindings

### ISSUE THREAD

**Issue by Kolcha** [arvidn/libtorrent#3344]
libtorrent version (or branch): 1.1.10
platform/architecture: Manjaro Linux, x86_64
compiler and compiler version: GCC 8.2.1

unable to use torrent_info.creation_date() from python bindings. tested with Python 3.7 and 3.6 on Arch/Manjaro and Fedora, with libtorrent 1.1.10 and 1.1.9

```python
info = libtorrent.torrent_info(sys.argv[1])
print(info.name(), info.creation_date())
```
produces:
```
Traceback (most recent call last):
  File "./tinfo.py", line 8, in <module>
    print(info.name(), info.creation_date())
TypeError: No to_python (by-value) converter found for C++ type: boost::optional<long>
```

**Comment by arvidn** [comment]
could you try this patch? https://github.com/arvidn/libtorrent/pull/3350

**Comment by Kolcha** [comment]
tested, my example works as expected, I got creation time as number.
feel free to merge this fix.
thanks
