### ISSUE TITLE
Unable to use python-bindings

### ISSUE THREAD

**Issue by asadsm** [arvidn/libtorrent#3346]
**Please provide the following information**

libtorrent version (or branch):
1.1.10

platform/architecture:
Centos 6.5 64bit
compiler and compiler version:
gcc-5.2.0

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
Cloned repo, and built libtorrent using the following:
`./configure --enable-python-binding LIBS="-L/home/asmalik/tools/anaconda2/lib" --prefix=/home/asmalik/libtorrent/libtorrent/install --enable-debug=no`

This builds without problems but then I run into the following:

```
>>> import libtorrent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libtorrent-rasterbar.so.10: cannot open shared object file: No such file or directory
```

I've tried including the path to `/home/asmalik/libtorrent/libtorrent/install/lib/python2.7/site-packages` for python so it picks it up at least.

**Comment by asadsm** [comment]
I'm able to resolve the Import error of it not finding it by adding `libtorrent-rasterbar.so.10` to LD_LIBRARY_PATH but I'm getting the following error:

`ImportError: /home/asmalik/libtorrent/libtorrent/install/lib/libtorrent-rasterbar.so.10: undefined symbol: _ZNSt13runtime_errorC1EPKc`

I'm using Python: `Python 2.7.13 :: Continuum Analytics, Inc.`

**Comment by arvidn** [comment]
The first problem is that the python binding can't find the main library (those are separate DSOs). The second error looks like the main library is not linked correctly against the c++ runtime. Specifically it's saying it can't find `std::runtime_error::runtime_error(char const*)`. You may want to review how the library was built and whether it was influenced by some environment variables causing the break. e.g. `CXX`, `CXX_FLAGS` etc.
