### ISSUE TITLE
[client_test] - torrent files without extension not loaded in monitor folder

### ISSUE THREAD

**Issue by murrayf** [arvidn/libtorrent#3358]
**Please provide the following information**
libtorrent version (or branch):
libtorrent-1.1.10

platform/architecture:
sbc/armhf (I don't know if this issue is reproducible in other platforms also)

compiler and compiler version:
gcc version 8.2.0 (Debian 8.2.0-7)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
If you drop a torrent file without .torrent extension in monitor folder it is not loaded. Is necesary to rename this file to something.torrent to make it work.

Thanks and congratulations for LTR.

Alberto.

**Comment by arvidn** [comment]
that behavior is by design. is it a problem?

**Comment by murrayf** [comment]
Of course not. I had only commented it to you in case of you considered 
it a mistake. But for me it is not important...

Thanks,
-- Alberto --
