### ISSUE TITLE
trivial build fix for 64-bit windows

### ISSUE THREAD

**Issue by c0ff** [arvidn/libtorrent#336]
A fix for building 64-bit windows version:
replaced GetFileAttributesEx with GetFileAttributesEx_ macro as was intended.

patch file attached

[libtorrent-GetFileAttributesEx-fix.zip](https://github.com/arvidn/libtorrent/files/66622/libtorrent-GetFileAttributesEx-fix.zip)

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/338
