### ISSUE TITLE
【performance optimize】

### ISSUE THREAD

**Issue by Joshua-Wang** [arvidn/libtorrent#3360]
**Please provide the following information**

libtorrent version (or branch):

platform/architecture:

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I am optimizing libtorrent to get better download speed. I found a phenomenon that some client get a lot of peer info from tracker , as seen in the picture, 200peers. But the client won't connect to them . His peers remains 2 for a long time so the speed is limited. So why the client won't connect to other peers which he gets from tracker?

I have already set max_out_request_queue = 10000.

![image](https://user-images.githubusercontent.com/6940489/47000870-d0cb1780-d15b-11e8-8df8-1d8c75d4e637.png)

Thanks a lot!

**Comment by Joshua-Wang** [comment]
Another symptom is sometimes a client has several peers(about 30), but the download speed is very very slow. How could I get into the reason? I have print all the peer_info, but did not find anything useful.

**Comment by arvidn** [comment]
you should enable more logging, and print it. You do this by enabling more flags in the `alert_mask` setting.

It can get quite verbose, so it's best to log to a file. But that should tell you every connection attempt that's made. Sometimes peers cannot be connected to for instance.

**Comment by arvidn** [comment]
which branch is this?
`max_out_request_queue` does not affect connecting to peers, that's the number of piece requests to keep outstanding.

**Comment by Joshua-Wang** [comment]
version is libtorrent-1.1.4. I'll try print more alerts.

**Comment by Joshua-Wang** [comment]
when I enabled performance_alert, I always get "max outstanding piece requests reached" and "send buffer watermark too low" . but I've already increase the related params.
see
   settings.max_out_request_queue = 10000
   settings.max_allowed_in_request_queue = 10000
   settings.send_buffer_low_watermark = 1024 * 1024 * 10
   settings.send_buffer_watermark = 1024 * 1024 * 10
   settings.send_buffer_watermark_factor = 150

Isn't this big enough ?

**Comment by Seeker2** [comment]
Some peers/seeds are slow to upload to you because their ISP connection is slow, they're running a buggy BitTorrent client, they're using bad settings in their BT client, their line is overloaded by other activities (such as other people using it on a LAN), etc.

It's worthwhile to have a friend on another ISP test your qBitTorrent using both qBitTorrent and other BitTorrent clients that don't use libtorrent -- the first thing to resolve in such testing is any firewall issues either ends have.

**Comment by Joshua-Wang** [comment]
I've print all the peer_info status. I found that peers who download fast have lots of interesting| interested peers to download from. while those who download show get lots of choked peers. So I guess the reason can be choking_algorithm. I've used setting settings_pack::seed_choking_algorithm = fastest_upload. 
I'll show the result if there is a performance improvement.

**Comment by Joshua-Wang** [comment]
I have add following params according to high_performance_seed() in src/session.cpp.
        settings.connection_speed = 100
        settings.connections_limit = 8000
        settings.listen_queue_size = 3000
        settings.unchoke_slots_limit = 2000
        settings.close_redundant_connections = True
        settings.request_timeout = 10
        settings.peer_timeout = 20
        settings.inactivity_timeout = 20
        settings.max_failcount = 1
        settings.aio_threads = 8
And the speed rocks. I can see a huge improvement.
