### ISSUE TITLE
python-binding params

### ISSUE THREAD

**Issue by Joshua-Wang** [arvidn/libtorrent#3361]
**Please provide the following information**

libtorrent version (or branch):

platform/architecture:

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Can all the members in libtorrent::session_settings be used in python-bindings ?

Just like
        import libtorrent as lt
        settings = lt.session_settings()
        settings.enable_dht = False
        settings.bandwidth_mixed_algo_t = False
        settings.mixed_mode_algorithm = False
        settings.upload_rate_limit = self.max_upload_rate
        settings.download_rate_limit = self.max_download_rate
        settings.unchoke_interval = 20
        settings.choking_algorithm = 0
        settings.seed_choking_algorithm = 0
        settings.send_buffer_low_watermark = 1024 * 1024 * 10
        settings.send_buffer_watermark = 1024 * 1024 * 10
        settings.send_buffer_watermark_factor = 150
        settings.active_downloads = 20
        settings.active_seeds = 20
        settings.active_checking = 20
        settings.max_suggest_pieces = 20
        settings.tick_interval = 1
        settings.ignore_limits_on_local_network = False
        settings.max_out_request_queue = 10000
        settings.max_allowed_in_request_queue = 10000
        settings.announce_to_all_trackers = True
        settings.allow_multiple_connections_per_ip =True
        settings.min_announce_interval = 10
        settings.local_service_announce_interval = 10
        session.set_settings(settings)

I have used this in my env. But I am not sure such as settings.max_allowed_in_request_queue = 10000 will actually take effect.

Thanks a lot.

**Comment by arvidn** [comment]
yes. which version of libtorrent is this?

**Comment by Joshua-Wang** [comment]
libtorrent-1.1.4
