### ISSUE TITLE
Is there any way to build it on linux using CLion?

### ISSUE THREAD

**Issue by abhi-jha** [arvidn/libtorrent#3374]
libtorrent version (or branch): master

platform/architecture: x86_64 GNU/Linux 

compiler and compiler version: clang version 6.0.0-1ubuntu2

I included the project in the CLion IDE and I was trying to build it through main.cpp.

**Comment by arvidn** [comment]
Assuming clion build with cmake, it should work

**Comment by abhi-jha** [comment]
I get the following when I try to run/build it : https://imgur.com/a/7Ki77Eg

Clicking on Executable I get to choose from a set of folders which doesn't make much sense to me. What am I doing wrong?

**Comment by arvidn** [comment]
I don't know what CLion does. I would recommend using boost-build or cmake

**Comment by aldenml** [comment]
@abhi-jha in case you still need it.

You need to add `-Dbuild_examples=ON` to your project CMake settings, allow CLion to refresh/reload the project, and then run one of the examples. Take a look at the images:

<img width="1042" alt="screen shot 2018-10-27 at 2 45 52 pm" src="https://user-images.githubusercontent.com/143813/47608166-9da84400-d9f7-11e8-9916-1cbe5cea6864.png">
<img width="405" alt="screen shot 2018-10-27 at 2 46 15 pm" src="https://user-images.githubusercontent.com/143813/47608170-a3058e80-d9f7-11e8-84d9-58fada81db09.png">
<img width="1689" alt="screen shot 2018-10-27 at 2 46 24 pm" src="https://user-images.githubusercontent.com/143813/47608172-a567e880-d9f7-11e8-9933-e04eccf9eea5.png">

**Comment by abhi-jha** [comment]
@aldenml Thanks. This helps.
