### ISSUE TITLE
deluge1.3.15 Cannot start daemon Deluged cannot start.

### ISSUE THREAD

**Issue by Unlash** [arvidn/libtorrent#3379]
libtorrent version (or branch):
 libtorrent-1.2.0-RC 

platform/architecture:
Debian GNU/Linux 9.5 (stretch)

compiler and compiler version:
gcc version 6.3.0

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
deluge1.3.15 Unable to start daemon  
WebUI Normal
Use libtorrent-1.1.10 Normal Using  libtorrent-1.2.0-RC  cannot start deluged WebUI normal.

![snipaste_2018-10-21_11-55-08](https://user-images.githubusercontent.com/32661990/47262965-81ecfb80-d528-11e8-8756-1a975f11bf52.png)
Click No entry.

**Comment by arvidn** [comment]
I think you meant to file this with deluge.
