### ISSUE TITLE
move_storage deletes everything till it can't

### ISSUE THREAD

**Issue by Bhambya** [arvidn/libtorrent#3380]
**Please provide the following information**

libtorrent version (or branch):
1.1.10

platform/architecture: Android
compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

The code below is the culprit:

             for (std::set<std::string>::iterator it(subdirs.begin())
			, end(subdirs.end()); it != end; ++it)
		{
			error_code err;
			std::string subdir = combine_path(old_save_path, *it);
			while (subdir != old_save_path && !err)
			{
				remove(jni_env, subdir, err);
				subdir = parent_path(subdir);
			}
		}

If the old_save_path (which is set from m_save_path) does not have a / at the end, and subdir has, it never compares the same and everything is deleted recursively until it can't due to permissions.

**Comment by arvidn** [comment]
the cleanest solution would probably be to use `boost.filesystem` (and `boost::path`) for this, which would have a correct comparison operator. Short of that, do you think it would be sufficient to strip any trailing "/" and "\"?

afaict, `parent_path()` returns a string without the trailing "/".

**Comment by Bhambya** [comment]
Yes the boost::path would be the best. I'll make a pull request with the change.

**Comment by arvidn** [comment]
transitioning to using boost.filesystem (and std::filesystem) is on my roadmap, but I don't think `RC_1_1` (where libtorrent 1.1.x is built from) nor `master` is the right time to do it. (I'm trying to release master). I would prefer a patch that solves it with plain strings in the short term

**Comment by arvidn** [comment]
does this work? https://github.com/arvidn/libtorrent/pull/3387

**Comment by Bhambya** [comment]
This is not working because `combine_path` adds back the slash to the `subdir`.
std::string subdir = combine_path(old_save_path, *it);
Maybe strip_trailing_slash can be used inside combine_path? But I don't know the repercussions of that.

**Comment by Bhambya** [comment]
Sorry, that's not the only issue, `parent_path` in fact, explicitly retains the trailing slash.

**Comment by arvidn** [comment]
I see, perhaps the patch should do the opposite, and it should be something like `ensure_trailing_slash()`

**Comment by arvidn** [comment]
I updated the patch. I realized that the problem is that sometimes there will be a slash, and sometimes not. I fixed it in the comparison instead.

**Comment by arvidn** [comment]
@Bhambya  any word on this?
