### ISSUE TITLE
Random offset writes happen in sequential download mode

### ISSUE THREAD

**Issue by zvirja** [arvidn/libtorrent#3382]
**Environment**

_libtorrent version (or branch):_ I use the latest version of [libretorrent app](https://gitlab.com/proninyaroslav/libretorrent). Expects it uses the latest version of the library.
_platform/architecture:_ Android 7, ARMv7
_compiler and compiler version:_ Don't know.

**Disclaimer**

First of all please notice that I never used this library for the development, so might miss some details. However, I've examined the API shape and am very confident you are the right target for this issue. Will try to describe the issue from the user's perspective, so we can together discuss what could be done here.

**Scenario**

I'm an owner of the Galaxy Tab S2 tablet and have an external SD Card installed. That card is not super fast - for sequential write it can give only 10-15 MB/s, for random it's much worse. It's formatted with `exFAT` file system and I cannot format it to the `ext3/ext4/ext?` - device simply doesn't recognize it then. Android uses FUSE and creates a virtual file system on top of that - on my Android device it's named as `sdcardfs` if I check that via `mount`. The issue is that at the end of this chain the `sparse` files are not supported (I suspect that's because of the underlying file system, but never had a chance to prove that).

When I start to download a torrent file to my SD Card, I _always_ enable the sequential mode. Otherwise, any write (seek/access?) to the advanced file position (e.g. to middle) forces kernel to fill file with zeros. The sequential mode does the trick and torrent starts to download at stable 9-10MB/s speed. However, after short time something goes wrong and download gets stuck. When monitoring the file during that time, I can see that it starts to grow and becomes filled with zeros, which indicates that seek to the end occurred. It happens randomly - sometimes soon after start, sometimes after it downloaded quarter or even half of the file - but happens almost for each time. After the file is fully created on the file system, the download resumes back at the previous speed, which indicates that normally write happens pretty linearly. Obviously, this stuck significantly increases the download time. For instance, for 10GB file it takes ~20min to fill it with zeros. Later it takes the same time to download the actual file content. Basically, this issue doubles the download time.

I noticed that behavior with the all torrent clients I tested. All of them suffer from the issue and I know that a lot of them use `libtorrent` library under the hood (e.g. libretorrent or Flud). Therefore, I made a conclusion that it's library related issue.

As far as I understand, the only ways we could prevent kernel from filling files with zeros are:
- use sparse files, like we do on modern file systems. Here it's not available due to SD Card file system.
- perform only linear writes without seeking too far (or without seeking at all).

When I enable the sequential download mode, I expect chunks to be downloaded and written one by one. I understand, that some buffering should happen as library still download chunks in a random order, but the write should be sequential as downloaded chunks have good locality. To me it looks like sometimes a chunk from the middle or end of the file is received, so library tries to write it and causes the issue.

So here are the main questions on that:
- Why does it happen? Do you clearly see why it could be? Don't we enforce the order when mark torrent with the `SEQUENTIAL` flag?
- Is it possible to somehow fix that issue from the library client side? Given the API shape you have it's unlikely, but still.

If the current behavior is expected and `SEQUENTIAL` flag shouldn't prevent random chunks from being downloaded, then I see the following possible ways to solve that:
- Introduce one more mode like `STRICT_SEQUENTIAL`. It will download chunks in the sequential order, but if suddenly any chunk far from the current HEAD is received, it will simply discard it and re-download it later. The final result will be slightly increased traffic, but much quicker download.
- Introduce a file cache for the parts which are far from HEAD. That cache file could reside on the separate drive (e.g. Internal Storage) which is fast for random writes. It might complicate the architecture, so is less attractive.

Will be really happy to have your expertise on the issue reasons and realistic ways to solve it! I would appreciate any feedback you could provide! 🙏 Thanks in advance for your time and for making this great product! 

----

I believe that I'm not the only user with slow SD Card and a lot of clients will win from this change. I'm quite surprised that I wasn't able to find the issue already here - the scenario doesn't look too unique 😕 Might happen that I simply is bad on searching or am the only dev with slow SD card on tablet 😉

**Comment by arvidn** [comment]
libtorrent is currently deliberately picking from the end from snubbed peers, when in sequential download mode. I don't have very strong opinions about this, and it may be a reasonable thing to change.

Here's a patch that I believe would:

https://github.com/arvidn/libtorrent/pull/3386

The rationale for "reversing" the picking strategy for snubbed peers is to make their picked blocks not be in the way for more urgent blocks. However, sequential downloading is not a very good way to indicate which blocks are urgent anyway, `set_piece_deadline()` (i.e. streaming) is a much better way for that already.

**Comment by zvirja** [comment]
Hi @arvidn,

Many thanks for your analysis, explanation and the quick fix you are applying - I appreciate it a lot! 🙏 

I've tried to test the fix by making a custom build of `libretorrent` Android client and found that the fix is not enough and the issue still happens. After that I spend almost two days on deployment/debugging in WinDBG/logging trying to figure out the exact reason and I believe I found it.

Issue happens in the following lines of code:
https://github.com/arvidn/libtorrent/blob/a5da48edd4be7f858d56724e4a82902e10b91ec6/src/piece_picker.cpp#L2146-L2185

If we are connected to a peer which doesn't have all the pieces, it might potentially start adding pieces at the middle or even end of the file - depends on the pieces availability. Later, once the piece is downloaded, it causes file seek and hung.

To prove my guess I applied a dirty fix on my environment by adding pieces only if peer is a seed (added `&& pieces.all_set()` to the condition) and it helped.

Therefore, we need one more change, which allows to ignore peers during the download and load data from the seeds only. I quickly checked the code and public API and it seems we don't have such a feature now. Or the solution could be more elegant - not download pieces which are far from the current download HEAD - but it doesn't seem that library has related concepts in the codebase as of now.

The feature about skipping the peers is questionable and I am not sure what is the best shape for it. It might be a part of this library via some flags, or library could provide enough API for the clients, so they could make the desired behavior by themselves.

Thanks for your time!

**Comment by ssiloti** [comment]
The piece picker is complex enough as it is, I don't think this would be a widely enough used feature to warrant support in libtorrent. If you *really* only want pieces to come in sequentially, have the client manage piece priorities so that everything but the first few incomplete pieces is set to do-not-download.

**Comment by zvirja** [comment]
@ssiloti I patched the `piece_picker` just to prove a guess. I agree that it's not a right place for that and likely logic should move to `peer_connection`, where we decide whether peer is interesting or not. Or, for instance, to the `torrent::peer_is_interesting` method where we might check for some flags.

It will be much easier to simply skip all the peers, rather than create and maintain a complex logic around the priorities. This way there are at least some chances Android application authors will support that.

**Comment by arvidn** [comment]
similar to how sequential download is a poor approximation for streaming, it's also a poor implementation of "support filesystems without sparse files". I recall logic we worked on at bittorrent many years ago supporting embedded systems, specifically writing to slow USB drives formatted as FAT.

I think the this is a decent algorithm:

1. Set the priorities to all pieces to 0.
2. For every file in the torrent, set the first 4 MiB worth of pieces to priority 1 (except the first piece in case it overlaps with the end of the previous file).
3. Every time a piece is downloaded, extend the pieces with piece priority 1, 4 MiB worth of pieces beyond that piece.

All of this *can* be done outside of libtorrent, and it's not that complicated. So I would be hesitant to include it in the scope of libtorrent.

**Comment by arvidn** [comment]
I landed the patch to make sequential downloading mode stricter. I'm reluctant to build more special cases around this

**Comment by arvidn** [comment]
this patch has been released in libtorrent 1.1.11 now

**Comment by zvirja** [comment]
@arvidn Many thanks for taking a look at this issue and sharing your opinion. Sorry for the complete silence from my side - was quite busy these days 😖 

Indeed, the `sequential mode` + `seeds only` is a poor approximation for pure sequential download, but so far it worked like a charm on my custom build of the Libretorrent app. Given cost of the development, it looked like a good trade-off.

I don't want this library to be over-complicated with the particular cases, that's why I suggested a generic API - just provide a way to reject a peer via callback. This way we could achieve even more powerful features (e.g. ban particular peers, etc) and it will not pollute API a lot.

The algorithm you described in [this](https://github.com/arvidn/libtorrent/issues/3382#issuecomment-433704010) comment might be OK, but the question is whether it's realistic for it to be implemented in the applications - it looks quite massive. That's why I wanted to have more primitive and trivial instrument, which also works fine and might be easily implemented.

@proninyaroslav As an author of the Libretorrent app, do you feel it realistic to have the sequential download algorithm described [here](https://github.com/arvidn/libtorrent/issues/3382#issuecomment-433704010) implemented in your app? What are your thoughts on the suggested approaches and the issue in general?

**Comment by arvidn** [comment]
There is an API for plugins, but it's primarily concerned about peer communication and unchoke logic.
It's not obvious to me that there is a simple and generic plugin architecture that can implement the functionality you want in a simpler way that what I suggested, using piece priority.
In my mind, the piece priority API *is* that lower level, simple API to achieve this.
Do you have something specific in mind?

**Comment by proninyaroslav** [comment]
@zvirja I encountered a similar problem when implementing file streaming in LibreTorrent. I needed to achieve a linear flow that is downloaded strictly from beginning to end. Sequential downloading doesn't guarantee the order of loading pieces, as it downloads only those pieces that are currently available. My solution was the algorithm that is very similar to the algorithm proposed by @arvidn. That is, I achieve linear downloading by setting priorities for pieces.

**Comment by arvidn** [comment]
I think it's important to distinguish *requesting* blocks and *completing download* of a block. It's easy to make *requests* be sequential (as long as all pieces are available to us). However, peers will be able to send the blocks at different rates with different delays. The only way to guarantee that the *completion* of downloading a block is sequential is to not have more than one outstanding request at a time, which clearly is a show-stopper performance-wise.

As I see it, there is no getting around the fact that you need to tolerate blocks arriving out-of-order. Now, in the case of FAT filesystem, *some* out-of-orderness is not a problem, as long as the blocks are close enough to the current end-of-file. The more blocks/pieces you allow to be outstanding at a time, the more likely you are to get good performance, that's why I suggested enabling blocks of pieces at the end of every file in the torrent, and not just a single piece, but a few megabytes worth of pieces.

**Comment by zvirja** [comment]
@proninyaroslav Thanks for kicking in! So does it mean that in fact this logic is already implemented in the LibreTorrent application? So I can use it to guarantee that no file seeks happen?

> I think it's important to distinguish requesting blocks and completing download of a block.

@arvidn Yeah, you are completely correct here. Requesting blocks in sequential order indeed might still lead to random offsets. However, per my tests, it worked more or less stable on the tablet and the locality did a trick. I think that it's not a big problem that from time to time spikes with speed slowdown could happen. More important is that we'll not get random spikes when offset happens too far and all the IO gets stuck.

**Comment by proninyaroslav** [comment]
@zvirja At the moment this feature is only available for streaming via http, that is, you can download files in this way via a browser. I can add alternate sequential download as a separate option when adding a torrent.

**Comment by zvirja** [comment]
@proninyaroslav It would be great!🌞Could you please register such a feature, or you want me to register it for you? I could test it later, so we see whether it's enough or we still require assistance from libtorrent side.

@arvidn Thanks so far for the great support I got!

**Comment by proninyaroslav** [comment]
@zvirja  I think you can make an issue and describe this feature.
