### ISSUE TITLE
Python 3.7 binding fail on Windows 10

### ISSUE THREAD

**Issue by DjLegolas** [arvidn/libtorrent#3391]
Trying to bind libtorrent 1.1.10 with python 3.7.
I'm using Boost 1.68.0, and have Visual Studio 2017 Enterprise.

I tried running using `python setup.py build --bjam`, and received the next output:
```
C:\Libraries\libtorrent-rasterbar-1.1.10\bindings\python>python setup.py build --bjam
c:\Libraries\boost_1_68_0\b2 python=3.7 libtorrent-link=static boost-link=static release optimization=space stage_module --abbreviate-paths address-model=32 toolset=msvc-14.1 -j4
CXXFLAGS =
LDFLAGS =
OS = NT
building boost from source directory:  C:\Libraries\boost_1_68_0
using python interpreter at:  C:\Python37-32\python.exe
Performing configuration checks

    - default address-model    : 32-bit (cached)
    - default architecture     : x86 (cached)
    - symlinks supported       : no  (cached)
    - junctions supported      : yes (cached)
    - hardlinks supported      : yes (cached)
error: Unable to find file or target named
error:     '/boost/python//boost_python3'
error: referred to from project at
error:     '.'

build failed
```
How can I fix this? Is there another way to do this?

**Comment by ssiloti** [comment]
Looks like boost.python changed the way it exports targets. Libtorrent's build scripts will need to be updated to work with Boost 1.67+. If you use boost 1.66 it should work.

**Comment by DjLegolas** [comment]
Ok, thanks.
I managed to compile using Boost 1.66.0.

**Comment by arvidn** [comment]
I can't remember now why I had to copy-paste the rule from boost.python, but I have a feeling it may have been related to introducing `<visibility>hidden`. This feature has now made it into the upcoming boost-1.69 so perhaps it could be simplified back to how it was originally meant to be done for more recent versions of boost

**Comment by arvidn** [comment]
as far as I can tell, just referring to `boost_python3`, even in a branch that's not taken, causes a failure (when that target does not exist).

**Comment by ssiloti** [comment]
That would at least make is possible to support all boost versions, but we'd need to add an option for the user to specify which target to use via `setup.py` and the user would need to set the option depending on which version of boost they're building against. Unless there's a good way to detect the boost version from `setup.py`?

**Comment by cas--** [comment]
The boost python naming now includes the python version: https://www.boost.org/doc/libs/1_67_0/libs/python/doc/html/rn.html

The Ubuntu Cosmic package has encountered the same issue where it is looking for `boost_python-py36` and defaults back to `boost_python`, which means it links to Python 2.7 and has broken python3-libtorrent: https://bugs.launchpad.net/ubuntu/+source/libtorrent-rasterbar/+bug/1800264

**Comment by ssiloti** [comment]
@cas-- That Ubuntu issue has to do with the naming of the Boost.Python shared library. This issue has to do with the naming of the Boost.Python target in Boost.Build.

**Comment by ajw107** [comment]
Note that if you use pythion 3.7 and up with boost 1.66.0 it won't compile (C2440 error about a type mismatch).  You have to edit `boost_1_66_0\libs\python\src\converter\builtin_converters.cpp` ~line 48 and remove the current #else and replace it with the newer elsif from boost 1.68.0:
```
#elif PY_VERSION_HEX < 0x03070000
  void* convert_to_cstring(PyObject* obj)
  {
      return PyUnicode_Check(obj) ? _PyUnicode_AsString(obj) : 0;
  }
#else
  void* convert_to_cstring(PyObject* obj)
  {
      return PyUnicode_Check(obj) ? const_cast<void*>(reinterpret_cast<const void*>(_PyUnicode_AsString(obj))) : 0;
  }
#endif
```

Obviously this is not really how it should be solved, but it's a work around until libtorrent is able to support python3 in boost versions greater than 1.66

**Comment by arvidn** [comment]
Here's an attempt at addressing this issue:
https://github.com/arvidn/libtorrent/pull/3524/files?utf8=%E2%9C%93&diff=split&w=1

If this works, I will back-port it to `RC_1_1`.

@ssiloti does this make sense? (I think it's a fairly reasonable expectation to find the boost version in `$BOOST_ROOT`).

@ajw107 would you mind testing it? If you want to test it in libtorrent 1.1.x, you can just apply the second commit! i.e. something like `git show 3b4e6a168d994a254fbfeda6d6eaf801c60ea883 | patch -p1`

**Comment by arvidn** [comment]
This is believed to be fixed now, in https://github.com/arvidn/libtorrent/pull/3524
