### ISSUE TITLE
Details on partfiles

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#3397]
I have seen mention of part files in docs and there is an incomplete changelog entry:

    support for partfiles, where partial pieces belonging to skipped files are put

There is no further information about them. How are they used and are there python bindings exposed?

Also I found when searching for information is there are two alternative spellings `partfile` and  `part_file` (Also `part file` in docs). I guess that it's too late to rename the `part_file.cpp` source file... ;)

**Comment by arvidn** [comment]
partfiles are used automatically when the *file* priority is set to 0. piece priorities don't affect this.

partfiles are stored in the root of the save path, they are named ".<info-hash>.parts".

When resuming a torrent with existing files, the partfile will be cecked as well as all files with priority 0, to support resuming torrents downloaded with a previous version, where parts were stored in their actual location.

If a file changes priority from 0 to something else, the blocks in the part file are "exported" into the right file. However, the opposite operation is not supported, a file with some downloaded blocks that's set to priority 0 will not have those blocks be moved into the partfile.

PRs with documentation fixes and additions are welcome!

**Comment by cas--** [comment]
What is the reasoning for not moving back to partfiles after exporting? This only seems useful if the user remembers to set `0` when initially adding the torrent.

**Comment by arvidn** [comment]
there's no reasoning, it's just not implemented, it also doesn't seem like a terribly important feature.
Additionally, the partfile isn't really designed to hold gigabytes of data. It's at least not tested at that scale, so it feels a little bit scary to possibly move in very large files into it.

**Comment by cas--** [comment]
It is an often requested feature from users so it is good to see. I just want to be clear of the workings and limitations when I document it for Deluge. I actually hadn't noticed the `.parts` files probably because I was not setting the `0` priority or only doing so later on.

> it feels a little bit scary to possibly move in very large files into it.
Oh good point. Well I was thinking that any non-overlapping pieces would be deleted but I suppose a user would be horrified if they marked a file `0` and all the data for it vanished instantly.

What if the file was deleted from disk though? Would setting it to `0` put new pieces back in to partfile?
