### ISSUE TITLE
Speed decrease with peers

### ISSUE THREAD

**Issue by kotbrain** [arvidn/libtorrent#3400]
libtorrent version (or branch): 1.1.10
platform/architecture: Any
compiler and compiler version: VS 2017

When I download the torrent alone through the web-seed, I keep a constant speed of 10 MB / s. But when I load the same torrent with peers (50+), the download speed drops to 3-5 mb / s, and the upload speed increases to 1-2 mb / sec. In the browser at the same time, the speed is also 10 mb / s.

I want to use an active exchange with peers only when the web-seed server is overloaded. How do i get maximum download speed?

**Comment by arvidn** [comment]
it depends on why your download speed decreases when you have peers. My guess would be that it has something to do with random access writes to your drive, and the page cache not being large enough to take the write spikes.

you can measure by regularly logging the stats counters (`session::post_session_stats()`)

**Comment by kotbrain** [comment]
Here are statistics on the disk at various download speeds:

500 kb / sec.
```queued_bytes: 15958016, queued_writes: 974, queued_reads: 22, writes_cache: 974
reads_cache: 12, pinned: 33, num_blocks_read: 9938, cache_hit: 1869
blocks_in_use: 1018, blocks_written: 42144, write_ops: 2271, mfu_size: 0
mfu_ghost: 0, mru_size: 11, mru_ghost: 16
```
3-5 mb / sec.
```queued_bytes: 5685248, queued_writes: 347, queued_reads: 0, writes_cache: 347
reads_cache: 641, pinned: 17, num_blocks_read: 6425, cache_hit: 1522
blocks_in_use: 988, blocks_written: 21393, write_ops: 1274, mfu_size: 0
mfu_ghost: 0, mru_size: 9, mru_ghost: 16
```
10 mb / sec. (with peers)
```queued_bytes: 7913472, queued_writes: 483, queued_reads: 7, writes_cache: 483 10 МБ \ сек
reads_cache: 439, pinned: 24, num_blocks_read: 10999, cache_hit: 1740
blocks_in_use: 977, blocks_written: 26768, write_ops: 1196, mfu_size: 1
mfu_ghost: 1, mru_size: 9, mru_ghost: 16
```
If set ```mixed_mode_algorithm``` to ```prefer_tcp```, the download speed increases and sometimes reaches its maximum. But it happens randomly. When I launched the download for the first time, download speed was a constant 10 mb / s, and at the second start 2-5 mb / s. The number of peers and all other conditions are the same in both cases.

**Comment by arvidn** [comment]
It’s a lot easier to analyse if you print every counter for every sample (just calling message() on the alert will do it). Then you can use tools/parse_session_stats.py to render plots.

Just a snapshot of those counters alone doesn’t say much, as it’s normally the rate that’s interesting
