### ISSUE TITLE
Can not compile on Cygwin

### ISSUE THREAD

**Issue by DRSDavidSoft** [arvidn/libtorrent#3404]
## Build system info
libtorrent version (or branch): `libtorrent-rasterbar-1.1.10`
platform/architecture: `Cygwin x86 WOW on Windows 10 x64`
compiler and compiler version: `gcc 7.3.0 (i686-pc-cygwin)`

## Description

`libtorrent` does not detect Cygwin and cannot be compiled.

<img width="711" alt="libtorrent-cygwin" src="https://user-images.githubusercontent.com/4673812/48021035-c396bc80-e14c-11e8-936f-b76ee4939a9e.png">

<img width="711" alt="libtorrent-cygwin-fail" src="https://user-images.githubusercontent.com/4673812/48031693-4417e600-e16a-11e8-9a03-55c8566e056c.png">

Could you please add Cygwin support?

**Comment by arvidn** [comment]
does cygwin not define `_WIN32`? I would have expected it to be classified as windows for the most part, or perhaps MinGW.

**Comment by DRSDavidSoft** [comment]
@arvidn it doesn't appear to do so, the following yields only in `__CYGWIN__`.

```cpp
#include <stdio.h>

int main(void)
{

	printf("detected flags:\n\n");

#ifdef _WIN32
	printf("_WIN32\n");
#endif

#ifdef __WIN__
	printf("__WIN__\n");
#endif

#ifdef __CYGWIN__
	printf("__CYGWIN__\n");
#endif

#if (defined linux || defined __linux || defined __linux__)
	printf("linux OR __linux OR __linux__\n");
#endif

#if (defined __FreeBSD__ || defined __NetBSD__ || defined __OpenBSD__)
	printf("any variant of BSD\n");
#endif

	return 0;
}
```

To be honest, this is weird, I half expected it would define `_WIN32_` or `__WIN__` at least.

<img width="535" alt="cygwin_flags" src="https://user-images.githubusercontent.com/4673812/48035716-7df0e880-e17a-11e8-8c74-a345589b4a3d.png">

Does `libtorrent` require any kind of modification to the `configure` file in order to build successfully?

**Comment by arvidn** [comment]
I don't have a windows system at hand to test. would you mind tweaking `libtorrent/config.hpp` to treat cygwin as windows? and see if you can get it to work?

**Comment by DRSDavidSoft** [comment]
Sure, no problem. I tried building after applying this:

```diff
--- config.hpp.orig     2018-11-06 04:33:40.427304700 +0330
+++ config.hpp  2018-11-06 04:40:11.608137400 +0330
@@ -273,7 +273,7 @@
 #define TORRENT_USE_PWRITEV 1

 // ==== WINDOWS ===
-#elif defined _WIN32
+#elif (defined _WIN32 || defined __CYGWIN__)
 #define TORRENT_WINDOWS
 #ifndef TORRENT_USE_GETIPFORWARDTABLE
 # define TORRENT_USE_GETIPFORWARDTABLE 1
```

No dice, it still isn't building.

I think Cygwin builds should lean more onto the Linux libs, but I'm not sure.

**Comment by DjLegolas** [comment]
According to Cygwin's [FAQ](https://cygwin.com/faq.html#faq.programming.preprocessor), all of the WIN32 macros/definitions are added when passing `-mwin32` to `gcc`.

Therefor, the solution might either adding this parameter to the gcc when building from Cygwin, or creating new config definition for Cygwin.
