### ISSUE TITLE
Rename library

### ISSUE THREAD

**Issue by thkvc** [arvidn/libtorrent#3417]
Can I have permission to rename library from libtorrent-rasterbar.dll to libtorrent.dll for use in project?
Please tell me.

**Comment by arvidn** [comment]
are you asking to change the name produced by the `Jamfile`, `CMakeLists.txt` in the libtorrent repo?

**Comment by arvidn** [comment]
as far as I understand the names of binaries is not covered by the license, and can be named whatever you like.

I think the `Jamfile` actually produces a file called `libtorrent.dll` but the `CMakeLists.txt` produces `libtorrent-rasterbar.dll`. I think to rename the target file you have to rename the target `torrent-rasterbar`, to replace all occurrences.

**Comment by thkvc** [comment]
ok. thanks for your reply. i will try it
