### ISSUE TITLE
Faulty pkg-config generated from cmake

### ISSUE THREAD

**Issue by Chocobo1** [arvidn/libtorrent#3424]
**Please provide the following information**

libtorrent version (or branch):
RC_1_1 latest.

platform/architecture:
Arch linux

compiler and compiler version:
gcc 8.2.1
cmake version 3.12.4

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

This is generated with autotools (omitted some lines), no problem compiling qbt with this:
```
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib

Libs: -L${libdir} -ltorrent-rasterbar -lboost_system 
Libs.private:  -lboost_chrono -lboost_random -lpthread   -lpthread  -lssl -lcrypto 
```

This is generated with cmake:
```
prefix=/usr
libdir=${prefix}/lib

Libs: -L${libdir} -llibtorrent-rasterbar -lpthread -l/usr/lib/libssl.so -l/usr/lib/libcrypto.so -l/usr/lib/libboost_system.so
```
Compiling qbt with it shows errors:
```
linking qbittorrent
/usr/bin/ld: cannot find -llibtorrent-rasterbar
/usr/bin/ld: cannot find -l/usr/lib/libssl.so
/usr/bin/ld: cannot find -l/usr/lib/libcrypto.so
/usr/bin/ld: cannot find -l/usr/lib/libboost_system.so
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1038: qbittorrent] Error 1
```

AFAIK there are some problems here:
1. `-llibtorrent-rasterbar` should be `-ltorrent-rasterbar`.
2. Don't know why `-l/usr/lib/lib*.so` are generated when you can link with shorthand `-l*` instead.

**Comment by arvidn** [comment]
@zeule you know how to fix this, right?
the absolute paths to ``libssl``, ``libcrypto`` and ``boost_filesystem`` looks wrong. However, I was under the impression that the ``lib``-prefix when specifying a library was optional, but not an error.

It also seems that the cmake package config file doesn't distinguish between private and public libraries.

**Comment by zeule** [comment]
I do remember that I accounted for the "lib" prefix, but apparently something went wrong. I'll fix that, of course. Considering the full library paths, why is that wrong? We can trim them, no problem, but then we need to put `-L` there for the dependencies, which might conflict with the directory for the main library. 

> It also seems that the cmake package config file doesn't distinguish between private and public libraries.

What private libraries do you mean?

**Comment by arvidn** [comment]
I was under the impression that the package config file may not be built on the machine it's installed (in the case of a binary package). In that case I would expect that libraries are primarily found by name, not by full path. But I imagine you to have more experience with this though.

the old pkg-cfg file made `boost_chrono`, `boost_random`, `pthread`, `pthread`, `ssl`, `crypto` "private" (whatever that means, I assume it means when linking statically, you need to include these, but not if you link dynamically).

iirc, libtorrent doesn't expose any parts of these libraries in its API. In master, chrono types are used, but those are the ones from the standard library there.

**Comment by zeule** [comment]
The absolute paths in pkg-config is my mistake: I had to either remove paths or avoid `-l`. Will remove paths to mimic autotools as that is what people probably expect.

On master branch If I change the following libs to be private I get linking errors:
pthreads:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: test/libtest_common.a(setup_transfer.cpp.o): undefined reference to symbol 'pthread_condattr_setclock@@GLIBC_2.3.3'
```

ssl:
```
 /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: test/CMakeFiles/test_tracker.dir/test_tracker.cpp.o: undefined reference to symbol 'SSL_library_init'
```

I'll check boost libs in RC_1_1 later.

**Comment by Chocobo1** [comment]
Just tried fccf25e8390a6aa4b3323697eb6232fab729689c in RC_1_1, it introduce another issue: now the file is wrongly named `torrent-rasterbar.pc` instead of `libtorrent-rasterbar.pc`.

**Comment by zeule** [comment]
Sorry, I overlooked that. #3440/3441 should make the filename correct again.

**Comment by zeule** [comment]
> I'll check boost libs in RC_1_1 later.

Making boost libs private (except boost::system) does not break linking of tests and examples.

**Comment by Chocobo1** [comment]
>Sorry, I overlooked that. #3440/3441 should make the filename correct again.

5c533522cb8be8390f2e2183a179e5ebab6edfbf fixed it, thanks!

@arvidn 
This issue is resolved, feel free to close it.
