### ISSUE TITLE
[Feature Request] Please stop creating empty folder for torrents that aren't even downloading.

### ISSUE THREAD

**Issue by Misiek304** [arvidn/libtorrent#346]
Initially I wrote about this issue in qBittorrent github account but I was told it's libtorrent issue.

For some reason qBittorrent is creating empty folders before I even start to download any data. I don't understand this behavior. I tested uTorrent and Transmission and they weren't doing this. It's super annoying when I delete torrent files, reopen the bittorrent client, get "missing files" status and empty folder for that torrent is being creating making a bit of the mess on my HDD.

The expected behavior would be to create folder after the download process has started and some data that where downloaded needs to be written to the drive.

Apparently "the problem is with the default_storage::initialize() function that creates all directories for files with priority above zero." in libtorrent.

**Comment by arvidn** [comment]
Which version of libtorrent is this with? If not the latest, please try the latest version (or at least some 1.0.x version). I'm fairly certain this is no longer the case in master ("soon" to be 1.1). If you're up for it, please confirm that too.

There is one detail however. Empty directories have to be created at some point. If not on startup, when's a better time? In some sense, they are completely downloaded immediately, so it would make sense to create them immediately. Just like empty files are completely downloaded and created immediately.

**Comment by Misiek304** [comment]
Apparently this issue was resolved in the newest version of qBittorrent (I haven't updated yet because of the bugs). I guess they used the updated version of libtorrent too. 

Sorry for the misunderstanding. This ticket can be closed now. 
Thank you for your help.
