### ISSUE TITLE
How to build client_test using dynamic library?

### ISSUE THREAD

**Issue by thkvc** [arvidn/libtorrent#3468]
libtorrent version (or branch): 1.1.10
platform/architecture:x86
compiler and compiler version: vs2017

i build client_test by bjam and it link static library. 
i don't know how to link it with dynamic library.
please help.

**Comment by arvidn** [comment]
yeah, the default build is `link=static`. If you say `link=shared` it will link against libtorrent (and boost) libraries dynamically.

There's a list of the most common build features [here](https://libtorrent.org/building.html#building-with-bbv2).
