### ISSUE TITLE
qBittorrent crash on startup with SIGSEGV

### ISSUE THREAD

**Issue by wangqr** [arvidn/libtorrent#3471]
libtorrent version (or branch):
25a1f1299 on the RC_1_1 branch 

platform/architecture:
archlinux on x86-64

compiler and compiler version:
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 8.2.1 20180831 (GCC)
```

I'm trying to use the RC_1_1 branch with qbittorrent 4.1.3 release. qbittorrent crashes after startup. By capturing packets, I can see tracker announcement for the torrent sent before crash. Here is the error log from qbittorrent: https://gist.github.com/wangqr/e7166b4885c36396b909a626c2e4b9b7
qbittorrent does not crash with libtorrent-rasterbar 1.1.10 on the same machine.

Reference: original issue at qbittorrent/qBittorrent#9860

**Comment by wangqr** [comment]
Git bisect shows that 6df82a9ee64dd4f12395421ea52dea06b0e60dcd is the first bad commit
```git
6df82a9ee64dd4f12395421ea52dea06b0e60dcd is the first bad commit
commit 6df82a9ee64dd4f12395421ea52dea06b0e60dcd
Author: arvidn <arvid@libtorrent.org>
Date:   Mon Oct 8 01:53:39 2018 +0200

    fix cmake default built to enable logging

:100644 100644 0d0b4a2a30cc5ab4401865bb7bf7aa8d1fd3ee69 0ac9a159d10a6e41305b8ae1d6afb6c5892212d7 M      CMakeLists.txt
```

**Comment by aldenml** [comment]
I'm not familiar with this branch anymore, but if you want to make sure logging is the problem (or not), put `OFF` in that cmake option and test again. I'm linking the other commit I found in `RC_1_1` related to logging (in case logging is the problem), https://github.com/arvidn/libtorrent/commit/e1eb12e60fd7c8d05f9122e43a513bc05f38ce27

**Comment by wangqr** [comment]
Build with `-Dlogging=OFF` does fix this issue.

I have also generated [a backtrace using gdb](https://gist.github.com/wangqr/e134ea5fdaf51f2e242e3d2ad9e75483), which might be easier to read.

**Comment by Chocobo1** [comment]
@wangqr 
You might want to try with this line removed: `CONFIG += c++11` at https://github.com/qbittorrent/qBittorrent/pull/9835/files#diff-b820e0828543b1da522ff0ab3dac6c75L6
You'll need a full rebuild (of qbittorrent) after the removal.

**Comment by wangqr** [comment]
Thank you for the effort, but I cannot reproduce this issue now after a reboot. I'll try to reproduce it tomorrow. And if everything works fine then maybe I should close this issue.

**Comment by wangqr** [comment]
Well, it seems that everything is fine after the reboot. I have no idea what has changed after reboot...
