### ISSUE TITLE
Novice trying to build libtorrent

### ISSUE THREAD

**Issue by kurinoku** [arvidn/libtorrent#3481]
libtorrent version (or branch): libtorrent-rasterbar-1.2.0-rc

platform/architecture: Windows 10 x64

compiler and compiler version: g++.exe (Rev1, Built by MSYS2 project) 8.2.0

boost version : 1_66_0

So I've been battling with this for a couple of weeks now...
I don't know what to do... I'm using MSYS2 with mingw64, my goal is to build the python module.
I unpacked the boost libraries, executed bootstrap.sh through MSYS2 mingw64 console, let it run then in the same folder ./b2 and after a couple of minutes it said it had succesfully built. Idk what to do with that if the headers or compiled files have to be move out to another  folder, they have to be added to path, I really don't know...

I set the BOOST_PATH and BOOST_PATH_BUILD, the latter to /tools/build because there wasnt a build/v2
even though I didnt use the bjam from that folder... (I had a previous attempt using that bjam instead of the one in the boost folder as shown below)

I just executed bjam on the libtorrent and got the log below, might have done other things in the various attempts I did in the last weeks so I don't remember every detail... I'm sorry if this isn't the place for this but I can't seem to find the exact response that I need.

`../boost_1_66_0/b2.exe
Jamroot.jam:1: syntax error at EOF
CXXFLAGS =
LDFLAGS =
OS = NT
...patience...
...found 1054 targets...
...updating 2 targets...
gcc.link.dll bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\libtorrent.dll.a
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lboost_system
collect2.exe: error: ld returned 1 exit status

    "g++" -L"\usr\local\lib"  "-Wl,--out-implib,bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\libtorrent.dll.a" -o "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\libtorrent.dll" -Wl,-h -Wl,libtorrent.dll -shared -Wl,--start-group "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\alert.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\alert_manager.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\allocator.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\announce_entry.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\assert.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\bandwidth_limit.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\bandwidth_manager.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\bandwidth_queue_entry.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\bdecode.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\bitfield.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\block_cache.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\bloom_filter.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\chained_buffer.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\choker.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\close_reason.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\cpuid.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\crc32c.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\create_torrent.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\disk_buffer_holder.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\disk_buffer_pool.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\disk_io_job.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\disk_io_thread.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\disk_io_thread_pool.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\disk_job_fence.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\disk_job_pool.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\entry.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\error_code.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\file_storage.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\escape_string.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\string_util.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\file.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\path.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\fingerprint.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\gzip.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\hasher.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\hex.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\http_connection.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\http_stream.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\http_parser.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\identify_client.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\ip_filter.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\ip_notifier.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\ip_voter.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\listen_socket_handle.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\merkle.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\peer_connection.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\platform_util.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\bt_peer_connection.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\web_connection_base.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\web_peer_connection.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\http_seed_connection.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\peer_connection_handle.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\i2p_stream.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\instantiate_connection.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\lazy_bdecode.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\natpmp.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\packet_buffer.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\piece_picker.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\peer_list.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\proxy_base.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\puff.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\random.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\read_resume_data.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\write_resume_data.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\receive_buffer.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\resolve_links.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\session.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\session_handle.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\session_impl.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\session_call.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\session_udp_sockets.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\settings_pack.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\sha1_hash.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\socket_io.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\socket_type.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\socks5_stream.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\stat.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\storage.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\storage_piece_set.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\storage_utils.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\torrent.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\torrent_handle.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\torrent_info.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\torrent_peer.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\torrent_peer_allocator.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\torrent_status.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\time.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\tracker_manager.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\http_tracker_connection.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\udp_tracker_connection.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\timestamp_history.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\udp_socket.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\upnp.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\utf8.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\utp_socket_manager.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\utp_stream.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\file_pool.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\lsd.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\enum_net.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\broadcast_socket.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\magnet_uri.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\parse_url.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\ConvertUTF.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\xml_parse.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\version.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\peer_class.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\peer_class_set.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\part_file.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\stat_cache.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\request_blocks.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\session_stats.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\performance_counters.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\resolver.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\session_settings.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\proxy_settings.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\file_progress.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\ffs.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\add_torrent_params.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\peer_info.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\stack_allocator.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\generate_peer_id.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\ut_pex.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\ut_metadata.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\smart_ban.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\ed25519\src\add_scalar.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\ed25519\src\fe.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\ed25519\src\ge.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\ed25519\src\key_exchange.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\ed25519\src\keypair.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\ed25519\src\sc.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\ed25519\src\sign.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\ed25519\src\verify.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\hasher512.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\dht_settings.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\dht_state.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\dht_storage.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\dht_tracker.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\dos_blocker.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\ed25519.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\find_data.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\get_item.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\get_peers.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\item.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\msg.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\node.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\node_entry.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\node_id.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\put_data.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\refresh.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\routing_table.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\rpc_manager.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\sample_infohashes.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\kademlia\traversal_algorithm.o" "bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\src\pe_crypto.o"  -Wl,-Bstatic  -Wl,-Bdynamic -ladvapi32 -lboost_system -liphlpapi -lws2_32 -lwsock32 -Wl,--end-group -g -mthreads -Wl,-Bsymbolic

...failed gcc.link.dll bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\libtorrent.dll.a bin\gcc-mingw-gnu-8.2.0\debug\threading-multi\libtorrent.dll...
...failed updating 2 targets...`

**Comment by arvidn** [comment]
if you link dynamically against boost and the main libtorrent library, those libraries need to be available when loading the python module. on windows, the current directory is part of the path where DLLs are searched, so you can put them there. To collect all dependencies, you can build the target `stage_dependencies`
