### ISSUE TITLE
Input/output error when torrent contains files with a long filename

### ISSUE THREAD

**Issue by cmrd-senya** [arvidn/libtorrent#349]
Forked from https://github.com/qbittorrent/qBittorrent/issues/3293, I've been told there it is a libtorrent issue.

When I use qBittorrent with torrents that contain files with names longer than 255 bytes I get input/output error. The filename limitation is filesystem specific and is 256 bytes for ext4 and less for eCryptfs and dm-crypt. KTorrent handles this situation by cutting filename to 256 bytes. So I think libtorrent based software must behaves like this.

More information: https://github.com/qbittorrent/qBittorrent/issues/3293#issuecomment-167761622

**Comment by arvidn** [comment]
which version of libtorrent has this issue? Have you tried the latest version (or at least a 1.0.x version)?

**Comment by cmrd-senya** [comment]
I use qBittorrent from Ubuntu 14.04 repository, so it must be libtorrent-rasterbar7 0.16.13-1ubuntu2.1 package.

I suppose, that if you don't do explicit cut of the filename according to each filesystem's specific limit, then it doesn't work anyway.

**Comment by cmrd-senya** [comment]
Just tested version 1.0.7 from the ```ppa:qbittorrent-team/qbittorrent-stable```, behavior is the same.

**Comment by arvidn** [comment]
do you know what the filename length limit is on your system? I truncate it to the FILENAME_MAX constant

**Comment by cmrd-senya** [comment]
It's 4096 bytes, much bigger than the filesystem limit.

**Comment by arvidn** [comment]
interesting. I do have a unit test with a filename that's 300 characters long, to make sure it gets truncated. Do you think you could provide an example torrent file that causes this issue?

**Comment by cmrd-senya** [comment]
A peace of cake!
Here is a magnet link if you don't mind Russian:
magnet:?xt=urn:btih:B7904D28DD40AF69F1159D1245397A9F5305935A&tr=http%3A%2F%2Fbt.rutracker.cc%2Fann%3Fmagnet

**Comment by arvidn** [comment]
It's a bit tricky to solve this in the ideal way. The limit depends on the filesystem and really should be queried. However, the logic to sanitize and truncate filenames is run when loading the torrent (because we don't really want to run it more than once). However, when loading the torrent file, we don't know where we intend to save the file, so we can't query the filesystem.

Is it possible to query the home directory, and use that name size limit globally?

Another problem is that if you ever copy the files over to a different drive (with a different filesystem), and truncated files would possibly be differently truncated, and you would have to re-download them when trying to seed. For that reason, perhaps the best approach is to use a hard coded constant on linux. (but a lower one than FILENAME_MAX). Would using 255 as the limit be reasonable?

**Comment by arvidn** [comment]
There's an attempted fix here: https://github.com/arvidn/libtorrent/pull/358
(this is the release branch for 1.0.x)

**Comment by cmrd-senya** [comment]
Unfortunately, that won't solve the situation with encrypted filesystems like eCryptfs, because they have stricter limit than 255 bytes. However, I believe, this is how KTorrent works now. It is better than nothing.

Do you use some kind of CreateFile/OpenFile methods? Is it possible to move the truncation to that point. Like the pseudocode:
```
function StartTorrentDownload(torrent, target_dir) {
  foreach(filename in torrent) {
    CreateFile(filename, target_dir);
  }
}

function CreateFile(filename, target_dir) {
  limit = QueryFileSystemLimit();
  System.Create(target_dir + filename.truncate_to(limit));
}
```

So make the truncation as close as possible to file IO operations. At this point you'll know the target directory and can request an fs limit. If you move files inside a partition, then the limit is constant. And if you move the files accross different partitions, then it is actually a copy, and thus you'll anyway do it one by one, so renaming is possible. I know it is not that simple as I describe, however, I beleive, still implementable.

**Comment by arvidn** [comment]
The problems with that are:

1. the truncation check needs to be done many more times, and can potentially be expensive (especially given that most filenames probably won't be too long)
2. If you copy your download from one drive to another and attempt to keep seeding, the truncation behavior may have changed and the files you have will be different than what the bittorrent client expects (i.e. the filename transformations will be incompatible across different drives. for similar issues, see [1])

[1] http://blog.libtorrent.org/2014/12/filenames/
