### ISSUE TITLE
Proposal: dispose of .unwanted folders completely

### ISSUE THREAD

**Issue by mzso** [arvidn/libtorrent#3501]
Hi!

As a QBittorrent user I find .unwanted folders to be quite a nuisance. (And I understand this to be libtorrent's realm)

- I get files moved in the .unwanted folder whenever something is deselected in the client.
- I don't know why, but I noticed multiple times empty folders with empty .unwanted folders within them created, for torrent folders that were always fully deselected within the client.
- These files in .unwanted, apart from being an eyesore a troublesome in other ways. They're files that I do not want, yet they're interfere whenever I load files resursively from the torrent's folder with some app. It's even worse if partially downloaded junk files are loaded by an app. (Most typically I get undesired files loaded by my media player, which gets hung a lot when they're partial files.)

What can be done instead:
- In my opinion what most obviously (and I suspect most simply) could be done is to append these files/folders into the partfile of the torrent.
- Alternatively, or besides this the files could be moved to a dedicated location in the drive's root. Which should be just as fast as simple (filesystem permissions permitting) as moving to the .unwanted folder.

**Comment by thalieht** [comment]
.unwanted folders have nothing to do with libtorrent. It's purely a qBittorrent functionality.

**Comment by arvidn** [comment]
right. qbt is responsible for all logic regarding `.unwanted`. It could stick those files anywhere it likes.
new in libtorrent 1.1 is support for partfiles, where libtorrent is responsible for the logic.

**Comment by mzso** [comment]
Sorry...
