### ISSUE TITLE
Question about using Travis Windows and AppVeyor Linux

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#3511]
libtorrent version: `master`

I wonder if there is a any build combination that warrants the use of these new images. Or rearrange the current jobs to speed up the builds.

**Comment by arvidn** [comment]
I didn't know travis supported windows now. Given how slow the windows machines are on appveyor, it probably makes sense to move some of the builds over to travis

**Comment by cas--** [comment]
That is interesting, although I had a quick look and seems would have to manually install a lot of packages, compared to e.g. Appveyor has pre-installed boost, openssl and pythons

**Comment by aldenml** [comment]
agree, I tried it and it requires a lot of work to make it work, maybe in a year or so

**Comment by filips123** [comment]
GitHub now also provides GitHub Actions which support Windows Server 2019, Ubuntu 18.04, Ubuntu 16.04 and macOS Catalina.
