### ISSUE TITLE
Python 3.x builds with Py_LIMITED_API

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#3515]
To ease maintaining and distributing the Python bindings I would suggest looking into being able to build 3.x bindings using the Py_LIMITED_API: https://docs.python.org/3/c-api/stable.html

I have done very little research on this but do you think this is possible @arvidn?

**Comment by arvidn** [comment]
The only hurdle I can imagine would be if boost.python use calls not part of this subset

**Comment by cas--** [comment]
Hmm so it seems boost.python has the same issues as [pybind11](https://github.com/pybind/pybind11/issues/1755) with usage of [PyTuple_SET_ITEM](https://github.com/boostorg/python/search?q=PyTuple_SET_ITEM&unscoped_q=PyTuple_SET_ITEM)

I shall close this for now.
