### ISSUE TITLE
web seed issue

### ISSUE THREAD

**Issue by otristan** [arvidn/libtorrent#3519]
Using libtorrent trunk version on Windows with VS2017

Looks like there is an issue with web seed when there is only one file in a single folder.
line 1380 of torrent_info.cpp, it's detected using 

`if (m_flags & multifile)`

while line 92 of web_peer_connection.cpp
`bool const single_file_request = t->torrent_file().num_files() == 1;`
resulting in some mismatch

maybe it should use the same way ?
adding is_multifile to torrentinfo and using it here fixes my issue.

Thanks !

**Comment by otristan** [comment]
You can try this torrent file to reproduce the issue
`http://files.uvi.net/SC33-Mello/Mello_1.2.4.torrent`

**Comment by arvidn** [comment]
is this not an issue in `RC_1_1`?

**Comment by arvidn** [comment]
could you describe the symptom(s) you see?
It sounds like perhaps the HTTP request you get is incorrect, is that right?

**Comment by otristan** [comment]
The issue is that the code line 92 of web_peer_connection.cpp detect the case that this is not a multifile
because there is only one file, but still the web seed got a trailing slash because it's actually a folder.

So the code line 105 strikes
`if (m_path[m_path.size() - 1] == '/')`
which results in adding the torrent name to the path
`m_path += escape_string(t->torrent_file().name());`
except this path do not exists on the server because the torrent source is actually the folder

Hope this clarify things.

I have fixed the issue on my end by using directly the file in the folder for the torrent and the web seed, but the issue remains if you have only one file in a single folder.

**Comment by arvidn** [comment]
I'm under the impression that logic in `torrent_info` (specifically the part that looks at `m_flags & multifile`) will correct any missing trailing slashes in the web seed URLs.

So, presumably the calls to `ensure_trailing_slash()` are unnecessary in `web_peer_connection.cpp`.

But that doesn't seem to be causing the problem you see though, right?

You have a torrent with a single file, but you say "in a single folder". Does that mean the torrent has a "name" field containing the directory name, slash, filename? (which is not the correct way of representing directories in torrent files, and I don't believe libtorrent will). Or does the torrent file have a "files" field containing a list of files, with only one file in it?

I assume it's the latter. If so, your torrent *is* a multi file-torrent. It just happens to contain 1 file.

My reading of the [specification](http://getright.com/seedtorrent.html) is that any kind of torrent (single-file or multi-file) can have a URL end with a slash, in which case the filename is supposed to be appended.

However, multi-file torrents, the *full path* within the torrent is *always* appended to the URL.

It sounds like the URL your "url-list" is the full path to the file on the web server. As far as I can tell, it's *supposed* to be pointing to the root, where the directory in the torrent is, the name of the torrent.

**Comment by arvidn** [comment]
Looking a bit more at this, libtorrent's implementation actually considers your torrent a single-file torrent in the sense that you can choose to specify a URL that ends with a '/' or a full URL pointing directly to the file.

I don't see how the logic is wrong here. I'd be happy to take a look at your .torrent file if you can share it. In case I'm misunderstanding something.

**Comment by otristan** [comment]
Here it is

http://files.uvi.net/SC33-Mello/Mello_X.X.X.torrent
(X.X.X because t's a dummy version for testing purpose)

Maybe it's the torrent that is malformed though

Thanks !

**Comment by arvidn** [comment]
yes, the torrent is malformed. The [original specification](http://getright.com/seedtorrent.html) states:

> For Multi-File torrents, this gets a bit more interesting. Normally, BitTorrent clients use the "name" from the .torrent info section to make a folder, then use the "path/file" items from the info section within that folder. For the case of Multi-File torrents, the 'url-list' should be a root folder where a client could add the same "name" and "path/file" to create the URL for the request. 

The specification was formally adopted in [BEP 19](http://bittorrent.org/beps/bep_0019.html), which phrases it slightly differently:

> Multi-File Torrents
> BitTorrent clients normally use the "name" from the torrent info section to make a folder, then use the "path/file" items from the info section within that folder. For the case of Multi-File torrents, the "url-list" must be a root folder where a client could add the same "name" and "path/file" to create the URL for the request.
> 
> For example:
> ... 8:url-list22:http://mirror.com/pub/ 4:infod5:filesld6:lengthi949e4:pathl10:Readme.txte e4:name7:michael
> 
> A client would use all that to build a url: http://mirror.com/pub/michael/Readme.txt

I suppose the term "multi-file torrent" may not be very clearly defined. My reading of the bittorrent specification through ([BEP 3](http://bittorrent.org/beps/bep_0003.html)) is that multi-file torrents refers to the "extended" form, where you specify a "files" key.

So, I think we're in implementation defined territory with regards to how clients behave.

That said, libtorrent doesn't behave as I expected (and expressed in my previous post). As you point out, the treatment of the web seeds differes between the `torrent` and `web_peer_connection`, which causes some discrepancy. Specifically in the case of trying to interpret malformed torrents. Part of me is tempted to just fail with torrents like these, as adding heuristics on how to interpret them prevents torrent makers from realising their mistakes (a bit how, in the late 90's, IE took liberties in interpreting malformed HTML, causing web sites to not work in other browsers).

I will look at tweaking the heuristics a bit, specifically, in this case the URL ends with a perfect match of the path and filename of the single file in the torrent, which should make it trivial to interpret it as a URL to that file, and not append a "/".

There one more egregious error in that torrent though. The web seed URL is *also* added under the "httpseeds" key, which is a [BEP 19](http://bittorrent.org/beps/bep_0019.html) web seed. Those kinds of web seeds require actual programs to run on the web server to implement a bittorrent-like protocol over HTTP.

I would encourage you to report this issue to the creator of the torrent, or the author of the software used to create the torrent.

**Comment by otristan** [comment]
Fair enough. Not sure indeed what is the best.
In the meantime we have moved to using directly the file and not the folder, so I'm good in any case.

Thanks  !

**Comment by arvidn** [comment]
addressed here: https://github.com/arvidn/libtorrent/pull/3533
