### ISSUE TITLE
Errant ._Changelog file in 1.1.11 release tarball 

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#3523]
![shutter_selection_005](https://user-images.githubusercontent.com/606038/49507949-773cba80-f879-11e8-8c5f-ee0487815d16.png)

**Comment by arvidn** [comment]
interesting. I thought the autoconf/automake tarballs only included files specifically in the dependency list.

**Comment by cas--** [comment]
Fixed in later releases
