### ISSUE TITLE
web seed wrong assert

### ISSUE THREAD

**Issue by otristan** [arvidn/libtorrent#3527]
using trunk version on Windows with VS2017, I hit
assert line 119 of http_seed_connection.cpp

`TORRENT_ASSERT_VAL(receive_buffer_size <= t->block_size(), receive_buffer_size);`

where

receive_buffer_size is equal to 17040
and
 t->block_size() is equal to  16384

Probably related to the TODO line 117

appears to work fine if I remove the assert though

Thanks !

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/3530
