### ISSUE TITLE
CMake issue

### ISSUE THREAD

**Issue by otristan** [arvidn/libtorrent#3538]
libtorrent CMake always check for OpenSSL and use it if found even if encryption option is set to off.

It add an unnecessary dependency if we don't care about encryption and add build issue in my case.
(OpenSSL installed but with not the right OS X deployment target)

It would only require an if (encryption) line 622 of the main CMakeLists.txt around 
```
find_public_dependency(OpenSSL)
set_package_properties(OpenSSL
	PROPERTIES
		URL "https://www.openssl.org/"
		DESCRIPTION "Full-strength general purpose cryptography library"
		TYPE RECOMMENDED
		PURPOSE "Provides HTTPS support to libtorrent"
)
```

Thanks !

**Comment by arvidn** [comment]
@otristan is this `master` or `RC_1_1`?

@zeule is this intended?

**Comment by otristan** [comment]
master

**Comment by zeule** [comment]
@otristan: you can disable finding a package passing `-DMAKE_DISABLE_FIND_PACKAGE_<PackageName>=True`

@arvidn, I can't remember exactly, but at some point when refactoring the CMake build script I was told OpenSSL (or LibGCrypt) are used not only for what the `encryption` option controls.

**Comment by aldenml** [comment]
for what I see and iirc, that`encryption` option is only for that old based RC4 obfuscation. If you disable `openssl` link (with `cmake`) you will not have `https`, optimized hashing functions, and torrents over ssl. But I don't see any explicit option to control `ssl` and `crypto` like in `Jamfile`, I guess `-DCMAKE_DISABLE_FIND_PACKAGE_OpenSSL` do the trick.

**Comment by otristan** [comment]
Fine with that then.

Thanks !
