### ISSUE TITLE
priority_queue_insert(...) called on an already queued it

### ISSUE THREAD

**Issue by vsystech** [arvidn/libtorrent#3539]
Hello, i have a following error when running rtorrent client. 

Caught internal_error: priority_queue_insert(...) called on an already queued it                                                                                        em. 
/usr/lib/libtorrent.so.20(_ZN7torrent14internal_error10initializeERKNSt7__cxx111                                                                                        2basic_stringIcSt11char_traitsIcESaIcEEE+0x214) [0x7f1f74c74324]
rtorrent(_ZN7torrent14internal_errorC1EPKc+0xa0) [0x565035b4c510]
/usr/lib/libtorrent.so.20(+0xf9788) [0x7f1f74d3c788]
/usr/lib/libtorrent.so.20(+0x2df9d) [0x7f1f74c70f9d]
/usr/lib/libtorrent.so.20(+0x2e780) [0x7f1f74c71780]
/usr/lib/libtorrent.so.20(+0xf7a77) [0x7f1f74d3aa77]
/usr/lib/libtorrent.so.20(+0xfa035) [0x7f1f74d3d035]
/usr/lib/libtorrent.so.20(_ZN7torrent11TrackerList10send_stateEPNS_7TrackerEi+0x                                                                                        74) [0x7f1f74c92d14]
/usr/lib/libtorrent.so.20(_ZN7torrent17TrackerController16send_start_eventEv+0xe                                                                                        3) [0x7f1f74c91883]
rtorrent(+0xcf2c6) [0x565035bb82c6]
rtorrent(+0xd4a67) [0x565035bbda67]
/usr/lib/libtorrent.so.20(+0xc6bfe) [0x7f1f74d09bfe]
/usr/lib/libtorrent.so.20(+0x2cffe) [0x7f1f74c6fffe]
/usr/lib/libtorrent.so.20(_ZN7torrent11thread_base10event_loopEPS0_+0x180) [0x7f                                                                                        1f74cd1000]
rtorrent(+0x1efa3) [0x565035b07fa3]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7f1f733b12e1]
rtorrent(+0x2052a) [0x565035b0952a]

any one can help me ?

**Comment by ssiloti** [comment]
rtorrent uses libtorrent-rakshasa. See https://github.com/rakshasa/libtorrent
