### ISSUE TITLE
lt::session into singletone class

### ISSUE THREAD

**Issue by Daimon04** [arvidn/libtorrent#3541]
libtorrent version: 1.1.11
platform/architecture: Windows
compiler and compiler version: VS 2017

I have singletone class

Test.h

```
#ifndef  TEST_H
#define TEST_H
#include <libtorrent/session>

class Test
{
public:
   static Test& instance();
   Test(const Test&) = delete;
   Test(Test&&) = delete;
   Test& operator = (const Test&) = delete;
   Test& operator = (Test&&) = delete;
   void start();
   void stop();
private:
   lt::session session_;
   Test() = default;
   ~Test() = default;
}

#endif;  //TEST_H
```

Test.cpp

```
#include <libtorrent/session.hpp>
#include "Test.h"

Test& Test::instance()
{
   static Test test;
   return test;
}

void Test::start()
{
...
}

void Test::stop()
{
...
}

```

I have class wrapper

Test2.h

```
#ifndef   TEST2_H
#define  TEST2_H
class Test2
{
public:
   void start();
   void stop();
}
#endif;  //TEST2_H
```

Test2.cpp

```
#include "Test2.h
#include "Test.h"

void Test2::start()
{
   Test &test = Test::instance();
   test.start();
}

void Test2::stop()
{
   Test &test = Test::instance();
   test.stop();
}
```

main function:

main.cpp

```
int main()
{
   Test2 test2;
   test2.start();
   test2.stop();
   return 0;
}
```

at the end of the function main, when execution line "return 0;" my program hangs and does not end.

if I change the code a little and change line "lt::session session_;" to "lt::session *session_;"
add line to methods

```
void Test::start()
{
   session_ = new lt::session();
}

void Test::stop()
{
   delete session_;
}
```

then this problem is solved

but if I don't change those methods and add those lines into constructor and destructor of class Test, then the problem is again

```
Test::Test()
{
   session_ = new lt::session();
}
Test::~Test()
{
   delete session_;
}
```

**Comment by arvidn** [comment]
well, I can't tell you exactly why, but I'm not too surprised things break when trying to destruct the session object as a global destructor. It's quite complex and it very likely depend on other singletons or other `atexit()` things not having happened yet.

I wouldn't recommend you keep the session as a global variable, but in particular, I would recommend initializing it with your desired settings up-front, and destruct it before `main()` returns.

Both the constructor and the destructor performs a fair amount of work, if the first thing you do after constructing it is to change its configuration, you'll likely have to perform a lot of that work again. Things like closing and re-opening sockets, bootstrapping the DHT, announce on local service discovery, etc.
