### ISSUE TITLE
Unable to skip checking (seed_mode=true and auto_managed=false)

### ISSUE THREAD

**Issue by ngjermundshaug** [arvidn/libtorrent#3544]
In previous versions (several years back) it was possible to set **seed_mode=true** and **auto_managed=false** - in order to start seeding a torrent without rechecking (or using fast resume). When running the code below - the torrent now enters the stopped state. Calling resume() starts checking. 

```
lt::add_torrent_params apr;
apr.save_path = pathToTransferFolder;
apr.flags |= lt::add_torrent_params::flag_seed_mode; //ON
apr.flags &= ~lt::add_torrent_params::flag_auto_managed; //OFF
apr.ti = std::make_shared<lt::torrent_info>(pathToTorrentFile);
lt::torrent_handle newHandle =s->add_torrent(apr);
```

This code is running on a seed box'es with 50-150TB of data - so re-checking every time is not desired.
Is there another way I can skip checking that works?

libtorrent version (or branch): 1.2.0-RC2 - win64.

**Comment by arvidn** [comment]
seed mode will still check the pieces, just lazily. Is it possible one such check fails?
Do you get any interesting alerts?

**Comment by ngjermundshaug** [comment]
When using code from the **utp-packetloss** branch - torrents are seedeed instantly when I set  **seed_mode=true** and **auto_managed=false**. Will investigate more regd. the alerts for RC2

**Comment by mkatsevVR** [comment]
also running into this issue, seed_mode flag is not working on 1.2 when set directly on the add_torrent_params without loading persisted resume data
relevant logs:
```
torrent_log: torrent_name: creating torrent: torrent_name max-uploads: 16777215 max-connections: 16777215 upload-limit: -1 download-limit: -1 flags: seed-mode apply-ip-filter update-subscribe  save-path: /tmp/torrent_copy_test.vXpkIX/src
torrent_log: torrent_name: fastresume data rejected: ret: 2 (0) Success
state_changed: torrent_name: state changed to: checking
```
I suspect [this line](https://github.com/arvidn/libtorrent/blob/libtorrent_1_2_0/src/disk_io_thread.cpp#L2538) is the problem, since it will fail the check if `have_pieces` are empty, which is normal in the seed mode

**Comment by mkatsevVR** [comment]
also in torrent::on_resume_data_checked, if should_start_full_check is true, m_seed_mode doesn't actually prevent the switch to the checking mode, afaict

**Comment by arvidn** [comment]
@mkatsevVR the problem is that the resume data was rejected. Do you know why? If it is accepted it will go straight to seeding (and verify the hashes lazily).

The line you point at is fine, `verify_resume_data()` doesn't have to be run.

as far as I can tell, it's `initialize()` that fails for you. You can get the full error message by printing `fastresume_rejected_alert::message()`.

**Comment by arvidn** [comment]
regarding `m_should_start_full_check`, that's specifically to pick up on torrents that are part-way checked. so, *only* if you set `have_pieces` to a vector that has a smaller size than the number of pieces will this logic kick in.

Are you setting `have_pieces` to a state to indicate that you've started checking, but not completed it?

**Comment by arvidn** [comment]
I started a small patch here: https://github.com/arvidn/libtorrent/pull/3641

How do those tests differ from your case?

**Comment by mkatsevVR** [comment]
create a new add_torrent_params, enable seed_mode but don't change have_pieces (leave it empty by default) and you get the result as in my logs above

**Comment by arvidn** [comment]
> create a new add_torrent_params, don't use read_resume_data, enable seed_mode, don't change have_pieces (leave it empty by default) and you get the result as in my logs above

`test_resume.cpp.seed_mode_preserve` does that, and it doesn't end up checking the files.

> because have_pieces is empty, which makes the test in line 2538 return true

which is correct, and doesn't (by itself) cause the resume data to be rejected. For example, the test I mentioned above also has an empty `have_pieces`.

All it does is to skip running `verify_resume_data()` and skip straight to `initialize()` followed by a `return no_error`. (unless initialization fails, which is my theory currently).

Would you mind printing the error you get?

**Comment by mkatsevVR** [comment]
> `test_resume.cpp.seed_mode_preserve` does that, and it doesn't end up checking the files.

no, it creates add_torrent_params via read_resume_data: https://github.com/arvidn/libtorrent/blob/bba3f206c79321fefc285cafd3e00b7844596aed/test/test_resume.cpp#L1010

> All it does is to skip running `verify_resume_data()` and skip straight to `initialize()` followed by a `return no_error`. (unless initialization fails, which is my theory currently).

if the condition in line 2538 is true, it goes to line 2547 which is also true, then line 2552 which is false, and finally returns need_full_check in line 2557

> Would you mind printing the error you get?

The fastresume_rejected_alert is not being sent.

**Comment by mkatsevVR** [comment]
here: https://github.com/mkatsevVR/libtorrent/commit/36f4c2097440c0c0df216ecc84078d50a6cb4c3d

**Comment by arvidn** [comment]
I see, the difference is that you actually have files, the test I was looking at doesn't

**Comment by arvidn** [comment]
I've updated https://github.com/arvidn/libtorrent/pull/3641 with what I believe is a fix. I will add a test too

**Comment by arvidn** [comment]
@mkatsevVR thanks for the help to understand and diagnose this. I'm pretty confident my patch fixes this now. Please give it a try and let me know!

https://github.com/arvidn/libtorrent/pull/3641

**Comment by arvidn** [comment]
@ngjermundshaug could you test https://github.com/arvidn/libtorrent/pull/3641 and let me know if it fixes the problem for you?

**Comment by mkatsevVR** [comment]
did the actual fix get lost in the rebase somewhere? i only see the logging and test changes in the PR

**Comment by arvidn** [comment]
damn! you're right. Something must have gone wrong in my git patch handling :(

**Comment by arvidn** [comment]
fixed!

**Comment by mkatsevVR** [comment]
I don't have a good way to test this with my application right now, but the fix seems reasonable and the new tests pass. For the sake of completeness might still want to add a separate test that doesn't rely on read_resume_data.
