### ISSUE TITLE
libtorrent as a lib for p2p apps

### ISSUE THREAD

**Issue by klueq** [arvidn/libtorrent#3547]
Can libtorrent be used as a library to create an overlay network of nodes interested in topic `foo/1.2.3` and let them exchange with arbitrary messages? Number of nodes: ~1M, nessage size: ~1 KB, number of messages: ~10 per day.

For example, I want to make a distributed p2p version of a books catalog. The catalog has a well-known name, e.g. `books/scifi`. Nodes use this name to discover other nodes connected to this overlay network. Once connected, they download the list of book hashes from a peer. If someone wants to add a book, they send its hash to a few peers, those add it to the local storage and re-transmit to other peers. An important property of this system is that all the nodes are equal: there is no admin who has special rights.

API needed for this:
- `join("books/scifi")` finds a few peers in this overlay network
- `peers("books/scifi")` returns the list of online peers we're currently connected to
- `send("books/scifi", peerId, "howdy, I've got a new book: 1efcc45")` sends a UDP message to the given peer
- `listen("books/scifi", callback)` gets messages sent by other peers with the `send()` API

Peer discovery here naturally maps to the DHT discovery process for a known infohash. Here we put `books/scifi` and other metadata into a file and use its infohash to discover peers. It also seems obvious that the second part - p2p messaging - can be done because libtorrent definitely sends those p2p messages to run DHT. The only question is whether this capability can be exposed as a reasonable API to an app that uses libtorrent.

Thoughts?

**Comment by arvidn** [comment]
It doesn't seem like a perfect fit, but I think libtorrent could be shoehorned into a use case like this.

One way of doing it (which is a bit heavier weight than what you describe) is that each topic could be a torrent (but without any content). The swarm is formed only to gossip extension messages among the peers. This would require a libtorrent plugin that can send and receive such extension messages.

**Comment by TheBlue24** [comment]
It's possible to create a P2P file transferring application using LibTorrent?
