### ISSUE TITLE
The master branch is 1.2 ?

### ISSUE THREAD

**Issue by Rootax** [arvidn/libtorrent#3556]
Hello,

Stupid thing, but it seems that the master is 1.2 right ? So not compatible with some bittorrent client yet.

Would it be possible to release a libtorrent-1.1.12 version, with the latest fixes ? I believe the improvement in cache flushing, and in ack handling is worthy of a new release ? Of course, I can take libtorrent-1.1.11 version, and then change the files impacted by the patches, but it's not very efficient...

Thx.

**Comment by arvidn** [comment]
yes, I intend to make another 1.1.x release because of the issues found in there lately. I'm also interested in improving the backwards compatibility of master (i.e. 1.2), if you have any specific errors you could bring up.

**Comment by Rootax** [comment]
Thx a lot.

It's rather generics error in the session.ccp, like a lot of "can't convert libtorrent::string_view' in 'const std::string'", and the compiler crash with the generic error 2 in the end.

**Comment by arvidn** [comment]
1.2 is now in the `RC_1_2` branch
