### ISSUE TITLE
1.2.0 make error

### ISSUE THREAD

**Issue by E4ck** [arvidn/libtorrent#3557]
libtorrent version: 1.2.0

platform/architecture: ubuntu 16.04

gcc: 5.4.0

Boots path: 
export LDFLAGS=-L/usr/local/lib
export CXXFLAGS=-I/usr/local/include

error:
In file included from web_connection_base.cpp:38:
In file included from ../include/libtorrent/web_connection_base.hpp:43:
In file included from ../include/libtorrent/torrent.hpp:48:
In file included from ../include/libtorrent/torrent_info.hpp:52:
../include/libtorrent/file_storage.hpp:64:15: error: exception specification of
      explicitly defaulted move assignment operator does not match the
      calculated one
                file_entry& operator=(file_entry&&) & noexcept = default;
                            ^
1 warning and 1 error generated.
Makefile:1105: recipe for target 'libtorrent_rasterbar_la-web_connection_base.lo' failed
make[1]: *** [libtorrent_rasterbar_la-web_connection_base.lo] Error 1
make[1]: Leaving directory '/home/eack/libtorrent/src'
Makefile:626: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

I ran ./configure successfully, but I ran make error

**Comment by E4ck** [comment]
"Building with BBv2、Build with autotools"
When building libtorrent, is this two optional options, or both?

**Comment by E4ck** [comment]
Thank you for your reply, I solved this problem, I think it is caused by the lack of libstdc ++

**Comment by arvidn** [comment]
yes, if any member of `file_entry` is not no-throw move-assignable, you'll get this message. so there may be standard types in there that some versions of standard libraries have as throwing move assignment (which technically isn't a bug in the compiler, but in the standard library)
