### ISSUE TITLE
https - no supported protocol

### ISSUE THREAD

**Issue by geforegtx** [arvidn/libtorrent#3559]
I was able to compile latest stable version - libtorrent-1.1.11 on CentOS Linux release 7.6.1810 (Core) x64, but HTTPS dont work. Compiler: gcc-4.8.5-36. On deluge there is information no supported protocol. HTTP work. On CentOS i installed openssl-devel (counterpart of libssl on ubuntu?). After startup deluged i got following errors:

--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 134, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/deluge/core/preferencesmanager.py", line 186, in start
    self._on_set_encryption)
  File "/usr/lib/python2.7/site-packages/deluge/config.py", line 314, in register_set_function
    function(key, self.__config[key])
  File "/usr/lib/python2.7/site-packages/deluge/core/preferencesmanager.py", line 364, in _on_set_encryption
    self.session.set_pe_settings(pe_settings)
exceptions.AttributeError: 'session' object has no attribute 'set_pe_settings'
[ERROR   ] 11:02:46 component:118 [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'session' object has no attribute 'set_pe_settings'
/usr/lib/python2.7/site-packages/deluge/main.py:241:start_daemon
/usr/lib/python2.7/site-packages/deluge/core/daemon.py:178:__init__
/usr/lib/python2.7/site-packages/deluge/component.py:296:start
/usr/lib/python2.7/site-packages/deluge/component.py:124:_component_start
--- <exception caught here> ---
/usr/lib64/python2.7/site-packages/twisted/internet/defer.py:134:maybeDeferred
/usr/lib/python2.7/site-packages/deluge/core/preferencesmanager.py:186:start
/usr/lib/python2.7/site-packages/deluge/config.py:314:register_set_function
/usr/lib/python2.7/site-packages/deluge/core/preferencesmanager.py:364:_on_set_encryption
]
Cant repair this issue for myself, so i was wonder if anybody could point me out to solve this issue. Client deluge was installed from nux-dextop repo.

**Comment by arvidn** [comment]
you have to enable openssl support when building.

```
b2 crypto=openssl
```

**Comment by geforegtx** [comment]
dont know how to install/use b2 on CentOS. Or i can just add to command: ./configure --with-boost-libdir=/usr/lib64 --enable-python-binding b2 crypto=openssl?

**Comment by arvidn** [comment]
you can specify `--enable-encryption` to `./configure`

**Comment by geforegtx** [comment]
./configure --with-boost-libdir=/usr/lib64 --enable-python-binding --enable-encryption that didnt help, still cant get to work https in deluge....

**Comment by arvidn** [comment]
did `./configure` print that it was looking for openssl and that it found it?
did `make` end up linking against `libcrypto` and `libssl`?
are you sure you're using the newly built library?

**Comment by geforegtx** [comment]
cd libtorrent-rasterbar-1.1.11
./configure --with-boost-libdir=/usr/lib64 --enable-python-binding --enable-encryption
configure: encryption support: now checking for the OpenSSL library...
checking whether compiling and linking against OpenSSL works... yes
OpenSSL library:
  OpenSSL Libs:         -lssl -lcrypto  
  OpenSSL LDFlags:       
  OpenSSL Includes:

**Comment by arvidn** [comment]
could you specify exactly which alert you get? or at least the message it prints?
is it a tracker or a web seed that's using HTTPS?
would you be able to share the .torrent file you're testing with?

**Comment by geforegtx** [comment]
Cant share torrent file, coz it comes from private trackers. Its tracker that are using https.  I get information about unsuportted protocol. Deluge cant connect to tracker, so it cant download single megabyte. On torrents that connect to tracker by http protocol all are ok. Also cant use self signed cert. to control deluge from web interface. On ubuntu i dont have that kind of issue. I install openssl-devel on centos but cant compile libtorrent with https support.

**Comment by aldenml** [comment]
@geforegtx can you provide which port are you listen on? I was looking at a similar problem here https://github.com/aldenml/libtorrent4j/issues/23 and the result was that the default port `6881` for some unknown reason was the problem. Solution was setting it to a random OS selected listen port.

**Comment by geforegtx** [comment]
ok just figure out that i need to delete old build of libtorrent, so command rm /usr/local/lib64/python2.7/site-packages/*, fix my issue and now i can build libtorrent to support https
