### ISSUE TITLE
Local IPv4/6 is reported to private trackers

### ISSUE THREAD

**Issue by airium** [arvidn/libtorrent#3571]
This is a bug further exposed after the introduce of `&ipv4=` parameter to private trackers, as described by <https://github.com/qbittorrent/qBittorrent/issues/10051>. I have confirmed it on both Windows and Linux.

If an IPv4-NAT end user selects a particular interface, then this interface's local IPv4 may be set to `m_ipv4_interface` at here:
	
<https://github.com/arvidn/libtorrent/blob/e53bc71f63fabfd7d0cf502b4534f96e3d582d00/src/session_impl.cpp#L1993-L1999>

This leads to `false` for `want_v4` and `want_v6` and skips the followed setting part traversing all IPv4/6 interfaces. Finally, either `m_ipv4_interface` or `m_ipv6_interface` may hold a local IP address. Since there is no more check in torrent.cpp, the announce message to private tracker will include this invalid local IP and raise tracker's error report, like this:

![4](https://user-images.githubusercontent.com/38249940/50819605-7cec5b00-1365-11e9-99d7-98733e60dd31.jpg)
where the `&ipv6=` part is a link-local address.

A simple fix is to add a sanity check in torrent.cpp, as <https://github.com/airium/libtorrent/commit/831901a61cfec4f45559e644e60715db768254e8>. I can PR that if you think it's ok. But I am wondering how can it be fixed just in the above shown code, which may be a better fix.

**Comment by arvidn** [comment]
I think `m_ipv4_interface` and `m_ipv6_interface` are not supposed to contain local IPs. would it be practical to add the check earlier, when those fields are assigned?

**Comment by airium** [comment]
I created another fix <https://github.com/airium/libtorrent/commit/b7efb92894b43240d67cfa0e5283ec8829ac2f77>. This one places the check when `m_ipv4_interface` and `m_ipv6_interface` are firstly assigned. Does it implement "add the check earlier" correctly?

**Comment by arvidn** [comment]
ok, I had some time to look at this. At a closer look it seems I was wrong. those members *are* expected to contain local IPs as well. Perhaps their most important use is to announce to trackers over both IPv4 and IPv6.

Would you mind creating a PR with your first patch?

**Comment by airium** [comment]
Thanks. I have created it.

**Comment by Rootax** [comment]
Why not use the second patch instead ? https://github.com/airium/libtorrent/commit/b7efb92894b43240d67cfa0e5283ec8829ac2f77

**Comment by arvidn** [comment]
@Rootax those members are not only used for posting to the tracker, they are also used by the logic that announces twice (once binding to an IPv4 socket and once binding to an IPv6 socket). And in that case it's not relevant whether the IP is local or not. In fact, it hast to be and IP that can be bound to. All of this code is questionable and doesn't *really* do the right thing, but it has been overhauled in master (1.2)
