### ISSUE TITLE
CAS issue for DHT 

### ISSUE THREAD

**Issue by tatashina** [arvidn/libtorrent#3578]
Hi guys,

It is not a bug exactly, just wonder, if that even possible to receive an error in case of updating the mutable item with the lower seq number? It seems like it should be an [error 302](https://www.libtorrent.org/dht_store.html) when you try to modify mutable item with lower (or equal) seq, but there are no such alerts of anything.

An error 301 is good too for my purposes, but I really do not understand how to enable CAS for **session.dht_put_item**. Is it possible? 

I have found only one mention of this error in your github: https://github.com/arvidn/libtorrent/search?q=302&unscoped_q=302 but as far as I understood it is a low-level solution and does not appropriate for functions like dht_put_item.

Will be glad for any help.

Thank you in advance!

**Comment by arvidn** [comment]
are you suggesting that libtorrent's DHT implementation does not respond with 302 error on "CAS retry"?
or are you asking if there is a way for the client of the libtorrent library to be notified specifically of the 302 error?

**Comment by arvidn** [comment]
this is where the 302 response is sent: https://github.com/arvidn/libtorrent/blob/master/src/kademlia/node.cpp#L1087

**Comment by tatashina** [comment]
Hi, thank you for your reply! I was able to find the example you stated and I see, that response is sent there. Unfortunately, I have no idea how to obtain it. In the implementations of session::dht_put_item there is only one, that accepts lambda-function and it accepts only specific arguments, amongst which there is no "cas". If I'm mistaken, please correct me.

**Comment by arvidn** [comment]
that's right, the only way you can tell that you got a CAS failure is that your callback will be called more than once.

What are you trying to achieve by explicitly being notified of the 302 error message?

**Comment by tatashina** [comment]
There are my steps:
1. First, I successfully save some arbitrary data in DHT using existing dht_put_item for mutable. Wait and receive then dht_put_alert it's absolutely ok.
2. Then I intentionally call this function (dht_put_item) again with different value, but with the same seq, public and private key (I want to catch any error just to be sure it works).
3. After some time I receive the common alert which coming after successfull (or not) mutable item update - dht_put_alert and nothing more. BTW I am checking only message from this alert (which is absolutely perfect) maybe that's my bad?

So there are my questions:
1. Should it be any error for such cases? I mean when I try to update mutable with the same sequence number. For now I can't see any. 
2. If so, which alerts I need to turn on or maybe add something to setting pack to have a possibility to handle this error? 
3. If I should turn on CAS somehow firstly, is there any way to turn it on isung simple put_mutable function? If not, how? How I can receive some errors using the scenario described above?

Thank you a lot again and sorry to bother you.

**Comment by arvidn** [comment]
when your callback is called, the sequence number is initialized to the current sequence number, and the `entry` will be initialized to what's currently stored.

it appears the put logic in libtorrent does not implement "cas" yet. it only supports it in incoming requests, not outgoing. It would have to be added to `kademlia/put_data.cpp`

**Comment by aldenml** [comment]
Hi @tatashina I believe all these errors are received via `dht_log_alert`, I think that if what you want is make sure someone will reply to you with `302`, that's the route, add `dht_log_notification` to the alert mask

**Comment by tatashina** [comment]
Hi @aldenml!
Thank you, I believed in that too. But then I checked several times aaaand that is doesn't work, unfortunately.

**Comment by arvidn** [comment]
I had a (brief) look, and as far as I can tell, libtorrent doesn't support *sending* the "cas" field, which means it won't have the condition on its DHT writes, which means they can't fail.

See the [docs](https://github.com/arvidn/libtorrent/blob/master/docs/dht_store.rst#id1), the "cas" field is optional, and libtorrent currently never sends it.

patches are welcome! (against `RC_1_2`)

**Comment by tatashina** [comment]
@arvidn, hi again. 
I have already seen the same document (BEP 44) so I know that it is an optional field. Actually, I just tried to find out if I missed something. So now when I have approval from you that's ok for me. As I said before, I do not commit it as a bug, just a bit curiosity from my side.

Thank you again a lot for your help. Also thanks for this library, it helped me a lot.

PS someday I'll try to find some time to patch it.
