### ISSUE TITLE
Https trackers using a lot of cpu ?

### ISSUE THREAD

**Issue by Rootax** [arvidn/libtorrent#3583]
libtorrent version (or branch): 1.1.11.0 , 1.1.12.0

platform/architecture: W10 Qbittorrent 4.1.x

Hi,

It seems that qbittorrent use a lot of cycles when contacting an https tracker. And I guess that libtorrent is managing that under the hood ?
Even when the transfert is finished, my client is using a lot of cpu with a https tracker in the list.
As soon as I remove it, it's ok again.

I tried with a build with 1.1.11.0, and 1.1.12.0, same thing. The only test I couldn't do is a test with a working https tracker, to see if the problem is https tracker, or https+non working tracker...

![httpstracker2](https://user-images.githubusercontent.com/22431162/51264133-0cbd8500-19b6-11e9-8dba-c1baf6df2312.JPG)
![httpstracker1](https://user-images.githubusercontent.com/22431162/51264134-0cbd8500-19b6-11e9-8e5b-6a7254a2b627.JPG)

I don't know where or how to catch meaningful log...

Thx.

**Comment by Rootax** [comment]
I tested, working https trackers don't cause a problem.

**Comment by arvidn** [comment]
I tried to reproduce this on linux without success, adding "https://open.kickasstracker.com:443/announce" to a random test torrent. I just got "hostname not found". and no abnormal CPU usage.

Is there a way to enable debug logging in qbt? if so, that would log a lot of logic around announcing to trackers that might reveal what's going on.

**Comment by arvidn** [comment]
so, a non-working HTTP tracker does not have the CPU problem?

**Comment by Rootax** [comment]
No, non working http tracker does not have this cpu problem. In a perfect world I would need to find another non working https tracker, but with a good dns resolution, see if the cpu issue is still here.
