### ISSUE TITLE
Compile error C4596 in win_crypto_provider.hpp

### ISSUE THREAD

**Issue by kerokim** [arvidn/libtorrent#3585]
**Please provide the following information**

libtorrent version (or branch): libtorrent 1.2.0

platform/architecture: Windows 10 x64

compiler and compiler version: Visual Studio 2017 15.9.5

Hello.
I was building a project using libtorrent 1.2.0 when an error C4596 occured.
The line on which errors occur are as follows.

https://github.com/arvidn/libtorrent/blob/3a1e546a6c63a056914547ecdbc565fb907b423d/include/libtorrent/aux_/win_crypto_provider.hpp#L75

No further errors have occurred since this line was fixed as follows.

```
		crypt_hash& operator=(crypt_hash const& h) &
```

This error did not occur when the '/permissive-' option turn off in Visual studio.

Can you correct this so that no errors will occur in the future?

Thanks.

**Comment by arvidn** [comment]
thanks for the report!

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/3588
