### ISSUE TITLE
[Feature] Setting for disable upload

### ISSUE THREAD

**Issue by elgatito** [arvidn/libtorrent#3592]
Hello. 

I could not find that setting in documentation. If I've missed it - please, close the issue.

What about:
It would be great to have a setting to disable seeding/upload for a torrent or a session in general.

Why:
There are countries where downloading of torrents is fine, while seeding/upload is restricted. So we have to make sure we don't give any single kilobyte, if needed.

It would, probably, be fine if we just say to peers we don't have any piece. 
Or any other way, it's up to you.

Thanks

**Comment by arvidn** [comment]
the first that come to mind would be to write a plugin that swallows all incoming `REQUEST` messages, an d also prevent `HAVE` messages and `BITFIELD` messages from being sent.

**Comment by elgatito** [comment]
@arvidn I have tried to make `peer_plugin` that returns _true_ to `on_have`, `on_request`, and `on_bitfield` . 
But in that case I'm not downloading anything...
