### ISSUE TITLE
support http2 for trackers

### ISSUE THREAD

**Issue by Pickoffs** [arvidn/libtorrent#360]
Hi
I'm using qBittorrent(libtorrent) and it can't connect to trackers who are using http2 with a secure https connection. (tracker behind cloudflare)
OS: Win7 64 pro

**Comment by arvidn** [comment]
I don't believe you're supposed to. who's trying to use http2 for bittorrent trackers?
I take it you mean google's spdy-based protocol: https://tools.ietf.org/html/draft-ietf-httpbis-http2-16

**Comment by Pickoffs** [comment]
Yes.
The tracker and the website are behind cloudfront because of ddos. http2 is used for the website and as the tracker and the website share the same certificate the tracker went http2.

**Comment by LudoDan** [comment]
Is it possible to know why this issue is closed ?
I use a Deluge client, which is based on libtorrent, and i encountered this issue with a tracker in http2 mode.
When i want to put torrent annonce in deluge, it doesn't work.
Is it possible to fix this issue, then http2 will be supported ?

Best regards.

**Comment by Pickoffs** [comment]
qBittorrent managed to get it to work I believe it was by updating some dependencies but I didn't had time to see in depth.

**Comment by LudoDan** [comment]
I don't thin it's just dependencies, i install deluge (which use libtorrent) on a new server with debian 8 with all packages (http/https ssl etc...) up to date and i've got the problème.
http2 is a new protocole, the code have to implement it, otherway it wont work.

**Comment by LudoDan** [comment]
do i have to do a new issue, or is this one can be re-opened ?

**Comment by t5awd** [comment]
I would like to add my voice to the requests that http/2 support be added to libtorrent. It is very important for BitTorrent trackers to be able to multiplex multiple announces over a single TCP connection. It very much cuts down on overhead, especially when SSL is involved.

**Comment by arvidn** [comment]
multiplexing multiple announces over a single connection can be done with HTTP/1.1 as well, and is probably a good idea to implement. HTTP/2 would be a massive surgery as it would be replacing the current HTTP code with a library that supports HTTP/2. And we're coming up on HTTP/3
