### ISSUE TITLE
[Question] About using libtorrent for syncing files like Dropbox

### ISSUE THREAD

**Issue by kilon** [arvidn/libtorrent#3600]
Hello there, this is not a bug report or feature request , just a simple general question.

Is there a project out there that uses this library to implement file syncing like Dropbox ?

If there is not, do you think this library is a good choice for such a project and if not why ?

**Comment by arvidn** [comment]
sorry I missed this. I may have been very busy. I don't know of a project off-hand. And I would think so. Resilio Sync (previously known as bittorrent sync), use the bittorrent engine from uTorrent under the hood.

**Comment by kilon** [comment]
no problemo, i closed thew issue because i did a test a couple days after i asked the question here and the syncing worked just fine without having to do anything extra. Other of course than creating a new torrent file. But I forgot the I had the issue opened, until your bot sent me the email. So the good news is that there is no need for extra software and services , a regular turrent client does the job, I use QTorrent because its open source and free :)
