### ISSUE TITLE
Can't build libtorrent 1.2.0 with MinGW 7.3.0

### ISSUE THREAD

**Issue by 3unjee** [arvidn/libtorrent#3603]
I'm on Windows 10 + MinGW 7.3.0 and I'm buidling libtorrent with the following:
`b2.exe -j4 toolset=gcc cxxflags=-std=c++11 link=shared variant=release openssl-version=pre1.1`

I get the following:
```
bin\gcc-7.3.0\release\threading-multi\src\hasher.o:hasher.cpp:(.text+0x52): undefined reference to `libtorrent::SHA1_init(libtorrent::sha1_ctx*)'
bin\gcc-7.3.0\release\threading-multi\src\hasher.o:hasher.cpp:(.text+0x81): undefined reference to `libtorrent::SHA1_init(libtorrent::sha1_ctx*)'
bin\gcc-7.3.0\release\threading-multi\src\hasher.o:hasher.cpp:(.text+0x16c): undefined reference to `libtorrent::SHA1_update(libtorrent::sha1_ctx*, unsigned char const*, unsigned long long)'
bin\gcc-7.3.0\release\threading-multi\src\hasher.o:hasher.cpp:(.text+0x193): undefined reference to `libtorrent::SHA1_update(libtorrent::sha1_ctx*, unsigned char const*, unsigned long long)'
bin\gcc-7.3.0\release\threading-multi\src\hasher.o:hasher.cpp:(.text+0x1b7): undefined reference to `libtorrent::SHA1_final(unsigned char*, libtorrent::sha1_ctx*)'
bin\gcc-7.3.0\release\threading-multi\src\hasher.o:hasher.cpp:(.text+0x31): undefined reference to `libtorrent::SHA1_init(libtorrent::sha1_ctx*)'
bin\gcc-7.3.0\release\threading-multi\src\hasher.o:hasher.cpp:(.text+0x67): undefined reference to `libtorrent::SHA1_update(libtorrent::sha1_ctx*, unsigned char const*, unsigned long long)'
bin\gcc-7.3.0\release\threading-multi\src\hasher.o:hasher.cpp:(.text+0x96): undefined reference to `libtorrent::SHA1_update(libtorrent::sha1_ctx*, unsigned char const*, unsigned long long)'
bin\gcc-7.3.0\release\threading-multi\src\hasher.o:hasher.cpp:(.text+0x1d1): undefined reference to `libtorrent::SHA1_init(libtorrent::sha1_ctx*)'
bin\gcc-7.3.0\release\threading-multi\src\hasher512.o:hasher512.cpp:(.text+0x52): undefined reference to `libtorrent::SHA512_init(libtorrent::sha512_ctx*)'
bin\gcc-7.3.0\release\threading-multi\src\hasher512.o:hasher512.cpp:(.text+0xc3): undefined reference to `libtorrent::SHA512_update(libtorrent::sha512_ctx*, unsigned char const*, unsigned long long)'
bin\gcc-7.3.0\release\threading-multi\src\hasher512.o:hasher512.cpp:(.text+0xea): undefined reference to `libtorrent::SHA512_final(unsigned char*, libtorrent::sha512_ctx*)'
bin\gcc-7.3.0\release\threading-multi\src\hasher512.o:hasher512.cpp:(.text+0x31): undefined reference to `libtorrent::SHA512_init(libtorrent::sha512_ctx*)'
bin\gcc-7.3.0\release\threading-multi\src\hasher512.o:hasher512.cpp:(.text+0x67): undefined reference to `libtorrent::SHA512_update(libtorrent::sha512_ctx*, unsigned char const*, unsigned long long)'
bin\gcc-7.3.0\release\threading-multi\src\hasher512.o:hasher512.cpp:(.text+0x101): undefined reference to `libtorrent::SHA512_init(libtorrent::sha512_ctx*)'
collect2.exe: error: ld returned 1 exit status
```

Thanks for your help.

**Comment by aldenml** [comment]
can you confirm that you have `openssl` installed in your MinGW env?

**Comment by 3unjee** [comment]
I thought "built-in" crypto was the default in libtorrent. Why would it need OpenSSL ?

I should also mention libtorrent 1.1.11 builds fine with the same environment. Maybe it's something specific to the way 1.2.0 handles crypto.

**Comment by 3unjee** [comment]
Adding this in Jamfile fixes the build:
```
result += <source>src/sha1.cpp ;
result += <source>src/sha512.cpp ;
```
Maybe there is something wrong with the Jamfile ?

**Comment by aldenml** [comment]
You are right with respect to "built-in". Since you are using  MinGW, can you execute `gcc -dM -E` (I don't know how to do that in windows) to see if in fact `_WIN32` is specified?

**Comment by 3unjee** [comment]
Well, honestly I'm not sure how to test this either :-).

Looking at the jamfile I get the following:
```
if <crypto>built-in in $(properties)
		&& ! <target-os>windows in $(properties)
		&& ! <target-os>darwin in $(properties)
	{
		result += <source>src/sha1.cpp ;
		if <dht>on in $(properties)
		{
			result += <source>src/sha512.cpp ;
		}
	}

	if <target-os>windows in $(properties)
		&& <windows-version>xp in $(properties)
	{
		result += <source>src/sha512.cpp ;
	}
```
I don't see how this could ever work on Windows with the "built-in" cryptography.

**Comment by arvidn** [comment]
@3unjee can you confirm that `_WIN32` is defined by mingw in your environment? afaict it's supposed to, but perhaps it's possible to disabled win32 support in mingw.

**Comment by 3unjee** [comment]
@arvidn Yes, I can confirm that `_WIN32` is defined in my MinGW 7.3.0.

My MinGW toolchain actually comes from the Qt 5.12.x package (http://download.qt.io/official_releases/qt/5.12).

**Comment by arvidn** [comment]
if `_WIN32` is defined, then `libtorrent/config.hpp` is supposed to define `TORRENT_USE_CRYPTOAPI` which causes `hasher` to use the native windows SHA-1 hash API, rather than the built-in one. The same thing goes for SHA-512. As it turns out, this logic was only in the config header for `_WIN32` if *not* using Mingw.

The logic to include `sha1.cpp`/`sha512.cpp` or not also seemed unnecessarily complicated. It shouldn't be spread out in both source *and* `Jamfile`.

@3unjee Could you please give this patch a try? https://github.com/arvidn/libtorrent/pull/3629

**Comment by 3unjee** [comment]
OK, this one seems to build: https://github.com/arvidn/libtorrent/tree/8033f6dc0cbf3d638ce2ac4e8d52a25303bcdec1

Thanks @arvidn.
