### ISSUE TITLE
Add --recurse-submodules option to cloning instructions

### ISSUE THREAD

**Issue by nelsonghezzi** [arvidn/libtorrent#3607]
**Please provide the following information**

libtorrent version (or branch): N/A

platform/architecture: N/A

compiler and compiler version: N/A

I was following the [official guide](https://libtorrent.org/building.html) to build libtorrent, and faced a b2 building issue with some missing Jamfile in `deps/try_signal`.

Being new to the build system, I spended some time figuring it out, but ultimately the issue was that the submodules on the repo were not cloned.

It would be helpful to change the instruction for cloning the repository to:

`git clone --recurse-submodules https://github.com/arvidn/libtorrent.git`

I think it could save someone in the future.

Cheers!

**Comment by arvidn** [comment]
I take it this is master, since that's where I've started to use submodules

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/3625

**Comment by nelsonghezzi** [comment]
That's right, it was from master.

Thanks!
