### ISSUE TITLE
Error compiling a simple program with static linking

### ISSUE THREAD

**Issue by nelsonghezzi** [arvidn/libtorrent#3608]
**Please provide the following information**

libtorrent version (or branch): **master@30b8a06b**

platform/architecture: **Windows 10 x64**

compiler and compiler version: **msvc-14.1**

I'm trying to compile the first example from [here](https://libtorrent.org/examples.html):

```cpp
#include "pch.h"
#include <iostream>
#include <stdlib.h>
#include <boost/make_shared.hpp>
#include "libtorrent/entry.hpp"
#include "libtorrent/bencode.hpp"
#include "libtorrent/session.hpp"
#include "libtorrent/torrent_info.hpp"

int main(int argc, char* argv[])
{
	if (argc != 2)
	{
		std::cerr << "usage: ./simple_client torrent-file\n"
			"to stop the client, press return.\n";
		return 1;
	}

	lt::session s;
	lt::add_torrent_params p;

	p.save_path = "./";

	lt::error_code ec;

	// line below commented as it errors with:
	// no operator "=" matches these operands
	// operand types are: std::shared_ptr<libtorrent::torrent_info> = boost::shared_ptr<libtorrent::torrent_info>
	// sample out of date ?
	// p.ti = boost::make_shared<lt::torrent_info>(std::string(argv[1]), 0);

	s.add_torrent(p);

	// code below commented as it errors with:
	// error C4996: 'scanf': This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS.
	// wait for the user to end
	// char a;
	// scanf("%c\n", &a);

	return 0;
}
```
### libtorrent Build Info

`b2 --toolset=msvc-14.1 variant=release boost-link=static link=static runtime-link=static -sBOOST_ROOT="C:\Users\nelsong\Documents\boost_1_66_0"`

**Output path:** libtorrent\bin\msvc-14.1\release\boost-link-static\link-static\runtime-link-static\threading-multi 
**File:** libtorrent.lib (102.079.202 bytes)

### VS Project Info

**IDE:** Visual Studio Community Edition 2017 (with C++ workload installed)
**Type:** Console App
**Additional Include Directories:** 
* C:\Users\nelsong\Documents\boost_1_66_0
* C:\Users\nelsong\Documents\libtorrent\include

**Code Generation:**
* Runtime Library: Multi-threaded (/MT)

**Additional Library Directories:**
* C:\Users\nelsong\Documents\boost_1_66_0\stage\win32\lib
* C:\Users\nelsong\Documents\libtorrent\bin\msvc-14.1\release\boost-link-static\link-static\runtime-link-static\threading-multi

### Questions
 
1. Why I've to add `boost_1_66_0\stage\win32\lib` to the list of Additional Library Directories, if I'm linking statically against `libtorrent.lib`?. If I don't do so, I get the following error:

`LINK : fatal error LNK1104: cannot open file 'libboost_system-vc141-mt-s-x32-1_66.lib'`

As far as I understood, building libtorrent with `boost-link=static` should avoid that, right?

2. Adding that path to the library directories effectively solves the error, but then I get this nice output:
```
1>------ Rebuild All started: Project: libtorrent-sample, Configuration: Release Win32 ------
1>pch.cpp
1>libtorrent-sample.cpp
1>Info: Boost.Config is older than your compiler version - probably nothing bad will happen - but you may wish to look for an update Boost version.  Define BOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE to suppress this message.
1>Please define _WIN32_WINNT or _WIN32_WINDOWS appropriately. For example:
1>- add -D_WIN32_WINNT=0x0501 to the compiler command line; or
1>- add _WIN32_WINNT=0x0501 to your project's Preprocessor Definitions.
1>Assuming _WIN32_WINNT=0x0501 (i.e. Windows XP target).
1>libtorrent-sample.obj : error LNK2001: unresolved external symbol "private: void __thiscall libtorrent::session::start(struct libtorrent::session_params &&,class boost::asio::io_context *)" (?start@session@libtorrent@@AAEX$$QAUsession_params@2@PAVio_context@asio@boost@@@Z)
1>libtorrent-sample.obj : error LNK2001: unresolved external symbol "public: __thiscall libtorrent::session_params::session_params(void)" (??0session_params@libtorrent@@QAE@XZ)
1>libtorrent-sample.obj : error LNK2001: unresolved external symbol "public: __thiscall libtorrent::session::~session(void)" (??1session@libtorrent@@QAE@XZ)
1>libtorrent-sample.obj : error LNK2001: unresolved external symbol "public: __thiscall libtorrent::add_torrent_params::add_torrent_params(void)" (??0add_torrent_params@libtorrent@@QAE@XZ)
1>libtorrent-sample.obj : error LNK2001: unresolved external symbol "public: struct libtorrent::torrent_handle __thiscall libtorrent::session_handle::add_torrent(struct libtorrent::add_torrent_params const &)" (?add_torrent@session_handle@libtorrent@@QAE?AUtorrent_handle@2@ABUadd_torrent_params@2@@Z)
1>C:\Users\nelsong\source\repos\libtorrent-sample\Release\libtorrent-sample.exe : fatal error LNK1120: 5 unresolved externals
1>Done building project "libtorrent-sample.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

I'm stuck with this error for almost a week now. Any help would be really appreciated.

Thanks in advance!

**Comment by nelsonghezzi** [comment]
Hi Alden, thanks for your reply!

Are you referring to the `address-model` and/or `architecture` [arguments](https://boostorg.github.io/build/tutorial.html#feature_reference) of Boost.Build?

(If you can give me a very quick explainer on how mixing those args affect the output would be great! e.g.: would make sense mixing `architecture=x86` with `address-model=64`?)

Indeed, I didn't pass them when building libtorrent, so probably they are defaulting to some value.

I build another variant of libtorrent as follows:

`b2 --toolset=msvc-14.1 address-model=32 architecture=x86 variant=release boost-link=static link=static runtime-link=static -sBOOST_ROOT="C:\Users\nelsong\Documents\boost_1_66_0"
`

Then changed the _Additional Library Directories_ setting to point to the output path of this variant (`C:\Users\nelsong\Documents\libtorrent\bin\msvc-14.1\release\address-model-32\architecture-x86\boost-link-static\link-static\runtime-link-static\threading-multi`).

The error stayed the same :disappointed:

What I've found is that, even removing the path to `libtorrent.lib` from the Library Directories, I still get the same linker errors (`LNK2001`).

I'm trying to build the sample program with the `Release | Win32` project configuration.

It looks like the linker is not happy with the libtorrent.lib for some reason, but I can't guess why

Any ideas?

Thanks!

**Comment by MassaRoddel** [comment]
Did you add libtorrent.lib to the linker input? Afaik, libtorrent does not do that via header files, therefore it is not enough to give just the path to the library.

**Comment by nelsonghezzi** [comment]
@MassaRoddel I've no idea about that!

I've made some changes to the project config, mixed in with your hint.

This is my progress so far.

I gave up on static linking, and started to look at building the program with dynamic linking.

1. Created a version of libtorrent with this options:
`b2 --toolset=msvc-14.1 address-model=32 architecture=x86 variant=debug boost-link=shared link=shared runtime-link=shared -sBOOST_ROOT="C:\Users\nelsong\Documents\boost_1_66_0"`

2. And a build of Boost with `address-model=32 architecture=x86 link=shared runtime-link=shared threading=multi` (into a folder `stage/win32-shared`).

3. Changed the project configuration to:
* Code Generation -> Runtime Library -> Multi-threaded Debug DLL (/MDd)
* _Additional Library Directories_ changed to:
  - C:\Users\nelsong\Documents\boost_1_66_0\stage\win32-shared\lib
  - C:\Users\nelsong\Documents\libtorrent\bin\msvc-14.1\debug\address-model-32\architecture-x86\boost-link-shared\threading-multi

> As a side note: with this setup, I was getting an error **cannot open file 'libboost_date_time-vc141-mt-gd-x32-1_66.lib'**. To workaround this, I had to create a copy of **boost_date_time-vc141-mt-gd-x32-1_66.lib** (that was present in stage/win32-shared) with the name the compiler was looking for.

4. At this point, I was getting the same error as with static linking.

5. Then, following your tip, I configured the _Additional Dependencies_ for the Linker:

![image](https://user-images.githubusercontent.com/6424021/52526716-ac6beb80-2cb4-11e9-9ccb-e6a041060092.png)

With that setting in place, the program was built with no errors! :tada: 

Trying to run the program, I quickly realized that I had to copy `torrent.dll` and all of Boost `dll`s into the program's folder (where the `.exe` is).

Now, my new troubles.

The program ran, but I did comment some parts of it because I was receiving compilation errors.

Particularly, this line was complaining about an invalid cast:
```cpp
p.ti = boost::make_shared<lt::torrent_info>(std::string(argv[1]), 0);
```

So, I changed to:
```cpp
lt::torrent_info ti = lt::torrent_info(argv[1], 0);
p.ti = std::make_shared<lt::torrent_info>(ti);
```

But now I get a new linker error:
`error LNK2001: unresolved external symbol "class libtorrent::from_span_t libtorrent::from_span" (?from_span@libtorrent@@3Vfrom_span_t@1@A)`

I see the constructor I'm using for `lt::torrent_info` calls an overload that uses a `from_span_t` class, declared in the same `torrent_info.hpp`:

```cpp
// hidden
class from_span_t {};

// used to disambiguate a bencoded buffer and a filename
extern TORRENT_EXPORT from_span_t from_span;
```

Do I have to declare some symbol or specify another compiler option for the linker to see that class?

Thanks for the help so far, I sure would not have gotten to this point without it!

**Comment by nelsonghezzi** [comment]
Adding to my last comment, and If it throws some light into the problem, this is a breakdown of the compiler and linker arguments as informed by Visual Studio.

Compiler:
```
/JMC 
/permissive- 
/Yu"pch.h" 
/GS 
/analyze- 
/W3 
/Zc:wchar_t 
/I"C:\Users\nelsong\Documents\boost_1_66_0" 
/I"C:\Users\nelsong\Documents\libtorrent\include" 
/ZI 
/Gm- 
/Od 
/sdl 
/Fd"Debug\vc141.pdb" 
/Zc:inline 
/fp:precise 
/D "WIN32" 
/D "_DEBUG" 
/D "_CONSOLE" 
/D "_UNICODE" 
/D "UNICODE" 
/errorReport:prompt 
/WX- 
/Zc:forScope 
/RTC1 
/Gd 
/Oy- 
/MDd 
/FC 
/Fa"Debug\" 
/EHsc 
/nologo 
/Fo"Debug\" 
/Fp"Debug\libtorrent-sample.pch" 
/diagnostics:classic 
```

Linker:
```
/OUT:"C:\Users\nelsong\source\repos\libtorrent-sample\Debug\libtorrent-sample.exe" 
/MANIFEST 
/NXCOMPAT 
/PDB:"C:\Users\nelsong\source\repos\libtorrent-sample\Debug\libtorrent-sample.pdb" 
/DYNAMICBASE "torrent.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "odbc32.lib" "odbccp32.lib" 
/DEBUG 
/MACHINE:X86 
/INCREMENTAL 
/PGD:"C:\Users\nelsong\source\repos\libtorrent-sample\Debug\libtorrent-sample.pgd" 
/SUBSYSTEM:CONSOLE 
/MANIFESTUAC:"level='asInvoker' uiAccess='false'" 
/ManifestFile:"Debug\libtorrent-sample.exe.intermediate.manifest" 
/ERRORREPORT:PROMPT 
/NOLOGO 
/LIBPATH:"C:\Users\nelsong\Documents\boost_1_66_0\stage\win32-shared\lib" 
/LIBPATH:"C:\Users\nelsong\Documents\libtorrent\bin\msvc-14.1\debug\address-model-32\architecture-x86\boost-link-shared\threading-multi" 
/TLBID:1 
```

**Comment by MassaRoddel** [comment]
It seems you are building an UNICODE program so argv should be wchar_t pointers. 
std::string(argv[1]) should not compile

**Comment by nelsonghezzi** [comment]
I took another look at the code, and realized that I wasn't using the desired constructor for `torrent_info`.

I made this change to use the constructor that takes a `torrent_info(std::string const& filename)` with a .torrent file path:

```cpp
std::string const& file = std::string("C:\\Users\\nelsong\\source\\repos\\libtorrent-sample\\Debug\\archlinux-2019.02.01-x86_64.iso.torrent");

lt::torrent_info ti = lt::torrent_info(file);
p.ti = std::make_shared<lt::torrent_info>(ti);
```

That worked and the torrent was successfully downloaded.

But if I try to use the other constructor,  `torrent_info(char const* buffer, int size)`, even with a hardcoded value that satisfies the signature:

```cpp
char const* buffer = "asd";
	
lt::torrent_info ti = lt::torrent_info(buffer, 0);
```

It doesn't link, and throws the error `unresolved external symbol "class libtorrent::from_span_t libtorrent::from_span"`.

I'm not sure if it has to do with the UNICODE support, because removing that compiler option has no effect on the output.

Any other thing to look for?

**Comment by arvidn** [comment]
ah, the `from_span_t` and `from_span` probably need to be exported by libtorrent, this is an issue I will fix. I think the problem is that those names are used in the header.

**Comment by arvidn** [comment]
@nelsonghezzi could you please try this patch? https://github.com/arvidn/libtorrent/pull/3626
(a short term fix would be to link statically against libtorrent btw)

**Comment by nelsonghezzi** [comment]
Hi Arvid,

Linking statically was my first attempt to build the program, but I had a hard time trying to solve various kinds of linker errors, and switched to dynamic linking where I found a setup that worked.

I'll give that patch a try and tell you how it goes.

**Comment by nelsonghezzi** [comment]
I got this warning logged multiple times in the build output:
```
warning C4091: '__declspec(dllexport)': ignored on left of 'libtorrent::from_span_t' when no variable is declared
```

And linking dynamically against this version still produces the same error for `from_span`.

**Comment by arvidn** [comment]
can you see if the symbol `from_span` is exported by `libtorrent.dll`? with `objdump` or something like that.

**Comment by arvidn** [comment]
for example, on macOS I can confirm it like this:

```
$ nm bin/darwin-4.2.1/debug/threading-multi/libtorrent.dylib.1.2.0 | grep from_span | c++filt
00000000006641e0 T libtorrent::torrent_info::torrent_info(libtorrent::span<char const>, libtorrent::from_span_t)
0000000000667130 T libtorrent::torrent_info::torrent_info(libtorrent::span<char const>, boost::system::error_code&, libtorrent::from_span_t)
0000000000663760 T libtorrent::torrent_info::torrent_info(libtorrent::span<char const>, libtorrent::from_span_t)
00000000006666b0 T libtorrent::torrent_info::torrent_info(libtorrent::span<char const>, boost::system::error_code&, libtorrent::from_span_t)
000000000098c3cc S libtorrent::from_span
00000000005a75d0 unsigned short std::__1::shared_ptr<libtorrent::torrent_info> std::__1::shared_ptr<libtorrent::torrent_info>::make_shared<libtorrent::span<char const>&, std::__1::reference_wrapper<boost::system::error_code>, libtorrent::from_span_t&>(libtorrent::span<char const>&&&, std::__1::reference_wrapper<boost::system::error_code>&&, libtorrent::from_span_t&&&)
```

**Comment by nelsonghezzi** [comment]
Opening the _x64 Native Tools Command Prompt for VS 2017_, running `dumpbin torrent.dll /EXPORTS` and searching for `from_span` this is what I've found:
```
328  147 00368430 ??0torrent_info@libtorrent@@QAE@U?$span@$$CBD@1@AAVerror_code@system@boost@@Vfrom_span_t@1@@Z = ??0torrent_info@libtorrent@@QAE@U?$span@$$CBD@1@AAVerror_code@system@boost@@Vfrom_span_t@1@@Z (public: __thiscall libtorrent::torrent_info::torrent_info(struct libtorrent::span<char const >,class boost::system::error_code &,class libtorrent::from_span_t))
329  148 00367900 ??0torrent_info@libtorrent@@QAE@U?$span@$$CBD@1@Vfrom_span_t@1@@Z = ??0torrent_info@libtorrent@@QAE@U?$span@$$CBD@1@Vfrom_span_t@1@@Z (public: __thiscall libtorrent::torrent_info::torrent_info(struct libtorrent::span<char const >,class libtorrent::from_span_t))
1230  4CD 00650D10 ?from_span@libtorrent@@3Vfrom_span_t@1@A = ?from_span@libtorrent@@3Vfrom_span_t@1@A (class libtorrent::from_span_t libtorrent::from_span)
```

Anyway, I'll later do a cleanup and rebuild the library, and see if that makes some difference.

**Comment by arvidn** [comment]
ok, so `libtorrent::from_span` appears to be in there. make sure you're actually linking against that specific .dll file, and not some other random build you may have laying around.

If you still get the link error message, compare the exact (mangled) name of the missing symbol with that last symbol you got in your list. If there are any differences, that indicates an ABI issue, i.e. the .dll was built with different configuration options that your client.

**Comment by ArtemGr** [comment]
> unresolved external symbol "private: void __thiscall libtorrent::session::start(struct libtorrent::session_params &&,class boost::asio::io_context *)"

This might happen when a wrong `BOOST_VERSION` is loaded.

> make sure you're actually linking against that specific .dll file, and not some other random build you may have laying around.

Or the other way around, linking against the right DLL but using the wrong headers.

**Comment by nelsonghezzi** [comment]
I've searched the mangled name that shows up in VS (`?from_span@libtorrent@@3Vfrom_span_t@1@A`) and found it in the list of exports from the .lib and the .dll (I think only the exports from the .lib are in play here, as the linker only looks there).

I managed to remove the warning `C4091` by placing the `__declspec` behind the `class` keyword:
```c++
class TORRENT_EXPORT from_span_t {};
```

But nothing changed (apart from no warnings showing during build).

[This SO question](https://stackoverflow.com/questions/49720034/msvc-unresolved-eternal-symbols-in-dll) is very similar to my situation, but I can't realize if the solution is valid too.

What is interesting, is that this line compile just fine:
```c++
lt::from_span_t x = lt::from_span;
```

No "undefined symbol" errors.

So the exports are in place, but for some reason the linker gets "confused" only when using that `torrent_info` constructor?

Any thought?

**Comment by ArtemGr** [comment]
`boost::system::error_code` can compile in a number of ways, based on the defines present in the moment (IIRC; including but not limited to defines that represent the version of compiler and the version of C++). If these defines are different between the time the boost library compiles and the time your program compiles then you'd be getting a mismatch between what the boost headers tell and what's actually there in the boost DLL.

**Comment by ArtemGr** [comment]
There's a lot of define-guided conditional compilation in the Boost headers. So the problem is usually to make sure that the same version of the compiler, C++ and Boost defines are used during the compilation of the Boost library and that of your code.

**Comment by MassaRoddel** [comment]
Does it link if you define your own local lt::from_span_t from_span?

**Comment by nelsonghezzi** [comment]
@MassaRoddel yes, declaring a local `lt::from_span_t from_span` inside `main()` compiles without linker issues.

The linker error only triggers invoking a particular `torrent_info` constructor (`torrent_info(char const* buffer, int size)`).

Even this code compiles OK:
```cpp
lt::error_code ec;
lt::from_span_t x;

lt::torrent_info ti = lt::torrent_info({ "asd", 0 }, ec, x);
```

Which makes me think that the problem only arises when `torrent_info(char const* buffer, int size)` delegates to `torrent_info(span<char const>{buffer, size}, from_span)`.

Poking around, I stumble upon the same error for another class, but discover that the class was decorated with `TORRENT_EXPORT_EXTRA` macro.

So I made a new clean build with this command:
```
b2 --toolset=msvc-14.1 define=TORRENT_EXPORT define=TORRENT_EXPORT_EXTRA address-model=32 architecture=x86 variant=debug boost-link=shared link=shared runtime-link=shared -sBOOST_ROOT="C:\Users\nelsong\Documents\boost_1_66_0"
```
(I guess the first `define` is not really needed).

That fixed the linker issue for that particular class, but no for the `torrent_info` ctor :sweat: 

Anyway, running a `dumpbin` on the new torrent.dll now gives me additional lines:
```
531  212 00398630 ??0torrent_info@libtorrent@@QAE@U?$span@$$CBD@1@AAVerror_code@system@boost@@Vfrom_span_t@1@@Z = ??0torrent_info@libtorrent@@QAE@U?$span@$$CBD@1@AAVerror_code@system@boost@@Vfrom_span_t@1@@Z (public: __thiscall libtorrent::torrent_info::torrent_info(struct libtorrent::span<char const >,class boost::system::error_code &,class libtorrent::from_span_t))
532  213 00397B00 ??0torrent_info@libtorrent@@QAE@U?$span@$$CBD@1@Vfrom_span_t@1@@Z = ??0torrent_info@libtorrent@@QAE@U?$span@$$CBD@1@Vfrom_span_t@1@@Z (public: __thiscall libtorrent::torrent_info::torrent_info(struct libtorrent::span<char const >,class libtorrent::from_span_t))
923  39A 000488E0 ??4from_span_t@libtorrent@@QAEAAV01@$$QAV01@@Z = ??4from_span_t@libtorrent@@QAEAAV01@$$QAV01@@Z (public: class libtorrent::from_span_t & __thiscall libtorrent::from_span_t::operator=(class libtorrent::from_span_t &&))
924  39B 000488F0 ??4from_span_t@libtorrent@@QAEAAV01@ABV01@@Z = ??4from_span_t@libtorrent@@QAEAAV01@ABV01@@Z (public: class libtorrent::from_span_t & __thiscall libtorrent::from_span_t::operator=(class libtorrent::from_span_t const &))
2339  922 006B8D18 ?from_span@libtorrent@@3Vfrom_span_t@1@A = ?from_span@libtorrent@@3Vfrom_span_t@1@A (class libtorrent::from_span_t libtorrent::from_span)
```

That output is more in line to the one Arvid shown me in a previous comment, but the error persists.

I have no clue what's going on with that stubborn constructor.

**Comment by arvidn** [comment]
You're not supposed to define `TORRENT_EXPORT_EXTRA`, that's only used to expose internal types for unit tests.

In the ticket, you mention that there are a few missing symbols, for instance `add_torrent@session_handle@libtorrent@@QAE?AUtorrent_handle@2@ABUadd_torrent_params@2@@Z`.

If you search the output from `dumpbin`, can you find that symbol in there?

If you can, I would suggest you look over your build and make sure you're actually linking against the correct binary (and not some other/older build).

I you cannot find it in there, look for a symbol looks very similar/ That would indicate that the library and the client are built with ABI incompatible compiler flags. Looking at the differences in the names may give you a hint as to what build options differ.

**Comment by MassaRoddel** [comment]
My intention was to define exactly from_span so that there is a second variable from_span and since the constructor is header file only it should use your variable not libtorrents from_span.
