### ISSUE TITLE
assertion failed. 

### ISSUE THREAD

**Issue by wkl001** [arvidn/libtorrent#3619]
**Please provide the following information**

libtorrent version (or branch): 1.1.11

platform/architecture: raspbian stretch

compiler and compiler version: ?

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Compiled and installed qbittorrent 4.1.5. After downloading for a while qbittorrent crashes and in syslog I get:

Feb 10 14:12:28 raspberrypi qbittorrent-nox[12479]: assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Feb 10 14:12:28 raspberrypi qbittorrent-nox[12479]: Please include the following information:
Feb 10 14:12:28 raspberrypi qbittorrent-nox[12479]: version: 1.1.11.0-ed4ca98a1
Feb 10 14:12:28 raspberrypi qbittorrent-nox[12479]: file: 'storage.cpp'
Feb 10 14:12:28 raspberrypi qbittorrent-nox[12479]: line: 995
Feb 10 14:12:28 raspberrypi qbittorrent-nox[12479]: function: virtual void libtorrent::default_storage::write_resume_data(libtorrent::entry&, libtorrent::storage_error&) const
Feb 10 14:12:28 raspberrypi qbittorrent-nox[12479]: expression: file_size == 0
Feb 10 14:12:28 raspberrypi qbittorrent-nox[12479]: file_size: 22351907
Feb 10 14:12:28 raspberrypi qbittorrent-nox[12479]: stack:
Feb 10 14:12:28 raspberrypi qbittorrent-nox[12479]: <not supported>
Feb 10 14:12:28 raspberrypi qbittorrent-nox[12479]: *************************************************************
Feb 10 14:12:28 raspberrypi qbittorrent-nox[12479]: Please file a bug report at http://bug.qbittorrent.org and provide the following information:
Feb 10 14:12:28 raspberrypi qbittorrent-nox[12479]: qBittorrent version: v4.1.5
Feb 10 14:12:28 raspberrypi qbittorrent-nox[12479]: Caught signal: SIGABRT
Feb 10 14:12:28 raspberrypi qbittorrent-nox[12479]: Stack trace:
Feb 10 14:12:28 raspberrypi qbittorrent-nox[12479]: There were no function names found in the stack trace
Feb 10 14:12:28 raspberrypi qbittorrent-nox[12479]: .Seems like debug symbols are not installed, and the stack trace is useless.
Feb 10 14:12:28 raspberrypi systemd[1]: qbittorrent.service: Main process exited, code=killed, status=6/ABRT
Feb 10 14:12:28 raspberrypi killall[21121]: qbittorrent-nox: geen proces gevonden
Feb 10 14:12:28 raspberrypi systemd[1]: qbittorrent.service: Control process exited, code=exited status=1
Feb 10 14:12:28 raspberrypi systemd[1]: qbittorrent.service: Unit entered failed state.
Feb 10 14:12:28 raspberrypi systemd[1]: qbittorrent.service: Failed with result 'signal

**Comment by wkl001** [comment]
https://qbforums.shiki.hu/index.php/topic,6604.0.html

**Comment by arvidn** [comment]
first of all, if you don't intend to *test* libtorrent, for example patch it, I wouldn't recommend running with invariant checks enabled, nor asserts really. You probably want to run a release build.

second, this assert suggests that libtorrent's cache of file sizes is mismatching what's actually on disk. The most likely cause for this error is that the files on disk were removed or moved.

Technically this isn't a fatal error, libtorrent doesn't really guarantee to function properly when files are yanked out from underneath. Specifically, in this case (when built without invariant checks enabled) the resume file that will be generated will say that these files are still there, even though they have been removed.

**Comment by wkl001** [comment]
I'm sorry for the non-bug.
Could you please tell me how I can tell which build is a release build? I'm new to this, sorry.

I got the impression too that the file was gone. In syslog:
Feb  9 07:53:02 raspberrypi qbittorrent-nox[384]: A file completed download in torrent ...
Feb  9 07:53:02 raspberrypi qbittorrent-nox[384]: Got a torrent finished alert for ...
Feb  9 07:53:02 raspberrypi qbittorrent-nox[384]: Torrent has seed status: no (WHY????)
Feb  9 07:53:02 raspberrypi qbittorrent-nox[384]: Saving fastresume data for ...
Feb  9 07:53:02 raspberrypi qbittorrent-nox[384]: Checking if the torrent contains torrent files to download

Than a number of these:
Feb  9 07:53:02 raspberrypi qbittorrent-nox[384]: Received a tracker reply from udp://exodus.desync.com:6969 (Num_peers = 200)

And than this:
Feb  9 07:55:25 raspberrypi qbittorrent-nox[384]: void BitTorrent::Session::handleFileErrorAlert(libtorrent::file_error_alert*)

Could it be completed that the torrent is not seeding and is than deleted??
https://github.com/qbittorrent/qBittorrent/issues/9924

I'm thinking it's a qbittorrent issue.

**Comment by wkl001** [comment]
I caught up on my reading, sorry.

What's the difference between:
./configure --enable-debug=no    and   ./configure --disable-debug          ?
(https://www.libtorrent.org/building.html/)

**Comment by arvidn** [comment]
> What's the difference between:
> ./configure --enable-debug=no and ./configure --disable-debug ?

I don't think there's a difference. Do you have a reason to believe there is?

**Comment by wkl001** [comment]
No, just making sure.

On qbittorrent I was instructed to use:
./configure --enable-debug --enable-python-binding --with-libgeoip --with-libiconv

libgeoip is decprecated? Got a "WARNING: unrecognized options".
Do I need to use --enable-python-binding or --with-libiconv?

Thanks for the response.

**Comment by arvidn** [comment]
> libgeoip is decprecated?

yes

> Do I need to use --enable-python-binding or --with-libiconv?

only if you want to build the python bindings. for qbt you shouldn't have to do that.
I believe on linux you would want to use `--with-libiconv`

**Comment by wkl001** [comment]
Thanks.
