### ISSUE TITLE
webseeds aren't present when a torrent added by an URL

### ISSUE THREAD

**Issue by Quentin-M** [arvidn/libtorrent#362]
Hey,

I was adding torrents to libtorrent using their HTTP URL and figured out that the torrents that only have webseeds were not downloading at all. The state switched from `downloading metadata` to `downloading` as expected but that's it.

By curling the torrent files and then passing them to libtorrent, it works as expected.

I do use libtorrent throught https://github.com/dmartinpro/libtorrent-go but it should'nt make any difference.

**Comment by aldenml** [comment]
libtorrent needs a proper linking to openssl in order to deal with https. Can you confirm libtorrent-go is doing it?

**Comment by Quentin-M** [comment]
Sorry, it was dealing with HTTP (and not HTTPS) URLs when I was trying to make it work. This can be excluded for the diagnostic.

I can also add that there was no apparent errors showing up in the alerts (alertMask = all_categories) and that I use the synchronous version of `add_torrent`.

Finally, as far as I know, libtorrent-go does link with OpenSSL:
- https://github.com/steeve/libtorrent-go/blob/5ec04775b30c5d58a12d6b4fa6d019733b167805/linux-x64/Dockerfile#L17
- https://github.com/steeve/libtorrent-go/blob/5ec04775b30c5d58a12d6b4fa6d019733b167805/libtorrent_cgo.go#L5

**Comment by arvidn** [comment]
which version of libtorrent do you use?

**Comment by Quentin-M** [comment]
1.0.7

https://github.com/dmartinpro/libtorrent-go/blob/master/linux-x64/Dockerfile#L28

**Comment by aldenml** [comment]
@Quentin-M I saw that somehow openssl is installed and instructed to link in the sed hack, but without giving the right define macro to the compilation, I'm not sure libtorrent is actually using it. In any case, if you are dealing with HTTP, then it is another problem.

**Comment by arvidn** [comment]
do you have a test torrent I could try? (you could send it to me at arvid@libtorrent.org if you'd like)

**Comment by arvidn** [comment]
Could you give this patch a try? https://github.com/arvidn/libtorrent/pull/390

**Comment by arvidn** [comment]
presumed to be fixed by: https://github.com/arvidn/libtorrent/pull/390 and https://github.com/arvidn/libtorrent/pull/394
