### ISSUE TITLE
TORRENT_USE_OPENSSL macro can break ABI compatibility

### ISSUE THREAD

**Issue by mkatsevVR** [arvidn/libtorrent#3627]
libtorrent version (or branch): 1.2

There are several places in the code where the value of this and a few other macros affects the layout of a class in a public header, eg https://github.com/arvidn/libtorrent/blob/libtorrent_1_2_0/include/libtorrent/http_connection.hpp#L165. This will change ABI if user of the library has a different value defined from the one used to compile libtorrent itself. 
One possible solution would be to generate a configuration header with all parameter values at the build time include it from all public headers (eg use cmake configure_file).

**Comment by arvidn** [comment]
currently it's "solved" by propagating these build options to dependees (Jamfile targets and cmake targets do), and for clients not using boost-build or cmake there's also a package-config file where the settings are stored.

However, in addition to this, the ABI should really be encoded in an inline namespace. I think I could fix this (sort of) in 1.2 without breaking ABI backwards compatibility

**Comment by mkatsevVR** [comment]
there are probably some other macros with the same issue, eg TORRENT_USE_I2P a few lines down in my link
is there a full list of macros that are supposed to be passed as compiler flags somewhere?

**Comment by mkatsevVR** [comment]
Is there any reason not to go the configure_file route? I think it would solve the whole ABI issue (including TORRENT_ABI_VERSION) in a safer way than namespaces (with namespaces you need manually keep track of classes that need to be "protected")

To clarify my suggestion, basically at the build time you generate a header like
```
#define TORRENT_ABI_VERSION 2
#define TORRENT_USE_OPENSSL 1
...
```
substituting correct parameter values (using configure_file in cmake or AC_CONFIG_HEADERS in autoconf or a custom python script for other systems) and make it a part of the library installation. Then whenever you need to use such macro in libtorrent, instead of passing it as a compiler flag, you include the configuration header. This way the values are guaranteed to be the same when the library itself is built and when somebody uses it.

**Comment by arvidn** [comment]
> Is there any reason not to go the configure_file route?

Nobody has implemented it. Would you be interested in giving it a stab?

> I think it would solve the whole ABI issue (including TORRENT_ABI_VERSION) in a safer way than namespaces (with namespaces you need manually keep track of classes that need to be "protected")

inline namespaces only solves the problem of memory corruption, it will still cause a link error.
the traditional way of solving this problem is `pkg-config` I would argue, the modern ways of solving it is to use proper build systems, like boost-build or cmake. So, it could be argued that the problem is "solved".

It's not obvious to me that a `config_file` would be a much better solution (but I'm eager to be convinced!)

**Comment by arvidn** [comment]
for the record btw, `http_connection` is not a public type. A better example is `hasher.hpp` and `hasher512.hpp`. However, it's not clear those *should* be public either.

**Comment by arvidn** [comment]
crypto ABI encoded in symbol names with https://github.com/arvidn/libtorrent/pull/3650
unfortunately I don't think I can do this in `RC_1_2` easily, while preserving ABI
