### ISSUE TITLE
Can't download file from Web seed server

### ISSUE THREAD

**Issue by bachlx-bitmark** [arvidn/libtorrent#363]
Hi Arvidn.
I'm using libtorrent and I have an issue with webseed (I using "add_url_seed" function).
I create a Web Seed server and a Client to download file from that server.
But client can't download success any files which has size > 1MB.
Ex: 
Case 1: When client download a file 1.1MB (11100001 byte). I make only two request to server: first request with rang:0-1048575, and second request with rang: 1048576-1110000. And at client progress of downloading  is :0.944663 and it don't increase.
Case 2: When client download a lager file. It make many request but progress of downloading also can't go to 100%. Some time, progress stop at 2%, 60%, 80%...
Case 3: Client will download success file which has size < 1MB. Client will make one request and download done.
This is my code:

Code create Web Seed server (I code by nodejs)
====================================================================
var http = require('http');
var express = require('express');
var fs = require('fs');
var path = require('path');
var downloadRouter = express.Router();
downloadRouter.use(function(req, res) {
	var fileName = req.query.fileName;
	var filePath = path.join(__dirname, 'data/', fileName);
	console.log(req.query);
	console.log(JSON.stringify(req.headers));

	fs.exists(filePath, function(exist) {
		if (exist) {
			fs.stat(filePath, function (error, stats) {
				if (error) {
					res.status(500);
					res.setHeader('Content-Length', '0');
					res.send('File is error!!!!');
				} else {
					var fileSize = stats['size'];
					if (fileSize <=0 ) {
						res.status(500);
						res.setHeader('Content-Length', '0');
						res.send('File is error!!!!');
					} else {
						var startIndex = 0;
						var endIndex = fileSize;
						var range = req.headers['range'];

						var status = 200;
						var headers = {};

						if (range) {
							range = range.substring(6).split('-');
							if (range[0].length > 0) {
								startindex = parseInt(range[0]);
								if (range[1].length > 0) {
									endIndex = parseInt(range[1]) + 1;
								}
							} else if (range[1].length > 0) {
								var temp = parseInt(range[1]);
								if (temp < fileSize) {
									startIndex = fileSize - temp;
								}
							}
							status = 206;
							headers['Content-Range'] = 'bytes ' + startIndex + '-' + endIndex + '/' + fileSize;
						}
						var length =  endIndex - startIndex;
						headers['Accept-Ranges'] = 'bytes ';
						headers['Content-Length'] = length;
						var buffer = new Buffer(fileSize);
						fs.open(filePath, 'r', function(error, fd) {
							if (error) {
								res.status(500);
								res.setHeader('Content-Length', '0');
								res.send('Open file error!!!!');
							}
							fs.read(fd, buffer, startIndex, length, null, function() {
								res.writeHead(status, headers);
								res.write(buffer, "binary");
								res.end();
							});
						});
					}
				}
			});
		} else {
			res.status(404);
			res.setHeader('Content-Length', '0');
			res.send('File is not exist!!!!');
		}

	});
});

var app = express();
app.use('/download', downloadRouter);

app.use('/*', function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  res.status(404);
  res.send('Not Found');
});

var port = 1102;
app.set('port', port);

var server = http.createServer(app);
server.listen(port);

Code to download file:
====================================================================
#include <stdlib.h>
#include "libtorrent/entry.hpp"
#include "libtorrent/bencode.hpp"
#include "libtorrent/session.hpp"
#include <ctime>

using namespace libtorrent;

torrent_handle downloadByTorrentFile(const std::string& torrenFile, libtorrent::session& ses) 
{
	using namespace libtorrent;
	add_torrent_params p;
	p.save_path = "./save";
	p.ti = new torrent_info(torrenFile);

	torrent_handle handle = ses.add_torrent(p);
	return handle;
}

int main()
{
	using namespace libtorrent;
	session ses;
	error_code ec;
	ses.listen_on(std::make_pair(11021, 11021), ec);
	if (ec)
	{
		fprintf(stderr, "failed to open listen socket: %s\n", ec.message().c_str());
		return 1;
	}
	session_settings settings(high_performance_seed());
	settings.seed_time_limit = 365 * 24 * 60 * 60;
	settings.share_ratio_limit = 1e10f;
	settings.seed_time_ratio_limit = 1e10f;
	settings.cache_size = 3 * 65536;//3 Gb
	settings.ban_web_seeds = false;
	ses.set_settings(settings);
	ses.set_max_connections(3000);
	ses.set_max_uploads(3000);

	torrent_handle handle = downloadByTorrentFile("text.torrent", ses);
	handle.add_url_seed("http://localhost:1102/download/file?fileName=text.txt");

	double duration;
	std::clock_t start;
	start = std::clock();
	while (true) {
		duration = ( std::clock() - start ) / (double) CLOCKS_PER_SEC;
		if (duration > 0.5) {
			start = std::clock();
			std::cout<< " progress :" << handle.status().progress;
			std::cout<< " state :" << handle.status().state <<std::endl;
			if (handle.status().progress == 1) {
				break;
			}	
		}
	}
}

Code create torrent file:
====================================================================
#include "libtorrent/bencode.hpp"
#include "libtorrent/create_torrent.hpp"
#include "libtorrent/file.hpp"
#include "libtorrent/file_pool.hpp"
#include <boost/bind.hpp>

using namespace libtorrent;

bool file_filter(std::string const& f)
{
	if (filename(f)[0] == '.') return false;
	fprintf(stderr, "%s\n", f.c_str());
	return true;
}

void print_progress(int i, int num)
{
	fprintf(stderr, "\r%d/%d", i+1, num);
}

int main() {

	int flags = 0;
	std::string full_path = "./text.txt";
	std::string outfile = "text.torrent";
	int piece_size = 0;
	int pad_file_limit = -1;
	
	file_storage fs;
	add_files(fs, full_path, file_filter, flags);
	create_torrent t(fs, piece_size, pad_file_limit, flags);

	error_code ec;
	set_piece_hashes(t, "./", ec);
	if (ec)
	{
		fprintf(stderr, "%s\n", ec.message().c_str());
		return 1;
	}
	
	std::vector<char> torrent;
	bencode(back_inserter(torrent), t.generate());
	FILE* output = fopen(outfile.c_str(), "wb+");	
	if (output == NULL)
	{
		fprintf(stderr, "failed to open file \"%s\": (%d) %s\n"
			, outfile.c_str(), errno, strerror(errno));
		return 1;
	}
	fwrite(&torrent[0], 1, torrent.size(), output);
	fclose(output);

	return 0;
}

Thanks!!!

**Comment by arvidn** [comment]
I take it you're using libtorrent 1.0.7, right?

**Comment by bachlx-bitmark** [comment]
Hi Arvidn.
I'm using libtorrent 1.0.6.0.
Thanks!

**Comment by arvidn** [comment]
are you always testing with a single-file torrent? Does your web server support keep-alive?
There's a known issue with servers that don't support keep-alive together with multi-file torrents (specifically where one block spans across a file boundary). Would it be easy for you to provide an example torrent I could test? (you could send it to me at arvid@libtorrent.org if you'd like)

**Comment by bachlx-bitmark** [comment]
Hi Arvidn.
I'm using and testing for case single file. And server is support keep-alive (https://nodejs.org/api/http.html#http_event_request).
I will send to you my example.
Thanks!

**Comment by arvidn** [comment]
if I can't reproduce this issue I'm inclined to close it. There are quite extensive unit tests and system tests to download via a web seed, and there are some known issues with multi-file torrents in the 1.0.x branch (as I explained above). That doesn't preclude there being bugs still of course, but I don't have a lot of time to put into reproducing this (especially given how little details of the problem you have provided). If you can reproduce it, either send me a torrent file that will exhibit the problem for me, or provide more detailed libtorrent logs and wireshark dumps of the traffic that I can take a look at

**Comment by bachlx-bitmark** [comment]
Hi Arvid.
Please keep this issue for a while longer, I will try to provide a better sample for you to be easier to reproduce the problems I have. Thanks for your patient.

**Comment by bachlx-bitmark** [comment]
Hi Arvid.
I had debug that I return wrong header in response at server.
```headers['Content-Range'] = 'bytes ' + startIndex + '-' + endIndex + '/' + fileSize;```
Must be:
headers['Content-Range'] = 'bytes ' + startIndex + '-' + (endIndex -1) + '/' + fileSize;

Sorry about making you lose time for this issue.
I close this issue.

Thanks for your support.
