### ISSUE TITLE
Python torrent_handle.set_flags() fails when flags == 1

### ISSUE THREAD

**Issue by aresch** [arvidn/libtorrent#3635]
**Please provide the following information**

libtorrent version (or branch): RC_1_2

platform/architecture: amd64

compiler and compiler version: gcc 8.2.1

Cannot set the 1 flag (seed_mode).

```python
>>> h
<libtorrent.torrent_handle object at 0x7fccee7fc2f0>
>>> h.flags()
24
>>> h.set_flags(1)
>>> h.flags()
24
>>> h.set_flags(9, 1)
>>> h.flags()
24
>>> h.set_flags(1, 9)
>>> h.flags()
16
>>>
````

**Comment by aresch** [comment]
Ok, I see, the only way to set seed_mode is when adding the torrent to the session:

https://github.com/arvidn/libtorrent/blob/RC_1_2/src/torrent.cpp#L348

So this makes sense considering the flag's purpose.  Should libtorrent raise an error when trying to modify this flag during runtime? Should it even be a flag if it's read-only? Maybe having it's presence in the torrent_status would be enough.

**Comment by arvidn** [comment]
I'm open to suggestions. It should definitely be documented that this flag cannot be changed once the torrent has been added. I'm not sure reporting an error when it's attempted makes that much sense either. Perhaps an assert in debug mode.

Note that it is possible to *clear* the `seed_mode` flag though.

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/3646

**Comment by aresch** [comment]
I'm not sure what would be better either without over-engineering the whole thing. The documentation update is probably good enough.
