### ISSUE TITLE
[Feature Request] Support for get_torrent_status / refresh_torrent_status in the Python bindings

### ISSUE THREAD

**Issue by karamanolev** [arvidn/libtorrent#3639]
Hello, for large number of torrents the manual recommends the usage of `session::get_torrent_status()` and `session::refresh_torrent_status()` for querying and updating torrent statuses. It seems those are missing from the Python bindings. Would it be possible to add them?

**Comment by arvidn** [comment]
actually, the manual (is supposed to) recommend using `post_torrent_updates()`. I would like to correct the documentation, could you point me to where it suggests `refresh_torrent_status()`?

That said, these functions should also be added to the python binding.

**Comment by arvidn** [comment]
I see, `tuning.rst` makes this recommendation. I will update it!

**Comment by arvidn** [comment]
documentation updated: https://github.com/arvidn/libtorrent/pull/3644

**Comment by arvidn** [comment]
@karamanolev would you mind giving this patch a try? https://github.com/arvidn/libtorrent/pull/3645

(it's against libtorrent-1.1.11, which I assume you're using)

**Comment by karamanolev** [comment]
@arvidn Thanks so much for the patch! Testing now and I'll report when done.

As for `post_torrent_updates` vs `get_torrent_status`/`refresh_torrent_status` - my understanding from reading the manual several times is that `post_torrent_updates` only sends an alert when the status changed (checking -> downloading -> seeding, etc). If one wants to track e.g. download progress then `refresh_torrent_status` needs to be used. My use case is that I want to frequently get updates for torrents that are:

- Downloading (to monitor progress).
- Uploading, meaning currently sending data, to monitor speeds.

The others I don't care that much about, since nothing is probably happening. I need that in the hopes of seeding some huge number of torrents (100K+). I'm thinking about get_torrent_status and using a predicate that checks for these two things. Is that correct? I feel it should be a common enough case to be worth mentioning the manual, maybe?

**Comment by arvidn** [comment]
> my understanding from reading the manual several times is that `post_torrent_updates` only sends an alert when the status changed (checking -> downloading -> seeding, etc). If one wants to track e.g. download progress then `refresh_torrent_status` needs to be used.

*any* property of a torrent changing will flag it to be included in the next `post_torrent_updates()`. This includes download progress and up- and download rates.

The main possible down side is that there's no predicate to filter, so you'll get all torrents that are active (so long as they have the subscribe flag set, which they do by default).

calling `get_torrent_status()` with a predicate is still *O(n)*, which won't scale well with many torrents. Internally, libtorrent still has to traverse the whole torrent list and apply the predicate. On the other hand, `post_torrent_updates()` is *O(1)*, as torrents register themselves for inclusion when they change any of their states.

**Comment by karamanolev** [comment]
@arvidn It fails to compile for me. I did `git reset --hard 516e1cbf634a8f76f59d254936c4eca9ac4d3761`. I'm on a super fresh Ubuntu 18.10 with the Boost from `apt install libboost-all-dev` version `Version: 1.67.0.0ubuntu1`. I'm compiling for Py 3.7. Here's the configure: `PYTHON=/usr/bin/python3.6 ./configure --enable-examples --enable-python-binding --with-boost-python=boost_python3`. Configure results and compilation results are in this gist: https://gist.github.com/karamanolev/184a6132e686d97960c5c6a56357841d

**Comment by arvidn** [comment]
https://blog.libtorrent.org/2012/01/seeding-a-million-torrents/

**Comment by karamanolev** [comment]
@arvidn I really appreciate the link. It's a shame I missed it, for which I apologize.

I'd appreciate it if you could share your expert opinion on what I did wrong with compiling this patch.

**Comment by arvidn** [comment]
the patch didn't work. I just updated it (force pushed, so you may need `git reset origin/python-get_torrent_stats-1.1`)

**Comment by arvidn** [comment]
this may be a more relevant post actually: https://blog.libtorrent.org/2011/11/scalable-interfaces/

**Comment by karamanolev** [comment]
@arvidn The new version seems to work. Thanks!

My only suggestion is, if you feel like it, to add the default argument values for the `flags` argument, which is present in C++ and not in the Python bindings.

**Comment by arvidn** [comment]
landed in `RC_1_1` and about to be merged into `RC_1_2`
