### ISSUE TITLE
Ideas to support an additional communication protocol

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#3653]
libtorrent: `master`

How to effectively incorporate WebRTC data channel as another way to communicate peers?

Hi @arvidn, I was navigating the  source code for clues about how to properly do this. I started with the exercise of categorizing the peers per protocol, but I soon realized that peers using data-channel _are_ better modeled with the current `bt_peer_connection`. In fact, nothing prevents the stacking of protocols, and use `ssl_stream` over it.

My idea will not trigger any OOP-style reengineering, but just use what's in place, that so far is working very very good.

I think that if `webrtc_stream` and `webrtc_peer : torrent_peer` are created, you are actually very close to support this data-channel communication, and all the integration changes are very limited to what I call the  `webrtc_manager` that provides you the streams (similar to `utp`).

This is not all, but I want to have some feedback in the approach.

Ref: https://github.com/arvidn/libtorrent/issues/223

**Comment by arvidn** [comment]
I definitely think it's worth exploring this path. It is kind of the "obvious" way of doing it (at least how I envisioned it be done at some point).

What I would be a bit worried about are:

1. `peer_connection` has a socket in it, and it's possible a lot of logic assumes that this socket is valid and in use
2. proxy support (SOCKS5) is implemented in the libtorrent socket layer. Granted, this is a luxury feature.
3. Rate limit support is tightly integrated with `peer_connection` and I think the socket.
4. `remote()` and `local_endpoint()` are not virtual, they rely on `m_socket` being in use

**Comment by arvidn** [comment]
when you say "stack protocols", do you mean a webRTC library that lets you use your own socket?

**Comment by aldenml** [comment]
good, I will continue my research on it. The "socket" for what I see is the `aux::socket_type`, and if I'm correct, that's the one to enhance to support one more option.

When I said "stack protocols", maybe that wasn't the best name for it, but I was referring to how you use SSL here `ssl_stream<utp_stream>`. I imagine you can have  `ssl_stream<webrtc_stream>` too.

One issue with the stream oriented `webrtc_stream` concept, is that WebRTC datachannel is more what I call a "callback oriented" interface. And since they run in another thread, then a trivial emulation needs some sort of synchronization, which in turn could impact the performance.

**Comment by arvidn** [comment]
Yes, as long as a webRTC data channel behaves like a TCP stream, and has a similar enough interface, that should be possible. You just have to post completions back onto the main thread

**Comment by ExE-Boss** [comment]
needinfo?(@lgrahl): How does RAWRTC handle multi&#x2011;threading?

**Comment by lgrahl** [comment]
RAWRTC is single-threaded and uses a tiny event loop based on whatever is available on the system.

**Comment by lgrahl** [comment]
> as long as a webRTC data channel behaves like a TCP stream

It doesn't. Data channels are based on SCTP which is message-oriented. There are several ways to mimic just a byte stream based on that. But before proceeding with it, the question should be:

1. Is the plan to use data channels as an additional transport, or
2. is the plan, more concretely, to support webtorrent?

Because IIRC the latter has some specific requirements (i.e. it's basically a protocol) that should be considered when designing interfaces.

**Comment by aldenml** [comment]
Hi @lgrahl, the plan (if there is such a thing :) is to support WebTorrent, but in order to do that, adding data channels as a transport for BitTorrent needs to happen. For what I understand (and commented here https://github.com/arvidn/libtorrent/issues/223#issuecomment-446715455), they are the same at this level. The difference is in how you gather the peers via a WebTorrent tracker.

**Comment by arvidn** [comment]
I think one pertinent question is: does WebTorrent use more than one channel?
It would make perfect sense to do so (in fact, I've been playing with the idea of supporting sctp for regular bittorrent, just to allow the control messages to be sent out-of-band with payload).

If it does, that would post a challenge to the current socket abstraction, which is a single stream

**Comment by aldenml** [comment]
When you say "more than one channel", are you referring to what's happening under the hood? or at the WebRTC API level?

**Comment by arvidn** [comment]
I meant "stream". What is called a stream in SCTP. i.e. independent streams of data over a single connection

**Comment by aldenml** [comment]
I have no idea if that's the case

**Comment by lgrahl** [comment]
I'm quite sure they don't use more than one channel but code digging or asking them would be required to confirm this. However, I agree with @arvidn that there are some potential enhancements where this feature could be leveraged even if they don't make use of it today.
