### ISSUE TITLE
Getting hash failed with custom storage

### ISSUE THREAD

**Issue by elgatito** [arvidn/libtorrent#3656]
Hello,
I have made custom storage which stores pieces in memory, much more like it was in documentation.
https://github.com/ElementumOrg/libtorrent-go/blob/master/memory_storage.hpp#L233

Evertyhing looked good, but then I noticed that some pieces are failing with hash_failed_alert. 
That is fine since peers can send everything, but then I noticed that I have one test torrent (with 16mb pieces), and when I run it - hash fails on same pieces. 

When I switch to default storage - pieces are passing hashes fine.
There are no options with custom storage. 

I have tried to see if we really get all writes, and it looks fine. Writes and reads are passed, all lengthes are there, but same piece always fail.

In my test torrent, I download 10 first pieces (from hundreds), and it always fail with pieces 6 and 7.

I don't know where to look. Spent a log of time to find the problem, but no progress...

libtorrent version (or branch): RC_1_1

platform/architecture: Linux x64

compiler and compiler version: gcc/swig

**Comment by elgatito** [comment]
I could treat this as a storage implementation bug in readv or writev functions, but there is no difference in pieces processing and those are not last/first pieces, and it happens only with the same pieces on same torrent.

But strange that with default storage there are no problems with hashing...

**Comment by elgatito** [comment]
Interesting, with `cache_size = -1` issue is not there, removing `cache_size` and getting hailed hash again.

**Comment by elgatito** [comment]
I see that when I use big cache, readv is not coming to custom storage. Probably getting all pieces from the cache?
Still not clear if it's readv/writev problem or the problem in the data requestor code.

**Comment by elgatito** [comment]
Okay, thinking further. 
If there 'd be a problem in readv/writev implementation -  I would see problems in some specific cases of randomly, but I see same behavior again and again.

**Comment by arvidn** [comment]
are you sure your `readv()` returns the same data as your `writev()` writes to them?
you could write a unit test for your storage that writes every block with some specific pattern, and then reads it back to ensure it gets the same pattern back.

**Comment by elgatito** [comment]
@arvidn It's pretty much simple and I still can't figure how it can fail with specific pieces only.

writev
```
int file_offset = offset;
                        int n = 0;
                        for (int i = 0; i < num_bufs; ++i)
                        {
                                std::memcpy(&buffers[pieces[piece].bi].buffer[file_offset], bufs[i].iov_base, bufs[i].iov_len);
                                file_offset += bufs[i].iov_len;
                                n += bufs[i].iov_len;
                        };
```

readv:
```
int file_offset = offset;
                        int n = 0;
                        for (int i = 0; i < num_bufs; ++i)
                        {
                                std::memcpy(bufs[i].iov_base, &buffers[pieces[piece].bi].buffer[file_offset], bufs[i].iov_len);
                                file_offset += bufs[i].iov_len;
                                n += bufs[i].iov_len;
                        };
```

**Comment by arvidn** [comment]
perhaps only those pieces that trigger your logic to handle multiple iovecs fail for instance, or where the buffer sizes are odd. You really should be writing tests for your code.

**Comment by elgatito** [comment]
This is a swig project, so not too easy to test.

I store piece entirely, so buffer (vector) length = piece length, I only read/write blocks from/to vector.
And you know, hash checks send clear requests for reading blocks, starting always from 0 and moving on with +=block_size.

I will try with debug enabled, maybe there is something usefull.

**Comment by elgatito** [comment]
I have tried more settings (use_read_cache=false, for example, cache_size=0).
When I leave download only pieces that are failing - they are passing hash check fine. 

When I download many pieces, passed hash pieces have `readv` calls with 1 buffer in a call. Calls coming from `disk_io_thread.cpp:2562`:
```
ret = j->storage->get_storage_impl()->readv(&iov, 1, j->piece
							, offset, file_flags, j->error);
```

Failed hash pieces have same calls, but after 1 buffer calls it gets also calls with 32 buffers (offset from 0 to the last one), coming from:
```
(gdb) bt
#0  libtorrent::memory_storage::readv (this=0x7fffc0027560, bufs=0x7fffcdffb8c0, num_bufs=32, piece=6, offset=0, flags=<optimized out>, ec=...)
    at /home/elgato/go/src/github.com/ElementumOrg/libtorrent-go/memory_storage.hpp:251
#1  0x0000000001173015 in libtorrent::disk_io_thread::do_read (this=0x7fffc803dca0, j=0x7fffc03360b0, completed_jobs=...) at disk_io_thread.cpp:1270
#2  0x000000000116fb60 in libtorrent::disk_io_thread::perform_job (this=this@entry=0x7fffc803dca0, j=j@entry=0x7fffc03360b0, completed_jobs=...)
    at disk_io_thread.cpp:1129
#3  0x000000000116fd91 in libtorrent::disk_io_thread::execute_job (this=this@entry=0x7fffc803dca0, j=j@entry=0x7fffc03360b0) at disk_io_thread.cpp:3334
#4  0x0000000001173520 in libtorrent::disk_io_thread::thread_fun (this=0x7fffc803dca0, thread_id=0, type=libtorrent::disk_io_thread::generic_thread, w=...)
    at disk_io_thread.cpp:3386
#5  0x000000000117628a in boost::_mfi::mf3<void, libtorrent::disk_io_thread, int, libtorrent::disk_io_thread::thread_type_t, boost::shared_ptr<boost::asio::io_context::work> >::operator() (a3=..., a2=libtorrent::disk_io_thread::generic_thread, a1=0, p=<optimized out>, this=<optimized out>)
    at /usr/local/include/boost/bind/mem_fn_template.hpp:393
#6  boost::_bi::list4<boost::_bi::value<libtorrent::disk_io_thread*>, boost::_bi::value<int>, boost::_bi::value<libtorrent::disk_io_thread::thread_type_t>, boost::_bi::value<boost::shared_ptr<boost::asio::io_context::work> > >::operator()<boost::_mfi::mf3<void, libtorrent::disk_io_thread, int, libtorrent::disk_io_thread::thread_type_t, boost::shared_ptr<boost::asio::io_context::work> >, boost::_bi::list0> (a=<synthetic pointer>..., f=..., this=<optimized out>)
    at /usr/local/include/boost/bind/bind.hpp:463
#7  boost::_bi::bind_t<void, boost::_mfi::mf3<void, libtorrent::disk_io_thread, int, libtorrent::disk_io_thread::thread_type_t, boost::shared_ptr<boost::asio::io_context::work> >, boost::_bi::list4<boost::_bi::value<libtorrent::disk_io_thread*>, boost::_bi::value<int>, boost::_bi::value<libtorrent::disk_io_thread::thread_type_t>, boost::_bi::value<boost::shared_ptr<boost::asio::io_context::work> > > >::operator() (this=<optimized out>) at /usr/local/include/boost/bind/bind.hpp:1294
#8  boost::asio::detail::posix_thread::func<boost::_bi::bind_t<void, boost::_mfi::mf3<void, libtorrent::disk_io_thread, int, libtorrent::disk_io_thread::thread_type_t, boost::shared_ptr<boost::asio::io_context::work> >, boost::_bi::list4<boost::_bi::value<libtorrent::disk_io_thread*>, boost::_bi::value<int>, boost::_bi::value<libtorrent::disk_io_thread::thread_type_t>, boost::_bi::value<boost::shared_ptr<boost::asio::io_context::work> > > > >::run (this=<optimized out>)
    at /usr/local/include/boost/asio/detail/posix_thread.hpp:86
#9  0x0000000001175dd8 in boost::asio::detail::boost_asio_detail_posix_thread_function (arg=<optimized out>)
    at /usr/local/include/boost/asio/detail/impl/posix_thread.ipp:74
#10 0x00007ffff76306db in start_thread (arg=0x7fffcdffc700) at pthread_create.c:463
#11 0x00007ffff6da388f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

After last call with 32 buffers (to get last piece of data) I get failed_hash_alert.

**Comment by elgatito** [comment]
I have changed reversed priorities for downloaded pieces and now failed pieces are from the other size of the list. I am also checking whether all blocks were written before reading them, and they are all there.

**Comment by elgatito** [comment]
Finally. Found a problem on my side. Not readv/writev, but a vector initialization typo.

Sorry for disturbing!
