### ISSUE TITLE
Add support for HSTS and HPKP

### ISSUE THREAD

**Issue by lesderid** [arvidn/libtorrent#367]
[HTTP Strict Transport Security (HSTS)](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) and [HTTP Public Key Pinning (HPKP)](https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning) are two security mechanisms that accompany HTTPS. Supporting these would be very useful for securely communicating with a HTTPS-based tracker.

If HSTS is implemented, adding support for [preloading](https://hstspreload.appspot.com/) would be highly desirable.

**Comment by arvidn** [comment]
what's the point of supporting HSTS? there's no human involved that can accidentally forget to say https here. what kind of attack would it protect against here?

**Comment by lesderid** [comment]
Consider a scenario where a (non-public) tracker is compromised and .torrent files are suddenly served with non-HTTPS announce URLs. Another reason this could be useful is to avoid (malicious) policy changes by tracker admins, i.e. lowering their security standards by dropping HTTPS support.

**Comment by arvidn** [comment]
if one doesn't trust the source of .torrent files, having a setting in the client would make more sense, no?

I see your point about actually specifying an http URL for adding a .torrent file, I forgot about that use of HTTP.

**Comment by lesderid** [comment]
I'm not sure what you mean with having a setting in the client. Could you elaborate?

**Comment by arvidn** [comment]
there could be a setting in the client blocking any announce to non SSL trackers (udp and HTTP). If you don't trust the person making the .torrent file (or the tracker admin sanitizing/verifying it) I don't see how HSTS would help you. The person making the .torrent file could simply change the hostname of the tracker _as_well_as downgrading the protocol to plaintext HTTP.

**Comment by lesderid** [comment]
A protocol change is much less obvious in most clients than a host name change.

**Comment by Breathe-in** [comment]
I'm in favor of implementing HSTS. When a tracker implements HTTPS there are a lot of users with old torrents still using HTTP. HSTS can be used to indicate that those older torrents now can use HTTPS as well without needing interaction of the end-user.

Modified example from [w3c](https://w3c.github.io/webappsec-upgrade-insecure-requests/#preference)

A client that supports this document’s upgrade mechanism requests http://example.com/ as follows:
```
GET /announce HTTP/1.1
Host: example.com:1337
Upgrade-Insecure-Requests: 1
...
```
The server parses the preference, notices that the user’s client can deal well with upgrade requests, and therefore responds to the request by redirecting the user to a secure version of the resource they are requesting:
```
HTTP/1.1 307 Moved Temporarily
Location: https://example.com:8443
```
The client connects to this new endpoint:
```
GET /announce HTTP/1.1
Host: https://example.com:8443
...
```
The HTTPS capable server returns with the HSTS header
```
HTTP/1.1 200 OK
Strict-Transport-Security: max-age=15768000
... bencoded response ..
```
Upon receiving the HSTS header along with a valid tracker response on a HTTPS connection, all future connections on the same domain+port are forced to use HTTPS for the duration of "max-age". If the domain has not changed in the HTTP upgrade redirect the HSTS can be enforced with a redirect from the original http port to the https port for future connections on this domain.

Within a period of days before max-age expiring, the client can send the ```Upgrade-Insecure-Requests``` header along requests to signal the server that a new HSTS header is needed to stop it from expiring.

Im not in favor of:
- HPKP, it is now obsolete now.
- preloading, HTTPS capability of tracker service is not related to the HTTPS capability of any website service running on the same domain. It enforces the 443 port for all HTTP traffic which might not be the port the (https) tracker runs on.

**Comment by arvidn** [comment]
The only benefit I can see is that if a tracker upgrades to HTTPS. all other torrents that use the same tracker can also automatically upgrade to HTTPS, without also having to go through an HSTS handshake.

The question then is, where is this information stored? Would it persist across sessions? Maybe the tracker URLs would just be re-written in the resume data.

**Comment by Breathe-in** [comment]
If implemented according to the HSTS standard, it should be persisted across sessions with respect to "max-age".  This can be  accomplished by maintaining a txt/csv/json file with the list of entries (domain, expiry date). The save_path can become a setting. If the save_path is not set, the cache will not persist across sessions. A user/developer can manipulate this file to clear the HSTS state in case of a mistake.

Rewriting the URIs is not sufficient
- "max-age" should be respected
- the HSTS mechanism should also work for new torrents that are added.

Note that I'm willing to implement it as part of a HTTP/1.1 enhancement that I'm investigating (Those details are out of scope of this issue).
