### ISSUE TITLE
TypeError accessing sock_type on listen failed/succeeded from Python bindings

### ISSUE THREAD

**Issue by karamanolev** [arvidn/libtorrent#3682]
libtorrent version (or branch): 1.1.11.0 (MacOS using `brew install libtorrent`)

platform/architecture: MacOS / Python Bindings / Python 3.7.2

compiler and compiler version: Whatever brew uses to compile it (I don't think it's relevant)

Accessing `sock_type` on a `listen_succeeded_alert` or a `listen_failed_alert` results in:

    {TypeError}No to_python (by-value) converter found for C++ type: libtorrent::listen_failed_alert::socket_type_t

**Comment by arvidn** [comment]
does this fix it? https://github.com/arvidn/libtorrent/pull/3811

**Comment by karamanolev** [comment]
@arvidn Yes. Thank you.
