### ISSUE TITLE
Removing torrent triggers assertion

### ISSUE THREAD

**Issue by mathijs727** [arvidn/libtorrent#3689]
libtorrent version (or branch): 1.2 (Github release source code)
platform/architecture: Windows 10 / x64 (AMD Zen+)
compiler and compiler version: MSVC 19.16.27027.1

I have an issue where removing a torrent causes libtorrent to crash (in debug mode) due to a failed assertion.
The assertion triggered is `TORRENT_ASSERT(m_added== true);` on line 345 of `torrent.hpp`.

Initially when the torrent is added to the session `m_added` is set to true (like expected), however `torrent::on_torrent_download` asks the session to delete itself (`m_ses.remove_torrent_impl(me, {});` on line 437 of `torrent.cpp`) which sets `m_added` to false.
Looking at the comments it seems like the torrent removes itself from the session and then adds itself again.
However, the m_added flag is not reset properly causing a subsequent call to `session.remove_torrent(...)` to trigger the assertion.

**Comment by arvidn** [comment]
first of all, keep in mind that adding torrent files via http:// URL is deprecated, and will be removed in the next major release (it's also disabled if you build with deprecated functions disabled).

Could you give this patch a try?

https://github.com/arvidn/libtorrent/pull/3691

**Comment by mathijs727** [comment]
Thank you for the patch, it fixed the issue.

I am porting some old code from Python to C++ hence the outdated code.
If adding torrents through URL parameter is deprecated what would be the correct way to add a *.torrent file that is hosted on a webserver (Ubuntu images for example)?

**Comment by arvidn** [comment]
you can download the .torrent file using python facilities (`urllib` for instance) and then add it to libtorrent. You should be able to create a `torrent_info` without, and add it to the session, saving it to a file too.
