### ISSUE TITLE
Questions about magnetic links   

### ISSUE THREAD

**Issue by fourLA** [arvidn/libtorrent#3696]
Hi, 
I am an iOS app developer.I have a problem when using libtorrent 1.2 .
The magnetic link must be added with "tr" before it can be downloaded. Like "magnet:?xt=urn:btih:8b8e5f0177df8daa48c6ef720523fe52011bd214&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce" can be downloaded, but "magnet:? Xt=urn:btih:8b8e5f0177df8daa48c6ef720523fe52011bd214" can't.
Do I need to do some configuration?
thanks！

**Comment by arvidn** [comment]
my DHT tracker isn't up and running right now (the hosting provider shut down the service I was using). So you'd have to set a different DHT router than the default. For instance, `router.bittorrent.com:6881`

**Comment by fourLA** [comment]
thank you for your reply!   
The problem now is that sometimes it can be downloaded and sometimes it can't, even with the same magnetic link. How should I configure it?

This is my test code:
--------
        lt::settings_pack pack = lt::default_settings();
        NSArray * arr = @[@"router.utorrent.com:6881",
                          @"router.bittorrent.com:6881",
                          @"dht.transmissionbt.com:6881",
                          @"router.bitcomet.com:6881",
                          @"dht.aelitis.com:6881",
                          @"router.silotis.us",
                          @"dht.libtorrent.org:25401"];
        NSString * nodes = [arr componentsJoinedByString:@","];
        pack.set_str(lt::settings_pack::dht_bootstrap_nodes, [nodes cStringUsingEncoding:NSUTF8StringEncoding]);

        lt::session _session = lt::session(pack);
        std::string sUrl([magnet cStringUsingEncoding:NSUTF8StringEncoding]);
        
        add_torrent_params params = lt::parse_magnet_uri(sUrl);
        params.save_path = [NSTemporaryDirectory() cStringUsingEncoding:NSUTF8StringEncoding];
        torrent_handle handle = _session.add_torrent(params);
----------
thanks！

**Comment by 11aihua** [comment]
@fourLA  Hello, I have encountered the same problem, have you solved it?
Hopping for your reply!
Thank you!
