### ISSUE TITLE
connection_speed behavior

### ISSUE THREAD

**Issue by elgatito** [arvidn/libtorrent#3699]
Hello,

I'm using branch RC1_1, and was dealing with an issue. reported by users.

How it looks:
When low-seed magnet is added and gets metadata, `num_complete` shows about 20, but `num_seeders` shows bigger number from the start, like 22. So it looks like `22/20` and no download at all, then, in a minute or so, `num_seeders` decreases, download is increasing little by little. I have tried same magnet on qBitTorrent and it was downloading fine, starting from `0/20` and gaining speed pretty fast.

Test magnet: `magnet:?xt=urn:btih:49f48fe6edb3fb01a71a3f481210af4ca11c97e7&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce`

What I found:
We had a default `connection_speed` setting, being set to `500`, and when I decreased to `200` - it still acted the same, but when I dropped it to `40` or `30`, it acted just like in qBitTorrent.

So I have expected more aggressive behavior with high connection_speed, but got opposive result.

Is that normal? Or is that a bug?

Thanks

**Comment by elgatito** [comment]
It looks like a bug in connection limit decider or something like that.
I'd expect trying all possible peers when connection_speed is very big.
But it acts in an opposite way. Everything hangs for 30 seconds or more, and only after that period it starts to init connections.

**Comment by elgatito** [comment]
User, that reported about this issue, says these settings make his torrent start connecting to peers right after metadata has been received
```
torrent_connect_boost=0
smooth_connects=false
connections_limit=200
connection_speed=100
```

I was trying to investigate his "all-alerts" log, but don't know what to search for. I see dht requests being sent right after metadata is here. 

What can I investigate to help with this issue?

**Comment by elgatito** [comment]
I was looking into this.

I enabled all the alerts, picked magnet without trackers. 
I see outgoing dht alerts, then received peers list.
Stats look like `Seeds 0/5, Peers 0/40` and peers is raising since other responses come.

But no connections are made (or I can't see them). 
Having `0` in peers/seeds for at least 10 seconds. Then at the same second I see `5/5` in seeds and block are requested and download is ongoing.

**Comment by arvidn** [comment]
ideally you would want to enable `torrent_log` alerts and possibly `session_stats` alerts. the session stats can be run through the `tools/parse_session_stats.py` tool to generate nice graphs. However, if there are literally 0 connection attempts being made, it's not clear that those stats would be helpful.

How could I reproduce this myself? Does it only happen when you get the peers from the DHT?
and only when you set `connection_speed` to a large number, like 200?
did you try flipping `torrent_connect_boost` on and off, to see if it affected things?

**Comment by elgatito** [comment]
Can't make a small example code to test this (I'm using libtorrent through swig bindings).

Yesterday I have caught almost the same issue (after torrent starts - nothing happens for a long time).
That was when I set max_in_requests to about 1000 and max_out_requests ti about 15000.

**Comment by arvidn** [comment]
are you confident that the `connection_speed` is causing the issue? If you only see the issue happen very rarely, you would need to run a lot of tests to establish a causation. But it also means that `connection_speed` *tend* to cause this issue, if it doesn't happen every time

**Comment by arvidn** [comment]
if you get a chance, could you test a newer version of libtorrent, from the 1.2-series?

**Comment by elgatito** [comment]
The library is used through the SWIG bindings, so it needs quite a lot of time to migrate bindings to 1.2.
Not sure if I could do that.

1.2 should be better in terms of a speed (in general)?
