### ISSUE TITLE
[MacOS 10.11.6] crash due to EXC_BAD_INSTRUCTION

### ISSUE THREAD

**Issue by AlexanderVitiuk** [arvidn/libtorrent#3708]
libtorrent 1.2
MacOS X 10.11.6 (15G22010)

Built libtorrent library and its examples on MacOS 10.13.6.
Own project which used it and libtorrent examples works fine on build Mac and other Mac with the same OS. 
But on older Mac (10.11.6) i get crashes somewhere in session constructor.
Unfortunately i have no ability to debug it on that Mac, but i can get crash reports.
Attached 2 crash reports: оne from example client_test (was launched as ./client_test -s ~Documents test.torrent), second from my application. 
[crash.zip](https://github.com/arvidn/libtorrent/files/2965600/crash.zip)

**Comment by arvidn** [comment]
are you building with `-mmacosx-version-min=` or `MACOSX_DEPLOYMENT_TARGET` with your oldest MacOS version specified?

**Comment by AlexanderVitiuk** [comment]
You are right, it was my mistake - it was built by default with target 10.13.
Rebuilt with -mmacosx-version-min=10.9 and now it is works fine for me.
