### ISSUE TITLE
Non-traditional shared library versioning

### ISSUE THREAD

**Issue by yurivict** [arvidn/libtorrent#3711]
The version ```1.2.0``` installs:
```
lib/libtorrent-rasterbar.so
lib/libtorrent-rasterbar.so.1.2.0
lib/libtorrent-rasterbar.so.10
```

The third file should be named ```lib/libtorrent-rasterbar.so.1.2``` or ```lib/libtorrent-rasterbar.so.1``` depending on SONAME.

**Comment by arvidn** [comment]
I believe the SONAME is 10, doesn't that make it named correctly?

**Comment by yurivict** [comment]
The convention is that the library is named: ```libxx.so.A.B.C```, the link would be ```libxx.so.A.B``` or ```libxx.so.A```, which is also the SONAME.
Your SONAME is ```libtorrent-rasterbar.so.10```, but the ```A``` part doesn't match the one in ```libxx.so.A.B.C``` which is non-standard. There should be no need to have a special schema like this.
