### ISSUE TITLE
Error with windows symlinks

### ISSUE THREAD

**Issue by amirotin** [arvidn/libtorrent#373]
Hi. I've some problems with torrents if i move files and create symlink.
As i understand - the problem is with `S_ISLNK` function, that doesn't work with windows symlinks.

Maybe it is possible to add some functions only for windows to work with files? i.e. `GetFileAttributesExW`?

**Comment by amirotin** [comment]
I think the best way is to check for `FILE_ATTRIBUTE_REPARSE_POINT` flag in file attributes and  `IO_REPARSE_TAG_SYMLINK` flag in `dwReserved0`

**Comment by arvidn** [comment]
you're talking about libtorrent looking for files in the download directory, and those files (or a directory in that path) being a symbolic link, and libtorrent not following the link correctly?

I was under the impression that reparse points and junctions are slightly different than symlinks, I can't say I have a very clear understanding of the distinctions though. However, primarily I would expect any symbolic link-like file to be transparent to the application. i.e. libtorrent wouldn't have to do anything special to support following links. Is that not the case? Do I need to specify some flags when opening files to support traversing reparse points?

Since you talk about the stat()/GetFileAttributes() calls, are you talking about downloading a torrent with symbolic links in it? and libtorrent failing to create them? (this is an extension that hasn't been tested on windows afaik, and may not work).

**Comment by arvidn** [comment]
could you describe in more detail the case that fail for you? Specifically what you do, what happens and what you would expect to happen.

**Comment by amirotin** [comment]
Ok, first i'll explain what i want to do:
I need to move and rename downloaded torrent files (i.e. some.movie.year.h264.mkv to Some Movie (year) [AC3 H264 6CH].mkv). In other words i want to organize my media storage.
To continue seeding downloaded files i move file to another drive with new name and place symlink with old name in place where torrent client has finished download.

I use python bindings (tryed native python and deluge torrent client). What i do:
1. Download torrent to T:\Finished\some.movie.year.h264.mkv
2. Pause torrent (with fastresume save)
3. Move file to P:\Movies\S\Some Movie (year) [AC3 H264 6CH].mkv, place symlink T:\Finished\some.movie.year.h264.mkv
4. Start torrent

What i expect - libtorrent will start seeding torrent (maybe with hash check).
What  happens - libtorrent start downloading torrent again.

What i've found in your sources - here https://github.com/arvidn/libtorrent/blob/master/src/file.cpp#L338 and here https://github.com/arvidn/libtorrent/blob/master/src/create_torrent.cpp#L66
you add `file_storage::attribute_symlink` and `file_status::link` only for posix version, so on windows libtorrent doesn't handle symlinks.

**Comment by arvidn** [comment]
I'm pretty sure the stat() call supporting symlinks is unrelated to this issue. When you start the torrent again, and pass in the resume data, I imagine you get a resume_data_rejected_alert. what does it say?

**Comment by amirotin** [comment]
The only reason for stat() call is that posix `lstat` doesn't work with windows symlink. And i think that libtorrent doesn't understand that file is symlink (and doesn't follow symlink path).

Here is alert message
`filename.mkv fast resume rejected. (D:\Test\filename.mkv): mismatching file size`

**Comment by arvidn** [comment]
on posix, a symbolic link is transparent to the application. you don't need to do anything to follow it (with lstat() however, you can detect whether or not something is a symbolic link). Basically, not detecting the symbolic link is exactly what you'd want in this case.

Are you suggesting that this is not the case on windows?

**Comment by amirotin** [comment]
That's exactly what I meant. With windows and ntfs there is no transparency with symlinks :(

**Comment by amirotin** [comment]
Due to the fact that the error refers to the file size i think libtorrent doesn't follow symlink path and checks exactly the symlink, not the file.

**Comment by arvidn** [comment]
The msdn documentation seems to disagree. look for FILE_FLAG_OPEN_REPARSE_POINT in https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx

You are using proper symlinks (i.e. reparse points) right? not .lnk files

**Comment by arvidn** [comment]
I see, GetFileAttributes() behaves like lstat(), according to: https://msdn.microsoft.com/en-us/library/windows/desktop/aa364944(v=vs.85).aspx

**Comment by arvidn** [comment]
I can't find a way to disable this behavior for GetFileAttributes(). Do know how to stat() a file on windows and follow links? Do I have to implement the following of links manually?

**Comment by amirotin** [comment]
Found some discussion about symlinks https://blogs.msdn.microsoft.com/oldnewthing/20100212-00/?p=14963
It seems that you need to use GetFileAttributes function to get attributes and check for FILE_ATTRIBUTES_REPARSE_POINT flag. If it exists - use FindFirstFile function, get dwReserved0 param and compare it with IO_REPARSE_TAG_SYMLINK. In this case you will check if file is symlink.

To get size, path and etc use GetFileSize, GetFileInformationByHandleEx, or GetFinalPathNameByHandle.

I'm not a C coder, so i can not provide example code. Here is some demo code from codeproject http://www.codeproject.com/Articles/21202/Reparse-Points-in-Vista

**Comment by arvidn** [comment]
I think the best fix is probably to, instead of using GetFileAttributes() (which takes a path) open the file with CreateFile() (which follows symlinks) and then use GetFileInformationByHandleEx() to query stats from it. That seems like the least error prone way of doing it. I don't want to manually support recursive symlinks and detect loops and such

**Comment by amirotin** [comment]
Yes, CreateFile would be best solution for this :)

**Comment by arvidn** [comment]
the problem with this plan is that it won't work for directories

**Comment by aldenml** [comment]
I want to add that GetFileInformationByHandleEx does not exits in Windows XP. I know libtorrent is on his way to drop support for XP, but there is still a lot of XP out there.

**Comment by arvidn** [comment]
All I need is GetFileInformationByHandle() though (no Ex).

**Comment by aldenml** [comment]
Good to know, btw, I'm looking for a way to remove `file::m_path` that is used in `file::set_size`

**Comment by arvidn** [comment]
@amirotin Could you please give this a try? https://github.com/arvidn/libtorrent/pull/385

**Comment by arvidn** [comment]
@aldenml yeah, that would be nice. with vista there is FILE_STREAM_INFO from GetFileInformationByHandle(), which is probably more accurate than what I do now (since currently a compressed file would be considered sparse too)

**Comment by arvidn** [comment]
oh, I guess the main file isn't considered a stream. but this one has the allocated size: FILE_STANDARD_INFO

**Comment by amirotin** [comment]
@aldenml If you want to support XP than you may need to check for symlink first. Windows XP has no support for symlinks.
@arvidn i've no capability to build libtorrent by myself. It seems that you've some build errors https://travis-ci.org/arvidn/libtorrent/builds/102016643

**Comment by amirotin** [comment]
Just want to know - what for you use `file_status::link` flag in libtorrent?
With your commit you've fixed getting file info, but you don't add this flag in windows section.

**Comment by arvidn** [comment]
it's used for creating torrents with the extension to preserve links

**Comment by amirotin** [comment]
I've tryed last build. Don't know if it associated with symlink changes, but get this error when i try download torrent:
filename.mkv write (D:\test\filename.mkv) error: The parameter is incorrect
