### ISSUE TITLE
FAIL: test_primitives.

### ISSUE THREAD

**Issue by Achaean** [arvidn/libtorrent#3741]
libtorrent version (or branch):
Last stable version (1.2).
platform/architecture:
Devuan ASCII (stable) x64 KDE (Debian stable based).
GNU Make 4.1.
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
Configure and make completed successfully, but make check failed for primitives.

I'm attaching the console output for all three commands:
1) ./configure --enable-silent-rules --enable-tests --enable-debug --disable-static --disable-logging --disable-deprecated-functions
2) make -j4 and
3) make -j4 check.
[OUTPUT.zip](https://github.com/arvidn/libtorrent/files/3000485/OUTPUT.zip)

**Comment by arvidn** [comment]
none of those files include the ouput from the test itself though. could you run it manually and capture the output?

**Comment by Achaean** [comment]
Yes of course, but...ehm...how can I run it manually?  :-)
What exactly should I do?

**Comment by arvidn** [comment]
it looks like `url_seed_multi_single_file.torrent` is missing from the test directory. Is that the case?
Did you get this from a tarball or did you check out head of `RC_1_2` from git?

**Comment by Achaean** [comment]
> it looks like `url_seed_multi_single_file.torrent` is missing from the test directory. Is that the case?
Indeed! There isn't such a file here. :-(

> Did you get this from a tarball or did you check out head of `RC_1_2` from git?
Tarball. It's the libtorrent-rasterbar-1.2.0.tar.gz from releases page.

**Comment by arvidn** [comment]
fixed here: https://github.com/arvidn/libtorrent/pull/3752
