### ISSUE TITLE
infinite loop in bt_peer_connection::on_choke

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#3747]
master branch 

I encounter infinite loops in bt_peer_connection::on_choke() because the download queue isn't modified.
IMO, it is because peer_connection::incoming_reject_request() has some paths which do not modify the download queue.

**Comment by arvidn** [comment]
thanks for the report! fix against `RC_1_2` here: https://github.com/arvidn/libtorrent/pull/3748
probably applies pretty cleanly against master too

**Comment by arvidn** [comment]
I'll merge to master shortly
