### ISSUE TITLE
[Bug] Encryption Not Work

### ISSUE THREAD

**Issue by zero77** [arvidn/libtorrent#3751]
As suggested by the qBittorrent developers i have posted this issue here.
https://github.com/qbittorrent/qBittorrent/issues/10352

Also, does anyone have any advice on a better way to track / debug this.

### qBittorrent version and Operating System
qBittorrent v4.2.0alpha Web UI (64-bit)
qBittorrent v4.2.0alpha Desktop (64-bit)
ubuntu 18.04

### If on linux, libtorrent and Qt version
Qt: 5.9.5
Libtorrent: 1.1.11.0

### What is the problem
I have encryption set to prefer but it didn't always seem to work.

So i tested it by using two Bittorrent clients with the same torrent both with the same versions and settings but one was on a remote server running as nox and the other was using a desktop ui.

Neither client used encryption when downloading even though they were both set to prefer.
### What is the expected behavior
Both qBittorrent clients used encryption that was set to prefer so, they should have used encryption when downloading.

**Comment by thalieht** [comment]
(settings_pack::pe_enabled)

**Comment by arvidn** [comment]
response [here](https://github.com/qbittorrent/qBittorrent/issues/10352#issuecomment-477171958)
