### ISSUE TITLE
test_ssl hangs on alpine linux x86_64

### ISSUE THREAD

**Issue by ncopa** [arvidn/libtorrent#3762]
libtorrent version (or branch):
1.2.0

platform/architecture:
alpine linux x86_64 (with musl libc), in an LXC container.

compiler and compiler version:
gcc (Alpine 8.3.0) 8.3.0
boost-1.67.

test suite hangs on `test_ssl`.

````
test: /home/ncopa/aports/testing/libtorrent-rasterbar/src/libtorrent-rasterbar-1.2.0/test/.libs/lt-test_ssl
cwd_prefix = "/home/ncopa/aports/testing/libtorrent-rasterbar/src/libtorrent-rasterbar-1.2.0/test/test_tmp_39282_"
rnd = 82ebe099
***** test_ssl.cpp:292 "TEST_ERROR: ssl_peer_disconnects > 0: 0 expected: 1" *****
````
After that it hangs for hours.

To reproduce:
Build on alpine linux edge. run `make check`.

**Comment by arvidn** [comment]
I've noticed that sometimes `async_shutdown()` on SSL sockets never completes. I'm not sure what the best solution is. There should probably be a timeout on it, but that would add some complexity I wouldn't be too excited about. If I would just close the socket, SSL would complain about not being shut down gracefully.
