### ISSUE TITLE
python: 'libtorrent' has no attribute 'dht_settings'

### ISSUE THREAD

**Issue by joriscarrier** [arvidn/libtorrent#3767]
libtorrent version (or branch): 1.2.0
platform/architecture: python 3.7.2 (Mac, Linux, Windows)

compiled with: `b2 cxxflags="-std=c++11" address-model=64`

> `AttributeError: module 'libtorrent' has no attribute 'dht_settings'`

**Comment by arvidn** [comment]
thanks! fixed in https://github.com/arvidn/libtorrent/pull/3774
