### ISSUE TITLE
Please support disabling DHT and LSD per torrent

### ISSUE THREAD

**Issue by TheKingintheNorthJonStark** [arvidn/libtorrent#3769]
Private trackers want them turned off, public ones work faster if they are turned on. So you have to run 2 instances of qbittorrent or any other client that uses libtorrent. Which is a waste of ram/cpu/io/...

So if you implement support for that in a reasonable amount of time I pledge myself (I don't think we pledge our swords  any more and it wouldn't help you anyway) to send you some btc.

**Comment by arvidn** [comment]
implement what?

**Comment by TheKingintheNorthJonStark** [comment]
Per tracker settings for dht/pex and all tht. Say so right in the title?

**Comment by ivan386** [comment]
@TheKingintheNorthJonStark Private trackers can set private flag in torrent file. With that flag torrent will not be announced to dht and pex.

**Comment by thalieht** [comment]
I think @TheKingintheNorthJonStark means per _torrent_ https://github.com/qbittorrent/qBittorrent/issues/7743

**Comment by arvidn** [comment]
@TheKingintheNorthJonStark can you be a bit more specific about the symptoms that you see, and what you would expect or would like to be able to do?

"per tracker dht/pex/..." is a bit hard to decipher. It sounds like you're talking about the "private" flag in .torrent files, but that's been well established for at least a decade (and it's per torrent, not per tracker). Per tracker doesn't make sense, since PEX and DHT are not properties of trackers.

**Comment by arvidn** [comment]
I updated the title to say what I think you mean. disabling PEX doesn't really make any difference if you don't have any peers anyway

**Comment by ryannathans** [comment]
Per torrent makes sense and should achieve the same effect as having the private flag.

In the meantime, is it possible to edit a torrent file to force it private?

**Comment by ivan386** [comment]
> In the meantime, is it possible to edit a torrent file to force it private?

[Private Torrents](http://bittorrent.org/beps/bep_0027.html)

> When generating a metainfo file, users denote a torrent as private by including the key-value pair "private=1" in the "info" dict of the torrent's metainfo file [1].

> When a BitTorrent client obtains a metainfo file containing the "private=1" key-value pair, it MUST ONLY announce itself to the private tracker, and MUST ONLY initiate connections to peers returned from the private tracker.

Open torrent file in bencode editor and add private flag to info dict.

**Comment by arvidn** [comment]
> Open torrent file in bencode editor and add private flag to info dict.

That will affect the info-hash, and effectively make it a different torrent

**Comment by ivan386** [comment]
@arvid yes. If you only turn off (DHT/PEX/LSD) it will not stop others cliens to use it. If you set private flag that create different torrent whith swarm that do not use DHT/PEX/LSD.

**Comment by arvidn** [comment]
would this work? https://github.com/arvidn/libtorrent/pull/3871
