### ISSUE TITLE
python - dht_put_mutable_item => segmentation fault

### ISSUE THREAD

**Issue by joriscarrier** [arvidn/libtorrent#3775]
libtorrent version (or branch): 1.2.0
platform/architecture: MacOs - python 3.7.2
compiler and compiler version: boost 1.69.0

a few seconds after calling `dht_put_mutable_item` (`ses.dht_put_mutable_item('private_key', 'public_key', 'data', 'salt'`): python crash with a  segmentation fault

**Comment by arvidn** [comment]
Do you have a test program I can reproduce this with?

**Comment by arvidn** [comment]
@joriscarrier ping

**Comment by joriscarrier** [comment]
since commit 8b925b85762f2f7d41b21835852a599b90c97314 I can't reproduce
