### ISSUE TITLE
Write 1MiB-4MiB at a time instead of writing 32KiB pieces

### ISSUE THREAD

**Issue by NavinF** [arvidn/libtorrent#3776]
I'm seeing an average read size of 11.7KiB and average write size of 31.7KiB  in my download directory's filesystem. I assume this is happening because my torrents have a small piece size and these pieces are downloaded in a random order by libtorrent. 

For cost reasons, my setup has very low IOPS (~70 reads + writes per second) even though sequential writes to the disk arrays via the same filesystem are reasonable (~400MiB/s fsynced). 

My download speed of 2MiB/s is clearly limited by IOPS (and perhaps by write amplification from tiny writes that straddle sectors)

How do I change the piece selection code to increase the priority of nearby pieces after the first 70 pieces have been downloaded in a random order? I'm hoping that my IO elevator will then coalesce nearby writes and significantly increase download speed.

**Comment by ssiloti** [comment]
This was recently discussed in https://github.com/arvidn/libtorrent/issues/3746 and https://github.com/arvidn/libtorrent/pull/3753

**Comment by sserdda-liamE** [comment]
> This was recently discussed in #3746 

Well any change there wouldn't have any effect on torrents already created, and the automatic piece size creation logic already leaves the tiny piece sizes pretty quickly.  It's 1MB and above it decides to multiply the pieces to absurd numbers. 

Though there's an argument to be made it shouldn't create <64kB piece size torrents at all.  Broadband (even really crappy broadband) obviates the need for it.  64kB is the minimum piece size uTorrent 2.2.1 will automatically select.

Anyway, what are you downloading that's 32kB piece size?  If you're just snatching a ton of tiny torrents from a private tracker to farm bonus points, use sequential downloading.  It doesn't hurt anything on a private tracker.

**Comment by arvidn** [comment]
I intend to improve this situation by creating an affinity to download adjacent pieces (when pieces are small). I also think https://github.com/arvidn/libtorrent/pull/3753 is a part of the solution, but probably less impactful.

**Comment by arvidn** [comment]
@NavinF which version of libtorrent are you using? There used to be a problem on windows where it failed to merge adjacent write requests. This was solved by defaulting `coalesce_writes` to be enabled on windows. So, if you're on windows, make sure that's enabled. If your system doesn't have `preadv()` and `pwritev()` you may also need to enable coalescing of writes.

**Comment by NavinF** [comment]
I'm using an old version (libtorrent 1.1.5.0), but I'm not on Windows. My machines currently run Linux kernel 4.13.16-coreos-r2. 

Downloading adjacent pieces sounds like the right solution. I'm not too concerned about libtorrent itself merging adjacent writes since the kernel can do that.

**Comment by arvidn** [comment]
here's how I've done this in the past. This may be worth building into libtorrent directly, or at least something like it. Perhaps this piece priority solution isn't the most efficient. 
https://github.com/arvidn/btfs/blob/master/src/block_affinity.cpp#L45

**Comment by arvidn** [comment]
oh, I just realized these tickets are duplicates now: https://github.com/arvidn/libtorrent/issues/3746

**Comment by fusk-l** [comment]
Good to see this is being brought to light, and being worked on. Single or raid ssd's appear to be easily overloaded on high speed torrents, this is probably the reason why.

**Comment by xavier2k6** [comment]
@arvidn FYI/related?

Torrent read/write nvme benchmark
https://qbforums.shiki.hu/index.php/topic,7273.15.html

**Comment by arvidn** [comment]
addressed in https://github.com/arvidn/libtorrent/pull/3913
It probably needs more practical testing and tweaking, once it's released.
