### ISSUE TITLE
Unresolved external symbol, iphlpapi

### ISSUE THREAD

**Issue by brucetauro** [arvidn/libtorrent#3779]
libtorrent version (or branch): 1.2.0
Boost version: 1.67

platform/architecture: Windows 10 x64

compiler and compiler version: MSVC++ 14.16 (Visual Studio 2017 version 15.9)

I've built Boost with :
.\b2 toolset=msvc address-model=64 architecture=x86 link=static threading=multi runtime-link=static --build-type=complete stage 

and libtorrent using :
b2 msvc-14.1 address-model=64 architecture=x86 link=static threading=multi runtime-link=static 

Libtorrent.lib compiles with this warning:
```
peer_info.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library
```

but when I try to compile the simple client example I get these error messages:
```
Error	LNK2019	unresolved external symbol CancelIPChangeNotify referenced in function "public: virtual void __cdecl libtorrent::aux::`anonymous namespace'::ip_change_notifier_impl::cancel(void)" (?cancel@ip_change_notifier_impl@?A0xb04c8b5c@aux@libtorrent@@UEAAXXZ)	Simpletorrent	C:\Users\Bruce\source\repos\Simpletorrent\Simpletorrent\libtorrent.lib(ip_notifier.obj)	1	
Error	LNK2019	unresolved external symbol NotifyAddrChange referenced in function "public: virtual void __cdecl libtorrent::aux::`anonymous namespace'::ip_change_notifier_impl::async_wait(class std::function<void __cdecl(class boost::system::error_code const &)>)" (?async_wait@ip_change_notifier_impl@?A0xb04c8b5c@aux@libtorrent@@UEAAXV?$function@$$A6AXAEBVerror_code@system@boost@@@Z@std@@@Z)	Simpletorrent	C:\Users\Bruce\source\repos\Simpletorrent\Simpletorrent\libtorrent.lib(ip_notifier.obj)	1	
```
The methods referenced are from the iphlpapi library but testing it separately in visual studio works fine.

**Comment by arvidn** [comment]
when you're creating a static library, it cannot declare dependencies on DLLs by itself (they way a DLL and EXE can contain references to have the loader pull in DLLs it depends on). A static library is essentially just a collection of object files. The dependency on `iphlpapi.dll` must therefore be propagated by the build system itself.

If you were to build `simple_client` with boost-build, this dependency would propagate and `simple_client` would link against this library. If you build it with some other build system, you have to add this dependency manually.

**Comment by arvidn** [comment]
try executing:

```
b2 msvc-14.1 address-model=64 architecture=x86 link=static threading=multi runtime-link=static
```

in the `examples` folder of libtorrent, that should successfully build all the examples.
