### ISSUE TITLE
[Feature Request] Peer Policy

### ISSUE THREAD

**Issue by black-cerberon** [arvidn/libtorrent#3781]
Hi. Can you add support 'isp.peer_policy_url' like in uTorrent? This option prioritize local peers and increase speed for them. My ISP provide me 1Gbps in local network, but speed in common networks is 100Mbps. I don't want use LSD, because it makes 'parasite traffic' and ISP ban me.

**Comment by arvidn** [comment]
does your ISP provide support for `isp.peer_policy_url`?

**Comment by black-cerberon** [comment]
Not literally, but this file may create manually by user. My ISP provide max speed for specific ip ranges.

**Comment by arvidn** [comment]
I think implementing something like this is outside of the scope of libtorrent, and in the scope of a client using it. I believe the peer policies can be implemented using [peer classes](https://libtorrent.org/manual-ref.html#peer-classes) and [IP filters](https://libtorrent.org/reference-Core.html#set_ip_filter()) in libtorrent.
