### ISSUE TITLE
Error brew install libtorrent-rasterbar Symbol not found: _kSCCompAnyRegex

### ISSUE THREAD

**Issue by viocost** [arvidn/libtorrent#3784]
**Please provide the following information**

libtorrent version (or branch): 1.2

platform/architecture: 10.12.6 (16G1710)

python version 3.7.3

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

``` brew install libtorrent-rasterbar ```
or
``` brew install libtorrent-rasterbar --build-from-source ```

then:

```
Python 3.7.3 (default, Mar 27 2019, 09:23:32)
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import libtorrent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/libtorrent.cpython-37m-darwin.so, 2): Symbol not found: _kSCCompAnyRegex
  Referenced from: /usr/local/Cellar/libtorrent-rasterbar/1.2.0/lib/libtorrent-rasterbar.10.dylib
  Expected in: flat namespace
 in /usr/local/Cellar/libtorrent-rasterbar/1.2.0/lib/libtorrent-rasterbar.10.dylib
```

**Comment by arvidn** [comment]
it looks like something is using `kSCCompAnyRegex` from the `SystemConfiguration` framework, without linking against it. Both the `Jamfile` and `CMakeList.txt` links against this framework. So it looks like the problem is how libtorrent is built.

How is it built?

**Comment by viocost** [comment]
As far as I understand ```brew install libtorrent-rasterbar``` only downloads pre-built library, and ```brew install libtorrent-rasterbar --build-from-source``` builds it using [this](https://github.com/Homebrew/homebrew-core/blob/master/Formula/libtorrent-rasterbar.rb) homebrew formula. I haven't done anythong else besides the brew commands. I was able to build it successfully on MacOS Sierra 10.12.6 without using homebrew, But homebrew attempt failed, with described error.

**Comment by Axure** [comment]
Any update on this? I encountered the same problem.

**Comment by arvidn** [comment]
as far as I can tell, this is an issue in brew. libtorrent builds fine on mac with both boost-build and cmake.

**Comment by devos50** [comment]
I think I found the issue. The brew formula for `libtorrent-rasterbar` does not add the `SystemConfiguration` and `CoreFoundation` libraries to the `LDFLAGS` env variables. Therefore, it does not link against the `SystemConfiguration` and `CoreFoundation` libraries, which contain the `_kSCCompAnyRegex` symbol.

To fix this, it is sufficient to add the following line to the formula, right after the definition of the `args` variable in the `install` function:

```
ENV.append "LDFLAGS", "-framework SystemConfiguration -framework CoreFoundation"
```

I will also make a PR to the brew formula.

**Comment by fxcoudert** [comment]
> The brew formula for libtorrent-rasterbar does not add the SystemConfiguration and CoreFoundation libraries to the LDFLAGS env variables

The configure-based build system for `libtorrent-rasterbar` should determine automatically what flags are supposed to be used to link against system frameworks, if they want to use them. That they do not is a bug in libtorrent, and should be reported to them.

Forcing `LDFLAGS` in the homebrew formula is a hack. We may use it as a temporary measure, but the root problem needs to be found and fixed.

**Comment by arvidn** [comment]
I see. So libtorrent is essentially built with `./configure && make`.
The automake build scripts have primarily been maintained by other people than myself. It's not a build system I support (and in fact, I've removed it in `master` for the next major version release).
I'm open to pull requests to fix the automake build system for `RC_1_2`, but I can't really fix this myself.

The supported build systems are boost build and cmake.

**Comment by fxcoudert** [comment]
> The supported build systems are boost build and cmake.

We'll move to `cmake` then.
