### ISSUE TITLE
Clarification of static/shared build options and Asio

### ISSUE THREAD

**Issue by jpetso** [arvidn/libtorrent#38]
So I've got a patch locally that lets me build with CMake with Asio sources provided by the executable, i.e. Asio not built into the library itself. In the best interest of not introducing unnecessary options, I thought maybe it's a good idea to understand the ones that already exist in the build.

There are two options related to dynamic vs. static linking:
- `shared`:  "build libtorrent as shared library, as opposed to static".
  - Implies hidden visibility.
- `static_runtime`: "build libtorrent with static runtime".
  - Implies `/MT` flag instead of `/MD` for MSVC builds. According to [this](https://msdn.microsoft.com/en-us/library/2kzt1wy3.aspx), that flag causes Visual Studio to link its C/C++ runtime library into libtorrent itself instead of using a DLL that will usually be the host system's version.
  - Switches from `BOOST_*_DYN_LINK` to `BOOST_ASIO_SEPARATE_COMPILATION`.

A quick review of the mentioned Boost defines:
- `BOOST_*_DYN_LINK` changes header-only stuff (`inline` declarations) of the public API to external symbol references (e.g. dllimport) that need to be resolved by the executable loading the shared object. In practice, this means if I'm a shared library and want to use the library user's Boost (rather than embedding it), I define DYN_LINK.
- `BOOST_ASIO_SEPARATE_COMPILATION` removes the `inline` from public API and makes it into a regular function/class definition that needs to be resolved when linking the result of all compiled objects, i.e. when linking the shared library or (if using static libraries) the executable itself.
- As an aside, Boost.Asio is also notorious for not caring about ABI stability because its maintainer considers only its source compatibility a goal. (Really looking forward to its stabilized version `std::network` in C++17 or whenever.)

This is my take on it:
- Static builds should always use `BOOST_ASIO_SEPARATE_COMPILATION` and _not_ include src/asio(_ssl).cpp, otherwise the parent project is tied to libtorrent as its Asio implementation. (This is bad for maintenance if the parent project also uses Asio, e.g.: "If building with libtorrent support, link libtorrent but don't include Asio sources. If building without libtorrent support, include Asio sources but not libtorrent.").
- Because of hidden default visibility, shared builds will hide Asio symbols if using either header-only or `BOOST_ASIO_SEPARATE_COMPILATION`. It seems libtorrent went with the latter (see libtorrent/config.hpp), presumably to avoid generating the same templated inline code multiple times. That's okay for the library build but it should avoid forcing the library user into defining `BOOST_ASIO_SEPARATE_COMPILATION` too. Since it already has everything it needs, `BOOST_ASIO_SEPARATE_COMPILATION` or `BOOST_ASIO_DYN_LINK` should be defined only as a compiler option when building the library and not in libtorrent/config.hpp.
- With all of Asio's ABI instability, I don't really see a point in using `BOOST_ASIO_DYN_LINK` because when using a shared library you ideally don't have the knowledge about libtorrent's exact Boost version at build time. I suggest removing this option and only leaving a separate Asio implementation as (forced) default for static builds.

So, the action plan in short:
- Remove the `BOOST_ASIO_*` check from src/config.hpp.
- For shared library builds, always define `BOOST_ASIO_SEPARATE_COMPILATION` and include src/asio(_ssl).cpp in the build.
  - The library user can include Asio for purposes other than libtorrent with any desired build define, or leave it out. Executable will link either way.
- For static library builds, always define `BOOST_ASIO_SEPARATE_COMPILATION` but don't include src/asio(_ssl).cpp in the build.
  - The library user will always provide the implementation by themselves, with the same Boost version as libtorrent was using.

Do you approve of this action plan, is it okay if I submit a patch to implement it this way?

One question I still have is how MSVC's `/MT` or `/MD` flags factor into all of this. Why does `static_runtime` have an effect on Boost defines in the CMake build? What goal does it achieve for shared builds and what for static builds?

**Comment by jpetso** [comment]
The patch referenced by the GitHub message above implements this proposal. I adapted all three build systems and tested all kinds of variations (all with examples enabled): CMake static and shared (with and without tests), autotools with tests, Boost.Build static and shared.

I couldn't get Boost.Build with link=shared to work even without my patch, it complains about some -fPIC issue in the system's Boost libraries. Please check if you've got this working yourself, otherwise I'm still pretty confident that it's good or extremely close. All other ones work. CMake shared has never worked since hidden visibility but now does. External programs that build against Asio are not dependent on matching shared libtorrent's Asio version anymore.

**Comment by arvidn** [comment]
in short, it's a little bit of a mess. One case I've really been wanting to support is to build everything as a static library (without -fPIC) and also so build the python binding as a single shared library (linking statically against libtorrent and all its dependencies). On top of this, obviously I need to be able to build against the system (installed) boost libraries on linux, which means shared linking against boost. One trick is to add -fPIC and visibility=hidden in the correct scenarios.

as far as I know, boost.asio doesn't have a shared library built by default (nor installed on linux). It would be nice if it did.

On top of this, it would be nice to only export the symbols that are external. asio is a bit of a problem here, since some of its types are used in libtorrent's API. linking statically against the runtime library is rarely necessary.
