### ISSUE TITLE
Refactor file::open to use an external file_open function

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#380]
Before send any PR, I would like to talk about it. I think I can refactor the current `file::open` function to extract (and then use) a more generic function like `file_open(std::string const& p, int m, error_code& ec)`  similar to `stat_file`.

My questions is if this is a desired change and in case of affirmative, how to better pass this function, in the `file` constructor or in the function `file::open` (with the corresponding default).

Related to https://github.com/arvidn/libtorrent/pull/335

**Comment by arvidn** [comment]
The idea would be that this free function would return an int or a HANDLE? basically factor out file::open() to a free function. That seems reasonable. There are a few things though:

1. I would expect that function to have internal linkage (anonymous namespace) which would still require a patch to replace (but perhaps a smaller and simpler patch)
2. I'm envisioning moving away from my own filesystem functions to boost.filesystem (v3) at some point (libtorrent 1.2 perhaps). That wouldn't significantly affect the file class though (but create_directory()/stat_file()/hard_link() etc.)

**Comment by aldenml** [comment]
I'm thinking more in preparing the API to easily swap the basic file operations (like a possible `file_open`). Making it internal would not work for me, or at least in a way that I can see. My current idea is:

1 - Make `storage` to have the file system primitives that receive a name in the interface.
2 - Have `default_storage` to implement this methods with the trivial ones.
3 - At the moment that `default_storage` needs to use a file, it pass the instance "file_open" function, that in turns is implemented but the new factored `file_open`, to the instance of `file` for internal use.

All of this would make `default_storage` extensible to android, but will not make any differences in API calls like `torrent_info(filename)`.

Does this make sense? good or bad idea?

**Comment by aldenml** [comment]
Closing this since there is no clear path to achieve something meaningful in a short term basis.

**Comment by aldenml** [comment]
Just to document that any solution should involve the correct handling of errors reported by the posix layer. Since `errno` is set by the posix calls, the abstraction should delegate both the task and the error reporting.
