### ISSUE TITLE
Libtorrent (in QBittorrent) cuts filename if it exceeds 240 bytes

### ISSUE THREAD

**Issue by dzmat** [arvidn/libtorrent#3804]
**Please provide the following information**
libtorrent version (or branch):
1.2.0

platform/architecture:
Windows (and Linux  version 1.1.12 on Fedora29 seems to be affected too).

compiler and compiler version:
mingw 5.3.0 shipped with Qt Creator.

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

**Libtorrent (in QBittorrent) cuts filename if it exceeds 240 bytes.**
While investigating qbittorrent issue https://github.com/qbittorrent/qBittorrent/issues/10521 , I have created test torrent file [111.torrent.zip](https://github.com/arvidn/libtorrent/files/3112817/111.torrent.zip) and traced problem down to function `void sanitize_append_path_element(std::string& path, char const* element, int element_len)` in libtorrent\src\torrent_info.cpp file. There is some strange code at the end of this function (around of https://github.com/arvidn/libtorrent/blob/ba731ef0cf7bf6b258f979fb75876f9a7f0aa11b/src/torrent_info.cpp#L292 ), which effectively cuts down file name to 240 chars when there is no extension.

To reproduce open test file with qbittorrent and trace file parsing process.

*call stack*
```
1   libtorrent::sanitize_append_path_element     torrent_info.cpp        302  0x1d2c34bc 
2   libtorrent::torrent_info::parse_info_section torrent_info.cpp        1154 0x1d2c884b 
3   libtorrent::torrent_info::parse_torrent_file torrent_info.cpp        1452 0x1d2c9eee 
4   libtorrent::torrent_info::torrent_info       torrent_info.cpp        913  0x1d2c6e43 
5   BitTorrent::TorrentInfo::load                torrentinfo.cpp         99   0x44046b   
6   BitTorrent::TorrentInfo::loadFromFile        torrentinfo.cpp         144  0x440876   
7   AddNewTorrentDialog::loadTorrentFile         addnewtorrentdialog.cpp 269  0x4c0866   
8   AddNewTorrentDialog::show                    addnewtorrentdialog.cpp 249  0x4c0677   
9   AddNewTorrentDialog::show                    addnewtorrentdialog.cpp 259  0x4c0746   
10  MainWindow::on_actionOpen_triggered          mainwindow.cpp          1372 0x4e2948   
<cut here>
```

**Comment by arvidn** [comment]
if you look a few more lines above that, you see that this is deliberate: https://github.com/arvidn/libtorrent/blob/ba731ef0cf7bf6b258f979fb75876f9a7f0aa11b/src/torrent_info.cpp#L278

You can read the comment to get a hint why:

> any given path element should not
> be more than 255 characters
> if we exceed 240, pick up any potential
> file extension and add that too

Where does 255 characters come from? a search for "windows max filename length" give you this: https://stackoverflow.com/questions/265769/maximum-filename-length-in-ntfs-windows-xp-and-windows-vista

**Comment by dzmat** [comment]
But why we are processing extension separately? There is no mention of separate storage space for extension and no limits for it. It is just part of string after the last dot. And why your code cuts **extensionless** file name to 240 chars, not to 255?

**Comment by arvidn** [comment]
> But why we are processing extension separately?

Because a lot of software treats files differently depending on the extension, so preserving the extension will make the file still work well, in windows explorer for instance.

> There is no mention of separate storage space for extension and no limits for it. It is just part of string after the last dot. And why your code cuts extensionless file name to 240 chars, not to 255?

I think the logic is a bit conservative to be on the safe side, and I think the *effective* max length is actually less than 255. The exact rules and limits don't seem straight-forward.

**Comment by arvidn** [comment]
Is there anything else in this ticket? Is it important that this behaviour is better documented?
It could probably be more precise, and truncate the file name depending on more things, like version of windows and file system etc. But it’s not obvious it’s worth it, as it would also be less robust

**Comment by dzmat** [comment]
I want to rewrite a bit this function and make a pull request. The goal is to save extension and to not cut the file name if it already fits in 255 chars.

**Comment by arvidn** [comment]
ok, just make sure to include references to what the exact limits are and how you detect them. [The disagreements on stackoverflow](https://stackoverflow.com/questions/265769/maximum-filename-length-in-ntfs-windows-xp-and-windows-vista) seem to suggest that this is non-trivial to find.

The last post [here](https://social.technet.microsoft.com/Forums/windows/en-US/43945b2c-f123-46d7-9ba9-dd6abc967dd4/maximum-path-length-limitation-on-windows-is-255-or-247) seems informational.

**Comment by arvidn** [comment]
actually, I think the best solution would be to use UNC paths pervasively, and not bother with the limit. I'm not completely sure, but my impression is that if all paths use the `\\?\` prefix together with the unicode versions of the win32 file functions, the effective limit is 32k.

**Comment by Chocobo1** [comment]
https://winaero.com/blog/how-to-enable-ntfs-long-paths-in-windows-10/

Seems Windows 10 can bypass that 260 char limit now (with tweaks but haven't tried it yet), so I'm thinking there should be an option to disable the 240 chars check, a compile time switch would be fine too.
