### ISSUE TITLE
python hash_for_piece can segfault

### ISSUE THREAD

**Issue by joriscarrier** [arvidn/libtorrent#3808]
**Please provide the following information**

libtorrent version (or branch): RC_1_2
platform/architecture: MacOS / Debian python 3.7.x
compiler and compiler version: boost 1.69

Hi, 
when I create a torrent of similar torrents my python interpreter crash and pytest show me this:

`malloc: Incorrect checksum for freed object 0x7f89849bba00: probably modified after being freed.`
`Corrupt value: 0x4e9b44024e601d2b`
`malloc: *** set a breakpoint in malloc_error_break to debug`

Any Idea ?

Here my code:

```python
    file_storage = lt.file_storage()

    for ti in torrents_info:
        for _file in ti.files():
            file_storage.add_file(_file.path, _file.size)

    file_storage.set_name(name)

    create_torrent = lt.create_torrent(file_storage)

    for torrent_indice, ti in enumerate(torrents_info):
        create_torrent.add_similar_torrent(ti.info_hash())

        for file_indice, _file in enumerate(ti.files()):
            for piece_indice in range(ti.num_pieces()):
                create_torrent.set_hash(
                    piece_indice * torrent_indice,
                    ti.hash_for_piece(piece_indice)  # if I delete this line I don't get a segfault
                )
            create_torrent.set_file_hash(
                file_indice * torrent_indice,
                _file.filehash.to_bytes()
            )
```

**Comment by arvidn** [comment]
what's the reason to pass in `piece_indice * torrent_indice`. That looks like it will pass in a piece index that's out-of-bounds, and hence undefined. If you build libtorrent in debug mode, I believe this would trigger an assert with a helpful error message.

Similarly, `file_indice * torrent_indice` looks like it will cause file indices past the last file as well.

**Comment by joriscarrier** [comment]
thx & sorry
