### ISSUE TITLE
[Wishlist] Different binary name for each build variant

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#382]
It would be very convenient if the build system has created the binaries with different names depending on the build variant. Just as when you build Boost, Qt, etc. Example: torrent.dll, torrent.lib for release build and torrentd.dll, torrentd.lib for debug build.

**Comment by glassez** [comment]
Well at least some response to that?

**Comment by arvidn** [comment]
yes, it would be nice. I haven't really had much time to look at this yet, but I imagine it would be fairly straig-forward with an install rule in the Jamfile. But it depends on how you consume libtorrent builds. If you don't use boost-build, any Jamfile changes won't make a difference.

It might be nice to add a proper install rule that can be configured with --prefix too.
