### ISSUE TITLE
file_error_alert returns wrong path

### ISSUE THREAD

**Issue by H1X4Dev** [arvidn/libtorrent#3822]
**libtorrent version:** libtorrent-rasterbar-1.2.0
**platform/architecture:** Windows 10 x64
**compiler and compiler version:** Visual Studio 2017 (v141) with /std:c++17

`file_error_alert` is producing incorrect result when after remaping to a different directory.

Current behavior:
`file_error_alert::message()` => "file_open (C:\download\testC:\download\test\file.txt) error: Access is denied"
`file_error_alert::filename()` => "C:\download\testC:\download\test\file.txt"

Expected behavior:
`file_error_alert::message()` => "file_open (C:\download\test\file.txt) error: Access is denied"
`file_error_alert::filename()` => `"C:\download\test\file.txt"

remapping:
```cpp
base_path is the remapped directory.

libtorrent::file_storage fs;
libtorrent::file_index_t num_files(params.ti->files().num_files());
for (libtorrent::file_index_t i(0); i != num_files; ++i)
{
    std::string full_path = params.ti->files().file_path(i);
    full_path.replace(full_path.begin(), full_path.begin() + strlen(params.ti->name().c_str()), base_path);
    fs.add_file(full_path, params.ti->files().file_size(i));
}
params.ti->remap_files(fs);
```

However, this issue did not happen in 1.1.8 since last was updated.

**Comment by arvidn** [comment]
it looks like you'd be better off using `rename_file()` on `file_storage`.
