### ISSUE TITLE
performance warning: using bittyrant unchoker with no upload rate limit set

### ISSUE THREAD

**Issue by Joshua-Wang** [arvidn/libtorrent#3827]
**Please provide the following information**

libtorrent version (or branch):
1.1.4

platform/architecture:

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I have already set choking_algorithm = settings_pack.fixed_slot_choker and unchoke_slots_limit = -1. But I still get performance warning like "performance warning: using bittyrant unchoker with no upload rate limit set". 
Not every torrent will produce such warning. I have already set choking_algorithm = settings_pack.fixed_slot_choker, why still I got such error like bittyrant unchoker?
Thanks a lot.

**Comment by arvidn** [comment]
did you figure out what was happening?
