### ISSUE TITLE
libtorrent 1.1.13 compiler error

### ISSUE THREAD

**Issue by PHCSJC** [arvidn/libtorrent#3829]
**Please provide the following information**

libtorrent version (or branch):
libtorrent-rasterbar-1.1.13

platform/architecture:
aarch64 arm64 armbian stretch

compiler and compiler version:
libtorrent-rasterbar-1.1.13
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

when I make in my system,I get below error,please help.
./configure --disable-debug --enable-encryption
make clean && make -j4
.............................................
.............................................
  CXX      torrent_handle.lo
  CXX      torrent_info.lo
Makefile:940: recipe for target 'session_impl.lo' failed
make[1]: *** [session_impl.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/usr/src/libtorrent-rasterbar-1.1.13/src'
Makefile:626: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by arvidn** [comment]
would you mind posting the error message?
that's the message that stats with: "error: "

**Comment by arvidn** [comment]
which compiler and version are you using?
