### ISSUE TITLE
upload performance issue

### ISSUE THREAD

**Issue by Joshua-Wang** [arvidn/libtorrent#3831]
**Please provide the following information**

libtorrent version (or branch):
1.1.4

platform/architecture:

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I have an environment which one host(dispatcher) make torrent and upload, and other hosts(receivers) download from it . I have found that some of the receivers's upload speed drop down after some time. 
![image](https://user-images.githubusercontent.com/6940489/57526566-4d278100-7360-11e9-879d-7d05942ea700.png)
some of the observations:
1. download speed have not dropped, only upload speed dropped.(receivers download more from dispatcher, not from each other).
2. first I doubt it could be limited by unchoke_slots_limit, so I turn it to -1, but it didn't work.
3. I have already set choking_algorithm = fixed_slots_choker, but I still get performance warning like "performance warning: using bittyrant unchoker with no upload rate limit set". I don't know why.
4. I printed all peer-info , and I found when upload speed is slow, lots of peer's status is "connecting" . Since dispatcher generate about 10 torrents per miniuts, so I doubt receviers may spend quite some time connecting to each other, which could decrease the upload speed. Total num of receiver is about 100.

So how could I  determine the reason and which params could alleviate the situation ?

Any help will be greatly appreciated. :)

**Comment by Seeker2** [comment]
Can you retest with a later version of libtorrent that fixed known issues with uploading, especially uTP bugs?

**Comment by Joshua-Wang** [comment]
I have already disabled uTP transmission.  I was wondering what uploading bug is in current version.I will test with newer versions.

**Comment by arvidn** [comment]
I think your best bet is to look at the "session_stats" and look for hints. You can enable session stats in the alert_mask, print them to a file and use `tools/parse_session_stats.py` to parse them and generate graphs for some interesting metrics. The python script expects you to have gnuplot installed.
