### ISSUE TITLE
simple_client.cpp

### ISSUE THREAD

**Issue by backhat-backhat** [arvidn/libtorrent#3835]
**Please provide the following information**

libtorrent version (or branch): 1.14

platform/architecture: macOS

compiler and compiler version: gnu c++11

when I use the simple_client.cpp, add xxx.torrent, and no file download, no file created, but when I use the bt tool, it will creates the download file, why?

**Comment by arvidn** [comment]
`simple_client.cpp` is so simple it barely prints any diagnostics. Try `client_test.cpp` and redirect the log to a file and have a look instead.

**Comment by backhat-backhat** [comment]
I try client_test.cpp, and the speed is still 0, when I use 迅雷, it has very fast speed, the link is :

magnet:?xt=urn:btih:b29c1058cc783f9ac8705dddc28575fa88118351&dn=[电影天堂www.dy2018.com]目击者BD韩语中字.mp4

why? the protocol is different ?
