### ISSUE TITLE
File corruption when downloading on Windows with sparse files

### ISSUE THREAD

**Issue by ssiloti** [arvidn/libtorrent#3842]
libtorrent version (or branch): master

platform/architecture: Windows x64

compiler and compiler version: msvc-14.2

When downloading multi-file torrents on Windows with sparse files enabled files can be written incorrectly due to an apparent bug in Windows. I've reported the issue to MS [here](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/44e9ddea-672f-441f-83ed-169f19fc48b8/concurrently-calling-createfilemapping-and-unmapviewoffile-with-a-mapped-sparse-file-causes-data?forum=windowsgeneraldevelopmentissues), but I'm not holding my breath for a fix. In any case we'll need to work around this by serializing opening/closing of mappings for the same file. I still need to figure out the best way to do this.

**Comment by Rootax** [comment]
You got an answer on the microsoft forum...

**Comment by ssiloti** [comment]
Yeah, by some level 1 support rep who clearly didn't spend more than 30 seconds reading what I wrote. We'll see if I can manage to climb the support ladder.

**Comment by arvidn** [comment]
good catch. I chimed in on the thread. The case where this happens in libtorrent is when a disk thread destructs the last `shared_ptr<>` to a file object, and it unmaps and closes the file, while another thread is opening and mapping the same file. Is that right?

afaict, the file object, the file mapping and the file view are all tied together, and have the same life-time.

**Comment by ssiloti** [comment]
Yes that's right.

I haven't had a chance to really dig into fixing this yet. I may end up serializing the entire open/map and unmap/close sequences.
