### ISSUE TITLE
single file torrent failes to complete

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#3843]
libtorrent version (or branch): master
platform/architecture: Windows 64
compiler and compiler version: VS2015

Sometimes a torrent file fails to complete because of a few pieces fail the hash check. Pausing/Resuming and/or enforcing file check does not help. Only removing the torrent and adding it to the session again can fix this problem. And then the pieces get downloaded an pass the hash check or the file is already complete. So far I saw this happen only at the end of the downloads.
I thought that an enforced file check would also reset all related states and this problem should not occur.
Do the piece hashes get messed up?

**Comment by arvidn** [comment]
do you think this could be related to https://github.com/arvidn/libtorrent/issues/3842 ?

**Comment by MassaRoddel** [comment]
Only if piece data is written to file before hash check.
IMO, it is not related because I would expect that #3842 does not happen repeatedly for the same pieces after pause/resume.

**Comment by arvidn** [comment]
can you think of anything to narrow down what might be happening? do you still see the blocks be downloaded? do you see the peers participating in the failed piece to have their hash failure counter increase? do you see any peer go into parole mode or banned?

**Comment by arvidn** [comment]
maybe you could try to disable sparse files too, just to make sure it's not related to the issue steven found

**Comment by MassaRoddel** [comment]
I observed only two thinks so far - the same pieces keep failing and there is download rate. I will try to find out more. Is there any code to log/dump the complete torrent + peer data? So that I could log in case of piece hash failed alerts.

**Comment by MassaRoddel** [comment]
Finally, I encountered this problem again and collected some extra logs. What I can tell from the logs is that piece 596 keeps failing and finally it is the only missing piece. However after an enforced file check - four pieces are missing 596 - 599. The torrent completed only after I removed it from the session and added it again. Peer logs have been written on every hash failed alert; torrent.log.txt contains the list of pieces reported by libtorrent; 90512D5A6A0CE784C3B6BC8BCB948EA1073AE9C4.log.txt is my clients default log for this torrent;
The logfiles contain data until it was removed the first time from the session. (sparse files were enabled)
[90512D5A6A0CE784C3B6BC8BCB948EA1073AE9C4.zip](https://github.com/arvidn/libtorrent/files/3369601/90512D5A6A0CE784C3B6BC8BCB948EA1073AE9C4.zip)

**Comment by MassaRoddel** [comment]
After more observation the problem seems to be related to some peers/clients. It is not that the torrent never gets finished but as long as libtorrent can connect to the same peers/clients it seems to  request the same piece blocks again. It looks like as if one waits long enough - until some peers have left the swarm - the torrent can finish.
Shouldn't smart_ban handle that?
