### ISSUE TITLE
Unable to get previous file name/path in file_renamed_alert

### ISSUE THREAD

**Issue by Chocobo1** [arvidn/libtorrent#3847]
**Please provide the following information**

libtorrent version (or branch):
RC_1_2

platform/architecture:
Linux

compiler and compiler version:
gcc-8

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

There is no way (or I'm not aware of a way) to get the previous file name/path when handling `file_renamed_alert`.
An usage scenario is renaming "a/b/c" -> "a/d/c". I need to remove the empty folder "a/b" after the renaming operation is complete.
`torrent_info::orig_files()` seems to be like the answer but it isn't, because it returns the very original path from .torrent file, not the most recent one before the rename operation.

I imagine you could add a new field `char const* old_name () const;` to `file_renamed_alert` as a solution.

**Comment by arvidn** [comment]
adding a field to an alert breaks the ABI though, and can't be done until the next major release. I agree that it seems reasonable to include the previous filename. Can you think of any other ways to make this simpler? Technically, you could store the previous filename when you call `rename_file()`, but I recognise that's a bit cumbersome.

**Comment by Chocobo1** [comment]
>Technically, you could store the previous filename when you call rename_file(), but I recognise that's a bit cumbersome.

For a workaround in client side, I recon it would be a `unordered_map<file_idx, vector<string>>` for each torrent handle, because the rename operation is async and the user might issue a series of rename at the same time... very cumbersome.

**Comment by Chocobo1** [comment]
I would also like to request a similar field `char const* old_path() const;` for `storage_moved_alert`.

**Comment by arvidn** [comment]
does this look reasonable? https://github.com/arvidn/libtorrent/pull/4006

**Comment by Chocobo1** [comment]
>does this look reasonable? #4006

👍 
Also [this](https://github.com/arvidn/libtorrent/issues/3847#issuecomment-499143160) would be nice to have.
