### ISSUE TITLE
centos7   libtorrent 1.1.13 compiler error。

### ISSUE THREAD

**Issue by tt2014** [arvidn/libtorrent#3850]
[root@2vcpu-4gb libtorrent-rasterbar-1.1.13]# ./configure --prefix=/usr --enable-python-binding --with-libiconv
............
............
............
............
[root@2vcpu-4gb libtorrent-rasterbar-1.1.13]# make
Making all in include/libtorrent
make[1]: Entering directory `/root/libtorrent-rasterbar-1.1.13/include/libtorrent'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/libtorrent-rasterbar-1.1.13/include/libtorrent'
Making all in src
make[1]: Entering directory `/root/libtorrent-rasterbar-1.1.13/src'
  CXX      web_connection_base.lo
  CXX      alert.lo
  CXX      alert_manager.lo
  CXX      announce_entry.lo
  CXX      assert.lo
  CXX      bandwidth_limit.lo
  CXX      bandwidth_manager.lo
  CXX      bandwidth_queue_entry.lo
  CXX      bdecode.lo
  CXX      bitfield.lo
  CXX      bloom_filter.lo
  CXX      broadcast_socket.lo
  CXX      block_cache.lo
  CXX      bt_peer_connection.lo
  CXX      chained_buffer.lo
  CXX      choker.lo
  CXX      close_reason.lo
  CXX      ConvertUTF.lo
  CXX      cpuid.lo
  CXX      crc32c.lo
  CXX      create_torrent.lo
  CXX      disk_buffer_holder.lo
  CXX      disk_buffer_pool.lo
  CXX      disk_io_job.lo
  CXX      disk_io_thread.lo
  CXX      disk_job_pool.lo
  CXX      entry.lo
  CXX      enum_net.lo
  CXX      error_code.lo
  CXX      escape_string.lo
  CXX      file.lo
  CXX      file_pool.lo
  CXX      file_storage.lo
  CXX      fingerprint.lo
  CXX      gzip.lo
  CXX      hasher.lo
  CXX      hex.lo
  CXX      http_connection.lo
  CXX      http_parser.lo
  CXX      http_seed_connection.lo
  CXX      http_stream.lo
  CXX      http_tracker_connection.lo
  CXX      i2p_stream.lo
  CXX      identify_client.lo
  CXX      instantiate_connection.lo
  CXX      ip_filter.lo
  CXX      ip_voter.lo
  CXX      lazy_bdecode.lo
  CXX      lsd.lo
  CXX      lt_trackers.lo
  CXX      magnet_uri.lo
  CXX      merkle.lo
  CXX      metadata_transfer.lo
  CXX      mpi.lo
  CXX      natpmp.lo
  CXX      parse_url.lo
  CXX      part_file.lo
  CXX      pe_crypto.lo
  CXX      performance_counters.lo
  CXX      peer_connection.lo
  CXX      peer_connection_handle.lo
  CXX      peer_class.lo
  CXX      peer_class_set.lo
  CXX      piece_picker.lo
  CXX      platform_util.lo
  CXX      packet_buffer.lo
  CXX      proxy_base.lo
  CXX      peer_list.lo
  CXX      puff.lo
  CXX      random.lo
  CXX      receive_buffer.lo
  CXX      request_blocks.lo
  CXX      resolve_links.lo
  CXX      resolver.lo
  CXX      rss.lo
  CXX      session.lo
  CXX      session_call.lo
  CXX      session_handle.lo
  CXX      session_impl.lo
  CXX      session_settings.lo
  CXX      proxy_settings.lo
  CXX      settings_pack.lo
  CXX      smart_ban.lo
  CXX      socket_io.lo
  CXX      socket_type.lo
  CXX      socks5_stream.lo
  CXX      stat.lo
  CXX      stat_cache.lo
  CXX      storage.lo
  CXX      session_stats.lo
  CXX      string_util.lo
  CXX      thread.lo
  CXX      torrent.lo
  CXX      torrent_handle.lo
  CXX      torrent_info.lo
  CXX      torrent_peer.lo
torrent_peer.cpp:40:39: fatal error: boost/predef/other/endian.h: No such file or directory
 #include <boost/predef/other/endian.h>
                                       ^
compilation terminated.
make[1]: *** [torrent_peer.lo] Error 1
make[1]: Leaving directory `/root/libtorrent-rasterbar-1.1.13/src'
make: *** [all-recursive] Error 1
[root@2vcpu-4gb libtorrent-rasterbar-1.1.13]#

**Comment by arvidn** [comment]
here's a related ticket: https://github.com/arvidn/libtorrent/issues/3563
and patch: https://github.com/arvidn/libtorrent/pull/3593

what boost version are you using?

**Comment by nelinnemann** [comment]
install boost169-devel and enable scl. 
yum install devtoolset-7
scl enable devtoolset-7 bash

then

./configure --with-boost=/usr/lib64/boost169/ --with-boost-libdir=/usr/lib64/boost169/ CPPFLAGS=-I/usr/include/boost169/

and 

make && make install
