### ISSUE TITLE
update: configure.ac (and configure) needs libboost version test updating

### ISSUE THREAD

**Issue by Corin-EU** [arvidn/libtorrent#3852]
In the Changelog, it states

       1.2 release
             requires boost >= 1.58 to build"

However when I ran configure (from downloaded 1.2.1 release source archive file), it says

     Checking for boost libraries:
     checking for boostlib >= 1.54... yes

The test in configure.ac on line 145 (unchanged in latest GIT version)

      AX_BOOST_BASE([1.54])

needs updating to the new version requirement 1.58 and then the configure script regenerated.

**Comment by arvidn** [comment]
like this? https://github.com/arvidn/libtorrent/pull/3866
