### ISSUE TITLE
magnet trackers are missing with torrent_info overload of create_torrent

### ISSUE THREAD

**Issue by claw111** [arvidn/libtorrent#3855]
libtorrent version (or branch): 1.2.0 and 1.2.1
platform/architecture/compiler: Fedora 29/x86_64/gcc 8.3.1 20190223
python version: 3.7.3

Pseudo steps to reproduce using the python binding:
Given a magnet link that has trackers in the URL
And the magnet link is added to libtorrent
When the metadata has been received
Then a torrent file is created and saved.

The torrent file is actually created without any trackers (i.e.: There are no `announce` or `announce-list` sections in the **.torrent** file), even though the magnet URL provided the trackers.  It is expected that the torrent file is created with the original trackers provided by the magnet.

I suspect this behavioural regression stems from an incomplete refactor between `<torrent_handle>.torrent_file().trackers()` and `<torrent_handle>.trackers()`.

**Comment by claw111** [comment]
Sample code to reproduce the issue:
```python
import sys
import os
import libtorrent as lt

def _dump_trackers(handle):
    info = handle.torrent_file()
    print(repr((
        [
            x['url'] for x in info.trackers()
        ],
        [
            x['url'] for x in handle.trackers()
        ],
    )))

def _main():
    magnet = sys.argv[1] if 2 == len(sys.argv) else 'magnet:?xt=urn:btih:37863d0a2c11ef31cf894be1260ef61fef17517b&dn=Fedora-Server-dvd-x86_64-30&tr=http%3A%2F%2Ftorrent.fedoraproject.org%3A6969%2Fannounce13'

    params = lt.parse_magnet_uri(magnet)
    if isinstance(params, lt.add_torrent_params):
        session = lt.session()
        session.set_alert_mask(
            lt.alert.category_t.status_notification
            | lt.alert.category_t.error_notification
        )

        os.chdir(os.path.dirname(__file__))
        params.save_path = os.getcwd()
        session.add_torrent(params)

        done = False
        alerts = []
        while not done:
            if alerts:
                alert = alerts.pop(0)
                print(alert.message())
                if isinstance(alert, lt.metadata_received_alert):
                    handle = alert.handle
                    _dump_trackers(handle)
                    handle.pause()
                    handle = None
                elif isinstance(alert, lt.torrent_paused_alert):
                    handle = alert.handle
                    _dump_trackers(handle)

                    filename = str(handle.info_hash())
                    info = handle.torrent_file()
                    with open(filename + '.torrent', 'wb') as thefile:
                        thefile.write(lt.bencode(
                            lt.create_torrent(info).generate()
                        ))
                    info = None
                    filename = None

                    session.remove_torrent(handle, lt.options_t.delete_files)
                    handle = None
                elif isinstance(alert, lt.torrent_deleted_alert):
                    done = True
                elif isinstance(alert, lt.torrent_delete_failed_alert):
                    if alert.error_value() == 0:
                        done = True
                alert = None
            else:
                alerts = session.pop_alerts()
        alerts = None
        session = None
    params = None


if __name__ == '__main__':
    print(repr((lt.__version__, )))
    _main()

```

**Comment by joriscarrier** [comment]
I don't think trackers are part of the torrent metadata.

**Comment by claw111** [comment]
Correct.  However, trackers and metadata are part of the **.torrent** file format though.  WIthout trackers you can't find the swarm of other participants.

**Comment by joriscarrier** [comment]
you can add trackers to the creation of the .torrent file after receiving the metadata from the swarm

**Comment by claw111** [comment]
Thanks for suggesting a work-around.

Thinking it through, I feel that such a temporary measure introduced into the code bases that call libtorrent would ultimately have to be ripped out again when this reported bug with 1.2 is fixed.  Failure to remove the measure when the fix is released and updated would cause duplicated trackers to suddenly appear in any libtorrent-created **.torrent** files when provided to any torrent clients.

Additionally, the expected behaviour has existed since libtorrent 0.14.  Even the [reference documentation for libtorrent 1.2](https://libtorrent.org/reference-Alerts.html#metadata_received_alert) describes how to save the **.torrent** file correctly in order to load it back up again whenever a libtorrent session is restarted.

This smells like an bug introduced into 1.2 that is having unintended side-effects for `create_torrent::create_torrent(torrent_info const& ti)`.  However, upon my further reflection, would you be alluding that this bug won't be triaged for fixing in the 1.2 series?

**Comment by cas--** [comment]
This looks like a regression in 1.2, the trackers are missing from the torrent_info for magnets:

1.2.1
```
list(handle.get_torrent_info().trackers())
[]
```

1.1.11
```
list(handle.get_torrent_info().trackers())
[<libtorrent.announce_entry object at 0x7fbc351e1650>]
```

**Comment by arvidn** [comment]
I've just briefly looked at this, but it looks like your suspicion is definitely pointing in the right direction. Normally, the `torrent_info` object is treated as immutable. This is because it's shared between the libtorrent thread and the clients' threads (potentially), as `const` pointers. If either thread could mutate that object thread safety would become a lot more complex.

I will have to dig a bit in the history, but I don't think the `torrent_info` object was ever updated when the metadata was received, to include the trackers.

I'm inclined to think the right fix is to update the documentation to caution about this issue and fix the example to use the `torrent_handle` overload of `create_torrent`.

**Comment by arvidn** [comment]
this is happening in `RC_1_1`: https://github.com/arvidn/libtorrent/blob/RC_1_1/src/torrent.cpp#L834
but I don't think that's done in `RC_1_2`

**Comment by arvidn** [comment]
I'm still not convinced that `RC_1_1` is the better approach though. Although I recognise it's not good to have a regression. Perhaps a magnet link could be a special case. Would that make sense?

`RC_1_2` improves the situation a bit by actually *automatically* saving the torrent file when saving resume data. When adding a torrent via a magnet link, when saving resume data, that resume data file will also be a valid .torrent file (as in it will have an `info` dictionary with a verbatim copy of the torrent metadata). This means that it's sufficient to load the fastresume file, and the torrent will be picked up. (This is cleaned up a bit further in `master`, which will be the next major release).

**Comment by arvidn** [comment]
I was convinced there was a `create_torrent` constructor that take a `torrent_handle`.. but I can't find one ever, throughout history.

**Comment by arvidn** [comment]
@claw111 does this look reasonable? https://github.com/arvidn/libtorrent/pull/3862

**Comment by arvidn** [comment]
one thing that probably should be clarified in the documentation is that trackers and web seeds added to a `torrent_handle` won't be included in the associated `torrent_info` object. I think this is a motivation for *having* a `create_torrent()` constructor that takes a `torrent_handle`.

**Comment by claw111** [comment]
@arvidn I'm taking a look at #3862 now.  I'll post comments specific to the changes onto that, leaving this ticket for bigger architectural discussion and decision making.

I really do appreciate that this is not going to be a quick fix because `torrent_info` is heavily overloaded with atleast 3 different representations (maybe more to come as I work through the code myself).  The internal, mutable representation within the library and atleast 2 external API representations - accessible from `torrent_handle` (presumably this ought to be mutable for manipulation of trackers, seeds, etc) and from `torrent_status` which should be immutable and contain the snapshot of the state of the system at the time of the query.

My gut tells me that `torrent_info` needs to be refactored to be split into 3 classes to accommodate the concerns.  Keep `torrent_info` as your internal representation, but maybe? inherit from a new immutable class representation.  The new mutable representation can also inherit from the immutable class representation but access and obtain appropriate locking on `torrent_handle` (perhaps?) to manipulate the internal state and at the same time update itself with the new changes.  My key thought here is the immutable and mutable class representations are provided for external representations only and are initially cloned/copied from the internal `torrent_info` when required, effectively providing a snapshot in time of the system/handle state (i.e.: these scope of these objects should be short lived).

Introducing an overload of `torrent_handle` for `create_torrent()` makes perfect sense to me, but as long as the `torrent_info` overload for `create_torrent()` is deprecated.

However, I of course do humbly defer to your vast experience and architectural knowledge of the code, because my suggestion would introduce even more API breakages for 1.2 - assuming breaking more eggs is acceptable to finish making the omlette which has already been started ;)

**Comment by arvidn** [comment]
a running torrent has an internal representation (the `torrent` class) where trackers, web seeds etc are all mutable. This object has a reference to the corresponding `torrent_info` object, the torrent it was started from.

I would say these lines are primarily blurred by the direction `add_torrent_params` is moving in, where it's the in-memory representation for resume data. It's written to disk with `write_resume_data()` and parsed with `read_resume_data()` (this is in master).

`torrent_info` is meant to hold the parsed state of a .torrent file. When you suggest splitting it into separate classes, I take it you're thinking that some parts can be immutable while others aren't. I don't think it necessarily needs to be split into multiple classes for that, I think the mutable portions could be tacked on. But I'm not sure `torrent_info` is the right place to do that. I think `add_torrent_params` is better. It includes the metadata (i.e. the `info` dictionary) as well as all trackers, web seeds, announce URLs, DHT nodes, peers, resume data, save-path, file priorities and other things too. So in a way it's like a torrent-file plus.

**Comment by arvidn** [comment]
I think it's fine to add torrents from `add_torrent_params` (which either come from resume data or from magnet link) when we don't have a complete torrent yet (i.e. when it was added from magnet link). At that point the `torrent_info` object will not have been shared with the client yet. In fact, it turns out that the `torrent_info` object is never shared with the client until *after* metadata is received. So, this patch doesn't affect thread safety.
