### ISSUE TITLE
Separating outbound and incoming traffic in Deluge

### ISSUE THREAD

**Issue by kevindd992002** [arvidn/libtorrent#3856]
**Please provide the following information**

libtorrent version (or branch): libtorrent-rasterbar9/now 1.1.5-1build1 amd64

platform/architecture: Debian Stretch Backport

compiler and compiler version: I'm a Linux noob and I'm simply using the linuxserver/deluge docker container so I'm not sure how to answer this

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Reference Deluge thread: https://forum.deluge-torrent.org/viewtopic.php?f=7&t=55375

So I have a site-to-site VPN link. My local site is behind a CGNAT network (not good for torrents) and my remote site has a static public IP subscription that I use. My media server (Debian) has docker containers and one of them is Deluge.

So what I did was to assign another IP (virtual IP) on my docker host's NIC so that I can use that for the incoming part in Deluge. Let's call them IP1 for outgoing (routes through the local site's WAN) and IP2 for incoming (routes through the remote site's WAN and port forwarded properly). Here's what I did to test and my observations:

I assigned a static incoming port and assigned IP2 as the incoming address. External address (in the bottom pane of Deluge) is now showing the remote's site external IP address. Port forward from remote site WAN to IP2 is confirmed working by testing in canyouseeme.org but test active port still gives an exclamation point. I did a packet capture on all interfaces along the route all is routed properly but the test active port won't still give me an OK outcome.

I assigned IP1 to the outgoing interface but when I tried downloading a torrent and inspecting the traffic, it looks like it uses IP2 as the source IP which is not what I want.

Leaving the incoming address empty while outgoing interface is still set to IP1 results into a source address of IP1(the expected result) when downloading a torrent. So it looks like Deluge doesn't want IP addresses with different external IP's for the incoming address and outgoing interface fields.

Any more ideas? I'm kinda at a lost here as I did everything correctly. I have a handful of servers in the local site that can be accessed properly using the remote site's WAN IP so setting port forward and policy-based routing in pfsense is not new to me.

EDIT1:
I tried using this IP check: https://torguard.net/checkmytorrentipad ... 1bccbb3e83 to see what IP address peers see when I download torrents. Surprisingly, it lists my local site's WAN IP when it is supposed to be my remote site's WAN IP (as shown in the external IP address field in the bottom of the GTK UI). So I think this is the problem. My question now is how does Deluge determine which external IP it will announce to its peers to download data from? Does it do this by putting an HTTP request against a Deluge server perhaps?

EDIT2:
That is indeed the cause of the issue. I've verified this by routing all traffic from my Deluge box source IP to go through the VPN and true enough the external IP address seen by that checkIP torrent listed my remote site's WAN IP. So I really need to know how Deluge determine's the external IP address to use so that I can route that specific traffic over through my VPN tunnel. There are other services in this box so I cannot route all traffic through the tunnel, only specific ones. Besides, my goal here is for Deluge to use my local site's WAN for outbound connections and my remote site's WAN for incoming connections.

This also doesn't answer question number 2 above.

**Comment by arvidn** [comment]
it's not clear to me what you're looking to do. there is no way (generally) to have all outgoing traffic be sent on one interface, and all incoming traffic on another.

The settings you have in libtorrent are "listen_interfaces", i.e. the local interface to bind the listen socket(s) to, and "outgoing_interfaces", i.e. the local interface to bind outgoing sockets to. Note that this last part is not well defined across operating systems. You can't generally force a socket to use a specific interface, that's decided by the routing table. However, there are some extensions like `SO_BINDTODEVICE`, and libtorrent makes some attempts to make that happen.

However, this is not binding *traffic*, it's binding one end of a TCP *connection*. Traffic still moves in both directions over that connection.

**Comment by kevindd992002** [comment]
> 
> 
> it's not clear to me what you're looking to do. there is no way (generally) to have all outgoing traffic be sent on one interface, and all incoming traffic on another.
> 
> The settings you have in libtorrent are "listen_interfaces", i.e. the local interface to bind the listen socket(s) to, and "outgoing_interfaces", i.e. the local interface to bind outgoing sockets to. Note that this last part is not well defined across operating systems. You can't generally force a socket to use a specific interface, that's decided by the routing table. However, there are some extensions like `SO_BINDTODEVICE`, and libtorrent makes some attempts to make that happen.
>
> However, this is not binding _traffic_, it's binding one end of a TCP _connection_. Traffic still moves in both directions over that connection.

I understand that. Traffic is always two way. If an outgoing (from your internal network to the Internet) goes one interface, then the reply incoming traffic should also go through the same interface, else everything gets messed up. My goal is not to totally separate outgoing and incoming traffic. I guess I'm using the wrong terms but let me explain my situation:

I have two home sites (100Km or so apart) that use the same ISP. Site A (where I stay, so local to me) is behind a CGNAT so port forwarding isn't possible. Site B (remote to me) has a static public IP subscription. A site-to-site VPN is setup between the two and all my resources (whether they're located in either site) go through site B first because all port forwards are set there.

I have Deluge setup in site A and what I want is for it to use my local WAN (no VPN traffic) when downloading (outbound) and broadcast/announce site B's WAN IP so that peers will connect to that IP and get data from my Deluge server through the VPN connection. I have similar setup with my Plex server and it works just fine.

My Deluge server is included in a NAS server with multiple services (using Docker containers) like Plex, Radarr, Sonarr, etc. It has 1 active NIC and 1 disabled NIC. Since all use the IP of the active NIC, I decided to assign a virtual IP to that same NIC for Deluge alone, to keep things separate because I don't want to tinker with traffic of the other services. 

Here are some of test results/observations:

1. Routing both outbound and inbound traffic of the real IP of the NAS server (both incoming address and outbound interface fields in Deluge blank) through the VPN connection gives me a check status when I test the port in Deluge. All working there but this is not the ideal setup because downloading torrent data will route through the VPN also.

2. When I assign the same Deluge fields the virtual IP and route both outbound and inbound traffic of that virtual IP through the VPN connection, I get an exclamation point in the Deluge test port button BUT canyouseeme.org sees that the listening port is open. This tells me that port forwarding is setup correctly but Deluge is announcing my local WAN's IP instead of the remote WAN's IP.

I hope I'm making sense here. If not, please let me know what's clear and I'll try to explain more.

**Comment by kevindd992002** [comment]
@arvidn 

Do you have any more ideas here?

**Comment by kevindd992002** [comment]
Just following up on this again, not sure if that's fine.

**Comment by kevindd992002** [comment]
@arvidn 

So to simplify things, what I did is to just make it simple and use the virtual IP that I assigned to my media server as incoming address and outgoing interface. This virtual IP is the routed through my OpenVPN tunnel and it uses the public IP of the the WAN interface on the remote side of the tunnel.

Everything works properly but in torrentday all my uploads are somewhat doubled which I don't get. For every torrent, there are two entries, one with my own network's public IP and one with the remote tunnel network's public IP. So if Deluge is really just using the virtual IP (as set in its settings) then all traffic should route through the OpenVPN tunnel and torrentday should never even see that my network's public IP is uploading data.

Can you help me trace why this is happening? Thanks.
