### ISSUE TITLE
no storage_moved_failed_alert for invalid drive letters on windows

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#3857]
libtorrent version (or branch): master
platform/architecture: Window 7
compiler and compiler version: vS2015
example: new save path: B:\ (B does not exist)
Instead of alert storage_moved_failed_alert alert storage_moved_alert is received.
The problem is that state_file() returns error code 3 (ERROR_PATH_NOT_FOUND) but libtorrent checks only for code 2 (ERROR_FILE_NOT_FOUND/boost::system::errc::no_such_file_or_directory) in create_directories. It seems libtorrent does not care for error code 3 at all.

**Comment by arvidn** [comment]
@MassaRoddel did you try to add the check for `ERROR_PATH_NOT_FOUND` and test? if so, does that appear to be a sufficient fix?

**Comment by MassaRoddel** [comment]
I have not tested any modification yet. But I thought about a modification in state_file() which would replace error code ERROR_PATH_NOT_FOUND  with ERROR_FILE_NOT_FOUND.

**Comment by MassaRoddel** [comment]
I tested my idea and modified state_file(). That failed because libtorrent then thinks it can create that path with create_directories(). However that has the flaw that is_root_path() returns true even if it does not exist.
Seems Boost has no error code for path not found. So the fix seems a bit more complicated.
Modifying this in create_directories():
if (ec != boost::system::errc::no_such_file_or_directory
	|| ec.value()==ERROR_PATH_NOT_FOUND)
	return;
fixed the problem. 
But the alert message is missing the path: 	storage move failed. mkdir (): ...
The error text part is ok.

**Comment by arvidn** [comment]
my understanding is that boost.system is supposed to translate via `error_condition`. But I suppose I may not be using this right if I'm comparing directly against an `error_code`.

The comparison against `ERROR_PATH_NOT_FOUND` really has to be against `error_code(ERROR_PATH_NOT_FOUND, system_category())`, to indicate that this is the native system error code category.

**Comment by arvidn** [comment]
if this change fixes the problem:
```
if (ec != boost::system::errc::no_such_file_or_directory
   || ec.value() == ERROR_PATH_NOT_FOUND)
```

That suggests that `ERROR_PATH_NOT_FOUND` is in fact treated as `no_such_file_or_directory`, which I think makes sense.

I think maybe a cleaner fix would be to make `create_directories()` not be satisfied with just `is_root_path()` (which is a textual property), but it should also `stat()` the path to make sure it actually exists.

**Comment by arvidn** [comment]
does this work? https://github.com/arvidn/libtorrent/pull/3864

**Comment by MassaRoddel** [comment]
That seems to work.
Windows behavior is like:
child path does not exit ->ERROR_FILE_NOT_FOUND
parent path does not exist ->ERROR_PATH_NOT_FOUND
