### ISSUE TITLE
Python add_torrent priorities/download limit params problems

### ISSUE THREAD

**Issue by elig0n** [arvidn/libtorrent#3860]
libtorrent version:
This is what pip for python3 say that I have:

> python-libtorrent (1.1.0)       - Python bindings for libtorrent-rasterbar
>     INSTALLED: 1.1.12
>     LATEST:    1.1.0

platform/architecture:
Linux x86_64

compiler and compiler version:
Python 3.7.3
Ditto on Python 2.7.16

Description of the problem:
I'm trying to retrieve only metadata for magnet link. I did it like [described here](https://www.libtorrent.org/manual-ref.html#magnet-links)  

    h = ses.add_torrent({ 
        'save_path': "./" ,
        'info_hash': some_info_hash,
        'file_priorities': [0] * 1000 })

But still download would start at max speed, even when there are only one three files to download.
In runtime, file priorities become 4 for all files. If I use `h.prioritize_files()` in code or interactive it is then set correctly

Using the param 'download_limit': 1 did not work either. 
Again, in an interactive python session I must use h.set_download_limit(1) function to get a very low download speed to throttle it.

Also, `s.download_rate` `s.num_peers` `s.progress` were all 0 value during active download,
while `s.state` would be `libtorrent.states.downloading_metadata`.

**Comment by arvidn** [comment]
This appears to have been fixed in libtorrent 1.2.0, but I see it's an issue in 1.1.x.

Does this patch fix it? https://github.com/arvidn/libtorrent/pull/3861
