### ISSUE TITLE
Empty tracker list in fastresume

### ISSUE THREAD

**Issue by proninyaroslav** [arvidn/libtorrent#3869]
libtorrent version (or branch): **1.2.0.0**
platform/architecture: **Android**

To make it clear, I'll start with the use case: when I add a torrent file, the trackers from this file are written to `fastresume`. 
When I delete all trackers using `torrent_handle::replace_trackers(empty_list)`, the trackers from `fastresume` are also deleted. But here a problem arises: if absolutely all trackers are deleted, libtorrent **again** writes the trackers that are located in the torrent file into `fastresume` (after start session). 

I studied `qBittorrent` (which also uses `libtorrent`) and found that after removing all the trackers in `fastresume`, followed string remains: `trackersllee`. In other words, `fastresume` contains only format stub, without any URL's. This allows `libtorrent` not to write trackers from a torrent file to `fastresume` again after start session. In my case, while saving `fastresume` to the file, I didn't  find such a stub, and therefore `libtorrent` again writes the trackers that are located in the torrent file into `fastresume`.

Do I understand correctly that `libtorrent` doesn't support writing `trackersllee` stub and `qBittorrent` uses a modified version of `libtorrent` for this? I would like to see this behavior in `libtorrent` by default (or as an option), as it causes problems with removing trackers. In this case, I will have to delete the trackers from the torrent file, which isn't optimal.

**Comment by arvidn** [comment]
if you save resume data, get the `save_resume_data_alert`, pick up the `params` member of the alert (which is of type `add_torrent_params`). You pass `params` into `write_resume_data()` which turns it into a bencoded buffer or `entry` type.

This bencoded buffer does not contain the trackers. You can deserialize the buffer using `read_resume_data()` to get it back into an `add_torrent_params` object, which you can add back into the session. It should not have the trackers in it.

However, if you use the old-style of adding the .torrent file back into the session, passing in the resume data, you'll have to also set the `override_trackers` flag (on the `add_torrent_params`), to actually avoid loading the trackers from the .torrent file.

I think the first approach is simpler. It also means you don't have to keep the .torrent file around separately from the resume data.

Please let me know if any of this does not work as I explained it, then there may be a bug.

**Comment by proninyaroslav** [comment]
Ok, i'll check it out in the coming days. If there are no problems, I will close this issue.

**Comment by proninyaroslav** [comment]
Thank you, `fast resume` to restore the session (instead of the torrent file) works for me.
