### ISSUE TITLE
_acrt_first_block==header

### ISSUE THREAD

**Issue by jiangfeng15** [arvidn/libtorrent#3870]
**Please provide the following information**

libtorrent version (or branch):1.2

platform/architecture: win10

compiler and compiler version: vs2017

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

when I test my client project, i get a error like "_acrt_first_block==header", code run at lt::settings_pack pack; lt::session ses(pack);

**Comment by arvidn** [comment]
when you say you get an "error", what do you mean? clearly not a compile error. who give you this error? where do you get this error? stderr?

**Comment by jiangfeng15** [comment]
I compile the torrent-rasterbar.dll with vs2017，Use Standard Windows Libraries and runtime library use /MD，I succeeded in getting torrent-rasterbar.dll and torrent-rasterbar.lib. I create a project for client later on. The project use MFC in a Static Library and  runtime library use /MT, when I compile the code of project, It was successful and get no errors, but when I run the code, I encounter this error. The error is  "__acrt_first_block == header " at line 996 of "debug_heap.cpp " . I want to use MFC in a Static Library to compiler the code, at last , I add a line like "#define _AFXDLL" in the "stdafx.h" and runtime library use /MD, I run the code successfully. but how to solve the problem when I use  MFC in a Static Library and  runtime library use /MT.
`	lt::settings_pack pack;
	pack.set_int(lt::settings_pack::alert_mask
		, lt::alert::error_notification
		| lt::alert::storage_notification
		| lt::alert::status_notification);
	lt::session ses(pack);//encouter debug assert failed`

**Comment by arvidn** [comment]
this sounds like an ABI incompatibility. most likely because you're linking static libraries together that are incompatible

**Comment by arvidn** [comment]
look up how the windows heap works across libraries, and static/shared linking to the runtime libraries

**Comment by MassaRoddel** [comment]
Why not create a libtorrent for static linking too?

**Comment by arvidn** [comment]
You can specify link=static to link statically. But if you link the *run-time* statically, you cannot interact with dynamically linked libraries, because they would have different heaps and not be able to share allocations

**Comment by jiangfeng15** [comment]
ok, I will try again as you said and tell you the test results.

**Comment by Col-blimp** [comment]
no dont bother
________________________________
