### ISSUE TITLE
HI What is the command to compile python3 now?

### ISSUE THREAD

**Issue by kslr** [arvidn/libtorrent#3872]
**Please provide the following information**

libtorrent version (or branch):
1.12
platform/architecture:
Ubuntu 18.04
compiler and compiler version:

I'm sorry I didn't find too much information.
I wonder what the best compilation command to support python3 at this moment is?

Old
```
./configure --enable-python-binding --with-libiconv
make -j install
```
is that useful?
```
PYTHON      the Python interpreter
PYTHON_VERSION
PYTHON_INSTALL_PARAMS
```

**Comment by arvidn** [comment]
I'm not sure what automake does for python bindings. it may depend on what version your installed boost.python is built for.

you can always build it with boost-build, in which case you specify the python version on the `b2` command line with `python=3.7`

**Comment by Chocobo1** [comment]
@kslr 
If you use cmake: 
See the build() function: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libtorrent-rasterbar-1_2-git#n25

**Comment by kslr** [comment]
@arvidn @Chocobo1 thanks
I wasted a lot of time in boost_python3. I have to use ppa directly.
https://launchpad.net/~libtorrent.org/+archive/ubuntu/1.2-daily

**Comment by Col-blimp** [comment]
fuck off
________________________________
