### ISSUE TITLE
 [Feature suggestion] Download .torrent file from webseed

### ISSUE THREAD

**Issue by ivan386** [arvidn/libtorrent#3874]
**Please provide the following information**

libtorrent version (or branch): 1.0.7.0

platform/architecture: windows 7

compiler and compiler version: do not know

We have magnte link with webseed:
```magnet:?xt=urn:btih:0000000000000000000000000000000000000000&ws=http://exapmle.com/file.avi``` 

Have infohash, data on server and no seeds in dht. Client can't start download data from webseed until it get .torrent.

Client can try dowload .torrent file from webseed.

**First try:**

Append ".torrent" extension to webseed link.

Single file:
```http://exapmle.com/file.avi --> http://exapmle.com/file.avi.torrent```

Multifile:
```http://exapmle.com/dirrectory/ --> http://exapmle.com/dirrectory.torrent```

If client rescieve 404 error or infohash not match.

**Second try:**

Replace file or dirrectory name with infohash with ".torrent" extension.

Single file:
```http://exapmle.com/file.avi --> http://exapmle.com/0000000000000000000000000000000000000000.torrent```

Multifile:
```http://exapmle.com/dirrectory/ --> http://exapmle.com/0000000000000000000000000000000000000000.torrent```

**Comment by arvidn** [comment]
wouldn't it be simpler to just have a separate argument containing the link to the torrent file? In fact, I'm seem to recall there is some existing convention for that in magnet links. `&as=`.

the complicated part is the logic that decides when it's time to fall back to an http download.

**Comment by ivan386** [comment]
This blowup magnet link.
```magnet:?xt=urn:btih:0000000000000000000000000000000000000000&ws=http://exapmle.com/file.avi&as=http://exapmle.com/file.avi.torrent```

When many webseeds in magnet client can try it all one by one. It will not cost much souces for client and server.

If after 10 seconds no peers found in DHT then client start to try webseeds. If after 30 secons it can't download info part from peers it try webseeds.

**Comment by ivan386** [comment]
xs, as and ws used by shareaza for direct links to file.
https://github.com/svn2github/shareaza/blob/master/shareaza/ShareazaURL.cpp#L588
