### ISSUE TITLE
stack use after return in socket_type.cpp

### ISSUE THREAD

**Issue by mkatsevVR** [arvidn/libtorrent#3876]
https://github.com/arvidn/libtorrent/blob/master/src/socket_type.cpp#L179 is passing a local variable `buffer` by pointer to the async function, which will read it after the original function has returned and the address is not valid anymore. An easy fix would be to declare the variable as static.

**Comment by arvidn** [comment]
Should probably be back ported to 1.1.13 as well

**Comment by arvidn** [comment]
fixed here: https://github.com/arvidn/libtorrent/pull/3881

**Comment by arvidn** [comment]
back ported here: https://github.com/arvidn/libtorrent/pull/3882

**Comment by arvidn** [comment]
thanks for the report!
