### ISSUE TITLE
bug in entry operator = 

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#3879]
libtorrent version (or branch): master

There seems to be a problem if a bdecode() result gets assigned to an entry that has already content.
I think the problem is caused by the assignment operator, which does not delete the existing entry content so that old content is preserved after the assignment.
IMO, the following two function have to call destruct() in case of list or dictionary content.
 
	// convert a bdecode_node into an old skool entry
	entry& entry::operator=(bdecode_node const& e) &
	{
...
	// convert a lazy_entry into an old skool entry
	entry& entry::operator=(lazy_entry const& e) &
...

**Comment by arvidn** [comment]
yeah, I think you're right. This problem dates back a long time. I'll fix it in `RC_1_1` and forward I think

**Comment by arvidn** [comment]
RC_1_1: https://github.com/arvidn/libtorrent/pull/3883
RC_1_2: https://github.com/arvidn/libtorrent/pull/3884
