### ISSUE TITLE
artificial bandwidth limit even if no bandwidth limit has been set

### ISSUE THREAD

**Issue by r79** [arvidn/libtorrent#3886]
**Please provide the following information**

libtorrent version (or branch): 1.1.13.0

platform/architecture: Arch Linux 5.2.1.arch1-1

compiler and compiler version: precompiled (Repository)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I'm using libtorrent with deluge. I already opened [a bug at their bugtracker](https://dev.deluge-torrent.org/ticket/3290) but slowly started to realize that this might actually be an issue with libtorrent itself (I haven't read deluge's source yet but I might get in there if this bug persists).

This is basically a copy paste of that issue (in order to save you from opening another link):

# Issue

Even with all bandwidth related settings set to -1 (or -1.0) I'm unable to get a DL speed faster then around 30M/s, currently with 22 active downloads, 508 connections and on a private tracker.

## Background

Deluge is running **headless** on **Arch** with the newest kernel (**5.2.1.arch1-1**). It's running in a **virtualized environment using Proxmox.** The cache is set according to the RAM available and at it's topmost setting (with the idea that more cache -> more speed). According to the disk usage, the write cache seems to be ignored though, which I might put into another ticket / do some research on. The **RAM usage** is at around **14GB of 17.5GB** (due to the 14 gigs cache I set, see the config below), the **CPU usage** at around **2.56 cores of 4 cores**.

The **router** is an old Server blade with like **24 cores and 24GB RAM**, running an **opnSense that is seriously tired** and completely unchallenged by the load (HW usage is at around 1 core and 1 GB RAM tops). The **WAN** is a **symmetrical Gigabit** connection that has some loss (I think the transceiver sucks), with an actual speed of around 700Mbps symmetrical (although it seems to be fluctuating a bit at times).

In order to maintain separation of concern, we're using a **separate (virtualized) server as fileserver** (as we're also running Plex). It's connected with **sshfs** with speed optimizations (cache, compression, chacha20 algo, some others) and in theory running over the LAN, in practice it shouldn't (we're still figuring that part out and probably create a virtual network to boost those speeds a bit).

The config can be seen below.

## What I did so far

- Fiddled around with the cache (smaller, higher, longer expiry, shorter expiry)
- checked sshfs speeds (copied a file with rsync and back, the speed was at around 30mb/s read and 80mb/s write, no impact on deluges speed at all)
- checked sshfs speeds from another pc (same scenario, no impact on deluges speed at all)
- did a speedcheck using fast.com, reached 600Mbps, no impact on the deluges speed at all
- changed the max connections and the connections per torrent, the speeds of the individual seeders went up, but the overall speed stayed the same
- restarted deluge
- added a file from a public tracker with like 8000 seeders, I got around 500 more connections, the speed of that file was pretty solid, but the overall speed stayed the same (it stole speed from the private trackers files).
- changed the max_download_speed to the highest value the gtk client let me, no impact on deluges speed at all
- removed "Auto Managed" from the torrents
- downloaded a torrent with the preallocated setting 

None of those things either changed the download speed nor fixed the problem. I feel like something should be bottlenecking there, but all the bottlenecks I could think of were checked, which makes me believe that this must be a bug, hence this report. 

# Config
Although the config is from deluge itself and therefore has nothing to do with libtorrent, I'm pretty sure some of these values are just passed to libtorrent, hence it might become interesting for you. If that's not the case I'm sorry for wasting githubs disk space :p

```╰─$ sudo cat core.conf
{
    "file": 1,
    "format": 1
}{
    "add_paused": false,
    "allow_remote": true,
    "auto_manage_prefer_seeds": false,
    "auto_managed": true,
    "cache_expiry": 240,
    "cache_size": 917868,
    "copy_torrent_file": false,
    "daemon_port": 58846,
    "del_copy_torrent_file": false,
    "dht": false,
    "dont_count_slow_torrents": false,
    "download_location": "/srv/deluge/ocean/Random",
    "download_location_paths_list": [
        "/srv/deluge/ocean/Series",
        "/srv/deluge/ocean/Random",
        "/srv/deluge/ocean/Movies"
    ],
    "enabled_plugins": [],
    "enc_in_policy": 1,
    "enc_level": 2,
    "enc_out_policy": 1,
    "geoip_db_location": "/usr/share/GeoIP/GeoIP.dat",
    "ignore_limits_on_local_network": true,
    "info_sent": 0.0,
    "listen_interface": "",
    "listen_ports": [
        6881,
        6881
    ],
    "listen_random_port": null,
    "listen_reuse_port": true,
    "listen_use_sys_port": false,
    "lsd": true,
    "max_active_downloading": -1,
    "max_active_limit": -1,
    "max_active_seeding": -1,
    "max_connections_global": -1,
    "max_connections_per_second": -1,
    "max_connections_per_torrent": -1,
    "max_download_speed": -1.0,
    "max_download_speed_per_torrent": -1,
    "max_half_open_connections": -1,
    "max_upload_slots_global": -1,
    "max_upload_slots_per_torrent": -1,
    "max_upload_speed": -1.0,
    "max_upload_speed_per_torrent": -1,
    "move_completed": false,
    "move_completed_path": "/srv/deluge/Downloads",
    "move_completed_paths_list": [
        "/srv/deluge/ocean/Series",
        "/srv/deluge/ocean/Movies"
    ],
    "natpmp": true,
    "new_release_check": true,
    "outgoing_interface": "",
    "outgoing_ports": [
        0,
        0
    ],
    "path_chooser_accelerator_string": "Tab",
    "path_chooser_auto_complete_enabled": true,
    "path_chooser_max_popup_rows": 20,
    "path_chooser_show_chooser_button_on_localhost": true,
    "path_chooser_show_hidden_files": false,
    "peer_tos": "0x00",
    "plugins_location": "/srv/deluge/.config/deluge/plugins",
    "pre_allocate_storage": false,
    "prioritize_first_last_pieces": false,
    "proxy": {
        "anonymous_mode": false,
        "force_proxy": false,
        "hostname": "",
        "password": "",
        "port": 8080,
        "proxy_hostnames": true,
        "proxy_peer_connections": true,
        "proxy_tracker_connections": true,
        "type": 0,
        "username": ""
    },
    "queue_new_to_top": false,
    "random_outgoing_ports": true,
    "random_port": false,
    "rate_limit_ip_overhead": false,
    "remove_seed_at_ratio": false,
    "seed_time_limit": -1,
    "seed_time_ratio_limit": -1.0,
    "send_info": false,
    "sequential_download": false,
    "share_ratio_limit": -1.0,
    "shared": false,
    "stop_seed_at_ratio": false,
    "stop_seed_ratio": 2.0,
    "super_seeding": false,
    "torrentfiles_location": "/srv/deluge/Downloads",
    "upnp": true,
    "utpex": true
}% 
```

**Comment by arvidn** [comment]
My first guess would be that the disk setup combined with the hight throughput creates a large bandwidth delay product. I’m assuming that the SAN has noticeable latency. This would not be a problem for something like cp. however, libtorrent limits the number of bytes it has queued up to the disk I/O thread. If that buffer is small and the disk latency is high, you may get stalls.

I would suggest you try raising the max_queued_disk_bytes setting.

If you’re downloading slower than you would expect from individual peers, you may also want to raise max_out_request_queue.

**Comment by r79** [comment]
Thanks a lot! I'll try this out :)

I actually might have found another bottleneck I'm investigating when I updated my disks, which I'm still investigating though: It's possible that the virtualization of Proxmox and LVM itself is taxing on the I/O Throughput. I'll investigate this further once my new disks are running (which are attached with virtio -> direct access from the vm without any management overhead from the virtualization).

**Comment by r79** [comment]
Alright, we fixed all possible latency issues now. The two VMs are now connected with a virtual bridge (and are hence not routing over the switch) and the drives are connected directly to the Storage VM (instead of the previous LVM).

The ping between the two VMs is at below 1ms, the latency on the disks is fluctuating between 1ms and 10ms (on heavy write spikes), usage is at around 50%, yet the torrent speeds still stay at some magical limit of around 15MB/s.

So yeah, looks like I gotta fiddle around with the deluge source (as they don't expose those settings you mentioned).

Thanks a huge lot for the help, I'll get back to you once I fought my laziness and created that PR over at deluge's page :)
