### ISSUE TITLE
AttributeError: module 'libtorrent' has no attribute 'session'

### ISSUE THREAD

**Issue by GrahamboJangles** [arvidn/libtorrent#3887]
**libtorrent version (or branch):** 1.2.1

**platform/architecture:** windows

**compiler and compiler version:** idk how to find that out

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I get the error: `AttributeError: module 'libtorrent' has no attribute 'session'` anytime I try to do anything.

**Comment by arvidn** [comment]
You don’t get any other errors before this saying it failed to load or find the module itself?
You can take a look at the appveyor CI for an example of using the python binding on windows

**Comment by GrahamboJangles** [comment]
@arvidn Here's the full error:
```python
AttributeError                            Traceback (most recent call last)
<ipython-input-20-8c21dcae694c> in <module>()
      1 import os
      2 os.chdir("/content/libtorrent/bindings/python/")
----> 3 import simple_client.py

/content/libtorrent/bindings/python/simple_client.py in <module>()
      9 import sys
     10 
---> 11 ses = lt.session({'listen_interfaces': '0.0.0.0:6881'})
     12 
     13 info = lt.torrent_info(sys.argv[1])

AttributeError: module 'libtorrent' has no attribute 'session'
```

**Comment by arvidn** [comment]
I would suspect that the import libtorrent as lt line also would print an error. You’re saying it doesn’t?

**Comment by GrahamboJangles** [comment]
@arvidn That's right, the error only occurs when using the attribute 'session'. Importing libtorrent itself is fine. 

I've had many problems like this before (module 'x' has no attribute 'y') so I'm wondering if I'm doing something wrong somewhere. Also, I'm sorry I should have mentioned I'm using Google Colab on Windows.

**Comment by arvidn** [comment]
Can you list what’s actually in the module? Is there anything? I don’t know about google colab, does it support native modules?

**Comment by GrahamboJangles** [comment]
@arvidn Sure! `inspect.getmembers(libtorrent)` returns 
```[('__doc__', None),
 ('__loader__',
  <_frozen_importlib_external._NamespaceLoader at 0x7fca0ef98cf8>),
 ('__name__', 'libtorrent'),
 ('__package__', 'libtorrent'),
 ('__path__', _NamespacePath(['/content/libtorrent'])),
 ('__spec__',
  ModuleSpec(name='libtorrent', loader=None, origin='namespace', submodule_search_locations=_NamespacePath(['/content/libtorrent'])))]```
if that is what you mean. I'm not sure what you mean by "supporting native modules" but I have imported modules into Colab before.

**Comment by arvidn** [comment]
By “native” I mean a compiled python module, not one implemented in python.

**Comment by GrahamboJangles** [comment]
@arvidn Oh okay. Yes, Colab does support native modules.

**Comment by GrahamboJangles** [comment]
@arvidn Hey if you have time, I opened up a Google Colab document for you to look at so you can replicate my problem. You should be able to comment directly on it if you wish. https://colab.research.google.com/drive/18LtLFaU05vHjM9cksKMU9Oq14SoPV3MD

**Comment by dhruvil009** [comment]
The issue has got to do something with python 3 Incompatibility. Changing environment to python 2 solves the problem

**Comment by arvidn** [comment]
sounds like the build of the python module may be linking against the wrong boost.python version
