### ISSUE TITLE
where is max_path.hpp in latest version

### ISSUE THREAD

**Issue by pmahend1** [arvidn/libtorrent#3889]
**Please provide the following information**

libtorrent version (or branch): RC1_2

patform/architecture: Windows 10 professional : vcpkg 64/32 

compiler and compiler version: MSVC 14.2 (Visual studio 2019)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
as mentioned in the [examples-make torrent](https://libtorrent.org/examples.html#make-torrent) the latest libtorrent include files doesnt have **libtorrent/aux_/max_path.hpp** the program expects TORRENT_MAX_PATH .
``` cpp
#include "libtorrent/entry.hpp"
#include "libtorrent/bencode.hpp"
#include "libtorrent/torrent_info.hpp"
#include "libtorrent/storage.hpp"
#include "libtorrent/hasher.hpp"
#include "libtorrent/create_torrent.hpp"
#include "libtorrent/aux_/max_path.hpp" // for TORRENT_MAX_PATH which is not found
```
in main
``` cpp
	lt::file_storage fs;
#ifdef TORRENT_WINDOWS
	if (full_path[1] != ':')
#else
	if (full_path[0] != '/')
#endif
	{
		char cwd[TORRENT_MAX_PATH]; -- here 
```
What do we have to set it with? Is it ok to define ```const unsigned int TORRENT_MAX_PATH = 255;``` on windows?

**Comment by arvidn** [comment]
`aux_/max_path.hpp` was removed in 1.2.1. The web site had not been updated to reflect the 1.2.1 version. I just fixed that.
