### ISSUE TITLE
Torrent download-No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by pmahend1** [arvidn/libtorrent#3895]
**Please provide the following information**

libtorrent version (or branch): "1.2.0.0" Revision "c76e9cc5e"
platform/architecture:

compiler and compiler version: MSVC Visual studio 19 64 bit (16.2)

I have created torrent file on a small text file with parameters. 
`client.exe abc.txt -o abc.torrent -t http://MyIpv4:9090/ -l` The code for creating torrent is same as in [libtorrent-tutorial-make_torrent](https://libtorrent.org/examples.html#make-torrent) and then while starting the client I have set `lt::settings_pack::broadcast_lsd` to true as below

``` cpp
void t_client_class::start_client(string torrent_file_name)
{
	lt::settings_pack sp;
	sp.set_bool(lt::settings_pack::broadcast_lsd, true);
	lt::session s(sp);

	lt::add_torrent_params p;
	p.save_path = "./";
	p.ti = std::make_shared<lt::torrent_info>(torrent_file_name);
	s.add_torrent(p);

}
```
Download torrent code:
-------------------------

``` cpp
bool t_client_class::download_torrent(string magnet_uri)
{
	lt::settings_pack p;
	p.set_int(lt::settings_pack::alert_mask, lt::alert::status_notification
			  | lt::alert::error_notification  );
	p.set_bool(lt::settings_pack::broadcast_lsd, true);
	lt::session ses(p);



	lt::add_torrent_params atp = lt::parse_magnet_uri(magnet_uri);
	atp.save_path = "."; // save in current dir
	lt::torrent_handle h = ses.add_torrent(std::move(atp));

	for (;;)
	{
		std::vector<lt::alert*> alerts;
		ses.pop_alerts(&alerts);

		for (lt::alert const* a : alerts)
		{
			std::cout << a->message() << std::endl;
			// if we receive the finished alert or an error, we're done
			if (lt::alert_cast<lt::torrent_finished_alert>(a))
			{
				goto done;
			}
			if (lt::alert_cast<lt::torrent_error_alert>(a))
			{
				goto done;
			}
		}
		std::this_thread::sleep_for(std::chrono::milliseconds(200));
	}
done:
	std::cout << "done, shutting down" << std::endl;
	return true;
}
```

This code is working for public torrents. I have tested it by downloading a file from valid torrent file from one of the torrent websites.  

On the same wifi network on another machine I am trying to download this torrent by passing magnet URI as below  

``` bash
magnet:?xt=urn:btih:<magnet_link_address>=abc.txt&tr=http%3a%2f%2f<IP_where_clinet_started>%3a9090%2f
```

Log for download
-----------------------
``` bash
successfully listening on [TCP] 0.0.0.0:6881
successfully listening on [UDP] 0.0.0.0:6881
successfully listening on [TCP] [current_device_mac]:6881
successfully listening on [UDP] [current_device_mac]:6881
successfully listening on [TCP] [current_device_mac_2]:6881
successfully listening on [UDP] [current_device_mac_2]:6881
added torrent: abc.txt
abc.txt: state changed to: dl metadata
abc.txt resumed
abc.txt (http://MyIpv4:9090/)[[current_device_mac]:6881] Unknown error "" (1)
abc.txt (http://MyIpv4:9090/)[[current_device_mac_2]:6881] Unknown error "" (1)
abc.txt (http://MyIpv4:9090/)[0.0.0.0:6881] No connection could be made because the target machine actively refused it "" (1)
abc.txt (http://MyIpv4:9090/)[[current_device_mac]:6881] Unknown error "" (2)
abc.txt (http://MyIpv4:9090/)[[current_device_mac_2]:6881] Unknown error "" (2)
abc.txt (http://MyIpv4:9090/)[0.0.0.0:6881] No connection could be made because the target machine actively refused it "" (2)


```

[I got to know from this question](https://stackoverflow.com/questions/22471139/libtorrent-rasterbar-cant-download-metadata-using-magnet-links) that in LAN I may have to turn on local peer discovery option and enable NAT-PMP/UPnP   

Things I tried:  
-------------  

- set `lt::settings_pack::broadcast_lsd` to `true`
- Enable windows network discovery in Control Panel -> Network and Sharing -> Advanced Settings --> Public folder sharing = Yes 
- Turned off firewall on the client machine completely
- added inbound rule for TCP and UDP for port 9090
- If create torrent with udp instead of http : On running download code I get  `An address incompatible with the requested protocol was used.`
I can not fiddle with router settings as I dont have access to it.

I am able to run 2 peers on same network and send receive messages without this issue . 

Is there a way I can overcome this error?

**Comment by arvidn** [comment]
you're specifying a tracker in the magnet link, but the log suggests that there is no tracker running at that IP and port. Are you running a tracker?
The solution to your problem is to either not specify a tracker in the magnet link (the `&tr=` argument) or to run a tracker at the IP and port that you specified.

**Comment by arvidn** [comment]
btw, libtorrent does not implement a tracker.

**Comment by pmahend1** [comment]
So instead of tracker can I add seed like `client.exe abc.txt -o abc.torrent -w http://MyIpv4:9090/ -l` Would that solve it ?

**Comment by arvidn** [comment]
if you have a web server that's serving the file on that IP and port, you can add it to the .torrent file. But if you don't, there's no point in adding it.
It's not entirely clear to me what you're really asking, but I get the impression that you're trying to get two peers connected to each other on a local network, and you don't have a tracker for them to find each other. Since it's on the same local network (presumably behind a NAT) the DHT may not be able to get them connected either.

if the local network supports multi-cast and broadcast between the two machines, enabling local service discovery (lsd) should do it. But not all networks are configured to let such packets through.

If you know where the other peer is running (which it sounds like you do), just call `torrent_handle::connect_peer()` [[docs](https://libtorrent.org/reference-Core.html#connect_peer())].

**Comment by pmahend1** [comment]
Yes. I do not have dedicated server for tracker. I am trying to torrent files between peers in same network,no tracker server .I thought `-w` parameter is to add the seeds which seed the file.  I have set lsd and enabled windows network finding on local machine , I can not make changes in router for port forwarding and multicasting. Let me check if `torrent_handle::connect_peer()` works

**Comment by pmahend1** [comment]
I am able to start server with [bittorrect-tracker node js](https://www.npmjs.com/package/bittorrent-tracker)

I am able to start server and even connect client and it shows in the tracker server but it shows as leech and on client I get `Unknown error`
![image](https://user-images.githubusercontent.com/21352870/62161792-f38e7d00-b2e4-11e9-8116-f24b64f2f3dd.png)

**Comment by pmahend1** [comment]
I set up the tracker with Opentracker and turned off firewall and to make sure at least one machine is seeding used uTorrent application , and was able to download torrented file.
