### ISSUE TITLE
Don't use regular PEX for i2p magnet links

### ISSUE THREAD

**Issue by mlt** [arvidn/libtorrent#39]
PEX plugin has a check [t->torrent_file().is_i2p()](https://github.com/arvidn/libtorrent/blob/master/src/ut_pex.cpp#L663). However torrent file is not downloaded (via _ut_metadata_ from other peers) at the time of check. Thus we erroneously getting regular PEX instantiated for i2p.

**Comment by mlt** [comment]
Probably, torrent_info::add_tracker should check for i2p url and set m_i2p. It is called from torrent::start via session_impl just before adding extensions. I'll prepare a patch.

**Comment by majestrate** [comment]
there's an ongoing discussion on the i2p developer forum about i2p and libtorrent. may be helpful. http://zzz.i2p.xyz/topics/1928-i2p-and-libtorrent

**Comment by arvidn** [comment]
this looks like a legitimate issue. but it's hard justifying prioritizing it given that nobody has seemed to care for so long
