### ISSUE TITLE
Announces with left!=0 for some finished torrents

### ISSUE THREAD

**Issue by laplacesdaemon** [arvidn/libtorrent#3912]
libtorrent version (or branch): libtorrent 1.1.12
torrent client: Deluge 2.0.3
platform/architecture: Linux x86_64
compiler and compiler version: gcc 8.3.0

 There is a problem in data sent to trackers for torrents that have been added to deluge for seeding/reseeding.

**Steps to reproduce**

- Copy the file/directory of the new torrent to the download directory.  
- Add the new torrent in paused state.
- Force a hash check. When it finishes successfully the torrent will be shown as completed in Deluge GUI.
- Start the torrent. It announces to the tracker.
- Check the tracker web UI. The torrent is shown as leeching instead of seeding. Also the percentage completed is shown as zero. We will get peers eventually and uploading will go on, but the tracker will not know we have a finished torrent. 

Spying the communications with the tracker shows that Deluge is sending a value for the left parameter equal to the size of the torrent instead of zero.

Torrents that are downloaded from scratch work fine and the tracker shows torrents that have finished downloading as seeding an 100% completed.

I'm not familiar with deluge/libtorrent, internals so not sure where the report belongs.

**Comment by Arathen** [comment]
I've just updated my libtorrent version and am also seeing this behaviour with 1.2.1 and the latest qbittorrent master. After compiling libtorrent and recompiling qbittorrent, all my previously "seeding" torrents are now listed as "leeching", despite being fully downloaded. As @laplacesdaemon  noted, new torrents are not affected.

Oddly, before updating, I was running libtorrent 1.1.12 and didnt see this behaviour, so im not sure how that lines up. I've now rolled back to that version and everything is back to normal.

**Comment by arvidn** [comment]
does this happen with all torrents or just some? If just some, are there any common traits among the ones that trigger this?

If I would guess, this is related to pad files, and that pad files could cause this. Is that the case?

**Comment by laplacesdaemon** [comment]
It happens for all torrents that are added for seeding or reseeding. It doesn't happen for torrents that are added to be fully downloaded. I've tested this with various trackers and many torrents.

There are no pad files in those torrents.

**Comment by Arathen** [comment]
For me, this happened as a result of updating libtorrent, so all files that were seeding before the update were then reported as leeching after the update. Just over 200 torrents from various trackers, mixture of single files and multi's, almost all of them without pad files.

**Comment by laplacesdaemon** [comment]
I correct myself, this happens also with newly downloaded torrents when we stop them and start them again. They report OK to the tracker when download finishes, but once restarted they send 0% completion to the tracker.

**Comment by Arathen** [comment]
Not sure if this is significant, but my old version of 1.1.12 was compiled with -std=c++11 and my new version of 1.2.1 was not. I believe the default for my gcc/g++ version (7.4.0) is -std=c++14 so that is a difference.

**Comment by arvidn** [comment]
when `&left` is incorrectly non-zero, what value does it have? is it the same every time? or is it (seemingly) random? is it 16384?

**Comment by arvidn** [comment]
could anybody give this patch a try? https://github.com/arvidn/libtorrent/pull/3945

**Comment by Arathen** [comment]
I've been testing this for the last couple of hours and initial results look good. All my seeds are still seeds and all my leeches are still leeches. This has remained consistent since I recompiled and restarted, and that was several tracker announces ago.

So far, so good. Thanks.

**Comment by arvidn** [comment]
thanks for testing!
