### ISSUE TITLE
assert in detail::bencode_recursive

### ISSUE THREAD

**Issue by lethanhviet** [arvidn/libtorrent#393]
Tried to test latest libtorrent build with deluge 1.3.12.

Please include the following information:

version: 1.0.7.0
0dff874

file: '../../include/libtorrent/bencode.hpp'
line: 228
function: int libtorrent::detail::bencode_recursive(OutIt&, const libtorrent::entry&) [with OutIt = std::back_insert_iterator<std::basic_string<char> >]
expression: false
e.type(): 4

stack:
1: assert_fail(char const*, int, char const*, char const*, char const*, int)
2: int libtorrent::detail::bencode_recursive<std::back_insert_iterator<std::string> >(std::back_insert_iterator<std::string>&, libtorrent::entry const&)
3: bencode_(libtorrent::entry const&)
4: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<bytes (*)(libtorrent::entry const&), boost::python::default_call_policies, boost::mpl::vector2<bytes, libtorrent::entry const&> > >::operator()(_object*, _object*)
5: boost::python::objects::function::call(_object*, _object*) const
6:
7: boost::python::handle_exception_impl(boost::function0<void>)
8:
9: PyEval_EvalFrameEx
10: PyEval_EvalFrameEx
11: PyEval_EvalFrameEx
12: PyEval_EvalCodeEx
13: PyEval_EvalFrameEx
14: ) [0x4e5fe8]
15: PyEval_EvalFrameEx
16: PyEval_EvalCodeEx
17: PyEval_EvalFrameEx
18: PyEval_EvalCodeEx
19: PyEval_EvalFrameEx
20: PyEval_EvalCodeEx
21: PyEval_EvalFrameEx
22: ) [0x4e5fe8]
23: ) [0x5045d8]
24: ) [0x503219]
25: ) [0x4ba94b]
26: PyEval_EvalFrameEx
27: PyEval_EvalCodeEx
28: PyEval_EvalFrameEx
29: PyEval_EvalCodeEx
30: ) [0x5030ef]
31: PyRun_FileExFlags
32: PyRun_SimpleFileExFlags
33: Py_Main
34: __libc_start_main
35: ) [0x497ca0]

**Comment by arvidn** [comment]
This looks like it may be the python code violating a precondition of the encoding function. Could you paste the relevant python code that calls bencode() and maybe what structure it's trying to encode?
