### ISSUE TITLE
dyld: Symbol not found: ___CFConstantStringClassReference

### ISSUE THREAD

**Issue by jarrodcal** [arvidn/libtorrent#3944]
**Please provide the following information**

libtorrent version (or branch): 1.2.1

platform/architecture: macOS 10.14.6

compiler and compiler version: 
g++ -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

./configure --enable-debug=yes --enable-encryption=no   --enable-examples=yes   --enable-tests=yes
make
make install
cd examples/
 ./custom_storage

dyld: Symbol not found: ___CFConstantStringClassReference
  Referenced from: /Users/liqingfang/Downloads/libtorrent-rasterbar-1.2.1/src/.libs/libtorrent-rasterbar.10.dylib
  Expected in: flat namespace
 in /Users/abc/Downloads/libtorrent-rasterbar-1.2.1/src/.libs/libtorrent-rasterbar.10.dylib
Abort trap: 6

Why>? Thank you

**Comment by arvidn** [comment]
it looks like there's a missing `-framework CoreFoundation ` to the linker. I would recommend using boost-build and possibly cmake to build instead
