### ISSUE TITLE
Last build - file write error

### ISSUE THREAD

**Issue by amirotin** [arvidn/libtorrent#395]
I've tryed last build. Don't know if it associated with symlink (https://github.com/arvidn/libtorrent/issues/373) changes, but get this error when i try download a torrent:
filename.mkv write (D:\test\filename.mkv) error: The parameter is incorrect

**Comment by arvidn** [comment]
I cannot reproduce this. Could you provide more details about your setup?

**Comment by amirotin** [comment]
I used build from here https://ci.appveyor.com/project/arvidn/libtorrent/history and get error.
But your last release (1.0.8) seems to work fine!
