### ISSUE TITLE
no remote_dl_rate for 1.2

### ISSUE THREAD

**Issue by colinhd8** [arvidn/libtorrent#3950]
**Please provide the following information**

libtorrent version (or branch):
1.2.1

platform/architecture:
Windows Server 2008 R2 64

compiler and compiler version:
VS 2019

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
Seems that there's no remote_dl_rate for peerinfo(libtorrent 1.2.1), if i still want to display the peer's download speed, how to do that?

Thanks.

**Comment by arvidn** [comment]
you can sample the `pieces` field of [peer_info](https://libtorrent.org/reference-Core.html#peer-info) regularly to estimate how many pieces are downloaded over some time window.

Keep in mind that if the peer is super seeding, or if it implements the optimization of not sending redundant have-messages, the estimate will be wrong.

**Comment by colinhd8** [comment]
Thanks for the reply. But why delete the field from 1.2.x? 
I'm not familiar with c++, hope one day it wil be readd to peerinfo.

**Comment by arvidn** [comment]
the field was deleted because the underlying logic to calculate it was deleted from libtorrent. The logic was deleted because it was complex and inaccurate and also not core to libtorrent's functionality
