### ISSUE TITLE
Error build CALG_SHA_256 + Windows XP

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#3955]
libtorrent version (or branch): master 
compiler and compiler version: VC++2017 
Platform toolset: Visual Studio 2017 - Windows XP (v141_xp)

WinCrypt.h

#if (NTDDI_VERSION > NTDDI_WINXPSP2)
#define CALG_SHA_256            (ALG_CLASS_HASH | ALG_TYPE_ANY | ALG_SID_SHA_256)
#define CALG_SHA_384            (ALG_CLASS_HASH | ALG_TYPE_ANY | ALG_SID_SHA_384)
#define CALG_SHA_512            (ALG_CLASS_HASH | ALG_TYPE_ANY | ALG_SID_SHA_512)

Error log:

1>q:\vc15\r5xx-libtorrent-git\libtorrent\include\libtorrent\hasher.hpp(159): error C2065: 'CALG_SHA_256': undeclared identifier
1>q:\vc15\r5xx-libtorrent-git\libtorrent\include\libtorrent\hasher.hpp(159): error C2975: 'AlgId': invalid template argument for 'libtorrent::aux::crypt_hash', expected compile-time constant expression
1>q:\vc15\r5xx-libtorrent-git\libtorrent\include\libtorrent\aux_\win_crypto_provider.hpp(74): note: see declaration of 'AlgId'

help?

**Comment by ssiloti** [comment]
Confirm that the value of `NTDDI_VERSION` is indeed greater than `NTDDI_WINXPSP2` (presumably `NTDDI_WINXPSP3` is what you want) and that the build is using the version of the Windows SDK that you think it is.

**Comment by pavel-pimenov** [comment]
libtorrent support Windows  XP?

**Comment by ssiloti** [comment]
Not really. No one has gone out of their way to break XP (yet), but AFAIK no one is testing it regularly either. I personally wouldn't spend a significant amount of time addressing an issue which was XP specific.
