### ISSUE TITLE
Possibility of using wolfSSL

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#3970]
I noticed that in the recent boost 1.71.0, there is an entry in the asio section:
```
Added wolfSSL compatability.
```
and I read this months ago:
https://www.wolfssl.com/wolfssl-support-asio-boost-asio-c-libraries/

I wonder if using wolfSSL is a real possibility since that will be a good improvement in android devices.

**Comment by arvidn** [comment]
if asio supports it, I imagine it would be relatively easy to do

**Comment by arvidn** [comment]
here it is: https://github.com/boostorg/asio/commit/3db13a1576f6173e59d470c48ccfd1fd3d1b3c9f

**Comment by arvidn** [comment]
@aldenml would you be interested in picking this up? I did the foundation of wolfssl support, mostly for wolfcrypt. What's left is to review all places conditionally compiled based on `TORRENT_USE_OPENSSL` and possibly add `TORRENT_USE_WOLFSSL` to the preprocessor condition.

https://github.com/arvidn/libtorrent/pull/3983

**Comment by aldenml** [comment]
@arvidn more than happy to do it, I'm just having no extra time for a few more weeks, but this is on my list. I wonder if you are willing to accept this change in `RC_1_2`.

**Comment by arvidn** [comment]
I think 1.2 might be a bit aggressive.

**Comment by aldenml** [comment]
Hi @arvidn, would you be open to the possibility of separate the "ability to make HTTPS connections (for trackers and web seed)" from "torrents over SSL feature"? 

Problem is that I'm able to run all the HTTPS related test, but when it comes to torrents over SSL, the challenges start:

1. There seems to be some incompatibility with openssl generated RSA private keys in PEM format (even in PKCS#8). I solved this changing the code to accept DER with ASN.1.
2. wolfSSL can not start doing the server handshake if the certificate and private key are not set. That means that the SSL context at `session_impl` needs to be properly setup (similar to the torrent `set_ssl_cert`) before start accepting connections. I solved this adding the necessary code, assuming some "master" cert should be created.
3. The wolfSSL cipher suite initialization for a generic context happens lazily at `do_connect` or `do_accept`, and that means that when the switch (via `SSL_set_SSL_CTX`) is done inside `servername_callback` (it is called after all with the setup in 2) above), the new context (from the torrent) lacks the ciphers to continue the negotiation with the peer connection (because it's brand new).
4. The wolfSSL error codes are richer than the ones from openssl, with the unfortunate result that for very specific errors ASIO gets wrong the `error_code` and the logic flow is broken.

The setup for torrents over SSL, human client wise, is not trivial already, and by having the possibility of not include this feature, I think we can use wolfSSL easily :)

**Comment by arvidn** [comment]
> Hi @arvidn, would you be open to the possibility of separate the "ability to make HTTPS connections (for trackers and web seed)" from "torrents over SSL feature"?

Yes, I would be open to this. I think it's important, though, that the API be disabled (maybe non-existant) when building with WolfSSL, to make it clear those features don't work. I don't think it's OK to silently fail.

> Problem is that I'm able to run all the HTTPS related test, but when it comes to torrents over SSL, the challenges start:

I don't think the HTTPS tests necessarily cover all important aspects. For instance, you need to be able to *set* the SNI on outgoing connections still.

>     There seems to be some incompatibility with openssl generated RSA private keys in PEM format (even in PKCS#8). I solved this changing the code to accept DER with ASN.1.

Does WolfSSL only work with the "system" root certificate(s) then? How does it work at all if it doesn't parse keys and certs?

>     wolfSSL can not start doing the server handshake if the certificate and private key are not set. That means that the SSL context at session_impl needs to be properly setup (similar to the torrent set_ssl_cert) before start accepting connections. I solved this adding the necessary code, assuming some "master" cert should be created.

I see. It cannot act as a server basically. That does rule out running bittorrent over TLS. It could still support contacting web servers though, as a client.

>     The wolfSSL cipher suite initialization for a generic context happens lazily at do_connect or do_accept, and that means that when the switch (via SSL_set_SSL_CTX) is done inside servername_callback (it is called after all with the setup in 2) above), the new context (from the torrent) lacks the ciphers to continue the negotiation with the peer connection (because it's brand new).

This is what you meant above, which I interpreted as it can not be a server?

>     The wolfSSL error codes are richer than the ones from openssl, with the unfortunate result that for very specific errors ASIO gets wrong the error_code and the logic flow is broken.

That seems like a general issue that would need to be fixed in asio.
 
> The setup for torrents over SSL, human client wise, is not trivial already, and by having the possibility of not include this feature, I think we can use wolfSSL easily :)

But you would still need to be able to set the SNI to the hostname of the HTTPS server, in order for it to work (with a server hosting multiple domains)

**Comment by aldenml** [comment]
Done with https://github.com/arvidn/libtorrent/pull/4133
