### ISSUE TITLE
Use assertion in alert_cast()

### ISSUE THREAD

**Issue by Chocobo1** [arvidn/libtorrent#3985]
**Please provide the following information**

libtorrent version (or branch):
RC_1_2

platform/architecture:
linux x64

compiler and compiler version:
gcc-9.1

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I'm a bit concerned about the additional checks in `alert_cast()` which seems unnecessary for release builds (more suitable for debug builds). Maybe it can be improved as such?
```c++
template <class T> T* alert_cast(alert* a)
{
	static_assert(std::is_base_of<alert, T>::value
		, "alert_cast<> can only be used with alert types (deriving from lt::alert)");
#if TORRENT_USE_ASSERTS
	TORRENT_ASSERT(a);
	TORRENT_ASSERT(a->type() == T::alert_type);
#endif
	return static_cast<T*>(a);
}
```

**Comment by arvidn** [comment]
the `TORRENT_ASSERT` macro expands to nothing in release builds (or specifically when `TORRENT_USE_ASSERTS` is defined to 0)

**Comment by Chocobo1** [comment]
>the TORRENT_ASSERT macro expands to nothing in release builds (or specifically when TORRENT_USE_ASSERTS is defined to 0)

That is exactly what I intend to do. I felt that `type() == alert_type` should only be done for debug builds. Release builds shouldn't worry about it.
Or do you think the checking is valuable for release build too?

ps. just to be clear here is what it looks like in RC_1_2: https://github.com/arvidn/libtorrent/blob/RC_1_2/include/libtorrent/alert.hpp#L305

**Comment by arvidn** [comment]
Oh, right. I misunderstood, I though what you had added was the `#if TORRENT_USE_ASSERTS`.

The purpose of `alert_cast<>` is to function sort of like `dynamic_cast<>`. If you already know the type, you can just use `static_cast<>`.

**Comment by Chocobo1** [comment]
>The purpose of alert_cast<> is to function sort of like dynamic_cast<>. 

Understood.

>If you already know the type, you can just use static_cast<>.

But are there cases that one would prefer `alert_cast<>` and not `static_cast<>`? The `T` type is always known and thus checking `type() == alert_type` doesn't look useful to me, maybe except for catching some silly logic error which should be done at debug build anyway.

**Comment by arvidn** [comment]
Here's an example: https://github.com/arvidn/libtorrent/blob/RC_1_2/examples/client_test.cpp#L724

**Comment by Chocobo1** [comment]
OK, my intuition is to place it in a [`switch()`](https://github.com/qbittorrent/qBittorrent/blob/master/src/base/bittorrent/session.cpp#L3842) and would not have thought of that.
Thanks for clarifying.
