### ISSUE TITLE
Crash via ip_filter methods while importing thousands of entries under Windows

### ISSUE THREAD

**Issue by int3l** [arvidn/libtorrent#4023]
libtorrent version (or branch): 1.x

platform/architecture: Windows 10 (1903) 64 bit

compiler and compiler version: Windows build included in Deluge 1.3.15 (uses python 2.7 Visual Studio compiler for python)

When adding around 15 000 or more rules via the **set_ip_filter** / **ip_filter.add_rule** methods, libtorrent crashes in the C runtime, which causes the torrent client Deluge to crash as well.

Please investigate or recommend workaround. Also is there any specific cases that needs to be avoided, when calling those methods? I can't see anything specific on the [documentation page](https://www.rasterbar.com/products/libtorrent/docs.html#ip-filter).

Deluge code base reference: [add_rule](https://github.com/deluge-torrent/deluge/blob/1.3-stable/deluge/plugins/blocklist/blocklist/core.py#L324) / [set_ip_filter](https://github.com/deluge-torrent/deluge/blob/1.3-stable/deluge/plugins/blocklist/blocklist/core.py#L329)

**Comment by arvidn** [comment]
how does it crash? do you have any more information about where it crashes?
What exactly do you mean by "crash"? is it a `SIGSEGV`?
You say "in the C runtime", can you be more specific?

**Comment by int3l** [comment]
Hi, and thank you for your reply.
Sorry for my delayed answer.

Here is what I have from the error logs:
```
Faulting application name: deluged.exe, version: 1.3.15.0, time stamp: 0x530bd002
Faulting module name: MSVCR90.dll, version: 9.0.30729.9619, time stamp: 0x5c4bd872
Exception code: 0xc0000417
Fault offset: 0x0006ccd5
Faulting process id: <PID>
Faulting application start time: <timestamp>
Faulting application path: C:\Program Files (x86)\Deluge\deluged.exe
Faulting module path: C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9619_none_508d9c7abcbd32b6\MSVCR90.dll
Report Id: <GUID>
Faulting package full name: 
Faulting package-relative application ID: 
```

The deluge log is empty.
I am not sure how helpful is the Windows report, but this is what I got for the error code 0xc0000417 - "STATUS_INVALID_CRUNTIME_PARAMETER"

And this is sample blocklist that triggers the crash (Inserted via the Deluge Blocklist plugin): 
[blocklist.txt](https://github.com/arvidn/libtorrent/files/3764099/blocklist.txt)
