### ISSUE TITLE
Torrents do not resume when session is resumed

### ISSUE THREAD

**Issue by Bhambya** [arvidn/libtorrent#4025]
**Please provide the following information**

libtorrent version (or branch):
1.1.13

platform/architecture:
Linux

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

1. Start a torrent
2. Pause session
3. Resume session

The torrent will stay paused. It should resume automatically.

I think [this line](https://github.com/arvidn/libtorrent/blob/RC_1_2/src/torrent.cpp#L8701) is at fault. The condition should be inverted.

**Comment by Bhambya** [comment]
My bad. I was doing something wrong.

**Comment by arvidn** [comment]
Is there any part of the documentation that can be improved?
