### ISSUE TITLE
Flags not passed correctly to move_storage

### ISSUE THREAD

**Issue by Bhambya** [arvidn/libtorrent#4030]
**Please provide the following information**

libtorrent version (or branch):
1.1.13
platform/architecture:
Linux

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I am passing the flag move_flags_t::fail_if_exist (which is 1) to move_storage. But by the time it reaches storage.cpp move_storage, it becomes 41. So the check on [line 1247](https://github.com/arvidn/libtorrent/blob/84f10d05caff0d20213280951752797d166e1759/src/storage.cpp#L1247)  never passes.

**Comment by arvidn** [comment]
thanks for the report! it has been fixed in later versions (1.2 and later).
Here's a patch against 1.1: https://github.com/arvidn/libtorrent/pull/4041

**Comment by Bhambya** [comment]
Thanks!
