### ISSUE TITLE
libtorrent-rasterbar.pc gets incorrectly generated

### ISSUE THREAD

**Issue by diizzyy** [arvidn/libtorrent#4040]
libtorrent version (or branch):
libtorrent 1.2.2

platform/architecture:
FreeBSD 13-CURRENT, AMD64

compiler and compiler version:
FreeBSD clang version 8.0.1 (tags/RELEASE_801/final 366581) (based on LLVM 8.0.1)
cmake version 3.15.3
boost 1.71.0
OpenSSL 1.1.1d

libtorrent-rasterbar.pc incorrectly adds pthread libs

```
prefix=/usr/local
libdir=${prefix}/lib

Name: libtorrent
Description: Bittorrent library
Version: 1.2.2
Libs: -L${libdir} -ltorrent-rasterbar -L/usr/lib -l-pthread -lssl -lcrypto -lboost_system
Cflags: -fexceptions -std=c++14  -pthread -I/usr/local/include -I/usr/local/include -DTORRENT_LINKING_SHARED -DBOOST_ASIO_ENABLE_CANCELIO -DTORRENT_USE_ICONV -DTORRENT_USE_OPENSSL -DTORRENT_USE_LIBCRYPTO
```

```Libs:``` ...```-l-pthread``` should be ```-pthread```
This gets pickuped up correctly during compilation

I've attached a patch if you want to try it yourself using ports
[0001-libtorrent-rasterbar-Update-to-1.2.2.patch.txt](https://github.com/arvidn/libtorrent/files/3758454/0001-libtorrent-rasterbar-Update-to-1.2.2.patch.txt)

**Comment by diizzyy** [comment]
Also reproducable on FreeBSD 12.1-BETA2
FreeBSD clang version 8.0.1 (tags/RELEASE_801/final 366581) (based on LLVM 8.0.1)
cmake version 3.15.4
boost 1.71.0
OpenSSL 1.1.1d

**Comment by arvidn** [comment]
is this the pc file generated by the cmake script? (or automake?) Since you mention cmake version, I assume that's the one.

I can't find any mention of `-pthread` in the CMakeList.txt, I imagine it's added by cmake itself via the `Threads` dependency.  I also can't find the place that string is generated by prepending `-l`
, perhaps that's not how it works.

@zeule any thoughts?

**Comment by zeule** [comment]
No ideas so far. @diizzyy, could you run cmake in the trace mode, adding these switches, please:
```
--trace-expand --trace-source=cmake/Modules/GeneratePkgConfig.cmake
```
?

**Comment by diizzyy** [comment]
Hi,
This is caused by ```-DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES``` being set in ```Mk/Uses/cmake.mk``` in FreeBSD.

References: 
https://mariadb.atlassian.net/browse/MDEV-9388
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=206169

I apologize for the noise
