### ISSUE TITLE
hard crash in libtorrent::aux::set_socket_buffer_size

### ISSUE THREAD

**Issue by barthek** [arvidn/libtorrent#4049]
**Please provide the following information**

libtorrent version (or branch):
libtorrent-rasterbar-1.2.2

platform/architecture:
linux / athlon i686

compiler and compiler version:
Target: i686-linux-gnu
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
I compiled libtorrent with debug enabled. Python bindings as well, so that deluged would run.
Unfortunately deluged hard crashes immediately after startup in libtorrent's set_socket_buffer_size.

Clearing deluged's session file makes the crash disappear but nevertheless I would expect libtorrent to fail nice and clean rather than with Signal 11.

gdb session attached.

as you can see the Signal 11 was received at:
Thread 2 (Thread 0xb5e65b40 (LWP 19608)):
#0  0xb68e1654 in void libtorrent::aux::set_socket_buffer_size<boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::executor> >(boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::executor>&, libtorrent::aux::session_settings const&, boost::system::error_code&) () from /usr/local/lib/libtorrent-rasterbar.so.10
[gdb_session.txt](https://github.com/arvidn/libtorrent/files/3780467/gdb_session.txt)

**Comment by arvidn** [comment]
this really smells like an ABI issue. i.e. libtorrent, the python bindings or boost were built with incompatible build flags. I would suggest you build as much as possible at the same time, and make sure they link with the right builds, or link statically.
