### ISSUE TITLE
Handler buffer not large enough, please increase it

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#4058]
compile error in peer_connection.cpp

libtorrent version (or branch): master
compiler and compiler version: VC2015 64Bit (v140)
Where/how do I increase the buffer?

**Comment by ssiloti** [comment]
Handler sizes are set in `include/libtorrent/aux_/allocating_handler.hpp`. Increase the size of the offending handler to the actual size you observe. Be sure to mind the `#ifdefs`, handler sizes vary per platform and build config.

**Comment by MassaRoddel** [comment]
Changing the debug_read_iter from 16*.. to 22*... fixed the compile problem.
Thanks.

**Comment by arvidn** [comment]
Is it the debug iterators that use up the space? After your change, do release builds still work?

**Comment by arvidn** [comment]
I imagine this change should go into master, right?

**Comment by MassaRoddel** [comment]
The change affects debug builds only (per #ifndef NDEBUG). The release version compiled without problems and seems to work.
I just started from the top to change sizes and increasing debug_read_iter fixed it. Could be that the actual problem is a different handler size (i.e. openssl_read_cost).
The change should go into master.
