### ISSUE TITLE
add_port_mapping - return vector

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#4075]
libtorrent version (or branch): master

Old code for maping custom TCP/UDP port :

		m_torrent_session = std::make_unique<lt::session>(l_sett);
		if (SETTING(INCOMING_CONNECTIONS) == SettingsManager::INCOMING_FIREWALL_UPNP || BOOLSETTING(AUTO_DETECT_CONNECTION))
		{
			m_maping_index[0] = m_torrent_session->add_port_mapping(lt::session::tcp, SETTING(TCP_PORT), SETTING(TCP_PORT));
			m_maping_index[1] = m_torrent_session->add_port_mapping(lt::session::tcp, SETTING(TLS_PORT), SETTING(TLS_PORT));
			m_maping_index[2] = m_torrent_session->add_port_mapping(lt::session::udp, SETTING(UDP_PORT), SETTING(UDP_PORT));
		}

New code: 

Help?

![изображение](https://user-images.githubusercontent.com/920705/68487788-ca22ad00-0254-11ea-986e-71771f7cb3bf.png)

**Comment by arvidn** [comment]
`add_port_mapping()` returns a vector of all mappings that were created. Since it's possible to have multiple listen sockets (say, one for IPv4 and one for IPv6), a mapping is created for each one.
