### ISSUE TITLE
void' function returning a value - polymorphic_socket.hpp VC++2017

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#4080]
libtorrent version (or branch): master

1>q:\vc15\r5xx-libtorrent-git\libtorrent\include\libtorrent\aux_\polymorphic_socket.hpp(80): note: while compiling class template member function 'void libtorrent::aux::polymorphic_socket<libtorrent::tcp::socket,libtorrent::socks5_stream,libtorrent::http_stream,libtorrent::aux::utp_stream,libtorrent::i2p_stream>::close(libtorrent::error_code &)'
1>q:\vc15\r5xx-libtorrent-git\libtorrent\src\session_impl.cpp(931): note: see reference to function template instantiation 'void libtorrent::aux::polymorphic_socket<libtorrent::tcp::socket,libtorrent::socks5_stream,libtorrent::http_stream,libtorrent::aux::utp_stream,libtorrent::i2p_stream>::close(libtorrent::error_code &)' being compiled
1>socket_type.cpp
1>q:\vc15\r5xx-libtorrent-git\boost\boost\variant\detail\apply_visitor_unary.hpp(124): error C2562: 'boost::detail::variant::result_wrapper1<Visitor,Visitable>::operator ()': 'void' function returning a value

![изображение](https://user-images.githubusercontent.com/920705/68594354-68f31780-04a8-11ea-9693-307c33de6cf0.png)

**Comment by arvidn** [comment]
this happens if you enabled deprecated functions in boost asio. both the `Jamfile` and `CMakeList.txt` turns those off.
