### ISSUE TITLE
WaitForMultipleObjects ERROR_INVALID_PARAMETER

### ISSUE THREAD

**Issue by ajax16384** [arvidn/libtorrent#410]
After 4a28e95ce0bfd3f9064196a503749d7dd8601355 "fix missing error handling in windows preadv/pwritev emulation" commit libtorrent starts reporting random write error at pwritev->WaitForMultipleObjects with GetLastError==ERROR_INVALID_PARAMETER.
Removing error check only for WaitForMultipleObjects (and leaving error check for events inside rest loop) solved issue.

**Comment by arvidn** [comment]
I bet this is because of exceeding MAXIMUM_WAIT_OBJECTS. I'll have to fix that, probably by calling it multiple times.

**Comment by arvidn** [comment]
attempted fix here: https://github.com/arvidn/libtorrent/pull/411
now I just need to figure out why appveyor isn't building it

**Comment by arvidn** [comment]
and now (with appveyor builds again) https://github.com/arvidn/libtorrent/pull/412

**Comment by ajax16384** [comment]
In bug case "num_bufs" was definetly over than 64 limit. Now this commit fixes problem and checks waitmultipleobjects result. Please backport this changes to master branch.
