### ISSUE TITLE
is_single_thread() assert in torrent::auto_managed

### ISSUE THREAD

**Issue by ghbplayer** [arvidn/libtorrent#4106]
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.2.2.0-b2c3b4dbf

file: 'src/torrent.cpp'
line: 8240
function: auto_managed
expression: is_single_thread()

stack:
1: 
2: 
3: 
4: 
5: 
6: 
7: 
8: 
9: 
10: 
11: clone

8201 Aborted                 (core dumped)

**Please provide the following information**

libtorrent version (or branch): 1.2 git from the other day

platform/architecture: AMD x64 Ubuntu 19.10, c++17 builds

compiler and compiler version: g++ 9.2.1 20191008

This happens on shutdown most of the time, but not always.

**Comment by arvidn** [comment]
would it be possible for you to make a build with symbols (`-g`) so that stack trace becomes helpful?

**Comment by ghbplayer** [comment]
You know, this is a debug build. I'm using meson/ninja, and -g is supposed to be the default with meson. Still, I added `--buildtype debug --debug` to my meson command line and even manually added -g to the generated build script when calling `c++`. No change. Sorry if I'm bad at this, none of these are tools I'm used to.

**Comment by arvidn** [comment]
right, of course. the assert wouldn't trigger in a release build. the stack trace should at least have been captured by the core file that was dumped, if you feel like loading it up in `gdb`.

The stack trace I print in the assert is based on [`backtrace()` and `backtrace_symbols()`](https://www.gnu.org/software/libc/manual/html_node/Backtraces.html). They may require the `-export-dynamic` and `-rdynamic` link flags to work (at least for the symbols).

**Comment by ghbplayer** [comment]
I probably should have asked this before, but I am using multiple threads. I read in the documentation that lt posts messages to the main lt thread, but perhaps I've gone too far with which APIs I use. What functions and classes are safe to use from multiple threads? What rules do I need to play by?

**Comment by arvidn** [comment]
yeah, the session object is thread safe. all interactions with it are posted to the single libtorrent network thread. this assert that's firing is used for internal types to ensure they are all used from within that thread only.

I suspect some aspect of the shutdown happens from the thread the session destructor runs on, after the main network thread has joined.

**Comment by ghbplayer** [comment]
Even with c'tor and d'tor running in the same thread (it wasn't at first), I have trouble because I'm going beyond the session object. This might be my problem with the other bug too, it's hard to say. I'll know after I redesign my program.

**Comment by ghbplayer** [comment]
Arvid, if I only use lt from a single thread, LT still has another thread. What can I safely use, and do I need to use any locking system or special care? Session is one thing, but I pretty quickly got into `torrent_handle`, `torrent`, `torrent_status`, `peer_info`, and `announce_entry`.

**Comment by arvidn** [comment]
I'd prefer to go to the bottom of this and understand how libtorrent can be fixed to work well when used from different threads (in fact, I use `session` and `torrent_handle` from many different threads regularly, without problems, so it's something non-obvious).

`session` and `torrent_handle` both post calls to libtorrent's network thread. Both `torrent_status` and `peer_info` are copied back to the client, so there's no shared data there.

**Comment by ghbplayer** [comment]
Okay, I rewrote my code to only call LT from a single thread and I still get the assert. As I mentioned, I'm using native_handle() to access a details that don't appear to be exposed otherwise.

One thing I'm accessing is is_paused for a torrent. Now, torrent_handle has an is_paused member but for some reason it's deprecated. It's also deprecated in torrent_status.

Other thread-unsafe things I'm doing:

- Set auto_managed to false on shutdown before pausing a torrent (maybe not needed, this was triggering the assert)
- retreive torrent_info to determine piece size and number of pieces in order to report download progress. I realize that torrent_status has progress, but I wasn't using that because it depends on the current task.
- check if it's an ssl torrent (for debug / logging)

I may copy torrent_handle::sync_call_ret and and friends as a workaround, because I do like having this information to see what's going on. Even if some information can be captured other ways (alerts, torrent creation), sometimes I want to be sure of the state.

I think LT needs a better answer though. The interface isn't thread safe and isn't documented unsafe. Something needs to change.

**Comment by arvidn** [comment]
actually, I don't recall any mention of using `native_handle()`. That explains it. That will give you access to the internals of libtorrent and is only supposed to be used from within libtorrent itself, in a plugin for instance.

Looking for a reference to the documentation, I realize my documentation generation tool fail to generate proper documentation for this. The non-deprecated way of knowing this is by asking for the `torrent_status` object, and inspect its `flags` member. But the `torrent_flags_t` type isn't turning into a link.

Anyway, the flags are defined in `libtorrent/include/torrent_flags.hpp` and one of them is `paused`. I will fix the documentation.

**Comment by arvidn** [comment]
To be fair, the documentation for `native_handle()` does say: "This function is intended only for use by plugins and the alert dispatch function. This type does not have a stable API and should be relied on as little as possible.". I suppose I could add that it's not thread safe to use from outside of libtorrent's own thread.

**Comment by ghbplayer** [comment]
Changing the documentation is good, and maybe you have everything covered. It seems like torrent_handle.native_handle()->get_torrent_copy() is safe in practice, because otherwise I wouldn't know how to get torrent size after starting from a magnet.

You can close this issue when you're satisfied.

**Comment by arvidn** [comment]
http://libtorrent.org/reference-Core.html#torrent_file()

**Comment by arvidn** [comment]
documentation fix is here: https://github.com/arvidn/libtorrent/pull/4189
