### ISSUE TITLE
Invalid linker flag in genereated .pc file

### ISSUE THREAD

**Issue by Chocobo1** [arvidn/libtorrent#4122]
**Please provide the following information**

libtorrent version (or branch):
RC_1_2

platform/architecture:
Linux x64

compiler and compiler version:
gcc version 9.2.0
boost 1.71.0
cmake version 3.15.5

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I'm building libtorrent via cmake and I noticed this linker flag `-lvals-NOTFOUND` is appearing in the generated libtorrent-rasterbar.pc file which cause the linker to fail when building other programs.
I would expect that flag not to appear.

Build script: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libtorrent-rasterbar-1_2-git#n29
Generated libtorrent-rasterbar.pc file:
```
prefix=/usr
libdir=${prefix}/lib

Name: libtorrent
Description: Bittorrent library
Version: 1.2.2
Libs: -L${libdir} -ltorrent-rasterbar -lpthread -lssl -lcrypto -lvals-NOTFOUND -lboost_system
Cflags: -fexceptions -std=c++14 -I/usr/include -DTORRENT_LINKING_SHARED -DBOOST_ASIO_ENABLE_CANCELIO -DTORRENT_USE_ICONV -DTORRENT_USE_OPENSSL -DTORRENT_USE_LIBCRYPTO -DBOOST_SYSTEM_DYN_LINK -DBOOST_ALL_NO_LIB
```

[build log.txt](https://github.com/arvidn/libtorrent/files/3890094/build.log.txt)

Also this might be relevant, from https://cmake.org/cmake/help/v3.16/command/get_target_property.html :
>  Non-inherited properties will set VAR to NOTFOUND, whereas inherited properties will search the relevant parent scope as described for the define_property() command and if still unable to find the property, VAR will be set to an empty string.

**Comment by ssiloti** [comment]
CMake's configure output should tell you which library was not found.

**Comment by Chocobo1** [comment]
>CMake's configure output should tell you which library was not found.

I have attached the build log in the first post. I didn't notice anything related.

**Comment by silverqx** [comment]
I have the same experience, `libtorrent-rasterbar.pc` corrupts linking.

I tracked this problem down to cmake boost_system file:
```
target_link_libraries(torrent-rasterbar PUBLIC ${Boost_SYSTEM_LIBRARY}) - CMakeLists.txt:678
/usr/lib/cmake/boost_system-1.72.0/boost_system-config.cmake:57
/usr/lib64/cmake/boost_system-1.72.0/libboost_system-variant-shared.cmake:70
```

If I remove:
```
set_target_properties(Boost::system PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE CXX 
  IMPORTED_LOCATION_RELEASE "${_BOOST_LIBDIR}/libboost_system.so.1.72.0"
  )
```
from `/usr/lib64/cmake/boost_system-1.72.0/libboost_system-variant-shared.cmake:70` file, so ` -lvals-NOTFOUND` disappears, but of course `-lboost_system` disappears too.

I don't know how to fix this, I have tried blindly `cmake_policy(SET CMP0007 OLD)` and `cmake_policy(SET CMP0007 NEW)` too, but without success.

**Comment by silverqx** [comment]
I have the same experience, `libtorrent-rasterbar.pc` corrupts linking.

Yesterday I posted comment here, but I deleted it later, because I was on the bad track.
Today I looked at it again and have discovered where this value comes from.

This value comes from `GeneratePkgConfig.cmake:48`:
```
get_target_property(val_for_cfg  ${_target_name} "${_propert_name}_${target_cfg}")
if (val_for_cfg)
  list(APPEND vals "$<$<CONFIG:${cfg}>:${val_for_cfg}>")
```

Values in variables are:
```
${vals} = vals-NOTFOUND
${_target_name} = Boost::system
${_propert_name}_${target_cfg} = IMPORTED_LOCATION_RELEASE
```

Command `list(APPEND vals "$<$<CONFIG:${cfg}>:${val_for_cfg}>")` appends `$<$<CONFIG:Release>:/usr/lib64/libboost_system.so.1.72.0>` to `${vals}`, which contains `vals-NOTFOUND` and the result is:
```
vals-NOTFOUND;$<$<CONFIG:Release>:/usr/lib64/libboost_system.so.1.72.0>
```

This line with `list(APPEND vals ...)` is called only for `Boost::system`.

I absolutely don't know how to solve this, the `_get_target_property_merging_configs` function normally returns `vals-NOTFOUND` value.

I'm thinking about these solutions:
1. add `list(FILTER _tmp_list EXCLUDE REGEX "(-NOTFOUND)$")` after `list(REMOVE_ITEM _tmp_list "")` in `GeneratePkgConfig/generate-pkg-config.cmake.in`
2. or better, fix it right up in `_get_target_property_merging_configs` function in `GeneratePkgConfig.cmake`, eg. :
    - at the beginning, `if (NOT vals)`, then set up `${vals}` to empty string
    - or at the end, if `${vals}` list has more than 1 value, than filter out `-NOTFOUND` items or use `list(POP_FRONT vals)` to remove the first item, which in this case will be `vals-NOTFOUND` every time

For now, as a workaround is to manually remove ` -lvals-NOTFOUND` value from `libtorrent-rasterbar.pc` file.
Help from the author of source code is appreciated @zeule

**Comment by zeule** [comment]
@Chocobo1, could you show, please, files from `torrent-rasterbar-pkgconfig` subdir of the build directory after the install stage?

**Comment by zeule** [comment]
An output from `cmake --trace-expand --trace-source=cmake/Modules/GeneratePkgConfig.cmake <other_ags>` would be helpful too.

**Comment by zeule** [comment]
@silverqx, could you try the following change, please?
```diff
diff --git a/cmake/Modules/GeneratePkgConfig.cmake b/cmake/Modules/GeneratePkgConfig.cmake
index 3c4520b22..0a2f18a56 100644
--- a/cmake/Modules/GeneratePkgConfig.cmake
+++ b/cmake/Modules/GeneratePkgConfig.cmake
@@ -30,6 +30,7 @@ endfunction()
 function(_get_target_property_merging_configs _var_name _target_name _propert_name)
  get_target_property(vals ${_target_name} ${_propert_name})
  if (NOT vals)
+   set(vals "")
    if (CMAKE_BUILD_TYPE)
      list(APPEND configs ${CMAKE_BUILD_TYPE})
    elseif()
```

**Comment by Chocobo1** [comment]
>@Chocobo1, could you show, please, files from torrent-rasterbar-pkgconfig subdir of the build directory after the install stage?

Sure, here are the files:
[cmake_log.txt](https://github.com/arvidn/libtorrent/files/4329030/cmake_log.txt)
[torrent-rasterbar-pkgconfig.zip](https://github.com/arvidn/libtorrent/files/4329031/torrent-rasterbar-pkgconfig.zip)

**Comment by silverqx** [comment]
`set(vals "")` will work, I'm sure.

**Comment by silverqx** [comment]
> Although, this branch should make no change on ArchLinux.

Why do you think so? I'm testing this on Manjaro.

**Comment by arvidn** [comment]
please feel free to submit a PR against `RC_1_2`!

**Comment by silverqx** [comment]
@Chocobo1 didn't pass `-DCMAKE_BUILD_TYPE=Release` to cmake command and in this case `foreach(cfg ${configs})` in `_get_target_property_merging_configs` function will not be entered, you can see it in his `cmake_log.txt` log file at line 243.

I think this is another problem, if I don't pass `-DCMAKE_BUILD_TYPE=Release|Debug` to cmake command, I don't have `-lboost_system` in generated `libtorrent-rasterbar.pc` file.

I'm attaching cmake log file too, I compiled like this `cmake --trace-expand --trace-source=cmake/Modules/GeneratePkgConfig.cmake -LH -DCMAKE_BUILD_TYPE=Release -Ddeprecated-functions=OFF ..`.

[cmake.txt](https://github.com/arvidn/libtorrent/files/4329940/cmake.txt)
[torrent-rasterbar-pkgconfig.zip](https://github.com/arvidn/libtorrent/files/4329955/torrent-rasterbar-pkgconfig.zip)

**Comment by Chocobo1** [comment]
>@Chocobo1 didn't pass -DCMAKE_BUILD_TYPE=Release to cmake command and in this case foreach(cfg ${configs}) in _get_target_property_merging_configs function will not be entered, you can see it in his cmake_log.txt log file at line 243.

Ah... I didn't notice `-DCMAKE_BUILD_TYPE` would have effect on this issue, so the `-lvals-NOTFOUND` didn't appear. Now I've uploaded the log with `-DCMAKE_BUILD_TYPE=Release` in my [post](https://github.com/arvidn/libtorrent/issues/4122#issuecomment-598658105) above.

>I think this is another problem, if I don't pass -DCMAKE_BUILD_TYPE=Release|Debug to cmake command, I don't have -lboost_system in generated libtorrent-rasterbar.pc file.

This is indeed an issue, good catch!

**Comment by silverqx** [comment]
> This is indeed an issue

I created #4416 for this, can be fixed later or something
