### ISSUE TITLE
Some confusions about NAT traversals and pieces downloading

### ISSUE THREAD

**Issue by Ty-Chen** [arvidn/libtorrent#4127]
Q1. When using ICE or TURN or some other traversal methods, we still need a center control like a tracker, so do we need to write or add one as a bt downloading server?

Q2. Since I try to download both by HTTP/HTTPS and BT download, do I need to allocate some pieces to HTTP and others to BT?  I see some extions BEP in libtorrent.org like first sending rare piece to others, but none have mension this circumstances. For example, if there are 100 pieces, I just simply give 1- 50 to HTTP and the others to BT, I think this is a really complex circumstances cause maybe BT downloading speed is really low and we need to give some more to HTTP, or it's really fast that we need to give more to BT.  And in 50 - 100, there may be some piece we cannot find resources from other peers. Is there any algorithm or paper can I learn from network?

**Comment by arvidn** [comment]
libtorrent does not support ICE, which is primarily a way to relay traffic into NATed peers. Instead libtorrent attempts to be accessible from the outside, via UPnP and NAT-PMP.

Why not treat an HTTP server just like any other seed? Request rarest pieces first from them, just like any other peer.
