### ISSUE TITLE
web_peer_connection::handle_padfile assert

### ISSUE THREAD

**Issue by ajax16384** [arvidn/libtorrent#413]
TORRENT_ASSERT(m_block_pos < front_request.length);

```
m_block_pos == 16384
-		front_request	{piece=1 start=16384 length=16384 }	libtorrent::peer_request
		piece	1	int
		start	16384	int
		length	16384	int

-		recv_buffer	{begin=0x00000000 <NULL> end=0x00000000 <NULL> }	libtorrent::buffer::const_interval &
+		begin	0x00000000 <NULL>	const char *
+		end	0x00000000 <NULL>	const char *
```

**Comment by arvidn** [comment]
I take it this is in RC_1_1 as well. What's file_size when this happens?
I would expect this to be reliably reproducible. What's the alignment and size of the padfile?
i.e. the padfile start offset and size in the torrent.

**Comment by arvidn** [comment]
I wonder if a 0-size pad file will do this

**Comment by arvidn** [comment]
if you don't mind, could you send me the torrent file that reproduce this?

**Comment by ajax16384** [comment]
it's definetly not zero sized pad files.
sorry but cannot reliably reproduce bug.

**Comment by arvidn** [comment]
would you mind trying this out? https://github.com/arvidn/libtorrent/pull/426
