### ISSUE TITLE
Question on load_torrent_limits overloads

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#4137]
libtorrent branch: `RC_1_2` 

Looking at https://github.com/arvidn/libtorrent/pull/3877, I see that there are no new overloads for the constructors that receive `error_code& ec`. Should they be created?

**Comment by arvidn** [comment]
I can't remember whether that was deliberate or not, probably not.

**Comment by arvidn** [comment]
I'm a little bit worried about the combinatorial explosion of overloads, but it's probably not too much of a concern. If you have a use case, I'm not opposed to adding them, but I also think that the main benefit of these overloads come with you use exceptions for error handling, as you can write shorter code without mixing in the error case everywhere. (you can still get the same outcome by loading the file and decoding it as separate steps, it's just a convenience to be able to do it in one step, much like exceptions)

**Comment by aldenml** [comment]
agree
