### ISSUE TITLE
Invalid message in announce_endpoint

### ISSUE THREAD

**Issue by NotKyros** [arvidn/libtorrent#4140]
**Please provide the following information**

libtorrent version (or branch): 1.2.2

platform/architecture: Linux x86_64

compiler and compiler version: gcc 8.3.0

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Sometimes announces will timeout when connecting to the tracker which produces a result

endpoint.is_working = false
endpoint.message = "error message"

The problem is that on the next successful announce the message is not cleared which results in

endpoint.is_working = true
endpoint.message = "same error message"

I know this is might be difficult to actually test so if you need any help testing I can pull and test it.

**Comment by arvidn** [comment]
could you please test whether this patch fixes it? https://github.com/arvidn/libtorrent/pull/4143

**Comment by NotKyros** [comment]
That fixed it. Thanks!
