### ISSUE TITLE
Priority not set using file_priority

### ISSUE THREAD

**Issue by NotKyros** [arvidn/libtorrent#4141]
**Please provide the following information**

libtorrent version (or branch): 1.2.2

platform/architecture: Linux x86_64

compiler and compiler version: gcc 8.3.0

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

When setting several file priorities in a loop with handle.file_priority not all of them are properly set. Typically only one of them will even change.

**Comment by arvidn** [comment]
can you be a bit more specific in *how* you set the file priorities, (there are multiple ways) and also *what* the symptom is. What calls do you make and what responses do you get to suggest that the file priorities have not been updated. Does the bittorrent engine behave as if they have not been set? e.g. if you set files to priority 0, are they still being downloaded.

**Comment by NotKyros** [comment]
Specially this method doesn't seem to work properly.

void file_priority (file_index_t index, download_priority_t priority) const;

What I do is add a torrent to the session with all the priorities set to 0, which works as expected.

Later on I will do the following. 

// indexes is a vector of file_index_t passed back from the client 
for (auto index : indexes) {
    handle.file_priority(index, 4);
}

After this I update the client as normal through the alert system, but only one of the files ever has its priority changed. I can keep doing this and each time it will update one file priority.

The work around is to use 

void prioritize_files (std::vector<download_priority_t> const& files) const;

but I figured you would want to know this isn't working properly.

**Comment by arvidn** [comment]
> After this I update the client as normal through the alert system

what do you mean by this exactly? you call `torrent_handle::get_file_priorities()`, right?

Also, are you taking into account the comment on [file_priority()](http://libtorrent.org/reference-Core.html#file_priority())?

> Since changing file priorities may involve disk operations (of moving files in- and out of the part file), the internal accounting of file priorities happen asynchronously. i.e. setting file priorities and then immediately querying them may not yield the same priorities just set. However, the piece priorities are updated immediately.

**Comment by NotKyros** [comment]
I do call get_file_priorities() but not immediately after setting the priorities. I had read that comment and knew not to expect it to be a synchronous operation.

I actually had a question about that. Is there a specific alert triggered when the file priorities change?

How it works right now is that the client is actually a thin client and doesn't do anything other than load data sent from the server into the GUI. On the server side I have a main loop that runs once a second that does post_torrent_updates() and pop_alerts(). From that set of alerts I generate a packet containing the torrent info to be sent to the client. So get_file_priorities() is called every time an alert associated with the torrent is encountered. It usually takes one or two passes through the main loop for the priorities to update but they do update exactly as expected when using prioritize_files(). But, if I set multiple file priorities through file_priority in a loop I only ever see one file change priority. It doesn't matter how much time passes, only the one will change. It also appears to be some what random as to which file's priority gets changed.

**Comment by arvidn** [comment]
> I do call get_file_priorities() but not immediately after setting the priorities. I had read that comment and knew not to expect it to be a synchronous operation.

Actually, come to think of it. I think I know what's going on. The call to `file_priority()` will take the vector of all file priorities currently in the torrent, update it with the new priority, and then post that new vector to the disk-I/O thread. Only when that disk operation comes back will the torrent's file priorities be updated, which means that any call to `file_priority()` in between, will have used a stale copy of the file priorities.

I will probably need to make the disk job a bit more sophisticated to support single-file priorities.

The fundamental reason to treat the vector of file priorities this way is because the disk job *might* fail, and in that case the priorities should be left unchanged, to remain consistent. i.e. the disk thread and the main thread should have consistent views of the file priorities. that's important.

> I actually had a question about that. Is there a specific alert triggered when the file priorities change?

No, there's not. Which is a bit inconsistent, since there *is* and alert fired in case of a failure to set the priority.

**Comment by arvidn** [comment]
I'm pretty sure this solves it: https://github.com/arvidn/libtorrent/pull/4151

**Comment by arvidn** [comment]
using `prioritize_files()`, as it sounds like you do now, is more efficient. I would recommend that. But would you mind testing this patch with your previous version to make sure I fixed it?

**Comment by NotKyros** [comment]
Thanks for the advice.

I tested the patch and it works correctly. Cheer!
