### ISSUE TITLE
Listening interfaces issues

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#4155]
These were tested with latest 1.2.x.

I did some recent refactor to qBittorrent on how we tell libtorrent to listen to IP/interfaces. Here are some things that I found out and you may be able to address some of them.
I make this as a quick and dirty list, otherwise I would forget to make it at all.

1. When `listen_interfaces` has only one IP/interface which fails (or doesn't exist) libtorrent shouldn't fail silently! If a bogus string is passed libtorrent doesn't post an `listen_failed_alert`. Maybe this is due to the string not being able to be represnted internally as an IP address? Moreover, and this is more concerning, libtorrent goes ahead and listens to `0.0.0.0`. If someone has configured a VPN interface and libtorrent suddenly listens to `0.0.0.0` that is a major security/privacy issue. IMO, libtorrent should just stop working (on the networking side) if the configured `listen_interfaces` are all bad.
2. In the above case it binds only to IPv4_ANY, even though an empty `listen_interfaces` binds to IPv4_ANY and IPv6_ANY.
3. I admit that the following is a "limitation" of boost.asio and it would be very hard for you to implement in a cross platform way. I just want to inform you, in case there is a way to document this: libtorrent can't handle **textual** IPv6 link-local addresses that have as a scope id an interface name. It expects an interface number (or plainly a number) as scope id.

**Comment by ssiloti** [comment]
Are you sure about libtorrent only listening on `0.0.0.0`? I'm unable to reproduce that behavior and the code should be listening on both `0.0.0.0` and `::`.

There is a weird distinction right now between specifying an invalid interface name and an invalid IP address. The former will be treated like an empty `listen_interfaces` (thus listening on the unspecified addresses) while the latter will not listen on any interfaces if that was the only interface specified. I'll change it so the empty `listen_interfaces` logic only triggers if `listen_interfaces` really is empty.

**Comment by sledgehammer999** [comment]
>Are you sure about libtorrent only listening on 0.0.0.0?

I am basing this on the `listen_success_alert` that I get. I only get one for `0.0.0.0`

**Comment by arvidn** [comment]
my recollection is that we disable the feature some operating systems have where binding a listen socket to `0.0.0.0`, it also accepts connections on `::`. My recollection/understanding of why we do this, is because there's a lot of internal logic that depends on knowing all the interfaces and address families we listen on. The tracker announce logic is one example. So, afaict, listening on `0.0.0.0` is distinct from `0.0.0.0:6881,[::]:6881`.

I agree through, that invalid strings should not fail silently. and it doesn't seem right that it treats an empty string (or invalid string) as 0.0.0.0. It would be better to not listen on anything in such cases.

**Comment by arvidn** [comment]
but it's not obvious to me how an invalid interface name should be reported though. It doesn't make it as far as to even *try* to listen, so technically it's not listening that fails. It's something earlier. Maybe there should be a separate alert for these errors.

**Comment by arvidn** [comment]
@ssiloti don't you think it's useful to be able to specify an empty string to indicate that no listen sockets should be opened?

**Comment by arvidn** [comment]
does this look reasonable? https://github.com/arvidn/libtorrent/pull/4159

**Comment by sledgehammer999** [comment]
@arvidn, shouldn't an empty string indicate default behavior?
PS: The online docs are a bit outdated on the default value of `listen_interfaces` (in the table) they list it as `0.0.0.0:6881` while the rest of the docs indicate `0.0.0.0:6881,[::]:6881` as default

**Comment by arvidn** [comment]
The setting already have a default value, which I would expect to be the default behavior.
If an empty string means listening to something, how would you say not to listen to anything?
(from looking at the code, it appears this is the case already)

yeah, there was a parser bug in the documentation generation script. I've fixed it and it should be reflected on the site when I cut the next 1.2.x release.

**Comment by ssiloti** [comment]
Right now if no listen interfaces are specified libtorrent will listen on the unspecified addresses. See https://github.com/arvidn/libtorrent/blob/RC_1_2/src/session_impl.cpp#L1827

Not listening on any interfaces would prevent libtorrent from announcing to UDP trackers or joining the DHT since there would be no UDP socket to use. We'd need to add some special casing to support operation without any listen interfaces.

**Comment by arvidn** [comment]
@sledgehammer999 I think this is mostly addressed now. as for (2), I think a subtle distinction is that the `listen_succeeded_alert` doesn't actually represent sockets that will accept incoming connections. They will only be used for outgoing connections, uTP peers, the DHT and UDP trackers.

**Comment by sledgehammer999** [comment]
>They will only be used for outgoing connections, uTP peers, the DHT and UDP trackers.

Isn't that the job of `outgoing_interfaces`?

**Comment by sledgehammer999** [comment]
PS: You can close this when you want.

**Comment by ssiloti** [comment]
The `outgoing_interfaces` setting is only for outgoing peer connections. The DHT and tracker announces are always tied to a listen socket.
