### ISSUE TITLE
Warning C4834: discarding return value of function with 'nodiscard' attribute

### ISSUE THREAD

**Issue by Chocobo1** [arvidn/libtorrent#4156]
**Please provide the following information**

libtorrent version (or branch):
RC_1_2

platform/architecture:
Windows

compiler and compiler version:
MSVC 2019 16.4.0

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I'm getting the following warning when compiling:
```
C:\Users\abc\Desktop\libtorrent\src\pe_crypto.cpp(331,24): warning C4834: discarding return value of function with 'nodiscard' attribute [C:\Users\abc\Desktop\libtorrent\_build\torrent-rasterbar.vcxproj]
```
which leads to here: https://github.com/arvidn/libtorrent/blob/RC_1_2/src/pe_crypto.cpp#L331
I wonder if it should be `if (!m_decrypt) return std::make_tuple(0, 0, 0);` instead.

**Comment by arvidn** [comment]
yes, you're right. *fixing*

**Comment by arvidn** [comment]
addressed here: https://github.com/arvidn/libtorrent/pull/4157
thanks for the report!
