### ISSUE TITLE
What happens if status is call in an invalid torrent_handle?

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#416]
The documentation states that `it will throw libtorrent_exception` but I can't see the throw in `torrent::status`. Looking at the code, it seems an undefined behavior or crash is more likely. If I'm correct, could you point out some idea about how to properly handle the case?

**Comment by arvidn** [comment]
torrent_handle is a wrapper around a boost::weak_ptr<>. the handle being invalid is the same as the weak_ptr<> having expired (i.e. the object it points to has been destroyed). Every call to a function on torrent_handle, will lock() the weak_ptr<> (and hence get a temporary shared_ptr<>). The shared pointer is either NULL or valid. If it's NULL, an exception is thrown. The logic to do this is in torrent_handle.cpp

**Comment by aldenml** [comment]
I will make another question a little related to this in another issue. Thanks
