### ISSUE TITLE
libtorrent 1.2 sends event_complete even if I didn't download the file.

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4170]
**Please provide the following information**

libtorrent version (or branch):
1.2
platform/architecture:
Windows/Linux
compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
libtorrent sends event_complete even if it just rechecked the files from disk and started seeding.
Scenario:
I uploaded a torrent on a tracker and then downloaded the metafile from site to seed it. After adding, qBit/deluge just rechecked the file. After the checking was done it sent event_complete to tracker even if it didn't download any data. This just added a false completion count on that tracker for that particular torrent.

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/4171
