### ISSUE TITLE
Is there a way to check proxy status?

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#4172]
~1 week ago qBittorrent switched officially to 1.2.2+git
I have some users complaining that they can't get any connections when using SOCKS5 proxies. The same proxy worked good with 1.1.x.

I see that there aren't any alerts for succeed/fail proxy connection/authentication etc. Shouldn't there be some? 

Is there any other way on how to debug this?

**Comment by arvidn** [comment]
I don't think there is any good ways. You could try enabling debug logging in the alert mask, but I'm not sure all relevant failures are logged even. I'm open to suggestions. One challenge is that if *every* message that fails triggers an alert, there would be a lot of alerts.

I'm hoping 1.2.3 will address most of the proxy issues.

**Comment by sledgehammer999** [comment]
Users keep facing 2 issues with latest RC_1_2 (68196dceae)
1. Some complain that they can't connect to udp trackers nor the DHT. I suspect that is due to the old 

2. Others complain that they no longer can login to their proxies. I'll follow up on this, but maybe this actually case 1, but haven't realized yet because their torrents use udp trackers only. I'll investigate furhter.

But I need your help. Is there any way (or tool) that I can run locally that can act as proxy which will just forward the connections to my usual network interface?

I tried doing this with ssh but I since I am noob may have used wrong configuration.
a) I fire up a debian VM install openssh-server and openssh-client.
b) I configure VirtualBox to forward the VM's address to the host's `127.0.0.1` along with ports.
c) Then in the VM I issue `ssh -N -D <vm address>:5555 0.0.0.0
d) I configure qbittorent to listen to a SOCKS5 proxy at `127.0.0.1:5555`

My hope was that udp connections would be handled too by this setup. But no, only http trackers work and TCP connections between downloading peers. No DHT, no udp trackers, utp protocol connections.

Do I need to do something else with ssh?

**Comment by sledgehammer999** [comment]
>Right, the bug was UDP packets sent over SOCKS proxies to hostnames. That mostly means UDP trackers. That would fail most of the time. (I just cut 1.2.3 which fixes this btw.)

Yeah, my new release was based on https://github.com/arvidn/libtorrent/commit/68196dceae3443e9af4b78c0ebb8dc24b63043b7 which includes the fixes.

>If you're using ssh, I don't think you need a VM

Unfortunately my main machine is Windows, and ssh doesn't play there (well it does, if I go out of my way to make it work)

>There is a proxy called dante

I'll try to see if that works.

But on another note: Is force_proxy behavior merged into anonymous mode? If anonymous mode is disabled are udp operations done without using the proxy (in the case where the proxy doesn't support udp)?
Can you give a more detailed explanation on what happens with regards 1) to udp trackers 2) DHT 3) μTP peer connections, when anonymous mode is enabled? (assume a proxy is used)

**Comment by arvidn** [comment]
> But on another note: Is force_proxy behavior merged into anonymous mode? If anonymous mode is disabled are udp operations done without using the proxy (in the case where the proxy doesn't support udp)?

Actually, `force_proxy` was removed/deprecated and always enabled. I think this is much more in line with what people expect. If they configure a proxy, it will be used or fail. The previous default behavior of using it as best-effort, and circumvent it if it didn't work, is unintuitive (I think).

> Can you give a more detailed explanation on what happens with regards 1) to udp trackers 2) DHT 3) μTP peer connections, when anonymous mode is enabled? (assume a proxy is used)

I've also been trying to phase out anonymous mode, and increasingly enable its behavior by default. Anonymous mode really only affects the kind of data that's sent over various connections. Off-hand I don't think it affects DHT or UDP trackers. For peers I think it advertises a different peer-id when connecting to them, and for HTTP trackers it does not include additional IPv4 and IPv6 IPs. But I think that last thing has already been disabled anyway.

**Comment by sledgehammer999** [comment]
OK. Since I don't have any proxy subscription the best I can do is provide info from affected users. Question is, what would help you understand the problem? Should I provide them a build with logging enabled and share back the log?

**Comment by arvidn** [comment]
I suppose I could add an alert to post back proxy failures. I'd have to think about how to do that in an ABI-stable way though. Maybe a `peer_log_alert`.

**Comment by arvidn** [comment]
@sledgehammer999 do you think this would work? https://github.com/arvidn/libtorrent/pull/4202
