### ISSUE TITLE
Question about concurrency and cached_piece_entry::ok_to_evict

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#418]
Do you think there's a chance of having concurrency issues during the call of this method (see the bold line)? The operation `!hash || hash->offset == 0` is not atomic and I don't know if `hash` could become null in other jobs.
<pre>
		bool ok_to_evict(bool ignore_hash = false) const
		{
			return refcount == 0
				&& piece_refcount == 0
				&& num_blocks == 0
				&& !hashing
				&& read_jobs.size() == 0
				&& outstanding_read == 0
				<b>&& (ignore_hash || !hash || hash->offset == 0);</b>
		}
</pre>

**Comment by arvidn** [comment]
The intention (iirc) is that this function would only be called while the cache mutex is held. There entire cache is protected by a mutex, and must be held whenever updating _metadata_ in the cache. Such as adding new blocks and removing blocks. Note that the time consuming operations like reading and writing from disk are done without holding the mutex (obviously). To indicate that a thread is using a piece, the piece_refcount is incremented. This is meant to prevent other threads from evicting it during such time consuming operations. Basically it's a way to pin a piece, or to record that a piece is in use while _not_ holding the lock. To decrement the counter (or to complete and clear the hash object, or touch any other direct member of the piece) the cache mutex must be held.

Are you seeing bugs that look like race conditions?

**Comment by aldenml** [comment]
You can see three instances of the error in this issue: https://github.com/frostwire/frostwire-jlibtorrent/issues/44

It has minimal occurrence in the released binaries. No idea of how to reproduce it or if it's happening in other architectures.

Thanks for the explanation.

**Comment by aldenml** [comment]
I will close this and open another one once I have the necessary data.

**Comment by arvidn** [comment]
btw. I took a pass over the flush_cache function, and it looks correct. It's possible that there's a mutex error somewhere else though. I should probably run this through hellgrind and thread-sanitizer (if you have an opportunity to do so, please go ahead. those aren't easily accessible on OSX)
