### ISSUE TITLE
tutorial describes depricated save_resume_data_alert

### ISSUE THREAD

**Issue by ghbplayer** [arvidn/libtorrent#4184]
The [LT tutorial](https://www.libtorrent.org/tutorial.html) describes save_resume_data_alert::resume_data which is deprecated in 1.2. It does not describe how to save resume data in the 1.2 manner.

**Comment by arvidn** [comment]
yes, I noticed that a few days ago. I fixed it here: https://github.com/arvidn/libtorrent/pull/4160
I will update the website soon when I release 1.2.3
