### ISSUE TITLE
documentation: torrent_handle::auto_managed deprecated

### ISSUE THREAD

**Issue by ghbplayer** [arvidn/libtorrent#4187]
Per the documentation, "To opt-out of the queuing logic, make sure your torrents are added with the add_torrent_params::flag_auto_managed bit cleared. Or call torrent_handle::auto_managed(false) on the torrent handle."

auto_managed is deprecated, documentation should describe the new way (whatever that is).

**Comment by arvidn** [comment]
I folded fixing this into the patch I was working on already: https://github.com/arvidn/libtorrent/pull/4189
