### ISSUE TITLE
Question about new PRs

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#419]
Hi @arvidn, with the cut of the new branch RC_1_1. What do you prefer for new PRs? Doing it in RC_1_1 for a while and you maintain master? or just to master? or... Thanks

**Comment by arvidn** [comment]
I'm hoping RC_1_1 can stay feature freezed, while I try to address bugs that people have brought up. So I'm thinking fixes go into RC_1_1 new features go into master. I will merge RC_1_1 into master periodically (now that I can finally do that natively in git, the svn -> git conversion did not preserve the relationships between my other branches correctly)
