### ISSUE TITLE
[Feature Request] solve the mismatched configuration problem

### ISSUE THREAD

**Issue by ghbplayer** [arvidn/libtorrent#4194]
Even though [the building page](https://www.libtorrent.org/building.html) clearly warns about #defines, and even though I read that page, I still got burned by mismatched  settings to the cost of 8-15 hours (haven't tracked down root cause for all the issues yet).

Since this is "a common mistake" perhaps it's time to fix it.

Other OSS libraries I've used in the past would generate a config header containing #defines. I haven't seen that recently, perhaps that's the old world way of handing the problem. Another solution would be to generate a symbol name based on #defines and cause a linker error if the client version of the symbol name doesn't match the library version.

**Comment by arvidn** [comment]
>  Another solution would be to generate a symbol name based on #defines and cause a linker error if the client version of the symbol name doesn't match the library version.

That's what I used to do in libtorrent-1.1, when almost all configuration options would affect the ABI. That's not supposed to be the case anymore though.

In libtorrent master, I use inline namespaces to encode configuration options in public types. If there are any types that I've missed, that's a mistake, and I would really like to fix them. Unfortunately I can't do that in 1.2, since that would break the ABI.

As far as I can tell, the only macros affecting the ABI are `TORRENT_ABI_VERSION`, and the macros controlling which crypto library to link against. Although, there are all kinds of other possible build options that affect ABI as well, such as `_GLIBCXX_USE_CXX11_ABI`, `-std=` and other build flags. That's typically what build systems help with. Both the `Jamfile` and the `CMakeLists.txt` propagate build options to clients to stay ABI compatible. The generated `libtorrent-rasterbar.pc` file is also supposed to include the build configuration.

**Comment by ghbplayer** [comment]
I've been working in RC_1_2 so I can't speak to master. In RC_1_2 I had clear problems with `torrent` even though I had ABI and std set correctly. I'm not sure what the ABI rules are, but in that header at least three #defines control data members and many change function members (not counting TORRENT_ABI_VERSION or_M_AMD64).

I built lt with boost jam, but my projects don't use either jam or cmake which are both rather complicated things I haven't learned.

Should I use master for development?

**Comment by arvidn** [comment]
you mean `torrent` as in the internal type? I'm only making attempts to have a stable ABI of the public API. Plugins that use the internal types are documented to not have the stable ABI guarantee. In fact, not even the internal API is stable.

https://www.libtorrent.org/reference-Plugins.html#a-word-of-caution

I don't think master would make a material difference with regards to this.

**Comment by ghbplayer** [comment]
I see. The clientdata feature I just wrote should probably have a function in torrent_handle then.

Despite that, please consider helping us client developers by bringing back the build setting feature you had before. Perhaps you could make it an opt-in feature.

**Comment by arvidn** [comment]
I'm bringing it back in master, but using inline namespaces. But still only for build configurations that affect the *public* ABI. I don't really think there's a good reason to try to maintain a stable *internal* ABI. That would add significant constraints.

**Comment by arvidn** [comment]
If `native_handle()` is the root of all this, perhaps I should add wording to make it clearer that it's not supposed to be used. I've slowly moved internal types into the `aux` namespace, but there are still a lot of types I haven't gotten to. I imagined that not mentioning internal types in the documentation would be mostly sufficient.

**Comment by ghbplayer** [comment]
I can tell you've put a lot of thought and effort into the design of libtorrent. It's a remarkable creation and I appreciate it. There have been many things I didn't see in torrent_handle.hpp (or were deprecated) that I found through native_handle. Most of those things were hiding in torrent_status or torrent_flags which have their own headers.

Thus I've been using native_handle plenty. Looking through my source now, I'm still using `torrent` to check if a torrent is ssl and to disable auto_managed mode for a torrent before saving resume data and removing it. I'm sure you know why that's critical to do.

My point is, there are always things that were overlooked, or things that most clients don't need but some do. In time I need to extract DHT and scrape/announce into another process, and write an alternate storage system to store torrent payload as a single file. And one other thing that's too horrible to mention. I'm not going to get less intimate with the non-ABI-guaranteed interfaces. Other clients aren't like me but they may need some of those overlooked bits too.

I'm not suggesting you try to maintain internal interface ABI. But for those of us who go deeper, could you add an opt-in check for matching build flags? If not, could you tell me how to do so?

**Comment by arvidn** [comment]
but `torrent` is not documented *anywhere*. The public API to do all of those things *are*:

### is a torrent an ssl torrent
[torrent_handle::torrent_file()](https://libtorrent.org/reference-Core.html#torrent_file()) returns [torrent_info](http://libtorrent.org/reference-Core.html#torrent_info) with a member [ssl_cert()](https://libtorrent.org/reference-Core.html#ssl_cert()). Perhaps there should be an `is_ssl()` there as well, but this is a niche feature that (afaik) very few people use.

### disable auto managed
The second paragraph of the [queuing](https://libtorrent.org/manual-ref.html#queuing) topic shows how to do this. Granted, the documentation for those flags had not made it into the reference documentation until yesterday.

### saving resume data
The documentation for [save_resume_data()](https://libtorrent.org/reference-Core.html#save_resume_data()) has an example of how to do that. Granted, the example stops the whole session to save resume data, not individual torrents. Keep in mind that pausing the torrent will affect the resume data though, as the paused and not-auto-managed states will be saved in the resume data. You still don't need to use the internal data structures to do this.

>  In time I need to extract DHT and scrape/announce into another process

You can do this with the public API too. See [dht_announce_alert](https://libtorrent.org/reference-Alerts.html#dht_announce_alert)

> and write an alternate storage system to store torrent payload as a single file

You can do this with the public API too. See the [custom storage topic](https://libtorrent.org/reference-Custom_Storage.html#overview). In fact, you'll find examples close to what you describe on the internet. For instance [btfs](https://github.com/arvidn/btfs).

> I'm not going to get less intimate with the non-ABI-guaranteed interfaces.

Another issue you may run into is that the internal functions are not exported. If you ever end up linking against libtorrent as a shared library you're likely to get missing symbols.

> I'm not suggesting you try to maintain internal interface ABI. But for those of us who go deeper, could you add an opt-in check for matching build flags? If not, could you tell me how to do so?

The only proper solution to this is to use a good build system, that ensures ABI compatibility between objects it links together. Unfortunately there aren't that many good build systems (few seem to care about ABI). boost-build is good, and cmake (as long as you stick to "modern") is getting closer.

**Comment by ghbplayer** [comment]
Okay, I think I'll just change config.hpp locally.
