### ISSUE TITLE
Change your git name/email to match those from svn

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#42]
This is really minor and you can insta-close it.
You may have not noticed but the commits coming from the svn import have as Author `Arvid Norberg <arvid@libtorrent.org>` while the commit from git have as Author either `arvidn <arvid@cs.umu.se>` or `arvidn <arvid@libtorrent.org>`

You can fix it for the next commits by doing:
```
git config user.name "Arvid Norberg"
git config user.email arvid@libtorrent.org
```

Add the switch `--global` after `config` to change it globally.
IIRC you have to do it for every local copy of the repo you have lying around on different machines.

**Comment by arvidn** [comment]
This is due to me having slightly different configs on different machines. I agree that it's annoying. I assume there's no way to rewrite history without breaking everyone's hashes, right?

**Comment by sledgehammer999** [comment]
>I assume there's no way to rewrite history without breaking everyone's hashes, right?

Exactly.
If you want to change without rewriting history, it will affect only your new commits to the repo.

**Comment by jpetso** [comment]
You can, however, add the other email address to GitHub so that at least online it links to the same author.

**Comment by arvidn** [comment]
I've added the email arvid@libtorrent.org to my account.

**Comment by sledgehammer999** [comment]
Just so you know your last commits still show another alias+mail. I think you forgot to update all your git configs.

**Comment by arvidn** [comment]
maybe I'm misunderstanding something. This is what I have from "git log".

   * commit ac377c07671bcee5b79e59985c80396d095af2ad

   | Author: arvidn <arvid@cs.umu.se>

   | Date:   Fri Jul 24 20:17:01 2015 -0700

And github links it to my account.

**Comment by sledgehammer999** [comment]
1. You have to understand that what I am talking is purely cosmetic, so don't fret over it.
2. If you go check a commit coming from SVN you'll see `Arvid Norberg <arvid@libtorrent.org>` as Author.

In case you want to use that, you need to do the steps I described in my first post.
If you want to continue using `arvidn arvid@cs.umu.se` (and other variations) don't do anything.
