### ISSUE TITLE
What happens with a status call for a torrent_handle in a multithreaded environment?

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#421]
If I obtain a `torrent_handle` either from `find_torrent` or handling a `torrent_alert`, I call `status`, what happens if in another different thread I remove the torrent from the session and still the `status` call is in progress? Nothing wrong with `m_picker` or `m_torrent_file`?

**Comment by arvidn** [comment]
hm.. it's not obvious that it would be a problem. Both the call to torrent::status() and that of session::remove_torrent() are serialized on the main network thread. However, if the remove_torrent() call runs first, it may actually start tearing things down. Ideally it wouldn't though. ideally everything owned by the torrent object should be torn down by the destructor.

**Comment by aldenml** [comment]
Thanks for the explanation.
