### ISSUE TITLE
Question about announce_entry and std::string

### ISSUE THREAD

**Issue by T00old4This** [arvidn/libtorrent#4215]
Hi,

I don't know if this is the right place to talk about the code ?

I'm playing a little with c++, and how compilation works, etc, and I'm not very good at it yet, so I'm doing some testing with my own tracker.

Right now I'm trying to change the response of libtorrent depending on the message returned by the tracker. My goal is, if the message is xxxxxxx, then retry in xx seconds, if not, use the normal delay.

I'm working on announce_entry.ccp, this section 

```
void announce_endpoint::failed(int const backoff_ratio, seconds32 const retry_interval)
	{
		++fails;
		// the exponential back-off ends up being:
		// 7, 15, 27, 45, 95, 127, 165, ... seconds
		// with the default tracker_backoff of 250
		int const fail_square = int(fails) * int(fails);
		seconds32 const delay = std::max(retry_interval
			, std::min(duration_cast<seconds32>(tracker_retry_delay_max)
				, tracker_retry_delay_min
					+ fail_square * tracker_retry_delay_min * backoff_ratio / 100
			));
		if (!is_working()) next_announce = aux::time_now32() + delay;
		updating = false;
	}
```

When I'm looking at announce_entry.hpp, I saw that the message returned by the tracker should be in std::string message . Am I right about this ?

So I changed the code above to 
```
int const fail_square = int(fails) * int(fails);
		seconds32 const delay = std::max(retry_interval
			, std::min(duration_cast<seconds32>(tracker_retry_delay_max)
				, tracker_retry_delay_min
					+ fail_square * tracker_retry_delay_min * backoff_ratio / 100
			));
		if (std::string message = "Error: xxxxx" || std::string message = "xxxxxx") next_announce = aux::time_now32() + seconds(60);
		else
if (!is_working()) next_announce = aux::time_now32() + delay;
```

With this, when I compile, I got an error c4458 saying that the declaration of "message" hides class member, and after that a note about the "std::string" declaration (and others syntax errors which I can work out).

Should I use another thing that std::string message to test the message send by the tracker ?

Thanks.

**Comment by arvidn** [comment]
is there a problem with just using the `interval` field?

**Comment by T00old4This** [comment]
Instead of next announce ?

**Comment by arvidn** [comment]
I mean, the tracker already responds with the re-announce interval in the `interval` key. If you, the tracker, wants to control how long the client should wait until re-announcing, you can just decide that when sending the `interval` key in the tracker response.

**Comment by T00old4This** [comment]
Oh sorry. Yes of course, but my goal here is to have the client making different choices according to the message sent by the tracker.

**Comment by arvidn** [comment]
different choice if what? if "what" is the re-announce interval, the `interval` field is the way to communicate that. but maybe it's some other choice.

**Comment by T00old4This** [comment]
But in my test I don't want to control that with/from the tracker side. The tracker will send a value, fine.
But I'm trying to have the client adapting his next announce time to the error or warning message sent by the tracker. If the message is xxxxxxx, then retry in xx seconds, if not, use the normal delay sent by the tracker.

**Comment by arvidn** [comment]
the simplest way of doing that is to insert an assignment to `resp.interval` [here](https://github.com/arvidn/libtorrent/blob/RC_1_2/src/http_tracker_connection.cpp#L448) and [here](https://github.com/arvidn/libtorrent/blob/RC_1_2/src/http_tracker_connection.cpp#L455).

I wouldn't recommend doing that though. If the tracker has an opinion about the re-announce interval, it has a way to communicate that already. I suppose the *client* may have opinions too, in which case it might make sense to have some heuristic. But those free-form fields can vary a lot, and be in different languages. It's hard to have a reliable one.

**Comment by T00old4This** [comment]
Oh I agree about the weakness of actions based on free form fields. That's why it's just some tests again a tracker that I can manage.
I'll look at http_tracker_connection , thanks you. I was looking at announce_entry because that's where it seems the simplest for in my mind, and where I can easily adjust the announce delay. Last question about that the, in the documentation about announce_entry  here : https://www.libtorrent.org/reference-Core.html

Is the part about the message _"message
if this tracker has returned an error or warning message that message is stored here"_ still valid ?

**Comment by T00old4This** [comment]
All right, I did it via the announce_entry in the end. I am ashamed of the code I wrote in the first post, what's wrong with me !

I won't put the code here, since I realize you can do bad stuff with it (like hammering a tracker non stop), even by mistake.

Happy new year everyone !

**Comment by arvidn** [comment]
> Is the part about the message "message
> if this tracker has returned an error or warning message that message is stored here" still valid ?

yes
