### ISSUE TITLE
expanding [::] to all IPv6 interfaces (multi-homed support)

### ISSUE THREAD

**Issue by arvidn** [arvidn/libtorrent#4216]
libtorrent version (or branch): RC_1_2

Currently, if one has multiple network interfaces and listens on `[::]` (which is done by default). That address is expanded to all IPv6 addresses the machine has. One reason for having multiple IPv6 addresses is by running a VPN, where there's a `tun0` device with an IPv6 address assigned to it.

The current logic opens a listen socket for both the VPN interface *and* the underlying "direct" interface. I don't think this is intuitive behavior. It's explained in the code with this comment:

```
      // To comply with BEP 45 multi homed clients must run separate DHT nodes
      // on each interface they use to talk to the DHT. For IPv6 this is enforced
      // by prohibiting creating a listen socket on [::]. Instead the list of
      // interfaces is enumerated and sockets are created for each of them.
      // This is not enforced for 0.0.0.0 because multi homed IPv4 configurations
      // are much less common and the presence of NAT means that we cannot
      // automatically determine which interfaces should have DHT nodes started on
      // them.
```

This is why it's not done with the IPv4 counterpart, 0.0.0.0.

My first thought of making this more intuitive was to only expand it to the single *main* IPv6 interface. To find the main interface:

1. find the first entry in the routing table with `[::]` as the destination. remember the associated device name.
2. find the first IP address in the interfaces list associated with this device, and whose gateway is specified.

If no entry in the routing table can be found, ignore the `[::]` entry in the `listen_interfaces` setting. This same algorithm could be used to treat the unspecified IPv4 address the same as well.

The idea is that in the (presumably rare) case of having a machine actually hooked up to two or more internet connections, one would have to explicitly add both to the `listen_interfaces` setting.

After having implemented this behavior though, it occurred to me that it really seems that the behavior I'm looking for is to preserve the unspecified listen addresses, and let the OS figure it out. The question in that scenario is what to do about the DHT nodes.

Perhaps the DHT node could be made to allow the unspecified IPv6 address, but use the algorithm above to find its concrete IP.

In either case, I should also add a section in the documentation talking about multi-homed support and explain this logic in detail, to make it clear how it works.

@ssiloti I'm hoping you have some thoughts or opinions on this. I'm not sure what the best solution is, but I really hope it involves reducing complexity.

**Comment by arvidn** [comment]
actually, the comment about prohibiting DHT nodes on `[::]` seem outdated. I don't see anything prohibiting this.

**Comment by ssiloti** [comment]
A DHT node on `[::]` is effectively prohibited because `session_impl::reopen_listen_sockets` will not create a listen socket on `[::]` unless network interfaces cannot be enumerated.

**Comment by arvidn** [comment]
what would fail by starting a DHT node on `[::]`?
I imagine a "plain" socket, not subject to any kind of `BINDTODEVICE`. It would just use the regular routing table, where it can only send packets over the one default route for IPv6, so (afaict) it would effectively be restricted to one external IP address (although, it might be able to receiving packets from another IP still)

**Comment by ssiloti** [comment]
I'm not familiar enough with how OSs handle routing in multi-homed environments to definitively refute that, but empirically the8472 found nodes running builds of libtorrent from before the multi-homed changes went in which were visible from multiple IPv6 addresses. Those builds were binding to `[::]` so apparently that does not effectively cause traffic to only use one address.

**Comment by arvidn** [comment]
I see. So, from the DHT's point of view, we would ideally *only* use sockets that's been `SO_BINDTODEVICE` (or similar). Now, in practice, I'm not sure that's really doing what we need, since it requires root privileges on linux. I'm not sure about BSD and MacOS (they have a similar socket option).

My impression is that what *really* is required is to be able to specify a different routing table, where the default route points to a different device for each socket. I imagine that's one of the effects of a successful call to `SO_BINDTODEVICE` (but I'm not sure).

**Comment by arvidn** [comment]
If it actually makes a difference for the DHT when the corresponding listen socket is attempted to be bound to a specific address, I think it would be better to translate `[::]` into the IPv6 address whose device has the default route and gateway associated with it. The same thing could be done for `0.0.0.0` as well.

**Comment by ssiloti** [comment]
Using heuristics to bind to an address on the interface with the default route would probably work, although it does make me a little nervous that there may be edge cases which aren't handled correctly.

**Comment by ssiloti** [comment]
I think expanding `[::]` to all addresses on the interface with the default route would provide a happy medium. The VPN case would be handled correctly with no heuristics. The only case which would require manual configuration would be if you want libtorrent to operate on multiple interfaces. I doubt that is a common use case, certainly less so that VPNs.

**Comment by arvidn** [comment]
yeah, that seems like a good idea. Wouldn't that work for `0.0.0.0` as well then?

**Comment by ssiloti** [comment]
Expanding `0.0.0.0` would be fine for common configurations. If there are private addresses on the interface which are not NATed it would cause spurious DHT nodes, tracker announces, etc, but AFAIK that sort of thing would be highly unusual.

**Comment by arvidn** [comment]
The problem of expanding `0.0.0.0` is that we skip loopback IPs in the expansion, so the loopback address will not be listened on, and all localhost unit tests fail.

The smaller patch would be to leave in the logic where IPv4 is special.

I wonder, though, if the long term fix would be to actually include loopback addresses, but then also restrict NATPMP, UPnP, SOCKS5 and tracker announces to skip listen sockets that don't make sense to use.

Exactly how to know which ones make sense I think would probably be something like this:

1. when expanding the unspecified listen address, also record which device it's from (and I suppose the loopback device would have to be a special case).
2. when determining whether a listen interface is sensible to announce from (or connect a SOCKS5 proxy for etc), we have a concrete destination IP (the tracker, the SOCKS5 proxy etc.), if (1) the IP either falls inside the network represented by the listen address and its netmask (2) the listen interface is associated with a default route (and has a gateway associated with it), then it's OK to use.

It seems a bit complex to do that, and I'm not a fan of making the loopback device a special case.

**Comment by arvidn** [comment]
in fact, this is a problem with the IPv6 loopback interface right now. There just isn't a unit test that runs over `[::]` (I added a `test_transfer` test that runs over IPv6 loopback to verify this). I think this is worth solving too.

I'm a bit worried about going down the path of (by default) not listening on all interfaces. Say we fix the loopback for IPv6, does that mean we don't accept connections from peers on the same network?

**Comment by arvidn** [comment]
Here's my understanding of the problem right now:

We expand `[::]` to all "external" IPv6 addresses on the machine, so that we'll open a `listen_socket_t` for each. We do this to avoid having a DHT node that's reachable via multiple different IP addresses. A `listen_socket_t` when used for outgoing packets, won't necessarily force the packet being sent from the specific IP/interface. The destination IP, via the (global) routing table decides which interface to send outgoing packets from. However, we do *filter* incoming packets based on the listen socket's interface. This means a DHT associated with a `listen_socket_t` will only receive packets from that socket (and hence only work for that socket). This is how we avoid having a DHT node be accessible from multiple IPs. We'll still run multiple node instances, but only one (likely) will work.

This solves the DHT problem (for IPv6) but instead causes the problem of bittorrent not being accessible over loopback (`[::1]`), because we don't expand to loopback devices.

The same problem exists for IPv4, but there we don't expand the unspecified address, which means we have the opposite problem. We *are* accessible over loopback, but the DHT node can possibly be accessible via multiple different external IPs.

If we can solve this problem, I think we can also treat IPv4 and IPv6 the same.

One possible solution would be to allow `listen_socket_t` to bind to the unspecified address ('[::]'). The DHT code can see if its socket is associated with the unspecified address and in that case, filter any packets that doesn't originate from the corresponding default route device.

**Comment by ssiloti** [comment]
I was under the impression that binding a socket caused the specified address to be used as the source address in outgoing packets. A quick google search [reveals](http://linux-ip.net/html/routing-saddr-selection.html) I am at least not alone in this belief. Given that, multiple DHT nodes should work as intended with the current code.

Filtering incoming packets based on interface isn't a complete solution because there can be multiple routable addresses on the same interface. This is a relatively common scenario with IPv6. A complete solution needs to discriminate based on local addresses.

I don't think we can support loopback in the default configuration without special casing it. We would need to add logic to prevent IPv4 activity (announces, uTP connections, DHT nodes) on loopback unless the destination is also on loopback. In the grand scheme of things this isn't all that horrible, just a couple of one-liners.

**Comment by arvidn** [comment]
> Filtering incoming packets based on interface isn't a complete solution because there can be multiple routable addresses on the same interface. This is a relatively common scenario with IPv6. A complete solution needs to discriminate based on local addresses.

Ah, yes. I was not careful in my phrasing.  that's what I meant and what is done today by `session_impl::verify_incoming_interface()`

> If we are going to expand 0.0.0.0, I don't think we can support loopback in the default configuration without special casing it. We would need to add logic to prevent IPv4 activity (announces, uTP connections, DHT nodes) on loopback unless the destination is also on loopback. In the grand scheme of things this isn't all that horrible, just a couple of one-liners.

Right. And we have this problem with IPv6 today.

**Comment by arvidn** [comment]
a small step to not run DHT nodes on loopback: https://github.com/arvidn/libtorrent/pull/4220/files

**Comment by arvidn** [comment]
I'm having a hard time wrapping my head around all the aspects of this problem. I'm starting to think that loopback *has* to be considered a special case.

One fundamental conflict (I think) is:

* in order for the source IP address of a connection or UDP packet, the socket has to be bound to the specific IP address.
* one expects to reach the application over loopback (normally), especially of one configures it to listen to the unspecified address

Perhaps the loopback address could be treated as a special case, where it's not used for any service or outgoing packet or connection. However, any incoming packet over loopback would be forwarded to one of the devices with the same address family.

**Comment by arvidn** [comment]
on the other hand, it seems legitimate to run a whole swarm, trackers and a DHT network on `127.0.0.1/8`.

**Comment by arvidn** [comment]
Maybe allowing unspecified listen addresses, but filter all incoming packets to such `listen_socket_t` to only allow packets and connection where the *destination address* matches the local address for the interface of the default route, or the loopback address.

In fact, it could be treated as if it was actually bound to that IP (i.e. set `listen_socket_t::local_endpoint`) to the default-route-IP. Even though the socket is bound to an unspecified address.

**Comment by ssiloti** [comment]
I'm not a fan of binding to the unspecified address and filtering incoming packets. That's going to result in odd behavior in cases where outgoing packets don't all use the same source address.

It seems to me that `127.0.0.0/8` and `[::1]` should be treated as if they have their own scope ID (as in IPv6 scopes). We'd need to replace all comparisons of addresses by IP version/scope ID with a call to a function which implements special handling for loopback. This way loopback traffic would be segregated from all other traffic in the same way traffic on a link-local IPv6 address is segregated. One downside is there'd be two unused DHT nodes on loopback in every production client. I'm not sure how big of a deal that would be. Maybe a setting to enable/disable DHT on loopback?

**Comment by arvidn** [comment]
my understanding is that the routing table has hints of which source address to use for different routes, so the OS will use a consistent source as long as it's sending to the same network. I also think this source can be known, by looking at the routing table (and maybe enumerate network interfaces).

But wouldn't it be a problem to run separate DHTs for loopback? I would expect that pinging a libtorrent instance with the DHT enabled over loopback would reach a "real" DHT node, and return real data. With a separate DHT node for loopback, it would be empty. Maybe my mental model is poor for this, and maybe it's not a widespread model, but in a way, I see `127.0.0.1` (or `localhost`) as an alias for whatever my real IP is, but I don't want to jump through the hoops of actually finding out what it is.

I'm also hoping there's a way to use the `listen_socket_t` for outgoing uTP conections, to avoid needing a separate list of outgoing sockets. (both for port-mapping and SOCKS tunnel purposes). I don't think it's important to bind `listen_socket_t` to the unspecified address for that though, as we can know which socket we need to use depending on the destination address.

**Comment by arvidn** [comment]
btw, what's the use case of expanding `::` to all IPv6 addresses? I imagine the main use case is that if you have multiple NICs and multiple paths to the internet, you want to be available via both to maximize bandwidth. So it probably would be sufficient to listen to one IP per device/NIC. If we go with your idea of expanding IPv6 to all addresses only on the "main device" (i.e. the one associated with the default path), does it even still make sense to expand? (as opposed to just "resolve" `::` into the one IP associated with the default path).

the8472 pointed "IPv6 privacy extension", which I don't really know anything about (yet), but it sounds like one may have multiple IP addresses on the same NIC, for privacy reasons. In which case binding to all of the is *not* what one would want.

**Comment by ssiloti** [comment]
Yes, listening on all interfaces is about making full use of multi-homed systems.

The problem with only listening on a single address per interface is that there is no rule that says all addresses must be equally valid. The OS could have any manner of non-trivial routing schemes and AFAIK there's no standard way of asking the OS what the "most preferred" address is for a given interface. In practice picking the first enumerated address for each interface will probably work for the vast majority of configurations, but the pendant in me doesn't like this.

IPv6 privacy addresses are generated randomly as opposed to statically based on the NIC's MAC address. A system implementing the extension will have the standard MAC based address and one-or-more privacy addresses. A new privacy address is generated periodically and the old one is marked as non-preferred. We can certainly make it a policy to not listen on the regular address if there is a preferred privacy address available on the same interface, it's just more logic in `expand_unspecified_address`.

**Comment by arvidn** [comment]
I imagine the true multi-homed use case (where there are multiple NICs and multiple paths to the internet) is quite rare. I think it's fine if that case requires explicit configuration of which addresses to listen on, and that the common case should work as expected by default.

I would expect some of this logic would be "for free" by binding to the unspecified address, as more decisions are left to the OS. I suppose that's part of the risk as well, if you *do* have the privacy extension, your *one* IPv6 DHT may be accessible over multiple IPs.

regarding source address selection, I think you're right, but there have been some attempts to standardize it. I found this: https://tools.ietf.org/html/rfc3484#section-5

**Comment by arvidn** [comment]
This is my current plan:

* associate a flag with each `listen_socket_t` to indicate whether its local address is represents an external network with a *gateway*. I do this by finding the device it's associated with, and the see if there's a default route, with a gateway configured that use this device to exit. This is a bit inaccurate for sophisticated network setups and could be improved. I think it's good enough for 99.9% of all setups though.
* add a netmask to each `listen_socket_t` to contain the mask indicating the size of the local network for the specified address. If there's no gateway configured, the `listen_socket_t` is considered to only be able to route to *internal* addresses.
* enable `expand_unspecified_address` to also expand loopback

This means one could ask a `listen_socket_t` object: "Can you route to address X?". It can tell by checking:

* is the address family of X incompatible with the local address: NO
* is X the same as the local address: YES
* do I have a gateway: YES
* considering the local address and netmask, is X within the local network: YES
* otherwise: NO

For example, my "internet IP", say: 192.168.1.2 has a gateway, so it can route to any IPv4 address. Which means if I run a tracker on localhost (127.0.0.1), both my loopback *and* my "internet IP" can route to it, and I will announce both. I think this is the correct behavior.

Then:

* Pass a `listen_socket_handle` to `udp_socket`, which in turn passes it on to the `socks5` object, if it attempts to open a SOCKS5 tunnel. Never open a SOCKS5 tunnel using a proxy the `listen_socket_t` cannot route to.
* pass it on to trackers via `tracker_req` (this is already done today). Never announce to a tracker the `listen_socket_t` cannot route to.
* pass it on to natpmp and upnp objects to have them restrict to the network they are associated with. (I think today both UPnP and NAT-PMP send a bunch of duplicate requests, just because they aren't constrained to the network/listen_socket_t they belong to).

Does that make sense?

The things missing still are:

* can 0.0.0.0 also be expanded the same way with this logic?
* To avoid binding to the regular device when using a VPN, the logic we previously mentioned of picking the "main" device and only expand addresses on that one should probably be implemented as well.

I'm also a little bit worried about enumerating the route and interfaces/devices/adapters must work correctly for even the most trivial setup to work. If either cannot be enumerated, things will fail. The code to enumerate the routes and interfaces is non-trivial and highly OS dependent, which makes me worried about portability and supporting of odd systems. This is partly why I like the idea of allowing binding to the unspecified addresses, because then the OS will just figure it out, and it would be fewer moving parts in libtorrent that would have to work. It's not obvious to me how to combine this with good support for multi-homing though.

For instance, right now there's a `#warning` if `enum_net_interfaces()` doesn't know what to do. That should probably be an `#error` now. Previously `enum_net_interfaces()` and `enum_routes()` were only used for UPnP and NAT-PMP (iirc), which aren't critical for basic functionality.

**Comment by arvidn** [comment]
I'm also wondering if it makes sense to split out the DHT nodes to make them a member of `listen_socket_t`, but maybe they need to share state.

One suspicious thing right now is that when the DHT receives an incoming packet (`dht_tracker::incoming_packet()`), it's forwarded to all nodes, and only looking at the socket it arrived on in case it's a request. This leads to, for example, associating the external IP address arriving in DHT packets to all `listen_socket_t`. I think this is easy to fix, but I'm getting the impression it would simplify things to split out the DHT nodes to be members of `listen_socket_t` instead.

It has been my experience so far that splitting out `lsd` and `upnp` to only operate on a single network and make them members of `listen_socket_t` simplifies things.

**Comment by arvidn** [comment]
I have a machine with 14 IP interfaces, it has a special configuration with access to a bunch of different external IPv4 addresses. Even though it only has a single route (from one of the NICs), we end up constructing 14 DHT nodes. Now, one might think this is not that big of a deal, only one will be used in practice. However, what ends up happening is that *every* DHT packet is fed to *every* DHT node. So, even though only one can be used for DHT *queries*, every single node maintains the same (essentially) routing table. This was so slow (it may not have been a release build) that the whole client came to a craw.

So, I'm thinking that maybe it would be best to limit DHT nodes to only interfaces that have a gateway associated with them. @ssiloti what do you think? can you think of any issues with that?
It would mean not being able to reach a DHT over loopback.

Maybe it shouldn't apply when explicitly configuring `listen_interfaces`, but just when they were expanded.

**Comment by ssiloti** [comment]
Agreed. I don't think it makes much sense to start a DHT node on an interface which does not have a gateway, except maybe loopback for testing.

**Comment by arvidn** [comment]
alright. https://github.com/arvidn/libtorrent/pull/4275

**Comment by arvidn** [comment]
I think all of this has been resolved in `RC_1_2` now.
