### ISSUE TITLE
file_pool.hpp? warning?

### ISSUE THREAD

**Issue by zbooa** [arvidn/libtorrent#4221]
boost-1.69.0, libtorrent-rasterbar-1.2.3
windows 10 x64    vs2015
Boost is the official installation version, not self compiled
this boost_1_69_0-msvc-14.0-64.exe 
Libtorrent compiled by b2
`b2 toolset=msvc link=shared runtime-link=shared dht=on extensions=on variant=debug address-model=64 --debug-building --build-dir=.\debug\out64 -j4 > .\buildout_debug_64.txt`
Success, no errors or warnings. Generate torrent.lib and torrent.dll.
@@@@@
Here, The test has problems!
Compile the client_test on vs2015，It is working. Can download, Can see the details. 
This is my macro
`BOOST_ALL_NO_LIB 
BOOST_ASIO_ENABLE_CANCELIO 
BOOST_ASIO_HAS_STD_CHRONO 
BOOST_MULTI_INDEX_DISABLE_SERIALIZATION  
BOOST_SYSTEM_DYN_LINK=1 
BOOST_SYSTEM_NO_DEPRECATED 
TORRENT_LINKING_SHARED
TORRENT_USE_I2P=1 
WIN32 
WIN32_LEAN_AND_MEAN 
_CRT_SECURE_NO_DEPRECATE 
_FILE_OFFSET_BITS=64 
_SCL_SECURE_NO_DEPRECATE 
_WIN32 
_WIN32_WINNT=0x0600 
__USE_W32_SOCKETS`
But 
There are some warnings during compilation
`1> D:\vs\libtorrent-rasterbar-1.2.3\include\libtorrent\file_pool.hpp (57): warning c4275: non dll interface class "boost:: noncopyable_::noncopyable" is used as the base of DLL interface struct "libtorrent::file_pool"
1> D:\vs\boost_1_69_0\boost\core\noncopyable.hpp (38): Note: see the declaration of "boost:: noncopyable_::noncopyable"
1> D:\vs\libtorrent-rasterbar-1.2.3\include\libtorrent\file_pool.hpp (56): Note: see the declaration of "libtorrent::file_pool"
1> D:\vs\libtorrent-rasterbar-1.2.3\include\libtorrent\session_handle.hpp (830): warning c4996: 'libtorrent::pe_settings': declared as deprecated
1> D:\vs\libtorrent-rasterbar-1.2.3\include\libtorrent\session_settings.hpp (54): Note: see the declaration of "libtorrent::pe_settings"
1> D:\vs\libtorrent-rasterbar-1.2.3\include\libtorrent\session_handle.hpp (832): warning c4996: 'libtorrent::pe_settings': declared as deprecated
1> D:\vs\libtorrent-rasterbar-1.2.3\include\libtorrent\session_settings.hpp (54): Note: see the declaration of "libtorrent::pe_settings"`
What is it? I try 1.2.0 , the same one. Tell me how fix this?

**Comment by arvidn** [comment]
My understanding of this warning is; if you export a class from a shared library, all of its member functions are implicitly exported, if you derive from a class that isn't exported from the library, the client using that class may not be able to reach member functions from the base class.

What this warning doesn't realize is that `boost::non_copyable` doesn't have any member functions, so in practice this isn't a problem. It would probably make sense to transition away from using `boost::non_copyale` in favour of just deleting the special member functions. I just suppress these warnings though.

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/4238
