### ISSUE TITLE
How to determine the compilation macro？

### ISSUE THREAD

**Issue by zbooa** [arvidn/libtorrent#4222]
Many <define> are printed out by the command "b2 toolset=msvc --debug-building". Which is used in vs?
There is <define> for compiling every file. Compiling samples in vs needs the same <define> as compiling libtorrent. How do you confirm? Here is my <define> for. torrent at compile time, but in the examples, the compilation fails.

> <define>BOOST_ALL_NO_LIB <define>BOOST_ASIO_ENABLE_CANCELIO <define>BOOST_ASIO_HAS_STD_CHRONO <define>BOOST_MULTI_INDEX_DISABLE_SERIALIZATION <define>BOOST_NO_DEPRECATED <define>BOOST_SYSTEM_NO_DEPRECATED <define>BOOST_SYSTEM_SOURCE <define>TORRENT_BUILDING_LIBRARY <define>TORRENT_BUILDING_SHARED <define>TORRENT_USE_I2P=1 <define>WIN32 <define>WIN32_LEAN_AND_MEAN <define>_CRT_SECURE_NO_DEPRECATE <define>_FILE_OFFSET_BITS=64 <define>_SCL_SECURE_NO_DEPRECATE <define>_WIN32 <define>_WIN32_WINNT=0x0600 <define>__USE_W32_SOCKETS

**Comment by arvidn** [comment]
I think the simplest way is to run `b2 -an`. This won't build anything, but will print all the commands as if it was building from scratch.

Windows, having a really short limit on command lines, the build system can't really invoke `cl.exe` with all the options on the command line, but instead use response files, so all the options are put in a file, ending in `.rsp`. you can open one of those files to see the actual options. The name of the response file should show up in the output from `b2 -an`

**Comment by zbooa** [comment]
> I think the simplest way is to run `b2 -an`. This won't build anything, but will print all the commands as if it was building from scratch.
> 
> Windows, having a really short limit on command lines, the build system can't really invoke `cl.exe` with all the options on the command line, but instead use response files, so all the options are put in a file, ending in `.rsp`. you can open one of those files to see the actual options. The name of the response file should show up in the output from `b2 -an`

I use b2 -an, and I saw the macro.
Through comparison, I found that the following three cannot be used in vs, but this is in <define> when generating the torrent.lib file through b2, but it cannot be used when compiling the demo in vs. It is normal to delete it. I Think <define> should not correspond.
`BOOST_SYSTEM_SOURCE
TORRENT_BUILDING_LIBRARY
TORRENT_BUILDING_SHARED`
