### ISSUE TITLE
Get different infohash at libtorrent and bencode

### ISSUE THREAD

**Issue by lysssssss** [arvidn/libtorrent#4230]
**Please provide the following information**

libtorrent version (or branch):1.2.3

platform/architecture:python

compiler and compiler version:MSVC14.0

Hi. I meet a problem with info hash calculation. if the torrent info has a custom key and inserts in the info dictionary (not the end), then it will get different info hash between libtorrent and bencode.

For example:
A torrent struct, like below:
![image](https://user-images.githubusercontent.com/15572021/71891930-a7444480-3182-11ea-8269-be1b05cebb4b.png)
libtorrent infohash and bencode infohash are different.

Then I swap 'source' and 'ttg_tag' key sequence(like below), it will get the same infohash at libtorrent and bencode.
![image](https://user-images.githubusercontent.com/15572021/71891680-1a998680-3182-11ea-9be7-c4bfec4551d1.png)

Python code parse here:
```
    print('original file')
    print('libtorrent:' + str(libtorrent.torrent_info('original.torrent').info_hash()))
    mangetlink = magneturi.from_torrent_data(open('original.torrent', 'rb').read())
    mangetlink = mangetlink[mangetlink.find('btih') + 5:mangetlink.find('btih') + 5 + 32]
    b16Hash = base64.b16encode(base64.b32decode(mangetlink))
    b16Hash = b16Hash.lower()
    b16Hash = str(b16Hash, "utf-8")
    print('bencode:' + b16Hash)

    print('update file')
    print('libtorrent:' + str(libtorrent.torrent_info('new.torrent').info_hash()))
    mangetlink = magneturi.from_torrent_data(open('new.torrent', 'rb').read())
    mangetlink = mangetlink[mangetlink.find('btih') + 5:mangetlink.find('btih') + 5 + 32]
    b16Hash = base64.b16encode(base64.b32decode(mangetlink))
    b16Hash = b16Hash.lower()
    b16Hash = str(b16Hash, "utf-8")
    print('bencode:' + b16Hash)
```
And here is the result:
```
original file
libtorrent:e78497d80ac16b34bc33ddd527a1a53ce1158925
bencode:3c1132fe4f86f6e23fad27505d4396550f672145
update file
libtorrent:3c1132fe4f86f6e23fad27505d4396550f672145
bencode:3c1132fe4f86f6e23fad27505d4396550f672145
```

Best regards!

**Comment by arvidn** [comment]
I don't know what "bencode" refers to in your ticket, but my suspicion is that it decodes and then re-encodes the info-dictionary, which may re-order some fields that were incorrectly ordered in the original torrent file. The bittorrent specification was clarified a few years ago that info-hashes should be computed on the verbatim info dictionary, not a re-encoded one.

**Comment by lysssssss** [comment]
> I don't know what "bencode" refers to in your ticket, but my suspicion is that it decodes and then re-encodes the info-dictionary, which may re-order some fields that were incorrectly ordered in the original torrent file. The bittorrent specification was clarified a few years ago that info-hashes should be computed on the verbatim info dictionary, not a re-encoded one.

The reason of first decode and then encode is the magnet link is 16 bytes hash string, not 20 bytes string, so I need to re-encode.
And I have used a torrent application, it also shows 3c1132fe4f86f6e23fad27505d4396550f672145  that whether the torrent file has modified.

**Comment by arvidn** [comment]
> The reason of first decode and then encode is the magnet link is 16 bytes hash string, not 20 bytes string, so I need to re-encode.

you mean you have a base32 inf-hash and you want hex? For that you just need to re-encode the *info-hash* itself. Perhaps I'm misunderstanding something.

> And I have used a torrent application, it also shows 3c1132fe4f86f6e23fad27505d4396550f672145 that whether the torrent file has modified.

Maybe I'm misunderstanding the problem. When you add the new field, clearly the info-hash will change. I think I lost what your argument is here. Could you please clarify? Are you suggesting that the original file has all its info-dict keys correctly ordered?

**Comment by arvidn** [comment]
search for "info_hash" here: http://bittorrent.org/beps/bep_0003.html

**Comment by lysssssss** [comment]
> > The reason of first decode and then encode is the magnet link is 16 bytes hash string, not 20 bytes string, so I need to re-encode.
> 
> you mean you have a base32 inf-hash and you want hex? For that you just need to re-encode the _info-hash_ itself. Perhaps I'm misunderstanding something.
> 
Yes, actually I need base40 infohash convert to hex, so I need base32 transform to base 40 first.
> > And I have used a torrent application, it also shows 3c1132fe4f86f6e23fad27505d4396550f672145 that whether the torrent file has modified.
> 
> Maybe I'm misunderstanding the problem. When you add the new field, clearly the info-hash will change. I think I lost what your argument is here. Could you please clarify? Are you suggesting that the original file has all its info-dict keys correctly ordered?

Okay, I think that there is something wrong in libtorrent infohash calculation when torrent info-dict is not correctly ordered.
And actually, this torrent wasn't created by myself. I downloaded it from somewhere. I find a little amount of torrent will have this problem.
Thank you for your patience。:)

**Comment by lysssssss** [comment]
In total, in all my have try, if the torrent info-dict is not correctly ordered, libtorrent infohash result will be different by others way that I have tried.
Maybe I have some mistake, If I am wrong, please correct me.:)

**Comment by arvidn** [comment]
> In total, in all my have try, if the torrent info-dict is not correctly ordered, libtorrent infohash result will be different by others way that I have tried.
> Maybe I have some mistake, If I am wrong, please correct me.:)

If those other ways you've tried include decoding and re-encoding, they yes, you're not doing it right. please take a look at the specification (linked above).

The history is that popular implementations (starting with uTorrent) would *accept* incorrectly encoded torrent files, whereas some implementations might reject them and others would calculate a different info-hash.

If we could go back in time, we would probably want to specify that invalid torrents must be rejected by implementations. But, it is what it is, and the most reasonable (cheapest) behavior for calculating the info-hash is to not require a re-encoding, which means defining it as the hash of the verbatim original info-dict, as encoded.

I think rejecting such torrents is also a totally reasonable behavior, it's just that since uTorrent and most other major implementations accept them with the behavior specified in BEP 3, users may complain if you do so.

**Comment by lysssssss** [comment]
> > In total, in all my have try, if the torrent info-dict is not correctly ordered, libtorrent infohash result will be different by others way that I have tried.
> > Maybe I have some mistake, If I am wrong, please correct me.:)
> 
> If those other ways you've tried include decoding and re-encoding, they yes, you're not doing it right. please take a look at the specification (linked above).
> 
> The history is that popular implementations (starting with uTorrent) would _accept_ incorrectly encoded torrent files, whereas some implementations might reject them and others would calculate a different info-hash.
> 
> If we could go back in time, we would probably want to specify that invalid torrents must be rejected by implementations. But, it is what it is, and the most reasonable (cheapest) behavior for calculating the info-hash is to not require a re-encoding, which means defining it as the hash of the verbatim original info-dict, as encoded.
> 
> I think rejecting such torrents is also a totally reasonable behavior, it's just that since uTorrent and most other major implementations accept them with the behavior specified in BEP 3, users may complain if you do so.

haha. Thank for your patience explain. Now I clearly know why libtorrent has different result, I agree with your opinion. That's a developer must insist.
Thanks again.
