### ISSUE TITLE
Query regarding SSL announce

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4237]
**Please provide the following information**

libtorrent version (or branch):
1.2.3
platform/architecture:

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Let’s say I have 500 torrents with the same SSL tracker and I just started my client. Libtorrent makes asynchronous announces for all of those torrents. Now my question is, does libtorrent use the same session/handshake to perform all these announces? Does it take advantage of cached sessions? Or it tries to do 500 asynchronous ssl handshakes to the same server? Asking this cause it seems like libtorrent is kinda slow when it comes to announcing to SSL trackers. Maybe this requires some optimisation.

**Comment by arvidn** [comment]
it makes 500 independent connections with individual SSL handshakes. There is definitely room for improvements.

**Comment by an0n666** [comment]
> it makes 500 independent connections with individual SSL handshakes. There is definitely room for improvements.

For the same tracker it could reuse the session for all announces. It would save a lot of round trips. As a handshake adds atleast 3 roundtrips for each announce.

**Comment by arvidn** [comment]
for sure. I would expect the SSL handshake itself to be by far the most expensive part of it though

**Comment by an0n666** [comment]
> for sure. I would expect the SSL handshake itself to be by far the most expensive part of it though

Yep! The handshake usually takes 250-500 ms! It’s the most expensive part of any bittorrent announces to a SSL tracker.

**Comment by an0n666** [comment]
> for sure. I would expect the SSL handshake itself to be by far the most expensive part of it though

The connect could be kept alive and reused for all the announces for that tracker? That would eliminate the need for a full handshake. Or you could use abbreviated handshake.

**Comment by arvidn** [comment]
yes, that could be done. That's what I meant by "There is definitely room for improvements."

**Comment by an0n666** [comment]
> yes, that could be done. That's what I meant by "There is definitely room for improvements."

Just to add, I think the same applies for Non-SSL trackers as well..Running 100s of independent connections for the same tracker on occassions like startup / shutdown is too expensive. libtorrent could adapt to an independent connection "per tracker" model for this perhaps.

**Comment by arvidn** [comment]
let's merge this ticket with https://github.com/arvidn/libtorrent/issues/4334
