### ISSUE TITLE
confused about ed2k metadata

### ISSUE THREAD

**Issue by bosskwei** [arvidn/libtorrent#4260]
Hi guys,
bep_0003 defined a torrent file (or metadata) like this:
```python
 {
     'announce': 'http://tracker.site1.com/announce',
     'info':
     {
         'name': 'directoryName',
         'piece length': 262144,
         'files':
         [
             {'path': ['111.txt'], 'length': 111},
             {'path': ['222.txt'], 'length': 222}
         ],
         'pieces': <binary SHA1 hashes>
     }
 }
```

but ed2k metadata:
```python
{
    'ed2k': '\xd6K\x94\xeeI\xde\x02d0\xc3\x8da\x00\xac\xdc\x98'
    'length': 1912818293
    'name': 'a.mp4',
    'name.utf-8': 'a.mp4'
}
```

ed2k metadata format is different to others, is this spec allowed (I can not find any spec to the ed2k format)?

**Comment by ssiloti** [comment]
Ed2k and is a completely different protocol than bittorrent. Metadata is not compatible between ed2k and bittorrent. You'll have to ask somewhere else about ed2k.

**Comment by bosskwei** [comment]
Thanks @ssiloti , I mentioned ed2k here because` h.get_torrent_info().metadata()` could return an ed2k metadata.

I'm really confused about this, ed2k as a different protocol but compatible with dht protocol, is this right?
What I'm doing is trying to implement a high performance dht server, and I don't know if bittorrent and ed2k share the same dht network.
If I implement a dht server for bittorrent, it also work ok for ed2k, is this right?

**Comment by ssiloti** [comment]
I'm not sure where you got the idea that `get_torrent_info().metadata()` could return ed2k metadata. It cannot. The bittorrent and ed2k DHTs are separate networks which are not compatible.

**Comment by bosskwei** [comment]
@ssiloti My wrong, I think I understand the problem. Some (really old) torrent like this:
```Python
{
    'ed2k': '\xd6K\x94\xeeI\xde\x02d0\xc3\x8da\x00\xac\xdc\x98'
    'length': 1912818293
    'name': 'a.mp4',
    'name.utf-8': 'a.mp4'
}
```
It's a real bittorrent metadata, but a 16-byte MD4 hash (ed2k infohash) was written to `ed2k` key, this maybe because the creator or legacy ed2k software use it to trace same file in different distribute networks.

**Comment by ivan386** [comment]
@bosskwei Shareaza use ed2k, md5sum, tiger (it is TTH) to find alternative sources in other p2p networks.
