### ISSUE TITLE
Help: Libtorrent in C# by C++/CLI wrapper

### ISSUE THREAD

**Issue by tlostak** [arvidn/libtorrent#4274]
Hello,

I would like to build own torrent client based on **C# WPF**.
That means, I want to use the libtorrent library, but I have some issues.

I found out I can use C++/CLI wrapper for access to the libtorrent library in my C# project.
**C# (WPF app) -> C++/CLI (wrapper) -> C++ (libtorrent)**

I successfully made a wrapper project linked with a static library built by b2.
Everything works fine -> From C# code I can access wrapper which can access the library.

But this works only for basic calls, 
e.g. I can call from wrapper lt::version() when I included #include "libtorrent/version.hpp"

**Wrapper Code: _(libtorrent.lib + include folders linked)_**

```
#include <libtorrent/version.hpp>
//#include <libtorrent/session.hpp> Will ocurr error
namespace CLI
{
    // Wrapping class
    public ref class Wrapper
    {
    public:
        String^ version()
        {
            return gcnew String(lt::version());
        }
    };
}
```

**C# Code:**

```
using CLI;
namespace Sandbox
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(new Wrapper().version());
        }
    }
}
```

When I use something more complex in my wrapper, e.g. lt::session from #include <libtorrent/session.hpp>
I get many errors, because C++/CLI doest support "c++ native" featues like mutex, threads etc.

e.g. error
#error directive: <condition_variable> is not supported when compiling with /clr or /clr:pure.

**How can I use the libtorrent library in C# project? Is it even possible?**
Can I use something different than C++/CLI?

I try to make this works for many days.
Thank you for the information.

Technical details:
libtorrent-1.2.3
boost-1.72.0
Visual studio 2015 / 2019 (tried both / different machines)
msvc
Windows 10

**Comment by ghbplayer** [comment]
You have to be thoughtful about how you design your abstraction. If some essential features aren't supported by C++/CLI then you'll need a C++ layer as well as C++/CLI and C# layers. The more complicated the interface you expose to C# the more complicated your project will be. If you don't know C++ at all, this could be a very difficult project for you.

I advise you put most of the business logic in C++ and expose a limited set of simple API functions to C# via C++/CLR. Do the GUI in C# and the real work in C++ where it's easier to access all the libtorrent details.

**Comment by arvidn** [comment]
that sounds right. The alternative would be to wrap libtorrent with a "simpler" API (really, something with some type erasure) that can be accessed from C++/CLI.

There's an old attempt to build C-bindings for libtorrent. They are terribly outdated though, and might not help you as they still use C-features like variadic functions.

**Comment by tlostak** [comment]
I see. I will consider all the options that you mentioned, thank you.
_(I will let this open for a day, maybe someone will have an idea too and then I will close It)_

**Comment by olegsavelos** [comment]
I am having similar issue, @tlostak have you found a solution for this ?
