### ISSUE TITLE
Proper way to shutdown torrent session

### ISSUE THREAD

**Issue by fmike7** [arvidn/libtorrent#4284]
Synopsis: Running into some very rare issue, which is difficult to reproduce. Once in a while, my application hangs inside session::~session when trying to properly close the session at application exit.

Details: I am using direct the destructor method (without calling abort() to get session_proxy) and inside there it gets stuck on m_thread->join() waiting for other threads to finish the execution. I tried experimenting with stop_tracker_timeout parameter setting it to low values like 5 seconds, but it still hangs. Sometimes it completes, taking 20-30 minutes. Somehow this might be related to computer going to sleep and/or temporary loss of network connections, such as when you disconnect from WiFi and then reconnect back and then try to shut it down.

I wonder if I am not using it properly or something is wrong with multi-threading. I create the session object and destroy it in the same main thread, but receive alerts (session::pop_alerts) and save resume data in the worker thread. The main thread also calls async_add_torrent when a new torrent is added or resumed from prior sessions. The main thread waits for the worker thread finishes before I call ~session() from the main thread, to make sure the session is not destroyed during any active worker operations.

Should I call remove_torrent() for each torrent before shutting it down? Or maybe pause() for the whole session and then terminate? Any insight would be highly appreciated. In the meantime I am trying to reproduce it and understand the exact conditions leading to it. But as I said, it happens rarely, making it difficult to catch.

Version: libtorrent 1.2.1 stable/boost 1.69/multithreaded/statically linked
Platform: Windows 8.1 / 32 bit
Compiler: Visual Studio 2017

P.S. On the other hand, this library has been a LIFESAVER for me! Thank you so much for creating and maintaining it.

**Comment by ghbplayer** [comment]
Your threading model sounds right, so long as you're not using native_handle() like I did. If you're not using a debug build with asserts, do that. The key is figuring out what the threads are doing, or what they're waiting for.

I pause torrents before destroying the session, but I don't know if it's required.

**Comment by fmike7** [comment]
No, I am not using native_handle() anywhere. I will try reproducing this on debug version with asserts and will keep digging into it. If I am able catch the situation again I will post call stacks of those waiting libtorrent worker threads, maybe that will shed some light into it.

I also have a feeling that it's probably a good idea to call pause() before destroying it, but at the same time given the asynchronous nature of libtorrent this may not help. Should you wait until they are actually paused (poll for "paused" alert?) But again, these are non-educated guesses of mine...

Anyway, any "official" guidance on the pre-steps before destroying the session object would be greatly appreciated while I am trying to reproduce this.

**Comment by MassaRoddel** [comment]
Do you have torrents with many not working trackers?

**Comment by arvidn** [comment]
@fmike7 Try building with `asio-debugging=on` (if building with `b2`) or defining `TORRENT_ASIO_DEBUGGING`.

Normally when this happens it's because some asynchronous operation is either taking a long time (and could not be cancelled) or there's a bug where some asynchronous operation is not correctly cancelled.

This will build configuration will keep a record of all outstanding async operations and, on shutdown, print to `stdout` all the async operations it's waiting for to finish.

Please report back what you find!

**Comment by fmike7** [comment]
> Do you have torrents with many not working trackers?
> Can you confirm that it only happens if there were/are torrents in the session?

Yes, it look like it happens only when there are torrent in the session. There is only one tracker in this scenario and it's almost always online.

**Comment by fmike7** [comment]
> @fmike7 Try building with `asio-debugging=on` (if building with `b2`) or defining `TORRENT_ASIO_DEBUGGING`.
> 
> Normally when this happens it's because some asynchronous operation is either taking a long time (and could not be cancelled) or there's a bug where some asynchronous operation is not correctly cancelled.
> 
> This will build configuration will keep a record of all outstanding async operations and, on shutdown, print to `stdout` all the async operations it's waiting for to finish.
> 
> Please report back what you find!

Ok, will do and post here as soon as I am able to reproduce.

But as far as any "pre-closing" steps there are really none, correct? No need to call remove_torrent or pause. I can just destroy the session anytime I want and it should shutdown everything properly. Right?

**Comment by arvidn** [comment]
> But as far as any "pre-closing" steps there are really none, correct? No need to call remove_torrent or pause. I can just destroy the session anytime I want and it should shutdown everything properly. Right?

That's correct

**Comment by fmike7** [comment]
Here is an interesting finding which helped me solve the issue. It turned out that this hanging was somehow related to handle inheritance by child processes. My main process is using libtorrent and it was starting a child process with handle inheritance. I rewrote the logic so the child process doesn’t require handle inheritance and libtorrent in the main process now shuts down quickly and properly.

My guess is libtorrent somehow relies on certain handles to be closed before it can shutdown. If the handles are inherited and the child process doesn’t exit (so the system keeps all the handles open), this causes this endless wait when it shuts down. 

Any chance my theory is correct?

**Comment by arvidn** [comment]
That sounds quite plausible. libtorrent closes both file handles and sockets and expect outstanding async operations to be cancelled.

**Comment by MassaRoddel** [comment]
I don't think that is correct unless you would actually use libtorrents internal handles somethere in your child process.

**Comment by fmike7** [comment]
> I don't think that is correct unless you would actually use libtorrents internal handles somethere in your child process

The child process doesn’t use any libtorrent functionality, but it does link with libtorrent statically (it’s essentially the same EXE as the main process). Does libtorrent use any global variables that have initializers or constructors that might use those handles and cause the issue?

Anyway, creating child process without handle inheritance does solve the issue, so it’s a good workaround in case someone ever runs into this issue.
