### ISSUE TITLE
peer_connection::send_suggest assert

### ISSUE THREAD

**Issue by whittmy** [arvidn/libtorrent#4289]
**Please provide the following information**

libtorrent version (or branch):
     -version: 1.2.2.0-b2c3b4dbf
platform/architecture:
    -ubuntu16
    - default address-model    : 64-bit (cached)
    - default architecture     : x86 (cached)
    - lockfree boost::atomic_flag : yes (cached)
    - lockfree boost::atomic_flag : yes (cached)

compiler and compiler version:
     - gcc-7.0

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

file: '../src/peer_connection.cpp'
line: 3899
function: send_suggest
expression: t->has_piece_passed(piece)

stack:
1: libtorrent::assert_fail(char const*, int, char const*, char const*, char const*, int)
2: libtorrent::peer_connection::send_suggest(libtorrent::aux::strong_typedef<int, libtorrent::aux::piece_index_tag, void>)
3: libtorrent::peer_connection::send_piece_suggestions(int)
4: libtorrent::peer_connection::send_unchoke()
5: libtorrent::torrent::unchoke_peer(libtorrent::peer_connection&, bool)
6: libtorrent::peer_connection::maybe_unchoke_this_peer()
7: libtorrent::bt_peer_connection::on_receive_impl(unsigned long)
8: libtorrent::bt_peer_connection::on_receive(boost::system::error_code const&, unsigned long)
9: libtorrent::peer_connection::on_receive_data(boost::system::error_code const&, unsigned long)
10: void std::__invoke_impl<void, void (libtorrent::peer_connection::* const&)(boost::system::error_code const&, unsigned long), std::shared_ptr<libtorrent::peer_connection> const&, boost::system::error_code const&, unsigned long>(std::__invoke_memfun_deref, void (libtorrent::peer_connection::* const&)(boost::system::error_code const&, unsigned long), std::shared_ptr<libtorrent::peer_connection> const&, boost::system::error_code const&, unsigned long&&)
11: std::__invoke_result<void (libtorrent::peer_connection::* const&)(boost::system::error_code const&, unsigned long), std::shared_ptr<libtorrent::peer_connection> const&, boost::system::error_code const&, unsigned long>::type std::__invoke<void (libtorrent::peer_connection::* const&)(boost::system::error_code const&, unsigned long), std::shared_ptr<libtorrent::peer_connection> const&, boost::system::error_code const&, unsigned long>(void (libtorrent::peer_connection::* const&)(boost::system::error_code const&, unsigned long), std::shared_ptr<libtorrent::peer_connection> const&, boost::system::error_code const&, unsigned long&&)
12: void std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>::__call_c<void, boost::system::error_code const&, unsigned long&&, 0ul, 1ul, 2ul>(std::tuple<boost::system::error_code const&, unsigned long&&>&&, std::_Index_tuple<0ul, 1ul, 2ul>) const
13: void std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>::operator()<boost::system::error_code const&, unsigned long, void>(boost::system::error_code const&, unsigned long&&) const
14: void libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 400ul>::operator()<boost::system::error_code const&, unsigned long>(boost::system::error_code const&, unsigned long&&) const
15: std::_Function_handler<void (boost::system::error_code const&, unsigned long), libtorrent::aux::allocating_handler<std::_Bind<void (libtorrent::peer_connection::*(std::shared_ptr<libtorrent::peer_connection>, std::_Placeholder<1>, std::_Placeholder<2>))(boost::system::error_code const&, unsigned long)>, 400ul> >::_M_invoke(std::_Any_data const&, boost::system::error_code const&, unsigned long&&)
16: std::function<void (boost::system::error_code const&, unsigned long)>::operator()(boost::system::error_code const&, unsigned long) const
17: void std::__invoke_impl<void, std::function<void (boost::system::error_code const&, unsigned long)>&, boost::system::error_code&, unsigned long&>(std::__invoke_other, std::function<void (boost::system::error_code const&, unsigned long)>&, boost::system::error_code&, unsigned long&)
18: std::__invoke_result<std::function<void (boost::system::error_code const&, unsigned long)>&, boost::system::error_code&, unsigned long&>::type std::__invoke<std::function<void (boost::system::error_code const&, unsigned long)>&, boost::system::error_code&, unsigned long&>(std::function<void (boost::system::error_code const&, unsigned long)>&, boost::system::error_code&, unsigned long&)
19: std::enable_if<std::is_void<void>{}, void>::type std::_Bind_result<void, std::function<void (boost::system::error_code const&, unsigned long)> (boost::system::error_code, unsigned long)>::__call<void, , 0ul, 1ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul>)
20: void std::_Bind_result<void, std::function<void (boost::system::error_code const&, unsigned long)> (boost::system::error_code, unsigned long)>::operator()<>()
21: void boost::asio::asio_handler_invoke<std::_Bind_result<void, std::function<void (boost::system::error_code const&, unsigned long)> (boost::system::error_code, unsigned long)> >(std::_Bind_result<void, std::function<void (boost::system::error_code const&, unsigned long)> (boost::system::error_code, unsigned long)>&, ...)
22: void boost_asio_handler_invoke_helpers::invoke<std::_Bind_result<void, std::function<void (boost::system::error_code const&, unsigned long)> (boost::system::error_code, unsigned long)>, std::_Bind_result<void, std::function<void (boost::system::error_code const&, unsigned long)> (boost::system::error_code, unsigned long)> >(std::_Bind_result<void, std::function<void (boost::system::error_code const&, unsigned long)> (boost::system::error_code, unsigned long)>&, std::_Bind_result<void, std::function<void (boost::system::error_code const&, unsigned long)> (boost::system::error_code, unsigned long)>&)
23: void boost::asio::detail::handler_work<std::_Bind_result<void, std::function<void (boost::system::error_code const&, unsigned long)> (boost::system::error_code, unsigned long)>, boost::asio::system_executor, boost::asio::system_executor>::complete<std::_Bind_result<void, std::function<void (boost::system::error_code const&, unsigned long)> (boost::system::error_code, unsigned long)> >(std::_Bind_result<void, std::function<void (boost::system::error_code const&, unsigned long)> (boost::system::error_code, unsigned long)>&, std::_Bind_result<void, std::function<void (boost::system::error_code const&, unsigned long)> (boost::system::error_code, unsigned long)>&)
24: boost::asio::detail::completion_handler<std::_Bind_result<void, std::function<void (boost::system::error_code const&, unsigned long)> (boost::system::error_code, unsigned long)> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long)
25: boost::asio::detail::scheduler_operation::complete(void*, boost::system::error_code const&, unsigned long)
26: boost::asio::detail::scheduler::do_run_one(boost::asio::detail::conditionally_enabled_mutex::scoped_lock&, boost::asio::detail::scheduler_thread_info&, boost::system::error_code const&)
27: boost::asio::detail::scheduler::run(boost::system::error_code&)
28: boost::asio::io_context::run()
29: ) [0x120ac03]
30: ) [0x120c361]
31: ) [0x120c170]
32: ) [0x120c708]
33: ) [0x120c6c4]
34: ) [0x120c694]
35: 
36: 
37: clone

**Comment by arvidn** [comment]
thanks for the report. it seems the `suggest_read_cache` setting is poorly tested and doesn't actually work right. I will try to fix this for 1.2.4 (with better tests)

**Comment by arvidn** [comment]
I believe this will fix the issue: https://github.com/arvidn/libtorrent/pull/4292

**Comment by arvidn** [comment]
@whittmy do you think you'll have a chance to git that patch a try?
