### ISSUE TITLE
Https tracker and server name indication

### ISSUE THREAD

**Issue by Sorvigolova** [arvidn/libtorrent#429]
Handshake failed with all trackers that used CloudFlare servers with certificates like this one: sniXXXXX.cloudflaressl.com
Server name does not send to host (to https tracker) into the client_hello info.
https://github.com/qbittorrent/qBittorrent/issues/4378

**Comment by ssiloti** [comment]
This seems like a simple fix so I made a quick patch. Could you try https://github.com/ssiloti/libtorrent/tree/set-sni-hostname

**Comment by JSWolf** [comment]
Could we please have libtorrent fixed so it works with https and CloudFlare? This issue is really annoying and it seems like a simple enough fix.

**Comment by arvidn** [comment]
@JSWolf does ssiloti's fix work?

**Comment by JSWolf** [comment]
I won't know until a new version of qBittorrent is released with that version of libtorrent.

**Comment by ssiloti** [comment]
I did a quick check with wireshark and with #431 libtorrent is sending the server_name extension now in the ClientHello so I'm pretty confident it fixes the problem.

**Comment by sledgehammer999** [comment]
@arvidn  this needs closing.

**Comment by Sorvigolova** [comment]
Thank You @ssiloti and @arvidn. Good Job!

**Comment by arvidn** [comment]
I still need to back-port this into RC_1_0. I'll try to remember doing that tonight
