### ISSUE TITLE
Need info regarding peer exchange.

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4291]
libtorrent version (or branch):
1.2.3

Clients that uses libtorrent disables DHT, PeX, LSD on torrents with the private flag. I found the codes where DHT and LSD is disabled in torrent.cpp of libtorrent. But I couldn't find the one for PeX. So does that mean PeX is disabled from the torrent client's side and not within libtorrent? Or did I just miss the code somewhere?

**Comment by arvidn** [comment]
you missed it. It's right [here](https://github.com/arvidn/libtorrent/blob/RC_1_2/src/ut_pex.cpp#L646).

**Comment by an0n666** [comment]
> you missed it. It's right [here](https://github.com/arvidn/libtorrent/blob/RC_1_2/src/ut_pex.cpp#L646).

Thank you!
