### ISSUE TITLE
x86 - file map - boost::system::errc::not_enough_memory

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#4295]
libtorrent version (or branch): master
platform/architecture: Windows x86
compiler and compiler version: VC++2019

![изображение](https://user-images.githubusercontent.com/920705/73557261-f586f380-4461-11ea-8947-6ddddaedd88b.png)

fix

Index: config.hpp
--- config.hpp	(revision 22277)
+++ config.hpp	(working copy)
@@ -273,7 +273,9 @@
 #endif
 
 #ifndef TORRENT_HAVE_MAP_VIEW_OF_FILE
-#define TORRENT_HAVE_MAP_VIEW_OF_FILE 1
+  #ifdef _WIN64
+    #define TORRENT_HAVE_MAP_VIEW_OF_FILE 1
+  #endif 
 #endif

**Comment by arvidn** [comment]
You're building as a 32 bit application, right?
The intention is to use ``posix_disk_io`` for all 32 bit builds. This is not windows specific. Is `_WIN64` a reliably way to check whether pointers are 64bits on windows?
I will need to fix this for all platforms though.

**Comment by pavel-pimenov** [comment]
You're building as a 32 bit application, right?

 (Win-32 ==  error)
 (x64 ==  ok)

help?

**Comment by arvidn** [comment]
I was thinking of something like this: https://github.com/arvidn/libtorrent/pull/4296
