### ISSUE TITLE
How to turn libtorrent as a super dht node/server

### ISSUE THREAD

**Issue by bosskwei** [arvidn/libtorrent#4298]
Hi guys,
I'm working on libtorrent and analysing it's p2p network these days. I run libtorrent on xeon server with GB network, and I want libtorrent become a super dht node, **accept dht requests as many as possible**, so how to set `settings_pack` for my need?

`active_dht_limit` may not work for me I think.

**Comment by ssiloti** [comment]
If you just want your client to respond to all requests it receives you can set the `dht_upload_rate_limit` setting to a large value, e.g. 1000000.

**Comment by arvidn** [comment]
right. `active_dht_limit` controls how many of your torrents will announce to the DHT, which I imagine will not be relevant for you.

In libtorrent-1.2.x You set the dht upload rate limit via `dht::dht_settings`. When constructing the session object, pass in a `session_params` object where you have set the dht settings. In the next major release however (currently `master`) the DHT settings have moved into the `settings_pack` object.

You may also want to raise these limits:

`max_dht_items`, `max_peers`, `max_torrents`, `max_torrent_search_reply`, `max_infohashes_sample_count`

**Comment by arvidn** [comment]
this is of course if what you're going for is to actually provide DHT services. If your main purpose is to help *introduce* nodes to the network, you want to look at https://github.com/bittorrent/bootstrap-dht instead
