### ISSUE TITLE
TORRENT_EXCEPTION_THROW_SPECIFIER might be a misnomer

### ISSUE THREAD

**Issue by jpetso** [arvidn/libtorrent#43]
I'm not entirely sure how to read this macro. Since you define it to `throw()` or `noexcept`, shouldn't it be more like `TORRENT_EXCEPTION_NOTHROW_SPECIFIER`? and also you apply it to a function that instantiates an `std::string` ([here](https://github.com/arvidn/libtorrent/blob/b5a477d7fd193348d1e30f20f9958bea2b012261/src/error_code.cpp#L326)), which can throw.

**Comment by arvidn** [comment]
the exception derives from std::exception or std::runtime_error. The what() function must have the same signature as the base class. Different versions and different compilers have different throw specifiers (I think c++ 11 says what() should be noexcept). I should probably throw in a TORRENT_OVERRIDE there too now.
