### ISSUE TITLE
Different listen ports for TCP & UDP when using port randomization

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4312]
libtorrent version (or branch):
1.2.3
platform/architecture:
Win10

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

When random port on each startup is selected in Qbit, it listens of different ports for TCP and UDP. This is an unexpected behavior. Both ports should be same. Also when there's different listening ports for TCP/UDP then which port is getting reported to tracker? Already reported this in qbit's git but I think the problem lies in libtorrent. Please take a look.
https://github.com/qbittorrent/qBittorrent/issues/11935

**Comment by arvidn** [comment]
this does not happen you listening to a specific port?
What's the difference in the `listen_interfaces` setting?

**Comment by arvidn** [comment]
is it possible that qbt calls `rand()` twice? (or whatever random number generator it uses)?

I imagine it constructs a string like this: `0.0.0.0:<port>,[::]:<port>`. It needs to make sure `<port>` is the same value in both places.

**Comment by Chocobo1** [comment]
>is it possible that qbt calls rand() twice? (or whatever random number generator it uses)?

qbt passes `0` as the port number to `listen_interfaces`.

That specific behavior is based on the following from `listen_interfaces` documentation:
>Binding to port 0 will make the operating system pick the port.

And obviously this results in TCP & UDP picking different port numbers.

**Comment by arvidn** [comment]
aha, I see what's going on. Right [here](https://github.com/qbittorrent/qBittorrent/blob/89e72b38ea276e8188c4d8be4f31a1e45241c3b4/src/base/bittorrent/session.cpp#L1457).

That piece of code uses port "0" to mean "let the OS decide". Libtorrent simply passes that 0 onto the OS, to let it decide. libtorrent is supposed to tie the TCP and UDP sockets to the same port, but it doesn't seem to be doing so.

**Comment by arvidn** [comment]
I can reproduce this. I will add a unit test and fix this for libtorrent-1.2.4
thanks!

**Comment by arvidn** [comment]
here's a fix. I will add a test before landing it too: https://github.com/arvidn/libtorrent/pull/4314
