### ISSUE TITLE
Boost::System library Could not find a version of the library in armv7

### ISSUE THREAD

**Issue by yjcn** [arvidn/libtorrent#4323]
**Please provide the following information**

libtorrent version (or branch):
libtorrent-1_2_4
platform/architecture:
rpi3 armv7
compiler and compiler version:
gcc gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1)
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
This is my gcc -v 
![图片](https://user-images.githubusercontent.com/8858803/74236389-0fe78980-4d0c-11ea-8ed1-2170e51c6195.png)
This is my build command. and the boost version is 1.67
```
apt-get update
apt-get install -y build-essential pkg-config automake libtool git zlib1g-dev
apt-get install -y libboost-dev libboost-system-dev libboost-chrono-dev libboost-random-dev libssl-dev libgeoip-dev
git clone https://github.com/arvidn/libtorrent.git
cd libtorrent
git checkout libtorrent-1_2_4
./autotool.sh
./configure --disable-debug --enable-encryption CXXFLAGS="-std=c++14"
```
this is the error
![图片](https://user-images.githubusercontent.com/8858803/74236562-740a4d80-4d0c-11ea-98d4-f8665894bf31.png)

**Comment by funkypoly** [comment]
For the armhf machines, you have to add the "--with-boost-libdir=/usr/lib/arm-linux-gnueabihf" in the configure line.

What was the previous libtorrent-rasterbar version you had installed ??? 1.2.2 ? 1.2.1 ?
Keep in mind that there are still issues with those latest versions (1.2.3 & 1.2.4) on armhf machines and python bindings doesn't work. 
Read this :  https://github.com/arvidn/libtorrent/issues/4204

Feel free to try and inform us here.
