### ISSUE TITLE
libtorrent compile failed with a future version of MSVC 

### ISSUE THREAD

**Issue by Cheney-W** [arvidn/libtorrent#4324]
libtorrent version (or branch): 1.2.2

platform/architecture: Windows 10

compiler and compiler version: MSVC

Hello, I'm a member of Microsoft VCPKG, when I built this port in an internal version of Visual Studio, it failed with span.hpp(87): error C2039: 'basic_string': is not a member of 'std'. This issue due to a change in MSVC: \<string> doesn't transitively include\<ostream>.
For fixing this issue, we need to add #include\<ostream> into the source.

**Comment by ssiloti** [comment]
I think the problem you are seeing is due to a missing <string\> include, not <ostream\>. The bug was fixed in 1.2.3 by 47dede4f7ee037600fa81bdc97cb4223af0574bf.

**Comment by Cheney-W** [comment]
@ssiloti Thanks for your reply, this issue is really fixed by adding \<string>.
