### ISSUE TITLE
Set TCP_NOTSENT_LOWAT socket option to limit state machine latency

### ISSUE THREAD

**Issue by the8472** [arvidn/libtorrent#4328]
Libtorrent already supports explicit `SO_SNDBUF` configuration to make some memory/performance tradeoff, but ideally that buffer size should be left to kernel auto-sizing policies which take the BDP into account.

Instead some low value (somewhere between 16 and 128KiB) for `TCP_NOTSENT_LOWAT` should be used to only enqueue a fixed amount of data beyond the congestion window.  This socket option is available on linux and osx. It does the right thing by both limiting the data that can be written via `send()` and delays `epoll` wakeup until the the unsent data falls below the threshold ([modulo hysteresis](https://github.com/torvalds/linux/commit/a74f0fa082b76c6a76cba5672f36218518bfdc09)).
On linux this can also be configured system-wide via the `net.ipv4.tcp_notsent_lowat` sysctl, but most distros don't do that by default.

Reducing the amount of enqueued data that's not in flight reduces the delay until a peer sees state bittorrent machine updates and thus makes interested/unchoke/request cycles more responsive, wastes less time of an unchoke window and thus should lead to better behavior overall.

**Comment by the8472** [comment]
For most uses it should be fine to set this to a small, fixed value.

But in scenarios where reducing syscall rate is important it might make sense to occasionally tune the option based on the socket's recent send rate and some desired wakeup interval, e.g. 50Mbit/s * 100ms -> 625KB.

Note that this does not have to be sized to match the BDP because it is the amount of *unsent* data, i.e. it's calculated on top of the needed congestion window.

**Comment by arvidn** [comment]
seems reasonable

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/4376

**Comment by xavier2k6** [comment]
@the8472 @arvidn seems there is an issue with previous cygwin1.dll that limited the receive buffer size for TCP sends. (That may not be relevant if cygwin isn't used) but the blog post may be somewhat insightful.

[Cygwin1.dll update](https://github.com/esnet/iperf/issues/960)

[Windows network performance suffering from bad buffering](https://techcommunity.microsoft.com/t5/networking-blog/windows-network-performance-suffering-from-bad-buffering/ba-p/339668)

>Windows telemetry results have indicated that a significant number of data connections are using the SO_RCVBUF and/or the SO_SNDBUF winsock options to statically allocate TCP buffers. There are many websites that recommend setting the TCP buffers with these options in order to improve TCP performance. This is a myth. Using Winsock options (SO_RCVBUF and/or SO_SNDBUF) to statically allocate TCP buffers will not make Windows networking stack “faster”. In fact, static allocation of the TCP buffers will degrade performance in terms of how fast the connection responds (latency) and how much data it delivers (bandwidth). The Windows transports team officially recommends **not** doing this.

>By statically allocating the receive buffer using SO_RCVBUF we limited ourselves to a top speed of 12.6 Mbps.  By letting Windows TCP autotuning dynamically allocate the buffers we achieved the true unloaded line rate of 151 Mbps.  That is about an order of magnitude better performance.  Static allocation of TCP buffers at the app level is a bad idea. **Don’t do it** .

**Comment by the8472** [comment]
Arvid already removed those settings in the associated PR.

**Comment by arvidn** [comment]
for the record, libtorrent has never set socket buffer sizes by default. The option to control them has just been there as an escape hatch for someone that need to work around some problem.
