### ISSUE TITLE
Delayed exit issue

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4330]
libtorrent version (or branch):
1.2.4
platform/architecture:
win10

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

qbt doesn't close (the process) if the listening interface IP gets changed. I'm suspecting it's a problem on libtorrents end? Maybe something gets stuck due to the change of IP address?
qbt is listening on all interfaces/addresses.
The process eventually closes after some time.

**Comment by arvidn** [comment]
please build libtorrent with `TORRENT_ASIO_DEBUGGING` defined (or if using `b2` with the `asio-debugging=on` build feature).

This will print debug information to `stdout` during session destruction. Specifically which asynchronous calls are still outstanding.

**Comment by gubatron** [comment]
having a similar issue with our Mac and Windows build when testing 1.2.4, app never closes and I have to kill the process manually.

Now that I see this I'll take a look at what's happening when we try to shutdown the libtorrent session. Will report what I find.

**Comment by an0n666** [comment]
I compiled a static version of libtorrent with asio-debugging=on for qBt. How do I see the stdout output? Is there any way to log this to a file or something?

**Comment by arvidn** [comment]
it's printed to `stdout`, so it won't work if you build it as a "windows application" on windows (in fact, I think the application may abort if you try to print in this mode), it has to be a "console application". On any other OS, just run your program from a terminal, to see the output.

To log it to a file, just redirect it like this: `./my_application >output.log`

**Comment by an0n666** [comment]
arvidn is it possible for disk I/O threads to get locked or hanged or something of that sort? I noticed a strange behavior where my upload speed suddenly drops from around 25 MB/s to 2-3 MB/s but disk read continues to be in the 20-30 MB/s range. And when this happens, if I try to close qBt client for restart, it gets stuck for long time exiting. I have to manually kill the process.

**Comment by arvidn** [comment]
If you’re asking whether it’s possible there’s a bug; yes.

This description doesn’t necessarily have to be caused by one though. When you say the disk read stays high, is that the libtorrent process issuing reads? Do you see those reads in process monitor?

**Comment by an0n666** [comment]
I have uploaded a recording here you can check https://gyazo.com/b512445aa9c04854dfa686ac89cf0a9b
And yes they are all read requests...qBt is reading more than sending....I think this is probably because the uploader used a very big piece size(32 MiB) and libtorrent is reading more data due to that?

**Comment by arvidn** [comment]
there is a subtle distinction between read requests sent to the OS and the number of bytes the file system reads from the drive. I believe activity monitor reports the latter (but I could be wrong).

For example, if you have a peer that's requesting blocks far apart, libtorrent's disk cache might read larger chunks from disk into cache anticipating they will also be requested. If the are never requested, that was wasteful. This is not very common behavior from clients though, but I suppose there could be a malicious or low-quality implementation

**Comment by an0n666** [comment]
If a client allocates a small amount of cache, lets say 64 MiB and pieces are 32 MiB.
I have 50 peers connected and requesting different pieces from me.
How would libtorrent behave in such a case?
Would it read 50 different pieces from the disk and try to cache them when there's no room?
Would it read 50 different pieces each 32 MiB = 1600 MiB from disk even before it can manage to fulfill one peers request? To me this looks like wasteful behavior. The piece size is somewhat responsible for this but there should be some intelligent allocation of upload slots if the pieces are large.

**Comment by arvidn** [comment]
the cache logic is complicated. there are measures to avoid thrashing, and when it's under high load the built-in read-ahead is disabled.
