### ISSUE TITLE
Andriod NDK build broken

### ISSUE THREAD

**Issue by geiseri** [arvidn/libtorrent#4338]
libtorrent version (or branch): libtorrent-1_2_4 tag

platform/architecture: Linux:x86_64 cross-compile to Andriod:armv7

compiler and compiler version: 

```
Android (5900059 based on r365631c) clang version 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 207d7abc1a2abf3ef8d4301736d6a7ebc224a290) (based on LLVM 9.0.8svn)
Target: armv7a-unknown-linux-android16
Thread model: posix
InstalledDir: /android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin
```

I get an error on build: 

```
libtorrent/src/file.cpp:647:4: error: use of undeclared identifier 'posix_fadvise'
                        posix_fadvise(native_handle(), 0, 0, POSIX_FADV_RANDOM);
```
 What strikes me as strange is the comment that the line is there as a workaround for Andriod.  Am I missing a compiler flag?  My cmake line was:

```
cmake -Dstatic-runtime=True -Ddeprecated-functions=False ../
```

**Comment by aldenml** [comment]
@geiseri look at the defines here https://github.com/aldenml/libtorrent4j/blob/master/swig/config/android-arm-config.jam#L16

**Comment by geiseri** [comment]
That looks like it compiled.  Is that something that can be added to the cmake options?

**Comment by aldenml** [comment]
do you mean inside `libtorrent` or in your cmake scripts?

**Comment by arvidn** [comment]
It seems like libtorrent should just not make that call on Android. Is there any other way to do the same thing on android?

**Comment by geiseri** [comment]
This is strange.  If I enable those flags on armv8 then the build fails, but if I remove those it builds just fine.  Could there be something else in play for 32bit arm?

**Comment by aldenml** [comment]
the workaround is specific to android 32 (both arm and x86) bits and API < 21, but in all other cases, those functions are there and they work as expected AFAIK

**Comment by geiseri** [comment]
@aldenml  I apologize, somehow CI had 16 for the API level.  I updated it to 21 and it worked as advertised originally. So in summary: If the NDK is r21 it all works as advertised.  If the API is less than 21 then the flags you provided are needed.  Sorry for the confusion.

@arvidn So if you are okay with not working on less than NDK 21 than this can be closed.  My understanding is that this would rule out ARM processors that lack NEON support, but in my experience, those are unbearable to use anyway.

**Comment by arvidn** [comment]
Is there a macro that can be used to detect an the NDK version? I would be open to patch `config.hpp` to just not use these calls on older NDKs.

**Comment by arvidn** [comment]
A patch would be welcome, especially against `RC_1_2` before I cut 1.2.5

**Comment by arvidn** [comment]
or before 1.2.6 :)

**Comment by master255** [comment]
@arvidn And where is the solution to the problem?
This command can compile on api 21+ and should make an exclusion for api 19+

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/issues/4338#issuecomment-590863970
this is how open source works.

**Comment by master255** [comment]
@arvidn I don't know how to fix it. At all.
I have an assumption that the error started to appear because of a different version of the NDK, but I'm not sure.
I don't think that's your problem.

**Comment by master255** [comment]
@geiseri  I found the problem!
The thing is that the toolchain for the 21 api is being used. And we need to use toolchain for 19 api. And then these commands will work:
    # hacks to remove when API >= 21
    <cxxflags>"-D\"epoll_create1(x)=-1; errno=ENOSYS\"
    <cxxflags>"-D\"posix_fadvise(x1,x2,x3,x4)\""
