### ISSUE TITLE
libtorrent::pe_settings deprecation error.

### ISSUE THREAD

**Issue by cos-public** [arvidn/libtorrent#4341]
libtorrent 1.2.4
boost 1.72
win10 x64
msvc 2019 (16.4)

I have troubles building libtorrent with cmake for the first time.
I've built boost with
```
b2 --with-context --with-system --with-test toolset=msvc link=static threading=multi runtime-link=shared --prefix=<path>\boost-1.72.0 install
```
then built libtorrent with 
```
set OPENSSL_ROOT_DIR=<path>\OpenSSL\Win_x64\
set BOOST_ROOT=<path>\boost
cmake -DCMAKE_CXX_STANDARD=17 -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=<path>\libtorrent-1.2.4 -DCMAKE_DEBUG_POSTFIX=d -G "Visual Studio 16" ..
msbuild INSTALL.vcxproj /p:Configuration=Debug
```
 I get error at ```async_result.hpp(44,1): error C2062: type 'bool' unexpected```. It seems boost tries to use concepts. So I define ```BOOST_ASIO_DISABLE_CONCEPTS``` in my project.
Then I get:
```
libtorrent\units.hpp(160,1): error C4996: 'std::_Conditionally_enabled_hash<_Kty,true>::result_type': warning STL4007: Many result_type typedefs and all argument_type, first_argument_type, and second_argument_type typedefs are deprecated in C++17. You can define _SILENCE_CXX17_ADAPTOR_TYPEDEFS_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
```

So I define ```_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS```. And now I'm left with ```session_handle.hpp(831,24): error C4996: 'libtorrent::pe_settings': was declared deprecated```.

Trying to rebuild libtorrent with```-Ddeprecated-functions=OFF``` doesn't help.

Am I doing something wrong?

**Comment by arvidn** [comment]
does this fix it? I assume you get this because you build with "warnings as errors", right?
https://github.com/arvidn/libtorrent/pull/4346

**Comment by cos-public** [comment]
I've tried both the current trunk and msvc-warnings versions. Both have the same warning. It appeared that C4996 warning is treated as error because of "SDL checks"=on setting in Visual Studio. With "SDL checks"=off it becomes warning again.

After trying few more hours I was able to successfully link the example project with libtorrent. For those who may find it useful here are my steps:

Build boost with RTTI disabled (optional):
edit boost/config/user.hpp and add `#define BOOST_NO_RTTI`
```
.\bootstrap.bat
b2 --with-context --with-system --with-test --with-date_time toolset=msvc link=static threading=multi runtime-link=shared --prefix=<libpath>\boost-1.72.0 install
```
I'm not sure which libraries are necessary to build for libtorrent, besides `date_time`.

Build libtorrent (using OpenSSL from Qt distribution):
```
set OPENSSL_ROOT_DIR=c:\Qt\Tools\OpenSSL\Win_x64\
set BOOST_ROOT=<path_to_boost>\lib\boost
cmake -DCMAKE_CXX_STANDARD=17 -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=<libpath>\libtorrent-1.2.4 -DCMAKE_DEBUG_POSTFIX=d -Ddeprecated-functions=OFF -G "Visual Studio 16" ..
msbuild INSTALL.vcxproj /p:Configuration=Release
msbuild INSTALL.vcxproj /p:Configuration=Debug
```

Add the following library dependencies in Visual Studio: `torrent-rasterbard.lib`, `Dbghelp.lib` (Debug only), `libssl.lib`, `libcrypto.lib`, `Iphlpapi.lib`. Append boost, OpenSSL and libtorrent library directories to the library search path. Add preprocessor definitions: `BOOST_ASIO_DISABLE_CONCEPTS`, `_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS`, `TORRENT_NO_DEPRECATE`

Boost automatically links boost libraries on msvc with a feature called auto-linking, which is a bit annoying. It links libboost_date_time, but doesn't set library search path. You can disable it with `BOOST_ALL_NO_LIB` entry in `boost/config/user.hpp` (haven't done yet).

**Comment by arvidn** [comment]
boost.date_time has not been a dependency of libtorrent for a very long time. many years. If you're building 1.2.x or trunk, there should be no dependency on boost.date_time.

I assume all those macros you specify weren't *necessary* to define, but you wanted to control the build in that way. The CI (appveyor) builds libtorrent in various configurations without resorting to any complicated heroics like that. It also doesn't rely on the auto-linking in boost (it can be disabled by `BOOST_ALL_NO_LIB ` which has been disabled by libtorrent builds since 13 years or so).

**Comment by arvidn** [comment]
btw, both warnings you mentioned in your original post should have been suppressed or fixed by my patch. Are you saying it did not have that effect?

**Comment by cos-public** [comment]
Sorry, It may be not clear from the first post, but deprecation warnings appear when building Visual Studio example project (generic native project without cmake or b2) using libtorrent, not the libtorrent itself. And as stated in the documentation I have to have the same defines for my project as for building libtorrent.

The only warnings I get when building libtorrent are like this:
```
include\libtorrent/units.hpp(160,1): warning C4996: 'std::_Conditiona
lly_enabled_hash<_Kty,true>::result_type': warning STL4007: Many result_type typedefs and all argument_type, first_argu
ment_type, and second_argument_type typedefs are deprecated in C++17. You can define _SILENCE_CXX17_ADAPTOR_TYPEDEFS_DE
PRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
```

I do have pe_settings deprecation warning in my project without `TORRENT_NO_DEPRECATE`, so I have to define it in the application and build libtorrent with `-Ddeprecated-functions=OFF`. I'm not sure why is this settings not stored in some hpp configuration file?

Libtorrent triggers the dependency on boost::date_time, may be it's an asio dependency (I didn't investigate it deeply). So I have to use `BOOST_ALL_NO_LIB` in the example project, as libtorrent does in its cmake file, or provide the date_time lib file, or define `BOOST_ALL_NO_LIB` in `boost/config/user.hpp`.

You have to set `BOOST_ASIO_DISABLE_CONCEPTS` if using c++latest probably because of partial concepts implementation in the current msvc.

`libssl.lib`, `libcrypto.lib`, `Iphlpapi.lib` are probably the implicit dependencies of boost.asio.

So all these defines and dependencies are logical and reasonable. It was just a bit non trivial to get started for a new user like me with generic non-cmake Visual Studio project.

**Comment by arvidn** [comment]
I had a typo in my patch, which caused the deprecated `result_type` to still be there.

> I do have pe_settings deprecation warning in my project without TORRENT_NO_DEPRECATE, so I have to define it in the application and build libtorrent with -Ddeprecated-functions=OFF.

Is that warning not suppressed by this? https://github.com/arvidn/libtorrent/pull/4346/files#diff-383ba3ebdfaa2d405788dd11f4c22266R827

> I'm not sure why is this settings not stored in some hpp configuration file?

How do you envision that to work? If it's defined in a header file, it's not a build configuration option anymore, but hard coded. Or do you mean the build system would record the build configuration options in a header that clients then can include?

**Comment by cos-public** [comment]
> Or do you mean the build system would record the build configuration options in a header that clients then can include?

I believe this cmake feature is intended for this purpose. https://cmake.org/cmake/help/latest/command/configure_file.html. But I'm not an expert in cmake and don't know how "modern cmake style" is this.

> Is that warning not suppressed by this?

I will try to check a bit later.
