### ISSUE TITLE
make torrent_handle::move_storage move only files part of the torrent, one-by-one

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#435]
1. Download a multi-file torrent and let it download a few files(don't know if last part is required).
2. Go the folder created by the torrent and create a dummy file.
3. Call `torrent_handle::move_storage()` on that torrent and move it somewhere else.

Result: The dummy file is also moved to the new location
Expected result: The dummy file stay in place while the torrrent's files are moved only.

A variation of step 2: Save the torrent in a folder that contains other files. Those files will be moved.

Windows 7 + libtorrent 1.0.8

**Comment by arvidn** [comment]
you don't think step two is suspicious? especially the variation of it. merging torrents like that isn't necessarily safe to begin with.

moving the files belonging to the torrent has subtle difficults too. You would like the move to be transactional, but if you move one file at a time, it can't be.

**Comment by sledgehammer999** [comment]
When I say "dummy" file, I mean any file.
For the variation of it look at this comment for a better use case: https://github.com/qbittorrent/qBittorrent/issues/91#issuecomment-8585478

Also a lot of users have requested a "strip subfolder" feature for multifile torrents. ie don't create a parent dir. I have a patch in the works that achieves this by setting `file_storage::set_name()` to an empty string. I suspect doing move_storage() in such a torrent will wreak havoc in the user's folder.

>You would like the move to be transactional, but if you move one file at a time, it can't be.

Truly sorry, but what "transactional" means here?

**Comment by arvidn** [comment]
I mean that the operation either successfully completes or it fails and the state of the filesystem is unchanged. i.e. it acts as an atomic operation.. imagine having 10 files to move, and the first 5 succeed and the 6ths fail.. you need to roll back. while rolling back, the file operation can also fail, and then you're screwed

**Comment by sledgehammer999** [comment]
>I mean that the operation either successfully completes or it fails and the state of the filesystem is unchanged. i.e. it acts as an atomic operation.. imagine having 10 files to move, and the first 5 succeed and the 6ths fail.. you need to roll back. while rolling back, the file operation can also fail, and then you're screwed

Oh yeah. That is a very serious problem. The only use case I still have objections is the "strip subfolder" one. I'll need to test how utorrent behaves on this.

**Comment by arvidn** [comment]
yeah, doing that is most likely not well supported by libtorrent. I remember putting lots of effort into getting all the edge cases right for that in uTorrent. it ended up being quite complex.
is there a compelling use case here?

would hard- or soft links be substitutes?

**Comment by glassez** [comment]
>You would like the move to be transactional, but if you move one file at a time, it can't be.

But you still move a number of files! What is the main difference between all files in a folder and some subset of those files? I mean why can't we move several files (but not all files of folder) in transaction?

**Comment by arvidn** [comment]
"all files" really just means "one directory". with a single operation, it typically is atomic. clearly if you "move" across volumes that's not the case anymore.

**Comment by glassez** [comment]
So, there is no really transactions here? Then you really have to change that. Users often have a "third party" files in the folder of the torrent (the reasons for this may be different).

**Comment by ssiloti** [comment]
Most platforms don't support performing multiple file operations in a single transaction. In fact BTRFS is the only file system I know of which exposes this capability, and even it's generally not safe to use. Between "atomically move all files in the directory" and "non-atomically move only the torrent files in the directory" I'd say the former is the less bad option.

**Comment by glassez** [comment]
>Between "atomically move all files in the directory" and "non-atomically move only the torrent files in the directory" I'd say the former is the less bad option.

What kind of atomicity do you say? It only seems to atomicity in the event of a move within the same logical drive (in essence, it is just simply renaming the folder).

**Comment by arvidn** [comment]
that's right. you could also phrase it like: "it's only in the case of the destination being on a different volume it's not atomic" :)
regardless of implying how common various cases are in the wild, with the current logic, there at least are some cases where it behaves well. On the other hand, copying files across a volume boundary and only delete them if it all succeeds isn't too bad either. patches are welcome!

**Comment by arvidn** [comment]
Taking into account the case raised in #543 (moving a torrent's storage into its own directory). The algorithm to support this, as far as I can tell, would be something like this:

1. create a temporary directory next to the torrent's directory, using a unique random name.
2. rename/move all files in the torrent, one by one, into that temporary directory. presumably the simplest way would be to not mimic the original hierarchy within the temporary location, but to just name the files "1", "2", "3" etc.
3. clean up any *empty* directory from the original download location (to support there still being unrelated files in there, that needs saving)
4. create the new destination directory (in case it happened to be in one of the directories removed in step 3 for instance)
5. move all files from the temporary location into the new destination directory, creating any subdirectory they're supposed to be stored in.
6. any individual rename/move that fails for any reason should fall back to a copy. If the copy fails, it's unclear what to do, as it would probably be very complicated to roll back.

obviously, any file that has been renamed/moved to an absolute path would have to be exempt from any of this treatment. They are never moved by move_storage.

The current algorithm for this is in default_storage::move_storage() in src/storage.cpp. patches are welcome! (as long as they come with proper tests)

**Comment by andwan0** [comment]
Yes, in uTorrent/Transmission, we had a Move Location which would only move the "files listed in the torrent".
But somehow qTorrent just moves the entire folder - regardless of what's inside.
