### ISSUE TITLE
Unsupported URL protocol on torrentleech

### ISSUE THREAD

**Issue by XITRIX** [arvidn/libtorrent#4350]
libtorrent version: 1.2.4
platform: macos/ios

I have a problem with private tracker "torrentleech", it has 2 trackers:
https://tracker.torrentleech.org/a/fc78e~~~756c9c/announce
https://tracker.tleechreload.org/a/fc78e~~~756c9c/announce
And both says "unsupported URL protocol", but in qBittorrent they works just fine.
Do I need to setup something more to make them work, or what?
I used for testing "client_test" from examples folder.

**Comment by mhertz** [comment]
That means usually openssl isn't enabled during building, I believe, so https announces is unsupported. Set crypto to openssl during building, and have openssl in right place(check docs), as deluge and qbittorrent both also does.

**Comment by arvidn** [comment]
yes, libtorrent can be built both with and without openssl support. If it's built without, HTTPS won't work.
Maybe it's silly to support a build configuration without openssl, but it's really only used for HTTPS trackers, and I can imagine systems where it's not necessary (and it's kind of a heavy dependency to have)
