### ISSUE TITLE
Confusion about the rootdevice struct in upnp

### ISSUE THREAD

**Issue by Ty-Chen** [arvidn/libtorrent#4351]
**Please provide the following information**

libtorrent version (or branch): 1.1.9

platform/architecture:Win10, VS2019

compiler and compiler version:V141

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

When reading the code, in upnp.cpp, line 101 - 101 I find that you use deafult for some functions that are not ** special member function (default constructor, copy constructor, destructor etc)**. 

`upnp::rootdevice::rootdevice(rootdevice const&) = default;
upnp::rootdevice& upnp::rootdevice::operator=(rootdevice const&) = default;`

I write a little test and there are errors as I think, so how does it work?

**Comment by arvidn** [comment]
I don't understand. those are the copy constructor and copy assignment operator. Those are special member functions.

What does your test look like and what errors do you get?

**Comment by Ty-Chen** [comment]
> I don't understand. those are the copy constructor and copy assignment operator. Those are special member functions.
> 
> What does your test look like and what errors do you get?

I read the article [https://www.geeksforgeeks.org/explicitly-defaulted-deleted-functions-c-11/](url), it says that the default constructor should not have any parameters. The test code is below



`#include <iostream>

struct trival {
	int port;
	bool able;
public:
	trival();
	trival(int port, bool able);
	trival& operator = (trival const&);
};

trival::trival()
	: port(0)
	, able(true)
{
}

trival::trival(int port, bool able) = default;
trival::operator=(trival const&) = default;

int main()
{
	trival* p = new trival;
	std::cout << "p. port = " << p->port;
	
}

`


The errors are just like the website says: 
Error	C2610	'trival::trival(int,bool)': is not a special member function or comparison operator which can be defaulted	default	D:\little try\default_constructor\default\default\main.cpp	18

**Comment by arvidn** [comment]
this doesn't seem to be a ticket related to libtorrent. so I'm going to close it.
The default constructor does not have any parameters, that's correct. but the default constructor is not the only special member function. the examples in libtorrent you pointed at were the copy constructor and copy assignment operator. Those *do* have parameters.
