### ISSUE TITLE
Possible to have a session-total `num_peers` that does not include peers who are queued or attempting to connect?

### ISSUE THREAD

**Issue by FranciscoPombal** [arvidn/libtorrent#4354]
**Please provide the following information**

libtorrent version (or branch): RC_1_2

platform/architecture: Any/amd64

compiler and compiler version: GCC 8.3.0

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

This came up in https://github.com/qbittorrent/qBittorrent/pull/9232#issuecomment-592145644. Basically, we want to display/provide via a web API the total number of actually connected peers. But to do this currently, we need to iterate through all the torrents and accumulate the `num_peers` we get from there, because the `num_peers` that can be obtained from status() also includes peers who are queued or attempting to connect. Relevant code: https://github.com/qbittorrent/qBittorrent/blob/9649c2a1638f7090d2c7dfa0e84fceb8d9256eb4/src/webui/api/synccontroller.cpp#L139

In terms of API this is also rather confusing as there is the following asymmetry:
- `status()` has `num_peers` which includes every peer (actually connected or just queued/attempting) from every torrent.
- `torrent_status()` has `num_peers` which only includes actually connected peers for a single torrent, and `num_connections` which behaves like status()'s `num_peers` but for a single torrent.

Instead I would expect `status()` to also have `num_connections` and for `num_connections` and `num_peers` in `status()` to behave analogously to their counterparts in `torrent_status()`.

This is what I understood from reading the relevant entries in https://libtorrent.org/manual.html.
Please correct me if I am looking at this the wrong way or if I am simply not seeing an existing easy way of obtaining the desired result.

EDIT: what am I even doing... I should be looking in https://libtorrent.org/single-page-ref.html instead. But please consider updating the other page.

**Comment by FranciscoPombal** [comment]
Just looked into the peer gauges. The docs says every gauge includes half open connections, but is there a way I can derive the number of peers excluding the half-open connections e.g. by summing/subtracting certain gauges from one another?

**Comment by FranciscoPombal** [comment]
@arvidn ping

**Comment by arvidn** [comment]
"queued" is not a thing anymore. That was back when there was a half-open connection limit.

https://libtorrent.org/manual.html has a version number 0.16. it's extremely old. There's no link pointing to this file anymore, and it's just here because when I update the website I just copy the existing files over the old ones (and this file doesn't exist in 1.0 and later). I should remove it.

It does seem reasonable to address this, for sure. The asymmetry is especially bad.

**Comment by FranciscoPombal** [comment]
@arvidn 

Looking at the new docs (https://libtorrent.org/single-page-ref.html), I don't see documentation for `session_status`.

But anyway, what would be the recommended way to obtain the total number of actually connected peers?
Assuming there was a `peer` gauge that didn't count half-opened connections, and `num_peers` in `session_status` also didn't count half-opened connections, would it be best to use the `peer` gauge or `session_status`'s `num_peers`?

**Comment by arvidn** [comment]
`session_status` was been deprecated in 1.1 (but it seems I had missed to mark them with the deprecated attribute).

**Comment by arvidn** [comment]
the new API is the [session stats](https://libtorrent.org/manual-ref.html#session-statistics). The main benefits of the new API is that it's asynchronous and ABI-stable (i.e. it can be extended without breaking ABI).

The first sentence there is a bit outdated actually: "This is primarily useful for troubleshooting of production systems and performance tuning.". I'll remove that.

**Comment by arvidn** [comment]
that said, I'm open to fixing the deprecated `session_stats` too

**Comment by FranciscoPombal** [comment]
@arvidn 

> `session_status` was been deprecated in 1.1 (but it seems I had missed to mark them with the deprecated attribute).

> The first sentence there is a bit outdated actually: "This is primarily useful for troubleshooting of production systems and performance tuning.". I'll remove that.

> that said, I'm open to fixing the deprecated `session_status` too

Those would all be welcome changes.

> the new API is the [session stats](https://libtorrent.org/manual-ref.html#session-statistics). The main benefits of the new API is that it's asynchronous and ABI-stable (i.e. it can be extended without breaking ABI).

So the gauge way it is. Still, the original request stands: is it possible to add a gauge like `num_peers_up_unchoked_all` but which excludes half-open connections? The goal is to obtain a count equal to summing all `torrent_status()->num_peers` in a session.

**Comment by arvidn** [comment]
first step: https://github.com/arvidn/libtorrent/pull/4424

**Comment by arvidn** [comment]
`peer.num_peers_connected` may be what you're looking for.

**Comment by FranciscoPombal** [comment]
@arvidn 
> `peer.num_peers_connected` may be what you're looking for.

I don't think so - at least from looking at the docs. Below that table with the `peer.num_peers_*` gauges, it says:
> the number of peer connections for each kind of socket. these counts include half-open (connecting) peers.

**Comment by FranciscoPombal** [comment]
@arvidn 
Huh, I think the answer was staring me in the face the whole time. I now see there is a `peer.num_peers_half_open`.

Thus, assuming `peer.num_peers_connected` does, in fact, also include the half-open peers in the count, I should be able to get the result I want by simply doing `peer.num_peers_connected - peer.num_peers_half_open`, correct?

**Comment by arvidn** [comment]
I would be surprised if `num_peers_connected` also counts half-open, because a socket that's half-open isn't connected yet. I think ti's more likely that documentation is misleading.

**Comment by FranciscoPombal** [comment]
> I would be surprised if `num_peers_connected` also counts half-open, because a socket that's half-open isn't connected yet. I think it's more likely that documentation is misleading.

Looking at: https://github.com/arvidn/libtorrent/blob/ce9be0c83f73af3da17e90e9d9becbf89353b530/src/peer_connection.cpp#L162

it seems like the following comment is correct:
https://github.com/arvidn/libtorrent/blob/ce9be0c83f73af3da17e90e9d9becbf89353b530/include/libtorrent/performance_counters.hpp#L363

and the documentation is in fact misleading.

I guess on qBittorrent's side, we have what we need then.

So here's the checklist of what came out of this so far:

- [x] `session_status` was been deprecated in 1.1 (but it seems I had missed to mark them with the deprecated attribute). (https://github.com/arvidn/libtorrent/pull/4424)

- [x]  The first sentence there is a bit outdated actually: "This is primarily useful for troubleshooting of production systems and performance tuning.". I'll remove that. (https://github.com/arvidn/libtorrent/pull/4424)

- [ ] that said, I'm open to fixing the deprecated `session_status` too

- [ ] fix misleading `peer.num_peers_*` docs

**Comment by FranciscoPombal** [comment]
@arvidn 

> that said, I'm open to fixing the deprecated `session_status` too

I assume with the upcoming 2.0, there is no more interest in this?

**Comment by arvidn** [comment]
I forgot what's wrong with it. But it it's just documentation, I don't think it's included in what's generated if it's deprecated.

**Comment by FranciscoPombal** [comment]
> I forgot what's wrong with it. But it it's just documentation, I don't think it's included in what's generated if it's deprecated.

This was the problem:

>In terms of API this is also rather confusing as there is the following asymmetry:
>- `status()` has `num_peers` which includes every peer (actually connected or just queued/attempting) from every torrent.
>- `torrent_status()` has `num_peers` which only includes actually connected peers for a single torrent, and `num_connections` which behaves like status()'s `num_peers` but for a single torrent.
>
>Instead I would expect `status()` to also have `num_connections` and for `num_connections` and `num_peers` in `status()` to behave analogously to their counterparts in `torrent_status()`.

**Comment by arvidn** [comment]
I see

**Comment by FranciscoPombal** [comment]
bump

**Comment by arvidn** [comment]
I imagine the documentation can be improved. But can anything be done to the inconsistent naming in the API without breaking things?

**Comment by FranciscoPombal** [comment]
@arvidn 

> I imagine the documentation can be improved. But can anything be done to the inconsistent naming in the API without breaking things?

Well, probably not... Though the fact that `session_status` is deprecated makes it less bad to break it, right?. Then again, since it is deprecated, there is not that much incentive to improve it anyway. Feel free to close this if you decide to leave it how it is now.

**Comment by FranciscoPombal** [comment]
I think the original issue has been sufficiently addressed.
