### ISSUE TITLE
Question about HTTPs client certificate validation

### ISSUE THREAD

**Issue by theopolis** [arvidn/libtorrent#4386]
Hi, I noticed that the `libtorrent` https client does not verify server certificates: https://github.com/arvidn/libtorrent/blob/a53d3a8746dbcf29fba1350f5bbf2b50df08e987/src/http_connection.cpp#L332 (`verify_none` instead of `verify_peer`).

Is there any reason this cannot be changed to `verify_peer`?

**Comment by arvidn** [comment]
the main reason is that there is no generally accepted convention to include a certificate in .torrent files. And libtorrent does not ship with any specific root certs. I think the best solution would be including the cert in the torrent. then it would be pinned correctly and not rely on any CA infrastructure.

I'm open to suggestions though. I could add APIs for clients to specify the certificate to use for instance.

**Comment by arvidn** [comment]
Note that SSL torrents *do* verify the certificate. Not just for trackers, but for all peers as well. But SSL torrents is a niche feature not used by many.

**Comment by theopolis** [comment]
Ah, thanks for the context.

Let me test again later tonight. I think OpenSSL will use a default search path for a root certificate bundle such that out of the box enabling peer verification will work (for trackers with certs signed by common authorities).

**Comment by theopolis** [comment]
For example, this works for me (verifies the tracker cert correct):

```diff
diff --git a/src/http_connection.cpp b/src/http_connection.cpp
index ca75b569a..dcc07cef6 100644
--- a/src/http_connection.cpp
+++ b/src/http_connection.cpp
@@ -329,7 +329,8 @@ void http_connection::start(std::string const& hostname, int port
                                if (m_ssl_ctx)
                                {
                                        m_own_ssl_context = true;
-                                       m_ssl_ctx->set_verify_mode(ssl::context::verify_none, ec);
+                                       m_ssl_ctx->set_default_verify_paths(ec);
+                                       m_ssl_ctx->set_verify_mode(ssl::context::verify_peer, ec);
                                        if (ec)
                                        {
                                                lt::get_io_service(m_timer).post(std::bind(&http_connection::callback
diff --git a/src/session_impl.cpp b/src/session_impl.cpp
index 93ab99a94..1fe6bebb6 100644
--- a/src/session_impl.cpp
+++ b/src/session_impl.cpp
@@ -536,7 +536,8 @@ namespace aux {
 
 #ifdef TORRENT_USE_OPENSSL
                error_code ec;
-               m_ssl_ctx.set_verify_mode(boost::asio::ssl::context::verify_none, ec);
+               m_ssl_ctx.set_default_verify_paths(ec);
+               m_ssl_ctx.set_verify_mode(boost::asio::ssl::context::verify_peer, ec);
 #if OPENSSL_VERSION_NUMBER >= 0x90812f
                aux::openssl_set_tlsext_servername_callback(m_ssl_ctx.native_handle()
                        , servername_callback);
```

The `boost::asio::ssl::context` method `set_default_verify_paths` calls `SSL_CTX_load_verify_locations`, which searches for root bundles based on the configure/install of OpenSSL. The assumption is OpenSSL is provided by the system/OS. If someone is statically linking OpenSSL then this will not work.

**Comment by arvidn** [comment]
thanks for testing and reporting this! I think for a feature like this to land in libtorrent, there would have to be a way to turn it off. My impression is that it's common among trackers to use self-signed certificates (or at least it used to be). I also think it would be a really useful feature to allow a root certificate be bundled in regular torrent files and use that to verify the tracker (even for regular torrents). This could be proposed in a BEP.

The reason why I like the ability to bundle certificates is that it improves security by not depending on the public CA infrastructure, and it pins certificates by default.

**Comment by theopolis** [comment]
> I think for a feature like this to land in libtorrent, there would have to be a way to turn it off. My impression is that it's common among trackers to use self-signed certificates (or at least it used to be).

Ah, ok, I'm not very familiar with common tracker practices, this makes sense. Since enabling verification sounds disruptive, perhaps a opt-in setting would be more practical?

> The reason why I like the ability to bundle certificates is that it improves security by not depending on the public CA infrastructure, and it pins certificates by default.

That sounds ideal! If there is a bundled certificate then there could be logic for the the optional verification to become required.

**Comment by arvidn** [comment]
would you mind testing and/or reviewing this patch? https://github.com/arvidn/libtorrent/pull/4415

It's a bit bigger than yours, mostly because it:

1. simplifies http_connection to never have to create its own SSL context (have it always be passed in)
2. make UPnP have its own context, just in case some router use an HTTPS URL for port mapping (to not break that case)
3. separate the SSL context for generic trackers and the listen socket used for SSL torrents (which needs a custom Server name indication callback, and cannot verify peers).
4. Makes it configurable to pick SSL/TLS version
5. makes it configurable whether to validate HTTP trackers at all

**Comment by theopolis** [comment]
Tested and it's working correctly!

**Comment by arvidn** [comment]
@NotTsunami Have you tested this patch? If so, do you feel confident it works as expected?

**Comment by arvidn** [comment]
after having landed the original patch, I found a bug, but more importantly; I don't think the TLS version should be configurable. https://github.com/arvidn/libtorrent/pull/4466
the openssl [documentation](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_new.html) has deprecated the version-specific methods.

**Comment by arvidn** [comment]
with this patch https://github.com/arvidn/libtorrent/pull/4466 I think this issue has been addressed
