### ISSUE TITLE
Save files from a byte in multithreaded mode

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#4387]
Hello. I'm writing another torrent media player.
And I'm having trouble using the library.
I urgently need to write a file from a certain byte to disk. The problem is that the disk doesn't support sparse mode and because of that rewinding to the middle of 40 GB file causes creation of 20 GB bytes on disk. This takes a few minutes. So I am saving the file in parts.  Starting with the required byte. I can't save a file starting from a block or a piece because other threads don't know about it. I need to save the file starting with a certain byte.
How can I do this with your library?

Threads for download - save the file, and threads for playback read the files. The file is saved in multithreaded mode, taking into account the priorities of the threads.
It also means I need to download data from a certain byte. I know how the torrent protocol works, and I know about 16kb blocks and pieces of 4mb.
We need to request blocks with offset.

**Comment by arvidn** [comment]
I'm not entirely sure I understand what you mean by "from a certain byte". Are you saying you can't chop up the file into 1 MB blocks, to emulate sparse files? The minimum granularity of bittorrent is 16kiB blocks, so you could chop up the files at that level, but your filesystem is probably not going to like you :P 

Fundamentally, to implement custom disk storage, you implement the [storage_interface](http://libtorrent.org/reference-Custom_Storage.html#storage_interface) and pass in a constructor function in `add_torrent_params`. This interface will change in the next major release of libtorrent, but will remain stable for the current stable release (1.2.x).

If *all* you want is chopping up the file, you could just [remap_files()](http://libtorrent.org/reference-Core.html#remap_files()). That's probably the simplest solution, as long as you don't need anything more sophisticated.

**Comment by master255** [comment]
@arvidn Video player reads video files starting from different bytes.
For example:
Playback always starts with 0 bytes. Then player asks for last 15kb, 80Gb file (reading codecs \ tags).
Then the user rewinds to the middle of the file and needs to read starting from 40GB bytes.
In this scenario, 3 files are created on my disk:
1. start 0 byte - size 300 Mbytes.
2. start 79GB - size 15 Kbytes.
3. start 40 GB - size 10 GB.
In the name of the file I save its initial byte. The threads of the player know this initial byte and read it by the name of the file.

No other algorithm is possible. It is not possible to split an 80GB file into smaller parts and save it to disk. 2-3 files divided into 16Kb will kill any file system.

To create this scenario, I need to start downloading files from a certain byte. And to request data from peers starting with a certain byte. Can you add the initial byte number as a parameter in "addTorrentParams"?
Or maybe there is already another mechanism?

**Comment by arvidn** [comment]
what you pass in via `add_torrent_params` is a constructor function/factory, for your storage implementation. It's a function object, so you can bind any parameters you'd like there. But the initial offset into the torrent doesn't make sense at the point of creating the torrent.

In your storage implementation, you will be passed data and its offset, and you can do whatever you want with it. Including creating a file with whatever filename. However, keep in mind that the bittorrent engine will also ask you to be able to read back data, so you should organize it in a way that makes it reasonable to get back too.

**Comment by master255** [comment]
@arvidn But the initial offset into the torrent doesn't make sense at the point of creating the torrent.
Why doesn't it make sense? Because I want the file from the middle, not the whole one. If you can request a particular piece, why not specify an offset for it?? It allows for the torrent protocol. Why not implement it in the library?

**Comment by master255** [comment]
@arvidn And you keep forgetting that I can't use the storage in its current form. An 80GB file is created on a disk for many minutes. This means that rewinding media files is not working.

**Comment by master255** [comment]
@arvidn I want to add torrent_handle of the same file several times in a session, but starting and ending with different bytes. And the initial byte is critical to me, and the last one is not and can be a multiple of 16K bytes...

**Comment by arvidn** [comment]
There’s some misunderstanding. I’m suggesting to implement your own storage, where you can do whatever you want. See the link I posted above

**Comment by arvidn** [comment]
a `torrent_handle` is a handle to a torrent that has been added to a session. You can't add the same torrent multiple times, that doesn't make much sense. It sounds like you want to download specific ranges of a torrent. you can use piece priorities for that. But if you're streaming, you probably want to look at piece deadline as well.

**Comment by master255** [comment]
@arvidn 

> There’s some misunderstanding. I’m suggesting to implement your own storage, where you can do whatever you want. See the link I posted above

Can I use this mechanism to request pieces with an offset? And then save them (file parts) under different files?

**Comment by master255** [comment]
@arvidn 

>  You can't add the same torrent multiple times, that doesn't make much sense.
Well, why not? We can group torrent_handle by hash and download and share them as one torrent_handle.

**Comment by arvidn** [comment]
> Well, why not? We can group torrent_handle by hash and download and share them as one torrent_handle.

I don't understand the question. I was making the distinction between a `torrent_handle` (a handle to a torrent that has been added) and the torrent itself. You can copy a `torrent_handle` object all you want, and they will all refer to the same torrent. Why you can't add the same torrent twice? You can *attempt* to do so, and chose whether you get an error or a copy of the `torrent_handle` to the existing one. The torrent is only added once still though.

> Piece priority does not allow you to download the torrent from the required byte. That's exactly what I'm asking you to do. It's a great way to save traffic.

That's not possible. How much traffic would you expect to save?

**Comment by master255** [comment]
@arvidn 

> That's not possible. How much traffic would you expect to save?

I think a lot. When 100Gb 4k file is started, more than 6 threads are created for reading. Each thread may spend up to 4 Mbytes of data unnecessarily (if it needs the last bytes of a piece).
Total: 6*4=24 Megabytes from a single movie start.
+rewind a 4 Megabyte file and multiply all this by the number of movies and users.
I watch 2 or 3 films a day. There are millions of users. 
28*3=84 Megabytes one user per day.
And 84000000 = 84Tb of unnecessary traffic per day!
That means no scaling.

**Comment by master255** [comment]
@arvidn Sorry, but I've already found the bug, found the traffic leak and suggested a very simple way to get rid of it. I think we should do something :-)

**Comment by arvidn** [comment]
> I think a lot. When 100Gb 4k file is started, more than 6 threads are created for reading.

from your description, it's not clear how a "thread" is a parameter. Are your threads duplicating work?
 
> Each thread may spend up to 4 Mbytes of data unnecessarily (if it needs the last bytes of a piece).

Ok, so 4MiB on average, if you use 8MiB pieces, yes? you could use smaller pieces too.

> Total: 6 * 4 = 24 Megabytes from a single movie start.

Do you have one play head per thread? why would all of them read unaligned bytes? Even if you make libtorrent more complicated by adding support for byte-level block requests, you would get better performance by sticking to aligned requests.

> +rewind a 4 Megabyte file and multiply all this by the number of movies and users.
> I watch 2 or 3 films a day. There are millions of users.
> 28*3=84 Megabytes one user per day.
> And 84000000 = 84Tb of unnecessary traffic per day!
> That means no scalability.

Is that a lot compared to the total bandwidth?
It still sounds like scaling linearly, you can't really expect *better* scaling than that.

So, you have 6 threads, each requesting 4 MiB redundant data, times 3 times the number of users. A few questions:

1. Why would the normal case be reading unaligned bytes? Isn't the normal case of streaming from beginning to end?

2. Why would all 6 threads make unaligned requests? Surely they don't request the *same* ranges, so they could make sure the work is split up at piece boundaries. It's also not clear what you mean by "thread". Is it separate read-head from a video player? (and what's the point of that?)

3. Why do you want to use 8MiB pieces? That's unusually large.

**Comment by master255** [comment]
@arvidn 

> from your description, it's not clear how a "thread" is a parameter. Are your threads duplicating work?

I'm writing an Android player. For this I use the fork of your library, named frostwire-jlibtorrent with java interface.
At this moment my multi-threaded streaming algorithm works with other protocols: http, ftp, samba, mega.nz, dc++ (nmdc). Using these protocols, I have given you an example about 6 threads. Now, I can't use your library, but I'm trying.

> Ok, so 4MiB on average, if you use 8MiB pieces, yes?
Yes. I hadn't thought about it. For me, any traffic leak is critical. I don't write bad programs with leaks and bugs, and neither do you :-)

>  you could use smaller pieces too.

How can I use smaller pieces if the size of the pieces is written into the torrent file and set by the torrent creator? It doesn't matter. Smaller pieces will cause less traffic leaks, but they will still. Smaller pieces will also reduce the download speed, making it impossible to stream online.

> Do you have one play head per thread? why would all of them read unaligned bytes?
I have 1 thread to read data from disk and 6 threads to write to disk. The player is another thread that asks the first (read) thread for the information it needs to read data. The reader thread creates new threads to download data or reads already downloaded data. Thus, at startup more than 6 threads are created for downloading data. Of course, there is a balancing algorithm between them.

> Even if you make libtorrent more complicated by adding support for byte-level block requests, you would get better performance by sticking to aligned requests.

Why? Can you explain? How will the performance decrease due to the decrease of transmitted traffic?

> 1. Why would the normal case be reading unaligned bytes? Isn't the normal case of streaming from beginning to end?

Unfortunately, no. I thought the same thing a few years ago. But media files have a very complex structure (it can be 2 video streams and 16 audio different translation languages in one file), so the player can often request the end of the file, at the beginning of playback and several times, and then several times the beginning of the file in several places.

> Surely they don't request the same ranges, so they could make sure the work is split up at piece boundaries. 

They can request the same bytes again. In this case, I don't make requests to the Internet, but I give the data from the disk. It greatly increases speed, as you understand it.

> Why do you want to use 8MiB pieces? That's unusually large.

No. In my example, I used 4MB pieces and the most pessimistic case where only the last bytes are needed from that piece. In this case your library will download the whole 4Mb piece when the player needs it, only 10 bytes from the end of the piece.

I'm sorry for the long stuff. I tried to answer all the questions and ask a minimum of mine.

**Comment by arvidn** [comment]
If I understand you correctly, by "threads" you mean multiple TCP connections. You're doing that to, effectively, download from multiple peers and to get an effective larger TCP window size and shorter startup-time. All of that is already built-in to bittorrent, there's no need to use multiple "play heads", doing so will probably just slow things down and add complexity. bittorrent already connects to multiple peers and downloads from them in parallel. You still need to make sure you have enough read-ahead though, to keep the in-order download pipeline full.

> Yes. I hadn't thought about it. For me, any traffic leak is critical.

why is that?

> How can I use smaller pieces if the size of the pieces is written into the torrent file and set by the torrent creator?

If you are the creator you do. In your previous post you made it sound like you were running a server, since you multiplied the wasted bandwidth by the number of users. If you're not, and you're downloading only from other users, your previous argument becomes a bit questionable.

> Smaller pieces will also reduce the download speed, making it impossible to stream online.

Are you sure about that? Do you understand why?

> I have 1 thread to read data from disk and 6 threads to write to disk. The player is another thread that asks the first (read) thread for the information it needs to read data. The reader thread creates new threads to download data or reads already downloaded data. Thus, at startup more than 6 threads are created for downloading data. Of course, there is a balancing algorithm between them.

libtorrent will, by default, write data to disk. It sounds like you would need to implement your own storage satisfying your storage requirements, where you can do whatever you want. But you would most likely want to write it to disk in there. libtorrent has a thread pool for disk reads and writes. I don't know what your 6 write threads would do in this scenario.

> Why? Can you explain? How will the performance decrease due to the decrease of transmitted traffic?

Every bittorrent client is built to serve 16kiB blocks, aligned to 16 kiB offsets from the start of the torrent.
The disk I/O on your end is likely to be either less efficient because of unaligned access as well.
Perhaps the biggest issue is that you will not be able to validate the data you receive from peers, because that can only be done at piece granularity. (so, performance, not just in terms of throughput, but correctness too).

In fact, if you're on a FAT-formatted SD card, chances are that your disk is your bottleneck, not your network.

> They can request the same bytes again. In this case, I don't make requests to the Internet, but I give the data from the disk. It greatly increases speed, as you understand it.

Ok, so the 6 threads are serving data to the player. In the case of using libtorrent, they would ask libtorrent to prioritize certain pieces and/or read them from disk. Keep in mind that libtorrent does not (by default) `fsync()` data to disk, so just because libtorrent reports data as downloaded, doesn't mean you can go read it from disk yet. You can as to read it via libtorrent's own disk I/O thread ([read_piece()](http://libtorrent.org/reference-Core.html#read_piece())).

**Comment by master255** [comment]
@arvidn 

> If I understand you correctly, by "threads" you mean multiple TCP connections.

Now there is 1 tcp\ip connection per thread. Yes. But threads are very complicated and if necessary, I can open 2 or more tcp\ip connections per thread.

> If you are the creator you do. In your previous post you made it sound like you were running a server, since you multiplied the wasted bandwidth by the number of users.

I don't have a server. That's not the point. My player has many users. I talked about it. Saving traffic is important to me because of the faster performance. User Internet speed is very low and every extra byte means they can't watch a movie. As a result, they won't be able to download the movie and share it through torrents. (I repeat. There are no torrents in my player right now)

> Perhaps the biggest issue is that you will not be able to validate the data you receive from peers,

Why do I need to check my streaming data? I don't need it at all. If the wrong data comes in, the playback will stop.
Is it possible that a check is needed because the udp protocol is used? Are the pieces checked when downloading? And if the hash does not match, then the piece is downloaded again? Am I getting this right? What if the only tcp protocol is used?

> Smaller pieces will also reduce the download speed, making it impossible to stream online. Are you sure about that? Do you understand why?

I previously thought it could be because of the large amount of service data, but if the size of the block is 16kb, it does not matter what size the piece. The performance is limited to a block size of 16kb. I don't really understand why it is done and why it's impossible, as in DC++, to just output the whole file. But it is so. The size of a piece doesn't affect the performance of downloading.

> In fact, if you're on a FAT-formatted SD card, chances are that your disk is your bottleneck, not your network.

For the cache I (and millions of users) will use the usual usb 3.0 flash drive, the volume of more than 128 GB and NTFS - formatted. However, the sparse mode is not supported by the operating system. I already checked. Their write speed is over 100Megabits \ s. In multithreaded mode, even more. This is more than enough to cache a 100GB movie.

> Keep in mind that libtorrent does not (by default) fsync() data to disk, so just because libtorrent reports data as downloaded, doesn't mean you can go read it from disk yet. You can as to read it via libtorrent's own disk I/O thread

If I'm not mistaken, I saw the setting to disable the disk cache. Maybe that's what I need. But I probably need the event "write cache data to disk". I understand your library isn't exactly for streaming, but it's a necessary development, otherwise we'll be standing still. This kind of development will seriously increase the popularity of torrents.

**Comment by master255** [comment]
@arvidn Okay. We've made up our minds about what to do:
1. We need the parameter specifying the start byte torrent_handle. At your choice, you can make it unchangeable in the future. That is, it is set in addTorrentParams and does not change anymore.
2. Necessary, support for grouping identical torrent_handle, by hash sum. Interaction with them will be in multithreading mode. Each torrent_handle - writes data to its own file. Grouping - necessary to exchange information, such as metadata, available pieces of peers. For sharing - reports all pieces, even if they are in three torrent_handles.
3. Need an Alert event that will tell you what data is written from cache to disk, with additional information about what data is written. Preferably it should be a range of byte. The data cache is needed to speed up the download. We can't write 16kb to disk. - it's too slow.
4. We need to add a mode (if not already) - without checking the hash.

If you make these modifications, we will get a torrent streaming with maximum speed and no excess data. Which will work on any Android TV.

**Comment by arvidn** [comment]
That list suggests that there are some misunderstandings on what libtorrent does and how bittorrent works.

(1) Adding a "start_byte" field to `add_torrent_params` doesn't do anything by itself. You're not saying anything about how it should be interpreted. However, I suggest you bind this value in your function object that creates the storage.

(2) a torrent_handle is a handle. You can have any number of handles to a single torrent. You cannot have multiple, identical, torrents added to the session. That is non-sensical. Obviously you would want single instances of peer list, peer connections, storage object, piece picker, etc.

(3) I would suggest you either use `torrent_handle::read_piece()` to read the data (which will pull it from the libtorrent cache in case it is still there) or use libtorrent `master` branch, where the disk cache uses the page cache directly, and should have data become available to other processes immediately.

(4) There is a setting for disabling hash checking. However, do you trust all peers to send valid data?

**Comment by master255** [comment]
1. Setting the start byte means..:
    a. Writing to disk will start from this byte (in sequential mode).
    b. The first request for the first piece of torrent will be calculated based on this byte. That is, if the size of a piece is 4MB and the start byte is 4.5MB, then the first request should request the second piece + 0.5MB offset. //Torrent protocol provides for byte offset in pieces.
    c. All pieces before this byte will be ignored. The first (from this byte) - not the whole piece will not be shared and announced.
2. For me, each torrent_handle is a torrent file. And in a session, there may be several torrent files. Is that correct? So I can pass my torrent_handle to each of my threads and manage it? Well, to increase performance on the library side (it is not necessary at this stage) you need to group torrent_handle. To share the same information between them.
3. torrent_handle::read_piece() - this refers to the first item. I need to start downloading the torrent file from a certain byte instead of reading a certain piece. For each torrent_handle - its own storage = file? If so, that's what I need.
The main question you haven't answered is: what happens if sparse mode isn't supported and I ask for the last piece of torrent when I start downloading a 100G torrent file?  I'm trying to help you fix this bug. The library will hang for a few minutes until it creates the 100G file. That's not acceptable.
4. I have excellent codec algorithms that will simply switch to the next file if there is an error. It's a good thing this setting is already available. Let's not discuss it.

**Comment by master255** [comment]
@arvidn For example. My work code for read piece from byte on java:
`private byte[] getRequestPiece(long startByte) {
        byte[] numPiece = ByteBuffer.allocate(4).putInt((int) (startByte / proxyParams.getTorrentFile().getPieceLength())).array();
        int offsetInt = (int) (startByte % proxyParams.getTorrentFile().getPieceLength());
        byte[] offset = ByteBuffer.allocate(4).putInt(offsetInt).array();
        if (offsetInt + 16384 > proxyParams.getTorrentFile().getPieceLength())
            return Bytes.concat(numPiece, offset, ByteBuffer.allocate(4).putInt((int) proxyParams.getTorrentFile().getPieceLength() - (offsetInt + 16384)).array());
        else
            return Bytes.concat(numPiece, offset, ByteBuffer.allocate(4).putInt(16384).array());
    }`

**Comment by arvidn** [comment]
>     1. Setting the start byte means..:
>        a. Writing to disk will start from this byte (in sequential mode).

What is written to disk would be defined by your storage object, implementing `storage_interface` (I linked to the documentation of this a few round-trips ago, please take a look)

>        b. The first request for the first piece of torrent will be calculated based on this byte. That is, if the size of a piece is 4MB and the start byte is 4.5MB, then the first request should request the second piece + 0.5MB offset. //Torrent protocol provides for byte offset in pieces.

You can achieve this using piece priorities (at the piece granularity level). If you want to actually send a request for less than a 16 kiB block, you could also implement a *plugin* that rewrites piece request messages. This would be somewhat uncharted waters though, as you would still somehow need to tell the bittorrent engine that the blocks in the beginning of the piece somehow failed to be downloaded. Furthermore, an incomplete piece will not be prioritized to be flushed to disk, because its hash hasn't been verified yet.

>        c. All pieces before this byte will be ignored. The first (from this byte) - not the whole piece will not be shared and announced.

It may be possible to do something like this with a plugin.

>     2. For me, each torrent_handle is a torrent file. And in a session, there may be several torrent files. Is that correct?

No, a torrent handle is a handle to a torrent. Let's use the word "swarm" instead of torrent. There is only one swarm per info-hash. You may have multiple handles to the same swarm.

> So I can pass my torrent_handle to each of my threads and manage it? Well, to increase performance on the library side (it is not necessary at this stage) you need to group torrent_handle. To share the same information between them.

It's not clear what you have in mind, but it sounds like it would decrease performance. Bittorrent already downloads from multiple peers in parallel. There is no need to use threads for this.

>     3. torrent_handle::read_piece() - this refers to the first paragraph. I need to start downloading the torrent file from a certain byte instead of reading a certain piece. For each torrent_handle - its own storage = file? If so, that's what I need.

You can do whatever you want in your storage implementation. You can't really affect the network protocol though, so it will still be based on pieces and blocks.

>        **The main question you haven't answered is**: what happens if sparse mode isn't supported and I ask for the last piece of torrent when I start downloading a 100G torrent file?

The default storage will create the file and seek to that location in the file and write to it. But as I've said several times now, you can implement your own storage where you do something else. Find the link to the documentation above.

> I'm trying to help you fix this bug. The library will hang for a few minutes until it creates the 100G file. That's not acceptable.

What bug?

The creation, seeking and writing to this file will happen in separate thread. The network thread will still be responsive. If you need a different behavior, implement your own storage. I've repeated this quite a few times now, how about you make sure you read the documentation on custom storage before responding?

>     4. I have excellent codec algorithms that will simply switch to the next file if there is an error. It's a good thing this setting is already available. Let's not discuss it.

Well, in peer-to-peer networks, if you don't verify what you're downloading, you could just save a lot of bandwidth by reading from `/dev/random`. My point is that whether you get correct data or not has nothing to do with your codec. You inherently download bytes from random peers on the internet, that you cannot trust.

**Comment by master255** [comment]
@arvidn 

> It's not clear what you have in mind, but it sounds like it would decrease performance. Bittorrent already downloads from multiple peers in parallel. There is no need to use threads for this.

You're talking as if you don't have a library, but a complete program. I have my own algorithm (with my threads) for loading data written in java language. To this algorithm, I add different protocols. The Torrent protocol is one of them. To embed your library into my algorithm, I need the changes mentioned above.
Your library is very good and fast. But it's not flexible enough.

> You can achieve this using piece priorities (at the piece granularity level). If you want to actually send a request for less than a 16 kiB block, you could also implement a plugin that rewrites piece request messages. This would be somewhat uncharted waters though, as you would still somehow need to tell the bittorrent engine that the blocks in the beginning of the piece somehow failed to be downloaded. Furthermore, an incomplete piece will not be prioritized to be flushed to disk, because its hash hasn't been verified yet.

There is no instruction for writing plug-ins and the instruction for managing storage is also very short. Even you, as a developer of the library, write that it's "uncharted waters", then I'll meet insurmountable difficulties.

> The default storage will create the file and seek to that location in the file and write to it. 

It'll take: 100Megabit writing speed. Well, then: 100Gigabyte / (100/8) = 8333 seconds = 138 minutes = 2.3 hours! Only for writing the last block. And a minimum of 2.3 hours to write the data.
Splitting it into small pieces is not the way out. There will be too many parts, the file system can't handle so many files. That would remain my algorithm. But you won't help me make it. I'll probably be looking for another library. 

> You can achieve this using piece priorities (at the piece granularity level). If you want to actually send a request for less than a 16 kiB block, you could also implement a plugin that rewrites piece request messages.

Maybe we should make it clear what I meant.
A piece - maybe different sizes, like 4MB.
Block - maximum 16 kbytes.
The pieces are made up of blocks.
So I need to offset the pieces, not the blocks. The request specifies the number of the piece, the offset and the size of the necessary bytes (16Kb maximum).
How can I do it with your library?

**Comment by arvidn** [comment]
> @arvidn
> 
> > It's not clear what you have in mind, but it sounds like it would decrease performance. Bittorrent already downloads from multiple peers in parallel. There is no need to use threads for this.
> 
> You're talking as if you don't have a library, but a complete program.

Yes. It implements bittorrent, which downloads and uploads from and to multiple peers in parallel, without using threads, in rarest-first order. It writes the downloaded data to disk, via a customization point where clients can customize how data is written (I assume you're familiar with this by now).

> I have my own algorithm (with my threads) for loading data written in java language.

There is no benefit (but I can think of potential performance degradation) of literally joining the swarm multiple times, duplicating the cost of piece picking and duplicating connections to peers (in fact, peers typically reject multiple connections from the same IP, so it would strictly speaking be an additional cost of finding other peers to connect to). There is no point in using threads to talk to libtorrent. All library calls will be posted to the network thread and serialized anyway.
 
> There is no instruction for writing plug-ins

It's [here](https://libtorrent.org/reference-Plugins.html#overview).

> and the instruction for managing storage is also very short.

Do you have specific questions? There's an example [here](https://github.com/arvidn/libtorrent/blob/RC_1_2/examples/custom_storage.cpp).

> Even you, as a developer of the library, write that it's "uncharted waters", then I'll meet insurmountable difficulties.

"uncharted waters" referred to trying to force libtorrent to send request messages *not* aligned to blocks.

> > The default storage will create the file and seek to that location in the file and write to it.
> 
> It'll take: 100Megabit writing speed. Well, then: 100Gigabyte / (100/8) = 8333 seconds = 138 minutes = 2.3 hours! Only for writing the last block. And a minimum of 2.3 hours to write the data.
> Splitting it into small pieces is not the way out. There will be too many parts, the file system can't handle so many files. That would remain my algorithm. But you won't help me make it. I'll probably be looking for another library.

I don't understand why you care about what the default storage does. It seems clear to me that you would need your own storage implementation. Everything you just said can be customized, you can do whatever you want an need.

Is the fundamental problem that you want to download out-of-order but you don't have a way to store data downloaded out-of-order? I can't solve that problem for you. You could try sqlite.

> Maybe we should make it clear what I meant.
> A piece - maybe different sizes, like 4MB.
> Block - maximum 16 kbytes.
> The pieces are made up of blocks.
> So I need to offset the pieces, not the blocks. The request specifies the number of the piece, the offset and the size of the necessary bytes (16Kb maximum).
> How can I do it with your library?

via a plugin. In case you haven't found the documentation, it's [here](https://libtorrent.org/reference.html). You would (probably) have to intercept request messages and write your own requests with the offsets adjusted. By overriding `write_request()` on `peer_plugin`.

The internal data structures in libtorrent are all based on block offsets, but the bittorrent protocol is based on byte offsets.

**Comment by elgatito** [comment]
@master255 As Arvid wrote you multiple times, libtorrent uses storage interface to read/write torrent pieces. Libtorrent has own default storage interface implementation, which uses OS's file creation functionality. If your OS does not support sparse files - it will create full sized files. That is not controlled by libtorrent in any way.

That takes you to the point Arvid is saying. You should make your implementation of storage interface, where you can split files per 1Gb for example, so when libtorrent asks storage to write piece (each piece sized 16kb) with index 0 - if will be 1st file, and so on, you always know the size of requested piece and it's index, so you know what offset of a torrent you need. 

I believe there are implementations of these on github, just need to search for them.

**Comment by master255** [comment]
@elgatito I think you don't know what this is about.
Write speed to USB flash drive 100Megabits \ s. 
If I break a file (100Gb) into pieces by 1Gigabyte, the user will wait when rewinding:
1000 Megabyte /(100 Megabit /8) = 83 seconds. This is a fiasco brother :)
Whatever a significant delay the file should be divided into pieces of 50 Mbytes (4 seconds delay). This is also a fiasco, because the file system will not be able to withstand thousands of pieces of these files.
So the only way out is not to divide the file into equal pieces, but to divide the file into pieces necessary for the player. Create a new file, every time the player will request it. If it exists, then give the data that is available and download further the existing file.
This is a very complex algorithm. It's a much more complex algorithm than the torrent algorithm.
And in my player it already works and large files of 100 Gb are cached on a USB flash drive and played without delay.
All the protocols (http, ftp, samba, mega.nz, dc++ (nmdc)) that I use allow me to request information from a specific byte. The problem has only arisen with this library. It does everything well but can't query and write information from a specified byte. 
If you know how to download a torrent file from a specific byte, then tell me. I'm looking for this feature right now.

@arvidn I thinking...

**Comment by arvidn** [comment]
> @elgatito I think you don't know what this is about.
> Write speed to USB flash drive 100Megabits \ s.
> If I break a file (100Gb) into pieces by 1Gigabyte, the user will wait when rewinding:
> 1000 Megabyte /(100 Megabit /8) = 83 seconds (only, to create a file). This is a fiasco brother :)
> Whatever a significant delay the file should be divided into pieces of 50 Mbytes (4 seconds delay). This is also a fiasco, because the file system will not be able to withstand thousands of pieces of these files.

His point was that you would have to implement your own storage, where you can do whatever you want. Not suggesting a solution to your problem.

> So the only way out is not to divide the file into equal pieces, but to divide the file into pieces necessary for the player. Create a new file, every time the player will request it. If it exists, then give the data that is available and download further the existing file.

I seriously doubt that that's the *only* way. I would expect you could solve the problem by implementing a "log filesystem" kind of storage too.

> If you know how to download a torrent file from a specific byte, then tell me. I'm looking for this feature right now.

If that is the specific feature you're looking for, you're probably better off implementing the peer-write protocol and request data directly. (and then pick pieces in some reasonable way, and support uploading that data back to peers etc.)

However, it sounds like the reason you're looking for this feature is to make it fit your existing model of how HTTP works. Bittorrent doesn't work like HTTP, I think you would benefit from taking a step back and looking at the bigger picture.

**Comment by master255** [comment]
@arvidn 

> If that is the specific feature you're looking for, you're probably better off implementing the peer-write protocol and request data directly. (and then pick pieces in some reasonable way, and support uploading that data back to peers etc.)

Yes. I'm trying to do it now. Waiting...

> However, it sounds like the reason you're looking for this feature is to make it fit your existing model of how HTTP works. Bittorrent doesn't work like HTTP, I think you would benefit from taking a step back and looking at the bigger picture.

All protocols: http, ftp, samba, mega.nz, dc++ (nmdc) can do it and the torrent protocol can do it too. Here's your instruction: https://libtorrent.org/reference-Core.html#peer_request.

**Comment by master255** [comment]
@arvidn Okay. I started loading the torrent:
torrentHandle.setFlags(TorrentFlags.SEQUENTIAL_DOWNLOAD);
torrentHandle.setFlags(TorrentFlags.UPLOAD_MODE);
How can I perform after that: peer_request, and then automatically download the file to the end from the byte specified in peer_request?

**Comment by arvidn** [comment]
to send a request message that's not block aligned, you have to implement a peer_plugin (I posted a link to the documentation earlier)

**Comment by master255** [comment]
@arvidn I should use torrent_handle::add_extension() ?

**Comment by master255** [comment]
@arvidn 

> peer plugins are associated with a specific peer.

That's not what I need. I don't want a request for a peer, I want a request to a library. So she can decide which peer to request to download the data. 
I need peer**s**_request

**Comment by arvidn** [comment]
yes, that's one way to do it. You can also pass it in with `add_torrent_params`, to avoid a race condition. Or you could add a plugin to the session, which in turn can add plugins to every torrent added.

Here are some examples of plugins:

https://github.com/arvidn/libtorrent/blob/RC_1_2/src/ut_metadata.cpp
https://github.com/arvidn/libtorrent/blob/RC_1_2/src/ut_pex.cpp
https://github.com/arvidn/libtorrent/blob/RC_1_2/src/smart_ban.cpp

https://github.com/arvidn/libtorrent-webui/blob/cpp11-upgrade/src/file_requests.hpp
https://github.com/arvidn/libtorrent-webui/blob/cpp11-upgrade/src/file_requests.cpp

https://github.com/arvidn/libtorrent-webui/blob/cpp11-upgrade/src/file_downloader.hpp
https://github.com/arvidn/libtorrent-webui/blob/cpp11-upgrade/src/file_downloader.cpp

**Comment by arvidn** [comment]
> That's not what I need. I don't want a request for a peer, I want a request to a library. So she can decide which peer to request to download the data.
> I need peers_request

and I'm giving you pointers on how to implement that

**Comment by master255** [comment]
@arvidn I honestly don't understand how to write a plugin for a compiled library in c++.
Do I need to change the library's code?
Do I need to compile my extension?
Does the extension have to be written in c++?
How can I add an extension to the library? What method does it use?
What development environment do I need for this?
I use 4 different versions of the library: 
implementation project(path: ':jlibtorrent-android-arm64-1.2.3.0')
    implementation project(path: ':jlibtorrent-android-x86_64-1.2.3.0')
    implementation project(path: ':jlibtorrent-android-arm-1.2.3.0')
    implementation project(path: ':jlibtorrent-android-x86-1.2.3.0')
Do I need to compile 4 different extensions for this?

**Comment by arvidn** [comment]
> @arvidn I honestly don't understand how to write a plugin for a compiled library in c++.
> Do I need to change the library's code?

In general no, but it's possible that what you want to do specifically may require some change.

> Do I need to compile my extension?

From libtorrent's point of view, all its clients are C++, so yes. I would expect that the jlibtorrent wrapper doesn't support plugins written in java, as that would be an extraordinary amount of work. So; most likely yes.

> Does the extension have to be written in c++?

Given the assumption from above; most likely yes.

> How can I add an extension to the library? What method does it use?

[add_extension()](https://libtorrent.org/reference-Core.html#add_extension())

> What development environment do I need for this?

A C++ compiler.

> I use 4 different versions of the library:
> implementation project(path: ':jlibtorrent-android-arm64-1.2.3.0')
> implementation project(path: ':jlibtorrent-android-x86_64-1.2.3.0')
> implementation project(path: ':jlibtorrent-android-arm-1.2.3.0')
> implementation project(path: ':jlibtorrent-android-x86-1.2.3.0')
> Do I need to compile 4 different extensions for this?

Yes.

**Comment by master255** [comment]
@arvidn I'm sorry, but this is too complicated for me. I'll probably choose a different, more flexible library.

**Comment by master255** [comment]
@arvidn , Yesterday, I created this algorithm in my Android player app. My algorithm allows you to play video and download data from torrents in multithreaded mode.
And..:
1. If peer is one, then threads pass the connection to peer among themselves.
2. Writing different parts of a file to disk goes in multithreading mode and in different files. If there are a lot of peers, the writing to the disk goes in multithreading mode at the same time, if there is one peer, then one by one.
3. The speed of peers is memorized, for the fastest search of the fastest.
4. Data query is performed from a certain byte and there is no need to download the whole piece or block.

Now I feel that it was a good decision not to use your library. It's very conservative. I wrote 1k lines of code and it completely replaces several megabytes of your library.

**Comment by master255** [comment]
@arvidn There was a [big release](https://play.google.com/store/apps/details?id=com.media.library) yesterday. I used your library. I learned how to change it. Thank you!
It works on Sony Android TV. There are more bugs, but I'll fix them soon.
