### ISSUE TITLE
How to download the specified file in the torrent?

### ISSUE THREAD

**Issue by zbooa** [arvidn/libtorrent#4401]
There are many files in a torrent, but I only want some of them. How can I transfer values? How about the code? Thank you again.

**Comment by arvidn** [comment]
It sounds like you're looking for [file priorities](https://libtorrent.org/reference-Core.html#prioritize_files()). They can be set when [adding a torrent](https://libtorrent.org/reference-Core.html#file_priorities).

I don't know what you mean by "transferring values".

**Comment by zbooa** [comment]
> It sounds like you're looking for [file priorities](https://libtorrent.org/reference-Core.html#prioritize_files()). They can be set when [adding a torrent](https://libtorrent.org/reference-Core.html#file_priorities).
> 
> I don't know what you mean by "transferring values".

thank you , i mean how to set up that。
Open a torrent file, it includes many files and folders, but only wants to download some files or a little part files, not all files. Use file priorities, OK?

**Comment by arvidn** [comment]
yes, use file priorities
