### ISSUE TITLE
How to creat torrent from a magnet link and request to write an instance?

### ISSUE THREAD

**Issue by zbooa** [arvidn/libtorrent#4402]
This question has been mentioned here, but I can't realize it. Ask for help， thanks.

**Comment by arvidn** [comment]
use [parse_magnet_uri()](https://libtorrent.org/reference-Core.html#parse_magnet_uri()) to turn it into an add_torrent_params object, which you then add to the session.

**Comment by zbooa** [comment]
> use [parse_magnet_uri()](https://libtorrent.org/reference-Core.html#parse_magnet_uri()) to turn it into an add_torrent_params object, which you then add to the session.

thanks. i mean i want to create a .torrent file from magnet link....

**Comment by arvidn** [comment]
https://stackoverflow.com/questions/8689828/libtorrent-given-a-magnet-link-how-do-you-generate-a-torrent-file
