### ISSUE TITLE
Website docs typo? 

### ISSUE THREAD

**Issue by userdocs** [arvidn/libtorrent#4405]
https://www.libtorrent.org/building.html#building-with-bbv2

Is this a typo? `pic` should be `fpic` because if use `pic=on` i get an unknown option error but if i use `fpic=on` it builds with no error.  

![2020-03-08_15-50-48](https://user-images.githubusercontent.com/16525024/76166232-ff80ce00-6154-11ea-88fb-44b0d079217c.png)

**Comment by arvidn** [comment]
yes, that's a typo. thanks!

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/4407
