### ISSUE TITLE
Could not disable sequential downloading.

### ISSUE THREAD

**Issue by ruslanfedoseenko** [arvidn/libtorrent#441]
I've migrated to RC_1_1. 
I tried to download some media torrents(with mkv or avi files) and see that pieces are downloaded sequentialy even if i dont put torrent in seqential mode. switching off/on sequential mode got no result.
Also i tried to download some non media torrent and see that now pieces a chosen randomly. Is this a new feature?
Also found that if it is single file torrent than download is sequential.

**Comment by arvidn** [comment]
yes, this is a new feature. it's called auto_sequential and is documented here https://github.com/arvidn/libtorrent/blob/master/include/libtorrent/settings_pack.hpp#L648
