### ISSUE TITLE
about file_priorities，i have two issue

### ISSUE THREAD

**Issue by zbooa** [arvidn/libtorrent#4410]
In my think, the libtorrent have two place can setting it. 
A, the lt::add_torrent_params , can setting it when adding torrent.
B, after adding torrent, can setting it on return the lt::torrent_handle of torrent.
The difference is that the set time is different.
###
In general, which method should we use? How does the other method work ?
If add magnetlink,  the file_priorities how should it be set ?
Set it after received metadata of the magnetlink ? else ?
###
How to write  the code ? i cant get it. like mine. it my copy the test project. but i dont understand it.
`p.file_priorities.resize(1, lt::top_priority);`
Example :
If there are 4 files in the torrent,   a.txt, b.txt, c.txt, d.txt
I want to set it like this
a.txt >> lt::dont_download
b.txt >> lt::default_priority
c.txt >> lt::low_priority
d.txt >> lt::top_priority
How to write  the code ? And 
Is set using method A(set it on lt::add_torrent_params when adding torrent)
or B(after adding torrent, on the lt::torrent_handle ) ?
thank you for developer.

**Comment by arvidn** [comment]
> In general, which method should we use?

By default all files have priority 4. If that's the priority you want, don't set it in `add_torrent_params`. If you want some other priorities, set those in `add_torrent_params`.

If you later change your mind about the priorities, use the function on `torrent_handle` to set the new priorities.

> How does the other method work ?

I don't know what you mean. They both do the same things, just at different times.

> If add magnetlink, the file_priorities how should it be set ?
> Set it after received metadata of the magnetlink ? else ?

You can do either, it depends on what you want to have happen.

> How to write the code ? And
> Is set using method A(set it on lt::add_torrent_params when adding torrent)
> or B(after adding torrent, on the lt::torrent_handle ) ?
> thank you for developer.

Are you asking how to create and initialize a `std::vector`? You may want to take a look at https://www.cppreference.com.

```
params.file_priorities = std::vector<lt::download_priority>{lt::dont_download, lt::default_priority, lt::low_priority, lt::top_priority};
```

That's assuming the files are ordered in the order you mentioned them.

**Comment by zbooa** [comment]
> > In general, which method should we use?
> 
> By default all files have priority 4. If that's the priority you want, don't set it in `add_torrent_params`. If you want some other priorities, set those in `add_torrent_params`.
> 
> If you later change your mind about the priorities, use the function on `torrent_handle` to set the new priorities.
> 
> > How does the other method work ?
> 
> I don't know what you mean. They both do the same things, just at different times.
> 
> > If add magnetlink, the file_priorities how should it be set ?
> > Set it after received metadata of the magnetlink ? else ?
> 
> You can do either, it depends on what you want to have happen.
> 
> > How to write the code ? And
> > Is set using method A(set it on lt::add_torrent_params when adding torrent)
> > or B(after adding torrent, on the lt::torrent_handle ) ?
> > thank you for developer.
> 
> Are you asking how to create and initialize a `std::vector`? You may want to take a look at https://www.cppreference.com.
> 
> ```
> params.file_priorities = std::vector<lt::download_priority>{
>    lt::dont_download
>    , lt::default_priority
>    , lt::low_priority
>    , lt::top_priority};
> ```
> 
> That's assuming the files are ordered in the order you mentioned them.

Thank you for your patience. You make me quite understand its principle.
