### ISSUE TITLE
the .resume and the .torrent, difference?

### ISSUE THREAD

**Issue by zbooa** [arvidn/libtorrent#4411]
on examples, the client_test.exe create a .resume file
rename this file to a .torrent file, can download the src.
so, the difference between the two is ?

**Comment by arvidn** [comment]
the resume file contains information to resume a download or seeding of a torrent. A torrent files doesn't (necessarily).

See this [glossary](https://libtorrent.org/manual-ref.html#glossary). And the documentation of the [resume file format](https://libtorrent.org/manual-ref.html#fast-resume).

**Comment by zbooa** [comment]
> the resume file contains information to resume a download or seeding of a torrent. A torrent files doesn't (necessarily).
> 
> See this [glossary](https://libtorrent.org/manual-ref.html#glossary). And the documentation of the [resume file format](https://libtorrent.org/manual-ref.html#fast-resume).

That turned out to be the case. thank you for your reply.
