### ISSUE TITLE
What's the mistake?

### ISSUE THREAD

**Issue by zbooa** [arvidn/libtorrent#4425]
I use libtorrent to write a WIN32 program, which runs well.
This is a sudden problem today. It's a long time before the program suddenly appears, and it's not always there. Sometimes it's normal. Is it due to the problem of libtorrent or other reasons?
How to fix it?
`	// if production asserts are defined, don't abort, just print the error
#ifndef TORRENT_PRODUCTION_ASSERTS
#ifdef TORRENT_WINDOWS
	// SIGINT doesn't trigger a break with msvc
	DebugBreak();
#else
	// send SIGINT to the current process
	// to break into the debugger
	::raise(SIGABRT);
#endif
	::abort();
#endif`

SIGINT doesn't trigger a break with msvc   ??
DebugBreak()  ??

**Comment by arvidn** [comment]
are you saying you hit an assert? if so, the details of the assert should have been printed to the terminal

**Comment by zbooa** [comment]
[https://photos.app.goo.gl/TnmCstVLNocpDdV4A](url)
i do not know how fix it
