### ISSUE TITLE
I want to change the file name of parts. Where is the code that defines it?

### ISSUE THREAD

**Issue by zbooa** [arvidn/libtorrent#4460]
I test a download folder. I see the .parts file be create.
I want to change the .parts file name, no use the hash of torrent.
But I can not find the code that defines it. and where is it ? let me see, thanks, please.

**Comment by arvidn** [comment]
it's hard coded in libtorrent [here](https://github.com/arvidn/libtorrent/blob/RC_1_2/src/storage.cpp#L95). You can always change that if you're building libtorrent yourself.
If you have a compelling use case for this, maybe that would warrant this to be configurable.

**Comment by zbooa** [comment]
> it's hard coded in libtorrent [here](https://github.com/arvidn/libtorrent/blob/RC_1_2/src/storage.cpp#L95). You can always change that if you're building libtorrent yourself.
> If you have a compelling use case for this, maybe that would warrant this to be configurable.

yes , i have and i will try.  thank you.

**Comment by zbooa** [comment]
> it's hard coded in libtorrent [here](https://github.com/arvidn/libtorrent/blob/RC_1_2/src/storage.cpp#L95). You can always change that if you're building libtorrent yourself.
> If you have a compelling use case for this, maybe that would warrant this to be configurable.

I want it to be a configurable option. How does libtorrent load this .parts file? What code? thanks again !

**Comment by arvidn** [comment]
I'm not sure I know what you mean. but you can look around for where `m_part_file_name` is used.

**Comment by zbooa** [comment]
> I'm not sure I know what you mean. but you can look around for where `m_part_file_name` is used.

yes, thanks, i will do it.
