### ISSUE TITLE
save path not-english characters issue. Hope fix it.

### ISSUE THREAD

**Issue by zbooa** [arvidn/libtorrent#4462]
My test project use UNICODE.
When p.save_path that have not-english characters(like chinese characters[新建文件夹])
torrent task will create a gibberish(like this[ÐÂ½¨ÎÄ¼þ¼Ð]) directory for it. And This issue is very old old old.
and if the file-list of torrent have not-englist characters, I change the font-code only. This, I still can handle it.
But p.save_path issue, I can not find out the way.
Hope fix it. Or let me try.

**Comment by MassaRoddel** [comment]
If your project is UNICODE - shouldn't you use something like this to convert between char and wchar?
add_torrent_params X;
X.save_path = wchar_utf8((LPCTSTR)ZielPfad);

**Comment by zbooa** [comment]
> If your project is UNICODE - shouldn't you use something like this to convert between char and wchar?
> add_torrent_params X;
> X.save_path = wchar_utf8((LPCTSTR)ZielPfad);

wchar_utf8 ?? write function to do this ? can i see your code ?

**Comment by zbooa** [comment]
> If your project is UNICODE - shouldn't you use something like this to convert between char and wchar?
> add_torrent_params X;
> X.save_path = wchar_utf8((LPCTSTR)ZielPfad);

wchar_utf8 ?? write function to do this ? can i see your code ?

> If your project is UNICODE - shouldn't you use something like this to convert between char and wchar?
> add_torrent_params X;
> X.save_path = wchar_utf8((LPCTSTR)ZielPfad);

and i have not iconv_t !

**Comment by arvidn** [comment]
libtorrent use utf-8 internally. All strings you pass to it are expected to be UTF-8. windows has functions to convert from UTF-16 if that's what you use internally

**Comment by zbooa** [comment]
> libtorrent use utf-8 internally. All strings you pass to it are expected to be UTF-8. windows has functions to convert from UTF-16 if that's what you use internally

i will find the way. thank you
