### ISSUE TITLE
Cannot connect to https trackers

### ISSUE THREAD

**Issue by skuizy** [arvidn/libtorrent#4478]
libtorrent version (or branch): RC_1_2

platform/architecture: armhf

compiler and compiler version: launchpad daily build

Every https tracker is failing with the folowing error message : Error: tlsv1 alert protocol version

**Comment by arvidn** [comment]
does your "RC_1_2" include this patch? https://github.com/arvidn/libtorrent/pull/4466

**Comment by skuizy** [comment]
It didn't.

It's working fine now that it does.

Thanks
