### ISSUE TITLE
Cant build libtorrent 1.0.81 / 1.1.0 - error: Boost.Python library not found.

### ISSUE THREAD

**Issue by lethanhviet** [arvidn/libtorrent#448]
Attempting to build libtorrent on clean debian 8 server with boost 1.55. I have installed libboost-python-dev, but libtorrent during configure cannot find it.

root@Debian-83-jessie-64-minimal ~/libtorrent # ./configure --enable-python-binding --with-libgeoip --with-libiconv --disable-debug --enable-logging=default --with-boost-libdir=/usr/lib/x86_64-linux-gnu
configure: WARNING: unrecognized options: --with-libgeoip
checking whether make supports nested variables... yes

Building libtorrent-rasterbar 1.1.0

Checking for a C/C++ compiler to use:
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking whether gcc and cc understand -c and -o together... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking whether g++ understands -c and -o together... yes

Checking system type:
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu

Initializing Automake:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking dependency style of g++... gcc3

Initializing Libtool:
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate

Checking for posix thread support:
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -lpthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking whether to check for GCC pthread/shared inconsistencies... yes
checking whether -lpthread fixes that... yes
Checking for visibility support:
checking for __attribute__((visibility("hidden")))... found
yes

Checking for boost libraries:
checking for boostlib >= 1.47... yes
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... yes
checking whether the Boost::Chrono library is available... yes
checking for exit in -lboost_chrono... yes
checking whether the Boost::Random library is available... yes
checking for exit in -lboost_random... yes

Checking for pkg-config:
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.20... yes

Checking for functions and headers:
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for clock_gettime... yes

Checking build options:
checking whether deprecated functions should be enabled... yes
checking whether debug build should be enabled... no
checking whether invariant check should be enabled... no
checking whether logging to disk should be enabled... yes
checking whether disk activity logging should be enabled... no

Checking features to be enabled:
checking whether encryption support should be enabled... yes
configure: encryption support: now checking for the OpenSSL library...
checking for pkg-config... /usr/bin/pkg-config
checking whether compiling and linking against OpenSSL works... yes
checking whether dht support should be enabled... yes
checking whether pool allocators should be enabled... yes

Checking for extra build files:
checking whether example files should be built... no
checking whether test files should be built... no
checking whether python bindings should be built... yes
checking for a Python interpreter with version >= 2.4... python
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... linux2
checking for python script directory... ${prefix}/lib/python2.7/dist-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/dist-packages
checking for python2.7... (cached) /usr/bin/python
checking for a version of Python >= '2.1.0'... yes
checking for a version of Python >= '2.4'... yes
checking for the distutils Python package... yes
checking for Python include path... -I/usr/include/python2.7
checking for Python library path... -L/usr/lib -lpython2.7
checking for Python site-packages path... /usr/lib/python2.7/dist-packages
checking python extra libraries... -lpthread -ldl  -lutil -lm
checking python extra linking flags... -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
checking consistency of all components of python development environment... yes
checking whether the Boost::Python library is available... yes
checking for main in -lboost_python... no
checking for main in -lboost_python... (cached) no
configure: error: Boost.Python library not found. Try using --with-boost-python=lib.

Here is the config log file:
[config.zip](https://github.com/arvidn/libtorrent/files/113384/config.zip)

**Comment by ssiloti** [comment]
This is a known bug fixed by 5bf3e62fe5bb024fce39e265f2b22bfa99fb1b3e which will be in 1.0.9.

**Comment by lethanhviet** [comment]
Thx so much @ssiloti working now.

**Comment by lethanhviet** [comment]
hi @ssiloti sorry but after successfully built, importing libtorrent results in a new error:

root@Debian-83-jessie-64-minimal ~ # python -c "import libtorrent; print libtorrent.version"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/local/lib/python2.7/dist-packages/libtorrent.so: undefined symbol: _ZTIN5boost6python15instance_holderE

**Comment by lethanhviet** [comment]
ok, so I'm able to get libtorrent working now, but there's this warning:

python -c "import libtorrent; print libtorrent.version"
-c:1: RuntimeWarning: to-Python converter for boost::shared_ptr<libtorrent::alert> already registered; second conversion method ignored.
1.0.8.0

**Comment by ssiloti** [comment]
I'm not seeing that, but I'm using boost 1.60 and I suspect it is related to using a version of boost less than 1.60 with 5330ba5af717b983e456be9f576d66b78d9ca214. The warning is probably harmless, but I guess we could add a BOOST_VERSION check around the `register_ptr_to_python` call if it's causing problems.

**Comment by arvidn** [comment]
I struggled with this problem a few weeks ago, in RC_1_0. Rather than fully understanding it, I gave up and made a crude assumption (based on my few observations) that this behavior depended on windows vs. non-windows. I tested osx, linux and windows, and experimented with various solutions, but no matter what I did, I would either break windows or osx and linux. Finally I simply ifdefed the code to make it work everywhere.

presumably my assumption was incorrect. I seem to recall that at least one non-windows platform used the same version of boost as windows though, but I might be wrong. perhaps this is tied to boost version instead.

**Comment by arvidn** [comment]
here's that pull request. @lethanhviet could you try to remove the ifndef _MSC_VER to see if that works for you? If so, perhaps that condition should be based on BOOST_VERSION instead.

https://github.com/arvidn/libtorrent/pull/387/files

**Comment by arvidn** [comment]
sorry, I just realized I repeated what ssiloti said :P, and I probably negated what I actually meant. anyway, I'm sure you get it. the warning says something is already registered, and the line in the code registers it. You want the condition to make it _not_ run for you presumably.

**Comment by arvidn** [comment]
I believe this fixes it: https://github.com/arvidn/libtorrent/pull/469

**Comment by arvidn** [comment]
merged into RC_1_1 here https://github.com/arvidn/libtorrent/pull/470

**Comment by ishanjain28** [comment]
@lethanhviet How did you Fixed 

```
ImportError: /usr/lib64/python3.5/site-packages/libtorrent.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE
```

I am on Fedora and I finally managed to compile libtorrent for python3 but now I am getting this error.. 

@arvidn Can you help me in building it for python3? 
Here are the steps i followed. 

```
1. Cloned repository.
2. cd libtorrent
3. ./configure
4. make 
5. make install 
6. PYTHON=/usr/bin/python3.5 ./configure PYTHON_LDFLAGS="$(python-config --libs)" --prefix=/usr --enable-python-binding --with-boost-python=boost_python3
7. cd bindings/python
8. make
9. sudo make install

```

If I skip steps 3, 4 and 5 I start getting another error, Something like, 

```
/usr/bin/ld: -ltorrent-rasterbar not found
```
What am I doing wrong here?

**Comment by arvidn** [comment]
it looks like the version of boost installed on your system perhaps is built against python2. I believe that symbol that's missing is supposed to be provided by ``boost_python.so``

**Comment by ishanjain28** [comment]
Previously I had installed ```boost-devel``` which uses python2, And now I cleaned up and removed everything and then reinstalled ```boost-python3-devel``` and did everything again, But it still gives the same error.

**Comment by ishanjain28** [comment]
Update:
I deleted all the libtorrent-rasterbar files ```/usr/local/lib``` and ```/usr/lib64/python3.5/site-packages/libtorrent.cpython-35m-x86_64-linux-gnu.so``` and then went through all the build steps again. 

Now I can import it in Python3.5 without any problem. But now it gives an error that says ```AttributeError: module 'libtorrent' has no attribute 'session_settings'```. 

Was something changed in the latest version and the version that is installed by doing ```apt-get install python3-libtorrent```? 

Should I create a new issue for this now? 

Also, Project [Link](https://github.com/torr-share/torr-share-webapp)

**Comment by arvidn** [comment]
yeah, session_settings was deprecated a while ago. It's possible that your build is made with deprecated functions disabled or that you're using a new enough version that it has actually been removed (in favor of setting_pack)

**Comment by ishanjain28** [comment]
Yes, I built it from the main branch of this repository, So it is the latest version. I'll use ```settings_pack``` instead. 

Thank you so much for quick replies and helping me.
