### ISSUE TITLE
libtorrent https://github.com/arvidn/libtorrent/commit/9ac4e6eed88c1ea1e6cdb6865889320164ad0b85 listening on bound interface but not making outgoing connections through it

### ISSUE THREAD

**Issue by rwasef1830** [arvidn/libtorrent#4482]
Hey @arvidn 
I just compiled qBittorrent https://github.com/qbittorrent/qBittorrent/tree/v4_2_x with libtorrent https://github.com/arvidn/libtorrent/commit/9ac4e6eed88c1ea1e6cdb6865889320164ad0b85 and even though I selected an interface and one of its addresses to bind, libtorrent does not use it when making outgoing connections.

It is listening on the correct interface and address but making actual outgoing connections to peers over the primary interface IP (not the explicitly selected one) (seen using `lsof -i tcp -i udp -n -L | grep qbitt`) in the shell.

**Comment by arvidn** [comment]
thanks for testing! Is this a regression with that patch specifically? I should review it to make sure there aren't any success paths where `bind()` isn't called.

**Comment by rwasef1830** [comment]
@arvidn 

OK, there's 2 strange behaviors that are affected by the patch. But overall the patch makes it more broken.

1. With the patch: 
- Bind interface + Bind address ---> No effect for outgoing (only honored by listen socket)
- Bind any interface + Bind address ---> No effect for outgoing (only honored by listen socket)

2. Without that patch: 
- Bind interface + Bind address ---> Outgoing connection uses correct IP (seen by lsof), listen socket listening on correct address.
- Bind any interface + Bind address --> No effect for outgoing (only honored by listen socket)

I think there is a missing or broken code path for outgoing connections. If only bind address is specified, outgoing connections should use it. If more than 1 interface has the same bind address, then outgoing connections should be distributed over all interfaces having it.

In both cases, the patch breaks outgoing connections. I'm not actually sure why there is a separate bind interface and bind address setting... It makes things very confusing.

**Comment by arvidn** [comment]
if `SO_BINDTODEVICE` succeeds, the `bind()` call will be using `0.0.0.0`. Is that a problem? Presumably binding to the device will still be in affect.

**Comment by rwasef1830** [comment]
I don't quite follow...
What I can say is https://github.com/arvidn/libtorrent/commit/9ac4e6eed88c1ea1e6cdb6865889320164ad0b85 causes outgoing connections to not honor any bind settings at all.

Without that commit, outgoing connections have the correct source IP only if *both* the interface and address to bind are selected in qBittorrent.

If only the IP is selected in qBittorrent, outgoing connections still have the wrong source IP.

**Comment by arvidn** [comment]
On Mon, Mar 30, 2020 at 2:43 PM Raif Atef <notifications@github.com> wrote:

> I don't quite follow...
> What I can say is 9ac4e6e
> <https://github.com/arvidn/libtorrent/commit/9ac4e6eed88c1ea1e6cdb6865889320164ad0b85>
> causes outgoing connections to not honor any bind settings at all.
>

Are you sure that's the commit that broke it?
and by "bind settings", you mean outgoing_interfaces, right?
what seems strange about this is that the call to bind() removed in that
patch, is made immediately before it as well; right where
bind_socket_to_device() returns.

> Without that commit, outgoing connections have the correct source IP only
> if *both* the interface and address to bind are selected in qBittorrent.
>
I'm not entirely familiar with how qbittorrent maps its "bind" and
"interface" settings to the libtorrent settings. In libtorrent there are
two settings listen_interfaces and outgoing_interfaces (and the latter is a
bit redundant these days, one day maybe I'll turn that to a boolean, and
use the interfaces specified as the listen interfaces).

If only the IP is selected in qBittorrent, outgoing connections still have
> the wrong source IP.
>
is this listen_interfaces or outgoing_interfaces, do you know?

-- 
Arvid Norberg

**Comment by arvidn** [comment]
On Mon, Mar 30, 2020 at 3:07 PM Arvid Norberg <arvid.norberg@gmail.com>
wrote:

> On Mon, Mar 30, 2020 at 2:43 PM Raif Atef <notifications@github.com>
> wrote:
>
>> I don't quite follow...
>> What I can say is 9ac4e6e
>> <https://github.com/arvidn/libtorrent/commit/9ac4e6eed88c1ea1e6cdb6865889320164ad0b85>
>> causes outgoing connections to not honor any bind settings at all.
>>
> Btw, are you talking about uTP sockets?
I was just focused on TCP connections, because that's what the github
ticket is talking about. But it's possible that patch would have broken uTP.

-- 
Arvid Norberg

**Comment by arvidn** [comment]
I cannot reproduce this issue. Can you help me? your `lsof` command is helpful in verifying the local endpoint of sockets.

I'm testing with this command line:

```
./client_test -f client-test.log -s . --alert_mask=error,connect,tracker --outgoing_interfaces=tun0 --listen_interfaces=tun0:8888 ubuntu-19.10-desktop-amd64.iso.torrent
```

and the peer list shows the local endpoint (correctly) as `10.51.10.6`, which is my VPN IP address.

The lsof command:

```
lsof -i tcp -i udp -n -L | grep client_t
```

Shows the outgoing connections to be bound to the VPN IP as well:

```
client_te 68960 arvid    8u  IPv4 906643      0t0  TCP 10.51.10.6:8888 (LISTEN)
client_te 68960 arvid   10u  IPv4 906644      0t0  UDP 10.51.10.6:8888
client_te 68960 arvid   11u  IPv6 906646      0t0  TCP [fe80::4830:521c:fb5d:8f6b]:8888 (LISTEN)
client_te 68960 arvid   12u  IPv6 906647      0t0  UDP [fe80::4830:521c:fb5d:8f6b]:8888
client_te 68960 arvid   13u  IPv4 906679      0t0  UDP 10.51.10.6:54214
client_te 68960 arvid   14u  IPv4 906680      0t0  UDP 10.51.10.6:1900
client_te 68960 arvid   15u  IPv4 906681      0t0  UDP 10.51.10.6:36445
client_te 68960 arvid   16u  IPv4 906682      0t0  UDP *:6771
client_te 68960 arvid   17u  IPv6 906683      0t0  UDP *:6771
client_te 68960 arvid   19u  IPv4 900924      0t0  TCP 10.51.10.6:47067->68.204.189.151:51413 (ESTABLISHED)
client_te 68960 arvid   23u  IPv4 900960      0t0  TCP 10.51.10.6:54813->91.12.53.117:51413 (SYN_SENT)
```

**Comment by rwasef1830** [comment]
With this command:

```
~/bin/client_test -f client-test.log -s . --alert_mask=error,connect,tracker --listen_interfaces=5.79.67.9:61888 ../ubuntu-18.04.4-server-amd64.iso.torrent
```
I get correct listen IP but wrong outgoing connection IP.

With this command
```
~/bin/client_test -f client-test.log -s . --alert_mask=error,connect,tracker --outgoing_interfaces=5.79.67.9  --listen_interfaces=5.79.67.9:61888 ../ubuntu-18.04.4-server-amd64.iso.torrent
```
I get correct listen IP and correct outgoing connection IP.

My server has a single interface eth4 but with many IPs assigned, one of which is 5.79.67.9

-- Ok so I guess the problem is actually in qBittorrent not setting libtorrent outgoing_interfaces properly. I will check there.

**Comment by arvidn** [comment]
thanks for testing! It's still possible there's an issue in libtorrent, but it's hard to say before we know more about what settings qbt set
