### ISSUE TITLE
Improve usability of lt::bencode()

### ISSUE THREAD

**Issue by Chocobo1** [arvidn/libtorrent#4486]
**Please provide the following information**

libtorrent version (or branch):
RC_1_2

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I'm trying to use `lt::bencode()` to output to [QSaveFile](https://doc.qt.io/qt-5/qsavefile.html) without deploying a buffer in the middle. The problem is `bencode()` expects a output iterator type but sadly Qt only have [QDataStream](https://doc.qt.io/qt-5/qdatastream.html) and I'll need to write a wrapper.
So the idea is, what about ditching the output iterator type requirement (or add another overload) and let `bencode()` can output on any type that has an `operator<<(char)`? I imagine this way `bencode()` could match easily to more container types or other functional types.
What do you think?

**Comment by Chocobo1** [comment]
I found out later that `QDataStream` isn't doing exactly what I had expected, so I'll need to write the wrapper anyway and that also means this issue isn't much relevant to me anymore. Feel free to close it.

Also I noticed that "output iterator type" is actually this: https://en.cppreference.com/w/cpp/named_req/OutputIterator
I suppose it is worth it to mention it at least in `bencode()` documentation.

**Comment by arvidn** [comment]
I think encoding to an `ostream_iterator` is not really a very common use case (because if you don't disable filtering of white space, it won't work). I would expect it to be much more common to encode to a `back_insert_iterator`, like this:

```
std::vector<char> buffer;
lt::bencode(std::back_inserter(buffer), entry);
```

I'm also not convinced this flexibility really warrants the additional complexity of having this be a template.

QDataStream doesn't look like a flat buffer, is it? It looks like, for example, using `writeBytes()` would yield a different result than to repeatedly call `operator<<` with the same bytes. I could be wrong though. It just gives me the impression there's some wrapping of the data (with higher level concepts like version).

**Comment by Chocobo1** [comment]
>I think encoding to an ostream_iterator is not really a very common use case (because if you don't disable filtering of white space, it won't work). 

This is new to me, however I only found `std::istream_iterator` would skip whitespace when reading and didn't found anything with `ostream_iterator`...

>QDataStream doesn't look like a flat buffer, is it? 

At first I thought it was, but in reality it is not. It is a class for doing object serialization.

>I would expect it to be much more common to encode to a back_insert_iterator, like this:
>std::vector<char> buffer;
>lt::bencode(std::back_inserter(buffer), entry);

Yes, when most of the time the encoded data size is manageable. However when user has less system memory or he is encoding a very large data then problem arise.

>I'm also not convinced this flexibility really warrants the additional complexity of having this be a template.

I imagine it won't be difficult, yet I haven't thought about the drawbacks. It is up to you. :)

**Comment by Chocobo1** [comment]
>I would expect it to be much more common to encode to a back_insert_iterator, like this:
>std::vector buffer;
>lt::bencode(std::back_inserter(buffer), entry);

BTW, do you think it is possible to provide a function that will predict the output size of bencoding? So that I can reserve memory for `buffer` and avoid repetitive resizing.

**Comment by arvidn** [comment]
I think the bulk of a torrent file are the filenames and the piece hashes. Piece hashes is easy to predict (num_pieces * 20) the filenames, you would probably have to go through them all and sum the full filename and path length.
