### ISSUE TITLE
Question about dht and utp

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#4493]
I can't find it anywhere. Are DHT and UTP using the same UDP port or different? In your library

**Comment by master255** [comment]
@arvidn ?

**Comment by arvidn** [comment]
yes, uTP and DHT use the same UDP socket, as well ass UDP trackers.

**Comment by master255** [comment]
@arvidn How do you differentiate DHT packets from UTP? Are there any characteristics?

**Comment by arvidn** [comment]
DHT packets are bencoded. they always start with `d` and end with `e`. uTP packets always have the uTP packet header, which has some specific characteristics too

**Comment by master255** [comment]
@arvidn How hard you did it. Thank you. Let's keep programming.
