### ISSUE TITLE
Python bindings item with empty key in libtorrent.default_settings() dict

### ISSUE THREAD

**Issue by fonic** [arvidn/libtorrent#4499]
**libtorrent version (or branch):**
Git RC_1_2

**platform/architecture:**
Gentoo Linux amd64

**compiler and compiler version:**
GCC 9.2.0
Python 3.6.10

When compiling/using libtorrent with _deprecated functions disabled_, there is an item with an empty key in the default settings dictionary:

```
$ python
>>> import libtorrent
>>> libtorrent.default_settings()
{'user_agent': 'libtorrent/1.2.5.0', 'announce_ip': '', '': False, 'handshake_client_version': '', 'outgoing_interfaces': '', 'listen_interfaces': '0.0.0.0:6881,[::]:6881', 'proxy_hostname': '', 'proxy_username': '', 'proxy_password': '', 'i2p_hostname': '', 'peer_fingerprint': '-LT1250-', [...] }
```
-> see item right after _announce_ip_

**Comment by arvidn** [comment]
ah. I bet there's more than one actually, but presumably the last one overwrites the previous ones. When disabling deprecated functions, I still preserve the indices of all settings, so there will be gaps. I have failed to take that into account in the python binding

**Comment by arvidn** [comment]
does this look reasonable? https://github.com/arvidn/libtorrent/pull/4501

**Comment by fonic** [comment]
Code looks good and testing shows empty key is gone.
