### ISSUE TITLE
libtorrent uses transient i2p destinations

### ISSUE THREAD

**Issue by majestrate** [arvidn/libtorrent#45]
there doesn't seem to be a way to have libtorrent persist i2p destination between restarts as it uses DESTINATION=TRANSIENT

https://github.com/arvidn/libtorrent/blob/master/src/i2p_stream.cpp#L507

**Comment by arvidn** [comment]
what is the alternative? to pick a name and store/restore it across sessions?

**Comment by majestrate** [comment]
the alternative value for parameter DESTINATION is a base64 encoded destination private key. 
it should be able to remember it for each session instead of generating a new one each time.

**Comment by arvidn** [comment]
Would this be something appropriate for the session settings you think? If so, it would be saved along with session state. Maybe if it isn't set the session could generate one. Is it complicated to generate a key, or is it preferable to have the user input the key to be used?

**Comment by majestrate** [comment]
it sounds like something the session should handle.

https://geti2p.net/en/docs/api/samv3

acording to the api docs for sam, to generate a new destination use give 'DESTINATION=TRANSIENT' and it returns the private keys.

**Comment by aaannndddyyy** [comment]
transient is good for anonymity......

**Comment by majestrate** [comment]
@aaannndddyyy it is but freedom of choice is also good to have. In addition there needs to be a way to have dht bootstrap servers.

**Comment by aaannndddyyy** [comment]
makes sense. so as long as transient will still be possible and maybe even default, I'm all for it
