### ISSUE TITLE
Default cache size documentation problem

### ISSUE THREAD

**Issue by FranciscoPombal** [arvidn/libtorrent#4502]
**Please provide the following information**

libtorrent version (or branch): RC_1_2

platform/architecture: N/A

compiler and compiler version: N/A

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Related to https://github.com/qbittorrent/qBittorrent/issues/12336.

The table in the documentation says (number of 16 KiB blocks):

name | type | default
-- | -- | --
cache_size | int | 2048

but in the code:
- `m_max_use` is initialized like this to `64`
- if the amount of physical RAM cannot be determined, it is set to `1024` (the documentation text also states this further down):
    > If the amount of physical RAM cannot be determined, it's set to 1024 (= 16 MiB).

In neither case does it default to `2048`.

**Comment by arvidn** [comment]
The logic to set the cache size based on the amount of physical RAM is only triggered if `settings_pack::cache_size` is -1, right? and that's not default.

I don't see a code path where `m_max_use` is left as its initialized value of 64. In the `disk_io_thread` constructor, `settings_updated()` is called, specifically to trigger the initial value of `m_max_use`. It will in turn call `block_cache::set_settings()` which will call `disk_buffer_pool::set_settings()` which does this initialization.

As far as I can tell, `m_max_use` is indeed set to 2048 by default.

**Comment by arvidn** [comment]
I see, the qbt ticket is specifically about the auto case. I agree that the 1024 there should *at least* be the same as the regular default.

**Comment by arvidn** [comment]
@FranciscoPombal is there any action I should take on this ticket still?

**Comment by FranciscoPombal** [comment]
@arvidn 
I think everything has been addressed, thanks. Relevant commit for future reference: https://github.com/arvidn/libtorrent/commit/6c880159c927f87ae4013e32023eb89a5336b5a4
