### ISSUE TITLE
Can it support normal HTTP downloads?

### ISSUE THREAD

**Issue by zbooa** [arvidn/libtorrent#4503]
Libtorrent support normal HTTP downloads?
Like https://i.loli.net/2019/07/27/5d3b31efed87a94133.jpg

**Comment by arvidn** [comment]
what's the question exactly?

**Comment by zbooa** [comment]
> what's the question exactly?

I mean, can libtorrent only download torrent and magnet ? HTTP is not supported ?

**Comment by arvidn** [comment]
libtorrent supports the two main kinds of HTTP seeding. That still requires a torrent file though
