### ISSUE TITLE
Follow BEP27 properly

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4504]
**Please provide the following information**

libtorrent version (or branch):
RC_1_2

Feature:

Peer list should be dropped(also block incoming requests from unknown peers) when user makes any changes to the tracker on a private torrent. Currently it’s possible to ghost leech in private torrents by removing the tracker/editing it to some rubbish. If user deletes/edits a tracker in a private torrent then empty the peer list and wait for a working tracker to be readded instead of continuing download/upload.

**Comment by an0n666** [comment]
According to BEP27, on private torrents you must not make any connections with peers outside of the list returned by the tracker. And if a tracker gets changed then you must disconnect all peers and only accept connections from peers returned by the new tracker. Libtorrent doesn’t seem to be conforming to BEP27
http://bittorrent.org/beps/bep_0027.html

**Comment by an0n666** [comment]
@FranciscoPombal 
is there any settings in qBt which allows peers outside of the peer list to make incoming connections? In utorrent/bittorrent I found that it doesn’t accept connections outside of peer list in private torrents. Which is the expected behaviour since our only source of peers in a private torrent is the tracker. But in qBt I’m seeing that it accepts connection from anyone even on private torrents.

**Comment by FranciscoPombal** [comment]
@an0n666 I don't think there is any setting in qBittorrent that controls that. Like you said, I'd say this is most likely something for libtorrent to fix.

**Comment by an0n666** [comment]
I think libtorrent takes the approach of assuming every peer that initiates an incoming connection to have found the peer details from the tracker. This might be a reasonable approach to allow new peers to make incoming connections before the next tracker announce. But it has the a loophole where one can guess the IP:port of a peer and make a connection without announcing to the tracker. 

The main concern however is about the peer list that remains intact after a tracker gets deleted/edited. Basically allowing the user to continue ghost leeching.

**Comment by an0n666** [comment]
@arvidn 
Does libtorrent provide a way of clearing the peer list from the client side? 
Like in utorrent one can clear the peer list manually. If there’s a function then maybe it can be used to automatically clear peer list as well after edit/delete.

Does libtorrent have any measures against connecting to unknown peers in a private torrent? If not, could it be added as a configurable feature? Like ‘Do not accept connections from outside of peer list’(obtained from tracker) in private torrents.

**Comment by arvidn** [comment]
> Does libtorrent provide a way of clearing the peer list from the client side?

Yes, by saving resume data, removing the torrent, clearing the peer list in the resume data (in `add_torrent_params`) and then re-add the torrent.

> Does libtorrent have any measures against connecting to unknown peers in a private torrent?

No, and I don't believe any *reasonable* such measures exist. I'm open to suggestions though.

private trackers is (and have always been) a hack that relies on most people not wanting to or figuring out how to circumvent the measures.

**Comment by an0n666** [comment]
> Yes, by saving resume data, removing the torrent, clearing the peer list in the resume data (in `add_torrent_params`) and then re-add the torrent.
> 

Sorry but that doesn't sound convenient. I thought a function would be already built into the library for clearing the peer list.

**Comment by arvidn** [comment]
what would be a reasonable behavior in this regard? An function to disconnect all peers and clear peer list, or some additional behavior to private torrents?

**Comment by arvidn** [comment]
would it not be more reasonable for the client to disable the ability to change tracker for private torrents? Is there any legitimate use case for that?

**Comment by arvidn** [comment]
another thing to consider is that tracker URLs are not hashed by the info-hash, so they can quite easily be changed and removed from the .torrent file itself. In this case, libtorrent won't notice it has happened, and you would still download the torrent (based on peers from the resume data).

So, perhaps peers should be removed from the resume data for private torrents as well.

**Comment by an0n666** [comment]
> would it not be more reasonable for the client to disable the ability to change tracker for private torrents? Is there any legitimate use case for that?

Private torrents contain a passkey in the tracker URL. If someone resets it for some reason, they have to update the tracker URL. So there are legitimate use cases.

**Comment by arvidn** [comment]
I'm open to suggestions for how to address these issues. In general I would prefer if special case logic for private trackers could stay on the client side (although I realize there is quite a lot of such special case in libtorrent already).

Perhaps all such special cases should be documented somewhere too.

**Comment by an0n666** [comment]
> what would be a reasonable behavior in this regard? An function to disconnect all peers and clear peer list, or some additional behavior to private torrents?

If tracker is edited/deleted on a private torrent:
#1. Disconnect all peers
#2. Clear the peer list from resume data

These are main issues that require to be addressed. 

There’s a 3rd issue which is kinda strict and many clients follow that:
Do not accept incoming connections from peers outside of peer list on a private torrent.

**Comment by an0n666** [comment]
And in private torrents do not save peer list to resume data.

**Comment by arvidn** [comment]
> Do not accept incoming connections from peers outside of peer list on a private torrent.

that assumes the swarm is small, or the tracker returns very large peer lists. If those aren't true, such logic would break really badly. Is it safe to assume private trackers always return the full peer list?

**Comment by an0n666** [comment]
> > Do not accept incoming connections from peers outside of peer list on a private torrent.
> 
> that assumes the swarm is small, or the tracker returns very large peer lists. If those aren't true, such logic would break really badly. Is it safe to assume private trackers always return the full peer list?

No. In most trackers the list is limited to 50-200 or controlled by the num_want parameter.
If it’s a breaking feature then at least the first two should be implemented.
Or apply that logic only when a working tracker is not present.

**Comment by arvidn** [comment]
could someone give this a try? https://github.com/arvidn/libtorrent/pull/4663

**Comment by arvidn** [comment]
It requires the client to call this new function when changing the trackers on a private torrent too

**Comment by an0n666** [comment]
@arvidn I justed added this function to qbt and tested it.
Here's the results:
Peer list gets cleaned, connected peers get disconnected..
But but, they almost instantly connect back due to incoming connections..So this isn't doing any good :(

**Comment by arvidn** [comment]
depending on who you ask, that might be super good :)
What would you want to happen? qbt *could* add all existing peers to the ban-list. But I'm not sure that would help anyone.

qbt could also change listen port, but that clearly would affect other torrents.

**Comment by an0n666** [comment]
Is there any way to not accept incoming connections if a private torrent which has no trackers.

**Comment by an0n666** [comment]
It’s a good solution if you’re behind a NAT. But public IP users will continue to get connections from other peers. I think you should merge it. It’s better than nothing.

**Comment by arvidn** [comment]
you can set the max number of connections per torrent, if you set it to 0 incoming connections will be rejected.

**Comment by an0n666** [comment]
@arvidn setting it to 0 seem to be not working. When I set to 0 I get unlimited connections. But when I set it to 1 I can connect with only 1 peer. Strange issue.

**Comment by an0n666** [comment]
Closing this since the main issue has been addressed.

**Comment by an0n666** [comment]
Closing this since the main issue has been addressed.

**Comment by ckcr4lyf** [comment]
From reading the PRs and history, it seems the issues resolved are:
> Not allowing users to add peers in private torrents
> Not allowing adding new trackers to a private torrent

But the third one - "on private torrents you must not make any connections with peers outside of the list returned by the tracker", this has not been, correct? Specifically for incoming connections - they may be accepted from a peer which was not returned in a previous announce to the tracker?

Blocking such connections would not be ideal, given how private swarms work, especially in the initial period

**Comment by arvidn** [comment]
> But the third one - "on private torrents you must not make any connections with peers outside of the list returned by the tracker", this has not been, correct?

I don't understand what you're asking, but you're right that it would not be practical to require every peer to know about every other peer up-front. For example, joining a swarm would require you wait 30 minutes (or 15 on average) until *other* peers know about you before you can actually connect to anyone.

**Comment by ckcr4lyf** [comment]
Sorry, what I meant was, this "change" was not made to libtorrent, while the other two were, correct? Or was it only client-side in qBittorrent (from the referenced issue in this thread)

> For example, joining a swarm would require you wait 30 minutes (or 15 on average) until other peers know about you before you can actually connect to anyone.

This is exactly what I was going for. Glad it's considered undesirable (at least by default).
