### ISSUE TITLE
i2p support is broken in libtorrent-1.2.5

### ISSUE THREAD

**Issue by susanwl** [arvidn/libtorrent#4511]
Hey, I have tried using slightly modified `simple_client.py` for downloading i2p torrents with the `libtorrent-1.2.5`. However, the download failed since the libtorrent was unable to resolve i2p trackers hostnames:
```
Host not found (non-authoritative), try again later ""
```

I have tested the same client with `libtorrent-1.1.14` and it worked perfectly, so apparently there was some regression after that version. I think that at least part of issue is caused by the commit 592544f30 `fix some PVS studio warnings`, since it changes `http_connection.cpp::start` logic from
```
if (i2p) {
    // i2p case
}
else {
    // non i2p case
}
m_hostname = hostname;
```

into
```
if (i2p) {
    // i2p case
}
else {
    m_hostname = hostname;
}
    // non i2p case
```

But, unfortunately reverting this change alone does not fix i2p torrent downloading.

libtorrent version (or branch): 1.2.5
platform/architecture: Linux x86_64
compiler and compiler version: gcc-9.3.0

**Comment by arvidn** [comment]
thanks for the report. What's really needed for i2p support to stay stable is a test. I think it's kind of a fringe feature still and so it hasn't received much attention. I think if there were similar tests to how socks5 is tested (in simulations) it would stay much more stable.

**Comment by arvidn** [comment]
this is addressed here: https://github.com/arvidn/libtorrent/pull/7356

**Comment by Vort** [comment]
@arvidn should #2530 be closed as well?
