### ISSUE TITLE
segmentation fault with a special resume file

### ISSUE THREAD

**Issue by beroal** [arvidn/libtorrent#4513]
libtorrent version (or branch): 
1.2.5

platform/architecture: Linux 5.5.13-arch2-1 #1 SMP PREEMPT Mon, 30 Mar 2020 20:42:41 +0000 x86_64 GNU/Linux

I have a program in Python that writes a resume file for "0.torrent", then adds the description of "1.torrent" with that resume file to a session. I think that the resume data should be rejected by the library. At least, the previous versions of the library did so. Instead, the library exits with a segmentation fault.

I do not attach my program because it is quite big. I attached the torrent files and the resume file. The extension "docx" is added so GitHub accepts the files.

[bt2pd.resume.docx](https://github.com/arvidn/libtorrent/files/4446881/bt2pd.resume.docx)
[0.torrent.docx](https://github.com/arvidn/libtorrent/files/4446883/0.torrent.docx)
[1.torrent.docx](https://github.com/arvidn/libtorrent/files/4446884/1.torrent.docx)

**Comment by arvidn** [comment]
thanks for the report!

**Comment by arvidn** [comment]
If you have a chance, please give this patch a try: https://github.com/arvidn/libtorrent/pull/4526

**Comment by beroal** [comment]
The patch fixes the segmentation fault.

**Comment by arvidn** [comment]
thanks for testing!

**Comment by arvidn** [comment]
I just realized that I reject the whole call to `add_torrent()` now, if the resume data info-hash doesn't match the info-hash from the torrent file. You were saying that previously the resume data would just be rejected. Is the new behavior acceptable you think?

**Comment by beroal** [comment]
The library sends `add_torrent_alert` and `torrent_added_alert`, and the torrent is in the list returned by `session::get_torrents`. It is not downloaded though, and it is valid and finished which is kind of strange. So I do not see how the call to `add_torrent` is rejected.

I am okay with this change if there is a way to detect a resume data error in Python. I do not see such a way right now. There is no `torrent_handle add_torrent(add_torrent_params const& params, error_code& ec)` in Python, and `torrent_handle add_torrent(add_torrent_params const& params)` does not throw an exception contrary to the documentation. However, this change may create problems for other programmer who are not aware of it.

**Comment by arvidn** [comment]
[this](https://github.com/arvidn/libtorrent/pull/4526/files#diff-8775d2d9460d9b7a42d64f06511742d7R4837) causes `add_torrent()` to fail. As demonstrated by [this](https://github.com/arvidn/libtorrent/pull/4526/files#diff-6726dc766bc1c5eeec1e6f7a6cdfff12R314) test, the error code indicates a failure. The overload that doesn't take a `error_code` reference throw instead.

Perhaps there's an issue in the python binding, causing `add_torrent()` not throwing.

**Comment by beroal** [comment]
I created  #4538 because I cannot test normally.
