### ISSUE TITLE
Acessing torrent.info_hash() from plugin (invalid info hash)

### ISSUE THREAD

**Issue by asb-72** [arvidn/libtorrent#4519]
libtorrent version (or branch): RC_1_2

platform/architecture:  4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

compiler and compiler version: c++ (Debian 8.3.0-6) 8.3.0

Simpe session example, with  "ses.add_extension(create_my_plugin);"
```
 struct my_torrent_plugin final
    : torrent_plugin
    , std::enable_shared_from_this<my_torrent_plugin> {

        explicit my_torrent_plugin(torrent& t)
        : m_torrent(t),
        m_ticks(60),
        m_first(true) {
              std::cout << "BBB:" << to_hex(m_torrent.info_hash()) << "\n";
        }

...

std::shared_ptr<torrent_plugin> create_my_plugin(torrent_handle const& th, void*) {
        torrent* t = th.native_handle().get();
        return std::make_shared<my_torrent_plugin>(*t);
    }
```

And get invalid info_hash on stdout:
```
BBB:0000000000000000f5a480c6c1ffc5dfd57ebb89
```
walid info hash: F5A480C6C1FFC5DFD57EBB89FA5006A7038AB8D

Please help me find root of the problem.

**Comment by arvidn** [comment]
as you may have noticed, it looks like the has has been shifted to the right. Are you sure this isn't just a problem with the printing of it? the conversion to hex specifically?
I take it you're building libtorrent with the same build configuration as you build your client, and that you use the headers from the same version too, right?

**Comment by asb-72** [comment]
to_hex code taken from aux::to_hex.
Same version of libtorrent. 
I attached archive with this test.

now code:
```
       std::shared_ptr<torrent_plugin> create_my_plugin(torrent_handle const& th, void*) {
        torrent* t = th.native_handle().get();

        std::cout << "AAA0:" << to_hex(th.info_hash()) << "\n";
        std::cout << "AAA1:" << to_hex(t->info_hash()) << "\n";
```
prints:
AAA0:f5a480c6c1ffc5dfd57ebb89fa5006a7038ab8dc
AAA1:0000000000000000f5a480c6c1ffc5dfd57ebb89

[test_plugin.zip](https://github.com/arvidn/libtorrent/files/4464190/test_plugin.zip)

**Comment by arvidn** [comment]
I'll take a look. One note off the bat is that `torrent` is an internal type, so its ABI is not necessarily preserved within minor versions either. So by "same version", I mean the exact same version.

**Comment by arvidn** [comment]
it works for me (I build it with boost-build as if it was one of the examples):

```
./bin/gcc-9.2/debug-mode/crypto-openssl/cxxstd-11-iso/link-static/threading-multi/main "magnet:?xt=urn:btih:e2467cbf021192c241367b892230dc1e05c0580e"
AAA0:e2467cbf021192c241367b892230dc1e05c0580e
AAA1:e2467cbf021192c241367b892230dc1e05c0580e
BBB:e2467cbf021192c241367b892230dc1e05c0580e
successfully listening on [TCP] 127.0.0.1:6881
successfully listening on [UDP] 127.0.0.1:6881
successfully listening on [TCP] 192.168.1.125:6881
successfully listening on [UDP] 192.168.1.125:6881
successfully listening on [TCP] 172.17.0.1:6881
successfully listening on [UDP] 172.17.0.1:6881
successfully listening on [TCP] [::1]:6881
successfully listening on [UDP] [::1]:6881
successfully listening on [TCP] [fe80::bc85:d038:dafc:c02e%enp5s0]:6881
successfully listening on [UDP] [fe80::bc85:d038:dafc:c02e%enp5s0]:6881
added torrent: e2467cbf021192c241367b892230dc1e05c0580e
e2467cbf021192c241367b892230dc1e05c0580e added
e2467cbf021192c241367b892230dc1e05c0580e: state changed to: dl metadata
e2467cbf021192c241367b892230dc1e05c0580e resumed
ubuntu-19.10-desktop-amd64.iso metadata successfully received
ubuntu-19.10-desktop-amd64.iso: state changed to: checking (r)
ubuntu-19.10-desktop-amd64.iso: state changed to: checking
```

Looking at `torrent.hpp`, I suspect some configuration macro differs in how libtorrent was built and how your client is built. Since `torrent` is internal, there hasn't been much care taken to ensure it's ABI stable across different build configurations. The most likely macro to differ is probably `TORRENT_ABI_VERSION`, but maybe also `TORRENT_USE_OPENSSL`

**Comment by arvidn** [comment]
Does this clarification of the documentation make sense? https://github.com/arvidn/libtorrent/pull/4528

**Comment by asb-72** [comment]
Oh, TORRENT_USE_OPENSSL helped me. Thank you.
