### ISSUE TITLE
Provide "fastresume" data via torrent_status

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#4520]
libtorrent 1.2 has some advantages in "fastresume" data handling, especially the fact that it is passed to session and obtained from it in non-encoded form.
But there is some inconvenience/disadvantage in the way how we can obtain "fastresume" data for torrent.
Despite the fact that almost all parts of the "fastresume" data are available in `torrent_status`, we still have to use an additional procedure to get it all. I strongly believe that it would be much more convenient and unified to use the existing procedures for obtaining torrent status to create "fastresume" data. You only need to add the missing fields to `torrent_status` and change `write_resume_data` to accept `torrent_status` as an input parameter (or just add another overload to it to keep support legacy way).
@arvidn?

**Comment by arvidn** [comment]
there's currently also symmetry in that resume data (i.e. `add_torrent_params`) can be passed to `session::add_torrent()`.

I agree that there's a non-trivial overlap of `torrent_status` and `add_torrent_params`. Have you looked at which fields would have to be added to `torrent_status`? it seems like it might be quite a few.

`trackers`, `tracker_tiers`, `dht_nodes`, `trackerid`, `max_upload`, `max_connections`, `upload_limit`, `download_limit`. all the limit settings and stats counters. `unfinished_pieces`, `file_priorities`, `piece_priorities`, `renamed_files`
