### ISSUE TITLE
 SIGSEGV on arm64 (raspberry pi 64bit) 

### ISSUE THREAD

**Issue by black-puppydog** [arvidn/libtorrent#4523]
**Please provide the following information**

libtorrent version (or branch): `1.1.13 (ubuntu)`

platform/architecture: arm64 (Raspberry Pi 4, Ubuntu 64bit image)

compiler and compiler version: gcc system default. not sure this matters here.

All applications using the ubuntu-packaged `libtorrent-rasterbar9` segfault on startup.
This occurs with qbittorrent, deluged, as well as the demo script for the python bindinds provided at the bottom of this page: 
http://libtorrent.org/python_binding.html

I ran the latter with gdb. Here's the `bt` output: [dump.txt](https://github.com/arvidn/libtorrent/files/4461544/dump.txt).
I have no idea if this is something in the build process, or upstream, and I don't feel qualified to decide that either. I couldn't find any issues that seem to match this here, and I also didn't manage to build from `master` on the pi, because PEBKAC.

This straight-up prevents deluge and qbittorrent from starting up, and this is on first startup, so they don't even know about any specific torrents. So if this is not fixed yet I thought it would be good to have it at least reported.
I hope I can spend some more time on this this weekend.

Edit: I first posted this [on launchpad](https://bugs.launchpad.net/ubuntu/+source/libtorrent-rasterbar/+bug/1871146).

**Comment by black-puppydog** [comment]
can report that this is no longer an issue on the 20.04 beta, which seems to include a patch. not sure why that wasn't backported to 19.04. Might be that this was only an issue for myself...? I can't go back to the old setup since I'm working with a limited supply of SD cards here due to covid and so trying this out meant overwriting the old setup. 

In any case, thanks all for the work you put into this. I've been on and off using this software since 2013, in different contexts. I really appreciate that this exists, thanks for making it happen! :)

**Comment by FranciscoPombal** [comment]
>All applications using the ubuntu-packaged `libtorrent-rasterbar9` segfault on startup.

Unfortunately, nothing we can do about this. This is in the Ubuntu maintainers' hands.

**Comment by black-puppydog** [comment]
that's why I reported it there first :P

**Comment by arvidn** [comment]
do I understand correctly that this ticket can be closed?

**Comment by black-puppydog** [comment]
from my perspective yes. It's not an upstream issue apparently, since there seems to be a fix deployed in the latest ubuntu beta release at least.
