### ISSUE TITLE
 RC_1_2 tracker announce error using "127.0.0.1".

### ISSUE THREAD

**Issue by mhertz** [arvidn/libtorrent#4529]
I make an unofficial deluge 2.0.3 windows installer(as not available for windows officially), and several users reported tracker connection errors sometime after libtorrent 1.2.3, in RC_1_2 branch builds. I asked for debug logs to forward here, from infected users, as I couldn't reproduce, but none replied with such unfortunetly. I last got a report not that long ago, with RC_1_2 build, so still an issue, though no logs provided again. Now all of a sudden i'm able to reproduce it for some reason, in my win10 VM which use bridged networking and host network nothing special and no VPN or anything(linux btw). In my installer I include an option for libtorrent 1.2.3 since fixes it for affected users I got reported, and it also fixes it for me I see now.

Deluge sets 0.0.0.0 as listen interface by default when you don't define anything yourself, and on RC_1_2 after 1.2.3, then I guess the multi-homed change, makes it so that I get announcess on localhost(127.0.0.1) and LAN IP, and the 127.0.0.1 always fails with error, so tracker shows in error status in deluge GTK-UI, and in the log I see the LAN IP works, and retrieves peers/seeds and scrapes etc.

Here are some parts of debug-logs I just obtained:

RC_1_2 today build:
````
15:40:05 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Config key: listen_ports set to [6881, 6881]..
15:40:05 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Listen Interface: 0.0.0.0, Ports: [61262, 61262] with use_sys_port: False
15:40:05 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Config key: listen_interface set to ..
15:40:05 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Listen Interface: 0.0.0.0, Ports: [61262, 61262] with use_sys_port: False
15:40:05 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Config key: outgoing_interface set to ..
15:40:05 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Config key: random_port set to True..
15:40:05 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Listen Interface: 0.0.0.0, Ports: [61262, 61262] with use_sys_port: False
15:40:05 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Config key: outgoing_ports set to [0, 0]..
15:40:05 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Outgoing port set to 0 with range: 0
15:40:05 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Config key: random_outgoing_ports set to True..
15:40:05 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Outgoing port set to 0 with range: 0
15:40:05 [DEBUG   ][deluge.core.alertmanager          :65  ] listen_succeeded_alert: successfully listening on [TCP] 192.168.0.15:61262
15:40:05 [DEBUG   ][deluge.core.alertmanager          :65  ] listen_succeeded_alert: successfully listening on [UDP] 192.168.0.15:61262
15:40:05 [DEBUG   ][deluge.core.alertmanager          :65  ] listen_succeeded_alert: successfully listening on [TCP] 127.0.0.1:61262
15:40:05 [DEBUG   ][deluge.core.alertmanager          :65  ] listen_succeeded_alert: successfully listening on [UDP] 127.0.0.1:61262
15:40:06 [DEBUG   ][deluge.core.alertmanager          :65  ] tracker_announce_alert: archlinux-2020.04.01-x86_64.iso (http://tracker.archlinux.org:6969/announce)[192.168.0.15:61262] sending announce (started)
15:40:06 [DEBUG   ][deluge.core.alertmanager          :65  ] Handling alert: tracker_announce_alert
15:40:06 [DEBUG   ][deluge.core.alertmanager          :65  ] tracker_announce_alert: archlinux-2020.04.01-x86_64.iso (http://tracker.archlinux.org:6969/announce)[127.0.0.1:61262] sending announce (started)
15:40:06 [DEBUG   ][deluge.core.alertmanager          :65  ] Handling alert: tracker_announce_alert
15:40:06 [DEBUG   ][deluge.core.alertmanager          :65  ] tracker_error_alert: archlinux-2020.04.01-x86_64.iso (http://tracker.archlinux.org:6969/announce)[127.0.0.1:61262] The system cannot open the device or file specified "" (1)
15:40:06 [DEBUG   ][deluge.core.alertmanager          :65  ] Handling alert: tracker_error_alert
15:40:06 [DEBUG   ][deluge.core.alertmanager          :65  ] tracker_reply_alert: archlinux-2020.04.01-x86_64.iso (http://tracker.archlinux.org:6969/announce)[192.168.0.15:61262] received peers: 100
15:40:06 [DEBUG   ][deluge.core.alertmanager          :65  ] scrape_failed_alert: archlinux-2020.04.01-x86_64.iso (http://tracker.archlinux.org:6969/announce)[127.0.0.1:61262] scrape failed: 
15:40:06 [DEBUG   ][deluge.core.alertmanager          :65  ] scrape_reply_alert: archlinux-2020.04.01-x86_64.iso (http://tracker.archlinux.org:6969/announce)[192.168.0.15:61262] scrape reply: 18 828
````
libtorrent-1_2_3 tag build:
````
15:42:58 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Listen Interface: 0.0.0.0, Ports: [61262, 61262] with use_sys_port: False
15:42:58 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Config key: listen_interface set to ..
15:42:58 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Listen Interface: 0.0.0.0, Ports: [61262, 61262] with use_sys_port: False
15:42:58 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Config key: outgoing_interface set to ..
15:42:58 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Config key: random_port set to True..
15:42:58 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Listen Interface: 0.0.0.0, Ports: [61262, 61262] with use_sys_port: False
15:42:58 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Config key: outgoing_ports set to [0, 0]..
15:42:58 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Outgoing port set to 0 with range: 0
15:42:58 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Config key: random_outgoing_ports set to True..
15:42:58 [DEBUG   ][deluge.core.preferencesmanager    :65  ] Outgoing port set to 0 with range: 0
15:42:58 [DEBUG   ][deluge.core.alertmanager          :65  ] listen_succeeded_alert: successfully listening on [TCP] 0.0.0.0:61262
15:42:58 [DEBUG   ][deluge.core.alertmanager          :65  ] listen_succeeded_alert: successfully listening on [UDP] 0.0.0.0:61262
15:42:59 [DEBUG   ][deluge.core.alertmanager          :65  ] tracker_announce_alert: archlinux-2020.04.01-x86_64.iso (http://tracker.archlinux.org:6969/announce)[0.0.0.0:61262] sending announce (started)
15:42:59 [DEBUG   ][deluge.core.alertmanager          :65  ] Handling alert: tracker_announce_alert
15:42:59 [DEBUG   ][deluge.core.alertmanager          :65  ] tracker_reply_alert: archlinux-2020.04.01-x86_64.iso (http://tracker.archlinux.org:6969/announce)[0.0.0.0:61262] received peers: 100
15:42:59 [DEBUG   ][deluge.core.alertmanager          :65  ] scrape_reply_alert: archlinux-2020.04.01-x86_64.iso (http://tracker.archlinux.org:6969/announce)[0.0.0.0:61262] scrape reply: 21 824
````
Thanks in advance, and let me know if I can do anything else e.g. run commands on network or whatnot, as I see you had others do, though this is maybe different, I dunno. Sorry if I should have posted in existing ticket, but as the error was different, and not same issue seemingly, I guessed was better start new to not derail the other ticket with off-topic'ness possibly. Anyway, just wanted to atleast report this, finally :)

Edit: I get same error logs now using a 1.2.4 build btw, but I just don't get why only all of a sudden reproducible first now. Granted I haven't checked logs of this, or tried reproduce this, in a pretty long time however, but regardless..

Edit2: I just remembered btw, that I recently changed my virtualbox win10 VM to instead of default choise(NAT I believe, cannot remember, as pretty much always use vboxmanage from shell-scripts, and not the QT GUI), then to bridged networking, as then I didn't need forwarding rules for ssh and such e.g. for headless access etc., so that seemingly was the culprit in this sudden change for me in being able to finally reproduce this.

**Comment by arvidn** [comment]
people have been having this problem in qBT as well. I suspect this has to do with a change where an `NXDOMAIN` error from a tracker hostname would make the retry timer 6 hours. It seems you can get `NXDOMAIN` errors even for transient errors, so I've reverted this patch in `RC_1_2`, slated for the 1.2.6 release

**Comment by mhertz** [comment]
Thanks for reply! The posted problem-log was from RC_1_2 today, including that reverted nxdomain commit, so seemingly not related here atleast.

**Comment by arvidn** [comment]
I just re-read the ticket again, a bit more carefully. Do I understand correctly that the issue is that the 127.0.0.1 listen socket announces to trackers or that it fails?

It's supposed (and expected) to fail. Otherwise you would end up announcing twice to the same tracker. The error should be (iirc) `no_route_to_host`.

Every listen socket (that can accept incoming connections) announce to the  trackers. Some of the local listen sockets cannot reach the tracker, because they are limited to a local network. In other words; the loopback listen interface is expected to fail. One listen socket failing should not make the UI suggest the *other* announces to the tracker failed.

**Comment by mhertz** [comment]
Thanks again for reply, and I understand now that it's merely a deluge error in UI, needing updating. Strange deluge forwards the lt tracker error alert message as instead "The system cannot open the device or file specified "" (1)", instead of your suggested "no route to host", but as per your explanation should be the issue, well deluge issue that is. I'll close this ticket now and again much appreciate the reply and help.

**Comment by DjLegolas** [comment]
From my investigation of this error I found some interesting behavior.
First, `deluge` is only showing the status of the last tracker update. Therefore, If the last one was the `127.0.0.1`, it will mark the torrent as having an error with its tracker.
This behavior can be valid. @cas-- - this is something you need to decide.

Second, which is relevant to `libtorrent`.
Log:
```
16:06:14.842 [DEBUG   ][deluge.core.core              :65  ] Forcing reannouncment to: ('f95c371d5609d15f6615139be84edbb5b94a79bc',)
16:06:15.636 [DEBUG   ][deluge.core.alertmanager      :65  ] Alerts queued: 6
16:06:15.636 [DEBUG   ][deluge.core.alertmanager      :65  ] tracker_announce_alert: archlinux-2020.05.01-x86_64.iso (http://tracker.archlinux.org:6969/announce)[192.168.1.15:59724] sending announce (none)
16:06:15.636 [DEBUG   ][deluge.core.alertmanager      :65  ] Handling alert: tracker_announce_alert
16:06:15.636 [DEBUG   ][deluge.core.alertmanager      :65  ] tracker_announce_alert: archlinux-2020.05.01-x86_64.iso (http://tracker.archlinux.org:6969/announce)[192.168.56.1:59724] sending announce (started)
16:06:15.636 [DEBUG   ][deluge.core.alertmanager      :65  ] Handling alert: tracker_announce_alert
16:06:15.636 [DEBUG   ][deluge.core.alertmanager      :65  ] tracker_announce_alert: archlinux-2020.05.01-x86_64.iso (http://tracker.archlinux.org:6969/announce)[127.0.0.1:59724] sending announce (started)
16:06:15.636 [DEBUG   ][deluge.core.alertmanager      :65  ] Handling alert: tracker_announce_alert
16:06:15.637 [DEBUG   ][deluge.core.alertmanager      :65  ] tracker_error_alert: archlinux-2020.05.01-x86_64.iso (http://tracker.archlinux.org:6969/announce)[192.168.56.1:59724] The system cannot open the device or file specified "" (14)
16:06:15.637 [DEBUG   ][deluge.core.alertmanager      :65  ] Handling alert: tracker_error_alert
16:06:15.637 [DEBUG   ][deluge.core.alertmanager      :65  ] tracker_error_alert: archlinux-2020.05.01-x86_64.iso (http://tracker.archlinux.org:6969/announce)[127.0.0.1:59724] The system cannot open the device or file specified "" (14)
16:06:15.637 [DEBUG   ][deluge.core.alertmanager      :65  ] Handling alert: tracker_error_alert
16:06:15.638 [DEBUG   ][deluge.core.torrentmanager    :65  ] Tracker Error Alert: archlinux-2020.05.01-x86_64.iso (http://tracker.archlinux.org:6969/announce)[192.168.56.1:59724] The system cannot open the device or file specified "" (14) [The system cannot open the device or file specified]
16:06:15.638 [DEBUG   ][deluge.core.torrentmanager    :65  ] Tracker Error Alert: archlinux-2020.05.01-x86_64.iso (http://tracker.archlinux.org:6969/announce)[127.0.0.1:59724] The system cannot open the device or file specified "" (14) [The system cannot open the device or file specified]
16:06:15.936 [DEBUG   ][deluge.core.alertmanager      :65  ] Alerts queued: 2
16:06:15.936 [DEBUG   ][deluge.core.alertmanager      :65  ] tracker_reply_alert: archlinux-2020.05.01-x86_64.iso (http://tracker.archlinux.org:6969/announce)[192.168.1.15:59724] received peers: 100
16:06:15.936 [DEBUG   ][deluge.core.alertmanager      :65  ] Handling alert: tracker_reply_alert
```
The `deluge`'s alert manager receives for 2 out of 3 interfaces/endpoints the same error from `libtorrent` (tested with `deluge` 2.0.4 and `libtorrent` 1.2.5).
Both of the failed interfaces are local (one `127.0.0.1` and the second `192.168.51.1` is `VirtualBox`'s network interface).
After that, the interface with an internet access (`192.168.1.15`) alerts about successful connection (at this point the `deluge` marks the torrent's tracker as valid and removes the error).

From what i read in https://github.com/arvidn/libtorrent/issues/4325#issuecomment-608054978 this is something with the name of the interfaces.
But I didn't set any interface and the IP addresses are correct.
Is there anything else?

**Comment by arvidn** [comment]
the concept of an `announce_endpoint` is new in libtorrent 1.2, and it does make this a bit more complicated. The reason for the `announce_endpoint` is to clearly model machines that are multi-homed, or that have multiple internet connections (say WiFi + cellular). Each tracker is (attempted to be) announce to from each listen interface, but some interfaces can't route to the tracker. e.g. 127.0.0.1 can't reach a tracker on the internet, likewise your local network connecting a virtualbox image can't reach the internet. So those announces fail. This is actually critical, otherwise you would end up announcing *the same* IP to the tracker multiple times. They don't like that.

So, I think the most reasonable model for a client is to track these endpoints individually. Even if they are hidden from the user, if one of them succeeds, the tracker should be considered working (regardless of which order they fail and succeed).
