### ISSUE TITLE
When downloading a folder, where can I get the progress of each file

### ISSUE THREAD

**Issue by zbooa** [arvidn/libtorrent#4531]
use a .torrent download a folder,  It includes some files, and I want to know the download progress of each file.
But now I can only get the overall progress, which is not what I want.
Thank you.

**Comment by joriscarrier** [comment]
you can look at the alerts and more specifically `piece_finished_alert`

**Comment by zbooa** [comment]
> `file_progress` http://libtorrent.org/reference-Core.html#torrent_status

Thank you, I see. 
Excuse me, do you know how to generate a file of the same size as the target file when the task is just started, and then let libtorrent overwrite and write data to the occupied file? What's the mark?

**Comment by joriscarrier** [comment]
http://libtorrent.org/reference-Core.html#add_torrent_params
http://libtorrent.org/reference-Storage.html#storage_mode_t

**Comment by joriscarrier** [comment]
close ?
