### ISSUE TITLE
std::chrono::_V2::system_clock has no member named ‘expires_after’; did you mean ‘expires_at’

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#4533]
@arvidn Recent commit 61d2c8c1f57b4 has broken the ubuntu libtorrent 1.2 daily builds on Bionic:

https://launchpad.net/~libtorrent.org/+archive/ubuntu/1.2-daily/+packages?field.name_filter=&field.status_filter=&field.series_filter=bionic

Buildlog: https://launchpadlibrarian.net/474181639/buildlog_ubuntu-bionic-amd64.libtorrent-rasterbar_1.2.1+daily10231+744e5bc+202004112303~ubuntu18.04.1_BUILDING.txt.gz

Error:
```
../../src/socket_type.cpp:153:7: error: ‘using element_type = class boost::asio::basic_waitable_timer<std::chrono::_V2::system_clock> {aka class boost::asio::basic_waitable_timer<std::chrono::_V2::system_clock>}’ has no member named ‘expires_after’; did you mean ‘expires_at’?
    t->expires_after(seconds(3));
       ^~~~~~~~~~~~~
       expires_at
```

**Comment by arvidn** [comment]
Right. `expire_after` is the new name (and part of networking TS). I should go back to the original name to support older boost versions

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/4535
