### ISSUE TITLE
Error: ‘tls_client’ is not a member of ‘boost::asio::ssl::context’

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#4534]
Recent commit a871668 has broken the ubuntu libtorrent 1.2 daily builds on Xenial:

https://launchpad.net/~libtorrent.org/+archive/ubuntu/1.2-daily/+packages?field.name_filter=&field.status_filter=&field.series_filter=xenial

Buildlog: https://launchpadlibrarian.net/471472657/buildlog_ubuntu-xenial-amd64.libtorrent-rasterbar_1.2.1+daily10206+a871668+202003291421~ubuntu16.04.1_BUILDING.txt.gz

Error:
```
../../src/session_impl.cpp:458:20: error: ‘tls’ is not a member of ‘boost::asio::ssl::context’
   , m_peer_ssl_ctx(ssl::context::tls)
```

**Comment by cas--** [comment]
@arvidn tls_client has only been available since boost 1.64: https://www.boost.org/doc/libs/1_64_0/doc/html/boost_asio/reference/ssl__context/method.html

Since 1.2 requires boost >= 1.58 to build this really needs fixed

**Comment by arvidn** [comment]
thanks for the report. Do you have a suggestion on how to solve this?
I suppose I could check the boost version and use `tlsv12_client` if it's older than 1.64. Does that seem reasonable?

**Comment by cas--** [comment]
A good plan :+1:

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/4542

**Comment by cas--** [comment]
Sorry meant to say that `tls` was also only added in 1.64: https://www.boost.org/doc/libs/1_60_0/doc/html/boost_asio/reference/ssl__context/method.html

**Comment by cas--** [comment]
@arvidn Fix half-worked... need to also fix src/torrent.cpp

**Comment by arvidn** [comment]
I tried to build against boost-1.58, but it wasn't trivial. is it just the `ssl::context` enum in torrent.cpp too?

**Comment by arvidn** [comment]
does this look good? https://github.com/arvidn/libtorrent/pull/4549

**Comment by cas--** [comment]
Thanks, yes that was the final part of the puzzle, all the builds are passing again: https://code.launchpad.net/~libtorrent.org/+recipe/libtorrent-1.2-daily
