### ISSUE TITLE
v2 status?

### ISSUE THREAD

**Issue by paxter** [arvidn/libtorrent#4539]
First of all it's awesome, that this library is still well supported and developed. I recently [asked in the qBittorrent project to support the Bittorrent specification v2](https://github.com/qbittorrent/qBittorrent/issues/12419) and they refered me to libtorrent.

I see, there are some v2 milestones, but I don't know exactly the development prioritys here. The main reason why I'm asking are the stronger hash functions to prevent the potential attacks on torrents. I know, that some features of the v2 specifications are supported yet by some extended BEPs. 

Maybe somebody can explain me the status of v2.
Thanks for all your hard time and support for this well developed library!

**Comment by ssiloti** [comment]
Support for v2 was merged to master with #3873. It will ship with libtorrent 2.0.

**Comment by arvidn** [comment]
I consider this a blocker for libtorrent 2.0 being released. https://github.com/arvidn/libtorrent/issues/4373 But a bunch of other issues have surfaced in 1.2.x recently that got all my attention. So those need to be resolved and merged into the main branch as well
