### ISSUE TITLE
DHT node id(s) longer than 20 bytes in Python bindings

### ISSUE THREAD

**Issue by fonic** [arvidn/libtorrent#4541]
**libtorrent version (or branch):**
Git master

**platform/architecture:**
Gentoo Linux amd64

**compiler and compiler version:**
GCC 9.2.0
Python 3.6.10

My understanding is that DHT node ids, same as info hashes, are always supposed to be exactly 20 bytes long. However, using the Python bindings, our own node id(s) appear(s) to be longer than that:

```
$ python
>>> import libtorrent
>>> session = libtorrent.session({})
>>> state = session.save_state()
>>> dht_state = state[b'dht state']
>>> for item in dht_state[b'node-id']:
...     print("Item: %s, length: %d" % (bytes.hex(item), len(item)))
... 
Item: f2140b6f1997ed354c13f1ec5138c1584998a92ec0a8b223, length: 24
Item: d2a9feed005fd343eae4c1f41005003904fb29cbc0a8b21b, length: 24
```

While at this, I'd like to point out that keys are byte values, is that intentional? Also, `dht state` (with a space) and `node-id` (with a hyphen) both differ from the usual naming scheme. I think `dht_state` and `node_id` would be more appropriate.

**Comment by arvidn** [comment]
The `node-id` strings are 20 byte ID and 4 or 18 bytes address associated with the node ID. (for IPv4 and IPv6 respectively).

It's parsed [here](https://github.com/arvidn/libtorrent/blob/RC_1_2/src/kademlia/dht_state.cpp#L40).

**Comment by fonic** [comment]
Ok, got it. Then it makes sense, my bad.
