### ISSUE TITLE
'make install' fails if sources reside in path containing spaces

### ISSUE THREAD

**Issue by fonic** [arvidn/libtorrent#4551]
**libtorrent version (or branch):**
Git master / RC_1_2

**platform/architecture:**
Gentoo Linux amd64

**compiler and compiler version:**
GCC 9.2.0
CMake 3.16.5

If the sources (or presumably the build directory) are put in a path containing spaces, `make install` fails. This is not a huge thing as the workaround is obvious, but I thought I'd report this nonetheless:

```
$ git clone https://github.com/arvidn/libtorrent.git "/tmp/lib torrent"
$ cd "/tmp/lib torrent"
$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX="../install" ..
$ make
$ make install
[100%] Built target torrent-rasterbar
Install the project...
-- Install configuration: ""
CMake Error at torrent-rasterbar-pkgconfig/generate-pkg-config.cmake:1 (include):
  include could not find load file:

    /tmp/lib
Call Stack (most recent call first):
  cmake_install.cmake:41 (include)


make: *** [Makefile:118: install] Error 1
```

~~I don't have enough knowledge about CMake to track this down or provide more insights.~~

**EDIT:** this seems to fix it:
```
cmake/Modules/GeneratePkgConfig/generate-pkg-config.cmake.in
< include(@_variables_file_name@)
> include("@_variables_file_name@")
```

**Comment by arvidn** [comment]
@zeule does that seem reasonable?

**Comment by zeule** [comment]
@arvidn, sure, and there could be more unquoted paths.

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/4555
