### ISSUE TITLE
Seeding partial torrent?

### ISSUE THREAD

**Issue by elgatito** [arvidn/libtorrent#4565]
Hello Arvid,

I've been testing different things with libtorrent.
I do have a case when I add a torrent, set all files priority to "0", then set one file to "1" and wait till the download ends.
I watch status changes for that torrent, first it's `checking`, then `downloading`, but when file is downloaded, it's `finished` and not `seeded`. 
And if I select all files and download them - then status is `seeded`.

What I'd like to know, torrent is not seeded when having only part of torrent and there is nothing to download?
Or it is seeding, but torrent status is not properly set?

I'm using branch RC_1_1.

**Comment by joriscarrier** [comment]
Hello, torrent is a seed when it has all the files.

cf: [torrent_status](http://libtorrent.org/reference-Core.html#torrent_status)  `enum state_t`

**Comment by elgatito** [comment]
@joriscarrier okay, we do not have a seed state. But when file download is complete - do we seed it? Or we seed it only when we download, and when download is finished - we are not available for uploading?

**Comment by joriscarrier** [comment]
torrent can uploading data when is the finished state.

**Comment by arvidn** [comment]
@elgatito it sounds like you use the word "seeding" to mean "uploading". Torrents are always (potentially) uploading. But "seeding" means you have all pieces. If you only have one file, you don't have all pieces, so you're not seeding

**Comment by elgatito** [comment]
@arvidn you are right. I did understand seed as "upload, not related to download", so when I see "finished" I thought libtorrent is not downloading AND is not uploading as well, and when status is "seeding" then it's not downloading but uploading.

So If I set priority of one file, I download it, status changes to "finished", is libtorrent uploading the file later? 

Another question, if I set priorities to "1" for all files in the torrent, but user first needs file from the middle, how sequential pieces downloads are done? From the first piece of torrent, if all files have same priority?

**Comment by arvidn** [comment]
> So If I set priority of one file, I download it, status changes to "finished", is libtorrent uploading the file later?

Yes (as long as there is a peer interested in the payload of course)

> Another question, if I set priorities to "1" for all files in the torrent, but user first needs file from the middle, how sequential pieces downloads are done? From the first piece of torrent, if all files have same priority?

I don't understand the question. Files with higher priority will be requested from before files with lower priority.

Sequential download mode will request pieces with lower index before pieces with higher index, as long as their priority is > 0.

**Comment by elgatito** [comment]
@arvidn 

> I don't understand the question. Files with higher priority will be requested from before files with lower priority.

> Sequential download mode will request pieces with lower index before pieces with higher index, as long as their priority is > 0.

What I mean:
We have a torrent with few files. 
All files are added with default priority 1.
User streams the file which starts from piece index 1000. 
The only way to make sequential inside this specific file is to set priority more than other files have?

**Comment by arvidn** [comment]
you can either use piece priorities or set_piece_deadline()

**Comment by elgatito** [comment]
@arvidn thanks for clarifications. 

It would be very helpful to have a method to set minimum piece index for sequential piece selection.

**Comment by arvidn** [comment]
I don't see how that would be very helpful. You might just as well use piece priorities.
