### ISSUE TITLE
strange static linker error when setting alert caregories

### ISSUE THREAD

**Issue by geiseri** [arvidn/libtorrent#4566]
I have a very strange error with static linking on linux.  If I pass a mask into `lt::settings_pack::set_int(...)`  I get a linker error:
```
lt::settings_pack settings;
settings.set_int(lt::settings_pack::alert_mask, lt::alert::status_notification | lt::alert::error_notification);
```
causes:
```
[build] /usr/bin/ld: /home/coder/vcpkg/installed/x64-linux/debug/lib/libtorrent-rasterbar.a(alert.cpp.o):(.rodata+0x45c): multiple definition of `libtorrent::alert::error_notification'; manual/torrent/CMakeFiles/torrent_tests.dir/main.cpp.o:(.rodata._ZN10libtorrent5alert18error_notificationE[_ZN10libtorrent5alert18error_notificationE]+0x0): first defined here
[build] /usr/bin/ld: /home/coder/vcpkg/installed/x64-linux/debug/lib/libtorrent-rasterbar.a(alert.cpp.o):(.rodata+0x474): multiple definition of `libtorrent::alert::status_notification'; manual/torrent/CMakeFiles/torrent_tests.dir/main.cpp.o:(.rodata._ZN10libtorrent5alert19status_notificationE[_ZN10libtorrent5alert19status_notificationE]+0x0): first defined here
```
What is strange is that the following works:
```
lt::settings_pack settings;
auto foo = lt::alert::status_notification | lt::alert::error_notification;
settings.set_int(lt::settings_pack::alert_mask, foo);
```
Details:
libtorrent version (or branch): 1.2.2-1 from vcpkg
platform/architecture: ubuntu 19.10 x64
compiler and compiler version: gcc version 9.2.1 20191008 (Ubuntu 9.2.1-9ubuntu2)

**Comment by arvidn** [comment]
Do you happen to end up including the libtorrent static library multiple times by any chance?
Those constants are defined in alert.cpp, and there should only be one instance of that TU.

**Comment by geiseri** [comment]
Looking closer a the compiler command I found that it is.  There is a core library, and I link various tests to that.  I thought gcc could "dedupe" those as long as the symbols were identical.  Could that be what is happening when I assign the value to foo first?

**Comment by arvidn** [comment]
I would guess the link error is caused by including libtorrent multiple times. the reason why it only happens sometimes could be because of optimizations where object files are omitted entirely when they are determined to not be needed by the build. I'm not sure
