### ISSUE TITLE
Slow / Non efficient random access storage seeding

### ISSUE THREAD

**Issue by sjpotter** [arvidn/libtorrent#4570]
I had a thought of a new seeding mechanism to enable seeding large amounts of data that can only be accessed via slow media that isn't random access friendly.

Today we have super seeding and this mechanism gives out 1 piece at a time until it spreads in the cluster and then the client moves on, I'm wondering if this idea could be extended to the above.

Imagine someone had a lot of the above mentioned slow / not random access friendly storage and one wanted to seed data off of it.  Say number of torrents measured in the hundreds or thousands.  Now if one was trying to seed it off it, this wouldn't work well today as bittorrent clients depends on having good random access to the data that they are seeding.  But in super seeding, that's not really the case, as one could cache the entire block in memory for the duration of the seed.  I believe in super seeding, we still need random access as the seeder will still allow its now shared blocks to be fetched from it.

What if we could extend that idea to seeding large numbers of torrents (even in the presence of other seeders) by essentially only offering a small group of pieces at a time.  i.e. we dedicated 32MB of space per active torrent to a piece cache.  we select what pieces are in this piece cache similar to how clients pick which pieces they want to download, the least available in the swarm.  Everyone so often it will reevaluate what pieces should be in the piece cache and read them in.  Those will be the only pieces that the torrent seeder will advertise as available.

So if one wanted to max 200 active torrents for seeding, they would need to dedicate 6-7GB of RAM (at 32MB, less if smaller torrent piece cache).

Now, one can be seeding much more than those 200 active torrents.  But, only 200 are active.  It will regularly ping the trackers to see if there are leechers for any of its torrents and put those leeching torrents into its active queue and will cycle through its active queue on a regular basis (some N minutes).  When it cycles an active torrent out, it frees the memory associated with its piece cache.  when it cycles a new torrent in it allocates a piece cache for it.

thoughts?

**Comment by arvidn** [comment]
The super seeding mechanism is not great for performance, since it limits "pipelining" requests.
There is a "suggest" message which is intended to work as an improvement for this. The most popular clients honor suggest messages. libtorrent has a mode where it can send suggest messages for pieces that are in the disk cache. It's kind of experimental though, and it won't be around in the next major release where the disk cache is overhauled.

There is already a mechanism in libtorrent to have seeding torrents auto-managed, where it will periodically scrape the trackers and start the torrents with the lowest seed-to-downloader ratio. The auto manage logic supports rotating between which torrents are being seeded as well.

**Comment by Seeker2** [comment]
"There is a "suggest" message which is intended to work as an improvement for this. The most popular clients honor suggest messages."

Would that be HAVE FAST -- for pieces that are very rare from the seed's point-of-view?

**Comment by arvidn** [comment]
> Would that be HAVE FAST -- for pieces that are very rare from the seed's point-of-view?

I don't know what you mean by that. the SUGGEST message encourages peers to request specific pieces. There's a feature in libtorrent to suggest pieces that are likely in the disk cache. However, there's no way to "un-suggest" a piece, so it's not super specific. It kind of means; "if you request this soonish, you may get it quickly and cheaply for me"

**Comment by Seeker2** [comment]
Here's what I was mis-remembering:
https://www.bittorrent.org/beps/bep_0006.html
"The Fast Extension packages several extensions: Have None/Have All, Reject Requests, Suggestions and Allowed Fast."
