### ISSUE TITLE
how to get dht put incoming request

### ISSUE THREAD

**Issue by tukeylee** [arvidn/libtorrent#4573]
I am trying to get dht put incoming request, which means I can get to know what keys that other clients sent out. 
I tried to observe "dht_pkt_alert", packets of 'get_peers', 'ping', 'find_nodes' etc can all be received, but no 'put' request. Does any one know how?

**Comment by arvidn** [comment]
how did you send the put request to your client to test?

**Comment by tukeylee** [comment]
> 
> 
> how did you send the put request to your client to test?

Hi, arvidn, so glad to have your reply.
I made two clients, A and B, both joining into DHT with default bootstrap nodes, and working fine.
On A, I send put request with dht_put_item(), and I do it time and time again.
On B, I keep on monitoring alerts (dht_pkt_alert). No incoming put request arrived on B, but when I call dht_get_item(), I can get content I sent from A.

**Comment by arvidn** [comment]
dht-put items are stored on nodes whose node IDs are close to the hash the item is keyed as. Chances are the item you store does not hash to something close to your other DHT node.

**Comment by tukeylee** [comment]
Thank you.
