### ISSUE TITLE
[QUESTION] python bindings: you cannot link statically against boost-python on linux

### ISSUE THREAD

**Issue by joriscarrier** [arvidn/libtorrent#4576]
Hello, in Jamefile (bindings/python) there is:
> you cannot link statically against boost-python on linux, because it links against pthread statically in that case, which is not allowed"

* Linux (debian:buster)
* python 3.8
* boost_1_72
```bash
    ./bootstrap.sh --with-libraries=python,system,iostreams,filesystem,random,chrono,regex --with-python=$(which python) && \
    ./b2 install variant=release link=static runtime-link=static threading=multi cxxstd=17 cxxflags='-fPIC' --prefix=/usr/local/ -d 0 -j8
```
* libtorrent 1.2.6 
```bash
/usr/src/boost_1_72_0/b2 libtorrent-link=static boost-link=static
```

if i update `bindings/python/Jamfile` like this:

`if <boost-link>shared in $(properties) || <target-os>linux in $(properties)`
to
`if <boost-link>shared in $(properties)`

and change the last g++ commande like this:

`"g++"    ... "/usr/src/boost_1_72_0/bin.v2/libs/python/build/gcc-8/debug/libtorrent-python-pic-on/lt-visibility-hidden/python-3.8/libboost_python38.so.1.72.0"  -Wl,-Bstatic  -Wl,-Bdynamic -ldl -lpthread -lutil -Wl,--end-group -fPIC -g -Wl,-Bsymbolic`

to 

`"g++"    ...  -Wl,-Bstatic -lboost_python38  -Wl,-Bdynamic -ldl -lpthread -lutil -Wl,--end-group -fPIC -g -Wl,-Bsymbolic`

build success

```$> ldd libtorrent.so
	linux-vdso.so.1 (0x00007ffec21fd000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f44a1450000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f44a142f000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f44a142a000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f44a12a6000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f44a1123000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f44a1109000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f44a0f46000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f44a2123000)
```

```python
>>> import libtorrent as lt
>>> lt.version()
'1.2.6.0'
```

**Comment by arvidn** [comment]
iiuc, what you're doing is force linking against `pthread` dynamically, while still linking statically against boost.python. My impression is that boost-build doesn't give you that granularity, if you say `<link>static` for boost.python, all its dependencies are also linked statically (except the runtime).

It seems like it would be more reasonable for boost-build to treat `libpthread` as part of the runtime, and have it honor the `runtime-link` feature.

**Comment by joriscarrier** [comment]
Thank you for the answer.
I'm a beginner with boost-build and c++, is it possible to do this with boost-build?

 `"g++"    -o "libtorrent.so" -Wl,-h -Wl,libtorrent.so -shared -Wl,--start-group ... "libtorrent.a" -Wl,-Bstatic -lboost_python38 -Wl,-Bdynamic -pthread -Wl,--end-group`

i juste move `-lboost_python38` between `-Bstatic ... -Wl,-Bdynamic` and replace `-lpthread` by `-pthread`

to obtain
```
 ldd libtorrent.so
	linux-vdso.so.1 (0x00007ffd7f8f5000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6415efa000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa6efaa3000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6415d77000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6415d5d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6415b9c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6416da5000)
```

ps: my goal is to create a python wheel.

**Comment by joriscarrier** [comment]
it is possible to change `-lpthread` by `-pthread` in boost build ?

**Comment by joriscarrier** [comment]
https://github.com/boostorg/build/pull/581
