### ISSUE TITLE
Receiving torrent_finished_alert before add_torrent_alert

### ISSUE THREAD

**Issue by vktr** [arvidn/libtorrent#458]
I'm using a relatively new version of libtorrent (don't remember the commitish but it's a clone of the master branch from around christmas), and I've noticed that when you add a single file torrent and set the only file to priority=0, the `torrent_finished_alert` is posted before `add_torrent_alert`.

I'm using the `add_torrent_alert` to sync the torrent list in my client, and it is built on the expectation that when I receive the `torrent_finished_alert`, a torrent would already exist.

Is this by design?

*Edit*
Also occurs when adding multi-file torrents and setting all file priorities to zero.

*Ninja edit*
I'm adding torrents via `async_add_torrent` if it matters.

**Comment by arvidn** [comment]
I should fix that. it's not deliberate

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/467

**Comment by vktr** [comment]
Awesome! A question not related to the PR, but I see it is being merged into the branch `RC_1_0` - will it end up in `master` as well or do you recommend following the `RC_1_0` branch instead?

**Comment by arvidn** [comment]
yes, once I pull this I'll put it in RC_1_1 and master too. sometimes down stream may lag a little bit
