### ISSUE TITLE
Zero value as permanent upnp lease duration doesn't work

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#4580]
I uncovered this after the recent #4572 was merged.
Setting `upnp_lease_duration` to zero results in a constant stream of `portmap_alert`

**Comment by FranciscoPombal** [comment]
@sledgehammer999 I also noticed that the OOTB default value is 0 (for permanent lease duration). The default lease duration should be the libtorrent default of 3600. Permanent lease duration is for the users with really shitty routers that need the workaround. Periodically refreshing the upnp lease is much more beneficial for more users.

**Comment by sledgehammer999** [comment]
And what does that have to do with the current issue?

**Comment by FranciscoPombal** [comment]
> And what does that have to do with the current issue?

Not much, it's just I had already written out all that when I noticed I was in the wrong issue tracker. Well now you know.

**Comment by an0n666** [comment]
It works fine on my end.

**Comment by arvidn** [comment]
I think this should fix it: https://github.com/arvidn/libtorrent/pull/4585

**Comment by NotTsunami** [comment]
> @sledgehammer999 I also noticed that in qBIttorrent the OOTB default value is 0 (for permanent lease duration). The default lease duration should be the libtorrent default of 3600. Permanent lease duration is for the users with really shitty routers that need the workaround. It is my impression that periodically refreshing the upnp lease is much more beneficial for more users, so that should be the default.

I was told on the PR to leave the default of 0 unchanged.

**Comment by arvidn** [comment]
the fix has landed
