### ISSUE TITLE
tlib::to_hex() is deprecated, what i should use instead?

### ISSUE THREAD

**Issue by Manu-sh** [arvidn/libtorrent#4584]
`torrent_info` is an instance of `tlib::torrent_info` (obtained from a torrent_handle and with all metadata downloaded) and i need to get the hash encoded as sha1hex, this is my code now:

```cpp
this->sha1 = tlib::to_hex( torrent_file->info_hash().to_string() );
```

**Comment by arvidn** [comment]
you could try something like this (untested):
```
std::stringstream str;
for (auto b : info_hash) str << std::hex << std::setw(2) << std::setfill('0') << unsigned(b);
sha1 = str.str();
```

**Comment by Manu-sh** [comment]
okay @arvidn I'll take a look, I was hoping for a replacement, thanks a lot!
