### ISSUE TITLE
High CPU usage/needed to kill Qbittorrent

### ISSUE THREAD

**Issue by swejuggalo** [arvidn/libtorrent#4586]
Apperently there is a problem with latest RC_1_2 build. Had it working fine a few days ago. Building Qbittorrent latests master branch against 1.2.5 solves it. Latest stable branch of Qbittorrent against latest RC_1_2 had the same problem. So it look like a recent change in RC_1_2 is the blame.

https://github.com/qbittorrent/qBittorrent/issues/12663

(Linux/Manjaro)

**Comment by FranciscoPombal** [comment]
Are you able to do a `git-bisect` (https://git-scm.com/docs/git-bisect) to figure out the problematic commit?

**Comment by swejuggalo** [comment]
> Are you able to do a `git-bisect` (https://git-scm.com/docs/git-bisect) to figure out the problematic commit?

I'll take a look on that tomorrow. AUR scripts makes you lazy... Either latest RC_1_2, RC_1_1 or stable are offered. I don't see a easy way to modify them to select specific commits and such. 
Guess I need to learn the basics with git some day 😉
Manually syncing gits and build yourself would probably be preferred if you want to help out... I'm pretty much a noob when it comes to using GIT 😋

**Comment by FranciscoPombal** [comment]
@swejuggalo 

https://wiki.archlinux.org/index.php/Bisecting_bugs_with_Git

**Comment by arvidn** [comment]
a profile of the process (built with debug symbols) would be even better

**Comment by swejuggalo** [comment]
> a profile of the process (built with debug symbols) would be even better

Great.
1. A manual git clone of libtorrent-rasterbar (no problem here) 
2. Configure options (abit more options here than I am used to. Some info points at debugging being on as default. I'll read more on this later) 
3. Make (here I'm used to just "normal" make... Here cmake, bb2 and all kind of stuff is mentioned)
4. Install

I've lost track of what year I built something with configure && make 😋

Note. In the process manager in Manjaro I saw some kind of "reloading" happening. I haven't any computer close by at the moment... In the process manager I see the process state. When closing a process it's marked red. No color at all during normal run. Here it regularly blinks yellow. Does not when built against 1.2.5

**Comment by FranciscoPombal** [comment]
@swejuggalo after git clone you can use CMake to build/install instead of b2/autotools (these commands work in CMake 3.15+):

- For libtorrent (in this example in will be installed under `/usr/local`)

```
$ cd libtorrent
$ cmake -S . -Bcmake-build-dir/RelWithDebInfo -DCMAKE_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr/local -Ddeveloper-options=TRUE -Ddeprecated-functions=FALSE
$ cmake --build cmake-build-dir/RelWithDebInfo --config RelWithDebInfo --parallel $(nproc)
$ sudo cmake --install cmake-build-dir/RelWithDebInfo
```

- For qBittorrent

```
$ cd qBittorrent
$ cmake -S . -Bbuild/RelWithDebInfo -DCMAKE_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr/local
$ cmake --build build/RelWithDebInfo --config RelWithDebInfo --parallel $(nproc)
# no need to install, you can just run it from build/RelWithDebInfo/src/app/qbittorrent
```

The build directories in the examples are automatically ignored in the `.gitignore` of each project.

**Comment by swejuggalo** [comment]
Failing to build Qbittorrent. Lokked fine up until that point.
`cmake --build build/RelWithDebInfo --config RelWithDebInfo --parallel $(nproc)
Scanning dependencies of target qbt_qtnotify_autogen
Scanning dependencies of target qbt_base_autogen
Scanning dependencies of target qbt_powermanagement_autogen
[  1%] Automatic MOC for target qbt_qtnotify
[  1%] Automatic MOC for target qbt_base
[  2%] Automatic MOC for target qbt_powermanagement
[  2%] Built target qbt_powermanagement_autogen
Scanning dependencies of target qbt_powermanagement
[  2%] Building CXX object src/gui/powermanagement/CMakeFiles/qbt_powermanagement.dir/qbt_powermanagement_autogen/mocs_compilation.cpp.o
[  3%] Building CXX object src/gui/powermanagement/CMakeFiles/qbt_powermanagement.dir/powermanagement.cpp.o
[  3%] Building CXX object src/gui/powermanagement/CMakeFiles/qbt_powermanagement.dir/powermanagement_x11.cpp.o
[  3%] Built target qbt_qtnotify_autogen
Scanning dependencies of target qbt_qtnotify
[  4%] Building CXX object src/gui/qtnotify/CMakeFiles/qbt_qtnotify.dir/qbt_qtnotify_autogen/mocs_compilation.cpp.o
[  4%] Building CXX object src/gui/qtnotify/CMakeFiles/qbt_qtnotify.dir/notifications.cpp.o
[  4%] Linking CXX static library libqbt_powermanagement.a
[  4%] Built target qbt_base_autogen
Scanning dependencies of target qbt_base
[  4%] Built target qbt_powermanagement
[  4%] Building CXX object src/base/CMakeFiles/qbt_base.dir/qbt_base_autogen/mocs_compilation.cpp.o
[  5%] Building CXX object src/base/CMakeFiles/qbt_base.dir/bittorrent/downloadpriority.cpp.o
[  5%] Building CXX object src/base/CMakeFiles/qbt_base.dir/bittorrent/infohash.cpp.o
[  5%] Building CXX object src/base/CMakeFiles/qbt_base.dir/bittorrent/magneturi.cpp.o
[  5%] Building CXX object src/base/CMakeFiles/qbt_base.dir/bittorrent/peeraddress.cpp.o
[  6%] Building CXX object src/base/CMakeFiles/qbt_base.dir/bittorrent/peerinfo.cpp.o
[  6%] Building CXX object src/base/CMakeFiles/qbt_base.dir/bittorrent/private/bandwidthscheduler.cpp.o
[  6%] Building CXX object src/base/CMakeFiles/qbt_base.dir/bittorrent/private/filterparserthread.cpp.o
[  6%] Linking CXX static library libqbt_qtnotify.a
[  6%] Built target qbt_qtnotify
[  7%] Building CXX object src/base/CMakeFiles/qbt_base.dir/bittorrent/private/nativesessionextension.cpp.o
[  7%] Building CXX object src/base/CMakeFiles/qbt_base.dir/bittorrent/private/nativetorrentextension.cpp.o
[  7%] Building CXX object src/base/CMakeFiles/qbt_base.dir/bittorrent/private/portforwarderimpl.cpp.o
[  8%] Building CXX object src/base/CMakeFiles/qbt_base.dir/bittorrent/private/resumedatasavingmanager.cpp.o
[  8%] Building CXX object src/base/CMakeFiles/qbt_base.dir/bittorrent/private/speedmonitor.cpp.o
[  8%] Building CXX object src/base/CMakeFiles/qbt_base.dir/bittorrent/private/statistics.cpp.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/base/CMakeFiles/qbt_base.dir/build.make:109: src/base/CMakeFiles/qbt_base.dir/bittorrent/infohash.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/base/CMakeFiles/qbt_base.dir/build.make:122: src/base/CMakeFiles/qbt_base.dir/bittorrent/magneturi.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:412: src/base/CMakeFiles/qbt_base.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
`

**Comment by swejuggalo** [comment]
The warnings before building

> cmake -S . -Bbuild/RelWithDebInfo -DCMAKE_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr/local
CMake Warning (dev) at CMakeLists.txt:3 (message):
  If the build fails, please try the autotools/qmake method.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Building in C++14 mode
-- Found Boost: /usr/lib64/cmake/Boost-1.72.0/BoostConfig.cmake (found suitable version "1.72.0", minimum required is "1.40")  
-- libtorrent definitions: -DTORRENT_USE_LIBCRYPTO;-DTORRENT_USE_OPENSSL;-DBOOST_ASIO_ENABLE_CANCELIO;-DUNICODE;-D_UNICODE;-D_FILE_OFFSET_BITS=64;-DTORRENT_LINKING_SHARED;-DBOOST_SYSTEM_DYN_LINK
-- Libtorrent Boost dependencies: chrono;date_time;random;system;thread
-- Found Boost: /usr/lib64/cmake/Boost-1.72.0/BoostConfig.cmake (found version "1.72.0") found components: chrono date_time random system thread 
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.1.1g")  
-- Found OpenSSL: /usr/lib/libcrypto.so (found suitable version "1.1.1g", minimum required is "1.0")  
-- Project is built in RELEASE mode.
-- Disabling debug output.
-- copying ../lang/lang.qrc to /home/swejuggalo/qBittorrent/build/RelWithDebInfo/src/app/../lang
-- copying ../webui/www/translations/webui_translations.qrc to /home/swejuggalo/qBittorrent/build/RelWithDebInfo/src/app/../webui/www/translations
CMake Warning (dev) at cmake/Modules/QbtTargetSources.cmake:16 (target_sources):
  Policy CMP0076 is not set: target_sources() command converts relative paths
  to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  A private source from a directory other than that of target "qBittorrent"
  has a relative path.
Call Stack (most recent call first):
  src/gui/CMakeLists.txt:171 (qbt_target_sources)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/QbtTargetSources.cmake:16 (target_sources):
  Policy CMP0076 is not set: target_sources() command converts relative paths
  to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  A private source from a directory other than that of target "qBittorrent"
  has a relative path.
Call Stack (most recent call first):
  src/webui/CMakeLists.txt:36 (qbt_target_sources)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- 
Configuration results:
-- The following features have been enabled:

 * COUNTRIES_RESOLUTION, Enable resolving peers IP addresses to countries
 * STACKTRACE, Enable stacktraces
 * WEBUI, Enables built-in HTTP server for headless use

-- The following OPTIONAL packages have been found:

 * X11
 * Qt5Gui (required version >= 5.14.2)
 * Qt5Widgets (required version >= 5.9.0), Set of components for creating classic desktop-style UIs for the Qt5 framework
   Enables qBittorrent GUI. Unneeded for headless configuration.

-- The following RECOMMENDED packages have been found:

 * Qt5DBus (required version >= 5.9.0), Qt5 module for inter-process communication over the D-Bus protocol
   Enables communication with other system components (e.g. notification service) via D-Bus. 

-- The following REQUIRED packages have been found:

 * boost_chrono (required version == 1.72.0)
 * boost_date_time (required version == 1.72.0)
 * boost_random (required version == 1.72.0)
 * boost_system (required version == 1.72.0)
 * boost_headers (required version == 1.72.0)
 * Threads
 * boost_thread (required version == 1.72.0)
 * Boost
 * LibtorrentRasterbar (required version >= 1.1.10)
 * OpenSSL (required version >= 1.0)
 * Qt5Network
 * Qt5Xml
 * Qt5LinguistTools
 * Qt5 (required version >= 5.9.0)
 * ZLIB (required version >= 1.2.5.2)
 * Qt5Core (required version >= 5.14.2)

-- Configuring done
-- Generating done
-- Build files have been written to: /home/swejuggalo/qBittorrent/build/RelWithDebInfo

**Comment by swejuggalo** [comment]
Oh...wait... Don't bother to reply just yet ;-)

**Comment by FranciscoPombal** [comment]
@swejuggalo 
>c++: fatal error: Killed signal terminated program cc1plus

You likely ran out of memory during compilation. Try running with less parallel jobs, like `4` or `2` instead of `$(nproc)`. `$(nproc)` just sets the number of parallel jobs to the number of logical CPUs in your machine (colloquially, cores+threads). The higher the number of parallel jobs, the faster it goes, but requires more memory.

**Comment by swejuggalo** [comment]
> @swejuggalo
> 
> > c++: fatal error: Killed signal terminated program cc1plus
> 
> You likely ran out of memory during compilation. Try running with less parallel jobs, like `4` or `2` instead of `$(nproc)`. `$(nproc)` just sets the number of parallel jobs to the number of logical CPUs in your machine (colloquially, cores+threads). The higher the number of parallel jobs, the faster it goes, but requires more memory.

Yeah. Boinc running at the same time wasn't the optimal either ;-) Maybe dynamic swap can be a problem too. Swap increased to 4GB.
Probably finish the whole build with 4 or something.

**Comment by swejuggalo** [comment]
> @swejuggalo
> 
> > c++: fatal error: Killed signal terminated program cc1plus
> 
> You likely ran out of memory during compilation. Try running with less parallel jobs, like `4` or `2` instead of `$(nproc)`. `$(nproc)` just sets the number of parallel jobs to the number of logical CPUs in your machine (colloquially, cores+threads). The higher the number of parallel jobs, the faster it goes, but requires more memory.

A whole buch of this

> [100%] Linking CXX executable qbittorrent
/usr/bin/ld: ../base/libqbt_base.a(session.cpp.o): in function `BitTorrent::TrackerEntry::~TrackerEntry()':

and finish with

> collect2: error: ld returned 1 exit status
make[2]: *** [src/app/CMakeFiles/qBittorrent.dir/build.make:1306: src/app/qbittorrent] Error 1
make[1]: *** [CMakeFiles/Makefile2:355: src/app/CMakeFiles/qBittorrent.dir/all] Error 2
make: *** [Makefile:150: all] Error 2

**Comment by swejuggalo** [comment]
Trying to modify the AUR scripts... These finish a build, but need further editing.

The first one currently looks like this after edit. I probably need more changes though.

> # Maintainer: Chocobo1 <chocobo1 AT archlinux DOT net>

pkgname=libtorrent-rasterbar-1_2-git
pkgver=1.2.6.r7.ge2501c061
pkgrel=1
pkgdesc="A feature complete C++ bittorrent library (git branch RC_1_2)"
arch=('i686' 'x86_64')
url="https://www.libtorrent.org/"
license=('BSD')
depends=('boost-libs')
makedepends=('git' 'boost' 'cmake' 'python' 'python-setuptools')
provides=('libtorrent-rasterbar')
conflicts=('libtorrent-rasterbar')
options=('!strip')
source=('git+https://github.com/arvidn/libtorrent.git#branch=RC_1_2')
sha256sums=('SKIP')


pkgver() {
  cd "libtorrent"

  git describe --long --tags | sed 's/^[A-Za-z]*[-_]//;s/\([^-]*-g\)/r\1/;s/[_-]/./g'
}

build() {
  cd "libtorrent"

  mkdir -p "_build" && cd "_build"
  cmake \
    -DCMAKE_CXX_STANDARD=14 \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DCMAKE_INSTALL_PREFIX="/usr" \
    -Ddeveloper-options=TRUE \
    -Ddeprecated-functions=FALSE \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -Dpython-bindings=ON \
    -Dboost-python-module-name="python" \
    "../"
  make
}

package() {
  cd "libtorrent"

  make -C "_build" DESTDIR="$pkgdir" install
  install -Dm644 "LICENSE" -t "$pkgdir/usr/share/licenses/libtorrent-rasterbar"
}

Here I probably need more help to make it equivalent to the suggests cmake build.

> # Maintainer: carstene1ns <arch carsten-teibes de> - http://git.io/ctPKG
# Maintainer: Eschwartz <eschwartz@archlinux.org>
# Contributors: Ner0, Sevenseven

# All my PKGBUILDs are managed at https://github.com/eli-schwartz/pkgbuilds

pkgname=qbittorrent-git
pkgver=4.2.5.r363.g725c836a2
pkgrel=1
pkgdesc="A bittorrent client powered by C++, Qt5 and the good libtorrent library (development version)"
arch=('i686' 'x86_64')
url="https://www.qbittorrent.org/"
license=('custom' 'GPL')
depends=('libtorrent-rasterbar' 'qt5-base' 'qt5-svg')
makedepends=('boost' 'git' 'qt5-tools')
optdepends=('python: needed for torrent search tab')
conflicts=('qbittorrent')
provides=('qbittorrent')
source=("${pkgname%-*}::git+https://github.com/qbittorrent/qBittorrent.git")
sha256sums=('SKIP')

pkgver() {
  cd ${pkgname%-*}

  _tag=$(git tag -l --sort -v:refname | sed -n '1,1{s/release-//p}')
  _rev=$(git rev-list --count release-${_tag}..HEAD)
  _hash=$(git rev-parse --short HEAD)
  printf "%s.r%s.g%s" "$_tag" "$_rev" "$_hash"
}

build() {
  cd ${pkgname%-*}

  # tell qmake not to break makepkg's debug/!strip options
  export QBT_ADD_CONFIG='nostrip'

  ./configure --prefix=/usr
  make
}

package() {
  cd ${pkgname%-*}

  make INSTALL_ROOT="$pkgdir/" install
  install -Dm644 COPYING "$pkgdir"/usr/share/licenses/$pkgname/COPYING
}

**Comment by swejuggalo** [comment]
Back at the builds made by the AUR scripts it actually works again (but modified trying to make debug build)... Can't replicate any high CPU usage. Been running normally for some time now. I never did before I removed them and tried the cmake builds... 

Would still be nice to get that debug build working though. If I can get it done with modified AUR scripts would be even nicer.

**Comment by swejuggalo** [comment]
> @swejuggalo
> 
> > c++: fatal error: Killed signal terminated program cc1plus
> 
> You likely ran out of memory during compilation. Try running with less parallel jobs, like `4` or `2` instead of `$(nproc)`. `$(nproc)` just sets the number of parallel jobs to the number of logical CPUs in your machine (colloquially, cores+threads). The higher the number of parallel jobs, the faster it goes, but requires more memory.

Finally made it. Change to /usr and not /usr/local was the solution.
So at least I know how to do it the next time. Still no replicated strange behavior as before.
So now I only need to know how to update the locally stored git and overwrite and rebuild ;-)

This build should output info when launching from terminal? Or anything else to do next time?

**Comment by swejuggalo** [comment]
I haven't been able to replicate any such strange behavior. So maybe this can be closed.
However I saw something else today that I haven't noticed before...

This is built via the instructions mentioned above. Do I need more than just running qbittorrent via terminal? Think I have some of the other reported issues so I guess I will try to find a way to be useful there. For example issues with uploading created torrents. (testing on the internal network - upload often starts after having restarting the seeding client. The receiver is windows 4.2.5). Either there is a log somewhere that can be useful or I need to start the client differently. I havn't really done much debugging since ages ago in windows with windows debugger on Libreoffice ;-)

Anyway this is what terminal showed. First 2 rows "badwindow" is always there. Don't really know then the rest came.

qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
qt5ct: D-Bus system tray: no
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 732, resource id: 0, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 736, resource id: 0, major code: 18 (ChangeProperty), minor code: 0
Http::RequestParser::ParseResult Http::RequestParser::doParse(const QByteArray&) unsupported request method:  "OPTIONS"
bool Http::RequestParser::parseRequestLine(const QString&) invalid http header: "OPTIONS / RTSP/1.0"
Http::RequestParser::ParseResult Http::RequestParser::doParse(const QByteArray&) header parsing error
bool Http::RequestParser::parseRequestLine(const QString&) invalid http header: "\u0005\u0004\u0000\u0001\u0002\u0080\u0005\u0001\u0000\u0003\ngoogle.com\u0000PGET / HTTP/1.0"
Http::RequestParser::ParseResult Http::RequestParser::doParse(const QByteArray&) header parsing error
Http::RequestParser::ParseResult Http::RequestParser::doParse(const QByteArray&) header parsing error
bool Http::RequestParser::parseRequestLine(const QString&) invalid http header: "OPTIONS sip:nm SIP/2.0"
Http::RequestParser::ParseResult Http::RequestParser::doParse(const QByteArray&) header parsing error

**Comment by FranciscoPombal** [comment]
The bad window errors could be Qt bugs. The HTTP errors could be either qBittorrent WebUI bugs or misuse of it by the browser or some other tools? I would suggested opening up your browser's dev tools or some other network inspection software and examining the requests, plus a debugger attached with suitable break points/log points. Either way, if anything comes of both of these matters, they should be handled in a separate thread, in qBittorrent's issue tracker.

Did you ever manage to get a `git-bisect` going? Also as far as I understand, you are only using Debug builds. It is possible the problem only manifests itself with release builds or something.

Or it could be something else entirely, due to now fixed bugs in other dependencies like boost.

**Comment by swejuggalo** [comment]
> The bad window errors could be Qt bugs. The HTTP errors could be either qBittorrent WebUI bugs or misuse of it by the browser or some other tools? I would suggested opening up your browser's dev tools or some other network inspection software and examining the requests, plus a debugger attached with suitable break points/log points. Either way, if anything comes of both of these matters, they should be handled in a separate thread, in qBittorrent's issue tracker.
> 
> Did you ever manage to get a `git-bisect` going? Also as far as I understand, you are only using Debug builds. It is possible the problem only manifests itself with release builds or something.
> 
> Or it could be something else entirely, due to now fixed bugs in other dependencies like boost.

I just got the build working according to the instructions. Since then not been able to replicate that issue. And by now pretty much have changed anyway. I rebuild approx weekly with the same method.
Maybe that http thing is a returning issue. Will see what I can find out about that and if I can trigger it somehow. 
Guess I'll see if I can find some info on how to use a debugger in Linux. Would be nice to be useful 😋
