### ISSUE TITLE
Peer list not cleaned and updated after event=complete

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4587]
**Please provide the following information**

libtorrent version (or branch):
libtorrent 1.2.6
platform/architecture:

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

After a torrent is completed and event complete is sent to tracker, tracker supplies with a list of leechers only since we have become a seeder now. But libtorrent holds on to old peer list and keeps trying to connect with seeders from which we just completed downloading the files. This is a very strange behaviour and should be corrected. When tracker sends us new peer list after event=complete is sent, update the peer list with the new list sent from tracker. It makes no sense to keep lets say 200 seeders in the peer list and keep trying to connect with them when almost all of them are seeders. On the other hand if we used the newly supplied peer list, we'd have better chances of connecting with the leechers.

**Comment by FranciscoPombal** [comment]
Or, instead of replacing the list entirely, just replace the seeders in the current list with new peers from the new list that are not already present in the current list.

**Comment by an0n666** [comment]
I think it’s better to replace the entire list. Some seeders could be behind NAT and I notice libtorrent just keeps retrying those peers. Whereas if they were connectable there wouldn’t be retries I guess.

**Comment by arvidn** [comment]
I don't see why it would ever make sense to *remove* peers from the peer list. Why would you assume all of those peers are seeds?

If we remove seeds from the peer list, there is nowhere to record the fact that they are seeds. If we ever hear about them again we would have to assume they are not, and try them again.

It's already the case that libtorrent does not connect to seeds, once it becomes a seed itself. However, peers don't necessarily advertise themselves as seeds before disconnecting, so you can't assume they are, and will retry them later.

**Comment by arvidn** [comment]
@an0n666 what is the behavior you would expect to see?

Is it expensive for you to connect to peers and then disconnect?

**Comment by an0n666** [comment]
I just downloaded a torrent with ~1100 seeders and only 2 leechers. But from what I noticed is after the download was completed libtorrent continued to attempt peer connections. Whereas if it relied on the new peer list sent by tracker this could’ve been avoided. To me it makes no sense to keep retrying peers which are most likely seeders after I’ve completed the torrent.

**Comment by arvidn** [comment]
> To me it makes no sense to keep retrying peers which are most likely seeders after I’ve completed the torrent.

It wouldn't make sense if the new peers were *not* connected. But that's not what you're saying, you're saying that just trying to connect to other peers as well doesn't make sense.

How is libtorrent supposed to know that all those other peers are seeds?
The only way the protocol communicates this is by the `HAVE_ALL` or a full bitfield message in the peer protocol. If you don't see either of those messages, how can you assume the peer is a seed?

**Comment by an0n666** [comment]
After my download finishes, announce to tracker is made with left=0, So tracker knows we’re a seeder now and sends peers list which announced with something other than left=0. So I can just use that list to connect with those peers. And whatever I had previously in my list can be replaced with the new list.

**Comment by an0n666** [comment]
I was expecting this^ behaviour in private torrents.

**Comment by arvidn** [comment]
> After my download finishes, announce to tracker is made with left=0, So tracker knows we’re a seeder now and sends peers list which announced with something other than left=0. So I can just use that list to connect with those peers. And whatever I had previously in my list can be replaced with the new list.

* Unless the tracker is shitty and doesn't distinguish between downloaders and seeds.
* Unless the swarm is so large that the 200 peers the tracker returns is just a small portion of it, and discarding your local list would make you *lose* downloaders.

Do you think those cases are unimportant or should there be some heuristic to detect them?

**Comment by an0n666** [comment]
We can keep the connected downloaders and discard the rest. If the tracker is shitty, the list will repopulate anyway. But if it’s not, then we don’t end up retrying NATed peers. And since we’re not discarding already connected downloaders, I think there’s little to lose.

**Comment by arvidn** [comment]
I'm a bit confused.

>  If the tracker is shitty, the list will repopulate anyway.

I don't see how this is true. Presumably using a shitty tracker is the *worst* way of repopulating a peer list (almost by definition).

> But if it’s not, then we don’t end up retrying NATed peers.

How is this ever avoided? (My impression is that the days of trackers performing NAT checks are gone). And what does it have to do with this topic?

> And since we’re not discarding already connected downloaders, I think there’s little to lose.

I don't believe this is true at all. I believe it's common for peer connections to fail because they have a full peer list, and connecting to them later may succeed. Having a large peer list has *only* benefits (up to some point of where it's not worth using RAM to store a larger list of course).

You haven't addressed my comment about keeping seeds in the peer list is the only way of remembering that they are seeds. If the the tracker sends those peers to us again, and we cleared them from our peer list, we'll have to connect to them again. If we keep them, we know they are seeds and won't connect to them.

I would also question the underlying issue. Is it really expensive to connect to peers and then disconnect?
Doing so provides robustness to the swarm, so I think there are benefits.

**Comment by an0n666** [comment]
No it’s not expensive. It just gives users an impression that peers are connecting and then disconnecting without any data transfer. I noticed this recently after Qbt started counting connecting peers in the transfer list. I think it’s more intuitive for client to not count peers that are in a connection attempt stage. You can close this.

**Comment by Seeker2** [comment]
uTorrent's logger records connection events.
While seeding a torrent, I regularly see in it:
Disconnect: Is seed
