### ISSUE TITLE
alert_name not present in libtorrent.so

### ISSUE THREAD

**Issue by waTeim** [arvidn/libtorrent#4589]
**Please provide the following information**

libtorrent version (or branch):

1.2.6

platform/architecture:

ubuntu 18, amd

compiler and compiler version:

gcc 7.5

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

apps using alerts (by including `alert_types.hpp`) fail to link with the following error

    /usr/local/include/libtorrent/alert_types.hpp:495: undefined reference to `libtorrent::alert_name(int)

coming from the following define (line 204)

    #define TORRENT_DEFINE_ALERT_IMPL(name, seq, prio) \
            name(name&&) noexcept = default; \
            static const int priority = prio; \
            static const int alert_type = seq; \
            virtual int type() const noexcept override { return alert_type; } \
            virtual alert_category_t category() const noexcept override { return static_category; } \
            virtual char const* what() const noexcept override { return alert_name(alert_type); }

checking with nm on the static library, it's present

    /usr/local/lib$ nm -pa libtorrent-rasterbar.a   | c++filt | grep alert_name
    0000000000000000 d libtorrent::alert_name(int)::names
    0000000000005790 T libtorrent::alert_name(int)
                     U libtorrent::alert_name(int)

And if the static library is linked rather than the dynamic library (only) then the symbol resolves.

but, the same fails when checking against the `.so`

    nm -D libtorrent-rasterbar.so | c++filt | grep alert_name

results in no symbols

**Comment by arvidn** [comment]
thanks for the report! I believe this patch should fix it: https://github.com/arvidn/libtorrent/pull/4590

**Comment by arvidn** [comment]
the fix has been merged
