### ISSUE TITLE
boost 1.73.0 support - failing to build 1.2.6 against this version of boost

### ISSUE THREAD

**Issue by userdocs** [arvidn/libtorrent#4592]
**Please provide the following information**

1.2.6

**platform/architecture:**

Any linux based

**Please describe what symptom you see, what you would expect to see instead and
how to reproduce it.**

I think there is an issue when building against the current release of boost 1.73.0

https://github.com/boostorg/boost/releases/tag/boost-1.73.0

When compiling against boost 1.73 it appears to compile successfully using `b2` but the final lines are: 

```
common.copy /root/qbittorrent-build/lib/libtorrent.a
...updated 417 targets...
```

Then it appears to error / exit out the script with no reason. It's not supposed to exit at this point but something is making `b2` exit at this point.

There is no obvious reason it errors out and i was wondering if you could tell how to debug it.

This may well be a boost issue itself but i have tried `b2 -d3` to see what the problem is but that's the issue. There is no obvious cause for this behaviour.

**Comment by userdocs** [comment]
Ok, so i think i see the problem. With version [4.2.0(1.73.0)](https://github.com/boostorg/build/releases/tag/4.2.0) one addition made me think.

> Fix b2 engine not exiting, with error, early when it detects a Jam language
error. -- Mateusz Loskot

When installing libtorrent there has been this error for some versions when using `b2` but it never stopped my build or gave me an issue so i ignored it:

```
Jamroot.jam:1: syntax error at EOF
```

If i remove this file the problem is fixed. This appears to show that issue exists as i described but i would think it should error out earlier and more drastically than it does. Silently and after the build completes

I also did this to troubleshoot

```
rm -f Jamroot.jam
mv clang_tidy.jam Jamroot.jam
b2 ...
```

Then i see this.

```
/root/qbittorrent-build/share/boost-build/src/build/toolset.jam:170: in toolset.flags from module toolset
error: Module Jamfile</root/qbittorrent-build/libtorrent> attempted to set flags for module clang_tidy
Jamroot.jam:40: in modules.load from module Jamfile</root/qbittorrent-build/libtorrent>
/root/qbittorrent-build/share/boost-build/src/build/project.jam:372: in load-jamfile from module project
/root/qbittorrent-build/share/boost-build/src/build/project.jam:64: in load from module project
/root/qbittorrent-build/share/boost-build/src/build/project.jam:142: in project.find from module project
/root/qbittorrent-build/share/boost-build/src/build-system.jam:618: in load from module build-system
/root/qbittorrent-build/share/boost-build/src/kernel/modules.jam:295: in import from module modules
/root/qbittorrent-build/share/boost-build/src/kernel/bootstrap.jam:139: in boost-build from module
/root/qbittorrent-build/share/boost-build/boost-build.jam:8: in module scope from module
```

Doe this file need fixing?

https://github.com/arvidn/libtorrent/blob/RC_1_2/clang_tidy.jam

**Comment by userdocs** [comment]
If i am correct problem number 1 is an EOF issue in the jamfile fixed by appending this `;` to the `Jamfile.jam` 

```
include clang_tidy.jam ;
```

Which resolves the Syntax error issue 

```
Jamroot.jam:1: syntax error at EOF
```

Problem number 2 is now this creates another error which causes `b2` to exit at this point.

```
/root/qbittorrent-build/share/boost-build/src/build/toolset.jam:170: in toolset.flags from module toolset
error: Module Jamfile</root/qbittorrent-build/libtorrent> attempted to set flags for module clang_tidy
clang_tidy.jam:40: in modules.load from module Jamfile</root/qbittorrent-build/libtorrent>
/root/qbittorrent-build/share/boost-build/src/build/project.jam:372: in load-jamfile from module project
/root/qbittorrent-build/share/boost-build/src/build/project.jam:64: in load from module project
/root/qbittorrent-build/share/boost-build/src/build/project.jam:142: in project.find from module project
/root/qbittorrent-build/share/boost-build/src/build-system.jam:618: in load from module build-system
/root/qbittorrent-build/share/boost-build/src/kernel/modules.jam:295: in import from module modules
/root/qbittorrent-build/share/boost-build/src/kernel/bootstrap.jam:139: in boost-build from module
/root/qbittorrent-build/share/boost-build/boost-build.jam:8: in module scope from module
```

**Comment by arvidn** [comment]
the missing semicolon definitely seems to be an issue. I can't reproduce the second error locally (but I haven't tested with boost 1.73 yet). I'll see if the CI is happy with the missing semicolon first.

**Comment by userdocs** [comment]
Doe this imported file require any installed dependencies?

I install this on a  fresh vps with minimal installed dependencies and the rest install locally for the build so i am wondering if the minimal nature of the platform of the cause of the env errors.

```
Dependency - OK - build-essential
Dependency - OK - pkg-config
Dependency - OK - automake
Dependency - OK - libtool
Dependency - OK - git
Dependency - OK - perl
Dependency - OK - python3
Dependency - OK - python3-dev
```

**Comment by arvidn** [comment]
> Doe this imported file require any installed dependencies?

It's not supposed to. It doesn't depend on boost, it's a toolset for boost-build. It's possible there's been some changes to boost-build that affects toolsets.

**Comment by userdocs** [comment]
My boost is 1.7.3.0 and installed locally.

I get this with the semi colon present so there is some issue created i don't fully understand yet.

```
/root/qbittorrent-build/share/boost-build/src/build/toolset.jam:170: in toolset.flags from module toolset
error: Module Jamfile</root/qbittorrent-build/libtorrent> attempted to set flags for module clang_tidy
clang_tidy.jam:40: in modules.load from module Jamfile</root/qbittorrent-build/libtorrent>
/root/qbittorrent-build/share/boost-build/src/build/project.jam:372: in load-jamfile from module project
/root/qbittorrent-build/share/boost-build/src/build/project.jam:64: in load from module project
/root/qbittorrent-build/share/boost-build/src/build/project.jam:142: in project.find from module project
/root/qbittorrent-build/share/boost-build/src/build-system.jam:618: in load from module build-system
/root/qbittorrent-build/share/boost-build/src/kernel/modules.jam:295: in import from module modules
/root/qbittorrent-build/share/boost-build/src/kernel/bootstrap.jam:139: in boost-build from module
/root/qbittorrent-build/share/boost-build/boost-build.jam:8: in module scope from module
```

**Comment by arvidn** [comment]
yeah, I'll take a look. thanks for the report!

**Comment by userdocs** [comment]
Is it ok to comment this out this include to just build libtorrent locally in the meantime?

**Comment by arvidn** [comment]
yes, definitely. the `clang_tidy` toolset is mostly used on the CI, for analyzing the code

**Comment by xavier2k6** [comment]
that `syntax error at EOF` issue occurs when compiling with MSVC 2019 on windows too but seems to compile fine.......doesn't exit. (Boost 1.73)

**Comment by userdocs** [comment]
@xavier2k6 you might want to look at this to understand the exit issue.

https://github.com/boostorg/build/issues/585

**Comment by arvidn** [comment]
@userdocs I ended up removing the include of `clang_tidy.jam`, as it didn't seem to have the effect I was expecting anyway. So I think that would fix the issue you were seeing, is that right?

**Comment by userdocs** [comment]
Yes as the issue this side was the syntax error which is being handled differently in boost 1.73 than it was in previous version. That should resolve the issue from your side and the rest will be something the boost devs need to consider. If the include is gone the issue with libtorrent is resolved.

**Comment by arvidn** [comment]
thanks!
