### ISSUE TITLE
Does it have ed2k support?

### ISSUE THREAD

**Issue by UnknownObject000** [arvidn/libtorrent#4600]
Can I download ed2k links using this libary?If yes,how can I do that?

ed2k link like this:
ed2k://|file|cn_windows_server_2019_updated_jan_2020_x64_dvd_4bbe2c37.iso|5608552448|39C663ABF26079240030395C7CB3F975|/

**Comment by ssiloti** [comment]
No. Libtorrent does not support the protocol used to download ed2k links.
