### ISSUE TITLE
Pause during piece hash (disk_io_thread::abort_hash_jobs?) leads to "zombie" torrents

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [arvidn/libtorrent#4604]
**Please provide the following information**

libtorrent version (or branch):
Tested on version 1.2.2 and 1.2.6

platform/architecture:
linux/x64

compiler and compiler version:
gcc 9.3.0

actions taken:
On a downloading torrent, I call `torrent_handle::pause()`, and later `torrent_handle::resume()`.

expected result:
I should eventually see `torrent_finished_alert` from the session. I should see `piece_finished_alert`, or at least `hash_failed_alert`, for every piece. The torrent should eventually be in the `finished` and/or `seeding` states.

actual result:
Sometimes, I will not see `torrent_finished_alert` or `piece_finished_alert` for all pieces. The torrent finishes writing all data to disk, but stays in the `downloading` state forever. Further `pause()`/`resume()` calls do not fix the problem.

I've attached two python scripts I used to reproduce the bug. In one I supply the data synthetically with `torrent_handle::add_piece()`, in the other I set up a seed and manually connect it. The bug seems to be a race condition, as the scripts do not always trigger it, and I found that subtle timing issues e.g. flushing log output affects whether the bug is triggered. I attached output from "successful" bug triggerings for each script.

The relevant lines seem to be:
```
torrent_log_alert test.txt: disk error: (125) Operation canceled [piece_verified : unknown] in file: 
torrent_log_alert test.txt: *** PIECE_FINISHED [ p: 8 | chk: disk failed | size: 16384 ]
```
This seems to be an outcome of `disk_io_thread::abort_hash_jobs()` being called while a hash job was outstanding. I don't fully understand the resulting callback logic, but the outcome is that I never see `piece_finished_alert` or `torrent_finished_alert`.

Let me know if my test is somehow invalid.
[hash_abort_with_add_piece_success.txt](https://github.com/arvidn/libtorrent/files/4567318/hash_abort_with_add_piece_success.txt)
[hash_abort_with_seed_success.txt](https://github.com/arvidn/libtorrent/files/4567320/hash_abort_with_seed_success.txt)
[hash_abort_tests.tar.gz](https://github.com/arvidn/libtorrent/files/4567321/hash_abort_tests.tar.gz)

**Comment by arvidn** [comment]
It appears what's happening is:

1. an async hash job is posted to the disk threads
2. you pause the torrent, the hash jobs are cancelled
3. you resume the torrent
4. the hash jobs come back as cancelled, which causes the torrent to pause

The torrent ends up being paused. Does this fit your experience?

e.g. is it the case that you resume shortly after you pause?

It's not clear to me that it's important to cancel those hash checks when stopping a torrent. It probably makes sense to do that when doing a full check (and it's the same kind of job).

I can think of two simple approaches to solving this.

1. Don't cancel hash checking jobs when stopping a torrent. (this may slow down stopping a torrent performing a full hash check).
2. Make a cancelled disk job not cause the torrent to be paused. The pieces whose hash checks were cancelled may still be "lost" and re-downloaded when the torrent is resume, which also isn't ideal.

**Comment by AllSeeingEyeTolledEweSew** [comment]
It doesn't end up paused. In fact in my seed + downloader case, the auto-manager appears to resume the torrent on its own, and will download any pieces whose jobs were not cancelled. I also tried manually resuming the torrent (in hash_abort_with_seed.py, I call `handle.resume()` when I see `torrent_paused_alert`), but the effect is the same.

From an API perspective, all I do is pause the torrent at the right time while downloading. When the torrent resumes (auto or manual), it is in the zombie state.

Overall it appears the problem is the hash jobs are never re-started when the torrent is resumed. I assume if they did, it would fix things. I did not try `force_recheck()` on a zombie torrent yet, I'll try that and report.

**Comment by arvidn** [comment]
@AllSeeingEyeTolledEweSew would you mind giving this a try? https://github.com/arvidn/libtorrent/pull/4610

**Comment by AllSeeingEyeTolledEweSew** [comment]
#4610 seems to solve it. I ran my test script for a few hours and it never produced the bug. Previously it produced the bug in less than a minute.

I haven't yet tried to abort hash jobs during a force_recheck. Do you suspect any problems with this? I bet this path is pretty well-exercised in practice so maybe I shouldn't worry.

**Comment by arvidn** [comment]
I wouldn't expect this patch to introduce any new (serious) issues, but there's not really any unit test covering these cases. It would be nice to have that, but I would have to spend a fair amount of time on improving the fidelity of the simulation.

If this patch just didn't abort *any* of these jobs, things would still work, it would just take a bit longer to stop a torrent while being checked.

thanks for testing!
