### ISSUE TITLE
linker warning when static library is used (built with cmake)

### ISSUE THREAD

**Issue by Kolcha** [arvidn/libtorrent#4608]
libtorrent version (or branch): RC_1_2, all releases
platform/architecture: macOS, x86_64
compiler and compiler version: Apple clang version 11.0.3 (clang-1103.0.32.59)

linker produces next warnings when linking qBittorrent using static library:
```
ld: warning: direct access in function 'std::__1::__function::__func<libtorrent::storage_interface* (*)(libtorrent::storage_params const&, libtorrent::file_pool&), std::__1::allocator<libtorrent::storage_interface* (*)(libtorrent::storage_params const&, libtorrent::file_pool&)>, libtorrent::storage_interface* (libtorrent::storage_params const&, libtorrent::file_pool&)>::target(std::type_info const&) const' from file '/Users/nick/tmp/qbt-work/lib/libtorrent-rasterbar.a(create_torrent.cpp.o)' to global weak symbol 'typeinfo name for libtorrent::storage_interface* (*)(libtorrent::storage_params const&, libtorrent::file_pool&)' from file 'magneturi.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'std::__1::__function::__func<libtorrent::storage_interface* (*)(libtorrent::storage_params const&, libtorrent::file_pool&), std::__1::allocator<libtorrent::storage_interface* (*)(libtorrent::storage_params const&, libtorrent::file_pool&)>, libtorrent::storage_interface* (libtorrent::storage_params const&, libtorrent::file_pool&)>::target(std::type_info const&) const' from file '/Users/nick/tmp/qbt-work/lib/libtorrent-rasterbar.a(create_torrent.cpp.o)' to global weak symbol 'typeinfo name for libtorrent::storage_interface* (*)(libtorrent::storage_params const&, libtorrent::file_pool&)' from file 'magneturi.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'std::__1::__function::__func<libtorrent::storage_interface* (*)(libtorrent::storage_params const&, libtorrent::file_pool&), std::__1::allocator<libtorrent::storage_interface* (*)(libtorrent::storage_params const&, libtorrent::file_pool&)>, libtorrent::storage_interface* (libtorrent::storage_params const&, libtorrent::file_pool&)>::target_type() const' from file '/Users/nick/tmp/qbt-work/lib/libtorrent-rasterbar.a(create_torrent.cpp.o)' to global weak symbol 'typeinfo for libtorrent::storage_interface* (*)(libtorrent::storage_params const&, libtorrent::file_pool&)' from file 'magneturi.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'std::__1::__function::__func<std::__1::shared_ptr<libtorrent::torrent_plugin> (*)(libtorrent::torrent_handle const&, void*), std::__1::allocator<std::__1::shared_ptr<libtorrent::torrent_plugin> (*)(libtorrent::torrent_handle const&, void*)>, std::__1::shared_ptr<libtorrent::torrent_plugin> (libtorrent::torrent_handle const&, void*)>::target(std::type_info const&) const' from file '/Users/nick/tmp/qbt-work/lib/libtorrent-rasterbar.a(session.cpp.o)' to global weak symbol 'typeinfo name for std::__1::shared_ptr<libtorrent::torrent_plugin> (*)(libtorrent::torrent_handle const&, void*)' from file 'session.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'std::__1::__function::__func<std::__1::shared_ptr<libtorrent::torrent_plugin> (*)(libtorrent::torrent_handle const&, void*), std::__1::allocator<std::__1::shared_ptr<libtorrent::torrent_plugin> (*)(libtorrent::torrent_handle const&, void*)>, std::__1::shared_ptr<libtorrent::torrent_plugin> (libtorrent::torrent_handle const&, void*)>::target(std::type_info const&) const' from file '/Users/nick/tmp/qbt-work/lib/libtorrent-rasterbar.a(session.cpp.o)' to global weak symbol 'typeinfo name for std::__1::shared_ptr<libtorrent::torrent_plugin> (*)(libtorrent::torrent_handle const&, void*)' from file 'session.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'std::__1::__function::__func<std::__1::shared_ptr<libtorrent::torrent_plugin> (*)(libtorrent::torrent_handle const&, void*), std::__1::allocator<std::__1::shared_ptr<libtorrent::torrent_plugin> (*)(libtorrent::torrent_handle const&, void*)>, std::__1::shared_ptr<libtorrent::torrent_plugin> (libtorrent::torrent_handle const&, void*)>::target_type() const' from file '/Users/nick/tmp/qbt-work/lib/libtorrent-rasterbar.a(session.cpp.o)' to global weak symbol 'typeinfo for std::__1::shared_ptr<libtorrent::torrent_plugin> (*)(libtorrent::torrent_handle const&, void*)' from file 'session.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```
regardless `qmake` or `cmake` build system is used for qBittorrent

libtorrent is build as static library using `cmake` using next command line:
```
${cmake} -DCMAKE_PREFIX_PATH=${depsdir} -DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_OSX_DEPLOYMENT_TARGET=${min_macos_ver} -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=${depsdir} ..
```

noticed that just **dropping these lines** from `CMakeLists.txt` fixes warnings, so reported here:
https://github.com/arvidn/libtorrent/blob/48627d7dfe47fb50a99fbd429de25bebec129dfc/CMakeLists.txt#L514-L520

this decision was made based on `CMakeLists.txt` for 1.1.10 (it didn't produce any warnings), I found similar options were set only for shared library:
https://github.com/arvidn/libtorrent/blob/200bb494c32c2ed8ee9eef912e73130aeb265023/CMakeLists.txt#L220-L229
since 1.1.11 these options are set in both cases, so I decided drop few lines to see what happens, and was right - warnings are gone...

P.S> I'm not familiar with cmake neither these options purpose, I just decided to report my observation. I'm ready to test anything required. I even can check build on Win/Linux/macOS if required.

**Comment by arvidn** [comment]
libtorrent builds with visibility=hidden by default. I think this is the most reasonable default. This linker warning happens when you link *your* binary, right? where that libtorrent is part of?

Is it the case that you build your client without visibility=hidden? If so, is there a good reason to do so?

**Comment by Kolcha** [comment]
> This linker warning happens when you link _your_ binary, right?

right



> where that libtorrent is part of?

don't quite understand what do you mean



> Is it the case that you build your client without visibility=hidden? If so, is there a good reason to do so?

very likely... I found no compiler flags similar to yours (just searched for 'visibility') in qBittorrent build files, also didn't set anything explicitly. I have to read more on `-fvisibility=hidden`, I don't know its purpose. Also I'll try to add that option to qBittorrent and see what happen.
I just noticed that change since specific version and decided to report just to clarify is there no typo because previously option was added only in case of shared library.

**Comment by Kolcha** [comment]
so... I rebuilt qBittorrent with the same compiler options as libtorrent (added `-fvisibility=hidden -fvisibility-inlines-hidden` to compiler flags) and warnings are gone. I'll report that to qBittorrent.

what I quickly read about visibility flags from https://gcc.gnu.org/wiki/Visibility , now it's clear for me why you are set them for shared library (I'm familiar with similar stuff for Windows discussed in mentioned article), but still unclear the case for static library, but it also seem reasonable.

in any case thanks for your time spent to that issue, closing it.

**Comment by Chocobo1** [comment]
>so... I rebuilt qBittorrent with the same compiler options as libtorrent (added -fvisibility=hidden -fvisibility-inlines-hidden to compiler flags) and warnings are gone. I'll report that to qBittorrent.

So if the client program needs these flags in order to build successfully, maybe it is better that the library export these compile flags via pkgconfig/cmake instead of adding the flags at client program side?

**Comment by arvidn** [comment]
yes. the cmake file should definitely make the visibility setting propagate up to dependees
