### ISSUE TITLE
docs:create_torrent::[mutable_torrent_support]

### ISSUE THREAD

**Issue by bjmgeek** [arvidn/libtorrent#4614]
Documentation under heading "create_torrent::[mutable_torrent_support]" could be improved.  Specifically, mutable torrents are not BEP 38 (that's "Finding Local Data Via Torrent File Hints").  Instead, mutable torrents are BEP 39 or BEP 46, for instance.

**Comment by arvidn** [comment]
Well, none of those BEPs are actually *called* mutable torrents. In fact, "mutable torrents" (originally at least) referred to the combination of BEP 35, 36 and 38. I think BEP 38 is the most important, useful and interesting of those.

You're suggesting the libtorrent documentation should not refer to BEP 38 support as "supporting mutable torrents"?

Actually, the flag `mutable_torrent_support` does *exactly* what the documentation says (with regards to supporting BEP 38). So it's just the term "mutable torrent" that you think is misleading?

**Comment by bjmgeek** [comment]
Correct.  I think of mutable torrents as torrents whose content could change over time.  I think BEP 38 support is indeed important, but you could certainly have "related" torrents (e.g. that share some content) that weren't "mutable" (i.e. not able to be changed after publishing).
