### ISSUE TITLE
Will magnet not download anything until it downloads metadata?

### ISSUE THREAD

**Issue by zbooa** [arvidn/libtorrent#4615]
I added a magnet and returned handle. And
I want to pause it after it downloads metadata
When I receive <metadata_received_alert>
execution pause
but found that the file has been created... ...
The Torrent is a folder that creates a file at random.
Only one has been created, which is different each time. In theory, nothing should be created.

```
...
else if (auto p = lt::alert_cast<lt::metadata_received_alert>(a)) {
	lt::torrent_handle h = p->handle;
	if (h.is_valid() && h.has_metadata()) {
		PauseTask(h);
        }
}
...
```

```
void CMainWnd::PauseTask(lt::torrent_handle& h) {
	lt::torrent_status const& ts = h.status(lt::torrent_handle::query_torrent_file);
	if ((ts.flags & (lt::torrent_flags::auto_managed | lt::torrent_flags::paused)) != lt::torrent_flags::paused) {
		h.unset_flags(lt::torrent_flags::auto_managed);
		h.pause(lt::torrent_handle::graceful_pause);
	}
}
```
Did I do anything wrong?
The "Task" may have been paused, but the file was created before it was paused.
The Storage Mode is` storage_mode_allocate`.
Will the file just be created and not downloaded? 
I don't know. But it didn't meet expectations.

**Comment by arvidn** [comment]
by the time you get the metadata alert, the torrent has started downloading, yes. It may have created files by the time you pause it. The reason a different file is created each time is because pieces are picked rarest first in random order. setting the storage mode to allocate probably made the file that was created non-sparse, or at least `ftruncate`ed to its final size.

**Comment by arvidn** [comment]
to do what you want to do, you can set file priorities to 0 in the `add_torrent_params`. It's not ideal as you don't know how many files the torrent will have. I can't recall off the top of my head if setting upload mode or stop when finished flags will have the desired effect. You can look around in the docs on torrent flags and experiment. Please report back here. This is something that is fairly common to do, so it should be documented.

**Comment by zbooa** [comment]
> to do what you want to do, you can set file priorities to 0 in the `add_torrent_params`. It's not ideal as you don't know how many files the torrent will have. I can't recall off the top of my head if setting upload mode or stop when finished flags will have the desired effect. You can look around in the docs on torrent flags and experiment. Please report back here. This is something that is fairly common to do, so it should be documented.

Yes. On you!

**Comment by arvidn** [comment]
I think you can use the `upload_mode` flag to prevent it from downloading anything once you have the metadata

**Comment by zbooa** [comment]
> I think you can use the `upload_mode` flag to prevent it from downloading anything once you have the metadata

Yes. Make sure to remove it before downloading.
And "set file priorities to 0" 
It ok, both of them.I think.
