### ISSUE TITLE
deprecation of "torrent_status::paused" - what should I use instead? 

### ISSUE THREAD

**Issue by libTorrentUser** [arvidn/libtorrent#4621]
`torrent_handle::is_paused()` is deprecated and it says we should use `status()` instead.

But the `torrent_status::paused` field is also flagged as deprecated. So... what exactly should we be using instead? I thought about using the `state` field, but there is no "paused" state.

**Comment by zbooa** [comment]
> `torrent_handle::is_paused()` is deprecated and it says we should use `status()` instead.
> 
> But the `torrent_status::paused` field is also flagged as deprecated. So... what exactly should we be using instead? I thought about using the `state` field, but there is no "paused" state.

This is how I judge the state, v1.2.4
`bool IsPaused = (ts.flags & (lt::torrent_flags::auto_managed | lt::torrent_flags::paused)) == lt::torrent_flags::paused ? true : false;`

**Comment by libTorrentUser** [comment]
ah... simple as that wink wink :)

Kidding aside, my vote goes for making "paused" one the torrent states. And if that is too complicated, at least put a comment on the field saying that , from now on, we should be checking the flags.

By the way zbooa, why are you ORing the `lt::torrent_flags::auto_managed` flag? It has not effect on the result of your test. Or am I being stupid

**Comment by arvidn** [comment]
@libTorrentUser it makes the check also ensure that the `auto_managed` flag is *not* set. If that flag is set, it's commonly referred to as "queued".

The issue of making paused another state is that a torrent can be paused in any of the existing states, it's orthogonal to the downloading/seeding/checking states. To preserve fidelity there would need to be multiple new paused states; paused_downloading, paused_seeding, paused_checking.

Deprecated functions aren't part of the documentation (they are filtered out by the documentation generation script). Do you think it's still helpful to put comments in the headers referring to the flags?

**Comment by libTorrentUser** [comment]
Ah!!! So I was being stupid afterall. Anyway, I think you can see how confusing things may get. Can a queued torrent be paused? I don't think that would make sense. I don't use the `auto_managed` flag in my code, but if I did I would expect the library to only enqueue torrents I did not manually pause. If I paused them it means I don't want them to start. Ever. Until unpaused, of course :) So, shouldn't those flags be exclusive? Shouldn't the library enforce only one of them can be set?

And I see your point about making "paused" one of the states. You are right. Scratch that.

As for putting comments in the headers referring to the flags, I absolutely think it is necessary.  `torrent_handle::is_paused()`, was deprecated, but it had a comment telling me what to use instead. But unless I am mistaken (again hehe), `torrent_status::paused` has nothing. I think a simple comment there telling the user to check the flags would help a lot. And if checking if the `auto_managed` flag is not set is necessary to ensure the torrent is really paused, then I think you defintelly should add that too.

Once again, thanks for your time. I won't close this issue now because I still want to hear your explanation about the "auto-managed paused" torrents. But feel free to close it as soon as you answer, because, technically, you've already solved this issue by giving me the official way to check for the paused state.

**Comment by arvidn** [comment]
> Can a queued torrent be paused?

A queued torrent is already paused, by definition.

queued = paused AND auto_managed flag set.
stopped (or force-stopped) = paused AND NOT auto_managed flag set

basically, anything you would say "force" in front of, means the auto_managed flag is not set. It sounds like you would want (and perhaps expect) the auto_managed flag not be set by default. It is, but you can clear it in `add_torrent_params` before adding the torrent. If you add all torrents with that flag cleared, no queing logic will apply to any of them.

> So, shouldn't those flags be exclusive? Shouldn't the library enforce only one of them can be set?

"queued" isn't a "state" per se. It's a combination of `paused` and `auto_managed` flags set at the same time. `auto_managed` meaning that built-in queing logic in libtorrent can decide to resume and pause torrents. So:

stopped = paused AND NOT auto_managed
started = NOT paused AND auto_managed
queued = paused AND auto_managed
force-started = NOT paused AND NOT auto_managed

> And if checking if the auto_managed flag is not set is necessary to ensure the torrent is really paused, then I think you defintelly should add that too.

I feel pretty confident that is well documented. I would be interested if you have some suggestion of where I could add a cross reference in the docs to help with that though.

**Comment by libTorrentUser** [comment]
Sorry. Once again I was wrong.  I guess that when you said "queued" in that previous post that word got stuck in my mind and I wrote that whole diatribe thinking the auto_managed flag meant "queued state". You are absolutely right. 

One little nitpick, if I may - I think you are right, and the way you setup the flags make a lot of sense**as an implementation detail**. Even though I agree with your logic and I would do the same, I still think those are low level implementation details and the library should expose a higher level unified "status" to the user. 

Just to be clear: you explanation about the possible torrent status and why "paused" is not one of them made perfect sense. And so did your explanation about how the flags work. I agree with your implementation and would not change a thing. But I strongly suggest thinking about hiding all that from the library user and expose instead a unified status field, one that would all the current statuses + the started, stopped, etc.

As for the documentation, 
    // https://github.com/arvidn/libtorrent/blob/RC_1_2/include/libtorrent/torrent_flags.hpp#L111
    // specifies whether or not the torrent is to be started in a paused
    // state. I.e. it won't connect to the tracker or any of the peers
    // until it's resumed. This is typically a good way of avoiding race
    // conditions when setting configuration options on torrents before
    // starting them.
    constexpr torrent_flags_t paused = 4_bit;

I believe it is worded like that because that flag used to be part of `add_torrent_params` right. So that comment is talking about things in the context of a brand new torrent being added. But unless I am doing some wrong (and I am wrong quite often, as you could see in the previous posts hehe), that same flag is also used when checking the torrent status and that comment says nothing about also checking the `auto_managed` flag.

So, yeah, I think you should add a couple of lines right there. Maybe you've already talked about how to perform the "paused" check somewhere else in the docs, but for a person doing it like me, trying to find his way using the code comments (which, by the way, are great), then I say you should definitely

- tell the user where to go from `torrent_status::paused`. Something like, "use the flags field instead" 
- add a couple of lines about being ware of the `auto_managed` on the `paused` flags comments.

Once again, although I still think I higher level "status" function is needed, you implementation logic makes perfect sense. But if things are to remain like that, a couple of extra comment lines would help a lot.

Last, but not least, I hope my posts did not "sound" confrontational. If they did, please understand that it was not my intention at all. As usually, I am thankfull you are taking some moments of your free time to answer me.

**Comment by arvidn** [comment]
yes, the torrent flags used to only exist on add_torrent_params. How does this look?

https://github.com/arvidn/libtorrent/pull/4635

Pull requests are welcome if you can think of more improvements to the documentation

**Comment by libTorrentUser** [comment]
I think it looks great now. Thanks!
