### ISSUE TITLE
On the setting and checking of flags

### ISSUE THREAD

**Issue by zbooa** [arvidn/libtorrent#4624]
I am setting and trying to modify torrent's flags，I don't know much about `set_flags` and `unset_flags`. I try to go to w through the function. But I found that some tags can't be modified by functions
`lt::torrent_flags::share_mode` => `set_share_mode(bool b)`
`lt::torrent_flags::upload_mode` => `set_upload_mode(bool b)`
`lt::torrent_flags::seed_mode` => ???
... ... There may be others.
My question is 
For flags that cannot be modified by function, how to judge the status by torrent handle? How to modify?
Thanks.

**Comment by arvidn** [comment]
> For flags that cannot be modified by function, how to judge the status by torrent handle? How to modify?

If you want to see which flags are set on a torrent, inspect the [flags](https://libtorrent.org/reference-Core.html#flags) field in [torrent_status](https://libtorrent.org/reference-Core.html#torrent_status) object. You can get the torrent_status object by calling torrent_handle::status(), or by calling [session::post_torrent_updates()](https://libtorrent.org/reference-Session.html#post_torrent_updates()) (which is a more scalable way of getting torrent status updates).

To update flags, use set_flags() or unset_flags(), it looks like you've found those already.

**Comment by zbooa** [comment]
> > For flags that cannot be modified by function, how to judge the status by torrent handle? How to modify?
> 
> If you want to see which flags are set on a torrent, inspect the [flags](https://libtorrent.org/reference-Core.html#flags) field in [torrent_status](https://libtorrent.org/reference-Core.html#torrent_status) object. You can get the torrent_status object by calling torrent_handle::status(), or by calling [session::post_torrent_updates()](https://libtorrent.org/reference-Session.html#post_torrent_updates()) (which is a more scalable way of getting torrent status updates).
> 
> To update flags, use set_flags() or unset_flags(), it looks like you've found those already.

Yes, I read the doc. On you.
