### ISSUE TITLE
Which parameters can't be modified after returning handle?

### ISSUE THREAD

**Issue by zbooa** [arvidn/libtorrent#4629]
A torrent is added to session with parameters
`p.storage_mode = lt::storage_mode_sparse`
And returned a handle.
Can I change it to `lt::storage_mode_allocate` at this time ？
Can't this parameter be changed after it is added ?
Which parameters can't be modified after returning handle?

**Comment by arvidn** [comment]
I don't believe you can change the storage mode after the torrent has been added.

most parameters are controller by the torrent flags, and most of those you *can* change on a running torrent, but there are some you cannot, and I believe those are called out in the [documentation](https://libtorrent.org/reference-Core.html#torrent_flags_t).

**Comment by zbooa** [comment]
> I don't believe you can change the storage mode after the torrent has been added.
> 
> most parameters are controller by the torrent flags, and most of those you _can_ change on a running torrent, but there are some you cannot, and I believe those are called out in the [documentation](https://libtorrent.org/reference-Core.html#torrent_flags_t).

No, I can not.
But the torrent was added.I want to know storage_mode... some way?

**Comment by arvidn** [comment]
https://libtorrent.org/reference-Core.html#storage_mode

**Comment by zbooa** [comment]
> https://libtorrent.org/reference-Core.html#storage_mode

Did not find the answer, is the introduction. But thank you very much. Let me learn new knowledge.

**Comment by arvidn** [comment]
that link points to the field you look at to know what storage mode a torrent is in

**Comment by arvidn** [comment]
@zbooa I made some documentation updates. would you mind taking a look? https://github.com/arvidn/libtorrent/pull/4635
