### ISSUE TITLE
Avoid writing to fastresume if there's inadequate disk space

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4630]
**Please provide the following information**

libtorrent version (or branch):
1.2.6
platform/architecture:
Windows
compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

If your storage becomes full and you attempt to write to fastresume, it fails and nulled 0 kB file is written to disk. This basically corrupts the fastresume file for no good reason.

**Comment by arvidn** [comment]
I don't think there's any function in libtorrent that writes resume data *to disk*. You can get it in an `add_torrent_params` object, and you can encode that as a bencoded structure or flag buffer with `write_resume_data()`. But it's still *in memory*.

**Comment by arvidn** [comment]
But, whoever does write it to disk probably should first save it under a different name, and only if it succeeds does it rename the file to replace the existing file
