### ISSUE TITLE
Hole punch extension

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4634]
**Please provide the following information**

libtorrent version (or branch):
1.2.6

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Since PeX is disabled in private torrents the hole punch extension will not work for private torrents right? BTW what's the main rational behind disabling PeX in private torrents? Is it to prevent swarm merging? I couldn't find anything in bep documentations..

**Comment by arvidn** [comment]
> Since PeX is disabled in private torrents the hole punch extension will not work for private torrents right?

That's correct.

> BTW what's the main rational behind disabling PeX in private torrents? Is it to prevent swarm merging? I couldn't find anything in bep documentations..

private torrents rely on the peer list being secret. If you manage to guess one peer of a private swarm, PEX would give you full access to the swarm.

**Comment by an0n666** [comment]
Since in private torrents we can get endpoints from the tracker,
Is hole punching not possible without PeX?
Like if both peers are NATed and try to connect at the same time, first attempt would fail..but the next attempt would allow them to connect. Now to achieve this you have to be retrying peers pretty fast?

**Comment by arvidn** [comment]
> Is hole punching not possible without PeX?

The existing hole punching protocol requires PEX. The alternative would be for the tracker to act as rendezvous-server. When we were implementing this (in 2007) we thought it would be unlikely that tracker software would add any features like this, so we implemented it client-side only

> Now to achieve this you have to be retrying peers pretty fast?

You really need a 3rd party to act as introducer/rendezvous server.

**Comment by an0n666** [comment]
I think it would make sense to add such functionality to trackers. At least for private trackers since they’re not allowing PeX.
It could’ve been an optional extended function like PeX for trackers, leaving it up to tracker operators/coders to implement it.

**Comment by an0n666** [comment]
One problem with that would be that the peers would have to be connected with the tracker all the time. I don’t think any tracker operator would want to have that much of extra traffic.
However a rendezvous server could be setup to be dedicated for this purpose. Tracker would reply with the rendezvous server endpoint that it wants its peers to use.
