### ISSUE TITLE
Questiona about libgeoip and libmaxminddb

### ISSUE THREAD

**Issue by SKIYET** [arvidn/libtorrent#4646]
**Please provide the following information**

libtorrent version (or branch):
RC_1_2

platform/architecture:
Debian/amd64

compiler and compiler version:
gcc8.3

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I  have a question about geoip.
The libgeoip now is libmaxminddb. if I  want to compile the libtorrent with libmaxminddb, what should I do ?

**Comment by arvidn** [comment]
libtorrent has not use geoip for a very long time. If you want to build an old version of libtorrent, I suppose you have to update the `Jamfile` or `configure.ac` to look for the new library name
