### ISSUE TITLE
libtorrent + MSVC gives a libboost_date link error

### ISSUE THREAD

**Issue by 3unjee** [arvidn/libtorrent#4651]
Greetings and thank you for the great work on libtorrent,

I'm building libtorrent 1.2.2 with Boost 1.71.0 on MSVC 14.2 (2019). The build with b2 generates libtorrent.lib and libboost_system-vc142-mt-x64-1_71.lib just fine.

However, when linking against these two libraries in my program I get the following:
`LINK : fatal error LNK1104: cannot open file 'libboost_date_time-vc142-mt-x64-1_71.lib'`

Which is weird because `libboost_date` is not built during the compilation process.

Any idea on why this could happen ?

**Comment by arvidn** [comment]
most likely because msvc supports adding link dependencies via `#pragma`, and boost does so unless you define `BOOST_ALL_NO_LIBS`

**Comment by 3unjee** [comment]
Thank you @arvidn 

Updated my build script with the following: `b2 -j4 toolset=msvc address-model=64 define=BOOST_ALL_NO_LIBS variant=release link=static openssl-version=pre1.1`

I still get the same `libboost_date_time-vc142-mt-x64-1_71.lib` issue at link. Am I missing something?

**Comment by arvidn** [comment]
oh, you're using `b2` to build, then it should "just work". `BOOST_ALL_NO_LIBS` is defined by the Jamfile.

Are you building against boost from source? i.e. do you set `BOOST_ROOT` to your boost source directory?

**Comment by arvidn** [comment]
so, the link error happens when you build *your* program, right?
that's where you need to define `BOOST_ALL_NO_LIB`, in your project file

**Comment by 3unjee** [comment]
Yeah I've tried to add the flag to my project first, with no sucess.

Now I'm actually building b2 using MinGW with the following:
```
cd boost/tools/build/src/engine
sh build.sh gcc
```
*Then* calling the following:
`b2 -j4 toolset=msvc address-model=64 define=BOOST_ALL_NO_LIBS variant=release link=shared`

I've been building libtorrent with gcc / MinGW for quite a long time but I'm new to MSVC builds. Maybe I should be using bootstrap.bat instead ?

**Comment by arvidn** [comment]
I don't think that matters for this issue. Can you build the libtorrent examples? (with `b2`)?

**Comment by 3unjee** [comment]
```
msvc.link bin\msvc-14.2\release\address-model-64\link-static\threading-multi\bt-get2.exe
msvc.manifest bin\msvc-14.2\release\address-model-64\link-static\threading-multi\bt-get2.exe
msvc.link bin\msvc-14.2\release\address-model-64\link-static\threading-multi\dump_torrent.exe
msvc.manifest bin\msvc-14.2\release\address-model-64\link-static\threading-multi\dump_torrent.exe
compile-c-c++ bin\msvc-14.2\release\address-model-64\link-static\threading-multi\make_torrent.obj
make_torrent.cpp
msvc.link bin\msvc-14.2\release\address-model-64\link-static\threading-multi\make_torrent.exe
compile-c-c++ bin\msvc-14.2\release\address-model-64\link-static\threading-multi\connection_tester.obj
connection_tester.cpp
msvc.manifest bin\msvc-14.2\release\address-model-64\link-static\threading-multi\make_torrent.exe
msvc.link bin\msvc-14.2\release\address-model-64\link-static\threading-multi\connection_tester.exe
msvc.manifest bin\msvc-14.2\release\address-model-64\link-static\threading-multi\connection_tester.exe
compile-c-c++ bin\msvc-14.2\release\address-model-64\link-static\threading-multi\upnp_test.obj
upnp_test.cpp
msvc.link bin\msvc-14.2\release\address-model-64\link-static\threading-multi\upnp_test.exe
msvc.manifest bin\msvc-14.2\release\address-model-64\link-static\threading-multi\upnp_test.exe
...updated 31 targets...

```
Yeah they seem to build fine !

**Comment by 3unjee** [comment]
Okay I just made progress by defining `BOOST_ALL_NO_LIB` directly in the code.

Now I get the following:
```
libtorrent.lib(ip_notifier.obj) : error LNK2019: unresolved external symbol __imp_NotifyAddrChange referenced in function "public: virtual void __cdecl libtorrent::aux::`anonymous namespace'::ip_change_notifier_impl::async_wait(class std::function<void __cdecl(class boost::system::error_code const &)>)" (?async_wait@ip_change_notifier_impl@?A0x51017996@aux@libtorrent@@UEAAXV?$function@$$A6AXAEBVerror_code@system@boost@@@Z@std@@@Z)
libtorrent.lib(ip_notifier.obj) : error LNK2019: unresolved external symbol __imp_CancelIPChangeNotify referenced in function "public: virtual __cdecl libtorrent::aux::`anonymous namespace'::ip_change_notifier_impl::~ip_change_notifier_impl(void)" (??1ip_change_notifier_impl@?A0x51017996@aux@libtorrent@@UEAA@XZ)
..\..\..\Sky\lib\SkTorrent.dll : fatal error LNK1120: 2 unresolved externals
```
I guess I'm pretty close :) !

**Comment by arvidn** [comment]
any translation unit that (directly or transitively) include a boost header should have that macro define. preferably in the project itself.

The last link error is because you're not linking against `iphlpapi.lib`
