### ISSUE TITLE
qBittorrent and Deluge freeze, unkillable process

### ISSUE THREAD

**Issue by dRaiNe** [arvidn/libtorrent#4661]
libtorrent version (or branch):
- qBittorrent 4.2.5 => libtorrent 1.2.6.0
- Deluge 1.3.15 => libtorrent 1.0.11.0 (but I'm absolutely confident QB freezes) - I mention it because Deluge seems to have this issue, too.

platform/architecture:
- Windows 7 x64

compiler and compiler version:
- MSVC 2017 (https://github.com/qbittorrent/qBittorrent/wiki/Windows-compilation) for QB 4.2.5 (official installer)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

- Libtorrent freezes my computer (what a precise description of an issue):
- On qBittorrent startup (with 114 torrents), QB freezes for ~2 minutes. Interestingly, Chrome locks down, too. After this time, computer unfreezes. It's relatively clean machine with SSD in it. => A strange behaviour. Ok, I have a lot of torrents, the not responding-ness of QB may be QB's fault, but it seems to be setting up wifi connection and should not lock up for so long - Transmission on Windows doesn't! And it shouldn't lock Chrome - implying it has something to do with driver/socket initialion, perhaps?
- Then sometimes qBittorrent freezes in such a way (when torrenting) it results in unkillable process (having this issue for a long time across many versions). I couldn't kill the process even with Process Hacker or similar tools, also tried Powershell. In one of the previous versions of QB - the unkillable process even resulted in shutting PC down taking unusually very long time (on multiple occasions). A wild unreliable guess - something with process being stuck with driver (https://sysinternals.d4rk4.ru/Blog/2005/08/unkillable-processes.html) ? But I used internal laptop (only 2.4Ghz) wifi for torrenting previously and now I'm using USB 5GHz wifi, so the driver is different, isn't it? Both being plagued with this problem. I regularly let my PC sleep, so it may be a factor or not.
- Deluge has the same problem - only clue is libtorrent.
- Problem doesn't occur when using Transmission Qt Client on Windows x64! Their implementation is better in something.
- I'm not sure, but think even War Thunder's torrent launcher had similar issues in the past. If they use libtorrent, too.. It may point to the issue.

- QB works flawlessly on Linux Ubuntu x64 on the same machine and always did (previous versions).

Reproduction steps:
- Launch QB/Deluge on my machine => strange startup freeze (freezes everything using network - even Chrome). It unfreezes after a few minutes.
- Download/seed for some time then find out the program has frozen totally and you can't kill it's executable in process explorer (got to restart the machine).

I am willing to give any debug info I can to help reproduction of this problem.

**Comment by arvidn** [comment]
so, would it be possible for you to run a qbt build with debug information enabled (but it should probably still be a release build, or an `/OB1` build) and then get a stack trace sample of the process while it's freezing? (I believe it can be done via taskmanager).

My first guess would be that it's something disk related that's causing the freeze. Do you have pre-allocation enabled of files by any chance?

**Comment by dRaiNe** [comment]
![image](https://user-images.githubusercontent.com/4710901/82237087-67157f80-9935-11ea-9e4f-3e0839775ad5.png)

**Comment by ichorid** [comment]
I've witnessed a similar problem with Tribler on Ubuntu (SSD drive) when downloading a couple of big torrents. The core is stuck for about a minute. During this period there is a **huge** spike in the "i/o wait" on the system monitor. Basically, every other process related to disk i/o becomes frozen. The system unfreezes after that. The system uses Ubuntu 18.04, SSD drive and manually compiled libtorrent 1.2.2.0.

The same thing regularly happens to my low-power seedbox with Tribler Core. The system will become completely unresponsive in regards to disk i/o. I can't open a new ssh connection to it, and it becomes impossible to run anything (though e.g., already opened `htop` works fine). After a while the system unfreezes. The seedbox is based on an Atom CPU, uses HDD drive, runs Debian 10.04 32bit, stock libtorrent 1.1.11.0.

Another interesting detail is that killing Tribler does not resolve the disk lock-up immediately. It feels like there is some kind of a long queue of disk-related operations being processed by the system even after Tribler is killed. At [our issue](https://github.com/Tribler/tribler/issues/5319) people report zombie processes left too.

This only happens with Tribler 7.5 that is Python3 + `asyncio` based. Tribler 7.4.4 which was Python3, `twisted` based did not show such behavior.

**Comment by ichorid** [comment]
seems related to #4638 . We refactored a lot of Libtorrent wrapper for our upcoming 7.5 release. Could have stepped on that.

**Comment by ichorid** [comment]
@arvidn , would you kindly read through [the Tribler issue](https://github.com/Tribler/tribler/issues/5319) that is very similar to this one and tell if it rings a bell with you?
