### ISSUE TITLE
macOS, libtorrent 1.2.6 and Boost 1.73 

### ISSUE THREAD

**Issue by 3unjee** [arvidn/libtorrent#4662]
So, I've been updating my toolchain to libtorrent 1.2.6 and Boost 1.73.

Unfortunately I get the following when building on macOS: `clang: error: unknown argument: '-fcoalesce-templates'`

I guess `fcoalesce-templates` is deprecated ?

**Comment by arvidn** [comment]
I think this may be an issue in boost-build shipping in boost-1.73. does it still fail if you add `warnings-as-errors=off` on the `b2` command line?

**Comment by 3unjee** [comment]
I've tested with Boost 1.73 and libtorrent 1.2.2 with no success. This is probably related to Microsoft updating its macOS images on Azure to darwin-11.0.3.

I've ran a bunch of libtorrent builds there, macOS is the only one failing: https://dev.azure.com/bunjee/libtorrent/_build/results?buildId=1531&view=results

**Comment by arvidn** [comment]
yes, it seems there's some issue in the version check in boost-build.

**Comment by 3unjee** [comment]
Fixed it by commenting the following in boost/tools/build/src/tools/darwin.jam:
# - GCC 4.0 and higher in Darwin does not have -fcoalesce-templates.
```
    #if $(real-version) < "4.0.0"
    #{
        #flags darwin.compile.c++ OPTIONS $(condition) : -fcoalesce-templates ;
    #}
```
