### ISSUE TITLE
Build error 'size_t': is not a member of 'std' with VS 2019

### ISSUE THREAD

**Issue by fmike7** [arvidn/libtorrent#4666]
libtorrent version (or branch): 1.2.6
platform/architecture: Windows x86/32
compiler and compiler version: Visual Studio 2019 (v14.2)
Boost: 1.73

Built boost first, then building libtorrent using b2:
b2 toolset=msvc-14.2 link=static runtime-link=static boost-link=static variant=release debug-symbols=on architecture=x86 address-model=32

Getting multiple errors:
<path>\libtorrent-libtorrent-1_2_6\include\libtorrent/config.hpp(471): error C2039: 'size_t': is not a member of 'std'

Fixed this myself by adding #include \<cstddef\> into config.hpp and it built successfully. I wonder if someone ran into this before or not?

**Comment by arvidn** [comment]
yes, this has been fixed in the `RC_1_2` branch and will be included in the next stable release, 1.2.7
