### ISSUE TITLE
Feature request: notify_all() for callers of wait_for_alert()?

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [arvidn/libtorrent#4668]
**Problem**:

In python, I'd like to use `session.wait_for_alert(TIMEOUT)` in a thread to monitor alerts. When I shut down, I need that thread to stop waiting and return to python code for a graceful shutdown.

If `TIMEOUT` is long, then my program may not shut down in a timely manner.

If `TIMEOUT` is short (say 1000ms), then the alert thread is waking the CPU often just to check if it needs to shut down.

The only way I can see to force `wait_for_alert()` to terminate early is to `exit()` early, but then the session destructor is never called. In particular I believe the session destructor can't be called while `wait_for_alert()` is active, as the frame stack will hold a reference to the session.

I know `set_alert_notify()` avoids this problem, but for my application I don't like the idea of slowing down the libtorrent thread.

**Solution?**:

There could be some `session.notify_alert_waiters()`, which calls `notify_all()` on the underlying condition variable.

I might be missing some other way around this problem, or some other way to alert the waiter. It may be possible to use signals somehow in POSIX, but I don't think it's portable.

If you think `notify_alert_waiters()` is a good idea, I can do a PR.

**Comment by arvidn** [comment]
it seems like at the very lease, the session destructor should wake up all threads waiting on alerts.
the scary part about making the destructor signal other threads, is that somehow those other threads have a reference to the session object, which is destructed. They will all have dangling references to the session as soon as they return.

In an ideal world, such waiter-threads would be able to hold a shared_ptr to the session, and still wake up and shut down when it's time to terminate. To make that work, shutdown has to be explicit, with something like you suggest.

**Comment by AllSeeingEyeTolledEweSew** [comment]
Another idea I had is a "shutdown alert", with the contract being that after it gets delivered the session pointer becomes invalid. Not sure how that would work with alert memory management though, and still requires explicit shutdown.

"shutdown alert" could also be just fired explicitly and have no shutdown side-effects, as a mechanism to trigger alert handlers to shut down and release references on their own. Maybe it's equivalent to the `notify_all()` solution though.

I like the `notify_all()` solution though, since it offers flexibility. It lets the alert handler thread handle other events. It also lets the alert handler shut down and leaves the session alive to be used in some other way.

**Comment by arvidn** [comment]
If the solution to #4638 would be to `get_alert_fd()`, or something like that. Where instead of setting a callback, you get a file descriptor (for instance, one returned by `os.pipe()`) and the python binding will register the `alert_notify` callback to write a byte to that pipe (ideally it would only write a byte if the alert queue is empty).

That way a thread can block on alerts by `select()` ing on a file descriptor, and possibly some other signal indicating that it's time to shut down.

That would solve this problem too, right?

**Comment by AllSeeingEyeTolledEweSew** [comment]
That would solve it, indeed.

One small reason I'd prefer `notify_all()` is I can write an application that uses `wait_for_alert()`, and either choose a short or long timeout depending on whether `notify_all()` support is present, and that app is compatible with any libtorrent version. If I want to use `alert_fd`, I either need to restrict support to libtorrent 1.2.7+, or maintain two different event handlers.

**Comment by arvidn** [comment]
I've landed this https://github.com/arvidn/libtorrent/pull/4672
