### ISSUE TITLE
dht crawling with libtorrent

### ISSUE THREAD

**Issue by Manu-sh** [arvidn/libtorrent#4669]
Following older implementations like https://github.com/jiachengpan/dht-crawler and https://github.com/logchan/dht_crawler that use libtorrent i had tried to make the same thing but seem to be slower that another in python that dosn't use libtorrent https://github.com/out0fmemory/simDHT now my question is assuming that the rest of the code is okay, im doing something of wrong here? (_except that i use a single client (session) so i should maybe i had only a single dht_node with his relative node_id_).

```
    const std::string magnet_uri{"magnet:?xt=urn:btih:01c227c8c9aac311f9365b163ea94708c27a7db4"};

    auto ses = make_session();
    ses.async_add_torrent(make_torrent_params(magnet_uri));

    while (1) {

        std::vector<tlib::alert*> alerts;
		ses.pop_alerts(&alerts);

		for (tlib::alert *const a : alerts) {
			assert(a);

			// TODO handle connection error
			if (auto *const alert = tlib::alert_cast<tlib::metadata_received_alert>(a)) {
				const auto &thandle = alert->handle;
				assert(thandle.is_valid());
				cout << "metadata success" << endl;
				ses.remove_torrent(thandle, tlib::session::delete_files);
				continue;
				// return 0;
			}

			if (auto *const alert = tlib::alert_cast<tlib::metadata_failed_alert>(a)) {
				cout << "metadata failed" << endl;
				const auto &thandle = alert->handle;
				ses.remove_torrent(thandle, tlib::session::delete_files);
				continue;
				// return 0;
			}

			if (auto *const alert = tlib::alert_cast<tlib::dht_get_peers_alert>(a)) {
				const lt::sha1_hash hash = alert->info_hash;
				cout << "get_peers " << hash << endl;
				continue;
				// return 0;
			}

			if (auto *const alert = tlib::alert_cast<tlib::dht_announce_alert>(a)) {
				const lt::sha1_hash hash = alert->info_hash;
				cout << "announce " << hash << endl;
				ses.async_add_torrent(make_torrent_params(hash));
				continue;
				// return 0;
			}

			// cout << a->what() << endl;
			// cout << a->message() << endl;

		}


		std::this_thread::sleep_for(std::chrono::milliseconds(200));
		ses.post_torrent_updates();
}
```

**Comment by arvidn** [comment]
There's nothing obviously wrong in that code, that I can see.
when you say "slower", I take it you mean you receive fewer requests and/or see less DHT traffic in general. This is typically proportional to how well connected you are to the DHT network.

You should make sure to disable or setting a very high upload rate limit for the DHT. You may also want to run multiple instances. The libtorrent DHT doesn't do anything special to "crawl" so to speak, where nodes are continuously traversed to just collect as many nodes as possible.
There's also no mechanism to appear as having different node IDs to different nodes, perhaps as a way to end up in more routing tables.

However, you probably want to use the new DHT request that lists torrents in DHT nodes.

This wasn't supported in versions earlier than `master` though. https://github.com/arvidn/libtorrent/blob/master/tools/dht_sample.cpp

**Comment by Manu-sh** [comment]
thank you, this help me a lot to understand in which way i can move :smile:
