### ISSUE TITLE
Different proxies for different trackers

### ISSUE THREAD

**Issue by Nick222** [arvidn/libtorrent#4673]
Are libtorrent allows to use PAC-file for proxy settings or to set different proxies for different trackers ?

**Comment by arvidn** [comment]
> Are libtorrent allows to use PAC-file for proxy settings

I don't know what a PAC file is, but if it contains configurations for a proxy, it probably has the information you need to configure libtorrent. libtorrent is a library, so it won't be reading any configuration files itself.

> or to set different proxies for different trackers ?

no

**Comment by Nick222** [comment]
PAC https://en.wikipedia.org/wiki/Proxy_auto-config

**Comment by arvidn** [comment]
Parsing those files is out of scope for libtorrent
