### ISSUE TITLE
A torrent transitions to the Error state (Invalid argument)

### ISSUE THREAD

**Issue by x-yuri** [arvidn/libtorrent#4675]
This might be related to #4479. Right now I have the torrent list empty in `deluge`. Whenever I add one particular torrent, its state changes this way: `None -> Paused -> Checking -> Error`. The error is `EINVAL` (`22`, Invalid argument). `wireshark` doesn't show any requests to the tracker. The target directory is empty. When I add the torrent, I deselect all the files:

https://gist.github.com/x-yuri/1a8637420b9b70f77ec7fb2b06d654a5#file-2-deluge-error-txt

Another file from the same tracker succeeds. `wireshark` sees requests to the tracker, so supposedly the error (in the previous case) gets triggered before that. The target directory is empty. When I add the torrent, I deselect all the files:

https://gist.github.com/x-yuri/1a8637420b9b70f77ec7fb2b06d654a5#file-3-deluge-success-txt

Is there a way to make `libtorrent` produce debugging output? I'd prefer to find the cause without building `libtorrent` from source. Any suggestions?

`libtorrent` version (or branch): `1.2.6`
platform/architecture: Arch Linux x86_64
I believe my instance was built [this way][1].

[1]: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/libtorrent-rasterbar&id=a6a5bfc788ca226ac3f15e450e5ac4846fa2c30d#n38

**Comment by arvidn** [comment]
Interesting. I take it you get a `torrent_error_alert` and you look at `error`, which then is `EINVAL`.
Do you also get a `file_error_alert` by any chance? if so, what's `operation` set to? (you can print it with the `message()` call, as usual on alerts).

You can enable additional logging (in the form of more alerts) by setting more bits in the `settings_pack::alert_mask` setting. Specifically, `alert_category::torrent_log`, and `alert_category::session_log`

**Comment by arvidn** [comment]
I just saw your log. You, you do get `file_error_alert` and the operation is `partfile_read`

**Comment by x-yuri** [comment]
I added `lt.alert.category_t.torrent_log_notification` and `lt.alert.category_t.session_log_notification` (`python`) to the `alert_mask` and I can now see the `torrent_log_alert` alerts in the log. But that probably doesn't explain much:

https://gist.github.com/x-yuri/1a8637420b9b70f77ec7fb2b06d654a5#file-3-deluge-error-torrent-log-txt

**Comment by arvidn** [comment]
well, there it says: `file_error_alert: Slayer file_open (/home/yuri/win/Users/yuri/Desktop/torrents/Slayer/Albums/1996 - Undisputed Attitude + Live Intrusion (Bonus CD) (Japanese Edition)/08 - Filler_I Don't Want To Hear It (Minor Threat cover).mp3) error: Invalid argument`

the operation that fails is `open()`. Is it possible the filesystem that file is saved to may have some unexpected limitations? say, file name length or path length, or which characters can be used in filenames?

**Comment by x-yuri** [comment]
Oh, I see, when I rename the target directory (hide the downloaded files), the operation is `partfile_read`. When I rename it back, the operation is `file_open`.

The setup is probably not too common. I'm running Arch Linux. But the torrents are saved to the Windows (NTFS) partition.

Limitations? I'm not sure, but the following command succeeds:

```
$ file "/home/yuri/win/Users/yuri/Desktop/torrents/Slayer/Albums/1996 - Undisputed Attitude + Live Intrusion (Bonus CD) (Japanese Edition)/08 - Filler_I Don't Want To Hear It (Minor Threat cover).mp3"
/home/yuri/win/Users/yuri/Desktop/torrents/Slayer/Albums/1996 - Undisputed Attitude + Live Intrusion (Bonus CD) (Japanese Edition)/08 - Filler_I Don't Want To Hear It (Minor Threat cover).mp3: Audio file with ID3 version 2.3.0, contains:MPEG ADTS, layer III, v1, 320 kbps, 44.1 kHz, JntStereo
```

**Comment by arvidn** [comment]
Would it be possible to get an `strace` of the process, to capture the call that fails with `EINVAL`?
I suspect that the filesystem isn't supporting some flag or attribute I use.

perhaps `O_NOATIME`. You could try disabling that in the settings, `settings_pack::no_atime_storage`

https://libtorrent.org/reference-Settings.html#no_atime_storage

**Comment by x-yuri** [comment]
I believe the following is the relevant part of the strace:

```
...
[pid 1955312] openat(AT_FDCWD, "/home/yuri/win/Users/yuri/Desktop/torrents/.24b9f8875d0051ae374ee8374b73f8b96e586783.parts", O_RDONLY <unfinished ...>
[pid 1955311] epoll_ctl(32, EPOLL_CTL_MOD, 31, {EPOLLIN|EPOLLERR|EPOLLET, {u32=1543527000, u64=140507103648344}}) = 0
[pid 1955176] <... epoll_wait resumed>[{EPOLLIN, {u32=1543527000, u64=140507103648344}}], 128, -1) = 1
[pid 1955311] futex(0x56056038a9bc, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 1955176] epoll_wait(32,  <unfinished ...>
[pid 1955312] <... openat resumed>)     = 50
[pid 1955312] close(53)                 = 0
[pid 1955312] preadv(50, [{iov_base=0x7fca6801bae0, iov_len=16384}, {iov_base=0x7fca6801faf0, iov_len=16384}, {iov_base=0x7fca68023b00, iov_len=16384}, {iov_base=0x7fca68027b10, iov_len=16384}, {iov_base=0x7fca6802bb20, iov_len=16384}, {iov_base=0x7fca6802fb30, iov_len=16384}, {iov_base=0x7fca68033b40, iov_len=16384}, {iov_base=0x7fca68037b50, iov_len=16384}, {iov_base=0x7fca6803bb60, iov_len=16384}, {iov_base=0x7fca6803fb70, iov_len=16384}, {iov_base=0x7fca68043b80, iov_len=16384}, {iov_base=0x7fca68047b90, iov_len=16384}, {iov_base=0x7fca6804bba0, iov_len=16384}, {iov_base=0x7fca6804fbb0, iov_len=16384}, {iov_base=0x7fca68053bc0, iov_len=16384}, {iov_base=0x7fca68057bd0, iov_len=16384}, {iov_base=0x7fca6805bbe0, iov_len=16384}, {iov_base=0x7fca6805fbf0, iov_len=16384}, {iov_base=0x7fca68063c00, iov_len=16384}, {iov_base=0x7fca68067c10, iov_len=16384}, {iov_base=0x7fca6806bc20, iov_len=16384}, {iov_base=0x7fca6806fc30, iov_len=16384}, {iov_base=0x7fca68073c40, iov_len=16384}, {iov_base=0x7fca68077c50, iov_len=16384}, {iov_base=0x7fca6807bc60, iov_len=16384}, {iov_base=0x7fca6807fc70, iov_len=16384}, {iov_base=0x7fca68083c80, iov_len=16384}, {iov_base=0x7fca68087c90, iov_len=16384}, {iov_base=0x7fca6808bca0, iov_len=16384}, {iov_base=0x7fca6808fcb0, iov_len=16384}, {iov_base=0x7fca68093cc0, iov_len=16384}, {iov_base=0x7fca68097cd0, iov_len=16384}, ...], 69, -2139091968) = -1 EINVAL (Invalid argument)
[pid 1955312] madvise(0x7fca6803c000, 8265728, MADV_DONTNEED) = 0
[pid 1955312] epoll_ctl(32, EPOLL_CTL_MOD, 31, {EPOLLIN|EPOLLERR|EPOLLET, {u32=1543527000, u64=140507103648344}}) = 0
[pid 1955176] <... epoll_wait resumed>[{EPOLLIN, {u32=1543527000, u64=140507103648344}}], 128, -1) = 1
[pid 1955312] openat(AT_FDCWD, "/home/yuri/win/Users/yuri/Desktop/torrents/.24b9f8875d0051ae374ee8374b73f8b96e586783.parts", O_RDONLY <unfinished ...>
[pid 1955176] epoll_wait(32,  <unfinished ...>
[pid 1955312] <... openat resumed>)     = 53
[pid 1955312] close(50)                 = 0
[pid 1955312] preadv(53, [{iov_base=0x7fca6801bae0, iov_len=16384}], 1, -2139091968) = -1 EINVAL (Invalid argument)
...
```

I can reproduce it when I ask it to save the result specifically to `/home/yuri/win/Users/yuri/Desktop/torrents`. If I copy `.24b9f8875d0051ae374ee8374b73f8b96e586783.parts` from `/home/yuri/win/Users/yuri/Desktop/torrents` to `/home/yuri/win/Users/yuri/Desktop/torrents2` and ask it to save to the latter dir, the same error occurs. My guess is that the `.24b....parts` file is broken. For what it's worth it takes 2 gb. I believe the error gets [triggered][1] [here][2].

Do you understand what could have caused this? Or what exactly is going on? At some point I started debugging `deluge`. And I probably didn't always stop the process correctly. But most likely that was after I encountered the problem.

[1]: https://github.com/arvidn/libtorrent/blob/libtorrent-1_2_6/src/disk_io_thread.cpp#L2433-L2434
[2]: https://github.com/arvidn/libtorrent/blob/libtorrent-1_2_6/src/storage.cpp#L554-L555

**Comment by arvidn** [comment]
thanks! this is great. It really looks like the error is the file offset paste to that `preadv()`, which is:

`-2139091968` just beyond 2 GiB, but wrapped as a signed integer. I think you're onto something about the part file being that big. Either there's an internal limitation where I just assumed part files would never get that big, or there's an issue in sanitizing input when reading the part-file.

**Comment by arvidn** [comment]
as far as I can tell, the file offsets *are* correctly computed in `std::int64_t`, so they should be passed correctly. Could it be the libc wrapper around `preadv()` that converts the offset to 32 bits?

**Comment by arvidn** [comment]
I found an issue in the part file code. Could you give this patch a try?
https://github.com/arvidn/libtorrent/pull/4680

**Comment by x-yuri** [comment]
Awesome, with this change it doesn't produce errors.

But it coredumps :) Not sure if this is related.

```
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.2.6.0-ac4dd411c

file: '../../libtorrent-rasterbar-1.2.6/src/torrent.cpp'
line: 2823
function: announce_with_tracker
expression: e == tracker_request::stopped || state() != torrent_status::checking_files

stack:
1: libtorrent::assert_fail(char const*, int, char const*, char const*, char const*, int)
2:
3:
4:
5:
6:
7:
8:
9:
10:
11: clone

Aborted (core dumped)
```

When I "Force Re-check" the torrent.

**Comment by arvidn** [comment]
if you could rebuild that with debug symbols (`-g` or `-DCMAKE_BUILD_TYPE=Debug`) that stack trace would be a lot more helpful

**Comment by x-yuri** [comment]
Are you sure? My `configure` command is:

```
$ ./configure --enable-python-bindings --enable-debug CFLAGS=-g
```

And I can see `./configure` saying:

```
Compiler and linker flags:
...
  CFlags:               -lpthread -g -fvisibility=hidden
```

I even tried `make clean install`. And yet it coredumps, but provides no more names.

For most users the assertions are supposedly disabled (enabled e.g. with `--enable-debug`).

**Comment by arvidn** [comment]
hm. I'm not sure. Sometimes you need link with `-export-dynamic` and `-rdynamic` to have access to symbols from within the process

**Comment by x-yuri** [comment]
I'm still trying to obtain a better backtrace. Could this function be called by some external/system code? **UPD** Well, judging from this, unlikely:

```
                                                Stack trace of thread 3780159:
                                                #0  0x00007f8b5bb90355 raise (libc.so.6 + 0x3c355)
                                                #1  0x00007f8b59d9b117 _ZN10libtorrent11assert_failEPKciS1_S1_S1_i (libtorrent-rasterbar.so.10 + 0xa6117)
                                                #2  0x00007f8b59fdb35e n/a (libtorrent-rasterbar.so.10 + 0x2e635e)
                                                #3  0x00007f8b59ff08a4 n/a (libtorrent-rasterbar.so.10 + 0x2fb8a4)
                                                #4  0x00007f8b5a04438d n/a (libtorrent-rasterbar.so.10 + 0x34f38d)
                                                #5  0x00007f8b5a049337 n/a (libtorrent-rasterbar.so.10 + 0x354337)
                                                #6  0x00007f8b59daa3bd n/a (libtorrent-rasterbar.so.10 + 0xb53bd)
                                                #7  0x00007f8b59f18311 n/a (libtorrent-rasterbar.so.10 + 0x223311)
                                                #8  0x00007f8b59f15b44 n/a (libtorrent-rasterbar.so.10 + 0x220b44)
                                                #9  0x00007f8b59ba7b74 execute_native_thread_routine (libstdc++.so.6 + 0xcfb74)
                                                #10 0x00007f8b5bb3b422 start_thread (libpthread.so.0 + 0x9422)
                                                #11 0x00007f8b5bc53bf3 __clone (libc.so.6 + 0xffbf3)
```

But as for the preconditions, they seem to be: 1) `--enable-debug`, 2) slow connection. I can reproduce it when I connect to the internet via phone (internet sharing, mobile provider). Are you sure that assertion can't be false?

**Comment by arvidn** [comment]
> Are you sure that assertion can't be false?

Clearly it can :) It's not supposed to be though. There aren't supposed to be any tracker announces made while checking files, unless we just force-rechecked and we're stopping the download (and announcing a stopped event).

Is it possible that this announce is "manually" triggered by the client somehow?

**Comment by x-yuri** [comment]
The thing is I vaguely understand what I'm doing :) I have some basic C/C++ knowledge. And you may very well consider that my first encounter with `deluge`'s code occurred yesterday. (@cas-- Can you possibly join us?) And I don't really know how torrents work on the inside. Can you possibly explain what are announces? And what are the parts files? And why not every torrent has them?

As for the stacktrace, I was able to make some progress:

```
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.2.6.0-ac4dd411c

file: '../../libtorrent-rasterbar-1.2.6/src/torrent.cpp'
line: 2822
function: announce_with_tracker
expression: e == tracker_request::stopped || state() != torrent_status::checking_files

stack:
1: libtorrent::assert_fail(char const*, int, char const*, char const*, char const*, int)
2: libtorrent::torrent::announce_with_tracker(unsigned char)
3: libtorrent::torrent::tracker_request_error(libtorrent::tracker_request const&, boost::system::erro
r_code const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&
, std::chrono::duration<int, std::ratio<1l, 1l> >)
4: libtorrent::tracker_connection::fail_impl(boost::system::error_code const&, std::__cxx11::basic_st
ring<char, std::char_traits<char>, std::allocator<char> >, std::chrono::duration<int, std::ratio<1l,
1l> >, std::chrono::duration<int, std::ratio<1l, 1l> >)
5: boost::asio::detail::completion_handler<std::_Bind<void (libtorrent::tracker_connection::*(std::sh
ared_ptr<libtorrent::tracker_connection>, boost::system::error_code, std::__cxx11::basic_string<char,
 std::char_traits<char>, std::allocator<char> >, std::chrono::duration<int, std::ratio<1l, 1l> >, std
::chrono::duration<int, std::ratio<1l, 1l> >))(boost::system::error_code const&, std::__cxx11::basic_
string<char, std::char_traits<char>, std::allocator<char> >, std::chrono::duration<int, std::ratio<1l
, 1l> >, std::chrono::duration<int, std::ratio<1l, 1l> >)> >::do_complete(void*, boost::asio::detail:
:scheduler_operation*, boost::system::error_code const&, unsigned long)
6: boost::asio::detail::scheduler::do_run_one(boost::asio::detail::conditionally_enabled_mutex::scope
d_lock&, boost::asio::detail::scheduler_thread_info&, boost::system::error_code const&)
7: boost::asio::detail::scheduler::run(boost::system::error_code&)
8:
9:
10:
11: clone
```

```
Stack trace of thread 4061875:
#0  0x00007fb0801dc355 raise (libc.so.6 + 0x3c355)
#1  0x00007fb07e074a04 _ZN10libtorrent11assert_failEPKciS1_S1_S1_i (libtorrent-rasterbar.so.10 + 0x240a04)
#2  0x00007fb07e2eb706 _ZN10libtorrent7torrent21announce_with_trackerEh (libtorrent-rasterbar.so.10 + 0x4b7706)
#3  0x00007fb07e2ee230 _ZN10libtorrent7torrent21tracker_request_errorERKNS_15tracker_requestERKN5boost6system10error_codeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENSt6chrono8durationIiSt5ratioILl1ELl1EEEE (libtorrent-rasterbar.so.10 + 0x4ba230)
#4  0x00007fb07e366cd6 _ZN10libtorrent18tracker_connection9fail_implERKN5boost6system10error_codeENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENSt6chrono8durationIiSt5ratioILl1ELl1EEEESG_ (libtorrent-rasterbar.so.10 + 0x532cd6)
#5  0x00007fb07e36b3fc _ZN5boost4asio6detail18completion_handlerISt5_BindIFMN10libtorrent18tracker_connectionEFvRKNS_6system10error_codeENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENSt6chrono8durationIiSt5ratioILl1ELl1EEEESK_ESt10shared_ptrIS5_ES7_SF_SK_SK_EEE11do_completeEPvPNS1_19scheduler_operationES9_m (libtorrent-rasterbar.so.10 + 0x5373fc)
#6  0x00007fb07e085e2a _ZN5boost4asio6detail9scheduler10do_run_oneERNS1_27conditionally_enabled_mutex11scoped_lockERNS1_21scheduler_thread_infoERKNS_6system10error_codeE (libtorrent-rasterbar.so.10 + 0x251e2a)
#7  0x00007fb07e086953 _ZN5boost4asio6detail9scheduler3runERNS_6system10error_codeE (libtorrent-rasterbar.so.10 + 0x252953)
#8  0x00007fb07e2164b1 n/a (libtorrent-rasterbar.so.10 + 0x3e24b1)
#9  0x00007fb07dce6b74 execute_native_thread_routine (libstdc++.so.6 + 0xcfb74)
#10 0x00007fb080187422 start_thread (libpthread.so.0 + 0x9422)
#11 0x00007fb08029fbf3 __clone (libc.so.6 + 0xffbf3)
```

I rarely build C++ projects, so it didn't occur to me early, that I probably should use `CXXFLAGS=-g`, not `CFLAGS=-g`. And I've found the [`--enable-export-all`][1] [switch][2].

Then, the crash happens regardless of the parts file size, even if the torrent has none. And it reproduces without your patch. So if you think it's time to start a new issue, just tell me.

Also, I wasn't able to reproduce it without a phone (mobile connection). Another precondition is `--enable-debug`, which supposedly enables the assertions. And somehow I wasn't able to reproduce it without `CXXFLAGS=-g`.

The steps to reproduce are roughly as follows. Start `deluge`. It starts checking the only torrent it has in the list, then transitions to "Seeding" (or seeds right from the start). "Force Re-check" it. It starts checking, then crashes. Usually, it's enough to force-recheck it once.

If you explain me what announces are (although I'm probably starting to understand), and what to look for in `deluge`'s code (which API calls), I'll give it a try.

[1]: https://github.com/arvidn/libtorrent/blob/libtorrent-1_2_6/configure.ac#L233
[2]: https://github.com/arvidn/libtorrent/blob/libtorrent-1_2_6/configure.ac#L413-L415

**Comment by arvidn** [comment]
I see, this happens when a tracker fails (for some reason, the error isn't preserved in the call stack), the next tracker in the list is attempted to be contacted. However, this is some time after the initial tracker was attempted. Say, perhaps the tracker timed out. By that time, the torrent state may have changed.

i.e. I think the sequence is this:

1. a torrent is starting and attempts to contact a tracker
2. the torrent transitions into checking mode (do you trigger this manually?)
3. the tracker times out and the next time is attempted to be contacted
4. the assert fails because we shouldn't be announcing while checking files

Regarding "announce", it's the act of contacting a tracker, which is a server that helps introduce bittorrent peers to each other. It's not mandatory (anymore) since there are other ways of finding peers also, like the DHT. I put together a glossary [here](http://libtorrent.org/manual-ref.html#glossary) (feedback welcome!).

**Comment by arvidn** [comment]
could you give this patch a try? https://github.com/arvidn/libtorrent/pull/4683

**Comment by x-yuri** [comment]
I just thought that it doesn't always reproduce, so how do I know if it's fixed? How many tries should I do? My idea is for you to show me in the output:

https://gist.github.com/x-yuri/1a8637420b9b70f77ec7fb2b06d654a5#file-5-deluge-error-2-txt

what to look for. Like, there's this line, then another one, so it should have crashed, but with the fix it doesn't. What do you say? I enabled `lt.alert.category_t.torrent_log_notification` and `lt.alert.category_t.session_log_notification`, and filtered out some alerts like `session_stats_alert`, `session_stats_header_alert`.

> I put together a glossary here (feedback welcome!).

Well, I think I understand what announces are now. But still not sure what are *.parts files, and why they don't not always exist. Torrent files contain hashes? But these files are usually small. While *.parts files might be quite big. Torrent files contain hashes of files, and *.parts files contain hashes of pieces? Then why are they not always present? Can I delete *.parts files?

**Comment by arvidn** [comment]
bittorrent can only validate and upload data from whole pieces. A piece is validated by hashing it and comparing against the piece-hash, in the .torrent file. Pieces are not necessarily aligned to files, and a piece may span two files. If one of the files is set to priority 0, the part of the piece that would have been written to that file, is instead written to the part file.

So, part files contain actual payload. Data that the user doesn't want, but are necessary in order to validate and upload data that the user *do* want.

**Comment by arvidn** [comment]
that output in the gist, is that from a build with the patch I posted? or from an earlier version?

**Comment by x-yuri** [comment]
For now without the patch. My idea is that to be able to confirm that the issue is fixed I need to understand where it goes wrong without the patch.

**Comment by x-yuri** [comment]
Okay, [this one][1] is with the patch. And the way I interpret it, it occasionally starts announcing, then switches to checking, not stopping the announcing thing:

```
tracker_announce_alert: [HorribleSubs] Berserk - 01 [1080p].mkv (http://nyaa.tracker.wf:7777/announce)[127.0.0.1:61327] sending announce (started)
...
tracker_announce_alert: [HorribleSubs] Berserk - 01 [1080p].mkv (http://nyaa.tracker.wf:7777/announce)[192.168.137.210:61327] sending announce (started)
...
tracker_announce_alert: [HorribleSubs] Berserk - 01 [1080p].mkv (http://nyaa.tracker.wf:7777/announce)[172.17.0.1:61327] sending announce (started)
...
state_changed_alert: [HorribleSubs] Berserk - 01 [1080p].mkv: state changed to: checking (r)
...
state_changed_alert: [HorribleSubs] Berserk - 01 [1080p].mkv: state changed to: checking
```

With no line like this:

```
tracker_announce_alert: [HorribleSubs] Berserk - 01 [1080p].mkv (http://nyaa.tracker.wf:7777/announce)[192.168.137.210:61327] sending announce (stopped)
```

before transitioning to "checking."

[1]: https://gist.github.com/x-yuri/1a8637420b9b70f77ec7fb2b06d654a5#file-6-deluge-success-txt

**Comment by arvidn** [comment]
it sounds like this issue was fixed then. I've landed the patch
