### ISSUE TITLE
Peer_id

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4684]
Libtorrent 1.2.6

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Libtorrent is generating per torrent peer_id for announcing to tracker. Some trackers hash a key using peer_id and userid to track peers stats. Due to random peer_id per torrent you have to hash and store a large number of keys in buffer. Is there any good reason why unique peer_ids are generated for each torrent? Why can’t we reuse the same peer_id across all torrents when announcing to trackers.

**Comment by arvidn** [comment]
the reason is privacy

**Comment by an0n666** [comment]
You mean privacy in trackers which do not use the compact list of peers?
Do such trackers really exist? I am yet to find one among the well known private trackers.
Also how does this ensure privacy? If you still use the same port for all torrents. I could still track someone using their IP:Port.

**Comment by arvidn** [comment]
> You mean privacy in trackers which do not use the compact list of peers?

No. I mean trackers tracking peers. Bit the random peer_id extends to what's sent to peers as well (each peer gets a different peer_id).

> Do such trackers really exist? I am yet to find one among the well known private trackers.

I doubt anyone uses that format anymore, except i2p trackers, which have to.

> Also how does this ensure privacy? If you still use the same port for all torrents. I could still track someone using their IP:Port.

It doesn't *ensure* privacy, it makes tracking a bit harder. For instance, if the IP:port is just as good, couldn't that be used to tracker peer's stats instead?

**Comment by an0n666** [comment]
Private trackers can still track you because they use a passkey in the tracker URL which is used to identify the user. So it makes no sense how generating random peer_id would make it hard for the tracker to track their activity. Maybe it’d make sense for public trackers where you do not announce with a passkey url. 

IP:port can’t be used to track stats because some peers are on dual stack or they have multiple IP addresses.

**Comment by arvidn** [comment]
> Private trackers can still track you because they use a passkey in the tracker URL which is used to identify the user. So it makes no sense how generating random peer_id would make it hard for the tracker to track their activity. Maybe it’d make sense for public trackers where you do not announce with a passkey url.

I think it makes perfect sense. it makes it harder for public trackers, and it doesn't affect private trackers since they have a passkey anyway.

**Comment by an0n666** [comment]
If someone is tracking peers using peer_id I guess it’ll just increase the chances of peer_id collisions. Since the tracker will have all peers with unique peer_id instead of some users with unique peer_ids. The result of which could be removing one of them from the peer list.
