### ISSUE TITLE
Torrent finished, when can the file be used?

### ISSUE THREAD

**Issue by fmike7** [arvidn/libtorrent#4688]
libtorrent version (or branch): 1.2.6
platform/architecture: Windows 10/64 bit
compiler and compiler version: Visual Studio 2019 (14.2)

My app downloads exe files from private torrent tracker and once received, it launches them. The issue I am running into is the file remains locked after torrent status changes to finished. Sharing violation error occurs, because it's still open for writing by libtorrent.

What is proper way to ensure that newly finished torrent file is closed and can be used? Shall I wait for another alert first?

Also what is interesting, libtorrent seems to be stumbling on itself, because after status changes to "seeding" it error with "The system cannot open the device or file specified "" (3) (category: 17)"

Here is the sequence:
1) downloading (getting alerts with percentages of completion)
2) alert: state changed to: finished
3) alert: torrent_finished_alert
4) alert: state changed to: seeding
5) alert::error_notification comes "{downloaded_filename} ({tracker_URL})[{address:port}] The system cannot open the device or file specified "" (3) (category: 17)
6) here in another process I am trying to launch the {downloaded_filename} and getting "The process cannot access the file because it is being used by another process."
7) alert: save_resume_data_alert
8) alert (non-error): {downloaded_filename} (category: 8)

After a while, the file becomes unlocked and I can launch a process using it, no sharing violation occurs.

**Comment by arvidn** [comment]
libtorrent always opens files with `FILE_SHARE_READ | FILE_SHARE_WRITE`, so it's probably the other application that's requesting exclusive access to the file.

libtorrent doesn't re-open files in read-only mode immediately as they are finished, but when the whole torrent finishes, all files will be closed (and possibly re-opened in read-only mode) and a `cache_flushed_alert` will be posted to let the client synchronize.

> alert::error_notification comes "{downloaded_filename} ({tracker_URL})[{address:port}] The system cannot open the device or file specified "" (3) (category: 17)

This is a tracker announce "failing", and by the looks of things, the `address:port` probably is a network that cannot reach the tracker. Is it `127.0.0.1` for instance? or is it some other local network? or an unconfigured IPv6 network?

I don't think it has anything to do with file I/O, and I would expect you to see those messages (but also a successful announce from some other network interface).

**Comment by fmike7** [comment]
Yeah, it's CreateProcess that needs exclusive access to prevent writes into image files while the process is running. As I said, once torrent is fully downloaded, my app launches (using CreateProcess) the file right from the torrent storage folder. I will try to use cache_flushed_alert as you suggested to synchronize. Thanks!

Address:port is 127.0.0.1:22551 (22551 is my custom port number that I use for private torrent seeding). I just noticed that this message is actually repeating multiple times throughout my log files and it's unrelated to the locked files.

So what would this mean? Torrent seeding is not working from this interface?

**Comment by arvidn** [comment]
> So what would this mean? Torrent seeding is not working from this interface?

Right, because it's the loopback interface. It can only reach other processes running on your machine. I assume you're listening on `0.0.0.0` though, which means *another* interface *is* announcing.

**Comment by fmike7** [comment]
Yes, I am listening on 0.0.0.0 - here is what I do:
lt::settings_pack session_settings;
session_settings.set_str(lt::settings_pack::listen_interfaces, std::string("0.0.0.0:22551"));
auto torrent_session = lt::session(session_settings);

In my understanding, 0.0.0.0 tells it to listen on all available interfaces, right?

It does output the following then, meaning that it listens on the non-loopback interface too:
successfully listening on [TCP] 192.168.181.113:22551 (category: 64)
successfully listening on [UDP] 192.168.181.113:22551 (category: 64)
successfully listening on [TCP] 127.0.0.1:22551 (category: 64)
successfully listening on [UDP] 127.0.0.1:22551 (category: 64

But then errors only on 127.0.0.1, but not the 192.168. interface. But should I just ignore this this error or is there a way to suppress it somehow?

**Comment by arvidn** [comment]
> But then errors only on 127.0.0.1, but not the 192.168. interface. But should I just ignore this this error

Yes.

**Comment by fmike7** [comment]
``cache_flushed_alert`` works, thanks!
