### ISSUE TITLE
alert message are cut

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#4696]
master branch

alert messages are limited to 200 character. Often the actual info gets cut of if the torrent name is long because the message starts with the name.
Maybe the used torrent name should be limited.

example: leaves about 155 characters for torrent name. However, it is utf8 encoded so it could be half or less.
char ret[200];
std::snprintf(ret, sizeof(ret), "%s block finished downloading (piece: %d block: %d)"
			, peer_alert::message().c_str(), static_cast<int>(piece_index), block_index);

**Comment by arvidn** [comment]
Do you have a suggestion for how to fix this? use `std::stringstream` instead perhaps?

Part of me is interested in pulling the "stringification" of alerts out into a free function that can be dead-code eliminated if it isn't used. In that case I wouldn't care as much about the resources used to print the string.

**Comment by vktr** [comment]
I've been using [{fmt}](https://fmt.dev) in a few other projects, which is supposedly landing in C++20 as https://en.cppreference.com/w/cpp/utility/format/format.

If it's not urgent, perhaps an overhaul of the string formatting can be done when we have format in C++20?

**Comment by arvidn** [comment]
yes, fmt is great and I'm looking forward to using it in C++20. I'm especially excited about how locales are disabled by default (which is the only sane design)

**Comment by MassaRoddel** [comment]
At least the torrent name should be truncated to fit the buffer without losing characters from the actual error message.
I was wondering what error "pe" meant until I figured out that the torrent name was long enough to leave only three characters for the error text. (pe comes from peer ...)

**Comment by vktr** [comment]
I'll see if I can find some time to make a PR for this
