### ISSUE TITLE
Assert in http_connection.cpp

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#4697]
libtorrent version (or branch): master

platform/architecture: Win7/64Bit
compiler and compiler version: VS2015

I get this assert in http_connection.cpp 253
TORRENT_ASSERT(!ssl || m_ssl_ctx != nullptr);

(several times already)

**Comment by arvidn** [comment]
Do you know of any specific circumstances where this happens?
I take it you’re not using an SSL torrent (but perhaps an SSL tracker)

**Comment by MassaRoddel** [comment]
It is a tracker problem. I just made a test torrent with a tracker from another failing torrent. It always asserts. Here is the stack:

>  	KernelBase.dll!000007fefd6a0932()	Unbekannt
 	MooPolice.exe!libtorrent::assert_fail(const char * expr, int line, const char * file, const char * function, const char * value, int kind) Zeile 387	C++
>	MooPolice.exe!libtorrent::http_connection::start(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & hostname, int port, std::chrono::duration<__int64,std::ratio<1,1000000000> > timeout, int prio, const libtorrent::aux::proxy_settings * ps, bool ssl, int handle_redirects, const boost::optional<boost::asio::ip::address> & bind_addr, libtorrent::flags::bitfield_flag<unsigned char,libtorrent::aux::resolver_flag_tag,void> resolve_flags, libtorrent::i2p_connection * i2p_conn) Zeile 253	C++
 	MooPolice.exe!libtorrent::http_connection::get(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & url, std::chrono::duration<__int64,std::ratio<1,1000000000> > timeout, int prio, const libtorrent::aux::proxy_settings * ps, int handle_redirects, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & user_agent, const boost::optional<boost::asio::ip::address> & bind_addr, libtorrent::flags::bitfield_flag<unsigned char,libtorrent::aux::resolver_flag_tag,void> resolve_flags, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & auth_, libtorrent::i2p_connection * i2p_conn) Zeile 213	C++
 	MooPolice.exe!libtorrent::http_tracker_connection::start() Zeile 236	C++
 	MooPolice.exe!libtorrent::tracker_manager::queue_request(boost::asio::io_context & ios, libtorrent::tracker_request && req, const libtorrent::aux::session_settings & sett, std::weak_ptr<libtorrent::request_callback> c) Zeile 301	C++
 	MooPolice.exe!libtorrent::aux::session_impl::queue_tracker_request(libtorrent::tracker_request req, std::weak_ptr<libtorrent::request_callback> c) Zeile 1234	C++
 	MooPolice.exe!libtorrent::torrent::announce_with_tracker(libtorrent::event_t e) Zeile 3064	C++
 	MooPolice.exe!libtorrent::torrent::start_announcing() Zeile 9429	C++
 	MooPolice.exe!libtorrent::torrent::files_checked() Zeile 8075	C++
 	MooPolice.exe!libtorrent::torrent::on_resume_data_checked(libtorrent::status_t status, const libtorrent::storage_error & error) Zeile 2160	C++
 	MooPolice.exe!libtorrent::torrent::init::__l2::<lambda>(libtorrent::status_t st, const libtorrent::storage_error & error) Zeile 1880	C++
 	[Externer Code]	
 	MooPolice.exe!libtorrent::aux::`anonymous namespace'::caller_visitor::operator()(std::function<void __cdecl(enum libtorrent::status_t,libtorrent::storage_error const &)> & h) Zeile 92	C++
 	MooPolice.exe!boost::detail::variant::invoke_visitor<libtorrent::aux::`anonymous namespace'::caller_visitor const ,0>::internal_visit<std::function<void __cdecl(enum libtorrent::status_t,libtorrent::storage_error const & __ptr64)> & __ptr64>(std::function<void __cdecl(enum libtorrent::status_t,libtorrent::storage_error const &)> & operand, int __formal) Zeile 1059	C++
 	MooPolice.exe!boost::detail::variant::visitation_impl_invoke_impl<boost::detail::variant::invoke_visitor<libtorrent::aux::`anonymous namespace'::caller_visitor const ,0>,void * __ptr64,std::function<void __cdecl(enum libtorrent::status_t,libtorrent::storage_error const & __ptr64)> >(int __formal, boost::detail::variant::invoke_visitor<libtorrent::aux::`anonymous namespace'::caller_visitor const ,0> & visitor, void * storage, std::function<void __cdecl(enum libtorrent::status_t,libtorrent::storage_error const &)> * __formal, boost::mpl::bool_<1> __formal) Zeile 115	C++
 	MooPolice.exe!boost::detail::variant::visitation_impl_invoke<boost::detail::variant::invoke_visitor<libtorrent::aux::`anonymous namespace'::caller_visitor const ,0>,void * __ptr64,std::function<void __cdecl(enum libtorrent::status_t,libtorrent::storage_error const & __ptr64)>,boost::variant<std::function<void __cdecl(libtorrent::disk_buffer_holder,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>,libtorrent::digest32<160> const & __ptr64,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>,libtorrent::digest32<256> const & __ptr64,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(enum libtorrent::status_t,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(void)>,std::function<void __cdecl(enum libtorrent::status_t,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(std::basic_string<char,std::char_traits<char>,std::allocator<char> >,libtorrent::aux::strong_typedef<int,libtorrent::aux::file_index_tag,void>,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>)>,std::function<void __cdecl(libtorrent::storage_error const & __ptr64,libtorrent::aux::container_wrapper<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void>,libtorrent::aux::strong_typedef<int,libtorrent::aux::file_index_tag,void>,std::vector<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void>,std::allocator<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void> > > >)>,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_>::has_fallback_type_>(int internal_which, boost::detail::variant::invoke_visitor<libtorrent::aux::`anonymous namespace'::caller_visitor const ,0> & visitor, void * storage, std::function<void __cdecl(enum libtorrent::status_t,libtorrent::storage_error const &)> * t, boost::variant<std::function<void __cdecl(libtorrent::disk_buffer_holder,libtorrent::storage_error const &)>,std::function<void __cdecl(libtorrent::storage_error const &)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>,libtorrent::digest32<160> const &,libtorrent::storage_error const &)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>,libtorrent::digest32<256> const &,libtorrent::storage_error const &)>,std::function<void __cdecl(enum libtorrent::status_t,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,libtorrent::storage_error const &)>,std::function<void __cdecl(void)>,std::function<void __cdecl(enum libtorrent::status_t,libtorrent::storage_error const &)>,std::function<void __cdecl(std::basic_string<char,std::char_traits<char>,std::allocator<char> >,libtorrent::aux::strong_typedef<int,libtorrent::aux::file_index_tag,void>,libtorrent::storage_error const &)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>)>,std::function<void __cdecl(libtorrent::storage_error const &,libtorrent::aux::container_wrapper<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void>,libtorrent::aux::strong_typedef<int,libtorrent::aux::file_index_tag,void>,std::vector<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void>,std::allocator<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void> > > >)>,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_>::has_fallback_type_ __formal, int __formal) Zeile 158	C++
 	MooPolice.exe!??@8fd52353ce5b4538cc1012ec258b7231@(const int internal_which, const int logical_which, boost::detail::variant::invoke_visitor<libtorrent::aux::`anonymous namespace'::caller_visitor const ,0> & visitor, void * storage, boost::mpl::bool_<0> __formal, boost::variant<std::function<void __cdecl(libtorrent::disk_buffer_holder,libtorrent::storage_error const &)>,std::function<void __cdecl(libtorrent::storage_error const &)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>,libtorrent::digest32<160> const &,libtorrent::storage_error const &)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>,libtorrent::digest32<256> const &,libtorrent::storage_error const &)>,std::function<void __cdecl(enum libtorrent::status_t,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,libtorrent::storage_error const &)>,std::function<void __cdecl(void)>,std::function<void __cdecl(enum libtorrent::status_t,libtorrent::storage_error const &)>,std::function<void __cdecl(std::basic_string<char,std::char_traits<char>,std::allocator<char> >,libtorrent::aux::strong_typedef<int,libtorrent::aux::file_index_tag,void>,libtorrent::storage_error const &)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>)>,std::function<void __cdecl(libtorrent::storage_error const &,libtorrent::aux::container_wrapper<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void>,libtorrent::aux::strong_typedef<int,libtorrent::aux::file_index_tag,void>,std::vector<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void>,std::allocator<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void> > > >)>,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_>::has_fallback_type_ no_backup_flag, boost::mpl::int_<0> * __formal, boost::detail::variant::visitation_impl_step<boost::mpl::l_iter<boost::mpl::l_item<boost::mpl::long_<10>,std::function<void __cdecl(libtorrent::disk_buffer_holder,libtorrent::storage_error const &)>,boost::mpl::l_item<boost::mpl::long_<9>,std::function<void __cdecl(libtorrent::storage_error const &)>,boost::mpl::l_item<boost::mpl::long_<8>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>,libtorrent::digest32<160> const &,libtorrent::storage_error const &)>,boost::mpl::l_item<boost::mpl::long_<7>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>,libtorrent::digest32<256> const &,libtorrent::storage_error const &)>,boost::mpl::l_item<boost::mpl::long_<6>,std::function<void __cdecl(enum libtorrent::status_t,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,libtorrent::storage_error const &)>,boost::mpl::l_item<boost::mpl::long_<5>,std::function<void __cdecl(void)>,boost::mpl::l_item<boost::mpl::long_<4>,std::function<void __cdecl(enum libtorrent::status_t,libtorrent::storage_error const &)>,boost::mpl::l_item<boost::mpl::long_<3>,std::function<void __cdecl(std::basic_string<char,std::char_traits<char>,std::allocator<char> >,libtorrent::aux::strong_typedef<int,libtorrent::aux::file_index_tag,void>,libtorrent::storage_error const &)>,boost::mpl::l_item<boost::mpl::long_<2>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>)>,boost::mpl::l_item<boost::mpl::long_<1>,std::function<void __cdecl(libtorrent::storage_error const &,libtorrent::aux::container_wrapper<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void>,libtorrent::aux::strong_typedef<int,libtorrent::aux::file_index_tag,void>,std::vector<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void>,std::allocator<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void> > > >)>,boost::mpl::l_end> > > > > > > > > > >,boost::mpl::l_iter<boost::mpl::l_end> > * __formal) Zeile 238	C++
 	MooPolice.exe!boost::variant<std::function<void __cdecl(libtorrent::disk_buffer_holder,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>,libtorrent::digest32<160> const & __ptr64,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>,libtorrent::digest32<256> const & __ptr64,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(enum libtorrent::status_t,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(void)>,std::function<void __cdecl(enum libtorrent::status_t,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(std::basic_string<char,std::char_traits<char>,std::allocator<char> >,libtorrent::aux::strong_typedef<int,libtorrent::aux::file_index_tag,void>,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>)>,std::function<void __cdecl(libtorrent::storage_error const & __ptr64,libtorrent::aux::container_wrapper<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void>,libtorrent::aux::strong_typedef<int,libtorrent::aux::file_index_tag,void>,std::vector<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void>,std::allocator<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void> > > >)>,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_>::internal_apply_visitor_impl<boost::detail::variant::invoke_visitor<libtorrent::aux::`anonymous namespace'::caller_visitor const ,0>,void * __ptr64>(int internal_which, int logical_which, boost::detail::variant::invoke_visitor<libtorrent::aux::`anonymous namespace'::caller_visitor const ,0> & visitor, void * storage) Zeile 2458	C++
 	MooPolice.exe!boost::variant<std::function<void __cdecl(libtorrent::disk_buffer_holder,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>,libtorrent::digest32<160> const & __ptr64,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>,libtorrent::digest32<256> const & __ptr64,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(enum libtorrent::status_t,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(void)>,std::function<void __cdecl(enum libtorrent::status_t,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(std::basic_string<char,std::char_traits<char>,std::allocator<char> >,libtorrent::aux::strong_typedef<int,libtorrent::aux::file_index_tag,void>,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>)>,std::function<void __cdecl(libtorrent::storage_error const & __ptr64,libtorrent::aux::container_wrapper<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void>,libtorrent::aux::strong_typedef<int,libtorrent::aux::file_index_tag,void>,std::vector<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void>,std::allocator<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void> > > >)>,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_>::internal_apply_visitor<boost::detail::variant::invoke_visitor<libtorrent::aux::`anonymous namespace'::caller_visitor const ,0> >(boost::detail::variant::invoke_visitor<libtorrent::aux::`anonymous namespace'::caller_visitor const ,0> & visitor) Zeile 2469	C++
 	MooPolice.exe!boost::variant<std::function<void __cdecl(libtorrent::disk_buffer_holder,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>,libtorrent::digest32<160> const & __ptr64,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>,libtorrent::digest32<256> const & __ptr64,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(enum libtorrent::status_t,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(void)>,std::function<void __cdecl(enum libtorrent::status_t,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(std::basic_string<char,std::char_traits<char>,std::allocator<char> >,libtorrent::aux::strong_typedef<int,libtorrent::aux::file_index_tag,void>,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>)>,std::function<void __cdecl(libtorrent::storage_error const & __ptr64,libtorrent::aux::container_wrapper<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void>,libtorrent::aux::strong_typedef<int,libtorrent::aux::file_index_tag,void>,std::vector<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void>,std::allocator<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void> > > >)>,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_>::apply_visitor<libtorrent::aux::`anonymous namespace'::caller_visitor const >(const libtorrent::aux::`anonymous-namespace'::caller_visitor & visitor) Zeile 2519	C++
 	MooPolice.exe!boost::apply_visitor<libtorrent::aux::`anonymous namespace'::caller_visitor,boost::variant<std::function<void __cdecl(libtorrent::disk_buffer_holder,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>,libtorrent::digest32<160> const & __ptr64,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>,libtorrent::digest32<256> const & __ptr64,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(enum libtorrent::status_t,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(void)>,std::function<void __cdecl(enum libtorrent::status_t,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(std::basic_string<char,std::char_traits<char>,std::allocator<char> >,libtorrent::aux::strong_typedef<int,libtorrent::aux::file_index_tag,void>,libtorrent::storage_error const & __ptr64)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>)>,std::function<void __cdecl(libtorrent::storage_error const & __ptr64,libtorrent::aux::container_wrapper<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void>,libtorrent::aux::strong_typedef<int,libtorrent::aux::file_index_tag,void>,std::vector<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void>,std::allocator<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void> > > >)>,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_> & __ptr64>(const libtorrent::aux::`anonymous-namespace'::caller_visitor & visitor, boost::variant<std::function<void __cdecl(libtorrent::disk_buffer_holder,libtorrent::storage_error const &)>,std::function<void __cdecl(libtorrent::storage_error const &)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>,libtorrent::digest32<160> const &,libtorrent::storage_error const &)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>,libtorrent::digest32<256> const &,libtorrent::storage_error const &)>,std::function<void __cdecl(enum libtorrent::status_t,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,libtorrent::storage_error const &)>,std::function<void __cdecl(void)>,std::function<void __cdecl(enum libtorrent::status_t,libtorrent::storage_error const &)>,std::function<void __cdecl(std::basic_string<char,std::char_traits<char>,std::allocator<char> >,libtorrent::aux::strong_typedef<int,libtorrent::aux::file_index_tag,void>,libtorrent::storage_error const &)>,std::function<void __cdecl(libtorrent::aux::strong_typedef<int,libtorrent::aux::piece_index_tag,void>)>,std::function<void __cdecl(libtorrent::storage_error const &,libtorrent::aux::container_wrapper<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void>,libtorrent::aux::strong_typedef<int,libtorrent::aux::file_index_tag,void>,std::vector<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void>,std::allocator<libtorrent::aux::strong_typedef<unsigned char,libtorrent::download_priority_tag,void> > > >)>,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_,boost::detail::variant::void_> & visitable) Zeile 98	C++
 	MooPolice.exe!libtorrent::aux::disk_io_job::call_callback() Zeile 133	C++
 	MooPolice.exe!libtorrent::mmap_disk_io::call_job_handlers() Zeile 1635	C++
 	MooPolice.exe!libtorrent::mmap_disk_io::add_completed_jobs_impl::__l58::<lambda>() Zeile 1602	C++
 	MooPolice.exe!boost::asio::asio_handler_invoke<void <lambda>(void) >(libtorrent::mmap_disk_io::add_completed_jobs_impl::__l58::void <lambda>(void) & function, ...) Zeile 70	C++
 	MooPolice.exe!boost_asio_handler_invoke_helpers::invoke<void <lambda>(void),void <lambda>(void) >(libtorrent::mmap_disk_io::add_completed_jobs_impl::__l58::void <lambda>(void) & function, libtorrent::mmap_disk_io::add_completed_jobs_impl::__l58::void <lambda>(void) & context) Zeile 39	C++
 	MooPolice.exe!boost::asio::system_executor::dispatch<void <lambda>(void),std::allocator<void> >(libtorrent::mmap_disk_io::add_completed_jobs_impl::__l58::void <lambda>(void) && f, const std::allocator<void> & __formal) Zeile 40	C++
 	MooPolice.exe!boost::asio::detail::work_dispatcher<void <lambda>(void) >::operator()() Zeile 60	C++
 	MooPolice.exe!boost::asio::asio_handler_invoke<boost::asio::detail::work_dispatcher<void <lambda>(void) > >(boost::asio::detail::work_dispatcher<void <lambda>(void) > & function, ...) Zeile 70	C++
 	MooPolice.exe!boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::work_dispatcher<void <lambda>(void) >,boost::asio::detail::work_dispatcher<void <lambda>(void) > >(boost::asio::detail::work_dispatcher<void <lambda>(void) > & function, boost::asio::detail::work_dispatcher<void <lambda>(void) > & context) Zeile 39	C++
 	MooPolice.exe!boost::asio::detail::executor_op<boost::asio::detail::work_dispatcher<void <lambda>(void) >,std::allocator<void>,boost::asio::detail::win_iocp_operation>::do_complete(void * owner, boost::asio::detail::win_iocp_operation * base, const boost::system::error_code & __formal, unsigned __int64 __formal) Zeile 70	C++
 	MooPolice.exe!boost::asio::detail::win_iocp_operation::complete(void * owner, const boost::system::error_code & ec, unsigned __int64 bytes_transferred) Zeile 48	C++
 	MooPolice.exe!boost::asio::detail::win_iocp_io_context::do_one(unsigned long msec, boost::system::error_code & ec) Zeile 421	C++
 	MooPolice.exe!boost::asio::detail::win_iocp_io_context::run(boost::system::error_code & ec) Zeile 163	C++
 	MooPolice.exe!boost::asio::io_context::run() Zeile 62	C++
 	MooPolice.exe!libtorrent::session::start::__l64::<lambda>() Zeile 342	C++
 	[Externer Code]	
 	MooPolice.exe!invoke_thread_procedure(unsigned int(*)(void *) procedure, void * const context) Zeile 92	C++
 	MooPolice.exe!thread_start<unsigned int (__cdecl*)(void * __ptr64)>(void * const parameter) Zeile 115	C++
 	[Externer Code]	


I just used this tracker url: https://tracker.lelux.fi:443/announce
ssl = true , m_ssl_ctx = nullptr

Is it because no certifacte is given (somehow)?

**Comment by MassaRoddel** [comment]
Is it because i did not define TORRENT_SSL_PEERS? So I do not have this code enabled?

> #ifdef TORRENT_SSL_PEERS
		// if this torrent contains an SSL certificate, make sure
		// any SSL tracker presents a certificate signed by it
		req.ssl_ctx = m_ssl_ctx.get();
#endif

**Comment by arvidn** [comment]
I'm pretty sure this was the problem: https://github.com/arvidn/libtorrent/pull/4706
would you mind testing it?

**Comment by MassaRoddel** [comment]
That seems to fix it.
