### ISSUE TITLE
Pieces priority isn't restored by 1.0.x

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#47]
I have tested with the latest from RC_1_0 (c0b5792792b4740320695b4c365305549977dd11)

Piece priority isn't restored. I am not sure if it is even saved correctly to the fastresume file.

However, this doesn't happen with latest from RC_0_16

**Comment by ngosang** [comment]
In 1.0.5 is saved correctly but not loaded the next time.

**Comment by arvidn** [comment]
could you please test this patch? https://github.com/arvidn/libtorrent/pull/51

**Comment by arvidn** [comment]
In fact, I feel pretty confident with this one, since I added a unit test as well. I'll merge it to RC_1_0 and master.

**Comment by sledgehammer999** [comment]
I confirm that it works now.

Btw, when are you going to release 1.0.6? I want to bump my building requirements of qbittorrent. I want to depend on at least 1.0.6. Plus, the site links need to be live.

**Comment by arvidn** [comment]
I want to land https://github.com/arvidn/libtorrent/pull/50 first, and I think that's it. unless something else pops up. but I'm hoping to pull the trigger this weekend.
