### ISSUE TITLE
Inconsistent tags

### ISSUE THREAD

**Issue by egorpugin** [arvidn/libtorrent#4700]
Was `libtorrent-{M}_{m}_{p}`.
Now we have `libtorrent_{M}_{m}_{p}`.

This breaks scripts.

**Comment by egorpugin** [comment]
Maybe you could switch to just `1.2.7` or `v1.2.7`.

**Comment by egorpugin** [comment]
Funny, 2.0.0 has now `libtorrent={M}_{m}_{p}`.

**Comment by arvidn** [comment]
Doh. Yes, clearly 2.0 was meant to use -2_0_0

I agree that the tag names should use . Using underscore is a holdover from the subversion days. But, do I change tags retroactively?

**Comment by egorpugin** [comment]
Is it possible to add another tag to single commit to fixes the issue?
I think it is better to keep tags for 1.x.x as is (`libtorrent-{M}_{m}_{p}`) and use new scheme for 2.x.x (https://semver.org/) - `2.0.0` or `v2.0.0`

**Comment by egorpugin** [comment]
Like a joke.

![image](https://user-images.githubusercontent.com/4325333/92333427-19f91d00-f08e-11ea-945a-d2f4349f3e88.png)

**Comment by egorpugin** [comment]
Is it possible to use semver with 3 numbers? https://semver.org/
So tags will be `2.0.0` or `v2.0.0`.

**Comment by arvidn** [comment]
sure. can you remind me why this matters again?

**Comment by egorpugin** [comment]
Automation of delivery of new library versions (scripts, build scripts, package managers).

**Comment by arvidn** [comment]
I've added tags `v1.2.10` and `v2.0.0`

**Comment by egorpugin** [comment]
Thank you!
Please keep going in such way.
