### ISSUE TITLE
v1+v2 interoperability test torrents

### ISSUE THREAD

**Issue by parg** [arvidn/libtorrent#4715]
Hi,

Any chance of you adding a few test torrents supporting both v1+v2 as outlined in BEP 52? You appear to only have v2 ones available.

cheers
Parg

**Comment by arvidn** [comment]
good point. I've put up two test torrents, one v2-only and one hybrid:

https://libtorrent.org/bittorrent-v2-test.torrent
https://libtorrent.org/bittorrent-v2-hybrid-test.torrent

I should mention these in the documentation some where too

**Comment by parg** [comment]
Nice, looks like it's working :)
