### ISSUE TITLE
Large buffer in save_resume_data_alert for v2 torrents

### ISSUE THREAD

**Issue by vktr** [arvidn/libtorrent#4720]
**Please provide the following information**

libtorrent version (or branch): master

platform/architecture: win64

compiler and compiler version: msvc

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

PicoTorrent tracks the master branch, and I just got around to verifying v2 torrents. Using the test torrent here (https://libtorrent.org/bittorrent-v2-test.torrent).

When I recieve the `save_resume_data_alert` for that torrent, the buffer is ~8MB, which is a large increase from v1 torrents. I haven't checked the code, but is this expected?

I generate the alert with

```
handle.save_resume_data(
                lt::torrent_handle::flush_disk_cache
                | lt::torrent_handle::save_info_dict);
```

**Comment by vktr** [comment]
Clarification - the buffer I recieve from `lt::write_resume_data` is big for v2 torrents.

**Comment by arvidn** [comment]
I suspect this is the `trees` field, which contains the full merkle tree for each file. Could you confirm this?, `dump_bencode` should do it.

I should probably optimize that format a bit, similarly to what I did for the in-memory representation.

**Comment by vktr** [comment]
Can confirm, the `trees` field contains a lot of entries, most of them empty (or null) (`\x00`).

**Comment by arvidn** [comment]
Here are some ideas of how this could be addressed:

If there is a full tree, just store the leaf nodes (this cuts the size in half).
If the tree is full down to the piece-layer, only store the piece layer.

For the partial tree case, one of these could help:

1. Use a simple RLE compression of the tree in the resume data.
2. use a bitmask to indicate which hashes are "set" (i.e. non-zero) and just store those.
3. store the only the "frontier" nodes. i.e. the ones closest to the leaf layer in each  sub-tree. This is a bit complicated to extract and to reconstruct.

I think right now, the simplest approach is the most feasible. It can always be improved down the line.

Thoughts?

**Comment by vktr** [comment]
I can't say I fully understand the merkle trees - I'll have to do a bit of reading on that. That said, I am in favor of simple solutions :) I'm also leaning towards the second suggestion on using a bitmask, mostly to avoid processing to stored data which I guess would make it easier to debug by eye.

**Comment by arvidn** [comment]
@vktr would you mind testing that PR to see if it improves things sufficiently for you?

**Comment by vktr** [comment]
@arvidn I'm out of office for a few days more, sorry :) I see you merged it already so I'll try it out as soon as I get back.

**Comment by arvidn** [comment]
I consider this fixed by #4788

**Comment by vktr** [comment]
Hey @arvidn, sorry I'm on vacation so haven't had the time to do anything at all w/ regards to this. You made the right call

**Comment by vktr** [comment]
@arvidn Sorry for the late feedback - just checked and the resume data is now in the 4MB range for the same torrent.
