### ISSUE TITLE
Potential bug in sanitize_append_path_element

### ISSUE THREAD

**Issue by tsangwpx** [arvidn/libtorrent#4729]
**Please provide the following information**

libtorrent version (or branch): libtorrent_1_1_11

platform/architecture: Linux

compiler and compiler version: Unknown

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I use qBittorrent on debian buster. Something odd is encountered. I think there is a bug in `sanitize_append_path_element` in the following loop.

https://github.com/arvidn/libtorrent/blob/8e710151c80e655ee0513ca37c367f75a448c6bd/src/torrent_info.cpp#L247-L305

In the line 303, `i = dot - 1` caused `i` point to one `char` behind.

but the increment of the `for`-loop is `i += seq_len`

If `seq_len` equals `1`, `i` will point to the dot `char`.
If not, the dot and the leading part of the filename extension are likely stripped.

Since C++ is hard , I am not sure whether this is a bug or not. 😅
If yes, adding `seq_len = 1` after  `i = dot - 1` should fix the issue. 

For example, in Python,
```python
str237long = 's' * 237
input_name = str237long + '一' + '.jpg'  # len = 237 + 3 + 4 = 244
output_actual = str237long + '一' + 'pg' # the extension is broken.
output_expected = str237long + '一' + '.jpg' # expected result
```

**Comment by arvidn** [comment]
> If yes, adding seq_len = 1 after i = dot - 1 should fix the issue.

what's the issue?

**Comment by tsangwpx** [comment]
For example,
```python
str237long = b's' * 237
char_3_bytes = '一'.encode('utf-8')
input_name = str237long + char_3_bytes + b'.jpg'
print(type(input_name), len(input_name))  # <class 'bytes'> 244
```
When `i=237`, there is a 3-byte character with `seq_len = 3`.
We have `added=240` in the line 278.
The file extension picking code would be executed in the line 288.
The dot is found at `dot=240` in the line 296.
So `i = dot - 1 = 239` in the line 303.

Here is the problem:
`i += std::size_t(seq_len)` in the line 248.
Hence, `i=239 + 3 = 242`.

So the substring `b'.j'` of `input_name` is skipped.
The actual output and the expected output are
```python
output_actual = str237long + char_3_bytes  + b'pg' # the extension is broken.
output_expected = str237long + char_3_bytes + b'.jpg' # expected result
```

**Comment by arvidn** [comment]
are you saying the issue is that the truncation disregards UTF-8 character boundaries?

**Comment by arvidn** [comment]
could you give this patch a try? https://github.com/arvidn/libtorrent/pull/4737

**Comment by tsangwpx** [comment]
The patch look good though I dont have build environment on hand.

**Comment by arvidn** [comment]
thanks for the report!
