### ISSUE TITLE
create_torrent creates invalid hybrid torrents by "default"

### ISSUE THREAD

**Issue by arvidn** [arvidn/libtorrent#4735]
libtorrent version (or branch): 2.0

the 2.0 create_torrent class is API compatible with the 1.2 version. If it's used the same but compiled against libtorrent 2.0, the resulting torrent will be a hybrid torrent with invalid v2 file root hashes.

The way this class is used is to construct it (and specify `v1_only` or `v2_only`, default is hybrid).

Then set hashes and set v2 hashes. If v2 hashes are not set (which wasn't an option in 1.2) the torrent is still created as a hybrid torrent, which is invalid.

The solutions I can think of are:

1. Change the default to be `v1_only` and instead have a flag for `v1_2_hybrid` (or some better name). This preserves the semantics of the 1.2 version of the class.

2. If the create_torrent object is configured as a hybrid, but only v1 hashes are set on it, silently fall back on just creating a v1 torrent.

Regardless of those options, there are more questions that should be answered.

If one is configuring the create_torrent object as `v1_only` but without setting any v1-hashes, what should `generate()` do?
Similarly, if you configure it as `v2_only` but don't set any v2-hashes. Or configure it as v1 and only set v2 hashes.

Perhaps it's unnecessary to specify up-front what version torrent to create, maybe it should just be based on which kinds of hashes are set. As far as I can tell, the main effect of this configuration right now is to pre-allocate some data structures.

When creating v2 torrents, there are some new restrictions on what file trees are possible. You can not have a directory with the same name as a file for instance (that is possible to represent in v1 torrents, but most likely not on most filesystems). If such file structure is passed in to `create_torrent` the call to `generate()` will throw. So there is some precedence of throwing.

Part of me thinks it's better to throw than to silently do something the user did not intend.

I'm leaning towards these changes:

1. scrap v1 and v2 flags in constructor
2. allocate internal data structures on-demand (instead of pre-allocate them)
3. `generate()` generates a v1 torrent if only v1 hashes were set, a v2 torrent if only v2 hashes were set, a hybrid torrent if both were set and throws an exception if none were set.

@ssiloti Do you have any throughts?

**Comment by arvidn** [comment]
I may have over-simplified a bit. the constructor does a few other things based on the `v1_only` and `v2_only` flags. It might make sense to keep the flags, just not keep the *state* and still base the generated torrent on what was actually set.

e.g. for a v2 and hybrid torrent, the file structure is canonicalized. and the piece size restriction (power of two) is enforced.

**Comment by ssiloti** [comment]
I'd prefer to keep the default to create a hybrid torrent so that v2 oblivious applications which use `set_piece_hashes` produce a hybrid torrent. Silently falling back to v1 only if v2 hashes are not provided is probably the best option. Throwing a runtime error on previously working code is pretty rude.

**Comment by arvidn** [comment]
yes, I agree. `set_piece_hashes()` should produce a hybrid torrent. In my patch I'm keeping the flags and the state (primarily so that `set_piece_hashes()` can query them). Since the default is neither `v1_only` nor `v2_only`, I think it makes sense to generate based on which hashes were set. However, if one explicitly sets `v1_only` and provide v2-hashes, or vice versa, I will throw in `generate()`.

**Comment by arvidn** [comment]
this is what I came up with. @ssiloti would you mind reviewing it?
https://github.com/arvidn/libtorrent/pull/4736
