### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#4775]
Trying to compile under Linux Ubuntu 20.04. What's the problem?

> building boost from source directory:  /mnt/c/Users/Oleg/Documents/frostwire-jlibtorrent1/swig/src/../boost_1_73_0
> Performing configuration checks
> 
>     - default address-model    : none
>     - default architecture     : none
> ...patience...
> ...patience...
> ...patience...
> ...found 5407 targets...
> ...updating 166 targets...
> clang-linux.compile.c++.without-pch bin/release/android/arm64-v8a/libtorrent_jni.o
> error: unknown target CPU 'armv8-a+crc'
> note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, icelake-server, tigerlake, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, x86-64
> 
>   "clang++" -c -x c++ -fno-rtti -fPIC -march=armv8-a+crc -std=c++14 -DANDROID -fno-strict-aliasing -fvisibility=hidden -g -gdwarf-4 -fdebug-macro -ggdb -fPIC -O0 -Wall -Wno-inline -Os -DBOOST_ALL_NO_LIB -DBOOST_ASIO_ENABLE_CANCELIO -DBOOST_ASIO_HAS_STD_CHRONO -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DBOOST_NO_IOSTREAM -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_SYSTEM_STATIC_LINK=1 -DNDEBUG -DOPENSSL_NO_SSL2 -DTORRENT_NO_DEPRECATE -DTORRENT_USE_I2P=1 -DTORRENT_USE_LIBCRYPTO -DTORRENT_USE_OPENSSL -D_FILE_OFFSET_BITS=64 -D_WIN32_WINNT=0x0600 -I"." -I"/mnt/c/Users/Oleg/Documents/frostwire-jlibtorrent1/swig/boost_1_73_0" -I"/mnt/c/Users/Oleg/Documents/frostwire-jlibtorrent1/swig/src/libtorrent/include" -I"/mnt/c/Users/Oleg/Documents/frostwire-jlibtorrent1/swig/src/libtorrent/include/libtorrent" -I"/mnt/c/Users/Oleg/Documents/frostwire-jlibtorrent1/swig/src/openssl/include" -I"/usr/local/include" -I"/usr/sfw/include" -o "bin/release/android/arm64-v8a/libtorrent_jni.o" "libtorrent_jni.cpp"
> 
> ...failed clang-linux.compile.c++.without-pch bin/release/android/arm64-v8a/libtorrent_jni.o...
> clang-linux.compile.c++.without-pch bin/release/android/arm64-v8a/src/alert_manager.o
> error: unknown target CPU 'armv8-a+crc'
> note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, icelake-server, tigerlake, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, x86-64

**Comment by arvidn** [comment]
what's the command line you run? it looks like it involves `armv8-a+crc` as an invalid argument. try to remove that one

**Comment by arvidn** [comment]
this is not really on topic for libtorrent though

**Comment by master255** [comment]
@arvidn I'm trying to compile libtorrent. The manual is out of date: https://www.libtorrent.org/building.html.
There are scripts and instructions from other programmers (https://github.com/frostwire/frostwire-jlibtorrent), third-party developers who are trying to help you.
There is an error in the scripts somewhere.
I checked on Ubuntu 18, 20. This error is repeated on these systems.
I have installed it on a clean system:
cmake, clang, gradle, javadoc, g++, boost 1.73.0. What else should I install?
Usually normal programmers specify a list of necessary components but there is nothing here.

My goal is just to compile libtorrent or check the code for errors. Maybe there are other ways?

**Comment by arvidn** [comment]
> The manual is out of date: https://www.libtorrent.org/building.html.

Could you be more specific?

> There are scripts and instructions from other programmers (https://github.com/frostwire/frostwire-jlibtorrent), third-party developers who are trying to help you.
> There is an error in the scripts somewhere.

Which script?

> I checked on Ubuntu 18, 20. This error is repeated on these systems.
> I have installed it on a clean system:
> cmake, clang, gradle, javadoc, g++, boost 1.73.0, openjdk-11-jdk. What else should I install?

You just need boost (which comes with boost-build), and you run `b2` in the libtorrent root. I'm pretty sure that's what the build document says too.

> Usually normal programmers specify a list of necessary components but there is nothing here.

I don't understand how you can miss it. There are even instructions on how to download and install boost. Are we looking at the same document?

https://libtorrent.org/building.html

> My goal is just to compile libtorrent or check the code for errors. Maybe there are other ways?

Well, nobody knows (yet) what way you are using. What command line are you running that fails?

But, since it fails, yes, there are clearly ways that don't fail. If you don't want to follow the instructions in the build documentation, you can also look at the `.travis.yml` or `appveyor.yml` files for demonstration of how to build.

**Comment by master255** [comment]
@arvidn 

> Could you be more specific?

in instruction:
c:\boost_1_69_0. You'll need at least version 1.58
in commit and https://github.com/frostwire/frostwire-jlibtorrent:
boost_1_73_0
I think it's an important library. What version is required for compilation? Maybe you need to decide which version to choose?

in instruction:

> Step 3: Building libtorrent

Where is the command that compiles the library? There is a lot of text and even some options for compilation, but where is the most important thing - the command?

For the compilation, I have done a lot of actions that are not described in the instructions.
I installed: cmake, clang, gradle, javadoc, g++, boost 1.73.0, openjdk-11-jdk.
Where is the full list of components that I need?
Because of this, I now have the error described above and do not know how to solve it.

> it looks like it involves armv8-a+crc as an invalid argument. try to remove that one

Are you joking? It's the name of the architecture I'm compiling. It can' t be deleted.

**Comment by arvidn** [comment]
>     Could you be more specific?
> 
> in instruction:
> c:\boost_1_69_0. You'll need at least version 1.58

 You imply that the current stable release of libtorrent (1.2.7) does not build with boost-1.58. Can you confirm that?

> in commit and https://github.com/frostwire/frostwire-jlibtorrent:
> boost_1_73_0
> I think it's an important library. What version is required for compilation? Maybe you need to decide which version to choose?

I don't think I know what you mean. I don't think it's feasible (nor necessary) to pick a single version of boost and *only* support that.

You ask for me to pick a version, and you reference my documentation saying you need at least 1.58. What else are you asking for?

> in instruction:
> 
>     Step 3: Building libtorrent
> 
> Where is the command that compiles the library? There is a lot of text and even some options for compilation, but where is the most important thing - the command?

In the grey boxes. They start with `b2`.

> For the compilation, I have done a lot of actions that are not described in the instructions.
> I installed: cmake, clang, gradle, javadoc, g++, boost 1.73.0, openjdk-11-jdk.
> Where is the full list of components that I need?
> Because of this, I now have the error described above and do not know how to solve it.

You can use cmake to build if you prefer, but from that list, you only need g++ (or any other C++ compiler, obviously) and boost.
Clearly it wouldn't make sense to include those steps that you took in the documentation, since they are not necessary.

> >    it looks like it involves armv8-a+crc as an invalid argument. try to remove that one
> 
> Are you joking? It's the name of the architecture I'm compiling. It can' t be deleted.

As I'm sure you understand, running an invalid command will keep failing, no matter how many times you try. You obviously have to apply your engineering skills and learn *where* and *how* to specify your target architecture. The way you're doing it now is clearly wrong, as the error message tell you. So, I would argue, it *has* to be deleted from its current place on the command line.

The command line, btw, is it secret?

If you search the internet, you may find descriptions of how to configure a boost-build toolset for cross compilation, like [here](https://blog.libtorrent.org/2017/02/building-libtorrent-for-c-h-i-p/) for instance. If you use cmake you have to learn more about cmake.

**Comment by master255** [comment]
@arvidn Okay. I think I found the command I need: b2 gcc. But you're gonna fix the documentation. Emphasize on the command and that it compiles the library. And other bugs with versions.

**Comment by master255** [comment]
@arvidn And it's too bad that I need to know all this stuff in order to use your library. That means that the library is bad.
It's a general opinion, not just of me about any library.
I respect your work, but you need to make really good software and often it's not as perfect as you see it.

**Comment by arvidn** [comment]
teaching people C++ and build systems for C++ is out of scope for libtorrent

**Comment by FranciscoPombal** [comment]
@master255 learn how to use CMake. The documentation is quite clear on how to build with CMake: https://libtorrent.org/building.html. Worked example: https://github.com/arvidn/libtorrent/pull/4748#issuecomment-643821453

**Comment by master255** [comment]
@arvidn And use Windows for Linux (WSL). Why are all your sh files in windows encoding?!

@FranciscoPombal We're talking about compiling for Android. Do you read what it says here?

**Comment by master255** [comment]
My problem is that boost should use clang from android toolchan. Not from the system. Now I don't know how to do it...

**Comment by arvidn** [comment]
That does indeed seem to be your problem.

**Comment by master255** [comment]
@arvidn I have long understood that you can only talk nonsense and never help, even if it is about your library.

**Comment by arvidn** [comment]
cmake and boost-build are not my projects, I don't understand why you're asking me for help with them.
A few posts ago I sent you a link that describes in detail how to do what you want with boost-build. Finding this information for cmake should be easy, as it's quite popular.

**Comment by master255** [comment]
@arvidn I found the bug. Bug was in path to android toolchain. Everything compiles perfectly on my computer now, without Travis. Thank you for not helping.

**Comment by arvidn** [comment]
> Thank you for not helping.

@master255 thank *you* for not helping :)
