### ISSUE TITLE
Golang binding

### ISSUE THREAD

**Issue by ipsq** [arvidn/libtorrent#478]
I would love a Golang binding for this. 

Would something like [SWIG](http://www.swig.org/Doc3.0/Go.html) be suited for this?

**Comment by arvidn** [comment]
I had a lot of issues last time I tried to make SWIG bindings for libtorrent, mostly around parsing C++ headers. But that was almost 10 years ago. I'm sure things are better now.

**Comment by aldenml** [comment]
@ipsq Maybe you want to take a look at https://github.com/frostwire/frostwire-jlibtorrent/blob/master/swig/libtorrent.i

It works for java and javascript, never explored Go, but I think it could be a good starting point.

**Comment by ipsq** [comment]
@aldenml Wow, cool stuff! Will try and post back.

**Comment by dimitriss** [comment]
Check this: https://github.com/steeve/libtorrent-go
