### ISSUE TITLE
question:  apply high-performance-seeding tuning to compiled library.

### ISSUE THREAD

**Issue by userdocs** [arvidn/libtorrent#4784]
Sorry, this is not really an issue but a question.

Can i apply the settings pack to a compiled build when i build it?

I was reading [here](https://libtorrent.org/tuning.html#high-performance-seeding) but i am not sure how i would do this?

The main question would be, how do i create and apply a settings pack to be used at build time?

The solution is just not obvious to me.

**Comment by arvidn** [comment]
you don't apply settings pack to "builds", you apply them to `session` objects. You can only do that at runtime, ideally by passing it into the `session` constructor.

**Comment by userdocs** [comment]
So it is the client, like qbittorrent that would apply this setting? I just wanted to check in case i was missing something i could specify at build time to hardcode the session defaults.

**Comment by arvidn** [comment]
correct
