### ISSUE TITLE
Document load_torrent_limits

### ISSUE THREAD

**Issue by FranciscoPombal** [arvidn/libtorrent#4785]
**Please provide the following information**

**libtorrent version (or branch)**

\>= 1.2.2

**platform/architecture**

N/A

**compiler and compiler version**

N/A

**please describe what symptom you see, what you would expect to see instead and
how to reproduce it.**

These configuration parameters haven't been documented since they were introduced. They should be documented.

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/4787
