### ISSUE TITLE
How to call emplace_alert

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#4794]
@arvidn , How do I call emplace_alert from storage.cpp?
I need to send log_alert for debugging.

alerts() not working

**Comment by master255** [comment]
@arvidn ?

**Comment by arvidn** [comment]
`emplace_alert` is a member function on `alert_manager`, so you need a reference to that object, and then you call it.

**Comment by master255** [comment]
@arvidn I know about this. Where do I get the alert_manager? Can I get it by some command or should I pass it in the constructor?

**Comment by arvidn** [comment]
the latter

**Comment by master255** [comment]
@arvidn Today I won file splitting and working with large files without sparse_mode.
For debugging in Android, I used this code:
`
file_handle new_file = std::make_shared<file>();
std::string full_path = m_save_path + "/debug...";
error_code ee;
new_file->open(full_path, open_mode::read_write, ee);
`
And yes. I want you to add that code to your instructions.
I know the code is very dirty, but I haven't found any other way to get logs in Android.

**Comment by arvidn** [comment]
could you file a pull request against the documentation, to make it clear?

**Comment by master255** [comment]
@arvidn No Arvidn. You haven't helped me, so I won't make any pull requests.

**Comment by arvidn** [comment]
you asked me to add something to the documentation. It's not clear what exactly you want me to add. The best way to make it crystal clear what it is, is to make a a pull request.

You seem mostly to be trolling though.

**Comment by master255** [comment]
@arvidn If I ask you to buy bread in the store, will you also ask me to go to the store myself and show you how it is done?
Maybe it is you trolling me?
