### ISSUE TITLE
Add the ability to add hashes.

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#4797]
@arvidn , My player parses the torrent file by itself and manages its content.
In this case, the playlist consists of torrent files, but which have hashes, only for this particular file (This is my technology for making playlists from torrent files and saving playlists to disk.).
To speed up the download, so that the library does not have to download the torrent file again, it would be good to add the hashes function.
Now it is possible to add trackers, in the future it is necessary to add hashes. If there is no hash for the downloaded file, then download the torrent file.

**Comment by master255** [comment]
@arvidn ?

**Comment by arvidn** [comment]
I don't know what you mean. you want to add a hash of what to what?

**Comment by master255** [comment]
@arvidn I need to add file hashes to AddTorrentParams. And not all files, but only those I want to download. But if when downloading Libtorrent finds out that there is no hash, let it download the torrent file (with hashes) from the peers (as it is now).

**Comment by arvidn** [comment]
can you explain what you mean by "file hash"? and also what you would expect libtorrent to do with it.

**Comment by master255** [comment]
@arvidn  

> can you explain what you mean by "file hash"?

I was writing the file hashes, not the file hashe. It's in the multiple. Of course I meant the hashes of pieces. In any convenient form, hex or byte[].

>  and also what you would expect libtorrent to do with it.

Libtorrent should use these hashes to check the downloaded pieces.

**Comment by arvidn** [comment]
You can add the piece hashes (or really the metadata) in a plugin, the way `ut_metadata` does it. However, you can't set individual piece hashes though, since they can't be validated against the info-hash individually.

**Comment by arvidn** [comment]
you can also set the metadata from the "outside" (without a plugin), using [set_metadata()](http://libtorrent.org/reference-Core.html#set_metadata()).

**Comment by master255** [comment]
@arvidn Why can't I specify hashes for just one file out of 10? If the other files are in IGNORE priority. Or this allowed for a plugin?

**Comment by arvidn** [comment]
you're talking about piece hashes, right? I answered that question already: https://github.com/arvidn/libtorrent/issues/4797#issuecomment-650073113
Nobody has implemented support for adding *unvalidated* hashes. It seems like a fringe feature.

**Comment by master255** [comment]
@arvidn 
> Nobody has implemented support for adding unvalidated hashes. 

What's wrong with that?
This is my program. I must have the freedom to do what I want if the users need it.

**Comment by arvidn** [comment]
> What's wrong with that?
> This is my program. I must have the freedom to do what I want if the users need it.

I don't know what you're on about. This ticket is not referring to *your* program. Of course you can do whatever you want in your program, you don't need to ask me for permission.

**Comment by master255** [comment]
@arvidn Hey men, maybe you need to relax. I'm a developer and an inventor. I've already offered you three super technologies of the future, and you didn't even thank me. And vice versa, you're treating me like an enemy. It's not right.
Maybe you need to look at yourself from the outside?

**Comment by ssiloti** [comment]
@master255 Arvid has shown incredible patience in dealing with you despite your repeated rude and condescending remarks. If it were me I would have ignored you and closed all of your issues a long time ago. I know there is little-to-no chance that anything I say here will get through to you so I will just say this: I seriously suggest you seek professional help for your mental health.

**Comment by master255** [comment]
@ssiloti :D ha ha. I'm flashy, yes. But I am master255. You can look at me on Google search.
We started with Arvidn writing to me about me being too rude to programmers, and now we come to the point where Arvidn is not ethical.
I think I was right. You miss me in real life. I'd show you how to code and what Siberia is))).

**Comment by master255** [comment]
@ssiloti In Google on 1, 2, 3, 4, wow! even on page 10 I found myself. A good person must be a lot))).

**Comment by arvidn** [comment]
@master255 please make your next post on-topic

**Comment by FranciscoPombal** [comment]
@master255 

If I had a reddit account, I would screenshot a lot of your posts, in particular these last few, post them to r/programmingcirclejerk and farm karma like a madman. Wait, no, they might actually be powerful enough to jump start a whole new sub, probably named r/programmingcringetopia.
