### ISSUE TITLE
memory and fd leak for parts file

### ISSUE THREAD

**Issue by xuefer** [arvidn/libtorrent#4798]
**Please provide the following information**

libtorrent version (or branch):
1.2.3-git-1

platform/architecture:
openwrt/x86-64

compiler and compiler version:
gcc 9.2.0-2

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

```
deluged 10403 downloader   62r      REG     0,24 10534912   200444 /custom/mnt/downloader/downloads/Anime/O/.4a7734d23f7795dff683cac656abcea2d609d12a.parts
deluged 10403 downloader   63r      REG     8,19  1242574      381 /usr/share/GeoIP/GeoIP.dat
deluged 10403 downloader   64r      REG     0,24  6341632   201187 /custom/mnt/downloader/downloads/Anime/O/.ce22d13ad84f2ca3da071c2c6f55f8e97de6a0e7.parts
deluged 10403 downloader   65r      REG     0,24 16779264   180487 /custom/mnt/downloader/downloads/Software/Art/.ef4d064672f18303937031fad9b62c93b50f1924.parts
deluged 10403 downloader   67r      REG     0,24   834872   200642 /custom/mnt/downloader/downloads/Anime/fav0/.54e6c692ba248d305bdf193e8b272cebaec0c801.parts
```

even after all torrent is stopped, parts files are not closed
RES mem was 200MB right after started but now RES mem is 935MB, until i remove all torrents of the above parts

**Comment by arvidn** [comment]
the title suggests that there's a leak of file descriptors. the list of open files you post though are to different part files, so that doesn't look like a leak.

All of the memory those open file use are under the control of the kernel, either as dirty pages or buffers that can be evicted cheaply. It's not obvious that it's a *problem* to keep those files open. Just like it's not obvious that the resident memory is higher, as long as it's kernel buffers.

You're saying you would expect them to be closed when the torrent is stopped?

**Comment by xuefer** [comment]
for active torrents (which use some cache memory and open fds), when torrent is stopped, most resident memory is free'ed, non-parts fd's are closed, may not immediately but after sometime

both fd and resident memory taken by parts file _are_ released right after torrent got "remove with data"

my box spec is 4G memory total, while deluge set to 65535*16*1024 (1G) cache and some more for running, but yes i suffer from out of memory issue.

**Comment by arvidn** [comment]
could you test this patch? https://github.com/arvidn/libtorrent/pull/4802

**Comment by arvidn** [comment]
@xuefer would you be able to test that fix?

**Comment by xuefer** [comment]
sorry, i was away. trying to test now. will report later

**Comment by xuefer** [comment]
look good, except in one case it still left open

condition: incomplete torrents with parts file (before torrent is started, uncheck some file, let it download some but don't let it finish all checked files)
event: restart deluge, parts fd left un-closed

**Comment by arvidn** [comment]
right. partfiles aren't managed by the file pool, which means they could cause the process to open more file descriptors than it's supposed to. Maybe it's a reasonable assumption that accessing the part file won't be very common, and the file can just be opened every time we need to read or write to it.

**Comment by xuefer** [comment]
part files fd leak is fixed with your latest pull request. i'd guess it won't help on memory issue
with first patch memory still take a lot more than in-lib cache size, eating system cache memory
it was using 2.2G (expected to be about 1.2G~1.4G) with first patch applied before i restarted it to test the second patch


i'm using this deluge+rblibtorrent for a years, most of the time memory issue didn't happen but sometimes it did, maybe parts file + incomplete torrent was the trigger

**Comment by xuefer** [comment]
it happens again
startup=200 RES
normally: with 1 active torrent it's 1.2GB~1.4GB;; 2 minutes after all paused: drop down to 700
abnormally: with some active torrent it's about 2GB;; 2 minutes after all paused: drop down to 1.3GB

**Comment by arvidn** [comment]
are there any files that appear to be leaking?

**Comment by xuefer** [comment]
> are there any files that appear to be leaking?

nope, so far so good with fd
