### ISSUE TITLE
Issue with seed mode

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4799]
**Please provide the following information**

libtorrent version (or branch):
RC_1_2
platform/architecture:

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Torrents added in seed mode are not checked for missing files, which is expected. 

But when client restarts, if torrent has missed files, fastresume rejected alert is generated and torrent gets paused. 
But apparently seed mode not exited. 
As client showing 100% completion which can happen when libtorrent is reporting torrent status as finished.

**Comment by an0n666** [comment]
Is it required to unset the seed mode flag when fastresume gets rejected?

**Comment by arvidn** [comment]
what's different the second time the torrent is started compared to the first time?
if there are missing files the *first* time the torrent is added, does it also cause the same issue?

**Comment by an0n666** [comment]
First time added, no missing files.
Exit client, delete files, start client, torrent is paused at 100% with fastresume rejected alert in log. But torrent can be resumed and it starts seeding instead of checking because it’s of the finished status.

**Comment by arvidn** [comment]
does the same thing happen the first time, if you delete the files first?

**Comment by an0n666** [comment]
Qbt calls the read piece function the first time torrent is added...and if there’s a file error alert that torrent is rechecked automatically. So if I add first time without any files, without the qbit rechecking, then it will add without errors.

**Comment by an0n666** [comment]
I mean if we use default libtorrent approach then the first time you add a torrent in seed mode without the actual files, it will add without any issue.
But when client is restarted fastresume failed alert is generated.
Which means libtorrent is checking for missing files on 2nd attempt.
I think this behaviour should be consistent.

**Comment by an0n666** [comment]
I looked inside fastresume file to make sure seed_mode flag was written there.
and looks like it's indeed written 9:seed_modei1e
Not sure though if qbit loads the file with seed_mode flag in 2nd attempt.

**Comment by an0n666** [comment]
There's another difference to note:

These torrents show 100% completion even though fastresume was rejected.
Other torrents would go to 0% in such cases.

**Comment by arvidn** [comment]
@an0n666 could you test this patch? https://github.com/arvidn/libtorrent/pull/4808

**Comment by an0n666** [comment]
@arvidn 
I tested it and it's still the same. No changes at all.

**Comment by arvidn** [comment]
@an0n666 are you completely certain that you ended up using the newly built libtorrent? (can you check with `ldd`?)
Do you have a log from the startup that fails? I imagine you still see the resume data check fail, but then resuming as if you had all files, is that right?

I added a unit test for that case specifically, which *does* end up running a full recheck of the files. But it's possible I've misunderstood the scenario.

What I tested was:

1. seed mode set in `add_torrent_params::flags`
2. `add_torrent_params::have_pieces` is empty
3. one file is missing from the save directory

**Comment by an0n666** [comment]
I switched to seed-mode-resume branch and then built it. So pretty sure using that branch. 
I had 1.2.6.0 installed before...now in qbit it’s showing 1.2.7.0.

There’s only one line is log that says File sizes mismatch for torrent 'xyz', pausing it.
It’s generated only by fast resume rejected alert. 

Torrent is paused at 100%. 
No auto recheck. 
No errors on torrent. 
Can resume as if nothing happened.

**Comment by an0n666** [comment]
add_torrent_params::have_pieces is empty

Is this correct scenario? Remember I had all pieces when I added the torrent first time in seed mode.

**Comment by arvidn** [comment]
> add_torrent_params::have_pieces is empty
> 
> Is this correct scenario? Remember I had all pieces when I added the torrent first time in seed mode.

I would think so. I the "have pieces" vector is populated (with all '1'), the seed-mode flag isn't really necessary, since we the resume data already indicates we have all pieces.

**Comment by arvidn** [comment]
I added a few more test cases with the piece vector set to have-all and have-none (while a file is missing)

**Comment by an0n666** [comment]
In qBt General tab it shows I have all the pieces in that torrent.

**Comment by arvidn** [comment]
would you mind investigating a bit further the state of `add_torrent_params` when it fails?
Can you run qbt in a debugger?

**Comment by an0n666** [comment]
@arvidn 
Need a bit of help...Is there any chance that a torrent finished alert is also generated when we use seed mode?
That would explain all the issues that I'm having in qBt.

**Comment by an0n666** [comment]
Nevermind.....I found the issue!

**Comment by an0n666** [comment]
Ok so here's the problem...

When we add torrents with seed_mode there's a torrent_finished_alert generated by libtorrent.
When qBt sees the alert it sets missing files state of false. Meaning if someone now resumes the torrent there'll be no force rechecks.

Also libtorrent is setting the torrent status to torrent_status::finished
This fools qBt into thinking it has 100% of files.

Now to fix these we should not send torrent finished alert in seed mode if files are missing.
Also we should fix the torrent status.

**Comment by an0n666** [comment]
I see that libtorrent posts that alert when torrent_status::finished is true.
So this status is the main culprit here.

**Comment by an0n666** [comment]
This can also be fixed by not reacting to torrent_finished_alert in seed mode...
Let me know if it's fixable in libtorrent otherwise I'll open a PR in qBt.

**Comment by FranciscoPombal** [comment]
> Edit : Seems like qBt was already ignoring torrent_finished_alert in seed mode but the missing files state was still being set to false due to misplaced code. Will fix that in qBt. You can close this.

https://github.com/qbittorrent/qBittorrent/pull/13087

**Comment by arvidn** [comment]
it doesn't sound right to issue a `torrent_finished_alert` if the resume check fails, and we determine the torrent is not finished.. I'm still interested in pursuing this patch. I will add a check for this alert to the unit tests

**Comment by glassez** [comment]
> Seems like qBt was already ignoring torrent_finished_alert in seed mode but the missing files state was still being set to false due to misplaced code. Will fix that in qBt. You can close this.

You misunderstood the qBt logic.

**Comment by an0n666** [comment]
> > Seems like qBt was already ignoring torrent_finished_alert in seed mode but the missing files state was still being set to false due to misplaced code. Will fix that in qBt. You can close this.
> 
> You misunderstood the qBt logic.

Thank you. Very informative post ;)

**Comment by glassez** [comment]
>Thank you. Very informative post ;)

It is so that others do not base their reasoning on the wrong assumptions that you have provided. I will provide something more detailed when I can set aside time for it.
https://github.com/arvidn/libtorrent/issues/4799#issuecomment-652343705 seems to be real libtorrent issue that should be fixed anyway.

**Comment by arvidn** [comment]
I made the unit tests ensure there is no `torrent_finished_alert` when adding a torrent in seed-mode but files are missing. Could someone provide more details about the scenario where this happens? What does `add_torrent_params` look like exactly?

**Comment by an0n666** [comment]
Fixed by https://github.com/arvidn/libtorrent/pull/4808
