### ISSUE TITLE
access violation in mmap_storage::writev

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#4800]
libtorrent version (or branch): master
platform/architecture: Win7 64Bit

compiler and compiler version: Visual Studio 2019

I get access violation errors in:

> sig::try_signal([&]{
	std::memcpy(const_cast<char*>(file_range.data()), buf.data(), static_cast<std::size_t>(buf.size()));
});

I do not know if this is due a change in libtorrent or my recent change to Visual Studio 2019 (had to upgrade from VS2015 because of libtorrents c++ requirements).

**Comment by arvidn** [comment]
is access violation the thing windows raise when you run out of disk space?
I'm imagining that maybe this is some I/O error you're seeing. Anyway, the `try_signal` function is supposed to catch it and turn it into an `error_code`. Is it possible the debugger catches the signal even though there's a handler installed for it?

**Comment by MassaRoddel** [comment]
Access violation is the same as segmentation fault. My debugger is set to catch that exception as it is a real problem. However, libtorrent handles it and continues to run - the torrent gets paused. But the torrent won't finish unless you recheck the files or restart the session.
There is no out of disk space problem.

**Comment by arvidn** [comment]
when you write to a memory mapped page that's backed by a file, you may get a page fault. The kernel will need to update the TLB and sometimes actually provide the physical memory backing the page. If it's writing to a file, it may even have to extend the file by 4 kiB. If there is an I/O error, it's reported back as `SIGSEGV` (linux) or `SIGBUS` (BSD) and I would imagine windows reports it as access violation.

I don't think there's really a channel for extended error codes to hint at *what* went wrong (apart from the signal number). What error does libtorrent report when it stops the torrent?

**Comment by MassaRoddel** [comment]
I have to wait until it happens again to get the libtorrent error.
Could it be this:

> A read-only view of the file is mapped. An attempt to write to the file view results in an access violation.

[MS Doc](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-mapviewoffile)

**Comment by MassaRoddel** [comment]
It happend again it seems to be a real crash.
There was another thread in readv for the same file. It looks like while in writev another thread entered readv for the same file.
[crash.txt](https://github.com/arvidn/libtorrent/files/4842081/crash.txt)

**Comment by arvidn** [comment]
the scenario you describe is *supposed* to work. The file mapping is reference counted and each thread that needs it holds on to a reference. i.e. it shouldn't be possible for one thread to *evict* and close the file and file mapping while another thread is using it.

Looking at your stack traces; it looks like one thread is writing to the file map and the other thread is opening and mapping a file. However, the second thread is in `string_view::to_string()`, so it doesn't look like it's interacting with the kernel at the time.

On the other hand, perhaps it has *just* done so, invalidating a mapping.

What I can imagine might happen is if the two threads race to open a file, neither sees one open in the `file_view_pool`, so they both open a file and create a file mapping, and subsequently inserts that new file in the pool. One of  the inserts would fail and that file would probably go out of scope and close the file. Maybe if the failure to insert case isn't handled correctly, maybe the thread ends up using the file after it has been destructed. It seems a bit far-fetched but I'll take a look at that.

There's also this issue @ssiloti discovered on windows, is there any chance this might be related? https://github.com/arvidn/libtorrent/issues/3842

**Comment by arvidn** [comment]
it looks like hold a mutex for the whole duration of checking the pool, opening the file and inserting it into the pool. So that race shouldn't exist.

**Comment by arvidn** [comment]
it looks correct afaict. after the file is opened, we lock the mutex, insert the new file, and return the entry we got back from the `insert()` call. in other words, if there's a race, the losing thread will have its `e` just be destructed and use the other thread's file mapping.

https://github.com/arvidn/libtorrent/blob/RC_2_0/src/file_view_pool.cpp#L138

**Comment by arvidn** [comment]
@MassaRoddel Can you see if the file mapping was opened in read-only mode?
The file entry is defined [here](https://github.com/arvidn/libtorrent/blob/RC_2_0/include/libtorrent/aux_/file_view_pool.hpp#L120) and the `mode` member should tell you.

I suppose at that point you might only have access to the [file_mapping](https://github.com/arvidn/libtorrent/blob/RC_2_0/include/libtorrent/aux_/mmap.hpp#L96) which means you'd have to go through to the [file_mapping_handle](https://github.com/arvidn/libtorrent/blob/RC_2_0/include/libtorrent/aux_/mmap.hpp#L96) and then to the [file_handle](https://github.com/arvidn/libtorrent/blob/RC_2_0/include/libtorrent/aux_/mmap.hpp#L71) which has an `m_open_mode` member on windows.

**Comment by MassaRoddel** [comment]
Could this be caused by the fact that in file_view_pool::open_file() the mutex l is unlocked inbetween and therefore two threads can first see key_view not having the file and then get to the stage there they both insert the file with different modes into key_view2?
That is just a hypotheses.
Btw, I referring to the master branch but i guess the code is the same in RC_2_0.

**Comment by MassaRoddel** [comment]
The IF statement is sometimes true. Isn't that a problem?

> auto it = key_view2.insert(std::move(e));
if (m & open_mode::write && it.second == false)
{	
}

**Comment by arvidn** [comment]
that's a condition you added to test this, right? I suppose you're right that if the other thread opened in read mode, the one opening in write mode need to win the race

**Comment by ssiloti** [comment]
I can't finds the commits now, but IIRC we had this problem in the pre-mmap code as well. If another thread wins the race to insert into the map then the current thread still needs to use its copy of `file_entry` because the other copy might be read-only.

**Comment by arvidn** [comment]
yeah, I guess that would be a simple solution

**Comment by MassaRoddel** [comment]
That was my test code to see if it was possible to return a read only file access to writev and access violation was correct.
Libtorrent did report that error as something like  "a bad pointer was passed as argument" (i don't have the correct english translation).

**Comment by arvidn** [comment]
@MassaRoddel could you test this patch? https://github.com/arvidn/libtorrent/pull/4809

**Comment by MassaRoddel** [comment]
Testing ...

**Comment by arvidn** [comment]
@MassaRoddel I updated the patch with an approach that I think is a bit safer. When you have a chance, would you mind testing the updated version too?
