### ISSUE TITLE
add_torrent using a url returns wrong info-hash

### ISSUE THREAD

**Issue by aresch** [arvidn/libtorrent#481]
libtorrent 1.1.0
Relevant code here: https://github.com/spritzle/spritzle/blob/master/spritzle/resource/torrent.py#L67

Snippet:
```python
    try:
        th = core.session.add_torrent(atp)
    except RuntimeError as e:
        raise HttpProcessingError(
            code=500, message="Error in session.add_torrent(): " + str(e))

    info_hash = str(th.info_hash())

    return web.json_response(
        {'info_hash': info_hash},
        status=201,
        headers={'Location': '{}://{}/torrent/{}'.format(
            request.scheme, request.host, info_hash)}
        )
```

I add a torrent to the session using the url, this maps directly to the add_torrent_params for session.add_torrent().

```
$ curl -i -X POST -d 'args={"url": "https://www.archlinux.org/releng/releases/2016.02.01/torrent/", "save_path": "/tmp"}' http://localhost:8080/torrent
HTTP/1.1 201 Created
LOCATION: http://localhost:8080/torrent/2aec398c6136971920d32e34d298d7476fe8ff53
CONTENT-TYPE: application/json; charset=utf-8
CONTENT-LENGTH: 57
DATE: Thu, 18 Feb 2016 05:39:58 GMT
SERVER: Python/3.5 aiohttp/0.21.0

{"info_hash": "2aec398c6136971920d32e34d298d7476fe8ff53"}
```

It successfully adds the torrent, but the info-hash from the torrent_handle isn't correct.

```
$ curl -i -X GET http://localhost:8080/torrent
HTTP/1.1 200 OK
CONTENT-TYPE: application/json; charset=utf-8
CONTENT-LENGTH: 44
DATE: Thu, 18 Feb 2016 05:48:55 GMT
SERVER: Python/3.5 aiohttp/0.21.0

["88066b90278f2de655ee2dd44e784c340b54e45c"]
```

The correct info-hash is 88066b90278f2de655ee2dd44e784c340b54e45c.

**Comment by arvidn** [comment]
It's not possible to return the info-hash before the file has been downloaded. the temporary "info-hash" is the hash of the URL. See [here](http://libtorrent.org/reference-Session.html#url) and [here](http://libtorrent.org/reference-Alerts.html#torrent_update_alert).

I'm considering deprecating this feature entirely because it fits so poorly. It doesn't make sense to treat an HTTP download as a torrent. Would you think that would be reasonable?

**Comment by aresch** [comment]
Yes, that seems reasonable.  It seems like this is something that a client could easily handle.

**Comment by aresch** [comment]
FWIW, I did see the alerts afterwards that showed me what was going on.  I wasn't printing out all of the relevant information from the alerts.

alert: state_changed_alert https://www.archlinux.org/releng/releases/2016.02.01/torrent/: state changed to: dl metadata
alert: torrent_added_alert https://www.archlinux.org/releng/releases/2016.02.01/torrent/ added
alert: add_torrent_alert added torrent: https://www.archlinux.org/releng/releases/2016.02.01/torrent/
alert: torrent_resumed_alert https://www.archlinux.org/releng/releases/2016.02.01/torrent/ resumed
alert: stats_alert https://www.archlinux.org/releng/releases/2016.02.01/torrent/: [1000] 0 0 0 0 0 0
alert: torrent_update_alert https://www.archlinux.org/releng/releases/2016.02.01/torrent/ torrent changed info-hash from: 2aec398c6136971920d32e34d298d7476fe8ff53 to 88066b90278f2de655ee2dd44e784c340b54e45c
alert: metadata_received_alert archlinux-2016.02.01-dual.iso metadata successfully received
