### ISSUE TITLE
Trying to understand libtorrent multi-homing

### ISSUE THREAD

**Issue by Gattag** [arvidn/libtorrent#4813]
1.2.7.0 (also 1.2.5.0) frostwire-jlibtorrent
Linux x86_64 

In my current tests I have two OpenVPN clients connected to different servers, producing a tun0 and tun1. I have a basic program set up to that takes a single magnet link, fetches the torrent info, and downloads the files. This has worked great for a bunch of my testing so far. When I set the incoming and outgoing interfaces to both tun0 and tun1 (also tested with IPs), it only sends traffic over whichever interface is the default route. So if default is tun0, the traffic is over tun0, same for tun1, and if I put eth0 as the current default route then the nothing happens. 

Assuming libtorrent is binding the socket to the device like I'm assuming it would, but I'm not sure, I'd expect some sort of load balancing of a single torrent without regard to the default route when using IPs.

I'm not sure where I'm going wrong, if this is routing, libtorrent, jlibtorrent, or something else.

Thanks

**Comment by ssiloti** [comment]
Libtorrent will attempt to use `SO_BINDTODEVICE` to bind each socket to its respective interface, but this is a privileged operation so you need to be running your client as root for it to work. The other solution is to configure source based routing so that packets are routed to the interface corresponding to the packet's source address.

**Comment by Gattag** [comment]
Everything in my testing has been running in route because of `SO_BINDTODEVICE`. is there any other information I could provide that would be useful?

And I'll look more into source based rooting if that's the only solution, but I'd love to avoid that if possible

**Comment by arvidn** [comment]
If you enable peer_logging, do you see half of your peer connections fail with some helpful error message?
If you can't see anything helpful in the log, one heavy-weight way to trouble-shoot would be `strace` and trying to filter out a single socket that fails to use the right interface.

my understanding is that, on linux, you can add hints to your routing table of which source IP addresses should use a specific route.

With libtorrent, there's a tool called `enum_if` you could test as well. It prints the routing table and network interfaces, as seen by libtorrent.

```
cd libtorrent/test
b2 link=static stage_enum_if
./enum_if
```

On linux this tool will print any source-hint set on a route as well.

In addition to `SO_BINDTODEVICE`, libtorrent will also `bind()` outgoing sockets to their assigned local IP.

**Comment by arvidn** [comment]
another thing to keep in mind is that uTP sockets can only be bound to an interface that's also in `listen_interfaces`. It sounds like you set `listen_interfaces` and `outgoing_interfaces` to the same though.

Do you notice any difference if you disable utp connections?

**Comment by Gattag** [comment]
So this is where I'm at so far

just TCP or just uTP appears to make no difference

While my understanding tells me that this should still work regardless, just to make it known, there is no UPNP, NAT PNP, or static port forwarding available on the tunnels currently

After looking at the alerts, it does appear that about half of the attempted connections fail, when the default route is set to one of the tunnels. The alert is a `PEER_DISCONNECTED` `Connection timed out (reason: 0)` (I don't know if I was supposed to see `PEER_LOG` alerts, but I never saw one, even after just setting the `alert_mask` to `0xFFFFFFFF`). Which is also evident when I use bmon, I don't know if I was oblivious before or what, but I somehow missed that it was always sending a bit of traffic out of the non default tunnel, but was just not really receiving anything (And both tunnels are fully working and can be fully saturated simultaneously through other means). 

![image](https://user-images.githubusercontent.com/6209327/86176013-52123b80-baf2-11ea-83ca-04f7e8b8b94b.png)

Here are a list of my routes if it helps
```
0.0.0.0/1 via 10.133.16.1 dev tun1
default via 10.54.1.1 dev eth0 proto static
10.20.16.0/24 dev tun0 proto kernel scope link src 10.20.16.26
10.54.1.0/24 dev eth0 proto kernel scope link src 10.54.1.16
10.133.16.0/24 dev tun1 proto kernel scope link src 10.133.16.4
globally-addressable-ip1 via 10.54.1.1 dev eth0
128.0.0.0/1 via 10.133.16.1 dev tun1
globally-addressable-ip2 via 10.54.1.1 dev eth0
```
These two are just generated by whichever vpn starts first (the other will error on route creation) and suppress the default route with the new one. If I remove them, then I still see both tunnels attempting to reach out, but neither get a successful response.
```
0.0.0.0/1 via 10.133.16.1 dev tun1
128.0.0.0/1 via 10.133.16.1 dev tun1
```
I'm still quite new to routing, so I have a little feeling I've done something very dumb or made a bonehead assumption in regards to that.

I haven't run strace yet but am just about to. Since I'm using jlibtorrent, I haven't dealt with building the source and dealing with that, but I will if that's what's required of me

**Comment by arvidn** [comment]
is it possible that the VPN software blocks *all* other interfaces, other than its own tunnel?
If so, the last one you start would be the only one that works

**Comment by Gattag** [comment]
I'm still looking into that just a little, but I really don't think so.
For an example, if I want to, after the vpns have started up, I can get rid of 
```
0.0.0.0/1 via 10.133.16.1 dev tun1
128.0.0.0/1 via 10.133.16.1 dev tun1
default via 10.54.1.1 dev eth0 proto static
```
and add
```
default via 10.20.16.1 dev tun0
```
or
```
default via 10.133.16.1 dev tun1
```
and the traffic will flow through the respective tunnel. And even moreso, packets are being sent and they are being received from the tunnel that is not the default route. Looking through the what is pushed by the OpenVPN server I don't see any configuration settings what would "block" anything except for `redirect-gateway def1`, which overrides the default gateway as mentioned above, but what I just described undoes all of that and in any case I believe is relevant.

I wouldn't rule it out just yet, but it looks very unlikely to me
I'm still looking through the `strace` atm also

**Comment by Gattag** [comment]
```
20275 socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP) = 8
20275 setsockopt(8, SOL_SOCKET, SO_BINDTODEVICE, "tun0\0", 5) = 0
20275 bind(8, {sa_family=AF_INET, sin_port=htons(6666), sin_addr=inet_addr("10.20.16.11")}, 16) = 0
20275 getsockname(8, {sa_family=AF_INET, sin_port=htons(6666), sin_addr=inet_addr("10.20.16.11")}, [28->16]) = 0
20275 setsockopt(8, SOL_TCP, TCP_NOTSENT_LOWAT, [16384], 4) = -1 ENOPROTOOPT (Protocol not available)
...
20275 socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP) = 14
20275 setsockopt(14, SOL_SOCKET, SO_BINDTODEVICE, "tun1\0", 5) = 0
20275 bind(14, {sa_family=AF_INET, sin_port=htons(6667), sin_addr=inet_addr("10.133.16.15")}, 16) = 0
20275 getsockname(14, {sa_family=AF_INET, sin_port=htons(6667), sin_addr=inet_addr("10.133.16.15")}, [28->16]) = 0
20275 setsockopt(14, SOL_TCP, TCP_NOTSENT_LOWAT, [16384], 4) = -1 ENOPROTOOPT (Protocol not available)
```
During the `strace`, `tun1` was the current default route, these two sockets were responsible for a lot of outbound traffic, and they were often seen both calling `sendmsg`, both to the same destination, then another destination, and so on. `recvmsg(14, ...` was called a lot, but `recvmsg(8, ...` was not called once. A `tcpdump -ni tun0` showed that the tunnel was sending and receiving packets as I'd expect. I don't know if this is useful, I'm not really sure what to look for. All this makes me think is that this is routing issue, but I don't really know, this is all a new area that I've been entering.

lmk what you think, thanks

**Comment by arvidn** [comment]
those are the two UDP sockets opened and bound to each interface, used to support uTP sockets. So, multiple uTP sockets will be tied to each of those, hence the many different destinations.

When a new peer connection is opened, it's assigned an outgoing interface (if configured) round-robin. Which means if you connect to a peer, disconnect and reconnect, the second time it may be using the other interface.

It looks like I'm setting `TCP_NOTSENT_LOWAT` on UDP sockets, which isn't right. I should fix that.

in tcpdump, do you see the traffic to and from both of those UDP sockets go over the same network?

This routing table:
```
0.0.0.0/1 via 10.133.16.1 dev tun1
128.0.0.0/1 via 10.133.16.1 dev tun1
```

Doesn't that look a bit suspicious?

Why split based on the top bit of the destination IP?
the network device is the same for both routes.
the gateway is the same for both routes.

**Comment by Gattag** [comment]
```
0.0.0.0/1 via 10.133.16.1 dev tun1
128.0.0.0/1 via 10.133.16.1 dev tun1
```
This definitely is a little odd, but as I kinda said earlier it is just a result of OpenVPN's `redirect-gateway def1` config param, which does it this way to not completely delete the default gateway and instead just suppress it. From OpenVPN's site: `def1 -- Use this flag to override the default gateway by using 0.0.0.0/1 and 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of overriding but not wiping out the original default gateway.` Now I have tried many different things (a lot just spitballing), like deleting both of those and the default (after both vpns are running), and then adding something like
```
default via 10.54.1.1 dev eth0 metric 100
default via 10.20.16.1 dev tun0 metric 101
default via 10.133.16.1 dev tun1 metric 102
```
Depending on which one has the lowest metric says if I get any real traffic on `tun0`, `tun1`, or neither, but still never both of the tunnels.

On the question about the `tcpdump` when looking at either of the tunnels I did not see any traffic that appeared out of place to me, but to be honest besides seeing the wrong IP addr or port (so for the other tunnel), I don't know what I would look for in the dump.

lmk know what you think, does the routing still off to you?

I'm currently setting up boost so I can see what `enum_if` says

**Comment by Gattag** [comment]
I'm also considering spinning up another hypervisor so that I can run the vpns at the hypervisor level and just pass the devices to a VM running under it just to see if that somehow makes a difference to it, but I'll save that until later

**Comment by Gattag** [comment]
I still doesn't solve it the desired way, but I got it to work with source based routing

**Comment by arvidn** [comment]
As a layman in routing and network stacks, my understanding is that that's the (only) way to do it on linux. I seem to recall reading about how you could assign routing tables to individual sockets on BSD as well, which would be another way of doing it (but libtorrent doesn't attempt that).

my impression is that, the traditional algorithm and function of a routing table only allows for a single best match. And if you have a single system-wide routing table, everything will go over that best match. I believe the source hint is linux specific, as a way to better support multi-homed hosts.

**Comment by Gattag** [comment]
I definitely have no clue if it's the only way or not, I assumed it wasn't necessary, but I couldn't seem to get it to work any other way. Is there anything else worth investigating or should it be closed? 

On a side note, and maybe as a different issue, I'd love to see the ability to change the peer mode from a round robin to something that can maintain multiple connections to a single peer over the different networks in a multi-home. Would that be simple to add? I'd love to contribute a little if possible

**Comment by arvidn** [comment]
unfortunately that would be a bit complicated. right now peers are kept unique by their remote IP (in `peer_list.cpp`), and it's optimized to not consider an IP we're already connected to. That would have to change to make the remote and local IP pair the unique key.
