### ISSUE TITLE
stop_upnp() sometimes gets stuck at m_socket.close();

### ISSUE THREAD

**Issue by BadPointer0** [arvidn/libtorrent#482]
If UPnP is used, it prevents the session object from being deleted and the app never closes. The issue must be specific for my PC. The good news is that it happens all the time, so it should be easy to track it down. Let me know if you need additional info or suggest trying some changes.

I'm using libtorrent 1.0.8 on Windows 7. MinGW-w64(5.3.0).

**Comment by arvidn** [comment]
do you have a stack trace to the hung thread?
I seem to recall there being a bug in either windows or some popular firewall software a long time ago with this symptom. that may have been windows vista though.
do you run a rd party firewall?

**Comment by BadPointer0** [comment]
I don't use firewall.

I don't have a backtrace because it doesn't crash but the control goes like this.
1) ~session()
2) ~session-imp()
{          
...
   m_io_service.post(boost::bind(&session_impl::abort, this));
   m_disk_thread.join();  // waits for session_impl::abort
...
}
3) void session_impl::abort()
{
...
   stop_upnp();  // locks up here
}

**Comment by Falcosc** [comment]
could this be related to https://github.com/arvidn/libtorrent/issues/1168 ?
