### ISSUE TITLE
download file that size is larger 8G, libtorrent happen memory leaking

### ISSUE THREAD

**Issue by wanlon** [arvidn/libtorrent#4821]
**Please provide the following information**

libtorrent version (or branch):
1.2.2    libboost is 1.65
platform/architecture:
linux X86_64
compiler and compiler version:
gcc     4:5.3.1-1ubuntu1
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.(initial memory is 4MB,max memory is 768M)
when we do downloading task again and again, memory occupied by the program always increase. 
Even if we just define the variable of session(lt::session ses(std::move(params));), the memory leaking also happen. the defined value is temporary，when finished the downloading task, the thread exit

**Comment by arvidn** [comment]
leak sanitizer does not report any leaks in any of the tests. Would it be possible for you to provide a minimal example that exhibits the problem? I it sufficient to just create and destruct sessions in a loop?

Could you build with leak sanitizer, or valgrind/massif to see if any leaks are detected?

**Comment by wanlon** [comment]
> leak sanitizer does not report any leaks in any of the tests. Would it be possible for you to provide a minimal example that exhibits the problem? I it sufficient to just create and destruct sessions in a loop?
> yeah，we create 
> Could you build with leak sanitizer, or valgrind/massif to see if any leaks are detected?

**Comment by wanlon** [comment]
We use valgrind to test leaking,but it seems to be useless,following is the code that we use:
int bt_download_block(bt_param_info_t* bt_param_info,int is_share)
{
    lt::settings_pack set_pack;
    int ret=0;
    char* seed_path = bt_param_info->seed_file_path;
    char* file_save_path = bt_param_info->file_save_path;
    int dl_speed = bt_param_info->dl_speed_limit*1024*1024;
    int upnp_enable = bt_param_info->upnp_enabled;
    int socket_id = bt_param_info->socket_id;
    int start_port = bt_param_info->start_port?bt_param_info->start_port:10000;
    lt::session_params params;

    if (!is_share && check_free_space(seed_path, file_save_path)) {
        return BT_ERROR_CODE_2;
    }

    if (add_element_to_vector(seed_path)) {
        return BT_ERROR_CODE_5;
    }

    bt_set_pack(params.settings,upnp_enable,start_port);

    lt::session ses(std::move(params));

    lt::torrent_handle handle = add_torrent(ses,seed_path,file_save_path,dl_speed,lt::storage_mode_allocate);

    if (is_share) {
        send_request_package(socket_id,ret,NULL,50);
        bt_param_info->socket_id = -1;
    }
    bt_dbg(INFO,"start download bt file");
    ret = bt_download_start(&ses,&handle,seed_path,is_share);
    bt_download_finish(ses,handle,seed_path);
    bt_dbg(INFO,"block task is end ret:%d,seed:%s",ret,seed_path);

    del_element_form_vector(seed_path);

    if (!is_share) {
        bt_watchdog_add_thread(bt_param_info->socket_id,bt_param_info->msg_type);//解决libtorrent线程无法正常退出的问题
    }

    return ret;
}

when "lt::session ses(std::move(params))" is "lt:session ses("")",there is no memory leak.  The function is called by multi threads,but download finish,the function also exit. As the client_test.cpp(the demo included in libtorrent) finish downloading task
,then it exit,so memory leak not happen. Our program is always running，nerver exit.

follow code represent the torrent prameter:
void bt_set_pack(lt::settings_pack& set_pack,int upnp_enable,int start_port)
{
    #define BIND_IP_ADDRESS "0.0.0.0:"
    std::string ip_port = BIND_IP_ADDRESS + std::to_string(start_port);

    bt_dbg(INFO,"ip and port :%s",ip_port.c_str());

    #if 0
    set_pack = lt::high_performance_seed();
    set_pack.set_int(lt::settings_pack::max_retry_port_bind, 100);
    set_pack.set_str(lt::settings_pack::listen_interfaces, "0.0.0.0:10000");
    #else
    set_pack.set_int(lt::settings_pack::cache_size, 1024);
    set_pack.set_int(lt::settings_pack::active_loaded_limit, 20);
    set_pack.set_int(lt::settings_pack::choking_algorithm, lt::settings_pack::rate_based_choker);
    set_pack.set_bool(lt::settings_pack::allow_multiple_connections_per_ip, true);
    set_pack.set_bool(lt::settings_pack::enable_dht, false);
    set_pack.set_int(lt::settings_pack::mixed_mode_algorithm, lt::settings_pack::prefer_tcp);
    set_pack.set_int(lt::settings_pack::max_retry_port_bind, 100);
    set_pack.set_str(lt::settings_pack::listen_interfaces, ip_port);

    set_pack.set_str(lt::settings_pack::user_agent, "bt_manager/1.2.0");
    //set_pack.set_int(lt::settings_pack::disk_io_write_mode, lt::settings_pack::disable_os_cache);
    set_pack.set_bool(lt::settings_pack::enable_upnp, true);
    set_pack.set_bool(lt::settings_pack::enable_natpmp, true);

    set_pack.set_int(lt::settings_pack::alert_mask, lt::alert::error_notification);
    set_pack.set_bool(lt::settings_pack::use_disk_cache_pool, true);
    set_pack.set_bool(lt::settings_pack::enable_outgoing_utp, false);
    //set_pack.set_bool(lt::settings_pack::enable_incoming_utp, false);
    set_pack.set_int(lt::settings_pack::min_reconnect_time, 0);
    #endif
}

**Comment by wanlon** [comment]
I forget to report thing that when we modify cache_size to 64(1MB) from 1024(16MB), memory leak reduces,but download rate also reduce

**Comment by arvidn** [comment]
Of valgrind can’t detect a leak, what symptom do you see that suggests there is a leak?

Even if the memory is freed at process exit, it could still be a leak. The best way to detect leaks in my mind is to take a heap snapshot after startup, once the process reaches steady state. Then let memory use grow, take another snapshot and look at the difference.

Sometimes the pmap tool can be helpful too, unless all memory is on the heap (anonymous pages)

**Comment by wanlon** [comment]
yeah，because we find the memory occupied by process grow from 40MB to 700MB(see it by top tool ).even if we exit the function that complete download task ,but memory of process not reduce. If we not call downloading function,the memory not change.So we think that libtorrent may exist memory leak or we use improperly.

**Comment by wanlon** [comment]
We use client_test.cpp to download file ,if client_test not exit,the memory of demo also grows,and not reduce. (the memory can grow to 169MB)

**Comment by arvidn** [comment]
are you sure the memory isn't "caches" or pages allocated in the page cache but attributed to the process?
