### ISSUE TITLE
announce list being stolen in non private torrents

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4827]
**Please provide the following information**

libtorrent version (or branch):
RC1_2
platform/architecture:

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Uploader didn’t use private flag in a torrent uploaded to a private tracker and somehow a bot stole qBt users’ (they may have used other clients as well) tracker URL. The stolen URL contains a tracker passkey which was then used to connect to the tracker and scrape other users IP and port (anti piracy bot)
Now my question is how is this possible? 
Is the announce-list shared with other peers when DHT is enabled? 
Is there any safeguards against this in libtorrent?

**Comment by MassaRoddel** [comment]
Maybe tracker exchange plugin was enabled (lt_tex).

**Comment by an0n666** [comment]
And this extension is enabled by default in public torrents? I would consider that a security issue.

**Comment by an0n666** [comment]
qBt or other libtorrent based clients don’t advertise this feature. There’s no toggle for it anywhere...is this part of peer exchange plugin?
Shouldn’t the client explicitly mention or ask for permission before sharing tracker URLs with others? Or is this a norm in major clients to share these URLs without the knowledge of users?

If it’s not advertised then it should be disabled by default or have some safeguards to prevent accidental leaking of tracker URLs containing a passkey.

I couldn’t find this leaky behaviour in utorrent users...perhaps they don’t use this extension.

**Comment by MassaRoddel** [comment]
My assumtion was wrong because that extension does not exist in libtorrent 1.2 anymore.

**Comment by arvidn** [comment]
I can’t think of how tracker urls would be shared off the top of my head. At least not with recent clients. The lt_tracker extensions was short lived

**Comment by an0n666** [comment]
I’ll reopen it if I can gather more info. 
Currently the only info I have is all of them downloaded the same torrents using qbit that didn’t have private flag.

**Comment by an0n666** [comment]
Just to get clarification regarding one thing:
If a peer requests a magnet uri download, exactly which parts of the metafile is shared with the peer? Is it only the info dict?

**Comment by arvidn** [comment]
> If a peer requests a magnet uri download, exactly which parts of the metafile is shared with the peer? Is it only the info dict?

yes. because that's the only part that can be validated against the info-hash.
