### ISSUE TITLE
assertion failure on tracker with no uri

### ISSUE THREAD

**Issue by tghosgor** [arvidn/libtorrent#4828]
libtorrent 1.2.7

arch linux amd64

gcc version 10.1.0 (GCC) 

Normal operation as far as I can say. Built with --enable-debug --enable-invariant + arch default options.

version: 1.2.7.0-3ed6fa64f

file: '../../libtorrent-rasterbar-1.2.7/src/alert.cpp'
line: 332
function: tracker_error_alert
expression: !u.empty()

stack:
1: libtorrent::assert_fail(char const*, int, char const*, char const*, char const*, int)
2: libtorrent::tracker_error_alert::tracker_error_alert(libtorrent::aux::stack_allocator&, libtorrent::torrent_handle const&, boost::asio::ip::basic_endpoint<boost::asio::ip::tcp> const&, int, boost::basic_string_view<char, std::char_traits<char> >, boost::system::error_code const&, boost::basic_string_view<char, std::char_traits<char> >)
3: 
4: 
5: 
6: 
7: 
8: 
9: 
10: 
11: __libc_start_main
12:

**Comment by tghosgor** [comment]
An empty `tr=` in the magnet link might be the reason for this.

**Comment by arvidn** [comment]
fixed here: https://github.com/arvidn/libtorrent/pull/4842
thanks for the report!

**Comment by arvidn** [comment]
I added a unit test for the case of an empty tr= argument, it failed, then I fixed that failure. Please let me know if your case isn’t fixed yet!
