### ISSUE TITLE
docs:torrent_handle::[clear_piece_deadlines() set_piece_deadline() reset_piece_deadline()]

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#4839]
@arvidn Documentation under heading "torrent_handle::[clear_piece_deadlines() set_piece_deadline() reset_piece_deadline()]" could be improved

It is necessary to specify that the value is specified from the current time and in units of measurement - milliseconds.

**Comment by arvidn** [comment]
> deadline is the number of milliseconds until this piece should be completed.
