### ISSUE TITLE
Tracker timeout error with valid working URL

### ISSUE THREAD

**Issue by fmike7** [arvidn/libtorrent#4851]
libtorrent version (or branch): 1.2.6
platform/architecture: Windows/32 bit
compiler and compiler version: Visual Studio 2019/14.2

I use a private torrent tracker service from Amazon on top of their S3 cloud storage. The tracker URL is http://tracker.amazonaws.com:6969/announce

It seems to be working fine in most cases, however most recently I started noticing that libtorrent sometimes fails to connect to it with the following error: "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." - which is basically a connection timeout error.

When I try to open http://tracker.amazonaws.com:6969/announce using Google Chrome from the same machine it opens just fine, giving output "Require exactly one value for info_hash". But this is fine, because Chrome doesn't follow the exact protocol. They key point is it's not a timeout, the connection actually happens.

Proxy server was my first suspect, however the current browser configuration doesn't have any explicitly configured proxies, it connects directly. I saw this with one customer of ours before and now I am getting this error myself while testing this on an airplane WiFi in flight. It could be because the airline has some network equipment that is blocking it. But still I don't understand why Chrome is able to open this URL and libtorrent is not able to?

**Comment by fmike7** [comment]
Any ideas on why this might be happening? I keep getting this error with different users of ours.

One particular user reported this today: "I am getting the following error message. I set behind a watchguard Firebox T15 [Firewall] , I have tried SNAT and nothing works. How would you configure a rule on teh Firewall?"?

A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. Please make sure tracker URL http://tracker.amazonaws.com:6969/announce is accessible from this local IP address: 10.0.0.135"

--------
Here is my code that outputs this error (it ignores it during the first 20 hours of trying - so it's not a one-off thing):

if (auto tracker_error = lt::alert_cast<lt::tracker_error_alert>(a))
{
   printf("Tracker error: %s. Please make sure tracker URL %s is accessible from this local IP address: %s.",
              tracker_error->error.message(),
              tracker_error->tracker_url(),
              tracker_error->local_endpoint.address().to_string()));
}

**Comment by arvidn** [comment]
I have a suspicion that the timeout you hit isn't the connection timeout, but rather the application-level timeout for the whole HTTP request.

If it takes more than the `tracker_completion_timeout` to complete, the request is aborted. The default value is 30 seconds.
This timeout includes the time it takes to perform the host name lookup, which sometimes can stall for quite long. Even if this specific tracker's hostname always is quickly available, I believe look-ups are done in serial, so a lookup that would complete quickly may be blocked behind one that stalls.

I would suggest extending the timeout to, maybe, 60 seconds. If you're up for it, you could also test this patch which I think improves the situation a bit: https://github.com/arvidn/libtorrent/pull/4884

**Comment by arvidn** [comment]
please report back any findings!

I also think this change makes sense, to more easily tell where the error is coming from: https://github.com/arvidn/libtorrent/pull/4886

**Comment by fmike7** [comment]
Ok, thanks for the patches, I will definitely give these a shot and report back! Changing tracker_completion_timeout to a higher value should solve the issue, I think.

#4886 - would definitely help too, since it's the same tracker we used for all torrents.

#4884 - so this one would help to differentiate between network-level issues and algorithm-related timeouts? Basically tracker_error_alert::error would contain more granular error information and not this generic socket timeout error code?

**Comment by arvidn** [comment]
> so this one would help to differentiate between network-level issues and algorithm-related timeouts? Basically tracker_error_alert::error would contain more granular error information and not this generic socket timeout error code?

It's a way to distinguish a kernel-level connect operation failing with `ETIMEOUT` from an application-level timer timing out. The error message on windows is very specific, that it's a connect call that timed out, so I shouldn't be re-using that error code for application level timers, since the message become a bit misleading.

**Comment by fmike7** [comment]
Got it, makes perfect sense! Ok, I will start testing these all in the field this coming week and report back.

**Comment by arvidn** [comment]
@fmike7 I believe this will help too. would you mind testing it too?
https://github.com/arvidn/libtorrent/pull/4893

**Comment by fmike7** [comment]
int(c->m_resolving_host) - are you sure bool->int conversion converts true to 1 on all compilers? I never relied on this before.

**Comment by arvidn** [comment]
yes, that's well defined

**Comment by fmike7** [comment]
I plan on testing 4884 and tracker_completion_timeout=90 first to see if it changes anything (already doing this). Then I will try those two other patches (4893 and 4886).

But my feeling these other two would not have any effect in my case, since I use the same tracker all the time (http://tracker.amazonaws.com:6969/announce)

Or would it?

**Comment by arvidn** [comment]
a hostname lookup can take a long time even for a hostname that should be quick to look up, if a slow lookup (that times out for instance) is queued ahead of it. This is the rationale for the most recent patch, to be more forgiving of timeouts while waiting for a lookup (since the announce may be queued to initiate the lookup).

The change to coalesce could look-ups could improve things by merging all lookups to your tracker into one, if they end up queued behind a slow one. It should also slightly reduce load on the system since it won't ask the DNS server multiple times.

**Comment by fmike7** [comment]
Got it, ok. I will test these other two after finishing testing the first two.

**Comment by fmike7** [comment]
And speaking of tracker errors, here is another one I am getting: "A socket operation was attempted to an unreachable network."  - this comes in as a tracker_error_alert.

This machine has two interfaces, one is physical network 192.x and one VPN (10.x.x.x). My guess is when VPN connects, 192.x somehow become "unroutable" and that why it encounters this error.

The question is how to determine whether it was able to connect to the tracker by ANY means instead of reporting failure prematurely? My current algorithm is this:

if (auto tracker_error = lt::alert_cast<lt::tracker_error_alert>(a))
{
    if ( !tracker_error->local_endpoint.address().is_loopback() &&
         (ERROR_OPEN_FAILED != tracker_error->error.value()) )			// non-connectable interface errors with this code
    {
         print_error(tracker_error->error.message());
    }
}

But a few seconds later 10.x connects just fine and download goes through.

**Comment by arvidn** [comment]
> The question is how to determine whether it was able to connect to the tracker by ANY means instead of reporting failure prematurely?

Right, I think the simplest and most reliable way is to keep track of failures for each individual "endpoint" (i.e. local listen socket/interface). For instance, you can see how I do this in the `client_test` example: https://github.com/arvidn/libtorrent/blob/RC_1_2/examples/client_test.cpp#L1878

If you want to base it entirely on alerts (which saves you from making blocking calls into libtorrent) you can see which endpoint the `tracker_error_alert` is referring to by the [local_endpoin](https://github.com/arvidn/libtorrent/blob/RC_1_2/include/libtorrent/alert_types.hpp#L184)t member

If you know up-front which interface will work and which won't, you could also set `listen_interfaces` to just have one IP. That would give you only a single announce-endpoint as well.

If you don't necessarily know which interface will work (say, sometimes the VPN is up and the tracker is on that network), then you may need to remember the errors and ask "are all endpoints failing", or "is there at least one endpoint that succeeded"

**Comment by fmike7** [comment]
I see, ok. I think my preference would be to continue relying of alerts.

Is there a similar "success" alert for tracker successes? Such as I could keep track of successful and failed endpoints for each torrent and maintain such "at-least-one-tracker-succeeded" status.

I see there is one named tracker_reply_alert - would this be the one?

**Comment by arvidn** [comment]
yes, `tracker_reply_alert` indicates success

**Comment by fmike7** [comment]
Just tried on a simple test torrent (small size - only 2Mb file), went through full cycle (added, downloaded, flushed) while ignoring a tracker_error_alert. All went well in terms of download, and received a bunch tracker_error_alert alert for those unroutable interfaces (all ignored for testing purposes). However tracker_reply_alert have not arrived even once. I actually found a workaround for my particular purpose, so I no longer need to rely on tracker_reply_alert, but still curious why it did not arrive?

**Comment by arvidn** [comment]
perhaps you don't have the `alert_category::tracker` flag set in the `alert_mask` setting. The failure will go through even without that flag, as long as `alert_category::error` is set in `alert_mask`. I suppose it's a bit asymmetric.

**Comment by fmike7** [comment]
Got it. I added alert::tracker_notification and it came through. Thanks!

**Comment by arvidn** [comment]
I've landed all patches related to this issue. I believe it to be fixed in `RC_1_2` now

**Comment by fmike7** [comment]
Yes, I think it's gone, you can close this issue.
