### ISSUE TITLE
b2 builds usrsctp in debug mode even with variant=release

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#4855]
libtorrent version: `master`

I understand this is more about the way `libdatachannel` builds `usrsctp`, but it concerns the `libtorrent` build. Any hint and I can give it a try.

```
-- No build type selected, using DEBUG
```
See https://ci.appveyor.com/project/arvidn/libtorrent/branch/master/job/jt65wnmdicmmpnt6?fullLog=true#L409

CC @paullouisageneau

**Comment by paullouisageneau** [comment]
I seems the `CMakeLists.txt` of `usrsctp` overrides the default build to debug. It should be solved by adding `-DCMAKE_BUILD_TYPE=Release` to the call from [libdatachannel's Jamfile](https://github.com/paullouisageneau/libdatachannel/blob/5825e44fc85056c74d85ceb93e8e354e4ac5c00c/Jamfile#L90).

**Comment by arvidn** [comment]
ideally, the `build` directory used for `cmake` would also be `build-release` and `build-debug`, or something like that. I've noticed that if you build with `crypto=openssl` followed by a build of `crypto=gnutls`, some of the builds will not be rebuilt, but use the binary from the previous build. so, maybe the build directory should even include which ssl library is used. (I forget which target this happened to, it may not have been `usrsctp`)

**Comment by paullouisageneau** [comment]
Indeed, cmake build directory should be different. It should be addressed by https://github.com/paullouisageneau/libdatachannel/pull/119

**Comment by arvidn** [comment]
this can be closed, yes?

**Comment by aldenml** [comment]
yes, thanks @paullouisageneau
