### ISSUE TITLE
remap_files const problem

### ISSUE THREAD

**Issue by greta1239** [arvidn/libtorrent#4858]
Consider the following code:

```
libtorrent::torrent_handle th = ...;
std::shared_ptr<const libtorrent::torrent_info> ti = th.torrent_file();
libtorrent::file_storage fs = ti->files();
fs.set_name("...");
ti->remap_files(fs);
```

The last line causes the following error during compilation:

`error C2662: 'libtorrent::torrent_info::remap_files' : cannot convert 'this' pointer from 'const libtorrent::torrent_info' to 'libtorrent::torrent_info &' Conversion loses qualifiers.`

In the documentation (albeit for the torrent_info::rename_file function) it states:

"If you want to rename the base name of the torrent (for a multi file torrent), you can copy the file_storage (see files() and orig_files() ), change the name, and then use remap_files()."

Which is what I think that I am doing in the code above, but the whole const thing seems insurmountable (I've been trying for two days).

What I want to be able to do is this:

1. Rename a single file torrent such that (a) the name in torrent_status::name is updated and (b) the name of the file on disk is updated.
2. Rename a multi file torrent such that (a) the name in torrent_status::name is updated and (b) the name of the root folder for that torrent on disk is updated. In this case, I specifically do not want the files to be moved outside of the torrent (which is what I think torrent_info::rename_file would do, and in any case it doesn't seem as if calling rename_file for every file in the torrent is the right way to do this).

I am no expert in libtorrent or C++ so I may be missing something obvious.

**Comment by arvidn** [comment]
that's actually not what you're doing. You're getting a *reference* to the *internal* `torrent_info` object, so you're not allowed to mutate it. The error you're getting is protecting you from corrupting internal state.

Instead, call `remap_files()` on the `torrent_info` object *before* you're adding the torrent to the session. i.e. `add_torrent_params::ti`. If you need to do it *after* you've already added the torrent, you'll have to use `rename_file()` for every file instead, or maybe `move_storage()`. Those will also rename the files on disk (as they may have been created by then).
