### ISSUE TITLE
Does libtorrent verify piece hash after writing to storage

### ISSUE THREAD

**Issue by sivachandran** [arvidn/libtorrent#4863]
libtorrent version (or branch): 1.1.12
platform/architecture: x86_64
compiler and compiler version: gcc

I've been observing downloaded file corruption from time to time. The storage is ZFS pool configured in RAID-Z (i.e., with parity block). Initially I thought the corruption is due to bit rot/silent corruption. The hypothesis was confirmed by ZFS reporting corruption at block level.

But recently I'm observing file corruption which is acknowledged by ZFS. I ran ZFS scrub to explicitly verify the block checksum but no corruption reported block level. This is possible only if the data written to ZFS itself was corrupted.

I know libtorrent checks individual piece hash after download. I'm wondering
1. Does libtorrent also verify the piece hash by writing the piece to storage and reading it back?
2. If not, is there a way to enforce this?

I don't want the entire file to be download to force a verification as it would take significant time. I want the individual pieces to be verified immediately after writing to the storage.

Thanks,
Sivachandran P.

**Comment by master255** [comment]
@sivachandran This is the bottleneck in the library right now.

To be answered, you must always add the @addressee, otherwise you can wait very long. (It should be @arvidn now.)

As I understand it, in my version 1.2.7 blocks are downloaded into RAM. When the whole piece is downloaded into RAM, the hash is checked and if it is correct, it is written to disk. Moreover, the recording to disk is not a complete piece, but in parts of different sizes. But it's sequential.
Arvidn, correct me. In what order is the data downloaded? 

Now I'm fighting the problem of the PIECE_FINISHED event. There are very rare moments when it comes, but the piece is not on the disk (or it is not fully written). This is not a small problem.

**Comment by master255** [comment]
@arvidn What is not clear to me is that if the hash test fails, this data will not be written to disk? Or is it possible that the unchecked data might be written to disk?
I know Arvidn is preparing a new release. Arvidn, if you can answer our main question. Yes or not?

**Comment by arvidn** [comment]
> I know libtorrent checks individual piece hash after download. I'm wondering
> 
>     Does libtorrent also verify the piece hash by writing the piece to storage and reading it back?

Not if it can avoid it. blocks are checked as they arrive and are put in the disk cache (as long as they arrive in order). If an incomplete piece has to be flushed to disk, pieces may have to be read back to be hashed.

>     If not, is there a way to enforce this?

The closest I can think of would be to turn off the disk cache, but it wouldn't quite be what you want. I take it you want to verify the filesystem/block storage itself doesn't introduce any corruption. If the (application level) disk cache is disabled in libtorrent, all blocks received in order are still hashed from the internal buffer, the same that's passed to the write call.

**Comment by master255** [comment]
@arvidn If a piece is written to disk and fails the hash test, will it be rewritten?
Perhaps we need the exact alert after which the data on the disk will be accurately written and verified?
Maybe there's a combination of events?
I think everyone needs to have that alert.

**Comment by arvidn** [comment]
> @arvidn If a piece is written to disk and fails the hash test, will it be rewritten?

once it has been re-downloaded, yes.

**Comment by master255** [comment]
@arvidn It's okay. I already tested the disk storage.
It's very bad that the block_finish event comes to the disk when writing, and the piece_downloaded event comes to the disk when the hash is checked successfully. I haven't made a hybrid event yet, which would mean that there is a piece of data that has been tested and written to disk, but without it, the streaming 100Gb 4k movie works on Android TV without friezes. 
No sparse mode, with my algorithm. The configuration of all Android TVs Sony 2019-2020: cortexA9 32bit 2 core, 2GB Ram, 8GB internal memory, 256Gb usb (no sparse). But everything works :-)!

Now there is only one bug in my algorithm: when the piece_finished event comes, torrentHandle.havePiece == true, but the data is not yet written to disk. It happens quite rarely, so the release will be with a bug.

**Comment by master255** [comment]
@arvidn You can join in my group dedicated to the library https://t.me/libtorrent_ru. You can ask questions there and you'll get an answer :-D 
_Or maybe vice versa)))_

And close this issue. I think the creator has received an answer.

**Comment by sivachandran** [comment]
Yes, I got my answers. You can close the issue. Thanks @master255 @arvidn.
