### ISSUE TITLE
libtorrent opens listen udp port even dht and utp are disabled

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#4870]
libtorrent version (or branch): master

Is there any reason to still open the port even it should never be used?
Still getting the listen alert:
successfully listening on [uTP] ....
is a bit confusing.

**Comment by arvidn** [comment]
UDP trackers still use that same UDP socket

**Comment by arvidn** [comment]
I agree that that message is a bit confusing.

**Comment by MassaRoddel** [comment]
Ok, I forgot the trackers. Thank you.
