### ISSUE TITLE
Unhandled exception in natpmp::send_map_request

### ISSUE THREAD

**Issue by fmike7** [arvidn/libtorrent#4877]
libtorrent version (or branch): 1.2.6
platform/architecture: Windows 10/32 bit
compiler and compiler version: Visual Studio 2019

Received a crash dump recently from a customer, so really don't know how to reproduce, but the call stack seems to be fairly clear:

```
 abort()
 ---exception throw frames omitted---
 boost::asio::detail::throw_error(const boost::system::error_code &) at boost_1_73_0\boost\asio\detail\throw_error.hpp(42)
 boost::asio::basic_socket<>::local_endpoint() at boost_1_73_0\boost\asio\basic_socket.hpp(1559)
 libtorrent::natpmp::send_map_request() at src\natpmp.cpp(467)
 libtorrent::natpmp::update_mapping() at src\natpmp.cpp(434)
 libtorrent::natpmp::mapping_expired() at src\natpmp.cpp(872)
 ---ASIO invocation frames omitted---
 boost::asio::io_context::run() at boost_1_73_0\boost\asio\impl\io_context.ipp(63)
 void session::start(session_params&& params, io_service* ios) at src\session.cpp(355)
 ---thread start frames omitted---
```

In a nutshell m_socket.local_endpoint() fails with error code 10009 (WSAEBADF - The file handle supplied is not valid) and it throws an exception that is not caught anywhere, which in turn calls abort().

Any fixes available for this yet?

**Comment by arvidn** [comment]
thanks for the report!

**Comment by fmike7** [comment]
I still have the full memory dump for the crashed process with debug symbols, in case you need to look at variables, heap etc. Let me know if you need it.

**Comment by fmike7** [comment]
Got 3 more the same crash dumps today with the same stack from different machines. So it seems to be happening every now and then.

**Comment by arvidn** [comment]
would you be able to test this patch? https://github.com/arvidn/libtorrent/pull/4880

**Comment by fmike7** [comment]
will do, thanks!

**Comment by arvidn** [comment]
I updated that patch

**Comment by fmike7** [comment]
I am going to release a new build to our users later this week. Since it doesn't happen to often, if after a week or so I don't see any new crashes like this anymore, consider it's fixed.

**Comment by fmike7** [comment]
Just received a new crash dump for the fixed version, but with slightly different call stack:

 abort()
 ---exception throw frames omitted---
 boost::asio::detail::throw_error() at boost_1_73_0\boost\asio\detail\throw_error.hpp(42)
 boost::asio::basic_socket<>::local_endpoint() at boost_1_73_0\boost\asio\basic_socket.hpp(1559)
 libtorrent::natpmp::send_map_request() at src\natpmp.cpp(467)
 libtorrent::natpmp::resend_request() at src\natpmp.cpp(569)
 libtorrent::natpmp::on_resend_request() at src\natpmp.cpp(552)
 ---ASIO invocation frames omitted---
 boost::asio::io_context::run() at boost_1_73_0\boost\asio\impl\io_context.ipp(63)
 libtorrent::session::start() at src\session.cpp(355)
 ---thread start frames omitted---

This time, however, m_socket.local_endpoint() failed with error code 10055 (WSAENOBUFS - An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.). And just like before it throws an exception that is not caught anywhere, which in turn calls abort().

It looks like some very rare resource utilization situation (computer is running on memory).

Would you mind adding a try-catch block somewhere so it doesn't result in unhandled exceptions like this? It's good question though whether or not its worth trying to continue under low-memory conditions, because at that point pretty much everything starts choking and maybe aborting is not actually such a bad idea. What do you think?

**Comment by arvidn** [comment]
are you sure you're using the new version? I would be really surprised if you would get this exception out of this function now, since there's an `error_code&` passed in, this error is supposed to be returned through that variable, not as an exception.

**Comment by fmike7** [comment]
My bad! I took natpmp::mapping_expired commit, but mistakenly forgot to take natpmp::send_map_request as well! Sorry for bothering. Will do it properly now.

**Comment by fmike7** [comment]
Btw, these log() lines, where do they actually log? I think it would be helpful for me to have the ability to enabled full diagnostic logging sometimes.

**Comment by arvidn** [comment]
they are logged as alerts, if you enable the `dht_log` alert flag, see [docs](http://libtorrent.org/reference-Alerts.html#alert-category-t).
