### ISSUE TITLE
Privacy and security implications of widespread use of WebTorrent-capable BitTorrent clients

### ISSUE THREAD

**Issue by KOLANICH** [arvidn/libtorrent#4878]
Hi.

Have you considered privacy implications of adding WebTorrent support to desktop clients?

I mean malicious actors will be able to insert maliciously modified WebTorrent lib into websites and utilize users' computers and internet connections in order to harvest IP addresses of the ones downloading particular files using desktop clients probably even without sites visitors consent, and maybe even maliciously interfere. IP filters will also be rendered useless.

**Comment by arvidn** [comment]
Could you describe this attack in some more details? What new capabilities would a malicious website have?

I assume your scenario includes:

* the user is running a desktop a desktop client that is webtorrent capable.
* the malicious web site runs a javascript webtorrent client.
* the website joins a bunch of swarms and collects peers it connects to, to report back

Some counter-arguments:

1. As far as I can tell, a torrent must have a webtorrent tracker to be webtorrent enabled. If no torrent has a webtorrent tracker, there won't be any connection to the introducer service, and the client won't be able to accept webtorrent peers, if there is at least one webtorrent-enabled torrent in the session, there will be a connection to the introducer service (tracker). But it will only accept peers for that torrent, not any arbitrary torrent. @paullouisageneau, is that right?

2. This resource stealing is a more general problem on the web, and it doesn't seem like a fundamentally new capability (one can do similar harvesting already, with ones own resources). The new feature would be to be able to use unsuspecting users' compute resources. Perhaps this allows for much larger scale harvesting operations.

3. I don't think any of this affects IP filters, unless you ascribe some other meaning to IP filters. They filter IPs, nothing else.

**Comment by KOLANICH** [comment]
Threat model:
1. malicious actors can connect all the trackers in the internet, even can infiltrate invite-only ones. They also can download all the torrent files in the net. Users useng BitTorrent to transfer files between 2 PCs are out of scope.
2. malicious actors act from business IP ranges
3. malicious actors can insert own JavaScript code to popu,ar websites
4. WebTorrent is widely adopted, is enabled in clients and webtorrent trackers are widely used too.
5. ipv6 is out of scope.

>But it will only accept peers for that torrent, not any arbitrary torrent.

Adversaries' scripts can join any seeding.

>The new feature would be to be able to use unsuspecting users' compute resources. Perhaps this allows for much larger scale harvesting operations.

Exactly. And adversaries` scripts observable behavior can be made kind of indistinguishable from ordinary users being downloading using desktop clients. If we ban them ... then adversaries win. If we don't, ... adversaries also win - they can try to maliciously interfere or just be a peer and log.

>I don't think any of this affects IP filters, unless you ascribe some other meaning to IP filters. They filter IPs, nothing else.

A predicate, taking any IP address as an argument. Desktop clients using an IP filter refuse to establish TCP connections or send UDP datagrams to the peers for which the predicate returns `true`.

For the purpose of this issue I assume IP filters to return `true` for IP addresses belonging to the ranges other than the ones used by ISPs to provide ordinary households with internet access.

**Comment by paullouisageneau** [comment]
>     1. As far as I can tell, a torrent must have a webtorrent tracker to be webtorrent enabled. If no torrent has a webtorrent tracker, there won't be any connection to the introducer service, and the client won't be able to accept webtorrent peers, if there is at least one webtorrent-enabled torrent in the session, there will be a connection to the introducer service (tracker). But it will only accept peers for that torrent, not any arbitrary torrent. @paullouisageneau, is that right?

That's right, webtorrent must be explicitly enabled by the presence of at least one websocket tracker in the torrent file or magnet link, otherwise it is disabled, and of course webtorrent peers will be connected or accepted only for enabled torrents.

**Comment by paullouisageneau** [comment]
@KOLANICH How are the privacy attacks fundamentally different with WebTorrent? For instance, it is relatively easy to embed a rogue Bittorrent client in a popular Android game to harvest addresses from household wifi.

**Comment by KOLANICH** [comment]
>embed a rogue Bittorrent client in a popular Android game

That's completely true! Shame on me, I haven't considered the simple fact that the most of the people are completely mad to install and run all the kinds of malware on their devices, both desktop and mobile. Even more - the app may be preinstalled on phones and its integrity may be protected with TEE-powered verification mechanisms, to make the collected information more *sound*.

**Comment by paullouisageneau** [comment]
> Even more - the app may be preinstalled on phones and its integrity may be protected with TEE-powered verification mechanisms, to make the collected information more _sound_.

Ha ha, honestly, I would be a bit surprised if it hasn't been done already...

**Comment by arvidn** [comment]
to be fair, it would most likely be a violation of the terms of most commercial app stores, and would risk being pulled. That is a little bit different from the wild internet.

I suppose google and mozilla still warn on abusive sites too though.
