### ISSUE TITLE
Invalid stats 

### ISSUE THREAD

**Issue by jagannatharjun** [arvidn/libtorrent#4890]
**Please provide the following information**

libtorrent version (or branch):
1.2.7

platform/architecture:
Windows 10

compiler and compiler version:
msvc 16.6.4

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

in high I/O usage scenario (not by libtorrent itself but by some other process), invalid stats are produced, I was investigating https://github.com/qbittorrent/qBittorrent/issues/12560 and logging value returned by libttorrent by something like this 

```diff
diff --git a/src/base/bittorrent/session.cpp b/src/base/bittorrent/session.cpp
index af6df18ae..1076fb4f6 100644
--- a/src/base/bittorrent/session.cpp
+++ b/src/base/bittorrent/session.cpp
@@ -4665,6 +4665,14 @@ void Session::handleSessionStatsAlert(const lt::session_stats_alert *p)
     m_cacheStatus.averageJobTime = (totalJobs > 0)
                                    ? (stats[m_metricIndices.disk.diskJobTime] / totalJobs) : 0;

+    QFile f("session - speed log");
+    if (f.open(QIODevice::Append | QIODevice::Text)) {
+        QTextStream t(&f);
+        t <<
+        QDateTime::currentDateTime().toString("dd.MM.yyyy hh:mm:ss.z") << " " << qSetFieldWidth(12) << m_status.uploadRate << ' ' << m_status.downloadRate << endl;
+    }
+    f.close();
+
     emit statsUpdated();
 }
```

noticed this weird invalid value
```
21.07.2020 18:12:39.563        66138                    1791           
21.07.2020 18:12:39.578 9223372036854775808            9223372036854775808           
21.07.2020 18:12:39.985      1190169                   32694           
21.07.2020 18:12:41.481       823395                   22634        
```

**Comment by arvidn** [comment]
`m_status` does not look like a libtorrent type. Which value reported from libtorrent is invalid?

For a moment I thought you were talking about `lt::session_status::upload_rate`, but its type is `int` and won't fit such a large number, also your field is called `uploadRate`.

The value you print is `0x8000000000000000`, i.e. `INT64_MAX`. libtorrent reports rates as `int` (also, they are deprecated). But, How is `uploadRate` computed?

**Comment by jagannatharjun** [comment]
uploadRate is calculated like this 
https://github.com/qbittorrent/qBittorrent/blob/23eb117a05bf8acaab675f96c15933a3090ccc5d/src/base/bittorrent/session.cpp#L4630

I'm trying to repro this to get more data, but this bug appear very randomly

actually these calls 
```
**21.07.2020 18:12:39.563**        66138                    1791           
**21.07.2020 18:12:39.578** 9223372036854775808            9223372036854775808           
**21.07.2020 18:12:39.985**      1190169                   32694           
21.07.2020 18:12:41.481       823395                   22634  
```

should have a gap of at least 1500ms, I suppose qt queues get full, and they are executed one after another while posting for stats update, and this may be causing simultaneous access on lt::session_stats_alert::counters(), but I'm not sure, trying to repro this with logging.

**Comment by arvidn** [comment]
I think it would be good to log the actual value for `totalUpload` as well, to ensure it doesn't regress (which would cause negative numbers).

There's also no protection against two stats alerts withing the same millisecond (which would cause division by zero), but I suppose that's unlikely under heavy load.

**Comment by arvidn** [comment]
I think it might be a good idea to build qbt with undefined sanitizer as well, to ensure this value isn't produced by invoking UB somewhere.

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/4891

**Comment by jagannatharjun** [comment]
does "TORRENT_ASSERT" work in release builds (or is there any way to make it), I'm actually running release builds as I'm running my everyday qBittorrent instance that has too many torrents with and debugs builds are kinda becomes useless

**Comment by arvidn** [comment]
no, they are only enabled in debug builds. It's possible to make a release build with asserts enabled with boost-build:

```
b2 release asserts=on
```

**Comment by jagannatharjun** [comment]
tried this (ask for session stats at very low interval) -
```
    for (int i = 0; i < 10; i++) {
        using namespace std::chrono_literals;
        std::this_thread::sleep_for(10ns);
        m_nativeSession->post_session_stats();
    }
```
and was able to find out a possible reason i.e. interval being zero https://github.com/qbittorrent/qBittorrent/blob/23eb117a05bf8acaab675f96c15933a3090ccc5d/src/base/bittorrent/session.cpp#L4620

if you see original logs 
```
21.07.2020 18:12:39.563        66138                    1791           
21.07.2020 18:12:39.578 9223372036854775808            9223372036854775808           
21.07.2020 18:12:39.985      1190169                   32694           
21.07.2020 18:12:41.481       823395                   22634        
```

here interval will be zero,

got no assert failure from libtorrent or something like that., so it was actually qbittorrent bug, sorry to take your time.

**Comment by jagannatharjun** [comment]
> if you see original logs
> 
> ```
> 21.07.2020 18:12:39.563        66138                    1791           
> 21.07.2020 18:12:39.578 9223372036854775808            9223372036854775808           
> 21.07.2020 18:12:39.985      1190169                   32694           
> 21.07.2020 18:12:41.481       823395                   22634        
> ```
> 
> here interval will be zero, (almost zero)

on bit more thinking maybe not, I will let qbittorrent run for some more time and come back

**Comment by arvidn** [comment]
you would think the interval would be `0.015`, which is a pretty small number, but it doesn't seem small enough to bring the rate out of bound of a 64 bit integer.

Although, I don't think it's right to post session stats that close to the previous call. The shorter the interval is, the more noise you get in the rate.

**Comment by jagannatharjun** [comment]
> you would think the interval would be `0.015`, which is a pretty small number, but it doesn't seem small enough to bring the rate out of bound of a 64 bit integer.

I thought the same, but now I'm 99% sure this was the reason. f.e here is refresh time is the timer for posting stats_alert which updates the status, and the interval is the time between the subsequent calls, if I make the interval 15ms and then add a assert(interval > 0) after here https://github.com/qbittorrent/qBittorrent/blob/23eb117a05bf8acaab675f96c15933a3090ccc5d/src/base/bittorrent/session.cpp#L4620 assert always fails, but doesn't fails for any value greater then that
![image](https://user-images.githubusercontent.com/34717789/88087120-11b05580-cba6-11ea-940b-71667334a66a.png)

**Comment by arvidn** [comment]
your assertion truncates the value to an integer though, so if you turn `0.015` to an integer, it will be zero. Instead, you assert should say `assert(interval > 0.);`

**Comment by jagannatharjun** [comment]
> your assertion truncates the value to an integer though, so if you turn `0.015` to an integer, it will be zero. Instead, your assert should say `assert(interval > 0.);`

😮🤐

**Comment by jagannatharjun** [comment]
but it still fails if refreshtime 14, doesn't fail on 15 though
![image](https://user-images.githubusercontent.com/34717789/88088283-c8f99c00-cba7-11ea-84ec-15ff57426a75.png)

**Comment by jagannatharjun** [comment]
> your assertion truncates the value to an integer though, so if you turn `0.015` to an integer, it will be zero. Instead, your assert should say `assert(interval > 0.);`

no it will no real types has higher type rank then any integer type, so it 0 will be converted to real type rather

**Comment by jagannatharjun** [comment]
Well anyway, I think I found the culprit, I'll let it run for some time though, thanks for your time,

**Comment by arvidn** [comment]
ah, right, of course.

I think the proper solution is not just to "round-up" 0ms to 1ms, but also ensure `post_session_stats()` isn't called that often

**Comment by arvidn** [comment]
@jagannatharjun do you feel confident that there is no issue in libtorrent regarding this? can this ticket be closed?
