### ISSUE TITLE
Crash when using WebTorrent

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#4899]
libtorrent: `master`
platform/architecture: Android arm64
compiler: clang 9.0.8

When using a WebTorrent transfer, in just under a minute this crash happens
```
A/libc: FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7961d1dc20)
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) 
```
I compiled with all the variants trying to get the stacktrace/backtrace and nothing. I looked around and only `libjuice` seems to use pthread explicitly, and finally, compiled with no WebTorrent, and no crash, everything seems to work fine.

@arvidn @paullouisageneau, I don't mind moving the issue and discussion to `libdatachannel` if it's more appropriate, I also can troubleshoot, but I need some guidance.

**Comment by arvidn** [comment]
If you run under a debugger, or enable coredumps and load it up in a debugger after the crash, you should be able to get a stack trace. You may want to build with `-fno-omit-frame-pointer`.

I'm pretty sure most implementations of `std::mutex` also use `pthread_mutex` under the hood, and this would point to a life-time issue, where a mutex is used after it's been destroyed.

**Comment by paullouisageneau** [comment]
`libjuice` is actually a likely culprit because it'll fallback to mutexes if C11 atomics are not available (they might not be here), which could trigger such a bug. Did you use openssl for crypto?

**Comment by aldenml** [comment]
Yes, I’m using openssl. Do you think that using nettle can improve the situation?

**Comment by aldenml** [comment]
and what about nice? (but I fear the big binary size)

**Comment by paullouisageneau** [comment]
I was asking just to try to narrow down the source of the issue. Did you have any luck getting a stack trace? Did you try with `ndk-stack`?

**Comment by aldenml** [comment]
Nope, nothing, I will start hardcoding some (stack unwind related) flags in the inner CMakeFiles to see if that helps. Btw, I just checked and atomics seems to be present, at least `__STDC_NO_ATOMICS__` is not defined.

**Comment by paullouisageneau** [comment]
A bit of a wild guess, but could you please try with this mitigation: https://github.com/paullouisageneau/libdatachannel/pull/133 ?

**Comment by aldenml** [comment]
@paullouisageneau good news!! With that branch in `libdatachannel` I have no errors and no crash for a while now


![Screenshot_20200724-143555](https://user-images.githubusercontent.com/143813/88425007-a2607e80-cdbc-11ea-8ca4-74ba525deaaa.png)
![Screenshot_20200724-143831](https://user-images.githubusercontent.com/143813/88425015-a4c2d880-cdbc-11ea-8537-8b2641ccb836.png)

**Comment by paullouisageneau** [comment]
Excellent!! I knew adding that check to only one of the callbacks seemed fishy :smile:

**Comment by aldenml** [comment]
Fixed with https://github.com/arvidn/libtorrent/pull/4907
