### ISSUE TITLE
question regarding proxies

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4903]
**Please provide the following information**

libtorrent version (or branch):
RC_1_2

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Since this PR https://github.com/arvidn/libtorrent/pull/4498 got merged, does these settings mean anything anymore?

proxy_hostnames
proxy_peer_connections
proxy_tracker_connections

If not, then they can be safely removed?

**Comment by iamtakingiteasy** [comment]
As per #4904 , PR #4498 in current state may be impeding certain use-cases, which would also benefit from this (or similar) options.

**Comment by arvidn** [comment]
It's true that the patch you link to breaks the use case of only producing trackers. The support for proxies is currently tied pretty strongly to the listen interfaces (and the udp socket specifically).

The issue I was solving with that patch was to avoid having every listen socket open a proxy connection.

Maybe a better way to solve it, and still support the use case of proxying some connections but still accept connections as normal would be to open a separate "listen socket" that represents the proxy, that any proxies connection will go through.

However, I would expect that if all connections are proxied, one would not want to accept connections over the normal IP either.

**Comment by arvidn** [comment]
I think it might make sense to revert #4498. If I make a PR, could someone test it?

**Comment by xavier2k6** [comment]
> I think it might make sense to revert #4498. If I make a PR, could someone test it?

What impact will this make to the users whose issue(s) were resolved with that patch?

ref https://github.com/arvidn/libtorrent/pull/4498#issuecomment-611948864 & does it have any bearing on https://github.com/qbittorrent/qBittorrent/issues/12583?

**Comment by arvidn** [comment]
I'm thinking of not reverting, but amending it to support this use case. I don't think it's as complicated as I thought. The case is where a proxy is configured, but `proxy_connections` is set to false, right?

**Comment by arvidn** [comment]
please test this patch! https://github.com/arvidn/libtorrent/pull/4909

**Comment by xavier2k6** [comment]
@iamtakingiteasy @an0n666 I'll compile a windows x64 build with this patch included later this evening & post it here, can you test & report back then please.

**Comment by iamtakingiteasy** [comment]
@xavier2k6 
Yes, that would be nice, thank you.

**Comment by arvidn** [comment]
I'm eager to pull the trigger on 1.2.8, and this is the last remaining patch I would like to land. It would be especially nice to have some affirmative tests first!

**Comment by xavier2k6** [comment]
> I'm eager to pull the trigger on 1.2.8, and this is the last remaining patch I would like to land. It would be especially nice to have some affirmative tests first!

@arvidn @iamtakingiteasy @an0n666 apologies - only getting around to compiling now.

**Comment by iamtakingiteasy** [comment]
Can confirm it is working as expected: trackers are contacted via proxy, while peer connections, DHT and UPNP are all unaffected.

**Comment by arvidn** [comment]
thanks for making a test build and testing!
