### ISSUE TITLE
State isn't updated when torrent goes into "moving files" state

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#4906]
libtorrent version (or branch): latest RC_1_2
platform/architecture: Windows 10 64 bit
compiler and compiler version: MinGW 8.1

When torrent goes into "moving files" state no updated `torrent_status` is included in `state_update_alert` unless some other status members are changed (e.g. when torrent is paused).

**Comment by arvidn** [comment]
Moving files isn't a state (it's not in the enum). It's just a mode where disk I/O is temporarily stalled.

**Comment by glassez** [comment]
But "moving files" is member of torrent_status structure... I supposed state_update_alert contains all torrents that have changed torrent_status since last call to post_torrent_updates.
