### ISSUE TITLE
supporting BittorrentV2 scrapes

### ISSUE THREAD

**Issue by arvidn** [arvidn/libtorrent#4914]
libtorrent version (or branch): RC_2_0

The V2 protocol, using SHA-256 info-hashes, is not supported by tracker scrapes. In [BEP48](http://bittorrent.org/beps/bep_0048.html), info-hashes are assumed to be 20 bytes.

It seems straight-forward to extend BEP48 to specify that an info-hash can be either 20 or 32 bytes, to support V2 torrents. IT should probably also be made clear whether truncated SHA-256 info hashes should be used. Perhaps the most consistent approach would be to mandate that scrape info-hashes be truncated SHA-256 info-hashes.

@ssiloti do you have any thoughts on this?

The relevant parts of libtorrent is `parse_tracker_response()`, which takes a `sha1_hash` for info-hash. But I guess all announces use truncated hashes for v2.

perhaps this is a non-issue.

**Comment by ssiloti** [comment]
Scrape should do what announces do: use truncated SHA-256.
