### ISSUE TITLE
Feature Request: tracker exchange

### ISSUE THREAD

**Issue by zero77** [arvidn/libtorrent#4917]
Can you please implement tracker exchange, as this could help to find more peers and seeds and ultimately speed up torrenting, thanks.

Description
http://bittorrent.org/beps/bep_0028.html

**Comment by arvidn** [comment]
libtorrent used to support tracker exchange (you may have noticed I wrote that BEP). It was abandoned and support was removed. That feature has a lot of problems.

Here are some references. If you decide to do some research on the topic and find more or better references, feel free to post them here for the record:

https://github.com/hamedramzi/libtorrent/issues/726
https://sourceforge.net/p/libtorrent/mailman/message/35592064/

**Comment by zero77** [comment]
Thanks, i will have a look through and if i find anything of note, i will post it hear.

> (you may have noticed I wrote that BEP)

I didn't spot that
