### ISSUE TITLE
request feature: Swarm Merging

### ISSUE THREAD

**Issue by cocokola** [arvidn/libtorrent#4936]
as per qbittorrent, they said to post the request for swarm merging to this development. see following paste:
 
Sometimes there are multiple torrents of the same data but the availability is low or incomplete and it would be nice to merge torrents.
In vuze the is something like swarm merging:
https://wiki.vuze.com/w/Swarm_Merging

It is possible to implement this too in qbittorrent?

Keep up the good work!

**Please provide the following information**

libtorrent version (or branch):

platform/architecture:

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

**Comment by arvidn** [comment]
previous ticket: https://github.com/arvidn/libtorrent/issues/829

**Comment by xavier2k6** [comment]
@arvidn as a suggestion, perhaps labeling this as **"enhancement"**/**"help wanted"** & **"pinning"** it would garner more exposure from others who may be interested or indeed be in a position to make a "PR" to introduce this "feature request".

**Comment by cocokola** [comment]
guess that is one way to lower the workload ;)   it would be nice to have IMHO, but not critical.

**Comment by allanlaal** [comment]
## use case: 

I read alot. like alot!
I use LazyLibrarian to constantly search for and download ebooks/abooks from my Goodreads' "To Read" list with Jackett from a massive list of public trackers. LazyLibrarian then queues them in a torrent client (currently qbittorrent) 
I'd like the torrent client (qbittorrent) to be able to swarm merge those torrents as usually trackers might duplicate a torrent by adding their own "tracked by xxx" text files & other trash.
in addition most (like 80%) of book torrents have little to no seeds or if they are seeded, they are slooooooow af, so thats an obvious use case for swarm merge

**Comment by zero77** [comment]
@allanlaal
Completely agree but, I think swarm merging will be more feasible with the wider adoption of BitTorrent v2 and hybrid torrents.

https://blog.libtorrent.org/2020/09/bittorrent-v2
https://torrentfreak.com/libtorrent-adds-support-for-bittorrent-v2-a-potential-game-changer-200912

**Comment by allanlaal** [comment]
unstaling

**Comment by allanlaal** [comment]
unstaling

**Comment by zero77** [comment]
Unresolved

**Comment by TheBestPessimist** [comment]
Should not be closed imo. Also, the stale not should have a tag "don't mark this as stalled", which will stop the "not stale" nose

**Comment by allanlaal** [comment]
vote here: https://github.com/arvidn/libtorrent/issues/6797

**Comment by master255** [comment]
Your feature request is still open in my issue:
https://github.com/arvidn/libtorrent/issues/6578

**Comment by master255** [comment]
@cocokola @allanlaal @TheBestPessimist I was able to teach libtorrent to load data from another torrent. I used https torrents for that. My free Android app Media Library (based on libtorrent 1.2.13) supports swarm merging. Enjoy!

**Comment by cocokola** [comment]
You folks are the bomb!    Impressive work overall.   Thank you!

**Comment by allanlaal** [comment]
@arvidn could you reopen this issue - its kind of an important feature imho :D

**Comment by iopq** [comment]
I would like this. I thought it wasn't going to be added because it is marked as closed, but now I see the stalebot closed it and "Closed" is not quite accurate

**Comment by arvidn** [comment]
the reason the swarm merging feature hasn't been implemented is not because this issue was inactive and closed by the stale bot. The reason it hasn't been implemented is because nobody has volunteered to do it.

**Comment by allanlaal** [comment]
unstale!

@arvidn kill all stale bots! ;)


we still care about this feature, but things of this complexity take time in OpenSource

**Comment by arvidn** [comment]
a ticket being stale and closed is not a sign of people not caring. It's a sign of work not being done. Keeping tickets open does not make it any more likely for work to be done.

**Comment by arvidn** [comment]
> I quite disagree with that. People looking for what could they generally improve upon wont check closed issues

I don't think those people exist. Contributors either have a feature they need or want for their project, or they have users requesting a feature, or they solicit feedback or requests from some group of people.

**Comment by iopq** [comment]
The default in Github is open issues, so when you search and find nothing, it seems like nobody else wants it

**Comment by mpeter50** [comment]
> I don't think those people exist. Contributors either have a feature they need or want for their project, or they have users requesting a feature,

You may be right, I don't actually know who are the contributors in this project. 

> or they solicit feedback or requests from some group of people

I think that includes the issue tracker of the project, though. Where else is it a better place to search for good new feature ideas? Suggestions are naturally appearing at that place.

Whatever is the chance that someone would start working on this feature by finding this issue, I think its significantly lower if the issue is closed. All the while the chance of users opening duplicates is higher. When I'm opening an issue, be it a feature request or a bug report at any repository, I only search in the (usually much fewer) open issues, and when it seems useful then also in the first page of closed issues, but I never go through all of those. In the case of this project, there are only 105 open issues, but 1900 closed ones. Rarely I did go through all of the closed issue search results, for example on the Gitea repo, but most often it took a hour or more to do that.

**Comment by master255** [comment]
I finished downloading a torrent from another torrent. It's been a while. Maybe this will help you somehow https://github.com/arvidn/libtorrent/issues/6578#issuecomment-1493174000

And read all the duplicate issues (check for updates) you create.
