### ISSUE TITLE
Wrong port being announced in a multi WAN setup as a load balancer

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4946]
**Please provide the following information**

libtorrent version (or branch):
1.2.6
platform/architecture:
Windows 10
compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

This issue is being experienced by another user. 
The user has two WANs setup as a load balancer in their router. 

They basically have two different networks with two different static public IPs. 

The port set in qbit is 55357

But one of the IP is announcing with port 55358
And another one with 55357

From the logs, I can see there’s success message from NAT-PMP for both of these ports..but no listen success alerts for port 55358. Now if NAT-PMP returns a different port, shouldn’t it be used by both the addresses during announce?
The tracker is seeing two announces from two different IP but different ports. It’s not counting the stats properly because of different ports. It thinks they’re different peers. 

(I) 2020-08-05T17:53:49 - Trying to listen on: 0.0.0.0:55357,[::]:55357
(I) 2020-08-05T17:53:49 - DHT support [ON]
(I) 2020-08-05T17:53:49 - Local Peer Discovery support [ON]
(I) 2020-08-05T17:53:49 - PeX support [ON]
(I) 2020-08-05T17:53:49 - Anonymous mode [OFF]
(I) 2020-08-05T17:53:49 - Encryption support [ON]
(I) 2020-08-05T17:53:49 - UPnP / NAT-PMP support [ON]
(N) 2020-08-05T17:53:49 - Options were saved successfully.
(I) 2020-08-05T17:53:49 - Successfully listening on IP: 192.168.1.11, port: TCP/55357
(I) 2020-08-05T17:53:49 - Successfully listening on IP: 192.168.1.11, port: UDP/55357
(I) 2020-08-05T17:53:49 - Successfully listening on IP: 127.0.0.1, port: TCP/55357
(I) 2020-08-05T17:53:49 - Successfully listening on IP: 127.0.0.1, port: UDP/55357
(I) 2020-08-05T17:53:49 - Successfully listening on IP: ::1, port: TCP/55357
(I) 2020-08-05T17:53:49 - Successfully listening on IP: ::1, port: UDP/55357
(I) 2020-08-05T17:53:49 - UPnP/NAT-PMP: Port mapping successful, message: successfully mapped port using NAT-PMP. external port: TCP/55357
(I) 2020-08-05T17:53:49 - UPnP/NAT-PMP: Port mapping successful, message: successfully mapped port using NAT-PMP. external port: UDP/55357
(I) 2020-08-05T17:53:49 - UPnP/NAT-PMP: Port mapping successful, message: successfully mapped port using UPnP. external port: TCP/55357
(I) 2020-08-05T17:53:49 - UPnP/NAT-PMP: Port mapping successful, message: successfully mapped port using UPnP. external port: UDP/55357
(I) 2020-08-05T17:53:59 - Successfully listening on IP: 192.168.1.134, port: TCP/55357
(I) 2020-08-05T17:53:59 - Successfully listening on IP: 192.168.1.134, port: UDP/55357
(I) 2020-08-05T17:53:59 - Successfully listening on IP: 192.168.1.11, port: TCP/55357
(I) 2020-08-05T17:53:59 - Successfully listening on IP: 192.168.1.11, port: UDP/55357
(I) 2020-08-05T17:53:59 - Successfully listening on IP: fe80::697e:89fa:1905:3f6d%30, port: TCP/55357
(I) 2020-08-05T17:53:59 - Successfully listening on IP: fe80::697e:89fa:1905:3f6d%30, port: UDP/55357
(I) 2020-08-05T17:53:59 - UPnP/NAT-PMP: Port mapping successful, message: successfully mapped port using NAT-PMP. external port: TCP/55357
(I) 2020-08-05T17:53:59 - UPnP/NAT-PMP: Port mapping successful, message: successfully mapped port using NAT-PMP. external port: TCP/55358
(I) 2020-08-05T17:53:59 - UPnP/NAT-PMP: Port mapping successful, message: successfully mapped port using NAT-PMP. external port: UDP/55357
(C) 2020-08-05T17:53:59 - UPnP/NAT-PMP: Port mapping failure, message: could not map port using UPnP: unknown UPnP error (-1)
(I) 2020-08-05T17:53:59 - UPnP/NAT-PMP: Port mapping successful, message: successfully mapped port using NAT-PMP. external port: UDP/55358
(C) 2020-08-05T17:53:59 - UPnP/NAT-PMP: Port mapping failure, message: could not map port using UPnP: unknown UPnP error (-1)
(I) 2020-08-05T17:53:59 - UPnP/NAT-PMP: Port mapping successful, message: successfully mapped port using UPnP. external port: TCP/55357
(I) 2020-08-05T17:53:59 - UPnP/NAT-PMP: Port mapping successful, message: successfully mapped port using UPnP. external port: UDP/55357
(I) 2020-08-05T17:54:02 - Detected external IP: ip1(censored)
(I) 2020-08-05T17:54:06 - Detected external IP: ip2(censored)

**Comment by ssiloti** [comment]
I don't think there's anything libtorrent can do about this. NAT-PMP requires a separate mapping for each local address. The client has to use the external address/port pairs it is given by the router in the announce since those are what will be forwarded to the client.

Libtorrent doesn't listen locally on external ports received from the router. The router maps the external port (55358) to the internal port (55357) so libtorrent never sees traffic on the external port.

**Comment by an0n666** [comment]
Thanks for the explanation.

I just wanted to confirm one thing:

Is this an issue with NAT-PMP specifically? I mean using UPnP only would solve the issue?

Also is it expected to map ports using both UPnP and NAT-PMP at the same time?

Shouldn't it be like this->
Try UPnP -> UPnP failed -> Try NAT-PMP

**Comment by ssiloti** [comment]
I'm not as familiar with uPnP, but I doubt it works any different in this situation. Usually both uPnP and NAT-PMP are handled by the same service in the router (miniupnpd) which can recognize and merge identical mapping requests from each protocol.
