### ISSUE TITLE
Crashed with SIGSEGV in malloc_consolidate()

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#495]
I am forwarding a bug from launchpad which has been reported recently by another user. The only details are those in the two bug reports but I hope this is enough to potential fix the issue.

https://bugs.launchpad.net/ubuntu/+source/libtorrent-rasterbar/+bug/1232446
https://bugs.launchpad.net/ubuntu/+source/deluge/+bug/1548438

**Comment by Falcosc** [comment]
One of them is on api version 7 (0.16.x) and the other on version 8 (1.0.x)

**Comment by cas--** [comment]
Old version closing
