### ISSUE TITLE
CMake 3.18 cannot configure

### ISSUE THREAD

**Issue by adriaandegroot** [arvidn/libtorrent#4956]
With CMake 3.18, libtorrent fails to configure:

```
CMake Error at cmake/Modules/GeneratePkgConfig.cmake:181 (file):
  Error evaluating generator expression:

    $<COMPILE_LANG_AND_ID:CUDA,NVIDIA>

  $<COMPILE_LANG_AND_ID:lang,id> may only be used with binary targets to
  specify include directories, compile definitions, and compile options.  It
  may not be used with the add_custom_command, add_custom_target, or
  file(GENERATE) commands.
Call Stack (most recent call first):
  CMakeLists.txt:747 (generate_and_install_pkg_config_file)
```

(on FreeBSD at least, but this looks like a generic CMake problem). There's an upstream report from me at https://gitlab.kitware.com/cmake/cmake/-/issues/21074 and a related report in a different project at https://github.com/facebook/folly/issues/1414

**Comment by arvidn** [comment]
@zeule FYI. Is it the fact that the pkg-config is used on an install rule maybe? (i.e. not a binary rule). It seems far fetched though

**Comment by adriaandegroot** [comment]
It's a CMake issue AFAICT: the interface_compile_options changed and now put other generators in there.

**Comment by adriaandegroot** [comment]
```
--- cmake/Modules/GeneratePkgConfig.cmake.orig  2020-08-09 10:43:19 UTC
+++ cmake/Modules/GeneratePkgConfig.cmake
@@ -171,6 +171,11 @@ function(generate_and_install_pkg_config_file _target 
        set(_pkg_config_file_template_filename "${_GeneratePkGConfigDir}/pkg-config.cmake.in")
 
        # put target and project properties into a file
+       # Avoid things in the CFLAGS -- which can come from INTERFACE_OPTIONS
+       # of dependencies -- that don't work with file(GENERATE). CMake bug 21074
+       string(REPLACE "<COMPILE_LANG_AND_ID:CUDA,NVIDIA>" "<COMPILE_LANGUAGE:CUDA>" _s "${_interface_compile_options}")
+       set(_interface_compile_options "${_s}")
+
        configure_file("${_GeneratePkGConfigDir}/target-compile-settings.cmake.in"
                "${_generate_target_dir}/compile-settings.cmake" @ONLY)
```

This is what I added to packaging, to restore the interface options back to what CMake 3.17 would have made of them. See the CMake issue for details.

**Comment by zeule** [comment]
Just build it with 3.18.1 on Linux and can't reproduce the problem. Don't understand yet why it compiles here...

**Comment by tambry** [comment]
CMake contributor here who indirectly introduced a feature causing another change by someone else, which caused this issue. CMake hasn't and will not guarantee stability and presence or lack there of generator expressions on targets from builtin find modules. CMake doesn't consider this a regression.

The workaround by @adriaandegroot is sensible. However, this seems like a valid usecase with no general solution possible in CMake. As a result, I [added the `TARGET` argument](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5131) to `file(GENERATE)` in CMake 3.19. This will allow specifying a target for the generation command, allowing resolution of target-dependent generator expressions as is the case here.  
Feel free to ping me if you require help making use of this.

Aside, the reproducability of this issue depends on whether `FindThreads` adds the generator expression to `Threads::Threads`, which is dependent on whether the compiler supports `-pthread`.

**Comment by arvidn** [comment]
@tambry thanks for your comment. It sound like I should land @adriaandegroot's patch.

@adriaandegroot You're seeing this in libtorrent-1.2.x, is that right?

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/5062
