### ISSUE TITLE
Crashed with SIGSEGV in std::_Rb_tree_rebalance_for_erase()

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#496]
Forwarding another bug from launchpad which has been reported recently by another user. The only details are those in the two bug reports but I hope this is enough to fix the issue.

https://bugs.launchpad.net/ubuntu/+source/deluge/+bug/1208213
https://bugs.launchpad.net/ubuntu/+source/deluge/+bug/1546691

**Comment by Falcosc** [comment]
@arvidn could be merged with https://github.com/arvidn/libtorrent/issues/495

**Comment by cas--** [comment]
Old version closing
