### ISSUE TITLE
cmake build issues RC2

### ISSUE THREAD

**Issue by bdekoz** [arvidn/libtorrent#4963]
**Please provide the following information**

libtorrent version (or branch):
RC 2 tar.gz file

platform/architecture:

fedora 32/x86-64/linux

compiler and compiler version:

g++ (GCC) 10.2.1
boost-1.69

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

- missing 'cmake/Modules/LibtorrentMacros.cmake'
- missing 'binding/CMakeLists.tx'

copying in these files from 1.2.8 release allows configure

otherwise get errors when configuring cmake:

CMake Error at CMakeLists.txt:812 (add_subdirectory):
  The source directory

    /home/bkoz/src/libtorrent-rasterbar-2.0.0/bindings

  does not contain a CMakeLists.txt file.

End with successful config:

%cmake -DCMAKE_INSTALL_PREFIX=/home/bkoz/bin/H-libtorrent-2.0.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -Dbuild_tests=ON -G Ninja ..
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Compiler default is C++14
-- Building in C++17 mode
-- Performing Test Iconv_IS_BUILT_IN
-- Performing Test Iconv_IS_BUILT_IN - Success
-- Found Iconv: /usr/lib64/libc.so  
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.1.1g")  
-- Found Boost: /usr/include (found version "1.69.0") found components: system 
-- Performing Test _WNO_ERROR_FORMAT_TRUNCATION
-- Performing Test _WNO_ERROR_FORMAT_TRUNCATION - Success
-- The following features have been enabled:

 * BUILD_SHARED_LIBS, build libtorrent as a shared library
 * build_tests, build tests
 * dht, enable support for Mainline DHT
 * encryption, Enables encryption in libtorrent
 * exceptions, build with exception support
 * extensions, Enables protocol extensions
 * i2p, build with I2P support
 * logging, build with logging
 * mutable-torrents, Enables mutable torrent support
 * streaming, Enables support for piece deadline

-- The following RECOMMENDED packages have been found:

 * Iconv, GNU encoding conversion library, <https://www.gnu.org/software/libiconv/>
   Convert strings between various encodings
 * OpenSSL, Full-strength general purpose cryptography library, <https://www.openssl.org/>
   Provides HTTPS support to libtorrent

-- The following REQUIRED packages have been found:

 * Threads
 * Boost

-- The following features have been disabled:

 * static_runtime, build libtorrent with static runtime
 * build_examples, build examples
 * build_tools, build tools
 * python-bindings, build python bindings
 * gnutls, build using GnuTLS instead of OpenSSL

-- Configuring done
-- Generating done
-- Build files have been written to: /home/bkoz/src/libtorrent-rasterbar-2.0.0/build

---

build is fine, but must be installed manually as 

cmake --install ..

from the nested build directory fails

---

This is the first of the 2x series I've been able to build and then link with. testing now...

**Comment by arvidn** [comment]
>     missing 'cmake/Modules/LibtorrentMacros.cmake'
>     missing 'binding/CMakeLists.tx'

I don't see these files as missing. They are included when building the tabrball [here](https://github.com/arvidn/libtorrent/blob/RC_2_0/Makefile#L187) and [here](https://github.com/arvidn/libtorrent/blob/RC_2_0/Makefile#L182).

> build is fine, but must be installed manually as
> 
> cmake --install ..
> 
> from the nested build directory fails

Can you specify exactly which commands you ran? trying to repoduce I did this:

```
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/home/arvid/bin/H-libtorrent-2.0.0 -DCMAKE_BUILD_TYPE=Release -GNinja ..
cmake --install ..
```

I that command does not fail, but prints these warnings:

```CMake Warning (dev) at /home/arvid/dev/2/libtorrent/torrent-rasterbar-pkgconfig/compile-settings-expanded.cmake:3 (set):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    ';@CMAKE_INSTALL_PREFIX@/include'

  the old evaluation rules produce:

    ';/home/arvid/bin/H-libtorrent-2.0.0/include'

  but the new evaluation rules produce:

    ';@CMAKE_INSTALL_PREFIX@/include'

  Using the old result for compatibility since the policy is not set.
Call Stack (most recent call first):
  /home/arvid/dev/2/libtorrent/torrent-rasterbar-pkgconfig/generate-pkg-config.cmake:1 (include)
  /home/arvid/dev/2/libtorrent/cmake_install.cmake:41 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /home/arvid/dev/2/libtorrent/torrent-rasterbar-pkgconfig/generate-pkg-config.cmake:29 (list):
  Policy CMP0007 is not set: list command no longer ignores empty elements.
  Run "cmake --help-policy CMP0007" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.  List has value =
  [/home/arvid/bin/H-libtorrent-2.0.0/lib;;/usr/lib/x86_64-linux-gnu;/usr/lib/x86_64-linux-gnu;/usr/lib/x86_64-linux-gnu].
Call Stack (most recent call first):
  /home/arvid/dev/2/libtorrent/torrent-rasterbar-pkgconfig/generate-pkg-config.cmake:36 (split_library_dirs)
  /home/arvid/dev/2/libtorrent/cmake_install.cmake:41 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /home/arvid/dev/2/libtorrent/torrent-rasterbar-pkgconfig/generate-pkg-config.cmake:5 (list):
  Policy CMP0007 is not set: list command no longer ignores empty elements.
  Run "cmake --help-policy CMP0007" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.  List has value =
  [TORRENT_LINKING_SHARED;;BOOST_ASIO_ENABLE_CANCELIO;BOOST_ASIO_NO_DEPRECATED;TORRENT_USE_ICONV;TORRENT_USE_OPENSSL;TORRENT_USE_LIBCRYPTO;TORRENT_SSL_PEERS;OPENSSL_NO_SSL2;BOOST_SYSTEM_DYN_LINK;BOOST_ALL_NO_LIB].
Call Stack (most recent call first):
  /home/arvid/dev/2/libtorrent/torrent-rasterbar-pkgconfig/generate-pkg-config.cmake:46 (cmake_list_to_pkg_config)
  /home/arvid/dev/2/libtorrent/cmake_install.cmake:41 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /home/arvid/dev/2/libtorrent/torrent-rasterbar-pkgconfig/generate-pkg-config.cmake:5 (list):
  Policy CMP0007 is not set: list command no longer ignores empty elements.
  Run "cmake --help-policy CMP0007" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.  List has value =
  [;/home/arvid/bin/H-libtorrent-2.0.0/include].
Call Stack (most recent call first):
  /home/arvid/dev/2/libtorrent/torrent-rasterbar-pkgconfig/generate-pkg-config.cmake:47 (cmake_list_to_pkg_config)
  /home/arvid/dev/2/libtorrent/cmake_install.cmake:41 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by bdekoz** [comment]
> > ```
> > missing 'cmake/Modules/LibtorrentMacros.cmake'
> > missing 'binding/CMakeLists.tx'
> > ```
> 
> 
> I don't see these files as missing. They are included when building the tabrball [here](https://github.com/arvidn/libtorrent/blob/RC_2_0/Makefile#L187) and [here](https://github.com/arvidn/libtorrent/blob/RC_2_0/Makefile#L182).

yet missing from the tarball. Look here: 
https://github.com/arvidn/libtorrent/releases/download/libtorrent-2.0-RC2/libtorrent-rasterbar-2.0.0-RC2.tar.gz

**Comment by arvidn** [comment]
ah, I see. I fixed this after I posted RC2

**Comment by bdekoz** [comment]
cool! thanks.

And then, for build I use

mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/home/bkoz/bin/H-libtorrent-2.0.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -Dbuild_tests=ON -G Ninja ..

ninja -j16

ctest

cmake --install .. 

-------------------------------

building is fine
testing is fine

install has:

%cmake --install ..
CMake Error: Error processing file: /home/bkoz/src/libtorrent-rasterbar-2.0.0/cmake_install.cmake

**Comment by arvidn** [comment]
I tested this and it worked in the RC3 I just cut

**Comment by bdekoz** [comment]
great will try RC3 this weekend and confirm

**Comment by bdekoz** [comment]
Ok, looking good on configure and build without any modification, still one install nit:

%cmake --install ..
CMake Error: Error processing file: /home/bkoz/src/libtorrent-rasterbar-2.0.0-RC.3/cmake_install.cmake

but this is user error! Sorry.


%cmake --install .

totally fine. I'll run this software linked to this binary in production this weekend
