### ISSUE TITLE
latest build error: undefined symbol: _ZN10libtorrent16read_resume_dataEPKciRN5boost6system10error_codeE

### ISSUE THREAD

**Issue by lethanhviet** [arvidn/libtorrent#497]
When trying to build libtorrent for deluge:
# python -c "import libtorrent; print libtorrent.version"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/local/lib/libtorrent-rasterbar.so.9: undefined symbol: _ZN10libtorrent16read_resume_dataEPKciRN5boost6system10error_codeE

**Comment by arvidn** [comment]
It looks like perhaps you're mixing a python binding from head of master with an older version of libtorrent (that does not have the read_resume_data() function in the API). Did you build libtorrent from source?
are you confident the freshly built library made it to /usr/local/lib ?

**Comment by lethanhviet** [comment]
Hi,

I checkout the latest build from here. I also did try to rebuild libtorrent using the file from latest commit 2fd80473089f0e87f98ea466177d227e2ce07f2a but still same error. Everything is in /usr/local/lib as supposed I believe.
# ls -l /usr/local/lib
total 292388
-rw-r--r-- 1 root staff 220515608 Feb 25 15:13 libtorrent-rasterbar.a
-rwxr-xr-x 1 root staff      1096 Feb 25 15:13 libtorrent-rasterbar.la
lrwxrwxrwx 1 root staff        29 Feb 25 15:13 libtorrent-rasterbar.so -> libtorrent-rasterbar.so.9.0.0
lrwxrwxrwx 1 root staff        29 Feb 25 15:13 libtorrent-rasterbar.so.9 -> libtorrent-rasterbar.so.9.0.0
-rwxr-xr-x 1 root staff  78874208 Feb 25 15:13 libtorrent-rasterbar.so.9.0.0
drwxr-sr-x 2 root staff      4096 Feb 25 15:13 pkgconfig
drwxrwsr-x 4 root staff      4096 Feb 25 15:13 python2.7
-rw------- 1 root staff         0 Feb 23 13:49 stJYpXbe
-rw------- 1 root staff         0 Feb 23 01:52 styhNbkk
-rw------- 1 root staff         0 Feb 25 14:42 styLFYdU

**Comment by arvidn** [comment]
fixed in master now
