### ISSUE TITLE
Downloading torrent isn’t rechecked on unclean shutdown 

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#4974]
**Please provide the following information**

libtorrent version (or branch):
RC 1_2

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

If client experiences a crash when downloading a torrent, resume data is not saved. So client loses progress. 

However on next start, libtorrent doesn’t perform a force recheck on the downloading files to re-assess the progress. It accepts whatever old progress the client feeds it. 

Is this a bug in libtorrent or this should be fixed on client side?

One way I can think of is use a flag in downloading torrents which will be set to true if session paused cleanly. In the event of an unclean shutdown this will be false and force recheck will be called.

**Comment by arvidn** [comment]
I assume the `no_recheck_incomplete_resume` setting is unchanged, and left as `false`, right?

libtorrent used to save timestamps of files in the resume data, and force a recheck if they didn't match. However, this turned out to be quite error prone. It would end up checking files for now good reason quite often. Some filesystems have low resolution of timestamps for example.

**Comment by an0n666** [comment]
> I assume the `no_recheck_incomplete_resume` setting is unchanged, and left as `false`, right?
> 

Right. 

> libtorrent used to save timestamps of files in the resume data, and force a recheck if they didn't match. However, this turned out to be quite error prone. It would end up checking files for now good reason quite often. Some filesystems have low resolution of timestamps for example.
>

Why not set a flag that will indicate session was paused properly.

**Comment by arvidn** [comment]
> Why not set a flag that will indicate session was paused properly.

Set a flag where?

**Comment by an0n666** [comment]
I meant a flag which client will write to fastresume when session is paused. So when passing the add torrent params client can let libtorrent know that this torrent requires recheck before resuming download.

**Comment by MassaRoddel** [comment]
IMO, only the client itself can use a flag to signal a clean shutdown. Writing to resumedata could also fail and would indicate wrong shutdown status.
I think such flag needs to be maintained outside of any libtorrent scope. That is what I do in my client. In case the shutdown was not clean - a recheck on all torrents is enforced.
