### ISSUE TITLE
Add ability to store timestamps in torrent file for downloaded files and folders

### ISSUE THREAD

**Issue by Directp2pinfinity** [arvidn/libtorrent#4976]
# libtorrent version (or branch)
libtorrent4j-1.3.0

https://gitlab.com/proninyaroslav/libretorrent/-/tree/libtorrent4j-1.3.0/app/src/main/java/org/proninyaroslav/libretorrent/core/system

https://github.com/aldenml/libtorrent4j

LibreTorrent 2.1 app

https://gitlab.com/proninyaroslav/libretorrent/-/releases/2.1

# platform/architecture
Android 10/arm64-v8a

# Device & Android version

- Huawei Mate 30 Pro
- Android 10 (Stock ROM, no root)

# Summary
It would be nice if the downloaded files and folders had exactly the same timestamp (creation time and modified time) as the source, instead of the current date/time of the completed download.

# Steps to reproduce

1. Create a torrent file on the first Android 10 device with LibreTorrent and add a folder with a video file. This folder and the video file have a timestamp (modified time) 4 Aug 2020 3:16:12 pm.

2. Start seeding
3. Send the torrent file to a second Android 10 device e.g. via Wi-Fi Direct
4. Open the torrent file in LibreTorrent app on the second Android 10 device and download it.
5. When the download is complete. On the second Android 10 device, open the folder and video file in the default file manager.
6. The folder and the video file has been set to the current time, e.g. 11 Aug 2020 6:29:22 pm (modified time)

# Additional information

Here are some suggestions from a torrent client application developer how this can be solved.

https://gitlab.com/proninyaroslav/libretorrent/-/issues/302#note_394284334

https://gitlab.com/proninyaroslav/libretorrent/-/issues/302#note_394301041

https://gitlab.com/proninyaroslav/libretorrent/-/issues/302#note_394357557

It is best to read the full report from the perspective of the user and practical experience. There are additional details because of Android 10 system which currently only shows modified time in default file manager.

There are already Linux distributions (e.g. Linux Mint Cinnamon) which show modified time, creation time and access time by default in the default file manager.

https://gitlab.com/proninyaroslav/libretorrent/-/issues/302

**Comment by proninyaroslav** [comment]
@arvidn 
Can you comment on this situation?

**Comment by arvidn** [comment]
sorry, I don't think I received a notification for this ticket when it was created.

I agree, this would be a nice feature. There is a field that's recognized by libtorrent called `mtime` which is interpreted as the posix-time modification time for the file. It's parsed in `torrent_info` and stored in `file_storage` (if present). The functionality to create a torrent in libtorrent supports a flag `create_torrent::modification_time`, to include the modification time of files in the generated .torrent file.

So, I made this addition: https://github.com/arvidn/libtorrent/pull/5127

The thing that's missing is the last bit to actually *set* the mtime of the downloaded file once it's downloaded.

**Comment by opw-art** [comment]
@arvidn 
Is it also possible to support more timestamps in libtorrent if the filesystem supports it.

Here is a list of what I mean.
https://wiki.sleuthkit.org/index.php?title=Mactime_output

An example is NTFS and EXT4 which support not only mtime (modification time).

But also atime (access time), ctime (change time) and btime (birth time).

Can you add it?

**Comment by arvidn** [comment]
I'm open to support other timestamps too, but it's not very high up on my list, but patches are welcome!
It would probably be a good idea to support mtime fully first though, but also *setting* the timestamp on downloaded files.

**Comment by Chavahtem** [comment]
@arvidn 
such a request was made a few years ago in bittorent forum
https://forum.bittorrent.com/topic/38648-timestamps-for-downloaded-files/

The advantage is I can provide my created files with the same timestamp as my original files.

**Comment by arvidn** [comment]
@Chavahtem this feature request has already been implemented. You can find the patch further up the thread.

**Comment by Chavahtem** [comment]
@arvidn 
ok, but there seems to be only 1 timestamp supported, modification date. And it seems to only work for files.

Are the other timestamps "created date" also supported + directory? I use Windows 10 and see in Windows File Explorer created date in the column and file or folder info.

**Comment by arvidn** [comment]
right. only modification time (`mtime`) is supported, and only for files. Directories would be a bit tricky because they are not first-class in torrent files. Directories are implied by the files.

The feature I was thinking of also only implements the subject of this thread, it includes mtime in .torrent files. There's still no feature to *set* the mtime of the files being created when downloading.

**Comment by Chavahtem** [comment]
@arvidn 

Ok I have read through the thread. 

This point is completed:

- [x] modification time (`mtime`) is supported

These points are missing according to the thread

- [ ] set the mtime of the files being created when downloading

- [ ] support more timestamps like "creation date"

- [ ] store timestamp of directories

It would be very good if these points are supported.

**Comment by arvidn** [comment]
The last bullet (directory timestamps) would need some novel research. Ideally anchored with people at BitTorrent.org

I suppose the other timestamps field ought to be documented in a BEP as well.

**Comment by Chavahtem** [comment]
> The last bullet (directory timestamps) would need some novel research. Ideally anchored with people at BitTorrent.org
> 
Oh, that's a good idea, maybe the BitTorrent developers will help.

> I suppose the other timestamps field ought to be documented in a BEP as well.
Exactly also the other timestamps field documented. Thanks.

**Comment by arvidn** [comment]
@Chavahtem what is you use case for these timestamps?

**Comment by Chavahtem** [comment]
> @Chavahtem what is you use case for these timestamps?

I would like to share my files and directories original with timestamp. Therefore find good if it can be supported.

I would say I am looking for the similar experience as otherwise only from local copying of files and directories to a USB backup hard drive.

**Comment by 1024mb** [comment]
I would like to also request more timestamp support. This is useful for archiving purposes. Thanks.

**Comment by 1024mb** [comment]
Was this implemented? I don't see any option about it.

**Comment by arvidn** [comment]
it was implemented in torrent creation. The mtime fields are not used when downloading to set the mtime of the files on disk to the times in the .torrent file however. That seems like a slightly more intrusive change that probably would need an option.
