### ISSUE TITLE
test_flags fails intermittently

### ISSUE THREAD

**Issue by lgbaldoni** [arvidn/libtorrent#4985]
**Please provide the following information**

> libtorrent version (or branch):

RC_2_0 
> platform/architecture:

i586 and armv7l

> compiler and compiler version:

gcc 10.1

> please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Build the package with on openSUSE Tumbleweed and then run tests with `/usr/bin/ctest --output-on-failure --force-new-ctest-process -j8 --verbose --exclude-regex test_upnp --parallel 1`

Log snippet for [i586](https://github.com/arvidn/libtorrent/files/5072932/libtorrent-rasterbar2-test_flags_i586.txt) and [armv7l](https://github.com/arvidn/libtorrent/files/5072933/libtorrent-rasterbar2-test_flags_armv7l.txt).

**Comment by lgbaldoni** [comment]
Just to say that I saw it failing on x86_64 at least once.

**Comment by arvidn** [comment]
some of the `tests_flags` tests are flaky. I've put some work into making them reliable, but I think at least one is still failing sporadically. As far as I can tell, it doesn't seem tied to the host architecture

**Comment by lgbaldoni** [comment]
> As far as I can tell, it doesn't seem tied to the host architecture

I concur. Do you want me to open another ticket? Just to keep track of a low-priority issue.

**Comment by arvidn** [comment]
I think this ticket is sufficient.
