### ISSUE TITLE
torrent_info::rename_file unable to strip .torrent "name" part

### ISSUE THREAD

**Issue by ajax16384** [arvidn/libtorrent#499]
````c++
		void rename_file(int index, std::string const& new_filename)
		{
			TORRENT_ASSERT(is_loaded());
-			if (m_files.file_name(index) == new_filename) return;
+			if (m_files.file_path(index) == new_filename) return;

````
for non-single file torrent "file_storage::file_name()" always returns string without .torrent "name" part. so any attempt to rename file to same relative name but with striped root part will fail.
file_name->file_path should fix this issue.

**Comment by arvidn** [comment]
which file is that in and which version? I can't find a rename_file() function that looks like that in master, RC_1_1 nor RC_1_0

**Comment by ajax16384** [comment]
https://github.com/arvidn/libtorrent/blob/master/include/libtorrent/torrent_info.hpp#L223
and "file_storage::file_name()" comparision was introduced in ae7058e1198923b85351f4ddf40f3f8e25c71560

**Comment by arvidn** [comment]
fixed here: https://github.com/arvidn/libtorrent/pull/504
