### ISSUE TITLE
Failed to compile 2.0.0 RCx

### ISSUE THREAD

**Issue by LiMinggang** [arvidn/libtorrent#4998]
**Please provide the following information**

libtorrent version (or branch):
2.0.0 RC
platform/architecture:
Windows
compiler and compiler version:
VS
please describe what symptom you see, what you would expect to see instead and
how to reproduce it
cmake failed. I had to copy LibtorrentMacros from 1.2 to make it work.

D:\libtorrent-rasterbar-2.0.0>cmake .\ -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_ST
ANDARD=11 -DBUILD_SHARED_LIBS=OFF -DTORRENT_NO_DEPRECATE=ON -Dstatic_runtime=ON
-D_WIN32_WINNT=0x0601 -DCMAKE_GENERATOR_PLATFORM=x64 -Ddeprecated-functions=OFF
CMake Error at CMakeLists.txt:4 (include):
  include could not find load file:

    LibtorrentMacros

CMake Error at CMakeLists.txt:6 (read_version):
  Unknown CMake command "read_version".

-- Configuring incomplete, errors occurred!

**Comment by LiMinggang** [comment]
D:\libtorrent-rasterbar-2.0.0\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1,10): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [D:\libtorrent-rasterbar-2.0.0\CMakeFiles\CMakeTmp\cmTC_c7a17.vcxproj]

**Comment by LiMinggang** [comment]
Not support Windows yet?

**Comment by arvidn** [comment]
libtorrent 2.0 requires C++14, not 11.

There were a few cmake files missing when I created the tarball last. It has been fixed now and will be in the next RC3 which I will be sending out soon. In the meantime you can use the `RC_2_0` branch from the git repository.

**Comment by arvidn** [comment]
you an see it being built with cmake on windows here https://ci.appveyor.com/project/arvidn/libtorrent/builds/34679181/job/diy9u7ncpqo3u9us

**Comment by LiMinggang** [comment]
Thanks!
