### ISSUE TITLE
Updating iconv / gettext autoconf macros

### ISSUE THREAD

**Issue by brad0** [arvidn/libtorrent#4999]
Please sync up to the latest iconv / gettext autoconf macros. The ancient macros shipped have a bug that prevent detection of the shared libs and proper linking on OpenBSD.

**Comment by arvidn** [comment]
where do I find them?
a pull request against the `RC_1_2` branch would be very welcome!

**Comment by arvidn** [comment]
does this look right? https://github.com/arvidn/libtorrent/pull/5004

**Comment by namtsui** [comment]
Thank you for the fix. I am trying to update OpenBSD's port to 1.2.8. I will test out the latest commit with autoconf and report back to see if this goes away during configure:
```
Iconv library:
  Iconv Libs:           /usr/local/lib/libiconv.a
```

Hopefully, this shows up:
```
Iconv library:
  Iconv Libs:           -liconv

```

**Comment by namtsui** [comment]
To test, I modified openbsd's port to run autoreconf on configure.ac. I was having some trouble with the bootstrap.sh script in calling aclocal-1.16.2 when only aclocal-1.16 is available.

It uses /usr/local/lib/libiconv.so.7.0 rather than -liconv, as done with cmake, which is probably correct. I was running autoreconf, and it errored. To resolve, I had to copy build-aux/config.rpath from m4/config.rpath.

This is something to look out for when creating a release tarball for 1.2.9. For now I will propose updating openbsd's port to 1.2.8 to prevent pulling in autotools.

from https://gist.github.com/namtsui/ac5045a6eebf25c98d820145128eb975
```
# error: required file 'build-aux/config.rpath' not found
post-extract:
        cd ${WRKSRC} && mkdir -p build-aux && cp m4/config.rpath build-aux

```

logs of `make configure` and `make update-plist` which worked after testing out autoreconf and this fix (search for libiconv):
https://gist.github.com/namtsui/8deae6bd3e0d143d18f27068eba5cee8
https://gist.github.com/namtsui/21cb5dd8a5d3231d3562bd28b9554b58
```
Iconv
 library:
  Iconv Libs:           /usr/local/lib/libiconv.so.7.0
```


```
c++ -pthread -shared -fPIC -L/usr/local/lib/
-L/usr/obj/ports/Python-3.8.5/Python-3.8.5 -L/usr/local/lib/ -O2
-pipe
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/alert.o
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/converters.o
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/create_torrent.o
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/datetime.o
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/entry.o
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/error_code.o
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/fingerprint.o
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/ip_filter.o
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/magnet_uri.o
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/module.o
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/peer_info.o
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/session.o
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/session_settings.o
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/sha1_hash.o
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/string.o
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/torrent_handle.o
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/torrent_info.o
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/torrent_status.o
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/utility.o
build/temp.openbsd-6.7-amd64-3.8/usr/obj/pobj/libtorrent-rasterbar-1.2.8-pl20200808/libtorrent-8d280cc2e6cdaf0c456c432b4bb802d54fd30ba3/bindings/python/src/version.o
-L../../src/.libs -L/usr/local/lib -L/usr/local/lib -L/usr/local/lib
-ltorrent-rasterbar -lboost_system-mt -lpthread -lboost_system-mt
-lboost_python38-mt -lpthread -lssl -lcrypto -o
build/lib.openbsd-6.7-amd64-3.8/libtorrent.so -fvisibility=hidden
-fvisibility-inlines-hidden /usr/local/lib/libiconv.so.7.0
```

**Comment by namtsui** [comment]
> Hopefully /usr/local/lib/libiconv.so.7.0 is equivalent to -liconv.

These are equivalent and the confusion stemmed from a lack of knowledge about how ld.so resolves shared libraries at runtime.

To test, I updated the port for libiconv to change libiconv.so.7.0 --> libiconv.so.7.1.

Now deluge happily loads despite being compiled against libiconv.so.7.0. Just watch out for the config.rpath quirk when creating the release tarball for 1.2.9. Thank you for the fix and sorry for the noise. 
```
$ ldd /usr/local/lib/libtorrent-rasterbar.so.3.0  
/usr/local/lib/libtorrent-rasterbar.so.3.0:
        Start            End              Type  Open Ref GrpRef Name
        0000063f4956a000 0000063f499e2000 dlib  2    0   0      /usr/local/lib/libtorrent-rasterbar.so.3.0
        0000063f05f1f000 0000063f05f8a000 rlib  0    1   0      /usr/lib/libssl.so.48.1
        0000063ede73b000 0000063ede96e000 rlib  0    2   0      /usr/lib/libcrypto.so.46.1
        0000063e97bdb000 0000063e97cdd000 rlib  0    1   0      /usr/local/lib/libiconv.so.7.1
        0000063f37d7d000 0000063f37d84000 rlib  0    1   0      /usr/local/lib/libboost_system-mt.so.11.0
        0000063eff0b2000 0000063eff18e000 rlib  0    2   0      /usr/lib/libc++.so.5.0
        0000063eb40a9000 0000063eb40ec000 rlib  0    3   0      /usr/lib/libc++abi.so.3.0
        0000063e6e050000 0000063e6e05c000 rlib  0    2   0      /usr/lib/libpthread.so.26.1
        0000063e88c8d000 0000063e88cbd000 rlib  0    2   0      /usr/lib/libm.so.10.1
```

**Comment by Chocobo1** [comment]
@namtsui 
Just curious, why not build with cmake? Any reason to stick with autotools on OpenBSD?

**Comment by namtsui** [comment]
- Harder to review port update by moving to cmake
- Pulling in cmake as a dependency is bad for non-clang architectures. I'm not sure of the specific reason though. (currently, I think non-clang architectures that use ports-gcc is broken for other reasons though. `popcnt bitfield.cpp:74: Error: no such instruction: `popcnt %ecx,%ecx'`)
source: https://marc.info/?l=openbsd-ports&m=159740740606917&w=2
- Submitted as autotools and I didn't want to propose moving to cmake unless there was a clear advantage. It works as is.

When it comes to building the python bindings, b2 > cmake > autotools in terms of reliability and support.

I do have a cmake variant of the port working but probably won't propose it to OpenBSD for these reasons.
https://www.namtsui.com/cgi-bin/cvsweb/ports/net/libtorrent-rasterbar/Makefile.diff?r1=1.30&r2=1.31&f=h
https://www.namtsui.com/cgi-bin/cvsweb/ports/net/libtorrent-rasterbar/Makefile?rev=1.31&content-type=text/x-cvsweb-markup

**Comment by namtsui** [comment]
@Chocobo1 I guess I'll have to revisit cmake and propose it. It seems like autotools is inserting -std=c++11 and there is no checking for c++14 at the moment in autotools. Thanks for getting me to re-evaluate.

https://github.com/arvidn/libtorrent/issues/5024

**Comment by namtsui** [comment]
Well, I do see some c++14 tests in the m4 scripts you added. I'll poke around here. m4/ax_cxx_compile_stdcxx.m4
