### ISSUE TITLE
deluge/libtorrent crached and cannot get back up again

### ISSUE THREAD

**Issue by lethanhviet** [arvidn/libtorrent#500]
Hi,

Deluge: 1.3.12
Libtorrent: 126ce22cb9917e110239652f531c25f401bfbc97

Deluged crashed and couldn't get it work again. Syslog report below error everytime when tried deluged:
Feb 27 07:11:42 kernel: [1842136.150595] deluged[18293]: segfault at d0 ip 00007f87d922adec sp 00007f87d817ba70 error 4 in libtorrent-rasterbar.so.9.0.0[7f87d9163000+397000]
Feb 27 07:12:25 kernel: [1842179.458138] deluged[18375]: segfault at 8 ip 00007f22bea9ddec sp 00007f22bd9eea70 error 4 in libtorrent-rasterbar.so.9.0.0[7f22be9d6000+397000]
Feb 27 07:13:03 kernel: [1842216.462483] deluged[18438]: segfault at 0 ip 00007f3e1fdacdec sp 00007f3e1ecfda70 error 4 in libtorrent-rasterbar.so.9.0.0[7f3e1fce5000+397000]
Feb 27 07:14:09 kernel: [1842283.084652] deluged[18545]: segfault at 8 ip 00007f5524783dec sp 00007f55236d4a70 error 4 in libtorrent-rasterbar.so.9.0.0[7f55246bc000+397000]

**Comment by arvidn** [comment]
there is no way I can make sense of this. I did not build that binary and I don't have its debug symbols. Please rebuild with debug symbols (and perhaps a debug build even) and report the stack trace and other possibly relevant state at the crash

**Comment by lethanhviet** [comment]
After rebuilding the latest vers 8cb18d39a102beb9d7f38f15071f12e0595f93ee, got the below errors when trying to start deluge/libtorrent:
broadcast socket [ if: 127.0.0.1 group: 239.255.255.250 mask: 255.0.0.0 ] Success
broadcast socket [ if: xxx.xxx.xxx.xxx group: 239.255.255.250 mask: 255.255.255.224 ] Success
broadcast socket [ if: 127.0.0.1 group: 239.192.152.143 mask: 255.0.0.0 ] Success
broadcast socket [ if: xxx.xxx.xxx.xxx group: 239.192.152.143 mask: 255.255.255.224 ] Success
broadcast socket [ if: ::1 group: ff15::efc0:988f mask: ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff ] Success
broadcast socket [ if: xxxx:xxxx:xxxx:xxxx::2 group: ff15::efc0:988f mask: ffff:ffff:ffff:ffff:: ] Success
A precondition of a libtorrent function has been violated.
This indicates a bug in the client application using libtorrent

file: 'file_storage.cpp'
line: 744
function: std::string libtorrent::file_storage::file_path(int, const string&) const
expression: index >= 0 && index < int(m_files.size())

stack:
1: assert_fail(char const*, int, char const*, char const*, char const*, int)
2: libtorrent::file_storage::file_path(int, std::string const&) const
3:
4:
5:
6:
7:
8:
9:
10: clone

broadcast socket [ if: 127.0.0.1 group: 239.255.255.250 mask: 255.0.0.0 ] Success
broadcast socket [ if: xxx.xxx.xxx.xxx group: 239.255.255.250 mask: 255.255.255.224 ] Success
broadcast socket [ if: 127.0.0.1 group: 239.192.152.143 mask: 255.0.0.0 ] Success
broadcast socket [ if: xxx.xxx.xxx.xxx group: 239.192.152.143 mask: 255.255.255.224 ] Success
broadcast socket [ if: ::1 group: ff15::efc0:988f mask: ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff ] Success
broadcast socket [ if: xxxx:xxxx:xxxx:xxxx::2 group: ff15::efc0:988f mask: ffff:ffff:ffff:ffff:: ] Success
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:



version: 1.1.0.0-7f05551

file: '../include/libtorrent/stack_allocator.hpp'
line: 87
function: const char* libtorrent::aux::stack_allocator::ptr(int) const
expression: idx < int(m_storage.size())

stack:
1: assert_fail(char const*, int, char const*, char const*, char const*, int)
2:
3:
4: libtorrent::tracker_alert::message() const
5: libtorrent::tracker_reply_alert::message() const
6: boost::python::objects::caller_py_function_impl<boost::python::detail::caller<std::string (libtorrent::alert::*)() const, boost::python::default_call_policies, boost::mpl::vector2<std::string, libtorrent::alert&> > >::operator()(_object*, _object*)
7: boost::python::objects::function::call(_object*, _object*) const
8:
9: boost::python::handle_exception_impl(boost::function0<void>)
10:
11: PyEval_EvalFrameEx
12: ) [0x4e5fe8]
13: PyEval_EvalFrameEx
14: PyEval_EvalCodeEx
15: PyEval_EvalFrameEx
16: PyEval_EvalCodeEx
17: PyEval_EvalFrameEx
18: PyEval_EvalCodeEx
19: PyEval_EvalFrameEx
20: ) [0x4e5fe8]
21: ) [0x5045d8]
22: ) [0x503219]
23: ) [0x4ba94b]
24: PyEval_EvalFrameEx
25: PyEval_EvalCodeEx
26: PyEval_EvalFrameEx
27: PyEval_EvalCodeEx
28: ) [0x5030ef]
29: PyRun_FileExFlags
30: PyRun_SimpleFileExFlags
31: Py_Main
32: __libc_start_main
33: ) [0x497ca0]

**Comment by arvidn** [comment]
this is most likely caused by alerts being saved off to the side (by deluge) and accessed after a subsequent call to pop_alerts(). This used to work, but some recent optimizations (in 1.1) makes alert objects, and the data they contain specifically, expire after the next call to pop_alerts().

I will try to think of ways to be backwards compatible in this regard. The optimization is described here:
http://blog.libtorrent.org/2015/04/libtorrent-alert-queue/

**Comment by lethanhviet** [comment]
I was using this libtorrent/deluge build for last 2 weeks without problem. it was only since after last crash that all of this issue just started to pop up one after another.

**Comment by arvidn** [comment]
do you think you could try this patch (based on RC_1_1). https://github.com/arvidn/libtorrent/pull/506

**Comment by lethanhviet** [comment]
I'm getting the patch now. Will report back later about the performance.

**Comment by arvidn** [comment]
yeah, sorry about that. typo. I just fixed it

**Comment by lethanhviet** [comment]
working now. thx!
