### ISSUE TITLE
wait_for_alert() pop_alerts() crash, natpmp crash, get_cache_info() magnet crash

### ISSUE THREAD

**Issue by 5523eeOMEGALUL** [arvidn/libtorrent#5018]
libtorrent-rasterbar-1.2.8

Win10 2004 10.0.19041.450
VS2019 16.7, boost 1.73-1.74, libiconv 1.16, openssl 1.1, c++17

I'm compiling and running libtorrent-rasterbar-1.2.8/examples/client_test.cpp with session_view, torrent_view and print.cpp(.hpp)

first problem was if
`params.settings.set_bool(settings_pack::enable_natpmp, false);`
not set program crash shortly after
`lt::session ses(std::move(params));`
you can put
`std::this_thread::sleep_for(refresh_delay);`
next line client_test.cpp will crash there.

second: when program run with magnet link as param client_test.cpp crash at
`ses.get_cache_info(&cs, h, cache_flags);`

third and most important are wait_for_alert() pop_alerts() crashes.
if magnet link used program crash at second call
`ses.pop_alerts(&alerts);`
when started with torrent file _with trackers_ there several options:
crash with default
`settings.set_int(settings_pack::alert_mask`

`params.settings.set_int(settings_pack::alert_mask, 0);`
able to download relatively big .torrent.

while experimenting I've found:
1. if wait_for_alert(X) called before pop_alerts() it crash same way
2. crash happen on empty m_alerts[m_generation]

I think there typing error in documentation too:
https://www.libtorrent.org/reference-Core.html
at where **ses.wait_for_alert** example
inside _for (alert* i : alerts) {}_ functions reference _**a**_ variable while it should be _**i**_
same example can be found in
libtorrent-rasterbar-1.2.8/include/libtorrent/alert.hpp
libtorrent-rasterbar-1.2.8/include/libtorrent/torrent_handle.hpp
libtorrent-rasterbar-1.2.8/docs/reference-Alerts.html
libtorrent-rasterbar-1.2.8/docs/reference-Core.html
libtorrent-rasterbar-1.2.8/docs/single-page-ref.html

also crash in client_test.cpp
`print_alert(a, event_string);`
since no a->message() on alert cat=17, type=11, type11(a->name)="tracker_error"
category 17 is constexpr alert_category_t tracker = 4_bit; + constexpr alert_category_t error = 0_bit;

**Comment by arvidn** [comment]
this smells like an ABI incompatibility issue. How are you building libtorrent and how are you building `client_test`?

**Comment by arvidn** [comment]
fixing typos here: https://github.com/arvidn/libtorrent/pull/5019

**Comment by 5523eeOMEGALUL** [comment]
> building libtorrent
`cd build
set OPENSSL_ROOT_DIR=c:\project\openssl-1.1
set OPENSSL_CRYPTO_LIBRARY=c:\project\openssl-1.1
set OPENSSL_INCLUDE_DIR=c:\project\openssl-1.1\include
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DBoost_INCLUDE_DIR=c:\project\boost_1_74_0\1b2\include -DIconv_LIBRARY=c:\project\libiconv\x64\Release -DIconv_INCLUDE_DIR=c:\project\libiconv\include -G "Visual Studio 16 2019" ..`
then I open .sln in VS. project missing only libiconv library location. there nothing special

client test is console x64 application. require only
https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus
7 files, include folder, libs, dlls


> ABI incompatibility
with alert_mask 0 and using .torrent files with trackers client_test.cpp do work.
natpmp crash can be related to extra network adapters from Hyper-V.

**Comment by arvidn** [comment]
I'm not super familiar with the details of how the cmake file works. Could you try using Ninja instead? (i.e. `-GNinja`)
or specifying `--build` directly on the cmake command line?

**Comment by arvidn** [comment]
the fact that you specify the boost include path seems suspicious. How does cmake know which binaries go with those headers? If you use boost binaries that don't belong to those headers, or binaries that were built in an ABI incompatible way, you will have these kinds of issues. I think it would be much more reliable to let cmake find boost, both headers and binaries (or ideally, build the binaries).

**Comment by 5523eeOMEGALUL** [comment]
I think boost get it in scripts since there 4 dll/lib for every boost class
`boost_atomic-vc142-mt-gd-x32-1_74.lib`
`boost_atomic-vc142-mt-gd-x64-1_74.lib`
`boost_atomic-vc142-mt-x32-1_74.lib`
`boost_atomic-vc142-mt-x64-1_74.lib`
what env variable should be set in libtorrent cmake to find boost?

**Comment by arvidn** [comment]
If you think your network adapters are causing the NAT-PMP crash, could you please provide information on that crash? Like, stack trace and what the actual fault is, and maybe the surrounding variable values

**Comment by arvidn** [comment]
did you build boost with the same compiler? I can't remember the visual studio versions off-hand, but is 14.2 the same as "Visual Studio 16 2019"?

**Comment by 5523eeOMEGALUL** [comment]
There no stack trace.
Program back in command prompt on errors, not saying a word.

boost build procedure:
1. open developer command prompt VS2019
2. run that bootstrap.bat to get b2.exe
3. type `b2 install --prefix=c:\project\boost --build-dir=c:\project\boostbuild --build-type=complete msvc stage`
then boostbuild can be deleted, libs and includes are in --prefix

**Comment by arvidn** [comment]
> There no stack trace.
> Program back in command prompt on errors, not saying a word.

So, it may not be a crash then. The program could just be calling `exit()`.

Could you run it in a debugger to find out?

**Comment by 5523eeOMEGALUL** [comment]
just added
`int main(int argc, char* argv[]) try {`
`}
catch (const std::exception& e) {
	std::cout << e.what();
}`
to client_test.cpp
nothing happened
I have modified it a bit, crash happen on line 1762
https://github.com/arvidn/libtorrent/blob/libtorrent-1.2.8/examples/client_test.cpp
I put
`alert const* alrt = ses.wait_for_alert(seconds(11));`
`if (alrt != nullptr) pop_alerts(view, ses_view, ses, events);`
crash ses.wait_for_alert(seconds(11))
if i remove my code it crash inside  pop_alerts(view, ses_view, ses, events){}, on line 1013
`ses.pop_alerts(&alerts);`

btw what do I click to paste block of code here and keep formatting?

**Comment by 5523eeOMEGALUL** [comment]
btw
Program not crash on first .wait_for_alert() .pop_alerts() call!!!
I see
`adding magnet: magnet:?xt=urn:btih:A98A4630`
`wait_for_alert()` call
`added torrent: torrentname`
`session stats header: long list`
then second call cycle
`while (!quit && loop_limit != 0)`
on line 1426 happen and after that alert queue empty and ses.wait_for_alert() call crash

**Comment by 5523eeOMEGALUL** [comment]
test 1:
https://github.com/arvidn/libtorrent/blob/libtorrent-1.2.8/src/alert_manager.cpp
commenting out lines 54, 55
https://github.com/arvidn/libtorrent/blob/libtorrent-1.2.8/include/libtorrent/alert_manager.hpp
commenting line 87
https://github.com/arvidn/libtorrent/blob/libtorrent-1.2.8/examples/client_test.cpp
changing line 1762 to
`alert const* alrt = ses.wait_for_alert(seconds(11));`
`if (alrt != nullptr) pop_alerts(view, ses_view, ses, events);`
what happen:
now every .wait_for_alert() call happen with 11s wait so there _always_ something for .pop_alerts()
no crash magnet link work and downloaded fine

test 2:
library and include files back to original, in file
https://github.com/arvidn/libtorrent/blob/libtorrent-1.2.8/examples/client_test.cpp
inserting before line 1762
std::this_thread::sleep_for(std::chrono::seconds(11));
what happen:
same to previous run, download complete


if this extra long wait removed
.dll gonna crash if `m_alerts[m_generation].empty() ` 

updating torrent client every 11 seconds or so not good idea.

**Comment by arvidn** [comment]
could you run it in a debugger to explain in some more details what "crash" means? e.g. what kind of fault is encountered?

**Comment by 5523eeOMEGALUL** [comment]
EXCEPTION_ACCESS_VIOLATION in ucrtbase.dll module regardless of crash place or debugger

modified fn alert_manager::get_all() to `{m_alerts[m_generation].get_pointers(alerts); return;}`
so after all it not empty `m_alerts[m_generation].empty()` causing problems

I'm starting to think torrent_view.cpp or ::handle_alert() can be problem so client_test.cpp crash on next .wait_for_alert() or line 1775
https://github.com/arvidn/libtorrent/blob/libtorrent-1.2.8/examples/client_test.cpp#L1775

**Comment by arvidn** [comment]
ok, you get an access violation. Which variable/pointer is invalid?
What is the stack trace of the thread that fails with access violation?

**Comment by 5523eeOMEGALUL** [comment]
https://github.com/arvidn/libtorrent/blob/libtorrent-1.2.8/examples/client_test.cpp
removing lines 940, 941 no dll crash.

**Comment by arvidn** [comment]
This is most likely an ABI incompatibility between your binaries. I have not seen any evidence to suggest otherwise. Your comments about what lines to add or remove do not narrow down the cause of this. Please use a debugger.

You could also try building the example with boost-build, with boost from source. That would ensure all libraries are ABI compatible.

**Comment by 5523eeOMEGALUL** [comment]
is it me or libtorrent only allow creating (session) torrents from files?
libtorrent 1.2.8
`std::vector<char> buf;`
`auto ti = std::make_shared<lt::torrent_info>(buf, ec, lt::from_span);`
`LNK2001	unresolved external symbol "class libtorrent::from_span_t libtorrent::from_span"`
`(?from_span@libtorrent@@3Vfrom_span_t@1@A)`

there similar code in what commented deprecated function
https://github.com/arvidn/libtorrent/blob/libtorrent-1.2.8/src/torrent.cpp#L451

**Comment by arvidn** [comment]
@5523eeOMEGALUL that last post is not related to the topic of this ticket, right? it looks like it should have been a new issue.

> is it me or libtorrent only allow creating (session) torrents from files?
> libtorrent 1.2.8
> std::vector<char> buf;
> auto ti = std::make_shared<lt::torrent_info>(buf, ec, lt::from_span);
> LNK2001 unresolved external symbol "class libtorrent::from_span_t libtorrent::from_span"
> (?from_span@libtorrent@@3Vfrom_span_t@1@A)

`from_span` is declared [here](https://github.com/arvidn/libtorrent/blob/RC_1_2/include/libtorrent/torrent_info.hpp#L113) and defined [here](https://github.com/arvidn/libtorrent/blob/RC_1_2/src/torrent_info.cpp#L80).

To trouble shoot your build of the library, you might want to dump the exported symbols and ensure `from_span` is in there. If it is, also ensure the mangling matches what the link error says.

> there similar code in what commented deprecated function
> https://github.com/arvidn/libtorrent/blob/libtorrent-1.2.8/src/torrent.cpp#L451

Yes, your code is correct. But from previous posts in this thread, it seems your build is not.

**Comment by 5523eeOMEGALUL** [comment]
in .dll project was defined TORRENT_BUILDING_SHARED, TORRENT_BUILDING_LIBRARY +many others
added TORRENT_LINKING_SHARED to .exe project
linking error gone, torrent_info() from vector passed.
got new warning
include\libtorrent\file_pool.hpp(57,2): warning C4275: non dll-interface class 'boost::noncopyable_::noncopyable' used as base for dll-interface struct 'libtorrent::file_pool'
include\libtorrent\file_pool.hpp(56): message : see declaration of 'libtorrent::file_pool'

should TORRENT_NO_DEPRECATE or TORRENT_ABI_VERSION be set?

**Comment by 5523eeOMEGALUL** [comment]
is there way automatically stop seeding?
`seed_time_limit, v=0`
`seed_time_ratio_limit, v=0`
`share_ratio_limit, v=0`
torrents keep seeding (moved to less prioritized seed state?)
turning on next option
`active_seeds, v=0`
torrents get (lt::torrent_flags::paused && lt::torrent_flags::auto_managed) which is 
https://github.com/arvidn/libtorrent/blob/libtorrent-1.2.10/examples/torrent_view.cpp#L56
what actually should happen for `lt::torrent_flags::auto_managed` torrent to switch to `torrent_status::finished`?
I'm trying to automatically stop torrent based on something (without manually setting `lt::torrent_flags::paused`) (handle.pause(lt::torrent_handle::graceful_pause))

**Comment by 5523eeOMEGALUL** [comment]
when ses.pause() ses.resume() happen while downloading something
getting wrong number from `torrent_status` `total_download`
number seems counting from 0, not from where .pause() happen
lets say 1gb torrent 500mb complete, ses.pause() ses.resume(), `total_download` report download begin from 0

**Comment by arvidn** [comment]
> what actually should happen for lt::torrent_flags::auto_managed torrent to switch to torrent_status::finished?

It depends. it's configurable.

> I'm trying to automatically stop torrent based on something (without manually setting lt::torrent_flags::paused) 

By "manually", I take it you mean "your program" doing it.

I assume you read the documentation for share_ratio_limit and seed_time_ratio_limit:

> when a seeding torrent reaches either the share ratio (bytes up / bytes down) or the seed time ratio (seconds as seed / seconds as downloader) or the seed time limit (seconds as seed) it is considered done, and it will leave room for other torrents. These are specified as percentages. Torrents that are considered done will still be allowed to be seeded, they just won't have priority anymore. For more, see [queuing](http://libtorrent.org/manual-ref.html#queuing).

> when ses.pause() ses.resume() happen while downloading something
> getting wrong number from torrent_status total_download
> number seems counting from 0, not from where .pause() happen

I assume you read the documentation for [total_download](http://libtorrent.org/reference-Core.html#total_download). Your description sounds like you're seeing the correct behavior (as documented).
