### ISSUE TITLE
qbittorrent fallout from entry.hpp changes in 1.2.9

### ISSUE THREAD

**Issue by namtsui** [arvidn/libtorrent#5024]
**Please provide the following information**

libtorrent version (or branch):

platform/architecture: openbsd amd64

compiler and compiler version: clang++ 10.0.1

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I get an error when compiling qbitorrent. I am guessing it is due to this commit because I diffed 1.2.8 and 1.2.9 entry.hpp:
https://github.com/arvidn/libtorrent/commit/0c0671987bbf615da94c8b3e759116d9f62e9f54

It works with 1.2.8 but not 1.2.9.

diff between entry.hpp in 1.2.8 and 1.2.9:
```
--- ../../libtorrent-rasterbar-1.2.8/libtorrent-rasterbar-1.2.8/include/libtorrent/entry.hpp    Tue Aug  4 09:21:21 2020
+++ ./include/libtorrent/entry.hpp      Thu Aug 20 14:04:27 2020
@@ -87,7 +87,7 @@
 
 namespace aux {
 
-#if (__cplusplus > 201103) || (defined _MSC_VER && _MSC_VER >= 1900)
+#if !defined TORRENT_CXX11_ABI && (__cplusplus > 201103) || (defined _MSC_VER && _MSC_VER >= 1900)
                // this enables us to compare a string_view against the std::string that's
                // held by the std::map
                // is_transparent was introduced in C++14
@@ -105,6 +105,9 @@
                struct map_string : std::map<std::string, T>
                {
                        using base = std::map<std::string, T>;
+                       using base::base;
+                       map_string() = default;
+                       map_string(base&& rhs) : base(std::move(rhs)) {}
 
                        typename base::iterator find(const string_view& key)
                        {
```

```
linking qbittorrent

ld: error: undefined symbol:
libtorrent::entry::entry(std::__1::map<std::__1::basic_string<char,
std::__1::char_traits<char>, std::__1::allocator<char> >,
libtorrent::entry, libtorrent::aux::strview_less,
std::__1::allocator<std::__1::pair<std::__1::basic_string<char,
std::__1::char_traits<char>, std::__1::allocator<char> > const,
libtorrent::entry> > >)

>>> referenced by tracker.cpp

>>>
tracker.o:(BitTorrent::Tracker::processRequest(Http::Request const&,
Http::Environment const&))

>>> referenced by tracker.cpp

>>>
tracker.o:(BitTorrent::Tracker::prepareAnnounceResponse(BitTorrent::Tracker::Tra
const&))

>>> referenced by tracker.cpp

>>>               tracker.o:(void
std::__1::allocator_traits<std::__1::allocator<libtorrent::entry>
>::construct<libtorrent::entry, std::__1::map<std::__1::basic_string<char,
std::__1::char_traits<char>, std::__1::allocator<char> >,
libtorrent::entry, libtorrent::aux::strview_less,
std::__1::allocator<std::__1::pair<std::__1::basic_string<char,
std::__1::char_traits<char>, std::__1::allocator<char> > const,
libtorrent::entry> > >&>(std::__1::allocator<libtorrent::entry>&,
libtorrent::entry*, std::__1::map<std::__1::basic_string<char,
std::__1::char_traits<char>, std::__1::allocator<char> >,
libtorrent::entry, libtorrent::aux::strview_less,
std::__1::allocator<std::__1::pair<std::__1::basic_string<char,
std::__1::char_traits<char>, std::__1::allocator<char> > const,
libtorrent::entry> > >&))

clang++: error: linker command failed with exit code 1 (use -v to
see invocation)
```

full log (click full file and look at the end): https://gist.github.com/namtsui/a390b052e70a02bd8ac81d9c09723b70

**Comment by FranciscoPombal** [comment]
@namtsui

This happens if you build libtorrent with C++11 but build qBittorrent with C++14 (which is the minimum version required anyway).

Possible solutions:

- (Re)Build libtorrent with C++14 (easiest)
- Pass `TORRENT_CXX11_ABI` as a compile definition when building qBittorrent (you probably have to patch the buildscripts to do this, how exactly depends on whether you're using qmake or CMake)
- Use CMake to build libtorrent with C++11, but taking care to pass `-DCMAKE_CXX_STANDARD=11`. This will force `TORRENT_CXX11_ABI` to be propagated to targets that link against libtorrent, eliminating the need to manually specify the `TORRENT_CXX11_ABI` compile definition when building downstream projects.

**Comment by namtsui** [comment]
@FranciscoPombal Thank you for the hints. I will try the first solution and report back.

**Comment by namtsui** [comment]
Thank you. It worked once I modified the configure.ac file as in the PR above. -std=gnu++14 now appears during libtorrent-rasterbar compilation and qbittorrent compiles.
