### ISSUE TITLE
Torrent trafic does not go through VPN

### ISSUE THREAD

**Issue by XITRIX** [arvidn/libtorrent#5027]
**Please provide the following information**

libtorrent version (or branch): 1.2.6 - 1.2.9

platform/architecture: MacOS, iOS/x86_64,arm64

compiler and compiler version: XCode 11/12beta

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
![530BB90A-A94E-4957-A077-FF0DEA820C1F](https://user-images.githubusercontent.com/9553519/90856577-e7131180-e38a-11ea-8c6a-616d2ce3856e.jpeg)

Just open a service like checkmyip.torrentprivacy.com, if you are using VPN, it will show your real ip. Tested on iOS and macOS with my iTorrent app, also tested on qBitTorrent it have this problem too starting with libtorrent 1.2.6, windows version of qBitTorrent does not have such problem, so I think this problem only on appleOS (may be Linux too)

**Comment by 5523eeOMEGALUL** [comment]
you want default route set inb4 running libtorrent
you can see it in `netstat -rn` command
you also want some script to stop torrent client when vpn goes down

**Comment by XITRIX** [comment]
Hi, is there any chance, that you'll implement some kind of config to force libtorrent to use the main device interface? I just realised, that there is much more dangerous thing, than just leak of ip from another interface, on mobile phone it also uses cellular data, while device is connected to WiFi. 

I am trying to implement interface selection using 
`settings_pack->set_str(lt::settings_pack::outgoing_interfaces, "some_interface");`
and then use this pack with `new lt::session(pack);` 
but it still use all ports instead of selected one, does that is the correct way to set interface or am I missed something?

**Comment by arvidn** [comment]
@XITRIX use the `listen_interfaces` setting

**Comment by XITRIX** [comment]
Thanks, it is working now!
But what about config to let OS decide which interface to use?

**Comment by arvidn** [comment]
OSes don't have settings like that. They often have weights on interfaces, and they can shut down interfaces.

**Comment by XITRIX** [comment]
I mean that earlier versions of libtorrent used some kind of “default” interface, cause when I and qbt used 1.2.4 there was no needed in manual configuration for interfaces, it used the main one by default. But now I need to manual setup it to prevent cellular traffic and ip leaking things. So is it possible to implement some kind of config to bring back that behavior?

**Comment by arvidn** [comment]
right, it always just used a single interface, instead of attempting to use all available ones.

**Comment by XITRIX** [comment]
https://github.com/arvidn/libtorrent/pull/4492/files
Also I found that PR where earlier it was like this: 
“An empty string binds outgoing connections to INADDR_ANY and port 0 (i.e. let the OS decide).”
But than you changed it, may be that was what I am talking about?
