### ISSUE TITLE
[windows] : cp == 65001 || cp == 65001 escape_string.cpp 471

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#5033]
libtorrent version (or branch): master
platform/architecture: x64
compiler and compiler version: vc++2019

![изображение](https://user-images.githubusercontent.com/920705/90927648-229af380-e3fe-11ea-87b2-67a666af67b0.png)

**Comment by arvidn** [comment]
msdn is not unambiguous about the values of that constant, and mentions both the numeric value and the constant.
Do you know if `CP_UTF8` is guaranteed to be 65001?

it seems odd if that wasn't the case I suppose

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/5063
