### ISSUE TITLE
Python binding warning about statically linking boost-python when building with b2 (jamfile)

### ISSUE THREAD

**Issue by userdocs** [arvidn/libtorrent#5045]
**Please provide the following information**

libtorrent version (or branch): 1.2.9

platform/architecture:

compiler and compiler version: gcc 8/9

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

When using b2 and and boost to compile the python binding there is a hardcoded warning in the jamfile about not being able to statically link the `boost_python` library.

https://github.com/arvidn/libtorrent/blob/RC_1_2/bindings/python/Jamfile#L127

```
ECHO "WARNING: you cannot link statically against boost-python on linux, because it links against pthread statically in that case, which is not allowed" ;
```

The result, due to this section https://github.com/arvidn/libtorrent/blob/RC_1_2/bindings/python/Jamfile#L147#L168, appears to force it to link as a shared object.

```
root@localhost:~# ldd python-libtorrent-build/completed/libtorrent.so
        linux-vdso.so.1 (0x00007ffef4d1c000)
        libboost_python37.so.1.74.0 => not found
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fad0b1af000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fad0b1aa000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fad0b189000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fad0b184000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fad0b000000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fad0ae7b000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fad0ae61000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fad0aca0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fad0baba000)
```

But it appears that I am able to link this statically with no issues and use the binding successfully with deluge.

```
root@localhost:~# ldd python-libtorrent-build/completed/libtorrent.so
        linux-vdso.so.1 (0x00007fff341cc000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f80664fb000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f80664da000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f80664d5000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f80664d0000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f806634c000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f80661c9000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f80661ad000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8065fec000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8066e31000)
```

This static linking is possible through two ways.

1: When i actually compile and install the boost libraries statically using b2

2: If i just use the boost build files (instead of compile) and edit the jamfile to force static.

https://github.com/arvidn/libtorrent/blob/RC_1_2/bindings/python/Jamfile#L152
https://github.com/arvidn/libtorrent/blob/RC_1_2/bindings/python/Jamfile#L161

Point of the issue:

With a statically linked boost_python i appear to have a fully functional python binding. Is this warning still valid?

I have attached a python binding with a statically linked boost_python as an example.

[libtorrent.zip](https://github.com/arvidn/libtorrent/files/5129402/libtorrent.zip)

**Comment by arvidn** [comment]
it seems that logic is outdated for linux then. Perhaps gcc links dynamically against pthread unconditionally these days. Anyway, please feel free to submit a PR to fix it!

**Comment by arvidn** [comment]
do you have to edit the Jamfiles to make it link statically against boost python? I would think you can just say `boost-link=static`, you get the warning, but that build property would still be in effect, no?

**Comment by userdocs** [comment]
So, this is the build command (expanded).

```
"b2" -j$(nproc) python=37 dht=on encryption=on crypto=openssl i2p=on extensions=on variant=release threading=multi libtorrent-link=static boost-link=static cxxstd=14 cxxflags="-std=c++14 -fPIC" cflags="-I$include_dir -fPIC" linkflags="-Wl,--no-as-needed -ldl -L$lib_dir -lpthread -pthread" toolset=gcc stage_module
```

Scenario 1: I download boost 1.74 and build it using b2,  creating static libraries in my build dir. When i build libtorrent using b2 the warning is present but the linking seems to be static automatically. I assume this is to b2 linking the existing `.../lib/boost_python37.a` instead of creating one.

Scenario 2: I download boost 1.74 but don't compile and install it. I just use it to build libtorrent as described here https://libtorrent.org/building.html by defining these variables and just extracting the archive:

```
BOOST_ROOT=$install_dir/boost_1_74_0/
BOOST_INCLUDEDIR=$install_dir/boost_1_74_0/boost
BOOST_BUILD_PATH=$install_dir/boost_1_74_0/tools/build
```

In this second instance i must modify the file or the linking is done shared, i assume due to the warning related code and if/else and the `boost_python37` being built based on this instead of already existing.

Regarding a pull, if i can understand to the issue and solution well enough then i can try.

**Comment by userdocs** [comment]
So i revised my build process based on what i figured out over the course of these last few (self inflicted?) issues. Now it is pretty streamlined, to the point and inline with documentation. I don't think there is anything i have introduced to the process to create this issue.

core dependencies installed > openssl static compiled > b2 compiled > boost build files downloaded > compile python binding using b2 and boost build files > libtorrent.so

https://github.com/userdocs/python-libtorrent-binding/blob/master/python-libtorrent-binding.sh

If you can confirm the issue and or nature of it, i can try to fix it via a pull request. I have tested on both Ubuntu Focal and Debian Stable identical results in both scenarios. Perhaps older distros are an issue but no point testing if there is not an actual issue to fix.

**Comment by arvidn** [comment]
I just tested this on ubuntu:

```
b2 -j30 stage_module libtorrent-link=static boost-link=static
python test.py
```

and it worked (despite printing the warnings about linking statically). As far as I can tell, the warning should be removed, but other than that, it seems fine. Is that also your impression, or do you experience any other issues?

**Comment by arvidn** [comment]
@userdocs how does this look? https://github.com/arvidn/libtorrent/pull/5048

**Comment by userdocs** [comment]
Can i just check, do you have boost installed as a dependency via `apt-get` on this test system?

The environment in my script is always on a new vm with just this installed `apt install -y build-essential pkg-config automake libtool git perl python3 python3-dev python3-pip` with everything else being compiled locally with the exception of boost, which appears to be part of the cause of this issue. This only happens when using building the binding by linking the boost source code with no prior builds or installs of boost.

```
root@localhost:~# ldd python-libtorrent-build/completed/libtorrent.so
        linux-vdso.so.1 (0x00007fffc67f1000)
        libboost_python37.so.1.74.0 => not found
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5a37d7a000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5a37d75000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5a37d54000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f5a37d4f000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5a37bcb000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5a37a46000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5a37a2c000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5a3786b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5a38685000)
root@localhost:~#
```

Here are my `$(properties)` from my jamfile using this build command in both instances:

```
b2 -j$(nproc) python="$python_short_version" dht=on encryption=on crypto=openssl i2p=on extensions=on variant=release threading=multi libtorrent-link=static boost-link=static cxxstd=14 cxxflags="$CXXFLAGS" cflags="$CPPFLAGS" linkflags="$LDFLAGS" toolset=gcc stage_module
```

Unmodified jamfile:

```
<abi>sysv <asio-debugging>off <asserts>off <asynch-exceptions>off <binary-format>elf <boost-link>static <cflags>-I/root/python-libtorrent-build/include <context-impl>fcontext <coverage>off <crypto>openssl <cxxflags>-std=c++14 -fPIC <cxxstd-dialect>iso <cxxstd>14 <debug-iterators>default <debug-symbols>off <define>NDEBUG <define>OPENSSL_NO_SSL2 <define>TORRENT_USE_I2P=1 <define>TORRENT_USE_LIBCRYPTO <define>TORRENT_USE_OPENSSL <define>_WIN32_WINNT=0x0600 <deprecated-functions>on <dht>on <encryption>on <exception-handling>on <export-extra>off <extensions>on <extern-c-nothrow>off <fpic>off <hardcode-dll-paths>true <host-os>linux <i2p>on <iconv>auto <inlining>full <install-dependencies>off <invariant-checks>off <libtorrent-link>static <libtorrent-python-pic>off <libtorrent-python>on <link>shared <linkflags>-L/root/python-libtorrent-build/lib <logging>on <lt-visibility>default <mutable-torrents>on <openssl-version>1.1 <optimization>speed <os>LINUX <pch>on <picker-debugging>off <predictive-pieces>on <preserve-test-targets>on <profile-calls>off <profiling>off <python-debugging>off <python>3.7 <relevant>cflags:<relevant>toolset <relevant>cxxflags:<relevant>toolset <relevant>library:<relevant>crypto <relevant>python.interpreter:<relevant>python <relevant>python.interpreter:<relevant>target-os <rtti>on <runtime-debugging>off <runtime-link>shared <share-mode>on <simulate-slow-read>off <simulator>off <stdlib>native <streaming>on <strip>off <super-seeding>on <suppress-import-lib>false <symlink-location>project-relative <target-os>linux <test-coverage>off <testing.execute>on <threadapi>pthread <threading>multi <toolset-gcc:version>8 <toolset>gcc <use>/python//python_for_extensions <user-interface>console <utp-log>off <variant>release <vectorize>off <warnings-as-errors>off <warnings>on <windows-version>vista
<abi>sysv <asio-debugging>off <asserts>off <asynch-exceptions>off <binary-format>elf <boost-link>static <cflags>-I/root/python-libtorrent-build/include <cflags>-fPIC <cflags>-fvisibility=hidden <context-impl>fcontext <coverage>off <crypto>openssl <cxxflags>-Wno-deprecated-declarations <cxxflags>-fvisibility-inlines-hidden <cxxflags>-std=c++14 -fPIC <cxxstd-dialect>iso <cxxstd>14 <debug-iterators>default <debug-symbols>off <define>NDEBUG <define>OPENSSL_NO_SSL2 <define>TORRENT_USE_I2P=1 <define>TORRENT_USE_LIBCRYPTO <define>TORRENT_USE_OPENSSL <define>_WIN32_WINNT=0x0600 <deprecated-functions>on <dht>on <encryption>on <exception-handling>on <export-extra>off <extensions>on <extern-c-nothrow>off <fpic>off <hardcode-dll-paths>true <host-os>linux <i2p>on <iconv>auto <inlining>full <install-dependencies>off <invariant-checks>off <library>/root/python-libtorrent-build/libtorrent/bindings/python//boost_python3/<link>shared/<warnings>off <library>/torrent//crypto <library>/torrent//ssl <library>/torrent//torrent/<link>static <libtorrent-link>static <libtorrent-python-pic>on <libtorrent-python>on <link>shared <linkflags>-L/root/python-libtorrent-build/lib <linkflags>-Wl,-Bsymbolic <logging>on <lt-visibility>hidden <mutable-torrents>on <openssl-version>1.1 <optimization>speed <os>LINUX <pch>on <picker-debugging>off <predictive-pieces>on <preserve-test-targets>on <profile-calls>off <profiling>off <python-debugging>off <python.interpreter>/usr/bin/python3.7 <python>3.7 <relevant>cflags:<relevant>toolset <relevant>cxxflags:<relevant>toolset <relevant>library:<relevant>crypto <relevant>python.interpreter:<relevant>python <relevant>python.interpreter:<relevant>target-os <rtti>on <runtime-debugging>off <runtime-link>shared <share-mode>on <simulate-slow-read>off <simulator>off <stdlib>native <streaming>on <strip>off <super-seeding>on <suppress-import-lib>false <symlink-location>project-relative <target-os>linux <test-coverage>off <testing.execute>on <threadapi>pthread <threading>multi <toolset-gcc:version>8 <toolset>gcc <use>/python//python_for_extensions <user-interface>console <utp-log>off <variant>release <vectorize>off <warnings-as-errors>off <warnings>on <windows-version>vista
```

Modified to force static

```
<abi>sysv <asio-debugging>off <asserts>off <asynch-exceptions>off <binary-format>elf <boost-link>static <cflags>-I/root/python-libtorrent-build/include <context-impl>fcontext <coverage>off <crypto>openssl <cxxflags>-std=c++14 -fPIC <cxxstd-dialect>iso <cxxstd>14 <debug-iterators>default <debug-symbols>off <define>NDEBUG <define>OPENSSL_NO_SSL2 <define>TORRENT_USE_I2P=1 <define>TORRENT_USE_LIBCRYPTO <define>TORRENT_USE_OPENSSL <define>_WIN32_WINNT=0x0600 <deprecated-functions>on <dht>on <encryption>on <exception-handling>on <export-extra>off <extensions>on <extern-c-nothrow>off <fpic>off <hardcode-dll-paths>true <host-os>linux <i2p>on <iconv>auto <inlining>full <install-dependencies>off <invariant-checks>off <libtorrent-link>static <libtorrent-python-pic>off <libtorrent-python>on <link>shared <linkflags>-L/root/python-libtorrent-build/lib <logging>on <lt-visibility>default <mutable-torrents>on <openssl-version>1.1 <optimization>speed <os>LINUX <pch>on <picker-debugging>off <predictive-pieces>on <preserve-test-targets>on <profile-calls>off <profiling>off <python-debugging>off <python>3.7 <relevant>cflags:<relevant>toolset <relevant>cxxflags:<relevant>toolset <relevant>library:<relevant>crypto <relevant>python.interpreter:<relevant>python <relevant>python.interpreter:<relevant>target-os <rtti>on <runtime-debugging>off <runtime-link>shared <share-mode>on <simulate-slow-read>off <simulator>off <stdlib>native <streaming>on <strip>off <super-seeding>on <suppress-import-lib>false <symlink-location>project-relative <target-os>linux <test-coverage>off <testing.execute>on <threadapi>pthread <threading>multi <toolset-gcc:version>8 <toolset>gcc <use>/python//python_for_extensions <user-interface>console <utp-log>off <variant>release <vectorize>off <warnings-as-errors>off <warnings>on <windows-version>vista
<abi>sysv <asio-debugging>off <asserts>off <asynch-exceptions>off <binary-format>elf <boost-link>static <cflags>-I/root/python-libtorrent-build/include <cflags>-fPIC <cflags>-fvisibility=hidden <context-impl>fcontext <coverage>off <crypto>openssl <cxxflags>-Wno-deprecated-declarations <cxxflags>-fvisibility-inlines-hidden <cxxflags>-std=c++14 -fPIC <cxxstd-dialect>iso <cxxstd>14 <debug-iterators>default <debug-symbols>off <define>NDEBUG <define>OPENSSL_NO_SSL2 <define>TORRENT_USE_I2P=1 <define>TORRENT_USE_LIBCRYPTO <define>TORRENT_USE_OPENSSL <define>_WIN32_WINNT=0x0600 <deprecated-functions>on <dht>on <encryption>on <exception-handling>on <export-extra>off <extensions>on <extern-c-nothrow>off <fpic>off <hardcode-dll-paths>true <host-os>linux <i2p>on <iconv>auto <inlining>full <install-dependencies>off <invariant-checks>off <library>/root/python-libtorrent-build/libtorrent/bindings/python//boost_python3/<link>static/<warnings>off <library>/torrent//crypto <library>/torrent//ssl <library>/torrent//torrent/<link>static <libtorrent-link>static <libtorrent-python-pic>on <libtorrent-python>on <link>shared <linkflags>-L/root/python-libtorrent-build/lib <linkflags>-Wl,-Bsymbolic <logging>on <lt-visibility>hidden <mutable-torrents>on <openssl-version>1.1 <optimization>speed <os>LINUX <pch>on <picker-debugging>off <predictive-pieces>on <preserve-test-targets>on <profile-calls>off <profiling>off <python-debugging>off <python.interpreter>/usr/bin/python3.7 <python>3.7 <relevant>cflags:<relevant>toolset <relevant>cxxflags:<relevant>toolset <relevant>library:<relevant>crypto <relevant>python.interpreter:<relevant>python <relevant>python.interpreter:<relevant>target-os <rtti>on <runtime-debugging>off <runtime-link>shared <share-mode>on <simulate-slow-read>off <simulator>off <stdlib>native <streaming>on <strip>off <super-seeding>on <suppress-import-lib>false <symlink-location>project-relative <target-os>linux <test-coverage>off <testing.execute>on <threadapi>pthread <threading>multi <toolset-gcc:version>8 <toolset>gcc <use>/python//python_for_extensions <user-interface>console <utp-log>off <variant>release <vectorize>off <warnings-as-errors>off <warnings>on <windows-version>vista
```

I also notice the warning gets printed twice and the properties are listed twice.

**Comment by arvidn** [comment]
> Can i just check, do you have boost installed as a dependency via apt-get on this test system?

No, I have the boost source distribution and the `BOOST_ROOT` environment variable pointing to it. Does `apt` install static libraries for boost python at all? I wouldn't expect you to be able to link statically from the apt packages.

**Comment by arvidn** [comment]
actually, the Jamfile won't even attempt to link against `boost_python38.a`, just the shared library. So `boost-link=static` has no effect when building against a pre-built library

**Comment by userdocs** [comment]
I understand the if/else code check and as far as i understand it i have the required properties to force the else condition.

But i get this everything `<library>/root/python-libtorrent-build/libtorrent/bindings/python//boost_python3/<link>shared/<warnings>off `

It appears that somewhere between reading the properties and generating them to `$(result) it gets confused and i cannot see why.

**Comment by arvidn** [comment]
oh, had missed on change in the Jamfile in my patch. When fixing it to *actually* link statically against boost-python on linux, I get this error:

```
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpthread.a(elision-lock.o): .preinit_array section is not allowed in DSO
/usr/bin/ld: failed to set dynamic section sizes: nonrepresentable section on output
collect2: error: ld returned 1 exit status
```

**Comment by arvidn** [comment]
I updated this patch to reflect my change. It's not working though. Is this the change you made too?
https://github.com/arvidn/libtorrent/pull/5048

**Comment by userdocs** [comment]
Ok, i tested it and good news. This patch in https://github.com/arvidn/libtorrent/pull/5048 fixes it.

```
if <boost-link>shared in $(properties) || <target-os>linux in $(properties)
```

Becoming 

```
if <boost-link>shared in $(properties)
```

The if/else now behaves as required with these correct outcomes.

`b2 ... <boost-link>static ` or the lack of `<boost-link>static` conditions to the `else` statement giving this ldd result on the `libtorrent.so`

```
root@localhost:~# ldd python-libtorrent-build/completed/libtorrent.so
        linux-vdso.so.1 (0x00007ffe62ebe000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb39d8c7000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb39d8a6000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb39d8a1000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fb39d89c000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb39d718000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb39d595000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb39d579000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb39d3b8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb39e1fd000)
```

`<boost-link>shared`  conditions to the `if` statement giving this ldd result on the `libtorrent.so`

```
root@localhost:~# ldd python-libtorrent-build/completed/libtorrent.so
        linux-vdso.so.1 (0x00007fffb7b7c000)
        libboost_python37.so.1.74.0 => not found
        libboost_system.so.1.74.0 => not found
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007feba0fb8000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007feba0fb3000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007feba0f92000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007feba0f8d000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007feba0e07000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007feba0c84000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007feba0c6a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007feba0aa9000)
        /lib64/ld-linux-x86-64.so.2 (0x00007feba18c3000)
```

Specifically,

```
        libboost_python37.so.1.74.0 => not found
        libboost_system.so.1.74.0 => not found
```

I admit, i was ignoring the secondary condition of the if for a a couple of reasons, but it seems kinda of obvious now i think about it.

1: i was not using this property as i assumed i would need to set it to trigger this condition.
2:  I wasn't 100% sure i wasn't creating the problem

Looking at the echoed properties i gave above `<target-os>linux` is definitely set automatically so it would trigger this condition and set shared by default.

**Comment by arvidn** [comment]
what is the problem that this patch solves? does your `apt` package of boost_python make a static library available to link against? And does that work on your platform?

As I mentioned earlier, on Ubuntu, it doesn't work to build statically against boost_python. But that's when building boost from source.

The name of a prebuilt boost_python binary is unfortunately a bit difficult to predict. The Jamfile currently hard codes it to `libboost_python37`, you may need to change that name depending on what your package names it.

**Comment by userdocs** [comment]
I don't install boost using apt, i only use the source to code to either build the static libs or in this particular example, just use the build files to build the python binding.

Attached are two build on Ubuntu xenial and focal x64 that have boost_python statically linked and should work with deluge on a fresh system install (vm)

```
root@localhost:~# ldd python-libtorrent-build/completed/libtorrent.so
        linux-vdso.so.1 (0x00007ffe63b5f000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f03411a5000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0340fc4000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0340fa9000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0340db7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0341b5f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0340c68000)
```

I built on xenial and ran on a focal, for example and the only thing installed was deluged using `pip3`

Can you confirm these files are indeed statically linked so we are not talking about something different?

[libtorrent-xenial.zip](https://github.com/arvidn/libtorrent/files/5137539/libtorrent-xenial.zip)
[libtorrent-focal.zip](https://github.com/arvidn/libtorrent/files/5137541/libtorrent-focal.zip)

**Comment by arvidn** [comment]
that `ldd` output looks right for a statically linked module

**Comment by arvidn** [comment]
so you think this patch is an improvement, right?

**Comment by userdocs** [comment]
I guess it depends if we have established it is possible to statically link it, if yes then and as i now understand the issue it would resolve the two parts of the error i was experiencing.

Part one was this error based on this check `if <boost-link>static in $(properties) && <target-os>linux in $(properties)`

https://github.com/arvidn/libtorrent/blob/RC_1_2/bindings/python/Jamfile#L125#L128

Part two was the OR part of this check `if <boost-link>shared in $(properties) || <target-os>linux in $(properties)` always returning a positive match due to be automatically set forcing the library to be set to shared.

https://github.com/arvidn/libtorrent/blob/RC_1_2/bindings/python/Jamfile#L150#L168

So with those two issue fixed it appears demonstrably build (attached files) python binding with boost_python statically linked.

The only part i am unsure about is why you had a build error and i don't.

**Comment by arvidn** [comment]
> The only part i am unsure about is why you had a build error and i don't.

It sounds like you're building the `libboost_python.a` library separately, first. I think the issue happens when building libboost_python as part of the whole python module. When building boost_python with `<link>static`, I believe that also affects how boost_python itself links against its dependencies. Specifically `libatomic`, which it may try to link against statically, which won't work.

**Comment by userdocs** [comment]
You can see exactly what is happening from my build by using an ubuntu/debian VM and running this script.

https://gist.githubusercontent.com/userdocs/4dd1975b06482211ff3c15ffd263db57/raw/95974137671483ff4d52904c93fd64106fe3d8c0/pyhton_binding.sh

By running the script with this argument.

```
./scriptname.sh all
```

It includes the patched `Jamfile`  and will produce a `libtorrent.a` statically linked to `boost_python` in the directory `$HOME/python-libtorrent-build/completed` upon completion. It takes me 8 minutes on a 4 CPU VM to build.

I think it will help you understand exactly what i am and am not doing in this build process and the relevance of the patch to that process.

**Comment by arvidn** [comment]
I see, you *are* building boost from source as part of the same `b2` invocation. perhaps there's something in your `CXXFLAGS` or `LDFLAGS` that might make a difference.

**Comment by joriscarrier** [comment]
hi, i've fix boost build with (https://github.com/boostorg/build/pull/581/files) it has been merged in 1.74.0

**Comment by userdocs** [comment]
What does that fix do?

**Comment by arvidn** [comment]
@userdocs it makes pthread be linked dynamically unconditionally on linux, which fixes the link error you would get otherwise.

**Comment by arvidn** [comment]
I think this issue has been addressed now
