### ISSUE TITLE
Python Bindings - Resume Data

### ISSUE THREAD

**Issue by latot** [arvidn/libtorrent#5046]
Hi hi, i'm Trying to use the resume data in python bindings, is in the same way as the client example (that large client example), sadly there is an error, I'm using this:

```
        params.ti = lt.torrent_info(torrent)
        params.flags |= lt.storage_mode_t.storage_mode_allocate \
        | lt.torrent_flags.upload_mode \
        | lt.torrent_flags.super_seeding
        lt.flag_override_resume_data = True
        params.resume_data = readfile(r, "rb")
```

The ```readfile``` function just, open, read all the file, close the file and return the data, basically we load the data in the same way as the example, but i'm getting this error:

```
Boost.Python.ArgumentError: Python argument types in
    None.None(add_torrent_params, bytes)
did not match C++ signature:
    None(libtorrent::add_torrent_params {lvalue}, libtorrent::aux::noexcept_movable<std::vector<char, std::allocator<char> > >)
```

I know I'm passing bytes, but i really don't get why fails or if is a bug.

Thx.

**Comment by arvidn** [comment]
I imagine there's no python converter for `bytes` -> `std::vector<char>`

**Comment by arvidn** [comment]
The `resume_data` field is deprecated in `add_torrent_params`, the way you're encouraged to load resume data is by using the `read_resume_data()` function, which takes a buffer and returns an `add_torrent_params` object. ([docs](http://libtorrent.org/reference-Core.html#read_resume_data())).

I can reproduce this issue, but I'm a bit hesitant to spend too much time addressing it, since it's a deprecated field already. Fundamentally the issue is about there not being a custom from_python converter (in `src/converters.cpp`) to perform this conversion from bytes to a vector of chars. It's possible you could work around it by "exploding" your bytes into a list of chars on the python side.

**Comment by arvidn** [comment]
are you using libtorrent 1.2.x btw?

**Comment by latot** [comment]
Hi hi :3 

Thx, if is deprecated or will be I prefer don't use it, i'll just use the function you tell me, actually i'm using the version 1.2.6.

I would recommend update the example to avoid use deprecated functions.

I have two questions if you can answer me please, i was reading the ```add_torrent_params.hpp```, and the ```torrent_flags```  is deprecated too, so, how the options now can be set?, actually in the doc still says use the ```torrent_flags```.

The other, newbie question maybe, if I want use a flag we use the or operator ```atp.flags |= lt.torrent_flags.duplicate_is_error```, so, if i want to disable the flag i must use the and operator?  ```atp.flags &= lt.torrent_flags.duplicate_is_error```

Thx.

**Comment by arvidn** [comment]
> I would recommend update the example to avoid use deprecated functions.

Oh, yeah, I don't look much at the python examples.

> The other, newbie question maybe, if I want use a flag we use the or operator atp.flags |= lt.torrent_flags.duplicate_is_error, so, if i want to disable the flag i must use the and operator? atp.flags &= lt.torrent_flags.duplicate_is_error

to clear a bit, you AND the value with the complement of the bit. So:

```
atp.flags &= ~lt.torrent_flags.duplicate_is_error
```

**Comment by arvidn** [comment]
apparently bitwise NOT is not trivial in python. the `~` operator is what you would use in C++

**Comment by latot** [comment]
Thx!, I was confused with that, the NOT operator and | was sending errors, and now works.

Actually, how can we set the flags without ```torrent_flags```?.  actually seems to be deprecated (add_torrent_params.hpp):

```
#define DECL_FLAG(name) \
		static constexpr torrent_flags_t TORRENT_DEPRECATED_MEMBER flag_##name = torrent_flags::name
```

Thx.

**Comment by arvidn** [comment]
the torrent flags moved here: https://github.com/arvidn/libtorrent/blob/RC_1_2/include/libtorrent/torrent_flags.hpp

**Comment by latot** [comment]
Thx!, so i was confused :3

Don't worry trying to fix ```resume_data```, lets just use the actual functions.

Thx.
