### ISSUE TITLE
(Windows) libtorrent-1.1.14 low download speed

### ISSUE THREAD

**Issue by southernedge** [arvidn/libtorrent#5050]
**Please provide the following information**

libtorrent version (or branch): libtorrent-1.1.14

platform/architecture: Windows

compiler and compiler version: VC2013

	Hello!
	
	I am trying to add libtorrent-1.1.14 library support into my software (C++).
	Here's a little trivial software code. 

```
	const int mask = lt::alert::error_notification |	lt::alert::status_notification;
	lt::settings_pack settings;
	settings.set_int( lt::settings_pack::alert_mask, mask );
	lt::session session( settings );
	lt::add_torrent_params atp;
	atp.ti = ti;
	lt::torrent_handle th = session.add_torrent( atp );
```

       It works!

	But in detailed testing, it works 5-6 times slower than uTottent and Tixati.
	My test shows speed ~1.2Mb/sec, but uTottent, Tixati ~6-8Mb/sec.
	I'm testing with this line 
	https://windows64.net/dow.php?url=https://windows64.net/engine/download.php?id=378
	file about 5GB.
	
	What could be the reason?
	Many thanks for your support!

**Comment by arvidn** [comment]
I would suggest you use a more recent version of libtorrent. I assume you're using a release build for this test.

To understand what the bottleneck is, you can subscribe to performance_warning_alert and see if you get any of those, you may need to increase buffer sizes, use more disk threads, increase the number of peer connections you allow or increase your disk cache size. All is done via `settings_pack`.

If you find some default setting that should be changed, please let me know. But only for a recent release (say, 1.2.9)

**Comment by southernedge** [comment]
Thank you for your advice! I'm gonna try this.
I wouldn't want to use a later version of your build, as it entails switching to a later version of the compiler (if I have got it right in libtorrent builds :)). I use VC2013 for all projects.

**Comment by southernedge** [comment]
I have some intermediate results of the test

1.  This setting allows to speed up 2.5 times up to 3-3.5 MB\s but it is still significantly lower than uTorrent, FDM3

`settings.set_int( lt::settings_pack::recv_socket_buffer_size, 1 * 1024 * 1024 );`

The following settings are no visible impact on download speed
```
lt::settings_pack::cache_size
lt::settings_pack::aio_threads
lt::settings_pack::aio_max
lt::settings_pack::network_threads
```

Perhaps there are some settings that I missed?


2. As there is a permanent error, which I can not escape

```
for ( lt::alert const* a : alerts ) 
{
  ...
  a->message();
  ...
}
```

`ru_windows_10_version_2004_updated_june_2020_x64_dvd.iso open (C:\DOWNLO~1\Torrents\ru_windows_10_version_2004_updated_june_2020_x64_dvd.iso) error: The process cannot access the file because it is being used by another process`

it is like https://github.com/arvidn/libtorrent/issues/3532

Arvid, you have any ideas?

**Comment by arvidn** [comment]
one setting you should look at also is [max_out_request_queue](http://libtorrent.org/reference-Settings.html#max_out_request_queue).

I take it you don't have another process opening that file, right? you think it's libtorrent opening it twice?
You could look in storage.cpp, and file.cpp to ensure files are always opened in share mode.

Are you stll on libtorrent 1.1.x btw?

**Comment by southernedge** [comment]
**_I take it you don't have another process opening that file, right?_**
The software structure
myexe->mydll->libtorent.1.1.4
mydll asks the download status in a loop and sends the data to myexe.
myexe does not open and does not check the status of a file download to complete.

**_you think it's libtorrent opening it twice?_**
dont know... :(

if I stop lintorrent download and restart it again then downloads continue again. Obviously, the stopping of libtorrent is correct and libtorrent does not lock files.

**_Are you stll on libtorrent 1.1.x btw?_**
1.1.4.  
Now I can not change the version of the compiler for the latest libtorrent because my project use 2013 in the current time.

**Comment by arvidn** [comment]
although libtorrent isn't supposed to be tripping over itself, there's a chance this is a bug in libtorrent causing this. Especially windows, I don't manually test there very much.

If you could catch this error in a debugger (you could probably set a breakpoint on any error from opening a file). You could see if the process has the file open already (some windows equivalence of `lsof`).

**Comment by arvidn** [comment]
btw. you can resume a torrent that has failed programatically. call `clear_error()` on the torrent handle, and then resume the torre

**Comment by southernedge** [comment]
Hello, Arvid!

I believe the ERROR_SHARING_VIOLATION issue has been solved.

A periodic call of the ExtractIconEx function in the base program caused an error in libtorrent.
I'm not sure that libtorrent should stop downloading the file in this case, because the next moment the file will be unlocked.
But you owner of the libtorrent project and decision is on you.

Now I'm gonna try to increase the download speed again. ~3MB is low compared to other torrent clients.

Thank you for your help!

**Comment by arvidn** [comment]
> A periodic call of the ExtractIconEx function in the base program caused an error in libtorrent.
> I'm not sure that libtorrent should stop downloading the file in this case, because the next moment the file will be unlocked.

I would be hesitant to add logic to libtorrent to recognise this specific kind of error, and periodically try again.

This is how windows works, by default files are opened in exclusive mode, I think it's primarily an "issue" with windows (or something one has to be aware of as a windows programmer).

**Comment by Seeker2** [comment]
Antivirus software could be making its rounds in scanning files and lock files for exclusive access while it's doing it?

**Comment by arvidn** [comment]
@Seeker2 which would break all kinds of things on windows. Or, from the makers of such hypothetical anti-virus, working as intended; since presumably they *meant* to open files with exclusive access, breaking all other applications trying to access them.

It's not obvious to me it makes sense to fight the natural order of how windows works.
Clearly Microsoft thinks this is a good default, and if a program opens a file in exclusive mode they presumably really want other processes to fail to open the file. libtorrent only opens files in shared mode, because I think that makes sense, to allow other processes to read them while downloading.

**Comment by Seeker2** [comment]
So antivirus software not a likely cause then...malware then?

**Comment by arvidn** [comment]
I assume the cause for the error was:

> A periodic call of the ExtractIconEx function in the base program caused an error in libtorrent.

**Comment by southernedge** [comment]
Arvid, is this a correct algorithm of actions to maximize downloadind speed (except for the ability to manipulate download parameters settings_pack())?
- if the download speed of the default tracker is unsatisfactory, the app should select to the next tracker with using force_reannounce()
- the app should try all the trackers and find the maximum download speed.
- select this tracker as the main with force_reannounce()

**Comment by arvidn** [comment]
if the problem is that you don't have enough peers, you probably want to be sure you have the DHT enabled first.

If you still don't have enough peers, then yes, you can be more aggressive in announcing to trackers. However, that's not really what `force_reannounce()` is meant for. You can configure libtorrent to be more aggressive. You can set [announce_to_all_tiers](http://libtorrent.org/reference-Settings.html#announce_to_all_tiers) to true.

I would also encourage you to subscribe to (i.e. enable in `alert_mask`) and print performance warning alerts.

**Comment by Seeker2** [comment]
If the torrents in question are public torrents, quite likely many of the trackers share the same list of peers+seeds.
Peer EXchange (plus DHT and to a lesser degree LPD) join together groups of peers+seeds from different trackers.

So even before you add any trackers, you probably already get a lot of peer+seed connections.
...But if your BitTorrent app is firewalled, you will get far fewer connections.

**Comment by southernedge** [comment]
Seeker2, 
my question in that I can get the file download speed (the torrent link in the start post) with default libtorrent settings 1.4MB.
If I increase `lt::settings_pack::recv_socket_buffer_size` up to 1MB then I get the speed 2.5-3.4MB
At the same time, the FDM3 (it also uses libtorrent) gives you speed 7.7MB and more.
I don't think it's only achieved by varying parameters in` lt::set_int()`. 
Obviously, there's some sort of tracker algorithm I'm trying to figure out...

**Comment by Seeker2** [comment]
My bad, after foolishly assuming antivirus/malware...seems my guess of potentially firewalled conditions (and lacking "sufficient" peers+seeds) isn't a cause at all either.

What's left as a possibility besides trackers?
...because those don't set speeds in any way as far as I know.

**Comment by southernedge** [comment]
Arvid,

I assume the low performance (slow download and overload CPU) issue has been solved.
The libtorrent debug build does not allow you to properly evaluate the performance of the torrent download.
This is important and should be mentioned somewhere for developers.
I put together a release project, it showed download speed in 3! times higher (2-3MB and 8-9MB!) than the test debug build.  
Honestly, I didn't expect such a difference.

Thank you for your support and your wonderful work!
