### ISSUE TITLE
RC_2_0 branch build fails with boost 1.74

### ISSUE THREAD

**Issue by lgbaldoni** [arvidn/libtorrent#5051]
**Please provide the following information**

> libtorrent version (or branch):

RC_2_0

> platform/architecture:

openSUSE Linux Tumbleweed x86_64

> compiler and compiler version:

gcc 10.2

> please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

See complete [build log](https://github.com/arvidn/libtorrent/files/5137826/libtorrent_RC_2_0-boost174.txt).

**Comment by userdocs** [comment]
I tried it as well and got a couple of errors. Here is my build log.

[libtorrent.log.txt](https://github.com/arvidn/libtorrent/files/5139139/libtorrent.log.txt)

**Comment by arvidn** [comment]
here's a fix. please give it a try!

https://github.com/arvidn/libtorrent/pull/5057

**Comment by userdocs** [comment]
It worked for me by patching in those changes.

[libtorrent.log.txt](https://github.com/arvidn/libtorrent/files/5142075/libtorrent.log.txt)

[libtorrent-2.0-RC3.zip](https://github.com/arvidn/libtorrent/files/5142076/libtorrent.zip)

**Comment by lgbaldoni** [comment]
Works for me.

**Comment by arvidn** [comment]
thanks for reporting and testing!
