### ISSUE TITLE
Where is request_time_critical_pieces function?

### ISSUE THREAD

**Issue by zim32** [arvidn/libtorrent#5053]
**Please provide the following information**

libtorrent version (or branch): RC_1_2

platform/architecture: x86_64 x86_64 x86_64 GNU/Linux

compiler and compiler version: gcc version 7.5.0 

Can not find request_time_critical_pieces function mentioned in streaming documentation. Where it is, how should I call it?

**Comment by master255** [comment]
@zim32 The truth is here https://github.com/arvidn/libtorrent/issues/4408

**Comment by arvidn** [comment]
http://libtorrent.org/reference-Core.html#set_piece_deadline()

**Comment by arvidn** [comment]
@zim32 that document is describing the implementation of streaming. The link I posted to `set_piece_deadline()` is the user facing API. The internal function is called request_time_critical_pieces(), and you can find that [here](https://github.com/arvidn/libtorrent/blob/RC_1_2/src/torrent.cpp#L9920).

**Comment by zim32** [comment]
Figured out. Tanks
