### ISSUE TITLE
DHT store mutable item?

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#5058]
@arvidn  How is this supposed to work?
Is there perhaps a code sample? I looked at the tests - there's nothing like that.
Here's my code. I get a message: "DHT mutable item (key=c706084eb172387a8cf125d19656a4ebfe7c2745f09fae9e384fb679d7c51954 salt=hamburger seq=0 auth) [ uninitialized ]" in alert DHT_MUTABLE_ITEM. 
What am I doing wrong?

`case DHT_BOOTSTRAP:
                                publicHandler.postDelayed(() -> {
                                    entry data = new entry("hello world333");

                                    byte_vectors_pair s1 = ed25519_create_keypair(ed25519_create_seed());
                                    byte_vector salt = Vectors.bytes2byte_vector("salt".getBytes(Constants.TORRENT_CHARSET));

                                    torrentSession.dht_put_item(s1.getFirst(), s1.getSecond(), data, salt);

                                    publicHandler.postDelayed(() -> {

                                        torrentSession.dht_get_item(s1.getFirst(), salt);

                                    }, 10000);

                                }, 5000);

                                break;`

**Comment by arvidn** [comment]
here's an example:https://github.com/arvidn/libtorrent/blob/RC_1_2/tools/dht_put.cpp

you want to make sure bootstrapping completes (and succeeds) before storing the item, and you want to make sure the store completes before trying to look it up

**Comment by master255** [comment]
@arvidn Okay. Thank you, maestro, for the library.
It's working fine.
Your instructions are very unclear. Now you have a better manual :-)

I'll explain to everyone what to do to make it work:
1. We wait for the DHT_BOOTSTRAP event and as soon as it comes, we launch the dht_put_item.
2. Wait for event DHT_PUT with success > 0. When it comes, we run the dht_get_item with the public key and salt.
3. Receive sent data in event DHT_MUTABLE_ITEM. Done.

**Comment by arvidn** [comment]
> Your instructions are very unclear.

It sounds like you expect me to write your code for you.
Evidently, my instructions were clear enough for you to understand them.

> Now you have a better manual :-)

I don't think I understand, are you preparing a PR to improve the documentation?

**Comment by master255** [comment]
@arvidn 

> It sounds like you expect me to write your code for you.

No. My instructions are not code. It's what is needed to write the code.

> Evidently, my instructions were clear enough for you to understand them.

No. Your instructions didn't help me at all. I figured out how it works myself. Because I have my own DHT library implementation.

> I don't think I understand, are you preparing a PR to improve the documentation?

I don't think you'll accept my PR. You have your own style of writing instructions. With a Google, programmers will find this issue and read it. That's how I help them.

And thank you for the many instructions on libtorrent.org. I read them a lot and they helped me a lot.

**Comment by master255** [comment]
@arvidn news from my player. Every day I watch torrent movies and distribute them from 60Gb traffic. The distribution works even when the TV is off. My player is the only one in the world that can do that.
