### ISSUE TITLE
Best way to play music?

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#5068]
@arvidn For example: I have a torrent with 5 music tracks.
I play the first track. It completely downloads and plays. At that moment it is disconnected from the peers that gave me the first track and the distribution of the first track begins.
Then I want to start the second track, but the problem is that the connections with the peers are already closed and I have to look for them again and try to connect. It takes more than a minute, how to not disconnect from the peers if all files from the torrent are not downloaded?

**Comment by arvidn** [comment]
there's a setting to not disconnect redundant peers. But those peers are quite likely to consider you redundant too, and disconnect you (unless you're still interested in any more pieces)

**Comment by master255** [comment]
@arvidn Okay. It works, but there are two problems:
1. The speed increases very slowly from the moment the download starts (slow congestion control). Is there a setting how to speed it up?
2. If the whole file is in the ".parts" file, there is no event when it is completely written to disk, when changing the priority of the file. What can I do with it? I need this event, because immediately after setting the file priority, there is no file. What is the maximum size of a ".parts" file?

**Comment by master255** [comment]
@arvidn where is my answer?

**Comment by arvidn** [comment]
>     The speed increases very slowly from the moment the download starts (slow congestion control). Is there a setting how to speed it up?

Maybe, but to know which one, you first need to understand what's happening. You can analyze various metrics [like this](https://libtorrent.org/tuning-ref.html#profiling).

>     If the whole file is in the ".parts" file, there is no event when it is completely written to disk, when changing the priority of the file. What can I do with it? I need this event, because immediately after setting the file priority, there is no file. What is the maximum size of a ".parts" file?
>

**Comment by master255** [comment]
> I think the part file can hold 2 billion blocks iirc, I think you'd hit other limits before that.

This can significantly increase the duration of the file creation operation.
Moreover, it is necessary to have an event for this purpose.
Now I have set the wait for 1 second. But sometimes it is not enough to create a file of 50 Mbytes.

**Comment by master255** [comment]
@arvidn  I think this is a bug.

**Comment by arvidn** [comment]
> @arvidn I think this is a bug.

What does "this" refer to in that sentence?

**Comment by master255** [comment]
@arvidn We need an alert in order to know when the file will be written to disk. Without the alert we cannot know it.

**Comment by arvidn** [comment]
I believe you can poll the file priorities. I don't think they are updated until the disk operation completes.
but also, patches are welcome.

**Comment by master255** [comment]
@arvidn Thank you for your answers and work.
