### ISSUE TITLE
Torrent disabled ip filter after old libtorrent upgrade to libtorrent 1.2.7 or newer

### ISSUE THREAD

**Issue by c0re100** [arvidn/libtorrent#5074]
**Please provide the following information**
libtorrent version (or branch):
`RC_1_2`

Extra info: 
qBittorrent version (or branch):
`master`

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Problem related to #4642
If I added 1 torrent in libtorrent 1.2.6, and upgraded to 1.2.7 or newer.
This torrent's IP Filter will be disabled after upgrade.
Since 1.2.6 resume data do not have `apply_ip_filter` field
After upgrade >=1.2.7
https://github.com/arvidn/libtorrent/blob/7732deb5c865ddca1c752ba8be18b1155c4c1731/src/read_resume_data.cpp#L159
Field `apply_ip_filter` default to `0`
All torrent setting save to torrent resume data and disable this torrent's ip filter.
Cause `apply_ip_filter` is 0, then you can't ban peer in this torrent.
No problem if you add new torrent in libtorrent >=1.2.7 (`apply_ip_filter` set to 1 in my test.)
Also, no problem if I reverted #4642.

1.2.6 upgrade to 1.2.9
![{6CF32B3A-9326-411B-88EA-0EEB28D1F53A}](https://user-images.githubusercontent.com/5726473/91672934-f7ce3f00-eb63-11ea-9805-b10c99431721.png)
1.2.9 new torrent
![{D117AF49-A1AD-4F2C-A61F-CE7C9A216A30}](https://user-images.githubusercontent.com/5726473/91672942-00bf1080-eb64-11ea-84af-69a138851b46.png)
you can see upgraded resume data, field `apply_ip_filter` set to `0`.

qBittorrent is using libtorrent's global IP Filter, it can't set single torrent's IP Filter on or off.
If a user want to enable global ip filter, user have only one way: edit each resume data `apply_ip_filter` to 1.

Expect behaviour:
I think libtorrent should set `apply_ip_filter` to 1 by default in `read_resume_data` stage if a user upgraded libtorrent.

**Comment by arvidn** [comment]
thanks for the report! I believe this change will fix it. Can somebody verify?
https://github.com/arvidn/libtorrent/pull/5081

**Comment by c0re100** [comment]
> thanks for the report! I believe this change will fix it. Can somebody verify?
> #5081

It works!
Field `apply_ip_filter` set to 1 now.
Thank you~
