### ISSUE TITLE
If I Make a Change to a Torrent

### ISSUE THREAD

**Issue by ki4jgt** [arvidn/libtorrent#5082]
If I make a change to a torrent directory, and send my users the new .torrent, will they have to download everything again, or just the parts that I've changed?

**Comment by master255** [comment]
@ki4jgt If you created torrent with alignment for files, only the changes are downloaded.
If not, the entire torrent will be downloaded again.
Old files are not deleted during the download process.

**Comment by arvidn** [comment]
@ki4jgt you have to specify the info hash of the previous torrent in the "similar torrents" list, in your new torrent. Alternatively, you can specify the same name of the "collection" field of *both* torrents.
