### ISSUE TITLE
Granular file recheck

### ISSUE THREAD

**Issue by lauyuen** [arvidn/libtorrent#5083]
**Please provide the following information**

libtorrent version (or branch):
N/A
platform/architecture:
N/A
compiler and compiler version:
N/A
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
N/A

This is a feature request/enhancement.
Quite often, my colleagues and I download hundreds of GBs of dataset for ML, sometimes even TBs per torrent, and sometimes each torrent would have thousands of files. It's sometimes impossible to recheck all the files due to time or storage space constraints. It would be amazing if I could only check the data I need. 

Related qB issue: https://github.com/qbittorrent/qBittorrent/issues/12972

**Comment by arvidn** [comment]
what would happen to the pieces that you don't want to check? be assumed that you don't have them?

**Comment by lauyuen** [comment]
Thanks for the response! It's a good question. I can't speak for the general case but for my use case, the pieces I don't want to check are usually data I know that are good, processed, or on rare occasions, parts of the dataset that I don't need. So it's safe for me to ignore them.
