### ISSUE TITLE
BEP 31: Failure Retry Extension

### ISSUE THREAD

**Issue by HDVinnie** [arvidn/libtorrent#5084]
### libtorrent version (or branch): 
v1.2.6.0

### platform/architecture:
MacOS 10.14.6 (18G87)
qBittorrent v4.2.5 (64 Bit)

### What is the problem
libtorrent does not respect BEP 31: Failure Retry Extension
https://www.bittorrent.org/beps/bep_0031.html

### What is the expected behavior
For libtorrent to respect the `retry in` flag.

**Comment by HDVinnie** [comment]
@arvidn any plans to add this?

**Comment by arvidn** [comment]
not really. I don't see a reason to have a new way of specifying the announce interval. I'm curious to know if you have any good reasons.

**Comment by HDVinnie** [comment]
Its perfect for a tracker maintenance interval.

**Comment by arvidn** [comment]
I'm suggesting that you can send a `failure reason` *and* an `interval` field. The interval field already means "announce again in this many seconds"
