### ISSUE TITLE
Question about removing pieces from custom storage

### ISSUE THREAD

**Issue by zim32** [arvidn/libtorrent#5086]
I've implemented custom storage interface. It stores pieces in RAM. When my buffer  is filled I want to remove some pieces from my storage. So I delete piece from my storage and then all reads of this piece return zero (0)

The question is do I need to do something else, or libtorrent will handle such missed pieces? Should I notify libtorrent about deleted piece somehow?

Thanks.

**Comment by arvidn** [comment]
> The question is do I need to do something else, or libtorrent will handle such missed pieces? Should I notify libtorrent about deleted piece somehow?

Libtorrent will "handle" it by possibly failing the hash of a piece and re-downloading it (and possibly attribute the corruption to the peer the block was downloaded from). It will also send corrupt data (i.e. zeros) to other peers.

There is no feature to tell libtorrent that a specific piece is now gone. I imagine it could be done by adding a function to `torrent_handle`, `remove_piece(piece_index_t)`, which updates all the accounting in the piece picker (and possibly creates the piece picker again, if we're a seed). It would also have to `write_dont_have()` to all peers.

It may also need to trigger a state update from `finished` -> `downloading` and trigger requesting that missing piece again from peers.

I imagine that in your case, you would like to set the piece priority to 0 as well, to avoid re-downloading the piece when you remove it.

**Comment by zim32** [comment]
So if I remove piece from my storage some bad things could happen?

**Comment by arvidn** [comment]
what can happen is that peers may request it from you, and the bittorrent engine will then request it from your storage. If your storage returns zeros, peers will receive zeros from you and disconnect and ban you because you sent corrupt data.
One aspect of this problem is that the bittorrent engine will still believe you to have those pieces, so it will keep advertise them and peers will keep asking for them.

**Comment by zim32** [comment]
I am not returning zeroes. I just did not fill buffers with data and return 0 as the result of  int readv(...) functoin call, meaning I didn't read any byte at all.

**Comment by zim32** [comment]
But I can not figure out the semantics of returning 0 bytes read. Will engine mark my piece as bad and try to redownload it, or it will try to read it again

**Comment by arvidn** [comment]
I would expect it to treat that as a disk failure and stop the torrent (and disconnect all peers)
