### ISSUE TITLE
V758 [CWE-416] The 'tree_file' reference becomes invalid...

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#5091]
libtorrent version (or branch): master

V758 [CWE-416] The 'tree_file' reference becomes invalid when temporary object returned by a function is destroyed. create_torrent.cpp 733

			if (make_v2 && !info.find_key("file tree"))
			{
				auto& tree_file = info["file tree"][m_files.name()].dict()[{}];
				tree_file["length"] = m_files.file_size(first);
				tree_file["pieces root"] = m_fileroots[first];
			}

**Comment by arvidn** [comment]
can you explain what the problem is? which object becomes invalid?
