### ISSUE TITLE
V826 Consider replacing the 'prev_opt_unchoke' std::vector with std::list.

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#5092]
libtorrent version (or branch): master

V826 Consider replacing the 'prev_opt_unchoke' std::vector with std::list. Overall efficiency of operations will increase. session_impl.cpp 4013

		// collect the currently optimistically unchoked peers here, so we can
		// choke them when we've found new optimistic unchoke candidates.
		std::vector<torrent_peer*> prev_opt_unchoke;
			if (pi->optimistically_unchoked)
			{
				prev_opt_unchoke.push_back(pi);
			}

		auto const existing =
			std::find(prev_opt_unchoke.begin(), prev_opt_unchoke.end(), pi);
			TORRENT_ASSERT(existing != prev_opt_unchoke.end());
			prev_opt_unchoke.erase(existing);

**Comment by ssiloti** [comment]
That's a...dubious suggestion. Better would be to replace the `erase` call with the swap-with-back-and-pop pattern.

**Comment by adzm** [comment]
a vector will outperform a list here in general simply due to the cpu cache.
