### ISSUE TITLE
Cannot move torrent to another directory

### ISSUE THREAD

**Issue by perfect7gentleman** [arvidn/libtorrent#5095]
- libtorrent version (or branch): RC1_2
- platform/architecture: Gentoo/AMD64
- compiler and compiler version: gcc version 10.2.0 (Gentoo 10.2.0-r1 p2)
CFLAGS="-march=native -mtune=native -O3 -pipe -fdevirtualize-at-ltrans -fgraphite-identity -fipa-pta -flto=9 -floop-interchange -floop-nest-optimize -floop-parallelize-all -fomit-frame-pointer -fuse-linker-plugin -fno-plt -fno-semantic-interposition -fno-stack-protector -s"

- how to reproduce it.
1. Open Deluge-GTK
2. Try to move downloaded torrent to another directory
```

 ~ $ deluge-gtk 
23:50:50.280 [ERROR   ][deluge.ui.client                                   :169 ] RPCError Message Received!
--------------------------------------------------------------------------------
RPCRequest: core.move_storage(['a41460d9bd7c65db83bdbcfa894b2e13569b62fe'], /home/DISK1_/DIR_1)
--------------------------------------------------------------------------------
ArgumentError
Python argument types in
    torrent_handle.move_storage(torrent_handle, str)
did not match C++ signature:
    move_storage(libtorrent::torrent_handle {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > path, libtorrent::move_flags_t flags=libtorrent.move_flags_t.always_replace_files): Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/deluge/core/torrent.py", line 1250, in move_storage
    self.handle.move_storage(dest.encode('utf8'), flags=2)
Boost.Python.ArgumentError: Python argument types in
    torrent_handle.move_storage(torrent_handle, bytes)
did not match C++ signature:
    move_storage(libtorrent::torrent_handle {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > path, libtorrent::move_flags_t flags=libtorrent.move_flags_t.always_replace_files)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/deluge/core/core.py", line 692, in move_storage
    if not self.torrentmanager[torrent_id].move_storage(dest):
  File "/usr/lib/python3.9/site-packages/deluge/core/torrent.py", line 1252, in move_storage
    self.handle.move_storage(dest, flags=2)
Boost.Python.ArgumentError: Python argument types in
    torrent_handle.move_storage(torrent_handle, str)
did not match C++ signature:
    move_storage(libtorrent::torrent_handle {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > path, libtorrent::move_flags_t flags=libtorrent.move_flags_t.always_replace_files)

--------------------------------------------------------------------------------
Unhandled error in Deferred:
23:50:50.280 [CRITICAL][twisted                                            :154 ] Unhandled error in Deferred:

Traceback (most recent call last):
Failure: deluge.error.WrappedException: Python argument types in
    torrent_handle.move_storage(torrent_handle, str)
did not match C++ signature:
    move_storage(libtorrent::torrent_handle {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > path, libtorrent::move_flags_t flags=libtorrent.move_flags_t.always_replace_files)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/deluge/core/torrent.py", line 1250, in move_storage
    self.handle.move_storage(dest.encode('utf8'), flags=2)
Boost.Python.ArgumentError: Python argument types in
    torrent_handle.move_storage(torrent_handle, bytes)
did not match C++ signature:
    move_storage(libtorrent::torrent_handle {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > path, libtorrent::move_flags_t flags=libtorrent.move_flags_t.always_replace_files)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/deluge/core/core.py", line 692, in move_storage
    if not self.torrentmanager[torrent_id].move_storage(dest):
  File "/usr/lib/python3.9/site-packages/deluge/core/torrent.py", line 1252, in move_storage
    self.handle.move_storage(dest, flags=2)
Boost.Python.ArgumentError: Python argument types in
    torrent_handle.move_storage(torrent_handle, str)
did not match C++ signature:
    move_storage(libtorrent::torrent_handle {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > path, libtorrent::move_flags_t flags=libtorrent.move_flags_t.always_replace_files)


23:50:50.280 [CRITICAL][deluge.log                                         :93  ] twisted.internet.defer 
[Failure instance: Traceback (failure with no frames): <class 'deluge.error.WrappedException'>: Python argument types in
    torrent_handle.move_storage(torrent_handle, str)
did not match C++ signature:
    move_storage(libtorrent::torrent_handle {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > path, libtorrent::move_flags_t flags=libtorrent.move_flags_t.always_replace_files)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/deluge/core/torrent.py", line 1250, in move_storage
    self.handle.move_storage(dest.encode('utf8'), flags=2)
Boost.Python.ArgumentError: Python argument types in
    torrent_handle.move_storage(torrent_handle, bytes)
did not match C++ signature:
    move_storage(libtorrent::torrent_handle {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > path, libtorrent::move_flags_t flags=libtorrent.move_flags_t.always_replace_files)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/deluge/core/core.py", line 692, in move_storage
    if not self.torrentmanager[torrent_id].move_storage(dest):
  File "/usr/lib/python3.9/site-packages/deluge/core/torrent.py", line 1252, in move_storage
    self.handle.move_storage(dest, flags=2)
Boost.Python.ArgumentError: Python argument types in
    torrent_handle.move_storage(torrent_handle, str)
did not match C++ signature:
    move_storage(libtorrent::torrent_handle {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > path, libtorrent::move_flags_t flags=libtorrent.move_flags_t.always_replace_files)
]
```

**Comment by arvidn** [comment]
this was addressed in https://github.com/arvidn/libtorrent/pull/5093
deluge use an integer instead of the enum, and I failed to provide a backwards compatible conversion from integers to the enum.
I think deluge should be updated to use the named enum too though.

**Comment by perfect7gentleman** [comment]
Fixed. Thanx.

**Comment by mhertz** [comment]
Thanks Arvid. Just a quick question. Not important, but I was just curious about why that patch/commit is only needed on linux, but not windows? I mean that the issue in deluge reported here, doesn't happen on windows, with same deluge, python and libtorrent version. On windows, libtorrent is built by myself with msvc 2019. As said, just curious :)

**Comment by arvidn** [comment]
> Thanks Arvid. Just a quick question. Not important, but I was just curious about why that patch/commit is only needed on linux, but not windows?

It's a bit subtle. The `move_storage` function is overloaded, there's an (old) overload that takes a wide character string (`wstring`) which is internally turned to UTF-8 (which all narrow strings are assumed to be in libtorrent). This overload was deprecated a long time ago. However, deprecation warnings isn't really a thing in python, so I expect python programs to not take notice. (I'm open to suggestions for what can be done about this).

the `move_storage()` function also takes a second (optional) parameter. It specifies what the behavior should be if there are files already at the destination directory. This second parameter was changed from a naked `int` to an enum class, to improve type safety. I didn't bother changing the deprecated overload, since it's there for backwards compatibility anyway. But the main overload taking a UTF-8 string was updated. This is really where the problem was introduced. Python programs wouldn't notice though. Deluge passes a naked `int` so the main overload no longer matches, but the deprecated one did (because strings in python can be both UTF-8 and UTF-16 or UTF-32).

The last step was me removing some old code with a Unicode license, this came up on debian because it wasn't compatible with their license. When removing this code, I had to finally remove the `wstring` overloads. But I left them in on windows for two reasons (still deprecated):

* On windows, using wide character strings is still kind of a thing, with the `UNICODE` macro and the `W` versions of the win32 API.
* On windows, I wasn't using the Unicode code anyway, but the built-on conversion functions

So, on windows, deluge still had the deprecated function available to it, that take a naked `int`, but on any other platform, it wouldn't.

The fix in libtorrent was to add a converter from `int` to the enum class, to allow the call to be made still, without specifying the type.

> I mean that the issue in deluge reported here, doesn't happen on windows, with same deluge, python and libtorrent version. On windows, libtorrent is built by myself with msvc 2019. As said, just curious :)

**Comment by eli-schwartz** [comment]
Deprecation warnings are a thing in python! But only at runtime, at which point you can spam the console and hope someone notices. (More effective with CLI programs than with GUI programs.)

Just use `PyExc_DeprecationWarning`.

Given a decently long deprecation period, you can probably assume *someone* would be running deluge on the CLI and notice this. This is not as good as build-time warnings, but it's still useful.

**Comment by eli-schwartz** [comment]
Deprecation warnings are a thing in python! But only at runtime, at which point you can spam the console and hope someone notices. (More effective with CLI programs than with GUI programs.)

Just use `PyExc_DeprecationWarning`.

Given a decently long deprecation period, you can probably assume *someone* would be running deluge on the CLI and notice this. This is not as good as build-time warnings, but it's still useful.
