### ISSUE TITLE
Connecting to same peer multiple times due to multiple external addresses

### ISSUE THREAD

**Issue by ghost** [arvidn/libtorrent#5096]
**Please provide the following information**

libtorrent version (or branch):
1.2.6
platform/architecture:

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Some peers have more than 1 external IP address and libtorrent is connecting with all of them.  
Libtorrent should connect with only one address or address family.

**Comment by arvidn** [comment]
It's not obvious to me that it should. If you have multiple routes to a peer, presumably you would want to use all of the available bandwidth.

But, this was addressed recently in [this](https://github.com/arvidn/libtorrent/pull/4962) patch.

If a peer has multiple IPs and use different peer-ids for each connection, I don't think there's a way to tell it's the same one.

**Comment by an0n666** [comment]
In some cases I’m noticing better speeds when connecting with a peer over IPv6. Is it possible to give preference to IPv6 over v4 in case of duplicate peer_id?
Also another question, does libtorrent generate different peer_ids for each addresses?

**Comment by arvidn** [comment]
> Is it possible to give preference to IPv6 over v4 in case of duplicate peer_id?

I don't think there's any logic to do that in libtorrent right now.

> Also another question, does libtorrent generate different peer_ids for each addresses?

I believe when anonymous mode is enabled, it generates a new peer_id for every connection.

**Comment by an0n666** [comment]
> > Is it possible to give preference to IPv6 over v4 in case of duplicate peer_id?
> 
> I don't think there's any logic to do that in libtorrent right now.
> 

I see. Then we’re limited to one random address family or address for each peer with that patch. Unless both ends using anonymous mode.

**Comment by an0n666** [comment]
I can think of another way is to unchoke only the faster one among the peers with duplicate peer ids.

**Comment by arvidn** [comment]
that's the default behavior regardless of whether a connection is "duplicate" or not.
