### ISSUE TITLE
 std::out_of_range() in verify_encoding() on Windows

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#5104]
libtorrent version (or branch): master (176079)
platform/architecture: Win7 64Bit
compiler and compiler version: VC2019

I get that exception here: ptr = ptr.substr(std::size_t(len));
i.e.: ptr length is 4 and len is 5 for
"-XL0012-Ï…©{ÆÑ\fjûÍ:\a"
2d 58 4c 30 30 31 32 2d cf 85 a9 7b c6 d1 0c 6a fb cd 3a 07

caused by this code in bt_peer_connection::on_extended_handshake():
...
m_client_version = std::string(client_info);
// the client name is supposed to be UTF-8
aux::verify_encoding(m_client_version);
..

Is that the intended error handling?

**Comment by arvidn** [comment]
it was an oversight, and caught in fuzzing last night. I fixed it in [RC_2_0](https://github.com/arvidn/libtorrent/pull/5102) and [RC_1_2](https://github.com/arvidn/libtorrent/pull/5103). But it hasn't made it to master yet.

**Comment by MassaRoddel** [comment]
Ok.
Btw, i am getting alot of this asserts too:
TORRENT_ASSERT(!m_abort || req.event == event_t::stopped);
m_abort =true, req.event = 0
in
tracker_manager::queue_request()
i.e. after adding a torrent
