### ISSUE TITLE
save_resume_data_alert occurs after torrent_removed_alert

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [arvidn/libtorrent#5112]
**Please provide the following information**

libtorrent version (or branch): 1.2.8.0

platform/architecture: linux/x86_64

compiler and compiler version: not sure; using alpine linux's edge testing binary

I'm seeing a case where if I do:
```
session.remove_torrent(handle)
handle.save_resume_data()
```
Then:
1. This succeeds without raising an exception (no `RuntimeError` in Python)
1. In the alert stream, I see `torrent_removed_alert` come before `save_resume_data_alert` for the same handle
1. When I receive `save_resume_data_alert`, then `alert.handle.is_valid()` is true, and `alert.handle.info_hash()` is non-all-zeros.

I sort of understand thing 1, as both calls are asynchronous, so they can both get queued before either is called.

Thing 2 follows from thing 1.

I am kind of confused by thing 3 though. My C++ is weak, but my understanding is that `handle::is_valid()` should return false once the torrent has been destructed. I don't understand exactly where it gets destructed in this case though.

The following python script triggers this condition. On my machine the last lines of output are like this:
```
torrent_removed_alert test.txt removed
torrent_log_alert test.txt: *** UPDATE LIST [ torrent_want_tick : 0 ]
torrent_log_alert test.txt: *** announce: no trackers
torrent_log_alert test.txt: aborting
torrent_log_alert test.txt: *** UPDATE LIST [ torrent_downloading_auto_managed
: 0 ]
save_resume_data_alert test.txt resume data generated
... info_hash = 9393ec7b02a264f71506301963429f064a472327 valid = True
```

[srda_timing.py.gz](https://github.com/arvidn/libtorrent/files/5181847/srda_timing.py.gz)

The big practical problem for me is figuring out how to serialize resume data correctly. If I write resume data when I see `save_resume_data_alert` and delete it when I see `torrent_removed_alert`, I end up with zombie data in this case. At the moment the only workaround I can think of is also watching `add_torrent_alert` and `torrent_removed_alert` to keep a list of all active handles, so I can properly ignore `save_resume_data_alert` after `torrent_removed_alert`. However this violates the "don't keep application state for every torrent" principle outlined in [your blog post](https://blog.libtorrent.org/2012/01/seeding-a-million-torrents/).

Do you have any guidance here? How do I figure out when the torrent is really removed?

**Comment by 5523eeOMEGALUL** [comment]
`if handle.is_valid() handle.save_resume_data()`?

**Comment by AllSeeingEyeTolledEweSew** [comment]
> `if handle.is_valid() handle.save_resume_data()`?

No difference. `session.remove_torrent(handle)` is an async call and doesn't immediately invalidate the handle.

**Comment by AllSeeingEyeTolledEweSew** [comment]
Also tested just now on 1.2.6.0, built using alpine's aports script for that version. The result is the same

**Comment by AllSeeingEyeTolledEweSew** [comment]
FWIW, I also tried:
```
session.remove_torrent(handle)
session.async_add_torrent(params)  # params.flags & duplicate_is_error == 0
handle.save_resume_data()
```
The result seems to be:
* `torrent_removed_alert` with handle 1
* `add_torrent_alert` with handle 2
* `save_resume_data_alert` with handle 1

As above, `handle.is_valid()` returns true when we receive `save_resume_data_alert`.

So `remove_torrent()` does remove the torrent from the session, even though the handle is apparently kept alive by the `save_resume_data()` call still in the queue. It's just surprising that `handle.is_valid()` is true for a torrent that's been removed from the session.

**Comment by arvidn** [comment]
`session.remove_torrent()` is actually even more async than that. Just because the corresponding internal call has been made to remove the torrent will the torrent object be freed immediately. For example, there may still be outstanding disk operations associated with the torrent object, they will keep it alive (even if it's unlinked from the main torrent list in the session).

So, you're not guaranteed that the handle you get back from that `save_resume_data_alert` is valid, but you're also not guaranteed that it will be *invalid*.

**Comment by AllSeeingEyeTolledEweSew** [comment]
Then, it seems that to coherently persist resume data an app needs to either:
* Synchronize calls such that `torrent_handle.save_resume_data()` can't be called after `session.remove_torrent()`
* Monitor `add_torrent_alert` and `torrent_removed_alert` to keep a list of active `torrent_handle`s, and ignore `save_resume_data_alert` if the handle is not in the list

Do you have any other suggestions? I'd love to not need to keep state per active torrent.

**Comment by AllSeeingEyeTolledEweSew** [comment]
Or:
* Make a call like `session.find_torrent(handle.info_hash()) == handle` as a proxy for `handle.is_valid()`

Though I'd also like to avoid making synchronous calls like `session.find_torrent()` while handling alerts, since it can block other alert handling code.

I guess I could save off `alert.handle` and `alert.params`, pass them to another thread, and call `session.find_torrent()` from that thread, that would solve all my concerns (except the extra CPU cycles doing all this)

Any of these ideas seem like a lot of work for such a basic use case though

**Comment by AllSeeingEyeTolledEweSew** [comment]
Spitballing: we could have `torrent_flags::removed` be set by `session.remove_torrent()`
* It would show up in the `add_torrent_params.flags` later
* aware code could just check the flag and ignore `save_resume_data_alert`, no need for extra state or surprising checks
* you could return an error when `add_torrent()` sees `torrent_flags::removed`, so that if any unaware code persists such a stale `add_torrent_params` and tries to add it again later, the user doesn't end up with a torrent they thought they removed

**Comment by arvidn** [comment]
when you call `save_resume_data()` on a torrent handle, where do you get the torrent handle from? I would expect you hold a vector of all torrent handles (or maybe even a vector of `torrent_status` objects, which include a `torrent_handle`).

You could clear the `torrent_handle` when you delete the torrent, so that you won't be able to call `save_resume_data()` later. But perhaps you still want to avoid any `save_resume_alert` that comes back *after* having removed the torrent too, even if it was called before removing it.

I don't think I know enough about your setup to really understand the challenge. Generally, I would think that in order to only make asynchronous calls to libtorrent, you *do* need to keep the state of all the torrents "locally" (in your thread) as well.

**Comment by AllSeeingEyeTolledEweSew** [comment]
> Generally, I would think that in order to only make asynchronous calls to libtorrent, you _do_ need to keep the state of all the torrents "locally" (in your thread) as well.

I found a way around that. I created an iterator over alerts, which lets me spawn narrowly-scoped jobs in their own thread, with their own iterators. My fastresume handling code looks like this, in a thread that runs for most of the lifetime of the app:
```
for alert in iter_alerts(save_resume_data_alert, save_resume_data_failed_alert, torrent_removed_alert, torrent_finished_alert, ...):
    if isinstance(alert, save_resume_data_alert):
        write_to_disk(alert.params)
        counter -= 1
    elif isinstance(alert, save_resume_data_failed_alert):
        counter -= 1
    elif isinstance(alert, torrent_removed_alert):
        delete_data(alert.info_hash)
    elif isinstance(alert, torrent_finished_alert):
        alert.handle.save_resume_data()
        counter += 1
    ...
```

When I do need to keep per-torrent state, I create a new thread, it creates an iterator whose alerts are filtered so it only sees alerts for that `torrent_handle`, and its thread exits when it sees `torrent_removed_alert` or its job is otherwise done.

The key to creating sane iterators over alerts is figuring out when it's safe to call `pop_alerts()` and invalidate the existing alerts. I realized that **while an iterator is blocked waiting for new alerts, its consumer isn't touching any alerts**. Once all live iterators are in this state, it's safe to call `pop_alerts()`.

I was previously using libtorrent the "traditional" way, having a bunch of `on_alert()` callbacks everywhere and a single thread to call them all, and it was driving me *nuts*. I found no way to avoid big blobs of global state, unclear control flow, lack of confidence in my code, and nightmares trying to test it all. The effect of switching to iterators has been *drastic*. Everything is better. Most of my modules have *less than half* the lines of code compared to using callbacks. Turning everything into narrowly-scoped jobs means inherently better readability and testability, and also means it's easier to create an app which in the common case has no per-torrent state and spends no CPU on polling.

I had a lot of thoughts on alert iterators and I was going to create a separate issue to document my process and comment on some outcomes, but it's a big refactor and I'm not done writing it all yet.

For this issue, the TL;DR is that I'd like to do at least the common use cases (like writing resume data) purely by reacting to alerts and making only asynchronous calls.

**Comment by AllSeeingEyeTolledEweSew** [comment]
As I write more, I'm finding other reasons to use `session.find_torrent(handle.info_hash()) == handle`.

When I create an iterator expecting to process alerts for a particular handle, there's a race that the iterator might not see the `torrent_removed_alert`. My current thought is that such iteration should look like this:
```python
iterator = iter_alerts(torrent_removed_alert, ..., handle=handle)
if session.find_torrent(handle.info_hash()) != handle:
    iterator.close()
for alert in iterator:
    if isinstance(alert, torrent_removed_alert):
        break
    else:
        ...
```
(if I'm feeling pedantic, I could do the blocking `find_torrent()` calls in a thread pool)

My understanding has changed a bit. I should ask some specific questions.
* What options are there for synchronizing on a given handle being in a session? I can think of
  * Check using `session.find_torrent(handle.info_hash()) == handle`
  * Keep a list of active handles, only the central torrent manager is allowed to call `session.[add|remove]_torrent()`
* What's the use case for `handle.is_valid()`? You point out that handles can be live after they're removed, so even a single-threaded non-concurrent app can't use `handle.is_valid()` as a shortcut to "is the torrent in the session".

**Comment by AllSeeingEyeTolledEweSew** [comment]
I split this into #5174 for a more specific behavior request.

This issue became about arriving at a more coherent picture of handle lifecycles and concurrency, which I think is satisfied by #5151.
