### ISSUE TITLE
SIGBUS handling for new mmap() I/O

### ISSUE THREAD

**Issue by farnoy** [arvidn/libtorrent#5118]
Hi and congrats on the 2.0 release!

This is not a bug report, I just wanted to ask about the strategy regarding `SIGBUS` as a consequence of using `mmap()`. People who download torrents to a shared locations (with write permissions for other users) might end up being vulnerable to DoS. I think that a single `truncate()` syscall on a file actively accessed by libtorrent could crash the entire process. The signal handler does not currently attempt recovery https://github.com/arvidn/libtorrent/blob/0f0afec8c8025cb55dfd2f36612d4bf61a29ff8a/test/main.cpp#L175

**Comment by farnoy** [comment]
Oh nevermind, I see that it is being handled with a [library](https://github.com/arvidn/try_signal)

**Comment by arvidn** [comment]
the handling just turns it into a disk I/O error, which stops the torrent. I think that's reasonable behavior though. If an attacker has write access to your files, there are a lot worse attacks that can be launched than causing write failures, I think.
