### ISSUE TITLE
[Q] Is lt::file_index_t unique identifier of the file?

### ISSUE THREAD

**Issue by silverqx** [arvidn/libtorrent#5119]
I want to ask, if `lt::file_index_t` is a unique identifier of file? eg if I restart the whole session, if file indexes will be the same for all files.

Thx for advice.

**Comment by arvidn** [comment]
`file_index_t` is a "strong typedef" of an `int`, that represents the index of a file inside a torrent file. Any specific torrent file will have a well defined and immutable file list, and a file index into it will always refer to the same file. However, the file index is not unique *across* different torrents. But within a specific torrent, they are unique (and dense, if you count pad-files).

If you need access to the underlying `int`, you can use `static_cast<int>(idx)`.

**Comment by 5523eeOMEGALUL** [comment]
> I want to ask, if `lt::file_index_t` is a unique identifier of file? eg if I restart the whole session, if file indexes will be the same for all files.

`lt::file_index_t` with `ti->num_files()` will crash if you query magnet and metadata not yet received
https://github.com/arvidn/libtorrent/blob/v1.2.10/examples/client_test.cpp#L2018

file indexes can be same per torrent (per magnet with metadata) only per libtorrent version

**Comment by silverqx** [comment]
I created PR #5122 answer is what I wanted to know, so I can use it as I intended. thx

**Comment by silverqx** [comment]
thx
