### ISSUE TITLE
libtorrent 1.2 failed to compile with clang

### ISSUE THREAD

**Issue by mnixry** [arvidn/libtorrent#5120]
**Please provide the following information**

libtorrent version (or branch): `RC_1_2`

platform/architecture: `x86_64-redhat-linux-gnu`

compiler and compiler version:` clang 3.4.2 (tags/RELEASE_34/dot2-final)`

libtorrent 1.2 could be compiled successfully with GCC 9.1.2 
but if I specify flag `CC=clang CXX=clang++`, it will shown up errors during build:
```
Scanning dependencies of target torrent-rasterbar
[  0%] Building CXX object CMakeFiles/torrent-rasterbar.dir/src/web_connection_base.cpp.o
In file included from /tmp/libtorrent-rasterbar-1.2.10/src/web_connection_base.cpp:38:
In file included from /tmp/libtorrent-rasterbar-1.2.10/include/libtorrent/web_connection_base.hpp:42:
In file included from /tmp/libtorrent-rasterbar-1.2.10/include/libtorrent/peer_connection.hpp:55:
In file included from /tmp/libtorrent-rasterbar-1.2.10/include/libtorrent/peer_connection_interface.hpp:39:
/tmp/libtorrent-rasterbar-1.2.10/include/libtorrent/alert_types.hpp:354:34: warning: unknown warning group
      '-Weverything', ignored [-Wunknown-pragmas]
#pragma clang diagnostic ignored "-Weverything"
                                 ^
In file included from /tmp/libtorrent-rasterbar-1.2.10/src/web_connection_base.cpp:38:
In file included from /tmp/libtorrent-rasterbar-1.2.10/include/libtorrent/web_connection_base.hpp:43:
In file included from /tmp/libtorrent-rasterbar-1.2.10/include/libtorrent/torrent.hpp:48:
In file included from /tmp/libtorrent-rasterbar-1.2.10/include/libtorrent/torrent_info.hpp:52:
/tmp/libtorrent-rasterbar-1.2.10/include/libtorrent/file_storage.hpp:69:15: error: exception specification of
      explicitly defaulted move assignment operator does not match the calculated one
                file_entry& operator=(file_entry&&) & noexcept = default;
                            ^
1 warning and 1 error generated.
make[2]: *** [CMakeFiles/torrent-rasterbar.dir/src/web_connection_base.cpp.o] Error 1
make[1]: *** [CMakeFiles/torrent-rasterbar.dir/all] Error 2
make: *** [all] Error 2
```
BTW, libtorrent 1.1 could be compile successfully by clang

**Comment by rubbershoesinmotion** [comment]
https://github.com/arvidn/libtorrent/blob/RC_1_2/docs/building.rst
and
https://github.com/arvidn/libtorrent/blob/RC_2_0/docs/building.rst
+
https://github.com/arvidn/libtorrent/blob/RC_1_2/ChangeLog
+
https://github.com/arvidn/libtorrent/blob/RC_2_0/ChangeLog

From building docs of 1.2:
"The CMAKE_CXX_STANDARD has to be at least 11, but you may want to raise it to 14 or 17 if your project use a newer version of the C++ standard."

In your case: Make sure to set required "**-std=_ _**" value.
Also, for C ++ 17 support, the version you are using needs to be updated.
-Check this page for more info: https://clang.llvm.org/cxx_status.html

**Comment by arvidn** [comment]
@mnixry that error suggests that your *standard library* has some type in it that is not nothrow-move-assignable, even though it should be. I assume you're using clang together with libstc++. Are you sure the copy of libstdc++ is new enough? and support C++11 fully?

**Comment by mnixry** [comment]
I've tried `llvm-toolset-7-5.0.1-4.el7.x86_64`, same error occurred.

**Comment by arvidn** [comment]
libstdc++ is the standard library that comes with GCC and libc++ is the standard library that (often) comes with clang, but clang supports libstdc++ as well (at least it used to, before libc++ was fully developed).

But, I might be wrong actually, maybe it's yout libc++ that's too old. clang-3.4 sounds pretty old.

**Comment by arvidn** [comment]
looking a bit closer at this, `std::string` wasn't made nothrow move assignable until C++17. I think most implementations did this a lot earlier though, but it is technically incorrect of me to rely on it when C++11 is supposed to be sufficient. That's why I haven't discovered this in testing as well.

**Comment by arvidn** [comment]
@mnixry could you give this patch a try? https://github.com/arvidn/libtorrent/pull/5124

**Comment by mnixry** [comment]
> @mnixry could you give this patch a try? #5124

Thank you! This patch can compile perfectly on my platform!

**Comment by arvidn** [comment]
thanks for the report!
