### ISSUE TITLE
save_resume_data() should include pieces waiting to be written to disk, for paused torrents

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [arvidn/libtorrent#5121]
**Please provide the following information**

libtorrent version (or branch): 1.2.8.0

platform/architecture: linux/x86_64

compiler and compiler version: gcc / unknown version, using alpine linux's edge testing build

I'm not sure if this is a bug report or clarification request.

The [docs](https://libtorrent.org/reference-Torrent_Handle.html) say:

>*flush_disk_cache*
>the disk cache will be flushed before creating the resume data. This avoids a problem with file timestamps in the resume data in case the cache hasn't been flushed yet.

Based on https://github.com/arvidn/libtorrent/blob/RC_1_2/src/torrent.cpp#L8560 , it seems like `save_resume_data(flush_disk_cache)` just asynchronously flushes the cache. It seems equivalent to
```
handle.save_resume_data()
handle.flush_cache()  # without generating cache_flushed_alert
```

Since the `add_torrent_params` is generated immediately after firing the flush, it's not clear to me the flag can affect the generated params at all.

In particular, I see that in the following sequence:
```
status = handle.status(flags=libtorrent.torrent_handle.query_pieces)
handle.save_resume_data(flags=libtorrent.torrent_flags.flush_disk_cache)
params = wait_for_save_resume_data_alert().params
```
If the torrent is actively downloading, there are cases where `states.pieces` has some "bits" set, but `params.have_piece` does **not** have those bits set.

The fields are built using piece picker code which is pretty hard for me to follow, but my understanding is that:
* `torrent_status::pieces` marks pieces which have been hashed
* `add_torrent_params::have_pieces` marks pieces which are hashed and written to disk

So it would be nice if `flush_disk_cache` behaved as described in the docs, but it doesn't do what I expect.

Is `flush_disk_cache` working as intended? If it is, what should I expect from it, and what's the best practice to ensure my resume data is up-to-date at shutdown?

**Comment by arvidn** [comment]
this flag is an old left-over from the days when the resume data contained modification timestamps for all files. flushing the cache first would make it slightly less likely that the resume data would have a stale timestamp in it. That's what the flag would do, it would ensure that the flushing happened immediately before `stat()`ing the file to get the modification timestamp.

I don't think it is very useful anymore. As you point out, you can flush the cache manually, and it doesn't need to be synchronized with generating the resume data.

**Comment by arvidn** [comment]
> The fields are built using piece picker code which is pretty hard for me to follow, but my understanding is that:
> 
>     torrent_status::pieces marks pieces which have been hashed
>     add_torrent_params::have_pieces marks pieces which are hashed and written to disk
> 
> So it would be nice if flush_disk_cache behaved as described in the docs, but it doesn't do what I expect.
> 
> Is flush_disk_cache working as intended? If it is, what should I expect from it, and what's the best practice to ensure my resume data is up-to-date at shutdown?

you're right that `torrent_status::pieces` indicate which pieces we have downloaded and passed the hash check, but not necessarily been sent to the disk subsystem yet.

The disk I/O is run in several threads, separate from the network thread, so not only is there a cache, managed by the disk threads, there's also a *queue* of blocks to be sent from the network thread to the disk threads (like a store buffer).

There is no synchronization between generating the resume data after the disk cache has been flushed anymore. But even if there was, I don't see how that would affect the bits you're looking at.

It sounds like you would like to either:

1. ignore pieces that are in the state "passed hash check but not written to disk", or
2. synchronize to wait for all of them to be written to disk before generating the resume data.

if you aim for (2), would you expect the download to stop while waiting? If the downloading wouldn't stop, there would presumably be *new* pieces in that state by the time you're done waiting for the ones to be flushed to disk, so you would still have to ignore those, like in option (1).

**Comment by AllSeeingEyeTolledEweSew** [comment]
>     2. synchronize to wait for all of them to be written to disk before generating the resume data.
> 
> 
> if you aim for (2), would you expect the download to stop while waiting? If the downloading wouldn't stop, there would presumably be _new_ pieces in that state by the time you're done waiting for the ones to be flushed to disk, so you would still have to ignore those, like in option (1).

I'd prefer that after graceful shutdown + a restart, the client doesn't have to re-download anything it already downloaded, so I think that means I prefer (2).

Since this is at shutdown, I'm calling `session.pause()` first; I understood that this synchronously pauses all torrents and disconnects all peers. I forgot to say that my "out-of-sync `torrent_status` vs `add_torrent_params` scenario" above comes after `session.pause()`.

I think that means my shutdown sequence needs to look like:
```python
session.pause()
for handle in handles:
    handle.flush_disk_cache()
# wait for N cache_flushed_alerts
for handle in handles:
    handle.save_resume_data(only_if_modified)
# wait for N save_resume_data[_failed]_alerts
```
Am I understanding things right?

**Comment by vktr** [comment]
@AllSeeingEyeTolledEweSew there is an example of a shutdown sequence here - https://github.com/arvidn/libtorrent/blob/master/examples/client_test.cpp#L2070

**Comment by arvidn** [comment]
I think there may be an issue with `save_resume_data()` not synchronizing with pieces that are waiting to be written to disk though. For a paused torrent, I think it should do that.

**Comment by AllSeeingEyeTolledEweSew** [comment]
> I think there may be an issue with `save_resume_data()` not synchronizing with pieces that are waiting to be written to disk though. For a paused torrent, I think it should do that.

Do you mean you claim `save_resume_data()` does currently synchronize with pieces waiting to be written, or that it should be _changed_ to do this?

I claim it doesn't do this now.

**Comment by arvidn** [comment]
yes. my "should do it" was an: "it ought to, even though it isn't now"

**Comment by arvidn** [comment]
In my mind, the issue of this ticket is fundamentally: "if I save resume data on a paused torrent and shut down, starting up again should not cause anything to be re-downloaded". I agree that this is an important property. I think the "paused torrent" is important in that description since a downloading torrent will have bytes in-flight and saving resume data will necessarily happen before stopping the download in that case, so whatever is downloaded after saving the resume data would not be covered by it.

The case that is (as far as I can tell) is believed to be problematic is when pausing an actively downloading torrent and then immediately save resume data. Blocks can be in a few different states, but notably they can be `finished` and `writing` (since the torrent is assumed to be paused in this scenario, they shouldn't be `requested`). A piece may have all its blocks in `finished` mode but still not be considered as we have it, if it hasn't passed the hash check yet (which is async).

I've briefly looked at this (but not done any testing yet). As far as I can tell from the code, there's at least an *attempt* to solve this, not by waiting and synchronizing with all currently downloaded pieces but by recording the state of blocks in unfinished pieces. A piece that is completely downloaded but hasn't passed the hash check yet *should* still be recorded in the resume data as such (not as having passed the hash check, but as completely downloaded). When starting up by resuming from the resume data, such pieces should have their hash checked, nothing re-downloaded.

My next step is to write a few tests to ensure that all the scenarios I can think of actually work this way. @AllSeeingEyeTolledEweSew does this description match what you see? If not, would you mind looking at the resume data (if you save it to disk in bencoded form, look for the "unfinished pieces" key).

**Comment by arvidn** [comment]
to amend to that description: The resume data currently does *not* record blocks that are waiting in the disk queue to be written to disk in its "unfinished pieces" field. So, this definitely seems like the problem.

The simplest solution would be to *assume* that they will be correctly written to disk and just include them as completed in the resume data. Because shutting down will definitely synchronize for all outstanding disk I/O to complete. However, if the disk happens to be full (or the write fails for some other reason), the resume data would not be accurate.

**Comment by AllSeeingEyeTolledEweSew** [comment]
I found at least one case where the "unfinished" key is not populated.

My triggering test case is:
https://github.com/AllSeeingEyeTolledEweSew/tvaf/blob/cebe896e443bedd541220583a8fce59023c911be/tvaf/tests/resume_test.py#L138-L170

I modified the test so I _don't_ wait for `cache_flushed_alert`, and ran it in a loop until it failed.

I printed the output of `write_resume_data()` for the case, it looks like this:
```
{b'active_time': 1, b'added_time': 1600267531, b'allocation': b'sparse',
b'apply_ip_filter': 1, b'auto_managed': 1, b'completed_time': 0,
b'disable_dht': 0, b'disable_lsd': 0, b'disable_pex': 0,
b'download_rate_limit': -1, b'file-format': b'libtorrent resume file',
b'file-version': 1, b'finished_time': 0, b'httpseeds': [], b'info': (100, 54,
58, 108, 101, 110, 103, 116, 104, 105, 49, 52, 56, 52, 53, 54, 101, 52, 58,
110, 97, 109, 101, 56, 58, 116, 101, 115, 116, 46, 116, 120, 116, 49, 50, 58,
112, 105, 101, 99, 101, 32, 108, 101, 110, 103, 116, 104, 105, 49, 54, 51, 56,
52, 101, 54, 58, 112, 105, 101, 99, 101, 115, 50, 48, 48, 58, 3, -8, -39, 33,
-101, -10, 116, -11, -30, 119, 79, -55, -18, 83, 57, -1, -125, 74, 115, 69,
-20, 111, -85, 2, -67, 107, -117, -12, -79, -13, 31, -46, -93, -79, -49, -100,
18, 124, 120, -114, -4, 101, 60, 97, -28, -60, -51, 7, -49, 112, -41, 103, 35,
50, 72, -20, -29, -124, -122, 106, -98, -70, 107, -103, 102, -61, -49, -33, 7,
-116, 94, -5, 82, -15, 6, -106, -93, 76, 65, 57, -24, 75, 99, -77, -83, -8, 57,
-65, 64, -37, -20, -16, -14, 110, 118, 122, -17, 26, -99, 8, -111, -86, 67,
-11, 69, 85, 125, -49, -37, 124, -30, -74, 1, -87, -43, -119, 90, 73, 91, -14,
-103, -108, -11, -17, 78, 80, 90, 98, -23, -70, 10, -8, -79, -2, -44, -121, 85,
121, 73, -81, 115, -92, 8, 31, -31, -57, -56, -72, 125, 63, -82, 110, 43, 32,
59, 6, -4, -53, -37, -22, -66, 8, -24, 60, -1, -12, 86, -5, 0, 107, -51, -8,
-41, -20, 80, -73, -18, 6, -14, 119, 100, 65, -52, -108, -42, 38, 16, -82, -96,
18, -14, 32, -102, 24, -14, -82, -119, 36, -110, 70, 101), b'info-hash':
b'\xd6\xf7P^\x04\x976\xd3\xe9-\xc9M\xd9bP.H8\x8c\xd6', b'last_download':
1600267532, b'last_seen_complete': 0, b'last_upload': 0, b'libtorrent-version':
b'1.2.8.0', b'max_connections': 16777215, b'max_uploads': -1, b'num_complete':
16777215, b'num_downloaded': 16777215, b'num_incomplete': 16777215, b'paused':
0, b'pieces': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', b'save_path':
b'/tmp/tmp4m49z95y', b'seed_mode': 0, b'seeding_time': 0,
b'sequential_download': 0, b'share_mode': 0, b'stop_when_ready': 0,
b'super_seeding': 0, b'total_downloaded': 0, b'total_uploaded': 0, b'trackers':
[], b'upload_mode': 0, b'upload_rate_limit': -1, b'url-list': []}
```

Maybe it's because my torrent just became a seed, the `save_resume_data()` code tests `has_picker()`:

https://github.com/arvidn/libtorrent/blob/49ddf02dd0531ca05ad89526f65e3d27155afd0d/src/torrent.cpp#L6632-L6655

**Comment by arvidn** [comment]
Yes, once you’re a seed, there won’t be any unfinished pieces.

**Comment by AllSeeingEyeTolledEweSew** [comment]
I applied #5160 but it didn't fix my test. The `unfinished` key isn't populated in my resume data.

If my suspicion is right that my torrent just became a seed, then #5160 probably needs to be expanded to cover the seed case.

test setup:
```python
        atp = self.torrent.atp()
        atp.flags &= ~lt.torrent_flags.paused
        atp.save_path = self.tempdir.name
        handle = self.session.add_torrent(atp)
        request_test_utils.wait_done_checking_or_error(handle)
        # NB: bug in libtorrent where add_piece accepts str but not bytes
        handle.add_piece(0, self.torrent.pieces[0].decode(), 0)

        for _ in lib.loop_until_timeout(5, msg="piece finish"):
            status = handle.status(flags=lt.torrent_handle.query_pieces)
            if any(status.pieces):
                logging.info("status.pieces = %s", status.pieces)
                break

        self.session.pause()
        self.resume.terminate()
```
(`self.resume.terminate()` calls `handle.save_resume_data()` and logs `write_resume_data(alert.params)`)
logs:
```
DEBUG    root:session.py:165 enabling alerts: status_notification
DEBUG    root:session.py:165 enabling alerts: storage_notification
DEBUG    tvaf.task:task.py:104 starting: ResumeService
DEBUG    tvaf.task:task.py:104 starting: fastresume data receiver
DEBUG    tvaf.task:task.py:104 starting: AlertDriver
DEBUG    tvaf.task:task.py:104 starting: fastresume save trigger
DEBUG    tvaf.task:task.py:104 starting: fastresume periodic save
DEBUG    tvaf.driver:driver.py:62 add_torrent_alert: added torrent: test.txt
DEBUG    tvaf.driver:driver.py:62 torrent_added_alert: test.txt added
DEBUG    tvaf.resume:resume.py:123 wrote: /tmp/tmpuau6bgiq/resume/d193b12dd1270f984865d38ec082e32ae5f606a3.torrent
DEBUG    tvaf.driver:driver.py:62 state_changed_alert: test.txt: state changed to: downloading
DEBUG    tvaf.driver:driver.py:62 torrent_checked_alert: test.txt checked
INFO     root:resume_test.py:151 status.pieces = [True, False, False, False, False, False, False, False, False, False]
DEBUG    tvaf.task:task.py:93 gracefully shutting down: ResumeService
DEBUG    tvaf.task:task.py:114 shutdown complete: fastresume save trigger
DEBUG    tvaf.task:task.py:114 shutdown complete: fastresume periodic save
DEBUG    tvaf.resume:resume.py:404 saving fastresume data for 1 torrents
DEBUG    tvaf.resume:resume.py:379 waiting for final fastresume data
DEBUG    tvaf.driver:driver.py:62 save_resume_data_alert: test.txt resume data generated
INFO     tvaf.resume:resume.py:243 received atp = {b'active_time': 1, b'added_time': 1600386540, b'allocation': b'sparse', b'apply_ip_filter': 1, b'auto_managed': 1, b'completed_time': 0, b'disable_dht': 0, b'disable_lsd': 0, b'disable_pex': 0, b'download_rate_limit': -1, b'file-format': b'libtorrent resume file', b'file-version': 1, b'finished_time': 0, b'httpseeds': [], b'info-hash': b"\xd1\x93\xb1-\xd1'\x0f\x98He\xd3\x8e\xc0\x82\xe3*\xe5\xf6\x06\xa3", b'last_download': 1600386541, b'last_seen_complete': 0, b'last_upload': 0, b'libtorrent-version': b'1.2.8.0', b'max_connections': 16777215, b'max_uploads': -1, b'num_complete': 16777215, b'num_downloaded': 16777215, b'num_incomplete': 16777215, b'paused': 0, b'pieces': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', b'save_path': b'/tmp/tmpuau6bgiq', b'seed_mode': 0, b'seeding_time': 0, b'sequential_download': 0, b'share_mode': 0, b'stop_when_ready': 0, b'super_seeding': 0, b'total_downloaded': 0, b'total_uploaded': 0, b'trackers': [], b'upload_mode': 0, b'upload_rate_limit': -1, b'url-list': []}
```

**Comment by arvidn** [comment]
> If my suspicion is right that my torrent just became a seed, then #5160 probably needs to be expanded to cover the seed case.

I must have misunderstood something. If you just became a seed, why would the resume data need to record any unfinished pieces?

Is the case you have in mind where you become a seed (i.e. all piece hashes have passed) but the blocks have not yet been flushed to disk? Perhaps they are sitting in the disk cache.

If so, I claim that those blocks will be written to disk when you shut down (as long as you don't `SIGKILL` the process). Is this not your experience?


In your test above, I assume what you consider a bug is the fact that the resume data has:

```
b'pieces': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

i.e. it says it has no pieces. In this case you use `add_piece()`, is that specifically the case you've had in mind all along? (I've been looking at the regular download path).

**Comment by arvidn** [comment]
I think I understand what's going on now. would you mind testing this patch? https://github.com/arvidn/libtorrent/pull/5165
I will add your test as well

**Comment by AllSeeingEyeTolledEweSew** [comment]
Tested 1.2.10 + #5160 + #5165, they seem to work. All my tests show I always have resume data for downloaded pieces, either in `have_pieces` or `unfinished_pieces`. Thanks!

**Comment by arvidn** [comment]
thanks for testing!
