### ISSUE TITLE
Why sha1_hash instead of info_hash_t ?

### ISSUE THREAD

**Issue by joriscarrier** [arvidn/libtorrent#5128]
libtorrent version (or branch): 2.0

Hi, is there a reason why some methods use sha1_hash instead of info_hash_t?

This list is not exhaustive:

- session.find_torrent
- session.dht_announce
- session.dht_get_peers
- ...

thank you in advance.

**Comment by arvidn** [comment]
I suppose all of those could have an `info_hash_t` overload, since they are user-facing. The DHT functions actually use a truncated hash for v2 torrents under the hood, but that doesn't have to be exposed to the user.

**Comment by joriscarrier** [comment]
thanks, I saw this on your blog: https://blog.libtorrent.org/2020/09/bittorrent-v2/

**Comment by arvidn** [comment]
I'm having second thoughts. I can see two reasonable behaviors if both v1 and v2 hash is provided:

* announce to the "best" info hash (i.e. v1 or truncated v2)
* announce to both v1 and v2

The second option would probably make the most sense, but might also be a bit unexpected.

**Comment by arvidn** [comment]
I think the current API is the most reasonable. I'm open to hearing arguments in favour of using `info_hash_t` and the semantic it should have.
