### ISSUE TITLE
Tracker announce issue - No such host is known

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#5135]
**Please provide the following information**

libtorrent version (or branch):
RC_1_2
platform/architecture:
Windows
compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Announces fails with no such host is known error if /announce is missing from URL. 
Related log here: https://github.com/qbittorrent/qBittorrent/pull/13348#issuecomment-690360124

**Comment by arvidn** [comment]
could you give this patch a try? https://github.com/arvidn/libtorrent/pull/5139

**Comment by arvidn** [comment]
I get "invalid port" errors in my testing though, so it's possible I fixed a different issue.

**Comment by an0n666** [comment]
Now they're not failing immediately. Most are failing with 400 Bad request
<tracker_error_alert> error: 400 Bad Request | failure reason: Bad Request
Whereas the one with /announce fails with 404 Not Found or 403 Forbidden errors.

**Comment by an0n666** [comment]
It gets fixed when a forward slash is added to URL.

**Comment by arvidn** [comment]
thanks for testing. I improved the fix here: https://github.com/arvidn/libtorrent/pull/5142

**Comment by an0n666** [comment]
> thanks for testing. I improved the fix here: #5142

That fixed the issue! Thanks!
