### ISSUE TITLE
Apparently unnecessary specification of allocators' allocated types

### ISSUE THREAD

**Issue by chriskohlhoff** [arvidn/libtorrent#5141]
libtorrent version (or branch): master

platform/architecture: x86_64

compiler and compiler version: gcc 10

I was looking into the fixes made under commit https://github.com/arvidn/libtorrent/commit/8d18fd198fbc7a259eea3a513db50b02da179882. There is an issue in Asio (actually it's an issue in the P0443 executors spec) to do with `any_executor::operator==` being considered a candidate function for overload resolution, even though neither argument is an `any_executor`. However, the problem was triggered because libtorrent instantiates allocator templates with the completion handler type.

Specifically:

* libtorrent passes the handler type as a template parameter to the allocator.
* Some handler types have the `any_executor` type encoded into their template parameters.
* During overload resolution for `operator==`, `any_executor::operator==` is included as a candidate when it shouldn't be.
* Recursive SFINAE/concept evaluation is triggered when evaluating whether the arguments to `any_executor::operator==` can be converted to `any_executor`.
* Compiler errors ensue.

The fix under commit https://github.com/arvidn/libtorrent/commit/8d18fd198fbc7a259eea3a513db50b02da179882 solves the issue because the lambda type does not include the original handler type, and thus does not add those additional candidates to overload resolution.

However, I think that the specification of the allocator's type is unnecessary in the following locations, and can probably be removed. Asio is going to rebind the allocator regardless.

```cpp
diff --git a/include/libtorrent/aux_/allocating_handler.hpp b/include/libtorrent/aux_/allocating_handler.hpp
index 4f9aa2580..ae1751d5c 100644
--- a/include/libtorrent/aux_/allocating_handler.hpp
+++ b/include/libtorrent/aux_/allocating_handler.hpp
@@ -262,7 +262,7 @@ namespace libtorrent { namespace aux {
 #endif
                }

-               using allocator_type = handler_allocator<allocating_handler<Handler, Size, Name>, Size, Name>;
+               using allocator_type = handler_allocator<int, Size, Name>;

                allocator_type get_allocator() const noexcept
                { return allocator_type{storage}; }
diff --git a/include/libtorrent/proxy_base.hpp b/include/libtorrent/proxy_base.hpp
index 2bfd68dc9..4ff83deea 100644
--- a/include/libtorrent/proxy_base.hpp
+++ b/include/libtorrent/proxy_base.hpp
@@ -295,14 +295,12 @@ struct wrap_allocator_t

        // rebind the underlying allocator to this wrapped type, since we need to use
        // it to allocate a larger handler context/closure.
-       using allocator_type = typename std::allocator_traits<
-               typename boost::asio::associated_allocator<UnderlyingHandler>::type>::
-                       template rebind_alloc<wrap_allocator_t>;
+       using allocator_type = typename boost::asio::associated_allocator<UnderlyingHandler>::type;

        using executor_type = typename boost::asio::associated_executor<UnderlyingHandler>::type;

        allocator_type get_allocator() const noexcept
-       { return allocator_type{boost::asio::get_associated_allocator(m_underlying_handler)}; }
+       { return boost::asio::get_associated_allocator(m_underlying_handler); }

        executor_type get_executor() const noexcept
        {
```

**Comment by arvidn** [comment]
sorry for the delay, I've been procrastinating spending the time to fully understand this issue. I get what you're saying about the overload set being "poisoned". However, it's not obvious to me that the `allocator_type` can be changed to a generic one. Is it safe to assume it will be rebound before actually being used?

I was under the impression that the `allocator_type` was supposed to be an allocator for the handler itself. There must be *some* cases where it's not rebound, no? Where it's not composed with any other handlers for instance.

**Comment by chriskohlhoff** [comment]
On Fri, Oct 23, 2020, at 9:14 PM, Arvid Norberg wrote:
> I was under the impression that the `allocator_type` was supposed to be 
> an allocator for the handler itself. There must be *some* cases where 
> it's not rebound, no? Where it's not composed with any other handlers 
> for instance.

The net TS specification for associated_allocator is in terms of ProtoAllocator, which means a rebind is always required to obtain an Allocator:

https://timsong-cpp.github.io/cppwp/networking-ts/async.assoc.alloc

Offhand I can't think of any places where the handler itself is the allocated type. At the very least, the allocated type wraps the handler and adds type erasure (function pointer, or inheritance with virtual functions) as well as a pointer to allow the object to be stored in a singly linked list.

**Comment by arvidn** [comment]
fixed here: https://github.com/arvidn/libtorrent/pull/5243
