### ISSUE TITLE
Generate resume data while metadata isn't downloaded yet

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#5143]
libtorrent version (or branch): 1.2+

I don't see any good reason why torrent can't generate resume data in case the metadata is still not downloaded. Maybe in older versions there were reasons, but since v1.2 resume data is just a set of parameters for adding a torrent to a session. So why can't it generate such parameters without metadata, if we can do it from the outside when adding (restoring) torrent? 
I am convinced that we must finally get rid of this legacy behavior.

**Comment by arvidn** [comment]
I agree

**Comment by glassez** [comment]
> I agree

So, can I hope that one of the libtorrent developers will implement this? Or your answer just means "I don't mind. You can implement it if you need"?

**Comment by arvidn** [comment]
does this work? https://github.com/arvidn/libtorrent/pull/5171

**Comment by glassez** [comment]
>does this work? #5171

👍 
It works as expected, with one exception. It should also save/load the torrent "name" (that is set via add_torrent_params during the initial addition).

**Comment by arvidn** [comment]
the patch has been updated to do this

**Comment by glassez** [comment]
>the patch has been updated to do this

Works as expected now. Thank you!

**Comment by arvidn** [comment]
thanks for testing!
