### ISSUE TITLE
peer fake sending client string with random data force libtorrent 2.0 to reset peer_info

### ISSUE THREAD

**Issue by 5523eeOMEGALUL** [arvidn/libtorrent#5147]
libtorrent 2.0

there a torrent with a peer that send random data in 'user_agent' on each connect
libtorrent reset `lt::peer_info` `.handle.get_peer_info(peers)` a lot when that happen, loosing peer list, slowdown download
getting "Unknown [dots-and-random-symbols]" as remote client from `<lt::peer_info>::const_iterator i->client`
torrent in question
magnet:?xt=urn:btih:e6e85467998ba3914865e2fd4482887d1bf488e1&dn=anime&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce
remote IP 114.109.124.248 (thailand)
he is seeding right now
tested: receiving random user_agent (client) strings from that address in uTorrent too
reproduce: limit download speed, watch peer list periodically disappear or cut
not sure if it good idea to post web link to torrent

**Comment by FranciscoPombal** [comment]
@5523eeOMEGALUL Can you post a wireshark capture that includes the problematic traffic?

**Comment by 5523eeOMEGALUL** [comment]
no

**Comment by arvidn** [comment]
> libtorrent reset lt::peer_info .handle.get_peer_info(peers) a lot when that happen, loosing peer list

what makes you say that? This is the core of your bug report. Please describe why you think this peer somehow triggers dropping the peer list.

sending random bytes in peer_id is expected behavior, not malicious. sending random bytes in the extension is mostly bad practice. That string is UTF-8 sanitized.

**Comment by 5523eeOMEGALUL** [comment]
can only theorize now, he not seeding anymore
