### ISSUE TITLE
Next Announce: Infinite (Symbol)

### ISSUE THREAD

**Issue by adir6** [arvidn/libtorrent#5149]
Hi, I am using Deluge 1.3.15 with LibTorrent 1.1.5.0 on Linux Platform OS: Ubuntu 18.04 minimal.

Issues:

1. There are huge differences between the upload showed by the Deluge and Tracker.

2. Next Announce in Deluge is coming as Infinity / Infinity in Symbol. (Screenshot: https://i.imgur.com/5MXYK3U.png)

Thanks.

**Comment by arvidn** [comment]
As for the upload shown in Deluge; I imagine the tracker will show *payload* upload. Do you know what Deluge is showing? If it's showing *all* upload, it would be expected to be a larger number.

I don't know in what case deluge use an infinity symbol, but maybe for trackers that will not be announced to.
