### ISSUE TITLE
Assert in set_piece_deadline()

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [arvidn/libtorrent#5150]
**Please provide the following information**

libtorrent version (or branch): 1.2.8.0-91a69dade

platform/architecture: linux/x86_64

compiler and compiler version: gcc-10.2.0

I built libtorrent with alpine linux's current build script, modified only to add `--enable-debug` to `./configure`

The relevant sequence seems to be:
```
atp = lt.add_torrent_params()
atp.save_path = "download"
atp.piece_priorities = [0] * len(PIECES)
atp.ti = lt.torrent_info(DICT)

handle = session.add_torrent(atp)

while True:
    status = handle.status()
    if status.state not in (lt.torrent_status.states.checking_resume_data,
                            lt.torrent_status.states.checking_files):
        break

handle.set_piece_deadline(0, 0, 1)

session.find_torrent(SHA1_HASH)
```
[assert.py.gz](https://github.com/arvidn/libtorrent/files/5221959/assert.py.gz)

On my machine, this gives:
```
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.2.8.0-91a69dade

file: 'torrent.cpp'
line: 7996
function: check_invariant
expression: m_links[aux::session_interface::torrent_downloading_auto_managed].in_list() == is_downloading

stack:
<not supported>
Aborted (core dumped)
```

No stack trace because alpine uses mingw, not glibc

**Comment by arvidn** [comment]
I can reproduce this. The invariant failure happens in `set_piece_deadline()`

**Comment by arvidn** [comment]
I believe this fixes it. https://github.com/arvidn/libtorrent/pull/5159

**Comment by arvidn** [comment]
as far as I can tell, this issue has been addressed
