### ISSUE TITLE
I would expect to not have this string at all when deprecated functions are disabled. There's no way to get this error in this case, is there?

### ISSUE THREAD

**Issue by crbrayity132139** [arvidn/libtorrent#5166]
I would expect to not have this string at all when deprecated functions are disabled. There's no way to get this error in this case, is there?

_Originally posted by @arvidn in https://github.com/arvidn/libtorrent/pull/4991#discussion_r470879203_

**Comment by crbrayity132139** [comment]
- `[](url)http://crb-informatique.com/@crbrayity132

>  @5162 crbrayity132

> #5121 bray_careto@hotmail.fr

> @1. `

**Comment by arvidn** [comment]
it looks like something may have gone wrong when filling this ticket. The PR and comment you link to was superseded by https://github.com/arvidn/libtorrent/pull/4993 as far as I can tell.

**Comment by crbrayity132139** [comment]
- https://github.com/arvidn/libtorrent/issues/5167

**Comment by crbrayity132139** [comment]
- https://github.com/arvidn/libtorrent/issues/#5166
