### ISSUE TITLE
Assert in add_completed_jobs_impl

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [arvidn/libtorrent#5172]
**Please provide the following information**

libtorrent version (or branch): 1.2.10, with #5159 applied

platform/architecture: linux/x86_64

compiler and compiler version: gcc-10.2.0

I was testing your fix to #5150 and encountered a new assert. It only happens with #5159 applied, otherwise I get the assert from #5150.

```
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.2.10.0-386596aa8

file: 'disk_io_thread.cpp'
line: 3379
function: add_completed_jobs_impl
expression: pe->blocks[j->d.io.offset / 16 / 1024].buf == nullptr

stack:
<not supported>
Aborted (core dumped)
```
Triggering case: [assert.py.gz](https://github.com/arvidn/libtorrent/files/5252340/assert.py.gz)

Relevant code:
```python
handle = session.add_torrent(atp)

while True:
    status = handle.status()
    if status.state not in (lt.torrent_status.states.checking_resume_data,
                            lt.torrent_status.states.checking_files):
        break

handle.add_piece(0, PIECES[0], 0)
handle.set_piece_deadline(0, 0, 1)
handle.prioritize_pieces([0] * len(PIECES))
handle.add_piece(0, PIECES[0], 0)
```

I wouldn't expect the second `add_piece()` to be meaningful; my test code was just calling it expecting it to be a no-op.

**Comment by arvidn** [comment]
thank you! I can reproduce this

**Comment by arvidn** [comment]
I think the underlying problem is that the disk I/O thread never expects the same block to be written twice, unless there's a `clear_piece()` in between (if hash fails). I never introduced any logic to prevent this from happening with `add_piece()`

**Comment by arvidn** [comment]
I believe this fixes it: https://github.com/arvidn/libtorrent/pull/5176
