### ISSUE TITLE
save_resume_data() should post save_resume_data_failed_alert if the torrent is removed/aborted

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [arvidn/libtorrent#5174]
Forking one of the topics from #5151 

Consider:
```python
session.remove_torrent(handle)
handle.save_resume_data()
```
This _usually_ succeeds, because the requests are asynchronous and the handle isn't invalidated by the time the second call is made. This results in `torrent_removed_alert` followed by `save_resume_data_alert`.

However, I'm struggling to think of a use case for the data in such a `save_resume_data_alert`. In the common case, an application deletes the resume data for any removed torrent. So a concurrent app must detect this sequence somehow, and _avoid_ persisting data in this case.

Even if the app _wants_ to persist data after removal, it would surprise me if it expected the above sequence to be valid.

In any case, it's not obvious the data generated by this sequence should be valid or meaningful today (it's generated for a torrent that's been aborted; what does that even mean?), or that we can guarantee going forward that it stays valid and meaningful.

It's essential for the above sequence to either fail or generate some alert, since the prescribed shutdown sequence looks like this:
```python
for handle in session.get_torrents():
    try:
        handle.save_resume_data()
        outstanding += 1
    except:
        pass

for alert in iter_alerts():
    if isinstance(alert, (save_resume_data_alert, save_resume_data_failed_alert)):
        outstanding -= 1
    if isinstance(alert, save_resume_data_alert):
        write_atp(alert.params)
    if outstanding == 0:
        break
```

So, I propose that the sequence in question generate `save_resume_data_failed_alert` instead.

I'll submit a PR shortly.

**Comment by arvidn** [comment]
I don't think this is unreasonable behavior, but I'm not entirely sold on that these operations should be (or need to be) coupled. removing a torrent doesn't necessarily mean it won't ever be added again. For example, a client that's seeding more torrents than can fit in working memory would need to pick and rotate which torrents are being seeded, maybe on-demand based on incoming connections. In that case, removing a torrent just means to take it out of rotation, to (possibly) put it back later.

I like the idea of these operations being orthogonal.

That said, removing the torrent *first* would always be risky. I don't think there could be any guarantees that the save_resume_data call after would work.

**Comment by AllSeeingEyeTolledEweSew** [comment]
I think that removing torrents and persisting resume data can still be orthogonal. I'm thinking of the proposed behavior as a question of the lifecycle of `torrent_handle`s, not torrents themselves.

I know that all kinds of operations can succeed after `remove_torrent()`, so that makes the proposed behavior is kind of a special case. But it _enables_ a use case, namely that an app developer can use resume data as the record of torrents in the session, without keeping its own state, or doing extra checks like `torrent_handle::in_session()`.

Is that a worthwhile tradeoff? It's my use case, so I'm biased.
