### ISSUE TITLE
MSVC WPO (LTO) build?

### ISSUE THREAD

**Issue by petersasi** [arvidn/libtorrent#5178]
_libtorrent version (or branch):_ 1.2.x

_platform/architecture:_ Windows

_compiler and compiler version:_ MSVC 2019

I am wondering if in the past you ever considered /GL for compilations and /LTCG for linking to enable MSVC Whole Program Optimization that is supposed to be similar optimization to gcc's LTO?
My knowledge of the build system is very far from being able to do this myself, but if you give me pointers on where to add these I can give it a spin to see if it works.
I am currently building Boost and LibTorrent together with B2 for the Windows installers of Deluge.

**Comment by arvidn** [comment]
the simplest way to do this would be to just specify it on the command line like this:

```
b2 msvc cxxflags=/GL linkflags=/LTCG
```
