### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by southernedge** [arvidn/libtorrent#5181]
**Please provide the following information**

libtorrent version (or branch):  libtorrent-1_1_14

platform/architecture: Windows

compiler and compiler version: VC2013

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Hello!

I unsuccessfully tried to download test torrent by using a proxy.
The test proxy sets I take here https://hidemy.name/en/proxy-list/
Here is my short example

```
        lt::session session( settings );

	lt::proxy_settings proxy = lt::proxy_settings();
	proxy.username = "";
	proxy.password = "";
	proxy.hostname = proxy.proxy_hostnames = "82.155.28.72";
	proxy.port = 34245;
	proxy.type = lt::aux::proxy_settings::socks4;

	***or***
	proxy.hostname = proxy.proxy_hostnames = "20.186.110.157";
	proxy.port = 3128;
	proxy.type = lt::aux::proxy_settings::http;

	***or***
	proxy.hostname = proxy.proxy_hostnames = "45.147.200.230";
	proxy.port = 30721;
	proxy.type = lt::aux::proxy_settings::socks5;

	session.set_proxy( proxy );
	
	settings.set_bool( lt::settings_pack::force_proxy,	true );
	settings.set_bool( lt::settings_pack::anonymous_mode,	true );

	session.apply_settings( settings );
```

 Maybe I use incorrect parameter(s) or I missed something???

 Thank for any advice!

**Comment by 5523eeOMEGALUL** [comment]
most publicity available proxies aren't working and often have ports firewalled
http(s) proxy should have 'connect' method enabled for non-web content to work

**Comment by southernedge** [comment]
> most publicity available proxies aren't working and often have ports firewalled
`netsh advfirewall firewall add rule`
was done...

**Comment by arvidn** [comment]
@southernedge what error alerts do you get? or what other symptoms do you see regarding the proxy not downloading?

**Comment by southernedge** [comment]
For example, something like that

error= message=name=10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions
comment=Torrent downloaded from torlock.com
creation_date=23.06.2020 16:29:31
#1 file_path=10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions\10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions.epub
#1 file_name=1
#1 file_size=3525453
#0 0 B from 3.36 MB (0%) rate=0 B
UDP error: UDP error: UDP error: UDP error: successfully listening on [TCP] [::]:6881
successfully listening on [TCP] 0.0.0.0:6881
successfully listening on [UDP] 0.0.0.0:6881
added torrent: 10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions added
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: state changed to: downloading
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions checked
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions resumed
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://tracker.leechers-paradise.org:6969/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://tracker.coppersurfer.tk:6969/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://tracker.openbittorrent.com:80/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://tracker.leechers-paradise.org:6969/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://eddie4.nl:6969/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://tracker.opentrackr.org:1337/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://9.rarbg.to:2790/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://tracker.pirateparty.gr:6969/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://tracker.internetwarriors.net:1337/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://9.rarbg.com:2790/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://9.rarbg.me:2730/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://denis.stalker.upeer.me:6969/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://open.demonii.si:1337/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://tracker.internetwarriors.net:1337/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://tracker.leechers-paradise.org:6969/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://tracker.coppersurfer.tk:6969/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://tracker.pirateparty.gr:6969/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://tracker.cyberia.is:6969/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://open.demonii.si:1337/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://open.stealth.si/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: tracker is not anonymous, set a proxy: udp://exodus.desync.com:6969/announce
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions (http://explodie.org:6969/announce) (-1)

**Comment by arvidn** [comment]
SOCKS4 does not support UDP. you need SOCKS5 for that

**Comment by southernedge** [comment]
SOCKS5, the same....

```
	proxy.hostname = proxy.proxy_hostnames = "157.230.7.119";
	proxy.port		= 40001;
	proxy.type		= lt::aux::proxy_settings::socks5;
```

error=false value=0 message=The operation completed successfully
error= message=name=10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions
comment=Torrent downloaded from torlock.com
creation_date=23.06.2020 06:29:31
#1 file_path=10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions\10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions.epub
#1 file_name=1
#1 file_size=3525453
#0 0 B from 3.36 MB (0%) rate=0 B

UDP error: The file handle supplied is not valid from: 0.0.0.0
UDP error: The file handle supplied is not valid from: 0.0.0.0
UDP error: The file handle supplied is not valid from: 0.0.0.0
UDP error: The file handle supplied is not valid from: 0.0.0.0
successfully listening on [TCP] [::]:6881

successfully listening on [TCP] 0.0.0.0:6881

successfully listening on [UDP] 0.0.0.0:6881

UDP error: No such host is known from: 0.0.0.0

added torrent: 10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions

10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions added

10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions: state changed to: downloading
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions checked
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions resumed
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions (udp://tracker.leechers-paradise.org:6969/announce) (-1) An invalid argument was supplied "" (1)
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions (udp://tracker.coppersurfer.tk:6969/announce) (-1) An invalid argument was supplied "" (1)
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions (udp://tracker.openbittorrent.com:80/announce) (-1) An invalid argument was supplied "" (1)
10-Minute Focus - 25 Habits for Mastering Your Concentration and Eliminating Distractions (udp://tracker.leechers-paradise.org:6969/announce) (-1) An invalid argument was supplied "" (2)

**Comment by arvidn** [comment]
does that torrent have any HTTP trackers? if so, are they succeeding?

**Comment by arvidn** [comment]
I should add, too, that the version you're using is quite old, and I'm not really interested in fixing issues in it. Would you mind trying version 2.0 or 1.2.10?

**Comment by southernedge** [comment]
_Would you mind trying version 2.0 or 1.2.10?_
My project is built in VC2013. I find it difficult to migrate on newer versions of VC.
Many libraries are trying to use the latest version of the new language standards, new opportunities compilers without considering that a large majority of users are not ready to change their PC, their OS. :(

I admit the possibility to refuse to support the proxy in my project, because this feature is rarely used and rather capricious.

An another torrent with HTTP trackers

```
	proxy.hostname = proxy.proxy_hostnames = "64.235.204.107";
	proxy.port		= 8080;
	proxy.type		= lt::aux::proxy_settings::http;
```

error=false value=0 message=The operation completed successfully
error= message=name=Osvobozhdenie
comment=http://nnmclub.to/forum/viewtopic.php?p=10700122
creation_date=23.06.2020 22:23:45
#1 file_path=Osvobozhdenie\Osvobozhdenie_Season 1_Ep_3_ Napravlenie glavnogo udara_HD.ts
#1 file_name=O
#1 file_size=5364186704
#2 file_path=Osvobozhdenie\Osvobozhdenie_Season 1_Ep_2_Proryv_HD.ts
#2 file_name=O
#2 file_size=3462072452
#3 file_path=Osvobozhdenie\Osvobozhdenie_Season 1_Ep_1_Ognennaya duga_HD.ts
#3 file_name=O
#3 file_size=3600812316
#0 0 B from 5.00 GB (0%) rate=0 B
#1 0 B from 3.22 GB (0%) rate=0 B
#2 0 B from 3.35 GB (0%) rate=0 B
UDP error: The file handle supplied is not valid from: 0.0.0.0
UDP error: The file handle supplied is not valid from: 0.0.0.0
UDP error: The file handle supplied is not valid from: 0.0.0.0
UDP error: The file handle supplied is not valid from: 0.0.0.0
successfully listening on [TCP] [::]:6881
successfully listening on [TCP] 0.0.0.0:6881
successfully listening on [UDP] 0.0.0.0:6881
added torrent: Osvobozhdenie
Osvobozhdenie added
Osvobozhdenie: state changed to: downloading
Osvobozhdenie checked
Osvobozhdenie resumed
Osvobozhdenie (http://bt01.nnm-club.cc:2710/ffffffffece2aa7a10770d152932daa1/announce) (-1) No such host is known "" (1)
Osvobozhdenie (http://bt01.nnm-club.info:2710/ffffffffece2aa7a10770d152932daa1/announce) (-1) No such host is known "" (1)
Osvobozhdenie (http://retracker.local/announce.php?size=12427071472&comment=http%3A%2F%2Fnnmclub.to%2Fforum%2Fviewtopic.php%3Fp%3D10700122&name=%CE%F1%E2%EE%E1%EE%E6%E4%E5%ED%E8%E5+%281967-1971%2F2020%29+HDTV+%5BH.264%2F1080i-LQ%5D+%28%F4%E8%EB%FC%EC+1-3+%E8%E7+5%29+%5B%CA%E8%ED%EE%FD%EF%EE%EF%E5%FF%5D+%28%CE%E1%ED%EE%E2%EB%FF%E5%EC%E0%FF%29) (-1) No such host is known "" (1)
Osvobozhdenie (http://[2001:470:25:482::2]:2710/ffffffffece2aa7a10770d152932daa1/announce) (-1) No such host is known "" (1)
Osvobozhdenie (http://bt01.nnm-club.cc:2710/ffffffffece2aa7a10770d152932daa1/announce) (-1) No such host is known "" (2)
Osvobozhdenie (http://bt01.nnm-club.info:2710/ffffffffece2aa7a10770d152932daa1/announce) (-1) No such host is known "" (2)
Osvobozhdenie (http://retracker.local/announce.php?size=12427071472&comment=http%3A%2F%2Fnnmclub.to%2Fforum%2Fviewtopic.php%3Fp%3D10700122&name=%CE%F1%E2%EE%E1%EE%E6%E4%E5%ED%E8%E5+%281967-1971%2F2020%29+HDTV+%5BH.264%2F1080i-LQ%5D+%28%F4%E8%EB%FC%EC+1-3+%E8%E7+5%29+%5B%CA%E8%ED%EE%FD%EF%EE%EF%E5%FF%5D+%28%CE%E1%ED%EE%E2%EB%FF%E5%EC%E0%FF%29) (-1) No such host is known "" (2)
Osvobozhdenie (http://[2001:470:25:482::2]:2710/ffffffffece2aa7a10770d152932daa1/announce) (-1) No such host is known "" (2)

**Comment by arvidn** [comment]
I get the impression that you don't expect these errors:

```
 (-1) No such host is known "" (1)
```

You could set a break point in resolver.cpp to see where that error is coming from. If it only happens when you enable a proxy, it's probably related to the hostname lookup of the proxy itself.

**Comment by arvidn** [comment]
> proxy.hostname = proxy.proxy_hostnames = "64.235.204.107";

That's most likely the problem. You really should increase the warning level (and use warnings-as-errors) in your compiler.
