### ISSUE TITLE
Q; Release schedule for v2

### ISSUE THREAD

**Issue by vktr** [arvidn/libtorrent#5187]
Not an issue really, more of a question. 

Are we supposed to follow the RC_2_0 branch or will you do release tags like with v2.0.0?

Also, if tagging, would it be possible to follow semver as you did with the v2.0.0 release?

**Comment by arvidn** [comment]
> Are we supposed to follow the RC_2_0 branch or will you do release tags like with v2.0.0?

`RC_2_0` is the current stable branch. There will be more releases out of this branch, and I expect they will be 2.0.x, as that's the convention I've used so far for ABI stability (where the major and minor indicate the ABI version). I'm open to suggestions though.

> Also, if tagging, would it be possible to follow semver as you did with the v2.0.0 release?

yes, I intend to use the `v<version>` format for release tags going forward.

**Comment by vktr** [comment]
Sweet! I don’t know enough about ABI vs API to have a strong opinion - in PicoTorrent we build libtorrent from source
