### ISSUE TITLE
Use GitHub Actions for Windows build

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#5189]
libtorrent branch: `master`
platform: `windows`

Appveyor is just too slow because its a single job at a time. GitHub Actions should improve the waiting time of PR merges.

**Comment by arvidn** [comment]
yes, it seems github actions could be quite helpful. I think travis supports windows these days too. It just takes a *lot* of time to get a new environment set up (at least to fully replace all the things appveyor does today).

**Comment by FranciscoPombal** [comment]
@arvidn 

I don't know about the rest, but if all your doing with CMake in Appveyor is just the the build, I can contribute something like what I recently did for qBIttorrent: https://github.com/qbittorrent/qBittorrent/blob/2bfaa8229a8f3ed00eabaf60f7039c7be4d4de25/.github/workflows/ci.yaml#L83. It's easy with vcpkg. The rest (b2 builds and test runs) could be added later.

The results have been quite good so far: https://github.com/qbittorrent/qBittorrent/actions. Apart from the very first run which was of course uncached, all Windows builds tend to finish in under 15 minutes, with the occasional excursion a bit over that, and the very infrequent excursion up to 30-40 minutes. All of this while multiple builds can run at the same time easily. In contrast, sometimes I've waited 6+ hours for libtorrent builds on Appveyor to even start.

**Comment by arvidn** [comment]
please do!

**Comment by vktr** [comment]
@FranciscoPombal are you looking at this? I might make a try otherwise - I did the same for PicoTorrent the other day much based on the suggestion from this thread :)

**Comment by FranciscoPombal** [comment]
@vktr Yeah I should be able to post something either to day or during the weekend, got a bit delayed, sorry about that.

**Comment by vktr** [comment]
Awesome :) No stress from me, just didn't want to start anything that is being looked at

**Comment by FranciscoPombal** [comment]
https://github.com/arvidn/libtorrent/pull/5197
