### ISSUE TITLE
assert pe->hash == NULL failure

### ISSUE THREAD

**Issue by ssiloti** [arvidn/libtorrent#519]
I've been hitting this reliably running deluge with d332a03281b0776e6da111d5c665f3a1f09a3ed1 (latest RC_1_1 as of this writing). I'm not familiar with the disk io thread code so maybe arvid can figure this out a lot faster than I can.

[disk_io_thread debug log](https://github.com/arvidn/libtorrent/files/158100/hash-job-assert-log.txt)
[backtraces](https://github.com/arvidn/libtorrent/files/158102/hash-job-assert-bt.txt) (note disk_io_thread.cpp line numbers are offset by one because I had to add a #include <cstdarg> to build with the debug logging enabled)

**Comment by arvidn** [comment]
cool, I'll dig into this. did you get anything printed out to stderr? the TORRENT_PIECE_ASSERT() is supposed to print out the content of the cached_piece_entry as well

**Comment by arvidn** [comment]
do you have any particular disk cache related settings? it looks like you end up checking piece hashes without using a cache. Did you disable the disk cache? Any other settings, like locking the files used by the storage?

**Comment by arvidn** [comment]
I believe this assert is wrong. it assumes no other thread is touching the piece than the one that just ran. but once the hash job releases the piece, any other thread can do whatever it wants to it, so this assert runs too late.

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/522

**Comment by arvidn** [comment]
merged
