### ISSUE TITLE
Libtorrent 2.0 is not building statically

### ISSUE THREAD

**Issue by maxim20002000** [arvidn/libtorrent#5194]
**libtorrent version (or branch)**: 2.0 (and 1.2.10) the rest have not tried
**platform/architecture:** x32 Windows 
**compiler and compiler version:** MSVC 14.2
**boost version:** 1.68 - 1.74

_**Simple torrent client**_

Hi Arvid! I've been trying to build a libtorrent for a week now. It turned out only through the VCPKG, since he sets everything up himself. There is an outdated version 1.2.10, I left an update request in the microoft repository but still haven't updated. With the help of VCPKG, it turned out to build only with a dynamic binding and /MDd and others prepocessor definitions.
But torrent file not downloaded, through the task manager, I see that the download speed increases in 3 seconds and a request from the firewall to give access. Then the speed drops to 0 and does not load. 

Somehow I managed to build through the boost build **libtorrent.lib** 
And here is the question, is it necessary to connect the openssl library? I tried without and the error is that there is no **ERROR LINK 2001 _Bcrypt ....** and if with it other errors fall.

I managed to reduce the list of errors to 2. But I don't know how to solve them.
![image](https://user-images.githubusercontent.com/54287601/94941656-e15a3100-04dd-11eb-9ff5-c83c0d490ac6.png)

Dear Arvid, I will be extremely happy if you tell in detail which versions are compatible with which (OpenSSL, Libtorrent, Boost, MSVC). I need a simple torrent downloader. You can also record a video so as not to write text. The priority is to build a static library.
Thank you very much in advance!

**Comment by maxim20002000** [comment]
I saw your assembly instructions. But there is always a mistake at some stage.

**Comment by vktr** [comment]
Link against  iphlpapi as well

**Comment by maxim20002000** [comment]
> Link against iphlpapi as well

Where to get it?

**Comment by vktr** [comment]
Yes, did it help?

**Comment by arvidn** [comment]
When you build libtorrent as a static library, it is YOUR responsibility to link against any dependencies libtorrent has. This is because dependencies are not recorded in archives (.lib) the way they are in shared libraries (.dll).

Normally this is the task of the build system, to propagate dependencies. However, I get the impression you're building the .lib with boost build, and then use visual studio to link against it. This effectively severs the build system's ability to propagate the dependencies.

If you would build your client with boost build, it would probably just work.

**Comment by maxim20002000** [comment]
> When you build libtorrent as a static library, it is YOUR responsibility to link against any dependencies libtorrent has. This is because dependencies are not recorded in archives (.lib) the way they are in shared libraries (.dll).
> 
> Normally this is the task of the build system, to propagate dependencies. However, I get the impression you're building the .lib with boost build, and then use visual studio to link against it. This effectively severs the build system's ability to propagate the dependencies.
> 
> If you would build your client with boost build, it would probably just work.
I was build: 
**b2 toolset=msvc-14.2 variant=release link=static runtime-link=static debug-symbols=on cxxstd=14 crypto=openssl openssl-lib=*** openssl-include=*****
libtorrent.lib weight around 600mb. Do I have to add openssl to boost build cmd line?And what defenitions preprocessor is needed to build a simple torrent client?

**Comment by arvidn** [comment]
Would you expect it to be less than 600 MB?

I don't think you need to define any macros when building the client, other than the ones defined when you built the library. e.g TORRENT_NO_DEPRECATE. It didn't look like you disabled deprecated functions though.

Do you get any link errors that make you ask?

When linking statically against the run-time library, you are expected to know what you're doing too, btw.

**Comment by maxim20002000** [comment]
I added **#pragma comment(lib, "IPHLPAPI.lib")** and some error disappeared.
But new problems arose and **#pragma comment(lib, "legacy_stdio_definitions.lib")** only solves a few of them.
![image](https://user-images.githubusercontent.com/54287601/94998310-a2011280-05b9-11eb-8519-53529263b1e0.png)
![image](https://user-images.githubusercontent.com/54287601/94998316-b80ed300-05b9-11eb-87ea-f8c355e048b4.png)

**OpenSSL version 1.1.1h**
with cmd line **_perl Configure VC-WIN32 --prefix=D:\libtor\BuildOpenSSL\lib --openssldir=D:\libtor\BuildOpenSSL\SSL no-shared_**

b2 cmd line **b2 -n -a toolset=msvc-14.2 variant=release link=static runtime-link=static debug-symbols=on cxxstd=14 crypto=openssl openssl-lib=D:\libtor\BuildOpenSSL\lib\lib openssl-include=D:\libtor\BuildOpenSSL\lib\include address-model=32 architecture=x86**

To linker add path to **libcrypto.lib libssl.lib libtorrent.lib**

Runtime lib **/MT**
![image](https://user-images.githubusercontent.com/54287601/94998540-1a1c0800-05bb-11eb-9627-06710efc8263.png)


With **-n -a** keys in **b2** i saw and after that added to MS Visual Studio

BOOST_ALL_NO_LIB
BOOST_ASIO_ENABLE_CANCELIO
BOOST_ASIO_HAS_STD_CHRONO
BOOST_ASIO_NO_DEPRECATED
BOOST_MULTI_INDEX_DISABLE_SERIALIZATION
BOOST_NO_DEPRECATED
BOOST_SYSTEM_NO_DEPRECATED
BOOST_SYSTEM_STATIC_LINK=1
NDEBUG
OPENSSL_NO_SSL2
TORRENT_BUILDING_LIBRARY
TORRENT_SSL_PEERS
TORRENT_USE_I2P=1
TORRENT_USE_LIBCRYPTO
TORRENT_USE_OPENSSL
WIN32
WIN32_LEAN_AND_MEAN
_CRT_SECURE_NO_DEPRECATE
_FILE_OFFSET_BITS=64
_SCL_SECURE_NO_DEPRECATE
_WIN32
_WIN32_WINNT=0x0600
__USE_W32_SOCKETS

What else could be the problem?

**Comment by maxim20002000** [comment]
**Succesfully builded!** Solution from stackoverflow helped
![image](https://user-images.githubusercontent.com/54287601/94998920-4422f980-05be-11eb-8699-f9de03bf3ac8.png)

**BUT,
Torrent files never download: ((**
As I wrote above, using the example of assembling VCPKG with DLL and version 1.2.10. The speed at the beginning increases for a few seconds, then drops to 0.
![image](https://user-images.githubusercontent.com/54287601/94998887-f27a6f00-05bd-11eb-8056-cdea0d20aa7f.png)

please help

**Comment by maxim20002000** [comment]
Only few seconds ... 
![image](https://user-images.githubusercontent.com/54287601/94999238-d1ffe400-05c0-11eb-8731-e616058eab61.png)

**Comment by arvidn** [comment]
I would really suggest you get things to work before you link statically against The run-time. Are you confident the issue you're experiencing is not caused by an issue in your build? Did you build libssl and libcrypto in a compatible configuration?

As for the problem you experience, please provide more details. Do you get any peers? Do you bootstrap the DHT? Do you get tracker responses? Do you get any error alerts?

**Comment by arvidn** [comment]
Also, posting text is much better than posting images

**Comment by maxim20002000** [comment]
Arvidn, pls link to message  **libtorrent.exe** if your have. I will test in my PC . Thanks

**Comment by arvidn** [comment]
I don't know what you mean by that.

**Comment by arvidn** [comment]
You want a client_test binary?for windows? I don't have access to my windows VM to build one right now

**Comment by maxim20002000** [comment]
Yes, binary for windows. I'm not hurrying. Please try to build one of these days and please describe all your actions.

**Comment by arvidn** [comment]
if you just want precise instructions on how to build on windows, you can look at the [appveyor file](https://github.com/arvidn/libtorrent/blob/RC_2_0/appveyor.yml). There's some complexity in there because it supports a bunch of different configurations.

Specifically:

```
b2.exe --hash openssl-lib=%ssl_lib% openssl-include=%ssl_include% warnings=all warnings-as-errors=on -j %NUMBER_OF_PROCESSORS% %compiler% address-model=%model% picker-debugging=on invariant-checks=full variant=%variant% link=shared crypto=%crypto% asserts=on export-extra=on
```

for example, you can set the variables to: `variant` = `release`, `model` = `64`, `crypto` = `openssl`. I would recommend you set the `BOOST_ROOT` environment variable to your boost directory path.

**Comment by 5523eeOMEGALUL** [comment]
> Torrent files never download:
to see what's going on you have to run message loop
see client_test.cpp pop_alerts(), handle_alert() fns
simpliest loop would be
while (-1) {
std::vector<lt::alert*> alerts;
s.pop_alerts(&alerts);
for (auto a : alerts) {
printf("alert, cat %d, type %d, %s", a->category(), a->type(), lt::alert_name(a->type()));
//if (0 != (a->category() & lt::alert_category::error)) continue;
printf("%s", a->message());
}
std::this_thread::sleep_for(std::chrono::milliseconds(1000)
}
put after `s.add_torrent(p);` in simple_client.cpp
also add on top
#include <SDKDDKVer.h>
#include <chrono>
#include <vector>
#include <thread>
uncomment commented line if code crash

**Comment by maxim20002000** [comment]
I tried to build a library as the guy wrote [here.](https://github.com/arvidn/libtorrent/issues/3608) I got the same errors as he did, I successfully built a shared library. Didn't even have to use preprocessor definitions. But again, the **torrent does not download** the file ((

**Comment by maxim20002000** [comment]
> @maxim20002000
> 
> > Torrent files never download:
> 
> to see what's going on you have to run message loop
> see client_test.cpp pop_alerts(), handle_alert() fns
> simpliest loop would be
> while (-1) {
> std::vectorlt::alert* alerts;
> s.pop_alerts(&alerts);
> for (auto a : alerts) {
> printf("alert, cat %d, type %d, %s", a->category(), a->type(), lt::alert_name(a->type()).c_str());
> //if (0 != (a->category() & lt::alert_category::error)) continue;
> printf("%s", a->message().c_str());
> }
> std::this_thread::sleep_for(std::chrono::milliseconds(1000)
> }
> put after `s.add_torrent(p);` in simple_client.cpp
> also add on top
> #include <SDKDDKVer.h>
> #include < chrono>
> #include < vector>
> #include < thread>
> uncomment commented line if code crash

Visual studio stresses  **lt::alert_name(a->type()).c_str());** and not building

**Comment by maxim20002000** [comment]
An acquaintance told me that this could be due to the fact that the **torrent tracker rejects this client** as it only downloads and does not share with the others. It does not emulate either qtorrent or bittorrent.
------------
 @Arvidn, what do you think about this? On what operating system did you build and with what compiler?

**Comment by arvidn** [comment]
If the tracker is rejecting the client it would show up in a tracker alert. If you print alerts you will know.

I build with gcc, clang and msvc on Linux, Mac and windows. That's extremely unlikely to affect whether your torrent can be downloaded or not though. Please look at the error messages.

**Comment by maxim20002000** [comment]
> That's extremely unlikely to affect whether your torrent can be downloaded or not though. Please look at the error messages.

If not difficult, please leave a piece of code for simple_client to show errors and alerts
compiled without error. I myself am not good at C ++ and it will take me too long to understand where the error is.

**Comment by arvidn** [comment]
`simple_client.cpp` does not print alerts, as it's meant to be the simplest possible example. You could try `bt-get.cpp` instead. Add the `lt::alert_category::tracker` to the `alert_mask` setting to get more tracker messages.

**Comment by MassaRoddel** [comment]
For legacy stdio support you have to provide your own __io_func definition (google helps). Seems to me that you build openssl with old stdio support (older toolset?).

**Comment by 5523eeOMEGALUL** [comment]
> Visual studio stresses **lt::alert_name(a->type()).c_str());** and not building

TORRENT_EXPORT char const* alert_name(int alert_type);
`char const*` not need .c_str() conversion for printf()

**Comment by maxim20002000** [comment]
> You could try `bt-get.cpp` instead. 
@arvidn Hooray! Tried `bt-get.cpp` and loads everything without problems! 
Again, I had to add a few lines of code to get the project to build.
```
#pragma comment(lib, "IPHLPAPI.lib")
#pragma comment(lib, "crypt32.lib")
#pragma comment(lib, "legacy_stdio_definitions.lib")

FILE _iob[] = { *stdin, *stdout, *stderr };
extern "C" FILE * __cdecl __iob_func(void) { return _iob; }
```

**Comment by maxim20002000** [comment]
Now i will try to understand why `simple_client.cpp` not downloaded )

**Comment by arvidn** [comment]
> Again, I had to add a few lines of code to get the project to build.

You have something strange going on in your build environment. Those issues are related to the standard library, not libtorrent.

**Comment by maxim20002000** [comment]
> > Again, I had to add a few lines of code to get the project to build.
> 
> You have something strange going on in your build environment. Those issues are related to the standard library, not libtorrent.

@arvidn  I founded problem in `simple_client` .  String  `p.save_path = "./";` not working for Windows and when i tried debug code, in this step code not crushing.  In `bt-get.cpp` path without slash `p.save_path = ".";`

`simple_client` **working correctly** now with `p.save_path = ".";` 🎉

Please, past in examples this notation `p.save_path = ".";`  and this code in comment:
```
#pragma comment(lib, "IPHLPAPI.lib")
#pragma comment(lib, "crypt32.lib")
#pragma comment(lib, "legacy_stdio_definitions.lib")

FILE _iob[] = { *stdin, *stdout, *stderr };
extern "C" FILE * __cdecl __iob_func(void) { return _iob; }
```
I believe that the issue can be closed. Many thanks to everyone for participating in solving the problem!

**Comment by vktr** [comment]
Hey @maxim20002000 - here's how to build a very opinionated version (static Boost and OpenSSL, dynamic runtime) libtorrent (the v2.0.0 tag) from scratch. **Not** using vcpkg since it contains an old version. This is for a x64 build with CMake, so make sure you have CMake installed and available in your path.

1. Install the pre-built Boost binaries from here, https://sourceforge.net/projects/boost/files/boost-binaries/1.74.0/boost_1_74_0-msvc-14.2-64.exe/download. Use the default install location.
2. Install the pre-built Win64 OpenSSL binaries from here, https://slproweb.com/download/Win64OpenSSL-1_1_1h.exe. Use the following option - install to the OpenSSL directory.
![image](https://user-images.githubusercontent.com/1491824/95178596-ecec7700-07bf-11eb-9842-90bd368f6a1f.png)
3. With both Boost and OpenSSL installed, run the following commands inside the libtorrent source folder;

```
> git clone --depth 1 --branch v2.0.0 --recurse-submodules https://github.com/arvidn/libtorrent; cd libtorrent
> mkdir build; cd build
> cmake -DBOOST_ROOT=C:/local/boost_1_74_0 -DBoost_USE_STATIC_LIBS=ON -DOPENSSL_USE_STATIC_LIBS=ON -Dbuild_examples=ON -DBUILD_SHARED_LIBS=OFF -Ddeprecated-functions=OFF ..
> cmake --build . --config Release
```

This will produce the example programs in the folder `build/examples/Release`.

For example, the following should work fine now - `.\client_test.exe <path-to-torrent>`.

You should *not* have to use `legacy_stdio_definitions`, etc.

**Comment by FranciscoPombal** [comment]
You can also use vcpkg to install everything except libtorrent, and then build libtorrent using the vcpkg dependencies/toolchian.

**Comment by maxim20002000** [comment]
> Hey @maxim20002000 - here's how to build a very opinionated version of libtorrent-2.0.0 (static Boost and OpenSSL, dynamic runtime) from scratch. **Not** using vcpkg since it contains an old version of libtorrent as you said. This is for a x64 build with CMake, so make sure you have CMake installed and available in your path. You should be able to deduce the x86 build from these instructions - just install the correct Boost and OpenSSL versions.
> 
> 1. Install the pre-built Boost binaries from here, https://sourceforge.net/projects/boost/files/boost-binaries/1.74.0/boost_1_74_0-msvc-14.2-64.exe/download. Use the default install location.
> 2. Install the pre-built Win64 OpenSSL binaries from here, https://slproweb.com/download/Win64OpenSSL-1_1_1h.exe. Install the binaries to the OpenSSL directory.
> 3. With both Boost and OpenSSL installed, the following commands would get you release binaries;
> 
> ```
> > git clone --depth 1 --branch v2.0.0 --recurse-submodules https://github.com/arvidn/libtorrent; cd libtorrent
> > mkdir build; cd build
> > cmake -DBOOST_ROOT=C:/local/boost_1_74_0 -DBoost_USE_STATIC_LIBS=ON -DOPENSSL_USE_STATIC_LIBS=ON -Dbuild_examples=ON -DBUILD_SHARED_LIBS=OFF -Ddeprecated-functions=OFF ..
> > cmake --build . --config Release
> ```
> 
> This will produce the example programs in the folder `build/examples/Release` and the following should work fine now - `.\client_test.exe <path-to-torrent>`.
> 
> You should _not_ have to use `legacy_stdio_definitions`, etc. I've seen this issue before and I believe it's your OpenSSL version that is built against the wrong runtime version.

Thank you very much for the detailed instructions 🤝. I believe that it should be on the library's website, since, although it is described in detail, it is confusing. And then it turned out in 3 steps to collect in 10 minutes. True, still need to correct by arms the download path in **simple_client**.

**Comment by maxim20002000** [comment]
> You can also use vcpkg to install everything except libtorrent, and then build libtorrent using the vcpkg dependencies/toolchian.

Also thanks for the answer. Your option is also one of the simple ones. 🤝
