### ISSUE TITLE
effectively test DHT on python binding

### ISSUE THREAD

**Issue by DiMartinoXBMC** [arvidn/libtorrent#52]
I have some code:

            is_dht_running='ON' if self.session.is_dht_running() else 'OFF'
            nodes=self.session.dht_state().get('nodes')
            nodes=len(nodes) if nodes else 0
            result='DHT: %s (%d)' % (is_dht_running, nodes)

So both 1.0.5 and 0.16.19 got "DHT: ON (>600)", but when I use private trackers with only 1 tracker in torrent file and it fails to give info (that happens a lot), 1.0.5 can't find seeds for 2-10 mins until tracker become verified and 0.16.19 searching seeds like a beast no matter what.

Both libraries built with the same keys.

The code is the same for both tests, this is how I start dht:

        self.session.start_dht()
        self.session.add_dht_router("router.bittorrent.com", 6881)
        self.session.add_dht_router("router.utorrent.com", 6881)
        self.session.add_dht_router("router.bitcomet.com", 6881)

The question is: how can I deeper debug DHT on python binding?

**Comment by arvidn** [comment]
for private torrents, the DHT is not used, right? I don't think I quite get what the issue you're seeing is. You're seeing 1.0.5 take a long time finding peers? or does it find peers, just none of them are seeds?
And you're saying it isn't finding any seeds until the tracker responds? but 0.16.9 does find seeds before the tracker responds? (presumably via the DHT). That means you're not testing private torrents then, is that right? (either that, or 0.16.9 has a bug where it announces private torrents to the DHT).

In either case, to debug the DHT you can build with DHT logging enabled (on the b2 command line, add dht=logging). This will make libtorrent log basically all the DHT activity to dht.log in current working directory.

Do you save the DHT state on exit and load it on startup? If not, that would probably significantly improve performance (since it can then cache DHT nodes to bootstrap from)

**Comment by DiMartinoXBMC** [comment]
[Logs](https://yadi.sk/d/exX5EEGpi6H9n) dht logs only for 1.0.5 because I couldn't build 0.16.19 with it (guess logging is new for dht). There are two files mylog.txt, it is the output of cal.py.

Yes, I meant peers, not only seeds. 0.16.9 does find seeds before the tracker responds correctly, unlike 1.0.5.

I don't save DHT state, got problems with cross-platform storage (and import as well), so I prefer not to use any caches.

**Comment by arvidn** [comment]
It's not obvious that this problem is related to the DHT. I'll take a closer look at the dht log, but in the meantime you may want to take a look at the trouble shooting guide http://libtorrent.org/troubleshooting.html

**Comment by DiMartinoXBMC** [comment]
I got to the point "The DHT is probably not working correctly".

By the way, I built 1.0.6 with dht=logging but logs did not apear.  I tested 1.0.6 and it doesn't work just like 1.0.5. 

Is that normal that on both 1.0.5 and 0.16.19 session.dht_torrents = 0 and all vars in dht_lookup, but 0.16.19 works.

**Comment by arvidn** [comment]
when collecting those DHT logs, how long did you run for?
The dht_stats.log only has 3 rows in it, suggesting the DHT shut down after
3 seconds (which isn't enough to bootstrap).

The dht.log is for 2 minutes 35 seconds though. The
dht_routing_table_state.txt suggests that you have lots of DHT nodes. If
you see the session stats saying you have 0 nodes, I'm guessing there's
either a reporting bug or you're looking in the wrong place.

actually, a closer look at the dht.log indicates that you cause the DHT to
be restart twice (started three times) in the first 100 ms. You should
probably fix that. (try adding the router nodes first, then starting the
DHT).

It also looks like the torrent you add ends up announcing to one of the
first two instances of the DHT, which get shut down. You may want to try
pausing and resuming the torrent after you start to see if it will announce
to the DHT again, and succeed.



On Thu, Jul 30, 2015 at 4:04 PM, DiMartinoXBMC <notifications@github.com>
wrote:

> I got to the point "The DHT is probably not working correctly".
>
> By the way, I built 1.0.6 with dht=logging but logs did not apear. I
> tested 1.0.6 and it doesn't work just like 1.0.5.
>
> Is that normal that on both 1.0.5 and 0.16.19 session.dht_torrents = 0 and
> all vars in dht_lookup, but 0.16.19 works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arvidn/libtorrent/issues/52#issuecomment-126463165>.
>



-- 
Arvid Norberg

**Comment by DiMartinoXBMC** [comment]
Thanks for answer! First of all logging works fine, sorry.

Second, you really helped, now I can workaround it.
I used two methods first try torrent_handle.force_dht_announce and then session.pause/resume.

This is my test results (dht logs):
[#1](https://yadi.sk/d/Ockj2dCsiCm3M) dht_start() is before add_router, download starts only after pause/resume, but nodes are found after force_dht_announce,

[#2](https://yadi.sk/d/LDFUV5xoiCm3R) dht_start() is after add_router, download starts after force_dht_announce

**Comment by arvidn** [comment]
you mean if you load and restore dht state?

It sounds like there's a "race" then. where the DHT is started, you add a torrent that announces to the DHT. you add a router node or something else causes it to be restarted, the previous DHT is shut down and your torrent won't hear back from it. and there's a new DHT that's bootstrapping and working well.

I would also imagine that if you wait 15 minutes, the torrent would re-announce to the DHT, which probably would work.
