### ISSUE TITLE
Update python doc - read resume data

### ISSUE THREAD

**Issue by latot** [arvidn/libtorrent#5205]
Hi hi, I'm using the 1.2.6 version, I use the code of:
https://github.com/arvidn/libtorrent/blob/RC_2_0/bindings/python/client.py

```
lt.read_resume_data(open(resume_file, 'rb').read())
```

This code works before, but now I get this error from an update (Gentoo 64):

```
expected value (list, dict, int or string) in bencoded string
```

Probably something change in how pass the data or something, actually the resume files works in a previous version of libtorrent, so I think they are fine.

Thx.

**Comment by arvidn** [comment]
that errors comes from the bdecoder. it indicates that the resume file you're loading is corrupt, or at least not in the correct resume file format. you can use the example program `dump_torrent` to look at the file to see where it fails to decode.

**Comment by latot** [comment]
H hi @arvidn sorry, i was little busy, I test and check this, sadly I get the same with ```dump_torrent```.

Running trying to decode manually the resume file I get this:
```bencodepy.decode(open(file, "rb").read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.7/site-packages/bencodepy/decoder.py", line 100, in decode
    return decoder.decode()
  File "/home/user/.local/lib/python3.7/site-packages/bencodepy/decoder.py", line 55, in decode
    return self.__wrap_with_tuple()
  File "/home/user/.local/lib/python3.7/site-packages/bencodepy/decoder.py", line 63, in __wrap_with_tuple
    l.append(self.__parse())
  File "/home/user/.local/lib/python3.7/site-packages/bencodepy/decoder.py", line 50, in __parse
    'Invalid token character ({0}) at position {1}.'.format(str(char), str(self.idx)))
bencodepy.exceptions.DecodingError: "Invalid token character (b'\\x80') at position 0."
```

What is weird, I have a local server with libtorrent-rasterbar-1.1.11, and the same file works fine..., So I don't get very well why is failing.

Thx.

**Comment by arvidn** [comment]
is the file actually valid bencoding? If the first byte actually `0x80`? That doesn't look like valid encoding.

Also, `decoder.py` doesn't look like part of libtorrent. Is the problem that *saving* resume data in libtorrent is incorrect?

**Comment by latot** [comment]
Hi, at least, the files are valid for libtorrent 1.1.11.

Even if is not valid now, and the saving resume data is incorrect, at least the decode/encode for 1.1.11 can handles that resume data.

So, maybe betwen 1.1.11 and 1.2.6 (at least here i know fails) something changes in encode/decode of the resume data.

**Comment by arvidn** [comment]
could you please provide some details about where the resume data comes from, and how you save it to file and how you load it.

Can you confirm that the file has invalid bencoding? ideally by inspecting the actual bytes of the file, with `hexdump` or something like that. Are you sure your python decoder isn't interpreting the file as utf-8 for instance?

**Comment by latot** [comment]
Hi hi, @arvidn , maybe will be easy in this way, i'm sending a resume file, where it comes? a python script I wrote, is running over libtorrent-1.1.11, we get the file saving directly the resume data to a file, the error is caused when we load that resume file in 1.2.6 for example.

[test.zip](https://github.com/arvidn/libtorrent/files/5818719/test.zip)

**Comment by latot** [comment]
Hi, @arvidn , has been able to check above?

https://github.com/arvidn/libtorrent/issues/5205#issuecomment-760664689

Here more details:

py scritp in torrent 1.1.11
```
pickle.dump(lt.bencode(a.resume_data), sfile) (to save the resume data)
info = lt.torrent_info(lt.bdecode(open(torrent, 'rb').read())) (load the resume data)
```

my new script to newer version of libtorrent:
```
lt.read_resume_data(open(ifile, "rb").read()) (load resume data)
lt.write_resume_data_buf(a.params) (get the resume data, this is saved in a file with rb options)
```

**Comment by arvidn** [comment]
you use `pickle.dump()` to save the file to disk. The resume file format is *not* the pickle file format. Just save it to the file directly. use `sfile.write()`
