### ISSUE TITLE
Read access violation in piece_picker::get_download_queue

### ISSUE THREAD

**Issue by vktr** [arvidn/libtorrent#5212]
libtorrent version (or branch): v2.0.0
platform/architecture: Windows, x64
compiler and compiler version: MSVC-19

Since setting up Sentry.io on PicoTorrent I've seen two `EXCEPTION_ACCESS_VIOLATION_READ` occur in `piece_picker::get_download_queue`. Unfortunately, I don't have any call stack for them, and I don't think it's a critical issue since it's only two crashes per (what I guess is) thousands of application sessions.

Also, I only have local registers and no source file mapping. If you can make sense of it, great! Otherwise, feel free to close if it's all to vague.

**Case 1**

```
registers

r14 0x0000006c352ff9b8
r15 0x0000000000000001
r12 0x000001f7f0eadba0
r13 0x0000006c352ffd00
r10 0x0000000000000000
r11 0x000001f7f3d665e0
rsp 0x0000006c352ff910
rbx 0x00000000000000c0
r8  0x0000000000000002
r9  0x0000000000000002
rip 0x00007ff7b973a8c9
rbp 0x0000006c352ff9e0
rdx 0x0000000000000000
rcx 0x0000000000000000
rdi 0x0000000000000120
rax 0x0000000000000000
rsi 0x00000000000000b8
```

**Case 2**
```
registers

r14 0x00000008b46ff428
r15 0x0000000000000001
r12 0x0000010ff9c03c20
r13 0x00000008b46ff770
r10 0x0000000000000000
r11 0x0000010ffa34a310
rsp 0x00000008b46ff380
rbx 0x00000000000000c0
r8  0x0000000000000001
r9  0x0000000000000001
rip 0x00007ff74f38a8c9
rbp 0x00000008b46ff450
rdx 0x0000000000000000
rcx 0x0000000000000000
rdi 0x0000000000000120
rax 0x0000000000000000
rsi 0x0000000000000028
```

**Comment by arvidn** [comment]
it's not a lot to go on. You don't get minidumps for these? if so, assuming you saved or can reproduce the .pdb files, there should be a lot of information about what happened

**Comment by vktr** [comment]
I don't, unfortunately 🤷 Sentry does not store the minidumps, it discards them after processing. Anyway, there hasn't been more of this particular crash since creating the issue so I'm closing this one.
