### ISSUE TITLE
evaluate using `std::byte` or `uchar_t` for new code

### ISSUE THREAD

**Issue by geiseri** [arvidn/libtorrent#5219]
It seems that all the cool kids are using `unsigned char` for non-printable 8 bit data due to STR34-C and STR37-C and the fact those savages don't have an string type.  At any rate this has made working with crypto things from libsodium, libolm, and even some c++ libraries like jsoncons cumbersome since I need to `reinterpret_cast<uint8_t*>` going between them.  I am sure this is by no means feasible since it would break some fundamental parts of the API that other wrappers would be using.   Feel free to close this if it is unreasonable but please give rationale so future generations can find this on google =)

**Comment by arvidn** [comment]
using `std::byte` is on the TODO-list for master (2.0 and earlier don't use C++17). patches are welcome!

**Comment by arvidn** [comment]
however, I don't think `std::byte` would save you from the `reinterpret_cast`, would it? I suppose you may be able to use a `static_cast<>` instead

**Comment by geiseri** [comment]
gah, no it won't, it is actually just as bad!  https://godbolt.org/z/db8aoM seems to imply that `uint8_t` aka `unsigned char` is the best.  of course `std::byte` seems to be exactly what you want, since it's intent and operations are clear... but it's interop is horrid.  On the plus side this would not require C++17.

**Comment by OlafvdSpek** [comment]
What are STR34-C and STR37-C?
And how is uint8_t defined in your case?

**Comment by FranciscoPombal** [comment]
> What are STR34-C and STR37-C?

https://wiki.sei.cmu.edu/confluence/display/c/STR34-C.+Cast+characters+to+unsigned+char+before+converting+to+larger+integer+sizes

https://wiki.sei.cmu.edu/confluence/display/c/STR37-C.+Arguments+to+character-handling+functions+must+be+representable+as+an+unsigned+char
