### ISSUE TITLE
renaming folders and files

### ISSUE THREAD

**Issue by fmkovzpjmdiwdhqlwg** [arvidn/libtorrent#5229]
If I have a torrent handle and the torrent is arranged as follows:

root_folder
....sub_folder_1
........file_1_1
........file_1_2
....sub_folder_2
........file_2_1
........file_2_2

What is the recommended way of renaming sub_folder_2?

I have worked out that if I do:

torrent_handle::rename_file(index_of_file_2_1, "new_sub_folder_2/file_2_1");
torrent_handle::rename_file(index_of_file_2_1, "new_sub_folder_2/file_2_2");

I end up with:

root_folder
....sub_folder_1
........file_1_1
........file_1_2
....sub_folder_2
....new_sub_folder_2
........file_2_1
........file_2_2

But that leaves sub_folder_2 behind (and I can find no way to remove it). Surely there's a way to simply do:

rename_folder("sub_folder_2", "new_sub_folder_2");

and end up with:

root_folder
....sub_folder_1
........file_1_1
........file_1_2
....new_sub_folder_2
........file_2_1
........file_2_2

Also, if both file_2_1 and file_2_2 have been moved outside of the torrent you can't even do the above (because the only way to rename sub_folder_2 is to rename one of the files within it).

Obviously I'm not concerned with only this specific case, but with a general way to easily rename files and folders in a torrent. I simply cannot find any functions in the libtorrent api that rename anything other than rename_file (which is deficient in the ways I describe above), and move_storage (which simply moves the folder that root_folder is stored within and is therefore not usable for renaming subfolders).

For anyone that wants to ask why I need to do this: it's to be able to build a GUI that allows the user to rename the files and folders whilst the torrent is downloading.

**Comment by master255** [comment]
@fmkovzpjmdiwdhqlwg What is the final goal? What is this for?

**Comment by master255** [comment]
@fmkovzpjmdiwdhqlwg 

> it's to be able to build a GUI that allows the user to rename the files and folders whilst the torrent is downloading.

What, for example, may it be necessary for? Why not remove the torrent and add it with saving to another directory?
You generate ideas where no one else needs them.

**Comment by fmkovzpjmdiwdhqlwg** [comment]
> What, for example, may it be necessary for?

The GUI has a list view. In the list view there is a row for each folder or file in the torrent. The user right clicks a folder to get the context menu, and selects "rename". The user enters a new name. The program calls a libtorrent function to set the new name of the folder - only there is no function to do this.

> Why not remove the torrent and add it with saving to another directory?

a. The torrent will stop downloading whilst this is happening.
b. That's way overkill to simply rename a folder.
c. You cannot rename a sub folder by doing this, unless you are suggesting rebuilding the entire torrent with just the name of one sub folder different (in which case, see b. above).

**Comment by master255** [comment]
@fmkovzpjmdiwdhqlwg 

> The user right clicks a folder to get the context menu, and selects "rename". The user enters a new name.

In what scenarios will the user need it? For example?
For what, the user needs to move or rename files to other directories if they have not yet been downloaded?
And he can't use these files in any way and he doesn't know if they will be downloaded yet.

**Comment by vktr** [comment]
@master255 

> In what scenarios will the user need it? For example?
> For what, the user needs to move or rename files to other directories if they have not yet been downloaded?
> And he can't use these files in any way and he doesn't know if they will be downloaded yet.

It can be used to map some files from the torrent to files which already exists, so you don't have to download them.

**Comment by master255** [comment]
@vktr To do this, you can move and rename files before adding a torrent. Does it work?

**Comment by vktr** [comment]
Sure, that's a clunky way of solving the problem. One can also use `netcat` instead of relying on libtorrent at all, but almost no one does.

**Comment by fmkovzpjmdiwdhqlwg** [comment]
No. I need to make this clearer I see. Have you ever used a bittorrent client like, say, tixati? In tixati, when you add a torrent from a torrent file it will display the torrent files is a list view. In that list view you can select a row containing, say, a folder, and rename the folder. The folder name will then be changed on the disk (and in the list view, obviously). It doesn't matter if the torrent is currently downloading or not. It gives the user an interface where they can rearrange the files before they've all arrived. It's nice to be able to do that. Of course, the user could wait until all the files have arrived and then do as they please, but I want to provide that "rename on the fly" interface that tixati provides. For that, I need libtorrent to allow me to rename sub folders inside the torrent (without rebuilding the torrent, without stopping the torrent, and preferably easily by calling a single function).

**Comment by master255** [comment]
@fmkovzpjmdiwdhqlwg Ok. You can:
1. Save torrent_handle state.
2. Remove torrent_handle
3. Rename the file in the resulting at step 1 add_torrent_params.
4. Add add_torrent_params to the session.

**Comment by vktr** [comment]
@fmkovzpjmdiwdhqlwg I'm aligned with what you want to do. When you say that it leaves sub_folder_2 behind, do you mean on disk or in the representation of the torrent file?

`torrent_handle::rename_file` should do what you want to do in terms of renaming files and folders, but libtorrent does not offer a way of traversing the files as a tree, only a regular list of (duplicated) paths.

**Comment by fmkovzpjmdiwdhqlwg** [comment]
@master255: Are you saying to use the add_torrent_params::ti (torrent_info) pointer? Because I've tried that and it doesn't work (as the torrent_info::files pointer (and others) are all const, so you can't change anything).

@vktr: It leaves sub_folder_2 behind on disk. I guess I could delete the dangling folder myself but it's not nice to have to write complicated functions to do something that (in my opinion) should be built in. I guess I'll have to knuckle down and write a rename_subfolder function that calls rename_file for every file in the sub folder, ignores files that have been moved out of the torrent (ie. absolute paths), checks for dangling folders orphaned on disk, then somehow offers the user the choice of what to do if the however many calls to rename_file fail halfway through. You see, I was hoping that somewhere in libtorrent there was a function that would simply, once called, rename a folder on disk, thereby ensuring that all the files are moved at once. That way, it either works or it fails. Calling rename_file on each file, one by one, means adding code to track the moves and do whatever the user wants to do when the moves fail half way through.

**Comment by master255** [comment]
@fmkovzpjmdiwdhqlwg 
Method 1:
1. handle.rename_file
2. handle. flush_cache()
3. delete empty folder

Method 2:
1. Save torrent_handle state.
2. Remove torrent_handle
3. Rename the file in the resulting at step 1 add_torrent_params.
4. Add add_torrent_params to the session.

Which point is not clear?

**Comment by fmkovzpjmdiwdhqlwg** [comment]
@master255 

To begin with, I don't think you understand what I want to do. I'll try again. If I have:

root_folder
....sub_folder_1
........sub_folder_2
............file_2_1
............file_2_2
........file_1_1
........file_1_2

and I want to rename sub_folder_1, then I have to do (at least):

rename_file(..., file_2_1);
rename_file(..., file_2_2);
rename_file(..., file_1_1);
rename_file(..., file_1_2);

Bear in mind that there are likely to be many more files in the torrent than four, so I may have to call rename_file any number of times.

Whereas what I really want to do is to call:

rename_folder(sub_folder_1, "new_name_of_sub_folder_1");

and have the folder on disk be renamed, by libtorrent, and in one step (so that the however many rename_file calls that I'd otherwise have to do can't fail half way through and leave a mess in both my interface and on disk).

If I don't go through rename_file and instead try to hack about at the innards of libtorrent I would be yanking the carpet out from under it. For example, if I try to force the paths in torrent_info::files to another string and libtorrent has the matching file on disk open bad things will happen. That is why torrent_info::files returns a const value (I assume). So that the contents can't be changed.

Also, when you're using, say, windows explorer, and you select a file, then press F2, a small text box appears so that you can alter the file name. The file's name changes on disk when you press return. You don't have to reboot the operating system to make the new name stick do you? You telling me to stop the torrent, save it, change the innards of the its data, rebuild it, then re add it to the session means, besides all the code to do all that, (a) stopping the torrent and (b) rebuilding the contents of the list view. Both of these will very quickly get annoying for the user if they want to change the names of half a dozen folders in the torrent.

With regard to what you suggest:

> Method 1:

>    handle rename_file
>    handle flush_cache()
>    delete empty folder

(a) I want libtorrent to do it after a single function call by me. I don't want to have to call rename_file for every file in the torrent that is either at the same level or below the level of the folder that is being renamed. It could fail half way through. I have to track all the renames. I have to create a dialog box to ask the user what to do if it fails. I have to create a special case for files that are outside of the torrent. If all of the files that are within the folder that I'm trying to rename are outside of the torrent then I can't rename the folder at all. It's a hack (I'm trying to rename a folder by renaming the files within it).
(b) flush_cache flushes all the disk caches for the torrent and closes all the file handles. This will stop the torrent. It may not physically stop it (from libtorrent's point of view), but it will most certainly cause the download speed to fall. And this will happen every time the user changes a folder name. And in any case, why am I fiddling with libtorrent's disk caches to rename a folder?
(c) If by "delete empty folder" you mean on disk, then why am I deleting a folder that was created by libtorrent? Why doesn't it just rename it, update its innards to point to the new location, and continue on as if nothing happened? If you mean within libtorrent, how on earth do I delete the empty folder? Although I could obviously just ignore it, it's a hack (I'd have to check that each folder has something in it before adding it to the list view).

> Method 2:

>    Save torrent_handle state.
>    Remove torrent_handle
>    Rename the file in the resulting at step 1 add_torrent_params.
>    Add add_torrent_params to the session.

(a) The torrent would stop.
(b) I'd have to rebuild the list view.
(c) Both (a) and (b) would happen every time the user renamed a folder.
(d) I don't know for certain that it would, but my guess is that if I fiddle with the innards of the saved torrent (by which I take it you mean the resume file) and re add it to the session, then the hash value will be wrong (amongst other things). For example, the hash value within the 'info' field of the resume file must match the 'info-hash' field. So, to achieve what you suggest I would have to hack about with the innards of the resume file and then hack the hash values to match. I would also guess that this would make libtorrent unable to find the files on the network (because it will be looking for a completely different torrent with a completely different hash). And all of this to simply rename a folder. Don't you think it's a bit of a stretch?

**Comment by master255** [comment]
@fmkovzpjmdiwdhqlwg , @vktr 

> It can be used to map some files from the torrent to files which already exists, so you don't have to download them.

When you have files with already preloaded data, you will not rename the directory for that. You will rename the files.
If this renaming is done by the program, all the more so you will rename the files, not the directory, as this is the best way to do it for a torrent.
If a library does this, it will also rename files, not directories. The library does not deal with directories, but with files.

**Comment by vktr** [comment]
@master255 

> The library does not deal with directories, but with files.

I don't think anyone in this thread is disagreeing with this statement (which is only true depending on your definition of "deal with").

**Comment by fmkovzpjmdiwdhqlwg** [comment]
@master255

> When you have files with already preloaded data, you will not rename the directory for that. You will rename the files.
> If this renaming is done by the program, all the more so you will rename the files, not the directory, as this is the best way to do it for a torrent.
> If a library does this, it will also rename files, not directories. The library does not deal with directories, but with files.

I'm afraid that there's a language barrier between you and I that I cannot overcome. To me, it seems that you think that I want to take an existing fully downloaded set of files that have no torrent and add them to a session as a new torrent for the purpose of uploading them. That's not it I'm afraid. I have explained it above and I don't really know how else to explain it. I want to dynamically change the names of the folders of an existing torrent that is already loaded into a libtorrent session, and I don't want to stop the torrent to do it. The files don't matter for this discussion (because rename_file handles that just fine). If you like, you could say that I want to change the content of the file_storage::paths that is within torrent_info::files, and that I want it to affect the folder names on disk. It's not a question of how libtorrent sees the files, it's a question of providing a useful, easy to use interface to rename a torrent's folders for the the user of my GUI. They can already rename the files by pressing F2, typing a new name, and return. They cannot rename the folders at all yet, but I want them to be able to rename them in the same easy way as the files.

**Comment by master255** [comment]
@fmkovzpjmdiwdhqlwg And what are the problems with renaming all the files inside the directory?

**Comment by fmkovzpjmdiwdhqlwg** [comment]
@master255 

> And what are the problems with renaming all the files inside the directory?

See above. I've stated them multiple times now.

> It does not matter on which side it will be done. On the application or library side. It will still rename the files and the logic will be the same.

No it won't. libtorrent could call the operating system's rename folder function and update its internal path. That's one function call (that can't fail half way through) and one string to be updated. The application has to call rename_file umpteen times (which can fail half way through), has to track the calls (in order to undo a half failure), deal with edge cases (such as all the files in a folder being outside of the torrent), and all the other problems I've already outlined above. The application is forced to abuse a function that was meant for something else to hack the innards of libtorrent. libtorrent could just do it in two easy steps.

**Comment by master255** [comment]
@fmkovzpjmdiwdhqlwg 

>  libtorrent could just do it in two easy steps.

I think the implementation of this feature will reduce the speed of working with files in other scenarios. You never gave any example of what it might be used for.
Users will not rename entire directories to continue downloading files. This is an extremely rare scenario. Perhaps there are some more necessary scenarios?

**Comment by fmkovzpjmdiwdhqlwg** [comment]
Sorry, but I give up.

> I think the implementation of this feature will reduce the speed of working with files in other operations.

Why on earth would it...

> You never gave any example of what it might be used for.

It's all I've been telling you above, again and again...

> Users will not rename entire directories to continue downloading files. This is an extremely rare scenario.

Download tixati. Start a download. Rename files or folders til your heart's content. It's useful. It's helpful. It's a nice feature. The fact that you seem dead set against it is obvious, but who knows how many users of tixati (and other) bittorrent clients would beg to differ.

> Perhaps there are some more necessary scenarios?

Like what? It's to enable the user to rename folders whilst the torrent is downloading. It's not going make your breakfast or fix your life.

As I say, I give up. Frankly, I think you're trolling me.

**Comment by master255** [comment]
@fmkovzpjmdiwdhqlwg 

> Download tixati. Start a download. Rename files or folders til your heart's content. It's useful. It's helpful. It's a nice feature.

Perhaps you can give a more specific example? For example, do you download a big movie consisting of seasons? Or a very large program? In what type of content may it be needed?

**Comment by arvidn** [comment]
@master255 please don't post if you're not going to help.

@fmkovzpjmdiwdhqlwg There is not feature in libtorrent to rename a whole folder. There is no strong technical reason there couldn't be, it's just that torrents are normally treated as a flat list of files, and not so much a directory hierarchy.

The reason for the old folder to remain is that, since only individual files are renamed, it may not be desirable to remove the directory, even when it's empty. It's kind of up to you to do that, after you've renamed all the files.

One thing to keep in mind is that the directory *may* contain files that don't belong to the torrent, that may not be removed. Another issue is that the directory may still contain files that *do* belong to the torrent, but haven't been downloaded yet (so just attempting to delete the directory in case it's empty is also not correct). If you know that you rename all files in this directory, you could remove it still. However, you need to wait for the alert to signal the completion.

The disk I/O subsystem is threaded, so there may be multiple threads accessing various files (or the same files). When a file is renamed, the rename operation is synchronized with all disk threads. It blocks all new disk jobs for the torrent, queuing them up. Once all jobs ahead of it have completed, the rename job runs, with exclusive access to the files for this torrent. This is where it's renamed.

At this point the rename *could* be of a directory (which would be a bit more complicated since multiple file entries would have to be updated) or it could be a bulk filr-rename operation. But today only a single file rename is implemented.
