### ISSUE TITLE
http_seed or url_seed examples

### ISSUE THREAD

**Issue by a2a111** [arvidn/libtorrent#5236]
Dears:
 Forgive me for my poor English！！
 I have a file in http server， for example: http://10.69.142.18:8765/coec_ns_feature_hourly_simplify.db.
I want to download the file use libtorrent. I can't find an example.
I make torrent file for the file and add_url_seed("http://10.69.142.18:8765/coec_ns_feature_hourly_simplify.db"), 
but I can't download the file use examples simple_client  ,it stay at downloading ,peer:1.
Maybe I am not use url_seed correct，I am not find http_seed or url_seed examples，who can help me，thanks。

**Comment by arvidn** [comment]
how do you create the torrent? and how do you add the URL seed to the torrent?

note that there are two kinds of web seeds (BEP 17 and BEP 19 iirc). One of them isn't used much.

**Comment by a2a111** [comment]
`import sys
import os
import libtorrent

if len(sys.argv) < 2:
    print('usage make_torrent.py file tracker-url')
    sys.exit(1)

input = os.path.abspath(sys.argv[1])

fs = libtorrent.file_storage()

parent_input = os.path.split(input)[0]
libtorrent.add_files(fs, input)

if fs.num_files() == 0:
    print('no files added')
    sys.exit(1)

t = libtorrent.create_torrent(fs, 4*1024*1024)

t.add_tracker("http://10.69.142.19:6666/announce")
t.set_creator('libtorrent %s' % libtorrent.version)
t.add_url_seed("http://10.69.142.18:8765/coec_ns_feature_hourly_simplify.db.1.tar")
libtorrent.set_piece_hashes(t, parent_input, lambda x: sys.stdout.write('.'))
raw = t.generate()
print libtorrent.make_magnet_uri(libtorrent.torrent_info(raw))
sys.stdout.write('\n')

f = open('out.torrent', 'wb+')
f.write(libtorrent.bencode(t.generate()))
f.close()`

then i use simple_client to download out.torrent

logs:
web seed connection started: [10.69.142.18:8765] http://10.69.142.18:8765/coec_ns_feature_hourly_simplify.db.1.tar')
('alert', 'coec_ns_feature_hourly_simplify.db.1.tar peer [ 10.69.142.18:8765 client: Unknown ] [10.69.142.18:8765] *** SET_PEER_CLASS [ a: 10.69.142.18 ]')
('alert', 'coec_ns_feature_hourly_simplify.db.1.tar peer [ 10.69.142.18:8765 client: Unknown ] [10.69.142.18:8765] *** CLASS [ tcp local  ]')
('alert', 'coec_ns_feature_hourly_simplify.db.1.tar peer [ 10.69.142.18:8765 client: Unknown ] [10.69.142.18:8765] >>> OPEN [ protocol: IPv4 ]')
('alert', 'coec_ns_feature_hourly_simplify.db.1.tar peer [ 10.69.142.18:8765 client: Unknown ] [10.69.142.18:8765] >>> BIND [ dst: 0.0.0.0:0 ec: Success ]')
('alert', 'coec_ns_feature_hourly_simplify.db.1.tar peer [ 10.69.142.18:8765 client: Unknown ] [10.69.142.18:8765] >>> ASYNC_CONNECT [ dst: 10.69.142.18:8765 ]')
('alert', 'coec_ns_feature_hourly_simplify.db.1.tar peer [ 10.69.142.18:8765 client: Unknown ] connecting to peer (TCP)')
('alert', 'coec_ns_feature_hourly_simplify.db.1.tar peer [ 10.69.142.18:8765 client: Unknown ] [10.69.142.18:8765] *** LOCAL ENDPOINT [ e: 10.69.142.18:55525 ]')
('alert', 'coec_ns_feature_hourly_simplify.db.1.tar peer [ 10.69.142.18:8765 client: Unknown ] [10.69.142.18:8765] >>> COMPLETED [ ep: 10.69.142.18:8765 ]')
('alert', 'coec_ns_feature_hourly_simplify.db.1.tar peer [ 10.69.142.18:8765 client: Unknown ] [10.69.142.18:8765] *** SET_NON_BLOCKING [  ]')
('alert', 'coec_ns_feature_hourly_simplify.db.1.tar peer [ 10.69.142.18:8765 client: Unknown ] [10.69.142.18:8765] >>> SET_TOS [ tos: 32 e: Success ]')
('alert', 'coec_ns_feature_hourly_simplify.db.1.tar peer [ 10.69.142.18:8765 client: Unknown ] [10.69.142.18:8765] <== HAVE_ALL [  ]')
('alert', 'coec_ns_feature_hourly_simplify.db.1.tar peer [ 10.69.142.18:8765 client: Unknown ] [10.69.142.18:8765] *** SEED [ this is a seed p: 0x7f39dc0114d8 ]')
('alert', 'coec_ns_feature_hourly_simplify.db.1.tar peer [ 10.69.142.18:8765 client: Unknown ] [10.69.142.18:8765] ==> INTERESTED [  ]')
('alert', 'coec_ns_feature_hourly_simplify.db.1.tar peer [ 10.69.142.18:8765 client: Unknown ] [10.69.142.18:8765] <== UNCHOKE [  ]')
('alert', 'coec_ns_feature_hourly_simplify.db.1.tar peer [ 10.69.142.18:8765 client: Unknown ] [10.69.142.18:8765] *** PIECE_PICKER [ dlq: 0 rqq: 0 target: 4 req: 4 engame: 0 ]')
('alert', 'coec_ns_feature_hourly_simplify.db.1.tar peer [ 10.69.142.18:8765 client: Unknown ] picker_log [ random_pieces prefer_contiguous ] (698,0) (698,1) (698,2) (698,3) (698,4) (698,5) (698,6) (698,7) (698,8) (698,9) (698,10) (698,11) (698,12) (698,13) (698,14) (698,15) (698,16) (698,17) (698,18) (698,19) (698,20) (698,21) (698,22) (698,23) (698,24)
'coec_ns_feature_hourly_simplify.db.1.tar peer [ 10.69.142.18:8765 client: Unknown ] requested block (piece: 60 block: 201)'

It seems that no reply from http  server,but  i can use "wget http://10.69.142.18:8765/coec_ns_feature_hourly_simplify.db.1.tar" 
to download the file. I don,t know if the http server need to support p2p protocol or  some steps are missing。

**Comment by a2a111** [comment]
@arvidn  help，help。。。。

**Comment by a2a111** [comment]
I use "python -m SimpleHTTPServer 8765" to as a http server

**Comment by arvidn** [comment]
Does the log end where you cut it off? It was just about to request pieces from the server.
What requests does your HTTP server receive?
