### ISSUE TITLE
Please consider defining `std::hash<libtorrent::info_hash_t>`

### ISSUE THREAD

**Issue by bershanskiy** [arvidn/libtorrent#5239]
**Please provide the following information**

libtorrent version (or branch): 2.0

platform/architecture: Any

compiler and compiler version: Any

Libtorrent defines [`std::hash<lt::sha1_hash>`](https://github.com/arvidn/libtorrent/blob/787ddef070ab937e6014edac69cc788c31146f48/include/libtorrent/sha1_hash.hpp#L277) Since `sha1_hash` is supposed to be replaced with `info_hash_t`, it would be convenient for libtorrent users to have `std::hash<lt::info_hash_t>` to use in place of `std::hash<lt::sha1_hash>`.

This would be useful, for instance, to qBitTorrent [here](https://github.com/qbittorrent/qBittorrent/blob/82602b51bf218b9dffc5d082db3fa8d59b258a60/src/base/bittorrent/infohash.cpp#L92).

**Comment by bershanskiy** [comment]
One possible implementation for `std::hash<libtorrent::info_hash_t>` is available here: https://github.com/qbittorrent/qBittorrent/pull/13627

**Comment by arvidn** [comment]
I agree that this makes sense.

**Comment by arvidn** [comment]
does this look reasonable? https://github.com/arvidn/libtorrent/pull/5893

**Comment by bershanskiy** [comment]
Yes, #5893 makes sense.
