### ISSUE TITLE
Should not save metadata unless explicitly requested

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#5241]
Currently libtorrent unconditionally saves metadata in resume data in case when torrent is added without it (e.g. using magnet link). 
But it doesn't seem to make sense, and there's no way to prohibit it except to delete it from the generated resume data manually. Apparently, you assumed that it would help to resume such torrents without any additional care from the user side, but it does not work as you want. Let's consider the following scenario: 
1. You add a torrent without metadata and it sets up the appropriate sign. 
2. Torrent receives the metadata and stores it in resume data (every time in the current session).
3. You restart the session and add the torrent with this resume data. Well, fine, the metadata is here and it's loaded successfully. But now the torrent doesn't save it in resume data. 
4. You restart the session again and add the torrent with this resume data. And voila - there is no metadata, so it needs to be downloaded again.

**Comment by arvidn** [comment]
hm, interesting. I take it you don't think it's worth the trouble of trying to make it work? part of me think it would be nice to include metadata unconditionally. I would think saving it as a single blob on the filesystem or in a database is faster than saving it in two blobs (at least that's my experience). I would also think it would be easier to use and less error prone.

I agree though that having a flag that isn't respected under certain circumstances isn't great. Ideally the default should change, but that wouldn't be backwards compatible.

There could be a *new* flag to say: "I don't want metadata in my resume file" perhaps.

**Comment by glassez** [comment]
> would think saving it as a single blob on the filesystem or in a database is faster than saving it in two blobs (at least that's my experience).

This is the first idea that comes to mind, and it came to me too. But the point is that metadata should only be saved once when it becomes available, and there is no point in constantly rewriting it with the same values (on the contrary, it can harm, increasing the overall load when saving resume data).
>I take it you don't think it's worth the trouble of trying to make it work?

I think Yes. But if you really want it you can try, but...
>I agree though that having a flag that isn't respected under certain circumstances isn't great. 

Yes.
>There could be a new flag to say: "I don't want metadata in my resume file" perhaps.

Yes.

**Comment by master255** [comment]
@arvidn During development, I realized that without, a directory with cache infoHash.torrent nothing would work.
So there is no need to save the .torrent file in "resume data". The metadata is always taken from the directory with the cache of the .torrent files, not from "resume data".
A flag allowing this would be very useful for performance and would reduce the size of the "resume data" cache.

**Comment by arvidn** [comment]
> During development, I realized that without, a directory with cache infoHash.torrent nothing would work.

`client_test` is counter-evidence. It works and it saved the metadata in its resume files.

**Comment by glassez** [comment]
> `client_test` is counter-evidence

It is counter-evidence of this issue? Or of something in previous comment only?

**Comment by master255** [comment]
@arvidn I found that you save metadata and "resume data" in one .resume file.
But what if the program only needs metadata?
In practice, it is more profitable for a large torrent program to store metadata and the "resume data" cache separately.
If the .torrent files can be managed by the user, then "resume data" is purely service data that only the program should manage.

**Comment by arvidn** [comment]
> > > During development, I realized that without, a directory with cache infoHash.torrent nothing would work.

> > client_test is counter-evidence

> It is counter-evidence of this issue? Or of something in previous comment only?

It's counter-evidence to the statement it was in response to.

**Comment by arvidn** [comment]
> But what if the program only needs metadata?

Yeah, then there should be a reliable way to ask for resume data without the metadata in it (as was established earlier in this ticket). I don't see how this supports your claim that "nothing will work" without saving .torrent files separately. As I pointed out, `client_test` works, and it uses the method of saving metadata together with resume data.

> In practice, it is more profitable for a large torrent program to store metadata and the "resume data" cache separately.

Could you elaborate? What's your performance metric? I don't think it's startup time, as you would require two disk seeks to load both. If it's shutdown-time, it could make sense, as you may get away with writing fewer bytes to disk.

**Comment by arvidn** [comment]
@glassez I'm leaning towards simply removing the special case that includes metadata unconditionally if the torrent was added by magnet. I think that complicates things unnecessarily.

**Comment by master255** [comment]
@arvidn 

> What's your performance metric?

When application starts - cache with "resume data" is loaded from a file and deserialized into an array.
While the program is running, this cache is stored in RAM (and theoretically can grow infinitely, perhaps it should be trimmed here too).
When the program closes the cache is serialized and truncated to 5 megabytes (old "resume data" is deleted) and written to disk.
5 Megabyte is an experimental value that will not cause performance problems.

**Comment by arvidn** [comment]
> In practice, it is more profitable for a large torrent program to store metadata and the "resume data" cache separately.

by "performance metric" I mean; you say it's more "profitable". By what metric? what are you measuring that's better?

**Comment by master255** [comment]
@arvidn For example:
 - fewer operations need to be performed to get torrent_info. This is necessary to display a list of files before downloading and, for example, to remove the torrent content. (I have my own function)
 - It is possible to share .torrent files.
 - It is possible not to limit the number of .torrent files, but to limit the "resume data" size.
 - allows the user to open .torrent files with another program.

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/5247
