### ISSUE TITLE
Bug. After restore"resume data" does not start downloading.

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#5246]
@arvidn
libtorrent version (or branch): 1.2.10
How to reproduce a bug:
1. Enable 4G (without torrent access). 
2. Turn on torrent download.
3. Save "resume data" of torrent_handle.
4. Remove torrent_handle from session.
5. Enable WIFI
6. Restore add_torrent_params from "resume data" and add it to session.

As a result the download does not start.  If you recover this "resume data" and restart the session, nothing changes. The download does not start.
I bypassed the bug by adding a check for the percentage of downloaded data >0. If it was downloaded, at least 0.1%, the bug does not appear, but if downloaded 0%, the bug is.

In the attached file saved "resume data", downloading, which does not start.
[log.txt](https://github.com/arvidn/libtorrent/files/5448418/log.txt)

**Comment by master255** [comment]
@arvidn State always: downloading
No errors happen.

**Comment by master255** [comment]
@arvidn Did you manage to reproduce the bug?

**Comment by master255** [comment]
@arvidn I found out where the bug is going.
The problem arose because I wanted to keep the "resume data" state when the torrent metadata was first loaded. I did it in "TORRENT_CHECKED" event. Example code:
```
case TORRENT_CHECKED:
torrentHandle.saveResumeData();
```

If to save "resume data" later and restore, this problem does not occur.
There is some fraction of a second when starting the torrent, which can lead to this bug if you save "resume data" at this moment.

I think it is a bad idea to save "resume data" when only metadata is loaded. 
What do you think about it?

**Comment by master255** [comment]
Steps of reproduction became more complicated:
1. Enable wifi
2. Download metadata and save "resume data" in the " TORRENT_CHECKED" event.
3. Remove torrent_handle from the session.
4. Turn off WIFI
5. Enable 4G
6. Restore add_torrent_params and add them to the session.
7. Save "resume data"
8. Remove torrent_handle from session.
9. Enable WIFI
10. Restore add_torrent_params and add them to the session.

Download is not going.

**Comment by arvidn** [comment]
please follow this trouble-shooting guide: https://libtorrent.org/img/troubleshooting.png

**Comment by arvidn** [comment]
> @arvidn State always: downloading
> Alerts usual. 

Surely you aren't getting `block_downloading_alert`, `block_finished_alert`, `file_completed_alert` or `piece_finished_alert`, are you? You would get those normally (when those alerts are enabled).

**Comment by arvidn** [comment]
> I think it is a bad idea to save "resume data" when only metadata is loaded.
> What do you think about it?

So, when do you think it would make sense to save resume data then? the only time metadata is *not* loaded is when adding a magnet link, before the metadata has been downloaded.

**Comment by master255** [comment]
@arvidn I found my error.
I download metadata with upload_mode flag.
This flag is saved in "resume data".
And then prevents the data from being downloaded.
This is not a bug.

**Comment by master255** [comment]
@arvidn 

> So, when do you think it would make sense to save resume data then?

I think I am doing everything right. But how not to save the "upload_mode" flag?
It's not beautiful to check it every time I load "resume data".

**Comment by arvidn** [comment]
if the torrent is auto managed (which it is by default) it may be switched into upload-only mode in case the disk fills up

**Comment by master255** [comment]
@arvidn No. When downloading data, I remove the "AUTO_MANAGED" flag.
The problem is that I save "resume data" with "upload_mode" flag. And I can't save "resume data" without this flag, because if I remove it, the download will start immediately.

**Comment by master255** [comment]
@arvidn Ok. I added the removal of the flag:
addTorrentParams.flags(addTorrentParams.flags().and_(TorrentFlags.AUTO_MANAGED.inv()).and_(TorrentFlags.UPLOAD_MODE.inv()));
Now everything works correctly and at maximum speed. 
Thank you.

**Comment by master255** [comment]
Better solution: addTorrentParams.flags(TorrentFlags.APPLY_IP_FILTER);
