### ISSUE TITLE
b2 Doesn't Install Python Bindings

### ISSUE THREAD

**Issue by emmercm** [arvidn/libtorrent#5248]
**Please provide the following information**

libtorrent version (or branch): v2.0.0 tag

platform/architecture: Alpine v3.12.1 on Docker v19.03.13 on macOS v10.15.7

compiler and compiler version: b2 v4.0, gcc v9.3.0

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

---

I'm sure this a misunderstanding, but I'm having difficulty figuring out how to install the built Python bindings (e.g. to `/usr/lib/python3.8/site-packages`).

These commands build fine:

```
cd bindings/python
LIBTORRENT_PYTHON_INTERPRETER="$(which python3)" BOOST_ROOT="" b2 release cxxstd=14 warnings=off address-model=32 -j$(nproc) stage_module stage_dependencies
```

or

```
cd bindings/python
sed -i 's/address-model=64/address-model=32/g' setup.py
python3 setup.py install
```

but neither install the bindings correctly such that `python3 -c "import libtorrent; print(libtorrent.version)"` works.

`b2` appears to be the preferred build method over `make`/`cmake`, but only `cmake -Dpython-bindings=ON` has been working for me. The reason I don't want to use `cmake` is I can't figure out how to force a 32-bit build (see `address-model` above).

**Comment by userdocs** [comment]
I am just going to chime in here and say i don't think it works to compile the python binding on Alpine. I can build libtorrent ok, just not the binding.

The only error i can seem to come across is:

When using this command `python setup.py build --bjam`

```
libboost_python38.a(errors.o): relocation R_X86_64_PC32 against undefined symbol `PyExc_OverflowError' can not be used when making a shared object; recompile with -fPIC
ld: final link failed: bad value
collect2: error: ld returned 1 exit status

...failed gcc.link.dll .../libtorrent.so...
...skipped <p.>libtorrent.so for lack of ...libtorrent.so...
...failed updating 1 target...
...skipped 1 target...
...updated 234 targets...
build failed
```

Using this command: `python3 -c "import libtorrent; print(libtorrent.version)"`

```
ImportError: Error relocating libtorrent.cpython-38-x86_64-linux-gnu.so: _ZNK10libtorrent17announce_endpoint12can_announceENSt6chrono10time_pointINS1_3_V212system_clockENS1_8durationIlSt5ratioILl1ELl1000000000EEEEEEbh: symbol not found
```

## Conclusion

I don't think this is a libtorrent issue as such but due to the implementation of python on Alpine linux?

If we look at deluge, it's in edge/testing

https://pkgs.alpinelinux.org/package/edge/testing/x86/deluge

And this package, i'm not sure itss 100% functional.

https://pkgs.alpinelinux.org/package/edge/testing/x86/py3-libtorrent-rasterbar

## Documentation stuff

https://libtorrent.org/python_binding.html

@arvidn is this a typo?

```
using msvc : 14.0 : : /std:c++14 ;
```

The boost docs seem to have a different examples:

```
using msvc : [version] : [c++-compile-command] : [compiler options] ;
```

And for gcc specifically (linux examples)

```
using gcc : 5 : g++-5 : ; # default is C++ 98
using gcc : 5~c++03 : g++-5 : <cxxflags>-std=c++03 ; # C++ 03
using gcc : 5~gnu03 : g++-5 : <cxxflags>-std=gnu++03 ; # C++ 03 with GNU
using gcc : 5~c++11 : g++-5 : <cxxflags>-std=c++11 ; # C++ 11
using gcc : 5~c++14 : g++-5 : <cxxflags>-std=c++14 ; # C++ 14
```

**Comment by emmercm** [comment]
I think there's a misunderstanding. I've been able to build and use the bindings for both Python 2 and 3 for libtorrent v1.0-1.2 in Alpine successfully (see https://github.com/emmercm/docker-libtorrent).

And I can even build the Python 3 bindings for libtorrent v2.0 (see https://github.com/emmercm/docker-libtorrent/pull/84/files#diff-113716c089a69ef1e92d4d861cc74d723e7e938fb10123b9b8ddfa87bf48649cR41-R49), but I'm not really able to test if it works or not because it doesn't get installed to a place that's importable in Python.

The issue is more around:

- Building and installing with `cmake` appears to be fine, but I can't find how to force 32-bit builds
- Building with `b2` appears to be fine, but I can't find how to install the built bindings

---

Side note, didn't know https://pkgs.alpinelinux.org/package/edge/testing/x86/libtorrent-rasterbar was in the "testing" repository, but the "community" repository version is drastically out of date: https://pkgs.alpinelinux.org/package/edge/community/x86/libtorrent. I'd rather not use anything out of "testing".

**Comment by userdocs** [comment]
I am doing something different with boost 1.74 (specifically with static boost-python) but the outcome should not be that different. I only have issues with the python binding. I am not so sure i am having an error but as the tests are now working but may still be able to assist with par of your issue.

## Help with b2

When you use `b2` it's built here `bindings/python/libtorrent.so` and you'd have to install it manually. The install argument you'd usually use with b2 `install --prefix="$install_dir"` will fail when used with `stage_module`. So you need to build it then test/move it from that location.

**Note:** I am not sure stage_dependencies is required if you are using system libs but i don't use it myself.

You can move to this directory and run your tests.

```bash
bindings/python # python3 -c "import libtorrent; print(libtorrent.version)"
2.0.0.0
```

Using the `bindings/python/client.py`

```bash
bindings/python # python3 client.py
```

![image](https://user-images.githubusercontent.com/16525024/97790918-f69daa80-1bc4-11eb-86c9-7e295baacc41.png)

## Where to install it?

This appears to be the defaul location.

```
/usr/lib/python3.8/site-packages/
```
So do something like this

```
cp -f "binding/python/libtorrent.so" "/usr/lib/python3.8/site-packages/libtorrent.so"
chmod 755 "/usr/lib/python3.8/site-packages/libtorrent.so"
```

And see something like this

```
~ # python3 -c "import libtorrent; print(libtorrent.version)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'libtorrent'
~ # cp -f "/root/libtorrent/bindings/python/libtorrent.so" "/usr/lib/python3.8/site-packages/libtorrent.so"
~ # chmod 755 "/usr/lib/python3.8/site-packages/libtorrent.so"
~ # python3 -c "import libtorrent; print(libtorrent.version)"
2.0.0.0
~ #
```
Hope that helps with the `b2` part

**Comment by arvidn** [comment]
@userdocs yes, that looks like a typo. fixed here: https://github.com/arvidn/libtorrent/pull/5255

**Comment by arvidn** [comment]
@emmercm there's no build rule in the `Jamfile` to install the python module to a place where the python interpreter can pick it up. If you know how to determine what a reasonable install directory would be, it probably wouldn't be very hard to add such rule though

**Comment by userdocs** [comment]
This looks like it works with a basic Alpine python3 install.

```bash
python3 -c "import sys; print(sys.path)"
```

Giving a result we can parse?

```
['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/lib/python3.8/site-packages']
```

Debian Stable.

```
['', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages']
```

What is the rule capable of in terms of getting this value?

**Comment by userdocs** [comment]
I think this is a consistent result?

```
python3 -c "import sys; print(sys.path[4])"
```

**Comment by userdocs** [comment]
So this command would work using a docker container, alpine and a build script to demonstrate the build + installation concept.

```bash
docker run -it -p 8112:8112 -v $HOME:/root alpine:latest /bin/ash -c 'apk add bash curl && curl -sL git.io/mplibtorrent | bash -s all install && cd && ash'
```

At the conclusion of this command you will have:

**Note:** We are using libtorrent 1.2.10 for the purpose of this script and 2.0.0 does not work with deluge right now.

-  libtorrent python binding built using boost 1.74 and statically linked to boost-python
-  Installed to the relevant directory (root or local)
-  Installed Deluge, Deluge Web and the ltconfig plugin.
-  Deluge Web UI accessible on IP:8112

**Comment by userdocs** [comment]
I have tested some things towards a solution:

`PYTHONPATH` should not be used as it conflicting variable name that can change the output of the command `python3 -c "import sys; print(sys.path)` as it is an official python ENV setting.

This command `python3 -c "import sys; print(sys.path[4]` is consistent until `PYTHONPATH` is set and then it is not consistent across systems and the ENV changes the result.

So i think perhaps we should consider two things.

1: Don't use this Variable `PYTHONPATH`.

2: `PYTHON_LIB_PATH` or something specific is OK.

Which brings me to part two.

If i add this to the `libtorrent/bindings/python/Jamfile` 

```
import os ;
local PYTHON_LIB_PATH = [ os.environ PYTHON_LIB_PATH ] ;

install install_module
    : libtorrent
    : <location>$(PYTHON_LIB_PATH)
    <install-type>PYTHON_EXTENSION
    : <cxxstd>14
    ;
```

And use these two settings

1: My export environment setting.

```
export PYTHON_LIB_PATH="/usr/lib/python3.8/site-packages"
```

2: Set my custom `b2` flag

```
b2 install_module
```

It works to use this variable to install.

```
common.copy /usr/lib/python3.8/site-packages/libtorrent.so
...updated 201 targets...
``` 

I cannot see a way for the Jamfile to detect this path without either being and an existing environment variable set by the user. If there is a way please tell me.

So either 

-  an exported ENV, like is recommended with `BOOST_ROOT` 
-  (Not sure if this is possible) specific setting in the `user-config.jam` but i could not see how to define this.

I think the exported ENV is the best option?

**Comment by arvidn** [comment]
> I cannot see a way for the Jamfile to detect this path without either being and an existing environment variable set by the user. 

How do other install scripts determine which directory to put modules in?

Do I understand you correctly that `python3 -c "import sys; print(sys.path[4])` is not a reliable way?
Even finding which python executable to run may be a challenge.

**Comment by userdocs** [comment]
On a fresh system install `python3 -c "import sys; print(sys.path[4])` is a consistent way across all platforms i tried to get the desired path, Ubuntu Debian and Alpine. The problem arises is a user has defined [PYTHONPATH](https://bic-berkeley.github.io/psych-214-fall-2016/using_pythonpath.html). This will have a direct effect on the results shown by that command by altering the `sys.path` so it seems more likely to conflict help if this path is set for other legitimate reasons. Also path naming conventions are inconsistent across say Ubuntu 16 to 20.

The real issue for me is not understand the limitations of what the [jamfile can or cannot do](https://www.boost.org/doc/libs/1_46_1/doc/html/bbv2/faq.html). It seems the syntax is pretty basic and `import os ;` is the most useful option i can decipher. I don't see another method to for the jamfile to be aware of this path unless is is specified at some point

Using boost lib paths as an example, it seem pretty dependant on **1:** a hardcoded list of paths to check **2:** user input in the form an argument like `--with-boost=/mypath`. There is no automated checking as such.

So unless there is a way to use a command that forcibly bypass the users ENV, like

```
env -i python3 -c "import sys; print(sys.path[4])"
```

**Note:** This would provide a pretty consistent result from here [env man pages](https://man7.org/linux/man-pages/man1/env.1.html)

```
       -i, --ignore-environment
              start with an empty environment
```

The results seem pron to conflict.

Which is why I leaned towards it being a user defined ENV, set like the docs describe for boost.

```
BOOST_BUILD_PATH=""
BOOST_ROOT=""
PYTHON_LIB_DIR=""
```

If the user specifies the dir and it exists, install otherwise error out for `install_module` being null.

```
export PYTHON_LIB_PATH=/path/i/can/define/or/user/bash/expansion
```

**Comment by arvidn** [comment]
does this work? https://github.com/arvidn/libtorrent/pull/5259

**Comment by arvidn** [comment]
if someone has set `PYTHONPATH`, is that supposed to be respected? I mean, wouldn't that have been done deliberately?

**Comment by userdocs** [comment]
Thank you, I am testing the now and will update soon.

Regarding the `PYTHONPATH` environment var is a good question.

These two commands will get a different string, meaning the `[4]` will come back with a correct (python3) and incorrect (python) response. 

```
python2 -c "import sys; print(sys.path)"
python3 -c "import sys; print(sys.path)"
```

I suppose it comes down to why did they set python path, which essentially makes their path the `[1]` result.

```
python2 -c "import sys; print(sys.path)"
['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
```
```
python3 -c "import sys; print(sys.path)"
['', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages']
```

With `PYTHONPATH` set

```
export PYTHONPATH="test"
```

We get this, which is perhaps the most consistent method.

```
python2 -c "import sys; print(sys.path)"
['', '/test', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
```

```
python3 -c "import sys; print(sys.path)"
['', '/test', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages']
```

If this is defined it is supposed to be pointing to the lib location, which is what we want, but i cannot say that is what is wanted by default by said user. Also python2 is the most unpredictable result here.

But if `PYTHONPATH` is set DO python -c "import sys; print(sys.path[1])" should provide a consistent outcome, wanted or not.

**Comment by userdocs** [comment]
## Regarding the patch:

So the patch does work to perform the required installation, so we are moving in the right direction. I am just not sure if trying to automatically detect the systems paths is the best way to do this or whether an alternate command, shown below could be safer

## Questions

do we need to support python 2? there is nothing broken as of yet. so i think the answer is yes

If yes, how do we test for and decide on using `python2` or `python3`. I can successfully build against both.

## Testing

Here is an example of some tests I did using 2 commands.

```bash
apt-get update
apt-get upgrade
apt-get install python2 python3
```

Here is a new option that gives the specific path relative to the users home directory `python -m site --user-site` and it is explained like this:

```bash
python3 -m site help
/usr/lib/python3.8/site.py [--user-base] [--user-site]

Without arguments print some useful information
With arguments print the value of USER_BASE and/or USER_SITE separated
by ':'.

Exit codes with --user-base or --user-site:
  0 - user site directory is enabled
  1 - user site directory is disabled by user
  2 - uses site directory is disabled by super user
      or for security reasons
 >2 - unknown error
```

**Note:** The path is always a full path like `/root/.local/...` or `/home/username/.local` but I abbreviated to `~` for convenience.

### Ubuntu Focal

```bash
env -i python2 -c "import sys; print(sys.path[6])" = /usr/local/lib/python2.7/dist-packages
env -i python3 -c "import sys; print(sys.path[4])" = /usr/local/lib/python3.8/dist-packages
python2 -m site --user-site = ~/.local/lib/python2.7/site-packages
python3 -m site --user-site = ~/.local/lib/python3.8/site-packages
```

### Debian Stable

```bash
env -i python2 -c "import sys; print(sys.path[6])" = /usr/local/lib/python2.7/dist-packages
env -i python3 -c "import sys; print(sys.path[4])" = /usr/local/lib/python3.7/dist-packages
python2 -m site --user-site = ~/.local/lib/python2.7/site-packages
python3 -m site --user-site = ~/.local/lib/python3.7/site-packages
```

### Alpine 3.12

```bash
env -i python2 -c "import sys; print(sys.path[6])" = /usr/lib/python2.7/lib-dynload
env -i python3 -c "import sys; print(sys.path[4])" = /usr/lib/python3.8/site-packages
python2 -m site --user-site = ~/.local/lib/python2.7/site-packages
python3 -m site --user-site = ~/.local/lib/python3.8/site-packages
```

## So some thoughts

I am wondering if using `python -m site --user-site` might be safer than using `python2 -c "import sys; print(sys.path)"`. I had some duplicated folder issues with docker but that could be resolved by making sure the docker generates the path tree and not the host.

In my testing so far I have found it to work with a system installed deluge using `pip` as root.

The patch needs to use `python2` and `python3` commands.

**Comment by userdocs** [comment]
or have 3 options (because python has no real one solution fits all method to this particular problem).

**1:** `install_module_custom` where the user specifies the path manually using an exported environment variable. `PYHTONPATH` is ignored

**2:** `install_module_local` where `python -m site --user-site` is used and the lib is localised to a user's home.

**3:** `install_module_system` where `env -i python -c "import sys; print(sys.path)"` is used and the lib is installed system wide. `PYHTONPATH` is respected
.

I could document them and explain it in the docs for the python binding.

The more i look at it the more i see a legitimate case for all three example.

**Comment by userdocs** [comment]
1: I didn't know how to edit your pull so i made one with changes I hacked together.

2: Here is my attempt at the proposed changes https://github.com/arvidn/libtorrent/pull/5262

I have tested on all settings and the results were consistent with no errors. The big BUT is that I am will not say my coding implementation is the best, i pretty much hacked it together from readme and other stuff in the jamfile so if there is a better/safer/proper way i'm all ears.

**Comment by arvidn** [comment]
@userdocs could you have a look at my updated patch? I've incorporated the features you added: https://github.com/arvidn/libtorrent/pull/5259

**Comment by userdocs** [comment]
Yes, i will do that now and try on a few containers/distros to see. Thanks

**Comment by userdocs** [comment]
@emmercm I think this is resolved now with this pull request?

https://github.com/arvidn/libtorrent/pull/5259

**Comment by emmercm** [comment]
The `install_module python-install-scope=system` is exactly what I needed: https://github.com/emmercm/docker-libtorrent/pull/84

Thank you both @arvidn and @userdocs !
