### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by dacorsa** [arvidn/libtorrent#5252]
**Please provide the following information**

libtorrent version (or branch): latest from github

platform/architecture: linux ubuntu groovy 20.10

compiler and compiler version: gcc-10 g++-10

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Not compile, i receive this error, please can help me?

rm -rf \
    bin \
    examples/bin \
    tools/bin \
    bindings/python/bin \
    test/bin \
    simulation/bin \
    simulator/libsimulator/bin
-- The following features have been enabled:

 * BUILD_SHARED_LIBS, build libtorrent as a shared library
 * dht, enable support for Mainline DHT
 * deprecated-functions, enable deprecated functions for backwards compatibility
 * encryption, Enables encryption in libtorrent
 * exceptions, build with exception support
 * extensions, Enables protocol extensions
 * i2p, build with I2P support
 * logging, build with logging
 * mutable-torrents, Enables mutable torrent support
 * streaming, Enables support for piece deadline

-- The following RECOMMENDED packages have been found:

 * OpenSSL, Full-strength general purpose cryptography library, <https://www.openssl.org/>
   Provides HTTPS support to libtorrent

-- The following REQUIRED packages have been found:

 * Threads
 * boost_headers (required version == 1.71.0)
 * Boost

-- The following features have been disabled:

 * static_runtime, build libtorrent with static runtime
 * build_tests, build tests
 * build_examples, build examples
 * build_tools, build tools
 * python-bindings, build python bindings
 * python-egg-info, generate python egg info
 * python-install-system-dir, Install python bindings to the system installation directory rather than the CMake installation prefix
 * gnutls, build using GnuTLS instead of OpenSSL

-- Configuring done
CMake Error at CMakeLists.txt:523 (add_library):
  Cannot find source file:

    deps/try_signal/try_signal

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at CMakeLists.txt:523 (add_library):
  No SOURCES given to target: torrent-rasterbar

CMake Generate step failed.  Build files cannot be regenerated correctly.
gmake: *** Nessun obiettivo specificato e nessun makefile trovato.  Arresto.
CMake Error: Error processing file: /app/libtorrent/cmake-build-dir/release/cmake_install.cmake

**Comment by dacorsa** [comment]
CMake Error at CMakeLists.txt:523 (add_library), this is the 523 line:

add_library(torrent-rasterbar

**Comment by arvidn** [comment]
you need to check out git submodules

**Comment by dacorsa** [comment]
ohh thanks, i use only git clone, now i type this:

git clone --recurse-submodules https://github.com/arvidn/libtorrent.git

but how update source to the last github?
cd /app/libtorrent
sudo git checkout default
sudo git reset --hard
sudo git pull

How do you think?

thanks
