### ISSUE TITLE
torrent_status::allocating is never assigned

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#5253]
libtorrent version (or branch): 1.2

platform/architecture: any

compiler and compiler version: any

`torrent_status::allocating` is queried in some places of code but this value is never assigned to `torrent_status::state` field.

**Comment by arvidn** [comment]
the `allocating` state hasn't been used for a long time as far as I remember. I think it's from the compact allocation days. These days files are created and allocated lazily, on-demand. So there's no allocation happening up-front.

I think this state should be deprecated.

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/5263
