### ISSUE TITLE
how to download some picece first

### ISSUE THREAD

**Issue by pangoo-reuse** [arvidn/libtorrent#5256]
hello ，
I want to download some fragments first, for example, I want to download 2-20 blocks first. How can I set up and deal with the download of these fragments first. Thank you.

i try to use 
 ht = torrent_handle 
 th.piecePriority(1, TOP_PRIORITY);
 th.setPieceDeadline(1, 1000);
but ,I don’t quite understand the meaning of these functions, what do these mean, if you can give me an example, thank you

**Comment by arvidn** [comment]
setting the piece priority will create an affinity to request those pieces first. the first piece is 0 though, not 1.
setting the piece deadline will request the pieces from fast peers, pieces with the earliest deadline first.

**Comment by pangoo-reuse** [comment]
thx
