### ISSUE TITLE
Seeding with cache enabled = more disk wear/read?

### ISSUE THREAD

**Issue by user674574** [arvidn/libtorrent#5269]
**Please provide the following information**

libtorrent version (or branch):
1.2.10

platform/architecture:
windows 10 pro x64

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
im not sure this is an issue or not, but when i have cache enabled i see alot more reads from disk, my belief was that cache was gonna do the opposite?

maybe someone can explain to me or correct me?

**Comment by user674574** [comment]
Is it intended behavior that there is more reads from disk wish cache enabled?

**Comment by arvidn** [comment]
yes, it might be. When read cache is enabled, larger buffers are read from disk at a time, as a read-ahead. This is done within a piece, with the expectation that most peers request a few blocks in a row for the same piece. If the requests from clients completely random, however, all that read-ahead served no purpose and was wasted disk I/O and memory.

There isn't really much sophistication in detecting which clients may be requesting blocks (within a piece) sequentially though. There is a setting for the read_stripe_size, controlling how much to read-ahead.

Perhaps even better though, in libtorrent 2.0, this logic is deferred to the operating system's disk cache, which typically *is* sophisticated in determining whether and how much to read-ahead.

**Comment by user674574** [comment]
> 
> 
> yes, it might be. When read cache is enabled, larger buffers are read from disk at a time, as a read-ahead. This is done within a piece, with the expectation that most peers request a few blocks in a row for the same piece. If the requests from clients completely random, however, all that read-ahead served no purpose and was wasted disk I/O and memory.
> 
> There isn't really much sophistication in detecting which clients may be requesting blocks (within a piece) sequentially though. There is a setting for the read_stripe_size, controlling how much to read-ahead.
> 
> Perhaps even better though, in libtorrent 2.0, this logic is deferred to the operating system's disk cache, which typically _is_ sophisticated in determining whether and how much to read-ahead.

Thank you for answer.
This makes sense yes.

As far as i know there is noway to control "read_stripe_size" in the windowsclient, is there?

Thanks again

**Comment by arvidn** [comment]
this is the setting: https://libtorrent.org/reference-Settings.html#read_cache_line_size

**Comment by user674574** [comment]
> 
> 
> this is the setting: https://libtorrent.org/reference-Settings.html#read_cache_line_size

Thanks, Ive been looking for ways to change settings like this, i understand if that kind of help is beyond the scope of help on github :) otherwise would you kindly point me in the correct direction?

**Comment by arvidn** [comment]
I'm not actually sure what you're looking for. To change settings, you create a `settings_pack`, set the desired configuration options, and pass it to `session::apply_settings()`.

**Comment by user674574** [comment]
> 
> 
> I'm not actually sure what you're looking for. To change settings, you create a `settings_pack`, set the desired configuration options, and pass it to `session::apply_settings()`.

well... i guess i must be dumb because i spent numerous hours trying to understand what means in practice, but came up short, i would really like to be able to change for example this setting, but i havent got any answers when i tried asking on reddit or qbittorrent forums

I know what you mention is available allover on libtorrent site etc, but i cannot for the life of me understand how i "create a settings_pack and pass it to session::apply_settings()" :/

**Comment by arvidn** [comment]
here's a C++ example snippet:

```
lt::session ses;

lt::settings_pack p;
p.set_int(lt::settings_pack::read_cache_line_size, 1);
ses.apply_settings(std::move(p));
```

Typically the session object (`ses`) would be constructed somewhere else though, and the code to change the settings would just have a reference or pointer to it.

**Comment by user674574** [comment]
> 
> 
> here's a C++ example snippet:
> 
> ```
> lt::session ses;
> 
> lt::settings_pack p;
> p.set_int(lt::settings_pack::read_cache_line_size, 1);
> ses.apply_settings(std::move(p));
> ```
> 
> Typically the session object (`ses`) would be constructed somewhere else though, and the code to change the settings would just have a reference or pointer to it.

Im afraid this doesnt tell me much, i guess im in over my head :( thanks anyway

**Comment by Seeker2** [comment]
> this is the setting: https://libtorrent.org/reference-Settings.html#read_cache_line_size

Since this seems to make no reference to piece size or size of a torrent...
Might this be overkill on small torrents with small piece size...and too little on large torrents with 4 MB or larger piece size?

**Comment by arvidn** [comment]
the read-ahead never crosses a piece boundary. the assumption is that *pieces* are requested in random order, but *blocks* (within a piece) are likely to be requested sequentially.

**Comment by arvidn** [comment]
i.e. if the read cache line size setting is greater than the piece size, the effective read ahead will be one piece, essentially.

**Comment by Seeker2** [comment]
(Wow, fast reply!)
That covers most of the potential way-too-much-caching part of the problem.

read_cache_line_size default of 32 (16 KB blocks) looks like ~512 KB read per peer, assuming pieces are at least 512 KB size or larger.
For slow peers, this might present a problem if they're extremely numerous...like 1000+.
To say nothing of ram usage, that's potentially a lot of disk wear/reads.

I did spot:
whole_pieces_threshold = 20 (seconds, by default)
would cause a peer to be the single-source for a whole piece.
But that seems to be download-only.

**Comment by user674574** [comment]
@Seeker2 or @arvidn , you think it would be possible if you tried to help me understand what "create a settings_pack and pass it to session::apply_settings()" means?

I know i got an answer from @arvidn with a c++ example, but like i said im afraid that doesnt tell me much :( maybe can give me step by step example in changing/implementing a change, such as "read_cache_line_size" in this example...
Sorry that im asking again, but ive tried reddit and qbit forums and it seems that either people dont want to answer, or they dont know the answer

**Comment by arvidn** [comment]
> maybe can give me step by step example in changing/implementing a change

A change to what to do what? if you want to change the libtorrent default, all default values are defined in `src/settings_pack.cpp`.

@user674574 if you're looking to learn C++, this forum and qbittorrent forums is probably not the place for it. You would probably have to put a fair amount of work into it.

**Comment by Seeker2** [comment]
@user674574 I don't know how to make a settings_pack for libtorrent, as I've only used libtorrent's library as a part of qBitTorrent, Deluge, and a couple lesser-known BT clients.

Deluge has a plugin that lets it change a LOT of libtorrent settings, but I don't know if it's compatible with Deluge v2.x ...and it probably has a badly out-of-date libtorrent library anyway.

**Comment by user674574** [comment]
> 
> 
> @user674574 I don't know how to make a settings_pack for libtorrent, as I've only used libtorrent's library as a part of qBitTorrent, Deluge, and a couple lesser-known BT clients.
> 
> Deluge has a plugin that lets it change a LOT of libtorrent settings, but I don't know if it's compatible with Deluge v2.x ...and it probably has a badly out-of-date libtorrent library anyway.

Yeah, ltconfig for deluge is exactly what i would like for qbittorrent, but i think ppl have been asking for that for a while and i doubt it will come.
There is a way, as ive tried to understand, the settings_pack, but i cant figure out how to edit/use/apply it

**Comment by arvidn** [comment]
@user674574 if qbt doesn't change this setting (which seems likely) you could change the libtorrent default and rebuild everything

**Comment by user674574** [comment]
> 
> 
> @user674574 if qbt doesn't change this setting (which seems likely) you could change the libtorrent default and rebuild everything

i looked at that alternative, tried to do it for abit, changing a libtorrent default seemed as hard (for me) :D

**Comment by Seeker2** [comment]
qBT's config file is human-readable text, so you could check in there for details of what can be changed and what can't.
Sometimes libtorrent settings are exposed there which do not have a checkbox (or the like) in qBT's interface.

**Comment by user674574** [comment]
> 
> 
> qBT's config file is human-readable text, so you could check in there for details of what can be changed and what can't.
> Sometimes libtorrent settings are exposed there which do not have a checkbox (or the like) in qBT's GUI interface.

Thx. Im afraid i can only see what i can already change in advanced settings

**Comment by Seeker2** [comment]
I probably shouldn't have bothered you to look then...

**Comment by xavier2k6** [comment]
@user674574 I've created a Feature Request for this https://github.com/qbittorrent/qBittorrent/issues/14425
