### ISSUE TITLE
Question - python binding : is python3-numpy recommended to be installed?

### ISSUE THREAD

**Issue by userdocs** [arvidn/libtorrent#5274]
**Please provide the following information**

libtorrent version RC_1_2/RC_2_0 built with b2

https://packages.ubuntu.com/focal/python-numpy
https://packages.ubuntu.com/focal/python3-numpy

When i used the flag `b2 --debug-configuration` i see this printed.

```
notice: [python-cfg] Configuring python...
notice: [python-cfg]   user-specified version: "3.8"
notice: [python-cfg]   user-specified cmd-or-prefix: "/usr/bin/python3.8"
notice: [python-cfg]   user-specified includes: "/usr/include/python3.8"
notice: [python-cfg]   user-specified libraries: "/usr/lib/python3.8"
notice: [python-cfg] Details of this Python configuration:
notice: [python-cfg]   interpreter command: "/usr/bin/python3.8"
notice: [python-cfg]   include path: "/usr/include/python3.8"
notice: [python-cfg]   library path: "/usr/lib/python3.8"
notice: [python-cfg] Checking for NumPy...
notice: [python-cfg] running command '/usr/bin/python3.8 -c "import sys; sys.stderr = sys.stdout; import numpy; print(numpy.get_include())"'
notice: [python-cfg] NumPy enabled
```

I am specifically curious about this part.

```
notice: [python-cfg] Checking for NumPy...
notice: [python-cfg] running command '/usr/bin/python3.8 -c "import sys; sys.stderr = sys.stdout; import numpy; print(numpy.get_include())"'
notice: [python-cfg] NumPy enabled
```

If `numpy` is not installed this part returns and error but does not cause the build to fail, so:

- I can build the binding without `numpy` installed. The error only shows in when debugging the config.
- Is it recommend that this be installed. I assume it is there for a reason?

It is just something i an unsure about. I'd prefer to not install it if i don't need it.

**Comment by userdocs** [comment]
I think it is this?

https://github.com/boostorg/python/blob/15115eb1f844e9ac8ed5dd454d46a4e7b5ae5b48/fabscript#L66

**Comment by arvidn** [comment]
libtorrent's python binding does not use numpy. that error is just the boost configuration failing to find numpy probably

**Comment by userdocs** [comment]
OK, thanks, pretty much all i wanted to know. I'll close this and consider it a boost specific issue if i want to know more.
