### ISSUE TITLE
low upload speed

### ISSUE THREAD

**Issue by chendj0710** [arvidn/libtorrent#5288]
**Please provide the following information**

libtorrent version (or branch):1.2.3

platform/architecture:ubuntu20   amd64

compiler and compiler version: cmake Ninja

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I used custom storage. When I tested it, I found that the upload speed of the client was very slow (10MB/s, my environment is 1000Mib/s), so I considered using tool/parse_session_stats.py for analysis, but I found that I could not Get session_stats_header_alert, which leads to parse_session_stats.py stuck there all the time, how I get the alert:
   
      for (;;) {
        // ask the session to post a state_update_alert, to update our
        // state output for the torrent
        psession->post_torrent_updates();
        psession->post_session_stats();    //add for get session stats

        std::vector<lt::alert *> alerts;
        psession->pop_alerts(&alerts);

        for (lt::alert const *a : alerts) {
            //add for session stats 
            if (lt::alert_cast<lt::session_stats_header_alert>(a))
            {
                // std::cout << a->message() << std::endl;
                printf("get session_stats_header_alert \n");
                writeBufferToFile("session_stats",  a->message().c_str());
            }

            if (lt::alert_cast<lt::session_stats_alert>(a))
            {
                // std::cout << a->message() << std::endl;
                writeBufferToFile("session_stats",  a->message().c_str());
            }
           ...
    }

Excuse me, where do I use this? I have a problem, please take the time to reply, thank you very much

**Comment by arvidn** [comment]
do you get the `session_stats_alert`?
if you run `client_test` and pass in the `-O` flag, and `-f alerts.log`, do you get the alert then? in `alerts.log`?

**Comment by chendj0710** [comment]
Hmm, when I use client_test, I get the aler I want, thank you

But when I see session_stats_report, I don’t know where to analyze it. Can you give me some suggestions? I want to check the reasons why some peers have low upload speed or no upload speed

**Comment by arvidn** [comment]
did you successfully run `parse_session_stats.py`? with `gnuplot` installed? if so, it should have produced an html file along with graphs for various performance counters.

For upload rate, you probably want to look at the disk-job timings, size of send buffers, size of disk read queue, the number of peers that are interested and unchoked (I think there are counters for that).

In your alert stream, you may also find performance_warning_alert, which are posted when limits are hit that might affect performance.

**Comment by chendj0710** [comment]
I am very sorry to reply to you now. I got the relevant graphs now. I observed that there is basically no read in the client disk time. The send buffer size is mostly size3, size4, etc. The read jobs in the disk queue are small. I adjusted send_buffer_watermark, recv_socket_buffer_size, connection_speed and other parameters, and now there is upload speed, but I observed that if a client A is offline for a period of time, and the other client starts to go offline B, then B can only be from a certain peer The download speed obtained is very low, sent-req has been maintained at 550/1, how should I troubleshoot this 

performance warning I only received performance warning: max outstanding piece requests reached

**Comment by arvidn** [comment]
> I observed that there is basically no read in the client disk time.

I'm not sure what you mean by "in the client disk time", but, it sounds like you're saying there are virtually no read jobs sent to the disk. is that right? Do you see more incoming requests than that? Do you think the issue is that your peer isn't sending enough requests to you or that libtorrent is taking too long to issue the disk read and respond? If it's the latter, it's really the other end that needs to send more outstanding piece requests (unless something is causing libtorrent to be unreasonably slow in responding to piece requests). In the session stats, you can see average timing for disk reads.

> The download speed obtained is very low, sent-req has been maintained at 550/1

What does that mean? You have 550 outstanding piece requests to a peer and that peer has one outstanding piece request to you? or is it the other way around?

**Comment by chendj0710** [comment]
1. it sounds like you're saying there are virtually no read jobs sent to the disk. is that right?
--yes ，I think it does not have enough read jobs, so how should I increase incoming requests?
   average timing for disk reads, how is this obtained?

2. you have 550 outstanding piece requests to a peer and that peer has one outstanding piece request to you?
 --yes,I don’t know if this is a deadlock in libtorrent or what’s wrong. This state will last for a long time without download speed.
