### ISSUE TITLE
False hash failures with disk cache disabled

### ISSUE THREAD

**Issue by ssiloti** [arvidn/libtorrent#530]
I'm investigating occurrences of false hash failures while downloading with cache_size set to zero. It appears to be a problem on the read side, if I disable hash failure handling the resulting file re-checks cleanly. This is running RC_1_1.

**Comment by ssiloti** [comment]
Looking at the disk IO thread log it's clear that the reads for the hash check are being performed while there are still outstanding writes for that block. In theory it looks like this could happen even with caching enabled but it is much less likely. The fundamental problem here is that there is no coherency checking against uncached writes.

**Comment by arvidn** [comment]
ah, yes. that's probably true. In the cached case though, I'm pretty sure it would work out right. The data is either on disk or still in the cache when the hash job is run. The write job won't remove the buffers when it's done, especially not if another thread incremented the reference count of the piece.

I suppose even in with cache enabled, there are failures that cause it to fall back on uncached operations, which could be a problem.

**Comment by ssiloti** [comment]
In particular, if a write is blocked by a fence then it does not get added to the block cache. Since the existing coherency checking is done as part of the block cache, the simplest solution (or at least the one which involves the least amount of new code) would be to _always_ add write buffers to the cache and allow reads to hit on them. In the uncached case the buffers would be marked for deletion as soon as they are written. If there are no objections I'll try implementing this and see where it goes.

**Comment by arvidn** [comment]
I think that makes sense

**Comment by arvidn** [comment]
actually, if the write jobs are blocked by a fence, shouldn't the read jobs be blocked too?
if they aren't, things like closing and re-opening files or renaming files may fail, or cause read failures.

**Comment by arvidn** [comment]
I suppose there's no harm in allowing the short-circuit still though, of having read jobs pick the data straight out of the block cache

**Comment by ssiloti** [comment]
You're right about the fence case. I thought writes never got added to the cache if they were blocked by a fence but now i see that I missed the call to `add_dirty_block` in `add_completed_jobs_impl`. So yeah this issue only really affects the cache disabled case.

**Comment by arvidn** [comment]
I'm increasingly thinking that all special cases for cache_size = 0 (and possibly some of the ones related to use_read_cache and use_write_cache) should be removed and basically rely on the cache, but just flush or evict it as quickly as possible

**Comment by ssiloti** [comment]
That's more-or-less what my changes are going to do. In fact right now I'm completely ignoring use_write_cache, it's not clear to me that it makes sense to automatically evict a piece just because it finished flushing. Currently I'm working through a series of deadlock bugs related to the cache not always getting flushed enough to get below the low watermark with small cache_size.

**Comment by arvidn** [comment]
thanks for looking at this btw. I will try to understand the fundamental issue here too. I would really prefer to have the smallest and simplest possible fix for the 1.1 branch. Inspired by you I started thinking more seriously about transitioning to mmap(). In some sense I don't feel like I can focus fully on more large scale changes like this until 1.1 is stable.

As you point out, it's probably a good idea to have a design relying on mmap existing, and then add the complexity for any system that doesn't support it (I wouldn't be surprised if android would be on that list for instance, at least if you want access to SD cards).

I'll put together a wiki page of challenges and consequences of transitioning to a memory mapped cache. Previously I've always considered the main point of moving to mmapped I/O (which I have been considering for years btw.) to be zero-copy of bytes received from the network and going back to the disk. However, now I think that's less important than what you bring up, memory usage efficiency and hopefully lower complexity.

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/wiki/challenges-with-memory-mapped-I-O

**Comment by ssiloti** [comment]
Yeah, mmapped IO is definitely a post-1.1 discussion. I have more to say but I'll save it for after 1.1 is tagged.

**Comment by arvidn** [comment]
great. please feel free to add/edit that wiki page too
