### ISSUE TITLE
libtorrent RC_2_0 constant File error alert. Torrent: file_read () error: invalid request message

### ISSUE THREAD

**Issue by trippleflux** [arvidn/libtorrent#5306]
libtorrent version (or branch):
libtorrent RC_2_0 d33e07fb0be7fd26e51496c263b9b3335fceda11 on qBittorrent v4.4.0alpha1 latest vanilla git

platform/architecture:
Windows 10 x64 Enterprise

compiler and compiler version:
MSVC 2019 16.8.2

Was using libtorrent RC_1_2, deleted the qBittorrent dir in C:\Users\username\AppData\Local & C:\Users\username\AppData\Roaming, and re-compiling my libtorrent & qBittorrent, qBittorrent v4.4.0alpha1 with libtorrent RC_2_0 being spammed with messages :
```
25/11/2020 23:06 - File error alert. Torrent: "TorrentName". File: "". Reason: TorrentName file_read () error: invalid request message
25/11/2020 23:05 - File error alert. Torrent: "TorrentName". File: "". Reason: TorrentName file_read () error: invalid request message
25/11/2020 23:05 - File error alert. Torrent: "TorrentName". File: "". Reason: TorrentName file_read () error: invalid request message
25/11/2020 23:05 - File error alert. Torrent: "TorrentName". File: "". Reason: TorrentName file_read () error: invalid request message
25/11/2020 23:04 - File error alert. Torrent: "TorrentName". File: "". Reason: TorrentName file_read () error: invalid request message
25/11/2020 23:03 - File error alert. Torrent: "TorrentName". File: "". Reason: TorrentName file_read () error: invalid request message
25/11/2020 23:02 - File error alert. Torrent: "TorrentName". File: "". Reason: TorrentName file_read () error: invalid request message
25/11/2020 23:00 - File error alert. Torrent: "TorrentName". File: "". Reason: TorrentName file_read () error: invalid request message
25/11/2020 23:00 - File error alert. Torrent: "TorrentName". File: "". Reason: TorrentName file_read () error: invalid request message
```

![libttorrent2](https://user-images.githubusercontent.com/1216215/100253179-5e040b80-2f73-11eb-9d29-d75bd1fba4db.png)

![libttorrent22](https://user-images.githubusercontent.com/1216215/100253605-e682ac00-2f73-11eb-8b62-f92baab24967.png)

What i have tried : 
1. Like mentioned above, deleting the all of the qBittorrent folder inside %APPDATA%
2. Re-check the torrent
3. Scanning or checking the disk for the bad sectors but none found or faulty.
4. Turning off Windows Defender completely.

The "file_read () error: invalid request" is happened also when seeding the torrent.

My b2 configure line : 
```
b2 toolset=msvc-14.2 address-model=64 architecture=x86 cxxstd=14 variant=release link=shared deprecated-functions=on runtime-link=shared crypto=openssl asserts=production encryption=on logging=on mutable-torrents=on dht=on openssl-version=1.1 i2p=on boost-link=shared extensions=on include="C:\QBITTORRENT\install_msvc64\base\include" library-path="C:\QBittorrent\install_msvc64\base\lib" --prefix="C:\QBittorrent\install_msvc64\base" cxxflags="-O1 -Gy -Gw -GL" define=BOOST_ASIO_DISABLE_CONNECTEX linkflags="/NOLOGO /sharedBASE /NXCOMPAT /LTCG /OPT:REF /OPT:ICF /MANIFEST:EMBED /INCREMENTAL:NO" --hash -j %NUMBER_OF_PROCESSORS%
```

This notification from qBittorrent on Windows 10 is always appearing every couple minutes : 
![libttorrent23](https://user-images.githubusercontent.com/1216215/100255045-a1f81000-2f75-11eb-9601-85ca5e429b7d.png)

Windows Long Path already enabled in Windows's group policy editor.

**Comment by trippleflux** [comment]
Decreasing aio_threads from 16 into default 10 is possibly fixed it, since i have 16 physical CPU core, i just wanted to use it fully.

Also high value of checking_mem_usage setting also causing above error, setting it into default 256 also fixed it.

**Comment by MassaRoddel** [comment]
Actually, that is not a real file error. It just indicates that a peer wanted to read piece data from a none block aligned offset. (support for that has been removed from libtorrent)
The important part is: invalid request message

**Comment by arvidn** [comment]
yes, I would be surprised if changing `aio_threads` or `checking_mem_usage` would affect this. As @MassaRoddel points out, this is really a peer error, where the request was invalid.

The error is generated [here](https://github.com/arvidn/libtorrent/blob/RC_2_0/src/mmap_disk_io.cpp#L680).

**Comment by arvidn** [comment]
It's not supposed to happen though. Invalid requests are supposed to be caught [here](https://github.com/arvidn/libtorrent/blob/RC_2_0/src/peer_connection.cpp#L2476).

**Comment by arvidn** [comment]
actually, the requirement in the disk I/O is stricter than the peer connection validation

**Comment by trippleflux** [comment]
Thanks @MassaRoddel & @arvidn, the problems is not with not really an important error but qBittorrent being spammed Windows's notification constantly, if i leave overnight, there a lots of them :-( .

**Comment by arvidn** [comment]
Yeah, I'll fix this for the next libtorrent release

**Comment by arvidn** [comment]
I believe this patch will fix it: https://github.com/arvidn/libtorrent/pull/5309

**Comment by trippleflux** [comment]
Confirmed fixed, thanks a lot @arvidn !
