### ISSUE TITLE
Anonymous mode port

### ISSUE THREAD

**Issue by OlafvdSpek** [arvidn/libtorrent#5315]
> The listen sockets are closed, and incoming connections will only be accepted through a SOCKS5 or I2P proxy (if a peer proxy is set up and is run on the same machine as the tracker proxy). Since no incoming connections are accepted, NAT-PMP, UPnP, DHT and local peer discovery are all turned off when this setting is enabled.

What port does it announce to the tracker?

https://libtorrent.org/single-page-ref.html#anonymous_mode

https://github.com/qbittorrent/qBittorrent/issues/13841#issuecomment-735501336

**Comment by arvidn** [comment]
it used to be port=0 (in 1.1.x) but was changed to port=1 in 2.0.x, since some trackers would fail the announce for 0.

**Comment by FranciscoPombal** [comment]
> it used to be port=0 (in 1.1.x) but was changed to port=1 in 2.0.x, since some trackers would fail the announce for 0.

Don't you mean 1.2.5?

https://github.com/arvidn/libtorrent/blob/2658c3658c232ed407b28867ee0cc10c19d2c92f/ChangeLog#L132

**Comment by arvidn** [comment]
that sounds right
