### ISSUE TITLE
Question regarding BEP 34 usage

### ISSUE THREAD

**Issue by rafi-d** [arvidn/libtorrent#5327]
Hi,
Not sure that BEP 34 is supported by libtorrent, so just a small question about it's usage by  the client:
Say you have a .torrent file that DOES specify UDP tracker and ports. If you do not use BEP 34, all UDP trackers are with fully working status. 
When you specify to the client to try and use BEP-34, what will the expected usage be:

When adding a new torrent file - should the client  automatically change the ports with those found on the TXT record(s) immediately when added? Or should it wait, check the tracker status first, and only do that after it sees some bad status/timeout etc?

For an existing torrent, if a tracker status is changed to "working" to some bad status - should BEP-34 be used then to try and replace to alternate ports?

Thanks

**Comment by arvidn** [comment]
libtorrent does not support BEP 34. I would expect the port in the TXT record to take precedence.

**Comment by rafi-d** [comment]
Are you sure? Regardless of the trackers' states? This is what happens when uTorrent successes to break perfectly good trackers applying this BEP... 
![355_46828_bad-tracker-ports](https://user-images.githubusercontent.com/2458280/101158551-9622e280-3634-11eb-9aa5-e3e6d1f675fc.png)
https://drive.google.com/file/d/1Nn_uq0TxaFGZtHmEKBTABPVFwGcstCLc/view?usp=sharing

I'd assume this protocol text should be enhanced with recommendation to use it "wisely"... Only for non-working trackers, or if not - always confirm tracker is working wit the new ports, or if not - revert to the old one.

https://drive.google.com/file/d/1Nn_uq0TxaFGZtHmEKBTABPVFwGcstCLc/view?usp=sharing

**Comment by arvidn** [comment]
> Are you sure?

I'm sure that's what I would expect :)
I'm also sure libtorrent doesn't support BEP 34, but I don't think that's what you're referring to.

My recollection of this extension was that the primary intention was to be able to ask clients to *stop* announcing to a hostname that is no longer running a tracker. (but it's been quite a while). piratebay's former tracker hostnames were updated to point to 127.0.0.1 to redirect all the traffic.

So, this is either a misconfiguration (which seems likely if the trackers are still up and operational) or a deliberate request to clients to stop using the trackers. It's not obvious that a client should be resistant to tracker operator's misconfigurations.

Your post you're missing this:

```
$ dig -t TXT tracker.trackerfix.com

; <<>> DiG 9.10.6 <<>> -t TXT tracker.trackerfix.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2958
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;tracker.trackerfix.com.                IN      TXT

;; ANSWER SECTION:
tracker.trackerfix.com. 14117   IN      TXT     "BITTORRENT UDP:80"
tracker.trackerfix.com. 14117   IN      TXT     "BITTORRENT UDP:83"
tracker.trackerfix.com. 14117   IN      TXT     "BITTORRENT UDP:82"
tracker.trackerfix.com. 14117   IN      TXT     "BITTORRENT UDP:85"
tracker.trackerfix.com. 14117   IN      TXT     "BITTORRENT UDP:81"

;; Query time: 3 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Fri Dec 04 14:09:02 CET 2020
;; MSG SIZE  rcvd: 201
```

```
$ dig -t TXT 9.rarbg.to            

; <<>> DiG 9.10.6 <<>> -t TXT 9.rarbg.to
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6361
;; flags: qr rd ra; QUERY: 1, ANSWER: 27, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;9.rarbg.to.                    IN      TXT

;; ANSWER SECTION:
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2890"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2770"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2850"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2830"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2720"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2870"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2880"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2960"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2950"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2760"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2750"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2940"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2920"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2910"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2790"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2730"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2740"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2930"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2970"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2820"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2980"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2840"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2810"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2800"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2860"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2900"
9.rarbg.to.             4312    IN      TXT     "BITTORRENT UDP:2780"

;; Query time: 4 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Fri Dec 04 14:09:57 CET 2020
;; MSG SIZE  rcvd: 903
```

```
$ dig -t TXT 9.rarbg.me

; <<>> DiG 9.10.6 <<>> -t TXT 9.rarbg.me
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39810
;; flags: qr rd ra; QUERY: 1, ANSWER: 27, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;9.rarbg.me.                    IN      TXT

;; ANSWER SECTION:
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2900"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2860"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2930"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2810"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2840"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2880"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2730"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2890"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2760"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2770"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2740"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2820"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2970"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2980"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2950"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2780"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2910"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2870"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2720"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2850"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2920"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2790"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2800"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2830"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2940"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2750"
9.rarbg.me.             869     IN      TXT     "BITTORRENT UDP:2960"

;; Query time: 14 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Fri Dec 04 14:10:25 CET 2020
;; MSG SIZE  rcvd: 903
```

**Comment by rafi-d** [comment]
>but I don't think that's what you're referring to.

I get that libtorrent is 'innocent', yeah... :) 

>  It's not obvious that a client should be resistant to tracker operator's misconfigurations.

Well, obvious or not, since mistakes in config  seem to exist , I expect a reliable client to take them into account. Don't you think it should? Even if just to be on the safe side.  Why even try to replace a perfectly good/working tracker URL:port? ...

**Comment by arvidn** [comment]
I can think of one reason: if the behavior of receiving a `TXT` record depends on the current state of the tracker, there is a race condition that can hide the fact that the DNS record is misconfigured. Imagine tracker operators testing their trackers, they might then not see the error.

Clearly that didn't help in this instance though.

**Comment by rafi-d** [comment]
I see. I'd consider this as an except-able risk/race, that can happen once in a very long time... 
Plus, I expect tracker-DNS-related packets to be decrease by at lease 50% (when a worse-case of 50% of the trackers are not working).

**Comment by rafi-d** [comment]
Here is an idea: if the client is not going to verify the new port frin TXT is working, change BEP-34 so to suggest adding  *all* the published ports into a single tier. This way the client will auto-find the first one that is really working...
