### ISSUE TITLE
libtorrent ram/memory usage out of control

### ISSUE THREAD

**Issue by tjjh89017** [arvidn/libtorrent#5332]
**Please provide the following information**

## libtorrent version (or branch):
Debian Sid with libtorrent 1.2.9
Ubuntu 20.04 with qBittorrent PPA libtorrent 1.2.11

## platform/architecture:
x86_64 Linux

## compiler and compiler version:
gcc version 10.2.0 (Debian 10.2.0-23)
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

## please describe what symptom you see, what you would expect to see instead and how to reproduce it.
We use [EZIO](https://github.com/tjjh89017/ezio) with Libtorrent to deliver our disk image to other PC.
In libtorrent 1.1.x, we can setup `cache_size` to limit ram/memory usage and increase the performance
But it seems libtorrent>=1.2.9 remove this configuration, I can setup this entry but it didn't limit ram usage
It will eat all the ram until OOM killer kill it.

In HTOP, we can see libtorrent program have more than 90% mem usage and marked as `used` not `buffer/cache`
That means other program cannot use memory at this moment until OOM killer kill libtorrent program.

By the way, EZIO will malloc other memory space to store other info.
Before we upgrade to 1.2.9, we used 1.2.5 without any exception.
we are sure that EZIO with 1.2.5 will not memory leak.

I found that libtorrent 2.x removed `cache_size` and rely on OS cache.
Is it also affect to libtorrent>=1.2.9?
Is it possible to get `cache_size` back to limit the libtorrent resource?
I'm not sure this will also affect libtorrent 2.x.

Thanks a lot

**Comment by tjjh89017** [comment]
**[WIP]
This comment is WIP
Ignore it first.**

I use qBittorrent to reproduce this problem
Setup qBittorrent with cache_size = 6GiB, and continue seeding a torrent with total 10GiB files (system has 8G ram)
setup a client to download the file when finishing download, restart it again.

qbitorrent mem usage will be almost 82% of whole system until OOM killer kill it.

if i pause the seeding torrent in qbittorrent, it will free some cache.

**Comment by tjjh89017** [comment]
[Setup]
1 server, 1 client
Server 8G ram

[Testing method]
1. Server setup 1G cache_size
2. Server setup 3G cache_size

Server is always up and seeding.
Only 1 Client will connect to server at the same time.
When client is finished, stop this client, and create another client to connect to server

[Reesult]
EZIO with libtorrent 1.2.11 will eat around 2x cache_size of ram in both cache_size

**Comment by FranciscoPombal** [comment]
@tjjh89017 

> EZIO with libtorrent 1.2.11 will eat around 2x cache_size of ram in both cache_size (use 2G with 1G cache_size, use 6G with 3G cache_size)

2x When comparing to which version? Are you able to `git-bisect` to find the revision that introduced the bug?

**Comment by tjjh89017** [comment]
> @tjjh89017 
> 
> 
> 
> > EZIO with libtorrent 1.2.11 will eat around 2x cache_size of ram in both cache_size (use 2G with 1G cache_size, use 6G with 3G cache_size)
> 
> 
> 
> 2x When comparing to which version? Are you able to `git-bisect` to find the first revision where you can reproduce the bug?

I use 1.2.5 as base version
This is the version with the result that i expected
(Debian buster libtorrent version)

Let me try git-bisect
But i will need to test 1.2.5 again to make sure debian repo didnt do something else
It will take some time

**Comment by arvidn** [comment]
> But it seems libtorrent>=1.2.9 remove this configuration, I can setup this entry but it didn't limit ram usage
> It will eat all the ram until OOM killer kill it.

Just to be clear then, the configuration option is still there, it just isn't working anymore, in your experience. Right?

> I found that libtorrent 2.x removed cache_size and rely on OS cache.
> Is it also affect to libtorrent>=1.2.9?

No

> Is it possible to get cache_size back to limit the libtorrent resource?
> I'm not sure this will also affect libtorrent 2.x.

In 2.0.x the configuration option is *actually* gone, so most likely not. Unless the root cause is something only tangentially related to the disk cache.

@tjjh89017 It would be a good idea to understand where the memory usage comes from. Are you confident it is related to the disk cache?
You can ask for performance counters (stats counters) which will tell you how many buffers of various kinds are currently in use. If you could post numbers that might help pin-point the kinds of buffers that are leaking.

If the leak *isn't* related to the disk cache, it would be very useful with some numbers of where the allocations are made. Instruments.app on MacOS is an excellent heap profiler which very easily pin-points leaks.

**Comment by tjjh89017** [comment]
> > But it seems libtorrent>=1.2.9 remove this configuration, I can setup this entry but it didn't limit ram usage
> > It will eat all the ram until OOM killer kill it.
> 
> Just to be clear then, the configuration option is still there, it just isn't working anymore, in your experience. Right?

the config option is working, but not work as I expected.
It will use mem with double size of cache_size in maximum.

> > I found that libtorrent 2.x removed cache_size and rely on OS cache.
> > Is it also affect to libtorrent>=1.2.9?
> 
> No
> 
> > Is it possible to get cache_size back to limit the libtorrent resource?
> > I'm not sure this will also affect libtorrent 2.x.
> 
> In 2.0.x the configuration option is _actually_ gone, so most likely not. Unless the root cause is something only tangentially related to the disk cache.

Is there any reason to remove it?
Because if we don't use libtorrent as file downloader but streaming or other usage, sometime disk cache will be important to temporarily store piece data and provide to others without any permanent storage.
Or maybe we can implement disk cache in custom_storage in future? 

> @tjjh89017 It would be a good idea to understand where the memory usage comes from. Are you confident it is related to the disk cache?
> You can ask for performance counters (stats counters) which will tell you how many buffers of various kinds are currently in use. If you could post numbers that might help pin-point the kinds of buffers that are leaking.
> 
> If the leak _isn't_ related to the disk cache, it would be very useful with some numbers of where the allocations are made. Instruments.app on MacOS is an excellent heap profiler which very easily pin-points leaks.

In my testing, I only adjust cache_size in options, and it usually shows double size of cache_size mem usage.
Do you have any guideline for me to use performance counters?
I will try to use performance counters to deep into it.

Thanks a lot

**Comment by arvidn** [comment]
using performance counters is briefly described [here](https://libtorrent.org/tuning-ref.html#profiling).

If you want to access the counters "programmatically" you need to find the index of the specific counter you're interested in, at run-time, to index the session stats array.

See [find_metric_idx()](https://libtorrent.org/reference-Stats.html#find_metric_idx()).

[These](https://libtorrent.org/manual-ref.html#session-statistics) are all the available counters.

You'd be interested in `disk.disk_blocks_in_use`, `disk.num_write_jobs`, `disk.queued_write_bytes` and maybe `disk.num_fenced_write`.

**Comment by arvidn** [comment]
> Is there any reason to remove it?

Yes. It's documented [here](https://github.com/arvidn/libtorrent/wiki/memory-mapped-I-O).

> Because if we don't use libtorrent as file downloader but streaming or other usage, sometime disk cache will be important to temporarily store piece data and provide to others without any permanent storage.

in libtorrent-2.0 pieces are still cached, but in the kernel's page cache.

> Or maybe we can implement disk cache in custom_storage in future?

Yes, you can still do this, but the protocol has changed. The customization point is now the whole disk subsystem, not just the storage for a single torrent. In some ways it's more flexible, but it also means more things may have to be built to just tweak some small existing behavior. The disk changes are briefly documented [here](https://libtorrent.org/upgrade_to_2.0-ref.html#disk-i-o-overhaul).

**Comment by tjjh89017** [comment]
Really thanks @arvidn 
I will take a look, test and hope I can give you some helpful info for you

**Comment by tjjh89017** [comment]
Thanks for helping me and guiding me
I will close this ticket first because I cannot be sure that is a bug or something.
Once I finished the test of different version and measure, I will update this ticket
Too busy for me to test my side project.
Thanks again for helping me.
