### ISSUE TITLE
How to detect if all endpoints failed in announce_infohash

### ISSUE THREAD

**Issue by Chocobo1** [arvidn/libtorrent#5335]
**Please provide the following information**

libtorrent version (or branch):
RC_2_0 (with deprecated functions ON)

platform/architecture:
Irrelevant.

compiler and compiler version:
Irrelevant.

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Hi,
I'm trying to decide whether all endpoints are failed with this code:
https://github.com/qbittorrent/qBittorrent/blob/master/src/base/bittorrent/trackerentry.cpp#L64-L78

After loading a **v1** torrent and manually setting an invalid tracker URL for it. The `endpoint.info_hashes.size()` will report `2`, I suppose this is because `info_hashes[0]` is for v1 hash and `info_hashes[1]` is for the unused v2 hash, right?
Now `info_hashes[0].failed` report `> 0` value as expected but `info_hashes[1].failed` will still report `0`, I suppose this is reasonable according to the field definitions in documentation. However this makes the above code snippet fail to detect the "all failed" status.

And here is my question, is there any possible way to determine `info_hashes[1]` is not in use by inspecting any field in [`announce_infohash`](https://libtorrent.org/reference-Trackers.html#announce_infohash)? I would at least expect the `last_error` is set to anything but `0` (currently it is always `0`), would that be reasonable? Or even initialize every field in `info_hashes[1]` to some special value such as `-1`.
Please advice.

@glassez FYI.

**Comment by ssiloti** [comment]
The `announce_endpoint` itself doesn't indicate which versions are in use. You'll need to get that from the `torrent_handle` (e.g. `torrent_handle::info_hashes().has(protocol_version)` from which you got the `announce_endpoint`.
