### ISSUE TITLE
RC_2_0 / b2 will not compile unless cxxstd=14 is in compile command and ignores user-config.jam

### ISSUE THREAD

**Issue by userdocs** [arvidn/libtorrent#5338]
**Please provide the following information**

libtorrent version (or branch): RC_2_0

platform/architecture: amd64 debian/alpine

compiler and compiler version: gcc 8/9 / b2

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

When compiling libtorrent `RC_2_0` with `b2`, if `cxxstd=14` is not passed directly to `b2` as an argument it will not build, producing this error/warning

```
./b2 ...
```

Will give this

```
CXXFLAGS = -std=c++14
LDFLAGS = --static -static -Wl,--no-as-needed -L/root/qb-build/lib -lpthread -pthread
OS = LINUX
building boost from source directory:  /root/qb-build/boost
libtorrent requires at least C++14. Specify <cxxstd>14 or higher
libtorrent requires at least C++14. Specify <cxxstd>14 or higher
...found 540 targets...
...updating 267 targets...
```

But this will work

```
./b2 cxxstd=14 ...
```

My `user-config.jam` 

```
using gcc : : : <cflags>-std=c++14 <cxxflags>-std=c++14 ;
``` 

It works fine with RC_1_2 to not pass this argument.

```
CXXFLAGS = -std=c++14
LDFLAGS = --static -static -Wl,--no-as-needed -L/root/qb-build/lib -lpthread -pthread
OS = LINUX
building boost from source directory:  /root/qb-build/boost
Performing configuration checks

    - default address-model    : 64-bit
    - default architecture     : x86
...patience...
...patience...
...patience...
...found 3763 targets...
...updating 432 targets...
```

Am I doing something wrong here or is the RC_2_0 jamfile checking this before it checks the `user-config.jam`. I think my settings are correct and the Jamfile is being too strict?

**Comment by arvidn** [comment]
the Jamfile isn't checking raw flags you may be passing to the compiler in `user-config.jam`. It just checks what you ask the build system to build. The way you do it used to be the simplest way of building for a newer C++ version until boost build gained first-class support for `cxxstd` option (which was a few years ago now).

`RC_2_0` expect that this `cxxstd` option is used instead. The main benefit is that the ABI may be different for different version of C++. There is one instance in libtorrent where the ABI will be different between C++11 and C++14 or later. It's not ideal to have such ABI issues though, and it is my intention to avoid it in the future.

Perhaps the library should default to some version of C++, but it may be a pessimization to pick the oldest version as the default.

**Comment by userdocs** [comment]
I suppose what threw me is I don't need this `./b2 cxxstd=14 ...` when building libtorrent python binding RC_2_0

It is only when building libtorrent libraries. Should this be consistent for both scenarios?

currently `/Jamfile` requires `./b2 cxxstd=14 ...` but /bindings/python/Jamfile` does not force `./b2 cxxstd=14 ...`

to conclude,

I should always provide this to `cxxstd=14` to `b2` for building RC_2_0?
