### ISSUE TITLE
compile error in master branch with web sockets

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#5340]
I try to build the master branch with websockets enabled. But there are two compiler errors in websocket_tracker_connection.cpp.
I use VS2019 (v142) 64bit address model.
These two lines fail to compile:

json::string const data = json::to_string(payload);

with error: connot convert "boost::json::object" to "boost::json::kind"

any ideas?

**Comment by MassaRoddel** [comment]
I changed it to:

json::string const data = json::serialize(payload);

is that ok?

**Comment by aldenml** [comment]
Hi @MassaRoddel, what boost version are you using? I found the same error but with `1.75.0`

**Comment by aldenml** [comment]
See https://github.com/arvidn/libtorrent/pull/5738

**Comment by MassaRoddel** [comment]
1.73.0

**Comment by aldenml** [comment]
I see, then you are in a similar situation as if using `1.75.0`, I imagine your boost clone is pulling Boost.JSON and overriding the include of the local one inside `deps`. If that's the case, I would just remove the one from github.

**Comment by MassaRoddel** [comment]
switched to boost 1.75.0 and removed boost.json

**Comment by paullouisageneau** [comment]
#5738 breaks compilation with boost 1.75.0 if you don't manually remove the `deps/json` submodule, as tries to include `deps/json/include/boost/json/src.hpp` which fails with `error: #error Do not compile library source with the header only macro defined`.

**Comment by aldenml** [comment]
@paullouisageneau do you have a CI job log with the problem that we can take a look at?

**Comment by paullouisageneau** [comment]
No it's only local. Don't worry, I'll update the submodule and push a fix.
