### ISSUE TITLE
Python dht_put_mutable_item segfaults due to accessing out of scope memory by reference

### ISSUE THREAD

**Issue by pw201** [arvidn/libtorrent#5342]
**Please provide the following information**

I'm using 1.2.10 on Python 3.9, Linux, GCC

Use of `libtorrent.session.dht_put_mutable_item` from Python causes a segfault or "bad alloc" error some time later. Looking at the contents of some alerts, I noticed the key and string I was putting were garbage. It turns out that the lambda used around `put_string` makes a closure over some local variables by reference and they are out of scope when the callback is called asynchronously. Changing the closure to by value fixes this issue (as does using std::bind in the dht_put.cpp example, I guess, though I'm no C++ expert).

I've attached a patch to the session.cpp file which just changes the lambda to capture by value, as well as the script (using the BEP 44 test data) that I use to reproduce.
[patch.txt](https://github.com/arvidn/libtorrent/files/5681242/patch.txt)
[repro.py.txt](https://github.com/arvidn/libtorrent/files/5681258/repro.py.txt)

**Comment by arvidn** [comment]
thanks for the report! I've prepared a slightly different patch that moves the data into the lambda instead.

Does this also work for you?

https://github.com/arvidn/libtorrent/pull/5344

**Comment by pw201** [comment]
Yep, worked for me a couple of times with no crashes (running the same repro.py script).
