### ISSUE TITLE
torrent_handle::set_max_connection takes both -1, 0 as unlimited.

### ISSUE THREAD

**Issue by an0n666** [arvidn/libtorrent#5345]
**Please provide the following information**

libtorrent version (or branch):
1.2.11

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

According to the [documentation,](https://libtorrent.org/reference-Torrent_Handle.html#set-max-connections-max-connections) We have to explicitly set -1 for unlimited connections. However, setting it to 0 also being treated as unlimited.
Also what happens if someone sets it to 1? As the minimum is 2. Perhaps that's also being treated as unlimited.
So, if I don't want any connections, what do I use?

**Comment by arvidn** [comment]
treating 0 as infinite was how it was originally done in libtorrent, not just for this limit, but others too. I've changed it to -1 specifically to open for the possibility to have 0 mean literally 0. and I think a few limits have transitioned to that already.

However, if you want 0 peers, you an pause the torrent.

**Comment by Seeker2** [comment]
I cannot think of a good reason why a torrent should continue doing tracker updates but not accept any peers...but advertise that it is accepting peers.

Is tracker scrapes (which are for paused/queued torrents) what you want?

**Comment by an0n666** [comment]
>I cannot think of a good reason why a torrent should continue doing tracker updates but not accept any peers...but advertise that it is accepting peers.
>

Since BitTorrent clients allow a user to set their upload rate to 1 KiB/s, I don't see why it won't allow a user to not accept any peers! They both do basically the same thing. I would rather not accept any peers than not send any payloads.

**Comment by Seeker2** [comment]
Accepting peers also means accepting seeds.
Seeds may accept peers but not seeds, however I don't know if trackers will differentiate peer/seed lists to them.
