### ISSUE TITLE
Node ID loaded from .session file is not used

### ISSUE THREAD

**Issue by ProteinsLive** [arvidn/libtorrent#5347]
libtorrent version (or branch): RC_2_0

platform/architecture: x86_64, Linux

compiler and compiler version: gcc 9.3.0

Saving and loading the session state out of a session file as introduced in the last example in https://libtorrent.org/tutorial-ref.html does not use the same node ID, that was also saved in the session file, as in the last session. The node ID is recomputed upon every startup, although the external IP address did not change.
I checked the node ID with session.session_state().dht_state.nids and with session.post_dht_stats() (I assume the result of those should not be different anyways).

Expected: Reuse node ID that was saved in the session file.

Note: I searched for a long time whether this is intended or not, but couldn't find any information regarding this issue.

**Comment by arvidn** [comment]
it's not intended. I'll take a look

**Comment by arvidn** [comment]
@ProteinsLive Could you test this patch? https://github.com/arvidn/libtorrent/pull/5773
It's against the 1.2 branch, but it should apply cleanly against the 2.0 branch as well.
