### ISSUE TITLE
Removing session::set_alert_notify callback

### ISSUE THREAD

**Issue by vktr** [arvidn/libtorrent#55]
*Using the `master` branch*

How can I remove the callback I set in `session::set_alert_notify`? The example below worked with the old `set_alert_dispatch`.

```
typedef boost::function<void()> notify_func_t;
sess_->set_alert_notify(notify_func_t());
```

This throws an exception saying "call to empty boost::function".

Ideas?

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/commit/f86283ac3070f61c40c0c6859eb06742d3d0ac6e

does that work?

**Comment by vktr** [comment]
Yes, awesome!
