### ISSUE TITLE
Is there any way or API for add_url_seek for every file block when downloading a multi-file torrent.

### ISSUE THREAD

**Issue by george5613** [arvidn/libtorrent#551]
In my app, the every file in a multi-file torrent we made always corresponds to a real http url source file.(but the http source file sometime not in the same Dir).So our team just wanted to improve the download quality by using the API add_url_seed but unfortunately there seems no api for adding url seeds for every file in a multi-file torrent. We tried to make single file torrent instead,but it makes the program too complicated. So we just wanted a help. Thanks anyway.

**Comment by arvidn** [comment]
There is no support for this in libtorrent. In case you're interested in adding support, the way I would envision it would be to fix the (currently quite restricted and unintuitive) support for http redirects. Ideally, a redirect would be associated with a specific file, and with redirect support, you could quite easily put up a front-end doing the redirects based on a regular web seed url.
