### ISSUE TITLE
configure script BUG?

### ISSUE THREAD

**Issue by buf1024** [arvidn/libtorrent#56]
I compile libtorrent in centos6.3, my os info is:  

```
    Linux HEIDONGVM 2.6.32-279.9.1.el6.x86_64 #1 SMP Tue Sep 25 21:43:11 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux  
```

I install boost library via `yum` software management tool, and the boost library works well and meets the libtorrent minimum required. But running the configure script detect no boost library.  

```
Checking for boost libraries:
checking for boostlib >= 1.36... configure: We could not detect the boost libraries (version 1.36 or higher). If you have a staged boost library (still not installed) please specify $BOOST_ROOT in your environment and do not give a PATH to --with-boost option.  If you are sure you have boost installed, then check your version number looking in <boost/version.hpp>. See http://randspringer.de/boost for more documentation.
checking whether the Boost::System library is available... no
configure: error: Boost.System library not found. Try using --with-boost-system=lib
```

also I try to make libtorrent using cmake, but link errors:   

```
   make[2]: *** 没有规则可以创建“libtorrent-rasterbar.so.8”需要的目标“/usr/lib64/lib64/libboost_system-mt.so.5”。 停止。
```

make[1]: **\* [CMakeFiles/torrent-rasterbar.dir/all] 错误 2

the error message seem linking the boost library again the path "/usr/lib64/lib64/", but the true is the library locate in path "/usr/lib64/".

I check the configure script and CMakeList.txt, it seems no error.  Is the OS problem?

**Comment by arvidn** [comment]
I'm guessing this file may need some patching to support your distro/version:

https://github.com/arvidn/libtorrent/blob/master/m4/ax_boost_base.m4

maybe you can play around with it and see if you can come up with a patch that fixes it.

**Comment by sledgehammer999** [comment]
@arvidn if you follow the link the top of the .m4 file you'll there is a newer version available.

**Comment by arvidn** [comment]
@buf1024 please let me know if the newer version fixes this for you.

**Comment by buf1024** [comment]
@arvidn it doesn't fix the problem.

**Comment by sledgehammer999** [comment]
Try invoking the configure like this `./configure --with-boost=<path to boost include folder> --with-boost-libdir=<path to boost lib folder>`

**Comment by buf1024** [comment]
@sledgehammer999, I try this way many times, and It does't work too, and print the same error. I link /usr/lib64/lib64/libboostXXX to /usr/lib64/libboostXX, and generate make file using cmake, and then temporary success build libtorrent.

**Comment by sledgehammer999** [comment]
I wonder if you'll have better luck reporting to the autoconf's bugtracker (or whichever this macro belongs to)

**Comment by buf1024** [comment]
@arvidn m4/ax_boost_base.m4 seems has some protention bug.

export $BOOST_ROOT, after success check it seems forget to set the varable $_version, this make boost check failed.

**Comment by Falcosc** [comment]
I guess we could close this ticked because currently we have newer boost versions as precondition anyway.
