### ISSUE TITLE
possible ed25519 typo

### ISSUE THREAD

**Issue by ajax16384** [arvidn/libtorrent#560]
fe.cpp contains strange loop pattern:

``` c++
    for (i = 1; i < 1; ++i) {
        fe_sq(...);
    }
```

where is any way it may execute loop block?

**Comment by arvidn** [comment]
coverity discovered that a while ago too, I looked into it then but I can't remember what my conclusion was. iirc, this code is from a 3rd party library.

**Comment by arvidn** [comment]
perhaps it would make sense to report this to: https://github.com/orlp/ed25519

**Comment by aldenml** [comment]
Just to document more about it. It seems that the code is a direct translation of the more primitive algebraic language: https://github.com/floodyberry/supercop/blob/master/crypto_scalarmult/curve25519/ref10/pow225521.h#L51

and it's interesting that in libsodium they removed the code: https://github.com/jedisct1/libsodium/commit/7e1ea85f47e48f9cf01a0becd7b63524762b9a5a

**Comment by Falcosc** [comment]
Should we use a submodule include as suggested by @arvidn ?

> This is one reason why I would be inclined to include this code via a submodule reference. It could still be packaged in the tarfile and built by the build files in libtorrent, but upgrading to new versions would be greatly simplified.
