### ISSUE TITLE
python binding: prioritize_files and prioritize_pieces broken

### ISSUE THREAD

**Issue by lawnmowerwcd** [arvidn/libtorrent#568]
It appears the methods "prioritize_files" and "prioritize_pieces" for the "torrent_handle" class python3 bindings do not work.

Calling the methods simply does nothing in python3. Python2 works as expected.

    >>> handle.file_priorities()
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    >>> x = handle.file_priorities()
    >>> x[0] = 0
    >>> x
    [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    >>> handle.prioritize_files(x)
    >>> handle.file_priorities()
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

edit: corrected affected versions. Only python3 is affected.

**Comment by arvidn** [comment]
which version of libtorrent is this? 1.0.x?

**Comment by lawnmowerwcd** [comment]
I could not get python3 to work with 0.16.17 but I experienced this problem with 0.16.19, 1.0.7 and 1.0.9

**Comment by lawnmowerwcd** [comment]
problems seems to be the line `iter_obj.attr( "next" )`. In python3 this method has been renamed to `__next__`.

**Comment by lawnmowerwcd** [comment]
I'm not sure if I missed something obvious but this patch seems to fix the problem for prioritize_files: https://gist.github.com/lawnmowerwcd/8a383a65af62b4c9042e4543089ccc09

prioritize_pieces is a little harder since there are two cases.

**Comment by arvidn** [comment]
Thanks for the report. This patch should fix it: https://github.com/arvidn/libtorrent/pull/571
