### ISSUE TITLE
python3 binding: torrent_info.metadata() and torrent_info.hash_for_piece() cause UnicodeDecodeError

### ISSUE THREAD

**Issue by lawnmowerwcd** [arvidn/libtorrent#570]
In the python3 bindings calls to `torrent_info.metadata()` and `torrent_info.hash_for_piece()` cause UnicodeDecodeError in almost all cases. In python3 those methods should return a python `bytes()` object, not `str()`.

**Comment by arvidn** [comment]
I updated this pull request to include a fix for this as well. thanks for the report!
https://github.com/arvidn/libtorrent/pull/571

**Comment by lawnmowerwcd** [comment]
Thanks for fixing this so quickly!

`read_piece_alert.get_buffer` has the same problem.
@arvidn do you want to re-open this issue or should I create a new one?

**Comment by arvidn** [comment]
does this fix it? https://github.com/arvidn/libtorrent/pull/576

**Comment by lawnmowerwcd** [comment]
Yes, that works. Thank you again for the swift fix!
