### ISSUE TITLE
Assertion failed on piece_priorities might lead to failed boost assertion, aborting running program

### ISSUE THREAD

**Issue by ardhipoetra** [arvidn/libtorrent#572]
Howdy guys, I got a failed assertion like this (it's on asserts.log)

```
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.0.9.0
ca54dc0

file: 'src/torrent.cpp'
line: 4107
function: void libtorrent::torrent::piece_priorities(std::vector<int>*) const
expression: m_picker.get()


stack:
1: assert_fail(char const*, int, char const*, char const*, char const*, int)
2:
3:
4:
5:
6:
7:
8:
9:
10:
11:
12:
13:
14:
15:
16: boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&)
17: boost::asio::detail::task_io_service::run(boost::system::error_code&)
18: boost::asio::io_service::run(boost::system::error_code&)
19:
20:
21:
22:
23:
24: boost_asio_detail_posix_thread_function
25:
26: clone
```

In the same time, my program got aborted and quit prematurely. The output was : 
```
python2.7: /usr/include/boost/smart_ptr/scoped_ptr.hpp:99: T* boost::scoped_ptr<T>::operator->() const [with T = libtorrent::piece_picker]: Assertion `px != 0' failed.
Aborted
```

I'm using python binding with libtorrent 1.0.9.0. I'm using boost 1.54.

Compiled libtorrent using `bjam` : `bjam -j 4 --debug-configuration boost=system link=shared dht=logging full-stats=on statistics=on asserts=production invariant-checks=off debug-symbols=on
`

I always failed to build RC_1_1, that's why I still used this version. Is this already fixed in the new release?

**Comment by arvidn** [comment]
would you mind filing another ticket about your build failure in RC_1_1?

**Comment by ardhipoetra** [comment]
As it's part **very** huge project, I have to put it hold now. It's related to other issue #582. 

Unfortunately, I can't reproduce that error in small code. But in my project, it's still producing error.

**Comment by arvidn** [comment]
this assert is fixed in RC_1_0: https://github.com/arvidn/libtorrent/commit/aca5f09a314f9d6b7ee819090a4bfa7155890510
