### ISSUE TITLE
python binding: prioritize_files and prioritize_pieces swallowing all exceptions

### ISSUE THREAD

**Issue by lawnmowerwcd** [arvidn/libtorrent#573]
In the python binding the methods `prioritize_files` and `prioritize_pieces` of `torrent_info` swallow all thrown exceptions, especially type casting exceptions. Invalid input will cause the methods to simply return without indication of any error.

This behavior is inconsistent with that of all other methods, which all throw type casting exceptions.

Changing this will potentially break some buggy python code using those methods in an unintended way.

This patch fixes this issue for prioritize_files: https://gist.github.com/lawnmowerwcd/8a383a65af62b4c9042e4543089ccc09 (legal note: my changes here are released into the public domain, do what you want)

sidenote: Thank you for fixing the reported bugs so quickly!

**Comment by arvidn** [comment]
I've spent some time trying to clean up prioritize_pieces(), but it's a bit tricky because the type is not known at compile time. Your patch has been applied though.

**Comment by lawnmowerwcd** [comment]
Thanks for looking into this. I created this patch to prevent exceptions being swallowed. Also simplified the code in prioritize_files a little.

https://gist.github.com/lawnmowerwcd/bbbc4b8b4c69e9242a9d9149549d2199

I'm not really happy about the code duplication but my C++ skills are too bad for anything nicer. May need some polishing but that's up to you.

**Comment by arvidn** [comment]
great, yes, that's a much better patch

**Comment by arvidn** [comment]
I assume you have a good reason to preserve the iterator the way you do, instead of creating a new iterator pair with the int or pair value_type after determining the type of the first element. Is it to support strict forward "iterator" sequences? like, generators?

**Comment by arvidn** [comment]
I would imagine it could be done like this (at least the test passes). https://github.com/arvidn/libtorrent/pull/585

**Comment by lawnmowerwcd** [comment]
Yes, avoidance of creating multiple iterators was done with generators in mind.

Your patch looks much cleaner and works great for me, thanks!
