### ISSUE TITLE
RC 1_1 vs RC 1_2 performance gains?

### ISSUE THREAD

**Issue by elgatito** [arvidn/libtorrent#5739]
Hello Arvid,

I want to ask you a question. Maybe qBitTorrent guys, can also add something about this.

Are there any gains when using RC1_2 compared to RC1_1? 

Maybe lower memory/cpu usage? Bigger download/upload speeds?

Why I ask, is that modification of Swig is not so trivial, and RC1_1 is looking good currently. So not sure if it worth the efforts.

Thanks

**Comment by FranciscoPombal** [comment]
@elgatito 

Not sure about performance (and which specific metric of performance you're most interested in); some things in the `RC_1_2` changelog can be categorized as "performance improvements" (e.g. `improve stat_file() performance on Windows`, in 1.2.10), but to know their real-world impact you'd have to do some benchmarks.

What I can say is this: in recent `RC_1_2` releases there have been a lot of network connectivity fixes that were very important for qBittorrent (e.g. related to using multiple network interfaces, tracker announces, etc). This has led to a perceived performance improvement; in many cases, connecting to more peers means more download/upload speed, which most user's yardstick for performance.

**Comment by arvidn** [comment]
If you're considering updating bindings, I would suggest skipping straight to libtorrent 2.0, where there has been a significant update to the disk I/O. There is no application level disk cache anymore, which lets the kernel make more efficient use of RAM on the system.

**Comment by elgatito** [comment]
@arvidn I have to stick to older C++11 (not even sure about C++14), to keep compatibility with older kernels, order systems, that usually run on media devices.
