### ISSUE TITLE
Question about concurrency access in part_file::export_file

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#574]
I was looking at the code, and I can see that almost all access to the map `m_piece_map` is protected with a mutex, but in this particular function `part_file::export_file` it is not (https://github.com/arvidn/libtorrent/blob/master/src/part_file.cpp#L313).

This function is called in `default_storage::set_file_priority`, is it possible to have some concurrency problem here? Thanks

**Comment by arvidn** [comment]
I think you're right. There's probably an issue there.

**Comment by arvidn** [comment]
does this seem reasonable? https://github.com/arvidn/libtorrent/pull/578

**Comment by aldenml** [comment]
It looks fine to me. I will close this, since it's a question answered.
