### ISSUE TITLE
deprecated vs. get_full_peer_list

### ISSUE THREAD

**Issue by bdekoz** [arvidn/libtorrent#5747]
**Please provide the following information**

libtorrent version (or branch):

top of tree

platform/architecture:

linux 86_64

compiler and compiler version:

g++ 10.2

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

trying to move to a no-deprecated build of libtorrent 2.0, and it's mostly working except for

include/libtorrent/torrent.hpp
```
#if TORRENT_ABI_VERSION == 1
                void get_full_peer_list(std::vector<peer_list_entry>* v) const;
 #endif
```
So, wanting the full list of known peers addresses, but not wanting to resurrect peer_list_entry:

```
diff --git a/src/torrent.cpp b/src/torrent.cpp
index 165c864a3..9283fd152 100644
--- a/src/torrent.cpp
+++ b/src/torrent.cpp
@@ -6978,6 +6978,18 @@ namespace {
        }
 #endif
 
+       void torrent::get_full_peer_ip_list(std::vector<std::string>& v) const
+       {
+               if (!m_peer_list) return;
+               v.clear();
+               v.reserve(aux::numeric_cast<std::size_t>(m_peer_list->num_peers()));
+               for (auto p : *m_peer_list)
+               {
+                 std::string ipaddr = (p->ip().address()).to_string();
+                       v.push_back(ipaddr);
+               }
+       }
+
        void torrent::get_peer_info(std::vector<peer_info>* v)
        {
                v->clear();
```

This is expedient and seems harmless, but could probably be

void torrent::get_known_peer_info(std::vector<peer_info>* v)

?

Thoughts on an interface hook that works for the maintainers but is not deprecated? What's an approved shape?

**Comment by arvidn** [comment]
sorry, I missed this.

I think a modern version of this function should return the vector, rather than take an in-out parameter. Returning vectors is cheap now, it would just means you can't re-use an existing (already allocated) vector.

Using strings  rather than `boost::asio::endpoint` might be a bit awkward, but if you want to support i2p and web seeds, you may have to go that route. However, i2p peers would not work with the code you posted, you'd have to use `dest()` for those.

**Comment by bdekoz** [comment]
hey, thanks. 

It turns out I still have this local patch in for the libtorrent 2.0 production path, it is indeed the only thing left. It would be cool to have an official solution integrated.

So you're saying a no-parameter, return vector<endpoint> is the preferred solution?

**Comment by arvidn** [comment]
> So you're saying a no-parameter, return vector endpoint is the preferred solution?

I would lean towards that, yes.

**Comment by arvidn** [comment]
At least returning the vector rather than an out-parameter.

Regarding the type of the entry, maybe a variant of endpoint and strings. It would be more efficient to return two vectors, one with the endpoints and one with the strings.
