### ISSUE TITLE
Compiling with boost shows no error, but no bin created

### ISSUE THREAD

**Issue by Sovxx** [arvidn/libtorrent#5753]
**Please provide the following information**

libtorrent version (or branch): RC_2_0

platform/architecture: Linux Mint 20 amd64 (fresh install)

compiler and compiler version: gcc 9.3
boost 1.75 installed manually (no package) :
```
benoit@benoit-MS-7971:~/libtor/libtorrent$ which b2
/usr/local/bin/b2
```

in `~/user-config.jam` I have :
`using gcc ;`

in `~/.pam_environment` I have :
```
BOOST_BUILD_PATH=/home/benoit/boost_1_75_0/tools/build/
BOOST_ROOT=/home/benoit/boost_1_75_0/
```

**please describe what symptom you see, what you would expect to see instead and
how to reproduce it.**

In short,
`benoit@benoit-MS-7971:~/libtor/libtorrent$ b2 cxxstd=14` shows no error (I think)
`benoit@benoit-MS-7971:~/libtor/libtorrent$ sudo -E b2 install --prefix=/usr/local` shows no error (I think)
In details,
https://pastebin.com/e1CfxPKR

Then,
`benoit@benoit-MS-7971:~/libtor/libtorrent$ libtorrent` says file not found :(
`benoit@benoit-MS-7971:~/libtor/libtorrent$ ./libtorrent` says file not found :(
a `bin` folder has been created (https://pastebin.com/KWbdQKkZ) but I don't know what to do to use libtorrent.

_It took me several hours to find out how to install and configure boost, use cxxstd=14 (see #5338 ) etc... ; would really appreciate a binary or package!_

Thanks

**Comment by userdocs** [comment]
Can i ask what you are trying to do here?

This command shows you are trying to load the library like a client in your path, `~/libtor/libtorrent$ libtorrent`

`--prefix=/usr/local` will install to the `/usr/local/lib` directory. It's won't be in the path and this won't work. You are building the library for libtorrent RC_2_0 but the question is why? What are you actually trying to do here?

It looks like you are trying to build RC_2_0 but think you can use it directly as a client when need to use it with deluge/qbitorrent but neither of those support it fully yet.

**Comment by Sovxx** [comment]
Wow, I thought it was a client !
I missed the fact that it was just a library...

Duh !
Shorty and thanks!

**Comment by userdocs** [comment]
As nothing is really working with RC_2_0 yet, you may was well stick to clients that support 1_2.

If you want a current qbitorrent build you can use this. (it can use RC_2_0 but there is no point)

https://github.com/userdocs/qbittorrent-nox-static
