### ISSUE TITLE
Cannot get metatada for more than 30-40 infohashes per minute

### ISSUE THREAD

**Issue by retonato** [arvidn/libtorrent#5754]
libtorrent version (or branch): 2.0.1

platform/architecture: Linux 64 bit

compiler and compiler version: I compiled  the lib and python extension manually, using https://github.com/emmercm/docker-libtorrent/blob/master/2.0/Dockerfile as an example

Hi Arvid. I would like to obtain metadata for some bittorrent infohashes. Everything goes fine, the problem is that I would like to do it faster. It seems that there is some setting, which limits the number of simultaneous metadata retrievals to around 30-40 (maybe 60), but I cannot find it.

Here are results of some tests:

100 infohashes added - it took 3 minutes to get metadata for 20% of them, 6.66 per minute
500 infohashes added - it took 12 minutes to get metadata for 20% of them, 8.33 per minute
1000 infohashes added - it took 18 minutes to get metadata for 20% of them, 11.11 per minute

Those infohashes are selected on random from the large collection, approximately 25-30% of them correspond to valid torrents with multiple peers (if I leave the code running long enough, it eventually gets metadata for 30-35% of them). So, the number of processed infohashes can be multiplied by 3-4 to get the number of attempts libtorrent made.

Still, that's not a lot. I expect that adding 500 infohashes instead of 100 will increase the number of processed torrents per minute fivefold. Instead, it increased only by around 25%.

Here are the session settings I use (MAX_TORRENT_NUMBER is the number of added torrents; not all settings are required, I added some just in case):

"active_checking": settings.MAX_TORRENT_NUMBER * 10
"active_dht_limit": settings.MAX_TORRENT_NUMBER * 10
"active_downloads": settings.MAX_TORRENT_NUMBER * 10
"active_limit": settings.MAX_TORRENT_NUMBER * 10
"active_seeds": settings.MAX_TORRENT_NUMBER * 10
"connections_limit": settings.MAX_TORRENT_NUMBER * 100
"dht_upload_rate_limit": 10\*\*9
"dont_count_slow_torrents": True
"download_rate_limit": 10\*\*9

I start session like this:

lt_session.add_dht_router("router.utorrent.com", 6881)
lt_session.add_extension("metadata_transfer")
lt_session.add_extension("ut_metadata")
lt_session.add_extension("ut_pex")
lt_session.start_dht()

Then I wait for at least 75 nodes in the DHT routing table and add torrents to the session like this:

lt_session.add_torrent({
        "file_priorities": [0] * 100000,
        "info_hashes": bytes.fromhex(info_hash),
        "save_path": tempfile.mkdtemp(),
})

The CPU, RAM and network is not a problem. DHT routing table size is around 300 after the first few torrents processed, that seems to be ok. All added torrents have state "downloading_metadata".

So, the question is: Is there some setting (which I missed), which limits the number of simultaneous metadata retrievals? Or is it hardcoded somewhere (like up to 60 torrents simultaneously), so the only way to get more is to launch multiple libtorrent sessions in separate threads?

**Comment by arvidn** [comment]
it looks like `MAX_TORRENT_NUMBER` is the limiting factor. What is that set to?

Presumably more torrents you have in the session in parallel, the more metadata throughout you will achieve. Is that not what you see?

**Comment by arvidn** [comment]
I see you kind of answer that question in your initial post.

You may want to look at `connection_speed` as well, that's the rate limit of making new outgoing connections to peers.

**Comment by retonato** [comment]
1. Thanks for the quick reply. MAX_TORRENT_NUMBER is just a number of torrents, which should be added to the session. I use it as a "base" for calculating settings values. So, if I add 100 torrents - "active_checking" will be 1000 (100 * 10) and so on. In other words, way larger, than is required, just so it doesn't limit in any way.

2. I do get more metadata if I add more torrents, but the rate increases only somewhat. If I add 100 info hashes (simultaneously) and get 20 torrents with metadata in 3 minutes, than I expect that adding 1000 (simultaneously) will produce 200 torrents with metadata in 3 minutes. Ok, maybe 150 (or even 100). Instead, less than 50 torrents have metadata within that time.

3. Hm, I missed connection_speed. However, setting it to MAX_TORRENT_NUMBER * 100 doesn't help, the test results are more or less the same, it still takes 16 minutes to get metadata for 20% of 1000 info_hashes (12.5 per minute). I will probably need to look into the direction of multiple libtorrent sessions.

**Comment by retonato** [comment]
I ended up just starting multiple libtorrent sessions in multiple threads. In that way it works as expected (2 times more sessions - 2 times more processes info hashes).

**Comment by arvidn** [comment]
that's curious. If you end up discovering what the bottleneck is, I'd like to know

**Comment by retonato** [comment]
Ok, I will
