### ISSUE TITLE
Strings don't round-trip properly with dht_put/get_mutable_item

### ISSUE THREAD

**Issue by pw201** [arvidn/libtorrent#5769]
Libtorrent 1.2.10 with the patch for #5344, Ubuntu 20.04, Python 3.9, GCC

dht_get_mutable_item's alert has a .item dictionary containing what I think should be the value in the put, but actually seems to turn the value into a hex representation surrounded by single quotes. See the attached reproduction script which puts a binary string and gets the following:

```
Traceback (most recent call last):
  File "/mnt/z/dev/brew-torrent/repro.py.txt", line 41, in <module>
    assert item.item['value'] == expected_string, f"{item.item['value']} is not {expected_string}"
AssertionError: b"'adefaceddeadd0d0'" is not b'\xad\xef\xac\xed\xde\xad\xd0\xd0'
```

I had a look at the code but can't follow the callbacks well enough to work out where this is happening.

[repro.py.txt](https://github.com/arvidn/libtorrent/files/5731535/repro.py.txt)

**Comment by arvidn** [comment]
it looks like the strings are the same, it's just one is HEX and one is binary. no?

**Comment by arvidn** [comment]
it looks like there may be a few `to_string()` calls [here](https://github.com/arvidn/libtorrent/blob/RC_1_2/bindings/python/src/alert.cpp#L103) that shouldn't be there. I think I meant to type just `string()` there.

**Comment by arvidn** [comment]
it looks like this isn't the first time I've made this mistake. some info-hashes are also turned into a human readable string and then to `bytes`. It's risky to change it though, as it may break clients.

**Comment by arvidn** [comment]
would you mind testing this patch? https://github.com/arvidn/libtorrent/pull/5770

**Comment by pw201** [comment]
Working, doesn't assert. Thanks!
