### ISSUE TITLE
Speed averaging issue

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#5771]
https://github.com/arvidn/libtorrent/blob/bf5d475a6c541ac5df7994d51fe0fdb36b616646/src/stat.cpp#L41

Current averaging algorithm is good because it uses less memory, since only one value is stored.
But at the same time, each value used has an impact on the result for much longer than expected. This does little harm to the result with unstable input data, but it is very noticeable at the boundaries of a stable input graph, especially when the input data is stabilized at a value much different from the previous averaging (for example, when a torrent downloaded data at a high speed, and then finished, so that the download speed became zero, as in [the related qBittorrent Issue](https://github.com/qbittorrent/qBittorrent/issues/14015)).

**Comment by arvidn** [comment]
Yes. I'm open to suggestions on what to do. Part of me would like to not have libtorrent be responsible for any averaging at all.

The challenge is that heuristics may also break badly in some cases. For example, at low transfer rates you may see 1kB. Be transferred (one TCP segment) and then nothing for a second or two. If every time a few samples of zero was read would be considered a singularity, and the averaging window was reset, it would break that edge case.

Probably a more reliable heuristic would be to consider outstanding requests and predict whether we expect to receive anything, and queued outgoing bytes, to predict upload rates >0.

The depth of this makes me prefer it be done outside the library somehow.

**Comment by arvidn** [comment]
The most reliable and intuitive thing to do would probably be to just pick a window size (say, two seconds) and report the number of bytes transferred in that window. It would only break really low rates.

**Comment by glassez** [comment]
The simplest (but more wasteful of memory) way is to store not the previous averaged value, but several previous samples. Then it will be guaranteed to represent the averaging over the last N seconds without affecting by previous values.

**Comment by glassez** [comment]
> The most reliable and intuitive thing to do would probably be to just pick a window size (say, two seconds) and report the number of bytes transferred in that window. It would only break really low rates.



> The simplest (but more wasteful of memory) way is to store not the previous averaged value, but several previous samples. Then it will be guaranteed to represent the averaging over the last N seconds without affecting by previous values.

Probably we are talking about the same thing...

**Comment by arvidn** [comment]
> The simplest (but more wasteful of memory) way is to store not the previous averaged value, but several previous samples. Then it will be guaranteed to represent the averaging over the last N seconds without affecting by previous values.

That's actually what libtorrent used to do (a long time ago). It was changed because it used a non-trivial amount of memory. However, it still had the same problem (to some degree), I think I used a 10 second window, meaning you would still see a non-zero download rate for 10 seconds after finishing.

**Comment by glassez** [comment]
Otherwise you could explicitly clear averagers in some particular cases. E.g. clear download speed averager once torrent is finished downloading.

**Comment by alervd** [comment]
> Part of me would like to not have libtorrent be responsible for any averaging at all.
+1 for this. Libtorrent should not do this.

**Comment by glassez** [comment]
> > Part of me would like to not have libtorrent be responsible for any averaging at all.
> 
> +1 for this. Libtorrent should not do this. Any developer using Libtorrent should decide himself if he wants to show an average value (and what algorithm to use) or not.

👍 
Otherwise application developers even have no chance to fix it if they aren't satisfied with underlying averaging.

**Comment by 4TJMn** [comment]
is there a way to disable this behavior? i would like to see the real rate in the clients interface instead of averages that clutter up the interface because inactive torrents stay on the active tab forever. code hacks are fine as solution if its nothing too complicated

**Comment by Seeker2** [comment]
I don't mind so much if instantaneous speeds were shown on individual torrents, to save memory.

Global speeds could be either also instantaneous OR averaging the last 5-10 seconds, as a user option...probably best defaulting to the 2nd one.

**Comment by TheBestPessimist** [comment]
not stale.

**Comment by arvidn** [comment]
@TheBestPessimist can you contribute to the discussion by proposing solutions or alternative approaches?

**Comment by TheBestPessimist** [comment]
No I can not add a solution. I believe https://github.com/arvidn/libtorrent/issues/5771#issuecomment-757441787 is good enough.

All I wanted to say with my comment is that until that is implemented, this issue should not be closed as it is not stale and not "done".

**Comment by arvidn** [comment]
> I believe #5771 (comment) is good enough.
> 
> All I wanted to say with my comment is that until that is implemented, this issue should not be closed as it is not stale and not "done".

As far as I know, libtorrent already implements this (and has for as long as I can remember).

`peer_info` has `total_download` and `total_upload` fields ([docs](http://libtorrent.org/reference-Core.html#total_download)), which can be used to deduce the download and upload rate at any interval.

**Comment by arvidn** [comment]
> I don't mind so much if instantaneous speeds were shown on individual torrents, to save memory.

@Seeker2 I don't know what you mean by "instantaneous". The instantaneous speed is always 0. The cheapest implementation for libtorrent would be to not provide rates at all. the problem with that is that some heuristics in libtorrent itself relies on rates. But it would be nice to not have to iterate over all peers every second just to decay/update their rate counters.

I imagine you mean to let libtorrent decide the averaging window, which is the same as the tick-rate, which defaults to 1 second.

**Comment by Seeker2** [comment]
Yes, I wrongly used "instantaneous" when I mean the 1 second interval without any averaging with previous 1 second intervals.
Doing no averaging over the torrents or peers would at least in theory be less CPU and memory load.

The global speeds could be averaged, (but does not have to be) since the data needed to do that may already be collected and stored to produce the pretty speed graphs in qBitTorrent.
