### ISSUE TITLE
Syntax error in setup.py (RC_1_2)

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#5783]
I am trying to build latest RC_1_2 on my PPA and it fails with this error message

```
dpkg-buildpackage
-----------------

dpkg-buildpackage: info: source package libtorrent-rasterbar
dpkg-buildpackage: info: source version 1.2.11+git20201226.2c7852ea22-1ppa1~18.04
dpkg-buildpackage: info: source distribution bionic
 dpkg-source --before-build libtorrent-rasterbar-1.2.11+git20201226.2c7852ea22
dpkg-buildpackage: info: host architecture amd64
 fakeroot debian/rules clean
dh clean --parallel --with autoreconf,python2,python3
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/<<BUILDDIR>>/libtorrent-rasterbar-1.2.11+git20201226.2c7852ea22'
rm -rf build build-py*
dh_auto_clean
	python-dbg setup.py clean -a
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    import platform
  File "<string>", line 103
    using = f'using python : {sysconfig.get_python_version()} : {escape(sys.executable)} : {" ".join(escape(path) for path in includes)} : : <libtorrent-python>on : "{target}" ;\n'
                                                                                                                                                                                   ^
SyntaxError: invalid syntax
dh_auto_clean: python-dbg setup.py clean -a returned exit code 1
debian/rules:53: recipe for target 'override_dh_auto_clean' failed
make[1]: *** [override_dh_auto_clean] Error 1
make[1]: Leaving directory '/<<BUILDDIR>>/libtorrent-rasterbar-1.2.11+git20201226.2c7852ea22'
debian/rules:15: recipe for target 'clean' failed
make: *** [clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
--------------------------------------------------------------------------------
```

I have zero experience with python so I am leaving it up to you to fix the syntax.

**Comment by arvidn** [comment]
@AllSeeingEyeTolledEweSew Is this because `f`-strings have to use `"` or is it because of python being too old?

**Comment by sledgehammer999** [comment]
>or is it because of python being too old?

FYI it fails on ubuntu 20.04 PPA too which seems to have python2 2.7.17 and python3 3.8.2 available. (not sure which one is used).
Build log: https://launchpadlibrarian.net/513595804/buildlog_ubuntu-focal-amd64.libtorrent-rasterbar_1.2.11+git20201226.2c7852ea22-1ppa1~20.04_BUILDING.txt.gz

**Comment by arvidn** [comment]
It's supposed to use python3 afaict

**Comment by AllSeeingEyeTolledEweSew** [comment]
> It's supposed to use python3 afaict

Yes. I believe there was a vague decision to stop supporting python 2 earlier this year, as it reached EOL on January 1 2020. I _believe_ there's nothing special in the codebase that blocks python 2 support; IIRC the discussion was based on cleaning up test scripts. Nonetheless I decided to go python3-only with the `setup.py` refactor.

(In hindsight I should've suggested including some strong messaging about dropping support, in the changelog at least)

From the build log, it looks like the PPA is trying to build against python 2. I guess building the python bindings is incidental, since qbittorrent doesn't depend on them? I'm not familiar enough with debian builds to know what to change.

**Comment by AllSeeingEyeTolledEweSew** [comment]
> @AllSeeingEyeTolledEweSew Is this because `f`-strings have to use `"` or is it because of python being too old?

f-strings are supported in python 3.6 and later. python 3.5 reached EOL on September 25 2020.

**Comment by sledgehammer999** [comment]
>I guess building the python bindings is incidental, since qbittorrent doesn't depend on them?

Yes, mostly to not create incompatibilities for users wanting to use Deluge alongside with qBittorrent.

So are the python2 bindings dropped? If so, I think I can make it build now with python3 only.

**Comment by arvidn** [comment]
> f-strings are supported in python 3.6 and later. python 3.5 reached EOL on September 25 2020.

I think that whether a version of python is declared EOL is less relevant than what people actually use, which seems to be recorded here: https://repology.org/project/python/versions

I don't have very strong opinions about dropping python 2, but it definitely seems like a reasonable time to do so. To properly support both would take a lot more work to maintain (both in code and in CI). CI never actually tested both python2 and python3 before.

My understanding right now is that `setup.py` is the only thing requiring 3.6 (as opposed to older 3.x versions). It may seem a bit risky to require such a new version, but I also don't have a very strong opinion.

**Comment by xavier2k6** [comment]
@sledgehammer999 also for ref.: https://github.com/qbittorrent/qBittorrent/pull/13268

**Comment by sledgehammer999** [comment]
@xavier2k6 this is irrelevant IMO for the current issue at hand.

@arvidn @AllSeeingEyeTolledEweSew to my best of my (debian packaging) abilities I have disabled the usage of python2, but it still fails(see [build log](https://launchpadlibrarian.net/513801279/buildlog_ubuntu-bionic-amd64.libtorrent-rasterbar_1.2.11+git20201226.2c7852ea22-2ppa1~18.04_BUILDING.txt.gz)).

If you want to take a look, this is the `debian/rules` file being used:
```
#!/usr/bin/make -f

DPKG_EXPORT_BUILDFLAGS = 1
include /usr/share/dpkg/buildflags.mk

export DEB_LDFLAGS_MAINT_APPEND  = -Wl,--as-needed

PYTHON3=$(shell py3versions -vr)
ALLPY=$(PYTHON3) $(PYTHON3:%=%-dbg)

CONFIGURE_ARGS = --with-libiconv --with-boost-libdir=/usr/lib/$(DEB_HOST_MULTIARCH) CXXFLAGS=-std=c++14 CPPFLAGS=-std=c++14

%:
	dh $@ --parallel --with autoreconf,python3

override_dh_auto_configure-nopy:
	dh_auto_configure --builddirectory build -- $(CONFIGURE_ARGS)

override_dh_auto_configure-%:
	CPPFLAGS="$(CPPFLAGS) $(shell python$*-config --includes)" \
	PYTHON_LDFLAGS="$(shell python$*-config --libs)" \
	dh_auto_configure --builddirectory build-py$* -- \
		PYTHON=/usr/bin/python$* PYTHON_INSTALL_PARAMS="--root=$(CURDIR)/debian/tmp --install-layout=deb" \
		--enable-python-binding --with-boost-python=boost_python-py$(subst .,,$(subst -dbg,,$*)) \
		$(CONFIGURE_ARGS)
	mv build-py$*/bindings/python build/bindings/python$*
	cp -r bindings/python/* build/bindings/python$*

override_dh_auto_configure: override_dh_auto_configure-nopy $(ALLPY:%=override_dh_auto_configure-%)


override_dh_auto_build-nopy:
	dh_auto_build --builddirectory build
	$(MAKE) -C docs/ -f makefile

override_dh_auto_build-%:
	dh_auto_build --builddirectory build/bindings/python$*

override_dh_auto_build: override_dh_auto_build-nopy $(ALLPY:%=override_dh_auto_build-%)


override_dh_auto_install-nopy:
	dh_auto_install --builddirectory build

override_dh_auto_install-%:
	dh_auto_install --builddirectory build/bindings/python$*

override_dh_auto_install: override_dh_auto_install-nopy $(ALLPY:%=override_dh_auto_install-%)


override_dh_auto_clean:
	rm -rf build build-py*
	dh_auto_clean

override_dh_compress:
	dh_compress -Xcpp

override_dh_strip:
	dh_strip --dbg-package=libtorrent-rasterbar-dbg

override_dh_makeshlibs:
	dh_makeshlibs -V

override_dh_builddeb:
	dh_builddeb -- -Z xz

```

**Comment by sledgehammer999** [comment]
Of course the `debian/rules` file was ripped from the official debian packaging some time ago. So I may not understand it fully.

**Comment by arvidn** [comment]
you're still getting the same syntax error? with the `f`-strings? Do you have python 3.6 or later?
It looks like Debian stable has python 3.7, so presumably you do.

**Comment by AllSeeingEyeTolledEweSew** [comment]
That build log is still invoking `python`, which means `python2` on deban/ubuntu. It needs to invoke `python3`.

Based on brief reading it looks like your `dh --with python3` ought to be correct, so I'm not sure what's going wrong. I'll look a little more in the interest of learning more about debian builds but I can't promise I'll find anything quickly

**Comment by AllSeeingEyeTolledEweSew** [comment]
Per https://launchpad.net/debian/+source/debhelper/+changelog
>python_distutils.pm: Deprecate the python-distutils build system
    and mark it as removed in compat 12.  Users are recommended to
    migrate to the third-party build system called "pybuild".  This
    deprecation implies that python3 (among other) will not be
    supported in the python-distutils build system.

It looks like this build is using the `python-distutils` buildsystem, which is still packaged with debhelper and seems to be invoked by default, despite being deprecated.

I added `--buildsystem=pybuild` to `dh` args and it at least invoked python 3 correctly, and got past the syntax error. It's a totally new build system though, so it led to a bunch of new errors.

**Comment by arvidn** [comment]
did the previous debian package only build a python2 module then? or is the version of python used to invoke setup.py not necessarily the target python version for the module?

Is there some simple patch to make this work with the existing build system and debian package rules file? I'd rather not delay cutting libtorrent 1.2.12 because of this.

**Comment by sledgehammer999** [comment]
>did the previous debian package only build a python2 module then? or is the version of python used to invoke setup.py not necessarily the target python version for the module?

My debian packaging build both python2 and python3 bindings. But, from what I gather, I believe the debian instrumentation uses python2 no matter what.

The latest **official** `debian/rules` seems rather [different](https://salsa.debian.org/debian/libtorrent-rasterbar/-/blob/master/debian/rules). It also seems to have dropped building the python2 bindings. I'll try to test it later but I don't know exactly when.

**Comment by sledgehammer999** [comment]
I have some progress! I used the official `debian/rules` and `debian/control` files. I only needed to add `python3-setuptools` as build dependency in `debian/control`.

The build continues for a bit but then it craps out again. It seems to want to use `b2` for building the bindings. Is this strictly necessary? Is this a change from older versions? I thought autotools wouldn't need `b2` for that.

The error is this:
```
running build
running build_ext
using python : 3.6 : "/usr/bin/python3.6" : "/usr/include/python3.6m" "/usr/include/python3.6m" : : <libtorrent-python>on : ".cpython-36m-x86_64-linux-gnu" ;

b2 release address-model=64 -j4 cxxstd=14 python-install-path=build/lib.linux-x86_64-3.6 libtorrent-python=on install_module python=3.6 --project-config=/tmp/tmpvvjrllab
error: command 'b2' failed with exit status 1
Makefile:536: recipe for target 'all-local' failed
make[2]: *** [all-local] Error 1
make[2]: Leaving directory '/<<BUILDDIR>>/libtorrent-rasterbar-1.2.11+git20201226.2c7852ea22/build/bindings/python3.6'
dh_auto_build: cd build/bindings/python3.6 && make -j4 -O returned exit code 2
debian/rules:47: recipe for target 'override_dh_auto_build-3.6' failed
make[1]: *** [override_dh_auto_build-3.6] Error 25
make[1]: Leaving directory '/<<BUILDDIR>>/libtorrent-rasterbar-1.2.11+git20201226.2c7852ea22'
debian/rules:19: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
```

The entire log is here: https://launchpadlibrarian.net/514003872/buildlog_ubuntu-bionic-amd64.libtorrent-rasterbar_1.2.11+git20201226.2c7852ea22-3ppa1~18.04_BUILDING.txt.gz

**Comment by arvidn** [comment]
> The build continues for a bit but then it craps out again. It seems to want to use b2 for building the bindings. Is this strictly necessary? Is this a change from older versions? I thought autotools wouldn't need b2 for that.

Yes, that is a change. only `b2` and `cmake` can be used to build the bindings now

**Comment by arvidn** [comment]
the makefile in `RC_1_2` (which has been removed in `RC_2_0`) just invokes `setup.py`, which previously would use python's distutils to build the python binding. It was risky as there were in total 3 build systems that could build the bindings, and python's distutils was the least maintained one.

**Comment by sledgehammer999** [comment]
>Yes, that is a change. only b2 and cmake can be used to build the bindings now

Since, I am totally unaware how to switch the debian script over to cmake, I'll just add the relevant package that provides `b2` as a build dependency and try again.

I'll report back soon.

**Comment by sledgehammer999** [comment]
It still fails with an error about Jamfile

```
b2 release address-model=64 -j4 cxxstd=14 python-install-path=build/lib.linux-x86_64-3.6 libtorrent-python=on install_module python=3.6 --project-config=/tmp/tmpo38sck1k
CXXFLAGS = -g -O2 -fdebug-prefix-map=/build/libtorrent-rasterbar-1.2.11+git20201226.2c7852ea22=. -fstack-protector-strong -Wformat -Werror=format-security -std=c++14 -ftemplate-depth=512 -Wno-format-zero-length -fvisibility=hidden -fvisibility-inlines-hidden
LDFLAGS = -L/usr/lib/x86_64-linux-gnu -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -fvisibility=hidden -fvisibility-inlines-hidden
OS = LINUX
/usr/share/boost-build/src/build/project.jam:262: in find-jamfile from module project
error: Unable to load Jamfile.
error: Could not find a Jamfile in directory '../..'.
error: Attempted to find it with pattern '[Bb]uild.jam [Jj]amfile.v2 [Jj]amfile [Jj]amfile. [Jj]amfile.jam'.
error: Please consult the documentation at 'http://www.boost.org'.
/usr/share/boost-build/src/build/project.jam:280: in load-jamfile from module project
/usr/share/boost-build/src/build/project.jam:64: in load from module project
/usr/share/boost-build/src/build/project.jam:89: in load-used-projects from module project
/usr/share/boost-build/src/build/project.jam:75: in load from module project
/usr/share/boost-build/src/build/project.jam:145: in project.find from module project
/usr/share/boost-build/src/build-system.jam:535: in load from module build-system
/usr/share/boost-build/src/kernel/modules.jam:295: in import from module modules
/usr/share/boost-build/src/kernel/bootstrap.jam:139: in boost-build from module
/usr/share/boost-build/boost-build.jam:8: in module scope from module

error: command 'b2' failed with exit status 1
Makefile:536: recipe for target 'all-local' failed
make[2]: *** [all-local] Error 1
```

[Build log attached.](https://github.com/arvidn/libtorrent/files/5748817/buildlog.txt)

**Comment by arvidn** [comment]
it looks like perhaps the `Jamfile` in the root of the repository isn't bundled with the package. The python `Jamfile` (in `bindings/python`) links against the main library by referring to the `Jamfile` two directories down, i.e. the root.

**Comment by arvidn** [comment]
@AllSeeingEyeTolledEweSew I think it may actually be problematic, since if the main library is built with autotools, then building the python bindings will trigger a second build of the main library. They should be compatible, but it still builds it twice.

**Comment by arvidn** [comment]
This has been addressed in `RC_2_0`, maybe it was a bit premature to land this in the `RC_1_2` branch.

**Comment by sledgehammer999** [comment]
>it looks like perhaps the Jamfile in the root of the repository isn't bundled with the package. The python Jamfile (in bindings/python) links against the main library by referring to the Jamfile two directories down, i.e. the root.

Do you mean the source tarball? It has a `Jamfile` in the root, I just checked.

**Comment by arvidn** [comment]
I notice this in the build log:

```
/usr/bin/python3.6 ../../../bindings/python/setup.py build
```

I wonder if something gets confused by the current working directory...

**Comment by arvidn** [comment]
@AllSeeingEyeTolledEweSew My first instinct was to `os.chdir()` in `setup.py`, since `b2` needs to be invoked in the directory where the `Jamfile` is found. But Perhaps the current working directory in distutils determines where the output is put, and fixing the `b2` invocation would still leave the target binary in the wrong place.

Do you have any suggestions?

It's possible to specify the Jamfile to use with the `-f<path>` option, but I would expect the binary output would still be placed relative to the Jamfile, not relative the current working directory.

**Comment by arvidn** [comment]
@sledgehammer999 could you try with this patch? https://github.com/arvidn/libtorrent/pull/5793

**Comment by AllSeeingEyeTolledEweSew** [comment]
> @AllSeeingEyeTolledEweSew I think it may actually be problematic, since if the main library is built with autotools, then building the python bindings will trigger a second build of the main library. They should be compatible, but it still builds it twice.

Yeah, that's rough.

From what I understand of b2, it seems like an impedence mismatch to get a target to depend on another target in the project, that wasn't built with b2.

Since you dropped autotools support in 2.0, I guess debian and other builders will need to build the main library with b2 eventually. If they reuse the source directory, maybe the build artifacts should be reused. Maybe we can punt on solving this in RC_1_2...

Should we try to get `setup.py` to use cmake instead, or as an alternative, if it's better at this? I used b2 because it seems to be the favorite child for build system logic, and it's more prominent in libtorrent's documentation. The distutils adaptor logic should be the same, we'd just have to figure out how to configure cmake for the running python. It would take a while to get this going though.

> It's possible to specify the Jamfile to use with the `-f<path>` option, but I would expect the binary output would still be placed relative to the Jamfile, not relative the current working directory.

`-f<path>` seems nice, but I suspect b2 would be brittle if we don't `chdir()`. The b2 manual shows an awful lot of "automagic" around cwd in lots of different places. I don't know exactly how distutils looks for the extension build output (relative to cwd or what), but there shouldn't be any harm in `chdir()`ing for `b2`.

**Comment by arvidn** [comment]
the `-f` option to `b2` didn't work. It seems to replace the whole build system, but setting the working directory seems right.

I added the functionality to link against a pre-built libtorrent library, and made `setup.py` default to that on non-windows (and default windows to statically link against libtorrent).
