### ISSUE TITLE
lt::torrent_info -> is_valid() crash on magnet link without metadata

### ISSUE THREAD

**Issue by wrtorrent** [arvidn/libtorrent#5789]
Hi.

I'm trying to save a .torrent file for each added download.

libtorrent 201 win10x64 MSVC 16.8

```
if (lt::add_torrent_alert* p = lt::alert_cast<lt::add_torrent_alert>(a)) {
	// some code skipped
	if (h.is_valid())
		h.save_resume_data(lt::torrent_handle::save_info_dict | lt::torrent_handle::only_if_modified);
}
if (lt::save_resume_data_alert* p = lt::alert_cast<lt::save_resume_data_alert>(a)) {
	if (p->handle.is_valid()) {
		std::shared_ptr<lt::torrent_info const> ti = p->handle.torrent_file();
		if (ti->is_valid()) {
			filename = ti->name().c_str();
			lt::create_torrent ct(*ti);
			lt::entry te = ct.generate();
			lt::bencode(std::back_inserter(buffer), te);
		}
	}
}
```

When magnet link without metadata added exception c0000005 at line `if (ti->is_valid())`
Is it possible to handle no metadata inside libtorrent lt::torrent_info?

**Comment by arvidn** [comment]
I'm pretty sure `ti` is a nullptr, and you just need to check for that:
```
if (ti && ti->is_valid()) {
```

If that's the case, there is no way to "handle" that inside `torrent_info::is_valid()`. You've already crashed before that.

**Comment by wrtorrent** [comment]
tyvm
