### ISSUE TITLE
python binding: crash in session.pop_alerts()

### ISSUE THREAD

**Issue by lawnmowerwcd** [arvidn/libtorrent#580]
I'm not sure if this is a problem with the python binding or a general problem. This happens using the latest code version from the master branch (with TORRENT_NO_DEPRECATE). The python3 interpreter crashes reliably with a segfault.

I also briefly tested with 1.0.7 which did not cause any crash.

    import libtorrent
    ses = libtorrent.session({})
    ses.async_add_torrent({"ti": libtorrent.torrent_info("test_torrent.torrent"), "save_path": "."})
    ses.async_add_torrent({"ti": libtorrent.torrent_info("test_torrent.torrent"), "save_path": "."})
    while True: ses.pop_alerts()

The last successfully received alert was always a `add_torrent_alert` for me. The value of `save_path` is irrelevant.

The time passed between the calls to `async_add_torrent` or `pop_alerts` does not appear to matter.

**Comment by arvidn** [comment]
thanks for the report. I can reproduce it and will fix

**Comment by arvidn** [comment]
My theory is that the last holder of the torrent_info object is in the main thread (and it's created by boost-python and hence is a python object). When the last reference goes out of scope, the shared_ptr releases the last python reference to the object. When releasing a python reference, one must hold the GIL, but it appears that perhaps the boost-python shared_ptr deleter doesn't do that (by default at least).

**Comment by arvidn** [comment]
This post describes this issue: https://mail.python.org/pipermail/cplusplus-sig/2007-June/012130.html

It doesn't seem like anyone has solved this problem. I will attempt to simply make a copy of the torrent_info object for the C++ side, to avoid the problem altogether.

**Comment by arvidn** [comment]
I imagine this would fix it (my reproduction test no longer fails at least). https://github.com/arvidn/libtorrent/pull/584

**Comment by lawnmowerwcd** [comment]
That seems like unintended behavior by boost. Your patch works well here, too. Thank you!
