### ISSUE TITLE
Suggestion : RC_1_1 set_settings python backward compatibility

### ISSUE THREAD

**Issue by ardhipoetra** [arvidn/libtorrent#582]
In version RC 1.1.0.0 it seems `set_settings` function is broken for python bindings. Instead of receive dictionary format, it needs `settings` data type. 

In [here](http://www.rasterbar.com/products/libtorrent/python_binding.html) and [here](https://github.com/arvidn/libtorrent/blob/RC_1_1/docs/python_binding.rst), I realize that the function need to be changed into `apply_settings` to be able to use dict format of python.

I suggest that, keep this function in python binding to be able dictionary instead of `settings` object.

**Comment by lawnmowerwcd** [comment]
If you use `TORRENT_NO_DEPRECATE` you should not need to use the `settings` data type at all.

**Comment by arvidn** [comment]
Please give this patch a try: https://github.com/arvidn/libtorrent/pull/586

**Comment by ardhipoetra** [comment]
It fixes this problem. However, I also found other backward incompatibility and a segmentation fault in the running program. Will report this later.

**Comment by arvidn** [comment]
@ardhipoetra I'm hoping to release 1.1 very soon, please don't wait too long with that crash and incompatibility report
