### ISSUE TITLE
Can't set `alert_mask` to `lt.alert.category_t.all_categories` in Python bindings

### ISSUE THREAD

**Issue by lucybythec** [arvidn/libtorrent#5848]
In #5831, the following code was suggested:

```python
settings = {'alert_mask': lt.alert.category_t.all_categories}
lt_session = lt.session(settings)
```

Contrary to expectations, this code does not work.

The problem is that `lt.alert.category_t.all_categories` does not fit into a signed 32-bit integer. As a result, an exception ("bad numeric conversion: positive overflow") is thrown in `make_settings_pack` when parsing the dict, but caught and silently discarded.

It works with this patch:

```diff
diff --git a/bindings/python/src/alert.cpp b/bindings/python/src/alert.cpp
index a004bda68..9652f78d3 100644
--- a/bindings/python/src/alert.cpp
+++ b/bindings/python/src/alert.cpp
@@ -346,7 +346,7 @@ void bind_alert()
         s.attr("piece_progress_notification") = alert::piece_progress_notification;
         s.attr("upload_notification") = alert::upload_notification;
         s.attr("block_progress_notification") = alert::block_progress_notification;
-        s.attr("all_categories") = alert::all_categories;
+        s.attr("all_categories") = alert::all_categories & INT_MAX;
     }
 
     {
```

Perhaps the C++ exception should be converted to a Python error?

Using libtorrent d5b27eeacb573d5b6c7b30357c8d27ef1231b7eb on Linux.

**Comment by arvidn** [comment]
I think this patch solves it for any value > `INT_MAX` and < `UINT_MAX`. https://github.com/arvidn/libtorrent/pull/5849
It's against the 1.2 branch but should apply cleanly against master as well, I would think.
