### ISSUE TITLE
Idea: Could DHT answer the "what is my ip" question?

### ISSUE THREAD

**Issue by kilves76** [arvidn/libtorrent#5851]
The old problem, people behind NAT and what is their public ip. 

Setting announce_ip ("&ip=" parameter in message sent to tracker) manually is prone to error due to user confusion and ignorance. What if there was a special message type in DHT which would ask a peer, where did this message come from, and the peer would reply with ip:port where it received the message from. Query 3 peers, if their responses are the same, set it. If not, ask one more peer until there's a quorum.

This would be especially nice in a GUI client where one could have a button for setting the announce ip. Because sometimes it's necessary, and the information gained from responses would also be of interest - if there's a port shifting NAT in the way it would become apparent. Would make different tunneling solutions easier to debug, especially when there's more than one tunnel.

So a DHT extension like this, for your consideration.

There are websites providing something like this but it's an external dependency, DHT should be self contained.
(And sorry if this is the wrong forum for this, thought this could fit in here.)

**Comment by MassaRoddel** [comment]
DHT does that already without any extra message.

**Comment by kilves76** [comment]
Nobody just thought to utilize it this way? I can't recall any client that would actually perform this.
Please do educate me if there's something I've missed.

**Comment by arvidn** [comment]
libtorrent estimates its external IP via these sources:

* DHT messages containing an `ip` field
* a tracker response containing an `external ip` field
* a bittorrent peer extended handshake containing a `yourip`

> Setting announce_ip ("&ip=" parameter in message sent to tracker) manually is prone to error due to user confusion and ignorance. What if there was a special message type in DHT which would ask a peer, where did this message come from, and the peer would reply with ip:port where it received the message from. Query 3 peers, if their responses are the same, set it. If not, ask one more peer until there's a quorum.

Why would you want to set an `&ip=` parameter in your announce message?

The tracker will always know your IP, since you connected to it. The only reason to set an `&ip=` would be if you want to tracker to ignore the source IP and instead use the one you promise is better.

As far as I can tell, trackers generally ignore such parameter, since it's risky to blindly trust peers like that. It would really only make sense to do this if you reach the tracker via some other network than you expect the peers to connect to you. But in that case, how do you know the DHT nodes you talk to are on the "correct" network?

It would be better to announce to the tracker via all networks, or specify the *interface* you want to use to announce to the tracker via.

**Comment by kilves76** [comment]
Consider a split tunnel setup:
Client lan ip is 192.168.0.3 (ip0) behind NAT. Proper port forwarding is in place.
Client traffic exits from ISP CGNAT box (ip1). 
DNS queries and tracker announces are routed into a tunnel (ip2). Tracker sees the announces coming from here. But due to slowness of the tunnel there is no port forwarding back to client listening port(s).

The client would need to know ip1 (preferably automatically) in order to fill the announce_ip properly and have tracker forward peers to the proper ip address. It would also be of interest to know if this gcnat box mangles ports, if DHT peers receive packets from a different port than is set up on the client. Upon finding out that the port gets mangled the client could try a new port.

It's up to tracker would it accept this or not. They could script dht pingback for the announce_ip:port and hash, and cache the check result for duration of the tracker reannounce period. So it'd be only 1 check per client per reannounce period, should they choose to trust the result of a single verification.

In general, it'd be nice to have all used network interfaces verified. If client is listening at 0.0.0.0, then show a list of verified DHT responses how at least 3 peers see the ip:port for each nic. That would be knowledge. Otherwise it's just trust without verification, and can go wrong with complex network setups.

> specify the interface you want to use to announce to the tracker 

It is possible to specify a certain nic to be used only for tracker announces in libtorrent? Tried to find this in the documentation but failed. Could you please point me in the right direction.

**Comment by arvidn** [comment]
If all client traffic exits the network via ip1, the tracker, all peers and all DHT nodes will know you as the client at ip1.
Why would you want to announce via ip2?

If you don't do anything fancy, your tracker announce would exit via ip1 and the tracker would know your correct external IP. There's no need to know what it is (for this purpose).

Even if ports are "mangled". If you announce to a UDP tracker or the the DHT, your source *port* can also be detected which allows peers to connect back over uTP on that same port (assuming a full-cone NAT). No need to know what that port is either.

**Comment by kilves76** [comment]
> Why would you want to announce via ip2?

For privacy from a repressive isp in a monopoly situation, and where the tunnel is too slow for all of the traffic. The easiest ways to detect bittorrent traffic are watching the standard ports 6881-6889, watching DNS requests for known trackers, and announce messages to ip's of known trackers.

Tunnel these through elsewhere and there's only the pure traffic left. Which can be decoded with a network analyzer but it takes a bit of effort for very little reward.

Doesn't have to be just an ISP issue, if one uses VPN the traffic becomes more anonymized if one tunnels the said portion of traffic through another server, or even another vpn provider. Or if renting a VPS in a general purpose datacenter (not a "seedbox").

It's just nice to know that creative solutions are available and possible.
