### ISSUE TITLE
Build fails with 1.2.12 and boost 1.66 with cmake

### ISSUE THREAD

**Issue by lgbaldoni** [arvidn/libtorrent#5858]
**Please provide the following information**

> libtorrent version (or branch):

1.2.12

> platform/architecture:

openSUSE Leap 15.2

> compiler and compiler version:

gcc 7.5.0

> please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Error during the cmake configuration phase. No apparent problem if building with autotools on the same system.
cmake build works on a newer (openSUSE Tumbleweed) system with boost 1.75, but most other packages are also newer.

See attached [logs](https://github.com/arvidn/libtorrent/files/5807268/logs_1.2.12_cmake.zip) for full details.

**Comment by lgbaldoni** [comment]
I stand corrected: the build with autotools fails later like [this](https://github.com/arvidn/libtorrent/files/5807349/1.2.12.txt).

**Comment by arvidn** [comment]
after a brief skimming of those logs, it looks like CMake is trying to determine whether `pthread` is available by default in the compiler, or whether one has to pass `-lpthread` to the linker. However, I don't see it try the most likely case, where you pass `-pthread` to the compiler.

As far as I can tell, it's the initial configuration step that fails, it doesn't even get to try to build libtorrent. Is that also your impression @lgbaldoni ?

**Comment by lgbaldoni** [comment]
> As far as I can tell, it's the initial configuration step that fails, it doesn't even get to try to build libtorrent. Is that also your impression

Indeed.

I tried building boost 1.75 for the same distro and I noticed two things:

1. libtorrent builds flawlessly
2. The [cmake logs](https://github.com/arvidn/libtorrent/files/5816141/175logs.zip) appear to be the same as with 1.66, so pthread is probably a red herring (failed attempts or something)

I wonder if there might be something in the .cmake scripts that make the detection fail.

**Comment by lgbaldoni** [comment]
Apparently passing `-Dboost-python-module-name="python-py3"` fixes the problem.

**Comment by arvidn** [comment]
that sounds vaguely related to this fix in the python binding Jamfile I made recently: https://github.com/arvidn/libtorrent/commit/6d9843cf5e99f86045f52d6156cc873d3e8297a4#diff-6abbccdb045e12134229c5dba31ef1783bb3b7301ccaa42c11f8855b4572a278

my understanding is that sometime around boost-1.66 or 1.67 the debian naming convention changed for the boost-python library.

**Comment by lgbaldoni** [comment]
These are the involved files I see in the two instances on openSUSE:
```
/usr/lib64/libboost_python-py3.so -> libboost_python-py3.so.1.66.0
/usr/lib64/libboost_python-py3.so.1.66.0 (SONAME libboost_python-py3.so.1.66.0)
/usr/lib64/libboost_python3.so -> libboost_python-py3.so
```
and
```
/usr/lib64/libboost_python-py3.so -> libboost_python-py3.so.1.75.0
/usr/lib64/libboost_python-py3.so.1.75.0 (SONAME libboost_python-py3.so.1.75.0)
/usr/lib64/libboost_python3.so -> libboost_python-py3.so
```

The changelog for 1.75 shows this note referred to 1.67 along with this [patch](https://github.com/arvidn/libtorrent/files/5817177/python_library_name.patch.txt)
```
- python_library_name.patch: update it to remove python version
  suffix and keep old sonames. We only support one python3 version
  at a time.
```

I can't say I spot the difference.

**Comment by lgbaldoni** [comment]
Ok, boost 1.75 comes with
```
> ls /usr/lib64/cmake/boost_python-1.75.0/ -1
boost_python-config.cmake
boost_python-config-version.cmake
libboost_python-variant-shared-py3.8.cmake
```
whilst boost 1.66 has nothing of the sort, so I bet `find_package()` [here](https://github.com/arvidn/libtorrent/blob/v1.2.12/bindings/python/CMakeLists.txt#L42) defaults on `/usr/share/cmake/Modules/FindBoost.cmake`.

Anyway, since the problem has a simple solution, I'm not sure it's worth investing too much time on.
