### ISSUE TITLE
Rust bindings

### ISSUE THREAD

**Issue by aykxt** [arvidn/libtorrent#5860]
Are there any plans for official rust bindings for this library like there are for Python? I would really like to use libtorrent in Rust.

**Comment by arvidn** [comment]
I don't have any plans, but I would be happy to support someone making bindings

**Comment by ccarral** [comment]
Hello, has anyone been assigned to making these bindings?

**Comment by arvidn** [comment]
I'm not aware of anyone working on this

**Comment by balupton** [comment]
Seems there was an initial and unfinished start here:
https://github.com/Sreyas-Sreelal/torrent-rs

Perhaps @Sreyas-Sreelal or one of the other rust devs in the bittorrent ecosystem could be funded to do it? If there are commercial users of libtorrent.

**Comment by balupton** [comment]
this comment is recent activity

**Comment by 95th** [comment]
touch

**Comment by balupton** [comment]
bump

**Comment by 95th** [comment]
touch

**Comment by andreymal** [comment]
oh, no one touched this
