### ISSUE TITLE
[Feature Request] BTT Support

### ISSUE THREAD

**Issue by Pgj1997** [arvidn/libtorrent#5861]
Someone over at the qBittorrent repository requested this some time ago, and another person said it'd be appropriate here.

Add support for BitTorrent tokens.

https://www.bittorrent.com/token/btt/

**Comment by arvidn** [comment]
This is quite unlikely to happen. As far as I know the extension to the bittorrent protocol to support paying for bandwidth with BTT is not documented. To be quite honest, I don't think BitTorrent/Tron *can* document it, I don't trust that it is quite what it claims to be.

I think a much more likely path towards a feature like this would be develop an extension that integrates with lightning and use bitcoin. (If anyone is interested in working on that, please contact me!).

**Comment by mozo78** [comment]
uTorrent implemented it. Do we have to use this unbelivable crap?

**Comment by Meehai** [comment]
utorrent is part of btt though... I'd also love this integration, and I hope there's some open source solution to this, since I think it's a pretty nice application of crypto for decentralization incentives.

**Comment by arvidn** [comment]
Do we have any first hand testimony of the speed boost working?
