### ISSUE TITLE
test_pex

### ISSUE THREAD

**Issue by namtsui** [arvidn/libtorrent#5863]
**Please provide the following information**

libtorrent version (or branch): 1.2.12

platform/architecture: openbsd amd64

compiler and compiler version: clang++ 10.0.1

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

test_pex used to pass in 1.2.11 but is skipped in 1.2.12.

https://github.com/arvidn/libtorrent/commit/e666fd7b54c3705d8b40cb7d6e6328071e1aa3e8

If I revert this commit and use pe_forced, test_pex passes.

I added some debug statements and see that the number of peers is 3, 2 and 3. This might come from connecting to themselves? I see "CONNECTION_CLOSED [ op: 1 ERROR: (libtorrent:47) connected to ourselves ]"

```
***** test_pex.cpp:138 "TEST_ERROR: check failed: "st1.num_peers == 2 && st2.num_peers == 2 && st3.num_peers == 2"" *****

st1 nam: 3
st2 nam: 2
st3 nam: 3
```

My basic understanding of this test from reading the comments is that it is trying to simulate session 1 as a seed, session 2 as an intermediary between sessions 1 and 3 using pex, and session 3 should discover 1 via 2. It looks like session 1 and 3 are exchanging pieces though.

full log: https://gist.github.com/namtsui/ba60693c83fc3b3f6fbfcbed9d0d7eba

**Comment by arvidn** [comment]
It's mysterious why it would fail just based on the PE setting. Instead of chasing down sources of flakiness, I rewrote the test as a simulation, which should be deterministic.

https://github.com/arvidn/libtorrent/pull/5876
