### ISSUE TITLE
incoming_connection field set on incoming DHT messages

### ISSUE THREAD

**Issue by 1265578519** [arvidn/libtorrent#5872]
qBittorrent 发起dht查询产生的UDP流量，如果发起收到回应DHT，那么此时客户端会错误显示为绿灯端口开放状态，应当排除请求DHT的UDP回包

This is a issue about the data of UDP packets created when qBittorrent makes DHT queries. The client will mistakenly show that the connection port is in opening state if the client starts to send DHT messages of "response received". So the client should neglect received UDP packets of DHT requests.

https://github.com/qbittorrent/qBittorrent/issues/14149
他们认为此问题属于libtorrent

**Comment by arvidn** [comment]
Is that an accurate update of the title?

**Comment by arvidn** [comment]
which version of libtorrent is this with?

**Comment by 1265578519** [comment]
我用的qbittorrent，我在哪找到他的libtorrent版本?
I use qbittorrent, where do I find his libtorrent version?

**Comment by arvidn** [comment]
I would expect there to be an "About" box somewhere. But I think there are better forums to ask for help with qBT

**Comment by xavier2k6** [comment]
@arvidn qBittorrent 4.3.3 uses `libtorrent-rasterbar | 1.2.12+git3efdb8a941`

**Comment by xavier2k6** [comment]
>qBittorrent 发起dht查询产生的UDP流量，如果发起收到回应DHT，那么此时客户端会错误显示为绿灯端口开放状态，应当排除请求DHT的UDP回包

`google translation`

qBittorrent initiates the UDP traffic generated by the dht query. If it initiates and receives the response DHT, then the client will display the green light port open state by mistake at this time, and the UDP return packet requesting DHT should be excluded
