### ISSUE TITLE
how do you install libtorrent in python on Mac I tried many times it did not work 

### ISSUE THREAD

**Issue by ahmedyasirx** [arvidn/libtorrent#5873]
**Please provide the following information**

libtorrent version (or branch):

platform/architecture:

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

**Comment by arvidn** [comment]
what did you try and how did they fail?

**Comment by arvidn** [comment]
also, which version of libtorrent did you try to install?

**Comment by ahmedyasirx** [comment]
> what did you try and how did they fail?

I tried to install lib torrent in python on Mac but I don't know how , but I do know you can install  Iibtorrent in linux by adding sudo apt-get install -y python3-libtorrent is there anyway I can do it on Macos

**Comment by arvidn** [comment]
There's documentation https://libtorrent.org/python_binding.html there's also a `setup.py` that can build and install the bindings. But if you're just interested in a package manager installing it, you should look to one of the MacOS package managers, homebrew for example
