### ISSUE TITLE
torrent handle function to manually check a single specified piece

### ISSUE THREAD

**Issue by sjpotter** [arvidn/libtorrent#5879]
I think it be interesting to have a torrent handle function that allows me to manually check a specific piece.

why?

so I can create a funky torrent client that can download data from multiple swarms that have equivalent data, but not equivalent torrent files.

simple example: if I have a block of data, which is mapped by 2 torrent files.  One file is using 128KB parts, while the other is using 512KB part (we can expand this to more than 2 torrents)

if I can map parts in the first torrent to the second and vice versa, I can manually ask the other to recheck a piece when the first has finished downloading all the data it needs for it.  what is mapping?  that pieces (X,Y,Z) in one torrent map to pieces (A,B,C) in the other.  (where these are sets of pieces and the size of the sets dont have to be the same size.

to go back to my example, lets make a simple example: assuming that both torrents have the same file names and sizes and files are listed in the same order, part 0-3 in the first file, will map to 0 in the second (and vice versa).  if torrent 1 completed parts 0-3, my funky cient can ask torrent 2 to force check part 0 and get the valid/invalid result.  If it gets a valid as expected (we are expecting the data to be the same), my funky client would continue.  If it gets an invalid result, my funky client can put this amalgam of torrents into an error state.  Similarly, if torrent 2 finished it's part 0, it would try to verify 0-3 of torrent 1.

this extends to partial overlaps as well.  though it would require a tiny bit more logic, you would only verify the "partial" block in the other torrent if the other torrent had already marked it completed, i.e. to verify that by overwriting a partial piece of the completed block, you didn't corrupt the data by writing something that doesn't match the hash.

**Comment by AllSeeingEyeTolledEweSew** [comment]
I've worked on this problem a little (slightly-different torrent files on different trackers).

One thing to note is that the "partial overlap" case is by far the most common. You'll pretty much never see two torrent authors pick files, blocks and alignments such that piece 0 in one torrent exactly maps to pieces 0-3 in another.

Another thing to note is that this is _not_ the case with v2 torrents. Files are always aligned there, and there are file-level hashes. It should be easier for libtorrent/applications/others to detect matching files, and do fancy things. You should encourage trackers to author v2 torrents.

I think piece hash checking is an awkward way to solve this. I reckon it doesn't play nicely with libtorrent's design, that torrents are either in a "checking" state or not. If you're trying to combine bandwidth between torrents, it doesn't work well for them to pop in and out of checking state all the time.

All that said, I have had an approach to the same problem rattling in the back of my mind for a while. Users often approach slightly-different torrents by detecting collisions themselves out-of-band, and symlinking or hardlinking files. libtorrent could recognize symlinks and hardlinks and take action, such as preventing duplicate downloads, combining bandwidth across swarms, or other fanciness.

**Comment by sjpotter** [comment]
I agree that the partial overlap is the common case, I wanted to build from first principles in my writeup before I got to it, so that it could be understood.  

I'm not sure it would have to switch between a leeching/checking states.  i.e. a torrent leeching that is told to piece_check(n) will check that piece and if it passes, will report it available to the swarm immediately, all while doing it things, and if it fails, its a design decision if it should put the torrent into an error state itself (doesn't make it a more generically useful function) or if the client that is managing it should be able to put it into an error state.  Off the cuff, I'd say probably a flag that is passed into it to say what should be done is the best, either using it just to check pieces out of band for whatever reason vs something that is being used on an active torrent and hence I'm calling you expecting you to pass and a fail is an error.
