### ISSUE TITLE
Unable to use Russian symbols in torrent_info() path

### ISSUE THREAD

**Issue by Gallardo994** [arvidn/libtorrent#5881]
**Please provide the following information**

libtorrent version (or branch): 2.0.2 (Python 3.8 x32)

platform/architecture: Windows 10 x64 20H2 (with latest updates), reproduces on any Windows version

compiler and compiler version: everything from this page https://libtorrent.org/python_binding.html, boost 1.7.3, python 3.8 x32 (reproduces in any version)

Unable to use Russian symbols in paths for adding torrents, using the code from https://libtorrent.org/python_binding.html
If I move the torrent to a different path without unicode symbols, it works as intended.
Output:
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    info = lt.torrent_info(sys.argv[1])
RuntimeError: No such file or directory
```

The path actually exists. Probably, more functions than torrent_info() don't support unicode in paths.

Test version:
[TestTorrent.zip](https://github.com/arvidn/libtorrent/files/5829657/TestTorrent.zip) (you can use any .pyd pre-built libtorrent file to test it, my x32 build is in the archive)
Run with: `python test.py .\РусскоеИмя\test.torrent`

**Comment by AllSeeingEyeTolledEweSew** [comment]
A workaround:
```python
with open(sys.argv[1], mode="rb") as fp:
    info = lt.torrent_info(lt.bdecode(fp.read()))
```
A number of functions in the python bindings have broken support with respect to unicode, `str` and `bytes`. I think probably some type converter functions need to be changed.

**Comment by Gallardo994** [comment]
Thanks, it seems to have worked. Could be nice if we added this workaround to python bindings page so people don't experience problems with that.

**Comment by arvidn** [comment]
I would assume this is broken in 1.2.x as well as 2.0.x. Or is this a recent regression?

**Comment by Gallardo994** [comment]
I personally haven't tested 1.2.x versions, only 2.0.0, 2.0.1 and 2.0.2. I can test those during the weekends and report back. Thanks.

**Comment by arvidn** [comment]
I suspect this is caused by 2.0.x branch now using `fopen()` to load files in `torrent_info()`. On windows it should probably use `_wfopen()`, to support unicode filenames

**Comment by arvidn** [comment]
could someone test this patch? https://github.com/arvidn/libtorrent/pull/5896

**Comment by arvidn** [comment]
@AllSeeingEyeTolledEweSew if you know of any other cases where non-ascii filenames are broken, please test those too (or report them here)

**Comment by AllSeeingEyeTolledEweSew** [comment]
I do know of some cases of unicode handling problems, but nothing specifically related to filenames. I'm gearing up right now to beef up coverage in the python tests.

**Comment by Gallardo994** [comment]
Is testing still required? Missed ability to test it due to having a surgery, I am able to test it on monday. Thanks.

**Comment by arvidn** [comment]
there's no unit test for this, so confirming that this works would be great.

**Comment by Gallardo994** [comment]
Built from non-ascii-files, with command `b2 libtorrent-link=static boost-link=static variant=release link=static runtime-link=static`, I still receive "RuntimeError: No such file or directory"

**Comment by arvidn** [comment]
> It works if the path does not include a dot at the start, indicating current directory in Windows.

I take it you mean `.\` as the prefix to the file, is that right? Or is it possible the issue is that you use a forward slash on windows?

**Comment by Gallardo994** [comment]
`.\` breaks it, but without `.\` it works as intended. No forward slashes, only backslashes on Windows

**Comment by arvidn** [comment]
I think this a separate issue. I will address it in another PR

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/5912
please test this patch (it's against `RC_1_2`, so it may not apply cleanly against `RC_2_0`)

**Comment by Gallardo994** [comment]
I can confirm that it works over `non-ascii-files` branch with no issues with the same Python code.
![image](https://user-images.githubusercontent.com/7792608/105843854-4e438a80-5fe9-11eb-9c74-efc97a758814.png)
