### ISSUE TITLE
set_piece_deadline causes major speed regressions

### ISSUE THREAD

**Issue by jagannatharjun** [arvidn/libtorrent#5891]
**Please provide the following information**

libtorrent version (or branch):
libtorrent 1.2.12

platform/architecture:
Windows x64

compiler and compiler version:
default CMake, msvc

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I am trying to implement an HTTP file serve on the top of libtorrent in qbittorrent but using set_piece_deadline is causing major speed regression while using sequential download doesn't cause any such regressions. I set-piece a deadline in the next 32 MiB file from the current range. but I am noticing very large speed drops because of it.
If interested here is the code https://github.com/jagannatharjun/qBittorrent/blob/stream-final/src/base/streaming/streamfile.cpp#L175

**Comment by arvidn** [comment]
the current algorithm for piece deadline does unfortunately not scale very well with many peers and/or small pieces. This is something I hope to have time to improve by keeping more state in between piece-picks, similar to the regular piece picker, but optimized for the deadline ordering, rather than rarest first.

**Comment by arvidn** [comment]
fewer peers and larger pieces help

**Comment by master255** [comment]
@jagannatharjun I think your algorithm should be much more complex. Study in more detail how it works.

**Comment by jagannatharjun** [comment]
using larger deadline time seems to improve the situation a bit but this increases wait times on the receiver side.

**Comment by master255** [comment]
@jagannatharjun 

> I think your algorithm should be much more complex.

**Comment by jagannatharjun** [comment]
>  improve by keeping more state in between piece-picks, similar to the regular piece picker, but optimized for the deadline ordering, rather than rarest first.

if someone wanted to work on this, can you point a good starting point?

**Comment by elgatito** [comment]
@arvidn Also encountered this. 

I test on a highly crowded torrent. 
Downloading 75 pieces, 4MB each (300MB in total). 
`strict_end_game_mode = true`.

If I just use priorities to mark which pieces to download - I got these times:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1544M  100 1544M    0     0  8222k      0  0:03:12  0:03:12 --:--:-- 13.7M
```

When I call `set_piece_deadline` on the currently read piece and the next one, then I get this:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1544M  100 1544M    0     0  2846k      0  0:09:15  0:09:15 --:--:-- 5190k
```

It would probably be fine to avoid using deadlines, but if I need to download piece with a maximum possible speed - I have no choice.
Even when having all pieces with max priority = `5`, and then marking urgent piece with `7`, it gets downloads few time slower.

**Comment by elgatito** [comment]
@arvidn I would probably expect to have maximum speeds when using simple prioritization used (priority 7 to 1). 
But if needed to get some piece urgently - then set a deadline for it, but when I set a deadline - it drops overall download speed quick a lot.

When not using deadlines, sometimes, piece with priority `7` gets downloaded after almost all pieces with priority `2` are downloaded.

Solution with sequential ranges (the one with a PR being prepared) does not help a lot, because it is possible that I have 2 or some readers for same file, which means I would need N sequential ranges processors.

**Comment by elgatito** [comment]
@arvidn 

While browsing `torrent.cpp` I look into `set_piece_deadline` code and see this:
```
		// if this is the first time critical piece we add. in order to make it
		// react quickly, cancel all the currently outstanding requests
		if (m_time_critical_pieces.empty())
		{
			// defer this by posting it to the end of the message queue.
			// this gives the client a chance to specify multiple time-critical
			// pieces before libtorrent cancels requests
			auto self = shared_from_this();
			m_ses.get_io_service().post([self] { self->wrap(&torrent::cancel_non_critical); });
		}
```

Does it mean, that if I call `set_piece_deadline`  - it will cancel all non-critical pieces requests, so it will only expect one piece? (if there are no other deadlined pieces). 
So then it cancels all the requests for pieces, place request for time critical piece, and then post usual requests. 
Then I post another time_critical piece and again all requests are cancelled?

**Comment by elgatito** [comment]
Also in `piece_picker.cpp`

```
					if ((options & time_critical_mode)
						&& piece_priority(i) != top_priority)
						break;
```

So any non top priority piece is skipped `we receive` deadlined piece? Or they are skipped only before `we send requests` for deadlined piece?

**Comment by elgatito** [comment]
@arvidn I'm trying to track the code to find the place where piece_picker will prioritize pieces with higher priorities over lower ones.

In `peer_connection.cpp`, `peer_connection::picker_options()`, If sequential is disabled, `initial_picker_threshold` is `0`, then `rarest_first` is returned.

In `piece_picker.cpp`, `piece_picker::pick_pieces()`, It seems that it never gets here - https://github.com/arvidn/libtorrent/blob/RC_1_2/src/piece_picker.cpp#L2251 ?

Can you guide here?

**Comment by arvidn** [comment]
> Does it mean, that if I call set_piece_deadline - it will cancel all non-critical pieces requests

yes.

>, so it will only expect one piece? (if there are no other deadlined pieces).

I don't know what you mean by that.

> So then it cancels all the requests for pieces, place request for time critical piece, and then post usual requests.
> Then I post another time_critical piece and again all requests are cancelled?

only if you wait to set the deadline for the second piece until after the first piece has been downloaded. You shouldn't do that, you need a *window* of deadline pieces ahead of your playback cursor.

> So any non top priority piece is skipped we receive deadlined piece? Or they are skipped only before we send requests for deadlined piece?

Yes. This is probably the reason you see a lower download rate overall. You could test to disable this logic (by removing all code related to `time_critical_mode`).

> In piece_picker.cpp, piece_picker::pick_pieces(), It seems that it never gets here - https://github.com/arvidn/libtorrent/blob/RC_1_2/src/piece_picker.cpp#L2251 ?
> 
> Can you guide here?

The piece priorities are baked into the rarity of the pieces to determine the order of the availability list. the way availability is handled is explained [here](https://blog.libtorrent.org/2011/11/writing-a-fast-piece-picker/).

**Comment by elgatito** [comment]
@arvidn 

>> , so it will only expect one piece? (if there are no other deadlined pieces).

> I don't know what you mean by that.

I mean, for example, I have 100 pieces with `priority > 0`. 
I call `set_piece_deadline` for specific piece. 
What will happen after calling that method and actually receiving that deadlined piece? Will piece picker send requests for getting other pieces while waiting for deadlined piece?

> Yes. This is probably the reason you see a lower download rate overall. You could test to disable this logic (by removing all code related to time_critical_mode).

I see it, as it should be, theoretically, great to use priorities to control download order by piece picker, and some way to force picking specific piece (like we do with time critical pieces, but without cancelling other ones' requests).

From the piece picker code I can't find how priorities order is handled and how can we guarantee, that priority 7 is handled before priority 6, even if it is not the rarest one.

**Comment by arvidn** [comment]
> From the piece picker code I can't find how priorities order is handled and how can we guarantee, that priority 7 is handled before priority 6, even if it is not the rarest one.

There is no such guarantee

**Comment by elgatito** [comment]
> There is no such guarantee

Do you have any advice, which place I can try to modify to deal with this? To make priority order + rarest order.

**Comment by arvidn** [comment]
what do you want to do? it's not clear what you mean by "deal with".

If you want to change the piece picker to always have piece priority take precedence over rarity, you'd have to change the way it works at a pretty fundamental level, I think.

**Comment by elgatito** [comment]
@arvidn 
> If you want to change the piece picker to always have piece priority take precedence over rarity, you'd have to change the way it works at a pretty fundamental level, I think.

Yes, I want to play with piece picker and try to change something, see how it goes then.
I was thinking about adding new bit to `picker_options_t`, then modifying `piece_picker::pick_pieces` with a new clause to add a new piece picking functionality.

**Comment by master255** [comment]
@elgatito At some point you have to stop calling set_piece_deadline. When there is enough loaded data for the player to play. From there the torrent is downloaded in sequential mode, without any calls.
Constantly calling methods to the library is a very heavy load on the device. In any case.

I think this is your main mistake.

**Comment by arvidn** [comment]
> Constantly calling methods to the library is a very heavy load on the device. In any case.

I think you're overestimating this cost. Surely the download time issue posted [here](https://github.com/arvidn/libtorrent/issues/5891#issuecomment-814397903) isn't caused by pegging the CPU.

**Comment by arvidn** [comment]
@elgatito would you mind rerunning that test after removing/commenting-out the `time_critical_mode` in the piece picker? (or simply to not set that flag)

**Comment by elgatito** [comment]
@arvidn removing what exactly? If I don't call `set_piece_deadline` - it will not get into `time_critical_mode` sections.

Or comment out places like this one?:
```
			if ((options & time_critical_mode)
				&& piece_priority(dp.index) != top_priority)
				continue;
```

**Comment by arvidn** [comment]
`time_critical_mode`, not `set_piece_deadline()`. The simplest patch is to never set this flag, to disable the feature in the piece picker. It's set [here](https://github.com/arvidn/libtorrent/blob/72b9e05f5840e4d7dccd7a54dae50c1881d64b4c/src/peer_connection.cpp#L912).

**Comment by elgatito** [comment]
@arvidn 
With commenting this code inside `peer_connection`:
```
		if (t->num_time_critical_pieces() > 0)
		{
			ret |= piece_picker::time_critical_mode;
		}
```

And still setting `set_piece_deadline` to the first piece, which we urgently need, average download speed is less than 500kb/s. And it looks like only pieces with priority=7 are downloaded.
```
  4 1544M    4 72.0M    0     0   384k      0  1:08:34  0:03:12  1:05:22  812k
```

Without `set_piece_deadline`, speeds quickly rise to 10-12 mb/s, but often I see this, while waiting for piece with priority 7:
```
[2021-04-08 15:21:24] INFO | Reader::wait_for_piece > Done waiting for piece '756' in 24917 ms
[2021-04-08 15:21:37] INFO | Reader::wait_for_piece > Done waiting for piece '767' in 7505 ms
[2021-04-08 15:21:47] INFO | Reader::wait_for_piece > Done waiting for piece '772' in 9911 ms
```

**Comment by arvidn** [comment]
@elgatito double check that you're using your updated library

**Comment by elgatito** [comment]
@arvidn Re-tested again.

With enabled `set_piece_deadline` for the most needed piece, and `time_critical_mode` enabled in `peer_connection`:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1544M  100 1544M    0     0  4066k      0  0:06:28  0:06:28 --:--:-- 9895k
```

Same but with disabled `time_critical_mode` (commented):
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 11 1544M   11  176M    0     0   956k      0  0:27:33  0:03:08  0:24:25  877k
```

I'm looking at pieces progress and I see 70 pieces with priority > 0, and they are not downloaded.

**Comment by elgatito** [comment]
@arvidn 
I have tried a simple way to prioritize pieces.
I added a bool setting to `settings_pack`, if enabled, `peer_connection` is setting it.
Here is a `piece_picker` code, placed here (before `rarest_first`): https://github.com/arvidn/libtorrent/blob/72b9e05f5840e4d7dccd7a54dae50c1881d64b4c/src/piece_picker.cpp#L2177

```
		else if (options & priority_order)
		{
			if (m_dirty) update_pieces();
			TORRENT_ASSERT(!m_dirty);

			for (auto prio = 7; prio > 0; --prio)
			{
				for (auto i : m_pieces)
				{
					if (piece_priority(i) != prio) continue;
					if (!is_piece_free(i, pieces)) continue;

					ret |= picker_log_alert::random_pieces;

					num_blocks = add_blocks(i, pieces
						, interesting_blocks, backup_blocks
						, backup_blocks2, num_blocks
						, prefer_contiguous_blocks, peer, suggested_pieces
						, options);
					if (num_blocks <= 0) return ret;
				}
			}
		}
```

Speed here:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1544M  100 1544M    0     0  5190k      0  0:05:04  0:05:04 --:--:-- 20.9M
```

And, sadly, still seeing things like this when waiting for currently read piece:
```
[2021-04-08 18:00:42] INFO | Reader::wait_for_piece > Done waiting for piece '869' in 39332 ms
[2021-04-08 18:01:23] INFO | Reader::wait_for_piece > Done waiting for piece '957' in 13818 ms
[2021-04-08 18:01:36] INFO | Reader::wait_for_piece > Done waiting for piece '970' in 10809 ms
```

Without my piece selection (and without using deadlines):
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1544M  100 1544M    0     0  4457k      0  0:05:54  0:05:54 --:--:-- 24.0M
```

Without deadlines, libtorrent maximizes my bandwidth usage, but here it waits for some piece for pretty long time (up to 30-40 seconds), time counter starts when priority is set to `7`, but it does not mean priority was `0` before that.

**Comment by elgatito** [comment]
@arvidn I'm now looking at the code of `peer_connection.cpp` and `piece_picker.cpp`.

If we have enabled `sequential` and set any piece deadline, then we have both `piece_picker::sequential` and `piece_picker::time_critical_mode`.
https://github.com/arvidn/libtorrent/blob/RC_1_2/src/peer_connection.cpp#L921
https://github.com/arvidn/libtorrent/blob/RC_1_2/src/peer_connection.cpp#L926

But in `piece_picker::pick_pieces` we get into this if clause:
https://github.com/arvidn/libtorrent/blob/RC_1_2/src/piece_picker.cpp#L2077
Which has check for having time critical pieces at:
https://github.com/arvidn/libtorrent/blob/RC_1_2/src/piece_picker.cpp#L2098
But then we can't get into this part:
https://github.com/arvidn/libtorrent/blob/RC_1_2/src/piece_picker.cpp#L2232

Is that an intended way?

**Comment by elgatito** [comment]
@arvidn As I understand, sequential piece selector does not take care about pieces priorities, it just needs to be more than `0`? 
I guess, the code, I posted above, for making `picker_options::priority_order` it actually a sequential selector, but depending of piece priority? 
So if I set file priority to `2`, while others are set with `1`, then I will make sequential download of that specific file?

**Comment by elgatito** [comment]
@arvidn I have added logging to `piece_picker` to see which mode is used, which piece is selected in specific moments.
When we have `time_critical_piece` - then same piece is picker all the time, until it gets downloaded.
Is there any check available in `piece_picker` that we don't need to send requests for this piece and can pick another one?

**Comment by elgatito** [comment]
@arvidn I am trying to find the code, which cancels current requests to peers, when `set_piece_deadline()` is called. 
Can you give a hint?

**Comment by elgatito** [comment]
@arvidn After about 100 re-compilations and checks, I have narrowed the search for this issue.

I have found that `desired_queue_size` in `request_blocks.cpp` is limited when there are time critical pieces.
Also non-top priority pieces are skipped later in that function.

This patch is maximizing my bandwidth to the max: https://github.com/ElementumOrg/libtorrent/commit/ea510a4418c76162778c2f7d0cb956b548e4e409

Somehow catched a segfault with this trace:
```
 0# signalHandler(int) in out/lt2http
 1# 0x00007F9E98947040 in /lib/x86_64-linux-gnu/libc.so.6
 2# libtorrent::piece_picker::update(int, libtorrent::aux::strong_typedef<int, libtorrent::prio_index_tag_t, void>) in out/lt2http
 3# libtorrent::piece_picker::set_piece_priority(libtorrent::aux::strong_typedef<int, libtorrent::aux::piece_index_tag, void>, libtorrent::aux::strong_typedef<unsigned char, libtorrent::download_priority_tag, void>) in out/lt2http
 4# libtorrent::torrent::remove_time_critical_piece(libtorrent::aux::strong_typedef<int, libtorrent::aux::piece_index_tag, void>, bool) in out/lt2http
 5# libtorrent::torrent_handle::async_call<void (libtorrent::torrent::*)(libtorrent::aux::strong_typedef<int, libtorrent::aux::piece_index_tag, void>), libtorrent::aux::strong_typedef<int, libtorrent::aux::piece_index_tag, void>&>(void (libtorrent::torrent::*)(libtorrent::aux::strong_typedef<int, libtorrent::aux::piece_index_tag, void>), libtorrent::aux::strong_typedef<int, libtorrent::aux::piece_index_tag, void>&) const::{lambda()#1}::operator()() const in out/lt2http
 6# boost::asio::detail::completion_handler<libtorrent::torrent_handle::async_call<void (libtorrent::torrent::*)(libtorrent::aux::strong_typedef<int, libtorrent::aux::piece_index_tag, void>), libtorrent::aux::strong_typedef<int, libtorrent::aux::piece_index_tag, void>&>(void (libtorrent::torrent::*)(libtorrent::aux::strong_typedef<int, libtorrent::aux::piece_index_tag, void>), libtorrent::aux::strong_typedef<int, libtorrent::aux::piece_index_tag, void>&) const::{lambda()#1}>::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) in out/lt2http
 7# std::thread::_State_impl<std::_Bind_simple<libtorrent::session::start(libtorrent::flags::bitfield_flag<unsigned char, libtorrent::session_flags_tag, void>, libtorrent::session_params&&, boost::asio::io_context*)::{lambda()#1} ()> >::_M_run() in out/lt2http
 8# 0x00007F9E99167D80 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 9# start_thread at /build/glibc-S9d2JN/glibc-2.27/nptl/pthread_create.c:463
```

I will continue with tests.

**Comment by AllSeeingEyeTolledEweSew** [comment]
unstale

**Comment by arvidn** [comment]
I think https://github.com/arvidn/libtorrent/pull/6262 addresses most (if not all) the issues raised here. If not, what's left?
That patch does not exhibit a segfault.

**Comment by elgatito** [comment]
@arvidn would we great to have it in RC_1_2. I could not easily move to RC_2_0 due to changed disk interface API.

**Comment by arvidn** [comment]
please feel free to back-port that patch
