### ISSUE TITLE
Suggestion : RC_1_1 files() python backward compatibility

### ISSUE THREAD

**Issue by ardhipoetra** [arvidn/libtorrent#590]
In libtorrent 1.0.9 (or maybe from earlier), function `files()` on `torrent_info` object returned a list of `file_entry`. In RC_1_1, it returned `file_storage` object, instead of this list.

Speaking in general, I think it'd be better if we keep the backward compatibility as much as possible. For example, in Ubuntu repository, they still use version `0.16.13` in their LTS (14.04). This will end in 2019, though.

**Comment by arvidn** [comment]
thanks. I will try to fix this tonight

**Comment by arvidn** [comment]
do you think it's important that it is literally a python list? or is it sufficient if it is iterable?
the main reason this changed is because building that list can be very expensive. the internal representation of the file list is a lot more efficient now. If the file_entry objects are created on the fly, it would be more efficient.

**Comment by arvidn** [comment]
do you think an acceptable solution would be to introduce a "files_deprecated()" function that retains the previous return type?

**Comment by ardhipoetra** [comment]
@arvidn based on my project and [deluge](http://git.deluge-torrent.org/deluge), I think it is safe to return just iterable type. On the other hand, introducing new function will be more difficult (at least for me, personally)

**Comment by arvidn** [comment]
If I recall correctly, I made the file_storage object iterable in the python bindings (brought up by the deluge devs). Perhaps I should double check that in the python test.

**Comment by arvidn** [comment]
it appears the file_storage object is indeed iterable. https://github.com/arvidn/libtorrent/pull/595

**Comment by arvidn** [comment]
if you think this is adequate, please close this ticket

**Comment by ardhipoetra** [comment]
@arvidn sorry for the late response, I think that's enough. Thanks!
