### ISSUE TITLE
Build 1.2.12 on Ubuntu 20.04 failed with [Errno 2] No such file or directory: 'b2'

### ISSUE THREAD

**Issue by skygunner** [arvidn/libtorrent#5909]
**Please provide the following information**

libtorrent version (or branch):
1.2.12

platform/architecture:
Ubuntu 20.04 LTS
AMD X64

compiler and compiler version:
gcc 9.3.0
Python 3.8

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
Follwing the building instruction on https://dev.deluge-torrent.org/wiki/Building/libtorrent
using release source tar ball or git repo 1.2.12 release,
after issuing make, the building failed with error message of 

 using python : 3.8 : "/usr/bin/python3" : "/usr/include/python3.8" "/usr/include/python3.8" : : <libtorrent-python>on : ".cpython-38-x86_64-linux-gnu" ;

b2 release address-model=64 -j8 libtorrent-link=prebuilt linkflags="-L/tmp/libtorrent-rasterbar-1.2.12/bindings/python/../../src/.libs" linkflags="-L/usr/lib/x86_64-linux-gnu" linkflags="-L/usr/lib/x86_64-linux-gnu" libtorrent-python=on python=3.8 python-install-path=/tmp/libtorrent-rasterbar-1.2.12/bindings/python/build/lib.linux-x86_64-3.8 install_module
error: [Errno 2] No such file or directory: 'b2'
make[2]: *** [Makefile:539: all-local] Error 1
make[2]: Leaving directory '/tmp/libtorrent-rasterbar-1.2.12/bindings/python'
make[1]: *** [Makefile:405: all-recursive] Error 1
make[1]: Leaving directory '/tmp/libtorrent-rasterbar-1.2.12/bindings'
make: *** [Makefile:658: all-recursive] Error 1

Is this related to now requires C++14 to build it?
https://github.com/jee-r/docker-deluge/blob/master/rootfs/5026.patch

Edit:
With the instruction found here
https://github.com/arvidn/libtorrent/blob/857a121cfe0edcb4c59a88b2aac715f7d8212ac7/docs/building.rst
I was able to build it with boost, however the last line of installaion command 

`b2 install --prefix=/usr/local
`

failed with permission denied if I ran as normal user, 

it will have the below error if ran with sudo b2 install --prefix=/usr/local:
Unable to load B2: could not find 'boost-build.jam'
Attempted search from '/tmp/libtorrent-rasterbar-1.2.12' up to the root at '/usr/local/bin/b2'
Please consult the documentation at 'https://boostorg.github.io/build/'.

**Comment by skygunner** [comment]
Config results:
  -=-=-=-=-=-=-=-=-

Package:
  name:                 libtorrent-rasterbar
  version:              1.2.12
  git revision:         2d3870c18

Build environment:
  build system:         x86_64-pc-linux-gnu
  host system:          x86_64-pc-linux-gnu
  target system:        x86_64-pc-linux-gnu

Compiler and linker flags:
  CPPFlags:             -I/usr/include
  CFlags:               -pthread -g -O2 -fvisibility=hidden
  CXXFlags:             -g -O2 -ftemplate-depth=512 -Wno-format-zero-length -fvisibility=hidden -fvisibility-inlines-hidden
  LDFlags:              -L/usr/lib/x86_64-linux-gnu  -fvisibility=hidden -fvisibility-inlines-hidden
  Libs:                 -lboost_system -lpthread
  Defs:                 -DPACKAGE_NAME=\"libtorrent-rasterbar\" -DPACKAGE_TARNAME=\"libtorrent-rasterbar\" -DPACKAGE_VERSION=\"1.2.12\" -DPACKAGE_STRING=\"libtorrent-rasterbar\ 1.2.12\" -DPACKAGE_BUGREPORT=\"arvid@libtorrent.org\" -DPACKAGE_URL=\"http://www.libtorrent.org\" -DPACKAGE=\"libtorrent-rasterbar\" -DVERSION=\"1.2.12\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_PTHREAD_PRIO_INHERIT=1 -DHAVE_PTHREAD=1 -DHAVE_BOOST=/\*\*/ -DHAVE_CXX11=1 -DHAVE_BOOST_SYSTEM=/\*\*/ -DHAVE_CLOCK_GETTIME=1 -DNDEBUG=1 -DTORRENT_USE_INVARIANT_CHECKS=0 -DTORRENT_USE_OPENSSL=1 -DTORRENT_USE_LIBCRYPTO=1 -DHAVE_ICONV=1 -DICONV_CONST= -DBOOST_ASIO_HAS_STD_CHRONO=1 -DBOOST_EXCEPTION_DISABLE=1 -DBOOST_ASIO_ENABLE_CANCELIO=1 -DTORRENT_BUILDING_SHARED=1

Build options:
  deprecated functions: yes
  debug build:          no
  invariant checks:     no
  logging support:      yes

Features:
  encryption support:   yes
  dht support:          yes

Extra builds:
  examples:             no
  tests:                no
  python bindings:      no

Pthread library:
  CFlags:               -pthread
  Libs:                 -lpthread

Boost libraries:
  version:
  CPPFlags:             -I/usr/include
  LDFlags:              -L/usr/lib/x86_64-linux-gnu
  boost.system:         -lboost_system

External libraries:
  system libiconv:      no

OpenSSL library:
  OpenSSL Libs:         -lssl -lcrypto
  OpenSSL LDFlags:
  OpenSSL Includes:

Type 'make' to compile libtorrent-rasterbar 1.2.12
or type 'make V=1' for verbose compiling
and then 'make install' to install it into /usr/local

**Comment by AllSeeingEyeTolledEweSew** [comment]
FWIW I'm not sure what the status of the deluge project is any more. I recall the deluge 2.0 branch was originally cut in 2008, and its first release was 2019, and now I see the last commit to develop branch was april 2020.

Not sure what you're trying to do, but here's some background.

Historically there have been several build systems in the libtorrent code base.
* libtool
* cmake
* b2
* distutils piggybacked on libtool
* distutils invoking b2

The distutils/libtool build system was always weakly-supported. Recently (1.2.x) libtorrent dropped this, in favor of having `setup.py` always invoke b2, and improved that. In 2.0, libtool was dropped altogether.

In deluge 1.3, they had maintained their own vendored fork of libtorrent, with their own build system. They seem to have dropped that in their develop branch for 2.0. I'm not sure how they expected this to work, as libtorrent has never been published on pypi (though we're working on that!)

Could you try the following:
```
python3 setup.py install
```
that's expected to work, on all branches now I think. I guess we should update build instructions more thoroughly.

**Comment by petersasi** [comment]
Hi, true that deluge looks kind of abandoned. Building the unofficial windows installer we hand-pick a few PR-s for it.

As for the original problem, at least for the windows build we currently use a vanilla python, boost and libtorrent:
1. require the latest MSVC and OpenSSL
2. scrape, fetch and install the latest python
3. fetch a vanilla boost (1.73 currently) and unpack it
4. fetch the latest libtorrent RC_1_2 branch
5. set up environment variables for the build
6. Bootstrap boost
7. Patch setup.py to really assume the latest MSVC (not sure of this is still needed) https://github.com/petersasi/deluge2-win-build/blob/master/libtorrent-build/1.2-setup-v3.patch
8. also to optimize for speed instead of space and set openssl crypto (maybe this could be done with setup.py command line instead of patching)
9. Build libtorrent pyrhon bindings (which in turn builds boost and libtorrent) using `python.exe setup.py bulid --bjam`
10. Use the resulting libtorrent.pyd

It's all here: https://github.com/petersasi/deluge2-win-build/blob/master/libtorrent-build/lt-RC_1_2.cmd 

I am currently working on trying to find it out where (environment? b2? setup.py?) should I add /GL to the libtorrent and boost compilation command line: https://devblogs.microsoft.com/cppblog/quick-tips-on-using-whole-program-optimization/ (and preferrably /LTCG to the linker)

**Comment by arvidn** [comment]
> I am currently working on trying to find it out where (environment? b2? setup.py?) should I add /GL to the libtorrent and boost compilation command line: https://devblogs.microsoft.com/cppblog/quick-tips-on-using-whole-program-optimization/ (and preferrably /LTCG to the linker)

I forget if the previous version of `setup.py` let you pass-through arguments to `b2`. If so, you can just add `lto=on` on the `b2` command line. It will enable link time optimization/whole program optimization. There's also `lto-mode=` to control what kind of LTO to use. It's documented [here](https://boostorg.github.io/build/manual/develop/index.html).

If you need finer grained control (but still can pass arguments on the `b2` command line) you can always use `linkflags=/LTCG`

However, if `setup.py` doesn't let you pass through arguments (and you don't want to patch `setup.py`) you could also configure the toolset from the "outside". Create a file in the libtorrent root called `Jamroot.jam` and put something like this in it:

```
using msvc : : <linkflags>/LTCG <compileflags>/GL ;
```

**Comment by petersasi** [comment]
> I forget if the previous version of `setup.py` let you pass-through arguments to `b2`. If so, you can just add `lto=on` on the `b2` command line. It will enable link time optimization/whole program optimization. There's also `lto-mode=` to control what kind of LTO to use. It's documented [here](https://boostorg.github.io/build/manual/develop/index.html).

Seems to me the source of the problem is the new setup.py, that no longer accepts --bjam, also I have no idea how to pass more essential b2 command line with it: `crypto=openssl` (could live without the perf optimization :)
Do I patch-add `write("...")` lines into  `write_b2_python_config`? :)
What to add for crypto=openssl (and optimize=speed lto=on etc)?

**Comment by arvidn** [comment]
we'll add a way to pass such arguments on to `b2`. To patch arguments in, you want to add them to the `args` list in `setup.py`

**Comment by petersasi** [comment]
Thanks for the swift backport, will close upon the 1.2.13 release hopefully including that. 👍

**Comment by arvidn** [comment]
@petersasi it would be great if you could try out the patch to confirm that it works for you before I land it and cut a release

**Comment by petersasi** [comment]
Hi, just built LT with boost 1.75 as I saw that actually includes some fixes / reverts in ASIO that may have a performance impact, then built deluge torrent then the installer, installed it on another box, deluge-daemon and deluge-web works, both downloading and seeding, so I believe this fix is good.
I am still struggling why deluge-gtk started failing to start requiring win32, but that is probably a python 3.9.1 or some wheel or deluge itself problem, unrelated to libtorrrent. 😅
