### ISSUE TITLE
0x76ECE486 (ntdll.dll) (xxxxx_171948.full.dmp 中)处有未经处理的异常: 0xC0000005: 读取位置 0x4635DE05 时发生访问冲突。

### ISSUE THREAD

**Issue by f4nff** [arvidn/libtorrent#5910]
libtorrent version (or branch):1.2.11
0x76ECE486 (ntdll.dll) (xxxxx_171948.full.dmp 中)处有未经处理的异常: 0xC0000005: 读取位置 0x4635DE05 时发生访问冲突。
![photo_2021-01-25_20-22-49](https://user-images.githubusercontent.com/19538878/105706677-cf990f80-5f4c-11eb-9e6f-eebd1ee0a026.jpg)

**Comment by arvidn** [comment]
english please

**Comment by arvidn** [comment]
how did you build libtorrent?

**Comment by Lyken17** [comment]
> english please


0x76ECE486 (ntdll.dll) (xxxxx_171948.full.dmp) has unhandled expection: 0xC0000005: Access violation when reading 0x4635DE05

**Comment by arvidn** [comment]
this looks like the same issue as https://github.com/arvidn/libtorrent/issues/6048
