### ISSUE TITLE
Upgrade python-libtorrent-bin

### ISSUE THREAD

**Issue by latot** [arvidn/libtorrent#5913]
Hi hi, I would like to know if that package for python will be updated, or will just be deprecated?

https://pypi.org/project/python-libtorrent-bin/

Thx :D

**Comment by AllSeeingEyeTolledEweSew** [comment]
That pypi project isn't officially maintained. Someone else owns it.

Right now there are no official releases in pypi, but we're working on it

**Comment by latot** [comment]
:O Ty!, I'll be waiting for it, can use libtorrent without compile is nice :3

**Comment by userdocs** [comment]
This project URL seems free. It also seems relevant to the project. (I assume the absence of a project means it is available)

https://pypi.org/project/libtorrent-rasterbar/

Can't you use this? It would seem to fall inline with recent changes and historical naming conventions.

**Comment by mayli** [comment]
> Hi hi, I would like to know if that package for python will be updated, or will just be deprecated?
> 
> https://pypi.org/project/python-libtorrent-bin/
> 
> Thx :D

That's my private binary distro, will update once I have some time :).

**Comment by thombet** [comment]
@AllSeeingEyeTolledEweSew 
> Right now there are no official releases in pypi, but we're working on it

I’m happy to know that it is planned because I am interested in a way to easily use precompiled python bindings on different systems.
I saw there are GitHub actions in this repo which compile the python bindings for several systems: is there a way to download and use these  compiled libraries?

Thanks!

**Comment by AllSeeingEyeTolledEweSew** [comment]
Not right now. The current github actions just test building on various systems, but they don't upload build artifacts anywhere.

I haven't really considered whether these artifacts *should* be downloadable; maybe it's more appropriate to only expose the outputs of `cibuildwheel`.

We've put a lot of work into the python build system though: http://libtorrent.org/python_binding.html

**Comment by mayli** [comment]
@AllSeeingEyeTolledEweSew correct, the wheels from `cibuildwheel` are much more useful, it's just a little bit tricky to get boost into it. I could make a fork and try to get it published over pypi.

**Comment by AllSeeingEyeTolledEweSew** [comment]
That would be awesome.

Please no more third-party-owned pypi projects though :)

We'd really like to get `cibuildwheel` images published to some pypi project actually owned by arvid, so we can maintain them in the release cycle.

**Comment by mayli** [comment]
Yep, I will try to put it as part of the current github actions.

**Comment by jerblack** [comment]
FYI, I was trying to use that third party package since I couldn't make any of python build instructions work for 1.2.13 in a blank Ubuntu:latest container, but that package causes Deluge to generate the error "Unsupported URL Protocol", which means that whoever built the package built it without OpenSSL for some reason. 
https://github.com/arvidn/libtorrent/issues/4350
Is it possible to get a list of clean instructions on how to build the latest version of the python bindings for the 1.2 branch for Ubuntu?

**Comment by AllSeeingEyeTolledEweSew** [comment]
What happens with the official instructions? http://libtorrent.org/python_binding.html

Debian/ubuntu have some modifications to b2's python support, so it's possible there's some quirks we haven't accounted for.

**Comment by jerblack** [comment]
This is as far as I've made it.
Start a clean container
```
docker run --name=libtorrent -it --rm ubuntu:latest bash
```
In the container, run the following:
```
apt-get update && \
apt-get upgrade -y && \
apt-get install -y git curl libboost-tools-dev libboost-dev libboost-python-dev libboost-system-dev build-essential libssl-dev build-essential python3-pip checkinstall && \
python3 -m pip install --upgrade pip && \
python3 -m pip install --upgrade tox && \
curl -Lo libtorrent.tar.gz https://github.com/arvidn/libtorrent/releases/download/v1.2.13/libtorrent-rasterbar-1.2.13.tar.gz && \
tar xf libtorrent.tar.gz && \
cd libtorrent-rasterbar-1.2.13 && \
python3 setup.py build
```
This fails during the build process
```
gcc.compile.c++ bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/session.o
gcc.compile.c++ bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/alert.o
gcc.link.dll bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/libtorrent.cpython-38-x86_64-linux-gnu.so
/usr/bin/ld: cannot find -ltorrent-rasterbar
collect2: error: ld returned 1 exit status

    "g++"    -o "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/libtorrent.cpython-38-x86_64-linux-gnu.so" -Wl,-h -Wl,libtorrent.cpython-38-x86_64-linux-gnu.so -shared -Wl,--start-group "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/module.o" "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/sha1_hash.o" "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/converters.o" "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/create_torrent.o" "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/fingerprint.o" "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/utility.o" "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/session.o" "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/entry.o" "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/torrent_info.o" "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/string.o" "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/torrent_handle.o" "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/torrent_status.o" "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/session_settings.o" "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/version.o" "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/alert.o" "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/datetime.o" "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/peer_info.o" "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/ip_filter.o" "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/magnet_uri.o" "bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/src/error_code.o"  -Wl,-Bstatic  -Wl,-Bdynamic -lboost_python38 -ltorrent-rasterbar -ldl -lpthread -lutil -Wl,--end-group -fPIC -Wl,-Bsymbolic

...failed gcc.link.dll bin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8/libtorrent.cpython-38-x86_64-linux-gnu.so...
...skipped <p/libtorrent-rasterbar-1.2.13/bindings/python/build/lib.linux-x86_64-3.8>libtorrent.cpython-38-x86_64-linux-gnu.so for lack of <pbin/gcc-9/release/address-model-64/lt-visibility-hidden/python-3.8>libtorrent.cpython-38-x86_64-linux-gnu.so...
...failed updating 1 target...
...skipped 1 target...
```
Which causes a Python error at the end
```
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    import multiprocessing
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "setup.py", line 450, in <module>
    setuptools.setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 348, in run
    self._build_extension_with_b2()
  File "setup.py", line 367, in _build_extension_with_b2
    subprocess.run(command, cwd=python_binding_dir, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['b2', 'boost-link=shared', 'libtorrent-link=prebuilt', 'deprecated-functions=on', 'variant=release', 'address-model=64', 'python=3.8', 'libtorrent-python=on', 'python-install-path=/libtorrent-rasterbar-1.2.13/bindings/python/build/lib.linux-x86_64-3.8', 'install_module']' returned non-zero exit status 1.
```

Am I missing something in my setup?

**Comment by mayli** [comment]
@jerblack you might want to reuse or follow the https://github.com/arvidn/libtorrent/blob/RC_2_0/.github/workflows/python.yml#L78
and it seems to be working on github actions.
https://github.com/arvidn/libtorrent/runs/2697698064?check_suite_focus=true

**Comment by jerblack** [comment]
Thank you. It looks like that fixed it. From the Github action and the python_binding documentation, I was able to put together a set of steps that will build an openssl-enabled wheel for me, so I can use these as a Docker build stage in my Deluge setup.

```
apt-get update && \
apt-get upgrade -y && \
apt-get install -y curl libboost-tools-dev libboost-dev libboost-python-dev libboost-system-dev build-essential libssl-dev build-essential python3-pip && \
curl -Lo libtorrent.tar.gz https://github.com/arvidn/libtorrent/releases/download/v1.2.13/libtorrent-rasterbar-1.2.13.tar.gz && \
tar xf libtorrent.tar.gz && \
cd /libtorrent-rasterbar-1.2.13/bindings/python && \
python3 setup.py build_ext --b2-args="libtorrent-link=static crypto=openssl" bdist_wheel
```
This generates a whl file for me at `/libtorrent-rasterbar-1.2.13/bindings/python/dist/python_libtorrent-1.2.13-cp38-cp38-linux_x86_64.whl` which is exactly what I needed. Thanks for the help!

**Comment by dylangerdaly** [comment]
Because you're building it statically, does that mean you don't need the actual native raw libtorrent shared lib as well?
