### ISSUE TITLE
Question: how to calculate the total_downloaded by connection_type for torrent/session?

### ISSUE THREAD

**Issue by 0xb0ba** [arvidn/libtorrent#5919]
peer_disconnected_alert has no peer statistics.
peer_disconnected_alert or torrent_finished_alert -> handle.get_peer_info () does not contain a disconnected peer.

Thanks.

**Comment by arvidn** [comment]
libtorrent does not keep download counters per connection type. one way you could count would be to enable alerts for every block uploaded and downloaded. You'd have to be prepared to handle a lot of alerts though.

**Comment by arvidn** [comment]
you could sample the peer list periodically too, to catch the most recent counters before peers disconnect. That would probably be a bit more efficient, but you would under estimate the counters a little bit, depending on how frequently you poll.

**Comment by 0xb0ba** [comment]
> libtorrent does not keep download counters per connection type. one way you could count would be to enable alerts for every block uploaded and downloaded. You'd have to be prepared to handle a lot of alerts though.

for each block, I will have to search for a peer and its type of connection. and if there are too many alerts?



> you could sample the peer list periodically too, to catch the most recent counters before peers disconnect. That would probably be a bit more efficient, but you would under estimate the counters a little bit, depending on how frequently you poll.

I will have to remember all the peers, take into their reconnections and zero crossings.
