### ISSUE TITLE
Slow download speed compared to scp/rsync

### ISSUE THREAD

**Issue by a1rwulf** [arvidn/libtorrent#5923]
I'm trying to find an explanation for the reason that a file transfer using my torrent client in my local network
is considerable (~3 times) slower than when I use scp for the copy.
While I get around 30MB/s using rsync, ctorrent seems to max out at around 10MB/s.

I've also tried to use 2 seeding hosts in the same network, but the speed is roughly the same as when I use 1 seed.
I get the same speed with my own torrent client based on libtorrent-python.
Also ctorrent gives me the same speed, without knowing if it uses the same library, it still seems
that the speed limit is a torrent thing, but I can't find any answer to it.

libtorrent version (or branch):
Ubuntu 20.04.1 libtorrent-python which seems to be python_libtorrent-1.1.13 and libtorrent-rasterbar.so.9.0.0

platform/architecture:
amd64

I'm just looking for a plausible explanation why it might be 3 times slower and if there's anything
I can do, to get better speed.
Thanks for any help.

EDIT:
After adding another peer, it got considerably faster - so I wonder if the amount of peers/seeds has such huge impact
even though it's only 1 vs. 3 seeds.

**Comment by arvidn** [comment]
> a file transfer using my torrent client in my local network
> is considerable (~3 times) slower than when I use scp for the copy.

http://timesless.com/  :)

> I'm just looking for a plausible explanation why it might be 3 times slower and if there's anything
> I can do, to get better speed.

It's most likely because of the default tuning for a single peer not supporting very large bandwidth delay products.

Try increasing:

```
send_buffer_low_watermark
send_buffer_watermark
```

https://libtorrent.org/reference-Settings.html#send_buffer_watermark

In order to make the client request more pieces, increase:
```
request_queue_time
```

https://libtorrent.org/reference-Settings.html#request_queue_time

It may also be your seeding client not allowing sufficiently many incoming piece requests. 

```
max_allowed_in_request_queue
```
https://libtorrent.org/reference-Settings.html#max_allowed_in_request_queue

**Comment by arvidn** [comment]
there's also this: https://libtorrent.org/tuning-ref.html#tuning-libtorrent

**Comment by arvidn** [comment]
you may also want to keep a lookout for `performance_warning_alert` both on your downloader and uploader. This alert will be posted when some limit is hit, that might affect performance.

**Comment by rafi-d** [comment]
Increasing the number of seeds will help. Try allowing multiple instances of the same IP or give the client couple of more IPs..

**Comment by a1rwulf** [comment]
Wow thanks much for all the pointers, I tried to educate myself, but was a bit overwhelmed with the sheer amount of options available.
I'll go through your suggestions and report back if I find a good improvement.

**Comment by a1rwulf** [comment]
After printing the `performance_warning_alert` I saw `max outstanding piece requests reached` on the downloading end, but increasing those queue sizes (on both ends) didn't really make any difference in the throughput, while the performance message didn't show up anymore after increasing the value of `max_out_request_queue` on the downloading side and `max_allowed_in_request_queue` on the seeding side.
Also I couldn't find any way to improve my situation.
I managed to plot the performance graphs, but I cannot spot an obvious bottleneck unfortunately.
I'm slightly puzzled.

>When disabling uTP (indicating your intention to not regulate speed), the client should really provide the maximum speed with a single seed too...

I also tried to set `mixed_mode_algorithm` to `0` but I see no difference in download speed.

Unfortunately it's not easy for my environment to add IP's on the same machine to make it be multiple seeds, so I'm really looking to understand the issue (if it's an issue at all, but I assume I should be able to get higher bandwidths with 1 seed)
I'm either holding it wrong or I miss something fundamental.

**Comment by arvidn** [comment]
to disable utp (and force TCP) `enable_incoming_utp`: false and `enable_outgoing_utp`: false

**Comment by a1rwulf** [comment]
I see, thanks for that information, will do another test.
Also after settling on some parameters that seem to increase the bandwidth usage a bit, I still see that the `max_out_request_queue` runs full, so I assume my bottleneck is on the seeding side?
One more question: If I disable utp, will I lose the ability to limit download/upload entirely?

**Comment by arvidn** [comment]
> I still see that the max_out_request_queue runs full, so I assume my bottleneck is on the seeding side?

Well, I think it could also be triggered by local limits on the number of outstanding requests. For example, if you increase `request_queue_time`, you're more likely to hit the upper limit of outstanding requests.

> One more question: If I disable utp, will I lose the ability to limit download/upload entirely?

No, but you then have to set limits explicitly. uTP will help your *upload* channel from bloating buffers. But it will also not "push" as hard as TCP does.

**Comment by a1rwulf** [comment]
>Well, I think it could also be triggered by local limits on the number of outstanding requests. For example, if you increase request_queue_time, you're more likely to hit the upper limit of outstanding requests.

I see, probably my queue time is way to high now, I'll reduce it a bit.

>No, but you then have to set limits explicitly. uTP will help your upload channel from bloating buffers. But it will also not "push" as hard as TCP does.

OK that's fine for my usecase I think.

**Comment by a1rwulf** [comment]
Reducing the `request_queue_time` back to 5, removes the performance alert again.
Also I disabled utp to see if it makes any difference, but I'm still kinda maxing out at ~13MB/s.
So not sure how to progress :(
I'll post my current parameter set in case you spot sth obvious wrong:
```
                'incoming_starts_queued_torrents': True,
                'allow_multiple_connections_per_ip': True,
                'apply_ip_filter_to_trackers': True,
                'announce_to_all_trackers': False,
                'announce_to_all_tiers': False,
                'enable_lsd': False,
                'enable_dht': False,
                'enable_upnp': False,
                'enable_natpmp': False,
                'max_allowed_in_request_queue': 5000,
                'max_out_request_queue': 5000,
                'request_queue_time': 5,
                'send_buffer_low_watermark': 500*1024,
                'send_buffer_watermark': 10000*1024,
                'send_buffer_watermark_factor': 300,
                'recv_socket_buffer_size': 6291456,
                'send_socket_buffer_size': 6291456,
                'enable_incoming_utp': False,
                'enable_outgoing_utp': False
```

Other than that, not sure if sharing the stats plot for both seed and downloader will be of any help.
I'm still not 100% in the mood to give it up yet, though :D

**Comment by MRSCARTER06** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by rafi-d** [comment]
How many connetions are you able to see active to that single seed during  downloading?

**Comment by a1rwulf** [comment]
@rafi-d Are we talking about number of connections like in `torrent_status` `num_connections`?
Or is there something else I need to look for?

**Comment by rafi-d** [comment]
No, not settings, just in your peers list - see if you can see two lines/connections to your seed(s). If not - you should try to have qBT create couple of more connections (both sides should be set to allow multiple IPs). If this is all on your local LAN - you can set your seed with an additional IP on this LAN.

**Comment by arvidn** [comment]
@rafi-d I believe @a1rwulf's scenario is a 1-1 transfer

**Comment by a1rwulf** [comment]
@arvidn yeah that's the case in my current scenario. If I make torrent listen to multiple ports like 6881, 6882, 6883 and connect the same peer to my seed 3 times, is this supposed to improve the speed of the data transfer?

**Comment by rafi-d** [comment]
> 
> 
> @rafi-d I believe @a1rwulf's scenario is a 1-1 transfer

Yes, this is why I suggested multiple IP for the seed, if over LAN...

**Comment by a1rwulf** [comment]
I'm not always on the same LAN, but as mentioned I think it's rather easy to use multiple ports.

**Comment by a1rwulf** [comment]
Got back to the topic and implemented to connect to 5 ports to the same IP, however it doesn't seem to keep connected.
```
[2021-02-26 09:42:21,545] - CES - INFO: My_Files peer (172.16.0.13:6885, libtorrent 1.1.13) disconnecting (TCP) [sock_read] [asio.misc]: End of file (reason: 0)
[2021-02-26 09:42:21,545] - CES - INFO: My_Files: *** UPDATE LIST [ torrent_want_peers_finished : 1 ]
[2021-02-26 09:42:21,545] - CES - INFO:  CLOSING CONNECTION 172.16.0.13:6885 : End of file
[2021-02-26 09:42:21,545] - CES - INFO: My_Files [172.16.0.13:6884] <<< ON_RECEIVE_DATA [ bytes: 0 error: (asio.misc:2) End of file ]
[2021-02-26 09:42:21,545] - CES - INFO: My_Files [172.16.0.13:6884] *** ERROR [ in peer_connection::on_receive_data_impl error: End of file ]
[2021-02-26 09:42:21,545] - CES - INFO: My_Files [172.16.0.13:6884] *** CONNECTION_CLOSED [ op: 10 error: End of file ]
[2021-02-26 09:42:21,545] - CES - INFO: My_Files [172.16.0.13:6884] *** SHORT_LIVED_DISCONNECT [  ]
[2021-02-26 09:42:21,545] - CES - INFO: My_Files peer (172.16.0.13:6884, libtorrent 1.1.13) disconnecting (TCP) [sock_read] [asio.misc]: End of file (reason: 0)
[2021-02-26 09:42:21,545] - CES - INFO:  CLOSING CONNECTION 172.16.0.13:6884 : End of file
[2021-02-26 09:42:21,545] - CES - INFO: My_Files [172.16.0.13:6882] <<< ON_RECEIVE_DATA [ bytes: 0 error: (asio.misc:2) End of file ]
[2021-02-26 09:42:21,545] - CES - INFO: My_Files [172.16.0.13:6882] *** ERROR [ in peer_connection::on_receive_data_impl error: End of file ]
[2021-02-26 09:42:21,545] - CES - INFO: My_Files [172.16.0.13:6882] *** CONNECTION_CLOSED [ op: 10 error: End of file ]
[2021-02-26 09:42:21,545] - CES - INFO: My_Files [172.16.0.13:6882] *** SHORT_LIVED_DISCONNECT [  ]
[2021-02-26 09:42:21,546] - CES - INFO: My_Files peer (172.16.0.13:6882, libtorrent 1.1.13) disconnecting (TCP) [sock_read] [asio.misc]: End of file (reason: 0)
[2021-02-26 09:42:21,546] - CES - INFO:  CLOSING CONNECTION 172.16.0.13:6882 : End of file
[2021-02-26 09:42:21,546] - CES - INFO: My_Files [172.16.0.13:6881] <<< READ_AVAILABLE [ bytes: 0 ]
[2021-02-26 09:42:21,546] - CES - INFO: My_Files [172.16.0.13:6881] <<< ON_RECEIVE_DATA [ bytes: 0 error: (asio.misc:2) End of file ]
[2021-02-26 09:42:21,546] - CES - INFO: My_Files [172.16.0.13:6881] *** ERROR [ in peer_connection::on_receive_data_impl error: End of file ]
[2021-02-26 09:42:21,546] - CES - INFO: My_Files [172.16.0.13:6881] *** CONNECTION_CLOSED [ op: 10 error: End of file ]
[2021-02-26 09:42:21,546] - CES - INFO: My_Files [172.16.0.13:6881] *** SHORT_LIVED_DISCONNECT [  ]
[2021-02-26 09:42:21,546] - CES - INFO: My_Files peer (172.16.0.13:6881, libtorrent 1.1.13) disconnecting (TCP) [sock_read] [asio.misc]: End of file (reason: 0)
[2021-02-26 09:42:21,546] - CES - INFO:  CLOSING CONNECTION 172.16.0.13:6881 : End of file
[2021-02-26 09:42:21,870] - CES - INFO: 100.00% completed (down: 0.00 kbyte/s up: 0.00 kbyte/s peers: 1) uploading
[2021-02-26 09:42:21,976] - CES - INFO: My_Files [172.16.0.13:6885] *** CONNECTION CLOSED [  ]
[2021-02-26 09:42:21,977] - CES - INFO: My_Files [172.16.0.13:6884] *** CONNECTION CLOSED [  ]
[2021-02-26 09:42:21,977] - CES - INFO: My_Files [172.16.0.13:6882] *** CONNECTION CLOSED [  ]
[2021-02-26 09:42:21,978] - CES - INFO: My_Files [172.16.0.13:6881] *** CONNECTION CLOSED [  ]
```

I'm bound to `0.0.0.0:6881-6885` on both machines, after connecting to all ports 1 random port will be used and the others will be closed after a few seconds.
Is there anything I can do, besides using different IP addresses?

**Comment by rafi-d** [comment]
> Is there anything I can do, besides using different IP addresses?

No. If the coder implemented randomizing ports and not multi select-wait, nothing will work concurrently, except using the same port with multiple peers' IPs.

**Comment by Seeker2** [comment]
Do 2-5 torrents at the same time, preferably to different destination storage drives with sequential downloading enabled in libtorrent (although that may be the default behavior of libtorrent now with 1 seed to 1 peer).
Sequential downloading to different drives at the same time should reduce disk fragmentation and be slightly faster.
Defraging HDDs before beginning might also help speeds slightly.

Multiple torrents at once can be done with a single BitTorrent app seeding ALL the torrents at once and a single libtorrent peer on the destination computer.

It's a good idea to break up huge unrelated groups of files into multiple separate torrents anyway.
And if the files are being backed up for archival purposes instead of mirroring drives for regular use, compress lots of small files into far fewer ZIP/7zip/RAR files ...which can be copied quicker across a network.
1 MB and larger torrent piece size can make for smoother and faster download speeds when using a gbit network, due to libtorrent writing whole pieces to disk at a time...but this will require libtorrent having a large cache buffer. (like >100 MB ram size for its cache, >10 times larger than the torrent piece size.)

**Comment by a1rwulf** [comment]
> > Is there anything I can do, besides using different IP addresses?
> 
> No. If the coder implemented randomizing ports and not multi select-wait, nothing will work concurrently, except using the same port with multiple peers' IPs.

Who is `the coder` in that case?
The coder of libtorrent or the coder of the torrent application (which would be me in that case).
If it's the latter I can change my code in whatever necessary way, but reading your sentence a few times I'm pretty sure we are talking about libtorrent's implementation or how the networking is done.

**Comment by Seeker2** [comment]
Downloading directly to a SSD has its own minor problems but slow speed isn't typically an issue.
This was your first mention though of drive type.

Making a couple torrents instead of 1 massive one shouldn't be too much trouble.
Just have 2-5 downloading at once.

**Comment by MRSCARTER06** [comment]
MrsCarter

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MRSCARTER06** [comment]
MrsCarter

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
