### ISSUE TITLE
Direct all tracker requests through non-standard proxy?

### ISSUE THREAD

**Issue by fmike7** [arvidn/libtorrent#5925]
libtorrent version (or branch): 1.2.6
platform/architecture: Windows/x86
compiler and compiler version: VS 2019
NOTE: This is a question, not an issue.

I am exploring the possibility of using a custom proxy-like protocol for all torrent tracker requests. Not a traditional HTTP or SOCKS proxy.

Basically instead of libtorrent sending direct HTTP queries to trackers specified in torrents, I would like to wrap these requests into another proprietary protocol (sort of "tunneling" them through). The custom proxy server would then unwrap those and pass to a private tracker service running in a local data center. Why? The eventual goal of this is to reduce the number of connections and ports used by the client app and eliminating the direct tracker connections from the client to the tracker helps to accomplish it.

Of course I can always just edit the libtorrent code directly and change the behavior from HTTP to whatever I want, but I wonder if there is a less "intrusive" way of doing this, via some kind of plugin or extension interface, so I don't modify the library?

**Comment by arvidn** [comment]
well, if the protocol is truly custom, there's no way around modifying libtorrent to make it speak it. you could make the ingress to your tunnel use a standard protocol though. SOCKS5 or HTTP proxy. There's also an i2p SAM connection that can be used as a proxy

**Comment by fmike7** [comment]
I see, ok. So to make it non-intrusive, one could implement a local proxy "wrapper" using one of the standard protocols. Such as listen on 127.0.0.1:3333 (or whatever port) and specify it in libtorrent session settings. And make it SOCKS, HTTP or SAM compliant. Right?

**Comment by arvidn** [comment]
right

**Comment by arvidn** [comment]
although, the i2p/SAM support doesn't have any tests, and there's been at least one report of it being broken.

**Comment by fmike7** [comment]
Going on back to this, is there a way to direct just the tracker traffic over HTTP proxy but continue to use direct P2P traffic between the nodes (not via proxy)?

The documentation for proxy_hostname says this: "Note that when using a proxy, the settings_pack::listen_interfaces setting is overridden and only a single interface is created, just to contact the proxy. This means a proxy cannot be combined with SSL torrents or multiple listen interfaces." So it isn't very clear. I use listen_interfaces to specify a non-standard P2P port, and I want it to listen on all of the available interfaces.

Found your post here: https://stackoverflow.com/questions/39068376/how-to-apply-a-proxy-in-libtorrent

I made it similar:
session_settings.set_str(lt::settings_pack::listen_interfaces, "0.0.0.0:1234);      // my non-standard port for P2P traffic
session_settings.set_str(lt::settings_pack::proxy_hostname, "proxyname.local");
session_settings.set_bool(lt::settings_pack::proxy_peer_connections, false);     // this disables proxy for P2P
session_settings.set_bool(lt::settings_pack::proxy_tracker_connections, true);   // this ENABLES proxy for tracker requests
session_settings.set_int(lt::settings_pack::proxy_type, lt::settings_pack::proxy_type_t::http);    // will this work with HTTPS too?
session_settings.set_int(lt::settings_pack::proxy_port, 443);
session_settings.set_bool(lt::settings_pack::force_proxy, true);              // do not attempt direct tracker requests if proxy fails

Should it be good then? (unless proxy_hostname changes the behavior).

In your post you also suggest to use alerts to monitor any proxy issue. I do monitor all tracker notifications currently:
session_settings.set_int(lt::settings_pack::alert_mask,
	lt::alert::error_notification | lt::alert::storage_notification | lt::alert::status_notification | lt::alert::tracker_notification);

... and watch for tracker_reply_alert, tracker_warning_alert, tracker_error_alert - would these three be enough for my purpose?

**Comment by arvidn** [comment]
> Going on back to this, is there a way to direct just the tracker traffic over HTTP proxy but continue to use direct P2P traffic between the nodes (not via proxy)?

I would think setting `lt::settings_pack::proxy_peer_connections` to false would do it.

> So it isn't very clear. I use listen_interfaces to specify a non-standard P2P port, and I want it to listen on all of the available interfaces.

What it means is that when using a proxy, that proxy is the listen interface. Now, if you disable the proxy for peer conntions, presumably listen interfaces would still be used for those. Please confirm this (and maybe submit a PR to improve that paragraph).

> session_settings.set_int(lt::settings_pack::proxy_type, lt::settings_pack::proxy_type_t::http); // will this work with HTTPS too?

I don't believe the HTTP proxy can run over SSL. Typically, an HTTPS proxy is an HTTP proxy that supports the `CONNECT` command, so you can run an arbitrary stream on top of it.

> ... and watch for tracker_reply_alert, tracker_warning_alert, tracker_error_alert - would these three be enough for my purpose?

Probably

**Comment by fmike7** [comment]
Stupid me, yes, you are right, no HTTPS proxies. Thanks for pointing this out!

**Comment by fmike7** [comment]
But can the tracker URL itself be HTTPS? I tried to use HTTPS but it gave me an error "unsupported URL protocol". I have previously seen other torrent clients using HTTPS as tracker URLs.

**Comment by arvidn** [comment]
> But can the tracker URL itself be HTTPS? I tried to use HTTPS but it gave me an error "unsupported URL protocol". I have previously seen other torrent clients using HTTPS as tracker URLs.

Make sure you build with SSL support enabled. with `b2` that's `crypto=openssl`

**Comment by fmike7** [comment]
Just to confirm: building with crypto=openssl worked!
