### ISSUE TITLE
file_fallocate - Operation not supported errors on macOS 10.14.6

### ISSUE THREAD

**Issue by Lord-Kamina** [arvidn/libtorrent#5937]
**Please provide the following information**

libtorrent version (or branch): 1.2.12

platform/architecture: macOS, downloading to an NTFS (and possibly also, but not sure, APFS) disk.

compiler and compiler version: XCode 11 clang.

symptom: Deluge constantly erroring out due to mysterious reasons; debug log shows the aforementioned `file_error` forwarded from libtorrent.

I've been working on and using Deluge for a while now and seeing it randomly error-out over and over again and I couldn't find the cause. Eventually I realized it appears to be disk errors originating on libtorrent. Initially I was using libtorrent 1.2.2; then updated to 1.2.12 and the issue persists.

From what I understand, this issue is instrinsic to some filesystems not supporting these operations? (Although I think NTFS should support it, no?)

Anyway... I wanted to know whether this is still a thing on current libtorrent master and/or whether there is anyway to prevent this from happening. I plan to try updating Deluge to support the 2.0 branch at least for personal use for now.

**Comment by arvidn** [comment]
> Anyway... I wanted to know whether this is still a thing on current libtorrent master and/or whether there is anyway to prevent this from happening.

Yes, this is still a thing in libtorrent. You can prevent it by disabling file pre-allocation.

> From what I understand, this issue is instrinsic to some filesystems not supporting these operations? (Although I think NTFS should support it, no?)

I think it's primarily a property of the filesystem driver/implementation.

I get the impression you're suggesting libtorrent should not treat this as a fatal error, is that right?
I think it's correct to treat it as a fatal error. The default setting is to not pre-allocate files, so the user made a deliberate choice to pre-allocate. If pre-allocation isn't possible, there would be no (reasonable) way for the user to know this unless it results in a failure.

The other scenario where this can happen (other than the user deliberately opting into pre-allocation) is if a file already exists on disk when adding a torrent, but the existing file is *larger* than what it's supposed to be. In this case, the file is truncated to it's correct size (where "correct" is defined by the torrent file).

If truncation fails in that case, I think it's more clear that it needs to be a fatal error, since it might be a security issue otherwise.

**Comment by Lord-Kamina** [comment]
> Yes, this is still a thing in libtorrent. You can prevent it by disabling file pre-allocation.
This is what I did in the meantime.

> I think it's primarily a property of the filesystem driver/implementation.

This is probably a dumb question, but I'm not certain what exactly is it that needs to be supported for this to succeed. Block allocation? Hard-links, something else?
 
> I get the impression you're suggesting libtorrent should not treat this as a fatal error, is that right?
> I think it's correct to treat it as a fatal error. The default setting is to not pre-allocate files, so the user made a deliberate choice to pre-allocate. If pre-allocation isn't possible, there would be no (reasonable) way for the user to know this unless it results in a failure.

Sorta. I mean, I understand why you treat it as a fatal error, but nowadays people will frequently deal with more than one filesystem in the same machine. Wouldn't it be possible to, for example, query whether the target disk actually supports the necessary operation and if it doesn't override the user selection for pre-allocating and emit just a warning?
 
> The other scenario where this can happen (other than the user deliberately opting into pre-allocation) is if a file already exists on disk when adding a torrent, but the existing file is _larger_ than what it's supposed to be. In this case, the file is truncated to it's correct size (where "correct" is defined by the torrent file).
> 
> If truncation fails in that case, I think it's more clear that it needs to be a fatal error, since it might be a security issue otherwise.

I agree with this entirely.

**Comment by arvidn** [comment]
> This is probably a dumb question, but I'm not certain what exactly is it that needs to be supported for this to succeed. Block allocation? Hard-links, something else?

filesystem drivers (on linux) have a hook to implement fallocate. Perhaps that's failing, I'm not sure.

The operations libtorrent call (depending on operating system) are:

* posix_fallocate()
* fcntl(fd, F_ALLOCSP64, ...)
* fcntl(fd, F_PREALLOCATE, ...)

> Sorta. I mean, I understand why you treat it as a fatal error, but nowadays people will frequently deal with more than one filesystem in the same machine. Wouldn't it be possible to, for example, query whether the target disk actually supports the necessary operation and if it doesn't override the user selection for pre-allocating and emit just a warning?

That would be the same as just ignoring the error.

**Comment by arvidn** [comment]
it would be possible to make "pre-allocate disk space" a per-torrent setting. but it would be a non-trivial change that also would alter the disk customization point and be an ABI break. It would have to go into the `master` branch.
