### ISSUE TITLE
Question: how to speed up web seed mode?

### ISSUE THREAD

**Issue by richardweiu** [arvidn/libtorrent#5947]
libtorrent version (or branch): 2.0.2

platform/architecture:centos7

compiler and compiler version: GCC7

how to speed up web seed mode? I change these setting items, increase or decrease but not work

```
            sts = {
                "ssrf_mitigation": False,
                "max_web_seed_connections": 8,
                "urlseed_pipeline_size": 8,
                "urlseed_wait_retry": 3,
                "urlseed_timeout": 3,
                "recv_socket_buffer_size": 5 * 1024 * 1024,
                # "urlseed_max_request_bytes": 16 * 1024 * 1024,
                # "max_peer_recv_buffer_size": 5*1024*1024,
                # "request_queue_time": 8,
                "file_pool_size": 50,
                "hashing_threads": 3,
            }
```

I don’t know which indicators（CPU and I/O ?） need my attention and which setting param needs to change to speed up

**Comment by richardweiu** [comment]
and Unstable and fluctuating

The time-consuming difference can reach two or three times in the same environment and download the same file

**Comment by arvidn** [comment]
You probably need to understand why it's slow first. Maybe you can look at your web server's log, or you can enable more logging in libtorrent (the `alert_mask` setting) to see if you find any hints there. Sometimes web servers have a hard time with lots of small requests. For instance, if the web server doesn't support pipelining, performance is likely suffering.
