### ISSUE TITLE
Question about replacing fseeko with lseek

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#5954]
libtorrent: `master`
platform/architecture: `android 32bits`

Hi @arvidn, I'm trying to troubleshoot an issue related to large files in android. Probably this is not the only problem, but in order to compile with API-21 and `fseeko`, I need to trick the android toolchain (with a `sed`).

Is it possible to use `lseek` instead?

**Comment by arvidn** [comment]
I can't recall off the top of my head why I changed to use fseeko, but it think it was because lseek() isn't guaranteed to use off_t, sometimes causing large files issues.

If Android need to use lseek(), that's an easy fix. Do you know what the best macro to detect android is? Are there different versions that need different treatment too?

**Comment by arvidn** [comment]
after looking at this some more; the reason to use the `fopen()`-family of functions (`fclose()`, `fread()`, `fseeko()`. `fwrite()`) is that it is more portable than POSIX. Those functions are not *just* part of POSIX, but also C89.

However, I just realized that `fseeko()` is *not* part of C89, but just POSIX. So this may be a bit of a problem. Perhaps `fsetpos()` would be better.

If android has better support for the `open()`-family of functions, the simplest patch would be to just use `fileno()` and call `lseek()` on it.

**Comment by aldenml** [comment]
Thank you @arvidn, I was missing `fileno()` :)

I think I can perform some additional hack on my side and avoid changes in `libtorrent`. I already do something similar for `getifaddrs`, `freeifaddrs` and `getrandom`. The support for these file related functions in Android is all over the place (in a bad way). I will report back my results.

**Comment by arvidn** [comment]
I don't mind patching libtorrent to support android. there's already some configuration options in `config.hpp` iirc

**Comment by aldenml** [comment]
This is what I did and seems to work: https://github.com/aldenml/libtorrent4j/blob/master/swig/libtorrent.hpp#L334
```cpp
extern "C" int fseeko64(FILE* __fp, off64_t __offset, int __whence)
{
    typedef int func_t(FILE*, off64_t, int);
    static func_t* f = (func_t*) dlsym(get_libc(), "fseeko64");
    if (f != NULL)
    {
        return f(__fp, __offset, __whence);
    }
    else
    {
        int fd = fileno(__fp);
        off64_t r = lseek64(fd, __offset, __whence);
        return r != -1 ? 0 : -1;
    }
}
```

**Comment by aldenml** [comment]
btw, these are the defines related to android
```
#if defined TORRENT_ANDROID && __ANDROID_API__ < 21
```

**Comment by arvidn** [comment]
if hte `lseek()` version work, it seems simpler to just use that, no?

**Comment by arvidn** [comment]
also, is this only an issue in `RC_2_0` and later? no need to patch `RC_1_2`?

**Comment by arvidn** [comment]
is `fseeko()` available in android 21 and later?

**Comment by aldenml** [comment]
hi, I need to check again if this is the only issue. I made a comment in the PR (it's api level `24`). You are right, if `lseek` is always there (API >= `19`), better to always use it.
