### ISSUE TITLE
Python binding documented build command no longer works

### ISSUE THREAD

**Issue by petersasi** [arvidn/libtorrent#5957]
_libtorrent version (or branch):_ 1.2.12
_platform/architecture:_ Windows 10/64bit
_compiler and compiler version:_ MS Visual Studio Build Tools 16.8.4 (vcver 14.28) - latest update
_Boost version:_ 1.74
1. installed python 3.9.1 64 bit into `c:\python`
2. downloaded boost and extracted into `c:\boost`
3. `git clone https://github.com/arvidn/libtorrent -b RC_1_2 C:/libtorrent`
`BOOST_BUILD_PATH=c:\boost\tools\build`
`BOOST_ROOT=c:\boost`
Having run bootstrap.bat, it succeeds with:
```
Building Boost.Build engine
Generating Boost.Build configuration in project-config.jam for msvc...
Bootstrapping is done. To build, run:
    .\b2
```
...and so on.
The option `--bjam` as written in the documentation is no longer recognized (did work when I have built libtorrent 1.2.10 last time, with the same 1.74 boost), the setuptools vs. distutils warning of the new setup.py is also worrysome:
```
C:\libtorrent\bindings\python>python setup.py build --bjam
C:\python\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --bjam not recognized

C:\libtorrent\bindings\python>
```

Additionally I would also need to know how to add items to the b2 command line: `crypto=openssl optimization=speed lto=on lto-mode=full`
Seems it changed at this commit: https://github.com/arvidn/libtorrent/commit/b87d01292a11af2d3dad1c91dbd27bd90d04350a#diff-34cc0f25ff048b0f9e6a88e67b0860c45056874287c359c1454ae32edd8826ab
but docs were not updated with the releases on how to use it. Unfortunately it's neither straightforward now backwards compatible.

**Comment by arvidn** [comment]
in addition to fixing the documentation, I will back port something like this https://github.com/arvidn/libtorrent/pull/5948/commits/36fb0c3c2ef53bf688c806c98cf204d08c11f4b1 to RC_1_2 for the next release.

**Comment by arvidn** [comment]
does this look ok? https://github.com/arvidn/libtorrent/pull/5958

**Comment by petersasi** [comment]
> in addition to fixing the documentation, I will back port something like this [36fb0c3](https://github.com/arvidn/libtorrent/commit/36fb0c3c2ef53bf688c806c98cf204d08c11f4b1) to RC_1_2 for the next release.

In the meantime I was thinking can I just invoke this cmdline directly (filling in the `setup.py` filled variables by hand): https://github.com/arvidn/libtorrent/blob/471e772cb7038f1bf5f44c32a09eb42fbb80ee99/bindings/python/setup.py#L124
Wasn't that what `setup.py build --bjam` did anyhow?

**Comment by petersasi** [comment]
> does this look ok? #5958

Using:
`C:\deluge2\libtorrent-build>git clone https://github.com/arvidn/libtorrent -b py-pass-through-b2-args C:/libtorrent`
and
`python setup.py build_ext --b2-args="toolset=msvc-14.2 crypto=openssl optimization=speed lto=on lto-mode=full"`
The result is:
```
msvc.link.dll bin\msvc-14.2\rls\adrs-mdl-64\crypt-opnsl\lto-on-fl\pythn-3.9\thrd-mlt\libtorrent.cp39-win_amd64.pyd
   Creating library bin\msvc-14.2\rls\adrs-mdl-64\crypt-opnsl\lto-on-fl\pythn-3.9\thrd-mlt\libtorrent.lib and object bin\msvc-14.2\rls\adrs-mdl-64\crypt-opnsl\lto-on-fl\pythn-3.9\thrd-mlt\libtorrent.exp
Generating code
Finished generating code
common.copy C:\libtorrent\bindings\python\build\lib.win-amd64-3.9\libtorrent.cp39-win_amd64.pyd
bin\msvc-14.2\rls\adrs-mdl-64\crypt-opnsl\lto-on-fl\pythn-3.9\thrd-mlt\libtorrent.cp39-win_amd64.pyd
        1 file(s) copied.
...updated 244 targets...
```
So it definitelly builds (y) :)
Did not have time this morning to test functionally as well, but looks good!

Still has several of these warnings that I promised to make go away with a PR defining the right phrase, just never was high-enough prio - guessing the same for you: :)
```
C:\boost\boost/bind.hpp(41): note: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
compile-c-c++ C:\boost\bin.v2\libs\python\build\msvc-14.2\rls\adrs-mdl-64\crypt-opnsl\lnk-sttc\lto-on-fl\pythn-3.9\thrd-mlt\object\inheritance.obj
inheritance.cpp
C:\boost\boost/detail/iterator.hpp(13): note: This header is deprecated. Use <iterator> instead.
```
I am not sure I have mentioned the `<iterator>` one before.

**Comment by arvidn** [comment]
> Wasn't that what setup.py build --bjam did anyhow?

Yes. It also placed the python module in the right place for distutils to create a package.

**Comment by petersasi** [comment]
> > Wasn't that what setup.py build --bjam did anyhow?
> Yes. It also placed the python module in the right place for distutils to create a package.

Yeah, maybe it would be more elegant of me to `bdist_wheel` (on the same command line after `build_ext`) and then just pip that wheel in the `pip install git+https://github.com/deluge-torrent/deluge` instead of hand-placing the `libtorrent.pyd` in the `c:\program files\deluge` folders.

Less of a hack, uses more disk - can't see any really important pros and cons.

**Comment by petersasi** [comment]
Hi, just built LT with boost 1.75 as I saw that actually includes some fixes / reverts in ASIO that may have a performance impact:
`python setup.py build_ext --b2-args="libtorrent-link=static boost-link=static variant=release toolset=msvc-14.2 crypto=openssl optimization=speed lto=on lto-mode=full"` (sample command line)
Then built deluge torrent then deluge installer, installed it on another box, deluge-daemon and deluge-web works, both downloading and seeding, so I believe this fix is good.
I am still struggling why deluge-gtk started failing to start requiring win32, but that is probably a python 3.9.1 or some wheel or deluge itself problem, unrelated to libtorrrent. 😅
