### ISSUE TITLE
Question: Ready recipe for decentralized file storage?

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#5959]
@arvidn For example: I have 1000 torrent clients.
These clients want to have a shared directory of files.
Each client can add and remove files (only his own). Each client is willing to keep a copy of this directory on his computer.
I have already figured out approximately how to do this with putDHT and getDHT. 

But I would like to hear your version. What do you think about it?
Perhaps there are ready-made solutions?

Ipfs, OrbitDB, blockchain - no need to suggest.

**Comment by arvidn** [comment]
I'm not familiar with an existing system like that built on bittorrent. I experimented with something along those lines in uTorrent many years ago. One feature that came out of that was the ability to distribute encrypted torrents, where a client that has the secret key decrypts/encrypts at the disk layer, so it's stored in plain text. Any client that doesn't have a key will simply download, and seed, a torrent of garbled data.

**Comment by master255** [comment]
@arvidn Ok. I think you need to develop torrents in that direction.
I'll write if I was able to do it with put and get.

**Comment by master255** [comment]
@arvidn Good news. I have developed an algorithm for a decentralized torrent storage.
I wrote this algorithm. It already works!
I don't understand why no one uses it yet.

**Comment by master255** [comment]
@arvidn The release of decentralized storage is ready in version 8.0 of my player!
We may not know such systems, but they exist.
My player now uses this system to store shared playlists.
I even added an administration screen that I can use to block users or forcibly delete their files.

I rate the complexity of the system as medium. For example, it is easier than multi-threaded streaming, which has 3D logic.

**Comment by master255** [comment]
@arvidn @markmdscott @aldenml @gubatron @glassez @proninyaroslav
I published an article on how to make a decentralized Torrent storage or even a decentralized database.
In two languages:
[ENG](https://habr.com/ru/post/546612/)
[RU](https://habr.com/ru/post/546354/)

I remind that everything written in the article really works and already used in [my player](https://play.google.com/store/apps/details?id=com.media.library) for a long time. For publishing playlists.
But it can be used to create billing systems, Torrent Index, slow sites, modifiable torrents, to create a shared cloud storage of any files with the ability to specify quotas and speed limits and much more...

**Comment by master255** [comment]
@arvidn @markmdscott @aldenml @gubatron @glassez @proninyaroslav
I invented two more scenarios to use DHT. Updated the articles. Read them again. Added variant 2 and 3. It's beautiful, but I don't have time to develop it.

**Comment by gubatron** [comment]
@master255 have you used Resilio (Formerly known as BTSync)? I wonder if you were inspired by it.

I've certainly thought of several scenarios on how to create something inspired by Resilio where you'd have a public directory of folder public keys. I imagine cryptographic tools today could allow for deriving shared private keys so you can add/remove content managers.

If one can create one level of abstraction above the inner workings of DHT put/get and create protocols based on canonical folder structures you could do even a distributed torrent search index and do away with torrent search indexing websites.

The problem that I have with this design is always spam. Which then I go on to think about distributed reputation, and instead of one giant index, have instead a bunch of DHT-based RSS-like feeds that can be used by the clients to create local torrent databases. You solve spam by following the more reputable DHT-based RSS feeds.

**Comment by master255** [comment]
@gubatron 

> have you used Resilio (Formerly known as BTSync)?

No. Of course I've never used this program and didn't even know it existed.

> If one can create one level of abstraction above the inner workings of DHT put/get and create protocols based on canonical folder structures you could do even a distributed torrent search index and do away with torrent search indexing websites.

For almost a year now, my player has had a shared playlist system. In fact, it is a torrent index. The work of this system is based on a decentralized database that works with DHT and torrents. It can be hacked, but it is quite difficult (you need to disassemble the program and find the private key in it) and will not damage the database.
Since it is a distributed database, it has, even access rights. I have an administrative control panel for this system. I can block users by id.

In the article above I described scenarios to use DHT which cannot be hacked. As in blockchain there appear two types of node. Users - who use the decentralized database, and managers - who handle changes in the database. From this you get a managed but decentralized database. This can be used for anything. For a torrent index, for billing, for distributed file storage, for a decentralized Internet.

If you have time for that, I can suggest answers to all the questions about creating such a system. I don't have time to program it. Besides in my country (Russia) DHT via 4G is blocked. And without that there is no point in programming anything. No one will be able to use it.

**Comment by master255** [comment]
I invented a new kind of decentralized database. This is DHT over DHT. Right now there is no time to describe it. But there is nothing complicated there. It just needs bootstrap nodes.

**Comment by master255** [comment]
@arvidn @markmdscott @aldenml @gubatron @glassez @proninyaroslav The world's first DHT over DHT application. [DHT Market](https://t.me/media_library/12913)

**Comment by master255** [comment]
Market already supports publishing editable torrents, torrent files, apk links to mega.nz, Apk files.
