### ISSUE TITLE
Does this compile on FreeBSD 10?

### ISSUE THREAD

**Issue by manasb** [arvidn/libtorrent#596]
Just wondering if anyone had any specific instructions. I'm actually trying to run Hadouken on FreeBSD 10 - https://github.com/hadouken/hadouken

**Comment by manasb** [comment]
I think I should just use the port - net-p2p/libtorrent-rasterbar

**Comment by arvidn** [comment]
If libtorrent is failing to build, I would love to hear about it! (especially the RC_1_1 branch)
