### ISSUE TITLE
Question about TORRENT_HAS_FALLOCATE logic

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#5971]
libtorrent: `RC_2_0`

Looking at the code here https://github.com/arvidn/libtorrent/blob/RC_2_0/src/mmap.cpp#L353
```cpp
...
// if fallocate failed, we have to use posix_fallocate
// which can be painfully slow
// if you get a compile error here, you might want to
// define TORRENT_HAS_FALLOCATE to 0.
int const ret = posix_fallocate(m_fd, 0, size);
...
```
I don't see in the code that `fallocate` is called or used. Sorry if I'm missing something obvious.

**Comment by arvidn** [comment]
that comment hasn't been updated it seems. It used to be the case that I first tried to call the linux specific `fallocate()` and then fall back to `posix_fallocate()`.

**Comment by aldenml** [comment]
Changing it with https://github.com/arvidn/libtorrent/pull/5978
