### ISSUE TITLE
Issue with the use of operation_t::file_fallocate right after open_file

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#5972]
libtorrent: `RC_2_0`

Hi @arvidn, I see similar code here
https://github.com/arvidn/libtorrent/blob/RC_2_0/src/posix_storage.cpp#L517
```cpp
file_pointer f = open_file(file_index, aux::open_mode::write, 0, ec);
if (ec)
{
	ec.file(file_index);
	ec.operation = operation_t::file_fallocate;
	return;
}
```
and here
https://github.com/arvidn/libtorrent/blob/RC_2_0/src/mmap_storage.cpp#L361
```cpp
auto f = open_file(sett, file_index, aux::open_mode::write
	| aux::open_mode::random_access | aux::open_mode::truncate, ec);
if (ec)
{
	ec.file(file_index);
	ec.operation = operation_t::file_fallocate;
	return;
}
```
If I read correctly, this hides the internal "operation" that was actually the problem. Is this right? am I missing some reasoning behind this?

**Comment by arvidn** [comment]
yeah, that doesn't seem right. I suppose I was thinking that the only reason to open and truncate those empty files was to allocate them, that should be part of the error message. But you're right that it does obfuscate the true operation that failed, which isn't good.

**Comment by arvidn** [comment]
there's also an issue right now that the if the actual call to `posix_fallocate()` fails, it's attributed to "open".

**Comment by aldenml** [comment]
renaming this to "issue"

**Comment by arvidn** [comment]
@aldenml does this look reasonable to you? https://github.com/arvidn/libtorrent/pull/5979

**Comment by aldenml** [comment]
based on my code understanding, yes (closing this since you have the PR now)
