### ISSUE TITLE
no python conversion for libtorrent::event_t

### ISSUE THREAD

**Issue by DjLegolas** [arvidn/libtorrent#5977]
libtorrent version (or branch): RC_2_0, version 2.0.2

platform/architecture: Windows 10, x64

compiler and compiler version: boost 1.75.0

Using Python binding, there seem to be an issue with the `libtorrent::event_t` enum.
When running on version 1.2.5, I can see in `Deluge` the correct `int` value (for example, `2`, which means `Started`).
But after building again against laterst RC_2_0 (d9f4ad79), I started getting the following exception:
`[Failure instance: Traceback: <class 'TypeError'>: No to_python (by-value) converter found for C++ type: enum libtorrent::event_t
`

The error happens when `Deluge` is copying the entire content of the alert (except `__` functions) and passes the copy to it's handler:
https://github.com/deluge-torrent/deluge/blob/092d07b68e48fb8480cb068bc6558ba3b269fb95/deluge/core/alertmanager.py#L139

There need to be an explicit conversion to `int`.

**Comment by arvidn** [comment]
there's also been some confusion about whether `event_t` is internal or public in libtorrent. I think it used to be internal, but not anymore. That's probably why I missed exposing it to python as well.

**Comment by arvidn** [comment]
does this fix it? https://github.com/arvidn/libtorrent/pull/5982

**Comment by DjLegolas** [comment]
Seem as it fixed it:
![image](https://user-images.githubusercontent.com/6710676/108094070-16c77b80-7087-11eb-806f-aa1b22b89960.png)

But, it will break the backwards compatibility as the previous value was `int`.
Just let me know if it is something you don't mind so I'll try to patch `deluge` itself to support this.

**Comment by arvidn** [comment]
I would prefer to use the stronger type. It's simple to add (deprecated) support for converting a number to `event_t`, but there's no existing logic for the opposite conversion

**Comment by arvidn** [comment]
I've force-pushed an update to the PR

**Comment by DjLegolas** [comment]
Looks good
