### ISSUE TITLE
Two passive/firewalled peers with closed port can NOT upload each to other in closed torrent without PEX?

### ISSUE THREAD

**Issue by vj000** [arvidn/libtorrent#5981]
Hello,

i was wondering what is the probability of two peers that are passive/firewalled(not opened/forwarded/mapped port) to connect and upload data each to other during leeching.

And if the "closed" kind of .torrent (which has DHT and PEX disabled) means no or too low probability of these two to have data transfer each to other and when DHT an PEX enabled (in "open" kind of .torrent), how much this improves the probability. And is it thanks to a PEX or thank to a DHT that firewalled/NATed? peers started being able to transfer the data each other?

Some [research on this topic and initial unanswered question is there](https://filesharingtalk.com/threads/474046-2-passive-peers-connect-over-DHT-(open-port-not-needed-no-advantage)).

Thank You

**Comment by arvidn** [comment]
without PEX and DHT there is no chance for the peers to connect, as far as I can tell. In both cases, only uTP can hole-punch, so that has to be enabled on both sides too.

PEX can be used by a 3rd peer to introduce two NATed peers to each other, and with some luck holepunch.

the DHT typically use the same UDP socket (and hence port) as uTP, and the listen port can be implied in DHT announces, which means you can find a NATed peer in the DHT, and find its external port it contacted the DHT node from. With some luck (i.e. the NAT being p2p-friendly) the NATed peer can be reached on that UDP port. This only works with uTP as well, since it's sitting on top of the same UDP socket.

**Comment by vj000** [comment]
So it can be currently said that when creating the .torrent as open (DHT, PEX enabled), then it helps connect more peers (get data faster) thanks to mainly increased possibility passive peers will interconnect via uTP? (i think at least half of the peers are passive)

I think it depends on many factors, but in general, what is your current estimate probability that the two passive peers on open torrent connect and transfer data each other thanks to uTP?
like 30% or rather 60%

(This connection per my understanding is made possible thanks to uTP and PEX enabled - in open torrent on both sides if also other conditions on both sides are right, like router software being p2p friendly - i am guessing people should look on router feature called maybe NAT Traversal/UDP hole punching - i would guess most modern routers has it)

**Comment by arvidn** [comment]
> So it can be currently said that when creating the .torrent as open (DHT, PEX enabled), then it helps connect more peers (get data faster) thanks to mainly increased possibility passive peers will interconnect via uTP?

Yes, I think that's safe to assume. Of course, disregarding any selection bias of where the fast peers are.

> I think it depends on many factors, but in general, what is your current estimate probability that the two passive peers on open torrent connect and transfer data each other thanks to uTP?

I don't want to speculate. I think it primarily depends on the NAT implementations in the most popular home routers. It should be measured. Routers that also consider themselves light-weight firewalls are typically less friendly to p2p, whereas routers that try to make the NAT as transparent as possible are more friendly.

NAT implementations used to be categorized in these 4 categories, where Full Cone is the most p2p friendly and easiest to hole punch through. But I think NATs these days have more complex behaviors and may not fit neatly in one category.

https://tools.ietf.org/html/rfc3489#section-5
