### ISSUE TITLE
Python bindings: info_hash_t: hash should be stable

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [arvidn/libtorrent#5987]
The following snippet should work:

```python
sha1 = lt.sha1_hash(b"a" * 20)
ih = lt.info_hash_t(sha1)
assert hash(ih) == hash(lt.info_hash_t(sha1))
```

I believe we just need to define `__hash__` on `info_hash_t`

**Comment by arvidn** [comment]
what does the default `__hash__` do? does it hash the pointers?
if so, presumably the same argument could be made for all libtorrent types, including `sha1_hash` and `sha256_hash`

**Comment by AllSeeingEyeTolledEweSew** [comment]
I think `sha1_hash` already does this; comparing `hash(sha1_hash(...))` seems to work already.

`sha256_hash` doesn't seem to be mapped in python right now, but yes, same goes for that.

I forgot to mention it, but the real use case here is to be able to use `info_hash_t` as a key for a `dict`, or in a `set`. This depends on stable `__hash__` (I haven't found another use case for `__hash__` actually)

**Comment by AllSeeingEyeTolledEweSew** [comment]
Looks like this is fixed in `master`
