### ISSUE TITLE
Python bindings: we should deprecate session.add_torrent(dict) and parse_magnet_uri_dict

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [arvidn/libtorrent#5992]
This is a debatable topic, but it should be brought up.

IMO, the `dict` versions of these functions don't provide enough value to offset the gap in support relative to the versions which accept and return `add_torrent_params`.

The support gap is fairly significant, and has endured for a while. The `dict` functions just don't support everything supported by their first-party `add_torrent_params` equivalents. We could fix them such that they have equivalent support, but if we haven't kept them equivalent up to now, it's not clear we will in the future.

I don't believe that working with `dict` makes these functions more pythonic, readable or useful. There might be an argument if `session.add_torrent()` took *keyword args* instead of a `dict` arg, but that's not what we have.

Moreover, a kwargs pattern like `session.add_torrent(info_hash=..., save_path=...)` would only help readability / pythonic-ness for *ad-hoc calls* which specify a small, fixed set of args. If the caller has more than a few lines of code to decide *which args to pass*, then it makes more sense to have that code just configure an `add_torrent_params` anyway. Any featureful python program will need to do this. I can only imagine a kwargs pattern being useful in single-purpose, ad-hoc scripts.

Our usage of `dict` doesn't appear to be useful for making the data portable, e.g. converting to/from JSON. The values still need to be converted to libtorrent's types, such as `storage_mode_t`.

The only advantage of `dict` I can think of is that it's straightforward to enumerate its elements, versus enumerating the attributes of an object (`dir(add_torrent_params())` is awkward in practice). For this case, it's straightforward (and probably more robust) to enumerate the elements of `write_resume_data(add_torrent_params())`.

**Comment by arvidn** [comment]
I think I agree
