### ISSUE TITLE
GitHub Action build system removes support for Boost

### ISSUE THREAD

**Issue by DjLegolas** [arvidn/libtorrent#5999]
According to an announcement from GitHub, Boost library will be removed from the build system for `Ubuntu` and `Windows`.

This will break the CI of `libtorrent` all together.

Ref:
https://github.com/actions/virtual-environments/issues/2667

**Comment by arvidn** [comment]
I believe it's only the windows build that depend on boost shipped with the machine image. MacOS and Linux use `brew` and `apt` respectively to install boost

**Comment by DjLegolas** [comment]
As I build `libtorrent` manually only on Windows, I wasn't aware of the usage of `brew` and `apt`.
Never the less, there will be a need to update the config file for Windows. Maybe start using `Chocolatey` package manager for windows which is installed?
https://chocolatey.org/packages?q=boost

**Comment by arvidn** [comment]
this has been addressed now
