### ISSUE TITLE
RC_1_0 doesn't build

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#60]
This is from the qbt travis ci, since we pull and build RC_1_0 on each of our travis builds.

It errors out with
```
lazy_bdecode.cpp: In function ‘int libtorrent::lazy_bdecode(const char*, const char*, libtorrent::lazy_entry&, boost::system::error_code&, int*, int, int)’:

lazy_bdecode.cpp:132:28: error: expected primary-expression before ‘do’

lazy_bdecode.cpp:132:28: error: expected ‘;’ before ‘do’
```

Link to travis log line: https://travis-ci.org/qbittorrent/qBittorrent/jobs/73618576#L771

PS: You should enable travis for the RC_1_0 branch too. Not only the master branch.

**Comment by arvidn** [comment]
I believe this is fixed now, right?

**Comment by sledgehammer999** [comment]
Yes now travis seems to work fine on our repo.
