### ISSUE TITLE
torrent_handle::need_save_resume_data() doesn't reflect all the changes

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#6009]
There are some kind of changed data that aren't reflected by `torrent_handle::need_save_resume_data()` which makes it useless and forces you to either save the data for all torrents unconditionally, or try to track the changes manually.
Examples:
1. Some kind of changed flags: disable_dht, disable_pex, disable_lsd etc.
2. Renamed files

This probably doesn't cause problems for active torrents, because there's often some other data being updated that sets `need_save_resume_data`. But users really want to change the properties of "paused" torrents from time to time.

**Comment by arvidn** [comment]
does this look good? https://github.com/arvidn/libtorrent/pull/6015

**Comment by glassez** [comment]
> does this look good? #6015

I need to check the rest of the cases. Will report it here.

**Comment by glassez** [comment]
> > does this look good? #6015
> 
> I need to check the rest of the cases. Will report it here.

add_tracker() is possible affected.

**Comment by arvidn** [comment]
yeah, it looks like it.

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/6027
