### ISSUE TITLE
No registered converter 

### ISSUE THREAD

**Issue by flourishing** [arvidn/libtorrent#601]
i have compiled lib torrent  with python bindings. 
there are no errors during compile.
and i run python and import lib torrent  works too.
but i try to run code handle = session.add _torrent(params)
throw a error 
TypeError: No registered converter was able to produce a C++ rvalue of type bytes from this Python object of type sha1_hash
how to fix this ?
i build it on vps of linode ubuntu 64bit 14.04 lts

**Comment by arvidn** [comment]
which version of libtorrent are you building?
which version of python are you using?
which build command did you use to build libtorrent?
there is a test that runs on travis' linux that should exercise this path, here: https://github.com/arvidn/libtorrent/blob/RC_1_0/bindings/python/test.py

**Comment by lawnmowerwcd** [comment]
The `info_hash` parameter of `add_torrent` takes a `bytes` object in the python binding. You can call the `to_bytes()` method on your `sha1_hash` object to convert it to a bytes sequence.

Supplying the parameters you use to call the method is inherently useful.

**Comment by arvidn** [comment]
@flourishing what's the type of "params" in your python statement?

**Comment by Falcosc** [comment]
@flourishing do you still have this issue? Because the python tests are running without any problems.
