### ISSUE TITLE
ERROR: (75 Value too big for defined data type) on 32 bit Sony Android TV

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6012]
@arvidn libtorrent version (or branch): 2.0

platform/architecture: Android/ ARM 32 bit

I tested the 32 bit arm version of the library on my Sony Android TV 8.0, Api 26, kd-43xf8599.
How does the file download process:
1) The download starts with the first piece
2) The first 10 pieces are downloaded
3) The last (500) piece is requested
4) Error:
```
2021-02-22 16:13:38.328 13116-13205 D/222222: FILE_ERROR
2021-02-22 16:13:38.328 13116-13205 d/222222: Walker.S01E05.1080p.rus.LostFilm.TV.mkv file_seek (/storage/emulated/0/MediaLibrary/Walker.S01E05.1080p.rus.LostFilm.TV.mkv-ml) error: Value too big for defined data type
2021-02-22 16:13:38.328 13116-13205 D/222222: TORRENT_ERROR
2021-02-22 16:13:38.328 13116-13205 D/222222: Walker.S01E05.1080p.rus.LostFilm.TV.mkv ERROR: (75 Value too big for defined data type) /storage/emulated/0/MediaLibrary/Walker.S01E05.1080p.rus.LostFilm.TV.mkv-ml
```

To query the last piece I use:
```
torrentHandle.clearPieceDeadlines();
torrentHandle.setSequentialStart(start);

.... torrentHandle.setPieceDeadline(i, deadline);....
```
The 1.2.12 version of the library never had such errors.

**Comment by master255** [comment]
@arvidn We don't have any other 32-bit Android devices. Only Android TV. And more to say. I don't think anyone uses the x86 architecture.
That means that all 32-bit modern devices are Android TV.

**Comment by master255** [comment]
@arvidn I just tested it. The error is repeated on the x86 Android emulator. And on a regular phone emulator, not Android TV.

**Comment by arvidn** [comment]
You're using head of `RC_2_0`, right? Which includes this patch, https://github.com/arvidn/libtorrent/pull/5960

**Comment by aldenml** [comment]
@arvidn I feel that I need to provide more context here. As far as I know, he is testing with `libtorrent4j` which internally uses a fork (based on `master`) of `libtorrent`. The workarounds are included, but right now, strictly speaking, it's not `RC_2_0` nor `master`.

Now, on top of that, he is applying a patch with some extra logic that I'm not familiar with: https://github.com/aldenml/libtorrent/commit/b9f0a8b5340d69e1d27e3be15788bf53c3e09dc2#diff-a89056030f3238ae74c7df3ac374c016fdcca37a13c9c712989974888ab0d558R2125)

I'm trying to reproduce the issue, but I think at this moment there is not enough information on the root of the problem to begin with.

**Comment by master255** [comment]
@arvidn aldenml was able to reproduce the bug on the x86 emulator Android 8.0. Now we are waiting for him. You can help him with the bug solution.

**Comment by master255** [comment]
@arvidn Okay. The bug is finally fixed. Thanks to Aldenml!

**Comment by arvidn** [comment]
what was it?

**Comment by aldenml** [comment]
This was the solution https://github.com/arvidn/libtorrent/pull/6014

I wonder if they are even testing LFS in Android 32 bits?
