### ISSUE TITLE
Python bindings fail to build: relocation R_X86_64_PC32 cannot be used against symbol __stack_chk_guard; recompile with -fPIC

### ISSUE THREAD

**Issue by yurivict** [arvidn/libtorrent#6019]
It uses static Boost Python libraries and fails:
```
ld: error: can't create dynamic relocation R_X86_64_32S against local symbol in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
>>> defined in /usr/local/lib/libboost_python37.a(list.o)
>>> referenced by list.cpp
>>>               list.o:(boost::python::detail::list_base::extend(boost::python::api::object const&)) in archive /usr/local/lib/libboost_python37.a
```

Build should always use shared libraries when they are available.

**Comment by arvidn** [comment]
The default boost linking is static, I believe this makes sense when building a self-contained python module independent of system packages (say, windows). I think it probably only works when building boost from source, so we can still force `-fPIC` too.

@yurivict you can fix this with `--boost-link=shared` (I think).

@AllSeeingEyeTolledEweSew Do you think it makes sense to change the default for `boost-link` in `setup.py` to link shared when *not* building boost from source (i.e. if `BOOST_ROOT` is not set)

**Comment by yurivict** [comment]
With ```--boost-link=shared```, thank you.

I think that you should make ```boost-link=shared``` a default when using the external boost package, because static libraries generally can't be used to build a shared object , in this case Python's module.

**Comment by AllSeeingEyeTolledEweSew** [comment]
Hm. So if I understand correctly, `boost-link=static` requires boost compiled with `-fPIC`, but when installed as a system library it usually doesn't have `-fPIC`?

Then, I guess whatever default of `boost-link=` we choose will be wrong for some set of people, and we don't have a reliable way to detect the right thing to do. That sucks. (Grumble grumble, boost's ignorance of the python ecosystem bites me again, grumble)

I understand the rationale, but I'm not a huge fan of changing the default based on `BOOST_ROOT` being set. The intent is too far away from the action. It's too surprising to anyone diagnosing build issues. Our goal is that `setup.py build_ext --config-mode=distutils` behaves "like distutils", and distutils has no intelligence about `-fPIC`, so I think we should be dumb as well.

My hope is that most people building the python bindings from source would just install from pypi if it were available (@yurivict, thoughts?). Once we publish there, users will only build from source for unreleased fixes/features, so we shouldn't pay high costs to streamline building from source right now.

What if we print a warning from `setup.py`, if `--config-mode=distutils` and `BOOST_ROOT` is unset, saying that the user may want `--b2-args=boost-link=shared`?

**Comment by arvidn** [comment]
The way windows does relocations also means it doesn't really have a counterpart to `-fPIC`, so on windows it's always safe to link a shared library against a static library. So, building boost from source isn't a perfect match for the cases where `boost-link=static` would work.

An alternative to looking at `BOOST_ROOT` could be to have different defaults for windows, where linking statically is default on windows and shared otherwise.

**Comment by AllSeeingEyeTolledEweSew** [comment]
I don't think I can be convinced that an intelligent default here is a good idea. I still expect that shared linking will only be used in the long run by distro build scripts, which don't need the help of defaults.
