### ISSUE TITLE
question : dht_get_peers python binding?

### ISSUE THREAD

**Issue by ardhipoetra** [arvidn/libtorrent#602]
Is there any way to do `get_peers` query explicitly in python binding? I saw `dht_get_peers` definition in `bindings/python/src/session.cpp` that (maybe) call `dht_get_peers` in `session_impl`.

Is this function can be called from session object? how to expose it so I can call it (from where doesn't matter). To be honest I can't understand how the binding works. The way it's defined is the same as `is_dht_running` (picked up as example), but it just won't work.

Thanks!

**Comment by aldenml** [comment]
I think you should be able to call this function the same way as others, this method is async and the corresponding alert is `dht_get_peers_reply_alert`

**Comment by ardhipoetra** [comment]
Unfortunately, it seems not the case. I run the program below and it shows `dht_get_peers` is not available in python binding.

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import libtorrent as lt
>>> lt.version
'1.0.9.0'
>>> s = lt.session()
>>> s.start_dht()
>>> s.dht_get_peers()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'session' object has no attribute 'dht_get_peers'
>>> s.is_dht_running()
True
>>> 
```

**Comment by aldenml** [comment]
I see your version is 1.0.9.0, this is for version >= 1.1.0, branch RC_1_1 or master.

**Comment by ardhipoetra** [comment]
will take a look for that, thanks!

**Comment by ardhipoetra** [comment]
That's weird, I can't get any `alerts` you mentioned. Full code in (here)[https://gist.github.com/ardhipoetra/e9ab3a94cf576c0208fcdca97560619b], but my step is : 

```
import libtorrent as lt
import time

infohash_str = "5aec5ee9f2d044316fe1de29d221452103ceb958"
ses = lt.session()
ses.start_dht()
ses.add_dht_router('router.bittorrent.com', 6881)
ses.add_dht_router('router.utorrent.com', 6881)
ses.add_dht_router('router.bitcomet.com', 6881)

ihash_sh1 = lt.sha1_hash(infohash_str)

ses.dht_get_peers(ihash_sh1)

stopped = False
count = 0
while(not stopped):
    al = ses.pop_alerts()

    if not len(al):
        time.sleep(5)

        # furiously ask for peers!
        ses.dht_get_peers(ihash_sh1)
    else:
        for a in al:
            print a
            count += 1

        time.sleep(1)

    # we've seen enough
    if count >= 30:
        stopped = True
```

What do you think?

**Comment by aldenml** [comment]
Well, I don't have the environment to test with python, but I just coded a java unit test (see https://github.com/frostwire/frostwire-jlibtorrent/blob/libtorrent-RC_1_1/src/test/java/com/frostwire/jlibtorrent/DhtGetPeersTest.java) and it works.

Try to get alerts related to DHT stats to see if indeed you are populating your DHT tables

**Comment by ardhipoetra** [comment]
I know it, I have to put `alert mask` in session settings before I can get the alerts. Updated my (gist)[https://gist.github.com/ardhipoetra/e9ab3a94cf576c0208fcdca97560619b].

Next problem is (probably specific to python binding) : 

- it doesn't have type/alert category `dht_notification`, `dht_operation_notification` (or maybe it's just me who missed it). Filtering with raw value seems work though. 

- alert retrieved from `dht_notification` still in `alert` type. Therefore, I can't call `peers` and `num_peers` function.

**Comment by aldenml** [comment]
Yes, a lot missing, working in a PR to add support for `dht_get_peers_reply_alert`.

**Comment by aldenml** [comment]
Ok, it's merged https://github.com/arvidn/libtorrent/pull/608, give it a try

**Comment by arvidn** [comment]
Does that PR cover all issues raised in here?

**Comment by ardhipoetra** [comment]
I still can't call `peers()`, and `num_peers` act as a attribute instead of function.

It does have _type_ which is `libtorrent.dht_get_peers_reply_alert` though

**Comment by aldenml** [comment]
Does it make a difference if they are a function or a property for you? I added both as properties following other alerts as example. Are you able to see them in the properties of the Python object?

**Comment by arvidn** [comment]
I think it would make sense for them to be functions, to map 1:1 to C++ (the fewer differences between the C++ and python API, the less important it is to have separate documentation for the python bindings)

**Comment by aldenml** [comment]
Well, I was thinking about this (API design wise). I agree with the documentation point, but I perceive that one reason to have `num_peers()` as a method, is the lack of convenient read-only property definition in C++ (the version in use) and the reason for `peers(std::vector<tcp::endpoint>& peers)` is mainly performance, since it involves deserialization of addresses (done only on demand). It seems to me more natural to have them mapped as properties in python (same for other languages).

Of course, this is completely subjective and I don't mind looking for the 1:1 map if you think otherwise.

**Comment by arvidn** [comment]
actually, when I looked at this earlier today, I realized that peers() really should return the vector. At some point I'll deprecate this one and add an overload that does that.

**Comment by arvidn** [comment]
@ardhipoetra could you give this a try? https://github.com/arvidn/libtorrent/pull/617

**Comment by arvidn** [comment]
#617 was merged

**Comment by ardhipoetra** [comment]
Sorry for the late response. I can confirm that the new patch fix this issue. 

However, talking about performance, it's very hard to get peer reply on the request. 

In approximately 30 minute with several swarms, I just get 1 reply of the `get_peers` request. Is there something wrong with my [code](https://gist.github.com/ardhipoetra/e9ab3a94cf576c0208fcdca97560619b)?

**Comment by aldenml** [comment]
Hi @arvidn, where do you like a possible PR to deprecate the current `peers` signature, RC_1_1 or master?

@ardhipoetra have you tried a very popular hash, like the one from a recent ubuntu distribution?

**Comment by ardhipoetra** [comment]
@aldenml, yes I have. I've tried some from linuxtracker and other common torrent sharing site. I picked up with > 1500 seeder and > 500 leecher

**Comment by aldenml** [comment]
I can't give you an ETA, but I will try to setup my python environment. In my java tests I get peers in less than 5 seconds.

**Comment by arvidn** [comment]
@aldenml RC_1_1 would be great

**Comment by Ueland** [comment]
Did you get around to check it @aldenml? i have tested the code mentioned in this thread and it does indeed appears that there never comes any replies to get_peers requests.

**Comment by Ueland** [comment]
Did you get around to check the missing replies @aldenml , i did some quick testing on the code mentioned in this thread it appears that more or less no replies comes back. (ports are open etc)

**Comment by aldenml** [comment]
@Ueland this issue is very old, but I just tested again and I have no problems. Do you have a minimal code to look at it. Async calls and polling alerts can be a little tricky.

**Comment by Ueland** [comment]
@aldenml Sorry about that, but since the isue was discussed here i took a chance to ask here, let me know if i should move to a new issue :)

I have updated OPs gist with a new popular hash for a Ubuntu release:
https://gist.github.com/Ueland/934e87898b362c474f1a7f5cf23d29d9

There appears to be a couple of thousand peers for that hash.

I let it run for 2-3 minutes, in that time it sent 327 outgoing get_peers, and it recieved 10 back for that hash.

**Comment by aldenml** [comment]
@Ueland is this running with `1.1`? because I only test (and deal with)`master` for a while now

**Comment by Ueland** [comment]
@aldenml version : 1.1.6.0 to be correct. Is there any specific branch i should try and build to check?

**Comment by aldenml** [comment]
try `master` and let me know, my tests are in java

**Comment by Ueland** [comment]
Ran it for two minutes now, the results are:
version : 1.2.0.0

**Comment by Ueland** [comment]
Ran it for two minutes now, the results are after two minutes 10s:
version : 1.2.0.0
outgoing dht get_peers: 291 times
incoming dht get_peers: 34 times
incoming dht announce:: 2 times

Of the 34 incoming dht get_peers, 20 was for the same hash that i requested, could it be that the messages that should be dht_get_peers_reply_alert are treaded as an incomin dht get_peers?

**Comment by aldenml** [comment]
strange, I get the `dht_get_peers_reply_alert` like immediately in my java app. That `# furiously ask for peers!` comment in your code does not inspire me confidence. I will try to code something in python to verify.

**Comment by Ueland** [comment]
I see, can i see the java test code somewhere? To see if i can figure it out :)

**Comment by aldenml** [comment]
I use this tool: https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/test/java/com/frostwire/jlibtorrent/demo/DhtShell.java
