### ISSUE TITLE
Bug: Impossible to create a torrent

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6021]
@arvidn @aldenml libtorrent version (or branch): 2.0

platform/architecture: Android

I have a problem.
These lines give an error
byte[] result = builder.generate().entry().bencode();
TorrentInfo torrentInfo = new TorrentInfo(result);

error:
    java.lang.IllegalArgumentException: Can't decode data: the v1 and v2 file metadata does not match
        at org.libtorrent4j.TorrentInfo.bdecode0(TorrentInfo.java:674)
        at org.libtorrent4j.TorrentInfo.<init>(TorrentInfo.java:46)

So what to do? I need to get torrentInfo from byte[]

Okay, looks like I'm the main tester of torrents 2.0.

**Comment by arvidn** [comment]
you have to reveal more code. what is `builder`? it looks like a `create_torrent` object.
What do you do with it before you try to generate the torrent?
You're clearly creating a hybrid (v1 and v2) torrent, but are you setting both v1 and v2 piece hashes?
If you would use the high level `set_piece_hashes()` function, that would be taken care of for you. Perhaps you're setting the hashes yourself, directly. In that case you'd have to set v2 hashes as well.

Or you could pass in the `v1_only` flag.

Did you look at the example for creating torrents?

https://github.com/arvidn/libtorrent/blob/RC_2_0/examples/make_torrent.cpp

**Comment by master255** [comment]
@arvidn I found a problem. Two new flags appeared when creating torrents. Need to use them.
