### ISSUE TITLE
Bug: Can't stop creating a torrent

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6024]
@arvidn Torrent creation is a long process and there must be a mechanism to stop it. How is this done?

I use this method: https://github.com/aldenml/libtorrent4j/blob/b28e0ce4d29c14271fa9382b7b5f95e3cfe1e37f/src/main/java/org/libtorrent4j/TorrentBuilder.java#L436

**Comment by arvidn** [comment]
do you mean how to abort the `set_piece_hashes()` function?
I would think you could throw an exception from the callback function

**Comment by master255** [comment]
@arvidn I checked. It really works. But it's a dirty method. How do I make it clean?

**Comment by master255** [comment]
@arvidn Okay. I found an acceptable way:
throw new RuntimeException(new Exception());

**Comment by master255** [comment]
@arvidn Bad news.
If I use the callback function, it takes 5 times longer to create a torrent.
I don't know what's causing it. But then I can't use callback function and therefore can't stop creation of torrents.
So this is a bug that must be fixed.

**Comment by arvidn** [comment]
please define what the issue in libtorrent is a bit more clearly

**Comment by master255** [comment]
@arvidn It turns out there are two bugs:
1. There is no mechanism to stop torrent creation. Using an error to stop is not correct.
2. Too slow to create torrent if you add callback.

**Comment by arvidn** [comment]
> There is no mechanism to stop torrent creation. Using an error to stop is not correct.

I disagree. I think it's a fairly appropriate use of an exception.

Do you have a suggestion of a different mechanism for cancelling?

> Too slow to create torrent if you add callback.

I very much doubt that this is generally true. If your callback does a lot of expensive things, sure. But the libtorrent interface does not mandate it does.

**Comment by master255** [comment]
@arvidn Adding a callback slows down the creation of a torrent. Even if the callback is empty. This is a bug.

**Comment by master255** [comment]
@arvidn 

> Do you have a suggestion of a different mechanism for cancelling?

If the callback can be used, I agree with you. But as long as it can't be used, it's not a workable way.

**Comment by arvidn** [comment]
> Adding a callback slows down the creation of a torrent. Even if the callback is empty. This is a bug.

I very much doubt that statement. can you back it up?

**Comment by master255** [comment]
@arvidn A backup of what?

**Comment by arvidn** [comment]
your statement that torrent creation slows down materially by providing a callback

**Comment by master255** [comment]
@arvidn Ok. I checked it out just now. It really took a long time to display the progress. I will work on that.

**Comment by arvidn** [comment]
it would be helpful if you would "check it" *before* posting "bug" reports.

**Comment by master255** [comment]
@arvidn I created this bug correctly. As you can see, other programmers have started to use my answer.
![image](https://user-images.githubusercontent.com/5380115/110257303-53afcf80-7fae-11eb-8590-62370578d324.png)

**Comment by arvidn** [comment]
and we have established this is not a bug

**Comment by master255** [comment]
@arvidn Dear Arvin. You are right. There is no bug. Everything is good.
