### ISSUE TITLE
Bug: wrong sha1 hash generation

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6030]
@arvidn  libtorrent version (or branch): 2.0

platform/architecture: Android

Does sha1 hash generation now depend on the device? What is happening?
[In this video I'm creating a torrent on two different devices.](https://mega.nz/file/RkMmyZaZ#ZVjDE6sjvVjI04aQRgF1u8rIRLkZXTDg48LiwK7q8pY)
The sha256 generation is device-independent, while the sha1 generation is device-dependent for some reason.
Please fix it as soon as possible.

**Comment by master255** [comment]
Arvin, admit it. Your autotests don't work.

**Comment by arvidn** [comment]
Do the tests pass despite the incorrect sha-1?

**Comment by master255** [comment]
@arvidn What tests? It's Android. It's obviously a bug.

**Comment by arvidn** [comment]
> What tests? It's Android. It's obviously a bug.

primarily the tests you don't think are working.

but really any of them. Could you be a bit more specific about what you're doing and why you expect the results to be identical?

For example, if you add files in different order in a v1 torrent, you'll get different info-hashes.

**Comment by master255** [comment]
@arvidn It worked in the 1.2 library. But it doesn't work in 2.0.
Code that creates torrents:
https://github.com/aldenml/libtorrent4j/blob/b28e0ce4d29c14271fa9382b7b5f95e3cfe1e37f/src/main/java/org/libtorrent4j/TorrentBuilder.java#L436

Everything is done by the libtorrent library. The bug is inside the library.

**Comment by arvidn** [comment]
can you post the two .torrent files here? the info-hash isn't stored in the .torrent file, it's computed from the info-section of it.
You say you get different info-hashes, it's possible they are both correct. Did you verify whether one of them is correct?

So this report still doesn't contain enough information to conclude there's a bug anywhere.

Can you confirm that you add the files in the same order both times you create the torrents?

**Comment by master255** [comment]
@arvidn I generated two files per v1 flag and v2 flag. These are different devices.
[Desktop.zip](https://github.com/arvidn/libtorrent/files/6092161/Desktop.zip)

**Comment by arvidn** [comment]
as you would see if you looked at `sharedV1.torrent` and `sharedV11.torrent`, the files are added in different orders. That makes them different torrents. You can fix this by adding the files in a consistent order. Presumably the underlying cause of the order being different is that different devices/operating systems/filesystems return directory listings in different orders.

You would also note that the v2 torrents are identical, and have the same info-hash. This is a feature of the v2 format, it defines one canonical order for files.

**Comment by arvidn** [comment]
would the ideal interface be to have a function that turns a `torrent_handle` into a `.torrent`-file buffer.

**Comment by master255** [comment]
@arvidn As you can see I only specify the path to create the torrent and cannot change the order of the files.
I repeat, the problem was not in the 1.2.12 version of the library.
Perhaps you need to add file sorting before generating hashes?
In the create_torrent function

**Comment by arvidn** [comment]
do you think it's important the default ordering for files is the same as all previous versions of libtorrent?

**Comment by master255** [comment]
@arvidn Of course. Without it, decentralized storage won't work. And in general it is important. It's an order.
Please make the hashes match.

**Comment by arvidn** [comment]
>  Of course. Without it, decentralized storage won't work. And in general it is important. It's an order.

That is a false statement.
You make these a lot, I would really urge you to think twice before making absolute statements like this.

I would also argue that if you rely on the same files generating the same .torrent files, you better make sure you create them exactly the same way. libtorrent does not guarantee this property you rely on. Sure, I could make the order of the files consistent, but not across versions (I think that's too late already).

If you don't want file timestamps to affect the info-hash, you better make sure not to add them for example. You should also make sure to determine the piece size in some deterministic manner. libtorrent does not guarantee that its default piece size logic is frozen in time, it may change in future versions.

One benefit of v2 torrents is that there are attempts to make the same files much more likely to generate the same torrent.

**Comment by master255** [comment]
@arvidn I'm talking about this decentralized storage, new technology: https://github.com/arvidn/libtorrent/issues/5959

Just add sorting to create the same hashes. Otherwise the library cannot be used to generate sha1 hash, to compare data.

**Comment by arvidn** [comment]
> Just add sorting to create the same hashes.

Right.

> Otherwise the library cannot be used to generate sha1 hash, to compare data.

Of course it can. Just sort the files to create the same hashes.

**Comment by master255** [comment]
@arvidn This is your code. Your library.
Fix the bug.
```
void add_files_impl(file_storage& fs, std::string const& p
		, std::string const& l, std::function<bool(std::string)> const& pred
		, create_flags_t const flags)
```

Or are you suggesting I make a fork and fix it instead of you?

**Comment by arvidn** [comment]
> Fix the bug.

I don't get the impression from you that even you know what the "bug" is.

I can fix it by clarifying in the documentation of `create_torrent` that the following attributes may affect the info-hash:

* the order in which files are added
* and that the piece size (and that the automatic piece size selection is not guaranteed to be stable)
* file timestamps (when enabled)
* file attributes
* collections
* similar torrents
* torrent name (or name of directory the files are in)
* the private-flag
* metadata version (v1, v2 or hybrid)

You seem to be under the impression that file-order is the only thing that matters, and perhaps it would *appear* to work if you just fixed the order. But if you still rely on libtorrents logic to pick a piece-size, you still may produce different torrents across different versions.

If you're arguing that "fixing the bug" entails freezing all of this logic forever, and guarantee they don't change, you need a really strong argument. Especially given that it's so easy for you, with your use case, to freeze your logic for these things.

**Comment by arvidn** [comment]
btw, I think it would make sense to add a flag to order files in v1-only torrents the same way as v2 torrents. But it's important to understand that this would not solve your problem. It would make your program work today, but may still break in the future.

**Comment by master255** [comment]
@arvidn 

> btw, I think it would make sense to add a flag to order files in v1-only torrents the same way as v2 torrents. 

For what reason do you think you need to add a flag? Who might not need to create an order? I don't care if the hash may be different because of the library version. My concern is that one version of the library generates a different hash. Because of this, I can't compare files. And I need this.

**Comment by master255** [comment]
@arvidn Okay. That's the scenario:
I created a torrent and am sharing it and my friend created a torrent and is sharing it (from the same files). We created the torrents on different devices, so they have different hashes.
So users will download from one of us and not both.
I think this is a strong argument.

**Comment by arvidn** [comment]
> For what reason do you think you need to add a flag?

To make the order optional, just like it was in the previous version. This might be critical if someone need to create torrents with very specific attributes and in consistent ways. Say, as it sounds you do.

> Who might not need to create an order?

Your future self, when you need the same order as already deployed software.

> I don't care if the hash may be different because of the library version.

Alright, that's fine. I recall this previous exchange though:

> > do you think it's important the default ordering for files is the same as all previous versions of libtorrent?

> Of course. Without it, decentralized storage won't work.

> My concern is that one version of the library generates a different hash.

You keep altering this slightly, I'm not sure if it's deliberate. The accurate statement is that "the info hash of the generated torrent depends on the order in which files are added".

> Because of this, I can't compare files. And I need this.

You seem to suggest that you don't have control over this order, which you do. Just like you can decide which order you mae any other function calls.

Until you explain why you cannot control this order, we're going to talk past each other. Specifically, you may want to identify the piece of code that forces you to add files in different orders on different devices and considering fixing that.

**Comment by arvidn** [comment]
> I think this is a strong argument.

It's a strong argument for your software to ensure you create the same torrents everywhere and every time, consistently. See my list of things to consider earlier. Also, creating torrents consistently across different versions of libtorrent also seem relevant there.

It's not an argument for libtorrent to freeze in time and prevent any future improvements.

**Comment by master255** [comment]
@arvidn 

> Until you explain why you cannot control this order, we're going to talk past each other.

I don't add files. The library adds the files itself. Can you show me the code where I add files?

**Comment by arvidn** [comment]
> I don't add files

There's your problem. You can fix it by using this function: http://libtorrent.org/reference-Storage.html#add-file-borrow-add-file

**Comment by master255** [comment]
@arvidn It is too slow to create file_storage by yourself and add one file at a time to it.
Each library call takes a long time. If there are thousands of files, it will cause serious performance problems. I think this is a strong argument.
It's much easier to send the library the path of the directory I want to use and the library will add all the files by itself.

**Comment by master255** [comment]
@arvidn Will this be fixed?

**Comment by arvidn** [comment]
I imagine there will be some change that you will consider is fixing this issue, but that I will not. And you may come back at some later point when libtorrent changes how it decides the piece size to use, arguing that it should be the same as it used to be, and I will argue that if you wanted it fixed you should have set it explicitly.

Anyway, I'm interested in hearing @aldenml thoughts as well, about it being impractical to list files at the java layer.

**Comment by aldenml** [comment]
I think that if the issue is in the order the files are added, that logic is _not necessarily_ something to be added in `libtorrent`. I used `add_files` strictly out of convenience. And....I just noticed https://github.com/arvidn/libtorrent/pull/6036 :)

**Comment by arvidn** [comment]
@master255 https://github.com/arvidn/libtorrent/pull/6036 would solve your problem, yes?

**Comment by master255** [comment]
@arvidn Perhaps. You are no longer trustworthy. I need to check it.

**Comment by arvidn** [comment]
@master255 did you try the patch? I'm not sure I would want to land it unless it solves your problem

**Comment by master255** [comment]
@arvidn  It's funny. This is where I have to ask @aldenml . How do I check the patch?
Right now I don't understand how I can set the path to Libtorrent in the docker that he made.

**Comment by aldenml** [comment]
@master255 I prepared a branch `test-patch1` (https://github.com/aldenml/libtorrent4j/tree/test-patch1) with your changes and the new flag (https://github.com/arvidn/libtorrent/pull/6036) that you can use to test. You need to perform a fresh clone and rebuild the docker image.

**Comment by master255** [comment]
@arvidn I tested it. This flag fixes the problem.
https://mega.nz/file/05sj2YaL#oLrxOXiS13NZEWPM0Zo2fkaUsG0L3jwEYI9OF1A4zz0
