### ISSUE TITLE
Question about impact of using mmap_disk_io in android

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#6035]
libtorrent: `master`
platform: `android`

Hi @arvidn, if I understand the code correctly, Android 64 bits is getting `mmap_disk_io` as the default disk io. Android is very particular in how the application memory is handled. Do you think that in this case, it is still a riskless proposition? Thanks.

https://github.com/arvidn/libtorrent/blob/5a0936b4b3778ce3c1339eb5224b775f5f320e94/src/session.cpp#L490

**Comment by arvidn** [comment]
> if I understand the code correctly, Android 64 bits is getting mmap_disk_io as the default disk io.

That's correct.

>  Android is very particular in how the application memory is handled. Do you think that in this case, it is still a riskless proposition?

In a way, using memory mapped I/O hands over control of the memory to the operating system, so I would expect it would be better. But perhaps android has ripped out/simplified its support for memory mapped files.

I can't immediately find evidence on the internet suggesting that Android has problems with memory mapped files. Have you encountered any?

**Comment by aldenml** [comment]
No issue so far. Thanks again!
