### ISSUE TITLE
Home nat/router traversal (hole punch)

### ISSUE THREAD

**Issue by ghost** [arvidn/libtorrent#604]
Hi,

Simple case to reproduce: 
- Sending private file between peers A and B both behind home router/nat withotut UPnP and NAT-TP
- Torren file opened by both peers, created with enabled DHT and two my own trackers UDP (utrack) and TCP (opentracker) which are up and running on public/external IP
-  Also tried with and without 3rd peer C running on another external/public IP opened same torrent but limited speed to to few KB/sec (just to act as introducer, not relay).

Result: 
- The only traffic of peers A and B is only few KB/sec with peer C only when it is up, otherwise no direct traffic at all between peers A and B. In neither latest libtorrent_RC_1_1 used with my simple test code in C++ nor torrent clients using libtorrent like Transmissing, qBitTorrent, Deluge.
- uTorrent/BitTorrent with same torrent gives direct traffic between peers A and B on their full internet speed, proving my knowledge and expectations it is potentially possible in libtorrent

Question:
Is it supposed to work in libtorrent_RC_1_1? I see it contains some nat traversal code via hole punching, but I never reached those points with debugger and I am not so strong in libtorrent code for a while to get what is wrong on the fly. Could anybody at least shed a light on this issue or give any point/direction to dig? I am highly interested in solving this issue in any case and making it available for public but want to make sure I will not do double job in case it is alredy not an issue.

Thanks in advance,
Best regards,
Sergiy

**Comment by arvidn** [comment]
yes, it is supposed to work (at least sometimes)

**Comment by lawnmowerwcd** [comment]
I am receiving `incoming_connection_alert`s for uTP connections on a NATed network. It's not completely broken.
