### ISSUE TITLE
Python3 bindings error on PPA

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#6047]
I am trying to build latest RC_1_2 on Ubuntu PPAs and it errors out during the python binding build.
Here is a PPA build log for you to disect. Let me know if you need extra info.

Log: https://launchpadlibrarian.net/526868604/buildlog_ubuntu-groovy-amd64.libtorrent-rasterbar_1.2.13+git20210308.ed960c2562-1ppa1~20.10_BUILDING.txt.gz

**Comment by sledgehammer999** [comment]
The problem starts with commit 037b0e579326f9a47b5bbcc0b0a44d36b25a554b according to `git bisect`

**Comment by ArcticGems** [comment]
@AllSeeingEyeTolledEweSew
You might need to check this, since commit https://github.com/arvidn/libtorrent/commit/037b0e579326f9a47b5bbcc0b0a44d36b25a554b that sledgehammer999 mentioned is based on your patch.

**Comment by arvidn** [comment]
it looks like perhaps this patch was clobbered: https://github.com/arvidn/libtorrent/commit/812e167c81daa2b019b0779fd5842c98f8a42121#diff-34cc0f25ff048b0f9e6a88e67b0860c45056874287c359c1454ae32edd8826abR243

**Comment by sledgehammer999** [comment]
I am a bit lost. Tell me if I need to apply a patch or revert some commit for testing.

**Comment by arvidn** [comment]
I think I messed up a back-port. I'll take a look

**Comment by arvidn** [comment]
This is my first stab at fixing this: https://github.com/arvidn/libtorrent/pull/6055

**Comment by arvidn** [comment]
@sledgehammer999 would you mind trying to trigger that PPA on that branch?
