### ISSUE TITLE
Using get_storage_impl() on RC1_2

### ISSUE THREAD

**Issue by elgatito** [arvidn/libtorrent#6057]
Hello Arvid,

I am moving my code from RC1_1 to RC1_2, and there I have a custom storage interface, that I was also using on RC1_1.
I have made changes, looking at `examples/custom_storage.cpp`.

So I have (short version):
```
lt::add_torrent_params p;
p.storage = lh::bittorrent::memory_storage_constructor;
lt::torrent_handle h = m_session->add_torrent(std::move(p), ec);

auto memory_storage = (lh::bittorrent::memory_storage*) h.get_storage_impl(); // <---- Segfault
```
Segfaults here:
```
	storage_interface* disk_io_thread::get_torrent(storage_index_t const storage)
	{
		TORRENT_ASSERT(m_magic == 0x1337);
		return m_torrents[storage].get(); // <---- Here
	}
```

So I get a segfault when trying to get storage impl. 
And it looks like in RC1_1 it was initialized immediately, and with RC1_2 storage initialization is made later.

How can I deal with it? Maybe missing some parameter or I need some check before accessing storage implementation?

**Comment by arvidn** [comment]
I take it `m_storage` hasn't been initialised yet, in the `torrent` object. Is that right?

**Comment by elgatito** [comment]
@arvidn Yes. Torrent handle it returned, but storage initialization seems to start when getting  first information about torrent. (I'm testing with magnets).

**Comment by arvidn** [comment]
right. constructing the disk storage object is deferred until the torrent has metadata. Are you adding a magnet link?

**Comment by elgatito** [comment]
@arvidn 

> Are you adding a magnet link?

Yes. Testing with magnet. 
So the proper way then is to call `get_storage_impl()` when I get alert about having metadata?

**Comment by arvidn** [comment]
in `RC_1_1`, did you get a nullptr in this case? or was it actually constructed without the metadata?

**Comment by arvidn** [comment]
does this help? https://github.com/arvidn/libtorrent/pull/6058

**Comment by elgatito** [comment]
@arvidn 

```
        storage_interface* torrent::get_storage_impl() const
        {
                if (!m_storage) return nullptr;
                return m_ses.disk_thread().get_torrent(m_storage);
        }
```

This one does avoid getting segfaults.
Thanks.

I have looked in the old code and it really is getting storage impl after checking for valid metadata. 

Probably, the perfect way would be sending a `lt::alert::storage_notification` for initialized storage.

**Comment by arvidn** [comment]
I would think you can use the `metadata_received_alert` for that

**Comment by elgatito** [comment]
@arvidn Yes, that is what I actually do with RC1_1 as well. 
Thanks for the fix of segfault.
