### ISSUE TITLE
"logging" is not a known value of feature dht

### ISSUE THREAD

**Issue by ardhipoetra** [arvidn/libtorrent#607]
Howdy, 

in documentation of version 1.1.0.0 in [here](http://www.rasterbar.com/products/libtorrent/building.html) and `building.rst` in `docs/`, it is said that _logging_ is a feature of dht. However, building failed when specified that value.

I remember this value is part of dht in version 1.0.6.0 or before where I can build it.

**Comment by arvidn** [comment]
the logging feature has been baked into the "logging" feature (which is on by default). In 1.1 you can enable DHT logging via the alert mask, and you'll get the log lines as dht_log_alerts.

I've fixed the documentation in RC_1_1, thanks!
