### ISSUE TITLE
Incorrect behavior of need_save_resume_data on prioritize_files

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#6070]
The issue is confirmed with libtorrent RC_2_0 but RC_1_2 is most likely affected too.

When `torrent_handle::prioritize_files()` is invoked `need_save_resume_data` is set in wrong place (before priorities are really updated) so when I call `torrent_handle::save_resume_data()` it stores incorrect priorities and clear `need_save_resume_data`.

**Comment by glassez** [comment]
Also I don't understand why file priorities (as torrent property) are required to be applied asynchronously. Why not apply them synchronously and then propagate their impact to I/O?

**Comment by arvidn** [comment]
The idea is that if the disk operation fail, the priorities are still consistent between the network thread (torrent object) and the disk thread.

It's a subtle detail, and maybe there are simpler ways of dealing with it. But the disk tread needs to have a copy of the priorities in order to know whether to write a block to the main file or the parts file.

If they got out of sync, weird things would happen.

**Comment by glassez** [comment]
> The idea is that if the disk operation fail, the priorities are still consistent between the network thread (torrent object) and the disk thread.

What kind of disk operation exactly do you mean?
>But the disk tread needs to have a copy of the priorities in order to know whether to write a block to the main file or the parts file.

This is understandable. But I do not understand what exactly can prevent copying priorities in disk thread? Does it require some kind of disk I/O itself?

Anyway the current behavior is incorrect. It says that I need to save resume data before it can be saved with the changes applied. And I haven't found a way to determine when the priorities are actually applied.

**Comment by glassez** [comment]
The problem is that we prefer to save resume data immediately after the changes applied by the user. For synchronous operations, we can do this directly after calling them. For asynchronous ones, this can be done in the corresponding alert handler. In this case, we seem to have no chance, except to hope for regular saving by timeout.

**Comment by glassez** [comment]
>What kind of disk operation exactly do you mean?

Apparently, you mean that you need to move the data from part file when the file changes priority from dont_download to some other one, etc. Then you really need to apply priorities only after these operations are completed.
The problem is that you don't give any notification about the end of applying priorities. And the most unpleasant thing is that even if you agree to add the appropriate alert, we will have to wait for it at least until version 2.1.

**Comment by arvidn** [comment]
> What kind of disk operation exactly do you mean?

Moving blocks out of the part file mostly. In theory moving data into part files too, but that's not implemented and is risky if there's a large file that has been downloaded.

> This is understandable. But I do not understand what exactly can prevent copying priorities in disk thread? Does it require some kind of disk I/O itself?

Yes, see above. If that fails, the file priorities must stay unchanged in the disk thread, so it still knows where to find blocks if they are requested.

> Anyway the current behavior is incorrect. It says that I need to save resume data before it can be saved with the changes applied. And I haven't found a way to determine when the priorities are actually applied.

Yes, I'm working on a patch. There are some other subtle issues I'm discovering too. I'm tempted to write a file-priority stress test.

> The problem is that you don't give any notification about the end of applying priorities. And the most unpleasant thing is that even if you agree to add the appropriate alert, we will have to wait for it at least until version 2.1.

That's true. If you change file priorities and exit immediately. session shutdown should wait for all outstanding operations to complete, but there's no way for the client to know when it can save the resume data then.

One way to mitigate this issue would be to only make this asynchronous when a file priority changes from zero -> non-zero or vice versa. But maybe that's the most common case anyway and won't help much.

**Comment by glassez** [comment]
> One way to mitigate this issue would be to only make this asynchronous when a file priority changes from zero -> non-zero or vice versa. But maybe that's the most common case anyway and won't help much.

This is unlikely to help. But it can be even more confusing.

I have one idea how to make it more user friendly. Although I'm not sure you can do it because of the subtle details I am not aware of.
The idea is make transition between zero-nonzero priorities relaxed towards moving pieces from/to partfile:
1. Immediately apply priorities to torrent and mark it as "need save resume data".
2. Start asynchronous propagating priorities to disk thread.
3. Unconditionally apply priorities in disk thread and then try to move pieces from/to partfile. If it's failed just mark such a pieces as missing and continue everything in a regular way.

The only weak point visible at first glance is that the pieces can be saved in resume data before they can be marked as missing due to an IO error. Maybe a pessimistic approach would be more appropriate? Mark the affected pieces as missing when applying priorities to torrent, and if everything goes well in disk thread, then mark them as available again.

**Comment by arvidn** [comment]
How does this look? https://github.com/arvidn/libtorrent/pull/6076

There is currently no way for the disk subsystem to communicate back to the bittorrent engine that a piece went missing. It could communicate that there was an error in executing a disk command, but that's about it. So it would be a non-trivial change to behave that way.

Marking pieces as missing, pessimistically, would also be a bit complicated. What if a peer was requesting those pieces during that window?

**Comment by glassez** [comment]
> How does this look? #6076

LGTM. Seems it fixes critical aspects of issues.
It is certainly inconvenient that there is no indication of the end of applying priorities. But at least it now has a chance to be saved during timeout based saving.

**Comment by glassez** [comment]
@arvidn
Wouldn't it be a good idea to provide `need_save_resume_data_alert()` in libtorrent-2.1 that is posted once `need_save_resume_data` flag goes from `false` to `true`?

**Comment by arvidn** [comment]
that sounds like a good idea. I don't think that would be an ABI break

**Comment by glassez** [comment]
> Wouldn't it be a good idea to provide `need_save_resume_data_alert()` in libtorrent-2.1 that is posted once `need_save_resume_data` flag goes from `false` to `true`?

Although if you look closely, it will do little good. After all, the "resume data" changes too often for running torrents. So more specific alerts are still relevant (ex. `file_priorities_changed_alert` in this case).

**Comment by arvidn** [comment]
@glassez how does this look? https://github.com/arvidn/libtorrent/pull/6079
