### ISSUE TITLE
Incorrect behavior of need_save_resume_data on torrent startup

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#6071]
The issue is confirmed with libtorrent RC_2_0 but RC_1_2 is most likely affected too.

When torrent is restored (i.e. added using previously stored resume data) it still has `need_save_resume_data` set unexpectedly. As I can see the wrong place is `update_piece_priorities()` that is called from `init()`. If resume data provides file priorities it calls `prioritize_pieces()` that sets `need_save_resume_data` to `true`.

**Comment by master255** [comment]
@glassez Why do you need_save_resume_data at all? Why you can''t just save all the data always?
This is a very small amount of data and it is very complicated to keep track of changes.

**Comment by arvidn** [comment]
It's not a safe assumption that it's a small amount of data. Additionally, it's not safe to assume that the number of *active* torrents is proportional to the *total* number of torrents.

**Comment by master255** [comment]
@arvidn How much maximal data can it be? 100MB? In modern computers - 100Mb of data is written instantly.
There is another way. I save this data after the application is closed. The interface closes and the saving is still running.
I save all torrents. Regardless of their status.
A computer that can handle a large amount of torrents will handle saving a large amount of data when closing.

I see that the library has more serious bugs. With proxy, file size and torrent file generation.

**Comment by arvidn** [comment]
I believe this has been addressed with https://github.com/arvidn/libtorrent/pull/6076 landing
