### ISSUE TITLE
Can I use multiple sessions within a single process?

### ISSUE THREAD

**Issue by Cempl** [arvidn/libtorrent#6089]
I want to use few sessions within a single process.
I suppose, sessions will be add/destroy dynamically.
Process should be a full peer with upload/download functionality.
Any thoughts, proposals?, or libtorrent may work only within a single session?
Any restrictions for session withing a single process?

**Comment by arvidn** [comment]
> Can I use multiple sessions within a single process?

Yes you can. In fact, many of the tests do this to connect them up to each other.
One thing to keep in mind is that (by default) only one peer per IP is allowed on any one swarm, so hooking up multiple sessions to *each other* on the same swarm requires some extra setup.
 

> I want to use a few sessions within a single process.
> I suppose sessions will be add/destroy dynamically.

Yep. Session objects are movable, so you can store them in a std::vector.

> Process should be a full peer with upload/download functionality.
> Any thoughts, proposals?, or libtorrent may work only within a single session?
> Any restrictions for a session within a single process? 

One thing to keep an eye out for is the file descriptor limit. on linux and MacOS, you may need to raise that limit to avoid having too many files and connections open simultaneously.

**Comment by Cempl** [comment]
> some extra setup

I suppose this extra setup "settings_pack::allow_multiple_connections_per_ip", right?

**Comment by arvidn** [comment]
right
