### ISSUE TITLE
docs:session_handle::[add_extension()]

### ISSUE THREAD

**Issue by kslr** [arvidn/libtorrent#6090]
Documentation under heading "session_handle::[add_extension()]" could be improved

https://www.rasterbar.com/products/libtorrent/libtorrent_plugins.html 
->
 https://www.rasterbar.com/products/libtorrent/reference-Plugins.html

**Comment by arvidn** [comment]
thanks for the report! https://github.com/arvidn/libtorrent/pull/6105
