### ISSUE TITLE
Connections are made using uTP first then uses TCP only if it fails

### ISSUE THREAD

**Issue by showstoppre** [arvidn/libtorrent#6104]
**Please provide the following information**

libtorrent version (or branch):
1.1.13 using Deluge
platform/architecture:
Windows 10 x64 
compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Connections are made using uTP first then uses TCP only if it fails. uTP connections are significantly slower than TCP. Is there a setting to prioritize TCP > uTP, so that TCP connections are tried first and if it fails, fallback to uTP.

I don't want to completely disable uTP.

**Comment by arvidn** [comment]
there is no such option, and I can't think of a work-around off the top of my head.

I can think of a few ways to *mitigate* uTP being slow, but it's fundamentally using a slower API right now. You could try setting the target delay to 1 second (I think it defaults to 100ms). That will only affect your upload rate though, not your download rate.

**Comment by markmdscott** [comment]
Oh I just came across this issue Arvid, though this is weird, you would think that uTP should be the fastest of the three approaches (uTP, UDP, TCP). What API is uTP using that makes it the slowest? Curious.

**Comment by markmdscott** [comment]
Oh I just came across this issue @Arvid, though this is weird, you would think that uTP should be the fastest of the three approaches (uTP, UDP, TCP).

What API is uTP using that makes it slow? Is this an issue on all OSes/platforms?

Curious.

**Comment by markmdscott** [comment]
Oh I just came across this issue @arvidn, though this is weird, you would think that uTP should be the fastest of the three approaches (uTP, UDP, TCP).

What API is uTP using that makes it slow? Is this an issue on all OSes/platforms?

Curious.

**Comment by arvidn** [comment]
traditional UDP APIs (like, berkley socket API) can only send a single UDP packet per system call. That means a system call about every 1400 bytes of data to send, and receive. This uses more CPU than TCP because with TCP you can send and receive many kilobytes per system call. This causes higher CPU usage for UDP.

There are work-arounds for this. linux has `sendmmsg()` for instance, and it's also possible to drop to a lower layer and use iouring or libpcap. But libtorrent doesn't do that.

Secondly, uTP is deliberately "slower" than TCP by its congestion controller being sensitive to outbound packet delays. This means it won't "push as hard" as TCP when it's sending data.

**Comment by markmdscott** [comment]
I understand that in the case of congestion, uTP goes easier on the connection than TCP or UDP peer connections; though if there is no congestion experienced, shouldn't it be just as keen when sending data?

I think I have the ability to remedy this issue of the utilization of substandard API (for modern OSes.) It should not be too difficult (at least no where near the level of apparent experience required as compared to the #3542 issue.)

These issues combined render libtorrent's performance substandard compared to uTorrent, so fixing this issue can help close the gap.

I can investigate using sendmmsg() on Linux (and the equivalent on Windows?) and maybe modern BSDs have an equivalent as well.

Do you think this should be readily doable Arvid?

**Comment by markmdscott** [comment]
I understand that in the case of congestion, uTP goes easier on the connection than TCP or UDP peer connections; though if there is no congestion experienced, shouldn't it be just as keen when sending data?

I think I have the ability to remedy this issue of the utilization of substandard API (for modern OSes.) It should not be too difficult (at least no where near the level of apparent experience required as compared to the #3542 issue.)

These issues combined render libtorrent's performance substandard compared to uTorrent, so fixing this issue can help close the gap.

I can investigate using sendmmsg() on Linux for UDP and uTP peer connections (and the equivalent on Windows?) and maybe modern BSDs have an equivalent as well.

Do you think this should be readily doable @arvidn ?

**Comment by Seeker2** [comment]
Might be possible to accept incoming uTP connections but not make outgoing ones, to at least "favor" TCP that way.

**Comment by markmdscott** [comment]
Arvid I understand that in the case of congestion, uTP goes easier on the connection than TCP or UDP peer connections; though if there is no congestion experienced, shouldn't it be just as keen when sending data?

I think I have the ability to remedy this issue of the utilization of substandard API (for modern OSes.) It should not be too difficult (at least no where near the level of apparent experience required as compared to the #3542 issue.)

These issues combined render libtorrent's performance substandard compared to uTorrent, so fixing this issue can help close the gap.

I can investigate using sendmmsg() on Linux for UDP and uTP peer connections (and the equivalent on Windows?) and maybe modern BSDs have an equivalent as well.

Do you think this should be readily doable @arvidn ?

**Comment by markmdscott** [comment]
Arvid I understand that in the case of congestion, uTP goes easier on the connection than TCP or UDP peer connections; though if there is no congestion experienced, shouldn't it be just as keen when sending data?

I think I have the ability to remedy this issue of the utilization of substandard API (for modern OSes.) It should not be too difficult (at least no where near the level of apparent experience required as compared to the #3542 issue.)

These issues combined render libtorrent's performance substandard compared to uTorrent, so fixing this issue can help close the gap.

I can investigate using sendmmsg() on Linux for UDP and uTP peer connections (and the equivalent on Windows?) and maybe modern BSDs have an equivalent as well.

Do you think this should be readily doable @arvidn ?

**Comment by arvidn** [comment]
I don't think it will be all that simple to use `sendmmsg()` and `recvmmsg()`, but probably not all that hard either. The internal interface to the udp socket class is prepared to send and receive multiple packets per call.

**Comment by markmdscott** [comment]
Ok might you know off the top of your head if Windows and the (modern) BSDs have an equivalent to this?

**Comment by markmdscott** [comment]
Arvid might you know off the top of your head if Windows and the (modern) BSDs have an equivalent to this?

**Comment by markmdscott** [comment]
@arvidn might you know off the top of your head if Windows and the (modern) BSDs have an equivalent to this?

**Comment by markmdscott** [comment]
Arvid, so I checked sendmmsg/recvmmsg, and it is 'broken' [*]:
```
The timeout argument does not work as intended.  The timeout is
checked only after the receipt of each datagram, so that if up to
vlen-1 datagrams are received before the timeout expires, but
then no further datagrams are received, the call will block forever.
```
You'll be stuck waiting forever; this is buggy behavior. (It is in fact listed under 'BUGS' in the man page.)

[*] https://news.ycombinator.com/item?id=9726185

**Comment by markmdscott** [comment]
Arvid, so I checked sendmmsg/recvmmsg, and it is 'broken' [*]:
```
The timeout argument does not work as intended.  The timeout is
checked only after the receipt of each datagram, so that if up to
vlen-1 datagrams are received before the timeout expires, but
then no further datagrams are received, the call will block forever.
```
You'll be stuck waiting forever; this is buggy behavior. (It is in fact listed under 'BUGS' in the man page.)

[*] https://news.ycombinator.com/item?id=9726185

**Comment by arvidn** [comment]
Does that apply to non-blocking sockets too? Normally you don't need a timeout on socket operations

**Comment by markmdscott** [comment]
> Does that apply to non-blocking sockets too? Normally you don't need a timeout on socket operations

No this bug only manifests when using this API on blocking sockets; even if you don't use/need a timeout it will block (possibly indefinitely) until/unless it has received the number of incoming messages you've specified.

Though you want to use this API in non-blocking mode?

Aren't async kernel operations much harder to get right? Esp. when considering supporting multiple OSes? (FreeBSD 11+ has the equivalent of sendmmsg/recvmmsg and Windows 8+ has the equivalent with Registered I/O)

I recall you yourself have documented problems using OS APIs offered asynchronously in the past and ended up resorting to thread pools of blocking syscalls as a result: https://blog.libtorrent.org/2012/10/asynchronous-disk-io/

**Comment by markmdscott** [comment]
> Does that apply to non-blocking sockets too? Normally you don't need a timeout on socket operations

No this bug only manifests when using this API on blocking sockets; even if you don't use/need a timeout it will block (possibly indefinitely) until/unless it has received the number of incoming messages you've specified.

Though you want to use this API in non-blocking mode?

Aren't async kernel operations much harder to get right? Esp. when considering supporting multiple OSes? (FreeBSD 11+ has the equivalent of sendmmsg/recvmmsg and Windows 8+ has the equivalent with Registered I/O)

I recall you yourself have documented problems using OS APIs offered asynchronously in the past and ended up resorting to thread pools of blocking syscalls as a result: https://blog.libtorrent.org/2012/10/asynchronous-disk-io/

**Comment by arvidn** [comment]
> No this bug only manifests when using this API on blocking sockets; even if you don't use/need a timeout it will block (possibly indefinitely) until/unless it has received the number of incoming messages you've specified.

Not if the socket is in non-blocking mode, right?

> Though you want to use this API in non-blocking mode?

Yes, all sockets in libtorrent are used in non-blocking mode. blocking sockets are mostly useful for simple- or example programs.

> Aren't async kernel operations much harder to get right? Esp. when considering supporting multiple OSes? (FreeBSD 11+ has the equivalent of sendmmsg/recvmmsg and Windows 8+ has the equivalent with Registered I/O)

The way non-blocking sockets work is well established and much simpler than posix-aio for example. I wouldn't say it's much harder. Just make sure to drain the socket every time it becomes readable, and make sure to send as much as possible when it becomes writable.

Do you have links to the documentation for the BSD and windows equivalents?

> I recall you yourself have documented problems using OS APIs offered asynchronously in the past and ended up resorting to thread pools of blocking syscalls as a result: https://blog.libtorrent.org/2012/10/asynchronous-disk-io/

That's for disk I/O, not socket I/O.

**Comment by markmdscott** [comment]
> > No this bug only manifests when using this API on blocking sockets; even if you don't use/need a timeout it will block (possibly indefinitely) until/unless it has received the number of incoming messages you've specified.
> 
> Not if the socket is in non-blocking mode, right?

Correct.

> > Though you want to use this API in non-blocking mode?
> 
> Yes, all sockets in libtorrent are used in non-blocking mode. blocking sockets are mostly useful for simple- or example programs.

Ah okay, I did not know libtorrent exclusively used non-blocking sockets.

> > Aren't async kernel operations much harder to get right? Esp. when considering supporting multiple OSes? (FreeBSD 11+ has the equivalent of sendmmsg/recvmmsg and Windows 8+ has the equivalent with Registered I/O)
> 
> The way non-blocking sockets work is well established and much simpler than posix-aio for example. I wouldn't say it's much harder. Just make sure to drain the socket every time it becomes readable, and make sure to send as much as possible when it becomes writable.
> 
> Do you have links to the documentation for the BSD and windows equivalents?

Windows Registered I/O equivalent:
https://stackoverflow.com/a/20123024
http://www.serverframework.com/asynchronousevents/2011/10/windows-8-registered-io-networking-extensions.html

FreeBSD equivalent has the same API signature, functionality (and bugs):
https://www.freebsd.org/cgi/man.cgi?query=recvmmsg&manpath=FreeBSD+11.0-RELEASE
https://www.freebsd.org/cgi/man.cgi?query=sendmmsg&manpath=FreeBSD+11.0-RELEASE

macOS has the equivalent in recvmsg_x() and sendmsg_x()
