### ISSUE TITLE
hashing using Intel ISA-L

### ISSUE THREAD

**Issue by fbdtemme** [arvidn/libtorrent#6112]
I want to suggest implementing a new hashing backend using the [Intel ISA-L crypto library](https://github.com/intel/isa-l_crypto).

ISA-L uses multi-buffer hashing, which takes advantage of the parallelism of the execution pipeline to compute several hashes at once within a single core using SIMD instructions. It supports ARM NEON as well as all Intel SIMD instruction sets.

I assume that significant refactoring would be needed to support this library, but the increase in throughput is quite impressive.

I am the author of a metafile utility [torrenttools](https://github.com/fbdtemme/torrenttools) which has implemented supported for this library. A small benchmark shows the AVX-2 SHA1 implementation in ISA-l can increase the throughput by a factor of 2.5 compared to the OpenSSL SHA1 implementation.

**Comment by userdocs** [comment]
How does it compare with wolfssl that can be built against libtorrent v2 (out of curiosity).

> wolfssl - links against wolfssl to use it for SHA-1 hashing and HTTPS tracker support.

`crypto=wolfssl`

https://libtorrent.org/building.html

**Comment by fbdtemme** [comment]
I have not tested wolfSSL. 
According to the benchmarks available on their website, the AVX2 implementation of SHA256 is about equal to that of OpenSSL, so the speedup by using Intel ISA-L should be the same as well.

**Comment by elgatito** [comment]
@fbdtemme can you shared a source code for your benchmark?

Do they target latest CPUs? What if you have to target systems with pretty old CPUs, will it still be that fast on both old and new CPUs?

**Comment by fbdtemme** [comment]
The benchmark is quite basic and is done be simply comparing the runtime of various torrent creation tools.
You can find the notebook file used to generate the timings in the benchmark folder of my torrent utility tool [torrenttools](https://github.com/fbdtemme/torrenttools). Files are read from an in-memory filesystem to make sure the storage device is not the bottleneck.  

My cpu is an Intel i7-7700HQ so the AVX-2 implementation is used. ISA-L has various backends that are automatically selected at runtime according to the best available instruction set.

Intel has some benchmarks with different configurations here: https://01.org/sites/default/files/documentation/intel_isa-l_2.19_performance_report_0.pdf
The numbers to look for are "Multibuffer SHA-1" and "Multibuffer SHA-256"

The Intel benchmarks include an Intel Atom C2750 (4M Cache, 2.40 GHz) which doesn't have any vector instructions and still shows a 1.5 improvement compared to openssl.

**Comment by arvidn** [comment]
I think this could fit quite well, especially with computing merkle trees. However, the documentation of how to use the `md_sha1_*` functions is quite sparse. It doesn't say much about how the parallel buffers are provided. It seems they have to be striped in advance and placed in a specific layout.

Also, @fbdtemme I don't see those functions called in any of your code either. Have you not pushed it to github yet?

**Comment by fbdtemme** [comment]
The hashing code is located in a seperate repo that is used as a dependency. You can find the relevant code here: https://github.com/fbdtemme/dottorrent/blob/master/include/dottorrent/hasher/backends/isal.hpp

An example of how to use the wrapper around the multibuffer interface is here:
https://github.com/fbdtemme/dottorrent/blob/master/src/v1_chunk_hasher_mb.cpp

Important is to use the multibuffer versions and not the multihash ones. 
The multihash version is a modification by intel and does not return the same results as OpenSSL.

**Comment by aldenml** [comment]
@arvidn do you have an idea of how to incorporate this in the build configuration?

**Comment by arvidn** [comment]
probably as a build option and using `pkg-config` to find the library and headers (at least on non-windows)

**Comment by aldenml** [comment]
In the code https://github.com/fbdtemme/dottorrent/blob/master/include/dottorrent/hasher/backends/isal.hpp, is the use of  `context_pool_ ` relevant to the hashing optimization?

**Comment by fbdtemme** [comment]
@aldenml
For maximum throughput multiple independent buffers ready for hashing need to be supplied to the context manager. Each of those buffers needs a single context object to initialize the buffer and keep track of the state for that buffer. 
context_pool_ is a vector that stores that context information for all jobs that are submitted to the context manager.
context_pool_ is thus an essential part of the interface to ISA-L.

**Comment by VADemon** [comment]
> According to the benchmarks available on their website, the AVX2 implementation of SHA256 is about equal to that of OpenSSL, so the speedup by using Intel ISA-L should be the same as well.

OpenSSL supports [acceleration using the SHA instruction set](https://stackoverflow.com/a/54277666/1599009), if wolfSSL does not mention it then they're being disingenious about their benchmark.

On top of that, ISA-L's own benchmark paper is outdated (2017), I do not know which version of OpenSSL exactly got SHA support, but they are benchmarked in uneven conditions (ISA-L uses and that OpenSSL version does not use SHA insns).

So far, this would benefit ARM, outdated processor µarchitectures and/or non-OpenSSL backends (SHA accel).

**Comment by arvidn** [comment]
@fbdtemme you measured and improvement over OpenSSL, right? The graphs on your github page lack axis, so it's hard to interpret those results.

Did you use a recent enough version of OpenSSL that support the Intel SHA acceleration instructions?

I get the impression the ISA-L folks are saying the SHA acceleration is more effective in SIMD-like mode, where you hash multiple buffers at once. OpenSSL's API doesn't support this (to my knowledge), so if this claim is true, ISA-L would still have a leg up on Intel CPUs.

**Comment by fbdtemme** [comment]
@arvidn I did measure an impressive improvement over single buffer hashing on my system with OpenSSL in my utility program and small benchmark.
There are axis on the plot so i think you have enabled github dark-mode which causes issues with svg rendering in markdown files. You can find the original file here which should render correctly: https://github.com/fbdtemme/torrenttools/blob/main/benchmark/benchmark.svg

I am using OpenSSL 1.1.1k as packaged in Fedora 33. From profiling it looks like my system uses the OpenSSL avx2 backend implementation. I do not have access to a machine with the SHA-NI extensions so I was not able to compare those implementations.

@VADemon I know the benchmarks by Intel are somewhat dated but I don't see how you think they are done in uneven conditions? I quickly checked the CPU's tested and they are broadwell, haswell, skylake and avoton which do not support SHA-NI.

**Comment by arvidn** [comment]
> There are axis on the plot so i think you have enabled github dark-mode which causes issues with svg rendering in markdown files.

Indeed. thanks!
Although, I don't think it's a markdown issue, it looks like the background is transparent (outside of the actual plot and legend).
