### ISSUE TITLE
libtorrent requires at least C++14. Specify <cxxstd>14 or higher

### ISSUE THREAD

**Issue by RafiAhmadinejad** [arvidn/libtorrent#6119]
**Please provide the following information**

libtorrent version (or branch): RC_2_0

platform/architecture: macOS

compiler and compiler version: darwin v18.7.0

please describe what symptom you see, 
```warning: mismatched versions of B2 engine and core
warning: B2 engine (b2) is 4.3.0
warning: B2 core (at /usr/local/share/boost-build/src) is 4.2-git
CXXFLAGS =
LDFLAGS =
OS = MACOSX
libtorrent requires at least C++14. Specify <cxxstd>14 or higher
libtorrent requires at least C++14. Specify <cxxstd>14 or higher
...found 24 targets...
```

what you would expect to see instead 
A successful build

**Comment by kslr** [comment]
```b2 crypto=openssl cxxstd=14 release```

**Comment by arvidn** [comment]
I think `cxxstd=14` should be the default for the libtorrent target. The reason I've hesitated earlier is that if the client, linking against libtorrent, is build with a different version of C++, there may be ABI issues (ideally there shouldn't be, and I try to avoid that, but this is a precaution).

Something like this: https://github.com/arvidn/libtorrent/pull/6124

**Comment by arvidn** [comment]
I landed that patch, so I consider this resolved
