### ISSUE TITLE
Minor conversion warning

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#612]
C:\Libtorrent-1.1.0\libtorrent-rasterbar-1.1.0\include\libtorrent/torrent.hpp(1087): warning C4244: '=': conversion from 'int64_t' to 'int16_t', possible loss of data

**Comment by arvidn** [comment]
I believe this fixes it. please confirm. https://github.com/arvidn/libtorrent/pull/616

**Comment by arvidn** [comment]
merged into RC_1_1. please close if this fixes the warning for you
