### ISSUE TITLE
Python3 bindings: TypeError: 'file_storage' object is not iterable

### ISSUE THREAD

**Issue by kslr** [arvidn/libtorrent#6122]
**Please provide the following information**

libtorrent version (or branch):
2.0.2 and 2.0.3

platform/architecture:
linux amd64

compiler and compiler version:
ubuntu 20.04, use ``` python3 setup.py build_ext --b2-args="libtorrent-link=static crypto=openssl" install --user --prefix=```

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

```python
import libtorrent as lt
import time

session = lt.session({})

atp = lt.parse_magnet_uri("magnet:?xt=urn:btih:46649a74088d9a766a6112fc3d549aaa61c91b59&dn=%5BSubsPlease%5D%20Back%20Arrow%20-%2014%20%281080p%29%20%5B3C5120CB%5D.mkv&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce")
atp.save_path = "./"

session.add_torrent(atp)

time.sleep(10)

for handle in session.get_torrents():
    if not handle.is_valid():
        continue

    ti = handle.torrent_file()
    if ti:
        for index, file in ti.files():
            print(file.size)


```

**Comment by arvidn** [comment]
this interface was deprecated (but, granted, no warning was emitted in python).

Instead, call `ti.files().file_size(index)`
