### ISSUE TITLE
tick_interval

### ISSUE THREAD

**Issue by Col-blimp** [arvidn/libtorrent#613]
This is a weird bug, scenario is that all settings are saved for the user then set again on the next launch so it goes:

`pack.set_int ( settings_pack::tick_interval , session_restore.tick_interval );`

and **tick_interval** causes the application window to never show and according to debugging there is nothing wrong but when **tick_interval** is omitted the application runs fine.

Libtorrent is 1.1.0 and is built:

toolset=msvc-14.0 
boost-link=static 
runtime-link=static
deprecated-functions=off 
encryption=on 
link=static 
dht=on 
logging=off 
i2p=on 
variant=release

As far as I can see **tick_interval** is not depreciated and Visual Studio does not show any sign that it is.

**Comment by arvidn** [comment]
you may want to run under a memory debugger, like valgrind or -fsanitize=address. It does smell a bit like heap corruption.
Another path to explore could be to see what setting the tick interval affects. Is it the case that a tick timer stops working in libtorrent and some events never get fired, that your client depend on?

**Comment by Falcosc** [comment]
@Col-blimp Could you check which tick_interval value got set during your action by enabling logging?
Because i am not sure what happen if the smallest value (1) get forced because time with 1ms is like and endless loop.
