### ISSUE TITLE
Python bindings: we should remove mappings for http_seeds

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [arvidn/libtorrent#6136]
```python
atp = lt.add_torrent_params()
atp.ti = ...
atp.http_seeds = ["http://httpseed.com"]
atp.url_seeds = ["http://urlseed.com"]
handle = session.add_torrent(atp)
handle.http_seeds()  # []
handle.url_seeds()  # ["http://urlseed.com"]
```

Also `write_resume_data()` doesn't seem to write `http_seeds` and `read_resume_data()` doesn't read it.

This doesn't appear to be a python bindings issue, the C++ code just drops the value. I know `http_seeds` is deprecated, but is it intended to be dropped?

**Comment by arvidn** [comment]
yes, support for `http_seeds` ([BEP 17](https://www.bittorrent.org/beps/bep_0017.html)) have been removed from master. As far as I know, nobody uses them. support for `url` seeds is still there ([BEP 19](https://www.bittorrent.org/beps/bep_0019.html)).

**Comment by arvidn** [comment]
mailing list announcement [here](https://sourceforge.net/p/libtorrent/mailman/libtorrent-discuss/thread/CAAhUOPVrbNMKOj%2BfjdCb3NCt-2SrmvUHxV5nuEek3qDUiw6wyA%40mail.gmail.com/#msg37074881).

**Comment by AllSeeingEyeTolledEweSew** [comment]
Ahhh, I see

IMO, once a feature is "vestigial" (function exists but has no effect), it can be removed from python bindings altogether. It shouldn't break any python clients until they go to call the function. At that point they'd break anyway if they depend on the effect

**Comment by AllSeeingEyeTolledEweSew** [comment]
(I'm assuming you only kept http_seeds in the C++ code to avoid link errors, which doesn't apply to python)

**Comment by AllSeeingEyeTolledEweSew** [comment]
unstale

**Comment by AllSeeingEyeTolledEweSew** [comment]
Actually, never mind. As I look through it, I can think of a lot of ways an app might touch `http_seeds` for passthrough purposes, and we'd break them needlessly if we removed it.

We should still deprecate `http_seeds` though, but that's #5967.
