### ISSUE TITLE
Invalid commandline option "-msse4.2" on PowerPC

### ISSUE THREAD

**Issue by susnux** [arvidn/libtorrent#614]
When comping on a PowerPC computer I get:

    gcc: error: unrecognized command line option '-msse4.2'

**Comment by arvidn** [comment]
how do you compile? are you using autotools? which version are you building?

**Comment by arvidn** [comment]
it looks like this option is added unconditionally in the autotools build. I expect it to work if you remove that line (from configure.ac), right?

If so, would you mind issuing a pull request against the RC_1_1 branch?

**Comment by arvidn** [comment]
Or even better, do you know of a way to detect intel target architecture in the makefile, and only add it in that case?

**Comment by lawnmowerwcd** [comment]
Just wondering, but shouldn't the compiler/build environment figure out cpu-specific optimizations? I think this option should be removed regardless of the architecture.

**Comment by arvidn** [comment]
my understanding/assumption is that gcc has conservative default assumptions, generating code that can run on any i386, or possibly somewhat later version. But it won't enable sse4 code generation unless it's asked to. autotools _is_ the build environment that I would expect to figure this out. perhaps there's even an m4 script that configure could use to determine this (by testing)

**Comment by lawnmowerwcd** [comment]
I'm not extremely familiar with the internals of the build process but in my understanding such optimizations should be passed in the CFlags/CXXFlags. At least that's how my build environment works.

**Comment by susnux** [comment]
Something like this should work:

    case "$host" in
            i?86-* | k?-* | athlon-* | pentium*-)
                    ARCH_SPECIFIC_CFLAGS="-msse4.2"
                    ;;
            x86_64-*)
                    ARCH_SPECIFIC_CFLAGS="-msse4.2"
                    ;;
            *)
                    AC_MSG_NOTICE([No architecture specific optimization])
                    ;;
    esac

Maybe remove the i... because sse is first available on athlon / pentium.

**Comment by arvidn** [comment]
looking into this a bit, I'm pretty sure this command line argument is not necessary. I went ahead and removed it in RC_1_1

**Comment by barracuda156** [comment]
In other shape, but the problem is back: https://github.com/arvidn/libtorrent/issues/7042
