### ISSUE TITLE
ImportError image not found

### ISSUE THREAD

**Issue by RafiAhmadinejad** [arvidn/libtorrent#6142]
**Please provide the following information**

libtorrent version (or branch): RC-2_0

platform/architecture: macOS

compiler and compiler version: darwin 18.7.0

please describe what symptom you see, 
```
>>> import libtorrent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/python_libtorrent-2.0.3-py3.8-macosx-10.9-x86_64.egg/libtorrent.cpython-38-darwin.so, 2): Library not loaded: libboost_python38.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/python_libtorrent-2.0.3-py3.8-macosx-10.9-x86_64.egg/libtorrent.cpython-38-darwin.so
  Reason: image not found
```
what you would expect to see instead 
success import

**Comment by arvidn** [comment]
it looks like you need to install `libboost_python38.dylib`

```
$ brew search boost-python
==> Formulae
boost-python                                                                                             boost-python3
```

`boost-python3` looks promising.

**Comment by RafiAhmadinejad** [comment]
I have already installed boost-python3 when I want to build libtorrent, but it doesn't work. So i build myself boost python3.8 and it has the libboost_python38.dylib and libboost_system.dylib but I need to move it /usr/local/opt/boost-python/lib/ everyday.
