### ISSUE TITLE
Deprecated info_hash-only path broken

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [arvidn/libtorrent#6145]
If I "simulate" a magnet uri by using `add_torrent_params` with no `torrent_info`, then using `info_hashes` works but `info_hash` does not.

It's a deprecated path, and probably rare, but it should technically work.

The following works:
```python
atp = lt.add_torrent_params()
atp.info_hashes = lt.info_hash_t(lt.sha1_hash(b"a" * 20))
session.add_torrent(atp)
```
But, the following breaks:
```python
atp = lt.add_torrent_params()
atp.info_hash = lt.sha1_hash(b"a" * 20)
session.add_torrent(atp)
"""
RuntimeError: missing info-hash from URI
"""
```

Tested in master

**Comment by arvidn** [comment]
I believe this fixes it: https://github.com/arvidn/libtorrent/pull/6154

**Comment by arvidn** [comment]
I added your examples to the test here: https://github.com/arvidn/libtorrent/pull/6162
