### ISSUE TITLE
About the official website.

### ISSUE THREAD

**Issue by Zjek** [arvidn/libtorrent#6155]
Hello！
I found that when I logged in to the official website(libtorrent.org) recently, the CPU consumption was very high.
I suspect the official website has been attacked.

**Comment by markmdscott** [comment]
> Hello！
> I found that when I logged in to the official website(libtorrent.org) recently, the CPU consumption was very high.
> I suspect the official website has been attacked.

You logged in to the libtorrent.org website? Are you sure of this?

What signup page did you use and what is the login page? I wasn't aware one could be logged in to it. At least I don't see a way how.

(Or do you just mean that you loaded the webpage in your browser?)

**Comment by Zjek** [comment]
@markmdscott 
When I browse this page in Chrome.Have you ever been in this situation？

**Comment by markmdscott** [comment]
Oh okay you mean just browsing. I haven't been in such a situation myself, but you can tell if somehow a javascript file is taking a lot of CPU time by inspecting the page's resources in your browser.

**Comment by arvidn** [comment]
there is no login on https://libtorrent.org
