### ISSUE TITLE
remove_torrent(..., option) should be treated as a mask, but isn't

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [arvidn/libtorrent#6158]
EDIT: `remove_torrent(..., delete_files | delete_partfile)` should work, deleting both data and partfile if one exists.

~~`remove_torrent(..., delete_files)` doesn't seem to be deleting data.~~

~~I tested this in master and RC_2_0. It never completes (the last check waiting for the data to delete doesn't complete)~~

```python
import libtorrent as lt
import hashlib
import os
import os.path

data = b"a" * 1024
info = {
    b"name": b"test.txt",
    b"pieces": hashlib.sha1(data).digest(),
    b"piece length": 16384,
    b"length": 1024,
}
atp = lt.add_torrent_params()
atp.ti = lt.torrent_info({b"info": info})

session = lt.session({"alert_mask": lt.alert_category.all, "alert_queue_size": 2**30-1})
handle = session.add_torrent(atp)
# wait until done checking
while True:
    if handle.status().state not in (lt.torrent_status.checking_files, lt.torrent_status.checking_resume_data):
        break
handle.add_piece(0, data, 0)
# wait until data is written
while True:
    try:
        with open("test.txt", mode="rb") as fp:
            if fp.read() == data:
                break
    except FileNotFoundError:
        pass
session.remove_torrent(handle, option=lt.session.delete_partfile | lt.session.delete_files)
# wait until torrent_deleted_alert
while True:
    for alert in session.pop_alerts():
        print(alert.what(), ":", alert.message())
        if isinstance(alert, lt.torrent_deleted_alert):
            break
# wait until data actually deleted
while True:
    if not os.path.exists("test.txt"):
        break
```

~~For a similar test, I also tried making `save_path` read-only after data was written, then `remove_torrent(..., delete_files)`. I expect to get `torrent_delete_failed_alert` in that case, but I actually just get `torrent_deleted_alert`, and the data stays.~~

**Comment by AllSeeingEyeTolledEweSew** [comment]
Ohhh, I see. The problem is that `option` is treated as an enum, not a mask, so `option=lt.session.delete_files` works as expected.

But then, I want to ensure the partfile is deleted if there is one, so I think `option` should be a mask

**Comment by arvidn** [comment]
@AllSeeingEyeTolledEweSew I'm working on a fix where I relax how the `options` parameter is treated, while staying backwards compatible, and add test coverage of it. However, in your test above, there are a few improvements you could make:

1. In the loop popping and printing alerts, you only `break` out of the inner loop when finding the alert you're looking for, not the outer loop.
2. You should also look for a `lt.torrent_delete_failed_alert`, and fail the test if you get one.
3. You should probably insert short sleeps in the loops waiting for conditions

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/6345

**Comment by AllSeeingEyeTolledEweSew** [comment]
#6345 looks good.

I think I probably modified my test script above, between running it and pasting it here. Ad-hoc tests look good though.
