### ISSUE TITLE
Some questions about dht_ get_ Item problem.

### ISSUE THREAD

**Issue by Zjek** [arvidn/libtorrent#6160]
Hello
I see dht_ get_ There are two methods for item. What do immutable and mutable stand for? What scenarios are these two methods used for?

Thanks!

**Comment by markmdscott** [comment]
So this page can help answer your questions:

http://www.libtorrent.org/dht_store.html

**Comment by Zjek** [comment]
@markmdscott 
First of all, thank you for answering for me.
I used the officially recommended bootstrap-dht project. I started the first boot node and linked it with other nodes, but in other nodes it showed that the boot node did not live.Show timeout in log.
 What should I do?


**print**
```
logs: starting IPv4 DHT tracker with node id: efb620b2bd62f0f1c8d55c23ee2cb1df7310986a
logs: starting IPv4 DHT tracker with node id: 31dc7b06adfe3940033a0830954a8f72d3c90dea
logs: adding router node: 192.168.1.107:6881
logs: adding router node: 192.168.1.107:6881
logs: adding router node: 192.168.1.107:6881
logs: adding router node: 192.168.1.107:6881
logs: *** new write key***
logs: [0] NEW target: 31dc7b06adfe3940033a083014d3dbe20e2baa45 k: 8
logs: bootstrapping with 0 nodes
logs: [0] using router nodes to initiate traversal algorithm 1 routers
logs: [0] ADD (no-id) id: 0000000000000000000000000000000000000000 addr: 192.168.1.107:6881 distance: 157 invoke-count: 0 type: bootstrap
logs: [0] INVOKE nodes-left: 1 top-invoke-count: 0 invoke-count: 0 branch-factor: 5 distance: 156 id: 24aac288f261061ea9302e193963758243a885ed addr: 192.168.1.107 type: bootstrap
logs: [0] invoking get_peers -> 192.168.1.107:6881
logs: [0] NEW target: efb620b2bd62f0f1c8d55c231eeda164d9c5234f k: 8
logs: bootstrapping with 0 nodes
logs: [0] using router nodes to initiate traversal algorithm 1 routers
logs: [0] ADD (no-id) id: 0000000000000000000000000000000000000000 addr: 192.168.1.107:6881 distance: 159 invoke-count: 0 type: bootstrap
logs: [0] INVOKE nodes-left: 1 top-invoke-count: 0 invoke-count: 0 branch-factor: 5 distance: 158 id: 852b728a2f775f80e77e70e77db60fef5da61426 addr: 192.168.1.107 type: bootstrap
logs: [0] invoking get_peers -> 192.168.1.107:6881
logs: [0] bootstrap done, pinging remaining nodes
logs: [0] bootstrap DONE
logs: [0] not alive: 192.168.1.107:6881
Bootstrap
logs: [0] COMPLETED distance: 160 type: bootstrap
logs: [0] short-timing out transaction id: 19514 from: 192.168.1.107:6881
logs: [0] 1ST_TIMEOUT id: 24aac288f261061ea9302e193963758243a885ed distance: 156 addr: 192.168.1.107 branch-factor: 6 invoke-count: 1 type: bootstrap
logs: [0] timing out transaction id: 19514 from: 192.168.1.107:6881
logs: [0] TIMEOUT id: 24aac288f261061ea9302e193963758243a885ed distance: 156 addr: 192.168.1.107 branch-factor: 6 invoke-count: 1 type: bootstrap
logs: [0] bootstrap done, pinging remaining nodes
logs: [0] bootstrap DONE
logs: [0] not alive: 192.168.1.107:6881
Bootstrap
logs: [0] COMPLETED distance: 160 type: bootstrap
```

**Comment by Zjek** [comment]
I use dht_get_item get entry data.How can I use it to download file?

**Comment by markmdscott** [comment]
I was not aware there was an officially recommended bootstrap-dht project. What is that? And where did you find it?

**Comment by Zjek** [comment]
@markmdscott 
https://blog.libtorrent.org/2016/09/dht-bootstrap-node/
and
https://github.com/bittorrent/bootstrap-dht

**Comment by markmdscott** [comment]
Ah interesting! Thanks for the references; I was not aware of them.

I have not used the bootstrap-dht project myself. Perhaps Ian can help. @geiseri have you used it before? Might you know what is going on?

**Comment by arvidn** [comment]
@Zjek there are tools to test your DHT bootstrap node as part of that repository. I'd suggest you use those to make sure it's set up correctly.

**Comment by Zjek** [comment]
@arvidn @markmdscott 
First of all, thank you.
How can I set up bootstrap-dht to act as a DHT server for BitTorrent?
Please give me some examples.

**Comment by Zjek** [comment]
@arvidn @markmdscott 
First of all, thank you.
How can I set up bootstrap-dht to act as a DHT server for BitTorrent?
Please give me some examples.

**Comment by markmdscott** [comment]
Zjek, though I haven't used it myself, it has a long description and list of instructions on its readme page, from the repo you told me about. And there are tests there as examples you can use to try them out.

**Comment by master255** [comment]
@Zjek 

> What scenarios are these two methods used for?

https://habr.com/ru/post/546612/
There are a lot of scenarios. I think the basic scenario is this. 

@arvidn , @markmdscott I think it's time to answer such questions with a link to my article. It describes in plain language how it can be used.
