### ISSUE TITLE
Question: Libtorrent 1.2.x.x Hashing Threads Settings

### ISSUE THREAD

**Issue by eldervamp** [arvidn/libtorrent#6161]
**Please provide the following information**

Libtorrent 1.2.x.x

Windows 10 x64

Does Libtorrent 1.2.x.x support changing the Hashing Threads setting? Was mentioned from a torrent client page that this setting is only supported on Libtorrent 2.0.x but I see this option on screenshot with Libtorrent 1.2.x.x.
![thread](https://user-images.githubusercontent.com/37281419/115654071-3710f200-a2e5-11eb-941b-1bacaabe6fb4.jpg)

**Comment by arvidn** [comment]
no, that setting was deprecated in 1.2 and then un-deprecated in 2.0

**Comment by eldervamp** [comment]
> 
> 
> no, that setting was deprecated in 1.2 and then un-deprecated in 2.0

Ok, Thank you :)
