### ISSUE TITLE
executable permissions on downloaded files

### ISSUE THREAD

**Issue by Kolcha** [arvidn/libtorrent#6168]
libtorrent version (or branch): 2.0.3, RC_2_0
platform/architecture: macOS 10.15.7, Debian Unstable/amd64
compiler and compiler version: Apple clang 11.0.3, GCC 10.2.1

any files downloaded with libtorrent 2.0 based client have executable bit set, libtorrent 1.2 has no such behavior, see attached screenshot. ubuntu 18.04 was downloaded using libtorrent 1.2 based client, ubuntu 20.04 - libtorrent 2.0:
![downloads_permissions](https://user-images.githubusercontent.com/947647/115995085-85263e00-a5e2-11eb-885c-add3f56a6c5f.png)

the same behavior is reproduced using `bt-get` example and ubuntu 18.04 torrent (magnet link was copied from qBittorrent) as source. issue affects at least macOS and Linux, very likely any other Unix-like systems.

**Comment by arvidn** [comment]
there is an extension to the .torrent file format to say whether a file should have the executable bit set or not. It's possible this bit is set in the .torrents you download (and there's a bug in 1.1.x causing it to not set it correctly).

Can you share the .torrent file where the executable bit is set?

**Comment by Kolcha** [comment]
just download official Ubuntu 18.04 or 20.04 torrents:
- http://releases.ubuntu.com/bionic/ubuntu-18.04.5-desktop-amd64.iso.torrent
- http://releases.ubuntu.com/focal/ubuntu-20.04.2.0-desktop-amd64.iso.torrent
I reproduce this using any of these torrents, any other torrents I tried (randomly downloaded media stuff) are also affected

**Comment by arvidn** [comment]
I believe this patch fixes it. if you have the ability to test it, please do!

https://github.com/arvidn/libtorrent/pull/6192

**Comment by Kolcha** [comment]
unable to build from your branch
<img width="899" alt="Screen Shot 2021-05-09 at 13 07 36" src="https://user-images.githubusercontent.com/947647/117568176-ad746900-b0c7-11eb-9fe7-ecf920025700.png">
ci also fails with exact this error (at least macOS build)

**Comment by arvidn** [comment]
thanks, fixed!

**Comment by Kolcha** [comment]
tested, #6192 fixes mentioned issue (tested on macOS, doesn't have suitable Linux machine right now). thanks!

**Comment by Kolcha** [comment]
PR with fix was merged, closing issue
