### ISSUE TITLE
custom_storage.cpp error in readv

### ISSUE THREAD

**Issue by damolp** [arvidn/libtorrent#6170]
**Please provide the following information**

libtorrent version (or branch):
2.0.3

platform/architecture:
Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1038 aarch64)

compiler and compiler version:
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

`custom_storage.cpp` seems to have a bug in `readv` as uTorrent connected directly to the `custom_storage` client keeps banning it as a peer due to the hash checks on pieces failing. I think this is because you're pushing more than 16384B refs (`int(i->second.size()) - offset`) back to libtorrent [[1]](https://github.com/arvidn/libtorrent/blob/RC_2_0/examples/custom_storage.cpp#L68) when it should be something like `peer_request.length` or the min of the two instead?

**Comment by arvidn** [comment]
thanks! how does this look?

https://github.com/arvidn/libtorrent/pull/6173

**Comment by damolp** [comment]
Yep - that looks pretty much like how I fixed `readv`. Confirmed it works.
