### ISSUE TITLE
Setting to set announce_port to trackers and DHT

### ISSUE THREAD

**Issue by showstoppre** [arvidn/libtorrent#6171]
libtorrent version (or branch):1.1.13 using Deluge
platform/architecture: Windows 10 x64

My understanding is port used in 'listen_interfaces' is announced to trackers. I wonder if any one of the below is possible

1. Is there a setting to set announce_port.
2. Is there a way to listen on more than one UDP port mianly for incoming uTP connections.  
	I noticed that when I setup multiple listen ports using listen_interfaces, the respective ports are correctly opened for TCP and not UDP. Only the last mentioned port is opened for UDP under unspecified IP address. (Intended?)
	Eg: "listen_interfaces": "0.0.0.0:4965,192.168.0.30:6546,192.168.0.31:6545"
	Here only UDP port 6545 is opened for Unspecified IPv4 and IPv6 addresses.
3. Is there a way to setup separate listen port for TCP and UDP.

Background: I'm behind a full-cone NAT(atleast for UDP). My external_port differs from internal_port. Announcing the right port will help in inbound uTP connections. Even though PEX and UDP hole punch already help in mitigating this, would be great if I could preemptively announce the correct port.

**Comment by arvidn** [comment]
libtorrent-1.2 and later will open a UDP socket per listen interface. I can't think of a way to sepecify the announce port explicitly though. When using UPnP, NAT-PMP or PCP, the external port is acquired from the port-mapping. I take it you have manually configured a port-forward and would like to tell libtorrent.

Perhaps it would make sense to allow such setting. I'm open to suggestsions on how to specify that. I imagine it would have to be through the listen_interfaces string somehow.

**Comment by showstoppre** [comment]
> libtorrent-1.2 and later will open a UDP socket per listen interface

Thanks for confirming that. Quick question though, when I'm listening on more than one interface with different ports, which port would be announced to trackers?

> When using UPnP, NAT-PMP or PCP, the external port is acquired from the port-mapping. 

In this case, is the external port reported to tracker or is the port libtorrent is listening on?

> I take it you have manually configured a port-forward and would like to tell libtorrent.

I'm behind a CGNAT with no scope for port-forwarding. However with a full-cone NAT for UDP connections, I can virtually achieve port-forwarding for uTP connections by announcing the correct external port which I can easily obtain using STUN.

>I'm open to suggestsions on how to specify that. I imagine it would have to be through the listen_interfaces string somehow.

Sorry. I'm no expert. Correct me if I'm wrong, my understanding is tracker announces have a bit-field for PORT and unlike aṇnounce_ip, port number in announce message is always respected. So maybe a setting similiar to announce_ip for announce_port could be implemented.

I'm sure this implementation would not benefit a larger audience. I think it is a good to have feature. So far I've only come across announce_port setting in BiglyBT.

**Comment by arvidn** [comment]
> when I'm listening on more than one interface with different ports, which port would be announced to trackers?

libtorrent-1.1 and earlier did not have great support for multiple networks, I'm not sure exactly which port is picked, probably the first one that satisfies some heuristic.

libtorrent-1.2 will announce *every* port and interface you're listening on to the tracker (except if the tracker cannot be reached via an interface, then its skipped). for example, if you're listening on 127.0.0.1, you can't reach the tracker via that interface, so it won't be announced. If you want to read up on this, see [this](https://github.com/bittorrent/bittorrent.org/issues/100) and [this](https://github.com/bittorrent/bittorrent.org/pull/101).

**Comment by arvidn** [comment]
> In this case, is the external port reported to tracker or is the port libtorrent is listening on?

The port opened on the NAT device is reported in the tracker announce. However, DHT is different, it has a feature where the port can be implied from the DHT message. meaning the source port of the DHT message is assumed to also be listening for incoming uTP connections. This will make things work automatically for full cone NATs.

**Comment by showstoppre** [comment]
> the source port of the DHT message is assumed to also be listening for incoming uTP connections

I wonder if this is always the case though. Isn't it the remote node that decides whether to choose the source port of the message or the listen port contained in the message?

>libtorrent-1.2 will announce every port and interface you're listening on to the tracker

This is interesting. _Close to a solution I was looking for_. On private torrents with DHT and PEX being disabled, announcing two ports(one referring to the actual external port of the other) would mean I'm guaranteed to get an incoming connection from an unreachable peer.

If the implementation effort to set announce_port outweigh the benefits, I'm happy to close this as there are other implicit alternatives.

On a side note I've got a couple of unrelated questions
1. Does utp hole_punch works on private torrents
2. In PEX messages, is it the source port(for inbound peers),destination port(for outbound peers) or listen port of a connected peer is that is shared with other peer. Or a mix of all with duplicate IP entries.
3. I've noticed that when a seed connects to another seed, the connection is immediately closed.(Not sure if its from local side,remote or both). Can I assume that PEX cannot takes place between two seeds or it is exchanged before the connection is closed. 
My thoughts are if PEX could take place between two seeds, it ll improve the connectivity of all peers in swarm by some length.

**Comment by arvidn** [comment]
> Sorry. I'm no expert. Correct me if I'm wrong, my understanding is tracker announces have a bit-field for PORT and unlike aṇnounce_ip, port number in announce message is always respected. So maybe a setting similiar to announce_ip for announce_port could be implemented.

Technically, this setting is per listen interface, not per session.

**Comment by arvidn** [comment]
>     Does utp hole_punch works on private torrents

No, because PEX is disabled.

>     In PEX messages, is it the source port(for inbound peers),destination port(for outbound peers) or listen port of a connected peer is that is shared with other peer. Or a mix of all with duplicate IP entries.

It's the port someone else is likely to be able to connect to the peer on. There is some logic to determine what that port is and it's not 100% reliable in case the other peer is behind NAT. For uTP is fairly reliable as the source port of the UDP packets are also the port peers listen on for incoming connections.

>     I've noticed that when a seed connects to another seed, the connection is immediately closed.(Not sure if its from local side,remote or both). Can I assume that PEX cannot takes place between two seeds or it is exchanged before the connection is closed.

That's correct.

>     My thoughts are if PEX could take place between two seeds, it ll improve the connectivity of all peers in swarm by some length.

It could help seeds find downloaders, yes.

**Comment by showstoppre** [comment]
Thanks a lot for clarifying all my questions. I really appreciate it. I'm gonna close this ticket as I have a partial solution by upgrading libtorrent and announcing both ports to tracker using listen_interfaces.

> > ```
> > My thoughts are if PEX could take place between two seeds, it ll improve the connectivity of all peers in swarm by some length.
> > ```
> 
> It could help seeds find downloaders, yes.

Is there a way at all to prevent disconnect between seeds/partial seeds. Probably something like keep alive for x seconds and exchange peers. Your thoughts?

**Comment by arvidn** [comment]
there is an option to not disconnect redundant peers, but I doubt it would help since the other end would most likely disconnect you immediately anyway.

I think a feature like this would be an improvement to the implementation.

**Comment by showstoppre** [comment]
Alright then. Have a nice rest of the day.

**Comment by kovalensky** [comment]
@arvidn I paid attention that the source port picked for connection to trackers is not the same as the one we set in the client.
The one we set, is being used to connect to peers, to my understanding, but what could be the reason to not to use the same for trackers? Kinda confused.

Wouldn't it be beneficial for port-restricted peers, if trackers could record their external port? 

  The bencoded warning message shows us external port which is 38707, &port parameter is 64027, static IP is present:

![photo_2023-11-22_20-36-02](https://github.com/arvidn/libtorrent/assets/45331093/3c6d4249-5154-4fb2-9971-e64f62e0d83c)

![photo_2023-11-22_20-36-07](https://github.com/arvidn/libtorrent/assets/45331093/ff026cda-f8fe-4099-9454-337a30e4d591)

**Comment by arvidn** [comment]
> I paid attention that the source port picked for connection to trackers is not the same as the one we set in the client.

Which setting specifically?

> The one we set, is being used to connect to peers, to my understanding, but what could be the reason to not to use the same for trackers?

Are you referring to the `outgoing_port` setting? ([here](http://libtorrent.org/reference-Settings.html#outgoing_port))
I think the rationale is pretty clear in the documentation. If you bind tracker connections to a specific port, you may fail announcements if you have multiple torrents using the same tracker. The (source-ip, source-port, destination-ip, destination-port) quadruple must be unique for connections.

It's also something that has questionable utility, there's no bulk data being transferred over the tracker connection. The main rationale for introducing the `outgoing_port` setting was to allow routers to apply QoS rules based on the source port, to control bulk transfers.

The `&port=` parameter being sent to the tracker is your *listen* port, not your local outgoing port for your peer connections. It's the port other peers can connect to you at.

Perhaps there's some misunderstanding of what you're asking.

**Comment by kovalensky** [comment]
> The (source-ip, source-port, destination-ip, destination-port) quadruple must be unique for connections.

I searched and read a couple of articles, I think I understand now, one more thing to the knowledge box.
Thanks for thorough answer Arvid 👍🏻
