### ISSUE TITLE
Question about tracker announce response for multi-homed client

### ISSUE THREAD

**Issue by t3link** [arvidn/libtorrent#6186]
Hello, I'm a private torrent tracker developer. Since libtorrent v1.2.0, for multi-homed clients, the tracker will receive multiple announce request with different source announce ip. The tracker responses may be in a random order. Although the interval between these responses may be only a few milliseconds.

For example, in a session, the tracker reply peers list `10.3.8.10` to source ip  `10.3.8.3`. And reply peers list `192.168.0.10` to source ip `192.168.0.3`. How will the client process the peers list replied by multi tracker response? Will it use the latest received response or combine those peers list. 

What's more, in a specific case, I will just reply full peers list to the first income announce request, and just drop the next announce request by just reply empty peers list or return an error http code. The way only handle the first income request will greatly reduce the pressure on the server. But I'm not sure about the client's behavior.  What will happen about this? And- if one announce request get an error http status, will it retry?

Also, there may be same problem with the `tracker id`. If the tracker reponse different tracker id value to thoses source ips. How will the client deal with it?

**Comment by arvidn** [comment]
> For example, in a session, the tracker reply peers list `10.3.8.10` to source ip  `10.3.8.3`. And reply peers list `192.168.0.10` to source ip `192.168.0.3`. How will the client process the peers list replied by multi tracker response? Will it use the latest received response or combine those peers list.

It will combine the peer lists. The client maintains a list of peers at all times and continuously add, remove and update entries based on various events. Whenever it receives a tracker response, those peers are merged into this list. Possibly just updating the entry indicating that we have received it from a tracker, if we already have the peer in the list.

> What's more, in a specific case, I will just reply full peers list to the first income announce request, and just drop the next announce request by just reply empty peers list or return an error http code.

But you still record the peers IP address and listen port though, right? So you can hand it out in other announces to other peers.

> The way only handle the first income request will greatly reduce the pressure on the server. But I'm not sure about the client's behavior.  What will happen about this?

If the client receives 0 peers to in the response, that's fine. That will still count as a success and the normal announce interval will be honored.

However, keep in mind that if the first request is over IPv4 and the second over IPv6, you may want to return IPv6 peers in the second announce.

> And- if one announce request get an error http status, will it retry?

Yes, but it depends. I believe there is a specific HTTP status code that will make the client consider the tracker dead, and never try it again. This would probably apply to all source IPs though.

> Also, there may be same problem with the `tracker id`. If the tracker reponse different tracker id value to thoses source ips. How will the client deal with it?

I'll have to look closer at that. I was under the impression that tracker id was a setting on the client, not a "cookie" set by the tracker.

**Comment by t3link** [comment]
@arvidn 😀 Thank you! It helps a lot!
