### ISSUE TITLE
python2: ImportError on loading module

### ISSUE THREAD

**Issue by lawnmowerwcd** [arvidn/libtorrent#619]
Version 1.0.7 works but at least since 1.0.9 I get this error when trying to import the python2 module:

    >>> import libtorrent
    ImportError: /usr/lib64/python2.7/site-packages/libtorrent.so: undefined symbol: _ZN5boost6python6detail11init_moduleEPKcPFvvE

The python3 module works. gcc 4.9.3, boost 1.56

**Comment by arvidn** [comment]
I would not be surprised if boost.python needs to be built against the same major version of python as the module. are you rebuilding boost for the different modules?

**Comment by lawnmowerwcd** [comment]
That was a pointer in the right direction. The python2 library gets linked against libboost_python-3.4.so.1.56.0. python3 is evidently my main system python version.

I think the linker somewhere links against the system python version instead of the python version it's compiling for. Might this happen somewhere?

**Comment by lawnmowerwcd** [comment]
Turns out my 1.0.7 had a patch to support compiling for different python versions. I close this issue because this was never intended to work with libtorrent anyway. Sorry for the trouble!
