### ISSUE TITLE
Build Error in Ubuntu 20.03 

### ISSUE THREAD

**Issue by ikonomn** [arvidn/libtorrent#6197]
**Please provide the following information**

libtorrent version (or branch):2.03

platform/architecture:Linux Ubuntu 20.04

compiler and compiler version:gcc 9

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
[build-error.txt](https://github.com/arvidn/libtorrent/files/6453516/build-error.txt)

**Comment by arvidn** [comment]
you don't have `openssl` or `libcrypto` installed.

```
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
```
