### ISSUE TITLE
libtorrent should not collect unlimited dht nodes if dht is disabled

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#6199]
session_impl::add_dht_node()

will always add nodes to the node list if dht is not enabled. This seems to be a ever increasing list with likely many redundant entries because it is called from peer_connection::incoming_dht_port(). 
Over time the same be will add itself again and again.
I think, there should be at least a limit. Maybe it is not necessary to collect nodes at all if dht is disabled.

example: less than 4h
599700 entries -> 16398KB

**Comment by arvidn** [comment]
it should be fixed by this: https://github.com/arvidn/libtorrent/pull/6217
