### ISSUE TITLE
how to get lt::torrent_info from magnet

### ISSUE THREAD

**Issue by libxengine** [arvidn/libtorrent#6202]
libtorrent version (or branch):1.2 vcpkg installed(VS2019)
platform/architecture:win10 x64
compiler and compiler version:vs2019 msvc x86

i am have magnet link.i got lt::torrent_info from torrent file.
but i don't know how to get lt::torrent_info from magnet

**Comment by wrtorrent** [comment]
After `lt::metadata_received_alert` or `lt::state_changed_alert` `case lt::torrent_status::state_t::downloading:`.

**Comment by libxengine** [comment]
do you mean,i have to start downloading if i want to get torrent_info?
i want to get torrent_info before start download,can i?

**Comment by MassaRoddel** [comment]
A magnet linke does not contain torrent info data your have to download it from other peers first.

**Comment by AllSeeingEyeTolledEweSew** [comment]
there's `parse_magnet_uri`, which gives you an `add_torrent_params`. this might be what you want.

a `torrent_info` holds torrent metadata (the info-dict), so you won't have that until you download it.

**Comment by libxengine** [comment]
o ....OK  thanks
