### ISSUE TITLE
is a bug?

### ISSUE THREAD

**Issue by libxengine** [arvidn/libtorrent#6203]
vs2019 msvc x86 ansi
win10 x64
vcpkg install libtorrent
1.2.13-b799640

#include <unordered_map>
#include <libtorrent/create_torrent.hpp>
using namespace std;

typedef struct
{
	std::shared_ptr<lt::create_torrent> pCreator;
}CREATORINFO;

unordered_map<int, CREATORINFO*> stl_MapBTCreator;

void createfile()
{
	lt::create_flags_t m_BTFlags;
	lt::file_storage fs;
	lt::add_files(fs, "D:\\123");

	CREATORINFO* pSt_Creator = new CREATORINFO;

	pSt_Creator->pCreator = std::make_shared<lt::create_torrent>(fs, 0, -1, m_BTFlags);
	stl_MapBTCreator.insert(make_pair(1, pSt_Creator));
}
int main(int argc_, char const* argv_[])
{
	createfile();
	unordered_map<int, CREATORINFO*>::const_iterator stl_MapIterator = stl_MapBTCreator.find(1);
	if (stl_MapIterator == stl_MapBTCreator.end())
	{
	}
	return 0;
}

when i get to unordered_map<int, CREATORINFO*>::const_iterator stl_MapIterator = stl_MapBTCreator.find(1);
is wrong in stl_MapIterator->second->pCreator all value

**Comment by libxengine** [comment]
but i use it like this does not error:
int main(int argc_, char const* argv_[])
{
	lt::create_flags_t m_BTFlags;
	lt::file_storage fs;
	lt::add_files(fs, "D:\\123");

	CREATORINFO* pSt_Creator = new CREATORINFO;

	pSt_Creator->pCreator = std::make_shared<lt::create_torrent>(fs, 0, -1, m_BTFlags);
	stl_MapBTCreator.insert(make_pair(1, pSt_Creator));

	unordered_map<int, CREATORINFO*>::const_iterator stl_MapIterator = stl_MapBTCreator.find(1);
	if (stl_MapIterator == stl_MapBTCreator.end())
	{
	}
	return 0;
}

**Comment by MassaRoddel** [comment]
In the first case, fs is a local variable in createfile(). It is not valid outside that function. create_torrent() uses a reference not a copy.

**Comment by sledgehammer999** [comment]
Unrelated, but this:
```c++
typedef struct
{
std::shared_ptrlt::create_torrent pCreator;
}CREATORINFO;
```

is C-ism. In C++ you don't need to `typedef` a `struct` and the struct name goes like this:
```c++
struct CREATORINFO
{
    std::shared_ptrlt::create_torrent pCreator;
}
```

Also another suggestion: Avoid using raw pointers and doing manual memory management. This:
```c++
CREATORINFO* pSt_Creator = new CREATORINFO;
```

becomes
```c++
std::unique_ptr<CREATORINFO> pSt_Creator = std::make_unique<CREATORINFO>();
// or alternatively to be less verbose but equal to the above
auto pSt_Creator = std::make_unique<CREATORINFO>();
```
and you won't have to remember to `delete` the pointer at all the necessary places. The destructor of `std::unique_ptr` does that for you.

**Comment by libxengine** [comment]
o thanks for you help
