### ISSUE TITLE
Has anyone successfully installed libtorrent in centos8.x?

### ISSUE THREAD

**Issue by libxengine** [arvidn/libtorrent#6213]
sudo dnf install rb_libtorrent-devel -y

package rb_libtorrent-devel-1.2.6-4.el8.x86_64 requires asio-devel, but none of the providers can be installed
  - conflicting requests
  - package asio-devel-1.10.8-7.module_el8.3.0+757+d382997d.i686 is filtered out by modular filtering
  - package asio-devel-1.10.8-7.module_el8.3.0+757+d382997d.x86_64 is filtered out by modular filtering

i want to install through yum ...Feel bad about this problem

**Comment by userdocs** [comment]
I think it would be easier to build it yourself ([but this info can wait](https://github.com/arvidn/libtorrent/blob/RC_1_2/docs/building.rst))

`asio-devel` ? i thought it used `boost-asio`?

What you are trying to use it with, use deluge? this

**Comment by abcfy2** [comment]
`asio-devel` is located in PowerTools repository: https://centos.pkgs.org/8/centos-powertools-x86_64/asio-devel-1.10.8-7.module_el8.3.0+757+d382997d.x86_64.rpm.html

So you must enable `PowerTools repository`, see: https://computingforgeeks.com/enable-powertools-repository-on-centos-rhel-linux/

**Comment by arvidn** [comment]
I would also be suspicious of that dependency on `asio-devel`. libtorrent uses asio out of boost, and I would expect installing boost would be enough (or possible `boost-asio` in case boost is split up into separate packages)

**Comment by libxengine** [comment]
> `asio-devel` is located in PowerTools repository: https://centos.pkgs.org/8/centos-powertools-x86_64/asio-devel-1.10.8-7.module_el8.3.0+757+d382997d.x86_64.rpm.html
> 
> So you must enable `PowerTools repository`, see: https://computingforgeeks.com/enable-powertools-repository-on-centos-rhel-linux/

i try to install PowerTools repository follow this step https://computingforgeeks.com/enable-powertools-repository-on-centos-rhel-linux/...
but is some error,when i execute shell command:sudo dnf search libtorrent
i don't know why....

**Comment by libxengine** [comment]
> I think it would be easier to build it yourself ([but this info can wait](https://github.com/arvidn/libtorrent/blob/RC_1_2/docs/building.rst))
> 
> `asio-devel` ? i thought it used `boost-asio`?
> 
> What you are trying to use it with, use deluge?

I want to facilitate deployment

**Comment by abcfy2** [comment]
You don't need to install `-devel` package, that's OK.

But epel seems not working any more, the libtorrent is too old.

**Comment by libxengine** [comment]
o ,thanks...i am installed by my self.
