### ISSUE TITLE
libtorrent 2.0.x shared build on Android

### ISSUE THREAD

**Issue by 3unjee** [arvidn/libtorrent#6220]
Thanks for all the hard work on libtorrent, it's an incredible piece of technology. 

After succesfully building libtorrent on Android with static linking I wanted to try a shared build for the same platform with the following: `b2 clang-arm -j4 cxxflags="-fPIC -DANDROID" cxxstd=14 variant=release link=shared threading=multi`

Unfortunately this gets me the following:
```
clang-linux.link.dll /home/bunjee/dev/workspace/android/libtorrent/boost/bin.v2/libs/system/build/clang-linux-arm/release/cxxstd-14-iso/threading-multi/visibility-hidden/libboost_system.so.1.71.0
/home/bunjee/dev/workspace/android/libtorrent/../3rdparty/android/NDK/21/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lrt
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Has anyone encountered this before ?

**Comment by userdocs** [comment]
`ld: cannot find -lrt` < This is the problem. I found this https://developer.android.com/ndk/guides/stable_apis#c_library

> Note that on Android, unlike Linux, there are no separate libpthread or librt libraries. That functionality is included directly in libc, which does not need to be explicitly linked against.

Maybe check the pkgconfig files or try linking to libc as it should contain the symbols?

**Comment by arvidn** [comment]
@3unjee can you post the complete command line invoking the linker?
There's nothing in the libtorrent jamfile that links against `librt`. I suspect that the toolset you're using (`clang`) detects linux and assumes it needs to link against `librt`.

However, looking at clang-linux.jam, I don't see anything like that. So, I don't know where the `librt` dependency would come from.

**Comment by 3unjee** [comment]
Here is my `user-config.jam`:
```
import os ;

COMPILER = [ os.environ COMPILER ] ;

using clang : arm : $(COMPILER) ;
```

Here is the log:
```
building boost from source directory:  /home/bunjee/dev/workspace/android/libtorrent/boost
Performing configuration checks
 
    - default address-model    : 64-bit (cached)
    - default architecture     : arm (cached)
...patience...
...patience...
...patience...
...found 3565 targets...
...updating 2 targets...
clang-linux.link.dll /home/bunjee/dev/workspace/android/libtorrent/boost/bin.v2/libs/system/build/clang-linux-arm/release/cxxstd-14-iso/threading-multi/visibility-hidden/libboost_system.so.1.71.0
/home/bunjee/dev/workspace/android/libtorrent/../3rdparty/android/NDK/21/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lrt
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
 
    "/home/bunjee/dev/workspace/android/libtorrent/../3rdparty/android/NDK/21/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang++"   -o "/home/bunjee/dev/workspace/android/libtorrent/boost/bin.v2/libs/system/build/clang-linux-arm/release/cxxstd-14-iso/threading-multi/visibility-hidden/libboost_system.so.1.71.0" -Wl,-soname -Wl,libboost_system.so.1.71.0 -shared -Wl,--start-group "/home/bunjee/dev/workspace/android/libtorrent/boost/bin.v2/libs/system/build/clang-linux-arm/release/cxxstd-14-iso/threading-multi/visibility-hidden/error_code.o"  -Wl,-Bstatic  -Wl,-Bdynamic -lrt -Wl,--end-group -fPIC -pthread -std=c++14 -fvisibility=hidden -fvisibility-inlines-hidden 
 
...failed clang-linux.link.dll /home/bunjee/dev/workspace/android/libtorrent/boost/bin.v2/libs/system/build/clang-linux-arm/release/cxxstd-14-iso/threading-multi/visibility-hidden/libboost_system.so.1.71.0...
...skipped <pbin/clang-linux-arm/release/cxxstd-14-iso/threading-multi>libtorrent-rasterbar.so.2.0 for lack of <p/home/bunjee/dev/workspace/android/libtorrent/boost/bin.v2/libs/system/build/clang-linux-arm/release/cxxstd-14-iso/threading-multi/visibility-hidden>libboost_system.so.1.71.0...
...failed updating 1 target...
...skipped 1 target...
```

**Comment by arvidn** [comment]
so, this happens when linking `libboost_system`. Maybe it has a reference to it.

**Comment by arvidn** [comment]
are you using clang or GCC btw? you seem to be using the `clang` toolset, but libboost_system appears to have been built with GCC.

**Comment by userdocs** [comment]
What i would like to know is what `b2 clang-arm`  is or does. This does not seem valid? When i cross compile on Alpine to arm i needed to do this

```
b2 toolset=gcc-arm
```
And in my `user-config.jam`
```
using gcc : arm : aarch64-linux-musl-g++ ;
```

https://www.boost.org/doc/libs/1_76_0/tools/build/doc/html/index.html#bbv2.tasks.crosscompile

Does he not have to do something like this but for clang / android / arm??

**Comment by arvidn** [comment]
`toolset` is an implicit feature, you can omit the `toolset=` part. just like `variant=` can be omitted and you can just say `debug` or `release`. This only works because there are only so many valid values for implicit features, and they aren't allowed to overlap.

**Comment by 3unjee** [comment]
> are you using clang or GCC btw? you seem to be using the `clang` toolset, but libboost_system appears to have been built with GCC.

This actually happens *while* building `libboost_system`, but I'm building b2 with gcc. Here's the complete function:
```
buildAndroid()
{
    cd boost/tools/build/src/engine
 
    sh build.sh gcc
 
    cd ../../../../../libtorrent
 
    # FIXME libtorrent 1.2.6 Linux: It seems b2 returns an error code, even when it succeeds.
    set +e
 
    b2 clang-arm -j4 cxxflags="-fPIC -DANDROID" cxxstd=14 \
		     variant=release \
 		     threading=multi \
                     link=shared \
 
    set -e
 
    cd ..
 
    sh deploy.sh $1
 
    # NOTE: We remove this folder to force a new architecture check.
    rm -rf boost/libs/config/checks/architecture/bin
    rm -rf boost/bin.v2
 
    rm -rf libtorrent/bin
}
```

**Comment by userdocs** [comment]
Maybe it's this

https://github.com/arvidn/libtorrent/issues/4592

**Comment by 3unjee** [comment]
> Maybe it's this
> 
> #4592

You mean my boost version is too old ?

**Comment by userdocs** [comment]
In your function you have this comment

>  # FIXME libtorrent 1.2.6 Linux: It seems b2 returns an error code, even when it succeeds.

My issue was for the same thing #4592

The boost build dev explain it. If you are using v1.2.6 you have this `include clang_tidy.jam` in your `Jamroot.jam`

https://github.com/boostorg/build/issues/585

**Comment by 3unjee** [comment]
> In your function you have this comment
> 
> > FIXME libtorrent 1.2.6 Linux: It seems b2 returns an error code, even when it succeeds.

Ah yes, good to know it's been fixed. That's unrelated to this issue though :).

**Comment by userdocs** [comment]
yeah sorry it's not specific to the issue I just recognised the problem. 

Specific to your problem, I think taking into account where arvidn is saying it does not look related to the jamfile then I would suggest you look at the pkgconfig files of some of the other shared libs you are building against.

It seems as though one of your shared libs is perhaps loading this, maybe something else built.

So i'd look at those to see if you can find what is trying it link `-lrt` using grep or something.

```
grep -r '-lrt' path/to/your/lib/dir
```

**Comment by aldenml** [comment]
@3unjee, just for testing, I changed the android github action to `link=shared`, and seems to build fine.

https://github.com/aldenml/libtorrent/commit/d8830f2fdf9f1b677cffc8e9449b87fe9800e5f4#diff-b46b6cdc887427355980140454172d7b5ff3dd1f68523667bdd4947358d927d8R65

https://github.com/aldenml/libtorrent/runs/2667320361#step:6:201

**Comment by arvidn** [comment]
@3unjee you may want to try these:

```
toolset=clang-linux-arm target-os=android
```

**Comment by 3unjee** [comment]
> @3unjee you may want to try these:
> 
> ```
> toolset=clang-linux-arm target-os=android
> ```

Thanks ! Adding `target-os=android" fixed the `-lrt` thing for me: `b2 clang-arm -j4 cxxflags="-fPIC -DANDROID" cxxstd=14 variant=release link=shared threading=multi target-os=android `

**Comment by arvidn** [comment]
I'm not particularly experienced with android development. On the one hand, apps probably don't share code between them (except the runtime perhaps), which is one of the main benefits of shared libraries. If you could link *everything* statically (except the runtime perhaps) you could disable `-fPIC` and save CPU and power by not needing a PLT or GOT. Although, with 64 bit processors I would think at least the GOT can be implemented quite efficiently.

On the other hand, all apps have to use Java on android, right? which means you still need to build everything as a shared library for Java to be able to load it. Which means you still need `-fPIC`, so it's probably a wash.
