### ISSUE TITLE
Existing files are being overwritten

### ISSUE THREAD

**Issue by sakkamade** [arvidn/libtorrent#6221]
**Please provide the following information**

libtorrent version (or branch): `RC_1_2` through qBittorrent

platform/architecture: Arch Linux x64
compiler and compiler version: cmake 3.20.2 (although I believe it's all irrelevant)

Hello. I have come  here from https://github.com/qbittorrent/qBittorrent/issues/127. 
Slightly relevant issue https://github.com/arvidn/libtorrent/issues/3695.

**The Issue**
 Problem is regarding two files/folders of identical names (two identical paths).

If I will start downloading a torrent while setting its download location to one where the name of downloading file/folder  already exists, application would overwrite existing content without any warning.

Pithy: steps to reproduce are
1. Have the "filename1.jpg" under the path `/home/user/downloads/`
2. Start downloading the torrent containing the "filename1.jpg" into aforementioned path
3. Observe absence of  former file 

--------------------------------------------

I see couple of global solutions:
1. Silently append "_1" or " (1)", etc. to downloading file/folder names
3. Add the torrent to the list, however prevent the start of downloading, and display some status-error, which will inform of situation and suggests the user to rename the content manually. (Thus, user will decide wether to do Recheck or Rename.)

**The first and main step**, of course, is that that libtorrent should survey every single name  within the folder for presence of identical to torrent's file/folder names before start of downloading.

One of hurdles to overcome in thoughtful solution would be that, after checking names within directory, if folder's name already exists, but  files in it are not, what actions should be?
Something like silent merging of such folders? Or the same as in solutions `#1` or `#2`?

**Comment by arvidn** [comment]
> I see couple of global solutions:
> 
>     1. Silently append "_1" or " (1)", etc. to downloading file/folder names

How would you envision this would work if you add a torrent, download half of it. Shut down and start back up again. In order to resume the torrent, the existing files need to be used. If you would select a different download directory every time you restart the client, you would keep re-downloading the files over and over again.

So, I think this rule would have to be more sophisticated. Only under certain circumstances would you rename the download directory.

>     2. Add the torrent to the list, however prevent the start of downloading, and display some status-error, which will inform of situation and suggests the user to rename the content manually. (Thus, user will decide wether to do Recheck or Rename.)

This would also solve the issue of how to distinguish whether the intention is to resume a download or not.

> **The first and main step**, of course, is that that libtorrent should survey every single name within the folder for presence of identical to torrent's file/folder names before start of downloading.

This is already done. It's required for libtorrent to know which files need to be checked to establish which pieces have already been downloaded.

> One of hurdles to overcome in thoughtful solution would be that, after checking names within directory, if folder's name already exists, but files in it are not, what actions should be?
> Something like silent merging of such folders? Or the same as in solutions `#1` or `#2`?

I'm not quite sure I'm following this. when you say "merging folders", do you mean the current behavior of resuming a download into existing files on disk?

**Comment by sakkamade** [comment]
> > 1. Silently append "_1" or " (1)", etc. to downloading file/folder names
>
> How would you envision this would work if you add a torrent, download half of it. Shut down and start back up again. 

Right, I didn't consider such situation. 👍

> > ... after checking names within directory, if folder's name already exists, but files in it are not, what actions should be?
> 
> I'm not quite sure I'm following this. when you say "merging folders", do you mean the current behaviour of resuming a download into existing files on disk?

For example, download location, which does not contain files from the torrent, has following structure
```
─ folder1 ┬ folder1.1
          └ folder1.2 ┬ folder2.1
                      └ folder2.2
```
Torrent has following
```
┬ folder1 ┬ folder1.1 ─ filename1.jpg
│         ├ folder1.3 ─ filename2.jpg
│         └ filename3.jpg
└ filename4.jpg
```

1. Should the torrent's content be written into directories  "folder1", "folder1.1",  and the root of download location? 
2. Otherwise the status-error should be displayed?

**Comment by arvidn** [comment]
(2) won't work. because it won't be possible to resume a download. I think that would be a bigger problem than the current one.

**Comment by sakkamade** [comment]
Ah, indeed. After the same logic as 
> ... In order to resume the torrent, the existing files need to be used. If you would select a different download directory every time you restart the client, you would keep re-downloading the files over and over again.

**Comment by sakkamade** [comment]
> (2) won't work. because it won't be possible to resume a download.

Why? I am talking about the situation when no files from the torrent exists in the disk, but partial paths of the files.
If only some of the files already present, or were downloaded partly  before, such error will  be displayed likewise, no?

**Comment by arvidn** [comment]
> Why? I am talking about the situation when no files from the torrent exists in the disk, but partial paths of the files.

By "partial paths" you mean, there are only directories, no files, right?

The reason it won't work is because that is a valid state of a torrent that was started in a previous session. How can you tell the difference between some other process creating the directories, and a previous libtorrent session creating the directories?

> If only certain filenames already present (identical paths), or some of the files were downloaded partly before, such error will be displayed likewise, no?

There is no error. The download is resumed. Are you suggesting there *should* be an error when attempting to resume a download?

**Comment by sakkamade** [comment]
> The reason it won't work is because that is a valid state of a torrent that was started in a previous session. 

Understood.
> There is no error. The download is resumed. Are you suggesting there should be an error when attempting to resume a download?

So libtorrent is (or will be?) able to tell the difference between file from the torrent, together with partially downloaded file, and just the file with the same name?

**Comment by arvidn** [comment]
> So libtorrent is (or will be?) able to tell the difference between file from the torrent, together with partially downloaded file, and just the file with the same name?

No, it can't do that today. If you have any ideas, I'd be interested. But I don't think it's so easy.

The one thing I can think of is a new flag you can set in `add_torrent_params` where you essentially say: "if there are any existing files for this torrent, error out instead of resume".

**Comment by sakkamade** [comment]
> The one thing I can think of is a new flag you can set in add_torrent_params

I guess this may be the only choice to prevent every case of data loss. 

However, some option which would be possible to use as default one, which will not interfere normal usage, and which will minimise the occasion of data loss, should not be set aside.

**Comment by sakkamade** [comment]
> The one thing I can think of is a new flag you can set in `add_torrent_params` ...

Yes, this will be it for normal usage. 

But when the torrent is downloaded partially (only one file of it), and then the rest of the torrent will be chosen to be downloaded, would it be possible to prevent overwriting of the rest of the files, if some of its filenames already exists, but these files are not from the torrent?

**Comment by sakkamade** [comment]
And I would also like to regard the case from this commentary https://github.com/qbittorrent/qBittorrent/issues/127#issuecomment-17459215.

1. User already has completely downloaded file from the torrent. 
2. However user will add the torrent to download to another location (which doesn't contain completed file). 
3. The torrent then will be downloaded to certain extent, e.g. 1%, and user decides to change the download location of this torrent to the one with completed file.
4. In the end, user would obtain a single file downloaded on 1%, being that the new file will be moved, and completed file will be overwritten by it.

**Comment by arvidn** [comment]
That use case is supported by removing the torrent and adding it back with a new `save_path`. That is a separate case from *moving* the storage though. Moving storage has these options:

http://libtorrent.org/reference-Torrent_Handle.html#move-storage

**Comment by welp-ops** [comment]
Perhaps we can do something similar to the venerable `rsync`: In the resume file, store the size and last modified time of each partially downloaded file (perhaps this data is already stored). On resume, check that each file has the same size and last modified time as it is expected to as per the resume file, and recheck it if not.
