### ISSUE TITLE
ut pex and seed flag

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#6225]
libtorrent version (or branch): master

For some time now, I was wondering why my client sees many connected seed which have payload going to them and they did not have the pieces my client wanted. Finally, I tracked it down to ut pex and its seed flag. Seems libtorrent puts to much trust into that flag and there is only the case handled if it is set but not the case if it is not set. Once the seed flag is set there are not many cases which would set it back.
Maybe, there needs to be a trust count/voting or similar before that information is used further.
i.e. if 10 different peers say it is a seed while only 3 peers say it is not

**Comment by MassaRoddel** [comment]
Just checked BEP0011 and it say that bit
0x02 indicates seed/**upload_only**.
Doesn't that break the idea of a seed flag? 
Shouldn't libtorrent change the way it uses that flag if it can mean **upload_only**?

**Comment by arvidn** [comment]
Right, the peer sending the pex message, may lie about the peers being seeds. It would seem the main victims are the peers who aren't seeds but the peer sending the pex message say they are anyway. Iirc, the only thing the seed flag is used for is to *not* connect to the peers if we are also a seed or in upload-only mode.

You have a good point though, that the network suffers is a peer is lying about this. Also, of course, the upload-only mode can change, but I would expect it to mostly mean someone setting some file(s) priorities' to zero.

Maybe libtorrent should just ignore the seed flag in pex messages. iirc, we introduced this to be able to connect downloaders and seeds a lot quicker, avoiding seed-to-seed connections.

**Comment by MassaRoddel** [comment]
Another thing that confused me was that libtorrent reported several connected seeds but the number of distributed copies was less than one.
It might be a good idea to ignore that flag.
As a simple workaround, I clear this flag in the ut_pex plugin now.

**Comment by arvidn** [comment]
> Doesn't that break the idea of a seed flag?
> Shouldn't libtorrent change the way it uses that flag if it can mean upload_only?

You mean because a peer can go from being "upload-only" to then downloading?

**Comment by MassaRoddel** [comment]
A seed flag means that a peer has all pieces - so it should have all the pieces a downloader wants. So that you could assume that it is possible to complete the download. 
At least in my client I use the seed flag from the peer_info for the UI.
In my client's peer list for a torrent - the seed flag created these wrong statements like:
peer is a **seed** and has **0%** of what I want.
(not to mention that there is upload to a seed)

**Comment by arvidn** [comment]
I see what you mean. That flag was intended to avoid or de-prioritize redundant connections when oneself is a seed. But I suppose it could make sense to prioritize peers we think may be seeds when we're still downloading too.

**Comment by arvidn** [comment]
does this make sense? https://github.com/arvidn/libtorrent/pull/6232

also, despite what the BEP say about the seed flag, libtorrent only sets it when the peer is truly a seed.

**Comment by Seeker2** [comment]
So how do I get multiple peers claiming to be seeds at the same time in qBitTorrent when seeding myself?

**Comment by MassaRoddel** [comment]
> 
> 
> does this make sense? #6232
> 
> also, despite what the BEP say about the seed flag, libtorrent only sets it when the peer is truly a seed.

Afaik, the problem is that this flag gets set before libtorrent connects to the peer and it is not cleared if libtorrent connects to the peer and learns that it is not a peer. Seems to me there is no code to clear this flag, except for the have-none message or a special case for the incoming bitfield message. (master branch)
If we receive seed flags via pex for unconnected peers it is very likely that flag remains set forever.

**Comment by MassaRoddel** [comment]
> 
> 
> So how do I get multiple peers claiming to be seeds at the same time in qBitTorrent when seeding myself?

We talk about the case here, there other peers claimed via pex that those are seeds. 

I did not check the case (yet) there you add yourself to the pex message with the seed flag set.
Basically, claiming via pex that you are a seed.

**Comment by arvidn** [comment]
> Afaik, the problem is that this flag gets set before libtorrent connects to the peer

Right, my patch addresses that, by not setting the flag in the `peer_list` just based on the `pex_seed` flag.

> and it is not cleared if libtorrent connects to the peer and learns that it is not a seed. Seems to me there is no code to clear this flag, except for the have-none message or a special case for the incoming bitfield message.

In the patch, I think it's fine to never clear it, since it's only set if the peer actually says it's a seed now.

> (master branch)
> If we receive seed flags via pex for yet unconnected peers it is very likely that flag remains set forever.

Right. But I don't think this is the case with my patch.

**Comment by MassaRoddel** [comment]
Btw, are there really clients which would use the extension flag "upload_only" and put that data into the ut pex message as seed/upload_only flag?
Or is there another way for a peer to get to know if a connected peer is in upload_only mode?

**Comment by arvidn** [comment]
> Btw, are there really clients which would use the extension flag "upload_only" and put that data into the ut pex message as seed/upload_only flag?

I don't know.

> Or is there another way for a peer to get to know if a connected peer is in upload_only mode?

There is the `upload_only` extension message as well as the upload-only field in the extension handshake.

**Comment by Seeker2** [comment]
I would expect an upload-only peer to disconnect from my seed and certainly not accept significant uploading from my seed.

**Comment by arvidn** [comment]
sometimes upload-only peers are peers whose disk filled up, and the disk space frees up. Or someone de-selecting certain files, and then selecting them.

I believe uTorrent will set the seed flag for any peer that's upload-only. It seems with the current logic will then blindly assume any peer received via pex with the seed flag, is in fact a seed. Not even if we connect to it and learn that it isn't a seed, will this flag be cleared. This will result in the local client misclassifying the peer as a "seed" (despite it only being upload-only). More importantly, even if the peer is no longer upload-only, libtorrent will still propagate it as-if it was a seed when it sends pex messages.

**Comment by Seeker2** [comment]
I'm seeing at least 25% of all connected peers doing this.
It is clearly not the result of either a rare or contrived condition.

**Comment by arvidn** [comment]
Whenever a torrent has padfiles, I think peers will end up in upload only rather than seeding

**Comment by Seeker2** [comment]
No padfiles in the torrents I'm on, but one in particular that's seriously prone to this problem is a poorly-seeded public torrent that's over 100 GB and has about 500 files.
I suspect due to its large size, slow download speed, and number of files...many people are marking files as "don't download" and other file priority.

**Comment by arvidn** [comment]
adressed here https://github.com/arvidn/libtorrent/pull/6232
