### ISSUE TITLE
Can't build Python bindings

### ISSUE THREAD

**Issue by khokm** [arvidn/libtorrent#6235]
libtorrent version (or branch): RC_2_0

platform/architecture: Windows 7 x64

compiler and compiler version:
gcc 9.20 (minGW)
B2 4.4-git

I'm trying to build python library using next command from `bindings/python` directory:
```
b2 release --toolset=gcc libtorrent-link=static boost-link=static stage_module stage_dependencies
```
As result there `./dependencies` folder and two dll's in it: 
```
libboost_python38-mgw9-x64-1_76
libtorrent-rasterbar.dll
```
but `libtorrent` file doesn't appear in current directory.

**Comment by arvidn** [comment]
I think those are the only two files you need. Why do you expect there to be a `libtorrent` file in current directory?

**Comment by arvidn** [comment]
oh, right, the python module itself. `libtorrent.pyd` should be there

**Comment by khokm** [comment]
@arvidn i will try to solve this problem by myself. I am just new in boost and b2 toolchain, so i completely don't understand how it works.
Just for clarification: should i read docs about b2 ["buildfile" format](https://build2.org/build2/doc/build2-build-system-manual.xhtml) or Boost.build [Jamfiles](https://www.boost.org/doc/libs/1_76_0/tools/build/doc/html/index.html#bbv2.overview.jam_language)? Is this a different formats? Are "b2" and "build2" the same or i just misunderstanding and this is different build systems?

**Comment by arvidn** [comment]
it's `b2`, or boost-build. They are different tools.

Do you get any error messages?

`b2` creates a tree of subdirectories for each build configuration. Sometimes these paths can get too long for what windows supports. Yo mitigate that you may have to pass `--hash` to the `b2` command line. But I would think there would be a pretty clear error message in that case.

**Comment by arvidn** [comment]
oh, btw. You're not supposed to say `--` in front of `toolset`. in `b2` all build features are specified as *name*=*value*.

`toolset=gcc` is the same kind of build configuration as `libtorrent-link=static`

**Comment by arvidn** [comment]
I don't have mingw set up on my windows machine, but when building with msvc, I also need to say `address-model=64`, because python requires 64 bit ABI I believe

**Comment by khokm** [comment]
First strings of build using `b2 release toolset=gcc libtorrent-link=static boost-link=static stage_module stage_dependencies` output contains this:
```
[1] gcc-9.2.0
...patience...
...patience...
...patience...
...patience...
...found 9163 targets...
...updating 411 targets...
```
After about a hour of building it ends with:
```
...failed updating 21 targets...
...skipped 2 targets...
...updated 387 targets...
```
`\dependencies` directory appears, `libtorrent.pyd` still not.
Are there any ways to run build only for python buildings, not rebuild whole project including boost files?

**Comment by arvidn** [comment]
what kinds of warnings?
you could search for "error: ", that's GCC's pattern for error messages.

**Comment by khokm** [comment]
There are many `note:` messages. And many `error:` messages with same description:
```
...\AppData\Local\Programs\Python\Python38\Include/pyerrors.h:317:20: error: '_vsnprintf'
is not a member of 'std'; did you mean 'isprint'?
```
Tried to add cxxstd=14 parameter. Same error.

**Comment by khokm** [comment]
The problem lies in `pyerrors.h`:
```C
#if defined(MS_WIN32) && !defined(HAVE_SNPRINTF)
# define HAVE_SNPRINTF
# define snprintf _snprintf
# define vsnprintf _vsnprintf
#endif
```
I suppose the error is specific to `gcc` (and other compilers except `msvc`).
Maybe should try to define  `HAVE_SNPRINTF` as workaround. I don't know yet how to define a variable using `b2` params, so I just temporary removed this lines and run build again.
**It finally compiles**, `libtorrent.pyd` appears in this directory.

**Comment by khokm** [comment]
There is another problem: `test.py` fails:
```
======================================================================
ERROR: test_alert (__main__.test_alerts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 546, in test_alert
    print(a.message())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 53: invalid continuation byte

======================================================================
ERROR: test_pop_alerts (__main__.test_alerts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 605, in test_pop_alerts
    print(a.message())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 53: invalid continuation byte

======================================================================
ERROR: test_add_torrent_info_hash (__main__.test_session)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 898, in test_add_torrent_info_hash
    print(a)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 53: invalid continuation byte

======================================================================
ERROR: test_read_resume_data (__main__.test_torrent_handle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 298, in test_read_resume_data
    print(a.message())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 53: invalid continuation byte

----------------------------------------------------------------------
Ran 88 tests in 12.702s

FAILED (errors=4)
```
But `simple_client.py` is working fine. The main problem is solved, but not completely:
 - that we suppose to do with `HAVE_SNPRINTF` bug? Should I research more about this and add possibly make a PR with note to documentation for windows gcc users?
 - what's with test.py ?

**Comment by arvidn** [comment]
I would say the `pyerrors.h` has a bug in that it defines `snprintf` and `vsnprintf`. It should have defined inline functions, or something like that, that doesn't pollute every namespace.

You can defined `HAVE_SNPRINTF` by specifying `define=HAVE_SNPRINTF` on the `b2` command line.

I'm not sure why `test.py` is failing

**Comment by arvidn** [comment]
however, it could be mitigated in `bindings/python/src/boost_python.hpp`, which is libtorrent's wrapper around those includes. It could check `#ifdef snprintf` and `#ifdef vsnprintf` and `#undef` them.

**Comment by arvidn** [comment]
I was just about to address this in libtorrent, but it seems this has been in here for a while already:

https://github.com/arvidn/libtorrent/blob/RC_2_0/bindings/python/src/boost_python.hpp#L28

```
#ifdef snprintf
#undef snprintf
#endif
#ifdef vsnprintf
#undef vsnprintf
#endif
```

Where did you get these errors? Did they happen inside the python headers themselves? If so, I would consider it a python issue.

Or did it happen in boost.python's headers? if so, I would consider it a boost.python issue.
