### ISSUE TITLE
Questions regarding DHT sanitizing

### ISSUE THREAD

**Issue by the8472** [arvidn/libtorrent#6236]
I have been looking at some DHT traffic again and noticed some new... creative behavior from nodes. I wanted to ask whether libtorrent happens to be immune to this.

The two interesting cases I have seen so far

A) full UDP reflections

```
[TRACE]  213.34.163.254:50239 <- d1:ad2:id20:⢑⠠Q⣵⠈[t3*⢠yj⠻⣑⣀M⡿⣛⣸96:target20:⢱⣗⠐⡗z⢏⡘⣋<⡯⣫⡍⣝⠕⡯Q⡫⢕⣅Me1:q9:find_node1:t8:y%⡭⠩⣝⠉S⠗1:v4:cr␀␀1:y1:qe
[TRACE]  213.34.163.254:50239 -> d1:ad2:id20:⢑⠠Q⣵⠈[t3*⢠yj⠻⣑⣀M⡿⣛⣸96:target20:⢱⣗⠐⡗z⢏⡘⣋<⡯⣫⡍⣝⠕⡯Q⡫⢕⣅Me1:q9:find_node1:t8:y%⡭⠩⣝⠉S⠗1:v4:cr␀␀1:y1:qe
```

B) node ID reflection

```
[TRACE]   35.167.186.212:6881 <- d1:ad2:id20:⢑⠠Q⣵⠈[t3*⢠yj⠻⣑⣀M⡿⣛⣸96:target20:⢱⡯⣾n⡫⣏`⢁#⣽⣸⡍a`⢋⣈%⠑⠹Je1:q9:find_node1:t8:⠟⢏Ra⣾⠱⡇41:v4:cr␀␀1:y1:qe
[TRACE]   35.167.186.212:6881 -> d1:rd2:id20:⢑⠠Q⣵⠈[t3*⢠yj⠻⣑⣀M⡿⣛⣸95:nodes0:e1:t8:⠟⢏Ra⣾⠱⡇41:v4:LT⢀⢀1:y1:re
```

The cases can be handled by dropping requests and responses which contain the local node ID and treating them as bogus or timeouts for the purpose of routing table maintenance or lookup procedures.

In case you're already implementing the [expected ID](https://github.com/the8472/mldht/blob/master/docs/sanitizing-algorithms.rst#user-content-expected-id-for-rpcs) checking / [ID mismatch oracle](https://github.com/the8472/mldht/blob/master/docs/sanitizing-algorithms.rst#user-content-id-mismatch-oracle) then one can also insert the socket / node ID pair into the oracle if
* it's a transaction-ID checked response
* remote id == local ID

That reduces repeat queries in scenario B). Well, doing it in case A) might be possible too but I haven't tested that yet.

**Comment by MassaRoddel** [comment]
Case A might not be a DHT specific thing. I have seen total reflection for normal Bittorrent traffic too. Actually, those servers seem to reflect everything.

**Comment by ssiloti** [comment]
Libtorrent's routing table rejects messages with the local node ID so there shouldn't be any problems there.

Incoming requests and lookups do not check for this though. In the full reflection case the local node will end up responding to its own request in a four way exchange.
