### ISSUE TITLE
dht_put.cpp "mget" command not working

### ISSUE THREAD

**Issue by thierryba** [arvidn/libtorrent#6243]
**Please provide the following information**

libtorrent version (or branch):
2.0.3

platform/architecture:
macOS 11
compiler and compiler version:
 Xcode (clang) 12

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
I compiled dht_put.cpp. First I had to fix the code that loads the sessions params because it would fail otherwise. I even commented out this thing.
then I ran
1. dht_put gen-key dht.key 
2. dht_put mput dht.key fooo 
`bootstrapping`
`bootstrap done.`
`MPUT public key: 59578eea1b424fce4ab3557f14efc44a39f7b9040b1f409245e8bbba87d29e23 [salt: ]`
`DHT put complete (success=1 key=59578eea1b424fce4ab3557f14efc44a39f7b9040b1f409245e8bbba87d29e23 sig=cf5f18a4b14814bf4ff293dd56a83216130c72823b338b75bea203d1bc7a62f5ec338905d53bfd452645633ca786387532ec4098d3cc55f8c2df49150b66460c salt= seq=1)`
3. dht_put mget 59578eea1b424fce4ab3557f14efc44a39f7b9040b1f409245e8bbba87d29e23
but this gives me 
`bootstrapping`
`bootstrap done.`
`MGET 59578eea1b424fce4ab3557f14efc44a39f7b9040b1f409245e8bbba87d29e23 [salt: ]`
`auth: <uninitialized>`

Am I doing something wrong?

**Comment by arvidn** [comment]
are you confident you successfully bootstrap? I don't think `dht_get` has any check to fail in case it can't find any nodes.
This tool is not quite as good as one might hope. The fact that it's very short lived means it is likely to have issues bootstrapping, and find a good place in the network and grow a healthy routing table. These things happen over time.

**Comment by arvidn** [comment]
could you give this patch a try? https://github.com/arvidn/libtorrent/pull/6252

The main change is to not break when there's an empty state file. But it also adds options for more verbose logging.

**Comment by thierryba** [comment]
Well that fixes the problem with having no .dht file. The rest still feels fragile. Sometimes it works, sometimes not. I'm leaving 1 process open and doing mput in a loop and it rarely goes to sequence #2... and then it goes back to 1.
In parallel I'm doing an mget and that's the same: it rarely works out of the box.
I'll try with bootstrap-dht to see if I can manage that with my own bootstrap node.

**Comment by arvidn** [comment]
yeah, I experience the same issue, that it sometimes works and sometimes not. I think it's all rooted in the putting process doesn't bootstrap enough before attempting the put. When I was testing this, once my `mput` went through, my `mget`s were reliable. But probably because my saved off DHT routing table was good.

**Comment by thierryba** [comment]
ok fair enough. I suppose there is not much more to it then. Thanks for having a look.
