### ISSUE TITLE
block_uploaded_alert rises before block is actually sent

### ISSUE THREAD

**Issue by 90felipe09** [arvidn/libtorrent#6247]
libtorrent version (or branch): v.1.2

platform/architecture: any, Windows/Linux

compiler and compiler version: MSVC, cLang, GNU

From what i've read from [documentation](https://libtorrent.org/reference-Alerts.html#block_uploaded_alert), this alert has the following property:

```
This alert is posted when a block intended to be sent to a peer is placed in the send buffer. Note that if the connection is closed before the send buffer is sent, the alert may be posted without the bytes having been sent to the peer. It belongs to the alert_category::upload category.
```

I'm implementing a use case in my graduation assignment  that needs an alert that rises when the block is actually uploaded. From what i've seen, in stackoverflow, [there are people that are also interested in this functionality](https://stackoverflow.com/questions/66759797/libtorrent-block-upload-alert). 

Also, in [another stackoverflow related question](https://stackoverflow.com/questions/13919367/get-alerts-for-upload-activity-with-libtorrent-rasterbar), arvidn suggested that it could be done with:

```
The closest thing you have to alerts is probably stats_alert. It will tell you the number of payload bytes uploaded. It won't give you the granularity of a full block being sent though.

If you'd like to add an alert, have a look at bt_peer_connection::write_piece.

patches are welcome!
```

I'm interested in implementing this patch and i'm just opening this issue in order to register that it's being implemented and also discuss about the best way to accomplish it. For example:

- This would be a welcome feature to the libtorrent project or it is somewhat of a specific issue that doesn't justify a PR to an oficial version of libtorrent?
- This change would better suit by changing when `block_uploaded_alert` is raised or it would be better to implement a new alert? (Something like... block_sent_alert).
- Please, some hints about how to achieve this? And also hints about `how not to do this`.

**Comment by arvidn** [comment]
I think just making the `block_uploaded_alert` post later would make it unamgiuously more useful. Presumably that point would be when it's been accepted by the kernel send buffer (which is still before it's actually sent).

The stats counters for sent bytes are updated in the callback of `async_write_some()`, which can be found [here](https://github.com/arvidn/libtorrent/blob/RC_2_0/src/peer_connection.cpp#L6379).

There is some logic in `bt_peer_connection.cpp` to keep track of *payload* and *protocol overhead* bytes in the send buffer, to keep accurate counters for those. Perhaps that would be something that could be extended for this. You'll find that [here](https://github.com/arvidn/libtorrent/blob/RC_2_0/src/bt_peer_connection.cpp#L3721).

Keep in mind that this is in the critical path of calls that happen *very* frequently when uploading at high rates. So it's important to be careful to not do very expensive things here.
