### ISSUE TITLE
torrent_error_alerts crash when posted from torrent ctor  

### ISSUE THREAD

**Issue by geiseri** [arvidn/libtorrent#6249]
I have a torrent that when loaded fails in `torrent::initialize_merkle_trees()` which is called from `torrent` ctor.  When it goes to post the `torrent_error_alert` the `get_handle()` uses `shared_from_this()` which in turn throws a `std::bad_weak_ptr`

https://github.com/arvidn/libtorrent/blob/f9836137acf97a2422a1a551860368229bc43912/src/torrent.cpp#L8986

In my case, this exception was thrown inside of an `add_torrent_async` and was swallowed by a session error alert. In an ideal world, the ctor could queue the alert until it was finished, but that looks like it would make things very convoluted when this is called outside of the ctor.  In reality, the best you could do is swallow the `std::bad_weak_ptr` in around that post and let the logging sort it out.  I am not sure how useful the alert would be on its own without the torrent handle populated.

**Comment by arvidn** [comment]
Yeah, it's problematic to attempt to report this error with `set_error()` here: https://github.com/arvidn/libtorrent/blob/RC_2_0/src/torrent.cpp#L7415

**Comment by arvidn** [comment]
just to be clear; the torrent you're loading *is* invalid, right?

**Comment by arvidn** [comment]
I believe this fixes the issue. would you mind giving it a try?
https://github.com/arvidn/libtorrent/pull/6253

**Comment by geiseri** [comment]
Yes, the torrent was invalid so this seems to have addressed the actual crash.   Sorry for the delay.
