### ISSUE TITLE
[Question] How to set asio-debugging=on ?

### ISSUE THREAD

**Issue by tuxayo** [arvidn/libtorrent#6266]
Hi :)

https://github.com/arvidn/libtorrent/issues/4510#issuecomment-609497496
> Do you think you could build libtorrent with asio-debugging=on? i.e. -DTORRENT_ASIO_DEBUGGING

For another issue, I'm searching how to enable this.

I have a script that builds a package that has this part:
```
  cmake \
    -B "_build" \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DCMAKE_INSTALL_PREFIX="/usr" \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -Dpython-bindings=ON \
    -Dboost-python-module-name="python" \
    ./
  make -C "_build"
```
I tried to add
-DTORRENT_ASIO_DEBUGGING=1
-DTORRENT_ASIO_DEBUGGING=ON
-DTORRENT_ASIO_DEBUGGING=on

But I always end up with
```
CMake Warning:
  Manually-specified variables were not used by the project:

    TORRENT_ASIO_DEBUGGING
```

**Comment by arvidn** [comment]
if you build with `b2` you add `asio-debugging=on` to the command line. Otherwise you make sure the preprocessor macro `TORRENT_ASIO_DEBUGGING` is defined on the build command line. with cmake, I believe you would do something like `-DCMAKE_CXX_FLAGS=-DTORRENT_ASIO_DEBUGGING`

**Comment by tuxayo** [comment]
Unfortunately that didn't do it. With qBittorrent, there should be a lot a output when starting it from the command line after a few minutes right?

Here is the full libtorrent build & packaging script in case that helps.

```
# Maintainer: Chocobo1 <chocobo1 AT archlinux DOT net>

pkgname=libtorrent-rasterbar-1_2-git
pkgver=r16804.gbf5d475a6
pkgrel=1
pkgdesc="A feature complete C++ bittorrent library (git branch RC_1_2)"
arch=('i686' 'x86_64')
url="https://www.libtorrent.org/"
license=('BSD')
depends=('boost-libs' 'openssl')
makedepends=('git' 'boost' 'cmake' 'python' 'python-setuptools')
provides=('libtorrent-rasterbar')
conflicts=('libtorrent-rasterbar')
options=('!strip')
source=('git+https://github.com/arvidn/libtorrent.git#branch=RC_1_2')
sha256sums=('SKIP')


pkgver() {
  cd "libtorrent"

  _rev=$(git rev-list --count --all)
  _hash=$(git rev-parse --short HEAD)
  printf "r%s.g%s" "$_rev" "$_hash"
}

build() {
  cd "libtorrent"

  cmake \
    -B "_build" \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DCMAKE_INSTALL_PREFIX="/usr" \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -Dpython-bindings=ON \
    -Dboost-python-module-name="python" \
    -DCMAKE_CXX_FLAGS=-DTORRENT_ASIO_DEBUGGING \
    ./
  make -C "_build"
}

package() {
  cd "libtorrent"

  make -C "_build" DESTDIR="$pkgdir" install
  install -Dm644 "LICENSE" -t "$pkgdir/usr/share/licenses/libtorrent-rasterbar"
}

```

**Comment by arvidn** [comment]
make it print the actual command line invocations of the compiler to see what's being passed in.

You probably need to define `TORRENT_ASIO_DEBUGGING=1`. i.e. not just define it, but set it to 1.

**Comment by arvidn** [comment]
the debug ooutput is printed to the terminal on shutdown, not at startup
