### ISSUE TITLE
MSVC seems unhappy with libtorrent 2.0.4

### ISSUE THREAD

**Issue by 3unjee** [arvidn/libtorrent#6277]
I'm building a library against libtorrent using MSVC and C++17 (libtorrent was built with C++14) and I get the following:
```
cl -c -nologo -Zc:wchar_t -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zc:__cplusplus -O2 -MD -std:c++17 -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -DSK_TORRENT_LIBRARY -DWIN32_LEAN_AND_MEAN -DBOOST_ALL_NO_LIB -DQT_LATEST -DSK_DESKTOP -DNDEBUG -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -D_WINDLL -I..\..\..\src\SkTorrent -I. -I..\..\..\include\SkCore -I..\..\..\include\SkCore\private -I..\..\..\include\SkGui -I..\..\..\include\SkGui\private -I..\..\..\include\SkTorrent -I..\..\..\include\SkTorrent\private -I..\..\..\include -I..\..\..\..\3rdparty\win64\Qt\5.15.2\include -I..\..\..\..\3rdparty\win64\Qt\5.15.2\include\QtQuick -I..\..\..\..\3rdparty\win64\Qt\5.15.2\include\QtGui -I..\..\..\..\3rdparty\win64\Qt\5.15.2\include\QtANGLE -I..\..\..\..\3rdparty\win64\Qt\5.15.2\include\QtQmlModels -I..\..\..\..\3rdparty\win64\Qt\5.15.2\include\QtQml -I..\..\..\..\3rdparty\win64\Qt\5.15.2\include\QtNetwork -I..\..\..\..\3rdparty\win64\Qt\5.15.2\include\QtCore -Irelease -I/include -I..\..\..\..\3rdparty\win64\Qt\5.15.2\mkspecs\win32-msvc -Forelease\ @C:\Users\bunjee\AppData\Local\Temp\WTorrentEngine.obj.21264.250.jom
WTorrentEngine.cpp
..\..\..\include\libtorrent/file_storage.hpp(238): warning C4003: not enough arguments for function-like macro invocation 'max'
..\..\..\include\libtorrent/file_storage.hpp(236): error C2589: '(': illegal token on right side of '::'
..\..\..\include\libtorrent/file_storage.hpp(238): error C2062: type 'unknown-type' unexpected
..\..\..\include\libtorrent/file_storage.hpp(238): error C2737: 'public: static __int64 const libtorrent::file_storage::max_file_size': 'constexpr' object must be initialized
..\..\..\include\libtorrent/file_storage.hpp(236): error C2789: 'libtorrent::file_storage::max_file_size': an object of const-qualified type must be initialized
..\..\..\include\libtorrent/file_storage.hpp(236): note: see declaration of 'libtorrent::file_storage::max_file_size'
..\..\..\include\libtorrent/file_storage.hpp(238): error C2059: syntax error: ')'
```
Full log is here: https://ci.appveyor.com/project/3unjee/sky/builds/39661275/job/sofk2ki67947lmd9

Has anyone encountered something similar before ?

**Comment by 3unjee** [comment]
This seems to be related: https://stackoverflow.com/questions/13416418/define-nominmax-using-stdmin-max

**Comment by FranciscoPombal** [comment]
You should define `NOMINMAX` when building your project (this is what qBittorrent does, for instance).

@arvidn

Do you think libtorrent should use and propagate the `NOMINMAX` define on MSVC? e.g.:

```cmake
target_compile_definitions(torrent-rasterbar
    # other defines
    PUBLIC
        $<$<BOOL:${MSVC}>:NOMINMAX>
    # other defines ...
)
```

Or could there be some consumers of the library that would have problems with that?

**Comment by arvidn** [comment]
I'm not sure. It would probably benefit most people, because this arcane behavior on windows most likely trips up more people than it helps. It's quite weird that they haven't retired this yet.

On the other hand, the people that *actually* use this would probably be quite frustrated with some 3rd party library being opinionated about *their* code.

Part of me feel like; if microsoft wants to make life hard for people developing for windows, who am I to try to stop them? It's kind of expected of anyone developing for windows to know about these traps and work around them, Trying to meddle with that can be risky too.

All that said, I think it would make sense for public libtorrent headers to defend against the `min` and `max` macro. And I think this should be fixable in the header file.

**Comment by arvidn** [comment]
@3unjee Would you mind testing this patch? https://github.com/arvidn/libtorrent/pull/6278

**Comment by 3unjee** [comment]
> @3unjee Would you mind testing this patch? #6278

Will do, I think it's a valid workaround indeed.

**Comment by 3unjee** [comment]
> Part of me feel like; if microsoft wants to make life hard for people developing for windows, who am I to try to stop them? It's kind of expected of anyone developing for windows to know about these traps and work around them, Trying to meddle with that can be risky too.
It's surreal something like that happens *still* happens on the latest Visual Studio environment.

Already had to deal with winsock2 issues in the past with the famous `WIN32_LEAN_AND_MEAN` flag.

**Comment by arvidn** [comment]
merged
