### ISSUE TITLE
Libtorrent implement - help

### ISSUE THREAD

**Issue by Lontron** [arvidn/libtorrent#6279]
Hello. 

Sorry to bother you. Want me to ask if you don't want to try implementing libtorrent in the new torrent server?  Unfortunately YouROK doesn't have time for implementation right now, libtorrent engine is better than anacrolix engine.

Source code for Torrserver Matrix stream torrent http: 
https://github.com/YouROK/TorrServer

Source code to be able to implement libtorrent-go in android: https://github.com/i96751414/libtorrent-go

Thank you for the help.

**Comment by Lontron** [comment]
@arvidn

**Comment by arvidn** [comment]
I don't think you mean "implement". I am implementing *BitTorrent* in *libtorrent*.
If you're asking if I have time to work on TorrServer, the answer is "no".
