### ISSUE TITLE
Couldn't add v2 torrent with previously stored "resume data"

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#6280]
libtorrent RC_2_0 with "deprecated functions" enabled.

When you add a pure v2 torrent from a .torrent file and the infohash is also specified in the `add_torrent_params` (for example, if you use previously saved "resume data"), it fails due to a infohash mismatch. The problem is that you replace the missing v1 infohash with a truncated v2 infohash, which later fails the check when comparing with the metadata, because the metadata does not have any v1 infohash (we have a pure v2 torrent).

https://github.com/arvidn/libtorrent/blob/abd51db4918d0714e509ed46b77a8e2c70d4a56d/src/session_handle.cpp#L402-L403

**Comment by arvidn** [comment]
was the resume data also saved by libtorrent-2.0? or from an older version?

**Comment by glassez** [comment]
>was the resume data also saved by libtorrent-2.0? or from an older version?

By exactly the same version.
But it doesn't matter. The point is that infohash is set in the add_torrent_params.

**Comment by arvidn** [comment]
I'll try to add test coverage for this.

**Comment by glassez** [comment]
When `add_torrent_params.info_hash` isn't set it is assigned from `add_torrent_params.info_hashes.get_best()`. Then if `add_torrent_params.info_hashes.v1` isn't set it is assigned from  `add_torrent_params.info_hash` which is seems to be incorrect.

**Comment by glassez** [comment]
> was the resume data also saved by libtorrent-2.0? or from an older version?

Older version couldn't save v2 infohash.

**Comment by arvidn** [comment]
what I'm worried about is clients that want to add a magnet link by setting *just* `info_hash`. That needs to refer to a v1 torrent. I'll need test coverage for this case too, to ensure I don't break it.

I think the intention was that resume data, saved by libtorrent 2.0 would always include "info_hashes" as well. The test `params.info_hashes.v1.is_all_zeros()` should probably *also* ensure that `params.info_hashes.v2.is_all_zeros()`. It's the v2-only feature of this torrent that breaks it.

**Comment by glassez** [comment]
I don't really care much about this issue, since it's about "deprecated functions ON". I discovered it by accident, and decided to report it, since someone else might be exposed to it.

**Comment by arvidn** [comment]
this is addressed here: https://github.com/arvidn/libtorrent/pull/6287
