### ISSUE TITLE
ed25519 keypair cannot used with python binding

### ISSUE THREAD

**Issue by qinghon** [arvidn/libtorrent#6286]
**Please provide the following information**

libtorrent version (or branch):
RC_2_0

platform/architecture:
linux/amd64

compiler and compiler version:
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

The keypair generated by `ed25519_create_keypair` in libtorrent is different from the keypair generated by python using pynacl

in libtorrent
```
seed: 829ee32a86b93d3766df28d8d77069fdc04e05b17fb095043c72a56d846d0372
# generated
pub_key: b5ed5efc01b59d13708efa6186a6b11df026e1f5f66d417492c795bbc53211ee
secret_key: d80f1dd2960eb009dfddc59869cfdfdcc7f1b53eced672bb44ec5a1ed5bb4b6b782b47fb7767f2d231dc37d84acaf1097ebd82636568e69a85759f9a13d274df
```
in https://github.com/orlp/ed25519
```
seed: 829ee32a86b93d3766df28d8d77069fdc04e05b17fb095043c72a56d846d0372
pub: b5ed5efc01b59d13708efa6186a6b11df026e1f5f66d417492c795bbc53211ee
sec_key: d80f1dd2960eb009dfddc59869cfdfdcc7f1b53eced672bb44ec5a1ed5bb4b6b782b47fb7767f2d231dc37d84acaf1097ebd82636568e69a85759f9a13d274df
```

but in python for pynacl or golang for crypto/ed25519 
```
seed: 829ee32a86b93d3766df28d8d77069fdc04e05b17fb095043c72a56d846d0372
pub: b5ed5efc01b59d13708efa6186a6b11df026e1f5f66d417492c795bbc53211ee
sec_key: 829ee32a86b93d3766df28d8d77069fdc04e05b17fb095043c72a56d846d0372b5ed5efc01b59d13708efa6186a6b11df026e1f5f66d417492c795bbc53211ee
```

I want to know who should be the standard？
or just export ed25519 from libtorrent to python binding?

**Comment by arvidn** [comment]
is it a problem that libtorrent's derivation of a keypair differs from python and go?
As far as I can tell, there's nothing in the DHT protocol that depends on this derivation method, as long as they keyes you get are still valid and in the same format.

**Comment by qinghon** [comment]
Thanks Reply！

This is the problem, the keypair I created using pynacl after put_mutable_item failed to verify on another client using the same code, the error code is `206 invalid signature`
I will paste the test code

**Comment by qinghon** [comment]
@arvidn this is test code using python binding

https://gist.github.com/qinghon/2e1ac878d9f468fcdb216181d6ba9eb7
```shell
# terminal 1
python3 main.py

# terminal 2
python3 main.py -p 6881
```
canbe see error log in terminal 1, but pynacl verifyed this message in terminal 2 top
```
<== [127.0.0.1:6881] { 'a': { 'id': '10539f5d610c176b131d3984d3f6682552bfedb6', 'k': 'b5ed5efc01b59d13708efa6186a6b11df026e1f5f66d417492c795bbc53211ee', 'seq': 1, 'sig': 'd18d40b9843e2983ec5511c086282029c942e54b8f84d555f4...f1985b04', 'token': 'aac5b34c', 'v': 'abcd' }, 'q': 'put', 't': '2fb9', 'v': '4c540203', 'y': 'q' }
==> [127.0.0.1:6881] { 'e': [ 206, 'invalid signature' ], 'ip': '7f0000011ae1', 'r': { 'id': 'd7d09e06002f87836558aefe40d18ed78ad19e23', 'p': 6881 }, 't': '2fb9', 'v': '4c540203', 'y': 'e' }
```

**Comment by aldenml** [comment]
I will do some keygen later with `libsodium` to see what's the output, but there are a few vector tests taken from `libgcrypt` https://github.com/arvidn/libtorrent/blob/RC_2_0/test/test_ed25519.cpp#L72.

I do have a question: I see you get the key via `signing._signing_key`, but that looks like a private field access, is that the way to get the signing key serialized via public API?

**Comment by aldenml** [comment]
@qinghon `libsodium` outputs the same as `pynacl` (as expected). I found this interesting post https://blog.mozilla.org/warner/2011/11/29/ed25519-keys/ that explains the differences between `NaCl` and `SUPERCOMP`. So you can not use the `sk` provided by `pynacl` in the libtorrent DHT operations. The good news is that the `seed` is "practically" the private key. I see two options:

1- `libtorrent` expose some form of `ed25519_create_keypair` in the API.
2- You compute a compatible `sk` from the `seed`.
```cpp
hasher512 hash({reinterpret_cast<char const*>(seed), 32});
std::memcpy(private_key, hash.final().data(), 64);
private_key[0] &= 248;
private_key[31] &= 63;
private_key[31] |= 64;
```
@arvidn any thoughts?

**Comment by qinghon** [comment]
@aldenml 
> I do have a question: I see you get the key via `signing._signing_key`, but that looks like a private field access, is that the way to get the signing key serialized via public API?

no, because `pynacl` does not have a public API to export `secret_key`, only `seed` and `verify_key` are public. I don’t know why it is designed this way, but I have no other way.

**Comment by aldenml** [comment]
@qinghon is the cpp code in my previous comment easy to translate to python?

**Comment by qinghon** [comment]
> @qinghon is the cpp code in my previous comment easy to translate to python?

yes, easy, but need test

**Comment by qinghon** [comment]
@aldenml May I ask if there is a safety or performance difference between `SUPERCOMP` and `NaCl`?
If yes or no, is there a third option: replace `SUPERCOMP` used by `libtorrent`?

**Comment by aldenml** [comment]
only the encoding of the private key (from the seed) is different, the rest is the same in terms of the mathematical construction, of course, particulars implementations differ in speed and safety. I doubt changing the assumption that code should be based on SUPERCOMP ref10 in `libtorrent` is an option, but I imagine we can provide some helper function for these "encoding" conversions.

**Comment by qinghon** [comment]
Before this issue any changed, this is a temporary solution for `python`

```python
import hashlib
from nacl.signing import SigningKey

def covert_seed_to_private(seed: bytes) -> bytes:
    assert len(seed) == 32
    sec_key = bytearray(hashlib.sha512(seed).digest())
    sec_key[0] &= 248
    sec_key[31] &= 63
    sec_key[31] |= 64
    return bytes(sec_key)

pub_key = SigningKey(seed).verify_key.encode()
sec_key = covert_seed_to_private(seed)
```
