### ISSUE TITLE
tracker error: timed out, error code 36

### ISSUE THREAD

**Issue by fmike7** [arvidn/libtorrent#6291]
libtorrent version (or branch): 1.2.6
platform/architecture: Windows/32 bit
compiler and compiler version: Visual C++ 2019

Running into this intermittent issue, unclear why. tracker_error_alert comes in with "timed out" in tracker_error_alert::error::message() and code 32 in tracker_error_alert::error::value(). I looked up code 36 and it translates to EDEADLK errno and ERROR_SHARING_BUFFER_EXCEEDED Win32 error. None of these make sense to me in this context.

Any suggestions here?

**Comment by arvidn** [comment]
Error code objects has a category as well. It's not necessarily a win32 error code.

To get the human readable message, call message() on it.

**Comment by fmike7** [comment]
Got it, thanks for explaining! The message() returns a simple "timed out". I guess it means the tracker really times out (network outage etc).

**Comment by fmike7** [comment]
I have a follow-up question on this.

I currently have the tracker_completion_timeout set to 90 (the default is 30, in my understanding), however, it still results in intermittent "timed out" errors. When I run a very simple test (curl or powershell script) on the same machine against the same tracker URL, and it works perfectly. 

I also see there is another parameter called tracker_receive_timeout. I currently don't set it. What is the default and do you think it would help the situation if I try to set it to something higher than the default?

Any other tracker-related parameters that might help the situation?

P.S. Still using version 1.2.6. Maybe something had been fixed since then.

**Comment by arvidn** [comment]
[tracker_receive_timeout](http://libtorrent.org/reference-Settings.html#tracker_receive_timeout) is probably the one you want to change. It is a shorter timeout to detect stalls. i.e. if the tracker doesn't send *anything* in this time (default 10 seconds) it's considered stalled and times out.

The [tracker_completion_timeout](http://libtorrent.org/reference-Settings.html#tracker_completion_timeout) is the upper limit on how long to wait for the complete response. If bytes are being received at a trickle, haven't completed the response in this time, it's also considered timed out.

**Comment by fmike7** [comment]
got it, thanks, will give it a shot!
