### ISSUE TITLE
why there is no `can_disconnect` in `bt_peer_connection.cpp` 

### ISSUE THREAD

**Issue by joriscarrier** [arvidn/libtorrent#6292]
libtorrent version (or branch): 2.0.4

Hi i try to create my own peer_plugin and manage disconnection but, even if i return false in the `can_disconnect()` method, disconnection still occur (The peer is upload only, and we are upload only.)

```c++
		// if we're finished and this peer is uploading only
		// disconnect it
		if (t->is_finished() && upload_only()
			&& m_settings.get_bool(settings_pack::close_redundant_connections)
#ifndef TORRENT_DISABLE_SHARE_MODE
			&& !t->share_mode()
#endif
			)
			disconnect(errors::upload_upload_connection, operation_t::bittorrent);
```

>  I saw `settings_pack::close_redundant_connections` can solve my probleme

why `bt_peer_connections` don't use `can_disconnect` method in parent `peer_connection` ?

thanks in advance.

**Comment by arvidn** [comment]
I can't think of a good reason not to use `can_disconnect()` there.

**Comment by arvidn** [comment]
something like this? https://github.com/arvidn/libtorrent/pull/6310
