### ISSUE TITLE
HTTP tracker over proxy

### ISSUE THREAD

**Issue by fmike7** [arvidn/libtorrent#6294]
We are trying to implement a proxy between our clients and the tracker. We don't have control over the tracker, because it managed by AWS (using S3's torrent tracker implementation).

1) Some people say that the GET /announce?ip=1.2.3.4 will be ignored by most standard trackers because it is easy to use for tracker DOS attacks as one can easily send multiple requests with spoofed IPs and "trash" the tracker. Instead, most trackers determine the client's IP from the TCP connection's socket. Does libtorrent use this parameter at all when making the tracker announce requests? I guess it does not, but I wanted to confirm.

2) Given that &ip most likely will be ignored by the tracker, it does not make sense for our proxy to add &ip with the client's IP from the socket. Hence goes (3) below.

3) Would the use of X-Forwarded-For do the trick? Such as libtorrent makes a request (no "IP" parameter), the proxy detects the client's IP, packs it into X-Forwarded-For HTTP header, and sends the request to the tracker. Is this even a viable scenario?

The questions are probably too generic since the tracker we use is really a black box and I don't have much knowledge about its implementation. But any general thoughts would be appreciated.

**Comment by arvidn** [comment]
> Does libtorrent use this parameter at all when making the tracker announce requests? I guess it does not, but I wanted to confirm.

Generally, no. There's an exception (just for backwards compatibility) for private torrents when using both IPv4 and IPv6.

> Would the use of X-Forwarded-For do the trick? Such as libtorrent makes a request (no "IP" parameter), the proxy detects the client's IP, packs it into X-Forwarded-For HTTP header, and sends the request to the tracker. Is this even a viable scenario?

I very much doubt it would, for the same reason trackers ignore `&ip=`.
it sounds like what you want to do is essentially, tell the tracker: "I promise there is a peer at this IP and this port. I can't prove it and you can't know whether I'm launching an attack or not, but, pretty please!"

If you can "trick" the tracker into accepting some 3rd party peer, I wouldn't think it's sustainable. You just discovered a vulnerability in the tracker, and it would probably be fixed soon.

One think you could do is to *be* the tracker yourself. You could connect peers announcing to the same info-hash to each-other. You could announce *yourself* to the tracker, and collect peers connecting to you in your "tracker". i.e. you would have to be a bit more of an active middle-man.

**Comment by fmike7** [comment]
But doesn’t it mean accessing trackers via proxy is a complete non-starter in the first place? Why there is even such an option to use a tracker proxy in libtorrent when technically it is not possible, because the IP address has to be direct and real?

**Comment by arvidn** [comment]
If you proxy both tracker connections *and* peer connections, it's not a problem. Because then other peers will connect to you via the proxy.

**Comment by arvidn** [comment]
also, some people don't mind not being reachable by other peers, they are just interesting in finding peers that are reachable, and only make outgoing connections.

**Comment by fmike7** [comment]
Right! Now this makes sense to me. Thanks for explaining it.
