### ISSUE TITLE
Seed rank oscillates when we are the only seed causing queued seeds to repeatedly pause/resume

### ISSUE THREAD

**Issue by thrnz** [arvidn/libtorrent#6302]
This is regarding libtorrent 1.2.14, although 2.0 appears to use the same code.

When seeding a number of torrents with 0 other seeds, torrents appear to regularly oscillate between seeding and queued.

If I understand [this code](https://github.com/arvidn/libtorrent/blob/33a10d5a723a6c27d9baee7d9bf2028eb81c88ed/src/torrent.cpp#L8575-L8636) right, a torrent with 0 seeds gets a boost to it's seed ranking causing it to generally get priority over other torrents. However, once seeding begins, the torrent appears to no longer be considered 'seedless' as the tracker will now report a single seed (ie us), and will no longer get a boost to its seed rank when its next recalculated (I assume after `auto_manage_interval`), causing it to become queued again. It will then be considered seedless again after the next `auto_manage_interval` and so on.

Ideally libtorrent might consider a torrent to have 0 seeds for the purpose of calculating the seed rank if the tracker reports a single seed and it is currently seeding (ie. we are that single seed).

C++ isn't my thing, so forgive the psuedocode, but this
https://github.com/arvidn/libtorrent/blob/33a10d5a723a6c27d9baee7d9bf2028eb81c88ed/src/torrent.cpp#L8625
Might be changed to something like:
```if (seeds == 0) or (seeds == 1 && currently_seeding)```

A semi-workaround I've been using for the time being is to set `stop_tracker_timeout` to 0, so the tracker still reports a single seed when scraped even once we've stopped. So after a while, all 'seedless' torrents will be considered to have a single seed and will no longer oscillate until the tracker no longer considers us a seed.

**Comment by wrtorrent** [comment]
try set 'active_seeds' to -1 (assume you not exceed 500 of `active_limit`)

**Comment by thrnz** [comment]
Uncapping the number of active seeds kind of defeats the purpose of queueing and [seeding based on demand](https://www.libtorrent.org/manual-ref.html#seeding-queue).

I rebuilt libtorrent having changed 
https://github.com/arvidn/libtorrent/blob/33a10d5a723a6c27d9baee7d9bf2028eb81c88ed/src/torrent.cpp#L8625

to:

```if (seeds == 0 || (seeds == 1 && !is_paused())```

and it no longer flip-flops between queued and seeding when it's the only seed.

**Comment by wrtorrent** [comment]
not work like utorrent
libtorrent active_seeds=3 mean all 10 downloaded files gonna be seeded, not just 3

**Comment by arvidn** [comment]
@thrnz this is an interesting case I hadn't considered. I wonder if there's some elegant way to solve this by simply deducting ourself from the scrape data. Presumably this same issue applies to other states as well. If we're downloading, maybe it would make sense to deduct 1 from the `incomplete` counter.

Would you mind proposing your patch as a PR?

**Comment by arvidn** [comment]
I imagine an alternative solution would be to remove the boost rank for seedless torrents. Would it make sense to remove that?

**Comment by thrnz** [comment]
I think keeping the rank boost for seedless torrents is still a good idea. Seeding data that's unavailable elsewhere should probably remain a priority.
