### ISSUE TITLE
consider to drop client name/version guessing code

### ISSUE THREAD

**Issue by Kolcha** [arvidn/libtorrent#6306]
libtorrent version (or branch): RC_2_0
platform/architecture: linux/amd64
compiler and compiler version: GCC 10.2.1

libtorrent has code to identify (mostly guess) client and its version based on peer id. this code relies on some kind of dictionary which is very outdated and inaccurate for now. moreover, there are client using the same prefix but different version numbers. corresponding function is also marked as deprecated.

in case of plugins (extensions), real client name is know even at `on_bitfield()` or first `on_have_all()` call, so I think guessing it on handshake (or maybe even earlier, I didn't read code too thoroughly) is redundant and confusing.

I do not suggest to completely remove mentioned function (to keep ABI compatibility), removing this line is enough:
https://github.com/arvidn/libtorrent/blob/f2eefd327f1ca89b053eb1e5f4ed229efe52e47f/src/bt_peer_connection.cpp#L3523

this just will lead to empty `client` field in `peer_info` struct until remote peer introduce itself, but this is reasonable.

**Comment by wrtorrent** [comment]
Would not prefer empty `client` fields.
Configurable option?

**Comment by arvidn** [comment]
I agree that `identify_client()` isn't all that useful. it's already deprecated in 2.0.
@Kolcha in your mind, what's the main benefit of *not* setting `m_client_version`?
In case the client doesn't send an extension handshake, or doesn't send the `v` field, it seems better than nothing, right?
I think one issue right now is that there's really no way to tell the difference between a name the client sent and a name guessed via this function.

**Comment by Kolcha** [comment]
@arvidn issue you mentioned (no way to find the difference between guessed and received name) was the main reason for opening this issue...
maybe the option to change this behavior will be better rather than just disabling guessing

**Comment by Kolcha** [comment]
considered not actual anymore, closing this issue to not leave it as abandoned
