### ISSUE TITLE
Node ID and Node IP Change

### ISSUE THREAD

**Issue by cyrillicw** [arvidn/libtorrent#6308]
As I understand, knowing Node ID allows me to get its IP by querying find_node. But Node ID itself depends on IP, so if the node's IP changes, its Node-ID will change too. Is there a way to be able to find a node's IP knowing its 'Public Key' - some identifier which is invariant for each node?

**Comment by arvidn** [comment]
I can't think of a way. If you know the node is running your software, there are some things one could explore:

* encode identifying information in the lower bits of the Node ID (only the top 32 bits depdend on the IP, iirc). Then you could search the space of the upper bits. Although, it could end up being a large space to search.
* don't make your Node ID depend on the IP, but maybe derive it from a key instead. The risk with this is that other nodes may not trust you as much
* periodically publish your Node ID under a public key as a "mutable put" in the DHT network. People wanting to find you could then look that up

**Comment by cyrillicw** [comment]
Great! Thank you! I thought about the third option too :)
