### ISSUE TITLE
vcpkg port for libtorrent v2

### ISSUE THREAD

**Issue by TheCelebrimbor** [arvidn/libtorrent#6309]
Hi, there is no port of `libtorrent` v2 in vckpg repo. 

Referencing to this issue https://github.com/microsoft/vcpkg/issues/18192
seems like it would be better to create a new port called `libtorrent2 `

Is this in the works or something ?

**Comment by FranciscoPombal** [comment]
Working on it...

**Comment by TheCelebrimbor** [comment]
hi @FranciscoPombal is there any projected time that this will converge ?

**Comment by arvidn** [comment]
what is missing from libtorrent 2.0, preventing this from "just working" with the current cmake file?

**Comment by pythagoras9** [comment]
libtorrent 2.0 uses submodules. The current portfile of libtorrent 1.2 in vcpkg uses vcpkg_from_github() to download the code as a zip and then build it. vcpkg_from_github() does not download submodules. So the build fails. The general approach is to either publish the submodules themselves as packages and make libtorrent take dependency on them or have the submodules as part of the same repo

**Comment by FranciscoPombal** [comment]
@TheCelebrimbor

Sorry about the delay. I got busy with other stuff, and I don't have much time to deal with this right now.

If someone wants/can deal with this in the meantime, you are more than welcome to do so.

As stated previously, the main problem are the submodules.
At a minimum, one needs to either also publish [try_signal](https://github.com/arvidn/try_signal) to vcpkg and say that building with GnuTLS is not supported for now (to avoid having to deal with `asio-gnutls` as well), or deal with the submodule downloads internally.
This was the best source I was able to find as a general guideline for the latter approach: https://github.com/microsoft/vcpkg/issues/1036#issuecomment-299608663.

**Comment by vktr** [comment]
Hi! I have a vcpkg overlay for libtorrent-2.0.3 in a repo here - https://github.com/picotorrent/server/tree/main/vendor/vcpkg-overlays/ports/libtorrent. It works for Linux and macOS builds (untested on Windows). While I don't have the time to upstream any changes to microsoft/vcpkg, it might serve as a base for someone who does 😄

**Comment by pythagoras9** [comment]
@vktr Your overlay-port was pretty helpful! I have created a PR for libtorrent2 in vcpkg. Any issues you can identify would be very helpful [https://github.com/microsoft/vcpkg/pull/22697](https://github.com/microsoft/vcpkg/pull/22697) .. Logs to the azure build [https://dev.azure.com/vcpkg/public/_build/results?buildId=66214&view=artifacts&pathAsName=false&type=publishedArtifacts](https://dev.azure.com/vcpkg/public/_build/results?buildId=66214&view=artifacts&pathAsName=false&type=publishedArtifacts)
