### ISSUE TITLE
Question : How to check if torrent failed to connect or download?

### ISSUE THREAD

**Issue by bemaru** [arvidn/libtorrent#6321]
libtorrent version (or branch): 1.2.3

platform/architecture: windows10 x64

compiler and compiler version: vs2015(v140)

I'm designing to try to download a file with torrent and if it fails, download with http(not torrent) or try downloading again with torrent.

How can I determine if a torrent connection or download has failed?

**Comment by arvidn** [comment]
> How can I determine if a torrent connection or download has failed?

It depends on your definition of failed. Perhaps you wait for some time, and if you haven't completed the download yet, you consider it failed.

In a peer-to-peer system like bittorrent, there is never a definitive "failure". There's always a chance some peer will show up that you can connect to and download from. There is no way of knowing for sure.

**Comment by bemaru** [comment]
I also had a similar thought to the answer, so I was wondering if there is another way. I will review the download failure criteria appropriate for our program. Thanks for the good answer.
