### ISSUE TITLE
Question: Setting to change tracker and DHT announce interval.

### ISSUE THREAD

**Issue by showstoppre** [arvidn/libtorrent#6322]
Quick question, is there a setting to setup trackers and DHT announce interval so that the peer list are updated more often.

On another note, is there is any negative impact of querying trackers and DHT for peers frequently.

**Comment by arvidn** [comment]
> is there a setting to setup trackers and DHT announce interval so that the peer list are updated more often.

There's [min_announce_interval](http://libtorrent.org/reference-Settings.html#min_announce_interval) and [dht_announce_interval](http://libtorrent.org/reference-Settings.html#dht_announce_interval).

> is there is any negative impact of querying trackers and DHT for peers frequently.

Yes, you increase the load of the network, possibly with questionable benefits.

**Comment by showstoppre** [comment]
Thanks. I'm clear about dht_announce_interval.

Correct me if I'm wrong. But min_announce_interval comes to play only when a tracker doesn't respond with announce_interval or if tracker announce interval is smaller is than our setup. Is there any option that overrides the announce_interval sent by tracker regardless whether it is small or large.

**Comment by wrtorrent** [comment]
some trackers can ban if you announce too often

**Comment by showstoppre** [comment]
aw I see. thanks for the information.
