### ISSUE TITLE
V2 torrents fail on similar torrents

### ISSUE THREAD

**Issue by geiseri** [arvidn/libtorrent#6323]
First off, I apologize if this is my bad understanding of v2 torrents that have the BEP-38 "similar" field defined.  My issue is in: 
https://github.com/arvidn/libtorrent/blob/ce367476e29cd2987bfd30c828328a8f72185bf1/src/resolve_links.cpp#L112

Now it might be my misunderstanding of BEP-52, but I was given the impression that they didn't have a  "pieces" entry, just the "piece layers".  When I migrated my code to only support  V2 torrents my code broke  at:
https://github.com/arvidn/libtorrent/blob/ce367476e29cd2987bfd30c828328a8f72185bf1/include/libtorrent/torrent_info.hpp#L503

Because at: https://github.com/arvidn/libtorrent/blob/ce367476e29cd2987bfd30c828328a8f72185bf1/src/torrent_info.cpp#L1363 it will fall through without setting a value for: `m_piece_hashes`.    It looks like the culperate is that https://github.com/arvidn/libtorrent/blob/ce367476e29cd2987bfd30c828328a8f72185bf1/src/torrent_info.cpp#L1065 needs to become aware of V2 "piece layers" as well as v1 "pieces"

**Comment by geiseri** [comment]
depends on PR #6329

**Comment by geiseri** [comment]
bump

**Comment by arvidn** [comment]
oh, sorry, I must have missed this when you first posted it. I think you're right, the logic supporting the "similar" feature probably doesn't handle v2 torrents correctly.

**Comment by arvidn** [comment]
@geiseri would you mind taking a look at this patch? https://github.com/arvidn/libtorrent/pull/6686

**Comment by geiseri** [comment]
@arvidn yes, sorry for the delay.  I will test today.
