### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [arvidn/libtorrent#6324]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by arvidn** [comment]
thanks! I added one here: https://github.com/arvidn/libtorrent/pull/6325

**Comment by JamieSlome** [comment]
E-mail sent!

**Comment by xavier2k6** [comment]
@arvidn Was the vulnerability legitimate? - if yes, has it been resolved?

**Comment by arvidn** [comment]
No, I don't consider it a problem. One of the developer python scripts uses os.system() and can be made to execute whatever you put on the command line.

If you're running the script, you may as well run your shell code directly
