### ISSUE TITLE
Updating mutable torrents

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6337]
@arvidn A simple question. Scenario:
User uses a link, downloads a mutable torrent. Torrent stays in his program in the seeding status.
Then the torrent changes.
Will the user's torrent be updated?
If not, what should I do so the program checks for updates? Is there something ready?

**Comment by arvidn** [comment]
there is nothing that does this built into libtorrent. There is a BEP that was implemented in uTorrent to check an RSS feed, or something similar. I didn't implement it in libtorrent as it's difficult to make something like that secure, when the user can't necessarily trust the .torrent file.

Once an update is detected, that torrent is simply added to the session as well, and it will reuse files that are identical and already in the session.

The new torrent should have a "similar" field containing the info-hash of the previous torrent (or possibly all previous versions). Alternatively, the collection of all versions can be given a name and have all torrents have the "collections" field with that name, creating an association.

**Comment by master255** [comment]
@arvidn I guess that's my mistake. When I said mutable torrents, I meant https://www.libtorrent.org/dht_store.html.

I thought I saw an example of a magnet link to download such torrents before. Now I can't find it. Maybe there is some mechanism for opening torrents from DHT? When we get not torrent file via magnet link, but its hash.

The good news is that I invented two new scenarios to use dht_store. I don't have time to write an article about it, but if interested, I can tell about it in telegram chat.

**Comment by arvidn** [comment]
the DHT store feature is not associated with torrents. It's a way to store arbitrary data in the DHT. You can write a program that polls and refreshes a mutable put blob, storing an info-hash, and whenever it changes add that torrent to the session.

**Comment by master255** [comment]
@arvidn Ok. Thank you.
