### ISSUE TITLE
DHT over Proxy

### ISSUE THREAD

**Issue by daimoniuma** [arvidn/libtorrent#6388]
Peers witch was found through DHT are not connecting through proxy if option to send all data through proxy was enabled. It makes disclosure for Internet providers. Some of them detect signature of Torrent blobs and cut a speed.

**Comment by arvidn** [comment]
do peers discovered via other means (like trackers) connect over the proxy?
do peers discovered via the DHT connect if you disable the proxy? If so, do you discover the same peers?

**Comment by daimoniuma** [comment]
Yes, proxy is working. I disabled DHT and all is fine. The same peers can share with me at acceptable speed (300+ kB/s) while DHT is not working and poor speed (1 kB/s) while trackers not working (without proxy denied by proviator) and DHT working only.

**Comment by daimoniuma** [comment]
Proxy is SOCS5. Some peers continues to send Torrent blobs directly to me, not through Proxy. If DHT enabled.

**Comment by master255** [comment]
@daimoniuma @arvidn Double the issue: https://github.com/arvidn/libtorrent/issues/6053
