### ISSUE TITLE
Does DHT 'annouce_peer' query always uses 'implied_port' argument?

### ISSUE THREAD

**Issue by showstoppre** [arvidn/libtorrent#6389]
libtorrent version (or branch):
1.1.13

Problem- ~~Occasionally~~ Very often I see a peer from DHT with my IP on 'Port 1'. 

Could it be that a faulty DHT node is capturing the port as 1, instead of the source port of the packet due to the 'implied_port' argument.

If so is it possible to avoid this argument altogether?

Edit - The real issue is that, this creates a duplicate peer entry with false port in DHT. A remote peer with 'allow_multiple_connections_per_ip' set to false, sometimes connection attempts are always made to the the IP with incorrect port 1 and never connects to the actual listening port.

**Comment by arvidn** [comment]
the packets that have `implied_port` enabled also have the `port` field though, right?

**Comment by arvidn** [comment]
you could log the DHT messages to see who's sending this incorrect port

**Comment by showstoppre** [comment]
Thanks for getting back.

> the packets that have `implied_port` enabled also have the `port` field though, right?

I believe the `port` field is set.  Isn't that a mandatory field? I'm using Deluge 1.3.15, not sure how I can check that.

> you could log the DHT messages to see who's sending this incorrect port

Could you please tell me, how to log this. 

Also, I think it shouldn't matter which peer is reporting my port incorrectly in DHT. I could be wrong, but I wonder if this is caused by `implied_port` option and if can be disabled through a flag.

**Comment by showstoppre** [comment]
@arvidn 
I've checked the logs and I can confirm `port` field is set in all announce queries and `implied_port` is always 1.

I'm finding it hard to decode DHT response.

For example:

'values': [ 'k\xb5\x9bv\xd9\x03', 'gk\xc5T\xc8\xd5' ]

Any lead would be appreciated. Thanks

**Comment by arvidn** [comment]
the protocol is documented here: http://bittorrent.org/beps/bep_0005.html

Those values are IPs (4 bytes) and ports (2 bytes). None of those ports look like 1. (`d902` and `c8d5`)

**Comment by showstoppre** [comment]
Sorry about the confusion. Those were sample values. Please find attached the log, with a bad node capturing incorrect port.

[log.txt](https://github.com/arvidn/libtorrent/files/6959425/log.txt)

Log contains - get_peers query and reply before announce, announce_peer query and reply and get_peers query and reply with updated peers capturing incorrect port for my IP.

The only thing I have modified from the log infohash which I removed.

As you can see from the log, this node has responded with 7 peers, with 6 peers having port as '1'.

I understand this is _not a libtorrent issue_, I'm trying to figure out, if by setting implied_port to '0', might help the remote peer capture my port correctly.

Is there a way this can be done in deluge?

**Comment by arvidn** [comment]
> Is there a way this can be done in deluge?

No, you'd have to change the libtorrent source code and rebuild.

**Comment by showstoppre** [comment]
Thanks for confirming. Thats what I thought as well. If I were to change, which part should I be changing.

Is implied_port set through a flag or a function in DHT announce?
