### ISSUE TITLE
Memory corruption in make_magnet_uri()

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#6390]
libtorrent version (or branch): RC_2_0 1d7063210a

platform/architecture: Windows 7 64 sp1

compiler and compiler version: msvc2017 x64

I tested `make_magnet_uri(torrent_handle const& handle)` but I expect `make_magnet_uri(torrent_info const& info)` to have the same problem.
I observed that the function returned different (and wrong) infohash each time it was called on the same torrent. This led me to believe it was accessing invalid memory.

I think the issue is with the const reference to a temporary. Normally this extends the lifetime of the temporary. But I think it doesn't apply when you have multiple temporaries in series.
This code:
```c++
sha1_hash const& ih = handle.info_hashes().v1;
```

works if I remove the reference. However I don't know if that is the ideal solution that's why I don't make a PR.

I presume that the following would also work (I haven't tested it):
```c++
info_hash_t const& info_hashes = handle.info_hashes();
sha1_hash const& ih = info_hashes.v1;
```

Same problem with the v2 code path.

**Comment by sledgehammer999** [comment]
Another suggestion is to capture `handle.info_hashes()` early in the function body and use the same (const ref) variable to do the various if tests. It should be cheaper than constantly asking for it.

**Comment by arvidn** [comment]
Thanks for the report!

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/6392
