### ISSUE TITLE
Hybrid torrents result in torrent_inconsistent_hashes error

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#6394]
libtorrent version (or branch): RC_2_0 10f290ad4d2b63cd3f7abb6a424fbed2db6cb1bc

platform/architecture: Windows 7 sp1 x64

compiler and compiler version: msvc2017 x64

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

1. Add the hybrid torrent from the blog
2. Let it download for a bit. Pause and remove it from session without deleting files.
3. Re-add it to the session. You might need to restart the client before you re-add the hybrid torrent.
4. Now it will recheck the files and wait for some peer connection. As soon as the first peer connection is established (I assume it is the 1st peer connection) the status changes to errored with the `torrent_inconsistent_hashes` error.

It isn't consistent but usually the above steps produce the error after a few tries.

**Comment by sledgehammer999** [comment]
Another observation:
If after the error, I just restart the application the torrent seems to start downloading again without issue.

**Comment by arvidn** [comment]
So this is the case where you add the torrent without resume data, but with partial data on disk, right?

**Comment by sledgehammer999** [comment]
Yes.

**Comment by sledgehammer999** [comment]
any progress on this?

**Comment by arvidn** [comment]
yes, I'm still working through this. it's a bit deeper than I expected (and I haven't had too much time lately)

**Comment by arvidn** [comment]
here's one step towards a solution. https://github.com/arvidn/libtorrent/pull/6415

**Comment by arvidn** [comment]
This is my work in progress to resolve this. I think this patch fixes the issues but I still need to write more tests to ensure it's all covered. But please feel free to try it out.

https://github.com/arvidn/libtorrent/pull/6454
