### ISSUE TITLE
v2 torrents, metadata from mangets and piece layers

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#6395]
I am trying to wrap my mind around the new v2 protocol and I have some questions and maybe some requests.

**Situation:** With v1 magnets we allowed users to save the `.torrent` file as soon as we received the metadata, reacting to `metadata_received_alert`.

Now with v2 torrents we can't do that.
Isn't `piece layers` considered part of the v2 metadata? Or is it a shortcoming of the magnet extension? Aka the extension isn't updated to accommodate v2 torrents?

Can't we get an explicit alert for when `piece layers` are received? Are piece layers always received as a whole or can a peer send a part of them?

**Comment by arvidn** [comment]
It's considered a feature in v2. The block hashes are committed to by a merkle tree root hash in the info-dict. Allowing to defer downloading them. In a v2-only torrent, this makes for smaller metadata and (possibly) shorter start-up times of magnet links.

There are new peer messages to request ranges of the block hashes, but libtorrent only request those on demand. So right now you only get all the hashes once you complete the download.

**Comment by glassez** [comment]
Related Issue: https://github.com/arvidn/libtorrent/issues/6283.
