### ISSUE TITLE
Block Downloaded Peers Notification

### ISSUE THREAD

**Issue by cyrillicw** [arvidn/libtorrent#6396]
Does a node when some block is downloaded notify other peers that it has downloaded a block (and is ready to upload it to other peers)?

**Comment by arvidn** [comment]
Yes. Though the terminology is "piece" for the unit that needs to be fully downloaded before it can be uploaded. A block is 16kiB, and there are typically multiple blocks per piece.

The message that's sent is HAVE.

**Comment by cyrillicw** [comment]
Yeah, I've meant a "piece". Thank you very much! Is the message sent via DHT? Is there documentation about the message? I can not find it((

**Comment by arvidn** [comment]
http://bittorrent.org/beps/bep_0003.html

search for "4 - have"

**Comment by cyrillicw** [comment]
Thank you very much!!
