### ISSUE TITLE
Editable torrents

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6401]
@arvidn My player has been released with the ability to use changeable torrents.
How it works: The user has a list of private and public keys.
It syncs with DHT at regular intervals.
When creating a torrent (or manually) user enters sha1 value there (and can change it in future). Then he can get a magnet link to an editable torrent. Example link:
 magnet:?xt=urn:dhtih: Þñ4°öö5Üüu+PîÄhfQí38ÃùÕª í ¬b

This link asks the player for information from DHT. It gets sha1 and uses that sha1 to download the torrent file (standard procedure).

So that's why I'm writing this.
The library has a magnet link parser. Could you add to it a procedure to search for sha1 key from DHT and then download torrent file, if this sha1 is valid?
It would increase popularity of editable torrents very significantly.

**Comment by arvidn** [comment]
supporting this natively in libtorrent would take a lot more than just supporting a new key in the uri parser.

btw, did you mean to use hex or base32 encoding for that hash?

Do you use a unique key pair per editable torrent? If not, I imagine you would want to use a salt as well, which ought to be part of the magnet link

**Comment by master255** [comment]
> supporting this natively in libtorrent would take a lot more than just supporting a new key in the uri parser.

Of course

> did you mean to use hex or base32 encoding for that hash?

hex, public key length = 32.

> Do you use a unique key pair per editable torrent?

Of course. 

> I imagine you would want to use a salt as well, which ought to be part of the magnet link

Yes. Salt can easily be specified as a parameter of the magnet link.
magnet:?xt=urn:dhtih: Þñ4°öö5Üüu+PîÄhfQí38ÃùÕª í ¬b&st=SALT

**Comment by master255** [comment]
@arvidn My interface
![Screenshot_1628893053](https://user-images.githubusercontent.com/5380115/129423726-55430a26-6520-43bd-95e9-3d4887730556.png)
![Screenshot_1628893083](https://user-images.githubusercontent.com/5380115/129423728-c61a0f90-72e9-4589-a12e-5a66a522bc40.png)
![Screenshot_1628893109](https://user-images.githubusercontent.com/5380115/129423729-e89d24a6-d154-4fcc-83b0-b5fa64300adc.png)

**Comment by master255** [comment]
I added salt to all the scenarios.
![Screenshot_1628941047](https://user-images.githubusercontent.com/5380115/129445117-6d883725-d057-4ae4-8aa9-5443b5370590.png)

**Comment by master255** [comment]
@arvidn New changes:
1) Public and private keys are encoded into HEX format. Without this magnet link cannot be copied.
2) In the magnet link of edited torrent you need to add all trackers of the torrent file to which the link is referring. Without that torrent either won't download or will take a very long time to download.

8.8.2 version of my player has it all and works.
Changing the link (torrent content) takes 30-60 seconds. Start downloading the torrent from one peer 1-5 minutes.

Example magnet link:
magnet:?xt=urn:dhtih:0ba9696e6a2df1e89b9c4fa22afd2af2d0ad4f91c61526b49797d080d71aee82&st=MediaLibrary&tr=udp%3A%2F%2Ftracker.ds.is%3A6969%2Fannounce

**Comment by mayli** [comment]
How about using the extension of https://www.libtorrent.org/dht_store.html ?

**Comment by master255** [comment]
@arvidn Where is my answer mr. Arvin? Yes or No?
