### ISSUE TITLE
Redirect 302 (Moved Temporarily) and webseed

### ISSUE THREAD

**Issue by KamilKoD** [arvidn/libtorrent#6402]
Hi!
Now libtorrent get redirection link from original webseed link, download some pieces, redirection link expires and downloading stop.
I want after download stop, libtorrent get new redirection link from original webseed link and download from this new link. 

or if it it difficult
1. if redirection 302, get new redirection link from original webseed link
2. download one piece using new redirection link
3. goto 1

I think that i must edit "web_peer_connection::handle_redirect(int const bytes_left)", but i do not know how.
Can somebody help?
Sorry for bad English.

**Comment by arvidn** [comment]
sorry for the delay in responding to this.
You are saying that all redirects are treated as permanent, is that right?
i.e. the original URL won't be tried again once a redirection is received?
That's not the intended behavior.

**Comment by arvidn** [comment]
here are the tests for redirects of web seeds: https://github.com/arvidn/libtorrent/blob/RC_2_0/simulation/test_web_seed.cpp#L292
