### ISSUE TITLE
The moment of Choking

### ISSUE THREAD

**Issue by cyrillicw** [arvidn/libtorrent#6404]
As I understand, the choking mechanism works in a separate thread and once per 15 seconds disconnects unfair (from the point of tit-for-tat view) nodes. But what if by the moment of choking some pieces are already queued for uploading? Will the uploading really take place?

**Comment by arvidn** [comment]
It's technically not a thread; it's a timer that fires every 15 seconds about (and it's configurable). It's also not disconnecting peers, it just sorts them by how many payload bytes they've sent us in the last interval, and unchokes the top peers (and chokes the others). i.e. it reciprocates.

There are two kinds of "queued for uploading". If we have already issued a read from disk, or already added it to the send buffer, then those bytes will be sent. But if we've received the piece-request but not yet issued a disk read, it will be cancelled. The size of the send buffer, and the number of outstanding disk reads depend on the upload rate we're getting. So a fast peer may have quite a lot of data in-flight when it's choked.

**Comment by arvidn** [comment]
looking at the code, it doesn't actually look like queued incoming requests *are* cancelled when the peer is choked. They probably should be.

Another thing worth mentioning is that there's a `reject` message, that tells the peer that it won't receive the piece it requested.

**Comment by cyrillicw** [comment]
Thank you very much!
