### ISSUE TITLE
Updating a torrent file

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6406]
@arvidn I have a large collection of files (catalog). 400GB+. I created a torrent file from it (with hash alignment on files). Then I added a couple of new files to this directory.
What is the best way to update the torrent file without creating it again? This is a very long and resource consuming process.

**Comment by wrtorrent** [comment]
SSD

**Comment by arvidn** [comment]
I wrote some tools to do things like this for v2 torrents. I believe the internet archive (archive.org) may have some tools to do this for v1 torrents. But I'm not sure it's open source.

https://github.com/arvidn/torrent-tools

**Comment by master255** [comment]
@arvidn I asked the question a month ago. Will you answer me?

**Comment by arvidn** [comment]
"what do I think?". I think you should read the documentation and realize you already have access to this functionality.

http://libtorrent.org/reference-Create_Torrents.html#set_hash()
http://libtorrent.org/reference-Create_Torrents.html#set_hash2()

**Comment by master255** [comment]
@arvidn I'm trying to do that, but I'm having trouble with the .pad files. As far as I know, no one has ever done this algorithm?
So that it could all be easily added to applications, maybe it should be added to the library?

**Comment by master255** [comment]
@arvidn Should I wait another month for an answer?

**Comment by AllSeeingEyeTolledEweSew** [comment]
@master255 I believe Arvid has a sponsorship program if you want personal support.

https://github.com/sponsors/arvidn

**Comment by master255** [comment]
@arvidn @AllSeeingEyeTolledEweSew I don't believe the problem is $1 or even $50. I need confirmation from Arvin.

**Comment by arvidn** [comment]
@master255 you made two statements and put questionmarks after them. Those aren't questions, they're statements. There's nothing to answer.

**Comment by master255** [comment]
@arvidn Thanks for not helping develop torrents again. I will make this feature at a high level in my app and it will only work in my app.

That's the reason I'm not your sponsor. You are not trustworthy. You have low karma.

You didn't help: 
- with proxy in DHT
- support for disks without sparse mode
- with my pull request
- with streaming
- with bugs I found
- support for editable torrents. 
Now you didn't help with the quick update of the .torrent file.

**Comment by master255** [comment]
@arvidn 

> "what do I think?". I think you should read the documentation and realize you already have access to this functionality.

Okay. I did find this functionality and did a quick update.
But you need to express yourself in more detail.
