### ISSUE TITLE
Tracker-only torrents without DHT on corporate networks

### ISSUE THREAD

**Issue by fmike7** [arvidn/libtorrent#6410]
This is a general question about the applicability of the torrent technology on corporate networks with only one external IP address and an externally located HTTP tracker.

Here is a situation:
1) Multiple computers are located on the same LAN behind a firewall that blocks all inbound traffic (as it should).
2) The network has only one external IP address.
3) The tracker and the initial seeder are both located outside the network.
4) DHT is not allowed in such an environment. UPNP would also be disabled.
5) When the clients send their announce requests, the tracker gets the same external IP address each time.
6) Each client then attempts to connect to the same external IP and the firewall just blocks it, because (a) it's not allowed (b) it would not know how to route such requests.

In my understanding, such an environment would not be operable, unless you use a local tracker located inside the firewall on the same LAN. Am I correct?

Does libtorrent use any form of IP broadcast or multicast protocol to announce itself to its peers on the LAN? (not via the tracker, and not via the DHT)

**Comment by arvidn** [comment]
As I understand your description, all peers on the internal network would connect to the external seed, and they would all fail to connect to each other via the tracker. Since, as you say, the tracker only hands out their external IP.

If the local network supports multicast, the peers may still find each other via local peer discovery (or local service discovery). This is an SSDP-based protocol to advertise bittorrent peers on local networks. In case the network doesn't support multicast, there's an option in libtorrent to use broadcast instead, but this is not done by default.

A long time ago, a few of us at BitTorrent Inc. considered developing a tracker extension where ones local IP address was also announced, to allow trackers to pair up peers on the same network as well. But nothing came of it, probably because local peer discovery already covers this case.

**Comment by fmike7** [comment]
Very insightful, thanks!

This leads to a few more questions:
1) Is local peer discovery enabled by default or do you have to explicitly enable it in the session settings?
2) How do you enable the option to use the broadcast mechanism for the local peer discovery?
3) Is there a way to determine if the network supports multicast or not and then use multicast or fall back to broadcast accordingly?
4) Stupid question: does SSDP require any router or switch configuration or is it purely peer-to-peer based on multicast or broadcast? I am an expert in the topic, but I know UPNP is controlled by your router, and UPNP and SSDP seem to be related.
5) And finally: can you possibly get rid of the tracker entirely so all the clients download from the external seed and then upload and download within the LAN limits via local peer discovery?

As far as that tracker extension that never materialized, I think it would possibly have issues with cross-network "contamination". Such as client A from network 1 announces itself as having IP address 192.168.0.5 and then client B from network 2 announces its IP address 192.168.0.6. But these are two entirely different 192.168.0.x networks in no way connected to each other. So unless the tracker is somehow aware that these are two different networks, it would not work. Maybe using a pair [external IP:local IP] would solve the issue, so the tracker identifies which network is what.

**Comment by arvidn** [comment]
>     1. Is local peer discovery enabled by default or do you have to explicitly enable it in the session settings?

Yes, it's enabled by default. The setting is called [enable_lsd](https://libtorrent.org/reference-Settings.html#enable_lsd)

>     2. How do you enable the option to use the broadcast mechanism for the local peer discovery?

Actually, I was wrong about this. There used to be a setting called `broadcast_lsd` to enable this, but it was deprecated and removed in 2015.

>     3. Is there a way to determine if the network supports multicast or not and then use multicast or fall back to broadcast accordingly?

I don't know of a way other than trying and see if it works.

>     4. Stupid question: does SSDP require any router or switch configuration or is it purely peer-to-peer based on multicast or broadcast? I am an expert in the topic, but I know UPNP is controlled by your router, and UPNP and SSDP seem to be related.

Right, SSDP is the discovery protocol used by UPnP to discover devices on the local network. Things like printers, google chromecasts, routers and media servers etc. Most home hetworks these days supports it no problem. My understanding is that large managed networks may have it disabled (but I don't know why) or possibly segmented (perhaps to limit UPnP discovery traffic across a large network).

>     5. And finally: can you possibly get rid of the tracker entirely so all the clients download from the external seed and then upload and download within the LAN limits via local peer discovery?

You don't need a tracker for a torrent to work. It's just another source of peees (next to DHT, local peer discovery, resume data). You would need some way to find the initial seed though. But if you know what its IP/hostname is, you can just add that peer with [connect_peer()](http://libtorrent.org/reference-Torrent_Handle.html#connect-peer)

> As far as that tracker extension that never materialized, I think it would possibly have issues with cross-network "contamination". Such as client A from network 1 announces itself as having IP address 192.168.0.5 and then client B from network 2 announces its IP address 192.168.0.6. But these are two entirely different 192.168.0.x networks in no way connected to each other. So unless the tracker is somehow aware that these are two different networks, it would not work. Maybe using a pair [external IP:local IP] would solve the issue, so the tracker identifies which network is what.

Our idea was to make the tracker only hand out local IPs to peers announcing from the same source IP. With the expectation that they are likely to be on the same network.

**Comment by fmike7** [comment]
Correct me if I am wrong, but from the description of connect_peer(), it's not the most reliable mechanism, because in case the seed host is not accessible immediately, it disconnects and forgets it. You would have to call it repeatedly, or the download would just stall. set_web_seeds() looks like it would attempt to contact the seed permanently, even if it's not accessible initially or from time to time.

This is what I ended up doing:
1) clear_trackers() to clear the trackers and ignore announce and announce-list in the .torrent file
2) set_web_seeds() to specify the web seed URL (luckily my storage supports https access)

What I am trying to accomplish is when a large file needs to be distributed, the clients would:
1) download some random pieces from the web seed outside of the LAN
2) announce themselves using local peer discovery on the LAN
3) share the already downloaded pieces with each other over the LAN, without contacting the web seed.
4) keep downloading the remaining locally unavailable pieces from the web seed

The question is how do I ensure that in such a scenario the clients don't always resort to downloading 100% of all the pieces from the web seed. Does libtorrent randomize the web seed downloading process somehow? Imagine a 100Gb file that needs to be downloaded by 1000 clients on the same LAN at the same start time. Ideally, I want to reduce the total external bandwidth usage (traffic between LAN and the external web seed) to be those 100Gb (vs 100Gb x 1000 clients). If libtorrent prefers sequential downloads, all these 1000 clients would be downloading piece by piece from the web seed and not from the local peers.

**Comment by arvidn** [comment]
> Correct me if I am wrong, but from the description of connect_peer(), it's not the most reliable mechanism, because in case the seed host is not accessible immediately, it disconnects and forgets it.

That last statement is not correct. The peer is added to the peer list, just as it would if you received if from the DHT or a tracker. If anything, it may not be tried immediately. If you already have a large peer list, all peers are considered when picking the next peer to try to connect to.

However, just like any peer in the list, if it fails a sufficient number of times, it may be evicted (and forgotten).

> You would have to call it repeatedly, or the download would just stall. set_web_seeds() looks like it would attempt to contact the seed permanently, even if it's not accessible initially or from time to time.

In case the peer is evicted, you would have to re-add it by calling `connect_peer()` again, yes.

web seeds are a bit different, they are only removed in case they send a respond indicating that they are not seeding the specified files, but they *can* be forgotten as well.

> 3. share the already downloaded pieces with each other over the LAN, without contacting the web seed.
> 4. keep downloading the remaining locally unavailable pieces from the web seed

I think there's a conflict between "without contacting the web seed" and " downloading the remaining locally unavailable pieces from the web seed". I suppose it comes down to deciding when to consider a piece "unavailable".

> The question is how do I ensure that in such a scenario the clients don't always resort to downloading 100% of all the pieces from the web seed.

If your peers on the local network have significantly more bandwidth capacity, I would imagine you'd get most of the data from them. You can also rate limit external peers and not have any limits for local network (or any network you chose).

> Does libtorrent randomize the web seed downloading process somehow?

Yes, pieces are downloaded rarest-first, just like for other peers. However, since web servers aren't typically prepared to have deep pipeline queues, and sometimes disconnect after a certain number of requests, libtorrent is a bit more conservative and requests larger ranges at a time from web seeds. iirc, it aims to request at least 1 MiB at a time from web seeds, instead of blocks or pieces.

> Imagine a 100Gb file that needs to be downloaded by 1000 clients on the same LAN at the same start time. Ideally, I want to reduce the total external bandwidth usage (traffic between LAN and the external web seed) to be those 100Gb (vs 100Gb x 1000 clients). If libtorrent prefers sequential downloads, all these 1000 clients would be downloading piece by piece from the web seed and not from the local peers.

By default, sequential download is enabled when the vast majority of peers are seeds (iirc, >90% ). However, that still doesn't mean it will download sequentially from *one* peer. It will still request pieces from as many peers it can in parallel.

**Comment by fmike7** [comment]
Seems to be working! One thing I wasted a few hours on was the wrong type of web seed. I specified ```http_seed``` initially, but in my case, it had to be ```url_seed```:

```torrent_handle.set_web_seeds({ lt::web_seed_entry(web_seed_URL, lt::web_seed_entry::type_t::url_seed) });```

For whatever reason libtorrent was not giving any alerts (alert mask ```lt::alert::error_notification | lt::alert::storage_notification | lt::alert::status_notification | lt::alert::tracker_notification```)

**Comment by fmike7** [comment]
One follow-up question on this. BitTorrent has one more peer discovery option called Peer Exchange (in addition to Local Peer Discovery):

![torrent_added](https://user-images.githubusercontent.com/60244290/131224730-5fa1a52a-7db0-4956-8898-6b3268a39aea.png)

I wonder what is that and is there a similar option in libtorrent?

**Comment by elgatito** [comment]
@fmike7 https://en.wikipedia.org/wiki/Peer_exchange 
Yes, libtorrent supports it.

**Comment by fmike7** [comment]
Do you have to enable this option explicitly in the session settings or is it enabled by default?

**Comment by arvidn** [comment]
`pex` is a default extension.

**Comment by fmike7** [comment]
Here is another question related to this.

My new algorithm removes the tracker info for all newly added torrents and adds a web seed. It's working great.

For all existing torrents that I am seeding, I use this algorithm:

```
add_torrent_params atp_resume = read_resume_data(...);
atp_resume.ti = MY_load_torrent_from_file(...);    // load from file, bdecode etc
async_add_torrent (std::move(atp_resume));
```

However, since the resume data for these older torrents had the tracker info embedded it continues to use it. I don't want to use it, the goal is to make all the torrents trackerless. The question is how do I remove the tracker info from the old resume data, but keep everything else? (such as downloaded piece info). Would these lines be enough:

```
atp_resume.trackers.clear();
atp_resume.trackerid.clear();
```

There is also the add_torrent_params::flags member that caught my attention:

```
torrent_flags::override_trackers, torrent_flags::override_web_seeds, torrent_flags::merge_resume_trackers, torrent_flags::merge_resume_http_seeds
```

Shall I unset all 4 above in atp_resume.flags in order to ignore all the tracker and web seed info in the existing resume data, but still be able to properly resume the seeding and downloading?

```
atp_resume.flags &= ~(torrent_flags::override_trackers | torrent_flags::override_web_seeds | torrent_flags::merge_resume_trackers | torrent_flags::merge_resume_http_seeds);
```

**Comment by fmike7** [comment]
I already figured that override_trackers and override_web_seeds indeed shall be cleared in my case, because read_resume_data would have it set from my previous torrents with the tracker info. The question remains about the merge_* flags. The merge_ flags are unfortunately not documented here: https://www.libtorrent.org/reference-Core.html#torrent_flags_t

**override_trackers**
when this flag is set, the tracker list in the add_torrent_params object override any trackers from the torrent file. If the flag is not set, the trackers from the add_torrent_params object will be added to the list of trackers used by the torrent. **This flag is set by read_resume_data() if there are trackers present in the resume data file. This effectively makes the trackers saved in the resume data take precedence over the original trackers. This includes if there's an empty list of trackers, to support the case where they were explicitly removed in the previous session.** This flag is not saved by write_resume_data()

Found this here: https://sourceforge.net/p/libtorrent/mailman/message/28368654/:
``flag_merge_resume_trackers`` defaults to off and specifies whether tracker URLs loaded from resume data should be added to the trackers in the torrent or replace the trackers.

I should then have both merge flags cleared then to fully ignore all the previous tracker and web seed info. Is my logic right?

**Comment by arvidn** [comment]
the `merge_*` flags are deprecated, that's why they're not included in the documentation. You can find their description in the source code though. https://github.com/arvidn/libtorrent/blob/RC_2_0/include/libtorrent/torrent_flags.hpp#L247

> I already figured that override_trackers and override_web_seeds indeed shall be cleared in my case, because read_resume_data would have it set from my previous torrents with the tracker info

I would expect you want to clear the trackers in `add_torrent_params` and then *set* the `override_trackers` flag. That way, any trackers in the `torrent_info` object itself will be overridden by the empty list of trackers in `add_torrent_params`.

In the future, this will be simplified by making it possible to read a .torrent file directly into an `add_torrent_params` object, and have the trackers specified in the .torrent file show up in `add_torrent_params::trackers` rather than in a second list in the `torrent_info` object also.

**Comment by fmike7** [comment]
Got it, thanks for explaining the tracker flags! That brings another question though about the web seeds.

I want to always re-specify the web seeds upon resuming a torrent. The override_web_seeds flag shall then be UNSET?

```
add_torrent_params atp_resume = read_resume_data(...);
atp_resume.ti = MY_load_torrent_from_file(...);    // load from file, bdecode etc
atp_resume.ti.set_web_seeds (...);                          // reset the web seeds
atp_resume.flags &= ~(lt::torrent_flags::override_web_seeds);    // prevent usage of the web seeds in the resume data
async_add_torrent (std::move(atp_resume));
```

This way, the web seeds will be used from the torrent object and not from the resume data, correct?

**Comment by arvidn** [comment]
> I want to always re-specify the web seeds upon resuming a torrent. The override_web_seeds flag shall then be UNSET?

No, it should be set. "override" refers to whatever is set in `add_torrent_params` taking precedence over what's specified in the .torrent file (i.e. `ti` object)

**Comment by arvidn** [comment]
> This way, the web seeds will be used from the torrent object and not from the resume data, correct?

Oh, that's correct. But if you want to replace the web seeds, unconditionally, you set them in the `add_torrent_params` object to what you want them to be, then you set the override flag to ensure any web seeds in the .torrent file are ignored

**Comment by fmike7** [comment]
Yes, the only problem with setting them in add_torrent_params::url_seeds is there is no way to specify the web seed type, because url_seeds is a vector of strings vs web_seed_entry has web_seed_entry::type_t::url_seed

```
atp_resume.url_seeds( { web_seed_URL } );
```

vs

```
ti.set_web_seeds({ lt::web_seed_entry(web_seed_URL, lt::web_seed_entry::type_t::url_seed) });
```

As I mentioned above, I had some issues with the seed type.

**Comment by fmike7** [comment]
One more question related to web seeding: how do you tell if a particular web seed has issues? Are there any alerts available for that, similar to how libtorrent posts all trackers connection alerts?

In my scenario, there would be no tracker and no tracker alerts. How do I tell if the web seed is non-responsive or has any other issues (such as file not found, network timeout errors, etc)?

**Comment by arvidn** [comment]
> Yes, the only problem with setting them in add_torrent_params::url_seeds is there is no way to specify the web seed type

You have two separate lists for the different kinds. `url_seeds` and `http_seeds`. `http_seeds` are being phased out and deprecated though.

> How do I tell if the web seed is non-responsive or has any other issues (such as file not found, network timeout errors, etc)?

see http://libtorrent.org/reference-Alerts.html#url_seed_alert

**Comment by fmike7** [comment]
Great, thanks for the clarification!
