### ISSUE TITLE
Incorrect hash created by sha1_hash in Python bindings 

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#6421]
While looking into another problem #6420 I found that I couldn't construct an lt sha1_hash

```python
>>> str(lt.sha1_hash('85bbba4035cca750f681284857f53e405eb41f8d'))
'3835626262613430333563636137353066363831'
```

Constructed from resume_data or parse_magnet_uri info_hash is fine:

```python
>>> str(lt.sha1_hash(b'\x85\xbb\xba@5\xcc\xa7P\xf6\x81(HW\xf5>@^\xb4\x1f\x8d'))
'85bbba4035cca750f681284857f53e405eb41f8d'
```

This is also a problem with `info_hash` key in **atp**:

```python
>>> h = ses.add_torrent({'info_hash': b'85bbba4035cca750f681284857f53e405eb41f8d'})
>>> str(h.info_hash())
'3835626262613430333563636137353066363831'
```

libtorrent version (or branch): 1.2.14

**Comment by arvidn** [comment]
I think this is more of an python binding issue than an actual bug. in C++, `sha1_hash` can be constructed from a 20 byte array, which (for historical reasons) is `char const*`. When binding this constructor to python, it automatically accepts strings, which may lead people to believe human readable hex can be passed in to the constructor.

the string passed to the `sha1_hash` constructor is always treated as 20 bytes of the actual hash.

The fact that it doesn't make a distinction between `str` and `bytes` in python makes a foot-gun.

**Comment by cas--** [comment]
You are correct! I wasn't paying attention to types and assumed it would take hex string.

```python
hex_hash = '85bbba4035cca750f681284857f53e405eb41f8d'
str(lt.sha1_hash(bytes.fromhex(hex_hash)))
'85bbba4035cca750f681284857f53e405eb41f8d'
```
Sidenote that python2 requires `bytes(bytearray.fromhex())`

**Comment by AllSeeingEyeTolledEweSew** [comment]
@cas-- did a hex string work in a previous version? We changed the bindings a lot recently, and had to make assumptions in some cases about what should be supported and what people were currently using.

**Comment by arvidn** [comment]
I believe all of those changes were made in `master` though
