### ISSUE TITLE
Is it possible to do only seeding without downloading?

### ISSUE THREAD

**Issue by bemaru** [arvidn/libtorrent#6424]
libtorrent version (or branch): 1.2.3

platform/architecture: windows10 x64

compiler and compiler version: vs2015(v140)

Is it possible to do only seeding without downloading?

(I used high_performance_seeds and auto_manage_perfer_seeds but it is getting download. )

**Comment by arvidn** [comment]
yes. when you're seeding nothing is being downloaded. At least as long as "downloaded" refers to actual content, obviously protocol chatter, such as requests, are still downloaded from peers.

By definition, when you're seeding, you already have all the files associated with the torrent, and there's no content left to download.

**Comment by bemaru** [comment]
Now I understand. In a state where seeding was not possible, I requested a download by adding a torrent. Thanks for the reply.
