### ISSUE TITLE
[NotABug] The actual use of file_pool_size

### ISSUE THREAD

**Issue by DJPlaya** [arvidn/libtorrent#6438]
Hello,
Ime just fine tuning my high performance torrent client, and i was wondering what is the actual usage of the file_pool_size setting nowadays.
I am using Sophos on my internal Proxy VM and have an UTM set to max security.
The server has Sophos Endpoint, it should skip most networked files since it communicates with the UTM, so basically there is no big need for local virus file checks.

In the documentation, it is just described as useful for virus scanners, so my main question is if there is any good use in having a high number set in the settings for performance. If ime not completely mistaken, the limit just shouldent be lower then the global active torrent limit, right?

**Comment by userdocs** [comment]
https://github.com/arvidn/libtorrent/discussions ?

**Comment by DJPlaya** [comment]
Sry, dident know about this Feature yet

**Comment by DJPlaya** [comment]
.ref https://github.com/arvidn/libtorrent/discussions/6439_
