### ISSUE TITLE
Decide on a policy for openssl linkage in pypi wheels

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [arvidn/libtorrent#6448]
@arvidn @jkterry1 @cas-- @mayli @filips123

Let's spin off the discussion about openssl linkage.

I'll try to summarize the ideas, and any conclusions, in the top comment here.

## Impact of openssl bugs on libtorrent
Assuming something like "heartbleed 2.0" happens:
* Users of SSL torrents would be at risk of attack by peers
  * These seem rare
* Users could be at risk when connecting to a malicious HTTPS tracker

## Risks of statically linking openssl
* **Developer maintenance**: Arvid may be on the hook to rapidly integrate new versions of openssl for critical bug fixes, and publish new wheels
  * **Mitigation**: we can roll our own dependabot for our openssl dependency. [manylinux does this](https://github.com/pypa/manylinux/blob/c009bd6f75c5a69fe1962d7a7b297d5351a898a6/.github/workflows/update-dependencies.yml). The outcome is a bot makes a PR against libtorrent when openssl needs to be updated; Arvid just needs to accept it and run the cibuildwheel workflow to publish it.
* **Disharmony**: There could be differences between libtorrent's openssl and other ssl contexts, even in the same app, yet both must be configured by the same global certificate store and environment variables
* **User surprise**: users may expect that updating their system openssl will be effective for all SSL connections on their machine
* **Development lock-in**: static linking will satisfy basic use cases in all environments. If we ever change to dynamic linking we will definitely break some users whose installations previously worked.

## Risks of dynamically linking openssl
* **Breakage**: Users with the wrong openssl version can't load libtorrent, because we can only link against one of a few ABI-incompatible versions
  * Impact: 1.1 is popularly installed; 1.0 reached EOL 18 months ago but is probably installed widely still
  * Impact gets worse once openssl 3.0 is more widely installed
  * Also impacts python distributions which link openssl statically (at least the build pythons found on `manylinux` centos images do this)
* **User surprise**: users may expect that updating their python packages is sufficient to fix security issues in those packages

## Risks of using `dlopen()` for openssl
* **Development risk**: I've only seen this method discussed in blog posts, not done in practice. There are many unknowns.
  * **High investment**: I expect this would require some significant work to research.
  * **Bad signs**: openssl has an infamously unstable API and ABI. Reading their blog posts, they expect you to recompile when they release a new version.

## Conclusions

* We should vendor openssl with static linking.
* There are known issues with accessing system certificate stores, but we will fix these after some initial release of  wheels on pypi.

**Comment by AllSeeingEyeTolledEweSew** [comment]
After some thought, I can think of more kinds of risks with static linking, **but** the big risk (maintaining up-to-date openssl linkage) can be mitigated with some automation. The dynamic linking strategies all have big risks that I can't figure out how to mitigate.

So I currently favor static linking, as a long-term strategy.

I didn't hear much opposition to this in #6188, but I really want to make sure we consider all sides of this issue, because changing this strategy in the future will be hard.

So, does anyone have any other thoughts?

**Comment by jkterry1** [comment]
Given this, static linking seems preferable to me because it doesn't have the problematic dependencies on system libraries

**Comment by mayli** [comment]
Agreed, static linking has it's own limitations, but I am willing to takes those risks.

**Comment by AllSeeingEyeTolledEweSew** [comment]
Seems like there's consensus for static linking / vendoring openssl. Just need @arvidn to sign off

**Comment by AllSeeingEyeTolledEweSew** [comment]
Do we need to build openssl ourselves? The prebuilt installations on github actions seem suitable for static linking AFAICT, but I haven't finished testing yet.

I believe libtorrent has little to do with configuring openssl. It seems to just tell it to use its defaults. Python has nothing at all to do with it. In particular when the libtorrent extension vendors openssl as proposed, python and libtorrent are using entirely different openssls, possibly in different versions. So we ought to pass through whatever compile-time defaults exist on CI.

**Comment by userdocs** [comment]
The cert path is hardcoded into the static bin. As long as all target OS reachable via pip installation share that it will be fine.

I don't think it matters if you build it your self or use the runner OS. It's hardcoded during compilation as recommended here

https://wiki.openssl.org/index.php/Compilation_and_Installation#PREFIX_and_OPENSSLDIR

So if the OS is ubuntu latest and the openssl version is 1.1.1 it will probably be hardcoded as `/etc/ssl`. 

Do all target OS reachable by a pip installation use this path? If not how do you resolve that. That is the main question. It just appears to me that by linking statically to the system library of the runner OS using Github Actions will create this problem potentially, unless I am totally misunderstanding how it works, in that case just ignore this.

**Comment by AllSeeingEyeTolledEweSew** [comment]
Hm, good point.

(aside: we *should* build openssl from source when building wheels, because we want to vendor the latest version).

I don't see much guidance from that wiki on *how* to set openssldir, or how different OSes do it today. The linux default appears to be `/etc/ssl`, and anecdotally I think every distro I've ever used uses that.

It looks like https://github.com/pyca/cryptography just [leaves openssldir unconfigured](https://github.com/pyca/cryptography/blob/ac645332d66a96dd86ebd024c56be0ac4162ccb2/.github/workflows/build_openssl.sh#L18) (they also vendor openssl in their wheels).

libtorrent [calls `SSL_CTX_set_default_verify_paths()`](
https://github.com/arvidn/libtorrent/blob/2e6f8f68d983bd9d050664d3f8537c72ba6d2c2d/src/session_impl.cpp#L601) when the session is created. [That will use paths from environment variables if set, before defaulting to the compile-time openssldir](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_default_verify_paths.html). If our default openssldir is wrong in some environments, users have a workaround.

So, it seems like the best course is to leave openssldir at its OS-specific default. I don't see evidence or precedent to do otherwise. If that exists, it seems like we can wait for it to come to us via bug reports.

**Comment by AllSeeingEyeTolledEweSew** [comment]
After more research, the openssldir situation is worse than I thought, but I found some precedent for what to do.

It looks like openssldir and certificate paths **are different** on various *nix environments. A single binary with statically-linked openssl will be wrongly-configured on some of them.

I find a general consensus that `SSL_CTX_set_default_verify_paths()` is **only** appropriate when openssl was built for the running system. Otherwise, it looks like authors roll their own version of this function. On Linux in particular the approach seems to be to search a well-known list of certificate paths used on various distros.

Precedent:
* golang doesn't use openssl, but has logic to load certificates from OS-specific sources: https://golang.org/src/crypto/x509/root_linux.go, https://golang.org/src/crypto/x509/root_windows.go
* `pyopenssl` checks if `cryptography` was built with a statically-linked openssl (true for their pypi wheels), by checking if openssldir is a sentinel path: https://github.com/pyca/pyopenssl/pull/633, https://github.com/pyca/pyopenssl/blob/8e1f599eb6bb4fc129ce0519506945fb306713fa/src/OpenSSL/SSL.py

So to follow the "best practice", it looks like we should have a function in libtorrent to mimic `SSL_CTX_set_default_verify_paths()`. This should only be enabled if the binary is intended to work across different Linux distros, so it should be a compile-time feature.

I'm not sure yet if this is only necessary for Linux, or other OSes as well. I'll do some testing.

**Comment by AllSeeingEyeTolledEweSew** [comment]
Looks like certificate stores are hard on every platform.

**Windows**: openssl does not natively integrate with the windows certificate store. If you want to use openssl to verify a server against the store, the guidance is to manually query the store(s) (`CA` and `ROOT`) and add all certificates to your `SSL_CTX`. Python's `ssl` module does this.

**macOS**: openssl does not natively integrate with the apple certificate store. The `ssl` module from the official python package doesn't verify any certificates out of the box. It includes an `Install Certificates.command`, which installs the `certifi` package, which provides a combined `cert.pem` sourced from Mozilla. This gets installed to a location which gets picked up by their vendored openssl.

**Comment by AllSeeingEyeTolledEweSew** [comment]
I propose we release wheels on pypi which vendor openssl **but** don't integrate with certificate stores.

https trackers won't verify, but could still be functional with various workarounds. Lazy users can just disable `validate_https_trackers`; less-lazy users can use the `SSL_CERT_FILE` or `SSL_CERT_DIR` env variables to point to the right store, possibly setting up their own.

We can provide better automatic integration in a later release. I think the "real" solutions are a lot of work on every platform, so would significantly delay getting wheels on pypi. I think getting libtorrent on pypi is going to do a lot of good and the sooner the better, so I think this is a good tradeoff.

Thoughts?

**Comment by jkterry1** [comment]
This don't impact my use case either way. I'd personally like to make whatever choices are need to get this released to PyPI in the near future (as it's blocking something important for me) and we can then see what issues the community raises with these decisions.

**Comment by arvidn** [comment]
> I propose we release wheels on pypi which vendor openssl but don't integrate with certificate stores.

I think that's fine. I would guess that the openssl default cert store path is compatible with a few popular linux distros at least, right?
there is already code to integrate with the windows cert stores.

https://github.com/arvidn/libtorrent/blob/RC_2_0/src/session_impl.cpp#L609

and homebrew's cert store on MacOS:

https://github.com/arvidn/libtorrent/blob/RC_2_0/src/session_impl.cpp#L635

**Comment by arvidn** [comment]
(sorry for the delay on responding to this thread)

**Comment by AllSeeingEyeTolledEweSew** [comment]
> > I propose we release wheels on pypi which vendor openssl but don't integrate with certificate stores.
> 
> I think that's fine. I would guess that the openssl default cert store path is compatible with a few popular linux distros at least, right?
> there is already code to integrate with the windows cert store:
> 
> https://github.com/arvidn/libtorrent/blob/RC_2_0/src/session_impl.cpp#L609
> 
> and homebrew's cert store on MacOS:
> 
> https://github.com/arvidn/libtorrent/blob/RC_2_0/src/session_impl.cpp#L635

Seems decent for an initial release.

@arvidn does that code have tests? I've been racking my brain trying to figure out how to test that certificates are validated against the system store. In theory if any CAs would validate a certificate for localhost or 127.0.0.1 then they shouldn't be in the system store.

**Comment by arvidn** [comment]
> @arvidn does that code have tests? I've been racking my brain trying to figure out how to test that certificates are validated against the system store. In theory if any CAs would validate a certificate for localhost or 127.0.0.1 then they shouldn't be in the system store.

No, there aren't any unit tests to ensure the system cert store is used correctly. I can't think of a good way to test that. You could ping some well know server, like `www.google.com` and ensure its certificate is validated. However, that adds an external dependency and a requirement to have an internet connection just to run the tests. The negative test would be fairly simple though, to just make sure a localhost web server with a self-signed cert is *not* validated.

Alternatively, the test could add its own cert to the system store and then make sure it's available. But I imagine the test would have to run as root to add a cert.

**Comment by AllSeeingEyeTolledEweSew** [comment]
> No, there aren't any unit tests to ensure the system cert store is used correctly. I can't think of a good way to test that. You could ping some well know server, like `www.google.com` and ensure its certificate is validated. However, that adds an external dependency and a requirement to have an internet connection just to run the tests. The negative test would be fairly simple though, to just make sure a localhost web server with a self-signed cert is _not_ validated.
> 
> Alternatively, the test could add its own cert to the system store and then make sure it's available. But I imagine the test would have to run as root to add a cert.

I concluded the same. Maybe we should have tests that attempt your second test, but are no-op if not root.

**Comment by AllSeeingEyeTolledEweSew** [comment]
I think we reached a consensus (that we should vendor openssl, and sort out the various system cert store issues later), so this thread can be closed.
