### ISSUE TITLE
skip of trackers

### ISSUE THREAD

**Issue by wrtorrent** [arvidn/libtorrent#6461]
libtorrent-2.0.4-master, win10-64, msvc16.11.2

Do libtorrent skip trackers after select one?
I've noticed same thing going: no seeders, no peers, I'm only downloading, at 0%, another peer starting download, he is getting %complete downloaded for someone else, I was able to download only from that new peer.
Tried utorrent. utorrent scrape all trackers, not stop at first working.
libtorrent seems to find first working (ae.verified) and stop here, while re-trying to scrape only these with error (av.fails), prior working in list.

next code not getting stats for trackers past `ae.verified` tracker
next code stats show libtorrent trying to reconnect not working trackers if they're prior to first ae.verified tracker
```
for (lt::announce_entry const& ae : torrent_status.handle.trackers()) {
	// ae.url, ae.verified, ae.tier list of trackers
	for (auto const& ep : ae.endpoints) {
		if (!ep.enabled) continue;
		for (lt::protocol_version const v : {lt::protocol_version::V1, lt::protocol_version::V2}) {
			if (!torrent_status.info_hashes.has(v)) continue;
			// av.fails, av.next_announce, av.message stats
		}
	}
}
```

by skipping trackers past ae.verified libtorrent client missing seeders, who happen to announce at different tracker.
edit1: for some torrents there no `ae.verified` then example code above not have stats past `torrent_status.current_tracker.c_str()`
edit2: right now ts.current_tracker is first working tracker in list, could be good to set to tracker with highest number of seeds (peers) instead.

**Comment by thalieht** [comment]
https://www.libtorrent.org/reference-Settings.html#announce_to_all_trackers
