### ISSUE TITLE
bdecode token_limit argument unattainable internally

### ISSUE THREAD

**Issue by Lymkwi** [arvidn/libtorrent#6467]
**Required information**

libtorrent version (or branch): 2.0.4 (current `RC_2_0`)

platform/architecture: x86_64-linux-gnu

compiler and compiler version: GCC 11.1.0

**Issue**

Over the past couple months I've frequently had my torrent client silently (and yet messily) fail to add torrents due to `"bencoded item limit exceeded"`. After messing around in libtorrent, I worked out a way to expose `token_limit` and `depth_limit` in the Python bindings used by my client.
However, while testing, I noticed that some calls to `bdecode` would still fail while adding those large torrents, and I traced those back to internal calls made by methods within libtorrent to the default definitions of `bdecode` written [here](https://github.com/arvidn/libtorrent/blob/2e6f8f68d983bd9d050664d3f8537c72ba6d2c2d/include/libtorrent/bdecode.hpp#L455) with default arguments. For example, while my client managed to decode a torrent's data to a `bdecode_node`, building a `torrent_info` class with it would immediately fail with the "token limit exceeded" error. The torrent info class does not have a parameter to expose the values it uses for `token_limit` and `depth_limit` in its [internal call](https://github.com/arvidn/libtorrent/blob/2e6f8f68d983bd9d050664d3f8537c72ba6d2c2d/src/torrent_info.cpp#L936). Similarly, [other](https://github.com/arvidn/libtorrent/blob/2e6f8f68d983bd9d050664d3f8537c72ba6d2c2d/src/torrent.cpp#L7477) [places](https://github.com/arvidn/libtorrent/blob/2e6f8f68d983bd9d050664d3f8537c72ba6d2c2d/src/http_tracker_connection.cpp#L512) seem to use it with default values without exposing it (and my guess is that these could fail as well in case of a large torrent).

The binding fix manages to preserve backwards compatibility, but I do not see the point of even exposing these parameters if the internal code still uses the default, lower hardcoded limit. Would it be possible to either expose those limits everywhere they are used internally, or provide another mechanism to provide them when using libtorrent? My current hotfix (alonside some additions to the Python binding) is to change the default value for `token_limit` in the three definitions to be a compile-time constant that defaults to `2000000` (its current value), but can be redefined by whoever compiles it. This is not great in my opinion and could be done way better.

**Comment by arvidn** [comment]
> The torrent info class does not have a parameter to expose the values it uses for token_limit and depth_limit in its internal call.

you can use this other [overload](https://github.com/arvidn/libtorrent/blob/2e6f8f68d983bd9d050664d3f8537c72ba6d2c2d/src/torrent_info.cpp#L971) to use your own configurations instead.

> Similarly, other places seem to use it with default values without exposing it (and my guess is that these could fail as well in case of a large torrent).

The one parsing the metadata should have a setting exposed, however, the second one I think is pretty legitimate. A tracker response that hits the default limits is malicious.

> Would it be possible to either expose those limits everywhere they are used internally, or provide another mechanism to provide them when using libtorrent?

Yes, there are two settings, `max_metadata_size` and `max_piece_count`. There should be at least one more exposing the token limit. The depth limit is probably not all that important to expose.

**Comment by arvidn** [comment]
@Lymkwi would you mind giving this a try? https://github.com/arvidn/libtorrent/pull/6525
