### ISSUE TITLE
[Feature request] torrent_status selection or grouping flag

### ISSUE THREAD

**Issue by wrtorrent** [arvidn/libtorrent#6469]
Every libtorrent UI/client program do operations with selected item(s) in list.
Then user of libtorrent based UI/client program never do actions on not selected items.

Have selection flag and class added to lt::torrent_status and lt::session
Selection class with most or all operations allowed from torrent_handle

lt::torrent_status.is_selected
lt::session.select(pos, int flag = 0); // flag is none, ctrl, shit modifiers
lt::session.select(handle);

instead of
lt::torrent_status.handle.is_valid()
lt::torrent_status.handle.scrape_tracker();
or
lt::torrent_status.handle.is_valid()
lt::torrent_status.handle.clear_error();
allow to
lt::session.selection.resume();
lt::session.selection.queue_position_up();
lt::session.selection.graceful_pause();
lt::session.selection.unselect_all();

pros: ease of use
cons: event handler of listview gonna select in-library with each click
assume(user not clicking fast to make significant load);

**Comment by arvidn** [comment]
I'm not keen on adding this state to torrent handles/torrents. But perhaps there could be benefits in supporting batch operations. The ones that would make sense are the ones that are "fire-and-forget" style operations, where you don't need to wait for a response. On the other hand, it seems unlikely that there would actually be much performance benefit over just looping over the handles and making those calls.

The main improvement, I would think, would be to make bulk calls to functions that actually have to wait to return a response. The most common cases for that are covered by subscribing to torrent update alerts though.

**Comment by arvidn** [comment]
btw, I would not recommend keeping track of which torrents have been selected in your listview by index. It would be enough for the user to re-sort the table and the indices would change (presumably).

I would think you have a unique identifier, but perhaps best the `torrent_handle` object itself.

**Comment by arvidn** [comment]
regarding the `is_valid()` check. That's relevant if you have some asynchronous task where you may remove torrents. Which it sounds like you might.

Depending on *how* asynchronous that task is, you may still have a race condition where the torrent is removed *after* the `is_valid()` check, but before the actual call on that torrent handle.

The most reliable way to ignore such torrents is to wrap the call(s) in `try` `catch`. You should probably remove the `torrent_handle` from the list when that happens too.

**Comment by wrtorrent** [comment]
libtorrent perfect sense: little to none asynchronous
client_test.cpp m_filtered_handles <-> library

libtorrent gui multi-threaded: mostly useful is_valid() everywhere, lock() for m_filtered_handles, try{}catch{} to library calls.
OS, Qt or web listview <-> m_filtered_handles from state_update, remove|add_alert <-> library

proposed selection class:
listview m_filtered_handles <-> library


> If it's general enough, it might make sense to move that out into a library

idk
