### ISSUE TITLE
Question about using clock_type::now in dht_tracker

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#647]
This function is used in two places:
https://github.com/arvidn/libtorrent/blob/master/src/kademlia/dht_tracker.cpp#L501
https://github.com/arvidn/libtorrent/blob/master/src/kademlia/dht_tracker.cpp#L607

Is it better to use here `aux::time_now()`?

**Comment by arvidn** [comment]
are those the only two places clock_type::now() is used in libtorrent? anything that is run relatively infrequent and requires > 100ms or so accuracy should use clock_type::now() directly

**Comment by aldenml** [comment]
Didn't grep the source tree looking for this, I found these two looking at `dht_tracker` and I ask mainly because in `dht_tracker::incoming_packet` could have a performance impact if 100ms accuracy is not necessary. What do you think?

**Comment by arvidn** [comment]
for DHT packet timeouts, it's probably a good idea to have a high resolution clock

**Comment by aldenml** [comment]
I looked at the `dos_blocker::incoming` (the point when `clock_type::now()` is used inside `dht_tracker::incoming_packe` and it works in the seconds resolution. My point is that this could be called frequently but it's used in the context of seconds resolution.

Still looking at `dht_tracker::has_quota` details.

**Comment by arvidn** [comment]
I see. the dos_blocker could probably use lower resolution. I'm guessing the send quota needs higher resolution though

**Comment by aldenml** [comment]
This potential PR is very simple, but I see there are a lot of differences between master and RC_1_1 around this code. How do you prefer to manage this?

**Comment by arvidn** [comment]
perhaps it's better to leave RC_1_1 as is for now (and make this change in master). at least until it's shown to be an actual problem

**Comment by aldenml** [comment]
Closing this, not clear what the impact of this is in performance vs correctness.
