### ISSUE TITLE
set_settings effect python binding

### ISSUE THREAD

**Issue by ardhipoetra** [arvidn/libtorrent#648]
libtorrent version (or branch): 1.1.0.0
platform/architecture: Ubuntu 16.04 64bit

I'm not sure if set_settings have any effect in python binding. I'm fully aware that `apply_settings` is asynchronous. I have waited for a long time but the settings value doesn't change.

```
import libtorrent as lt
import time

ses = lt.session()
sesdict1 = ses.get_settings()

print sesdict1['user_agent']

sett = {}
sett['user_agent'] = "TestAgent/1.6"
ses.apply_settings(sett)

found = False
while not found:
    ua = ses.get_settings()['user_agent']
    if ua == "TestAgent/1.6":
        found = True
    else:
        time.sleep(3)
    print ua
````

any clue? Or, do I call it correctly?

**Comment by arvidn** [comment]
seems like a bug. I'll take a look tonight

**Comment by lawnmowerwcd** [comment]
Can confirm this bug. Not all options are affected. `user_agent` does not work but `alert_mask` for example works.

**Comment by arvidn** [comment]
@ardhipoetra btw, get_settings() is synchronous, and it is guaranteed to return after the settings have been applied (the apply_settings call and the get_settings call are put in the same FIFO queue)

**Comment by arvidn** [comment]
believed to be fixed by: https://github.com/arvidn/libtorrent/pull/652

**Comment by arvidn** [comment]
does anyone know of any other settings than user_agent that's affected? the bug I found only affects user_agent.

**Comment by lawnmowerwcd** [comment]
Seems `user_agent` is the only key causing problems. You can add this test if you like: https://gist.github.com/lawnmowerwcd/86b545be3ed418db53523997a7efb77a

Note: `get_settings()` has an empty str key that cannot be modified using `apply_settings()`

**Comment by ardhipoetra** [comment]
Out of curiosity, why did you merge the fix into RC_1_1 instead of master?

**Comment by arvidn** [comment]
because it was a bug affecting the currently released version. I merge RC_1_1 into master regularly
