### ISSUE TITLE
qBittorrent makes way too many DNS queries when using a SOCKS5 proxy

### ISSUE THREAD

**Issue by MarkWieczorek** [arvidn/libtorrent#6548]
**Please provide the following information**

libtorrent version (or branch): Installed via qbittorent (libtorrent-rasterbar-dbg/focal 1.2.14+git20211025.eb4bbfd49c-1ppa1~20.04 amd64)

platform/architecture:  Ubuntu server 20.04.3

I am connecting to a VPN by a SOCKS5 proxy server (proxy.torguard.org) with qBittorrent. The problem is that when using a proxy connection, qBittorrent makes alot of DNS queries to the proxy server. The number of queries is so large that it sometimes exceeds 1000 queries per minute. When this happens, my pihole DNS resolver exceeds the default number of allowed queries per minute, and hence stops responding to future requests from qBittorrent. This behavior has been [confirmed](https://github.com/qbittorrent/qBittorrent/issues/15652).

I have tried a few things to help fix this issue, but none of them really worked.

    I have disabled "Enable Local Peer Discovery to find more peers"
    I have disabled "Resolve peer countries:"
    I have reduced the number of connections to a maximum of 200.

Though these changes might affect the number of queries, the number of queries is still way higher than what is normal. A possible work around would be to turn off DNS rate limits on pihole, but there is obviously a problem with qBittorrent, so maybe this wouldn't be a good idea. I note that I am only downloading a single file.

I note that the same behavior occurs with the Deluge client on Ubuntu.

**Comment by arvidn** [comment]
interesting, I'll take a look at this

**Comment by arvidn** [comment]
could someone give this patch a try? https://github.com/arvidn/libtorrent/pull/6549

**Comment by MarkWieczorek** [comment]
Thanks for looking into this!

**Comment by arvidn** [comment]
that patch has landed
