### ISSUE TITLE
socket_type.cpp won't go together

### ISSUE THREAD

**Issue by weaselBuddha** [arvidn/libtorrent#6557]
**Please provide the following information**

libtorrent version (or branch): newest

platform/architecture: Linux (ubuntu) / 64-bit 

compiler and compiler version: gcc 7.5.0 / ubuntu 18.04

Made with b2  (boost 1.77) - ground up install of boost

gcc.compile.c++ bin/gcc-7/release/cxxstd-14-iso/fpic-on/lto-on-full/threading-multi/visibility-hidden/src/socket_type.o
.
.
In file included from /usr/local/include/boost/variant/apply_visitor.hpp:16:0,
                 from /usr/local/include/boost/variant/detail/hash_variant.hpp:23,
                 from /usr/local/include/boost/variant/variant.hpp:34,
                 from include/libtorrent/aux_/polymorphic_socket.hpp:39,
                 from include/libtorrent/aux_/socket_type.hpp:44,
                 from src/socket_type.cpp:37:

src/socket_type.cpp:119:47:   required from here
/usr/local/include/boost/variant/detail/apply_visitor_unary.hpp:145:21: error: no match for call to ‘(const libtorrent::aux::idx_visitor) (libtorrent::socks5_stream&)’

Repeated. cmake has the same result.

I'm sure this is on me. What am I doing wrong?

**Comment by userdocs** [comment]
At a glance it hard to say, whether it's not cloning the sub modules or building boost in a weird way, since there is not a lot go on to decipher the issue and I don't know what this means `ground up install of boost`. You do not need to build boost as libtorrent does builds what it needs. Perhaps this is where the issue arises.

So what I can do is show you a successful way to build libtorrent and the python binding on `18:04` using boost `1.77.0` libtorrent `RC_2_0` with cxxstd `17`

```bash
docker run -it -w /root -e "LANGUAGE=en_GB.UTF-8" -e "LANG=en_GB.UTF-8" -v $HOME/build:/root ubuntu:bionic
```

The build script

```bash
#!/usr/bin/env bash

apt-update
apt-get upgrade -y
apt-get install -y build-essential curl pkg-config git perl python3 python3-dev zlib1g-dev libssl-dev # install the deps

boost_v="77" && build_dir="$(pwd)" && lt_branch="RC_2_0" && cxxstd="17 " # set values for boost the build dir and the liborrent branch.
#
curl -sNLk https://boostorg.jfrog.io/artifactory/main/release/1.${boost_v}.0/source/boost_1_${boost_v}_0.tar.gz --create-dirs -o "${build_dir}/lt-build/boost_1_${boost_v}_0.tar.gz"
tar xf "${build_dir}/lt-build/boost_1_${boost_v}_0.tar.gz" -C "${build_dir}/lt-build"
pushd "${build_dir}/lt-build/boost_1_${boost_v}_0/" || exit
"${build_dir}/lt-build/boost_1_${boost_v}_0/bootstrap.sh"
#
export BOOST_BUILD_PATH="${build_dir}/lt-build/boost_1_${boost_v}_0" # once boost is bootstrapped and b2 is built you only need to set this for b2 + libtorrent.
#
echo "using gcc : $(gcc -dumpversion) : g++-$(g++ -dumpversion) ;" > "$HOME/user-config.jam" # Create this file for b2: -dumpversion may give return a bad result outside a debian based systems
#
git clone --single-branch --branch "${lt_branch}" --shallow-submodules --recurse-submodules --depth 1 https://github.com/arvidn/libtorrent "${build_dir}/lt-build/libtorrent"
#
pushd "${build_dir}/lt-build/libtorrent" || exit
#
"${build_dir}/lt-build/boost_1_${boost_v}_0/b2" -j"$(nproc)" fpic=on lto=on optimization=speed cxxstd="${cxxstd}" variant=release dht=on encryption=on crypto=openssl i2p=on extensions=on threading=multi install --prefix="${build_dir}/libs"

# ${build_dir}/libs/libtorrent-rasterbar.so

# You also want the python bindings then use these commands
python_major="$(python3 -c "import sys; print(sys.version_info[0])")"
python_minor="$(python3 -c "import sys; print(sys.version_info[1])")"
echo "using python : ${python_major}.${python_minor} : /usr/bin/python${python_major}.${python_minor} : /usr/include/python${python_major}.${python_minor} : /usr/lib/python${python_major}.${python_minor} ;" >> "$HOME/user-config.jam"
#
pushd "${build_dir}/lt-build/libtorrent/bindings/python" || exit
#
"${build_dir}/lt-build/boost_1_${boost_v}_0/b2" -j"$(nproc)" fpic=on lto=on optimization=speed cxxstd="${cxxstd}" variant=release dht=on encryption=on crypto=openssl i2p=on extensions=on threading=multi install_module python-install-path="${build_dir}/libs"

# ${build_dir}/libs/libtorrent.so
```

**Comment by userdocs** [comment]
I fixed two small but script breaking typos

**Comment by weaselBuddha** [comment]
Thank you. Will take a look at the script.

Will take a look, was hoping someone could chime in with a specific insight.

Boost was downloaded as source and built "from the ground up", which may indeed be the problem. The assertion that boost needn't be built, isn't that also the case of the library, and the target torrent client?

**Comment by userdocs** [comment]
```bash
libboost_system.so->libboost_system.so.1.77.0
libboost_system.so.1->libboost_system.so.1.77.0
libboost_system.so.1.77->libboost_system.so.1.77.0
libboost_system.so.1.77.0
libtorrent-rasterbar.so->libtorrent-rasterbar.so.2.0.4
libtorrent-rasterbar.so.2->libtorrent-rasterbar.so.2.0.4
libtorrent-rasterbar.so.2.0->libtorrent-rasterbar.so.2.0.4
libtorrent-rasterbar.so.2.0.4
libtry_signal.a
pkgconfig
```

This is what you get from the method I demonstrated. `libtry_signal.a` specific to v2 and `libboost_system.so` which is always built. This is all that is needed by any client to link successfully. How that is linked depends on whether you used b2 + qmake or b2 + cmake or cmake + cmake when building libtorrent + qbittorrent, since if it was deluge we'd be using the binding and that's not an issue.

If you use all cmake + cmake you don't need certain files just the boost headers since it won't be using pkgconfig. If you mix and match you need the pkgconfig setup and build the files using b2

Your issue is not an issue in the sense that that there is a problem building libtorrent on bionic as the script can be set to use libtorrent RC_1_2 and or cxxstd 14 and successfully build. So if the correct method is applied to boot strap and build then the issue should go away.

**Comment by userdocs** [comment]
For cmake if you look here for what I do with Alpine, you can see how boost the boost files are used when using cmake instead of b2

https://github.com/qbittorrent/qBittorrent/wiki/Compilation:-Alpine-Linux#boost-build-files

**Comment by weaselBuddha** [comment]
Cheers. 

Does anyone have specific insight in what is going awry with the particular issue I'm encountering while compiling the library, with socket_type.cpp compilation error?

**Comment by arvidn** [comment]
@weaselBuddha could you post what command line you use to build libtorrent?
Could you post the actual error message? What you pasted in the main post was just part of it, and not the actual error itself.

**Comment by arvidn** [comment]
when you say: "libtorrent version (or branch): newest"

Do you mean head of master or the commit with the most recent timestamp on it?

**Comment by arvidn** [comment]
my guess is that you pick up old libtorrent headers from the system include paths, like `/usr/local/include`.

The latest version of libtorrent does not use `boost::variant`, it uses `std::variant`

**Comment by weaselBuddha** [comment]
Jeez, really appreciate the responses

We are following build directions:

git clone --recurse-submodules https://github.com/arvidn/libtorrent.git

And then

export CXXFLAGS="-O5 -Q"
export LD_LIBRARY_PATH=/usr/local/lib

 b2  fpic=on lto=on optimization=speed cxxstd="14" variant=release dht=on encryption=on crypto=openssl i2p=on extensions=on threading=multi link=shared runtime-link=shared install

We think we had the wrong BOOST_BUILD_PATH

I'm verifying that now







I think we have this figured out, we think we were pointing to the wrong BOOST_BUILD_PATH, changing that seems
