### ISSUE TITLE
Examples incorrectly work with non-ascii characters on windows, also CAPITAL drive letter in arguments causes error

### ISSUE THREAD

**Issue by gtumanyan** [arvidn/libtorrent#6566]
libtorrent version (or branch): 1.2.15, 2.0.4

platform/architecture: Windows 11 x64 21H2 (with latest updates), reproduces on any Windows version

compiler and compiler version: Microsoft (R) C/C++ Optimizing Compiler Version 19.31.30818 for x64, boost 1.7.8

Unable to use Russian symbols in paths for adding torrents or saving for any example code.
client_test.exe -s D:\Документы\ Drivers.torrent -f log.txt
Log.txt: `[1583] drivers mkdir (E:\sdi\project\vs_libtorrent\x64\examples\Debug\D:\Документы\drivers\DP_Video_Intel-NT_21113.7z) error: The filename, directory name, or volume label syntax is incorrect`
[log.txt](https://github.com/arvidn/libtorrent/files/7597742/log.txt)

**Comment by wrtorrent** [comment]
> E:\sdi\project\vs_libtorrent\x64\examples\Debug\D:\...

`D:` in E: path, `:` not allowed

**Comment by gtumanyan** [comment]
It's just how the logger concatenates the strings. The command line is 

> client_test.exe -s D:\Документы -f log.txt Drivers.torrent

There is only one ":" in the string

**Comment by gtumanyan** [comment]
client_test.exe -s d:\Test Drivers.torrent - works
client_test.exe -f log.txt -s D:\Test Drivers.torrent - "invalid argument"
`6075] drivers mkdir (E:\sdi\project\vs_libtorrent\x64\examples\Debug\D:\Test\drivers\DP_Videos_AMD_Legacy-NT_21101.7z) error: The filename, directory name, or volume label syntax is incorrect`
client_test.exe -s d:\Тест -f log.txt Drivers.torrent - works, but save folder name is "����", not "Тест"

**Comment by arvidn** [comment]
@gtumanyan does your shell encode those characters as UTF-8? If not, it's not a problem in libtorrent. The examples aren't meant to demonstrate how to convert from the local locale to utf-8.

I would expect your shell might use `\` as an escape character. Are you sure you don't need to put those strings in quotes or use double `\`?

**Comment by gtumanyan** [comment]
Windows 11 cmd console uses OEM  code page by default, not UTF-8.



> The examples aren't meant to demonstrate how to convert from the local locale to utf-8.

The drive letters printed in capital case cause the "The filename, directory name, or volume label syntax is incorrect" error.

**Comment by arvidn** [comment]
please try this out https://github.com/arvidn/libtorrent/pull/6569

**Comment by arvidn** [comment]
actually, I'll rebase it onto `RC_1_2`
