### ISSUE TITLE
libtorrent-rasterbar.pc installs into wrong path

### ISSUE THREAD

**Issue by Albert1st1** [arvidn/libtorrent#6574]
libtorrent version (or branch):
libtorrent-rasterbar-1.2.14.tar.gz
platform/architecture:
Slackware64-current
compiler and compiler version:
gcc 11.2.0
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
I compiled with 
cmake \
    -DCMAKE_CXX_FLAGS:STRING="-O2 -fPIC" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib64 \
    -DCMAKE_BUILD_TYPE=Release \
    -Dpython-bindings=ON \
    -Dboost-python-module-name="python" \
    -Dpython-egg-info=ON ..
make
make install DESTDIR=/tmp/build/

and it installs libtorrent-rasterbar.pc in usr/usr/lib64/pkgconfig/libtorrent-rasterbar.pc
I expect it to be installed in usr/lib64/pkgconfig/libtorrent-rasterbar.pc so other things i compile can find it.

cat libtorrent-rasterbar.pc
prefix=/usr
libdir=${prefix}//usr/lib64

Name: libtorrent
Description: Bittorrent library
Version: 1.2.14
Libs: -L${libdir} -ltorrent-rasterbar -L/usr/lib64 -lpthread -lssl -lcrypto -lcrypto
Cflags: -fexceptions -I/usr/include -DTORRENT_LINKING_SHARED -DBOOST_ASIO_ENABLE_CANCELIO -DTORRENT_USE_ICONV -DTORRENT_USE_OPENSSL -DTORRENT_USE_LIBCRYPTO

**Comment by userdocs** [comment]
What happens if you do

```
DCMAKE_INSTALL_LIBDIR=/lib64
```

Because it appears you issues in this path

```
usr/usr/lib64/pkgconfig/libtorrent-rasterbar.pc
```

Is the combination of these settings

```
-DCMAKE_INSTALL_PREFIX=/usr
-DCMAKE_INSTALL_LIBDIR=/usr/lib64
```

**Comment by userdocs** [comment]
It worked for me if the path was trelative to the install dir.

So no leading `/`

```
-DCMAKE_INSTALL_LIBDIR=lib64
```

I get this

```
prefix=/root/qbt-build
libdir=${prefix}/lib64

Name: libtorrent
Description: Bittorrent library
Version: 1.2.14
Libs: -L${libdir} -ltorrent-rasterbar -L/root/qbt-build/lib -lIconv::Iconv -lssl -lcrypto -ldl -ldl -lcrypto
Cflags: -fexceptions -I/root/qbt-build/include -I/root/qbt-build/boost -DBOOST_ASIO_ENABLE_CANCELIO -DTORRENT_USE_ICONV -DTORRENT_USE_OPENSSL -DTORRENT_USE_LIBCRYPTO
```

**Comment by userdocs** [comment]
But it looks like this part is hardcoded

```
Libs: ... -L/root/qbt-build/lib
```

**Comment by Albert1st1** [comment]
-DCMAKE_INSTALL_LIBDIR=lib64 installs everything in the right path.

cat libtorrent-rasterbar.pc
prefix=/usr
libdir=${prefix}/lib64

Name: libtorrent
Description: Bittorrent library
Version: 1.2.14
Libs: -L${libdir} -ltorrent-rasterbar -lpthread -lssl -lcrypto -lcrypto
Cflags: -fexceptions -I/usr/include -DTORRENT_LINKING_SHARED -DBOOST_ASIO_ENABLE_CANCELIO -DTORRENT_USE_ICONV -DTORRENT_USE_OPENSSL -DTORRENT_USE_LIBCRYPTO

**Comment by userdocs** [comment]
So that fixed the problem for you?

**Comment by Albert1st1** [comment]
Yes it's fixed so issue resolved.
