### ISSUE TITLE
Custom field in the "info" section?

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6575]
@arvidn 1) Can I add my own field, with my own content, to the "info" section?
Will this prevent the torrent file from being distributed via magnet links? Maybe it will break something else? What problems might occur?

2) Will other torrent clients be able to open such a torrent file?

**Comment by arvidn** [comment]
yes you can. Just keep in mind that once set, it's "set in stone" changing it will change the info-hash and be a different swarm.

As long as the key is not used as an extension by any other client, it should be ignored.

**Comment by arvidn** [comment]
it will not prevent it from being a magnet link. In fact, your content will be included in the metadata shared by peers in a magnet link swarm.

**Comment by master255** [comment]
@arvidn Can it be that other torrent clients will calculate hash only by certain fields of info section and they will not match info hash?

**Comment by arvidn** [comment]
no. custom fields in `info` dictionary has been done many times before and clients support them. The one thing to look our for is if you insert the field out-of-order (which is invalid according to spec), clients sometimes disagree on what the hash is. But I think it's mostly a thing of the past.
