### ISSUE TITLE
Loading from another swarm

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6578]
@arvidn I am using the 1.2.13 version of the library.

On the first computer I have files distributed in alignment by pieces.
On the second computer I download them.

When I change at least one file on the first computer (and recreating the torrent file.), the second computer stops downloading.
I tried adding the same line in the collection - did not help.

What do I need to do to keep downloading? After all, the hashes of unchanged files are the same.
Perhaps another version of the library can do this? Or did I use the collections incorrectly somehow?

**Comment by arvidn** [comment]
> When I change at least one file on the first computer (and recreating the torrent file.), the second computer stops downloading.
> I tried adding the same line in the collection - did not help.

Why does it stop downloading? Is it because you change the file from under the feet of the seeder and it ends up sending corrupt data to the downloader?

If you don't want the download to stop, don't change the file. If you want the downloader to download the new file, add the new torrent to its session

**Comment by arvidn** [comment]
> Why doesn't it start?

I was going to ask you that. Do you have any peers?

see this trouble shooting guide: https://libtorrent.org/troubleshooting.html

> How do the collections work? I couldn't find any details about this anywhere. What data should be put in the collections and how will it work?

Collections are arbitrary names you can associate with torrents. Torrents belonging to the same collection (i.e. having a matching string in the collections list) will be assumed to share many piece hashes. It's a hint to libtorrent to go compare them and possibly reuse files.

iirc, files are only reused from seeding torrents, this is to avoid having to coordinate which pieces are downloaded across swarms.

**Comment by master255** [comment]
@arvidn 

> I was going to ask you that. Do you have any peers?

1) Probably not. Are the peers computers with the same hash I'm looking for?
2) Or are peers computers with the same or similar hash mentioned in the info section of the torrent file?
3) Or are peers computers with the same hash or similar collections mentioned in the info section of the torrent file?

**Comment by arvidn** [comment]
peers are other clients part of the same swarm as you. A swarm is identified by its info-hash.

**Comment by arvidn** [comment]
the "mutable torrents" feature is purely local to your machine. Think of it as a way to hint that you may have large portions of a torrent already. i.e. if you have downloaded version 1 of a torrent, downloading v2 may reuse most of the files you already have from v1.

**Comment by master255** [comment]
@arvidn Okay. I got it.
Why aren't similar hashes used to find pieces of files?
It's an obvious feature and should be easy to add to the library functionality.

**Comment by arvidn** [comment]
> Why aren't similar hashes used to find pieces of files?

I don't know what you mean by that. This is exactly what happens, as I described above. if the v2 torrent has a "similar" field pointing to the v1 torrent, libtorrent will look for matching pieces in v1 for v2, and reuse identical files.

**Comment by master255** [comment]
@arvidn Why aren't similar hashes used to search for file pieces in DHT and trackers?

**Comment by master255** [comment]
@arvidn ?

**Comment by arvidn** [comment]
because piece hashes aren't announced to DHT or trackers,

**Comment by arvidn** [comment]
yes, that's possible

**Comment by master255** [comment]
@arvidn Okay. This functionality would be very useful. We are waiting for it to appear.

**Comment by master255** [comment]
@arvidn And if this feature is going to work, a new search function for a similar torrent is needed:
torrent_session.find_similar_torrent(sha1);
This function should return a torrent_handle_vector that will contain all torrent_handles that match the main sha1 or similar.

**Comment by master255** [comment]
@arvidn Without it, my editable torrents will stop downloading after any change in the source. This is very bad.

**Comment by arvidn** [comment]
the issue you're experiencing is not related to editable torrents. It's because you stop seeding the v1 torrent when you start seeding v2. That's not supported. always seed all versions

**Comment by master255** [comment]
@arvidn Okay. You're right. It's not really about editable torrents.

Editable torrents require different functionality:

It needs the server to check similar torrents and distribute pieces of them when they are requested by the client.
Is it possible to do this?

**Comment by master255** [comment]
@arvidn Where is my answer?

**Comment by master255** [comment]
> Editable torrents require different functionality:

It needs the server to check similar torrents and distribute pieces of them when they are requested by the client.
Is it possible to do this?

@arvidn When will this functionality be implemented and will it be implemented?

**Comment by master255** [comment]
This is interesting, but with https torrents I was able to download data from different torrents. That's cool :-)

My Media Library supports swarm merging

**Comment by zero77** [comment]
> This is interesting, but with https torrents I was able to download data from different torrents. That's cool :-)
> 
> My Media Library supports swarm merging
> 
> Of course, I would like to see this functionality in regular torrents.

@master255 

Is this something you could create a PR for.

**Comment by master255** [comment]
@zero77 you are too naive. My ideas are not accepted here, much less my PR.

**Comment by master255** [comment]
@arvidn I haven't had a chance to test it yet.
Is there any such functionality in the second version of the library?
**Is there any way to download data from a torrent that has a different main hash than needed? Of course, if the hash of the files matches.**

Otherwise, what good is updating to version 2.0?

**Comment by AllSeeingEyeTolledEweSew** [comment]
>  **Is there any way to download data from a torrent that has a different main hash than needed? Of course, if the hash of the files matches.**

Sounds like a version of https://github.com/arvidn/libtorrent/issues/5168#issuecomment-697512432, except it sounds like you already know the swarms you want to use, so you don't need the announcing part.

I do think some version of that would be a cool idea. There's a heck of a lot of redundancy between swarms in the wild, and being able to make use of it would be a really good selling point for v2.

**Comment by master255** [comment]
@arvidn @zero77 @AllSeeingEyeTolledEweSew @gubatron @aldenml @proninyaroslav
I finally finished the real swarm merge.
It allows torrent with hash 1 to find torrent with hash 2 in DHT and download files from it if it has them.
It does not increase CPU load and has no drawbacks.
How it works:
This is made possible by several technologies I invented.
The user creates a torrent with hash 1. Distributes it to other users.
Then modifies it and updates it (my technology for updating the torrent without recalculating the hash of all files, just the ones that have changed). While updating the torrent file the hash of the old torrent is written to it and an array of hashes of the old distributions is stored in it. 
When users start downloading this torrent file a get_peers request is made for all torrent hashes from the old hash array.
When peers are returned with the torrentHandle.connect_peer method (this is our only torrent) new peers are added to the torrentHandle. But this method is modified as follows:
torrentHandle.connect_peer(peers.get(r), peer_source_flags_t.all(), pex_flags_t.all(), replyAlert.getInfo_hash());
The last parameter is the hash of the torrent for which these peers fit.
As a result, the handshake is executed with this infohash and the peer replies with the handshake. And this hash contains the https port number to connect to the https torrent server of this peer (my technology which allows you to download torrents via https protocol). **Downloading via https protocol begins :-) applause!** 

True swarm merging will be included in the new version of [Media Library 10.8](https://t.me/media_library)

**Comment by master255** [comment]
@hbednar I don't think Arvidn wants that. It's 100% unlikely to be approved.
I created a progressive version of Libtorrent.
Arvidn creates a conservative version.
If you need my library code, message me in Telegram in our group: https://t.me/libtorrent_ru
