### ISSUE TITLE
How redownload deleted file?

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6579]
@arvidn I have a big 1TB torrent with a million files in it.

All files are checked and the torrent is distributed.
Then I purposely delete one file of 20MB.
And I want to download it again.
How do I do this without checking all the files?

Checking all files takes a very long time. Which file I know exactly.

**Comment by arvidn** [comment]
the simplest way I can think of is to remove and re-add the torrent and specify that you have all files except that one you removed in the resume data (i.e. in the `add_torrent_params` object)

**Comment by master255** [comment]
@arvidn Why don't you want to make a method for that? In my opinion, this functionality is a must.
Reset file progress in torrent_handle.
Without this it is impossible to re-download.

And this is some simple method. Without global changes.

**Comment by master255** [comment]
@arvidn If you don't want to include this in the library, maybe you can write me the file_progress.cpp and/ or torrent.cpp method here? 
I'm sure it's not hard to do. Just outline it quickly. I'll test it and let you know what happens.

**Comment by master255** [comment]
@arvidn 

> it's the have_pieces field: http://libtorrent.org/reference-Add_Torrent.html#have_pieces

This cannot be used because disabling torrent_handle will break connections to peers.
Then I will need to move the priorities of all the files. To do this I will have to convert the vectors.
Then it will start searching for the peers that were just disconnected and waiting for timeouts for about 5 minutes to reconnect to them.
This is a very long process.

**Comment by master255** [comment]
@arvidn The other reason is that I cannot remove the torrent_handle since it is used for streaming.

My player has a preload of the next tracks. These next files may already be deleted by the autoclean system and to pre-download them I need to delete the torrent_handle, and it is used for streaming right now. So I can't pre-download the next files.

**Comment by arvidn** [comment]
> I'm sure it's not hard to do. Just outline it quickly.

Patches are welcome, just make sure there are good tests.

> This cannot be used because disabling torrent_handle will break connections to peers.

The BitTorrent protocol does not support telling peers that a you no longer have a piece, that use previously had. The only way to communicate that is to reconnect.

libtorrent has an extension message for this (`lt_dont_have`), and peers that already have the pieces you lost could probably stay connected.

**Comment by master255** [comment]
@arvidn 

> Patches are welcome, just make sure there are good tests.

Can you roughly write the method? And I'll debug it, check it, and report the results. Maybe I'll create a patch.
I have absolutely no idea how to do it.

> The BitTorrent protocol does not support telling peers that a you no longer have a piece

Now I did it with addTorrentParams, but that resets the torrent_handle too often. This is costly for resources. There are too many nuances to consider.

And I restored the entry method torrent_handle::write_resume_data(); in this case it is very hard to use it asynchronously. I recommend to restore it.

**Comment by master255** [comment]
@arvidn Where is my answer?

**Comment by master255** [comment]
@arvidn If you help me, I will help you get rid of version 1.2.

**Comment by master255** [comment]
@arvidn It's actual

**Comment by master255** [comment]
Another way to re-download a deleted file if data validation is turned off:
1. Unprioritize all files and prioritize only the deleted file. 
2. Run handle.force_recheck();

**Comment by master255** [comment]
@arvidn as you can see, your library has this function. But it is for the mode when there is no file checking.

You need the same function, but for the mode with file checking. If it is possible to reset the progress of a file by data checking, then there must be a function to reset the progress without full data checking. You should write it. It is really necessary for everyone who has auto-cache clearing of downloaded data.

The variant you suggested - removing and adding torrents - does not work well and causes a lot of bugs.

**Comment by master255** [comment]
Or add a quick file checker.

**Comment by master255** [comment]
And an elegant way to do it:
in torrent.cpp:
```
    void torrent::clear_file_progress(file_index_t const index, piece_index_t const start_piece, piece_index_t const end_piece) {
        if (has_picker()) {
            for (piece_index_t i = start_piece; i < end_piece; ++i) {
                m_picker->we_dont_have(i);
            }
            update_gauge();
        }
        m_file_progress.clear_file(index);
    }
```
in file_progress.cpp:
```
    void file_progress::clear_file(file_index_t const index)
    {
        m_file_progress[index] = 0;
    }
```
