### ISSUE TITLE
2.0.4 / android: Generate libraries without the version extension

### ISSUE THREAD

**Issue by 3unjee** [arvidn/libtorrent#6580]
I'm building 2.0.4 for Android and I would like to generate a single `lib.so` dynamic library  as opposed to the `lib.so.x.x.x` format.  

That way I can link my binary against a plain and simple `libtorrent-rasterbar.so`.

Is there an easy way to do this with b2 ?

EDIT: By the way that's actually an issue on Android since Gradle only accepts .so library files without version extensions.

**Comment by master255** [comment]
@3unjee How will your VLC work on Windows if there is no separation of architectures?

Where did the Android problem come from. My Android app has architecture separation and it really reduces the size of the app and I think the speed of the app. Use Jar files like everyone else.

**Comment by 3unjee** [comment]
I'm currently using static android libraries instead of so.x.x.x and AFAIK gradle won't accept anything that's not `.so`.

**Comment by 3unjee** [comment]
> @3unjee How will your VLC work on Windows if there is no separation of architectures?
> 
> Where did the Android problem come from. My Android app has architecture separation and it really reduces the size of the app and I think the speed of the app. Use Jar files like everyone else.

On windows it's `libtorrent-rasterbar.dll.a` and `libtorrent-rasterbar.dll` for x86 and X86_64.

**Comment by master255** [comment]
@3unjee 

> On windows it's libtorrent-rasterbar.dll.a and libtorrent-rasterbar.dll for x86 and X86_64.

Did you hear that Android will be supported by Windows?
Have you heard that Android emulators for Windows fully support torrents? NoxPlayer, for example.
https://docs.microsoft.com/en-us/windows/android/wsa/
Your dlls are almost irrelevant.

> AFAIK Gradle won't accept anything that's not .so.

I am using gradle-6.7.1. It fully supports Jar files. What version of gradle do you use?

**Comment by 3unjee** [comment]
I'm building libtorrent with ClangC++ which generates a .so file and I'm using these directly, not jar.

**Comment by master255** [comment]
@3unjee Okay. Don't you know that a jar is a packed so file? It's the same thing.

**Comment by arvidn** [comment]
@3unjee there is no way to make the output .so file not be versioned. This is a convention on unix-like systems to mitigate ABI incompatibility issues. When a library is built, its ABI version is appended to the filename, and a plain .so *symbolic link* is created pointing to the versioned file. The idea is that your build file refers to the plain .so file, but the file your binary depends on is the versioned one, since your binary also will depend on the actual ABI you ended up linking against.

If you want your binary to depend on a plain .so filename, you can rename the versioned library before linking against it. But doing so, you should realize that just renaming the file doesn't change the fact that you still depend on the ABI of the library you ended up linking against. It won't work to replace that .so file with a different (ABI) version of the library,

**Comment by userdocs** [comment]
Is there any benefit to using a share lib in this case? I don't now gradle or android stuff but I was reading and it looks like it can link to a prebuilt static lib fine?

And stuff like this?

https://coderedirect.com/questions/388305/how-to-create-a-static-library-a-file-in-android-studio-3-2-with-cmake

I fail to the see the benefit of a shared lib in thus usage.

**Comment by master255** [comment]
@userdocs We already have all the necessary jar libraries. There is no need to invent anything.
https://github.com/aldenml/libtorrent4j
https://github.com/frostwire/frostwire-jlibtorrent

**Comment by userdocs** [comment]
I don't have an opinion on any of that i just read you can link static prebuilt libs using gradle. So that makes the issue not an issue i guess?

**Comment by 3unjee** [comment]
> @3unjee there is no way to make the output .so file not be versioned. This is a convention on unix-like systems to mitigate ABI incompatibility issues. When a library is built, its ABI version is appended to the filename, and a plain .so _symbolic link_ is created pointing to the versioned file. The idea is that your build file refers to the plain .so file, but the file your binary depends on is the versioned one, since your binary also will depend on the actual ABI you ended up linking against.

Yes, I actually found a way to generate .so libraries without versioning by messing with the `Jamfile` in libtorrent and the `boostcpp.jam` for Boost libraries. But that's not ideal, so I went back to static libraries for my use case. Which is probably better anyway.

Thank you for your support.

**Comment by 3unjee** [comment]
> @userdocs We already have all the necessary jar libraries. There is no need to invent anything. https://github.com/aldenml/libtorrent4j https://github.com/frostwire/frostwire-jlibtorrent

Thank you for pointing that out but I'm developping a native C / C++ application based on libVLC. So the less Java the better.

**Comment by master255** [comment]
@3unjee I installed your MotionBox. Tested it.
It's very strange to start developing a player in the 21st year. Also, your player is only for Windows, which is very irrelevant. Windows has very poor HDR support and it uses an audio resampler which cuts down on quality. Users don't have big screen devices on Windows.
For example, my Android "Media Library" player works for me: 
1. on a Windows server via a Nox emulator
2. in my Sony TV
3. on my phone
4. in my car via my phone
5. on my Windows computer via Nox emulator.
In other words on all devices and all places.

Soon there will be no need for emulator and Windows 11 will be able to run my player without emulators.
I have been developing my player for over 7 years. You will never catch up with it in terms of functionality and features.

If you continue to develop it, it will only make my player less popular. So you want to make it better and help users, but you only make it worse.

You can help promote my player. It would be logical.
Maybe you can write a critique about my player too, but I know almost everything already.
