### ISSUE TITLE
Python binding's Jamfile doesn't work with Python 3.10 (wrong number comparison)

### ISSUE THREAD

**Issue by sergiodj** [arvidn/libtorrent#6584]
We currently have Python 3.10 in Debian and I'm working on getting libtorrent-rasterbar to build with it.  Because of the following excerpt from the Jamfile:

https://github.com/arvidn/libtorrent/blob/53f90cf6f5108990a89a1eb0a5a6f0b9d3245f97/bindings/python/Jamfile#L114-L117

the package is currently FTBFS'ing:

```
...
gcc.link.dll bin/gcc-11/release/address-model-64/lt-visibility-hidden/python-3.10/libtorrent.cpython-310-x86_64-linux-gnu.so
/usr/bin/ld: cannot find -lboost_python-py310
...
```

The problem is that the `-py` infix is being included in the library name, which is wrong.  The code *should* be working, but it seems like `bjam` (or whatever it is that processes these files) can't do the version number comparison properly.

I hacked a quick Jamfile here to try and investigate the issue:

```
if 3.10 < 3.7 { ECHO "TEST" ; }
```

Parsing it with `bjam` confirms the suspicion:

```
# bjam 
TEST
```

**Comment by AllSeeingEyeTolledEweSew** [comment]
@arvidn the `cibuildwheel` workflows have been building against python 3.10, but only ever statically, so we haven't hit this.

**Comment by userdocs** [comment]
Neither Debian or Ubuntu are python 3.9 in [Sid](https://packages.debian.org/sid/python3)/[Hirsute](https://packages.ubuntu.com/search?suite=hirsute&searchon=names&keywords=python3)

Where are you getting 3.10 from?

Here is example a Debian stable build.

```
gcc.compile.c++ bin/gcc-10/release/address-model-64/cxxstd-17-iso/fpic-on/libtorrent-python-pic-on/python-3.9/threading-multi/src/...
```

Where are you getting 3.10 from?

![image](https://user-images.githubusercontent.com/16525024/144820049-d92c3f8e-8fa6-4b47-b53b-0b8e06837279.png)

You are using RC_2_0? You did not specify but your linked the RC_2_0 `libtorrent/bindings/python/Jamfile`

So i think you need to provide some more details about what you are doing and how.

How did you get python 3.10?
How are you linking boost? system libs or from source?
Which version of boost??
What version of libtorrent are you using?

This maybe be a legitimate issue with python 3.10 but your issue info is vague.

**Comment by arvidn** [comment]
@sergiodj Thanks for the report! does this patch fix it? https://github.com/arvidn/libtorrent/pull/6585

**Comment by sergiodj** [comment]
> Neither Debian or Ubuntu are using python 3.10 in [Sid](https://packages.debian.org/sid/python3)/[Hirsute](https://packages.ubuntu.com/search?suite=hirsute&searchon=names&keywords=python3)

I think you meant Ubuntu Jammy.  Hirsute has been released in 21.04.

> Where are you getting 3.10 from?

From Debian unstable.  `python3-defaults` still defaults to Python 3.9, but we already have Python 3.10 in the archive and are working towards getting it supported.

> Here is example a Debian stable build.
> 
> ```
> gcc.compile.c++ bin/gcc-10/release/address-model-64/cxxstd-17-iso/fpic-on/libtorrent-python-pic-on/python-3.9/threading-multi/src/...
> ```
> 
> Ubuntu Focal
> 
> ![image](https://user-images.githubusercontent.com/16525024/144820049-d92c3f8e-8fa6-4b47-b53b-0b8e06837279.png)

Sorry, I fail to see how building the package on Debian stable or Ubuntu Focal (20.04) will help here.  The problem happens with Python 3.10, which is not present in either of these distros.

> You are using RC_2_0? You did not specify but your linked the RC_2_0 `libtorrent/bindings/python/Jamfile`

Debian unstable currently has libtorrent-rasterbar version 1.2.14; version 2.0 will eventually show up in experimental.  I linked the Jamfile from `master` because it is exactly the same as the one present in Debian.

> So i think you need to provide some more details about what you are doing and how.
> 
> How did you get python 3.10? How are you linking boost? system libs or from source? Which version of boost?? What version of libtorrent are you using?

Python 3.10 is present in Debian unstable.  We're using the boost libraries from Debian unstable also, version 1.74.  libtorrent version 1.2.14.

You can easily reproduce this problem in a Debian unstable chroot.  Let me know if you need pointers on how to do that.

> This maybe be a legitimate issue with python 3.10 but your issue info is vague.

This is actually an issue with how Jamfiles compare version numbers.

**Comment by sergiodj** [comment]
> @sergiodj Thanks for the report! does this patch fix it? #6585

Thanks, @arvidn.  I'll comment on the PR :-).

**Comment by userdocs** [comment]
Do you know the difference between Debian stable and experimental when referencing an OS in an issue? if you had used the the issue template it would not have been so misleading. Let me know if you need pointers on how to do that.

**Comment by sergiodj** [comment]
> Do you know the difference between Debian stable and experimental when referencing an OS in an issue? if you had used the the issue template it would not have been so misleading. Let me know if you need pointers on how to do that.

Sorry, I don't understand the question.  I do know the difference between Debian stable, unstable and experimental (and by the way, Debian experimental is not a real distribution and doesn't relate to this bug).  I should probably have mentioned explicitly that I am doing the development on Debian unstable, but I considered that this was clear given the fact that I mentioned Python 3.10, which is obviously not part of Debian stable.  I apologize if failing to mention Debian unstable caused was confusing to you.

I appreciate that @arvidn has already fixed the issue upstream.  I will proceed with the backporting of the patch downstream; thanks!

**Comment by arvidn** [comment]
since I've landed that patch, I'll close this
