### ISSUE TITLE
sha1 and sha512 implementations are redundant in the presence of OpenSSL

### ISSUE THREAD

**Issue by UnitedMarsupials** [arvidn/libtorrent#659]
**Please provide the following information**

libtorrent version (or branch): rasterbar-1.1.0

platform/architecture: FreeBSD-10/amd64

compiler and compiler version: clang-3.4.1

I see, that the included implementations of sha1 and sha512 are compiled and linked in, even when OpenSSL is used to provide encryption. OpenSSL's own implementations of these digests should be used instead.

First `hasher.cpp` needs to stop including `sha1.hpp` -- `hasher.hpp` already does that, and only when necessary:

``` diff
--- src/hasher.cpp      2016-04-10 17:39:15.000000000 -0400
+++ src/hasher.cpp      2016-04-28 01:03:58.003106000 -0400
@@ -32,5 +32,4 @@

 #include "libtorrent/hasher.hpp"
-#include "libtorrent/sha1.hpp"

 namespace libtorrent
```

Then the Makefiles in `src/` and `include/libtorrent/` need to be told to only include `sha1.[ch]pp` if `@WITH_OPENSSL_FALSE@`. And then something similar needs to happen to `sha512`.

**Comment by UnitedMarsupials** [comment]
This file takes care of sha1 for me -- [patch-redundant-digests](https://github.com/arvidn/libtorrent/files/239852/patch-redundant-digests.txt). Not sure, how to properly modify `Makefile.am`. Hope, this helps...

**Comment by aldenml** [comment]
I'm not sure fixing this in `RC_1_1` worth the effort, in master it is fixed with https://github.com/arvidn/libtorrent/pull/1028

**Comment by arvidn** [comment]
I guess this is the case for the makefiles. The Jamfile only include ``sha1.cpp`` when the ``<crypto>build-in`` feature is set.

**Comment by arvidn** [comment]
does this look like a reasonable fix? (mostly back-ported from aldenml's patch): https://github.com/arvidn/libtorrent/pull/1040

**Comment by lyssdod** [comment]
are there plans to enable this for CMake?

**Comment by arvidn** [comment]
if you use cmake, please submit a pull request! it should be a pretty straight-forward back-port of aldenml's patch to master that he linked to. (and make sure cmake still builds)
