### ISSUE TITLE
torrent_flags::no_verify_files + file_storage set_name is not work with magnet link 

### ISSUE THREAD

**Issue by stdjs** [arvidn/libtorrent#6595]
**Please provide the following information**

libtorrent version (or branch): 2.0

platform/architecture:opensuse x86_64 

compiler and compiler version: gcc 11

//------------------------------------

first:
I create a task -> download -> remove_torrent (without lt::session_handle::delete_files)

![image](https://user-images.githubusercontent.com/16369899/145697496-306749b5-db38-4bc9-82ba-f19a2deb6f35.png)

keep directory 2 exists on 
/home/devel01/Downloads/test/2/

//------------------------------------
then: 

I use same magnet link create a new task,but with another name (new_name):

```
lt::error_code error;
lt::add_torrent_params params;

....
lt::parse_magnet_uri("magnet:...........................",params,error);
params.flags |= lt::torrent_flags::no_verify_files; 

async_add_torrent(std::move(params))
```

call set_name to change root directory name.

```
on lt::metadata_received_alert
{
  ((lt::file_storage&)handle_.torrent_file()->files()).set_name("new_name")
}
 ```

set_name is not work, the root directory name still "2" instead of "new_name".

but if i pass magnet link, just use torrent file, no_verify_files flag is working.

/home/devel01/Downloads/test/new_name/ 
created

```

lt::add_torrent_params params;
...
params.ti = std::make_shared<lt::torrent_info>("torrent_path......",error);
params.flags |= lt::torrent_flags::no_verify_files; 
async_add_torrent(std::move(params))


on lt::add_torrent_alert
{
((lt::file_storage&)handle_.torrent_file()->files()).set_name("new_name")
}
```

purpose is use no_verify_files flag to skip disk file check,so i can use set_name to set directory name,but for magnet link,the lt::torrent_flags::no_verify_files flag doesn't seem to work.

**Comment by arvidn** [comment]
First of all, this code is undefined behaviour. Whatever your program is doing, it's according to specification (i.e. undefined). Please don't do this:

```
((lt::file_storage&)handle_.torrent_file()->files()).set_name("new_name")
```

You can call this on a `torrent_info` object that you own, before you pass it into libtorrent for example. The `torrent_info` object you get from `torrent_file()->files()` is not owned by you, it's owned by libtorrent and immutable.

So, disregarding this, does `no_verify_files` still not work for magnet links?
