### ISSUE TITLE
Getting local i2p destination address

### ISSUE THREAD

**Issue by allhailjarjar** [arvidn/libtorrent#6604]
I want to run some tests for the i2p integration in libtorrent but I ran into an issue where I don't have the i2p destination that libtorrent creates with the i2p SAM bridge. I need this i2p destination so I can set it as the DHT bootstrap node when I start my other test instances.

I tried tracking down how to get the destination, but the codebase is not very straight forward (for someone coming to C++ from other languages).

It appears that [it is being kept track of](https://github.com/arvidn/libtorrent/blob/RC_2_0/include/libtorrent/i2p_stream.hpp#L603), but it also looks like it isn't exposed on the session object. Please correct me if I'm wrong.

Question 2:
I think this is the case, but want to double check. There's only 1 session created with SAM right? Not one for talking to peers, and one for DHT?

Thanks!

**Comment by arvidn** [comment]
it's been a really long time ago since I looked at this. I *believe* each peer connection has its own sam connection, but maybe all UDP traffic share one.

**Comment by arvidn** [comment]
UDP does not appear to be supported over i2p in libtorrent

**Comment by allhailjarjar** [comment]
>UDP does not appear to be supported over i2p in libtorrent

Does that mean DHT traffic is done over TCP on i2p, or is DHT not supported on i2p?

**Comment by arvidn** [comment]
I believe DHT is disabled when using i2p

**Comment by absolutep** [comment]
then how is this possible?

![156916220-bc918810-5974-454e-98cb-47cda07750ff](https://user-images.githubusercontent.com/97702149/159759384-ae368c8d-d61b-4fcb-9b93-e4e00dfad23d.png)
