### ISSUE TITLE
Build error with Visual Studio 2022

### ISSUE THREAD

**Issue by Natasm** [arvidn/libtorrent#6606]
* Branch RC_2_0
* Windows - Visual Studio 2022
* Boost 1.78

Translation of highlighted part of the figure: the syntax for filename directory name or volume label is incorrect.
![a](https://user-images.githubusercontent.com/31316300/147418650-56add4d5-d60d-4d5d-8dc6-c50a67df1e0b.png)

**Comment by arvidn** [comment]
google translate says:

"'The file name, directory name or volume label syntax is incorrect."

I see a few suspicious things:

1. the path suggests that you're using msvc-6.0 (which is over 20 years old). you may want to check your `user-config.jam` to make sure you've configured your compiler correctly
2. you use `fpic=on` when building on windows, which is a unix option. This command line option won't work on msvc.

Could you include the actual command line you invoke to build?

**Comment by Natasm** [comment]
The problem was only of msvc version. I updated to 14.3 version. Thanks @arvidn
