### ISSUE TITLE
use_read_cache resulting in erroneous failed hash/piece checks

### ISSUE THREAD

**Issue by michaelkrieger** [arvidn/libtorrent#6607]
libtorrent version (or branch): 1.2.15
platform/architecture: Alpine Linux 3.14.2
compiler and compiler version: g++ (10.3.1_git20210424-r2) gcc (10.3.1_git20210424-r2) 

Start with Deluge 2.0.5 with libbittorrent 1.2.15 with a paused torrent at 100% completion. I force a recheck and the torrent goes to 99.91% completion. Further rechecks of the same paused torrent return 99.96%, 99.87%, etc completion. Based on the piece_finished_alerts, the pieces it is missing differs each time the recheck is executed.

A filesystem sync (linux), restart of deluge, restart of the system doesn't change things and this erratic behaviour continues. As a general note, I find more than I'd like of wasted downloads (likely due to the same hash fails during download) as well.

Meanwhile, the file is unchanged on disk between completions. Using torrent-checker at the command line, I get the torrent as verified OK every time without any failed pieces. MD5Sums of the file on disk (which I've done 20 in sequence without any variation in hashes) shows the file unchanged. I have made the files immutable to ensure no changes to them and yet, there are variations in how the torrent client sees them.

To narrow down between Deluge and libbittorrent, I compiled qBitTorrent 4.3.9 with libtorrent 1.2.15. Add the same torrent file and map the same folder. Paused torrent. Force a recheck and the file goes from 100.0% to 97.1% to 98.6% to 97.2% complete between three rechecks. Tried turning off the "OS Cache" in qBittorrent but did not find a change in behaviour. Eventually let the torrent complete to 100% (though md5sum of the files shows the same as before). Paused it at that point. Did a force recheck and it's at 94.7%, losing 863MB of data... but the md5sum on the file is still exactly the same as the incomplete file previously.

### System Tests
**_28_ passes of all Passmark's memtest86 UEFI tests shows no sign of memory concern.** CPU stress tests don't show errors. The ext4 hard drives fsck without error when unmounted. dmesg shows nothing about I/O or anything relevant. If there was a system issue, I would expect that the torrent-checker would have shown an issue with the file or the md5 hash would have changed if any other product was raising issue. Moreover, hours later, any disk write cache at an OS level would have long expired, especially at a restart of Deluge.

### Settings which fix this
**If I turn off 'use_read_cache' in libTorrent 1.2.x's settings, I actually get to 100% each recheck.  So it's something that shows only with the read caching enabled...**  In fact, now that I've done that, I haven't had a single failure at all.

In qBittorrent, I've found if I turn on coalesce_reads ("Coalesce reads & writes"), I get to 100% as well, but with it off, still stop somewhere in the 90's.

### Summary
So a file, unchanged on disk as per md5sum and torrent-checker, produces entirely random piece completion results. Given that this is the same across more than one client using libtorrent, I'm setting my sights at libtorrent.  Given no system issues detected, I can't see how a simple read and hash would show something when 30+ hours of memtest86 doesn't show any challenge.  And it only causes issues with certain cache settings.

**Comment by arvidn** [comment]
to summarize, the problematic configuration is:

`use_read_cache` = `true`
`coalesce_reads` = `false`

right?

**Comment by arvidn** [comment]
do you happen to know which of these defines end up being set on your platform?
`TORRENT_USE_PREADV` or `TORRENT_USE_PREAD`.

I suspect you may not end up using `preadv()`, but instead `pread()`

**Comment by arvidn** [comment]
I've tried to trigger this kind of issue on MacOS by forcing both `pread()` and `preadv()` versions of the file I/O, with no success.

Can you check which version of musl libc you're using? I found these, could you be affected by these bugs?
https://git.musl-libc.org/cgit/musl/tree/WHATSNEW#n1776

**Comment by arvidn** [comment]
One thing to keep in mind; platforms that don't have either `pread()` or `preadv()` can only use a single disk I/O thread. Except windows, which has `pread`-like functions. Using 1 thread is the default in that case.

I don't think this is relevant to this issue though, since linux has had both of those for a very long time.

**Comment by michaelkrieger** [comment]
> to summarize, the problematic configuration is:
> `use_read_cache` = `true` `coalesce_reads` = `false`
> right?
Yes. I feel like I could have written a more concise report all of a sudden.

In deluge:
  Working: `use_read_cache = true` works with `coalesce_reads = true`
  Working: `use_read_cache = false`
  Bugged: `use_read_cache = true`, `coalesce_reads = false`

In qBittorrent, I don't see a way to disable the `use_read_cache` (which, I believe is on by default) but toggling `coalesce_reads` (to false) brings back or (to true) eliminates the error

> Can you check which version of musl libc you're using? I found these, could you be affected by these bugs? https://git.musl-libc.org/cgit/musl/tree/WHATSNEW#n1776

It appears to be musl 1.2.2-r3 with some patches ( https://git.alpinelinux.org/aports/tree/main/musl?h=3.14-stable ) from looking at the strings in the library as well as referencing the available packages.  Based on that, i should be long after that version.

> do you happen to know which of these defines end up being set on your platform? TORRENT_USE_PREADV or TORRENT_USE_PREAD.

Based on my test using config.hpp from the build, it appears to be using **preadv**
```
#include <cstdio>
#include "config.hpp"
int main() {
#if TORRENT_USE_PREADV 
printf("preadv");
#endif
#if  TORRENT_USE_PREAD
printf("pread");
#endif
return 0;
}
```



This is my reproduceable build environment, doing it from a base alpine image 3.14 to try and narrow things down
```
# apk --update add --no-cache boost-python3 boost-system libgcc libstdc++ openssl python3 && \
   apk --update add --no-cache --virtual build-dependencies boost-build boost-dev cmake coreutils g++ gcc git jq py3-setuptools python3-dev openssl-dev samurai
# mkdir /tmp/src && cd /tmp/src
# git clone --branch "v1.2.15" --depth 1 https://github.com/arvidn/libtorrent.git
# cd libtorrent
# git clean --force
# git submodule update --depth=1 --init --recursive
# PREFIX=/usr
# BUILD_CONFIG="debug cxxstd=14 crypto=openssl warnings=off address-model=32 -j$(nproc)"
# BOOST_ROOT="" b2 ${BUILD_CONFIG} link=static install --prefix=${PREFIX}
# cd bindings/python
# PYTHON_MAJOR_MINOR="$(python3 --version 2>&1 | sed 's/\(python \)\?\([0-9]\+\.[0-9]\+\)\(\.[0-9]\+\)\?/\2/i')"
# echo "using python : ${PYTHON_MAJOR_MINOR} : $(command -v python3) : /usr/include/python${PYTHON_MAJOR_MINOR} : /usr/lib/python${PYTHON_MAJOR_MINOR} ;" > ~/user-config.jam
# BOOST_ROOT="" b2 ${BUILD_CONFIG} install_module python-install-scope=system
```

**Comment by arvidn** [comment]
I would recommend against passing in `-j$(nproc)` to b2 btw. It will use all your CPUs by default.

**Comment by arvidn** [comment]
I notice you build with c++14 on alpine (with musl libc), this could be related to: https://github.com/arvidn/libtorrent/issues/6567

**Comment by arvidn** [comment]
trying to reproduce this in docker:

```
docker pull i386/alpine
docker run -i -t i386/alpine /bin/sh
```

I get this link error:

```
gcc.link client_test
/usr/lib/gcc/i586-alpine-linux-musl/10.3.1/../../../../i586-alpine-linux-musl/bin/ld: cannot find -lboost_system
/usr/lib/gcc/i586-alpine-linux-musl/10.3.1/../../../../i586-alpine-linux-musl/bin/ld: cannot find -lssl
/usr/lib/gcc/i586-alpine-linux-musl/10.3.1/../../../../i586-alpine-linux-musl/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status

    "g++" -L"/opt/homebrew/lib" -L"/usr/local/opt/boost/lib"  -Wl,-rpath-link -Wl,"/opt/homebrew/lib" -Wl,-rpath-link -Wl,"/usr/local/opt/boost/lib" -o "client_test" -Wl,--start-group "bin/gcc-10.3.1/debug-mode/address-model-32/crypto-openssl/cxxstd-14-iso/link-static/threading-multi/client_test.o" "bin/gcc-10.3.1/debug-mode/address-model-32/crypto-openssl/cxxstd-14-iso/link-static/threading-multi/print.o" "bin/gcc-10.3.1/debug-mode/address-model-32/crypto-openssl/cxxstd-14-iso/link-static/threading-multi/torrent_view.o" "bin/gcc-10.3.1/debug-mode/address-model-32/crypto-openssl/cxxstd-14-iso/link-static/threading-multi/session_view.o" "../bin/gcc-10.3.1/debug-mode/address-model-32/crypto-openssl/cxxstd-14-iso/link-static/threading-multi/libtorrent-rasterbar.a"  -Wl,-Bstatic -lboost_system -lssl -lcrypto -Wl,-Bdynamic -lrt -ldl -Wl,--end-group -pthread -std=c++14 -g -export-dynamic -rdynamic

...failed gcc.link client_test...
```

Do you need to do anything special to make the `openssl-dev` package available?

**Comment by michaelkrieger** [comment]
> Do you need to do anything special to make the `openssl-dev` package available?
```
docker run -i -t alpine:3.14.2 /bin/sh
apk --update add --no-cache boost-python3 boost-system libgcc libstdc++ openssl python3
apk --update add --no-cache --virtual build-dependencies boost-build boost-dev cmake coreutils g++ gcc git jq py3-setuptools python3-dev openssl-dev samurai
```

The rest is:
```
cd /tmp
git clone --branch "v1.2.15" --depth 1 https://github.com/arvidn/libtorrent.git
cd libtorrent
git clean --force
git submodule update --depth=1 --init --recursive
PREFIX=/usr
BUILD_CONFIG="debug cxxstd=14 crypto=openssl"
BOOST_ROOT="" b2 ${BUILD_CONFIG} link=static install --prefix=${PREFIX}
cd bindings/python
PYTHON_MAJOR_MINOR="$(python3 --version 2>&1 | sed 's/\(python \)\?\([0-9]\+\.[0-9]\+\)\(\.[0-9]\+\)\?/\2/i')"
echo "using python : ${PYTHON_MAJOR_MINOR} : $(command -v python3) : /usr/include/python${PYTHON_MAJOR_MINOR} : /usr/lib/python${PYTHON_MAJOR_MINOR} ;" > ~/user-config.jam
BOOST_ROOT="" b2 ${BUILD_CONFIG} install_module python-install-scope=system
```

**Comment by michaelkrieger** [comment]
Tried by removing the cxxstd=14 (though not overriding it with a different value) and didn't see any difference.
I've ultimately made a bundle (attached) with some Dockerfiles and shell scripts (as well as very simple python script).

I start by building libtorrent and deluge (it builds both as separate images). After that, simply starting the Alpine version vs starting the Debian version of Deluge and running a force recheck results in 100% completion vs hash fails.

That said, in my testcase (see the file in /testcase after running `./run-testcase.sh alpine`) I can't seem to reproduce it.  Still working on the right combination of options to reproduce it without running the deluge client to help narrow down the exact combination of options.  I'm hopeful I will find some insight into why both deluge and qbittorrent do it, but my simple test case doesn't.

Anyone looking at this might need to update some paths in the run-*.sh commands to point it to media and whatnot
[testbundle.zip](https://github.com/arvidn/libtorrent/files/7786643/testbundle.zip)

**Comment by arvidn** [comment]
my mistake was that I was linking statically

**Comment by michaelkrieger** [comment]
Possibly unrelated but with the Debian build  I’m now getting a ton of hash fails and surplus downloads (1.7-2x the download size and a torrent that isn’t making progress).  Will have to keep digging on this one.

**Comment by arvidn** [comment]
if most of your peers are still having the first problem, it's not surprising they send you corrupt data though.
