### ISSUE TITLE
UPnP - bad requests when gateway exposes both WANIPConnection and WANPPPConnection

### ISSUE THREAD

**Issue by PhillipAnd** [arvidn/libtorrent#6611]
On my router, the UPnP device list looks in part like this:
```
       <serviceList>
        <service>
         <serviceType>urn:schemas-upnp-org:service:WANIPConnection:1</serviceType>
         <serviceId>urn:upnp-org:serviceId:WANIPConn1</serviceId>
         <SCPDURL>/wipc_scpd.xml</SCPDURL>
         <controlURL>/wipc_cont</controlURL>
         <eventSubURL>/wipc_evnt</eventSubURL>
        </service>
        <service>
         <serviceType>urn:schemas-upnp-org:service:WANPPPConnection:1</serviceType>
         <serviceId>urn:upnp-org:serviceId:WANPPPConnection</serviceId>
         <SCPDURL>/wpppc_scpd.xml</SCPDURL>
         <controlURL>/wpppc_cont</controlURL>
         <eventSubURL>/wpppc_evnt</eventSubURL>
        </service>
       </serviceList>
```
Looking at the implementation for the `find_control_url` function, one can see that in this case `state.control_url` will be set to the URL endpoint for the WANIPConnection service, while `state.service_type` is set to the string`urn:schemas-upnp-org:service:WANPPPConnection:1`. Therefore we end up trying to POST a WANPPPConnection action to the WANIPConnection control URL, which results in an error code 401 for invalid action. From the code it appears that we want to default to the first service listed, so we just need to make that happen for both of these parameters.

This would also need to be backported to the RC_1_2 branch.

**Comment by arvidn** [comment]
thanks for the report! I believe this fixes it: https://github.com/arvidn/libtorrent/pull/6613

**Comment by arvidn** [comment]
I've landed that patch in `RC_1_2` and merged it into `RC_2_0`. @PhillipAnd will you have a chance to test it?
I feel pretty confident with the test and I'll close this ticket if you won't.

**Comment by PhillipAnd** [comment]
Unfortunately I will be unable to do any testing.

**Comment by an0n666** [comment]
You can test with this if you're on windows.
https://github.com/arvidn/libtorrent/issues/6603#issuecomment-1002537170
