### ISSUE TITLE
client_test Execution failed

### ISSUE THREAD

**Issue by shuai555** [arvidn/libtorrent#6622]
**Please provide the following information**

libtorrent version (or branch):
libtorrent-rasterbar-1.2.14
platform/architecture:
arm 32
compiler and compiler version:
gcc
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
o fail:        down:          (      )   bw queue:   0 |   0 conns:   0  unchoked:  0 /  8 queued-trackers: 00
waste:          up:          (      ) disk queue:   0 |   0 cache w:   0% r:   0% size: w:        r:        total:
uTP idle: 0 syn: 0 est: 0 fin: 0 wait: 0
[▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌]
[Dec 17 19:03:31] incoming dht get_peers: 0891629a73bd6bc1cbfce7495ab3bf40d7e1e2c2
[Dec 17 19:03:35] incoming dht get_peers: 1b5185bc26c62e59ebcc3646b2b74d734b79552b
[Dec 17 19:03:40] incoming dht get_peers: 5123043d9b00714baabc86eef5af83f2f82846ea
[Dec 17 19:03:45] incoming dht get_peers: 2fa8c85617be2f61ffc59c6daae51a5095cea767
[Dec 17 19:03:49] UPnP: broadcasting search for rootdevice
[Dec 17 19:03:50] incoming dht get_peers: 66cbaa4a11ab9c8dac162d3690c6d4cc67e713ac
[Dec 17 19:03:55] incoming dht get_peers: 59c303bf09ba50bd14bdeefedaa3f8d5d3ebb2ed
[Dec 17 19:04:00] incoming dht get_peers: 535856f23657985bddc9730f00f596d73d2d350a
[Dec 17 19:04:06] incoming dht get_peers: 4498548b62a1319ddd66c6306cf18c9ce692493c
[Dec 17 19:04:11] incoming dht get_peers: 417e7b6521e4c4d6133497e3664b721b5be5d765
[Dec 17 19:04:13] could not map port using UPnP: no router found
[Dec 17 19:04:13] could not map port using UPnP: no router found
[Dec 17 19:04:16] incoming dht get_peers: 3ea46d44113d19fa283023c8da154741940a1369
[Dec 17 19:04:21] incoming dht get_peers: 481476fbb977037812911acfd2ee5f1c1ce55834
[Dec 17 19:04:26] incoming dht get_peers: 5b1bdd54869ff4c466592083fc912c6cab1de888

The page will always be like this, why is this

**Comment by arvidn** [comment]
could you include what platform you're running on? and also which terminal you're using.

**Comment by arvidn** [comment]
I don't see any error messages. how is `client_test` failing?

**Comment by shuai555** [comment]
On the arm 32-bit bmc platform, the failure is because the above log keeps printing and no download

**Comment by shuai555** [comment]
linux平台
