### ISSUE TITLE
Use simple_client to report an error

### ISSUE THREAD

**Issue by shuai555** [arvidn/libtorrent#6624]
**Please provide the following information**

libtorrent version (or branch):
libtorrent-1.2.12
platform/architecture:
linux 
compiler and compiler version:
gcc arm32
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
 ./simple_client “[image](https://user-images.githubusercontent.com/94608188/147715451-3c680e3f-834e-42e6-97c2-2dc87253fa03.png)”
error： ERROR: No such file or directory [system:2]

**Comment by arvidn** [comment]
please describe what symptom you see, what you would expect to see instead and
