### ISSUE TITLE
dht_get_peers does not match C++ signature when building with debian bullseye

### ISSUE THREAD

**Issue by seik** [arvidn/libtorrent#6630]
libtorrent version (or branch): `RC_2_0`

platform/architecture: `Docker python:3.9-bullseye`

compiler and compiler version: `b2 1.74.0.3`

After building libtorrent using dht_get_peers results in:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Boost.Python.ArgumentError: Python argument types in
    session.dht_get_peers(session, str)
did not match C++ signature:
    dht_get_peers(libtorrent::session {lvalue}, libtorrent::digest32<160l>)
```

I prepared a Dockerfile to reproduce this issue:

```
FROM python:3.9-bullseye

RUN apt-get update && \
    apt-get install -y git libboost-tools-dev libboost-python-dev libboost-dev libboost-system-dev python3-setuptools libssl-dev

RUN dpkg -s libboost-dev | grep 'Version'

RUN git clone -b RC_2_0 --recurse-submodules https://github.com/arvidn/libtorrent.git \
    && cd libtorrent/bindings/python \
    && python setup.py build install

RUN python -c "import libtorrent as lt; \
    session = lt.session(); \
    info_hash = lt.sha1_hash(b"a" * 20); \
    session.dht_get_peers(info_hash);" 
```

To reproduce: Download that code into a Dockerfile and run `docker build .` .

All the dependencies and build steps are copied from the github actions.

**Comment by arvidn** [comment]
for me, that test program fails with:
```
NameError: name 'info_hash' is not defined
```

When I fix it to set info_hash to:
```
 info_hash = lt.sha1_hash(b"a" * 20)
```

it works fine. are you actually running the latest `RC_2_0` commit? which commit hash are you building?

**Comment by arvidn** [comment]
does this test pass for you? https://github.com/arvidn/libtorrent/pull/6635

**Comment by seik** [comment]
@arvidn Yes that works. It was a problem on my side.
