### ISSUE TITLE
Does not work under Android 11: bind: Permission denied

### ISSUE THREAD

**Issue by alervd** [arvidn/libtorrent#6632]
**Please provide the following information**

libtorrent version (or branch):
1.2.15.0 rev. 0facda852

platform/architecture:
Android 11

compiler and compiler version:
clang, NDK 21.3.6528147

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
Android must be 11 (did not test 12 version). targetSdkVersion in the Android.manifest must also be set to 30.

1. Add a torrent in the paused state.
2. session_error_alert will arrive while LT will be adding the torrent. It will contain the following error message: "session error: (13 Permission denied) bind: Permission denied".
3. Resume the torrent. torrent_checked_alert will arrive and nothing more will happen. Torrent will not be downloading anything. If I try to pause it, nothing happens: torrent_paused_alert is never arrived.

Probably, this can be related to this issue: https://github.com/frostwire/frostwire-jlibtorrent/issues/254#issuecomment-854815190.

For now, it's a critical bug: LT can't be used under Android 11 in case targetSDK is set to Android 11. 

Any workaround?

**Comment by arvidn** [comment]
It sounds like binding the listen socket fails. To get more diagnostics, you could enable debug logging.

**Comment by alervd** [comment]
I'll have to recompile LT then. Do you really need this debugging info from me?

**Comment by arvidn** [comment]
Maybe someone else knows what's failing. @aldenml perhaps?

**Comment by gubatron** [comment]
This is because Netlink sockets have been disabled after Android 11, you need to use IFADDR sockets instead.
We currently apply this patch
https://github.com/frostwire/frostwire-jlibtorrent/blob/master/swig/libtorrent_patches/ifaddr.1.2.14.patch

But if I remember correctly, I believe @aldenml submitted something similar so that these flags work properly during compilation time. I tried many different ways to define these flags at compile time and failed, ended up creating that patch which I apply right before compiling for android targets for the jlibtorrent library.

**Comment by gubatron** [comment]
This was @aldenml's patch
https://github.com/arvidn/libtorrent/commit/36fba13f4db5493541e2c5de75463cd9d0dffc70

But I suppose this is for the 2.0 branch only. I remember trying something similar too checking the android API level but this wasn't enough for the 1.2 branch.

**Comment by aldenml** [comment]
One of the changes for the Android fix is after the commit `0facda8` in `RC_1_2`, and still, there is another one missing (the one mentioned by @gubatron). Right now, in order to use `RC_1_2`, you will need to recompile with some custom changes. The alternative is to move to `RC_2_0` (let us know if this is a possibility).

**Comment by alervd** [comment]
Is 2.0 stable enough? Is the fix planned for 1.2? When (approximately)?

**Comment by alervd** [comment]
Also, the bug is not only in bind failure, but also in improper work of LT APIs in this situation (e.g. torrent can't be paused).

**Comment by aldenml** [comment]
the branch `RC_2_0` is the current stable branch. As for plans to fix it in 1.2, that I don't know :(

**Comment by alervd** [comment]
So, can you please say what exact steps are required to get 1.2 working under Android 11? 
1. Apply the patch mentioned by @gubatron (https://github.com/frostwire/frostwire-jlibtorrent/blob/master/swig/libtorrent_patches/ifaddr.1.2.14.patch). 
2. Anything else?

**Comment by gubatron** [comment]
that should be it

**Comment by alervd** [comment]
OK, thanks, now it's working.

**Comment by alervd** [comment]
I've decided to stick with 1.2 because 2.0 seems to have some critical non-fixed issues... E.g. this one: https://github.com/arvidn/libtorrent/issues/6522. Arvid has made some fixes, but some guys reported that it's not fixed yet (https://github.com/qbittorrent/qBittorrent/issues/15961).

**Comment by alervd** [comment]
The patch https://github.com/arvidn/libtorrent/commit/36fba13f4db5493541e2c5de75463cd9d0dffc70 is not very good because it's for Android 7.0+ only. It will not fix things for ones wanting to support previous versions of Android. Yes, I know that this ifaddrs.h is correctly implemented for Android-24+ level. But it's possible to use custom headers. I use this one: https://android.googlesource.com/platform/libcore/+/refs/heads/gingerbread-release/luni/src/main/native/ifaddrs-android.h

**Comment by BD9Max** [comment]
I can't get Libretorrent (latest from August 2025) to work in Android 11. When I add a torrent it doesn't download and says access denied (Download folder).

Please help

**Comment by arvidn** [comment]
surely it must say more than just "access denied". Is it that the process doesn't have access to the download folder perhaps?

**Comment by BD9Max** [comment]
> surely it must say more than just "access denied". Is it that the process doesn't have access to the download folder perhaps?

Yes!

**Comment by BD9Max** [comment]
I used F-Droid version like always. It used to work. Ver 3.6 at least. I think 4.0 beta too, but since spring of 2025 I haven't been able to use it since no storage access. F-Droid version in January/February 2025 when I installed Libretorrent it worked.

Now using torrent app called Flud. It's a fork I think Libretorrent I want to use.

**Comment by BD9Max** [comment]
Should I use the posix setting?

I hope you overcome major issues.

**Comment by BD9Max** [comment]
And btw, F-Droid repo is slow to update, could you also publish into Izzyondroid F-Droid repo? It updates within few hours/days. @IzzySoft

**Comment by gubatron** [comment]
Android storage works differently depending on the versions, you're going to have to implement different versions of Media Storage, in some versions you have to interact with its MediStore API and insert the bytes of the files (in a buffered fashion) for files to appear in your media collections.

It's an absolute nightmare, they keep changing the way you access depending on who's the product manager at Google

This might help, this is how we store/media scan files depending on the android release

https://github.com/frostwire/frostwire/blob/master/android/src/com/frostwire/android/gui/Librarian.java

**Comment by BD9Max** [comment]
Android 11 uses scoped storage I know they keep changing. I hope that it's fixed soon. Libretorrent 3.6 worked so :)

**Comment by IzzySoft** [comment]
@BD9Max we can't without an APK (attached to its corresponding release); we always ship the APKs built and signed by the resp. developers. Also see the [IzzyOnDroid App Inclusion Policy](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Inclusion-Policy) for further details-

**Comment by BD9Max** [comment]
I installed 3.5.2 and torrents do work. I transferred my torrents from Flud to Libretorrent it was easy.

But I miss new features in 3.6 and 4.0.

I think I might take a backup of the app (I'm rooted) and install 4.0.1 to see if it works.

**Comment by BD9Max** [comment]
Not working. Dunno if 3.6 but now I'm on 3.5.2

**Comment by BD9Max** [comment]
I reckon the problem started (again) with ver 3.6.0. 

In winter when I was torrenting it must be 3.5.2 that I used as 3.6.0 was released after and in the spring when I was torrenting again to my dismay Libretorrent wasn't functioning.

Now looking forward to get to use updates 3.6.0 and 4.0 in my client.

**Comment by BD9Max** [comment]
Hmm I just updated 352 to 360 and I can add torrents and they do download.

But there's a bug somewhere. Does clean install matter?

I did got the error notice with 3.6.0 previously. But yesterday when I tried 4.0.1 I didn't get error notice the torrent wasn't even added to client.

Previously I was able to add torrents though wasn't able to download/save.

**Comment by BD9Max** [comment]
Aand I'm back in 352. Wasn't working, wasn't working, wasn't working, starting from 360.
