### ISSUE TITLE
Unable to compile Boost/Ninja/Cmake; 'Handler buffer not large enough'

### ISSUE THREAD

**Issue by DyonR** [arvidn/libtorrent#6634]
**Please provide the following information**

**libtorrent version (or branch)**:  
Latest master branch commit (RC_2_0) (https://github.com/arvidn/libtorrent/commit/d0f7a09adb73157f4c35e870de65935fd331a3a4 as of writing)

**platform/architecture**:  
debian:bullseye-slim Docker
Docker version 20.10.5, build 55c4c88 on Unraid 6.9.2 (Slackware based)
Kernel: 5.10.28-Unraid #1 SMP Wed Apr 7 08:23:18 PDT 2021  

**compiler and compiler version**:  
Boost v1.78.0  
Ninja v1.10.2  
Cmake v3.22.1  
  
**cmake commands**:  
`cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_CXX_STANDARD=17`  
`cmake --build build --parallel $(nproc)`

**please describe what symptom you see, what you would expect to see instead and how to reproduce it**:  
When running `cmake --build build --parallel $(nproc)`, the compilation crashes, because of this I can not compile libtorrent.  
In the past running this exact same Dockerfile worked flawlessly without problems, but for 2-3 weeks it hasn't been working.

Dockerfile that I use: https://pastebin.com/BTnvxkne  
Output of `cmake --build build --parallel $(nproc)`: https://pastebin.com/hjrw8XME  
Output of `cmake --build build --parallel $(nproc) --verbose`: https://pastebin.com/8tZTrBA8  
  
If I need to provide any additional information, please let me know!
Naturally, I  did already check issues related to 'handle buffer' on this GitHub, but all those issues were marked as solved already.

**Comment by userdocs** [comment]
https://github.com/arvidn/libtorrent/issues/6589#issuecomment-991971120

**Comment by Chocobo1** [comment]
Also encountered this when building with boost 1.78 on linux x64, here is the log: https://flathub.org/builds/#/builders/12/builds/8807/steps/6/logs/stdio

**Comment by arvidn** [comment]
can you confirm you have this patch in your history? 71d608fceca7e61c9d124f9ea83f71b06eda3b17

also, make sure there aren't any old libtorrent headers that might get mixed into the build. the error messages suggest that the above commit hasn't been applied to the `include/libtorrent/aux_/allocating_handler.hpp` file. Even though, that patch is an ancestor of d0f7a09.

**Comment by DyonR** [comment]
I can confirm that https://github.com/arvidn/libtorrent/commit/71d608fceca7e61c9d124f9ea83f71b06eda3b17 matches the file that I use to compile libtorrent; 
<img width="923" alt="image" src="https://user-images.githubusercontent.com/16341409/148628660-2aadd17b-101b-4ab7-9a5f-aa41c5ec4742.png">  
  
It's a clean Debian Docker image that I compile it on with a clean `git clone --recursive https://github.com/arvidn/libtorrent.git`.    

The git I pulled is not out of date either, matches https://github.com/arvidn/libtorrent/commit/d0f7a09adb73157f4c35e870de65935fd331a3a4
```   
root@c52cf354b5b0:/opt/libtorrent# git rev-parse HEAD
d0f7a09adb73157f4c35e870de65935fd331a3a4
```

**Comment by userdocs** [comment]
I cannot replicate this issue in actions using debian

https://github.com/userdocs/qbittorrent-nox-static/actions/runs/1668691590

Or using the same docker image `debian:bullseye-slim`.

I only have this if I am using a release tag with no patch `2.0.5` and not `RC_2_0`

It appears to work fine in `RC_2_0` so unless there is something being done that is not clear I cannot see what the issue is.

**Comment by arvidn** [comment]
I can reproduce this on ubuntu with 32 bit builds without openssl. This fixes it for me: https://github.com/arvidn/libtorrent/pull/6642

**Comment by arvidn** [comment]
hm, DyonR is building release though.

**Comment by DyonR** [comment]
> hm, DyonR is building release though.

I am able to compile without problems using the fix you posted... 🤔

**Comment by arvidn** [comment]
yeah, I updated it to not only affect debug builds
