### ISSUE TITLE
Incorrect Announce Timer 

### ISSUE THREAD

**Issue by cyrillicw** [arvidn/libtorrent#6638]
When ```on_dht_announce``` is executed, it first of all tries to announce those torrents that have not been announced yet in the next way: only one torrent is announced per execution, but if there are more torrents to be announced, the next execution will take place soon (in 4 seconds):
```
		if (!m_dht_torrents.empty())
		{
			// we have prioritized torrents that need
			// an initial DHT announce. Don't wait too long
			// until we announce those.
			delay = std::min(4, delay);
		}
```
But if ```on_tick``` is executed before the timer expires, it can call ```update_dht_announce_interval``` that will change expire time of the timer. The ```update_dht_announce_interval``` does not make check whether there are torrents that have not been announced yet, so after its execution the timer that had to be executed in 4 second will be executed in several minutes.

**Comment by arvidn** [comment]
how does this look? https://github.com/arvidn/libtorrent/pull/6639

**Comment by cyrillicw** [comment]
This looks good. But maybe (I am not sure) it can be useful to change time of the timer expiration only in the case when the new delay is less then the one that is now left before the timer expiration?

**Comment by arvidn** [comment]
I don't think there's any important difference either way

**Comment by cyrillicw** [comment]
Okey :)
