### ISSUE TITLE
Build fails with boost 1.66

### ISSUE THREAD

**Issue by lgbaldoni** [arvidn/libtorrent#6640]
**Please provide the following information**

libtorrent version (or branch): 2.0.5

platform/architecture: openSUSE Leap 15.4 x86_64

compiler and compiler version:
gcc 7.5.0

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Several errors during the build, see attached logs. Problem not showing with boost 1.78.
[libtorrent205_boost166.tar.gz](https://github.com/arvidn/libtorrent/files/7833221/libtorrent205_boost166.tar.gz)

**Comment by arvidn** [comment]
libtorrent 2.0.x requires a newer version of boost. at least 1.68 or 1.69 iirc

**Comment by xavier2k6** [comment]
> libtorrent 2.0.x requires a newer version of boost. at least 1.68 or 1.69 iirc

Docs need to be updated then:

>You'll need at least version **1.66** of the boost library in order to build libtorrent.

Reference:
[Boost version **1.66** required](https://github.com/arvidn/libtorrent/blob/RC_2_0/docs/building.rst#:~:text=You'll%20need%20at%20least%20version%201.66%20of%20the%20boost%20library%20in%20order%20to%20build%20libtorrent.)

You could possibly change it to 1.71.0 (this is default/oob on ubuntu 20.04 [focal])

**Comment by lgbaldoni** [comment]
> libtorrent 2.0.x requires a newer version of boost. at least 1.68 or 1.69 iirc

I see. Unless a workaround can be found, it won't be included in openSUSE Leap 15.4. :frowning:
Do you think 1.2.x be maintained until next year?

**Comment by arvidn** [comment]
it turns out it works with boost -1.67. I updated this PR with the documentation updates: https://github.com/arvidn/libtorrent/pull/6643

**Comment by lgbaldoni** [comment]
I guess there's nothing else to add. Closing the issue.
