### ISSUE TITLE
Ed25519 license issue

### ISSUE THREAD

**Issue by orlp** [arvidn/libtorrent#6645]
In https://github.com/arvidn/libtorrent/blob/be254588b6d8b640cd766ca12464b5997ceb57ba/src/ed25519/LICENSE it is claimed I put my contributions for the ed25519 library in the public domain. This isn't (completely) true, my ed25519 library is available only under the zlib license, and has been since March 2015. Looking at various of my commits after March 2015, `libtorrent`'s ed25519 library is clearly derived from a version after that date.

This is no big issue, all I ask that my license file is included in the source distribution: https://github.com/orlp/ed25519/blob/master/license.txt. And as stated in the license, a small acknowledgement in the documentation is appreciated but not required.

**Comment by userdocs** [comment]
Not to contest you but to seek better understanding of a particular element of one aspect of this request, I have a question. 

_To be clear I do not speak on behalf of @arvidn or represent this project in what I say._

If you contribute to a public domain licenced project, as this appears to be, do you not waive your right to such a license for those contributions?

https://en.wikipedia.org/wiki/Public-domain-equivalent_license

> Public-domain-equivalent license are licenses that grant public-domain-like rights and/or act as waivers. They are used to make copyrighted works usable by anyone without conditions, while avoiding the complexities of attribution or license compatibility that occur with other licenses.

The way the commit reads to me is that is references this website and project which clearly states it is in the pubic domain

http://ed25519.cr.yp.to/software.html

```
Copyrights
The Ed25519 software is in the public domain.
```

And then references contributions to that project as also being in the public domain, which appears technically correct if that project is being used.

I suppose if your forked version is being used the license is applicable but if the original project is being used your contributions waived their attribution and are in the public domain. (clarification required and not a hard statement of fact)

Can you apply a license over the top of a public domain l project, even to ask for contributions?

It has peaked my curiosity as I've not encountered a public domain licensing issue before.

@arvidn would need to clarify which project is actually implemented

**Comment by orlp** [comment]
> If you contribute to a public domain licenced project, as this appears to be, do you not waive your right to such a license for those contributions?

I never contributed to djb's ed25519 SUPERCOP implementation, [my repository](https://github.com/orlp/ed25519) is a fork wrapping it.

> I suppose if your forked version is being used

My forked version is being used, albeit with modifications. You could say the version in libtorrent is a fork of my fork. For example neither the file nor the functionality of https://github.com/arvidn/libtorrent/blob/be254588b6d8b640cd766ca12464b5997ceb57ba/src/ed25519/add_scalar.cpp exists in the original project. But the contributions aren't just limited to that file.

> Can you apply a license over the top of a public domain

Yes. This (obviously) doesn't prevent anyone from taking the original project and keep using it as the public domain as they please. But any contributions over the original project can be licensed.

Either way, complying is as simple as dropping the license text in <https://github.com/arvidn/libtorrent/blob/RC_2_0/LICENSE>, there's no further requirements.

**Comment by userdocs** [comment]
Ok, thanks for the info.

**Comment by arvidn** [comment]
does this look good? https://github.com/arvidn/libtorrent/pull/6663

I noticed the `readme` I have still says "public domain". Perhaps I cherry picked certain files without updating it...

**Comment by orlp** [comment]
> does this look good? #6663
> 
> I noticed the `readme` I have still says "public domain". Perhaps I cherry picked certain files without updating it...

That does look good, only I would also update `libtorrent/src/ed25519/LICENSE` to either refer to `libtorrent/LICENSE` or duplicate the zlib license there (it still only mentions my contributions as being public domain). Or alternatively delete that file altogether and merge the remaining info into `libtorrent/LICENSE`.

**Comment by arvidn** [comment]
> Looking at various of my commits after March 2015, libtorrent's ed25519 library is clearly derived from a version after that date.

Digging into this a bit, I don't think it's all that obvious. The bulk of the code is based on the 2013 version. I found this [libtorrent PR](https://github.com/arvidn/libtorrent/pull/1037) which landed in 2016, which includes code from [this commit](https://github.com/orlp/ed25519/commit/09ec167693edff9478b53d772487e94569cb58d0) (reported [here](https://github.com/orlp/ed25519/issues/3)) which (as you say) was after the license change commit, [here](https://github.com/orlp/ed25519/commit/e65e7f944d03dda8564f9f901e2a9999bbdf71c8).

So, it was an easy thing to miss.

**Comment by arvidn** [comment]
I've updated https://github.com/arvidn/libtorrent/pull/6663

**Comment by orlp** [comment]
> > Looking at various of my commits after March 2015, libtorrent's ed25519 library is clearly derived from a version after that date.
> 
> Digging into this a bit, I don't think it's all that obvious. The bulk of the code is based on the 2013 version. I found this [libtorrent PR](https://github.com/arvidn/libtorrent/pull/1037) which landed in 2016, which includes code from [this commit](https://github.com/orlp/ed25519/commit/09ec167693edff9478b53d772487e94569cb58d0) (reported [here](https://github.com/orlp/ed25519/issues/3)) which (as you say) was after the license change commit, [here](https://github.com/orlp/ed25519/commit/e65e7f944d03dda8564f9f901e2a9999bbdf71c8).
> 
> So, it was an easy thing to miss.

Ah I see. The history was more complicated than I thought. Either way, thanks for fixing it, all is good now.
