### ISSUE TITLE
Build fail on raspberry pi 3 64 bits

### ISSUE THREAD

**Issue by colombojrj** [arvidn/libtorrent#6646]
Can not build libtorrent-rasterbar on raspberry pi 3 64 bits. I got the following error:

[10/188] /usr/bin/aarch64-unknown-linux-gnu-g++ -DBOOST_ALL_NO_LIB -DBOOST_ASIO_ENABLE_CANCELIO -DBOOST_ASIO_HAS_STD_CHRONO -DBOOST_ASIO_NO_DEPRECATED -DBOOST_EXCEPTION_DISABLE -DOPENSSL_NO_SSL2 -DTORRENT_BUILDING_LIBRARY -DTORRENT_BUILDING_SHARED -DTORRENT_DISABLE_LOGGING -DTORRENT_SSL_PEERS -DTORRENT_USE_LIBCRYPTO -DTORRENT_USE_OPENSSL -D_FILE_OFFSET_BITS=64 -Dtorrent_rasterbar_EXPORTS -I/var/tmp/portage/net-libs/libtorrent-rasterbar-2.0.5/work/libtorrent-rasterbar-2.0.5/include -I/var/tmp/portage/net-libs/libtorrent-rasterbar-2.0.5/work/libtorrent-rasterbar-2.0.5/deps/try_signal  -march=armv8-a+crc -mtune=cortex-a53 -ftree-vectorize -O2 -pipe -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wc++11-compat -Wextra -Wno-format-zero-length -Wparentheses -Wpedantic -Wvla -Wno-c++11-compat -Wno-noexcept-type -ftemplate-depth=512 -fexceptions -std=gnu++17 -MD -MT CMakeFiles/torrent-rasterbar.dir/src/crc32c.cpp.o -MF CMakeFiles/torrent-rasterbar.dir/src/crc32c.cpp.o.d -o CMakeFiles/torrent-rasterbar.dir/src/crc32c.cpp.o -c /var/tmp/portage/net-libs/libtorrent-rasterbar-2.0.5/work/libtorrent-rasterbar-2.0.5/src/crc32c.cpp

FAILED: CMakeFiles/torrent-rasterbar.dir/src/crc32c.cpp.o 
/usr/bin/aarch64-unknown-linux-gnu-g++ -DBOOST_ALL_NO_LIB -DBOOST_ASIO_ENABLE_CANCELIO -DBOOST_ASIO_HAS_STD_CHRONO -DBOOST_ASIO_NO_DEPRECATED -DBOOST_EXCEPTION_DISABLE -DOPENSSL_NO_SSL2 -DTORRENT_BUILDING_LIBRARY -DTORRENT_BUILDING_SHARED -DTORRENT_DISABLE_LOGGING -DTORRENT_SSL_PEERS -DTORRENT_USE_LIBCRYPTO -DTORRENT_USE_OPENSSL -D_FILE_OFFSET_BITS=64 -Dtorrent_rasterbar_EXPORTS -I/var/tmp/portage/net-libs/libtorrent-rasterbar-2.0.5/work/libtorrent-rasterbar-2.0.5/include -I/var/tmp/portage/net-libs/libtorrent-rasterbar-2.0.5/work/libtorrent-rasterbar-2.0.5/deps/try_signal  -march=armv8-a+crc -mtune=cortex-a53 -ftree-vectorize -O2 -pipe -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wc++11-compat -Wextra -Wno-format-zero-length -Wparentheses -Wpedantic -Wvla -Wno-c++11-compat -Wno-noexcept-type -ftemplate-depth=512 -fexceptions -std=gnu++17 -MD -MT CMakeFiles/torrent-rasterbar.dir/src/crc32c.cpp.o -MF CMakeFiles/torrent-rasterbar.dir/src/crc32c.cpp.o.d -o CMakeFiles/torrent-rasterbar.dir/src/crc32c.cpp.o -c /var/tmp/portage/net-libs/libtorrent-rasterbar-2.0.5/work/libtorrent-rasterbar-2.0.5/src/crc32c.cpp
/var/tmp/portage/net-libs/libtorrent-rasterbar-2.0.5/work/libtorrent-rasterbar-2.0.5/src/crc32c.cpp:54:16: error: conflicting declaration of ‘uint32_t libtorrent::crc32c_32(uint32_t)’ with ‘C’ linkage
   54 |  std::uint32_t crc32c_32(std::uint32_t v)
      |                ^~~~~~~~~
In file included from /var/tmp/portage/net-libs/libtorrent-rasterbar-2.0.5/work/libtorrent-rasterbar-2.0.5/src/crc32c.cpp:36:
/var/tmp/portage/net-libs/libtorrent-rasterbar-2.0.5/work/libtorrent-rasterbar-2.0.5/include/libtorrent/crc32c.hpp:42:37: note: previous declaration with ‘C++’ linkage
   42 |  TORRENT_EXTRA_EXPORT std::uint32_t crc32c_32(std::uint32_t);
      |                                     ^~~~~~~~~
/var/tmp/portage/net-libs/libtorrent-rasterbar-2.0.5/work/libtorrent-rasterbar-2.0.5/src/crc32c.cpp:87:16: error: conflicting declaration of ‘uint32_t libtorrent::crc32c(const uint64_t*, int)’ with ‘C’ linkage
   87 |  std::uint32_t crc32c(std::uint64_t const* buf, int num_words)
      |                ^~~~~~
In file included from /var/tmp/portage/net-libs/libtorrent-rasterbar-2.0.5/work/libtorrent-rasterbar-2.0.5/src/crc32c.cpp:36:
/var/tmp/portage/net-libs/libtorrent-rasterbar-2.0.5/work/libtorrent-rasterbar-2.0.5/include/libtorrent/crc32c.hpp:43:37: note: previous declaration with ‘C++’ linkage
   43 |  TORRENT_EXTRA_EXPORT std::uint32_t crc32c(std::uint64_t const*, int);
      |                                     ^~~~~~
/var/tmp/portage/net-libs/libtorrent-rasterbar-2.0.5/work/libtorrent-rasterbar-2.0.5/src/crc32c.cpp:151:1: error: expected ‘}’ at end of input
  151 | }
      | ^
In file included from /var/tmp/portage/net-libs/libtorrent-rasterbar-2.0.5/work/libtorrent-rasterbar-2.0.5/src/crc32c.cpp:49:
/usr/lib/gcc/aarch64-unknown-linux-gnu/9.4.0/include/arm_acle.h:33:12: note: to match this ‘{’
   33 | extern "C" {
      |            ^

**Comment by userdocs** [comment]
Can i ask where you are getting the source code for libtorrent and how (git clone?)

**Comment by colombojrj** [comment]
I am a gentoo user. The source link is from emerge (please see line 12 of https://gitweb.gentoo.org/repo/gentoo.git/tree/net-libs/libtorrent-rasterbar/libtorrent-rasterbar-2.0.5.ebuild ).

**Comment by arvidn** [comment]
it's quite a mystery how the first declaration gets interpreted as to have C linkage. Everything should have C++ linkage.

There are very few uses of `extern "C"` in libtorrent, and none in the vicinity of this declaration. All the patches applied looks good as well.

**Comment by colombojrj** [comment]
Hi,
I have successfully built it. I have downloaded the github zip file and used cmake, with make and make install. It worked perfectly. I believe this is a Gentoo related issue.
