### ISSUE TITLE
Incorrect (at least undocumented) assumptions in create_torrent constructor

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#6649]
https://github.com/arvidn/libtorrent/blob/070bde592a2f1388200bdf2a43628e31bf324574/include/libtorrent/create_torrent.hpp#L195

This is not obvious and I have not found any declaration that passed `torrent_info` instance should exist for the lifetime of `create_torrent` instance.

**Comment by arvidn** [comment]
I agree, it is not obvious. Are you sure it's the case?
what symptom do you see?

**Comment by arvidn** [comment]
ah, the `file_storage` is referenced by `create_torrent`

**Comment by arvidn** [comment]
do you have a use case where it is complicated to keep the `torrent_info` object alive for the duration of `create_torrent`?
i.e. do you think this should be more than a documentation fix?

**Comment by glassez** [comment]
> do you have a use case where it is complicated to keep the `torrent_info` object alive for the duration of `create_torrent`?

IMO, it's not a problem if you aware of it.
But there is another problem (even more serious). You allow (at least potentially) to change object passed as const (by produce non-const reference to its member) which is clearly a bug.

**Comment by arvidn** [comment]
yeah, I noticed that. I addressed it here: https://github.com/arvidn/libtorrent/pull/6659

**Comment by arvidn** [comment]
documentation updated here: https://github.com/arvidn/libtorrent/pull/6661
