### ISSUE TITLE
ignore_resume_timestamps deprecated

### ISSUE THREAD

**Issue by vktr** [arvidn/libtorrent#6666]
Hello!

As seen here,

https://github.com/arvidn/libtorrent/blob/8e6e3c2d010f291ed526f2f3b964a9c04c699bda/include/libtorrent/settings_pack.hpp#L647

The setting `ignore_resume_timestamps` is deprecated. However, here,

https://github.com/arvidn/libtorrent/blob/8e6e3c2d010f291ed526f2f3b964a9c04c699bda/src/settings_pack.cpp#L182

It does not use `DEPRECATED_SET`, which means that `name_for_setting` will return a non-empty string when passing the integer value for `deprecated_ignore_resume_timestamps`.

I'm currently iterating each setting sort-of like this,

```
for (int it = lt::settings_pack::type_bases::int_type_base;
     it < lt::settings_pack::int_types::max_int_setting_internal;
     it ++)
{
    std::string settingName = lt::name_for_setting(it);
    if (settingName.empty()) { continue; }

    // impl. defined
}
```

The idea is to walk each (non)-deprecated setting and act on it.

Is there a better way to iterate the settings or would you accept a PR for changing `SET` to `DEPRECATED_SET`?

**Comment by vktr** [comment]
The same is true for these as well,

https://github.com/arvidn/libtorrent/blob/8e6e3c2d010f291ed526f2f3b964a9c04c699bda/include/libtorrent/settings_pack.hpp#L1525-L1527

I might misunderstand how it's supposed to work, though 😄

**Comment by vktr** [comment]
I'm running the `v2.0.5` tag

**Comment by arvidn** [comment]
thanks for the report! https://github.com/arvidn/libtorrent/pull/6668
