### ISSUE TITLE
lt::create_torrent crash when add a bad torrent

### ISSUE THREAD

**Issue by stdjs** [arvidn/libtorrent#6673]
**Please provide the following information**

libtorrent version (or branch): 2.04

platform/architecture: opensuse x86-64

compiler and compiler version: gcc11

I created a bad torrent, after add i use lt::create_torrent to dump this torrent to disk.

```
lt::add_torrent_params params;
params.ti = std::make_shared<lt::torrent_info>(path,error);
....
...

on lt::add_torrent_alert
{
    auto torrent = handle_.torrent_file();
    if(torrent && torrent->is_valid() && status.has_metadata){
         lt::create_torrent creator(*torrent); //crash
    }

}
```

this torrent is created by lt::create_torrent, data is clone from [deluge](https://github.com/deluge-torrent/deluge) 

in most case lt::create_torrent is OK, but some directories contains some special files (like deluge) , lt::create_torrent will generate a bad torrent.

in the begining i believe is something wrong about my code, then i tried use other libtorrent clients to create the torrent (like qbittorrent) ,but i got same result, after a while i tried use transmission 3.0 to create the deluge torrent, every thing is OK,
so i guess this issues is 99% caused by lt::create_torrent or just my usage is incorrect???

How can i fix this.

sample torrent file:
[deluge.zip](https://github.com/arvidn/libtorrent/files/7881667/deluge.zip)

**Comment by arvidn** [comment]
`create_torrent` is used to turn *files* on disk into a `.torrent` file. I'm a bit confused by you talking about "adding" a bad "torrent" to `create_torrent`. The only thing you add to `create_torrent` are *files*, not torrents.

Do you mean you are creating a .torrent file that itself contain other .torrent files? or by "torrent", do you just mean a directory of files?

**Comment by arvidn** [comment]
the generation of a bad torrent is most likely because the torrent you're downloading is a v2 or a hybrid (v1 and v2) torrent.

To generate a valid v2 torrent, you need the piece hashes, but they aren't part of the metadata. So, when you get the `metadata_received_alert`, you don't have enough information to generate a v2 torrent (or the v2 portion of a hybrid torrent).

I believe `create_torrent` will still produce a .torrent file, it just won't have the (mandatory) "piece layers" field in it.

**Comment by stdjs** [comment]
I just made a new example proved it crashes only by special files (like deluge) 

```
std::string torrent_path = "/home/devel01/Downloads/tmp.torrent";

    lt::file_storage storage;
    //lt::add_files(storage,"/home/devel01/Downloads/xcb/"); this is OK
     //lt::add_files(storage,"/home/devel01/Downloads/zlib/"); this is OK
    //........other 10 directories also OK
    lt::add_files(storage,"/home/devel01/Downloads/deluge/"); //this is not OK
    lt::create_torrent torrent(storage);
    lt::set_piece_hashes(torrent,"/home/devel01/Downloads/");

    {
        std::ofstream out(torrent_path,std::ios_base::binary);
        lt::bencode(std::ostream_iterator<char>(out),torrent.generate());
    }

    lt::error_code error;
    lt::add_torrent_params params2;
    params2.flags = lt::torrent_flags::apply_ip_filter |lt::torrent_flags::need_save_resume |lt::torrent_flags::update_subscribe | lt::torrent_flags::duplicate_is_error;
    params2.ti = std::make_shared<lt::torrent_info>(torrent_path,error);
    params2.info_hashes = params2.ti->info_hashes();

    auto handle = context_->add_torrent(std::move(params2));
  
    lt::create_torrent creator2(*handle.torrent_file()); //SIGSEGV (Segmentation fault)
```

as you can see i tried few different of directories,they are all OK, successfully create torrent and dump torrent, but only failed when the directory is deluge, torrent file is not very big, only 438.5KB, i insert a breakpoint , the handle.torrent_file() variable (xxx total_size,offset ) contains very big size.

sory i can't provide debug info,because when i link with debug version of libtorrent, i always got 

![image](https://user-images.githubusercontent.com/16369899/149813115-07ac61d5-8362-4e1e-b6d2-2ee5098e4349.png)

![image](https://user-images.githubusercontent.com/16369899/149813017-fdbd70de-cf40-4fb2-9e5b-d8947af5719e.png)

**Comment by stdjs** [comment]
I just found what cause this problem, that directory contains a empty file (0 byte), if i put a 0 byte file into any directory, i use that directory to create a torrent, load the torrent, then lt::create_torrent(*handle.torrent_file()) => Segmentation fault
