### ISSUE TITLE
How does openwrt build python modules?

### ISSUE THREAD

**Issue by hong0980** [arvidn/libtorrent#6675]
CC="x86_64-openwrt-linux-musl-gcc"
CCSHARED="x86_64-openwrt-linux-musl-gcc -DPIC -fpic"
CXX="x86_64-openwrt-linux-musl-g++"
LD="x86_64-openwrt-linux-musl-gcc"
LDSHARED="x86_64-openwrt-linux-musl-gcc -shared"
In this `https://github.com/immortalwrt/packages/blob/master/libs/libtorrent-rasterbar/Makefile` how to build deluge with python3-libtorrent dependency in openwrt, thanks!

**Comment by arvidn** [comment]
I'm not sure I understand what you're asking. If you need help cross-compiling libtorrent, you could take a look here: https://blog.libtorrent.org/2017/02/building-libtorrent-for-c-h-i-p/

**Comment by hong0980** [comment]
root@OpenWrt:~# ldd /usr/lib/libtorrent-rasterbar.so.1.2.15
        ldd (0x7f31e8dc2000)
        libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x7f31e8a07000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x7f31e873d000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f31e8657000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7f31e8643000)
        libc.so => ldd (0x7f31e8dc2000)
Error relocating /usr/lib/libtorrent-rasterbar.so.1.2.15: libiconv: symbol not found
Error relocating /usr/lib/libtorrent-rasterbar.so.1.2.15: libiconv_open: symbol not found
