### ISSUE TITLE
Protocol encryption does not work

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6676]
@arvidn Looks like I've invented (or maybe I just activated) a way to get rid of tracking sites like iknowwhatyoudownload.com and similar.
To do this I use: disabling distribution, encrypting incoming and outgoing connections and blocking by ip address of different countries. For example iknowwhatyoudownload.com is Luxembourg. Ip lists by country are available on this site: https://www.iblocklist.com/lists?category=country

But my question is different. As you know, torrents via 4G are blocked in Russia.
Even the protocol encryption does not help to bypass this blocking. For what reason? Because of the first message, which is transmitted in unencrypted form? Or there is some other reason?

**Comment by arvidn** [comment]
> Even the protocol encryption does not help to bypass this blocking. For what reason? Because of the first message, which is transmitted in unencrypted form? Or there is some other reason?

the protocol encryption (or, obfuscation) doesn't send any messages in clear-text. it uses a random length prefix of random bytes.

I don't know how that filtering is done.

**Comment by master255** [comment]
@arvidn I turned it on:
settingsPack.set_bool(settings_pack.bool_types.enable_outgoing_utp.swigValue(), false);
settingsPack.set_bool(settings_pack.bool_types.enable_incoming_utp.swigValue(), false);
settingsPack.set_bool(settings_pack.bool_types.prefer_rc4.swigValue(), true);
settingsPack.set_int(settings_pack.int_types.in_enc_policy.swigValue(), settings_pack.enc_policy.pe_forced.swigValue())
settingsPack.set_int(settings_pack.int_types.out_enc_policy.swigValue(), settings_pack.enc_policy.pe_forced.swigValue());

After that, I ran Packet Capture app from Playmarket to record packets.
Then started downloading my torrent.

In the packet record I saw this. The message is unencrypted. Maybe I did something wrong? Or is there something I don't understand?
![Screenshot_20220122-171944_Packet Capture](https://user-images.githubusercontent.com/5380115/150642413-748350b0-2ed0-4148-9836-aad9d7a93db4.jpg)

**Comment by master255** [comment]
@arvidn And I checked it twice. After I enabled encryption on the server. No encryption. Why is there no encryption?

**Comment by Seeker2** [comment]
DHT enabled?
LSD/LPD enabled?
Internal Tracker enabled?
WEBUI enabled?

**Comment by master255** [comment]
@Seeker2 

> DHT enabled?
LSD/LPD enabled?
Internal Tracker enabled?
WEBUI enabled?

DHT enabled
LSD enabled
The rest is not in Libtorrent.

And this is a TCP packet.

**Comment by Seeker2** [comment]
In your picture, it shows ut_holepunch ...which is something I thought only went by UDP packet, but I guess that could be TCP as well.

I don't understand if the traffic you logged is incoming or outgoing from your local PC's point-of-view (so would be the opposite for the remote peer/seed).

**Comment by master255** [comment]
@Seeker2 You can check it yourself by enabling encryption.

**Comment by Seeker2** [comment]
You have little-to-no control over incoming connections, many/most of which will be initially unencrypted regardless of your end's settings.

But if it's an OUTGOING packet, it is a BUG.

**Comment by master255** [comment]
@Seeker2 This is an outgoing packet and an incoming packet.

**Comment by Seeker2** [comment]
It can't be both from libtorrent's point-of-view.

**Comment by master255** [comment]
@arvidn And I tested Libretorrent with the latest version. There, too, messages are sent without encryption, even though I specified in the settings to force the use of encryption. It turns out all versions of Libtorrent do not encrypt some messages when encryption is enabled. How to fix this?

![Screenshot_20220122-195940_Packet Capture](https://user-images.githubusercontent.com/5380115/150648306-cffc9617-66b3-430d-b44b-812a05bc7de8.jpg)

**Comment by Seeker2** [comment]
Seems like a definite bug then in Libtorrent.

**Comment by master255** [comment]
> Seems like a definite bug then in Libtorrent.

All torrent clients have this bug.

**Comment by master255** [comment]
@arvidn 2. Why is the "Bittorent protocol" used? Not just bt. This is how much traffic can be reduced by reducing this text.

**Comment by HanabishiRecca** [comment]
It is not a bug or some `libtorrent` issue. This particular string is part of the Bittorrent protocol handshake and defined in the standard: https://www.bittorrent.org/beps/bep_0003.html

![image](https://user-images.githubusercontent.com/13597663/150653213-1dbc08fe-93e7-443d-b3e4-793a79ce29fc.png)

In the library it defined here:
https://github.com/arvidn/libtorrent/blob/91d59336106ef7b8461c6ba256509c570c40f253/src/bt_peer_connection.cpp#L706

**Comment by master255** [comment]
Excuse me. I accidentally brought this disgraceful circus from Russia. You need to get out of the habit of posting links.

**Comment by master255** [comment]
@arvidn You can fix the protocol encryption or add a setting that will enable encryption of the first message. Or do you have any ideas?

**Comment by arvidn** [comment]
@master255 it would be nice to rule out an issue in the swig bindings.
and that capture log isn't so easy to interpret from your screenshot. Do you have a wireshark capture for that connection?
Is it an incoming unencrypted connection that libtorrent then responds to, even though it should have disconnected it? Or it it an outgoing unencrypted connection?

Your capture seems to suggest (but it's hard to know given there's no context of where connections start and end on your screenshot) that protocol encryption works *sometimes*, so your title is misleading (or at least the screenshot doesn't support it).

**Comment by master255** [comment]
@arvidn This is an incoming unencrypted connection and an unencrypted outgoing response. Although both the client and the server had forced encryption flags in their settings.

Immediately after this message, the ISP blocks the data transmission.

> it would be nice to rule out an issue in the swig bindings.

@aldenml Perhaps you can help here? What do you think about it? A problem with your library too. Encryption forcing either does not work or is not enabled.
@arvidn  All other settings work on the same principle and they definitely work.
It is impossible to select something else in the code.

Wireshark is missing for Android. But you can check it yourself.
The program I used uses a global VPN to redirect and analyze traffic. Of course, it does not contain any mechanisms to decrypt messages.

> Is it an incoming unencrypted connection that libtorrent then responds to, even though it should have disconnected it?

Well, yes. Because the forced encryption setting is enabled. And it's on both sides.

**Comment by arvidn** [comment]
> @arvidn You can fix the protocol encryption or add a setting that will enable encryption of the first message. Or do you have any ideas?

I think you have misunderstood how protocol encryption works. there's no distinction between the "first message" and other messages. It encrypts the whole stream and a layer below the bittorrent protocol.

There are two modes of the protocol encryption
1. Just obfuscates the handshake, by introducing a random number of random bytes at the start of the connection followed by the protocol in plain text.
2. encrypts the plain-text protocol with RC4 in addition to the padding at the connection handshake time.

Is it possible that you're seeing (1)?
In your capture, are the plain-text packets the *first* packets in the connection?

**Comment by arvidn** [comment]
@master255 as far as I can tell from your code snippet, you're not setting `allowed_enc_level` to `pe_rc4`, which means you allow both.

**Comment by arvidn** [comment]
If you think the documentation aught to be improved, please submit a PR

**Comment by master255** [comment]
> @master255 as far as I can tell from your code snippet, you're not setting `allowed_enc_level` to `pe_rc4`, which means you allow both.

I need to test it. Ok.

**Comment by master255** [comment]
> @master255 as far as I can tell from your code snippet, you're not setting `allowed_enc_level` to `pe_rc4`, which means you allow both.

@arvidn Yes. I checked it twice. It does include the encryption from the first message.
I think this setting should be added to all clients when enabling encryption.
@proninyaroslav
@glassez

**Comment by proninyaroslav** [comment]
@arvidn
@master255 

Do I understand correctly that setting `prefer_rc4` in `true` (as in example) doesn't make sense if `allowed_enc_level` set in `pe_rc4`? Based on the documentation it's right: 

> if the allowed encryption level is both, setting this to true will prefer RC4 if both methods are offered, plain text otherwise

**Comment by master255** [comment]
@proninyaroslav It should be a single setting. There is no need to separate the outgoing channel from the incoming one.

if (options.isTorrentEncryptionOn()) {
                settingsPack.set_int(settings_pack.int_types.in_enc_policy.swigValue(), settings_pack.enc_policy.pe_forced.swigValue());
                settingsPack.set_int(settings_pack.int_types.out_enc_policy.swigValue(), settings_pack.enc_policy.pe_forced.swigValue());
                settingsPack.set_int(settings_pack.int_types.allowed_enc_level.swigValue(), settings_pack.enc_level.pe_rc4.swigValue());
            } else {
                settingsPack.set_int(settings_pack.int_types.in_enc_policy.swigValue(), settings_pack.enc_policy.pe_enabled.swigValue());
                settingsPack.set_int(settings_pack.int_types.out_enc_policy.swigValue(), settings_pack.enc_policy.pe_enabled.swigValue());
                settingsPack.set_int(settings_pack.int_types.allowed_enc_level.swigValue(), settings_pack.enc_level.pe_both.swigValue());
            }

**Comment by master255** [comment]
@arvidn You might need to think about removing unnecessary settings. Combine some settings into a single setting. This is called settings refactoring. Of course very carefully and without new issues.

**Comment by arvidn** [comment]
> There is no need to separate the outgoing channel from the incoming one.

You mean to say that *you* don't have that need. Other people of course might.

**Comment by master255** [comment]
@arvidn You can delete the setting and wait for the issue to appear. If it appears, return it.

**Comment by proninyaroslav** [comment]
The fix pushed to LibreTorrent https://github.com/proninyaroslav/libretorrent/commit/3adea817b2fc636cdfde01b76b21ee7a47caaef7
