### ISSUE TITLE
pkgconfig .pc definition file contains Darwin lib and include directories that do not exist on other platforms

### ISSUE THREAD

**Issue by darktohka** [arvidn/libtorrent#6677]
**Please provide the following information**

libtorrent version (or branch): branch RC_2_0

platform/architecture: x86_64, Alpine 3.15, Linux

compiler and compiler version: gcc 10.3.1, b2 1.77.0

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I am compiling libtorrent with `BOOST_ROOT` set to an empty string, with the following BUILD_CONFIG: `release cxxstd=14 crypto=openssl warnings=off address-model=32`

After compiling and installing libtorrent with `b2`, I am trying to link `libtorrent` to another project: qBittorrent, through CMake. Compiling qBittorrent with CMake yields the following CMake error:

```
CMake Error in src/base/CMakeLists.txt:
  Imported target "PkgConfig::PC_LIBTORRENT_RASTERBAR" includes non-existent
  path

    "/opt/homebrew/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

However, this is actually an issue on libtorrent's part. The `/opt/homebrew` and `/usr/local/opt/boost` folders only make sense on the Darwin platform, and should not be in the pkgconfig definition file on any other platform. Installing libtorrent using b2 has yielded the following, incorrect pkgconfig file in /usr/lib/pkgconfig/libtorrent-rasterbar.pc:

```
Name: libtorrent-rasterbar
Description: libtorrent is an open source C++ library implementing the BitTorrent protocol
URL: https://libtorrent.org
Version: 2.0.5
Libs:  -L"/usr/lib"  -L"/opt/homebrew/lib"  -L"/usr/local/opt/boost/lib"  -ltorrent-rasterbar  -lboost_system  -lcrypto  -ldl  -lssl
Libs.private:  -L"/usr/lib"  -L"/opt/homebrew/lib"  -L"/usr/local/opt/boost/lib"  -llibtry_signal.a
Cflags:  -DTORRENT_USE_LIBCRYPTO  -DTORRENT_USE_OPENSSL  -DTORRENT_SSL_PEERS  -DTORRENT_USE_I2P=1  -DBOOST_ALL_NO_LIB  -DBOOST_ASIO_ENABLE_CANCELIO  -DBOOST_ASIO_HAS_STD_CHRONO  -DBOOST_ASIO_NO_DEPRECATED  -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION  -DBOOST_SYSTEM_NO_DEPRECATED  -DTORRENT_LINKING_SHARED  -I"/usr/lib"  -I"/opt/homebrew/include"  -I"/usr/local/opt/boost/include"
```

Expected output:

```
Name: libtorrent-rasterbar
Description: libtorrent is an open source C++ library implementing the BitTorrent protocol
URL: https://libtorrent.org
Version: 2.0.5
Libs:  -L"/usr/lib"  -ltorrent-rasterbar  -lboost_system  -lcrypto  -ldl  -lssl
Libs.private:  -L"/usr/lib"  -llibtry_signal.a
Cflags:  -DTORRENT_USE_LIBCRYPTO  -DTORRENT_USE_OPENSSL  -DTORRENT_SSL_PEERS  -DTORRENT_USE_I2P=1  -DBOOST_ALL_NO_LIB  -DBOOST_ASIO_ENABLE_CANCELIO  -DBOOST_ASIO_HAS_STD_CHRONO  -DBOOST_ASIO_NO_DEPRECATED  -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION  -DBOOST_SYSTEM_NO_DEPRECATED  -DTORRENT_LINKING_SHARED  -I"/usr/lib"
```

This file is generated in `Jamfile` at https://github.com/arvidn/libtorrent/blob/RC_2_0/Jamfile#L1035.

I suggest removing the /opt/homebrew and /usr/local/opt/boost definitions when the `target-os` is not `darwin`, or suggest adding a check to see if these folders actually exist (if `Jamfile` allows this - I am not familiar with the format).

Thank you in advance!

**Comment by arvidn** [comment]
fixed here (for `RC_1_2`). It will get merged into `RC_2_0` later.

https://github.com/arvidn/libtorrent/pull/6680
