### ISSUE TITLE
[Android] Operation not supported on transport endpoint, code 95

### ISSUE THREAD

**Issue by proninyaroslav** [arvidn/libtorrent#6688]
**Please provide the following information**

libtorrent version (or branch): master

platform/architecture: Android arm64

Initially, this problem is seen in libtorrent4j, but I think this is the upstream problem: https://github.com/aldenml/libtorrent4j/issues/200

This error appears at every session start after the network fix for Android 11 has been pushed: https://github.com/arvidn/libtorrent/commit/908bdd93459c9c52fbef55edb732f926d03b153c. Tested on API 25 - 31.

```
I: Peer fingerprint: -Lr3200-
I: User agent: LibreTorrent 3.2
E: Session error: Operation not supported on transport endpoint, code 95
E: Session error: Operation not supported on transport endpoint, code 95
E: Session error: Operation not supported on transport endpoint, code 95
E: Session error: Operation not supported on transport endpoint, code 95
E: Session error: Operation not supported on transport endpoint, code 95
E: Session error: Operation not supported on transport endpoint, code 95
E: Session error: Operation not supported on transport endpoint, code 95
E: Session error: Operation not supported on transport endpoint, code 95
I: [SESSION_LOG] update listen interfaces: 0.0.0.0:46849,[::]:46849
I: [SESSION_LOG] parsed listen interfaces count: 2, ifaces: 0.0.0.0:46849,[::]:46849
I: [SESSION_LOG] about to stop DHT, running: false
I: [SESSION_LOG] starting DHT, running: false, router lookups: 0
I: [SESSION_LOG] external address updated for 0.0.0.0:46849 [ new-ip: 37.235.201.30 type: 2 last-voter: 185.157.221.247 ]
```

Full log: [LibreTorrent.-.Debug_log_11-21-2021_18-57-17.txt](https://github.com/arvidn/libtorrent/files/7923927/LibreTorrent.-.Debug_log_11-21-2021_18-57-17.txt)

**Comment by arvidn** [comment]
the `session_error_alert` is posted when something throws an exception that wasn't expected to fail. Would it be possible for you to catch the exception and report where it's coming from?

in `gdb`, run:

```
catch throw
```

**Comment by proninyaroslav** [comment]
Probably I need debug symbols for this? But I'm not sure if libtorrent4j has them.

**Comment by arvidn** [comment]
yeah, that would help.

**Comment by arvidn** [comment]
presumably it's this error bubbling up: https://github.com/arvidn/libtorrent/commit/908bdd93459c9c52fbef55edb732f926d03b153c#diff-04ca6b977648e95b569d15893d7625a5fef352042a1917cd19f2ba183619fb2dR1493

**Comment by proninyaroslav** [comment]
Yeah, I had that thought. But why does this branch pass if we have `TORRENT_USE_IFADDRS` set?

**Comment by proninyaroslav** [comment]
Yes, this seems to be a bug on the Android Framework side. The system gives incorrect information about the write permission.

**Comment by proninyaroslav** [comment]
Sorry, my bad.
