### ISSUE TITLE
Wrong file attributes

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6697]
@arvidn I'm creating a torrent:
file_storage fileStorage = new file_storage();
libtorrent.add_files(fileStorage, file.getAbsolutePath(), TorrentBuilder.OPTIMIZE_ALIGNMENT);

Bug#1: Depending on the device, the "executable" attribute is set. This affects the hash. (It shouldn't depend on the device.)
Bug#2: There is no method to set (or clear) the flag to files after adding them with this function.

**Comment by arvidn** [comment]
how does this look? https://github.com/arvidn/libtorrent/pull/6706
