### ISSUE TITLE
Verify whether some file is contained in a torrent

### ISSUE THREAD

**Issue by cyrillicw** [arvidn/libtorrent#6705]
Since libtorrent uses merkle tree for hashing, I suppose that it is possible to check whether a file with a given hash is contained in a torrent with a given hash. Is there such a functionality in libtorrent?

**Comment by cyrillicw** [comment]
If it can be helpful, it can be guaranteed that the file is in the end of torrent and its size is very small (32 bytes)

**Comment by arvidn** [comment]
there's no index of all root hashes that can be used as a lookup, but you can always iterate all files in a torrent and compare the hashes.

There's an internal class that's used to match identical files (for the "similar"-torrent feature) that can be used as inspiration: https://github.com/arvidn/libtorrent/blob/RC_2_0/src/resolve_links.cpp#L41

**Comment by cyrillicw** [comment]
Thank you very much!
