### ISSUE TITLE
Windows shared drive directory issue

### ISSUE THREAD

**Issue by FletcherD** [arvidn/libtorrent#6708]
I've noticed an issue with the way file handles on shared drives are handled than can prevent libtorrent from downloading torrents to Windows shared drives. I also created a workaround that fixes this and a pull request. #6707 

The issue is this:
When starting to write a file in a torrent libtorrent checks if it can open the file using CreateFileW. If the directory doesn't exist then Windows responds with "ERROR_FILE_NOT_FOUND". Libtorrent then tries to create the directory tree and tries again.

However when we try to create a file on a Windows network drive, there can be some odd behavior. If the directory doesn't exist Windows instead returns error code 1117, "ERROR_IO_DEVICE". This doesn't really make sense to me because there is no real I/O error with the network drive, the directory just doesn't exist.

This causes libtorrent to fail instead of trying to create the directory.
As a workaround I just check for this code too on Windows platforms and also try to create the directory in this case.

It's possible this could also occur when a real I/O device error occurs, however I don't see this having much impact as if there is a real I/O error, the subsequent directory creation will fail too.

libtorrent version (or branch):
RC 2.0

platform/architecture:
Windows x64

compiler and compiler version:
MSVC 22

How to reproduce:
Have write access to a network share in Windows
Choose a torrent that contains files in a directory (not one file)
Attempt to start downloading it to the network drive

Expected behavior:
The directory structure is created and files are downloaded to it

Actual behavior:
The torrent fails with Error value: 1117 - "The request could not be performed because of an I/O device error."

**Comment by PriitUring** [comment]
If patch was merged and has been working correctly for you, then can this issue be closed?
https://github.com/arvidn/libtorrent/pull/6718#issuecomment-1039826075
