### ISSUE TITLE
python: apply lt.min_memory_usage or high_performance_seed causing 100% cpu usage

### ISSUE THREAD

**Issue by mayli** [arvidn/libtorrent#6710]
libtorrent version (or branch): 1.2.x 2.x
platform/architecture: x86
compiler and compiler version: pypi precompile wheels

Reproduce:

Dockerfile
```
from python
run pip install libtorrent
cmd python -i -c "import libtorrent as lt; s=lt.session();s.apply_settings(lt.min_memory_usage())"
```
build and run
`docker build -t lt .`
`docker run --rm -ti lt`

Use htop or top to monitor the cpu usage.

This only happens when those builtin settings_pack are applied. I notice the [tick_interval](https://www.libtorrent.org/reference-Settings.html#tick_interval) is given default value 0 in both settings_pack, which will trigger the 100% cpu usage immediately. Most of the values from the min_memory_usage or high_performance_seed are either `False` or `0`, is it expected to filter those values out before calling `apply_settings`?

**Comment by arvidn** [comment]
perhaps there's an issue in the binding, where when a value is missing, instead is interpreted as present as value 0.

**Comment by arvidn** [comment]
does this look good? https://github.com/arvidn/libtorrent/pull/6714

**Comment by arvidn** [comment]
thanks for the report!
