### ISSUE TITLE
WebSeed doesn't work on Android

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6712]
@arvidn I tested with the latest version of Libretorrent and Media Library. This file does not download, although the link to the file works.
This is a PeerTube file.

But on Windows qBittorrent can download this file. There must be a condition in the library somewhere that affects whether webseed can be downloaded
[af0988c5bb62cdadb600c553809563d1f3693bec.zip](https://github.com/arvidn/libtorrent/files/8006623/af0988c5bb62cdadb600c553809563d1f3693bec.zip)
.

**Comment by master255** [comment]
@aldenml Maybe you can help here.
I see this in the logs of the Android library:
com.media.library D/222222: PEER_LOG: lesson2.mp4 1080p.mp4 peer [ 51.79.220.234:443 client: Unknown ] [51.79.220.234:443] *** CONNECTION FAILED [ 51.79.220.234:443 ERROR: (asio.ssl:537313350) asio.ssl error ]
com.media.library D/222222: LOG: CONNECTION FAILED: 51.79.220.234:443
com.media.library D/222222: PEER_LOG: lesson2.mp4 1080p.mp4 peer [ 51.79.220.234:443 client: Unknown ] [51.79.220.234:443] *** CONNECTION_FAILED [ op: 16 ERROR: (asio.ssl:537313350) asio.ssl error ]
com.media.library D/222222: PEER_LOG: lesson2.mp4 1080p.mp4 peer [ 51.79.220.234:443 client: Unknown ] [51.79.220.234:443] *** CONNECTION CLOSED [  ]

**Comment by master255** [comment]
@aldenml Maybe you can help here.
I see this in the logs of the Android library:
2022-02-05 02:03:10.454 11996-12170/com.media.library D/222222: PEER_LOG: lesson2.mp4 1080p.mp4 peer [ 51.79.220.234:443 client: Unknown ] [51.79.220.234:443] >>> OUTGOING_CONNECTION [ ep: 51.79.220.234:443 type: SSL/TCP seed: 0 p: 0x756f4dda78 local: 0.0.0.0:0 ]
2022-02-05 02:03:10.454 11996-12170/com.media.library D/222222: PEER_LOG: lesson2.mp4 1080p.mp4 peer [ 51.79.220.234:443 client: Unknown ] [51.79.220.234:443] *** URL [ web_peer_connection https://peertube.rtnkv.cloud/static/webseed/0c1540ed-97fa-41df-9ca7-08a4132db58c-1080.mp4 ]
2022-02-05 02:03:10.454 11996-12170/com.media.library D/222222: PEER_LOG: lesson2.mp4 1080p.mp4 peer [ 51.79.220.234:443 client: Unknown ] [51.79.220.234:443] *** SET_PEER_CLASS [ a: 51.79.220.234 ]
2022-02-05 02:03:10.455 11996-12170/com.media.library D/222222: PEER_LOG: lesson2.mp4 1080p.mp4 peer [ 51.79.220.234:443 client: Unknown ] [51.79.220.234:443] *** CLASS [ global tcp  ]
2022-02-05 02:03:10.455 11996-12170/com.media.library D/222222: PEER_LOG: lesson2.mp4 1080p.mp4 peer [ 51.79.220.234:443 client: Unknown ] [51.79.220.234:443] >>> OPEN [ protocol: IPv4 ]
2022-02-05 02:03:10.455 11996-12170/com.media.library D/222222: PEER_LOG: lesson2.mp4 1080p.mp4 peer [ 51.79.220.234:443 client: Unknown ] [51.79.220.234:443] >>> BIND [ dst: 0.0.0.0:0 ec: Success ]
2022-02-05 02:03:10.457 11996-12170/com.media.library D/222222: PEER_LOG: lesson2.mp4 1080p.mp4 peer [ 51.79.220.234:443 client: Unknown ] [51.79.220.234:443] >>> ASYNC_CONNECT [ dst: 51.79.220.234:443 ]
2022-02-05 02:03:10.457 11996-12170/com.media.library D/222222: PEER_LOG: lesson2.mp4 1080p.mp4 peer [ 51.79.220.234:443 client: Unknown ] [51.79.220.234:443] *** LOCAL ENDPOINT [ e: 192.168.1.103:45004 ]
2022-02-05 02:03:11.070 11996-12170/com.media.library D/222222: PEER_LOG: lesson2.mp4 1080p.mp4 peer [ 51.79.220.234:443 client: Unknown ] [51.79.220.234:443] *** CONNECTION FAILED [ 51.79.220.234:443 ERROR: (asio.ssl:537313350) asio.ssl error ]
2022-02-05 02:03:11.071 11996-12170/com.media.library D/222222: LOG: CONNECTION FAILED: 51.79.220.234:443
2022-02-05 02:03:11.071 11996-12170/com.media.library D/222222: PEER_LOG: lesson2.mp4 1080p.mp4 peer [ 51.79.220.234:443 client: Unknown ] [51.79.220.234:443] *** CONNECTION_FAILED [ op: 16 ERROR: (asio.ssl:537313350) asio.ssl error ]
2022-02-05 02:03:11.071 11996-12170/com.media.library D/222222: PEER_LOG: lesson2.mp4 1080p.mp4 peer [ 51.79.220.234:443 client: Unknown ] [51.79.220.234:443] *** CONNECTION CLOSED [  ]

**Comment by aldenml** [comment]
`libtorrent4j` use the latest openssl version, and maybe there is some ciphersuites left out. Can you try `openssl s_client ...` to the host of the webseed?

**Comment by arvidn** [comment]
it also seems the ssl error messages aren't printed as human readable. which makes it hard to know what's actually failing. OpenSSL generates its error codes, I don't know of a way to convert the error code to a message "offline".

```
*** CONNECTION_FAILED [ op: 16 ERROR: (asio.ssl:537313350) asio.ssl error ]
```

Operation 16 is "connect". It could also be a missing root certificate on the phone.

**Comment by master255** [comment]
@arvidn I checked. Exactly the same error on all Android devices and emulators. The problem is not with the device, but in the library. Even Media Library can open this file, but Libtorrent cannot.

**Comment by master255** [comment]
@aldenml Everything is beautiful? :

`oleg@RAIDER:~$ openssl s_client -connect peertube.rtnkv.cloud:443
CONNECTED(00000003)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = peertube.rtnkv.cloud
verify return:1
---
Certificate chain
 0 s:CN = peertube.rtnkv.cloud
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFrzCCBJegAwIBAgISA+N1D0gJoKfSlauZu3knRDUpMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMjAxMTUwNTI4MjBaFw0yMjA0MTUwNTI4MTlaMB8xHTAbBgNVBAMT
FHBlZXJ0dWJlLnJ0bmt2LmNsb3VkMIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIB
igKCAYEA0kRJl1h9yXY7/sHuiqNLy6Zoi3Cp1p/yH/WOhJIcU+20zQUrB92QUVpd
Zq8vjicl7iCzjOMfkwGTBh4LxzWhI0KNnm7PW0lh4x1MrQ3CkG6B/jZB2VgN9xma
cPp70yivg+zQo6McSNy1k/oj8nmk19R323uYkJvvQagGA+NuX6tTb4sYsX25hMs3
NjBuwBTgi2jKnJm9yZAObIXr37FyHzERNAdawV835jkiSeGKsddz0pj1R6NeuwJ5
mYh83UZFsSYr/3VQ+684IG/NMiVFRpQ8vPbGMza+beGyblTnFEj2SNMQzYbofULQ
1I+UxZP+4i+oz8E55UTE90nUGwrhArNVIoCBAKr3Mmyr1e4A5NHTdD8u1wzENmm1
J5W5PTZMlaVi8D6/t8IwOZygTd4G3pnx3fSp36nxHTEGv8elI/A/xkTPT3yjqnhd
vK+5F85mZfvuiN4SYHGJIUCnP9xatI59MRlYVqISuKuPxghVGsHwx6w7xXaFArvq
4d5qAFljAgMBAAGjggJQMIICTDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYI
KwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFGQMMOZ3
LCS9IMQ4XCyurniSnr+9MB8GA1UdIwQYMBaAFBQusxe3WFbLrlAJQOYfr52LFMLG
MFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0cDovL3IzLm8ubGVuY3Iu
b3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMuaS5sZW5jci5vcmcvMB8GA1UdEQQY
MBaCFHBlZXJ0dWJlLnJ0bmt2LmNsb3VkMEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcG
CysGAQQBgt8TAQEBMCgwJgYIKwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5
cHQub3JnMIIBBQYKKwYBBAHWeQIEAgSB9gSB8wDxAHcAQcjKsd8iRkoQxqE6CUKH
Xk4xixsD6+tLx2jwkGKWBvYAAAF+XGwsTwAABAMASDBGAiEAzoPmTH2sIDhhRlU9
Zm7lvNOyLgMshJWbMaBgpTfy3LgCIQCM3JLUz50QnE4I8zhEn0dkilv2v95iw7T9
ygb4KRgVtAB2AEalVet1+pEgMLWiiWn0830RLEF0vv1JuIWr8vxw/m1HAAABflxs
LIoAAAQDAEcwRQIhAN4A6iCeZo6pnNxxQ00sFGB5pRfy0/yjM0F57NQ4D4VkAiAf
ea4XBDuZnToXx3RObBqbMY0s1oswLEs7iCuPEfywEDANBgkqhkiG9w0BAQsFAAOC
AQEAPA9cdUyFPTr7leWofhdDyqcW9qDQA95JdYIcepwRSUBgVItGzW2uAu50LOgl
wYMaAyIAVcw5SJzCRJdvafAXjkzULXYavJ73TSHfMlFc0HRiMzoIlL5y9T0ybKVx
fE6Y70XF/RktoDgg8EgWPV4lGtA+hBVhYDSHUg6CDaZFCfwoupyAkW2NqelWQMnQ
olDdJFaHIpqOIV0b420YgaMWFBEnqjndV/DNZhAKD3kPJS5YMr5FsRi6Y9yeg+2s
4r4eWzO2OZPMfrPJa4nh66fFw+T+jfSS8fX0cy1UsD+jC9tHl4NtXRgZzjMDfzTb
BX3TBuPOzzvb+e6Q5+SAVWSFxQ==
-----END CERTIFICATE-----
subject=CN = peertube.rtnkv.cloud

issuer=C = US, O = Let's Encrypt, CN = R3

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 4843 bytes and written 392 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 3072 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 65121DEC6D5BC9C6942BAD08B29869B419F64A503CA0A874D43C5F515A2C9B43
    Session-ID-ctx:
    Resumption PSK: BAEA091131D0E1733FDB2247478066FB82666CD1B3CEF8E84A351831AEDFAFEC9B4643136B10480EF7040147BCAD2C75
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 86400 (seconds)
    TLS session ticket:
    0000 - 0e 2a ca 74 64 6a 6a 41-f3 11 c6 c7 cd 46 42 e2   .*.tdjjA.....FB.
    0010 - 90 88 f5 3c 13 b2 da 1d-b9 ba 29 cd 85 f0 51 10   ...<......)...Q.

    Start Time: 1644054723
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: FB2694F56E51DDE30C9BB881B91B99CFFB49724300817909772D2E74A833C3E6
    Session-ID-ctx:
    Resumption PSK: 18577D65D6824035040B0A6B69A919DE932EFE515668EC5D8657BA729F3E80D0EAD73F253F999464B8747B7C51616329
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 86400 (seconds)
    TLS session ticket:
    0000 - 40 31 7d 4f b0 fb 47 75-bc 45 11 8d 15 77 78 18   @1}O..Gu.E...wx.
    0010 - 67 7c a4 94 29 59 c3 01-53 a8 cf 7b 5a 23 b7 7b   g|..)Y..S..{Z#.{

    Start Time: 1644054723
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK`

**Comment by aldenml** [comment]
@master255 I need some time to look into this. Can you clarify if this happens on both `libtorrent4j` and `jlibtorrent`? (I don't which one uses Media Library)

**Comment by master255** [comment]
@aldenml This is reproduced on all versions of Libtorrent.

**Comment by master255** [comment]
@aldenml message me on "telegram" https://t.me/Master255
I'll try to help.

**Comment by master255** [comment]
@aldenml , @arvidn Perhaps it is necessary to use this TORRENT_USE_OPENSSL constant somewhere?

**Comment by master255** [comment]
@aldenml How much time do you need?

**Comment by aldenml** [comment]
Hi @master255 , I might be able to work on this during the weekend

**Comment by master255** [comment]
@aldenml @gubatron I found that frostwire-android-release-2.2.8-b672-plus could download this file, but frostwire-android-release-2.2.9-b675-plus could not. 
What has changed between these versions?

**Comment by master255** [comment]
@arvidn It was your change that broke it all. What did you do?
![image](https://user-images.githubusercontent.com/5380115/152992314-82c6b71b-8faf-4de5-8644-fa94a2819160.png)

**Comment by aldenml** [comment]
@master255 this is the commit relevant to that change https://github.com/arvidn/libtorrent/commit/c56a8aec912682c7d5191647430beb3ad2faf695

maybe you want to set `validate_https_trackers` to `false` and test it.

**Comment by master255** [comment]
@aldenml @arvidn Yes. This setting helps. But the bug is still there. Libtorrent probably can't find the Android certificate. [The Jam file has certificate paths for all operating systems except Android.](https://github.com/arvidn/libtorrent/blob/77172672c8db2f6bcef17d867d9a81faae77ec1e/Jamfile#L533)

**Comment by master255** [comment]
@arvidn And then there's this question. Why is it necessary to check the certificates at all? What for? It doesn't matter which tracker's certificate will expire. Why this should affect the download of data, if the data is checked with hashes anyway.

**Comment by proninyaroslav** [comment]
`validate_https_trackers` is already added in version 3.4

**Comment by master255** [comment]
> `validate_https_trackers` is already added in version 3.4 as an option https://gitlab.com/proninyaroslav/libretorrent/-/issues/381

As you can see, this feature does not work on Android. It makes sense to temporarily enable it, without a choice.

**Comment by proninyaroslav** [comment]
> It makes sense to temporarily disable it, without a choice.

Yes, you are probably right. At least force enable it.

**Comment by gubatron** [comment]
Thanks for the heads up. In Jlibtorrent and FrostWire we've:
 - [Exposed `settings_pack.validate_https_trackers` on our higher level `SettingsPack` java wrapper](https://github.com/frostwire/frostwire-jlibtorrent/commit/2561abec22f92b05cc5dd6ad2e5e13be6d1a352f)
 - For now, [disabled this setting by default](https://github.com/frostwire/frostwire/commit/f38a5d8d07b8f64db0846258206e3b31757366c2) starting our next release.

**Comment by arvidn** [comment]
It's OpenSSL that's loading the certificates from the operating system. Either that doesn't work, or the tracker you're using is signed by some fringe CA that isn't shipped with android.

It sounds like @master255 has concluded it's the former, but I haven't seen any evidence. The latter is quite plausible too. I have seen examples of that.

If anyone know how to read the certificate store on android, please share, it might be a simple fix. There is already special handling of the windows certificate store.

**Comment by master255** [comment]
@arvidn A simple question. Why is this needed at all?  https://github.com/arvidn/libtorrent/issues/6712#issuecomment-1032664268

**Comment by arvidn** [comment]
> Why is this needed at all?

To authenticate the tracker you're talking to. Otherwise you don't know who you're talking to. If you don't care, you might as well use the DHT (where you also don't know who you're talking to).

**Comment by master255** [comment]
@arvidn Okay. I think this excessive functionality should be removed.

**Comment by arvidn** [comment]
Why do you think the person making the torrent would use http over ssl then? Why not just http, if authentication and confidentiality is unimportant?

**Comment by master255** [comment]
@arvidn Https allows encryption of traffic, but we're not talking about overriding encryption, we're talking about trust in certificates.

**Comment by arvidn** [comment]
Who are you encrypting the traffic from?
How do you know that's not person you're talking to?

**Comment by master255** [comment]
@arvidn What difference does it make with whom and from whom. If I trust the torrent file, I trust all the trackers listed in it. If some tracker ran out of certificate, it should not be a problem to download data.

An expired certificate is the server's problem, not the client's.  

If you want to get extra privacy from it, that won't work. An expired certificate will still encrypt the data. And if we ignore it, we can't download the data at all.

**Comment by arvidn** [comment]
> What difference does it make with whom and from whom.

If you don't care about authentication and confidentiality, it doesn't matter. But the fact that the tracker is running over SSL suggests that, at least, the person creating the torrent *does* care about those things.

> If I trust the torrent file, I trust all the trackers listed in it. If some tracker ran out of certificate, it should not be a problem to download data.

You trust the torrent file: yes
you trust the tracker hostname: yes
you connect to an IP address and trust that you're talking to the owner of the hostname: no, you can't know that without validating a certificate tied to that hostname.

> An expired certificate is the server's problem, not the client's.

It's the client's problem if it wants authentication and confidentiality of the counter-party.

**Comment by master255** [comment]
@arvidn 

> you connect to an IP address and trust that you're talking to the owner of the hostname: no, you can't know that without validating a certificate tied to that hostname.

But what is it for? If we still check the data we receive with hashes?
Why do we need to check the sender of the data?
It has no effect on privacy. Because it is unlikely that someone would hack into the server to send data that will not be used in any way.

**Comment by arvidn** [comment]
> But what is it for? If we still check the data we receive with hashes?
> Why do we need to check the sender of the data?

That's a question for the person making the torrent. I'm guessing they want to control access to the peer list, for private torrents.

> It has no effect on privacy. Because it is unlikely that someone would hack into the server to send data that will not be used in any way.

You mean it's *unlikely* to affect privacy then.
You don't need to hack the server to intercept someones traffic to it. There are lots of other ways.

**Comment by master255** [comment]
@arvidn 

> That's a question for the person making the torrent. I'm guessing they want to control access to the peer list, for private torrents.

But he himself specifies trackers in the torrent file. If he specifies trackers, it means he trusts them. 
Perhaps you are talking about a long time. If a tracker in a private torrent runs out of certificate in a year, an attacker could organize a man-in-the-middle attack? 
This is a very unique and rare case, which in practice is unlikely to happen.

> You don't need to hack the server to intercept someones traffic to it. There are lots of other ways.

Okay. I purposely asked silly questions.
I would like to highlight a few problems, which theoretically can arise if you cancel the certificate check:
1. World government - will be able to organize "man in the middle" attack on user downloading unknown torrent file, with trackers with unsigned certificates. Extremely unlikely (cheaper to send a police squad to the person's home), but theoretically possible.
2. If it is possible to forge a response from the tracker, it may be a DDOS attack via torrents. This is a more likely scenario. But in order to do this, it is necessary to hack the victim's ISP or router.

Are there any third theoretical points?
Both of these points are highly unlikely in principle. Of course you can leave this functionality, but the default setting should be "false" because this does not significantly affect security, but significantly affects the availability of data.

**Comment by arvidn** [comment]
there are lots of other ways to intercept someones traffic. But I don't think there's really any point in attempting an exhaustive enumeration. I don't think there's a point in arguing how unlikely an attack is. It's unlikely until it happens.

If you don't care about that risk, fine. Disable validation. There are use cases where this matters. Defaulting to not validating is unacceptable.

**Comment by master255** [comment]
@arvidn ok
@aldenml We're waiting for you to fix this bug. I'll close the issue.

**Comment by master255** [comment]
@aldenml You didn't do anything?

**Comment by aldenml** [comment]
hi @master255 , I'm under the impression that setting `validate_https_trackers` to `false` is an acceptable workaround for you. I have no plans to change the default value, but I would like to find where the Android local CAs are installed to set the path in `libtorrent`.

**Comment by master255** [comment]
@aldenml Hi. So you write down why and in what scenario would that somehow cause a problem? 
In the discussion with Arvin, we didn't find any significant problems.

**Comment by gubatron** [comment]
@master255 how about you submit a patch, stop bitching.

**Comment by proninyaroslav** [comment]
I think that "security" should not be partial, in the full sense of the word. If we use encryption, checking hash sums and other things, then the trackers should also give certain warranties, otherwise they can simply use HTTP, and not HTTP/S. 
In addition, disabling certificate verification doesn't solve the problem, it's just a workaround. The problem, as I understood it, in the missing access to the system certificates storage. I think that the disabling of certificate verification must stay to choose for the clients developers. They can simply disable, or give a choice to users (as I did). Maybе with some explanations for the user so that it can weigh the pros and cons.

**Comment by master255** [comment]
@gubatron But I'm on the dark side. I don't see the point of this at all. I don't need it. I have much more important things to do. Other than that, Alden himself offered to help. Let the one who thinks it is necessary do it.

And you need to study Media Library more. I check Frostwire (and Libretorrent) regularly.

**Comment by arvidn** [comment]
@master255 if you don't need it, how come disabling it isn't an acceptable solution for you?

**Comment by master255** [comment]
@arvidn You're right. For me this solution is acceptable. I will be glad if the bug is fixed, but I will decide what to do with this flag, after fixing the bug. So far, no one has made an argument that this could cause problems. So I will leave this flag at false.

**Comment by gubatron** [comment]
> But I'm on the dark side. I don't see the point of this at all. I don't need it. I have much more important things to do.
yada yada, all talk no action.

> And you need to study Media Library more.
Yes, they keep changing the damn android storage every 6 months, such a waste of time.
Please teach me with a pull requests, I could use the help.

**Comment by master255** [comment]
@gubatron 

> Yes, they keep changing the damn android storage every 6 months, such a waste of time.
Please teach me with a couple of pull requests, lots of bugs to fix I'm sure, I could use the help.

What? :)

**Comment by master255** [comment]
@proninyaroslav Maybe you didn't read what we're talking about.
The setting doesn't work. Set the default value to false, with no selectable options.

**Comment by arvidn** [comment]
@master255 
when you say:
> The setting doesn't work. Set the default value to false, with no selectable options.

What that sentence mean is "whether certificates are validated or not is unrelated to what the `validate_https_trackers` setting is set to".

I'm pretty sure you're wrong. It's really unhelpful to add so much noise as you do. please stop doing that.

**Comment by master255** [comment]
@arvidn 

> What that sentence mean is "whether certificates are validated or not is unrelated to what the validate_https_trackers setting is set to".

I didn't say that text and I don't know where you found it. And I don't know what it means. Arvin, express yourself in a way that I can understand you. Stop talking in riddles. I always write to you as legibly as possible.

> I'm pretty sure you're wrong. It's really unhelpful to add so much noise as you do. please stop doing that.

I proved above that Libtorrent cannot download a file using a direct https link from a server with a valid certificate. This is a bug that needs to be fixed.

**Comment by arvidn** [comment]
you said "The setting doesn't work."

Which I'm certain is wrong. It *does* work. The fact that you can use unauthenticated trackers when you disable it is evidence that it does.

**Comment by arvidn** [comment]
a setting that does not work means you have the same outcome regardless of how you set it. That isn't the case, and you haven't provided any evidence of that being the case.

**Comment by master255** [comment]
@arvidn Why are you doing this? You have too much free time and decide to spam me? 

The validate_https_trackers setting does not work on Android if set to true. Because Libtorrent cannot establish connections to any https site. This is an obvious bug. If the setting only allows downloads from valid https sites when set to false, then it does not work.

**Comment by master255** [comment]
@arvidn In Russia, we call such settings not working! :-O :-O :-O

**Comment by arvidn** [comment]
> Why are you doing this?

Because you're making false claims, and I feel responsible for these forums. They shouldn't be left uncontested.

> The validate_https_trackers setting does not work on Android if set to true. Because Libtorrent cannot establish connections to any https site. This is an obvious bug.

I don't trust that you have tested a sufficiently large sample of HTTPS sites to claim that *all* fail, but it seems reasonable to assume *some*, at least.

It's not an obvious bug in libtorrent. It could quite reasonably be a bug in OpenSSL. I suspect there's a bit of a gap of who feels responsible for it. The Android developers could distribute a version of OpenSSL that works for instance Just because it's an obvious bug *somewhere*, doesn't mean the report belongs in the libtorrent forum.

> In Russia, we call such settings not working!

Everywhere else we call it what it is; the certificate store in OpenSSL on Android may be lacking or missing. I think we can establish that to be likely at this point at least.

**Comment by proninyaroslav** [comment]
> I don't trust that you have tested a sufficiently large sample of HTTPS sites to claim that all fail, but it seems reasonable to assume some, at least.

Anyway, these trackers works in qBittorrent, for example. I got a lot of messages that HTTPS trackers don't work on my client. The problem is definitely with the certificates storage.

**Comment by FooIbar** [comment]
This requires an upstream fix https://github.com/openssl/openssl/pull/24002, or use BoringSSL.
