### ISSUE TITLE
/usr/lib/python3.10/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 2.0.5-build-libtorrent-rasterbar-src-libtorrent-rasterbar-2.0.5-bindings-python is an invalid version and will not be supported in a future release   warnings.warn(

### ISSUE THREAD

**Issue by killertofus** [arvidn/libtorrent#6716]
**Please provide the following information**

libtorrent version (or branch):
2.0.5.0
platform/architecture:
arch
compiler and compiler version:
qbittorrent 4.4.0
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

debugging a python file that I made it spits out 

```
[killertofus@killertofus Codev2]$  cd /mnt/10TBHD/Codev2 ; /usr/bin/env /bin/python /home/killertofus/.vscode-oss/extensions/ms-python.python-2022.0.1786462952/pythonFiles/lib/python/debugpy/launcher 36489 -- /mnt/10TBHD/Codev2/pybot.py 
/usr/lib/python3.10/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 2.0.5-build-libtorrent-rasterbar-src-libtorrent-rasterbar-2.0.5-bindings-python is an invalid version and will not be supported in a future release
  warnings.warn(
[killertofus@killertofus Codev2]$
```
![image](https://user-images.githubusercontent.com/16343162/152669048-a7e16556-3bf5-4e92-a6dc-fd754b292143.png)

**Comment by arvidn** [comment]
that's a deprecation warning. What's the issue?

**Comment by killertofus** [comment]
@arvidn try running this python code in arch
https://mystb.in/BoxesPowerfulRegular.python

**Comment by Kolcha** [comment]
should be already fixed by https://github.com/arvidn/libtorrent/commit/509d7e16d8f404a1cfd848703d46e5d9535d4802 after https://github.com/arvidn/libtorrent/pull/6674 merge

**Comment by prasket** [comment]
Thank you for the fix info, @arvidn any idea when the next official version will be pushed out? 

I am running Debian Testing and looking forward to the fixed version to be available to not see the messages when I open a new terminal :D  https://tracker.debian.org/pkg/libtorrent-rasterbar
