### ISSUE TITLE
HTTP tracker doesn't work with VPN interface

### ISSUE THREAD

**Issue by antoninblanc** [arvidn/libtorrent#6717]
libtorrent version : 2.0.5
qbittorrent version : 4.4.0

platform/architecture: amd64
compiler and compiler version: gcc 11.2

When I setup qbittorrent to use the client VPN interface (tun0), I can't connect to any http tracker. 

I'm puzzled because 
 - UDP tracker works
 - DHT works
 - TCP download works

So it seams the issue is just with http tracker.... I gave a quick look at the source code of `http_connection.cpp`. it effectively called `async_connect` but this end up to `on_connect` with this error code "system:125" (str). I assume it is boost error_code::operation_canceled.

With tcpdump, I didn't see any TCP packet going through tun0 interface, so I guess it doesn't even try to connect.

Any idea ? Anything I could do to troubleshoot this ?

Thanks !

**Comment by arvidn** [comment]
Do you get any error messages in the log?

**Comment by antoninblanc** [comment]
Hi. The only error is on qBittorrent himself, showing tracker connect timeout.

Nothing in log, it even correctly detected my external IP from VPN. 

```
(I) 2022-02-08T07:40:19 - PeX support [OFF]
(I) 2022-02-08T07:40:19 - Anonymous mode [OFF]
(I) 2022-02-08T07:40:19 - Encryption support [ON]
(I) 2022-02-08T07:40:19 - IP geolocation database loaded. Type: DBIP-Country-Lite. Build time: Tue Feb 1 09:11:03 2022.
(N) 2022-02-08T07:40:19 - Using built-in Web UI.
(N) 2022-02-08T07:40:19 - Web UI translation for selected locale (en) has been successfully loaded.
(N) 2022-02-08T07:40:19 - Web UI: Now listening on IP: *, port: 8080
(I) 2022-02-08T07:40:19 - Successfully listening on IP: 172.0.0.10, port: TCP/50100
(I) 2022-02-08T07:40:19 - Successfully listening on IP: 172.0.0.10, port: UTP/50100
.... (some stuff related to added torrents files) ...
(I) 2022-02-08T07:40:19 - Detected external IP: xxx.xxx.xxx.xxx
```
Good news tho, I fixed my problem. 

As I don't want to forward all traffic to my VPN, i didn't change the default route. I just got the local VPN network routes pushed by OpenVPN himself. It seams not enough to forward external traffic. I added a custom rt_table for openvpn interface.

```
ip rule add from 172.0.0.10 table openvpn
ip route add default via 172.0.0.1 dev tun0 table openvpn
```

Now everything works perfectly.

Issue can be closed, nothing related to libtorrent.
