### ISSUE TITLE
Unable to compile current libtorrent master

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#672]
libtorrent master (f856b6bbe379167fa1e11d973a79b6969130ee9d)
Windows 10 64-bit
GNU GCC 4.9.2 (MinGW) 32-bit

```
libtorrent\src\session_impl.cpp:441: error: no matching function for call to 'libtorrent::udp_socket::udp_socket()'
```

**Comment by arvidn** [comment]
yeah, I just merged a branch that fixes that. I'm not sure how that made it in there :/ (or why it worked on clang)
