### ISSUE TITLE
How to use typing stubs?

### ISSUE THREAD

**Issue by gazpachoking** [arvidn/libtorrent#6730]
**Please provide the following information**

libtorrent version (or branch): 2.0.5

platform/architecture: Windows

compiler and compiler version: pypi installed wheel

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I'm trying to figure out how the python typing stubs work, and it doesn't seem like it's working to me. I have libtorrent 2.0.5 installed from pypi, and pycharm doesn't even recognize that it's installed, let alone the contents. Just trying to figure if this is supposed to work, or if I need to obtain the stubs separately. Hoping to enable mypy eventually, but it's a bit harder to even add type hints when autocomplete isn't working in pycharm. Any advice?

**Comment by arvidn** [comment]
I'll defer to @AllSeeingEyeTolledEweSew

**Comment by gazpachoking** [comment]
Oh wait, are those not even released yet? I see them in master branch, but not RC_2_0 branch. Are all the current releases from RC_2_0?

**Comment by Samfun75** [comment]
> Oh wait, are those not even released yet? I see them in master branch, but not RC_2_0 branch. Are all the current releases from RC_2_0?

2.0.5 wheels are built from RC_2_0 and 1.2.15 wheels are built from RC_1_2 if I'm not mistaken. You are right, master branch have a stub file and type hinting works on wheels built from it. try this [wheels](https://github.com/Samfun75/libtorrent/suites/5233704630/artifacts/161003420)

**Comment by AllSeeingEyeTolledEweSew** [comment]
The type stubs aren't backported yet, but it was next on my list. #6532

**Comment by Banou26** [comment]
@Samfun75 Could you update your fork with the latest 2.0.7 release please? I relied on your wheel to get autocompletion but it doesn't have new API 2.0.7 endpoints like `loadtorrent*()`
Or maybe if @AllSeeingEyeTolledEweSew could update the master branch with them that'd be great too
