### ISSUE TITLE
TypeError: No Python class registered for C++ class libtorrent::flags::bitfield_flag<unsigned char, libtorrent::connection_type_tag, void>

### ISSUE THREAD

**Issue by brausepulver** [arvidn/libtorrent#6731]
libtorrent version (or branch): 2.0.5

platform/architecture: Linux x86_64 5.4.109

compiler and compiler version: GCC 11.2.0

Where peer_info is a libtorrent.peer_info object:
```
>>> print(peer_info.connection_type)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: No Python class registered for C++ class libtorrent::flags::bitfield_flag<unsigned char, libtorrent::connection_type_tag, void>
```

Python version is 3.9.9. The issue is also present in libtorrent version 2.0.4, but not in 1.2.15.

**Comment by arvidn** [comment]
thanks for the report! Here's a fix: https://github.com/arvidn/libtorrent/pull/6758

**Comment by brausepulver** [comment]
Thank you
