### ISSUE TITLE
Completion moving - "defragmentation"

### ISSUE THREAD

**Issue by cheater** [arvidn/libtorrent#6734]
Files being downloaded in random order creates pathological file systems that have very long extent chains or weird file system trees. This also happens if a file is downloaded in-order, but this is also in parallel happening to thousands of other files. This increases access times and lowers file system speed. For example, some pathological file systems can go down to less than 1 MB/s read speed on certain files. This even becomes an issue on solid state drives.

One way to go around this issue is to use a scratch disk and then upon completion move files to a destination disk. Statistically you won't have a lot of torrents completing at the same time, and so files will have very large chunks written to the file system contiguously, not creating a pathological file system. However, this is not possible if the temporary and destination directories are on the same file system, because eg you only have one partition; or when there is no temp directory set. The benefit is only clear to the most advanced users, as it is not stated anywhere in clients, so many will not know to have a setup like that. Also the issue remains of files that are still in the temp directory.

Another way is to pre-allocate files. However, if you have a bunch of files that have slow swarm speeds, what will often happen is the file will sit at say 20% for weeks and then suddenly a complete seeder shows up and lets you complete the file in minutes or a couple hours. This means that all this time you would have disk space tied up. Without pre-allocating files it is possible to have much more data downloading (in terms of ultimate disk size) than you actually have on your temp disk, and it's a pretty important thing when downloading rarely seeded torrents.

These issues are compounded as disk defragmentation is currently being shunned upon due to it shortening SSD life expectancy, which is especially important on budget drives. Some modern FSes don't even have outright disk defrag tools. In the ideal world, file systems would take care of this themselves. However, FSes are simply not built for this sort of random writing and when it happens over an extended period of time, their heuristics for how to allocate and physically lay out files just aren't prepared for that.

I would like to propose the following.

1. When moving files, have a flag you can set to have the files be recreated, whether sparsely or not, so that whatever blocks they do have can be put in a contiguous chunk on the drive or a simplified extent chain or tree in the file system. A sort of file-level disk defragmentation upon completion. This can be exposed in the UI.

2. Have an option to do the following. While still downloading files, before they are moved, periodically re-create files at certain completion points, eg every time 1GB of a file is downloaded, or every 1 week, whichever comes first. The user would be able to use their knowledge of whether their disk drive can handle the additional write load (if it's a HDD or a higher end SSD). Ideally a warning would be produced if the temp directory is on an SSD.

**Comment by Seeker2** [comment]
I use a multi-GB sized ramdrive as the scratch drive. It risks data loss from a sudden power outage, but a battery backup reduces that risk immensely.
I generally download small (<400 MB) sized torrents, but often do 3-10 at a time so fragmentation otherwise would be a big problem.
Largest ramdrive size I've used with BitTorrent downloading is 8 GB...as this PC only has 12 GB of ram.

**Comment by AllSeeingEyeTolledEweSew** [comment]
FWIW, I've found btrfs' `autodefrag` works really well for torrents, though I have more experience using it with transmission than with libtorrent. Its defrag tool also works online. So I challenge the claims that filesystems "simply aren't built for this", or that defragmentation is "being shunned".

The features OP describes could also be implemented with scripts.

**Comment by cheater** [comment]
I don't wish to start a fight or anything, let me just say that I will not be using btrfs

**Comment by arvidn** [comment]
option (1) shouldn't be too difficult.

I imagine you could have a job run on all torrent completions that defrag the files for that torrent. e.g. `sudo e4defrag <torrent-path>`.

**Comment by arvidn** [comment]
something like this. It doesn't quite seem to work yet though: https://github.com/arvidn/libtorrent/pull/6905

**Comment by cheater** [comment]
@arvidn glad you're working on this, thank you! Would you mind also working on a flag that controls the sparsity of the target file? With the options: sparse/fully pre-allocated/don't care (last one is the default if no flags are passed)

This will remove the ambiguity of whether a move creates a sparse or pre-allocated file, which is an issue in this and a related bug I posted, #6725.

I guess this is a similar enough area of code that you might be able to do this without a lot of ramp-up time.

**Comment by arvidn** [comment]
libtorrent doesn't copy sparse regions still. so if the source file is sparse, the destination file will also be sparse. This can potentially save a lot of time

**Comment by cheater** [comment]
In addition, files with a lot of 0s in them could be made sparse, skipping those...

**Comment by arvidn** [comment]
> Sure, but it's not guaranteed anywhere.

you mean older version of libtorrent still copies sparse regions?
the latest version of libtorrent is guaranteed not to copy sparse regions.

> In addition, files with a lot of 0s in them could be made sparse, skipping those...

I don't understand what your point is with this.

> This will remove the ambiguity of whether a move creates a sparse or pre-allocated file

I don't see how it's possible to remove the ambiguity in general. Not all filesystems support sparse files, so it could be unambiguous for a specific filesystem. But that's already the case.

**Comment by cheater** [comment]
No, I'm saying "not guaranteed" as in that there is no guarantee for that anywhere in the documentation or the code.

The ambiguity could be resolved by saying: if the target file system allows a file to be sparse, and the source file is sparse, then the target file will be sparse. But this needs to be said "officially" in the code and docs, not speculated on in a bug tracker :)

**Comment by cheater** [comment]
(didn't mean to close, sorry!)

**Comment by AllSeeingEyeTolledEweSew** [comment]
I assume arvid's idea of sparse regions is the regions that have been downloaded, and I think @cheater's idea is regions of the file with nonzero data (i.e. like `--sparse=auto` from GNU `cp`).

Personally I don't think it's right to add to libtorrent's huge feature surface for stuff that could be accomplished with scripts. There's no upper bound to the number of ways to copy a file (see `man rsync`).

**Comment by cheater** [comment]
That's not so easy. libtorrent already exposes the functionality of moving, it just needs to be specified what it does - if there's no guarantee it's kind of "useless". in practicality it's useful, but fragile, and a possible source of bugs if someone at some point forgets something when modifying it. but it's definitely necessary functionality especially for clients with smaller, simpler code base.

**Comment by cheater** [comment]
this is still required

**Comment by arvidn** [comment]
I'm leaning towards agreeing with @AllSeeingEyeTolledEweSew . There needs to be some limit of scope of features in libtorrent (which already is very large, perhaps a bit too large).

I believe this could be solved by using a defragmentation tool once a file completes downloading, alternatively a custom storage that takes care of downloading to a temporary drive and moves large contiguous chunks over to a final destination as it downloads.

Btw, "sparse region" means the parts of a file that aren't allocated on disk, but implicitly zeroes. Also known as "holes". What I meant by "copying sparse regions" was to preserve those regions as sparse/holes in the copy. The new copy function in 2.0.7 does this. This is especially helpful when copying a partially downloaded file over the network, or some other low-bandwidth storage.

**Comment by cheater** [comment]
The problem is that any such tool will not know which files need to get defragmented, whereas libtorrent does know that. Scanning a 50TB file system for files that need to be defragmented every time a 1 GB file is finished is a bad design.

**Comment by arvidn** [comment]
presumably the tool would only be asked to defragment the file that just completed downloading, which is knowable outside of libtorrent. There's even an alert when a file completes.

**Comment by cheater** [comment]
Are you talking about the option "run external program on download completion"?

**Comment by arvidn** [comment]
> Are you talking about the option "run external program on download completion"?

not specifically. I'm talking about the option of running a program on receiving the `file_completed_alert`

**Comment by cheater** [comment]
@arvidn sorry, what's an "alert" in this situation?

**Comment by cheater** [comment]
oh, i see, and in the actual torrent client it's going to be used for running the download completion program.

**Comment by cheater** [comment]
This still needs to happen.

I think the conversation got sidetracked into talking about sparse files. However, even non-sparse files can be spread across many, many inodes when they are downloaded over a long period of time, or if you're downloading a lot of files at the same time. This situation is easily reached by normal users. Fixing it should not require hacking together external scripts etc that only few people know how to do.
