### ISSUE TITLE
lt::create_torrent::set_hash2 write file piece hash out-of-range

### ISSUE THREAD

**Issue by stdjs** [arvidn/libtorrent#6740]
**Please provide the following information**

libtorrent version (or branch): 2.0.5

platform/architecture: opensuse x86-64

compiler and compiler version: gcc11

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

```
void create_torrent::set_hash2(file_index_t file, piece_index_t::diff_type piece, sha256_hash const& h)
{
  ..............................
  ............
  //If the file size is 0, file_num_pieces will return 0
  auto& fh = m_file_piece_hash[file];
  if (fh.empty())
	  fh.resize(std::size_t(m_files.file_num_pieces(file)));   //fh still empty,because m_files.file_num_pieces(file) is 0
  
  //piece value is 0 and fh.size is 0,cause invalid write
  fh[piece] = h; 


  //fix this, should do a check
  if(!fh.empty()){
      fh[piece] = h;
  }
  //or
  if(piece < fh.size()){
      fh[piece] = h;
  }

}
````

this only happens when v2 torrent contains an empty file

**Comment by arvidn** [comment]
I think it's a prerequisite to `set_hash2()` that the file referred to by `file` has a size greater than 0. Is there some other part of libtorrent that makes this call for empty files?

**Comment by arvidn** [comment]
I believe this fixes the issue: https://github.com/arvidn/libtorrent/pull/6754
