### ISSUE TITLE
Why is the url-list not in the info section?

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6741]
@arvidn Why is the url-list not in the info section?
These are direct links to download the file. If they won't be in the info section, how will it be distributed via DHT? ???

**Comment by arvidn** [comment]
because they don't describe the content of the torrent. URLs come and go, but the content stays the same.
I presume by "distributed via DHT" you mean via the `ut_metadata` extensions. They aren't.

**Comment by an0n666** [comment]
I think it's not in the info section because otherwise you won't be able to add or remove urls from torrent without changing the hash.

**Comment by master255** [comment]
@arvidn Now when I moved the url-list to the info section in the editable torrents I can convert any https link to a torrent magnet link. 
But such torrents will be downloaded only in Media Library because evil Arvin refuses to parse magnet links and try to read url-list from info section.

**Comment by arvidn** [comment]
dude...
