### ISSUE TITLE
macOS - static assertion failed: Handler buffer not large enough, please increase it.

### ISSUE THREAD

**Issue by xavier2k6** [arvidn/libtorrent#6743]
**Please provide the following information**

libtorrent version (or branch): **2.0.5**

platform/architecture: **macOS**

compiler and compiler version: **AppleClang 13.0.0.13000029**

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

qBittorrent CI - macOS

`-DCMAKE_BUILD_TYPE=RelWithDebInfo`

Reference: https://github.com/qbittorrent/qBittorrent/actions/runs/1869793562
____

`Boost` dependency was updated to `1.78` by `Homebrew` & is failing on `2.0.5` with below:

`/Users/runner/work/qBittorrent/qBittorrent/libtorrent/include/libtorrent/aux_/allocating_handler.hpp:180:3: error: static_assert failed due to requirement 'required_size<168>::value <= available_size<160>::value' "Handler buffer not large enough, please increase it"`

`/Users/runner/work/qBittorrent/qBittorrent/libtorrent/include/libtorrent/aux_/allocating_handler.hpp:202:7: note: in instantiation of template class 'libtorrent::aux::assert_message<libtorrent::aux::required_size<168>, libtorrent::aux::available_size<160>, libtorrent::aux::udp_handler>' requested here`

`/Users/runner/work/qBittorrent/qBittorrent/libtorrent/include/libtorrent/aux_/allocating_handler.hpp:180:3: error: static_assert failed due to requirement 'required_size<192>::value <= available_size<184>::value' "Handler buffer not large enough, please increase it"`

`/Users/runner/work/qBittorrent/qBittorrent/libtorrent/include/libtorrent/aux_/allocating_handler.hpp:202:7: note: in instantiation of template class 'libtorrent::aux::assert_message<libtorrent::aux::required_size<192>, libtorrent::aux::available_size<184>, libtorrent::aux::utp_handler>' requested here`

`/Users/runner/work/qBittorrent/qBittorrent/libtorrent/include/libtorrent/aux_/allocating_handler.hpp:180:3: error: static_assert failed due to requirement 'required_size<136>::value <= available_size<128>::value' "Handler buffer not large enough, please increase it"`

`/Users/runner/work/qBittorrent/qBittorrent/libtorrent/include/libtorrent/aux_/allocating_handler.hpp:202:7: note: in instantiation of template class 'libtorrent::aux::assert_message<libtorrent::aux::required_size<136>, libtorrent::aux::available_size<128>, libtorrent::aux::tick_handler>' requested here`

**Comment by wrtorrent** [comment]
same issue
https://github.com/arvidn/libtorrent/issues/6589

**Comment by xavier2k6** [comment]
My bad, I thought these were only updated previously for Debian/Windows....(I see now that they are Universal)

It's not an issue with latest RC_2_0 commit.

Closing as PEBKAC
