### ISSUE TITLE
Please add a new torrent_status for torrents that finished downloading but some job is still pending

### ISSUE THREAD

**Issue by summerqB** [arvidn/libtorrent#6745]
**Please provide the following information**

libtorrent version (or branch):
RC2_0
platform/architecture:

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Sometimes torrents finish downloading on a fast connection but some other job is pending like pieces being flushed to disk or maybe pieces being validated. When that happens these torrents are still in downloading state which is wrong!
I once got a torrent stalled at 100% completion in qBt and then when I look at piece count I see the count increasing every second and when all pieces are there the torrent finishes and changes status.
We need a new status that would represent this transition period so users are not confused about what's going on. They may think it's a bug and create more problem by maybe force rechecking the torrent or exiting the client.

**Comment by wrtorrent** [comment]
qbittorrent uses Qt
```
    const auto progressString = [](qreal progress) -> QString
    {
        progress *= 100;
        return (static_cast<int>(progress) == 100)
                ? QString::fromLatin1("100%")
                : Utils::String::fromDouble(progress, 1) + '%';
    };
```
then, according to
https://forum.qt.io/topic/24899/solved-round-double/16
QString::number("52.48", 'f', 1); return: "52.5"
same for 99.999 will return 100 due rounding.

most likely qbittorrent has to fix it's code
