### ISSUE TITLE
Anonymous mode is incompatible with some public trackers

### ISSUE THREAD

**Issue by vodzl** [arvidn/libtorrent#6748]
libtorrent version (or branch):
both 1.2 and 2
platform/architecture:
qBittorrent 4.x.x
compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I have reported this issue at QBT but was advised to report it here.
When Anonymous Mode is enable QBT is incompatible with some
public trackers - I get 'Forbidden' message in tracker status column.
When i disable anonymous mode and click force announce - trackers work like it supposed to.
Current examples:
http:// bt3.t-ru.org /ann?magnet
https:// tracker.lilithraws.org:443 /announce

I would like to have anonymous mode automatically disabled for a tracker/torrent if it is not supported by a tracker.

![amodedisabled](https://user-images.githubusercontent.com/48808824/155210350-484982b9-e1c3-4ba9-8662-1149f66f6d40.jpg)
![amodeenabled](https://user-images.githubusercontent.com/48808824/155210352-8a6b504b-5348-44b8-b70e-3820ecb1d524.jpg)

**Comment by arvidn** [comment]
does anyone know what it is that's causing the trackers to fail with a `Forbidden` response?

**Comment by an0n666** [comment]
> does anyone know what it is that's causing the trackers to fail with a `Forbidden` response?

I think it's because you send an invalid user agent header.

**Comment by an0n666** [comment]
Why not just send something like `Anonymous client` in the user agent.

**Comment by arvidn** [comment]
I see. The idea behind not sending a user agent at all is that whatever I send can be used for fingerprinting, even not sending anything at all. Perhaps I could send an empty string.

**Comment by arvidn** [comment]
is it possible those trackers respond with `Forbidden` for any request from an unknown user agent?

**Comment by arvidn** [comment]
does this patch fix it? https://github.com/arvidn/libtorrent/pull/6759

**Comment by an0n666** [comment]
No it doesn't. I tested with this branch.

However, I'll give you more details.

I tried with an empty user agent with curl 
`curl --user-agent "" https://tracker.lilithraws.org/announce`
The tracker replied with message error code: 1020. Looks like its a message that Cloudflare sends when it's firewall blocks someone.

So your empty user agent string is being detected as malicious and blocked by CF.

I also tried with `curl --user-agent "qBittorrent/4.4.1" https://tracker.lilithraws.org/announce` and it worked fine.
The reply was `d14:failure reason31:no info_hash parameter supplied`

Also tried with user agent set to "Anonymous" and that worked too! However it failed it "test". So I think they may have a set of banned list as well.

**Comment by arvidn** [comment]
thanks! I updated the patch.

**Comment by an0n666** [comment]
Yeah it's working now.

**Comment by an0n666** [comment]
@arvidn please update the documentation as well regarding anonymous mode.
I think these lines are invalid 
`Trackers will only be used if they are using a proxy server.`
`The user-agent will be reset to an empty string (except for private torrents)`

**Comment by paxter** [comment]
With enabled anymous mode the client sends `port=1`. Maybe the affected trackers just block that port number?

**Comment by arvidn** [comment]
> Trackers will only be used if they are using a proxy server.

That sounds like some left-over from the old `force_proxy` mode. I'll have to investigate a bit.
