### ISSUE TITLE
How to get packets downloading

### ISSUE THREAD

**Issue by AtmegaBuzz** [arvidn/libtorrent#6751]
Question.
using Python 3
I want to fetch packets of the video file downloading and feed it into a video player.
but i can't find anything or function which can give me the received packets.

my code : 
session = libtorrent.session()
session.listen_on(6881,6892)
params = {
        'save_path':os.path.join(os.getcwd(),'downloads'),
        'storage_mode':libtorrent.storage_mode_t(2),
    }

handler = libtorrent.add_magnet_uri(session,link,params)
session.start_dht()

**Comment by wrtorrent** [comment]
piece_finished_alert, see alert_types.hpp

**Comment by AtmegaBuzz** [comment]
this doesn't answer my question. I want the video packets of the downloading video so i can stream it.

**Comment by jagannatharjun** [comment]
you can make an HTTP file server. The media player will request you the needed packet in the form of an HTTP range request. Use TorrentInfo::map_file to get the required piece corresponding to that range request, use Torrent::read_piece and forward the read bytes to the request. An implementation would be https://github.com/jagannatharjun/qBittorrent/blob/stream-2021/src/base/streaming/streamingmanager.cpp

There is a libtorrent example also somewhere for this. There is also a Deluge plugin which implements the same idea in python

**Comment by arvidn** [comment]
you can use [read_piece](http://libtorrent.org/reference-Torrent_Handle.html#read-piece). to receive the bytes of the specified piece. If you haven't downloaded the piece yet, you can use [set_piece_deadline()](http://libtorrent.org/reference-Torrent_Handle.html#clear-piece-deadlines-reset-piece-deadline-set-piece-deadline), and specify the `alert_when_available` flag. That flag will post a `read_piece_alert` once the piece is downloaded.
