### ISSUE TITLE
torrenting to network drive broken

### ISSUE THREAD

**Issue by janekos** [arvidn/libtorrent#6752]
libtorrent version (or branch): RC_2_0 (i think)
platform/architecture: win 10 x64
compiler and compiler version: whatever qbittorrent team is using

im experiencing this issue through qbittorrent client. i started an issue there https://github.com/qbittorrent/qBittorrent/issues/16525 and they told me to come here.
long story short after qbittorrent 4.4.0 torrenting to my network drive is not working. what happens is folder is created and 30% of files are downloaded and then qbittorent says its done. other 70% are left as 0kb files. to fix this i have to force recheck like 10-20 times until all of the files are fully downloaded.

this issue was not present in qbittorrent versions earlier than 6 january 2022. im guessing they used whatever came before RC_2_0 and then there was no issue.

i was asked to check io after pausing completed torrent but that didn't reveal much of anything. one qbittorrent contributor suggested that these symptoms point towards some upstream issue in libtorrent RC_2_0, which is why im here. check referenced issue above for more info.

to reproduce it try torrenting something to some smb network share. not sure if/how that is doable with a library (i think this is a library)

hopefully this issue is not too out of place here 🤷‍♂️

**Comment by arvidn** [comment]
I believe this was fixed here: https://github.com/arvidn/libtorrent/pull/6718

**Comment by janekos** [comment]
doesnt this pull request only handle missing directory handling in windows network drives? in my case i have no issues with directories but instead the files are created but are not filled with data.
but is this fix only in latest version 2.0.5 (judging by the releases) of libtorrent? because looking at qbittorrent cmake files it looks like they use 2.0.4 but im not certain

**Comment by janekos** [comment]
@an0n666 just tried with different torrents and directory path depths in network drive (just in case). seems to be working correctly. no broken files
looks like qbittorrent just needs to use latest libtorrent code.
i'll close issue in this repo then. thanks @arvidn and @an0n666
