### ISSUE TITLE
Url seeds are not saved in write_resume_data

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6765]
@arvidn I noticed that from time to time when I start and stop the torrent when I execute torrentHandle.get_url_seeds().size() I get 0 and sometimes 1 (the correct value). Because of this, when I save state with write_resume_data url-list is not saved to cache. Then when I restore addtorrentParams from the cache and even put torrentInfo in it, the download does not start from url seed.
After that, torrentHandle returns 0 url seeds and torrentInfo returns 1 url seed.

I found that this function is called in too many places. This is probably the problem https://github.com/arvidn/libtorrent/blob/1b25eb5584db5f335167e6f8beda1ae280f28445/src/torrent.cpp#L5843

And even if I execute this code, it doesn't work. Which I think is inadequate.
```
if (addTorrentParams.get_url_seeds().size()==0 && torrentInfo.web_seeds().size()>0){
                        string_vector stringVector = new string_vector();
                        web_seed_entry_vector entryVector = torrentInfo.web_seeds();
                        int size = (int) entryVector.size();
                        for (int i=0; i< size; i++)
                            stringVector.push_back(entryVector.get(i).getUrl());
                        addTorrentParams.set_url_seeds(stringVector);
                    }
```

This is my torrent file and its saved cache. After restoration I can't download any file, even from torrent peers.
[5.zip](https://github.com/arvidn/libtorrent/files/8185905/5.zip)

Ok. I was trying to download a file that no one is distributing.  The other files are downloading. There is probably a mechanism to get web seeds from torrentInfo.
I can't repeat and reproduce the bug yet. That is why I am temporarily closing the bug.

**Comment by arvidn** [comment]
it's possible the web seed was removed, and then saved as removed because of the web server responding with a 404 or some similar error
