### ISSUE TITLE
Is it necessary to call setVerified_pieces?

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6766]
@arvidn I need to re-download a downloaded but deleted file. I do it like this. I read the documentation, but I still don't understand if it is necessary to call setVerified_pieces? What will it change and what will it affect?

```
piece_index_bitfield pieceIndexBitfield = addTorrentParams.getHave_pieces();
                                long offset = storage.file_offset(torrentFile.getNumFile());
                                int pieceSize = info.piece_length();
                                int startPiece = (int) (offset / pieceSize);
                                int endPiece = (int) ((offset + storage.file_size(torrentFile.getNumFile())) / pieceSize);
                                for (int i = startPiece; i <= endPiece; i++)
                                    pieceIndexBitfield.clear_bit(i);
                                addTorrentParams.setHave_pieces(pieceIndexBitfield);
                                addTorrentParams.setVerified_pieces(pieceIndexBitfield);
```

**Comment by arvidn** [comment]
`setVerified_pieces` sounds like some wrapper around the `verified_pieces` vector. You can read about it here: https://libtorrent.org/reference-Add_Torrent.html#verified_pieces

I would expect you to mostly be interested in clearing bits from [have_pieces](https://libtorrent.org/reference-Add_Torrent.html#have_pieces).

**Comment by master255** [comment]
@arvidn If I regularly delete different files from the disk, of this torrent, is it probably better to use "addTorrentParams.setVerified_pieces(pieceIndexBitfield);"? If I don't use it, will the files (the whole torrent) be checked more often?

**Comment by arvidn** [comment]
did you read the documentation on `verified_pieces`? are you using `seed_mode`?

**Comment by master255** [comment]
@arvidn Of course. In the future the user can delete the torrent and add it from the cache in SEED_MODE. And it will have verified_pieces, which will be actual or not - I decide with this command. 
What will happen if verified_pieces are not relevant in SEED_MODE?

**Comment by arvidn** [comment]
> What will happen if verified_pieces are not relevant in SEED_MODE?

I don't know what you're asking. `verified_pieces` are *only* relevant in seed mode. What are you asking? What happens if "false is true"?

**Comment by master255** [comment]
@arvidn I used the wrong word.
What will happen if verified_pieces are not actual in SEED_MODE?

**Comment by arvidn** [comment]
the `verified_pieces` vector is ignore unless the torrent is in `seed_mode`

**Comment by master255** [comment]
@arvidn Do you read what I write? That's not the question I'm asking.

**Comment by arvidn** [comment]
> What will happen if verified_pieces are not actual in SEED_MODE?

torrents can be in `seed_mode`. a `std::vector<>` cannot be in seed_mode. so, what do you mean then?

**Comment by master255** [comment]
@arvidn If I add a torret with the SEED_MODE flag and incorrect verified_pieces, what happens if some peer tries to download an already verified piece but it is not available (Have_piece)?

**Comment by arvidn** [comment]
pieces that have their bit *set* in `verified_pieces` will be sent to peers without having their piece hashes checked first. So, there;s a possibility to send corrupt data and get banned (in case the data on disk is corrupt).
piece that have there bit *clear* in `verified_pieces` will have their hash checked before sending it to a peer, to ensure it's still correct.

i.e. `seed_mode` means "assume we have everything, and defer checking the hashes".

If a file doesn't exist, it doesn't matter whether the hash will be checked or not. It will fail either way. The torrent will stop with some I/O error.

**Comment by master255** [comment]
@arvidn Ok. So, to prevent users from being banned for sending corrupted data, it is necessary to clear the necessary verified_pieces.

**Comment by arvidn** [comment]
> So, to prevent users from being banned for sending corrupted data, it is needed to clear the necessary verified_pieces.

If you corrupt the data on disk, and you add the torrent in `seed_mode` (i.e. promises that it isn't corrupt), then yes. Every time you corrupt the data and add the torrent, you should make sure the files you corrupted don't have their bits set in the `verified_pieces` vector.

Although, if you know that you're corrupting data, you probably shouldn't add the torrent in `seed_mode` to begin with.
