### ISSUE TITLE
Exception when creating multifile torrent

### ISSUE THREAD

**Issue by keithrausch** [arvidn/libtorrent#6771]
**Please provide the following information**

libtorrent version (or branch): 
branch RC_2_0, commit 9c04d24504d5e447d95e14c9f9fc6417079dec6d 

platform/architecture:
Ubuntu 21.10 64bit

compiler and compiler version:
gcc 11.2.0 (compiled libtorrent with cmake and same gcc)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

**Having trouble adding multiple files to a single torrent**
 - when running with v2_only flags, `t.generate()` throws the error: "the v1 and v2 file metadata does not match" 
 - when running with v1_only flags, `t.generate()` does not throw an error, but the .torrent file cant be opened by Deluge

**Minimum reproducible code:**
```cpp
using namespace libtorrent;
file_storage fs;      

auto flags = lt::create_torrent::v2_only;

libtorrent::add_files(fs, "/home/username/Desktop/torrenty_stuff/aaa.txt", flags);
libtorrent::add_files(fs, "/home/username/Desktop/torrenty_stuff/bbb.txt", flags);

create_torrent t(fs, 0, flags);
t.set_creator("my_torrent");
// t.add_tracker("127.0.0.1"); // trackerless
t.add_node(std::make_pair("127.0.0.1", 6881)); // for trackerless torrent

// reads the files and calculates the hashes
set_piece_hashes(t, "/home/username/Desktop/torrenty_stuff");

auto entry = t.generate(); // THROWS ERROR IN v2_only mode
```
When in v1_only mode, the produced magnet link is 

> magnet:?xt=urn:btih:6550911cbafeee63afc08e855f9d8b09460d0387

and the contents of the .torrent file are:

> d10:created by10:my_torrent13:creation datei1646763252e4:infod5:filesld6:lengthi12e4:path0:ed6:lengthi113e4:path0:ee4:name7:bbb.txt12:piece lengthi16384e6:pieces20:�Tm?I���YՉ�_��dO�e5:nodesll9:127.0.0.1i6881eeee

**Comment by keithrausch** [comment]
I got some more time to throw at this recently. I retried with newer and older versions of libtorrent with no results. Does this process even seem correct to y'all or am I doing something blatantly wrong here? @arvidn

**Comment by arvidn** [comment]
multi-file torrents have a restriction that all files added to it must share a root directory. If you put `aaa.txt` and `bbb.txt` in the same directory, and call `add_files()` once on that directory, I believe it would work. unfortunately, this aspect of the API doesn't have great error messages.

**Comment by arvidn** [comment]
in debug mode, there should be a precondition-assertion failure. But maybe I should turn that into a run-time error instead. My assumption was that the target audience for this error is developers, and they would run in debug mode.

**Comment by keithrausch** [comment]
As it turns out, the call to `set_piece_hashes()` requires the path to _just above the multi-file root_. In my case, that looks like this:

```cpp
        libtorrent::add_files(fs, "/home/keithrausch/Desktop/torrenty_stuff");
        create_torrent t(fs, piece_size, flags);

        set_piece_hashes(t, "/home/keithrausch/Desktop" );
```
this was shown in the example here https://github.com/arvidn/libtorrent/blob/beb9dbc3fedeabfa052289937c4533414fca775e/examples/make_torrent.cpp#L285

when creating a single file torrent, you can just use the same path, like so: `set_piece_hashes(t, "/home/keithrausch/Desktop/torrenty_stuff" );`

The torrent file and magnet links now generate without errors, and clients appear to connect, but they're unable to download the files. I'll post back if I figure out why. 

Thank you for your time

**Comment by nilskp** [comment]
@keithrausch 
I'm having the same issue right now, but in your original code you add individual files, and in your solution you're adding a directory. I need to add individual files, so your solution doesn't work for me.

**Comment by arvidn** [comment]
the directory structure inside the .torrent file is required to have a root directory. You're not required to use the same directory structure on disk when you create the torrent, but it adds a few additional steps to then seed the torrent. You need to rename the files (in libtorrent, in `add_torrent_params`) to point to the actual files on your disk. Anyone downloading the torrent will, by default, get the file structure in the .torrent file on disk. This is how the multi-file torrent format is designed.

There aren't really any utility functions to help you with this use case. You can't use `set_piece_hashes()`, you have to read and call `set_hash()` or `set_hash2()` (for v2 torrents) for each piece.

The simplest way of doing it is probably to reconstruct the .torrent file structure with symbolic links to the real file, and create the torrent from that directory.
