### ISSUE TITLE
Custom protocol?

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6773]
@arvidn **A request for a feature:** if we already have web-seeds that use the https protocol, why not add the ability to transfer data between peers using the https protocol? Of course, I'm not suggesting to abandon the torrent protocol, but to add a backup possibility to transfer data using https if the torrent protocol cannot be used.
This would help avoid blocking torrents in many countries. Use some expired, non-valid certificate as a certificate. The main thing is to have data encryption.

**And of course the question:** How can I add my own data transfer protocol using Java code in the Android application? Is it possible with plugins? In what direction should I look for answers?

Ok. I guess I can't do that in Java? Because I won't get events from Libtorrent. I have to redo Libtorrent?

**Comment by paxter** [comment]
I found this: https://ccextractor.org/public/gsoc/bittorrent-tls/

But nothing concrete and no BEP or something similiar. I'm with you. It's curious, that there is still no end to end encryption between peers in any of the bittorrent documents and specifications. Maybe there is a reason against it. I don't know.

**Comment by master255** [comment]
@paxter You don't understand what I'm writing about. I'm writing about the https protocol, not the torrent protocol. Https works on http requests. It will be very easy to build this into Libtorrent - for someone who wrote the library.
I am not talking about encryption of torrent protocol, but about completely different protocol. Libtorrent now has an https client. Now if we add an https server, it will improve all the processes.

**Comment by paxter** [comment]
Sorry, my fault.

**Comment by arvidn** [comment]
@master255 if your objective is to not look like bittorrent traffic, it doesn't really matter what protocol you speak under TLS, does it?

**Comment by master255** [comment]
@arvidn Logical. Yes. But if we start encrypting the torrent protocol, we will have big compatibility problems.
To avoid this I propose to add backup https protocol, which the library will use only last, if bittorent protocol doesn't work.

**Comment by MassaRoddel** [comment]
Why not put the http server/client into your client without any libtorrent dependancies? You could get the peer's ip addresses from libtorrent.

**Comment by master255** [comment]
@MassaRoddel Yes. But I have a very complex streaming system that interacts with Libtorrent. And I need to verify the data I get. There is no way to make a web server separately. The web server has to be inside Libtorrent. I think it's so complicated that it's impossible to take it out of libtorrent.
The Https protocol is very different from the torrent protocol. Even the order of requests.

**Comment by master255** [comment]
@arvidn Since https has no bitfields of pieces and various other technologies such as PEX... it should only be used if the whole file is available. One https request. If the file is available, it will be transferred. If the file isn't available, it won't.
Of course the data received has to be verified, just like from a regular web-seed.

**Comment by AllSeeingEyeTolledEweSew** [comment]
:+1: for the idea of TLS to cloak bittorrent traffic from manipulation.

I think you'd be shooting yourself in the foot to do a libtorrent-specific hack. Only other libtorrent peers (of new enough version) would ever support the protocol. You'd be better off to develop a standard to maximize adoption, and thus maximize performance.

@master255 you could try running an http server in your app, then add peers as web seeds. Not sure how well it would work but you could do it without modifying libtorrent.

**Comment by master255** [comment]
@AllSeeingEyeTolledEweSew No. It won't work. How to save the torrent then? There may be a lot of web seeds. And webseeds are saved in my program in the info section and it will change the main hash.

**Comment by AllSeeingEyeTolledEweSew** [comment]
Use libtorrent to save the torrent, as normal. Use `torrent_handle::add_url_seed()` to modify a live torrent. You don't need to modify the info. This doesn't solve the problem of how to discover peers in the first place but I think you still weren't solving that anyway.

**Comment by wrtorrent** [comment]
Would be nice to be able to add custom (proto) downloads (or jobs) to list of libtorrent active torrents (to make multi-purpose downloader).

**Comment by master255** [comment]
@AllSeeingEyeTolledEweSew ok. I need to test it...

**Comment by master255** [comment]
@AllSeeingEyeTolledEweSew Why didn't I know this before? It really does work. I can even make my own torrents.

**Comment by master255** [comment]
> Would be nice to be able to add custom (proto) downloads (or jobs) to list of libtorrent active torrents (to make multi-purpose downloader).

I don't know what you mean. In torrents you can download many torrents at once.

**Comment by master255** [comment]
@arvidn 

> @master255 if your objective is to not look like bittorrent traffic, it doesn't really matter what protocol you speak under TLS, does it?

Don't you think about making a third torrent protocol over https?

**Comment by master255** [comment]
@paxter @arvidn @gubatron @aldenml @AllSeeingEyeTolledEweSew @wrtorrent @MassaRoddel 
Looks like I'm done implementing the https protocol in libtorrent!
Since version 10 of the Media Library this is supported (Coming out tomorrow). I think it's cool B-)
Suddenly https speed is faster than torrent :-)

[Read more](https://t.me/media_library/12364)
