### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by olegsavelos** [arvidn/libtorrent#6779]
libtorrent version (or branch): RC_2_0

platform/architecture: Windows 7 sp1 x64/x32

compiler and compiler version: msvc2017

I am researching a potential of adding my own custom data to the generated file, for example configuration related to the torrent deployment such as an default directory to deploy to and so. As I understand it should be possible to have custom key/value either in the info or the torrent root but I cant find a way to do this with libtorrent, is such functionality supported ?
Thanks!

**Comment by master255** [comment]
@olegsavelos It's very simple. It is enough to open the source code and see.

**Comment by arvidn** [comment]
@olegsavelos when you create the torrent, the `generate()` call returns the full (mutable) bencode tree. you can add new fields to the root or to the `"info"` dictionary, by using `operator[]`.
