### ISSUE TITLE
With libtorrent-rasterbar-2.0.5 the memory in qBittorrent goes up into hundreds of gigabytes on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [arvidn/libtorrent#6781]
libtorrent version (or branch): 2.0.5

platform/architecture: FreeBSD

compiler and compiler version: clang-12

This isn't a normal memory profile:
```
  PID USERNAME    THR PRI NICE   SIZE    RES STATE    C   TIME    WCPU COMMAND
29462 yuri         26  22    0   109G   167M select   7   0:06  11.46% qbittorrent
```

**Comment by wrtorrent** [comment]
Have similar issue
2.0.5 Win10 x64 no qBittorrent
cache_size=4096
while downloading 200GB torrent
.exe in Task Manager goes from 5MB idle to 1200MB (1.2GB) memory usage.

**Comment by EsEnZeT** [comment]
Downgrade to 4.3.9, latest libtorrent suck too much https://github.com/arvidn/libtorrent/issues/6667

**Comment by Sin2x** [comment]
No need to downgrade, there are 4.4.2 builds with 1.2: https://github.com/qbittorrent/qBittorrent/actions/runs/2036890690

**Comment by yurivict** [comment]
This shouldn't be closed.

**Comment by MartinVonReichenberg** [comment]
_A possible duplicate of: #6667_
