### ISSUE TITLE
How to test ssl torrent?

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6784]
@arvidn I have the ssl port open. 
I created a torrent based on root_ca_cert.pem (as in test_ssl.cpp)
I executed this on server and client (same files): handle.set_ssl_certificate(options.getCacheFolderPath()+"/peer_certificate.pem", options.getCacheFolderPath()+"/root_ca_private.pem",options.getCacheFolderPath()+"/dhparams.pem");

The download doesn't start. It says handshake ssl error.
What am I doing wrong???

**Comment by arvidn** [comment]
the root CA cert in the .torrent file needs to have signed the tracker's SSL connection handshake, also, each peer needs a certificate signed by (or indirectly by) that same root cert.

SSL torrents implement a private swarm, where only peers allowed by the central authority (that holds the root private key) can let peers join.

**Comment by master255** [comment]
@arvidn Thanks for replying. You did a great job!
I'll come back to this question later.
