### ISSUE TITLE
Code optimization?

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6786]
https://github.com/arvidn/libtorrent/blob/d102b9c70c487590aa691c05e8a80354f8a4cb99/src/bt_peer_connection.cpp#L2128

@arvidn How about optimizing calls to m_settings.get_str. This is still a costly procedure and this code is executed often. I think you should create a string variable for it?

**Comment by arvidn** [comment]
what's the expensive part? is your name long enough to trigger a heap allocation? surely that's cheap compared to everything else that happens when connecting to a peer.

**Comment by master255** [comment]
@arvidn Maybe this should be?:
```
string client_version = m_settings.get_str(settings_pack::handshake_client_version);
handshake["v"] = client_version.empty()
				? m_settings.get_str(settings_pack::user_agent)
				: client_version;
```

**Comment by master255** [comment]
@arvidn Arvin, this is first class :-D
