### ISSUE TITLE
PL Err 2 and SL Err 4

### ISSUE THREAD

**Issue by deminio** [arvidn/libtorrent#6787]
**Please provide the following information**

libtorrent version (or branch):2.0.5.0

platform/architecture: gentoo

compiler and compiler version:

I have these errors qBittorrent 4.4.2 in tracker status. PL Err 2 and SL Err 4. What these errors mean?

**Comment by arvidn** [comment]
@deminio can you provide some more context? how are those error messages delivered to you?
