### ISSUE TITLE
Build directly through pip?

### ISSUE THREAD

**Issue by th0ma7** [arvidn/libtorrent#6788]
**Please provide the following information**

libtorrent version (or branch): 2.0.5

platform/architecture: any

compiler and compiler version: gcc 7.5

I'm trying to build libtorrent from sources with boost.  I am wondering if it is possible to produce a wheel by calling `pip` directly with options?  My current code runs quite far but eventually fails and this seems to be due to trying to build in static instead of shared mode.  Wonder how I can pass arguments through p2p to fix that?

Ref: https://github.com/SynoCommunity/spksrc/pull/5180

**Comment by th0ma7** [comment]
@userdocs I was able to get the build to work out on 64-bit archs using master in crossenv using pip.  Although it fails on all 32-bit archs and my guess is `address-model` being set at `64` (not verified yet).  Is there any way for me to pass arguments to pip to enforce it to `32` ?

**Comment by userdocs** [comment]
Probably need this if you are using python to build it and not using b2 directly.

https://libtorrent.org/python_binding.html 

Something like this example I modified.

`python setup.py build_ext --b2-args="address-model=32" install`

**Comment by th0ma7** [comment]
I was finally able to get it to work.  Should I be using `master` or `RC_2_0` and any timeframe as of when 2.0.6 will get released?

**Comment by userdocs** [comment]
you would use `RC_2_0` not master. 

No idea on the timeframe but you can either patch 2.0.5 whilst it the current release or use  `RC_2_0` as that is where all v2 releases are from.

Usually as the time for a new release comes you see the dev merging version changes into that relevant RC branches.

**Comment by th0ma7** [comment]
Thnx.  btw as I am closing this issue, note that the version in RC_2_0 is still 2.0.5 when building through pip.  I thought it would make sense for it to be bumped.  Thnx, cheers.

**Comment by th0ma7** [comment]
Thnx for your reply, in fact I actually implemented the `--no-use-pep517` and made a few other adjustments to our build framework and now all is good.

As for the `address-model` it was missing the `BOOST_BUILD_PATH` so it can find the `user-config.jam` file used to build `boost`.

As for the version I thought it would already be showing 2.0.6 or 2.1.0 (perhaps with an rc).  But that really is more estetic than anything.

My last remaining bug really is https://github.com/arvidn/libtorrent/issues/6792 and is a major blocker for multiple archs.
