### ISSUE TITLE
Support websocket trackers?

### ISSUE THREAD

**Issue by abcfy2** [arvidn/libtorrent#6789]
**Please provide the following information**

libtorrent version (or branch): v2_0_RC

platform/architecture: x86

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Some trackers list will contain websocket URL, E.g:

![Screenshot_20220329_165938](https://user-images.githubusercontent.com/5327677/160574853-ddcea00c-3545-4af5-8bce-960babe27064.png)

An example trackers list: https://trackerslist.com/all.txt

Would you please support websoket ?

**Comment by filecxx** [comment]
Sure.

**Comment by arvidn** [comment]
is there a specification for the websocket tracker protocol?

or are you referring to supporting WebTorrent? (if so, that's supported in libtorrent `master` branch)

**Comment by abcfy2** [comment]
Seems webtorrent uses `ws` or `wss` protocol: https://github.com/webtorrent/bittorrent-tracker

Did you support this protocol in `RC_2_0` branch?

Thanks.

**Comment by arvidn** [comment]
supporting WebTorrent is not just about supporting websocket trackers, it's a new protocol over Datachannel peer connections. Support for WebTorrent is in the `master` branch.
