### ISSUE TITLE
libtorrent-rasterbar error using pipenv due to non-compliance with pep440

### ISSUE THREAD

**Issue by jdix531** [arvidn/libtorrent#6791]
**Please provide the following information**

libtorrent version (or branch):
2.0.5

platform/architecture:
x86/64

compiler and compiler version:
n/a

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Hi, my issue was something I was able to find here:
https://forum.manjaro.org/t/libtorrent-rasterbar-pkgresourcesdeprecationwarning/100904

The crux of it is that when using pipenv for any cause (even 'pipenv --version' throws it) on a system with this installed there's ~~an error~~ a warning that looks like below due to non-compliance with pep440:

```bash
PkgResourcesDeprecationWarning: 2.0.5-build-libtorrent-rasterbar-src-libtorrent-rasterbar-2.0.5-bindings-python is an invalid version and will not be supported in a future release
```

I'm not 100% I'm correct on this, but trying my best here!

**Comment by AllSeeingEyeTolledEweSew** [comment]
See #6674
