### ISSUE TITLE
Important issue related to a wrong call of async_release_files

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#68]
Hi @arvidn, we are getting a lot of errors like this (using master):
```
backtrace:
#00  (libtorrent::disk_io_thread::async_release_files(libtorrent::piece_manager*, boost::function<void (libtorrent::disk_io_job const*)> const&)+19)
#01  (libtorrent::torrent::finished()+442)
#02  (libtorrent::torrent::prioritize_pieces(std::vector<int, std::allocator<int> > const&)+240)
#03 (libtorrent::torrent::update_piece_priorities()+294)
#04 (libtorrent::torrent::read_resume_data(libtorrent::bdecode_node const&)+3050)
#05  (libtorrent::torrent::init()+3938)
#06 (libtorrent::torrent::start(libtorrent::add_torrent_params const&)+860)
#07 (libtorrent::aux::session_impl::add_torrent_impl(libtorrent::add_torrent_params const&, boost::system::error_code&)+1242)
```

I think that something happened in this commit: https://github.com/arvidn/libtorrent/commit/105c105867cd2d341dbe2901fd10eec64bad6c41#diff-19929347e18a6ff1fc37f09ec720306bL6762

that triggers a call to async_release_files with null.

What do you think?

Thanks

CC @gubatron

**Comment by arvidn** [comment]
what's the error?

**Comment by aldenml** [comment]
Here it is
```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000004
```

**Comment by arvidn** [comment]
does the error happen consistently for a given resume file and torrent? if so, do you have a pair I could have a look at?

**Comment by aldenml** [comment]
No, it happens in avery small fraction of our stage rollout, but enough to be worried. I myself can not replicate it. To me, this is a typical null pointer error associated to an edge case, but I'm not clear in the states at this point.

I'm not a fan of hiding errors, but do you think a valid pointer check is in order before calling async_release_files? And if so, why?

**Comment by arvidn** [comment]
it looks like this could be caused by loading a torrent with resume data where all file priorities are set to zero

**Comment by aldenml** [comment]
And that is something I need to take care of? or it's something that must be handled by libtorrent?

**Comment by arvidn** [comment]
I have a test that reproduces this now. But I have to go to bed. I'll have a fix tomorrow night

**Comment by aldenml** [comment]
Let me know if I can help. Thank you.

**Comment by arvidn** [comment]
fixed here: https://github.com/arvidn/libtorrent/commit/fb3460731323b05ba7aafc920da1307791945ac3

**Comment by aldenml** [comment]
Thank you. I will build with this fix and see how it goes.
