### ISSUE TITLE
‘class libtorrent::dh_key_exchange’ has no member named

### ISSUE THREAD

**Issue by qilinbar** [arvidn/libtorrent#6803]
**Please provide the following information**

libtorrent version (or branch):rc2.0

platform/architecture:x64

compiler and compiler version:rc2.05

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
common.copy /usr/local/lib/pkgconfig/libtorrent-rasterbar.pc
gcc.compile.c++ bin/gcc-9/debug/cxxstd-14-iso/threading-multi/visibility-hidden/src/bt_peer_connection.o
src/bt_peer_connection.cpp: In member function ‘void libtorrent::bt_peer_connection::write_pe1_2_dhkey()’:
src/bt_peer_connection.cpp:530:49: error: ‘class libtorrent::dh_key_exchange’ has no member named ‘good’
  530 |   if (!m_dh_key_exchange || !m_dh_key_exchange->good())
      |                                                 ^~~~
src/bt_peer_connection.cpp: In member function ‘void libtorrent::bt_peer_connection::on_receive_impl(std::size_t)’:
src/bt_peer_connection.cpp:3142:25: error: ‘init_bt_handshake’ is not a member of ‘libtorrent::bt_peer_connection::state_t’
 3142 |      m_state = state_t::init_bt_handshake;
      |                         ^~~~~~~~~~~~~~~~~
src/bt_peer_connection.cpp:3185:25: error: ‘init_bt_handshake’ is not a member of ‘libtorrent::bt_peer_connection::state_t’
 3185 |      m_state = state_t::init_bt_handshake;
      |                         ^~~~~~~~~~~~~~~~~
src/bt_peer_connection.cpp:3202:24: error: ‘init_bt_handshake’ is not a member of ‘libtorrent::bt_peer_connection::state_t’
 3202 |     m_state = state_t::init_bt_handshake;
      |                        ^~~~~~~~~~~~~~~~~
src/bt_peer_connection.cpp:3236:27: error: ‘init_bt_handshake’ is not a member of ‘libtorrent::bt_peer_connection::state_t’

please ask me ?

**Comment by arvidn** [comment]
are you using a new version of the header and an old version of the cpp file? how are you building?
