### ISSUE TITLE
use std::get_if when possible instead of std::get

### ISSUE THREAD

**Issue by otristan** [arvidn/libtorrent#6808]
Hi,

std::get is only available on OSX 10.14
while std::get_if was available for older versions.

utp_socket_manager.cpp could maybe use this instead.

Thanks !

**Comment by arvidn** [comment]
I would welcome a patch to do this. It's only an issue in `master`, right?
one challenge is that a lot of places where `std::get` is used right now, we know the variant has the right type. Using `std::get_if` might imply that we expect it to sometimes return `nullptr`, but then unconditionally dereference the pointer. It might make for some more questionably looking code.

**Comment by otristan** [comment]
Actually there is the same issue with std:visit in bencode.hpp

error: 'visit<libtorrent::aux::bencode_visitor<std::__1::back_insert_iterator<std::__1::vector<char, std::__1::allocator<char> > > >, const std::__1::variant<long long, std::__1::basic_string<char>, std::__1::vector<libtorrent::entry, std::__1::allocator<libtorrent::entry> >, boost::container::map<std::__1::basic_string<char>, libtorrent::entry, libtorrent::aux::strview_less, void, void>, std::__1::vector<char, std::__1::allocator<char> >, libtorrent::entry_types::uninitialized_type> &>' is unavailable: introduced in macOS 10.14

Not sure there is a workaround for this one
