### ISSUE TITLE
Too low limit for bdecode_node header size

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#6809]
https://github.com/arvidn/libtorrent/blob/07a5305a95096ea76633c1b6a7943026608d2bb0/include/libtorrent/bdecode.hpp#L209

Current limit for header size of bdecode_node of string type is 10 which seems to be too low (maybe only since the era of BitTorrent v2).
Users began to complain that some previously added torrents could not be resumed when the qBittorrent was restarted. As it turned out, this affects torrents of large sizes (several tens of GB) and, apparently, only torrents of the second version.
Subsequently, I discovered that the stored "fastresume" data is also quite large (several tens or even hundreds of MB). More specifically, they contain a very long string with hashes, so its header may be longer than the above limit.

**Comment by arvidn** [comment]
I will make this a priority to fix. thanks for the report

**Comment by arvidn** [comment]
the string has to be 100 Megabytes or longer for this problem to arise. Is it the merkle tree for a large file that exceeds this?

**Comment by arvidn** [comment]
here's a fix: https://github.com/arvidn/libtorrent/pull/6817

**Comment by arvidn** [comment]
the fix has landed
