### ISSUE TITLE
How to download a torrent knowing the DHT Node Id?

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6819]
@arvidn  Now I learned how to get the DHT Node Id. Suppose I know the sha1 of the torrent and the sha1 node id of the peer from which I can download the torrent.
How can I find this peer and download the torrent?

**Comment by arvidn** [comment]
> Suppose I know the sha1 of the torrent and the sha1 node id of the peer from which I can download the torrent.

This questions suggests there is a misunderstanding. You don't download the torrent/metadata from the dht node. you're just introduced to other peers in the swarm. You can download the metadata from them.

> How can I find this peer and download the torrent?

Make sure you have joined the DHT network and add a torrent with the info-hash set in `add_torrent_params`

**Comment by master255** [comment]
@arvidn 

> This questions suggests there is a misunderstanding. 

This answer suggests that there is a misunderstanding.

Such a scenario:
I have 1 seeder, it distributes 1 torrent. But the problem is that this torrent changes very often.
So that it can be downloaded by clients seeder publishes sha1 of torrent file using put_dht.
Clients receive sha1 of torrent file with dht_get and try to download it.
But the problem is that it takes a long time to start downloading because there is only one seeder.

In order to speed up the download seeder is ready to provide any useful information. But what can he provide?
1. ip - address. But there are several of them and they can change regularly. This is not reliable.
2. the address of the tracker with which he distributes the content. But the tracker may be available from the sender, but blocked from the client. This is not reliable.
3. DHT Node id - it may not change even if ip address changes. It cannot be blocked. Perfect! But how can the client use this id?

Maybe I don't understand it correctly? How to solve this simple scenario?

**Comment by master255** [comment]
Ok. Perhaps I got mixed up in the experiments. I need to not use trackers so that the peer can be found in DHT.

**Comment by master255** [comment]
@arvidn No. I'm right, though.
I created a torrent on computer 1 with no trackers, with DHT publishing.
On computer 2 I added a torrent, only with sha1 (the one created by computer 1), a torrent.

Result: Computer 2 cannot download the torrent. Even if I do a torrentHandle.force_dht_announce(); on computer 1, it does not help.
And computer 2 gets results with the ip address of computer 1, but the port is not correct there. Is it possible in this case? DHT peers don't change their information if port is changed?

I add a peer manually and the downloading starts.

**Comment by arvidn** [comment]
is computer 1 accessible from the internet? i.e. will its listen port be announced correctly to the DHT?
it's possible computer 1 does not have its listen port forwarded, or that UPnP/NAT-PMP doesn't work. Then computer 2 won't be able to connect to it.

Are computer 1 and 2 on the same local network? If so, could the incorrect port you observe be explained by it being the other conputer's port?

**Comment by master255** [comment]
@arvidn Computer 1 and computer 2 are on different internet networks. From two different Internet Service Providers. Computer 1 has a white ip address, nat and exactly working upnp.

I already figured out what the problem is. This is a big bug in libtorrent.

I am using the 1.2.13 version of the library. Maybe newer versions have already fixed it?

I create a torrent with port 40000 and it automatically gets announced in DHT. Then I turn off the application and turn it on again. The torrent port changes to 40200. It restores the torrent, but the DHT announcement happens without specifying a new port. So DHT keeps information about my old port.
Result: After restarting the application nobody can download torrent, via DHT.

This can be solved either in the application:
torrentSession.dht_announce("infoHash", torrentSession.listen_port())
When restoring the torrent.
Or in library - when restoring check port from save and current port and make announce with port if they are different.

I think it's more logical to take the port from random only once, when starting the application. In the future, if the port will be changed by the user, then make an announcement specifying the port.
But how to keep track of this? What if the user changes the port today and restores the torrent from the cache tomorrow? It turns out that only library can do this.

@aldenml @gubatron @proninyaroslav But it is necessary urgently to remove random port from the programs. Random port is not compatible with DHT.

**Comment by arvidn** [comment]
> I create a torrent with port 40000 and it automatically gets announced in DHT. Then I turn off the application and turn it on again. The torrent port changes to 40200. It restores the torrent, but the DHT announcement happens without specifying a new port. So DHT keeps information about my old port. Result: After restarting the application nobody can download torrent, via DHT.

I don't believe this conclusion is correct. Do you have packet captures?
I think a more likely scenario is that your new port is updated on some DHT nodes, but not others. Your old port will hang around for a while on nodes that may no longer be responsible for the info-hash.
There's always some uncertainty in the DHT interactions, you may have time-outs causing some announcements to be incomplete. Over time it tends to correct itself though.

Can you reproduce this behavior reliably?

> This can be solved either in the application: torrentSession.dht_announce("infoHash", torrentSession.listen_port()) When restoring the torrent. Or in library - when restoring check port from save and current port and make announce with port if they are different.

`listen_port()` isn't necessarily the port you can be contacted via on your external IP though. That port is decided by your router's NAT.

I'm curious about what it is you think libtorrent does to update the DHT but not the port, or using the old port.
 
> I think it's more logical to take the port from random only once, when starting the application. In the future, if the port will be changed by the user, then make an announcement specifying the port. But how to keep track of this? What if the user changes the port today and restores the torrent from the cache tomorrow? It turns out that only library can do this.

I agree. If you listen on port 0 (i.e. let the OS decide), you should update your settings once a port has been picked and try to stick to it in future sessions.

> @aldenml @gubatron @proninyaroslav But it is necessary urgently to remove random port from the programs. Random port is not compatible with DHT.

I think this conclusion is also incorrect. Could you share your observations you base this on?

**Comment by master255** [comment]
@arvidn One command on the server instantly starts the download on the client:
torrentSession.dht_announce(torrentHandle.info_hash(), torrentSession.listen_port());

I don't think there's anything else to check. We need to fix this very big bug urgently!

**Comment by master255** [comment]
@arvidn 

> I don't believe this conclusion is correct.

I don't believe you all missed such a big bug.

**Comment by master255** [comment]
@arvidn Your DHT only works because sometimes the peers in the DHT change and data storage expires. But this is a very slow process.

**Comment by arvidn** [comment]
> In what situations will the NAT port be different?

For example when the port you're requesting is already taken on the router

**Comment by master255** [comment]
@arvidn I checked some more. When I change the port but don't make an announcement with the port specified, then the peer is searched in DHT much longer. I get a lot of other results back with the wrong ports. After I made an announcement with the port once - my torrent started to be found instantly.

**Comment by master255** [comment]
```
case DHT_BOOTSTRAP:
                                if (options.isTorrentPortChanged()) {
                                    options.setTorrentPortChanged(false);
                                    saveOptions();
                                    final torrent_handle_vector torrentHandleVector = torrentSession.get_torrents();
                                    final int sizeVector = (int) torrentHandleVector.size();
                                    final int port = torrentSession.listen_port();
                                    for (int r = 0; r < sizeVector; r++) {
                                        final torrent_handle torrentHandle = torrentHandleVector.get(r);
                                        if (torrentHandle.is_valid() && torrentHandle.status().getIs_seeding())
                                            torrentSession.dht_announce(torrentHandle.info_hash(), port, 1);
                                    }
                                    Log.d("httpPlayer", "Announce port change");
                                }
                                break;
```

Yes. This code cuts the start time of downloading from 3-10 minutes to a couple of seconds (using DHT only). Tested it several times.

**Comment by master255** [comment]
@arvidn 

> For example when the port you're requesting is already taken on the router

Maybe you're talking about the old specification? My router opens the same ports, even if they are busy. 
![image](https://user-images.githubusercontent.com/5380115/164103683-4c5b259b-57d9-46d4-924c-a2fa8030e543.png)
