### ISSUE TITLE
asio_disk_io?

### ISSUE THREAD

**Issue by mayli** [arvidn/libtorrent#6821]
**Please provide the following information**
It seems the network io stack is using boost::asio, is there any plan to use it on the storage io stack as well?
Since the asio has been improved to support file io, and [introduced io_uring support](https://www.boost.org/doc/libs/1_79_0/doc/html/boost_asio/history.html#boost_asio.history.asio_1_22_0___boost_1_78). It might be interesting to implement an alternative storage engine based on that.

libtorrent version (or branch):
2.x

**Comment by markmdscott** [comment]
#6208 used the xNVMe API (which uses io_uring as a backend option on Linux.)

**Comment by james58899** [comment]
Implement boost::asio based storage engine possible resolve #6667 #6612 #6561 #6522

POSIX fallback will blocking network thread, it significantly reduces download and upload speeds.
It would be nice if there were other non-blocking options besides mmap.
