### ISSUE TITLE
Ctest case failed (Built with boost 1.79)

### ISSUE THREAD

**Issue by gesangtome** [arvidn/libtorrent#6825]
libtorrent version (or branch): scm tag: 2.0.6

platform/architecture: CentOS Stream8  x86_64

compiler and compiler version: gcc version 8.5.0 20210514 (Red Hat 8.5.0-12) (GCC)

Ctest case failed, libtorrent built with the latest Boost-1.79.

A failure occurs when running the Ctest case, The error occurs in case 16,

The testing report:

[CTestCostData.txt](https://github.com/arvidn/libtorrent/files/8511950/CTestCostData.txt)
[LastTest.log](https://github.com/arvidn/libtorrent/files/8511951/LastTest.log)
[LastTestsFailed.log](https://github.com/arvidn/libtorrent/files/8511952/LastTestsFailed.log)

**Comment by diizzyy** [comment]
I'm seeing this issue too on FreeBSD 13.1-STABLE (amd64), Boost 1.72

**Comment by arvidn** [comment]
`test_create_torrent` is the failing test, right?
I can't get this to fail on MacOS or Ubuntu with the latest boost. But if it's failing on FreeBSD with boost-1.72, it's probably not related to boost.

**Comment by diizzyy** [comment]
Yes, that's correct

**Comment by gesangtome** [comment]
@arvidn 

You are right, it has nothing to do with BOOST, because I tested it again on Fedora and I got the same result.

➜ rb git:(test) ✗ rpm -qa | grep boost
boost-1.76.0-4.fc35.x86_64

**Comment by gesangtome** [comment]
@[diizzyy](https://github.com/diizzyy)
hey man, are you using old version RB case will it fail?

**Comment by arvidn** [comment]
I tried the older version of GCC on Ubuntu as well, without reproducing the failure. Is musl a common feature between the systems where this fails?

**Comment by diizzyy** [comment]
FreeBSD uses llvm/clang 13 and libc++
If you want some pointers as far as FreeBSD goes it's pretty easy and quick to setup

**Comment by gesangtome** [comment]
> FreeBSD uses llvm/clang 13 and libc++ If you want some pointers as far as FreeBSD goes it's pretty easy and quick to setup
> 
> @gesangtome RB?

It's libtorrent, on Fedora the developers renamed it rb-libtorrent - ：)-

**Comment by diizzyy** [comment]
No, I'm on 2.0.6

**Comment by diizzyy** [comment]
@arvidn 
This now works on RC_2_0 commit https://github.com/arvidn/libtorrent/commit/13b252e1a435f84ebbdf21452417ce533c810d1f (latest as of writing this)

**Comment by arvidn** [comment]
thanks for testing!
