### ISSUE TITLE
DHT Requests Timeout

### ISSUE THREAD

**Issue by cyrillicw** [arvidn/libtorrent#6829]
In order to download a file, the client makes requests to DHT in order to find out the peers to download from. If there are no such peers, then the client will repeat the effort again. Is there a possibility to regulate this timeout?

**Comment by master255** [comment]
There's no need for that. DHT works instantly.

**Comment by arvidn** [comment]
yes, there's a `dht_announce_interval`, which defaults to 15 minutes.

https://libtorrent.org/reference-Settings.html#dht_announce_interval

**Comment by cyrillicw** [comment]
Thank you!
