### ISSUE TITLE
Decipher the purpose of the branches?

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6837]
@arvidn There is a branch 2.0 - it develops the second version of torrents?

There is a 1.2 branch which develops the 1.2 version of torrents?

There is a master branch - what's going on there? Is it stable? Is it available for use? For whom is this branch? Why does it have streaming and other branches do not have streaming? What else does it have?

**Comment by arvidn** [comment]
it's just normal software versioning. 1.2.x was the penultimate major release, 2.0.x is the latest major release and master is the next major release.

**Comment by master255** [comment]
@arvidn Why for many months now, some commits (streaming is one of them) don't get into either 1.2 or 2.0 from the master?

**Comment by glassez** [comment]
> Why for many months now, some commits (streaming is one of them) don't get into either 1.2 or 2.0 from the master?

Isn't it answered above?
>master is the next major release.

So I suppose the changes from master aren't intended for neither 2.0 nor 1.2.

**Comment by master255** [comment]
@glassez @arvidn So the master is the future 2.1 version? or 1.3?
