### ISSUE TITLE
How ports from one ip are selected?

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6843]
@arvidn I updated the library from version 1.2.13 to 1.2.16 and my https torrents stopped working.

The problem is that I have a lot of ports on my server.
And one of them gives out https torrent. Version 1.2.13 somehow found the correct port (sometimes not the first time. I had to delete the torrent and add again). Version 1.2.16 only ever connects to the one port. Random is gone. 

By what logic is the port selected if there are many?
Where is this logic in the code?

**Comment by master255** [comment]
@arvidn I'm talking about the torrent port. Url seed is not involved. Url seed is only used after the torrent connection. And the torrent connection does not happen because of port problems.

**Comment by arvidn** [comment]
you mean the listen port for peer connections? it's configured in `listen_interfaces`

**Comment by master255** [comment]
@arvidn It's okay. There are questions, but that's not relevant to the update.
