### ISSUE TITLE
Inconsistent torrent trackers handling

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#6846]
The list of torrent's trackers is inconsistently handled. In some places the duplicated URLs are disallowed while in other ones there are no such checking so there can be duplicated trackers added.

Loading trackers from resume data (disallowed):
https://github.com/arvidn/libtorrent/blob/beb9dbc3fedeabfa052289937c4533414fca775e/src/torrent.cpp#L325-L328

Adding single tracker to torrent (disallowed):
https://github.com/arvidn/libtorrent/blob/beb9dbc3fedeabfa052289937c4533414fca775e/src/torrent.cpp#L5743-L5747

Adding single tracker to torrent info (disallowed):
https://github.com/arvidn/libtorrent/blob/beb9dbc3fedeabfa052289937c4533414fca775e/src/torrent_info.cpp#L1766-L1768

Replace all the trackers from torrent (allowed):
https://github.com/arvidn/libtorrent/blob/beb9dbc3fedeabfa052289937c4533414fca775e/src/torrent.cpp#L5689-L5693

Parsing magnet link (allowed):
https://github.com/arvidn/libtorrent/blob/beb9dbc3fedeabfa052289937c4533414fca775e/src/magnet_uri.cpp#L223-L236

Parsing .torrent file (allowed):
https://github.com/arvidn/libtorrent/blob/beb9dbc3fedeabfa052289937c4533414fca775e/src/torrent_info.cpp#L1629-L1646

Therefore, first of all, I have the following question - what kind of behavior is still intended?
Obviously, there is no point in having pure duplicate trackers (or is there?). But, AFAIK, some people think that it might be useful to have duplicate trackers with different tiers (for the purposes of some very advanced tracker management).
In any case, the current behavior looks inconsistent/incorrect, so it should be fixed in one way or another.

**Comment by arvidn** [comment]
I can't think of a reason to allow duplicates in the tracker list. not even in different tiers. The de-facto behavior of tiers is to announce to all tiers in parallel, and (afaik) the de-factor behavior of creating torrents is to add all trackers to individual tiers. i.e. all trackers are typically announced to in parallel.

On the other hand, it dosen't seem core to libtorrent to enforce uniqueness. I suppose it would be a matter of quality when loading poorly made .torrent files. I take it people create torrents with duplicate trackers in the wild then, is that right?

**Comment by glassez** [comment]
>I can't think of a reason to allow duplicates in the tracker list. not even in different tiers

👍 
It doesn't seem like it can do any good. After all, it will either announce the same tracker several times at the same time, or it will try to do it if the previous announcement failed, which does not make sense since it should try another tracker instead.
>I take it people create torrents with duplicate trackers in the wild then, is that right?

Don't know. I didn't pay attention to it. I'm here only because I noticed inconsistencies in libtorrent's behavior.
>On the other hand, it dosen't seem core to libtorrent to enforce uniqueness.

But it is more convenient to do it at libtorrent side, besides, part of it has already been done.
In any case, inconsistent behavior should be fixed either one way or the other (either take care of the uniqueness of trackers, or not do it at all).

**Comment by glassez** [comment]
> On the other hand, it dosen't seem core to libtorrent to enforce uniqueness.

As I said it related discussion at qBittorrent side (https://github.com/qbittorrent/qBittorrent/pull/17017#issuecomment-1124535746) at least there are problems with mapping between tracker responses and tracker entries (aka announce entries in libtorrent) unless they are unique, aren't there?

**Comment by arvidn** [comment]
one challenge here is that I don't think it's acceptable to have O(n^2) complexity of loading tracker URLs from a torrent. So there would need to be some more sophisticated data structure, which in turn would make everyone pay (a small) cost for this feature.

Presumably adding a single tracker URL to a torrent also shouldn't be O(n) either.

**Comment by glassez** [comment]
> one challenge here is that I don't think it's acceptable to have O(n^2) complexity of loading tracker URLs from a torrent.

It's already there when you load resume data. Do not forget that this is exactly the action that is performed in a batch for many torrents when resuming a session. So it won't make the situation much worse if it does the same when loading a .torrent file or a magnet link, since these actions are mostly rare during application lifetime.
At least, it would be better to fix the problem in this way first, and only then think about how to optimize it.
>So there would need to be some more sophisticated data structure, which in turn would make everyone pay (a small) cost for this feature.

You could use `std::set` but I don't think it will bring any performance increase in case of not so much trackers per torrent (it seems to me that most users don't have many trackers on their torrents). Besides, `std::set` is unlikely allowed to be sorted so freely.

**Comment by glassez** [comment]
@arvidn
Or do you have any ideas how to make reliable and predictable behavior with allowed tracker duplicates?

**Comment by arvidn** [comment]
I've started work on a patch that will use a bloom filter to detect duplicates

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/6873

**Comment by glassez** [comment]
> #6873

Parsing .torrent file or magnet link still doesn't filter out tracker duplicates.

**Comment by summerqB** [comment]
was this resolved? if yes, it should be closed.

**Comment by arvidn** [comment]
it was fixed in libtorrent master branch (so, not released yet). duplicates torrents are not filtered when parsing a torrent file, they are filtered when adding it to the session.
