### ISSUE TITLE
Libtorrent does not understand the HTTP 404 error

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#6857]
@arvidn When a client requests a file from a url seed and receives a 404 error in response, it does not stop requesting data. He makes a second request indefinitely.
This is not correct behavior.

Libtorrent should stop requesting this file. The request can only be re-requested if the url seed has been re-added.
Does the torrent protocol work similarly?

**Comment by arvidn** [comment]
do you have an example log of this happening?

**Comment by master255** [comment]
I tested it. It works correctly.
