### ISSUE TITLE
Python bindings missing FileStorage functions

### ISSUE THREAD

**Issue by Banou26** [arvidn/libtorrent#6862]
libtorrent version: 2.0.6

The python bindings are missing pretty important functions including:

https://www.libtorrent.org/reference-Storage.html#file-num-pieces-file-num-blocks-file-piece-range
`file_num_pieces()` `file_num_blocks()` `file_piece_range()`
`file_first_piece_node()` `file_first_block_node()`

**Comment by AllSeeingEyeTolledEweSew** [comment]
The python bindings aren't an exact one-to-one match with the C++ implementation.

See here: https://github.com/arvidn/libtorrent/blob/13b252e1a435f84ebbdf21452417ce533c810d1f/bindings/python/src/create_torrent.cpp#L157

* `file_num_pieces()` is `fs.num_pieces()`
* `file_num_blocks()` is `fs.num_pieces() * fs.piece_length() / 16384`
* I don't think boost.python supports range types very well, so there's no `file_piece_range()`.
* `file_first_piece_node()` is maybe a bigger miss. I don't know how merkle trees actually work, so I'm not sure how one would calculate this using the given functions. @arvidn?

**Comment by Banou26** [comment]
I see, for `file_first_piece_node()` i was thinking of using `torrent_info.map_file(0, 0, 0).piece`, would that be correct?

**Comment by Banou26** [comment]
Actually `file_num_pieces` isn't `fs.num_pieces()` as `file_num_pieces` accepts a file index, to return the amount of pieces for that file, which `num_pieces` doesn't accept and instead return the entire torrent pieces, which is similar to `torrent_info.num_pieces()`

**Comment by Banou26** [comment]
Actually `file_num_pieces()` isn't the same as `fs.num_pieces()`.
As per the documentation (https://www.libtorrent.org/reference-Storage.html#file-num-pieces-file-num-blocks-file-piece-range), `file_num_pieces()` accepts a file index to return the amount of pieces related to that file, which the current implementation of `fs.num_pieces()` doesn't accept any arguments, so I'm assuming it returns the total amount of pieces, which would make it the same as `torrent_info.num_pieces()`

**Comment by AllSeeingEyeTolledEweSew** [comment]
ah right.

i've used stuff like this:

```python
first_piece, last_piece = fs.file_offset(i) // fs.piece_length(), (fs.file_offset(i) + fs.file_size(i) - 1) // fs.piece_length()
piece_range = range(first_piece, last_piece + 1)
file_num_pieces = len(piece_range)
```
and so on.

the python bindings aren't terribly pythonic. and based on my experience with boost.python, i think a project like "make the python bindings pythonic" would start with "ditch boost.python and use pybind11". It's a worthy project, but there are more pressing projects.
