### ISSUE TITLE
Python bindings build failure

### ISSUE THREAD

**Issue by tasoss** [arvidn/libtorrent#6866]
Hello.
I have built boost from git(master branch).
Then i have installed libtorrent(RC_2_0 branch and using correct BOOST_ROOT and BOOST_BUILD_PATH)

`b2 crypto=openssl cxxstd=14  release`
`sudo b2 install --prefix=/usr/local`

After that i try
`python3 setup.py build`
but i get

> gcc.archive ../../bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/libtorrent-rasterbar.a
gcc.link.dll bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/libtorrent.cpython-39-x86_64-linux-gnu.so
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
    "g++"    -o "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/libtorrent.cpython-39-x86_64-linux-gnu.so" -Wl,-h -Wl,libtorrent.cpython-39-x86_64-linux-gnu.so -shared -Wl,--start-group "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/module.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/sha1_hash.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/sha256_hash.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/info_hash.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/converters.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/create_torrent.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/fingerprint.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/utility.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/session.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/entry.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/torrent_info.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/string.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/torrent_handle.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/torrent_status.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/session_settings.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/version.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/alert.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/datetime.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/peer_info.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/ip_filter.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/magnet_uri.o" "bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/src/error_code.o" "/home/tasoss/t/boost/bin.v2/libs/python/build/gcc-11/release/cxxstd-14-iso/libtorrent-python-pic-on/link-static/python-3.9/libboost_python39.a" "../../bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/libtorrent-rasterbar.a" "../../deps/try_signal/bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/libtry_signal.a" "/home/tasoss/t/boost/bin.v2/libs/system/build/gcc-11/release/cxxstd-14-iso/libtorrent-python-pic-on/link-static/threading-multi/visibility-hidden/libboost_system.a"  -Wl,-Bstatic -ldl -lutil -lssl -lcrypto -Wl,-Bdynamic -lpthread -lssl -lcrypto -ldl -lutil -Wl,--end-group -fPIC -std=c++14 -Wl,-Bsymbolic
...failed gcc.link.dll bin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9/libtorrent.cpython-39-x86_64-linux-gnu.so...
...skipped <p/home/tasoss/t/libtorrent/bindings/python/build/lib.linux-x86_64-3.9>libtorrent.cpython-39-x86_64-linux-gnu.so for lack of <pbin/gcc-11/release/address-model-64/cxxstd-14-iso/libtorrent-python-pic-on/python-3.9>libtorrent.cpython-39-x86_64-linux-gnu.so...
...failed updating 1 target...
...skipped 1 target...
...updated 216 targets...
Traceback (most recent call last):
  File "/home/tasoss/t/libtorrent/setup.py", line 6, in <module>
    runpy.run_path('setup.py')
  File "/usr/lib64/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "setup.py", line 449, in <module>
    setuptools.setup(
  File "/usr/lib64/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.9/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 328, in run
    self._build_extension_with_b2()
  File "setup.py", line 347, in _build_extension_with_b2
    subprocess.run(command, cwd=python_binding_dir, check=True)
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['b2', 'boost-link=static', 'libtorrent-link=static', 'crypto=openssl', 'deprecated-functions=on', 'variant=release', 'address-model=64', 'python=3.9', 'libtorrent-python=on', 'python-install-path=/home/tasoss/t/libtorrent/bindings/python/build/lib.linux-x86_64-3.9', 'install_module', '--project-config=/tmp/tmp2tbm70rl']' returned non-zero exit status 1.

I have read [here](https://www.libtorrent.org/building.html) 

> To customize the library path and include path for openssl, set the features openssl-lib and openssl-include respectively.

but i don't know how to set it correctly.
Any ideas please?
I'm using slackware 15 ,  gcc 11.2.0 , python 3.9.12
Thanks!

**Comment by AllSeeingEyeTolledEweSew** [comment]
`python setup.py build_ext --b2-args=openssl-include=/path` may work for you.

It looks like it found your openssl headers though, just not your `-lssl` /`-lcrypto`, indicating one is installed in an expected place but the other isn't. Is that expected for you?

**Comment by tasoss** [comment]
Thanks for replying.
`tasoss@deluger:~/t/libtorrent$ ldd /usr/local/lib/libtorrent-rasterbar.so.2.0.6 
linux-vdso.so.1 (0x00007ffdf25c7000)
libboost_system.so.1.80.0 => /usr/local/lib/libboost_system.so.1.80.0 (0x00007f4cc2e18000)
librt.so.1 => /lib64/librt.so.1 (0x00007f4cc2e0e000)
libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007f4cc2d78000)
libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f4cc2a93000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007f4cc2a8e000)
libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f4cc287a000)
libm.so.6 => /lib64/libm.so.6 (0x00007f4cc2730000)
libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007f4cc2715000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4cc26f4000)
libc.so.6 => /lib64/libc.so.6 (0x00007f4cc2515000)
/lib64/ld-linux-x86-64.so.2 (0x00007f4cc390c000)
libz.so.1 => /lib64/libz.so.1 (0x00007f4cc24fb000)
`
I have tried using what you have suggested but i get the same error.
It's a new installation of the OS so i don't think that this is something that i should expect.

**Comment by userdocs** [comment]
Are you using this package of openssl or did you build it yourself?

https://packages.slackware.com/?r=slackware-current&p=openssl-1.1.1o-i586-1.txz

**Comment by tasoss** [comment]
Hello.
I'm using 
[https://packages.slackware.com/?r=slackware64-15.0&p=openssl-1.1.1o-x86_64-1_slack15.0.txz](https://packages.slackware.com/?r=slackware64-15.0&p=openssl-1.1.1o-x86_64-1_slack15.0.txz)

It's an official package , i didn't compile it by myself.
Thanks!

**Comment by userdocs** [comment]
After taking another look I have a question. You comment before mine shows it appears to have built and installed successfully but you say there is the same error.

`ldd /usr/local/lib/libtorrent-rasterbar.so.2.0.6`

```
libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007f4cc2d78000)
libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f4cc2a93000)
```

It is still not working?

**Comment by tasoss** [comment]
Hello again and thanks for replying.
I have compiled successfully the library BUT the error i get is when i run
python3 setup.py build (in order to build the python bindings).
The library is compiled just fine.
No it's not the python library.
Thanks again!

**Comment by AllSeeingEyeTolledEweSew** [comment]
Looking at the file contents of the slackware package, it looks like it includes headers and `*.so`s, but not `*.a`s.

`setup.py` will invoke `b2` to link everything statically, as that's the normal case for python packages distributed on pypi or built from source. If you want dynamic linking, you can do `python setup.py build_ext --b2-args="libtorrent-link=shared boost-link=shared"`

Otherwise, you may need to find some other package that includes `libssl.a`, and possibly other `*.a`s as well.

**Comment by tasoss** [comment]
You are right.
Thanks!!
