### ISSUE TITLE
MacOSX version min comparison

### ISSUE THREAD

**Issue by i96751414** [arvidn/libtorrent#6871]
Hi Arvidn,

I am not a Mac OSX user, however I do some cross compiling for it. Recently I've noticed you do this comparison for enabling `preadv`:
https://github.com/arvidn/libtorrent/blob/c05affe19ccbc02ae53434f957ccb15d1e7d3fe0/include/libtorrent/config.hpp#L135

Wouldn't this fail for `-mmacosx-version-min=10.10` as it produces `MAC_OS_X_VERSION_MIN_REQUIRED=101000`?

I've decreased the VERSION_MIN to 10.9 and everything works as expected:  `-mmacosx-version-min=10.9` produces `MAC_OS_X_VERSION_MIN_REQUIRED=1090`, however I didn't manage to make it work with VERSION_MIN=10.10

Kindly

**Comment by arvidn** [comment]
are you saying `1100` should be `110000`?
or are you saying `preadv()` exists in older kernels?

**Comment by i96751414** [comment]
Neither one :p 1100 is correct, as 11.0 produces that value. I am just confused about the comparison.
For example, 10.9 produces 1090, however 10.10 produces 101000. That said, the comparison will wok for 10.9 but not (erroneously) for 10.10. Maybe this can't be a simple integer comparison?

Probably (I am assuming here, as I really don't have much knowledge on this) this kind of comparisons can only be done within the same major version.

**Comment by i96751414** [comment]
Sorry, probably, `1100` should be `110000`: https://opensource.apple.com/source/AvailabilityVersions/AvailabilityVersions-70/AvailabilityVersions.h.auto.html

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/6875
