### ISSUE TITLE
[help] compiling a file

### ISSUE THREAD

**Issue by cs-mshah** [arvidn/libtorrent#6884]
libtorrent version (or branch): 2.04

platform/architecture: ubuntu 20.04

compiler and compiler version: gcc 9.4.0

I was unable to compile the first basic example given in the [tutorial](https://www.libtorrent.org/tutorial-ref.html).  

I ran `g++ test.cpp` and it gave:
![image](https://user-images.githubusercontent.com/56499208/170185861-4355f88f-d262-4a52-b07b-83ede5559a03.png)

I have followed all the build instructions for building libtorrent and they all ran successfully.
Is there something I am missing? kindly help me to compile and run a few examples.

**Comment by cs-mshah** [comment]
thanks a lot! It worked. I would suggest that this be added to the tutorial as the flags to run are not known to beginners.

**Comment by Kolcha** [comment]
such things are obvious for any C/C++ developer at least from Linux. it is very generic rather than libtorrent specific.
please close the issue as it is solved.

**Comment by cs-mshah** [comment]
I knew about `-lpthread`, but wasn't aware of `-ltorrent-rasterbar`
