### ISSUE TITLE
SEGV with boost-libs-1.79.0

### ISSUE THREAD

**Issue by yurivict** [arvidn/libtorrent#6889]
After upgrading boost-libs from 1.72.0 to 1.79.0 qbittorrent now crashes:

```
Caught signal: SIGSEGV
Stack trace:
  0x801168bbf <pthread_setschedparam+0x82f> at /lib/libthr.so.3
  0x7ffffffff8a3 <???> at ???
  0x8010ad742 <_ZN10libtorrent14torrent_statusaSEOS0_+0x1992> at /usr/local/lib/libtorrent-rasterbar.so.2.0
  0x8010acd30 <_ZN10libtorrent14torrent_statusaSEOS0_+0xf80> at /usr/local/lib/libtorrent-rasterbar.so.2.0
  0x8010b03b0 <_ZN10libtorrent14torrent_statusaSEOS0_+0x4600> at /usr/local/lib/libtorrent-rasterbar.so.2.0
  0x8010b04ad <_ZN10libtorrent14torrent_statusaSEOS0_+0x46fd> at /usr/local/lib/libtorrent-rasterbar.so.2.0
  0x800d962d7 <_ZNK5boost4asio10io_context19basic_executor_typeINSt3__19allocatorIvEELm0EE7executeINS0_6detail17executor_functionEEEvOT_+0x347> at /usr/local/lib/libtorrent-rasterbar.so.2.0
  0x800d88fd2 <boost_asio_detail_posix_thread_function+0x7b2> at /usr/local/lib/libtorrent-rasterbar.so.2.0
  0x800d88a31 <boost_asio_detail_posix_thread_function+0x211> at /usr/local/lib/libtorrent-rasterbar.so.2.0
  0x800d85aa3 <_ZN10libtorrent14create_torrent17set_creation_dateEl+0x1cb3> at /usr/local/lib/libtorrent-rasterbar.so.2.0
  0x800f73ea0 <_ZN10libtorrent27default_disk_io_constructorERN5boost4asio10io_contextERKNS_18settings_interfaceERNS_8countersE+0x70> at /usr/local/lib/libtorrent-rasterbar.so.2.0
```

[Downstream](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264278) bug report.

Version: 2.0.8
FreeBSD 13.3

**Comment by yurivict** [comment]
The latest 2.x code revision doesn't crash when built with -std=c++17.

**Comment by yurivict** [comment]
Maybe you should just add ```std=c++17``` and make a new release?

**Comment by userdocs** [comment]
The releases are just the source code so no need to make a new release. It would just be docs about building

I think there have already been examples of problems with cxx14 and newer version of boost and libtorrent v2 that using cxx17 has resolved. So maybes it's just better to advise using cxx 17 where possible.

**Comment by arvidn** [comment]
it smells like an ABI issue, which could be caused by a number of build flags differing between libtorrent, boost and qbittorrent.

I don't have any issues on Ubuntu. After updating boost, did you also rebuild libtorrent and qbittorrent?

**Comment by userdocs** [comment]
I think most of the examples were on non debian based systems, like the gentoo, alpine and there was one or two others I think, openbsd maybe.

https://github.com/arvidn/libtorrent/issues/6567

https://github.com/arvidn/libtorrent/issues/6468#issuecomment-988825158

Maybe a non gcc issue or something where the standard used is part of the reason why the default happens.

This is what I was referencing.
