### ISSUE TITLE
Python binding fails to build: can't create dynamic relocation R_X86_64_32 against local symbol in readonly segment

### ISSUE THREAD

**Issue by yurivict** [arvidn/libtorrent#6890]
```
d: error: can't create dynamic relocation R_X86_64_32 against local symbol in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
>>> defined in ../../deps/try_signal/bin/clang-linux-12/release/address-model-64/cxxstd-14-iso/link-static/threading-multi/visibility-hidden/libtry_signal.a(signal_error_code.o)
>>> referenced by signal_error_code.cpp
>>>               signal_error_code.o:(sig::errors::make_error_code(sig::errors::error_code_enum)) in archive ../../deps/try_signal/bin/clang-linux-12/release/address-model-64/cxxstd-14-iso/link-static/threading-multi/visibility-hidden/libtry_signal.a
```

Revision: 2.0.6-27-g34c75eb5f
clang-13.3
FreeBSD 13.1

**Comment by userdocs** [comment]
I think this is the problem.

 > recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output

https://www.libtorrent.org/building.html#build-features

With `b2` you would use `fpic=on` when compiling libtorrent.

**Comment by yurivict** [comment]
Shouldn't this be a default in the project？

**Comment by userdocs** [comment]
I don't know about that that but if you used the flag when building it's in the build path like `/cxxstd-14-iso/fpic/link-static/`

Try it and see if it works.

**Comment by yurivict** [comment]
> With b2 you would use fpic=on when compiling libtorrent.

I use setup.py to build, How do I pass ```fpic=on``` to  setup.py?
Both ```--b2-args fpic=on``` and ```--b2-args=fpic=on``` as suggested in ```setup.py``` don't work.

**Comment by userdocs** [comment]
According to the docs here https://www.libtorrent.org/python_binding.html

I think it's like this, maybe @AllSeeingEyeTolledEweSew can confirm, since I only build it using b2
 
`python setup.py build_ext --b2-args="fpic=on"`

**Comment by yurivict** [comment]
Adding ```fpic=on``` like is described above doesn't solve the problem. b2 fails the same way with this argument.

**Comment by yurivict** [comment]
```
ld: error: relocation R_X86_64_PC32 cannot be used against symbol __stack_chk_guard; recompile with -fPIC
>>> defined in /lib/libc.so.7
>>> referenced by list.cpp
>>>               list.o:(boost::python::detail::list_base::index(boost::python::api::object const&) const) in archive /usr/local/lib/libboost_python38.a

ld: error: can't create dynamic relocation R_X86_64_32S against local symbol in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
>>> defined in /usr/local/lib/libboost_python38.a(list.o)
>>> referenced by list.cpp
>>>               list.o:(boost::python::detail::list_base::index(boost::python::api::object const&) const) in archive /usr/local/lib/libboost_python38.a

ld: error: relocation R_X86_64_PC32 cannot be used against symbol __stack_chk_guard; recompile with -fPIC
>>> defined in /lib/libc.so.7
>>> referenced by list.cpp
>>>               list.o:(boost::python::detail::list_base::index(boost::python::api::object const&) const) in archive /usr/local/lib/libboost_python38.a

ld: error: relocation R_X86_64_PC32 cannot be used against symbol __stack_chk_guard; recompile with -fPIC
>>> defined in /lib/libc.so.7
>>> referenced by list.cpp
>>>               list.o:(boost::python::detail::list_base::insert(long, boost::python::api::object const&)) in archive /usr/local/lib/libboost_python38.a

ld: error: can't create dynamic relocation R_X86_64_32S against symbol: PyList_Type in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
>>> defined in bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/session.o
>>> referenced by list.cpp
>>>               list.o:(boost::python::detail::list_base::insert(long, boost::python::api::object const&)) in archive /usr/local/lib/libboost_python38.a

ld: error: can't create dynamic relocation R_X86_64_32S against local symbol in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
>>> defined in /usr/local/lib/libboost_python38.a(list.o)
>>> referenced by list.cpp
>>>               list.o:(boost::python::detail::list_base::insert(long, boost::python::api::object const&)) in archive /usr/local/lib/libboost_python38.a

ld: error: can't create dynamic relocation R_X86_64_32 against local symbol in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
>>> defined in /usr/local/lib/libboost_python38.a(list.o)
>>> referenced by list.cpp
>>>               list.o:(boost::python::detail::list_base::insert(long, boost::python::api::object const&)) in archive /usr/local/lib/libboost_python38.a

ld: error: relocation R_X86_64_PC32 cannot be used against symbol __stack_chk_guard; recompile with -fPIC
>>> defined in /lib/libc.so.7
>>> referenced by list.cpp
>>>               list.o:(boost::python::detail::list_base::insert(long, boost::python::api::object const&)) in archive /usr/local/lib/libboost_python38.a

ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

    "clang++"  -o "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/libtorrent.cpython-38.so"  -Wl,-soname -Wl,libtorrent.cpython-38.so -shared -Wl,--start-group "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/module.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/sha1_hash.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/sha256_hash.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/info_hash.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/converters.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/create_torrent.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/fingerprint.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/utility.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/session.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/entry.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/torrent_info.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/string.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/torrent_handle.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/torrent_status.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/session_settings.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/version.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/alert.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/datetime.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/peer_info.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/ip_filter.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/magnet_uri.o" "bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/src/error_code.o" "../../bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/link-static/threading-multi/visibility-hidden/libtorrent-rasterbar.a" "../../deps/try_signal/bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/link-static/threading-multi/visibility-hidden/libtry_signal.a"  -Wl,-Bstatic -lboost_python38 -lboost_system -lssl -lcrypto -Wl,-Bdynamic -lpthread -lssl -lcrypto -Wl,--end-group -fPIC -std=c++14  /usr/local/lib/libboost_python38.so /usr/local/lib/libiconv.so -fstack-protector-strong -L/usr/local/lib 

...failed clang-linux.link.dll bin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8/libtorrent.cpython-38.so...
...skipped <p/disk-samsung/freebsd-ports/net-p2p/py-libtorrent-rasterbar/work-py38/libtorrent-2.0.6-27-g34c75eb5f/bindings/python/build/lib.freebsd-13.1-STABLE-amd64-3.8>libtorrent.cpython-38.so for lack of <pbin/clang-linux-13/release/address-model-64/cxxstd-14-iso/fpic-on/python-3.8>libtorrent.cpython-38.so...
...failed updating 1 target...
...skipped 1 target...
...updated 222 targets...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 449, in <module>
    setuptools.setup(
  File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 328, in run
    self._build_extension_with_b2()
  File "setup.py", line 347, in _build_extension_with_b2
    subprocess.run(command, cwd=python_binding_dir, check=True)
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['b2', 'fpic=on', 'boost-link=static', 'libtorrent-link=static', 'crypto=openssl', 'deprecated-functions=on', 'variant=release', 'address-model=64', 'python=3.8', 'libtorrent-python=on', 'python-install-path=/disk-samsung/freebsd-ports/net-p2p/py-libtorrent-rasterbar/work-py38/libtorrent-2.0.6-27-g34c75eb5f/bindings/python/build/lib.freebsd-13.1-STABLE-amd64-3.8', 'install_module', '--project-config=/tmp/tmpdfp_8ze0']' returned non-zero exit status 1.
*** Error code 1

```

**Comment by AllSeeingEyeTolledEweSew** [comment]
arvid added the feature `libtorrent-python-pic` in `bindings/python/Jamfile`, presumably so that the python bindings and the main library can be built with independent choices of `-fPIC`.

It conditionally defaults on:

https://github.com/arvidn/libtorrent/blob/34c75eb5f3e68896532838b9d408ccdc11b900ef/bindings/python/Jamfile#L157-L162

If the defaults aren't working on FreeBSD, I believe this block should probably be updated. @arvidn?

In the meantime, try
```
python setup.py build_ext --b2-args=libtorrent-python-pic=on
```

**Comment by yurivict** [comment]
Same with ```libtorrent-python-pic=on```.

**Comment by arvidn** [comment]
there's already a `fpic=on` build feature.
```
python setup.py build_ext --b2-args=fpic=on
```

**Comment by yurivict** [comment]
> there's already a fpic=on build feature.

But it doesn't solve the problem.

**Comment by AllSeeingEyeTolledEweSew** [comment]
> Same with `libtorrent-python-pic=on`.

`libtorrent-python-pic=on` isn't producing `-fPIC`? That's surprising; it's a very straightforward application in the Jamfile. Could you add some more `b2` debug flags to `--b2-args`, to verify the compilation command being produced? I'm not sure which are needed.

**Comment by userdocs** [comment]
If the Op has already built `libtorrent.so` and installed it to a system path will it need to be rebuilt with `fpic` for this to work when creating the binding? 

Or will that lib have no effect on the outcome of the binding?

I'm not sure how the python build works to be honest and I only build it using b2 + boost source in docker and using fpic just works.

**Comment by yurivict** [comment]
> If the Op has already built libtorrent.so and installed it to a system path will it need to be rebuilt with fpic for this to work when creating the binding?

Shared libraries can only be built with fpic option.

**Comment by userdocs** [comment]
Then maybe do this and use the debug to see if there is more helpful info?

> > Same with `libtorrent-python-pic=on`.
> 
> `libtorrent-python-pic=on` isn't producing `-fPIC`? That's surprising; it's a very straightforward application in the Jamfile. Could you add some more `b2` debug flags to `--b2-args`, to verify the compilation command being produced? I'm not sure which are needed.

I think using `b2` will work

https://www.mankier.com/1/b2

```
-dx
Set the debug level to x (0-9)
```

To be honest I can't test anything on that OS as i only used Debian based or Alpine.

**Comment by arvidn** [comment]
passing `-n` to `b2` will make it print the command lines. Although, it should be printing the command lines that fail already.

**Comment by AllSeeingEyeTolledEweSew** [comment]
The link command is what's failing, but we need to know what's passed to clang. It should be passing `-fPIC` but isn't.

(or something else is going on, like build artifacts are staying around when they should be rebuilt)

**Comment by yurivict** [comment]
[Here](https://people.freebsd.org/~yuri/py38-libtorrent-rasterbar-2.0.6.27.log) is a log with ```-n```.

**Comment by yurivict** [comment]
Sorry, this was due to a typo.
I updated the file.

**Comment by mexicarne** [comment]
Hello, are there any news on setup.py build?

**Comment by yozart** [comment]
No fix since the 28th of May ? what shall we do to install Deluge then ?

**Comment by yurivict** [comment]
For Python bindings pybind11 is really great.

Yesterday I created a binding for an unrelated project and it was a breeze. It only requires 1 C++ source file and 1 cmake script.

Why can't this project use pybind11?

**Comment by AllSeeingEyeTolledEweSew** [comment]
@arvidn `fpic=on` still shouldn't be required here, right? I think the fpic feature logic in `Jamfile` is only effective for gcc today, should it cover clang too?

**Comment by AllSeeingEyeTolledEweSew** [comment]
@yurivict 

or maybe you want
`setup.py build_ext --b2-args="fpic=on libtorrent-link=prebuilt boost-link=default`
depending on the build environment

**Comment by yozart** [comment]
It's beyond my knowledges and understanding here. 
If anyone can help me to complete the script I made in following topic I would be very thankfull !

https://www.truenas.com/community/threads/issues-with-deluge-on-truenas-12-u2.92105/post-720208

**Comment by AllSeeingEyeTolledEweSew** [comment]
@yozart I tried sorting through those scripts but it's a bunch of freebsd-specific stuff, some of it declarative. I don't know anything about freebsd. Can you point me to the thing that tries to build libtorrent?

**Comment by sporkman** [comment]
@AllSeeingEyeTolledEweSew - TL;DR is that the key is downgrading the "py39-libtorrent-rasterbar" package/port to an older version pre-dating this bug (version 1.2.16). This was enough for me to get deluge working.

If anyone working on this from the project needs a) a FreeBSD VM and b) a quick conversation to get the basics of the FreeBSD ports/packages systems down I can provide that.

**Comment by bergman** [comment]
I have been working on this a bit on the FreeBSD ports side and got things to build and run at least but it is a bit hacky since I am not proficient at writing ports or configuring boost/Jamfile things. I would gladly take any help on this.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264970 (patch also updates deluge but you can ignore that part)
