### ISSUE TITLE
[help] Attempt to seed torrent in a private network

### ISSUE THREAD

**Issue by harnaman-hk** [arvidn/libtorrent#6895]
libtorrent version (or branch): 2.04, C bindings

platform/architecture: Ubuntu 20.04

compiler and compiler version: gcc 9.4

I have a private network consisting of a few virtual machines. I need to share files/folders using torrent, I am able to create a torrent and a magnet link using the bindings available, but the torrent is not able to seed. What should be appropriate function call for seeding and trackers to achieve this?
I have followed a few resources to seed torrents but remained unsuccessful, kindly help with correct protocol to follow to achieve file sharing using libtorrent in a private network.

**Comment by Seeker2** [comment]
Marking a torrent as private eliminates almost all of the ways peers and seeds can find and connect to one another.

Also, a magnet link will not work without an accessible-to-all tracker if the torrents are private.

**Comment by arvidn** [comment]
@harnaman-hk I suspect the key issue you're facing is peer discovery. You can either set up a tracker on your local network, and make sure it accepts private-range IP addresses. Or if you know all peers (or most of them) in advance, you can just call [connect_peer](http://libtorrent.org/reference-Torrent_Handle.html#connect-peer) to connect them all up. They will gossip peers amongst each other.
