### ISSUE TITLE
Question : add_feed in Session

### ISSUE THREAD

**Issue by ardhipoetra** [arvidn/libtorrent#691]
Not really an issue, but are you planning to remove `add_feed` function in `session` class? I don't see any documentation in [here](http://libtorrent.org/reference-Core.html#session), but the function exist in the code.

**Comment by aldenml** [comment]
It seems to me like that function is not in the code anymore (master branch).

**Comment by ardhipoetra** [comment]
Now that you mentioned it, you're right. It was removed on https://github.com/arvidn/libtorrent/pull/662. It's still there in version 1.1 though.

As currently I'm using this function, any reason why removed it, @arvidn?

**Comment by arvidn** [comment]
@ardhipoetra the main reason is that it's not really in libtorrent's scope. I also get the impression that the majority of libtorrent users either don't use RSS or use a 3rd party library. It makes more sense to me to have rss functionality in a separate library. There are a few conventions around it in bittorrent, but that's minor compared to the rest of RSS.

**Comment by arvidn** [comment]
tribler doesn't use it, right?

**Comment by ardhipoetra** [comment]
@arvidn one of the future feature will use it. Although as you say, we can also find alternatives. We found out this function already there since 0.16.x (CMIIW), so we played around with it.

Thanks for the answer!
