### ISSUE TITLE
Does the libtorrent use UDP as compensation when uTP is limited to a very small rate?

### ISSUE THREAD

**Issue by Lwxiang** [arvidn/libtorrent#6915]
libtorrent version (or branch): 1.1.14

By default, I brings up my client and start with lots of torrents. The client works with a big UDP recv&send rate.
When I set both `enable_outgoing_utp=false` and `enable_incoming_utp=false`, then the UDP rate down to nearly zero.

This confused me.

Is that my client tcp send rate is limited by uTP(because of terrible network or other reasons), and libtorrent use UDP to send pieces data as compensation? And when I disable uTP, all sending action go back to TCP sender?

**Comment by rafi-d** [comment]
Nope. UDP applies only to uTP

**Comment by AllSeeingEyeTolledEweSew** [comment]
> Nope. UDP applies only to uTP

or DHT

**Comment by rafi-d** [comment]
Sure, DHT, but it is not related to data transfer at all...

**Comment by Lwxiang** [comment]
> Nope. UDP applies only to uTP

it that when I disabled uTP, then all data transfers will go with TCP?

**Comment by rafi-d** [comment]
> > Nope. UDP applies only to uTP
> 
> it that when I disabled uTP, then all data transfers will go with TCP?

Yes

**Comment by Lwxiang** [comment]
thx for your reply.
