### ISSUE TITLE
Unable to compile current libtorrent master

### ISSUE THREAD

**Issue by lethanhviet** [arvidn/libtorrent#692]
libtorrent version (or branch): commit 045e9316adacfe364298d9480526c6d70ac45459
platform/architecture: debian wheezy

[build.txt](https://github.com/arvidn/libtorrent/files/246226/build.txt)
[config.txt](https://github.com/arvidn/libtorrent/files/246227/config.txt)

**Comment by arvidn** [comment]
error: #error This file requires compiler and library support for the ISO C++ 2011

you need to use a compiler that supports C++11, and you probably need to enable it with a command line switch (gcc until 6.1 defaults to c++98). assuming you're building with GCC, you need to pass in -std=c++11

are you building with the autoconf/automake files that come with libtorrent? They probably need some updating to enable c++11.. I would have to do some research on that though. do you know by any chance?

**Comment by lethanhviet** [comment]
Hi,

Yes I'm building with autoconf/automake file that come with the libtorrent. And no I don't know how to get this work. Sorry. :/

Regards.

**Comment by arvidn** [comment]
as a workaround, you could probably get it to work by doing:

`CXXFLAGS=-std=c++11./configure`

**Comment by lethanhviet** [comment]
Hi,

After running configure using your suggestion above, I run make and got this error.

[makelog-error.txt](https://github.com/arvidn/libtorrent/files/248374/makelog-error.txt)

From the log, I manually added the flag -std=c++11 again to bindings/python/compile_flags and the build was successful.

However, after building, importing libtorrent flag below error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/local/lib/libtorrent-rasterbar.so.9: undefined symbol: _ZN10libtorrent9sha1_hashlSEi

Regards.

**Comment by lethanhviet** [comment]
Hi,

After running configure using your suggestion above, I run make and got this error.

[makelog-error.txt](https://github.com/arvidn/libtorrent/files/248396/makelog-error.txt)

From the log, I manually added the flag -std=c++11 again to bindings/python/compile_flags and the build was successful.

[makelog-successful.txt](https://github.com/arvidn/libtorrent/files/248397/makelog-successful.txt)

However, after building, importing libtorrent flag below error:
 $ python -c "import libtorrent; print libtorrent.version"
 Traceback (most recent call last):
 File "", line 1, in 
 ImportError: /usr/local/lib/libtorrent-rasterbar.so.9: undefined symbol: _ZN10libtorrent9sha1_hashlSEi

Regards.

**Comment by arvidn** [comment]
make sure your python module loads the correct version of libtorrent.so. if you don't install libtorrent, and link dynamically, you may have an older version installer already which it picks up.

**Comment by Indust** [comment]
I have the same issue while building with gcc 5.3 on centos 7.2, it seems that this commit [077e9bb](https://github.com/arvidn/libtorrent/pull/693/commits/7de8c800b37d5549dfb6513a5eec5bce252119cd) break it.

**Comment by arvidn** [comment]
thanks. sha1_hash.cpp had not been added to Makefile.am. fixed now!
