### ISSUE TITLE
how can I speed up checking torrent?

### ISSUE THREAD

**Issue by Lwxiang** [arvidn/libtorrent#6922]
I see the option "hashing_threads" is marked as DEPRECATED in 1.1.14

Is that hashing threads num controlled by the aio_threads?

**Comment by Lwxiang** [comment]
I found that WHAT I need is how to speed up checking, checking torrent of a big file(100G+) is very time-consuming.

**Comment by Lwxiang** [comment]
I have looked into the code `torrent::start_checking()`

I seems that `num_outstanding=max(aio_threads/4, checking_mem_usage something)`
So I guess when I increasing the `aio_threads`, the checking file threads should be increased too.
But in fact when I set the `aio_threads` from 8 to 64, the checking file time is nearly the same. And during checking the CPU usage is always between 30% to 50%, It seems libtorrent doesn't take the advantage of multi-threads hashing? Or just my configuration is wrong?

**Comment by arvidn** [comment]
look at these settings:
http://libtorrent.org/reference-Settings.html#hashing_threads
http://libtorrent.org/reference-Settings.html#checking_mem_usage

**Comment by master255** [comment]
@Lwxiang And another way. You can take the old hash if your files have not changed size and name.
That way it will take a few minutes to recheck even 500GB+ files.

**Comment by Lwxiang** [comment]
@master255 @arvidn Thanks, but my files are always new for seeding, so I am looking for the way to speed up first-time file checking .

I found that hashing_threads is deprecated in libtorrent 1.1.14, and the aio_threads settings seems no affected for checking.

**Comment by arvidn** [comment]
`hashing_threads` was un-deprecated in 1.2.8. That setting is not used in 1.1.14+, but it *is* used in 1.2.x

**Comment by Lwxiang** [comment]
@AllSeeingEyeTolledEweSew `flag_seed_mode` works, thanks.

by the way `set_piece_hashes` also a time killer, maybe it is impossible to rewrite it in my code instead of calling it directly, I will have a try.

**Comment by arvidn** [comment]
Are you creating a torrent, or checking it?

**Comment by Lwxiang** [comment]
I am creating a torrent, now `set_piece_hashes` takes me nearly 20min with a 200G file.

**Comment by arvidn** [comment]
Do you know if you're limited by disk I/O or CPU to hash?

If you're limited by disk I/O, make sure you only use a single read thread. you're also using a very old version of libtorrent, you may want to experiment with newer ones.

**Comment by Lwxiang** [comment]
I think that is limited by disk I/O.
I copy the [set_piece_hashes](https://github.com/arvidn/libtorrent/blob/libtorrent-1_1_14/src/create_torrent.cpp#L260) function out, and modify the `disk_thread.set_num_threads(1);` to a bigger number, along with a bigger `aio_threads`, that can really reduce some creating time. But I can see the threads are always in state D, so I guess they are waiting for disk reading.
<img width="308" alt="wecom-temp-f38b0575d084d0741f08efdb4cd0558d" src="https://user-images.githubusercontent.com/7104402/175295013-37320721-9748-4fbb-b0a5-2465033f7144.png">

> If you're limited by disk I/O, make sure you only use a single read thread. you're also using a very old version of libtorrent, you may want to experiment with newer ones.

I am very very interested in a high version, but I have to use C++98 in my product environments for some reasons, 1.1.14 is the newest version I can find.

**Comment by AllSeeingEyeTolledEweSew** [comment]
> I am very very interested in a high version, but I have to use C++98 in my product environments for some reasons, 1.1.14 is the newest version I can find.

What environment is this?

Libtorrent 1.2 requires c++11, but [gcc has had full c++11 support since 4.8.1](https://gcc.gnu.org/projects/cxx-status.html#cxx11), which was [released may 31 2013 and EOL june 23 2015](https://gcc.gnu.org/gcc-4.8/).
