### ISSUE TITLE
Option no_connect_privileged_ports extends to web seed

### ISSUE THREAD

**Issue by kirill-782** [arvidn/libtorrent#6959]
libtorrent version (or branch): RC_1_2

platform/architecture: Widnows 10 x64

I think that this is a bit wrong, since torrent trackers work on standard HTTP (80) and HTTPS (443) ports. And for the web seed to work, you either have to disable this setting or change the configuration of the web server.

Line from log 
```
(W) 2022-07-10T16:58:27 - URL seed name lookup failed. Torrent: "maps". URL: "http://example.com/". Error: "maps url seed (http://example.com/) failed: port blocked by port-filter"
```

**Comment by arvidn** [comment]
Yes, I think I agree. Web seeds aren't gossiped around, so it's not as easy to get magnification on a DDoS attack, as far as I can tell.

**Comment by arvidn** [comment]
The error you posted suggests that the *port-filter* was enabled though, not `no_connect_privileged_ports`. Those are separate features.

as far as I can tell, the `no_connect_privileged_ports` does not apply to web seeds, but the port-filter applies to all peers. The expected error code for this feature is a `peer_blocked_alert` with a reason code `peer_blocked_alert::privileged_ports`.

**Comment by escape0707** [comment]
Hi, can we reopen this issue? My friend and I tried to create a web seed torrent, and when we test it with qBitTorrent, I hit the same issue. The only difference between a working default config and the config that can't function is this switch. And the error log is the same: 

```
2/13/2024 3:12 PM - URL seed DNS lookup failed. Torrent: "blablabla". URL: "https://example.com/foo". Error: "blablabla url seed (https://example.com/foo) failed: port blocked by port-filter"
```
