### ISSUE TITLE
Failure to record download progress on system failure will skip rechecking of files on next startup

### ISSUE THREAD

**Issue by summerqB** [arvidn/libtorrent#6975]
**Please provide the following information**

libtorrent version (or branch):
RC2_0
platform/architecture:

compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

While a download is in progress, if you hard reboot the system or system fails/reboots, download progress is lost.
However, on next start, libtorrent does not feel it necessary to recheck the file progress before starting from zero or last known progress.

My suggestion is, when a download is active, write a flag to resume data to indicate download is in progress.
This flag will only be turned off if user pauses the torrent or shuts down the client cleanly.
Otherwise this flag should cause libtorrent to force recheck the torrent data on session startup for downloading torrents.

**Comment by glassez** [comment]
The problem is that users are terribly averse to all sorts of automatic rechecks when launching the application (at least, qBittorrent users). I am sure that many people would really prefer to re-download several hundred megabytes rather than recheck anything. Unless libtorrent will ever be able to do a partial recheck, because in fact in such a situation we can skip checking those parts that are marked in the resume data as "existing".

**Comment by summerqB** [comment]
Then maybe mark the torrent as requires recheck and pause it. But when user asks to resume download, ask if they want to resume downloading(and potentially overwrite already downloaded data) or they want to run a force recheck.

**Comment by glassez** [comment]
> Then maybe mark the torrent as requires recheck and pause it. But when user asks to resume download, ask if they want to resume downloading(and potentially overwrite already downloaded data) or they want to run a force recheck.

it's all too complicated and impractical to wait for unknown amount of time for user action, if it can be solved in one way or another by that time. All that is needed is to provide the user with the opportunity to indicate their preferences in this matter, either download everything that was not counted in resume data (as it is happening now), or recheck such torrents.

**Comment by summerqB** [comment]
> I am sure that many people would really prefer to re-download several hundred megabytes rather than recheck anything. 
>

I'm quite sure this is only true for public tracker users as they're don't care about trackers keeping count of download/upload stats. On private trackers if you have to redownload several gigs of data it will affect the ratio badly.

>it's all too complicated and impractical to wait for unknown amount of time for user action, if it can be solved in one way or another by that time. All that is needed is to provide the user with the opportunity to indicate their preferences in this matter, either download everything that was not counted in resume data (as it is happening now), or recheck such torrents.
>

I believe having at least the preference to choose which way the user prefers is pretty important and current behaviour is not the expected one.

**Comment by glassez** [comment]
> I believe having at least the preference to choose which way the user prefers is pretty important

That's what I suggested above, isn't it? You could open Feature request on qBittorrent.


> current behaviour is not the expected one.

Maybe for users of private trackers...
Since real atomicity in this matter is impossible, I intend to treat this as two equivalent ways (although I personally believe that most users don't share your cares about it).
