### ISSUE TITLE
P2P connections from idle torrents

### ISSUE THREAD

**Issue by mj-p** [arvidn/libtorrent#6981]
Hey,
in our environment which is a LAN with no PeX, LSD or DHT and only our private tracker (qbittorrent) we face following issue:
There are like 100+ client hosts in the same network and they all share the same lets say 6 torrents.
If they have nothing more to download because every host is done, they are still exchanging handshake every minute for each torrent with every peer announced by the tracker which in fact seem to be all client hosts.
This in fact creates a performance problem in our network because there are so many p2p connections in the same network even when there should be nothing to upload or download. 

I could not seem to find any settings to change the behaviour.
Is it really necessary to keep up connections like that even if nothing interesting is happening because both peers are already done?

Same issue was discussed here in 2017: [https://qbforums.shiki.hu/viewtopic.php?t=5505](https://qbforums.shiki.hu/viewtopic.php?t=5505)

Any guidance or suggestions are welcome

**Comment by mj-p** [comment]
Maybe adding an option to apply inactivity_timeout always instead only when close to limit of connections somewhere along those lines:

[https://github.com/arvidn/libtorrent/blob/505c63b3bc8bd0c16aa44d224543fcb3962d4b9b/src/peer_connection.cpp#L4975-L5011](https://github.com/arvidn/libtorrent/blob/505c63b3bc8bd0c16aa44d224543fcb3962d4b9b/src/peer_connection.cpp#L4975-L5011)

**Comment by arvidn** [comment]
my understanding is that what you see are connections made to the other peers, they exchange handshake and realize they're both seeds and disconnect. The inactivity timeout is about peers that look like they are still useful connections but nothing happens for an extended period of time.

Anyway, your situation is *supposed* to be handled by remembering that peers are seeds, and as long as one self is seeding, those peers won't be contacted again. Perhaps there's some issue with this logic.

It's possible, for instance, that as soon as *one* of the peers realizes that it's a seed-to-seed connection, it disconnects. Possibly before it sends its messages telling the other end that it's a seed. That way, one of the peers may still not learn that it was a redundant connection, and try again later.

Also, there is a `min_reconnect_time` (which defaults to 60 seconds). If you raise that timer, the peers won't reconnect to each other as often.

http://libtorrent.org/reference-Settings.html#min_reconnect_time

**Comment by sserdda-liamE** [comment]
Is this the same issue I'm seeing with qBittorrent and Deluge out in the wild?
https://github.com/qbittorrent/qBittorrent/issues/17872

**Comment by Seeker2** [comment]
There are multiple bugs causing/aggravating this behavior:
https://github.com/arvidn/libtorrent/issues/3542#issuecomment-1257038658

**Comment by reardonia** [comment]
> my understanding is that what you see are connections made to the other peers, they exchange handshake and realize they're both seeds and disconnect. The inactivity timeout is about peers that look like they are still useful connections but nothing happens for an extended period of time.
> 
> Anyway, your situation is _supposed_ to be handled by remembering that peers are seeds, and as long as one self is seeding, those peers won't be contacted again. Perhaps there's some issue with this logic.
> 
> It's possible, for instance, that as soon as _one_ of the peers realizes that it's a seed-to-seed connection, it disconnects. Possibly before it sends its messages telling the other end that it's a seed. That way, one of the peers may still not learn that it was a redundant connection, and try again later.
> 
> Also, there is a `min_reconnect_time` (which defaults to 60 seconds). If you raise that timer, the peers won't reconnect to each other as often.
> 
> http://libtorrent.org/reference-Settings.html#min_reconnect_time

LT is not remembering the seed-status of peers, and as you said, it is not sending the early messages (LTEP "upload_only" and/or FastExt "HaveAll" that would. LT *does* send those messages during incoming connections, but during outgoing connections it cuts the convo short before sending.

That is the core problem.  Adjusting the min_reconnect_time is the wrong solution; none of the users of LT have done so.
