### ISSUE TITLE
Negative `total_wanted_done ` or `total_wanted ` after rechecking a finished (partial) v2 torrent

### ISSUE THREAD

**Issue by thalieht** [arvidn/libtorrent#6982]
**Please provide the following information**

libtorrent version (or branch): 2.0.7

**please describe what symptom you see, what you would expect to see instead and
how to reproduce it.**

qBittorrent uses `total_wanted_done / total_wanted` to calculate progress but that results in a negative number after rechecking the finished v2 test torrent. The only file i have selected to download is "Darkroom (Stellar, 1994, Amiga ECS) HQ.mp4"
magnet:?xt=urn:btmh:1220caf1e1c30e81cb361b9ee167c4aa64228a7fa4fa9f6105232b28ad099f3a302e&dn=bittorrent-v2-test

I can't test any fixes, sorry.

**Comment by arvidn** [comment]
does this reproduce reliably? If so I should be able to figure it out.

**Comment by summerqB** [comment]
Also libtorrent counts torrent wanted done before validating pieces, resulting in false impression that download is stalled at 100% since qBt uses this information to calculate progress.

**Comment by arvidn** [comment]
I can't immediately reproduce this in `client_test`. It might depend on which flags are passed to `torrent_status()`

**Comment by thalieht** [comment]
I added another file to download (13.Popsy Team - ViP 2.vob.mp4) and now the number
`total_wanted_done / total_wanted` is 2.1 after a `force_recheck`. 
The negative number before was `total_wanted` if it helps.

**Comment by arvidn** [comment]
I finally managed to reproduce it! Here's a fix: https://github.com/arvidn/libtorrent/pull/7052
