### ISSUE TITLE
Compile error: MSYS2 Mingw64 + wolfssl 

### ISSUE THREAD

**Issue by filecxx** [arvidn/libtorrent#6988]
$BOOST_ROOT/b2.exe --toolset=gcc --layout=system cxxstd=20 variant=release threading=multi boost-link=static link=static runtime-link=static i2p=on dht=on boost-link=static fpic=on logging=off crypto=wolfssl deprecated-functions=on debug-symbols=off

![image](https://user-images.githubusercontent.com/100348948/182011968-702bb882-5f66-4c05-ab7c-5f13c56abbbb.png)

Insert the header file ```#include <sys/stat.h> ``` into include\libtorrent\stat.hpp could pass the compiling process.

But the "libtorrent.a" was broken because the stat macro (OpenSSL & WolfSSL) replaced the libtorrent::stat.

There is no such problem if crypto=built-in, it only existed on windows + MinGW.

**Comment by filecxx** [comment]
The crypto=built-in was great, but I need HTTPS trackers to work, is there a way to create a custom handle like below
```
session_.xxx_handle([](auto prototol,auto callback)
{
    if(protocol =="https"){
         //....
         callback(my_connector,my_sender,my_receiver,....);
         return true;
    }
    return false;
});
```
So I can use my own implemented HTTP library without OpenSSL & WolfSSL.

**Comment by arvidn** [comment]
you could try `#undef` the `stat` macro before including libtorrent headers. You could also try to build with deprecated functions disabled, `deprecated-functions=off`. At least the `stats_alert` won't be included in that case.

**Comment by filecxx** [comment]
uhh...
it's a "libtorrent-rasterbar.a" compiling problem before I am able to include the libtorrent headers into my program.

but thanks anyway.

**Comment by arvidn** [comment]
I see, libtorrent itself is failing to build

**Comment by Vort** [comment]
I faced the same problem when tried to build libtorrent with msys2 + cmake + ninja.
I hackfixed it like this: https://github.com/Vort/libtorrent/commit/c2502237c7525a5d429c4c69e4b282b74d26cc66
But I hope that developers can find better solution.

**Comment by filecxx** [comment]
The best solution is to rename the libtorrent::stat to libtorrent::stat_t

**Comment by JokerGT** [comment]
@filecxx  can you describe how you apply that fix?
im running into the same problem with msys + gcc

**Comment by filecxx** [comment]
> @filecxx can you describe how you apply that fix? im running into the same problem with msys + gcc

I haven't fixed that, I'm still using crypto=built-in.

**Comment by JokerGT** [comment]
which boost version did you try?

i just downgraded to boost1.73.0 and was able to compile against openssl.

**Comment by filecxx** [comment]
I always use the latest version of Boost, but I haven't tried Boost 1.73 yet. 

I don't think it's worth downgrading, so it would be great if @arvidn could fix the issue.

**Comment by JokerGT** [comment]
@arvidn @filecxx it was just a work-around for my build scripts so i can continue developing. i also would like to see a fix here soon ! thanks a lot for all the hard work!

**Comment by JokerGT** [comment]
it might be interresting: it works till version 1.77 of boost and throws those erros for 1.78 and above

**Comment by filecxx** [comment]
When I 
```
#undef stat
```
It doesn't throw those errors either, but it doesn't work correctly when I statically link it into my program.

Have you done a runtime test?
