### ISSUE TITLE
Checking on a Mounted Drive

### ISSUE THREAD

**Issue by FloatingMind12** [arvidn/libtorrent#6990]
Hi, I use libtorrent to download on a mounted google drive but when I resume a transfer, I always run out of disk space while it is checking the files. It seems like it copies the files locally. What settings could help me get around that? I'm using the python binding btw on a Ubuntu 18.04
Thank you

**Comment by Aleksman4o** [comment]
Logically files from Google Drive loads to your Google directory to check it. That's why you run out of space.

**Comment by FloatingMind12** [comment]
The behavior that I expect is that it would stream check the files
When I just download a torrent, everything is fine: I can download torrent as large as I want, independent to my local storage.
But the issue is only when I resume one, it shouldn't have anything to do with my local storage so why is my local storage being used here?

Sorry but I don't understand what you mean by Google Directory

**Comment by arvidn** [comment]
@FloatingMind12 what version of libtorrent are you using?
Do you see any evidence that files are copied or duplicated other than the error message (`ENOSPACE`)?
It's possible the out-of-disk error is incorrectly inferred from an underlying failure.
