### ISSUE TITLE
Too long filename cannot be renamed

### ISSUE THREAD

**Issue by xnoreq** [arvidn/libtorrent#7007]
libtorrent version (or branch):
RC_2_0

platform/architecture:
Linux x86_64

compiler and compiler version:
gcc 12.1.1

Issue:
(originally reported at https://github.com/qbittorrent/qBittorrent/issues/17405)
Some filesystems have low filename length limits. Starting a torrent that contains a file with a too long filename results in an error.
Trying to rename the file to shorten the filename results in an error.

Workaround that works for me:
```
---
 src/path.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/path.cpp b/src/path.cpp
index a829a414c..80ad6e2d9 100644
--- a/src/path.cpp
+++ b/src/path.cpp
@@ -823,7 +823,7 @@ namespace {
        stat_file(f, &s, ec);
        if (ec)
        {
-           if (ec == boost::system::errc::no_such_file_or_directory)
+           if (ec == boost::system::errc::no_such_file_or_directory || ec == boost::system::errc::filename_too_long)
                ec.clear();
            return false;
        }
--
2.37.1
```

**Comment by arvidn** [comment]
what's the effect of this patch? it looks like if would still just fail to create the files, right?
But you're saying that it will at least let you rename the file to make it succeed after that. Is that right?

**Comment by xnoreq** [comment]
> what's the effect of this patch? it looks like if would still just fail to create the files, right? But you're saying that it will at least let you rename the file to make it succeed after that. Is that right?

Exactly. On rename, libtorrent checks if a file exists. If the filename is too long then rename fails, preventing the user from shortening the filename to something the filesystem can handle.

I'm not sure why the stat is needed in the first place, but this patch just changes how ENAMETOOLONG is handled. With the patch, it is handled as "file does not exist" instead of an error.

**Comment by arvidn** [comment]
that stat is needed because sometimes people rename files to match an existing file, and they want to pick up seeding that. So there are a few different use cases for renaming

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/7026
