### ISSUE TITLE
Deluge/Libtorrent cant load previous torrents after upgrade from libtorrent 1.0.9 to newest build

### ISSUE THREAD

**Issue by lethanhviet** [arvidn/libtorrent#701]
libtorrent version (or branch): 60088a1672cffaef9f805d777433f16264373749

$ [ERROR   ] 11:57:46 torrentmanager:666 Torrent state file is either corrupt or incompatible! 'torrent_handle' object has no attribute 'resolve_countries'

**Comment by lethanhviet** [comment]
Update, can't seem to add new torrent as well from deluge/libtorrent. When new torrent is added, error below is reported:

$ [ERROR   ] 13:17:45 core:243 There was an error adding the torrent file *******.torrent
[ERROR   ] 13:17:45 core:244 'torrent_handle' object has no attribute 'resolve_countries'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/deluge-1.3.12-py2.7.egg/deluge/core/core.py", line 241, in add_torrent_file
    torrent_id = self.torrentmanager.add(filedump=filedump, options=options, filename=filename)
  File "/usr/lib/python2.7/dist-packages/deluge-1.3.12-py2.7.egg/deluge/core/torrentmanager.py", line 486, in add
    torrent = Torrent(handle, options, state, filename, magnet)
  File "/usr/lib/python2.7/dist-packages/deluge-1.3.12-py2.7.egg/deluge/core/torrent.py", line 186, in __init__
    self.handle.resolve_countries(True)
AttributeError: 'torrent_handle' object has no attribute 'resolve_countries'

**Comment by arvidn** [comment]
I take it that commit belongs to master, is that right? resolve countries has been deprecated for a few versions and has been removed in master

**Comment by UnitedMarsupials** [comment]
> has been deprecated for a few versions and has been removed in master

Seems like it was removed 1.1.0 _release_, actually. When I run `configure`, I get:

     configure:22743: WARNING: unrecognized options: --enable-geoip, --with-libgeoip

**Comment by lethanhviet** [comment]
Hi,

I'm aware of the deprecated --with-libgeoip. I run configure without the flag, and for some previous commit of 1.1.0, deluge/libtorrent stills work fine.

Regards.

**Comment by arvidn** [comment]
I would suggest, if deluge would like to preserve this feature, to look up the peer country in the maxmind database based on the IP in the peer_info object. (that's basically what libtorrent did internally, and since deluge still had to provide the database, it might as well do the lookup itself too)

**Comment by arvidn** [comment]
This message: "Torrent state file is either corrupt or incompatible!" seems misleading. it appears the underlying problem is using a function that has been removed.
