### ISSUE TITLE
Numerous ioctl-errors after upgrading to 1.1.0

### ISSUE THREAD

**Issue by UnitedMarsupials** [arvidn/libtorrent#702]
**Please provide the following information**

libtorrent version (or branch): rasterfile 1.1.0

platform/architecture: FreeBSD-10.3/amd64

compiler and compiler version: clang-3.4.1

After upgading libtorrent-rasterfile from 1.0.9 to 1.1.0 and qbittorret from 3.3.3 to 3.3.4, things appear to work well _except_... Except for the following error message appearing in kernel's output too often for comfort:

    +WARNING pid 56182 (qbittorrent): ioctl sign-extension ioctl ffffffffc0206933

The fix seems to be simple:

```diff
--- src/enum_net.cpp    2016-04-10 17:39:15.000000000 -0400
+++ src/enum_net.cpp    2016-05-05 10:54:59.018918000 -0400
@@ -91,5 +91,5 @@
 #if TORRENT_USE_IFADDRS || TORRENT_USE_IFCONF || TORRENT_USE_NETLINK || TORRENT_USE_SYSCTL
 // capture this here where warnings are disabled (the macro generates warnings)
-const int siocgifmtu = SIOCGIFMTU;
+const unsigned long siocgifmtu = SIOCGIFMTU;
 #endif
 ```
The second argument of `ioctl(2)` must be `unsigned long`. I wonder, what those warnings, mentioned in the comment, were saying and why was it deemed better to disable them instead of fixing?

**Comment by arvidn** [comment]
hm.. that's unfortunate. the open group specifies it to be signed "int". just changing it will presumably cause warnings on non-bsd systems. in master (which requires c++11) I could use auto. I'm not sure what the best solution is in 1.1. I feel like this problem has come up in the past though, I wonder what I did then.

**Comment by UnitedMarsupials** [comment]
> the open group specifies it to be signed "int".
Khm, yes, I see that Linux declares it as `int`. How about simply using the constant directly?

**Comment by arvidn** [comment]
at least on linux, the macro itself uses constructs that generates compiler warnings. and I'm building with -Werror. that's why it's being captures in a context where I can disable warnings.

**Comment by UnitedMarsupials** [comment]
> the macro itself uses constructs that generates compiler warnings

So, C++ code on Linux can not call `ioctl(2)` in the way documented in the function's manual page without triggering compiler warning(s)?..

**Comment by arvidn** [comment]
I'm not sure I necessarily would attribute it to linux specifically. Actually, iirc, some layer of the macros used to build those constants used C-style casts. Which, if you are a C programmer, have no problem with (which I imagine is common among linux developers). But if you're a C++ programmer you may want to dial up your compiler to warn about C-style casts, which, together with -Werror, causes build failures. So, whether it's the C programmer (using C-style casts) or the C++ programmer (making the compiler warn about them) who's at fault, probably depends on who you ask :)

**Comment by arvidn** [comment]
btw. is enum_net.cpp the only place where an ioctl command is captured by an int like that, or are there more places?

**Comment by arvidn** [comment]
as far as I can tell, linux take an "unsigned long" for the ioctl command as well, so it will likely not cause any sign warnings. https://github.com/arvidn/libtorrent/pull/705

**Comment by UnitedMarsupials** [comment]
> is `enum_net.cpp` the only place where an ioctl command is captured by an int like that, or are there more places?

After I added the above patch, `qbittorrent`-process stopped causing kernel-warnings. I think, this is because this particular ioctl's numeric value exceeds certain size...

> as far as I can tell, linux take an "unsigned long" for the ioctl command as well

Strange. On a CentOS-6 box, to which I have access, the ioctl(2) man-page starts with:

    SYNOPSIS
       #include <sys/ioctl.h>

       int ioctl(int d, int request, ...);

Ah, but the actual `/usr/include/sys/ioctl.h` says:

```C
    extern int ioctl (int __fd, unsigned long int __request, ...) __THROW;
```

So like Linux, pardon my bigotry... The platform's attraction remains a mystery.

**Comment by arvidn** [comment]
thanks!
