### ISSUE TITLE
how to download what I want in a torrent

### ISSUE THREAD

**Issue by mikebilly** [arvidn/libtorrent#7032]
Hi!, I'm trying to download torrents to my mounted drive on google colab. I only need to download 1 or 2 videos in a torrent of more than 40 videos. Can I make it only download the videos that I want, instead of downloading everything from the torrent file?

**Comment by arvidn** [comment]
yes, you can set file priorities to 0 for all files except the ones you want to download. Libtorrent also supports this via magnet links via the "select-only" parameter, e.g. `&so=2,3`

see: https://www.bittorrent.org/beps/bep_0053.html

**Comment by shindigin** [comment]
@arvidn I tried appending `&so=1, 2, 3` and `&so=1-3` to the magnet link, it doesn't work and just downloads all files.

**Comment by arvidn** [comment]
which version of libtorrent are you using?

**Comment by shindigin** [comment]
I'm using python bindings version `2.0.7`. The only approach that works is through passing params like the following:

    params = {'save_path': 'path/to/dest', 'file_priorities': [1, 0, 1, 1, ...]}
    magnet_link = 'magnet:?xt=urn:btih:...'
    download = lt.add_magnet_uri(ses, magnet_link, params) 

If I exclude `file_priorities` from the params and just add `so=...` to the magnet link, it doesn't work.
