### ISSUE TITLE
Is that "OVERVIEW" page on libtorrent.org updated?

### ISSUE THREAD

**Issue by Lwxiang** [arvidn/libtorrent#7047]
I am used to follow the [overview page](https://www.libtorrent.org/manual-ref.html) on libtorrent.org for learning.

But seems it has been updated recently? Some topics like "alert popping", "async torrent adding" are gone. 

It there somewhere I can find  the history versions of the overview page?

**Comment by arvidn** [comment]
yes, the history ie here: https://github.com/arvidn/libtorrent/commits/RC_2_0/docs/manual.rst
If you want some more details on significant changes between versions you may want to also check out:

https://www.libtorrent.org/upgrade_to_2.0-ref.html
https://www.libtorrent.org/upgrade_to_1.2-ref.html

**Comment by Lwxiang** [comment]
thank you!
