### ISSUE TITLE
A way to access userdata via torrent_handle interface

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#7049]
libtorrent version (or branch): RC_1_2

platform/architecture: N/A

compiler and compiler version: N/A

In RC_2_0 torrent stores the pointer to `userdata` provided by `add_torrent_params` and `torrent_handle::userdata()` method to access it.
@arvidn
Is it acceptable to backport it to RC_1_2, or will it break API/ABI compatibility?

**Comment by arvidn** [comment]
I think that would be possible without breaking ABI. the internal `torrent` object is not exposed by the library.

The main caveat, though, is that 1.2 uses a plain `void*` as userdata. So here's no type-safety and the API will be slightly different from 2.0

**Comment by arvidn** [comment]
something like this: https://github.com/arvidn/libtorrent/pull/7050

**Comment by glassez** [comment]
> The main caveat, though, is that 1.2 uses a plain `void*` as userdata. So here's no type-safety and the API will be slightly different from 2.0

Not a problem, since these differences already exist, so those who support both branches should already somehow deal with them.
