### ISSUE TITLE
A way to get progress and interrupt torrent info parsing

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#7051]
Recently I came across the existence in the wild of torrents containing a really huge number of files (several tens or even hundreds of thousands). Metadata (info section) of such files is parsed for quite a long time (we are talking about several tens of seconds), which is completely unacceptable for the main thread of an interactive application. Even if you move this task to the working thread, there is still no way to find out its progress, or interrupt its execution if the user wants to cancel it, or when the application is shutting down (of course, there is still the possibility to simply "kill" the thread, but this is not the best solution).
The proposed solution is to add the ability to set the callback as parameter of parsing function, which would be called periodically inside it, providing some feedback (reporting the current progress and checking the interrupt request).

**Comment by arvidn** [comment]
this is an issue when opening and parsing a torrent file with, say, `load_torrent()` or the `torrent_info` constructor?

I imagine a similar issue exists inside libtorrent where if a magnet link resolves to such torrent the libtorrent network thread may hang in a similar manner, while parsing the metadata.

**Comment by glassez** [comment]
> Is there any chance you have access to a .torrent file exhibiting this issue you could send me?

It is the torrent mentioned in https://github.com/arvidn/libtorrent/pull/7013#issuecomment-1226836675.

**Comment by glassez** [comment]
> I would expect that the most expensive part of the loading of the torrent actually is the code that ensures there are no duplicate filenames

Do you mean the following?
https://github.com/arvidn/libtorrent/blob/0061352077ff53ff9dd50d69957fb2ee10fd34e5/src/torrent_info.cpp#L1551
Initially, I also suspected him. But if I'm not confusing anything, most of the time in my tests, the call in the line above it was executed:
Do you mean the following?
https://github.com/arvidn/libtorrent/blob/0061352077ff53ff9dd50d69957fb2ee10fd34e5/src/torrent_info.cpp#L1550

**Comment by glassez** [comment]
> this is an issue when opening and parsing a torrent file with, say, `load_torrent()` or the `torrent_info` constructor?

`torrent_info` constructor.

**Comment by arvidn** [comment]
> Do you mean the following?
>   resolve_duplicate_filenames(); 

Yes, that's what I was suspecting.

It parses very quickly for me and loading it up in `client_test` doesn't cause any freezes.

Can you provide any more details of where you saw a lot of time being spent while parsing the metadata?

**Comment by glassez** [comment]
> Initially, I also suspected it. But if I'm not confusing anything, most of the time in my tests, the call in the line above it was executed:
> https://github.com/arvidn/libtorrent/blob/0061352077ff53ff9dd50d69957fb2ee10fd34e5/src/torrent_info.cpp#L1550

**Comment by arvidn** [comment]
`parse_info_section()` does a lot of work though. In fact, it does all of the parsing of files. did that call take multiple seconds to complete?

**Comment by glassez** [comment]
> `parse_info_section()` does a lot of work though. In fact, it does all of the parsing of files. did that call take multiple seconds to complete?

It is call to `extract_files()` at line 1269 that is executed for torrent mentioned above about 20 secs on Ryzen 5 2600X: https://github.com/arvidn/libtorrent/blob/0061352077ff53ff9dd50d69957fb2ee10fd34e5/src/torrent_info.cpp#L1269

**Comment by arvidn** [comment]
I tested this on a raspberry PI. It's slower, but still pretty far from what you're seeing:

```
$ time ./dump_torrent oldversion.com_Sept2019.torrent >/dev/null

real	0m2,207s
user	0m2,103s
sys	0m0,100s
```

**Comment by glassez** [comment]
> I tested this on a raspberry PI. It's slower, but still pretty far from what you're seeing:
> 
> ```
> $ time ./dump_torrent oldversion.com_Sept2019.torrent >/dev/null
> 
> real	0m2,207s
> user	0m2,103s
> sys	0m0,100s
> ```

Well, that's weird... I'll try to figure out what's going on.

**Comment by arvidn** [comment]
To be clear, 2 seconds is still pretty slow. I'll look closer at what's going on. It might be simpler to optimize this a bit than to introduce a progress callback.

Ideally a callback would be called regularly based on wall clock time, and it might significantly slow down the parsing

**Comment by glassez** [comment]
> Well, that's weird... I'll try to figure out what's going on.

It looks like the problem is in the debug build that I use most of the time. But, damn it, I would not have thought that it could run several dozen times slower than the release build does. I usually didn't notice such a slowdown.

**Comment by arvidn** [comment]
the reason this torrent is slow to parse is not exactly because it has many files, but because it has many (unique) directories. libtorrent does not handle this in the most efficient way right now.
