### ISSUE TITLE
assert in peer_class_pool::new_peer_class

### ISSUE THREAD

**Issue by MassaRoddel** [arvidn/libtorrent#706]
libtorrent version (or branch): master

platform/architecture: win64

compiler and compiler version: VS2013

I am getting this assert: TORRENT_ASSERT(m_peer_classes.size() < 0x100); in  peer_class_pool::new_peer_class called from

MooPolice.exe!assert_fail(const char * expr=0x000000014066fa48, int line=90, const char * file=0x000000014066fa20, const char * function=0x000000014066f9f0, const char * value=0x0000000000000000, int kind=0) Zeile 298	C++
MooPolice.exe!libtorrent::peer_class_pool::new_peer_class(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & label={...}) Zeile 90	C++
MooPolice.exe!libtorrent::torrent::setup_peer_class() Zeile 8623	C++
MooPolice.exe!libtorrent::torrent::set_limit_impl(int limit=51200, int channel=0, bool state_update=true) Zeile 8613	C++
MooPolice.exe!libtorrent::torrent::set_upload_limit(int limit=51200) Zeile 8587	C++

Is that some kind of number of torrent limit?

**Comment by arvidn** [comment]
I imagine that assert is there because peer class IDs are kept in a uint8 somewhere

**Comment by arvidn** [comment]
it's a limit on the number of peer classes btw. and it looks like the logic is incorrect. it's appears to be creating a peer class per torrent, rather than globally (per session)

**Comment by arvidn** [comment]
ah, no. this is by design. when you set a rate limit on a torrent, a peer class is created on-demand associated with it, to hold the setting. But I suppose that internal limit on 255 peer classes might be low.

**Comment by arvidn** [comment]
Does this patch fix this issue? https://github.com/arvidn/libtorrent/pull/707

**Comment by MassaRoddel** [comment]
seems to work
