### ISSUE TITLE
Sequential download

### ISSUE THREAD

**Issue by Banou26** [arvidn/libtorrent#7067]
libtorrent version (or branch): Python 2.0.7
platform/architecture: Win 64 21H2

It seems to me that the sequential download mode doesn't work.
I have tried a few ways to set my torrent as sequential download with none of them effectively working
```python
self.session.apply_settings({
    'auto_sequential': True
})
```
```python
params.flags |= lt.add_torrent_params_flags_t.flag_sequential_download
```
```python
handle.set_sequential_download(True)
```
All of these don't seem to make my torrents download sequentially, ~~i add my torrents with `params.flags &= ~lt.add_torrent_params_flags_t.flag_auto_managed` as i don't want them managed (it's for a server) as the managed mode has some side effects(prioritize some torrents while leaving others) as auto management suggest, that aren't suited for my server implementation.~~

~~Is the sequential download only working for auto managed torrents?~~

For example, with a torrent set as sequential download, i am getting random downloads without priority on the beginning at all, even though i know sequential download doesn't provides any guarantees that they will be in order, it should at least be a little bit sequential, which in my case isn't.
```
0000000000000000000100100000001000000000000000000000100000000000000000000000000000000000000000000111000001000
0100000000000000010000000000000000000000000000000000000000000000000000000000000000000000000100000011000000000
0000000000000000000000010000000000000000000000100000000000000110110000000001000000000011100000000000000000010
0000000100000001100000000000000000000000000010000000000000000000000000000000000000000000000001110000000100000
0000100010000000000000100000010000000000000001000000100000000000000100010000000000000000000000000000000000000
0010110000000000000000000000001100100000000000000000000000000000000000000000000000010000000000010000010100000
0000100000000000000000000000000000000001000000000000000111000000000000000000000000000000001111000000010100000
0000000001000000000000000000001111110000000010001111111000000000000000000000011111100000000000000000010000001
0000000000000000000001100000000000000000000000000000000000110000000000000111111000000000000000000000001000000
0000001111000011111111111110000010000000000000000000000000000000000000001000000000001111100000000010000000000
000000000000000000000000000000000000000000000000000000000000001100000000010000000000000000
```

<details>

<summary>Other examples:</summary>

```
00000000000111100000000000001110000000000000000001001100010100000000000000000111100000000000000100000000
00000000000001000000001100000000111100111000000000000000000111111111111111100000000000011000001111111111
11111111111111111111111000000111100001000000000100000000000000000000000010010000011111111110000000000111
11111111111111101110000000000000000000000011111100000010000000000000000000010000100000000000000100000111
10000000100100011111111000001000000000000000000000011111111111111110000000000100011111111111111111111111
10011010111100000000010000000000000000000000000000000001110010000000000000000101111111111111000011110000
00001000001011111111111011100001111110000111111111111110000000000000011111111111100000011111111100000001
11111110100011111111011111111111111111111111111111111111111111111111111111111111111111111111111111111101
11111111111111111111111111111111111110000000000010111111111111111111111111111111111111100010000000100000
00000000011111111110000010000000111111111111100111111100000111111111111111111111111111111111110000001000
00000001111111111111111111111111111111100000000111111111111110000011111111111100000111111100011111111111
111111111111111111111111111110000000
```
</details>

Should i rely entirely on `piece_priority` and `set_piece_deadline` instead?

Edit: Just tried with the auto managed mode, the sequential flag doesn't seem to make the torrents download sequentially either

**Comment by arvidn** [comment]
I cannot reproduce this. I tested this in `client_test`. it uses
```
h.set_flags(~ts.flags, lt::torrent_flags::sequential_download);
```

![Screenshot from 2022-09-16 14-08-54](https://user-images.githubusercontent.com/661450/190635646-f17eba19-8975-4c0c-b94a-88b0092632e3.png)

**Comment by Banou26** [comment]
For some reason trying in a clean repo sequential download works properly, i'm guessing the issue is the wheel i installed for typings that breaks it, is it possible to get python typings for future releases?

**Comment by arvidn** [comment]
> is it possible to get python typings for future releases?

I don't know how to do that, but patches are welcome!
