### ISSUE TITLE
replace incompatible characters like colon 

### ISSUE THREAD

**Issue by jaccc** [arvidn/libtorrent#7072]
libtorrent version (or branch):
2.0.7.0

platform/architecture:
Gentoo Linux

compiler and compiler version:
gcc 11.3
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
QBittorrent 4.4.5 on Linux can download files with colon, but such files can't be copied using rsync to Windows originated filesystems like exFAT.

**Comment by arvidn** [comment]
changing how filenames are sanitized can be a pretty intrusive change. It effectively means upgrading your client may no longer find the files the previous version downloaded.

Currently, libtorrent used os-specific rules for filename sanitization. It has trade-offs. The upside is that you get the most out of what your operating system supports, and the downside is (as you highlight) poor interoperability between operating systems.

The alternative (as I imagine you're proposing) would be to use the lowest common denominator for all systems.

Presumably there are linux and MacOS users that would disagree with the emphasis of supporting interoperability with windows, so you may need to make some compelling arguments in favour of that.

Here's some more background if you're interested: https://blog.libtorrent.org/2014/12/filenames/

**Comment by jaccc** [comment]
New version of client can automatically rename non-universal filenames.
exFAT is usually only or preferred option for microSD cards and USB drives connected to phones and tablets.
