### ISSUE TITLE
move_storage() not asynchronous when low IO happens

### ISSUE THREAD

**Issue by murder** [arvidn/libtorrent#708]
> 0.15.10.0 on amd64
> 
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.7/lto-wrapper
> Target: x86_64-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Debian 4.7.2-5' --with-bugurl=file:///usr/share/doc/gcc-4.7/README.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --with-arch-32=i586 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
> Thread model: posix
> gcc version 4.7.2 (Debian 4.7.2-5) 
> 

This happens when I have a destination with low IO throughput

Eg: My setup is basically:

- Download to SSD mountpoint (/data/fast/incomplete)
- Once finished, move to low rpm HDD big storage (/data/slow/new)

So, when this process happens, everything that the client (libtorrent) is doing is stalled and waits for the copy to happens.

Reproduce:

1. Add various downloads and start them (around 10gb+ size)
2. Move any finished downloads to a low IO mountpoint (eg: USB 2.0 External HDD)
3. Notice the non-finished downloads stall

Related to move_storage() - ​http://www.rasterbar.com/products/libtorrent/manual.html

**move_storage()**

```
void move_storage(std::string const& save_path) const;
void move_storage(std::wstring const& save_path) const;

```

> Moves the file(s) that this torrent are currently seeding from or downloading to. If the given save_path is not located on the same drive as the original save path, The files will be copied to the new drive and removed from their original location. **This will block all other disk IO**, and other torrents download and upload rates may drop while copying the file.

This affects various client implementations that rely on libtorrent.
Can't this be fixed (featured)?

**Comment by arvidn** [comment]
I believe if you increase the number of disk I/O threads, the impact of copying the files will be less significant. Each torrent that's copying should only be blocking a single disk thread. How many threads are you using? (i.e. settings_pack::aio_threads)

**Comment by arvidn** [comment]
oh, are you using libtorrent 0.15? (that's 6 years old). try the latest release, 1.1
