### ISSUE TITLE
Support for WASM

### ISSUE THREAD

**Issue by 3unjee** [arvidn/libtorrent#7091]
Dear libtorrent maintainers,

Has anyone tried building libtorrent against Web Assembly or is this something that could be supported in the future ?

**Comment by arvidn** [comment]
I have not tried to build libtorrent for WASM. I would expect there might be a few hurdles to make it work:

1. OpenSSL or libtls would probably have to be replaced
2. BSD sockets (as used by boost.asio) might have to be replaced
3. Disk I/O may need to be replaced
4. the thread may need to be replaced by something else

**Comment by 3unjee** [comment]
Thank you for the comprehensive reply. As far as I can't tell that's not a trivial mater.

**Comment by frank-dspeed** [comment]
i have invested into it and lib boost is 100% a blocker we would need to integrate that some how. I get Easy WASM builds working when i switch to c  from libc but i do not want to hard fork this only for that and code transpilers that i maintain. 

When the project maintainer will update his project to lib c a WASM build is not far away .

**Comment by ArniDagur** [comment]
I would love to see `libtorrent` built for WASM. `libtorrent` is the most feature complete and widely deployed BitTorrent implementation by far. However, a huge C++ codebase which accepts network connections from stranger's computers is just begging for trouble. Being able to sandbox `libtorrent` using WASI would be great.

**Comment by arvidn** [comment]
@frank-dspeed Would you mind elaborating? clearly not *all* of boost would be a blocker for a WASM build.
Are you suggesting you have managed to port all of the C++ standard library to WASM? including `std::thread`?
When you say "lib c", do you mean the C standard library (without the C++ standard library)?

I remain skeptical of the claim "if only ..." a WASM build is not far away.

**Comment by frank-dspeed** [comment]
but it makes no sense to transfer this implementation to wasm it would make much more sense to split this up into modules thats what i am preparing at present because we do not want to load everything always. I need this dynamic for my New Project which is mainly a Universal Component System Based on Chromium/v8 Spidermonkey/Webkit i will contrib indipendent wasm modules if you want that.
