### ISSUE TITLE
For a multi-file torrent, is it possiable to add url for each file

### ISSUE THREAD

**Issue by shughuangQQQ** [arvidn/libtorrent#7117]
For a multi-file torrent in HTTP seed, url should point to a directory containing a directory with the same name as this torrent, and all the files of the torrent in it.

This rule need me to write some kind of proxy between my storage and HTTP seed instead directly use the URL provided by my storage(for example I need deploy proxy to forward request to webhdfs URL or s3 pre-signed URL)
Is that any way to use HTTP seed for multi-file torrent without such forward(or specify a URL for each file in multi-file torrent)?

**Comment by arvidn** [comment]
there is no way to do this. However, you don't need to proxy requests, you can redirect requests for files to their underlying URL.
