### ISSUE TITLE
aux::time_now() used in comparisons with clock_type::now()

### ISSUE THREAD

**Issue by jonathanmcdougall** [arvidn/libtorrent#712]
RC_1_1, windows 10 x64, visual c++ 2015 update 2

I just had a division by zero on torrent.cpp:8421:

    time_point now = aux::time_now();
    boost::int64_t lhs_time_connected = total_seconds(now - lhs->connected_time());
    boost::int64_t rhs_time_connected = total_seconds(now - rhs->connected_time());

    lhs_transferred /= lhs_time_connected + 1;      // <--- here
    rhs_transferred /= (rhs_time_connected + 1);

Turns out `aux::time_now()` is using a "cached time" that's supposed to be updated every 100 ms, but this depends on the speed of the session thread. If things slow down, the cached time can be quite behind.

The problem is that there is at least one comparison between the cached time and the actual time. In the code above, the call to `peer_connection::connected_time()` returns `m_connect`, which is set in `peer_connection::start()` using `clock_type::now()`. If the session thread is running slow, this can be in the future compared to `aux::time_now()`. So `lhs_time_connected` can end up being rounded to `-1`, giving a division by zero.

A quick fix for this particular crash would be to use `clock_type::time_now()` for the comparison, but I'm not sure about the impact on performance. Both `lhs_time_connected` and `rhs_time_connected` could also be clamped to 0.

A more general fix would be to make sure "cached time" is never compared to "actual time", unless negative time differences are acceptable.

**Comment by arvidn** [comment]
thanks for this report. You're right about the cached time and actual time being fundamentally different domain and should not be mixed. I think the long term solution is to define a separate time_point and time_duration type for the cached time domain, to make the type system check for mixing.

For the short term fix, I will try to make anything that doesn't require high precision to use the cached time, i.e. make sure connected_time() returns a cache time delta

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/719

**Comment by jonathanmcdougall** [comment]
I can't reproduce this particular instance of division by zero and based on the commit, this looks fixed. I agree with the long term fix of having discrete types for both, it'll save you lot of headaches in the future.

**Comment by arvidn** [comment]
I have a (growing) patch locally where I separate these two clocks. once it builds again I'll see if I like the result and possibly push it to master

**Comment by jonathanmcdougall** [comment]
I can have a look at it if you want to. I was actually thinking of tackling this in the next few days.

**Comment by arvidn** [comment]
sorry for the delay, I pushed what I have so far into a branch (off of master) "cached-clock" [ https://github.com/arvidn/libtorrent/tree/cached-clock ]. It does not yet compile. There's a lot of ripples where the timestamp type needs changing.

If you're up for it, either pull that branch and submit PRs against this branch, or get it to work and submit a PR against master.
