### ISSUE TITLE
Add a way to stop after metadata received

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#7125]
It would be useful to have some analog of `stop_when_ready` flag to tell libtorrent to stop torrent after metadata is received.
Ideally it would be also useful to have a way to tell libtorrent to stop torrent after metadata is received and checking is done. It could be implemented by redefining behavior of `stop_when_ready` in case it is combined with new flag (since otherwise it is meaningless to set them at the same time).

**Comment by arvidn** [comment]
the way this is typically done is to set all file priorities to 0. The main problem is that you don't know how many files there are until metadata is received. However, in `RC_2_0` I've added a flag [default_dont_download](https://github.com/arvidn/libtorrent/blob/RC_2_0/include/libtorrent/torrent_flags.hpp#L292) which makes the default download priority 0, and files can then be picked by setting their priority to non-zero in `add_torrent_params::file_priorities`.

This new flag can be used to stop (or at least not download anything) when the metadata is received. It will technically still upload that metadata to peers requesting it still.

**Comment by glassez** [comment]
@arvidn 
What you're suggesting looks like a workaround for the task I'm talking about. It is much better to have a direct way that does not affect other aspects. In addition, your way will "erase" the info about pre-selected files from the magnet link.

**Comment by ukoz** [comment]
```
lt::metadata_received_alert* p
lt::torrent_handle h = p->handle;
if (h.is_valid()) h.pause(libtorrent::torrent_handle::graceful_pause);
```

**Comment by arvidn** [comment]
@ukoz that code has a race. Pieces may be downloaded while delivering the alert and before the pause message reaches the network thread

**Comment by glassez** [comment]
> @ukoz that code has a race. Pieces may be downloaded while delivering the alert and before the pause message reaches the network thread

@ukoz 
Welcome to asynchronous world.
