### ISSUE TITLE
some alerts can be posted before add_torrent_alert

### ISSUE THREAD

**Issue by jonathanmcdougall** [arvidn/libtorrent#713]
RC_1_1, windows 10 x64, visual c++ 2015 update 2

There are cases where torrent alerts are posted _before_ `add_torrent_alert`. It makes handling alerts more difficult because I cannot rely on a specific alert to initialize whatever data structure I'm using internally to track torrents and handles. Any torrent alert could be the first one I get about a specific torrent.

What makes this worse is that depending on timing, `add_torrent_alert` could be retrieved in a different call to `pop_alerts()`. Since alerts get destroyed on the next call to `pop_alerts()`, I can't even keep them around. There was a time when `pop_alerts()` would require the caller to delete the alerts (so I could keep checking them until I got an `add_torrent_alert`), but not anymore.

I've found at least two alerts that seem to be consistently posted early: `fastresume_rejected_alert` and `state_changed_alert`. I haven't tracked down the former yet, but a `state_changed_alert` is posted on torrent.cpp:850, when adding a torrent from a magnet link or (I think) a hash only, but without a torrent file. With the following stack trace:

    torrent::set_state() Line 11854
    torrent::start() Line 851
    aux::session_impl::add_torrent_impl() Line 4932
    aux::session_impl::add_torrent() Line 4741
    aux::session_impl::async_add_torrent() Line 4702

The `add_torrent_alert` would be generated in `session_impl::add_torrent()`, just _after_ the call to `add_torrent_impl()`, which will eventually call `torrent::set_state()`. This will generate a `state_changed_alert`:

    // we need to start announcing since we don't have any
    // metadata. To receive peers to ask for it.
    set_state(torrent_status::downloading_metadata);    // <-- here
    start_announcing();

I guess any torrent alert generated from `session_impl::add_torrent_impl()` would be problematic.

The fix would be complicated, I think. It would require splitting up `session_impl::add_torrent_impl()` so that bookkeeping happens first (finding duplicates, inserting into `m_torrents`, etc.), followed by a `add_torrent_alert`. Only then would the `add_torrent_params` be parsed and the torrent started properly.

**Comment by arvidn** [comment]
couldn't add_torrent_impl() post the alert before calling start?

**Comment by arvidn** [comment]
could you try this patch? https://github.com/arvidn/libtorrent/pull/717

**Comment by jonathanmcdougall** [comment]
I did some limited testing, but I cannot reproduce my two test cases with `fastresume_rejected_alert` and `state_changed_alert`. This looks fixed.
