### ISSUE TITLE
Adding not auto_managed torrent results in paused state

### ISSUE THREAD

**Issue by giesmininkas** [arvidn/libtorrent#7136]
libtorrent version (or branch): 2.0.7
platform/architecture: Linux 5.10.140 (2022-09-02) x86_64 GNU/Linux
compiler and compiler version: clang-14

When adding torrent with `auto_managed` and `paused` flags unset the added torrent is in paused state. 
Is this a bug, or do I need to have some additional logic to add the torrent in regular download mode?

Example code:
``` C++
lt::add_torrent_params params{};
params.flags &= ~lt::torrent_flags::auto_managed;

lt::error_code error;
auto torrent_handle = session.add_torrent(params, error);
```

**Comment by joriscarrier** [comment]
hi,

can you try this:

```c++
lt::add_torrent_params params{};
params.flags &= ~(lt::torrent_flags::paused | lt::torrent_flags::auto_managed);
```

**Comment by giesmininkas** [comment]
Hi. Yes. I've found it a bit later after writing the ticket.

As far as I see, the paused flag is set by default. 
I think this could be reflected in the documentation.

**Comment by joriscarrier** [comment]
@giesmininkas can you close this issue ?
