### ISSUE TITLE
Non-automanaged torrent gets randomly paused

### ISSUE THREAD

**Issue by giesmininkas** [arvidn/libtorrent#7137]
libtorrent version (or branch): 2.0.7
platform/architecture: Linux 5.10.140 (2022-09-02) x86_64 GNU/Linux
compiler and compiler version: clang-14

A torrent gets randomly paused even though it's not an auto-managed torrent. Happens very rarely with only certain big torrents.

Not sure how to even start debugging it, so thanks for any suggestions.

**Comment by joriscarrier** [comment]
hi,

torrents are paused when a session or torrent error is encountered (auto-managed or not).

Do you have any `session_error_alert` or `torrent_error_alert`?

**Comment by joriscarrier** [comment]
It seems that the save path defined in `add_torrent_params` is wrong. but hard to say without more info

**Comment by giesmininkas** [comment]
No, the save path is right. As I've mentioned, it happens very rarely (I think I've seen that with total of maybe 5 different torrents in ~1.5 years of using the library). The path is right, and there are more different files in the same torrent created and downloaded successfully. Also, it fails with different files between different runs, but that is probably because of different pieces downloaded. The same errors happen with any save path in `add_torrent_params` that I've tested.

My code for adding the torrent in this case:
``` C++
lt::error_code error {};
auto params = lt::parse_magnet_uri(uri, error);

/* error handling */

params.save_path = /* path checked to be correct */;
params.max_connections = /* value from settings */;
params.flags &= ~lt::torrent_flags::auto_managed;
params.flags &= ~lt::torrent_flags::paused;

auto torrent_handle = _params.session.add_torrent(add_torrent_params.value(), error);
```

What information would help more with diagnosing this issue?

**Comment by giesmininkas** [comment]
I've managed to create a torrent which reproduces this issue: 
[error.torrent.zip](https://github.com/arvidn/libtorrent/files/9757792/error.torrent.zip)

Same behavior persists with both, sparse and full file allocation modes. 
Hope this helps in further debugging.

**Comment by giesmininkas** [comment]
Seems like the current RC_2_0 works.

**Comment by joriscarrier** [comment]
@giesmininkas can you close this issue ?

**Comment by giesmininkas** [comment]
Hi. Yes. I think it's resolved.
