### ISSUE TITLE
Prevent unrelated files from being overwritten

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#7138]
_(This Issue is extracted from discussion 
started at https://github.com/qbittorrent/qBittorrent/issues/7146#issuecomment-1272293815.)_

Currently, when libtorrent starts processing an existing file (either when adding a new torrent, or when moving an existing one with `dont_replace` flag, when the file name matches the name of one of the files belonging to the torrent), it "naively" believes that this file belongs to the torrent. And if, when checking hashes, the hash of some piece does not match, then such a piece is considered not downloaded. Because of this behavior, any unrelated file with the matched name is simply considered by libtorrent as not having any downloaded piece, as a result of which such a file is overwritten by a file from the torrent, which is undesirable behavior from the point of view of users.
As mentioned in the linked Issue, it would be nice to make the initial file check smarter, or at least make the behavior described above less "naive".

**Comment by glassez** [comment]
There are three possible variants of the existing file in relation to torrent:
1. Related file that has all the data, i.e. complete file
2. Related file that partially has the data, i.e. incomplete file
3. Unrelated file

So, in order to make the behavior less "naive", libtorrent could set an error and pause the torrent when any unrelated file is found, thereby preventing unrelated files from being unexpectedly overwritten. This will still allow overwriting such a file if necessary, if the user explicitly wants it (by clearing error and resuming the torrent).

**Comment by glassez** [comment]
> either when adding a new torrent, or when moving an existing one with `dont_replace` flag

Apparently, the key action is checking files, so it doesn't matter what it is initiated by, adding a new torrent, moving storage, or just forced rechecking, at the end of it the torrent should get an errored status if at least one unrelated file is found.

**Comment by glassez** [comment]
@arvidn, ping, in case you didn't notice it.

**Comment by AllSeeingEyeTolledEweSew** [comment]
How would libtorrent know if a file is "related" or not?

**Comment by arvidn** [comment]
For example how I outline above; if a file contains non-zero pieces that fail the hash check (where all blocks are non-zero, naturally)

**Comment by glassez** [comment]
> How would libtorrent know if a file is "related" or not?

1. If file matches the size and all the piece hashes it is exactly "related".
2. If at least one piece hash matches (especially if size is matches too) it is highly likely "related" file (incompletely downloaded previously).
3. If no piece hash matches but only size it is probably "related" file (only preallocated previously).
4. If neither size nor any piece hash matches it is highly likely "unrelated" file.

So if it falls in "errored" state at least in case 4. it would be really better than currently. And I believe it should cover most of regular cases.

**Comment by AllSeeingEyeTolledEweSew** [comment]
It seems like there are edge cases:
* What if the file was partially downloaded in sparse mode? IIUC the file size may be smaller than the fully-allocated size.
* Files smaller than 1 piece may not have enough data to hash check

Is there a reason these checks couldn't be done in the app, prior to calling `move_storage()`?

The goal seems to be to answer "did the user really mean to do X?". That's ill-defined, and may be different for different apps. Libtorrent's codebase is already huge. Personally I think there needs to be a really compelling reason to extend that codebase with fuzzy logic like this.

**Comment by glassez** [comment]
> The goal seems to be to answer "did the user really mean to do X?". That's ill-defined, and may be different for different apps.

This is completely wrong. The goal is to prevent something that the user definitely does not want (i.e. overwriting the files that are unrelated to torrent and only have the matched names by accident).

**Comment by arvidn** [comment]
a change that would be simple to make is; if `no_verify_files` flag nor the `seed_mode` flag is set when adding a torrent, any existing file is considered an error.

It would support the following cases:

1. When starting to seed existing files for the first time: specify the `seed_mode` flag. Existing files are expected and assumed to match
2. When starting a download for the first time. Do not set `seed_mode` nor `no_verify_files` flags. Existing files are considered an error (with this proposal)
3. When resuming a torrent from a previous session (either downloading or seeding), set the `no_verify_files` flag. Existing files are expected to belong to the torrent already

Perhaps a better way would be to add a new flag saying any existing files are to be considered an error. Say, `no_overwrite_existing` or something like that.

**Comment by glassez** [comment]
> 3\. When resuming a torrent from a previous session

This case is not relevant at all.

As for 1. and 2.
The prerequisite is that user doesn't know enough about the files on disk and content of added torrents. It's either about magnet links, or about some automated ways to add torrents, for example from RSS.
I don't want to worsen the current UX by killing the ability to download previously unfinished torrents (again, I don't mean torrents from a resumed session, but those that were either incompletely downloaded by another torrent client, or transferred from another computer, etc.).

File checking should be done completely as currently and only then some more advanced analysis could be performed. And if it detects any possible unrelated files, then it should prevent them from being overwritten without explicit permission from the user side. That's the whole point.
BTW, now it seems to me that it can even be implemented at the application level (of course, not without using tricks with libtorrent extensions, which I have to use for closer integration with libtorrent in such cases).

**Comment by arvidn** [comment]
> This case is not relevant at all.

You mean it's not relevant to this ticket, right? It *is* a case that needs to be supported,

**Comment by arvidn** [comment]
>  then it should prevent them from being overwritten without explicit permission from the user side.

The "explicit permission" could be in the form of a `torrent_flag` to `add_torrent_params` or by `clear_error()` on the torrent after being stopped with an error.

Did you have any other mechanism in mind?

**Comment by glassez** [comment]
> 



> > This case is not relevant at all.
> 
> You mean it's not relevant to this ticket, right? It _is_ a case that needs to be supported,

It **isn't** a case that needs to be supported.
Of course unless resume data is rejected so libtorrent check the files from the scratch.

**Comment by arvidn** [comment]
> It isn't a case that needs to be supported.
> Of course unless resume data is rejected and libtorrent checks the files from the scratch.

It was added as part of this discussion: https://github.com/arvidn/libtorrent/issues/5163

**Comment by glassez** [comment]
> > It isn't a case that needs to be supported.
> > Of course unless resume data is rejected and libtorrent checks the files from the scratch.
> 
> It was added as part of this discussion: #5163

Sorry, I'm confused. What do you mean?

I mentioned that the case of restoring torrents from a previous session (neither with `no_verify_files` flag nor without it) does not apply to this Issue.

**Comment by glassez** [comment]
> > then it should prevent them from being overwritten without explicit permission from the user side.
> 
> The "explicit permission" could be in the form of a `torrent_flag` to `add_torrent_params` or by `clear_error()` on the torrent after being stopped with an error.

Explicit permission to overwrite a "suspicious" files is `clear_error()` (after some file has been identified as possibly unrelated).
But as I have repeatedly mentioned above, there may also be a global `session` setting and/or `torrent_flag` in `add_torrent_params` to enable/disable this advanced analysis (and optionally adjust its sensitivity).
> Did you have any other mechanism in mind?

No.

**Comment by calumapplepie** [comment]
@arvidn Should this be fixed in libtorrent? Yes.   Will I be submitting a fix for it in qBittorrent instead? Also yes.  Was this issue closed for being "stale" without any good reason? You betchya.

**Comment by luzpaz** [comment]
bumping for re-open
