### ISSUE TITLE
the criminal team

### ISSUE THREAD

**Issue by JhonParenteses** [arvidn/libtorrent#7139]
**Please provide the following information**

libtorrent version (or branch):6.17.0.4792 (9a17ce2)

platform/architecture:windows 10

compiler and compiler version: agust, 18,2022

please describe what symptom you see, what you would expect to see instead and
how to reproduc it
improper handling and suspicious updates, hacker attacks and faulty dll's that make it impossible for repositories to work.

**Comment by master255** [comment]
What?
