### ISSUE TITLE
Missing static_category documentation for some alerts

### ISSUE THREAD

**Issue by jonathanmcdougall** [arvidn/libtorrent#714]
RC_1_1

The `static_category` field is missing for alerts where the definition is split over multiple lines, such as for [`fastresume_rejected_alert`](http://www.libtorrent.org/reference-Alerts.html#fastresume_rejected_alert). The code looks like this:

    static const int static_category = alert::status_notification
        | alert::error_notification;

and the resulting html looks like this:

    struct fastresume_rejected_alert final : torrent_alert
    {
       virtual std::string message () const override;
       char const* file_path () const;
    
       | alert::error_notification;
       error_code error;
       char const* operation;
    };

**Comment by arvidn** [comment]
I've tried to fix this in the past by restoring the initialization to be on a single line. perhaps I should look into fixing the documentation generation script..

**Comment by jonathanmcdougall** [comment]
I had a quick look at `gen_reference_doc.py`. I gave up.

**Comment by arvidn** [comment]
I think this fixes it. hopefully it doesn't introduce any regressions. https://github.com/arvidn/libtorrent/pull/716

**Comment by jonathanmcdougall** [comment]
I've regenerated the docs and looked at `reference-Alerts.html`, that particular problem looks fixed.
