### ISSUE TITLE
error: The requested operation cannot be performed on a file with a user-mapped section open

### ISSUE THREAD

**Issue by 13xforever** [arvidn/libtorrent#7140]
libtorrent version (or branch): 2.0.7.0 (through qBittorrent v4.4.5)

platform/architecture: Windows x64 (running on Windows 11 22H2)

compiler and compiler version: not sure what official builds use

Downloading torrent to the folder where some files already exists, somwhere along the process it errored out (I didn't see whether that happened during recheck or during actual download afterwards).

This is a fairly common scenario, but I never had this error before. 
~~Pausing, force rechecking, and resuming doesn't help.~~ Actually this error seems to happen once per file that needs to be truncated?

```
11.10.2022 19:05 - File error alert. Torrent: "<snip_torrent_name>". File: "<snipped_file_path>". Reason: <snip_torrent_name> file_truncate (<snip_file_path>) error: The requested operation cannot be performed on a file with a user-mapped section open
```

One additional note: target file is on ReFS with integrity streams enabled, though I'm not sure this is relevant in the end.

**Comment by arvidn** [comment]
when you say it happens for files that need to be truncated, do you mean you start a download to a directory that already have some of the files, but they are too large?

**Comment by 13xforever** [comment]
I think in this particular case the layout between torrents has changed, so some chunks shared between files have changed, so it had to truncate and re-download a bunch of files, but in general yes, you can probably reproduce it with any torrent if you modify the files by adding some extra data

**Comment by arvidn** [comment]
I'm quite confident there is a unit test covering this case. I suspect there is some other day factor involved too

**Comment by arvidn** [comment]
The tests don't run on ReFS for example

**Comment by 13xforever** [comment]
So, I did some tests.

1. if you append extra data at the end of any file inside torrent, then add the torrent and point to existing files (with appended data), it will pass check and **will not** even attempt to truncate the extra bytes. Even if you pause and force recheck.
2. in the same scenario, if you _insert_ some data in the middle of the file, it'll truncate and re-download the rest of that file correctly (and may trigger truncation on adjacent files too if they have appended data at the end)
3. I was not able to reproduce truncation exception yet, so it's obviously some edge case (and as I said, I haven't had that error before despite this being a common scenario)

**Comment by arvidn** [comment]
in recent versions of libtorrent, files aren't automatically truncated. instead there's an alert posted to indicate that there are files that are too large, deferring to the client to call a new function to truncate the files. It's possible that if the client calls the function to truncate the files while the torrent is active (i.e. not stopped) it could fail with the error you posted.

**Comment by 13xforever** [comment]
if there's anything I hate the most, it's the bots like this one; how to make anyone lose any will to contribute to anything in the future 101

**Comment by arvidn** [comment]
would you prefer some other name for the the "stale" tag? or do you just not like that inactive tickets are identified at all?

**Comment by 13xforever** [comment]
I despise the whole premise behind the auto close bots. All they do is harass the contributors/reporters, hide valid issues for the sake of appearances, and discourage any interaction that's not a five-minute fix of a trivial issue.

There's plenty enough arguments from [the last time](https://twitter.com/github/status/1580826746294652929) GitHub tried to spotlight it. I'd link more thorough discussions from that to not beat the dead horse, but most people have moved from twitter and their accounts are gone.

**Comment by arvidn** [comment]
so the "closed" state is interpreted as "not an issue" rather than: "nobody is working on this". Would it be better to set the "nobody is working on this"-tag instead of closing?

**Comment by 13xforever** [comment]
If you need special tags for organizational purposes, then sure. But closing issues without human oversight and reasonable explanation/solving the underlying issue will never have good optics.

**Comment by paxter** [comment]
Unfortunately, it's not the first time, that stale bot is closing serious open issues. Project management of libtorrent really need some improvements.

**Comment by arvidn** [comment]
surely the problem is that nobody is working on important issues, not that they are closed (they are never deleted)

**Comment by paxter** [comment]
For me a closed issue means that it's not an issue and/ will never be fixed. That's an anti-pattern and should be prevented in projects like this.
