### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by DanieleAlessandro98** [arvidn/libtorrent#7142]
**Please provide the following information**

libtorrent version (or branch): Current version (libtorrent-2.0.7)
platform/architecture: Windows
compiler and compiler version: Visual studio 2019
<br>
Hi.
I'm trying to update an old project that used libtorrent 1.1.12 (so libtorrent 1.1.12 to libtorrent current version).
When i compile it, i've these warnings:

```
warning C4996: 'libtorrent::session::session': was declared deprecated
warning C4996: 'libtorrent::session_handle::set_max_half_open_connections': was declared deprecated
warning C4996: 'libtorrent::session_handle::set_max_uploads': was declared deprecated
warning C4996: 'libtorrent::session_handle::set_max_connections': was declared deprecated
warning C4996: 'libtorrent::session_handle::listen_on': was declared deprecated
```

So my questions are:

1. What is wrong with initializing "ses" in this way? Why does it report the warning?
2. What about session_handle methods warnings? I haven't found any similar enums/functions in v2. For example in settings_pack enum i haven't found anything about "half_open_connections", "max_uploads" or "max_connections".
3. As for listen_on, i saw in the documentation that i can use settings_pack::listen_interfaces. However, i no longer pass "ec" as a parameter. So how can i perform the check on the error_code that is right after?
4. In this case, is it a good practice to disable all warnings?
With "#pragma warning(disable: 4996)"?
<br>
Finally, this is a part of the project code that reports the warnings.

```
bool Patcher::Begin()
{
    ses = new session(                                                      // warning C4996: 'libtorrent::session::session': was declared deprecated
        fingerprint("LT", LIBTORRENT_VERSION_MAJOR, LIBTORRENT_VERSION_MINOR, 0, 0),
        session::add_default_plugins
    );
    
    settings_pack settings;
    settings.set_int(settings_pack::alert_mask, alert_category::status | alert_category::error);
    // ... other settings

    ses->set_max_half_open_connections(stConfig.maxHalfOpenConnections);    // warning C4996: 'libtorrent::session_handle::set_max_half_open_connections': was declared deprecated  
    ses->set_max_uploads(stConfig.maxUploadsPerSession);                    // warning C4996: 'libtorrent::session_handle::set_max_uploads': was declared deprecated
    ses->set_max_connections(stConfig.maxConnectionsPerSession);            // warning C4996: 'libtorrent::session_handle::set_max_connections': was declared deprecated

    std::pair<int, int> portRange(stConfig.minPort, stConfig.maxPort);
    error_code ec;

    ses->listen_on(portRange, ec, nullptr, 0);                              // warning C4996: 'libtorrent::session_handle::listen_on': was declared deprecated
    if (ec.value() != 0)
        // ...
        return false;

    ses->apply_settings(settings);
    return true;
}
```

Thank you.

**Comment by arvidn** [comment]
> 1. What is wrong with initializing "ses" in this way? Why does it report the warning?

The fingerprint was moved to the settings_pack, which is the way all session settings are handled now. The main reason to transition to settings_pack was to be able to add new settings without breaking ABI, for point-releases. The recommended way to initialize a session is now to pass it a session_params, which contains a settings pack and also flags. That way, settings are set before the thread is started and sockets are opened.

> 2. What about session_handle methods warnings? I haven't found any similar enums/functions in v2. For example in settings_pack enum i haven't found anything about "half_open_connections", "max_uploads" or "max_connections".

the `half_open_connections`-feature has been removed. It was primarily a work-around for Windows XP until service pack 2.

They remaining settings have been moved into settings_pack."max_connections" is called [connections_limit](http://libtorrent.org/reference-Settings.html#connections_limit) and "max_uploads" is called [unchoke_slots_limit](http://libtorrent.org/reference-Settings.html#unchoke_slots_limit).

> 3. As for listen_on, i saw in the documentation that i can use settings_pack::listen_interfaces. However, i no longer pass "ec" as a parameter. So how can i perform the check on the error_code that is right after?

Any failure to open a socket is reported asynchronously via [listen_failed_alert](http://libtorrent.org/reference-Alerts.html#listen_failed_alert)

> In this case, is it a good practice to disable all warnings? With "#pragma warning(disable: 4996)"?

These functions and overloads will be removed eventually, so I would suggest either updating to use the newer API or at least leave the warnings enabled to advertize that it may break with a future version of libtorrent.

**Comment by DanieleAlessandro98** [comment]
> > 1. What is wrong with initializing "ses" in this way? Why does it report the warning?
> 
> The fingerprint was moved to the settings_pack, which is the way all session settings are handled now. The main reason to transition to settings_pack was to be able to add new settings without breaking ABI, for point-releases. The recommended way to initialize a session is now to pass it a session_params, which contains a settings pack and also flags. That way, settings are set before the thread is started and sockets are opened.
> 
> > 2. What about session_handle methods warnings? I haven't found any similar enums/functions in v2. For example in settings_pack enum i haven't found anything about "half_open_connections", "max_uploads" or "max_connections".
> 
> the `half_open_connections`-feature has been removed. It was primarily a work-around for Windows XP until service pack 2.
> 
> They remaining settings have been moved into settings_pack."max_connections" is called [connections_limit](http://libtorrent.org/reference-Settings.html#connections_limit) and "max_uploads" is called [unchoke_slots_limit](http://libtorrent.org/reference-Settings.html#unchoke_slots_limit).
> 
> > 3. As for listen_on, i saw in the documentation that i can use settings_pack::listen_interfaces. However, i no longer pass "ec" as a parameter. So how can i perform the check on the error_code that is right after?
> 
> Any failure to open a socket is reported asynchronously via [listen_failed_alert](http://libtorrent.org/reference-Alerts.html#listen_failed_alert)
> 
> > In this case, is it a good practice to disable all warnings? With "#pragma warning(disable: 4996)"?
> 
> These functions and overloads will be removed eventually, so I would suggest either updating to use the newer API or at least leave the warnings enabled to advertize that it may break with a future version of libtorrent.

Thanks for your reply. I've last question.
What about "file_entry" and torrent_info::file_at?

In the old project it is used like this:
```
	error_code ec;
	bdecode_node e = bdecode(torrentHead, ec);
	torrent_info ti(e);

	const std::string& tname = ti.name();

	const int numFiles = ti.num_files();
	for (int i = 0; i != numFiles; ++i)
	{
		const file_entry& fe = ti.file_at(i);			// warning C4996: 'libtorrent::file_entry': was declared deprecated
									// warning C4996: 'libtorrent::torrent_info::file_at': was declared deprecated
																
		const std::string& filePath = fe.path.c_str();		// warning C4996: 'ibtorrent::file_entry::path': was declared deprecated
		if (filePath.compare(0, tname.length(), tname) == 0)
		{
			// ...
	}
```

**Comment by arvidn** [comment]
> Thanks for your reply. I've last question.
> What about "file_entry" and torrent_info::file_at?

The new API is to ask for various file properties directly from `file_storage` and specify the file index. e.g. `file_size()`, `file_path()` etc., here: http://libtorrent.org/reference-Storage.html#root-ptr-file-path-pad-file-at-root-hash-symlink-file-offset-file-size-mtime-file-name
