### ISSUE TITLE
libtorrent 2.0.8 on Android with NDK 23 and SDK 31

### ISSUE THREAD

**Issue by 3unjee** [arvidn/libtorrent#7181]
Google now enforces SDK 31+ to publish anything on the Play Store. So I had to update my android stack to NDK 23.1.7779620.

Unfortunately libtorrent 2.0.8 does not seem happy in that scenario and I get the following stack when opening / closing multiple torrent / magnets:
![stack](https://user-images.githubusercontent.com/17432415/201493860-7637fb41-df1b-48ac-af47-058d284107f8.png)

NDK 23 seems to be "the culprit" given everything works fine when using NDK 21 / 22, Has anyone encountered the same or could give me pointers on how to debug this further ?

**Comment by master255** [comment]
I stopped posting my app to the Play Store last week.
I recommend that you do the same. They dictate too much to developers and demand too much.
It's not fair to programmers like you. You need more freedom.

Regarding library builds, look towards off-the-shelf libraries. Everything compiles successfully there.
https://github.com/frostwire/frostwire-jlibtorrent
https://github.com/aldenml/libtorrent4j

But do not forget that you still need to write a very complex algorithm of streaming.
Now it seems to me your player doesn't even compete with mine...

**Comment by 3unjee** [comment]
This was caused by a conflicting libc++_shared.so causing random crashes at runtime. So probably unrelated to libtorrent.

**Comment by arvidn** [comment]
thanks for the update. libtorrent depends on exceptions being thrown and caught in the disk I/O, and it looked a bit suspicious to get a `SIGSEGV` in the exception handling itself. So, yeah, another ABI issue.
