### ISSUE TITLE
[Feature request] Chat

### ISSUE THREAD

**Issue by ukoz** [arvidn/libtorrent#7182]
Hi

Back when file transfer was done via BBS systems one little big thing happened: chat while downloading.
Some popular protocols with chat feature were SuperZmodem, HS/Link and few others.
IRC+torrent not usable since peers de-anonymized.

Chat with other torrent peers. Messages can be timestamped. Backlog avail or not. Ofc require support client side. When used to transfer huge backups at workplace gonna be very reliable otherwise you seed to keep chat open.

**Comment by MassaRoddel** [comment]
Security flags in torrents make no sense because clients can simply ignore them.

**Comment by master255** [comment]
You can add chat information to the torrent file as info data field. When downloading, if the client supports this field, it can automatically open a chat with the initiator of the torrent.

**Comment by ukoz** [comment]
Should be done via protocol. External service URL not gonna do.

**Comment by MassaRoddel** [comment]
There has been a chat extension which was supported by libtorrent (LT_Chat). It was removed some/several years ago. It is a libtorrent plugin - not difficult to add again.

**Comment by master255** [comment]
@ukoz  You can add an additional parameter to the protocol handshake and specify there the tcp port number to establish the chat communication. I did so for https protocol data transfer.
