### ISSUE TITLE
Something is wrong with libtorrent

### ISSUE THREAD

**Issue by Wintreist** [arvidn/libtorrent#7183]
I am using libtorrent version 2.0.7.0
On Python 3.8.3
When
`handle = libtorrent.add_magnet_uri(ses, url, params)`
returns: `<ipython-input-6-ee1a6e84bb54>:1: DeprecationWarning: add_magnet_uri() is deprecated`
I found on the Internet what I need to write now: `handle = libtorrent.add_torrent()`
but returns: `AttributeError: module 'libtorrent' has no attribute 'add_torrent'`.
That was the first problem. Now I want that when adding a new torrent, it does not download immediately, but is in a pause state until I want to start, I found a video where `"paused": True` was added to the parameters  `add_magnet_uri`. But now I get an error: `KeyError: 'unknown name in torrent params: paused'`. 

The question is how to work correctly now and what parameter do I need so that the torrent is not automatically downloaded?

**Comment by passiomatic** [comment]
Hi! I'm currently using lib torrent 2.0.7 with Python 3.10.8 and this is how to add a new torrent:

```python 
    
  import libtorrent as lt 
    
  class Torrenter(Thread):
    
    # Setup object and self.session here ...
    
    def add_torrent(self, save_path, magnet_uri):
        params = lt.parse_magnet_uri(magnet_uri)
        params.save_path = save_path
        params.flags |= lt.torrent_flags.duplicate_is_error | lt.torrent_flags.auto_managed
        self.session.async_add_torrent(params)
```

You should check the [simple-client.py][1] example in the repo, on the web you are likely to find outdated example using libtorrent 1.x version. I had a my good amount of headache trying to port older code using 1.x to 2.x. :) 

[1]: https://github.com/arvidn/libtorrent/blob/RC_2_0/bindings/python/simple_client.py

**Comment by Wintreist** [comment]
Thank you, it helped me a lot
