### ISSUE TITLE
(C++20) warning C5054

### ISSUE THREAD

**Issue by pavel-pimenov** [arvidn/libtorrent#7184]
Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.5.0 Preview 1.0 

4>session_stats.cpp
4>C:\vc17\r6xx\libtorrent\include\libtorrent\performance_counters.hpp(440,39): warning C5054: operator '-': deprecated between enumerations of different types
4>settings_pack.cpp
4>C:\vc17\r6xx\libtorrent\include\libtorrent\performance_counters.hpp(440,39): warning C5054: operator '-': deprecated between enumerations of different types

https://github.com/arvidn/libtorrent/blob/95afba30e9acfd8411076a0b05f7ca69bf33b9bb/include/libtorrent/performance_counters.hpp#L463

**Comment by ukoz** [comment]
`/std:c++latest` related, this equals to c++20 in VS 17.4+
https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c5054

libtorrent c++14 or 17
The `CMAKE_CXX_STANDARD` has to be at least 14, but you may want to raise it
to `17` if your project use a newer version of the C++ standard.
https://github.com/arvidn/libtorrent/blob/RC_2_0/docs/building.rst
