### ISSUE TITLE
Wrong windows version being used 

### ISSUE THREAD

**Issue by i96751414** [arvidn/libtorrent#7190]
libtorrent version (or branch):
v2.0.8 / v1.2.18

platform/architecture:
Windows x86/x64

Hi @arvidn .

At the moment, libtorrent is targeting windows vista or later according to https://github.com/arvidn/libtorrent/blob/64817e0e8793d0875fc10245de52ffb2540a223d/CMakeLists.txt#L621.

However, I believe there are some functionalities being used which require windows 7 or later, such as https://learn.microsoft.com/en-us/windows/win32/api/winioctl/ns-winioctl-device_seek_penalty_descriptor

To fix this, the _WIN32_WINNT should be set to 0x0601

Kindly

**Comment by arvidn** [comment]
Do you know of any other windows 7 features that are used?
The one you highlight is not used in the 1.2.x branch.

I made this patch: https://github.com/arvidn/libtorrent/pull/7191

**Comment by i96751414** [comment]
Apologies, I thought I had seen that in 1.2.18 as well, but I was mistaken.
I did some tests and that seems to be the only one.

**Comment by i96751414** [comment]
Closing this as it has been fixed.
