### ISSUE TITLE
Is there any way to generate torrent file from HDFS or  other non-local storage ?

### ISSUE THREAD

**Issue by chenyuanxing** [arvidn/libtorrent#7197]
**Please provide the following information**

libtorrent version (or branch):
1.2.17

language:
python/java

hello,masters, As the title suggests, If We already have many files stored on external storage, Is there any way to generate torrent file from HDFS or  other non-local storage directly? (without download all the files)

**Comment by master255** [comment]
To generate hashes, you need to read all the data. This is the math. It is impossible to cheat.

**Comment by master255** [comment]
@chenyuanxing Of course. You can generate torrent files separately for the different files on the disk. You can then merge them into one torrent file, without any additional calculations. But you need a small program to do that.

**Comment by chenyuanxing** [comment]
I am in the version 1.2.17. Do I need to guarantee the order of the hashes generated by each file? thanks @master255

**Comment by master255** [comment]
@chenyuanxing You have to use these parameters: create_torrent createTorrent = new create_torrent(fileStorage, 0, 0, create_torrent.optimize_alignment.or_(create_torrent.mutable_torrent_support), -1);

**Comment by chenyuanxing** [comment]
@master255 Sorry for the late reply, this problem has troubled me for a long time.  and finally I found we can write merge logic just like this. [torrent-tools](https://github.com/arvidn/torrent-tools) . 
but when we use merged torrent logic. do we must use merged torrent to seeding?  or we can use the many single small torrent file to seedings and just use merged torrent to download ? 
and very thanks for your reply.

**Comment by master255** [comment]
@chenyuanxing I don't know how torrent-tools work.
I wrote my own program that loops through all the files in the directory and in the loop finds the necessary pieces for them or generates new ones if not found. From these pieces a single torrent file is created.

The program matches files according to three properties: file path, file size and file modification date.

**Comment by chenyuanxing** [comment]
So after you generate the merged torrent . Can it be used directly for downloading ?  Or do you need to use it for seeding before you can use it to download?

**Comment by master255** [comment]
@chenyuanxing It's a regular torrent file, just like all the others.

**Comment by chenyuanxing** [comment]
em . Maybe I didn't make it clear just now. I give an example：
if we have two folders folderA and folderB. (If they have the same folder name)
we create the torrent file A.torrent for folderA and B.torrent for folderB. and We use some machines to seed via A.torrent and B.torrent2. So now we can download the folderA & folderB by A.torrent &  B.torrent . 

And then . we merge the A.torrent & B.torrent and output a merged.torrent . 

So can we use merged.torrent to download directly? 
or we need to use some machines to seed via merged.torrent before. Then we can download through merged.torrent .

**Comment by master255** [comment]
@chenyuanxing that's another question. Create a new discussion thread for that. Close this one.

**Comment by chenyuanxing** [comment]
okay. thanks @master255 .the new question is here. [#7278](https://github.com/arvidn/libtorrent/issues/7278) 
I will close this one.
