### ISSUE TITLE
What's the best way to generate a torrent from a torrent_info

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#7200]
libtorrent: `master`

The recently deprecated constructor `create_torrent(torrent_info const& ti)` is very useful and takes advantage of direct access to private members to perform non-trivial logic. Such logic looks very difficult to reproduce (if possible at all) by other means. The use case in `libtorrent4j` is the possibility to fetch magnet torrents and save them as regular `.torrent` files.

@arvidn are you open to reconsidering the deprecation of this constructor?

**Comment by arvidn** [comment]
the direction I'm hoping to go in is that `torrent_info` represents *just* the immutable `info`-section of a torrent file. The structure that contains everything in a .torrent file is `add_torrent_params`.

So, to answer the question, it depends on whether you get the `torrent_info` by loading a .torrent file from a file, get an `add_torrent_params::ti`, then you could use `write_torrent_file()` and pass in the whole `add_torrent_params` object.

However, it sounds like you have an active torrent and a `torrent_handle` to it. Then you can call `save_resume_data()` and pass in the `save_info_dict` flag. The resulting `add_torrent_params` object can then be passed to `write_torrent_file()`.

**Comment by aldenml** [comment]
Thanks @arvidn! sounds like a good approach, I will try it.
