### ISSUE TITLE
No sparse allocation on 2.0 Windows 32-bit

### ISSUE THREAD

**Issue by WerctFourth** [arvidn/libtorrent#7208]
Hello.
I noticed that after adding a torrent there is 100% disk usage and file size growth immediately regardless of the sparse/full allocation setting in the application GUI. I observe this behavior only on 32-bit versions of programs, 64-bit variants are working correctly, sparse allocation works as intended (instant full size file allocation).
Software tested: Deluge 2.1.1 lt20 x86/x64, qBittorrent 4.5.0 beta 1 lt2.0 Qt5 x86/x64, qBittorrent 4.5.0 release lt2.0 Qt5 x86 (self-built lt2.0.8 Qt5 because there is no official 32-bit version)/x64
Platforms tested: Windows 10 1607 x86, Windows 11 21H2 x64

**Comment by arvidn** [comment]
the 32 bit disk back-end is not very sophisticated at the moment. it doesn't handle windows sparse flags
