### ISSUE TITLE
Failed assertion on blocks count

### ISSUE THREAD

**Issue by glassez** [arvidn/libtorrent#7209]
libtorrent version (or branch): 2.0.8 (not tested on 1.2.x)

platform/architecture: Windows 11

compiler and compiler version: MSVC 2022

```
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 2.0.8.0-63e1ec8c8

file: 'C:\Users\glassez\Devel\qbittorrent\libtorrent\include\libtorrent/bitfield.hpp'
line: 101
function: set_bit
expression: index < size()

stack:
 0: 00007FFB1358D8F2 libtorrent::print_backtrace +242  C:\Users\glassez\Devel\qbittorrent\libtorrent\src\assert.cpp:189
 1: 0000000A734FB3B0
 2: 0000000000000001
 3: 0000000A734FB4C0
 4: 00007FFB135BDDF8 boost::iterator_range_detail::iterator_range_base<boost::iterators::zip_iterator<boost::tuples::tuple<std::_Array_iterator<unsigned int,5>,std::_Array_const_iterator<unsigned int,5>,boost::tuples::null_type,boost::tuples::null_type,boost::tuples::null_ty +120  C:\Users\glassez\Devel\usr\include\boost\range\iterator_range_core.hpp:315
 5: 0000000A734FAEC0
```

@arvidn 
The following qBittorrent Issue could be related:
https://github.com/qbittorrent/qBittorrent/issues/18182#issuecomment-1348895782
_(I'm not sure if you get any notifications about mentions on GitHub, especially in third-party repositories.)_

**Comment by arvidn** [comment]
I did see this one. thanks for making an issue. I haven't had a chance to look into it yet

**Comment by arvidn** [comment]
I believe this might address it. Ideally I would have a test for this too, but I don't think my torrent creation tools support making torrents like this.

https://github.com/arvidn/libtorrent/pull/7219
