### ISSUE TITLE
how to check that a torrent is alive?

### ISSUE THREAD

**Issue by Wintreist** [arvidn/libtorrent#7215]
I tried checking `handle.status().state != 2` and `handle.status().list_seeds >= 1`, but it seems to me that this is not enough, do you know any more checks?

**Comment by ukoz** [comment]
When `handle.status().state > 2`
(( `handle.status().last_seen_complete` == 0) && (std::difftime(std::time(nullptr), `handle.status().added_time` ) >= number))
When incomplete with seed abandoned last_seen_complete != 0 && !(state == 4 || state == 5)
std::difftime(std::time(nullptr), `handle.status().last_seen_complete` ) >= another number
If there `added_time` for `handle.status().has_metadata == false` magnet links.

`last_download`, `last_upload` date value not reliable

**Comment by Wintreist** [comment]
> Когда handle.status().state > 2 (( handle.status().last_seen_complete == 0) && (std::difftime(std::time(nullptr), handle.status().added_time) >= число) ) Когда неполный с заброшенным семенем last_seen_complete != 0 && !(state == 4 || state == 5) std::difftime(std::time(nullptr), handle.status().last_seen_complete ) >= другое число If там `added_time`для `handle.status().has_metadata == false`магнитных ссылок.
> 
> `last_download`, `last_upload`значение даты ненадежно

thx, I'll test it
