### ISSUE TITLE
How do I check how fast a torrent is loading?

### ISSUE THREAD

**Issue by Wintreist** [arvidn/libtorrent#7216]
I use: Python, Libtorrent 2.0.7

I limit each torrent to 6 MB\sec, but let's say the torrent is not popular, and only 1 MB\sec is used, and I have a queue of torrents, I would like to give these 5 MB\sec to the next torrent in the queue

**Comment by ukoz** [comment]
https://www.libtorrent.org/reference-Settings.html

`download_rate_limit` set 6000000
`active_downloads` default is 3, you want 1?
`dont_count_slow_torrents` default is true
`inactive_down_rate` set 1000000

**Comment by Wintreist** [comment]
I wrote the code for my torrent queue.

> active_downloads default is 3, you want 1?

I want all 6MB\sec to be allocated in the order of the queue, and if the torrent that is being downloaded does not use all 6MB\sec, then the rest of the speed should be given to the next torrent in the queue and run it.
At the moment I am running torrent downloads via handler.resume(), but if it is possible to make such a queue as I want through libtorrent parameters, then this would simplify my code

**Comment by arvidn** [comment]
That's correct, you cannot implement that rule simply via settings in libtorrent. However, I would suspect that you would run into issues trying to implement it manually.

Download rates are not necessarily steady and can depend greatly on which peers you happen to be connected to. If a fast peer of your top priority torrent drops, you may open up a new torrent to be downloaded. But if you find another fast peer for the top priority torrent, would you pause the torrent you just started? How would you know that your overall download rate wouldn't suffer?

There's also ramp-up time for connections, you would need to wait long enough to be somewhat confident that a peer won't send any faster to you. Except if you're at your limit, you can't (easily) know which peers are safe to drop and still stay at the limit.

What you *can* do in libtorrent is to set limits per torrent, and a global limit. You can create a queue and specify how many torrents to have running at the same time, and define a lower rate cut-off where you consider a torrent "inactive" to not count against that limit. Which has the effect that the next torrent in the queue will start. If the first one comes back above the inactive-cut off, it will count against the limit again and the torrent that was resume will be paused again.

**Comment by Wintreist** [comment]
> Download rates are not necessarily steady
yes, I understand, I need a variable in which the connection speed is stored, I would check for the maximum value reached by this variable + 1 MB\sec to add speeds if necessary.
Is there such a variable? If not, then I will do as you suggest
