### ISSUE TITLE
libtorrent webtorrent websocket tracker peer_id changing on announce answer

### ISSUE THREAD

**Issue by SilentBot1** [arvidn/libtorrent#7237]
**Please provide the following information**

**libtorrent version (or branch):**
`main`/`2.1.0.0`

**Platform/architecture:**
`Windows 11 x64`, `Gentoo x64`, `Ubuntu 22.04 x64`

**Compiler and compiler version:**
 `gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0` on Ubuntu 22.04 x64
`Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30145 for x64` on Windows 11 x64

**Please describe what symptom you see, what you would expect to see instead and how to reproduce it:**

When using a compiled version of libtorrent 2.1.0.0 ([libtorrent@e22f3ee](https://github.com/arvidn/libtorrent/commit/e22f3ee7d3dc87aea79c1c0ecacfeffaea17866d)) compiled for qBittorrent v4.6.0apha1, and standalone libtorrent 2.1.0.0 via [libtorrent4j](https://github.com/aldenml/libtorrent4j) in Java, in conjunction with bittorrent-tracker ([bittorrent-tracker@df39fe](https://github.com/webtorrent/bittorrent-tracker/commit/df39fed6faf20b6a345fe6136759294ddbbe7b65)) or aquatic-ws ([aquatic-ws@8bf0e12c](https://github.com/greatest-ape/aquatic/commit/8bf0e12cb4553fe0e9dc4985a42bda7fc56e5fd3)), I have noted that the `peer_id` provided by libtorrent webrtc peers via websockets is different per `announce` when `answers` are sent to the tracker.

This issue can be observed when there are two or more peers within a swarm, when a libtorrent client sends an announcement which contains answers, when this occurs, the announcement sent will contain a new `peer_id`, which is different than the `peer_id` provided in previous announcements.

While these `answers` are sent with a new `peer_id`, all other announcements, including `offers` are still sent from the client with it's original `peer_id`, which I believe is unique per swarm for privacy reasons.

In bittorrent-tracker, this is silently ignored by default and treated as an announcement update event, so peer discovery still functions, though with how the tracker keeps tracks of peers, this ends up with an artificially inflated peer count per libtorrent peer. When using other trackers, such as aquatic-ws, clients are disconnected with the error message `Only one peer id can be used per torrent`.

**Steps to reproduce:**
- Build [libtorrent@e22f3ee](https://github.com/arvidn/libtorrent/commit/e22f3ee7d3dc87aea79c1c0ecacfeffaea17866d) from main with the `-Dwebtorrent` flag enabled.
- Start a local [bittorrent-tracker](https://github.com/webtorrent/bittorrent-tracker) tracker with the `DEBUG=*` environment variable set.
- Download a torrent/magnet which contains the above `bittorrent-tracker` on two different libtorrent clients with webtorrent enabled.
- Verify in the `bittorrent-tracker` console output as ``bittorrent-tracker:swarm unexpected `update` event from peer that is not in swarm`` is logged and the `peer_id` (in hex) can be seen to be changing within the ``bittorrent-tracker:server sent answer to`` log messages.

**Comment by arvidn** [comment]
I'm not very familiar with this part of the code, but it looks like `rtc_signaling.cpp` generates another peer ID every time it receives a response. I'm not sure why.

https://github.com/arvidn/libtorrent/blob/master/src/rtc_signaling.cpp#L362

The answer_callback is defined here: https://github.com/arvidn/libtorrent/blob/master/src/websocket_tracker_connection.cpp#L349

which seems to then use that peer ID in the next announce.

@paullouisageneau any insights?

**Comment by paullouisageneau** [comment]
Answers are indeed sent with a different `peer_id` and it looks like a mistake. I'm looking into it.

**Comment by markmdscott** [comment]
Arvid should webtorrent support not go into its own repo within your account, with a dependency on libtorrent?

Unlike say the metadata extension, webtorrent is a full fledged protocol and deserves to be in its own repo.

**Comment by SilentBot1** [comment]
@markmdscott, is there any reason you would want treated differently than uTP and TCP support both being built into libtorrent, even though they are different connection protocols?  WebTorrent is just BitTorrent via WebRTC with WebSocket trackers (required to relay SDP offers).

**Comment by SilentBot1** [comment]
As a side note, I made an attempt at fixing this issue myself, with the following changes found [here](https://github.com/SilentBot1/libtorrent/commit/f7fb13b43bb0fd6e6e9dd8a4d172ed924793f8b5).

I will note, I'm not a C++ developer, so the way I have implemented this may not be optimal, and we may wish to have a different `peer_id` solely for WebSocket trackers or per tracker, rather than using `m_peer_id`, but I can confirm that this change, once built, does fix the issue originally raised.

**Comment by markmdscott** [comment]
WebTorrent is used by very few BitTorrenters, it is not standardized or part of any BEP, it just belongs in its own repo, that's all I'm saying. Perhaps @the8472 has his own thoughts on this.

**Comment by paullouisageneau** [comment]
@SilentBot1 The issue is fixed in https://github.com/arvidn/libtorrent/pull/7249, thank you for reporting!

> As a side note, I made an attempt at fixing this issue myself, with the following changes found [here](https://github.com/SilentBot1/libtorrent/commit/f7fb13b43bb0fd6e6e9dd8a4d172ed924793f8b5).
> 
> I will say, I'm not a C++ developer, so the way I have implemented this may not be optimal or correct, and we may wish to have a different `peer_id` solely for WebSocket trackers or per tracker, rather than using `m_peer_id`, but I can confirm that this change, once built, does fix the issue originally raised.

Your fix is fine, only I fixed it in a less invasive way with a new getter, so the `peer_id` does not need to be passed in every method, in particular this way no changes are needed in the tests. I think it would actually involve some redesign to have a different `peer_id` for a WebSocket tracker because trackers are handled in a generic manner by the `torrent` class.

**Comment by paullouisageneau** [comment]
> WebTorrent is used by very few BitTorrenters, it is not standardized or part of any BEP, it just belongs in its own repo, that's all I'm saying. Perhaps @the8472 has his own thoughts on this.

Like @SilentBot1 I view WebTorrent as basically another transport. For instance, libtorrent also has optional support for connecting over I2P, which is not standardized in a BEP either if I'm not mistaken. Most of the implementation is actually in the libdatachannel repository, the corresponding code in libtorrent mostly consists of tracker/signaling implementation and connection wrapper. The decision would be up to @arvidn anyway, I'd consider it but I think it would be quite complex to move out.

**Comment by xavier2k6** [comment]
@paullouisageneau May be no harm to bump `libdatachannel` along your way from `0.17.1` to `0.18.0` (unless there's a reason to hold-off) ref.: https://github.com/arvidn/libtorrent/tree/master/deps

**Comment by paullouisageneau** [comment]
@xavier2k6 Indeed, I updated libdatachannel to v0.18.0 in https://github.com/arvidn/libtorrent/pull/7251

**Comment by the8472** [comment]
> WebTorrent is used by very few BitTorrenters, it is not standardized or part of any BEP, it just belongs in its own repo, that's all I'm saying. Perhaps @the8472 has his own thoughts on this.

I have some strong opinions regarding webtorrent, but none that are really relevant regarding peer IDs. Peer IDs already underspecified and vary significantly between implementations so libtorrent can make whatever privacy-consistency tradeoff it wants to make here.

**Comment by SilentBot1** [comment]
With the merging of #7249, I have tested and this is now fixed, thanks!
