### ISSUE TITLE
rtc signalling offer_id inconsistent with webtorrent

### ISSUE THREAD

**Issue by SilentBot1** [arvidn/libtorrent#7238]
The default rtc signalling implementation within libtorrent currently defines `offer_id` as a 16-byte value, which can be seen [here](https://github.com/arvidn/libtorrent/blob/569960a67dbcbcc1a55ce47e06023bd26c8ed018/include/libtorrent/aux_/rtc_signaling.hpp#L50), which is inconsistent with the reference WebTorrent library, which currently defines `offer_id` as a random 20-byte value, which can be seen [here](https://github.com/webtorrent/bittorrent-tracker/blob/df39fed6faf20b6a345fe6136759294ddbbe7b65/lib/client/websocket-tracker.js#L379).

This value is not strictly enforced in either `bittorrent-tracker`, or `openwebtorrent-tracker`, which account for the two default websocket trackers used by WebTorrent, which can be seen [here](https://github.com/webtorrent/create-torrent/blob/ce33efa4e9688ccb9bd21e0926246069ee706f1d/index.js#L16), but other trackers, such as aquatic-ws verify that the `offer_id` is 20-byte in length, which can be seen [here](https://github.com/greatest-ape/aquatic/blob/8cab0297a14b24fe51031cd73de0033ae19a5eb3/aquatic_ws_protocol/src/common.rs#L25).

To bring libtorrent in line with the reference `offer_id` length defined by WebTorrent, and ensure compatibility with any software which uses WebTorrent/bittorrent-tracker as a reference implementation of websocket signalling, would libtorrent consider upping the default `offer_id` to a 20-byte value?

**Comment by paullouisageneau** [comment]
Good point, generating an `offer_id` of the same length as the reference WebTorrent implementation makes sense. It would also make it consistent with the other 20-bytes fields like peer id and info hash.

**Comment by SilentBot1** [comment]
Can confirm this is now resolved with the merging of #7250. Closing this down.
