### ISSUE TITLE
[I2P] unknown error

### ISSUE THREAD

**Issue by Vort** [arvidn/libtorrent#7248]
After #7247 fix applied, another error appears.
It happens because of incorrect initialization of `remaining` variable here:
https://github.com/arvidn/libtorrent/blob/690881fec9cc069976cd3d909254a87c22f43ce0/include/libtorrent/i2p_stream.hpp#L285
When such code is used, `remaining` also contains null character, which prevents this comparison from working correctly:
https://github.com/arvidn/libtorrent/blob/690881fec9cc069976cd3d909254a87c22f43ce0/include/libtorrent/i2p_stream.hpp#L309
When such line is used instead:
`string_view remaining(m_buffer.data(), m_buffer.size() - 1);`
unknown error disappears.
Related: #2530

_libtorrent version (or branch)_: 690881fec9cc069976cd3d909254a87c22f43ce0
_platform/architecture_: Windows x64
_compiler and compiler version_: clang 14.0.0

**Comment by jiigen** [comment]
Did some tests too  and this is what i get:
`successfully listening on [uTP] 0.0.0.0:6881
I2P+ Universal Installer 2.0.0+ added
I2P+ Universal Installer 2.0.0+: state changed to: dl metadata
added torrent: I2P+ Universal Installer 2.0.0+
I2P+ Universal Installer 2.0.0+ resumed
I2P+ Universal Installer 2.0.0+ (http://tracker2.postman.i2p/announce.php)[0.0.0.0:6881] v1  "Waiting for i2p acceptor from SAM bridge" (1)
I2P+ Universal Installer 2.0.0+ (http://tracker2.postman.i2p/announce.php)[0.0.0.0:6881] v1  "Waiting for i2p acceptor from SAM bridge" (2)
I2P+ Universal Installer 2.0.0+ (http://tracker2.postman.i2p/announce.php)[0.0.0.0:6881] v1 Host not found (authoritative) "" (3)`

No more unknown error
