### ISSUE TITLE
Question about stats and settings for DHT with IPv6

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#725]
libtorrent: master

I don't see any code related to the inclusion of the DHT for IPv6 in `dht_tracker::dht_status` and `dht_tracker::update_stats_counters`. How to address this? additive or separate counters (per protocol)?

Also the settings, it seems to me that they are duplicated, is it just a matter of documentation?

**Comment by ssiloti** [comment]
I think summing the stats data from both nodes would be appropriate, although I could see an argument for providing separate v6 stats too. I'll leave it to whoever submits a patch first :). DHT related settings are applied to both nodes, I don't think there's a need for separate v6 settings.

**Comment by aldenml** [comment]
Well, the patch is kind of trivial, without the tests :) @arvidn should decide, I think.

For the settings, my concern is lack of clarity if for example, a user specify `dht_settings::max_dht_items` he needs to know that under IPv6 support, the total amount is twice that number. But documentation should be enough.

**Comment by ssiloti** [comment]
The two DHT nodes should probably share the same storage, I just haven't gotten around to making that change.

**Comment by arvidn** [comment]
I can see arguments in both directions here. from the perspective of other DHT participants, they may have a certain expectation of capacity per node. If a user runs more than one node, it might make sense to have the settings scale, and apply per node. but the user may also want to be able to set an upper bound for the machine..

**Comment by aldenml** [comment]
@arvidn and what about the status? additive or per protocol?

**Comment by aldenml** [comment]
To document that this issue is being addressed by:
https://github.com/arvidn/libtorrent/pull/762 (@ssiloti thanks for your comments)
https://github.com/arvidn/libtorrent/pull/783

@arvidn I'm still pending review of `min_distance_exp`

**Comment by aldenml** [comment]
With https://github.com/arvidn/libtorrent/pull/789 I consider this issue fixed
