### ISSUE TITLE
Cross Swarm Seeding feature

### ISSUE THREAD

**Issue by kovalensky** [arvidn/libtorrent#7252]
Follow up of [#6289](https://github.com/arvidn/libtorrent/issues/6289) 

Since the v2 version complements the _pieces root_ key in the info dictionary, which is the root hashes of each individual file, this issue will serve as a suggestion of ideas for design approaches for the long wish cross-swarm seeding feature.

This opens up many possibilities, such as continuous bandwidth and resistance contribution of previous peers in the event of a change in the information hash of a torrent by updating/adding files, say, an episode of a TV series, increasing the lifetime of torrent swarms, reviving dead torrents and reducing the load on hoarders.
And this would accelerate the adoption of the v2 compatible torrents standard before it acquires the fate of something like ipv6.

I don't want to bother the maintainers, I came after my post about the v2 got a lot of votes on Reddit, so I reopened the issue.

**Comment by Tykov** [comment]
I'm backing this🙏

**Comment by kovalensky** [comment]
ChatGPT's opinion to this question, more following up brings more information, maybe I didn't ask the right questions, due to lack of technical knowledge:

Q: So as you know in 2017 BitTorrent v2 reference came, in contrary of v1 reference now every .torrent file has individual hashes of files in its contents, specifically in its info dictionary.
Which could give us a chance to finally search and download individual files with the help of Distributed Hash Table.
We are thinking making a synthetic storage of hashes, so that torrent clients could search and answer to other clients requesting desired hashes of files.
As you know clients can find desired swarms with info hashes, via DHT by approximation of similar node ids to hash.
We don't want to overwhelm network by requesting every peer if it has desired files, how could we more easily find peers which could probably have files we wanted?

A: One approach to finding peers with the desired files more efficiently would be to use a distributed hash table (DHT) optimized for torrent files, such as the Mainline DHT used by BitTorrent. This network can help you find peers with the desired file by searching for nodes that have recently announced the file's info hash. Additionally, you can also store and maintain a list of "well-seeded" torrents, which are torrents with a high number of peers, as these are likely to contain the desired files. Additionally, you could also use torrent trackers, which are centralized servers that keep track of all the seeds and peers in a swarm, to find peers with the desired files.

Q: How about doing this for every file? One client could have thousands of files, we don't want to overwhelm the DHT network

A: One solution to avoid overwhelming the DHT network is to use a hierarchical structure for the synthetic storage of hashes. Instead of storing individual hashes of all files, you could store hashes of groups of files (e.g. by directory, by file type, etc.). When a client is searching for a file, it first queries the DHT network for the group of files that the desired file belongs to. The result of this query would give the client a set of peers that have the desired group of files. The client could then directly query these peers for the desired file, without having to search the entire DHT network. This hierarchical approach would reduce the number of queries to the DHT network and limit the network overhead, while still allowing clients to find the desired files.

Q: Could we mathematically create a short hash which resembles files in those groups of files?

A: Yes, you can create a short hash that represents a group of files. One method is to use a content-defined chunking technique, which divides the file into small fixed-size chunks, then computes a hash for each chunk and concatenates the hashes to form a summary. Another approach is to use a rolling hash, which computes a hash over a sliding window of data, generating a series of hashes that represent the file as a whole. These summary hashes can be used to efficiently find similar files without having to examine the entire file contents.

Q: What would be size of this hash?

A: The size of the hash would depend on the specific hash function used to generate it. Common hash functions used for this purpose include SHA-256, which produces a 256-bit hash, and SHA-1, which produces a 160-bit hash. The size of the hash affects the collision resistance and security of the hash, with longer hashes generally providing stronger security.

Q: How many summary hashes we need to represent that group of files, let's say thousands?

A: The number of summary hashes needed would depend on the desired level of accuracy in identifying the group of files. A smaller number of summary hashes would result in lower accuracy, while a larger number would result in higher accuracy but also require more computation and storage. To accurately represent thousands of files, it might be necessary to use multiple layers of summary hashes, with each layer condensing the information from the previous layer. The specific number of hashes needed would depend on the size and number of files in the group, as well as the desired level of accuracy.

Q: How could we reduce the number of hashes while retaining more accuracy?

A: You can use a hierarchical hash tree structure similar to a Merkle tree, where instead of hashing individual files, you hash groups of files and represent them with a single hash. The tree structure allows for efficient and accurate aggregation of large numbers of files into a smaller number of hashes. By adjusting the size of the groups of files being hashed, you can control the number of hashes that are generated and the level of accuracy of the representation. Additionally, by only exchanging the summary hashes relevant to a particular search, you can reduce the number of hashes transmitted and the load on the network.

Q: What would you do to make this approach more efficient, I mean how could we search individual files in the DHT network with millions of peers by knowing only its hash, what could peers do to make it easier to find that file?

A: To make searching for individual files in the DHT network more efficient, one approach would be to use techniques like Bloom filters or distributed data structures like Kademlia. These techniques allow peers to efficiently share information about which files they have available and where those files can be found. Additionally, peers could periodically exchange information about which files are currently in high demand, allowing them to prioritize those files in their search results. Another approach would be to leverage machine learning techniques, such as clustering or classification, to group similar files together and make searching for them more efficient.

**Comment by kovalensky** [comment]
Hello @arvidn Some people asked if we could crowdfund this feature for faster implementation.

Could we donate to your PayPal with "Cross Swarm Seeding" comment to payment?

**Comment by arvidn** [comment]
My personal limiting factor is time, but perhaps a code bounty could incentivize someone else to help out.
My impression is that addressing the issue with memory mapped files is more urgent. I spend my libtorrent-time mostly on implementing a new disk cache for the `pread-disk-io` branch (targeting `master`). This is a fairly big project.

But, for this project, assuming we're only aiming to support v2 torrents, I think these are some of things that need to happen:

* [ ] function to produce a new info-dictionary for individual files in a v2 torrent
* [ ] algorithm for determining which files are significant enough to warrant creating an individual torrent (since there's cost associated with tracker- and DHT announces)
* [ ] make a single torrent announce multiple info-hashes (for the individual files) to trackers and DHT
* [ ] support peers to have a limited view into the torrent, where it may only be observing (and indexing into) a single-file torrent. This is a big one, as it requires translating piece indices to and from all interactions with the peer. Ideally there would be some abstraction that would allow to isolate this translation. Perhaps an extra indirection to the torrent object.
* [ ] There would probably need to be some API decisions around whether these extra single-file torrents would be visible to clients, and to what extent. Perhaps the client should have control over which files are selected to be made into single-file torrents. Maybe the .torrent file itself could have some hints.

**Comment by Seeker2** [comment]
A lot of dead torrents I deal with are private-flagged torrents.
They weren't even on private trackers, just flagged as private on public trackers.

They're v1 torrents only, but even assuming they were v2 torrents...would Cross Swarm Seeding them even be allowed?

**Comment by arvidn** [comment]
just to clarify; when I say v2-torrents, I include hybrid torrents too.

> They're v1 torrents only, but even assuming they were v2 torrents...would Cross Swarm Seeding them even be allowed?

My interpretation of the private flag is that it's a promise to only ask for peers from the tracker (not DHT, LSD or any other possible source of peers). For this cross-swarm-seeding to work, the private tracker would have to co-operate and white-list the single-torrent info-hashes.

The generated single-file torrents probably shouldn't duplicate non-essential info-torrent fields, such as `private`. At which point the tracker wouldn't have to co-operate anyway.

**Comment by kovalensky** [comment]
> My personal limiting factor is time, but perhaps a code bounty could incentivize someone else to help out. My impression is that addressing the issue with memory mapped files is more urgent. I spend my libtorrent-time mostly on implementing a new disk cache for the `pread-disk-io` branch (targeting `master`). This is a fairly big project.
Thanks for the answer, I'll look into if I can find a reliable developer for this task, do you know any by chance?
Then after review with him and you, I gotta start a crowdfunding campaign.

**Comment by kovalensky** [comment]
I see that this feature will require serious changes in DHT, probably it would be better for trackers & DHT crawlers to show those hashes.
