### ISSUE TITLE
[I2P] Update to SAM 3.1

### ISSUE THREAD

**Issue by zzzi2p** [arvidn/libtorrent#7258]
ref: https://geti2p.net/en/docs/api/samv3

Supported since 2014 and the minimum recommended version.

Changes:

- HELLO VERSION MIN=3.1 MAX=3.1
- SESSION CREATE DESTINATION=TRANSIENT SIGNATURE_TYPE=7 ...

We also recommend specifying inbound.quantity=x outbound.quantity=x in the SESSION CREATE line, as i2pd and Java I2P have different defaults.

More background and guidance in the spec linked above.
Thanks

**Comment by Vort** [comment]
Are changes in #7272 enough to close this issue?
