### ISSUE TITLE
Opening empty torrent file produce a valid torrent handle

### ISSUE THREAD

**Issue by ruslanfedoseenko** [arvidn/libtorrent#726]
libtorrent version (or branch):  1.1.0

platform/architecture: Windows/x86

compiler and compiler version: msvc 14.0 (Visual Studio 2015)

Opening an empty (with size 0 bytes) file produces a valid torrent handle with no metadata and zero infohash.
Expect to throw error or set error_code in no exception mode.

**Comment by arvidn** [comment]
I believe this fixes it: https://github.com/arvidn/libtorrent/pull/729
