### ISSUE TITLE
Broken link to the `prerequisites for the main libtorrent library`

### ISSUE THREAD

**Issue by drew2a** [arvidn/libtorrent#7274]
## How to reproduce

1. Got to the [main page](https://github.com/arvidn/libtorrent)
2. Go to the [the python docs](https://github.com/arvidn/libtorrent/blob/RC_2_0/docs/python_binding.rst)
3. Go to the [the build prerequisites for the main libtorrent library](https://github.com/arvidn/libtorrent/blob/RC_2_0/docs/building.html)

<img width="622" alt="image" src="https://user-images.githubusercontent.com/13798583/212879980-b6459829-cc6e-42cd-b349-1dadababd166.png">

## Screenshots
<img width="544" alt="image" src="https://user-images.githubusercontent.com/13798583/212880131-e248e738-3fea-4099-adc2-00979ee0eb63.png">
<img width="616" alt="image" src="https://user-images.githubusercontent.com/13798583/212880265-9dcd42d9-f3c6-425e-b390-9556cb727d2f.png">
<img width="622" alt="image" src="https://user-images.githubusercontent.com/13798583/212879980-b6459829-cc6e-42cd-b349-1dadababd166.png">

**Comment by Vort** [comment]
There are lots of such broken links in `docs`.
For example, [todo list](https://github.com/arvidn/libtorrent/blob/RC_2_0/docs/todo.html) in https://github.com/arvidn/libtorrent/blob/RC_2_0/docs/contributing.rst .

**Comment by Vort** [comment]
I found two suggestions about how to make such links correctly:
https://stackoverflow.com/a/43413256/8680450
https://stackoverflow.com/a/50592281/8680450
Not sure if they can be used here, however.

**Comment by arvidn** [comment]
I don't use sphinx so I don't think those stackoverflow answers apply. Perhaps it makes sense to transition to using sphinx, but I also do some amount of generation `.rst` files
