### ISSUE TITLE
When we generate the merged torrent . Can it be used directly for downloading ? 

### ISSUE THREAD

**Issue by chenyuanxing** [arvidn/libtorrent#7278]
**Please provide the following information**

libtorrent version (or branch):
2.0.8 or  1.2.17

if we have two folders folderA and folderB. (If they have the same folder name)
we create the torrent file A.torrent for folderA and B.torrent for folderB. and We use some machines to seed via A.torrent and B.torrent2. So now we can download the folderA & folderB by A.torrent & B.torrent .

And then . we merge the A.torrent & B.torrent and output a merged.torrent .

So can we use merged.torrent to download directly?
or we need to use some machines to seed via merged.torrent before. Then we can download through merged.torrent .

**Comment by master255** [comment]
This is the double of https://github.com/arvidn/libtorrent/issues/5168.
Close this thread.

**Comment by arvidn** [comment]
there is no swarm merging. I believe the most promising approach would be to announce each (large enough) file independently to the DHT as if it was its own torrent. i.e. the info-hash would have to be computed and maybe the actual info dictionary too.

**Comment by arvidn** [comment]
> So can we use merged.torrent to download directly?
> or we need to use some machines to seed via merged.torrent before. Then we can download through merged.torrent .

If there is someone seeding the merged torrent you can download it, not otherwise.

**Comment by master255** [comment]
@arvidn 

> there is no swarm merging. I believe the most promising approach would be to announce each (large enough) file independently to the DHT as if it was its own torrent. i.e. the info-hash would have to be computed and maybe the actual info dictionary too.

We already have a field of similar infocaches. We just need to use this array of infohashes and announce them one by one, as if the hash of the same torrent is changing. What could be a problem with it? Maybe a problem with handshake calculation?
