### ISSUE TITLE
DHT can't download file on Windows

### ISSUE THREAD

**Issue by pqqsxhy** [arvidn/libtorrent#7290]
**Please provide the following information**

libtorrent version (or branch):
2.0.8-2

platform/architecture:
Windows server 2019 datacenter. x86
compiler and compiler version:
https://packages.msys2.org/package/mingw-w64-x86_64-libtorrent-rasterbar

Test environment：
1. Two windows servers. 2. ServerA ip:10.4.0.8, SeverB ip:10.4.0.44. 3. ServerA  as source DHT node, start with C:\images\game-keen1\0117\raster.torrent + raster.zip . I think ServerB will download from ServerA, but failed. 
2. The torrent I made did not specify a tracker server，it like this:  number of pieces: 817
piece length: 131072
info hash: 9c75ba3c91a70915889879737c8aaa92385fa19f, 9d6b160753030b15127e6a313e35cfc216a06b0dc8313dc7381939afa67a4702
comment:
created by: libtorrent
magnet link: magnet:?xt=urn:btih:9c75ba3c91a70915889879737c8aaa92385fa19f&xt=urn:btmh:12209d6b160753030b15127e6a313e35cfc216a06b0dc8313dc7381939afa67a4702&dn=libtorrent-rasterbar.so
name: libtorrent-rasterbar.so
number of files: 1
files:
        0   106989840 -x-- [     0,   816 ]       0 18e71387bbdd108db4a3a947c10fc88ac9a7619d8f98a5eb032f067c0ab412e4 libtorrent-rasterbar.so
web seeds:

4. ServerA:
C:\Users\Administrator\Downloads>netstat -ano |findstr "2316"
  TCP    0.0.0.0:9910           0.0.0.0:0              LISTENING       2316
  TCP    10.4.0.8:6881          0.0.0.0:0              LISTENING       2316
  TCP    127.0.0.1:6881         0.0.0.0:0              LISTENING       2316
  TCP    127.0.0.1:50734        127.0.0.1:50735        ESTABLISHED     2316
  TCP    127.0.0.1:50735        127.0.0.1:50734        ESTABLISHED     2316
  TCP    [::]:9910              [::]:0                 LISTENING       2316
  TCP    [::1]:6881             [::]:0                 LISTENING       2316
  TCP    [fe80::791d:b23c:9dfd:a579%13]:6881  [::]:0                 LISTENING       2316
  UDP    0.0.0.0:6771           *:*                                    2316
  UDP    0.0.0.0:6771           *:*                                    2316
  UDP    0.0.0.0:6771           *:*                                    2316
  UDP    0.0.0.0:6771           *:*                                    2316
  UDP    0.0.0.0:60800          *:*                                    2316
  UDP    0.0.0.0:60801          *:*                                    2316
  UDP    10.4.0.8:6881          *:*                                    2316
  UDP    10.4.0.8:52752         *:*                                    2316
  UDP    127.0.0.1:6881         *:*                                    2316
  UDP    127.0.0.1:9999         *:*                                    2316
  UDP    [::]:6771              *:*                                    2316
  UDP    [::]:6771              *:*                                    2316
  UDP    [::1]:6881             *:*                                    2316
  UDP    [fe80::791d:b23c:9dfd:a579%13]:6881  *:*                                    2316
ServerB:
C:\Users\Administrator\Downloads>netstat -aon |findstr "5088"
  TCP    0.0.0.0:9910           0.0.0.0:0              LISTENING       5088
  TCP    10.4.0.44:6881         0.0.0.0:0              LISTENING       5088
  TCP    10.4.0.44:64577        113.96.18.200:443      ESTABLISHED     5088
  TCP    127.0.0.1:6881         0.0.0.0:0              LISTENING       5088
  TCP    127.0.0.1:64539        127.0.0.1:64540        ESTABLISHED     5088
  TCP    127.0.0.1:64540        127.0.0.1:64539        ESTABLISHED     5088
  TCP    [::]:9910              [::]:0                 LISTENING       5088
  TCP    [::1]:6881             [::]:0                 LISTENING       5088
  TCP    [fe80::a55b:4b82:cc1c:9d9b%13]:6881  [::]:0                 LISTENING       5088
  UDP    0.0.0.0:6771           *:*                                    5088
  UDP    0.0.0.0:6771           *:*                                    5088
  UDP    0.0.0.0:6771           *:*                                    5088
  UDP    0.0.0.0:6771           *:*                                    5088
  UDP    0.0.0.0:64897          *:*                                    5088
  UDP    0.0.0.0:64898          *:*                                    5088
  UDP    10.4.0.44:6881         *:*                                    5088
  UDP    10.4.0.44:63128        *:*                                    5088
  UDP    127.0.0.1:6881         *:*                                    5088
  UDP    127.0.0.1:9999         *:*                                    5088
  UDP    [::]:6771              *:*                                    5088
  UDP    [::]:6771              *:*                                    5088
  UDP    [::1]:6881             *:*                                    5088
  UDP    [fe80::a55b:4b82:cc1c:9d9b%13]:6881  *:*                                    5088

ServerB telnet ServerA:

C:\Users\Administrator\Downloads>telnet.exe fe80::791d:b23c:9dfd:a579%13 6881  is failed.
正在连接到fe80::791d:b23c:9dfd:a579%13...不能打开到主机的连接， 在端口 6881: 连接失败(Connecting to fe80::791d:b23c:9dfd:a579%13... Could not open connection to host on port 6881: Connection failed)

C:\Users\Administrator\Downloads>telnet.exe 10.4.0.8 6881  is succeed.

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

 Init lt::session like this:
` sp.set_int(lt::settings_pack::alert_mask, lt::alert_category::status | lt::alert_category::error);

    sp.set_bool(lt::settings_pack::validate_https_trackers, false);

    sp.set_bool(lt::settings_pack::enable_lsd, true);

    sp.set_bool(lt::settings_pack::dht_enforce_node_id, true);

    sp.set_str(lt::settings_pack::listen_interfaces, "0.0.0.0:6881,[::]:6881");`

The log output by the calling code

`for (const lt::dht_lookup& l : alert->active_requests) {

        std::snprintf(str, sizeof(str)
            , "  %10s target: %s "
            "[limit: %2d] "
            "in-flight: %-2d "
            "left: %-3d "
            "1st-timeout: %-2d "
            "timeouts: %-2d "
            "responses: %-2d "
            "last_sent: %-2d "
            , l.type
            , ToHex(l.target).c_str()
            , l.branch_factor
            , l.outstanding_requests
            , l.nodes_left
            , l.first_timeout
            , l.timeouts
            , l.responses
            , l.last_sent);
        out += str;
    } `

The business code will automatically load the torrent file under the preset folder and try to download it. Out put log like this: 

`2023/01/27 12:29:33.553170 log.go:220: [INFO] load torrent file:raster.torrent, C:\images\game-keen1\018\raster.torrent

2023/01/27 12:29:33.554176 log.go:220: [INFO] need reload cmd:[{command:0 id:game-keen1 version:0117 savePath:C:\images\game-keen1\0117\ torrentFile:C:\images\game-keen1\0117\btagent.torrent uploadSpeed:-1 downloadSpeed:-1} {command:0 id:game-keen1 version:018 savePath:C:\images\game-keen1\018\ torrentFile:C:\images\game-keen1\018\raster.torrent uploadSpeed:-1 downloadSpeed:-1}]

2023/01/27 12:29:33.554176 log.go:220: [INFO] create file share:{command:0 id:game-keen1 version:0117 savePath:C:\images\game-keen1\0117\ torrentFile:C:\images\game-keen1\0117\btagent.torrent uploadSpeed:-1 downloadSpeed:-1}
2023/01/27 12:29:33.554339 log.go:220: [INFO] create file share:{command:0 id:game-keen1 version:018 savePath:C:\images\game-keen1\018\ torrentFile:C:\images\game-keen1\018\raster.torrent uploadSpeed:-1 downloadSpeed:-1}

2023/01/27 12:29:33.555271 log.go:220: [INFO] get local ip is 10.4.0.44

2023/01/27 12:29:33.555271 log.go:220: [INFO] local ip range is 10.4.0.1,10.4.63.254

2023/01/27 12:29:35.972284 log.go:220: [INFO] add torrent:game-keen1_0117

2023/01/27 12:29:35.972284 log.go:220: [INFO] default alert:3

2023/01/27 12:29:35.972284 log.go:220: [INFO] alert message:

2023/01/27 12:29:35.972284 log.go:220: [INFO] add torrent:game-keen1_018

2023/01/27 12:29:35.972284 log.go:220: [INFO] name:btagent.exe, state:7, progress:0.000000, dowload_rate:0, userdata:game-keen1_0117

2023/01/27 12:29:35.972284 log.go:220: [INFO] name:libtorrent-rasterbar.so, state:7, progress:0.000000, dowload_rate:0, userdata:game-keen1_018

2023/01/27 12:29:35.972284 log.go:220: [INFO] default alert:92

2023/01/27 12:29:35.972284 log.go:220: [INFO] alert message:

2023/01/27 12:29:35.972284 log.go:220: [INFO] default alert:10

2023/01/27 12:29:35.972284 log.go:220: [INFO] alert message:

2023/01/27 12:29:35.972284 log.go:220: [INFO] default alert:41

2023/01/27 12:29:35.972284 log.go:220: [INFO] alert message:

2023/01/27 12:29:35.972284 log.go:220: [INFO] default alert:40

2023/01/27 12:29:35.972284 log.go:220: [INFO] alert message:

2023/01/27 12:29:36.374453 log.go:220: [INFO] name:btagent.exe, state:3, progress:0.000000, dowload_rate:0, userdata:game-keen1_0117

2023/01/27 12:29:36.374453 log.go:220: [INFO] name:libtorrent-rasterbar.so, state:3, progress:0.000000, dowload_rate:0, userdata:game-keen1_018

2023/01/27 12:29:36.374453 log.go:220: [INFO] dht info:   bootstrap target: 7470bea73efabde7739bf8bd38ed455b83a26155 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 2     get_peers target: aa7113b2679f2031b24bda0f72c0c24d6bd889d8 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 1     get_peers target: 81dd926d31c85c1f37aa698f8de4522e99a77ea0 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 1  

2023/01/27 12:29:36.374453 log.go:220: [INFO] default alert:37

2023/01/27 12:29:36.374453 log.go:220: [INFO] alert message:

2023/01/27 12:29:36.781042 log.go:220: [INFO] name:btagent.exe, state:3, progress:0.000000, dowload_rate:0, userdata:game-keen1_0117

2023/01/27 12:29:36.781042 log.go:220: [INFO] name:libtorrent-rasterbar.so, state:3, progress:0.000000, dowload_rate:0, userdata:game-keen1_018

2023/01/27 12:29:36.781042 log.go:220: [INFO] dht info:   bootstrap target: 7470bea73efabde7739bf8bd38ed455b83a26155 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 2     get_peers target: aa7113b2679f2031b24bda0f72c0c24d6bd889d8 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 2     get_peers target: 81dd926d31c85c1f37aa698f8de4522e99a77ea0 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 2  

2023/01/27 12:29:37.187679 log.go:220: [INFO] dht info:   bootstrap target: 7470bea73efabde7739bf8bd38ed455b83a26155 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 3     get_peers target: aa7113b2679f2031b24bda0f72c0c24d6bd889d8 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 2     get_peers target: 81dd926d31c85c1f37aa698f8de4522e99a77ea0 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 2  

2023/01/27 12:29:37.591806 log.go:220: [INFO] dht info:   bootstrap target: 7470bea73efabde7739bf8bd38ed455b83a26155 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 3     get_peers target: aa7113b2679f2031b24bda0f72c0c24d6bd889d8 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 3     get_peers target: 81dd926d31c85c1f37aa698f8de4522e99a77ea0 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 3  

2023/01/27 12:29:37.999396 log.go:220: [INFO] dht info:   bootstrap target: 7470bea73efabde7739bf8bd38ed455b83a26155 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 3     get_peers target: aa7113b2679f2031b24bda0f72c0c24d6bd889d8 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 3     get_peers target: 81dd926d31c85c1f37aa698f8de4522e99a77ea0 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 3  

2023/01/27 12:29:38.406963 log.go:220: [INFO] dht info:   bootstrap target: 7470bea73efabde7739bf8bd38ed455b83a26155 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 4     get_peers target: aa7113b2679f2031b24bda0f72c0c24d6bd889d8 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 3     get_peers target: 81dd926d31c85c1f37aa698f8de4522e99a77ea0 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 3  

2023/01/27 12:29:38.819448 log.go:220: [INFO] dht info:   bootstrap target: 7470bea73efabde7739bf8bd38ed455b83a26155 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 4     get_peers target: aa7113b2679f2031b24bda0f72c0c24d6bd889d8 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 4     get_peers target: 9d6b160753030b15127e6a313e35cfc216a06b0d [limit:  5] in-flight: 1  left: 0   1st-timeout: 0  timeouts: 0  responses: 0  last_sent: 0     get_peers target: 9c75ba3c91a70915889879737c8aaa92385fa19f [limit:  5] in-flight: 1  left: 0   1st-timeout: 0  timeouts: 0  responses: 0  last_sent: 0     get_peers target: 81dd926d31c85c1f37aa698f8de4522e99a77ea0 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 4  

2023/01/27 12:29:39.228491 log.go:220: [INFO] dht info:   bootstrap target: 7470bea73efabde7739bf8bd38ed455b83a26155 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 5     get_peers target: aa7113b2679f2031b24bda0f72c0c24d6bd889d8 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 4     get_peers target: 9d6b160753030b15127e6a313e35cfc216a06b0d [limit:  5] in-flight: 1  left: 0   1st-timeout: 0  timeouts: 0  responses: 0  last_sent: 0     get_peers target: 9c75ba3c91a70915889879737c8aaa92385fa19f [limit:  5] in-flight: 1  left: 0   1st-timeout: 0  timeouts: 0  responses: 0  last_sent: 0     get_peers target: 81dd926d31c85c1f37aa698f8de4522e99a77ea0 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 4  

2023/01/27 12:29:39.638623 log.go:220: [INFO] dht info:   bootstrap target: 7470bea73efabde7739bf8bd38ed455b83a26155 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 5     get_peers target: aa7113b2679f2031b24bda0f72c0c24d6bd889d8 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 5     get_peers target: 9d6b160753030b15127e6a313e35cfc216a06b0d [limit:  5] in-flight: 1  left: 0   1st-timeout: 0  timeouts: 0  responses: 0  last_sent: 1     get_peers target: 9c75ba3c91a70915889879737c8aaa92385fa19f [limit:  5] in-flight: 1  left: 0   1st-timeout: 0  timeouts: 0  responses: 0  last_sent: 1     get_peers target: 81dd926d31c85c1f37aa698f8de4522e99a77ea0 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 5  

2023/01/27 12:29:40.047700 log.go:220: [INFO] dht info:   bootstrap target: 7470bea73efabde7739bf8bd38ed455b83a26155 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 6     get_peers target: aa7113b2679f2031b24bda0f72c0c24d6bd889d8 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 5     get_peers target: 9d6b160753030b15127e6a313e35cfc216a06b0d [limit:  5] in-flight: 1  left: 0   1st-timeout: 0  timeouts: 0  responses: 0  last_sent: 1     get_peers target: 9c75ba3c91a70915889879737c8aaa92385fa19f [limit:  5] in-flight: 1  left: 0   1st-timeout: 0  timeouts: 0  responses: 0  last_sent: 1     get_peers target: 81dd926d31c85c1f37aa698f8de4522e99a77ea0 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 5  

2023/01/27 12:29:40.454527 log.go:220: [INFO] dht info:   bootstrap target: 7470bea73efabde7739bf8bd38ed455b83a26155 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 6     get_peers target: aa7113b2679f2031b24bda0f72c0c24d6bd889d8 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 5     get_peers target: 9d6b160753030b15127e6a313e35cfc216a06b0d [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 1     get_peers target: 9c75ba3c91a70915889879737c8aaa92385fa19f [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 1     get_peers target: 81dd926d31c85c1f37aa698f8de4522e99a77ea0 [limit:  6] in-flight: 1  left: 0   1st-timeout: 1  timeouts: 0  responses: 0  last_sent: 5  

2023/01/27 12:29:40.863635 log.go:220: [INFO] name:libtorrent-rasterbar.so, state:3, progress:0.000000, dowload_rate:0, userdata:game-keen1_018`

**Comment by master255** [comment]
@pqqsxhy The LSD is used to search for peers locally. DHT is used when searching on the Internet. What you write cannot be. It means you are doing something wrong.

**Comment by pqqsxhy** [comment]
> @pqqsxhy The LSD is used to search for peers locally. DHT is used when searching on the Internet. What you write cannot be. It means you are doing something wrong.

Thank you. I want to share files in LAN without relying on tracker service. The same code is shared normally on the Linux platform. But in the windows environment, it cannot share success. Libtorrent's LSD is enabled by default. libtorrent does not provide a complete sample code on windows.

**Comment by pqqsxhy** [comment]
Solved the problem a while ago, because I only started lsd, but the windows system does not support multicast, so the local peer cannot be found
