### ISSUE TITLE
Unhandled exception boost::system::system_error when trying to open torrent file lt::torrent_info

### ISSUE THREAD

**Issue by KulaGGin** [arvidn/libtorrent#7298]
libtorrent version (or branch): [Release libtorrent-2.0.8](https://github.com/arvidn/libtorrent/releases/tag/v2.0.8)
platform/architecture: x86
compiler and compiler version: Visual C++ 14.3

I built the library with cmake, following the building tutorial: https://www.libtorrent.org/building.html#building-with-cmake
I built it as a static lib(added option `static_runtime=ON` while building it), copied the `include` folder into my project, as well as the `torrent-rasterbar.lib` and `torrent-rasterbar.dll` file into a `lib` folder in my project.
I added the `include` folder with all the libtorrent headers to the include folders of my Visual Studio project and I added the `torrent-rasterbar.lib` to the input of the linker.

I'm trying to open a torrent file:

```
#include "libtorrent/session.hpp"
#include "libtorrent/torrent_info.hpp"

#include <filesystem>
#include <iostream>

using namespace std;
using namespace filesystem;

int main(int argc, char const* argv[])
{
    if (argc != 2) {
        std::cout << "usage: <filename>\n";
        return 1;
    }

    lt::session session;

    path fullFilePath = weakly_canonical(path(argv[0])).parent_path() / std::string(argv[1]);

    lt::torrent_info torrent_info(fullFilePath .string());
}
```
When it tries to execute the last line, I get `Unhandled exception at 0x74D608B2 in TorrentRenamer.exe: Microsoft C++ exception: boost::system::system_error at memory location 0x006FF1F0.` error:
![devenv_7vcswP1jY6](https://user-images.githubusercontent.com/16989713/217826211-657aeb88-a3e6-447c-82ad-20b12357838b.png)

I also tried to pass to the constructor `std::string("./torrentFile.torrent")` and `std::string("torrentFile.torrent")` and still got the same error.

I tried a different constructor with:
```
    lt::error_code ec{};

    lt::torrent_info torrent_info(fullFileName, ec);
```
And with this I get error code 13 instead of unhandled exception.

The file is present in the folder and is available to read and write:
![explorer_eQ2HGbKcTk](https://user-images.githubusercontent.com/16989713/217826381-8f91347f-7d5a-4bc0-88e9-a318252a74c9.png)

It's also a valid torrent file: I can open it in torrent programs just fine.

**Comment by arvidn** [comment]
> And with this I get error code 13 instead of unhandled exception.

In order to understand what's going wrong, you need to understand that error message. An `error_code` is not just a number, it's also an error category. error 13 could be `ERROR_INVALID_DATA` if the category is windows errors. It could also be `···too_many_pieces_in_torrent`, if the category is `libtorrent`.

Typically the simplest way to know is to print the `message()` of the error code.
