### ISSUE TITLE
bt_peer_connection::write_have(int) crash

### ISSUE THREAD

**Issue by AlexTalker** [arvidn/libtorrent#73]
```
assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.0.6.0
$Rev$

file: 'bt_peer_connection.cpp'
line: 2292
function: virtual void libtorrent::bt_peer_connection::write_have(int)
expression: m_sent_handshake && m_sent_bitfield


stack:
1: assert_fail(char const*, int, char const*, char const*, char const*, int)
2:
3:
4:
5:
6:
7:
8: boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&)
9: boost::asio::detail::task_io_service::run(boost::system::error_code&)
10:
11: boost_asio_detail_posix_thread_function
12:
13: clone
```

And the qbittorrent crash log below:

```
*************************************************************
Catching SIGABRT, please report a bug at http://bug.qbittorrent.org
and provide the following backtrace:
qBittorrent version: v3.2.1
stack trace:
  /usr/lib/libc.so.6 : gsignal()+0x38  [0x7fdc508a8528]
  /usr/lib/libc.so.6 : abort()+0x16a  [0x7fdc508a993a]
  /usr/lib/libtorrent-rasterbar.so.8 : assert_fail(char const*, int, char const*, char const*, char const*, int)+0xf7  [0x7fdc533c75b7]
  /usr/lib/libtorrent-rasterbar.so.8 : ()+0xa2571  [0x7fdc533d8571]
  /usr/lib/libtorrent-rasterbar.so.8 : ()+0x16b45a  [0x7fdc534a145a]
  /usr/lib/libtorrent-rasterbar.so.8 : ()+0x17ba8a  [0x7fdc534b1a8a]
  /usr/lib/libtorrent-rasterbar.so.8 : ()+0x28c2a6  [0x7fdc535c22a6]
  /usr/lib/libtorrent-rasterbar.so.8 : ()+0x210ae9  [0x7fdc53546ae9]
  /usr/lib/libtorrent-rasterbar.so.8 : ()+0x21df9d  [0x7fdc53553f9d]
  /usr/lib/libtorrent-rasterbar.so.8 : boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&)+0x33f  [0x7fdc533bc38f]
  /usr/lib/libtorrent-rasterbar.so.8 : boost::asio::detail::task_io_service::run(boost::system::error_code&)+0xd9  [0x7fdc533bc519]
  /usr/lib/libtorrent-rasterbar.so.8 : ()+0x20da2b  [0x7fdc53543a2b]
  /usr/lib/libtorrent-rasterbar.so.8 : boost_asio_detail_posix_thread_function()+0x52  [0x7fdc533c0512]
  /usr/lib/libpthread.so.0 : ()+0x7354  [0x7fdc52f1c354]
  /usr/lib/libc.so.6 : clone()+0x6d  [0x7fdc5095cbfd]
[1]    24004 abort (core dumped)  qbittorrent
```

System: Arch Linux(x64)

Where is a problem? Crashes is too fast than I can use qbittorrent :cry:

**Comment by AlexTalker** [comment]
https://github.com/qbittorrent/qBittorrent/issues/3591
@arvidn

**Comment by arvidn** [comment]
you should probably use a release build if you intend to actually use the library. debug builds are primarily for debugging and trouble shooting

**Comment by AlexTalker** [comment]
@arvidn yes, sure, I've rebuild package with debug symbols for trace what's odd with qbittorrent but folks there tells me that problem with your library :disappointed:

**Comment by sledgehammer999** [comment]
@AlexTalker have you build libtorrent with debug symbols too? The trace shows that it doesn't have debug symbols. Just useless addresses.

**Comment by arvidn** [comment]
@AlexTalker There's no question about the assert firing because of a problem in libtorrent causing an invariant to be violated. In order to find out what happened, having the back trace is probably very useful.

**Comment by AlexTalker** [comment]
@sledgehammer999 @arvidn Okay, guy, just tell me more how I can help you and I'll try.BTW, I've used the PKGBUILD(I have modified original version from Arch Build System), just put '--enable-debug' in ./configure, I thought that will be enough but you may tell me more. https://gist.github.com/365bf8d8ef907d55a1dc

**Comment by AlexTalker** [comment]
Sorry for late answers, I just have bad memory and I've forget about the topic. I really enjoy to help people like you. :disappointed:

**Comment by arvidn** [comment]
--enable-debug should be enough. however, make sure the new libtorrent library you built is actually the one qBT uses. If you already have another libtorrent installed, that will most likely take precedence (make sure you don't have an old installation laying around in some other directory, /usr/lib /usr/local/lib lib64 etc).

You can use "lld" to confirm that qBT ultimately depends on the correct libtorrent:

   http://man7.org/linux/man-pages/man1/ldd.1.html

**Comment by sledgehammer999** [comment]
@AlexTalker to expand a little more on what @arvidn has said.
Use
```
ldd qbittorrent
```
to see which libtorrent (with full path) is picked up when qbittorrent is launched.
If it is the wrong one you can invoke qbittorrent with the correct one like this
```
LD_PRELOAD=/path/to/your/libtorrent/lib/libtorrent.so qbittorrent
```
(notice that you include the .so in the path)

**Comment by AlexTalker** [comment]
@arvidn oh, yeah, sure, the library which linked with qbittorrent binary when I'd open it in gdb has debugging  symbols('words' in gdb terminology). But the joke is that now I have SIGABRT instead of SIGINT as before and now it's seems like some problems with qBT GUI. SIGINT crash was somewhere after the SIGABRT position, when GUI was already started and ready to use(for 5-10-30 seconds or ever more) but now it's just crash on start. Only load GUI and immediately crash :disappointed: But thanks for explanations anyway.

**Comment by AlexTalker** [comment]
@arvidn https://gist.github.com/d13e99a4c326d8857a21 new log here, I guess, I've catch what you want.

```
$ qbittorrent --version
qBittorrent v3.2.3
```

Version of libtorrent -- `1.0.6`

**Comment by arvidn** [comment]
could you give this patch a try? https://github.com/arvidn/libtorrent/pull/139

**Comment by AlexTalker** [comment]
@arvidn if you mean only the single commit, the result is: https://gist.github.com/dce5495dda6592ff7c03

**Comment by arvidn** [comment]
thanks for testing! I have put one more patch into that pull request

**Comment by AlexTalker** [comment]
@arvidn I hope, I've applied it well https://gist.github.com/4aad11e01b69e7f6e098

**Comment by arvidn** [comment]
ok, I put in another update

**Comment by AlexTalker** [comment]
@arvidn I guess, I do not have the crash anymore, at least in last few minutes(before the crash happens in first 1-2 minutes)

**Comment by arvidn** [comment]
thanks for testing! I will merge this patch
