### ISSUE TITLE
`peer_blocked_alert::privileged_ports` never fired

### ISSUE THREAD

**Issue by HanabishiRecca** [arvidn/libtorrent#7300]
When `no_connect_privileged_ports` is set, you add a port filter here
https://github.com/arvidn/libtorrent/blob/73f6aba64eafb2b0d454434681950dbbf18a6b44/src/session_impl.cpp#L5343
Which means ports are always filtered here
https://github.com/arvidn/libtorrent/blob/73f6aba64eafb2b0d454434681950dbbf18a6b44/src/torrent.cpp#L11061
And will never reach this condition
https://github.com/arvidn/libtorrent/blob/73f6aba64eafb2b0d454434681950dbbf18a6b44/src/torrent.cpp#L11084
So `peer_blocked_alert::privileged_ports` never actually fired, `peer_blocked_alert::port_filter` always fired instead.

**Comment by arvidn** [comment]
Do you have a suggestion on how I should solve this?

It seems like the simplest solution would be not not mix the port filter and the `privileged_port` setting.

**Comment by HanabishiRecca** [comment]
Yeah, mixing it up produces weird results. The filter actually is being set even twice:
https://github.com/arvidn/libtorrent/blob/73f6aba64eafb2b0d454434681950dbbf18a6b44/src/session_impl.cpp#L5343

https://github.com/arvidn/libtorrent/blob/73f6aba64eafb2b0d454434681950dbbf18a6b44/src/session_impl.cpp#L1195

I think these chunks can be dropped entirely. Because
https://github.com/arvidn/libtorrent/blob/73f6aba64eafb2b0d454434681950dbbf18a6b44/src/torrent.cpp#L11084

deals with it anyway, regardless of port filter settings.

**Comment by HanabishiRecca** [comment]
Btw, in current state 1024 port is filtered, which is technically wrong. As documentation states, privileged ports are **below** 1024. So `adr.port() < 1024` condition is actually will the right one here.

**Comment by arvidn** [comment]
how does this look? https://github.com/arvidn/libtorrent/pull/7304
