### ISSUE TITLE
macOS aarch64 wheel files missing on pypi

### ISSUE THREAD

**Issue by robd003** [arvidn/libtorrent#7308]
Now that the CI system is building macOS ARM64 wheel files could you please upload them to pypi?

At the moment only macOS x86_64 is available: https://pypi.org/project/libtorrent/#files

**Comment by robd003** [comment]
Hey @arvidn could you please help upload the new wheels to pypi?

**Comment by arvidn** [comment]
the process for uploading the pypi wheels is define by this job https://github.com/arvidn/libtorrent/blob/RC_2_0/.github/workflows/cibuildwheel.yml

Is there any chance that could be extended to also publish the arm64 wheels?

**Comment by robd003** [comment]
Let's keep this ticket open

**Comment by efiop** [comment]
For the record, might be fixed by https://github.com/arvidn/libtorrent/pull/7548

**Comment by ben221199** [comment]
I have set a workflow back from `macos-latest` to `macos-13` because of this.
