### ISSUE TITLE
Not all trackers retry on failure

### ISSUE THREAD

**Issue by HanabishiRecca** [arvidn/libtorrent#7322]
There are `announce_to_all_tiers` and `announce_to_all_trackers` options to enable announcing to all trackers in the list.

But still only 1st tracker in 0 tier of a torrent retries again on failure. All other trackers are essentially remain dead if the connection once failed for some reason.

_I actually discovered this inconsistency a long time ago, but get a deep dive into it only now._

I was able to track the issue down to here:

https://github.com/arvidn/libtorrent/blob/356219bda36077329051b68ca253db9e7de1932d/src/torrent.cpp#L3124

Removing this line seemingly fixes the issue. But I can't figure out why, your code is fairly complex.

**Comment by arvidn** [comment]
Thanks for the report!
Yes, that code is unfortunately quite complex. There are tests in the simulator that cover various tracker setups, we should add coverage there to reproduce.

**Comment by arvidn** [comment]
in your scenario, do you enable both `announce_to_all_tiers` and `announce_to_all_trackers`?

**Comment by arvidn** [comment]
I update the patch and added another test case
