### ISSUE TITLE
Open up uTP stream between 2 peers without torrent management

### ISSUE THREAD

**Issue by su-xingyu** [arvidn/libtorrent#7336]
Hello,

I am a master student at SaCS Lab at EPFL. I want to use the uTP implementation in distributed machine learning setting to transfer data between peers, and have a few questions about its feasibility.

 1. Is it possible to open up a uTP stream and transfer data between 2 peers using `aux::utp_stream` and `aux::utp_socket_manager`? We want to avoid the overhead introduced by torrent management and ideally the uTP sockets can work in a similar manner as UDP or TCP sockets.

 2. Which properties should I set when building the source code to access all functions needed for opening up a uTP stream? I see that the visibility of `aux` namespace is hidden by default. I tried to apply some settings when building `version 2.0.8` with cmake
	```cmake
	set_target_properties(torrent-rasterbar
		PROPERTIES
			CXX_VISIBILITY_PRESET "default"
			VISIBILITY_INLINES_HIDDEN "false"
	)
	target_compile_definitions(torrent-rasterbar PUBLIC TORRENT_EXPORT_EXTRA)
	```
	But there was still some link error when I tried to build `fuzzers/src/utp.cpp`.

 3. Is there any example for opening up uTP stream and transferring data using `aux::utp_stream`? `fuzzers/src/utp.cpp` seems outdated and is not very complete.

Looking forward to hearing back and thanks in advance!

**Comment by luzpaz** [comment]
Is this ticket still relevant ?
