### ISSUE TITLE
[Feature request] Proxying traffic in DHT

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#7340]
@arvidn There is only one problem left today, when a torrent file cannot be downloaded by other peers.
For example: there are 15 peers located behind different NAT (4G internet). One of these peers created a torrent and all others want to download it. They will never be able to download it until one of the 15 peers has a white ip address or something like that.

For downloading to start we need peers with white ip and they are available only in DHT cloud.

It is possible to add to library logical flag which enables and disables voluntary proxying of torrent traffic via DHT node.
Peers (who can't download torrent) should start looking for proxies in DHT at the very last moment when all other methods didn't work.
There will probably be rare, false positives and downloads, through proxies, which increases traffic, but saves people time, which is a higher priority.

The proxy should be turned off when there is a working peer with downloadable data.
Proxy peer - should only proxy traffic, not store it.
The proxy must support the three torrent protocols: UDP, TCP, HTTPS and retransmit the data in the protocol that will be requested.

DHT nodes proxying traffic must have a special logical flag with the port number (for proxy).

**Comment by master255** [comment]
Perhaps [this comment](https://github.com/arvidn/libtorrent/issues/7440#issuecomment-1561642331) solves the problem

**Comment by ValeZAA** [comment]
Is not that already implemented in https://play.google.com/store/apps/details?id=org.proninyaroslav.libretorrent

E.g.? It uses 11.162.19.103 ips, which belong to DOD USA that work as your proxy for DHT network.

**Comment by master255** [comment]
@ValeZAA No. It's about the problem when all the peers are behind the nat. And no one has open ports to the network.
