### ISSUE TITLE
Treat CGNAT address space as a local network

### ISSUE THREAD

**Issue by HanabishiRecca** [arvidn/libtorrent#7357]
I think it will be a good idea to treat [CGNAT](https://en.wikipedia.org/wiki/Carrier-grade_NAT) address space (`100.64.0.0/10`) as a local network.
IPs from this range can't be global, it always will be a peer from a local network of an ISP, if present.

Examples of what I refer to:

https://github.com/arvidn/libtorrent/blob/7a266700af4376ee447d8ebf80fac7fb8081c83b/src/session_impl.cpp#L406

https://github.com/arvidn/libtorrent/blob/7a266700af4376ee447d8ebf80fac7fb8081c83b/docs/dht_sec.rst?plain=1#L212

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/7389
