### ISSUE TITLE
[Question] Bandwideth limit way.

### ISSUE THREAD

**Issue by yutayu** [arvidn/libtorrent#7384]
**Please provide the following information**

libtorrent version (or branch):
libtorrent: 1.2.9.0
platform/architecture:
raspbian
compiler and compiler version:

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I set qdisc cake traffic shaping.
At the same time , I set deluge bandwidth limitter Because I think deluge bandwidth limitter doesn't make packet more than qdisc traffic shaping.

Is this thought correct?

**Comment by arvidn** [comment]
libtorrent does not implement its rate limit very efficiently unfortunately. The router might do a better job.

**Comment by arvidn** [comment]
ideally, download rate limits would be implemented by limiting the *requests* made to peers. That would be efficient, and be good for the swarms. It would probably be even more noisy though

**Comment by yutayu** [comment]
Thank you so much for your reply.
I got it.
