### ISSUE TITLE
Adopt libp2p to take care of basic p2p functionality 

### ISSUE THREAD

**Issue by SemiAccurate** [arvidn/libtorrent#7395]
I hope this is not so crazy an idea. Adopting [libp2p](https://github.com/libp2p/libp2p) would eliminate the chores of maintaining and bug fixing basic p2p functions like the Kademlia DHT, add new transports including QUIC & WebTransport (in addition to WebRTC), also take care of peer discovery, NAT traversal and hole punching, etc. All of this would be done for libtorrent, which would be free to focus on functionality specific to torrenting.

**Comment by ukoz** [comment]
libp2p is meme

**Comment by arvidn** [comment]
I don't think it's viable, but I'm open to being convinced otherwise. preferably through patches.

**Comment by arvidn** [comment]
it would be an enormous amount of work and quite likely to result in tons of bugs and either not working or having to cut features from libtorrent

**Comment by master255** [comment]
@arvidn 3 days of integration? And a couple weeks of fine-tuning?
Okay okay, everyone thinks to the best of their ability. I have already integrated Libp2p into Libtorrent. And it didn't require any code changes in Libtorrent. Good library :)
