### ISSUE TITLE
ERROR: no files in torrent

### ISSUE THREAD

**Issue by hekkr000** [arvidn/libtorrent#7406]
libtorrent version (or branch): 2.0.8-4 (Apparently from April 2023) [https://archive.archlinux.org/packages/l/libtorrent-rasterbar/]
platform/architecture: x86 Arch Linux

There are certain torrent files that are throwing this exception whenever they are parsed: ERROR: no files in torrent [libtorrent:16]
I tested this with qBittorrent and with the dump_torrent example provided here: https://www.[libtorrent](https://www.libtorrent.org/examples.html).org/examples.html

I've also tested it with BitTorrent, which was able to add it, and start downloading such files.
I've also managed to extract the information from the torrent file using torrent-file-editor, so the torrent itself should be fine.

I'm not sure if I can manage to find an example that is safe to share, so please contact me if you cannot get this through meta download: 9ef1b6b2878683838f7de911382efaa118ba3595

I've seen a lot of errors coming in lately, I'm estimating about 100 torrents/hour with such errors, and some more "missing or invalid 'hash' entry [libtorrent:175]", but that one I'm still investigating, maybe some clients are creating files that are not up to specification?

**Comment by hekkr000** [comment]
As for the invalid 'hash' entry error, the same could be said. qBittorent fails, BitTorrent loads it, torrent-file-editor can read it as well. However this one doesn't fail when it tries to read the data, the example "dump_torrent" function works, it fails when generate is called on create_torrent. I would say that this happens just about as often as the no files in torrent error. Here is an example: a03e9eabb77054bafe9bf7821f17ddabcb9b160e

**Comment by MassaRoddel** [comment]
I can confirm this problem (in master branch). extract_files2() failes to find the file. Actually, extract_single_file2() is never called. I received the metadata from transmission so maybe the problem is a wrong metadata structure caused by transmission or a logic error on the libtorrent side.

**Comment by hekkr000** [comment]
I'm closing this issue as the hashes that generated it no longer give me these errors. I guess it really was a rogue client.

**Comment by arvidn** [comment]
Does anyone have the .torrent file for this?
You're not supposed to be able to send metadata over the network that *matches* the info-hash but is different from the original torrent. That would be a serious issue.

@hekkr000 it sounds like you *used* to see this error when adding the magnet link, but not anymore, it works now. Is that right?
Did you capture the metadata/torrent file that was failing?

@MassaRoddel do you have a copy of the failing torrent file?

(if so, please send it to me at arvid@libtorrent.org)

**Comment by MassaRoddel** [comment]
I do not have a torrent file for this. I did run my client in the debugger to test it and since it failed to decode no file was saved (info hash + dht was used to find a peer to get the metadata).
I just used the debugger to look at the metadata which was received and there it failed to decode.

**Comment by hekkr000** [comment]
I've sent you 2 torrent files, that give such errors. I'm not sure if they were generated using libtorrent, but I think they were.
