### ISSUE TITLE
want_tick invariant fails when resuming a torrent in a paused session

### ISSUE THREAD

**Issue by jonathanmcdougall** [arvidn/libtorrent#742]
RC_1_1

With the following:

    lt::session s;
    s.pause();
    
    lt::add_torrent_params ps;
    ps.ti = boost::make_shared<lt::torrent_info>("file.torrent");
    ps.flags = lt::add_torrent_params::flag_paused;
    ps.save_path = ".";
    
    s.async_add_torrent(ps);
    
    std::this_thread::sleep_for(std::chrono::seconds(1));
    s.get_torrents()[0].resume();
    std::this_thread::sleep_for(std::chrono::seconds(1));

The invariant check on torrent.cpp:9000 fails:

    TORRENT_ASSERT(want_tick() == m_links[aux::session_interface::torrent_want_tick].in_list());

Stack trace:

    torrent::check_invariant() Line 9000
    invariant_access::check_invariant<libtorrent::torrent>(const libtorrent::torrent & self) Line 24
    check_invariant<libtorrent::torrent>(const libtorrent::torrent & x) Line 31
    invariant_checker_impl<libtorrent::torrent>::~invariant_checker_impl<libtorrent::torrent>() Line 58
    torrent::resume() Line 9984

The call to `do_resume()` in `torrent::resume()` is basically a no-op because of the early check of `is_paused()`, which is true because the session itself is paused.

    void torrent::do_resume()
    {
        TORRENT_ASSERT(is_single_thread());
        if (is_paused()) return;
        [...]
    }

This skips updating a bunch of stuff, such as `update_want_tick()` on torrent.cpp:10018.

I think the problem is with the invariant check (which should probably use `is_paused()` in some way), not the behaviour of `do_resume()`.

**Comment by arvidn** [comment]
the session-level pause has always been a hack :/ I added it to make it possible to not have a race condition when saving resume data on shutdown. I've actually been dreaming about removing that feature..

anyway, I'll add your test to the test suite and make sure it passes.

**Comment by arvidn** [comment]
I can't reproduce this issue in RC_1_1. would you mind giving that version a try? It's possible this has been fixed already (although, nothing stands out in the log with a quick skim)

**Comment by jonathanmcdougall** [comment]
This *is* on RC_1_1, as I mentioned on top. Let me try to figure this out.

**Comment by arvidn** [comment]
oh, right. I thought maybe you were on the 1.1 release

**Comment by arvidn** [comment]
I added added your test to test/test_session.cpp and it's passing on all CIs as well

**Comment by jonathanmcdougall** [comment]
Yeah, I can reproduce this consistently on RC_1_1, Visual C++ 2015 Update 2, Windows 10 x64.

This is how I built libtorrent:

    set BOOST_ROOT=d:\dev\libraries\boost_1_60_0
    set BOOST_BUILD_PATH=%BOOST_ROOT%
    set PATH=%PATH%;%BOOST_ROOT%
    
    bjam ^
        address-model=64 ^
        toolset=msvc ^
        boost-link=shared ^
        logging=on ^
        dht=on ^
        asserts=auto ^
        encryption=on ^
        mutable-torrents=on ^
        crypto=built-in ^
        allocator=pool ^
        link=shared ^
        runtime-link=shared ^
        variant=debug ^
        character-set=unicode ^
        invariant-checks=on ^
        debug-symbols=on ^
        deprecated-functions=off ^
        iconv=auto ^
        i2p=on ^
        profile-calls=on ^
        --abbreviate-paths ^
        %*

This is my full test case:

    #define TORRENT_DEBUG 1
    #define TORRENT_NO_DEPRECATE 1
    #include <libtorrent/session.hpp>
    #include <libtorrent/torrent_info.hpp>
    #include <libtorrent/entry.hpp>
    #include <thread>
    #include <chrono>
    
    int main()
    {
        libtorrent::session s;
        s.pause();
    
        libtorrent::add_torrent_params ps;
        ps.ti = boost::make_shared<libtorrent::torrent_info>("a.torrent");
        ps.flags = libtorrent::add_torrent_params::flag_paused;
        ps.save_path = ".";
    
        s.async_add_torrent(ps);
    
        std::this_thread::sleep_for(std::chrono::seconds(1));
        s.get_torrents()[0].resume();
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }


Building (I left the include and lib paths out):

    cl /EHsc /MDd /c a.cpp
    cl a.obj torrent.lib /Fe:a.exe

Executing:

    > a
    assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
    Please include the following information:
    
    version: 1.1.0.0-044ee0f
    
    file: 'src\torrent.cpp'
    line: 9000
    function: libtorrent::torrent::check_invariant
    expression: want_tick() == m_links[aux::session_interface::torrent_want_tick].in_list()
    
    stack:
    0: print_backtrace
    1: assert_fail
    2: libtorrent::torrent::check_invariant
    3: libtorrent::invariant_access::check_invariant<libtorrent::torrent>
    4: libtorrent::check_invariant<libtorrent::torrent>
    5: libtorrent::invariant_checker_impl<libtorrent::torrent>::~invariant_checker_impl<libtorrent::torrent>
    6: libtorrent::torrent::resume
    7: boost::_mfi::mf0<void,libtorrent::torrent>::call<boost::shared_ptr<libtorrent::torrent> >
    8: boost::_mfi::mf0<void,libtorrent::torrent>::operator()<boost::shared_ptr<libtorrent::torrent> >
    9: boost::_bi::list1<boost::_bi::value<boost::shared_ptr<libtorrent::torrent> > >::operator()<boost::_mfi::mf0<void,libtorrent::torrent>,boost::_bi::list0>
    10: boost::_bi::bind_t<void,boost::_mfi::mf0<void,libtorrent::torrent>,boost::_bi::list1<boost::_bi::value<boost::shared_ptr<libtorrent::torrent> > > >::operator()
    11: boost::asio::asio_handler_invoke<boost::_bi::bind_t<void,boost::_mfi::mf0<void,libtorrent::torrent>,boost::_bi::list1<boost::_bi::value<boost::shared_ptr<libtorrent::torrent> > > > >
    12: boost_asio_handler_invoke_helpers::invoke<boost::_bi::bind_t<void,boost::_mfi::mf0<void,libtorrent::torrent>,boost::_bi::list1<boost::_bi::value<boost::shared_ptr<libtorrent::torrent> > > >,boost::_bi::bind_t<void,boost::_mfi::mf0<void,libtorrent::torrent>,boost::_bi::list1<boost::_bi::value<boost::shared_ptr<libtorrent::torrent> > > > >
    13: boost::asio::detail::completion_handler<boost::_bi::bind_t<void,boost::_mfi::mf0<void,libtorrent::torrent>,boost::_bi::list1<boost::_bi::value<boost::shared_ptr<libtorrent::torrent> > > > >::do_complete
    14: boost::asio::detail::win_iocp_operation::complete
    15: boost::asio::detail::win_iocp_io_service::do_one
    16: boost::asio::detail::win_iocp_io_service::run
    17: boost::asio::io_service::run
    18: boost::_mfi::mf0<unsigned __int64,boost::asio::io_service>::operator()
    19: boost::_bi::list1<boost::_bi::value<boost::asio::io_service * __ptr64> >::operator()<unsigned __int64,boost::_mfi::mf0<unsigned __int64,boost::asio::io_service>,boost::_bi::list0>
    20: boost::_bi::bind_t<unsigned __int64,boost::_mfi::mf0<unsigned __int64,boost::asio::io_service>,boost::_bi::list1<boost::_bi::value<boost::asio::io_service * __ptr64> > >::operator()
    21: boost::asio::detail::win_thread::func<boost::_bi::bind_t<unsigned __int64,boost::_mfi::mf0<unsigned __int64,boost::asio::io_service>,boost::_bi::list1<boost::_bi::value<boost::asio::io_service * __ptr64> > > >::run
    22: boost::asio::detail::win_thread_function
    23: register_onexit_function
    24: register_onexit_function
    25: BaseThreadInitThunk
    26: RtlUserThreadStart

**Comment by jonathanmcdougall** [comment]
> I added added your test to test/test_session.cpp and it's passing on all CIs as well

You didn't add my test, you added a different one that uses `info_hash` instead of `ti`.

**Comment by arvidn** [comment]
ah, yes. you're right. having the metadata may be significant there.. I'll update

**Comment by arvidn** [comment]
ok, making that change reproduces it. thanks!

**Comment by arvidn** [comment]
attempted fix: https://github.com/arvidn/libtorrent/pull/750

**Comment by jonathanmcdougall** [comment]
I'm not sure about that fix. `do_resume()` does a lot of stuff which wouldn't normally happen for paused torrents. If you mean for paused torrents to behave exactly like resumed torrents in a paused session, then this fix would be incorrect. Among other things:

- `on_resume()` is called on all extensions
- `torrent_resumed_alert` will be posted
- `m_started` is set, so active time will be off

Some calls will be no-ops because they themselves check for pause (such as `start_announcing()`), but others don't (`want_tick`) so it sounds as if you'd get a weird state where parts of the torrent are paused, but others aren't.

None of my (limited) tests are failing with this change, and it does fix my original report, but it makes me a bit uneasy.

**Comment by arvidn** [comment]
I agree. the session calls do_resume() as well to notify torrents when it's resumed. I'll take another approach.
