### ISSUE TITLE
peer_blocked_alert doesn't inherit from peer_alert

### ISSUE THREAD

**Issue by jonathanmcdougall** [arvidn/libtorrent#743]
RC_1_1

`peer_blocked_alert` is the only peer alert to derive from `torrent_alert` instead of `peer_alert`. It would be useful if `dynamic_cast<peer_alert*>` could work for all of them.

**Comment by arvidn** [comment]
I wonder if changing this necessarily has to change the ABI. It seems like it would be very likely to

**Comment by arvidn** [comment]
actually, iirc, the reason for this alert not to be a peer_alert is that peer object never existed. To some degree this is just the torrent informing about a potential peer that never was one.

**Comment by jonathanmcdougall** [comment]
You could argue either way, I guess. To me, this is an alert about a peer, not a torrent. Since `peer_alert` doesn't actually expose a `peer` object, I don't think it would be a problem.

In fact, I'm pretty sure I've received a `peer_disconnected_alert` as the first alert about a peer before. I had to add a "find or add" function for every peer alert I get, since there's no alert that's guaranteed to always be fired first for a peer.

Ultimately, this is small stuff. I just added a special case for `peer_blocked_alert` and changed my peer alert handling function to take a `torrent_alert` instead of a `peer_alert` (which did make me a bit sad though).

As for the ABI, it would most definitely change since `peer_alert` has an `endpoint` instead of an `address`, plus an additional `pid`.

**Comment by arvidn** [comment]
I'll make this change in master then, to preserve 1.1.x ABI

**Comment by arvidn** [comment]
does this seem reasonable? https://github.com/arvidn/libtorrent/pull/747

**Comment by jonathanmcdougall** [comment]
I'm having some issues, can you hop on irc?

**Comment by jonathanmcdougall** [comment]
This looks perfect. Thanks!
