### ISSUE TITLE
Libp2p ready integration recipe?

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#7440]
@arvidn How can [go-libp2p](https://github.com/libp2p/go-libp2p) be used to download torrents? 
Is integration with the go-libp2p library planned or already exists?

**Comment by ukoz** [comment]
https://github.com/arvidn/libtorrent/issues/7395

**Comment by master255** [comment]
I found a ready-made recipe! It is necessary to add libp2p peer id to the extended handshake. Then create local http server with any port ( for example 6500). On getting such a handshake add url-seed with address http://127.0.0.1/wqewqeqweqweqweqwqeqweqweq (libp2p peer id from handshake). Libtorrent will send http request to local server and server will convert and redirect request via libp2p to this peer wqewqeqweqweqwqeqweq . The peer will return the information and the server will return it as an http response.
Done. It is possible to add any protocol (or library) in this way.

**Comment by master255** [comment]
@arvidn @aldenml @gubatron @glassez @proninyaroslav  [I did this](https://t.me/media_library/13173): when adding a torrent - it is searched in Libp2p DHT. The library checks and returns peers (it's very easy). Then found peers are added, like this:
handle.add_url_seed("http://127.0.0.1:40000/" + peerId);
The local webserver accepts the http request and connects to the Libp2p peer by peerId.
It gets the file size and transfers the data. Everything happens at maximum speed and using all Libp2p technologies.
The server side of Libp2p (the same client) receiving a request for file distribution - checks if there is a torrent distribution of this torrent in Libtorrent and only after that starts distribution of the file.

Leave the Nobel Prize under the door :-)
