### ISSUE TITLE
Torrents Stop Announcing

### ISSUE THREAD

**Issue by Jaywalker** [arvidn/libtorrent#7457]
libtorrent version (or branch): 2.0.9

platform/architecture: Linux/amd64

compiler and compiler version: Compiled by Arch package maintainer

My issue is pretty well described in this post: https://forum.deluge-torrent.org/viewtopic.php?t=56245

but tl;dr, when I first launch Deluge, all torrents announce fine, but when it comes time to reannounce, nothing happens on several hundred (seems to be the most recently added torrents). Force Reannounce/Update Tracker doesn't do anything it seems, but if I pause and restart the torrent, they continue seeding as expected until it comes time to reannounce again.

I've tried with both libtorrent 2.0.8 and 2.0.9 and saw the same issue. I couldn't downgrade further without having way too many packages affected due to dependencies.

**Comment by DUTNO1** [comment]
I think this is due to the `active_tracker_limit` being reached if you have a lot of torrents, this can be increased with the plugin [deluge-ltconfig](https://github.com/ratanakvlun/deluge-ltconfig).

**Comment by Jaywalker** [comment]
Thanks so much!! It looks like you were right and that was the issue. I've increased that number and it looks like my torrents are now announcing properly!!

Seems to me that this variable should be accessible by Deluge's standard interface without a plugin, but that's a bug to post in a different bug tracker :P.
