### ISSUE TITLE
I2P SAM ID isn't persistent

### ISSUE THREAD

**Issue by ExperiBass** [arvidn/libtorrent#7464]
It appears libtorrent doesn't reuse SAM session IDs. This has the effect of creating a new destination each time a client is restarted, which is different from what i'm used to (for example, bitcoind).  
This also seems to confuse tracker2.postman.i2p, as you appear as a new client to it.  
I tested this with `client_test --i2p_hostname="localhost" --i2p_port=7656 "magnet:?xt=urn:btih:37533aa1c010678587a4a2966e29ad56f0bd0043&dn=I2P%2B+2.3.0%2B+%28i2pupdate.zip%29&tr=http://tracker2.postman.i2p/announce.php"`.

libtorrent version (or branch): c2012b084  
platform/architecture: Linux x86_64  
compiler and compiler version: GCC 13.1.1

**Comment by Vort** [comment]
From [documentation](https://geti2p.net/en/docs/api/samv3) it looks like SAM ID and destination are generated independently and to use fixed destination, all needed keys should be specified in session creation request, which is non-trivial.
From usability point of view, dynamic destination is preferred mode of operation - it increases anonymity.
Anyway, even if such a feature were to be implemented, it should be optional.

**Comment by ExperiBass** [comment]
> Anyway, even if such a feature were to be implemented, it should be optional.

yeah, thinking over it again i agree. i'll close this issue.
