### ISSUE TITLE
ERROR: No matching distribution found for libtorrent

### ISSUE THREAD

**Issue by iw4p** [arvidn/libtorrent#7473]
pip3 install libtorrent
ERROR: Could not find a version that satisfies the requirement libtorrent (from versions: none)
ERROR: No matching distribution found for libtorrent

libtorrent version (or branch): 2.0.7

platform/architecture: macOS M1 - Windows 10

compiler and compiler version:

Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.1.0
Thread model: posix

I tried to install it with pip (which is from torrentp) on both mac and windows and I got this error:

<img width="1003" alt="Screenshot 2023-07-13 at 3 27 17 PM" src="https://github.com/arvidn/libtorrent/assets/30632761/b1d79eb0-9e07-40dc-bb89-e0a8fffabbde">

I tried to use other versions also, but it does not work.

<img width="863" alt="Screenshot 2023-07-13 at 3 31 20 PM" src="https://github.com/arvidn/libtorrent/assets/30632761/d5b5fcd9-f39a-43ed-af2d-cb2ca9b1f884">

**Comment by pedrodearaujoalvarenga** [comment]
having the same problem here. downgrading python to 3.9 worked but now having error 

    import libtorrent
ImportError: DLL load failed while importing libtorrent

**Comment by iw4p** [comment]
> having the same problem here. downgrading python to 3.9 worked but now having error
> 
> ```
> import libtorrent
> ```
> 
> ImportError: DLL load failed while importing libtorrent

So now you can install it without any problem, but you can not use it at all, right?

**Comment by pedrodearaujoalvarenga** [comment]
Found way to deal with the problem (in my specific case):
Use Google Colab. It is working there.

**Comment by iw4p** [comment]
> Found way to deal with the problem (in my specific case): Use Google Colab. It is working there.

Yes exactly, I tried it on Colab yesterday and It is fine.

**Comment by guseggert** [comment]
The libtorrent PyPI package doesn't include an arm64 version for MacOS, that would need to be released.

**Comment by PystoyPlayer** [comment]
sad

**Comment by arvidn** [comment]
Would anyone be interested in contributing a github workflow that builds the wheel for M1?
I also seem to recall that the release script may have been failing for the last few releases

**Comment by iw4p** [comment]
I can contribute for M1 and testing it if anyone has experience or can help.

**Comment by alexkutsan** [comment]
I am also struggling from that :-(

**Comment by gourangasatapathyvit** [comment]
i resolved in windows using  - 

`python -m pip install --upgrade pip setuptools wheel`
`python -m pip install lbry-libtorrent`

**Comment by Wamy-Dev** [comment]
this is still an issue

**Comment by iw4p** [comment]
@arvidn What's the essentials for releasing it on MacOS M1 and Windows? Give us an instruction and we'll try to contribute.
