### ISSUE TITLE
Upnp port is not re-announced

### ISSUE THREAD

**Issue by master255** [arvidn/libtorrent#7487]
@arvidn There is a serious problem with upnp port announcement.

Turn on the application (Libtorrent application where there is upnp announcement). Upnp port is announced on the router. It is announced every minute (for test).
Then turn off the internet connection in the router settings or pull the wire out of the router (emulate a real internet disconnection). Then turn on the Internet.
Check upnp ports. There are none. And, even after 5 minutes they do not appear.
This presents a serious problem. Because the stability of the internet connection is very bad all over the world (I checked).

**Comment by master255** [comment]
@arvidn Let's solve this bug? It's very important.

**Comment by arvidn** [comment]
Do you have a solution in mind?

**Comment by master255** [comment]
At the Libp2p meeting, when discussing this problem - it seems they were saying that an error occurs - wrong gateway. I haven't looked into the problem yet. But they are going to fix it. I don't know how the upnp port creation protocol works on a router. But it's clearly having a problem.

**Comment by master255** [comment]
Can't reproduce in 1.2.19
