### ISSUE TITLE
How to build to separate the build output as separated .a file and headers

### ISSUE THREAD

**Issue by jingliancui** [arvidn/libtorrent#7513]
**Please provide the following information**

libtorrent version (or branch):
clone from here git clone --recurse-submodules https://github.com/arvidn/libtorrent.git, so maybe the rc2

platform/architecture:
here https://github.com/arvidn/libtorrent/blob/RC_2_0/.github/workflows/macos.yml#L110

compiler and compiler version:
boost the latest version

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
https://github.com/arvidn/libtorrent/blob/RC_2_0/.github/workflows/macos.yml#L110
direct using this command

result,the second picture is mine output:
reference https://github.com/official-antique/QuixTorrent/issues/1
<img width="684" alt="Screenshot 2023-09-02 at 22 16 21" src="https://github.com/official-antique/QuixTorrent/assets/16309962/aac6d05c-f0aa-4840-a9a5-b70642abd12c">
<img width="588" alt="Screenshot 2023-09-02 at 22 17 30" src="https://github.com/official-antique/QuixTorrent/assets/16309962/bf4103b2-c3b6-48d6-9156-97304ba8ea56">

**Comment by arvidn** [comment]
I'm not sure what the question is. If you want to build a static library (i.e. archive) you say:
```
b2 link=static
```

**Comment by jingliancui** [comment]
thanks, I can figure it out now, it's about the apple dev stuff, so this issue can be closed, thanks again.
