### ISSUE TITLE
Size rasterbar.so.10.0.0 = 81MByte

### ISSUE THREAD

**Issue by xdostup** [arvidn/libtorrent#7522]
Good day.
libtorrent-1.2.19 gcc-4.9(and gcc-9.5) boost-1.69 i686(32bit) 

./configure --prefix=/usr/local --enable-encryption --with-boost=yes --disable-logging --with-cxx-standard=11

after building size libtorrent-rasterbar.a = 180MByte and libtorrent-rasterbar.so.10.0.0 = 81MByte. Is such a large size normal ?

**Comment by xdostup** [comment]
b2 install -j 2 --prefix=./usr/local cxxstd=11 release boost-link=static logging=off dht=on asserts=off encryption=on crypto=openssl debug-symbols=off i2p=on profile-calls=off utp-log=off picker-debugging=off

libtorrent-rasterbar.so.10.0.0 = 5MByte size is normal

**Comment by master255** [comment]
![image](https://github.com/arvidn/libtorrent/assets/5380115/96adac3a-e615-4b2e-bfb8-3c42b8717e40)
Normal size libraries. Use https://github.com/frostwire/frostwire-jlibtorrent

**Comment by master255** [comment]
Okay. Don't forget to close the issue.
