### ISSUE TITLE
Python 3.11 wheels?

### ISSUE THREAD

**Issue by mayli** [arvidn/libtorrent#7536]
I am lookin at pypi, it seems the wheels are built up to python3.10, any plan to push 3.11 builds?

**Comment by ichorid** [comment]
The fix necessary for Python 3.11 to work with Libtorrent was pushed on May 28, just after the 2.0.9 release. There were recent patches related to Python support by @arvidn, too. I guess @arvidn is planning to update the wheels with the Libtorrent 2.10 release.

**Comment by mxctx-jake** [comment]
Any updates to this issue?

I am unable to install libtorrent on my system due to this.
```
pip3 install libtorrent
ERROR: Could not find a version that satisfies the requirement libtorrent (from versions: none)
ERROR: No matching distribution found for libtorrent
```

**Comment by JokerGT** [comment]
same here on 3.12.4

**Comment by sochartgit** [comment]
any update ? same trouble here
