### ISSUE TITLE
libtorrent::aux::watermark_callback thread-safety issue

### ISSUE THREAD

**Issue by dushabaev** [arvidn/libtorrent#7540]
Here is a [`libtorrent::aux::watermark_callback::watermark_callback()`](https://github.com/arvidn/libtorrent/blame/5ce4c516479085eda9327d35891b7732d6d5037b/src/disk_buffer_pool.cpp#L65C7-L65C25) function. It's called only on the network thread, so this function itself is ok.

Now, let's look at how it's posted: [`disk_buffer_pool.cpp#L106`](https://github.com/arvidn/libtorrent/blame/5ce4c516479085eda9327d35891b7732d6d5037b/src/disk_buffer_pool.cpp#L106).

The `post()` function itself should be thread-safe, so unlocking passed lock `l` before posting seems okay too.

But if `check_buffer_level` would be called simultaneously with `watermark_callback`, then this [`swap()`](https://github.com/arvidn/libtorrent/blame/5ce4c516479085eda9327d35891b7732d6d5037b/src/disk_buffer_pool.cpp#L104C3-L104C25) corrupts `watermark_callback`'s loop over `cbs`

Should we consider pass lock inside `watermark_callback` too?

**Comment by arvidn** [comment]
I don't see how there would be a data race. the `swap` is done under the mutex. so the *member* `m_observers` is swapped out to an empty vector with no problem. The swapped vector is then posted to the callback. There's no other thread referencing that vector. No mutex need to be held while iterating it.
