### ISSUE TITLE
How to set disk_io_constructor and how to define custom class disk_interface in python?

### ISSUE THREAD

**Issue by hlf20010508** [arvidn/libtorrent#7556]
**Please provide the following information**

libtorrent version (or branch): 2.0.9.0

platform/architecture: macOS 13.6, Apple M2

compiler and compiler version: Python 3.8.10

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I've checked the doc [Custom Storage](https://libtorrent.org/reference-Custom_Storage.html), but I don't know where to pass `disk_io_constructor ` in python bindings, and I don't know if I can create custom class `disk_interface` in python.

I need help.

**Comment by joriscarrier** [comment]
hi, unfortunately this is not available for python binding.

**Comment by hlf20010508** [comment]
> hi, unfortunately this is not available for python binding.

Thank you for your explanation.
