### ISSUE TITLE
Rethinking test_ssl's certificate expiration

### ISSUE THREAD

**Issue by graywolf** [arvidn/libtorrent#7565]
As far as I can tell, currently test_ssl uses a certificate located in test/ssl.  That certificate has a certain expiration date and is periodically refreshed.  That complicates running the test suite for older releases, since the certificate would be already expired.

I would like to inquire what is the reason for this approach, and whether it would be possible to just have a certificate expiring in the year 9999.  That would remove the need to spend time on certificate rotations and would allow the test suite to be ran even in the future.  And since this is just a test certificate, there are no security considerations.

Thank you for considering this.

**Comment by arvidn** [comment]
I would prefer that. I've spent a little bit of time trying to figure out how to ask OpenSSL's tools to extend the default expiration, but haven't managed to yet. If you know how, I'd love to update the test certificates.

**Comment by arvidn** [comment]
yes, it will create the CA cert like that (`root_ca_cert.pem`), but the certificate request (`peer_certificate.pem`) is still only valid for 1 year.

iirc, it's the `CA.pl -newreq` script that creates the certificate request, and it also needs to request a later expiration time.

Even with this change, I don't get a peer certificate that lasts longer than a year.

``` diff
index 58adcc9be..86c1414da 100755
--- a/test/ssl/regenerate_test_certificate.sh
+++ b/test/ssl/regenerate_test_certificate.sh
@@ -7,7 +7,7 @@ cp peer_private_key.pem invalid_peer_private_key.pem
 
 printf "\n\n   ======== \e[33muse common name: * \e[0m=========\n\n"
 
-openssl req -newkey rsa:4096 -nodes -keyout server_key.pem -x509 -days 1097 -out server_cert.pem
+openssl req -newkey rsa:4096 -nodes -keyout server_key.pem -x509 -days 999999 -out server_cert.pem
 cat server_key.pem server_cert.pem >server.pem
 
 PATH=/opt/homebrew/Cellar/openssl@3/3.0.3/bin:/opt/homebrew/etc/openssl@1.1/misc:$PATH:/usr/local/etc/openssl/misc:/usr/lib/ssl/misc
@@ -17,7 +17,7 @@ rm -rf demoCA
 printf "\n\n   ======== \e[33muse passphrase: \"test\" \e[0m=========\n\n"
 printf "\n\n   ======== \e[33muse common name: \"test\" \e[0m=========\n\n"
 
-CA.pl -newca
+CADAYS="-days 999999" CA.pl -newca
 
 cp ./demoCA/cacert.pem root_ca_cert.pem
 cp ./demoCA/private/cakey.pem root_ca_private.pem
@@ -25,11 +25,11 @@ cp ./demoCA/private/cakey.pem root_ca_private.pem
 printf "\n\n   ======== \e[33muse passphrase: \"test\" \e[0m=========\n\n"
 printf "\n\n   ======== \e[33muse common name: * \e[0m=========\n\n"
 
-CA.pl -newreq
+DAYS="-days 999999" CA.pl -newreq
 
 cp newkey.pem peer_private_key.pem
 
-CA.pl -sign
+DAYS="-days 999999" CA.pl -sign
 
 cp newcert.pem peer_certificate.pem
 

```

**Comment by arvidn** [comment]
maybe I have a different version of `CA.pl`, but it doesn't work for me. It's appending the `-days 999999` parameter to the `openssl` command line, but it's at the end, after `-infiles ./demoCA/careq.pem`. This makes openssl interpret it as a file, and fails with:

```
Can't open "-days" for reading, No such file or directory
40D7D18E0B7F0000:error:80000002:system library:BIO_new_file:No such file or directory:../crypto/bio/bss_file.c:67:calling fopen(-days, r)
40D7D18E0B7F0000:error:10000080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:75:
Unable to load certificate request
```

**Comment by arvidn** [comment]
I also see this warning:
```
openssl req  -new  -keyout newkey.pem -out newreq.pem -days 365  -days 999999
Ignoring -days without -x509; not generating a certificate
```

**Comment by arvidn** [comment]
I got this to work.

https://github.com/arvidn/libtorrent/pull/7618
