### ISSUE TITLE
test_copy_file fails on tmpfs

### ISSUE THREAD

**Issue by graywolf** [arvidn/libtorrent#7566]
**Please provide the following information**

libtorrent version (or branch): 2.0.9

platform/architecture: linux/x86_64

When running the test suite, test_copy_file fails since it assumes that tmpfs does not support sparse file, but in fact it does.  Adding TMPFS_MAGIC into sparse_filesystems seems to suffice to fix this problem.

But in general I wonder if more robust detection strategy should not be used, the whitelist approach does seem like it has few holes.

**Comment by arvidn** [comment]
Perhaps, since it's just a test though, it's hard to justify too much effort into making it more robust. But patches are welcome!

Thanks for this, I'll make this change!
