### ISSUE TITLE
[question] IP banned by smart ban global or local (per torrent)

### ISSUE THREAD

**Issue by Antorell** [arvidn/libtorrent#7571]
I was looking at the bug reports on qBittorrent's github and somebody mentioned smart_ban in [one of the bug reports ](https://github.com/qbittorrent/qBittorrent/issues/20111)

I use qbittorrent with libtorrent on linux with the WebUI, and when I looked at the Execution Log tab -> Blocked IPs in qBittorrent, most of the IP that were automatically banned (The "20 xxx.xxx.xxx.xxx \<date\> Banned" format is smart_ban I assume) were from seedbox providers or big VPN vendors with multiples users using the same IP address. 

My question is; are those ban global, the same as if I entered an IP in qBittorrent's "IP Filtering" option, or local tied to the torrent those IP were banned?

If the bans are global, how does one disables smart_ban without disabling all the extensions at compile time?

Thanks.

Edit: recompiling Qbittorrent with `add_extension(&lt::create_smart_ban_plugin);` commented out or removed doesn't disable smart_ban.

```
diff --git a/src/base/bittorrent/sessionimpl.cpp b/src/base/bittorrent/sessionimpl.cpp
index 725ad7735..9a75d2dd3 100644
--- a/src/base/bittorrent/sessionimpl.cpp
+++ b/src/base/bittorrent/sessionimpl.cpp
@@ -48,7 +48,7 @@
 #include <libtorrent/address.hpp>
 #include <libtorrent/alert_types.hpp>
 #include <libtorrent/error_code.hpp>
-#include <libtorrent/extensions/smart_ban.hpp>
+/* #include <libtorrent/extensions/smart_ban.hpp> */
 #include <libtorrent/extensions/ut_metadata.hpp>
 #include <libtorrent/extensions/ut_pex.hpp>
 #include <libtorrent/ip_filter.hpp>
@@ -1571,7 +1571,7 @@ void SessionImpl::initializeNativeSession()
     });
 
     // Enabling plugins
-    m_nativeSession->add_extension(&lt::create_smart_ban_plugin);
+    /* m_nativeSession->add_extension(&lt::create_smart_ban_plugin); */
     m_nativeSession->add_extension(&lt::create_ut_metadata_plugin);
     if (isPeXEnabled())
         m_nativeSession->add_extension(&lt::create_ut_pex_plugin);

```

**Comment by arvidn** [comment]
the peers are only banned for that torrent.

if the session is created by passing in `session_params`, that's where the default plugins are set up. in the `extensions` field.

I find it hard to believe that the smart ban functionality would be detrimental to your performance though. It detects peers that send corrupt data and disconnects them.

**Comment by Antorell** [comment]
I thought it was detrimental because the log text ambiguously report a peer as "banned" without mentioning if it's global or local ban.
