### ISSUE TITLE
Crash when build with boost 1.83

### ISSUE THREAD

**Issue by marillat** [arvidn/libtorrent#7572]
After a rebuild  with boost 1.83 qBittorrent crash as reported in these issues.

Of course I don't know if this is a problem with libtorrent 2.0.9 or boost 1.83

https://github.com/qbittorrent/qBittorrent/issues/20149
https://github.com/qbittorrent/qBittorrent/issues/20148

**Comment by essinghigh** [comment]
Downgrading libtorrent-rasterbar2.0 from 2.0.9-2+b1 to 2.0.9-2 fixed this for me.
https://snapshot.debian.org/archive/debian/20230814T151706Z/pool/main/libt/libtorrent-rasterbar/libtorrent-rasterbar2.0_2.0.9-2_amd64.deb

**Comment by marillat** [comment]
Why librorrent is linked statically with boost ?

**Comment by glassez** [comment]
This should be closed due to https://github.com/qbittorrent/qBittorrent/issues/20149#issuecomment-1865381504.

**Comment by glassez** [comment]
> Why librorrent is linked statically with boost ?

https://github.com/qbittorrent/qBittorrent/issues/20149#issuecomment-1864947209
