### ISSUE TITLE
Add I2P SAM option for more encryption types (i2cp.leaseSetEncType)

### ISSUE THREAD

**Issue by anikey-from-i2p** [arvidn/libtorrent#7578]
Hello. Sorry if i'm not doing this right.

There has been an [issue](https://github.com/qbittorrent/qBittorrent/issues/19625) open in qBittorrent repository for some time. The issue is about not being able to contact some I2P trackers (including the most popular one, tracker2.postman.i2p).

After a discussion, the conclusion is that these unconnectable trackers use a specific encryption type that is not supported by the default SAM settings (namely, type 4 only instead of 0).

The fix is simple: add a SAM option `i2cp.leaseSetEncType=4,0` which will allow to contact trackers that use both of these encryption types.

Here is a link to the line that probably needs to be changed:
https://github.com/arvidn/libtorrent/blob/44598ba5d76e0aa118e656b281b89014032d4868/include/libtorrent/i2p_stream.hpp#L450C47-L450C47

(maybe the buffer size also needs to be increased, but i dont know for sure). (**edit**: it probably does not).

Even official [i2p docs](https://geti2p.net/en/docs/protocol/i2cp) (search for the option name) recommend to set this option to that value.

After testing connectability with SAM and netcat, it definitely seems to work.

**Comment by anikey-from-i2p** [comment]
@Vort why not create a PR with your suggested patch at [issue comment](https://github.com/qbittorrent/qBittorrent/issues/19625#issuecomment-1879582395)? I'm just thinking you should create it because you suggested it.

**Comment by Vort** [comment]
> why not create a PR with your suggested patch at https://github.com/qbittorrent/qBittorrent/issues/19625#issuecomment-1879582395? I'm just thinking you should create it because you suggested it.

I don't like when changes, which can be made in few minutes, require lengthy discussions and months of waiting. I was hoping to avoid excessive actions.
As for copyright (maybe you meant it) - this change is trivial, so copyright does not matter in this case.

I will most likely make PR despite I think it's unnecessary, but not right now.

**Comment by Vort** [comment]
> why not create a PR

Done: #7585.
