### ISSUE TITLE
SIGSEGV in dh_key_exchange class

### ISSUE THREAD

**Issue by Athorcis** [arvidn/libtorrent#759]
libtorrent version: RC_1_1 (44a668db621fc8f949fcc6bb7f5654ced6baecb0)
platform/architecture: windows/x64
compiler: GCC 5.3 (MinGW64)

This crash happens pretty often before i switched to commit 44a668db621fc8f949fcc6bb7f5654ced6baecb0 i was working with the release 1.1.0
and i had a similar crash in the constructor of dh_key_exchange which was fixed by commit 44a668db621fc8f949fcc6bb7f5654ced6baecb0

```
0  0x00000000004cdfc9  libtorrent::dh_key_exchange::compute_secret(char const*)    
1  0x00000000004b54ea  libtorrent::bt_peer_connection::on_receive_impl(unsigned long long)    
2  0x00000000004b6aa5  libtorrent::bt_peer_connection::on_receive(boost::system::error_code const&, unsigned long long)    
3  0x00000000004d62f5  libtorrent::peer_connection::receive_data_impl(boost::system::error_code const&, unsigned long long, int)    
4  0x00000000004d667a  libtorrent::peer_connection::on_receive_data_nb(boost::system::error_code const&, unsigned long long)    
5  0x000000000055a0d6  boost::asio::detail::completion_handler<boost::_bi::bind_t<void, boost::function2<void, boost::system::error_code const&, unsigned long long>, boost::_bi::list2<boost::_bi::value<boost::system::error_code>, boost::_bi::value<unsigned long long> > > >::do_complete(boost::asio::detail::win_iocp_io_service*, boost::asio::detail::win_iocp_operation*, boost::system::error_code const&, unsigned long long)    
6  0x000000000055ce41  complete  /mingw64/include/boost/asio/detail/win_iocp_operation.hpp  46
7  0x000000000055ce41  do_one  /mingw64/include/boost/asio/detail/impl/win_iocp_io_service.ipp  405
8  0x000000000055ce41  boost::asio::detail::win_iocp_io_service::run  /mingw64/include/boost/asio/detail/impl/win_iocp_io_service.ipp  164
9  0x0000000000423eff  std::thread::_Impl<std::_Bind_simple<libtorrent::session::start(int, libtorrent::settings_pack const&, boost::asio::io_service*)::{lambda()#1    
10  0x000000006fd06560  ??    
11  0x0000000064944ac4  ??    
12  0x00007ffcfb06b097  msvcrt!_beginthreadex    
13  0x00007ffcfb06b16c  msvcrt!_endthreadex    
14  0x00007ffcfd818102  KERNEL32!BaseThreadInitThunk    
15  0x00007ffcfdc8c5b4  ntdll!RtlUserThreadStart    
16  0x0000000000000000  ??
```
So i guess preventing this crash is not that hard and adding the same kind of safe guard than commit 44a668d should suffice. But finding the real cause could be more tricky, do you have any ideas?

**Comment by arvidn** [comment]
basically, you're suggesting I back-port that range check in dh_key_exchange::dh_key_exchange() to 1.1 and add another similar one to compute_secret?

**Comment by arvidn** [comment]
is this about what you had in mind? https://github.com/arvidn/libtorrent/pull/761
followed by back-porting it

**Comment by Athorcis** [comment]
i'm not sure that the backport is necessary but yeah it would be nice to add a range check to compute_secret.

When i ran my program in with libtorrent in debug mode the size of the key in dh_key_exchange constructor was 199. Is this a normal behavior or an absurd case?

**Comment by Athorcis** [comment]
this was exactly what I had in mind

**Comment by arvidn** [comment]
my understanding is that preceding zeros are not counted by tommath, and instead the length is less than the full key length. 199 seems pretty low though, it perhaps suggests that the entropy in random() isn't that great

**Comment by Athorcis** [comment]
i dug into tommath code and i found the problem: tommath uses a self defined type called mp_digit used as a base storage unit for the type mp_int. on my environnement this type size 4 bytes long but tommath also defined the constant DIGIT_BIT which is supposed to contain the number of actual bit stored per digit and on my environment this value is set to 60 and this is greater than 32.

The type mp_digit should actually be 8 bytes long, thus the problem happens only on 64bit env.
I looked on tommath github the problem seams to be fixed.

**Comment by arvidn** [comment]
thanks for looking into this. I will upgrade tommath in RC_1_0 and later.
Is there any chance you could help me with a test that exercises this problem?

**Comment by Athorcis** [comment]
Yeah of course, this should do it:

``` cpp
bool isTommathWorking() {
    const unsigned char key[96] = {
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xC9, 0x0F, 0xDA, 0xA2,
        0x21, 0x68, 0xC2, 0x34, 0xC4, 0xC6, 0x62, 0x8B, 0x80, 0xDC, 0x1C, 0xD1,
        0x29, 0x02, 0x4E, 0x08, 0x8A, 0x67, 0xCC, 0x74, 0x02, 0x0B, 0xBE, 0xA6,
        0x3B, 0x13, 0x9B, 0x22, 0x51, 0x4A, 0x08, 0x79, 0x8E, 0x34, 0x04, 0xDD,
        0xEF, 0x95, 0x19, 0xB3, 0xCD, 0x3A, 0x43, 0x1B, 0x30, 0x2B, 0x0A, 0x6D,
        0xF2, 0x5F, 0x14, 0x37, 0x4F, 0xE1, 0x35, 0x6D, 0x6D, 0x51, 0xC2, 0x45,
        0xE4, 0x85, 0xB5, 0x76, 0x62, 0x5E, 0x7E, 0xC6, 0xF4, 0x4C, 0x42, 0xE9,
        0xA6, 0x3A, 0x36, 0x21, 0x00, 0x00, 0x00, 0x00, 0x00, 0x09, 0x05, 0x63
    };

    mp_int bigint;
    mp_read_unsigned_bin(&bigint, key, sizeof(key));

    return mp_unsigned_bin_size(&bigint) == sizeof(key);
}
```

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/765

**Comment by arvidn** [comment]
tommath has been updated in RC_1_0 and RC_1_1. there's a PR to replace it with boost.multiprecision https://github.com/arvidn/libtorrent/pull/768

**Comment by Athorcis** [comment]
Since segfaults are fixed, i consider that this issue can be closed
