### ISSUE TITLE
Can't import hugh torrents

### ISSUE THREAD

**Issue by MPW1412** [arvidn/libtorrent#76]
Hello,

libtorrent can't handle hugh torrents like for example 400 GB content and 24 MB torrent file. Please look into the importing process, maybe there's some buffering problem.

Thanks for reading.

MPW

**Comment by arvidn** [comment]
what error do you get when you try? and do you have an example torrent I could try? (if so, feel free to send one in private to arvid@libtorrent.org)

**Comment by sledgehammer999** [comment]
Which constructor of torrent_info() did you use? The one that takes filepath to the .torrent file?
That one uses some internal limit. IIRC it is useful for until 10MB .torrent files.
The other constructors don't have that limit.
If this is the case, I advice you to use `lazy_bdecode()` to have a `lazy_entry` for your .torrent file and then pass it to the `torrent_info` constructor. (Don't forget to adjust `lazy_bdecode()`'s limits if it fails at first).
