### ISSUE TITLE
2.0.10 . Please tag to resolve the blocklist of lt2.

### ISSUE THREAD

**Issue by KyleSanderson** [arvidn/libtorrent#7608]
**Please provide the following information**

libtorrent version (or branch): 2.0.10

platform/architecture: amd64

compiler and compiler version: GCC 14

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

https://github.com/arvidn/libtorrent/pull/7596#issuecomment-1925474673

Still blocking 3 issues on this one unfortunately. Just need a tag to resolve the situation from the person saying libtorrent-rasterbar was a mistake.

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/7619

**Comment by XinfitX** [comment]
> #7619

@arvidn thanks very much for all works, please is possible update pypi

https://pypi.org/project/libtorrent/#history

**Comment by arvidn** [comment]
there's an issue blocking the CI workflow from uploading wheels. On windows, the openssl library appears to be missing a symbol:

https://github.com/arvidn/libtorrent/actions/runs/7944867453/job/21690958791#step:5:899

```
libtorrent-rasterbar.lib(torrent.obj) : error LNK2019: unresolved external symbol SSL_CTX_set0_tmp_dh_pkey referenced in function "private: void __cdecl boost::asio::ssl::context::do_use_tmp_dh(struct bio_st *,class boost::system::error_code &)" (?do_use_tmp_dh@context@ssl@asio@boost@@AEAAXPEAUbio_st@@AEAVerror_code@system@4@@Z)
```
