### ISSUE TITLE
Overflow of m_num_pad_bytes

### ISSUE THREAD

**Issue by 3107RU** [arvidn/libtorrent#7646]
libtorrent version (or branch): latest

platform/architecture: win64

compiler and compiler version: vs22

Variable **int m_num_pad_bytes** too small for some torrents and gets overflowed.

![image](https://github.com/arvidn/libtorrent/assets/80814158/c1186ff4-3db1-40a4-9121-24d97b0cf4a1)

![image](https://github.com/arvidn/libtorrent/assets/80814158/f037ef42-95a7-46df-9ec5-43a93176919f)

**Comment by arvidn** [comment]
thanks for the report!

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/7647
