### ISSUE TITLE
qBittorrent announces IPv4 and IPv6 to private HTTPS tracker twice

### ISSUE THREAD

**Issue by bearx3f** [arvidn/libtorrent#7653]
**Please provide the following information**

libtorrent version (or branch): 2.0.10

platform/architecture: qbittorrent-static-nox x86_64

compiler and compiler version: GCC 13.2.0 -- x86_64-linux-musl

Description:
qBittorrent is configured to use the primary network interface and both IPv4 and IPv6.
When announcing to a private HTTPS tracker, qBittorrent sends two announce requests, one for IPv4 and one for IPv6.
This causes the tracker to receive duplicate announcements, which results in incorrect upload and download statistics.

![image](https://github.com/arvidn/libtorrent/assets/9717561/88073a70-3669-4f5d-b5ec-e3749301d0a9)

Additional Information:

This issue is not present when using only IPv4 or IPv6.

Expected Behavior:

qBittorrent should only send one announce request to the tracker, regardless of whether IPv4 or IPv6 is being used.

Actual Behavior:

qBittorrent sends two announce requests to the tracker, one for IPv4 and one for IPv6.

Screenshot of Proxy server log:

![image](https://github.com/arvidn/libtorrent/assets/9717561/0900e5b1-a4d8-44d3-b8db-76eefe83da58)

as you can see same info_hash, peer_id but difference IP Address

**Comment by bearx3f** [comment]
Unfortunately My tracker don't. I think they ban qBittorrent because of this incident.

**Comment by stalkerok** [comment]
I'm afraid the tracker will have to ban all libtorrent-based clients, as well as others with multiple network stack support.

**Comment by bearx3f** [comment]
Yes, they've banned [Deluge](https://en.wikipedia.org/wiki/Deluge_(software)) too

I think this is not libtorrent fault 

so I close it then

**Comment by stalkerok** [comment]
I wonder what kind of tracker it is, instead of discarding duplicates, it bans clients. It would be much more reasonable to remove support for double stack if you can't customize it. None of the popular private trackers have slid down to banning libtorrent based clients.

**Comment by ValeZAA** [comment]
Wait... What does uTorrent do here??

**Comment by bearx3f** [comment]
> I wonder what kind of tracker it is, instead of discarding duplicates, it bans clients. It would be much more reasonable to remove support for double stack if you can't customize it. None of the popular private trackers have slid down to banning libtorrent based clients.

It's ancient site (10+ year ago) low code maintenance but still active by community
