### ISSUE TITLE
Fails to build with python-dbg on linux

### ISSUE THREAD

**Issue by sledgehammer999** [arvidn/libtorrent#766]
I am trying to make a deb package for 1.0.9 to use on qbittorrent's ppa but I have found out it errors out. I narrowed it down to this command:

```
./configure PYTHON=/usr/bin/python2.7-dbg --enable-python-binding --with-boost-python=boost_python-py27
```

It fails with:

> checking for the distutils Python package... no
> configure: error: cannot import Python module "distutils"

However, I have been able to build 1.0.7. (1.0.8 fails too).

Any ideas on what to do?
PS: You need to install package `python-dbg` to have access to python27-dbg.
PS2: Using the non-dbg python binary it works. It doesn't complain about distutils.

**Comment by arvidn** [comment]
what's the error?

**Comment by arvidn** [comment]
oh, the distutils..

**Comment by sledgehammer999** [comment]
I found out which file causes this. It is `m4/ax_python_devel.m4`. I replaced it with the one found in 1.0.7 and run `autotool.sh`. Then the command in my 1st post worked.

**Comment by arvidn** [comment]
that m4 file was updated here: https://github.com/arvidn/libtorrent/commit/2092e30852253082512974d941f74e8113efd390

which was a back-port of this PR: https://github.com/arvidn/libtorrent/pull/324
perhaps @voyageur can shed some light on this.

Is the new m4 script not compatible with older versions of python?
Is it not compatible with the debug build of python?

**Comment by voyageur** [comment]
Hmm, it works for me with python 2.7 (and here for the release build apparently). So something does not go well with the python-dbg setup… Does this command work?
`python2.7-dbg -c "import distutils"`

There may be some additional env variables to set for these debug builds, that "happened to work" with the older ax_python_devel.m4?

**Comment by sledgehammer999** [comment]
`python2.7-dbg -c "import distutils"` gives output `[21667 refs]` while the 3.4 and 3.5 variants don't give something. Is this normal? (I am a python noob).

PS: I use debian unstable for the above.

**Comment by voyageur** [comment]
So this is probably caused by [this change](https://github.com/arvidn/libtorrent/commit/2092e30852253082512974d941f74e8113efd390#diff-808824a21167bd07857fe4cc03527a84L136). As there is some output from the command, the configure script considers there was an error.

If 3.x versions do not have this , this verbose output has robably been fixed then in Debian, but not for 2.7...

I think reverting this line should be enough to fix your case and still support new library suffix.

**Comment by arvidn** [comment]
@sledgehammer999 would you mind giving that a try? (and maybe submit a PR)

**Comment by sledgehammer999** [comment]
I reverted that line, run autotoo.sh and it works for 2.7. But now configure fails for 3.5.
Command line:
```
./configure PYTHON=/usr/bin/python3.5-dbg --enable-python-binding --with-boost-python=boost_python-py35
```

Fails with:
>configure: error: Boost.Python library not found. Try using --with-boost-python=lib.

And I have checked that `/usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.58.0` exists. Also the dev package for boost.python is installed too.

**Comment by sledgehammer999** [comment]
I doesn't fail for `PYTHON=/usr/bin/python3.5`

**Comment by sledgehammer999** [comment]
If I am reading correctly the log this is how it fails:
```
configure:19533: checking whether boost_python-py35 is the correct library
configure:19552: g++ -o conftest -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -ftemplate-depth=120 -fvisibility=hidden -fvisibility-inlines-hidden -I/usr/include -I/usr/include/python3.5dm -I/usr/include -Wdate-time -D_FORTIFY_SOURCE=2 -I/usr/include/python3.5dm -I/usr/include/python3.5dm -L/usr/lib/x86_64-linux-gnu -lpython3.5dm -lpthread -ldl  -lutil -lm  -L/usr/lib/x86_64-linux-gnu -Wl,-z,relro -Wl,--as-needed -fvisibility=hidden -fvisibility-inlines-hidden conftest.cpp -lboost_python-py35 -lpthread   -L/usr/lib -lpython3.5dm >&5
/usr/lib/x86_64-linux-gnu/libboost_python-py35.so: undefined reference to `PyModule_Create2'
collect2: error: ld returned 1 exit status
configure:19552: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "libtorrent-rasterbar"
| #define PACKAGE_TARNAME "libtorrent-rasterbar"
| #define PACKAGE_VERSION "1.0.9"
| #define PACKAGE_STRING "libtorrent-rasterbar 1.0.9"
| #define PACKAGE_BUGREPORT "arvid@libtorrent.org"
| #define PACKAGE_URL "http://www.libtorrent.org"
| #define PACKAGE "libtorrent-rasterbar"
| #define VERSION "1.0.9"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define HAVE_PTHREAD 1
| #define HAVE_BOOST /**/
| #define HAVE_BOOST_SYSTEM 1
| #define HAVE_GETHOSTBYNAME 1
| #define HAVE_GETHOSTBYNAME_R 1
| #define GETHOSTBYNAME_R_RETURNS_INT 1
| #define HAVE_CLOCK_GETTIME 1
| #define NDEBUG 1
| #define TORRENT_USE_OPENSSL 1
| #define HAVE_PYTHON "3.5"
| #define HAVE_BOOST_PYTHON /**/
| /* end confdefs.h.  */
| 
| #include <boost/python/module.hpp>
| BOOST_PYTHON_MODULE(test) { throw "Boost::Python test."; }
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
```

**Comment by cas--** [comment]
I was attempting to update the launchpad PPA with lt `1.0.9` and ran into this issue.

Adding back the `>/dev/null` for `ac_distutils_result` fixes the [`python2.7-dbg` build error](https://launchpadlibrarian.net/272540947/buildlog_ubuntu-precise-amd64.libtorrent-rasterbar_1.0.9-1~precise~ppa1_BUILDING.txt.gz) however now the [`python3.2-dbg` build fails](https://launchpadlibrarian.net/272548216/buildlog_ubuntu-precise-i386.libtorrent-rasterbar_1.0.9-1~precise~ppa2_BUILDING.txt.gz) as a result of changes to `ax_boost_python.m4` made in 5bf3e62fe. Snippet below for reference:

```
checking whether boost_python3 is the correct library... no
configure: error: Boost.Python library not found. Try using --with-boost-python=lib.
```

I reverted both `ax_python_devel.m4` and `ax_boost_python.m4` to `1.0.7` versions but it still [fails to build](https://launchpadlibrarian.net/272566942/buildlog_ubuntu-precise-amd64.libtorrent-rasterbar_1.0.9-1~precise~ppa3_BUILDING.txt.gz):

```
/usr/bin/ld: cannot find -l-lboost_python-py27
```
Not had the time to investigate where this extra `-l` comes from...

**Comment by cas--** [comment]
Finally found that 14387f52a4 commit in `configure.ac` is reason for the extra `-l` which is related to the `ax_boost_python.m4` script change. I shall verify and update tomorrow as it's late here.

Regarding the python3 issue I did find a similar one here: https://github.com/phatina/python-lmiwbem/issues/21#issuecomment-75747616

**Comment by cas--** [comment]
The problem with `ax_python_devel` affects both `python3.2-dbg` and `python2.7-dbg` as they by default output a `ref count` ([changed to no output in py3.4](https://bugs.python.org/issue17323)) and requires the additional pipe output to /dev/null for example. However this is not ideal as all errors from non-debug builds are then swallowed up.

I am not sure what the solution for the `ax_boost_python` could be, it is clear as sledgehammer has posted that when testing for the boost python lib with `python3-dbg` results in `undefined reference to `PyModule_Create2'`...

The current solution for the launchpad PPA is to revert these changes to as they were in 1.0.7.

**Comment by arvidn** [comment]
what would break by reverting that in the libtorrent repo?

**Comment by cas--** [comment]
Nothing that I know of except the gentoo builds that instigated this #324.

However after more investigation I have narrowed it down to the smallest changeset possible and still keep these updated m4 macros. With all builds passing on debian/ubuntu.

The `ax_python_devel.m4` changes greps and removes the offending 'ref count' if found.

The `ax_boost_python.m4` changes use the generic '_main' method search as per old m4 file. Potentially could have replaced that section of code with AC_CHECK_LIB (as it was in 1.0.7) but decided keeping the changes small and obvious so less likely to break unexpectedly and easier to debug or update in future.

```diff
--- libtorrent-rasterbar-1.0.9.orig/m4/ax_python_devel.m4
+++ libtorrent-rasterbar-1.0.9/m4/ax_python_devel.m4
@@ -136,7 +136,7 @@
 	# Check if you have distutils, else fail
 	#
 	AC_MSG_CHECKING([for the distutils Python package])
-	ac_distutils_result=`$PYTHON -c "import distutils" 2>&1`
+	ac_distutils_result=`$PYTHON -c "import distutils" 2>&1 | grep -v '^\[[0-9]\{1,\} refs\]'`
 	if test -z "$ac_distutils_result"; then
 		AC_MSG_RESULT([yes])
 	else
--- libtorrent-rasterbar-1.0.9.orig/m4/ax_boost_python.m4
+++ libtorrent-rasterbar-1.0.9/m4/ax_boost_python.m4
@@ -101,12 +101,10 @@
    fi])
   BOOSTLIBDIR=`echo $BOOST_LDFLAGS | sed -e 's/@<:@^\/@:>@*//'`
   for ax_lib in $ax_python_lib $ax_boost_python_lib `ls $BOOSTLIBDIR/libboost_python*.so* $BOOSTLIBDIR/libboost_python*.dylib* $BOOSTLIBDIR/libboost_python*.a* 2>/dev/null | sed 's,.*/,,' | sed -e 's;^lib\(boost_python.*\)\.so.*$;\1;' -e 's;^lib\(boost_python.*\)\.dylib.*$;\1;' -e 's;^lib\(boost_python.*\)\.a.*$;\1;' ` boost_python boost_python3; do
-    AS_VAR_PUSHDEF([ax_Lib], [ax_cv_lib_$ax_lib''_BOOST_PYTHON_MODULE])dnl
+    AS_VAR_PUSHDEF([ax_Lib], [ax_cv_lib_$ax_lib''_main])dnl
     AC_CACHE_CHECK([whether $ax_lib is the correct library], [ax_Lib],
     [LIBS="-l$ax_lib $ax_boost_python_save_LIBS $PYTHON_LIBS"
-    AC_LINK_IFELSE([AC_LANG_PROGRAM([[
-#include <boost/python/module.hpp>
-BOOST_PYTHON_MODULE(test) { throw "Boost::Python test."; }]], [])],
+    AC_LINK_IFELSE([AC_LANG_PROGRAM([[]], [])],
         [AS_VAR_SET([ax_Lib], [yes])],
         [AS_VAR_SET([ax_Lib], [no])])])
     AS_VAR_IF([ax_Lib], [yes], [BOOST_PYTHON_LIB=$ax_lib break], [])
```

**Comment by sledgehammer999** [comment]
@voyageur does the above patch work for Gentoo too?

**Comment by voyageur** [comment]
Will test and report next week, unless another Gentoo/Arch user beats me to it :)

**Comment by cas--** [comment]
@arvid happy with that diff or prefer a PR?

**Comment by arvidn** [comment]
A or would be great. I will get around to merging it eventually either way though. Thanks for looking in to this!

@cas-- could you let me know when you think RC_1_1 is in a good place to be released?

**Comment by cas--** [comment]
Ok I shall see if I can squeeze some time in to do that. 

I have just pushed the RC1.1 branch to our [develop PPA](https://launchpad.net/~deluge-team/+archive/ubuntu/develop) for testing and will give feedback.

**Comment by cas--** [comment]
@sledgehammer999 Can this issue be closed now?

**Comment by sledgehammer999** [comment]
For some reason 0.16 still has problems. I can't remember what exactly. I'll try to provide info in ~3 days from now. If I do not, @arvidn feel free to close this.

**Comment by sledgehammer999** [comment]
>For some reason 0.16 still has problems. I can't remember what exactly. I'll try to provide info in ~3 days from now. If I do not, @arvidn feel free to close this.

What an idiot I am! I meant to say 1.0.x not 0.16.x

**Comment by sledgehammer999** [comment]
It turns out I kept a log of my local cowbuilder build for Ubuntu trusty but I forgot to post it here.
I cannot understand how and why it fails. The makefile fails when it enters the docs/ dir.
The log is pasted [here](https://www.zerobin.net/?d93fa4e1366934e2#lQGtJbjhaFXubUbJShDCDhpvqayRIDs8/MVwJBHVL2w=).

**Comment by arvidn** [comment]
does the ``doc`` directory have a makefile in it? or is it missing from the tarball?

**Comment by sledgehammer999** [comment]
You are right. This is the sequence of commands that produce the error(and maybe even simpler):
```
./configure --with-libgeoip --with-libiconv --with-boost-system=boost_system CXXFLAGS=-std=c++11 --prefix=/home/hammered/Desktop/libt/build_install
make
make -C docs/ -f makefile
```
I checked the docs/ dir and I don't see a generated makefile. Hell, I don't even see a Makefile.am or Makefile.in in that dir.

The `docs/makefile` file exists in the repo but not in the generated tarball.

**Comment by arvidn** [comment]
I see. I imagine the intention was to include the existing makefile in the tarball. It probably just need to be mentioned as EXTRA_DIST in the root makefile then

**Comment by arvidn** [comment]
taking a closer look at this, why is the makefile ever referencing anything in ``docs/``? It shouldn't even try to do that in the first place.

**Comment by sledgehammer999** [comment]
FYI, in the past I was able to build .debs from 1.0.7 with the same commands. While 1.0.8 onwards it fails. But 1.0.7 doesn't include the docs/makefile. So I guess it was generated during configuring/building in the past but now it doesn't?

**Comment by arvidn** [comment]
perhaps. I suppose it may make sense to include it

**Comment by sledgehammer999** [comment]
Keep in mind that the commands I described are part of the debian packaging scripts, which I just copied for my PPAs. I really don't know why their maintainer wanted those commands. I suppose it has something to do with their -docs package. Unfortunately I don't know much about debian packaging to rework the script.

**Comment by arvidn** [comment]
looking through the history of Makefile.am, I can't see it ever having been included in the tarball

**Comment by arvidn** [comment]
maybe they patch the ``Makefile.am`` too, to include the makefile?

**Comment by cas--** [comment]
Iirc docs is patched in debian/patches. For Deluge ppa I removed that as docs were not needed.

**Comment by sledgehammer999** [comment]
>Iirc docs is patched in debian/patches. For Deluge ppa I removed that as docs were not needed. 

Wow. You're right. One of their patches touches many files. And one of those files is creating a new docs/makefile file. And I bet is an exact copy of the one in the repo. Question is, why doesn't it build? Maybe the patch fails? Give me one day so I can re-generated the source package and get a new build log.

**Comment by arvidn** [comment]
does this make sense? https://github.com/arvidn/libtorrent/pull/1253

**Comment by sledgehammer999** [comment]
It turns out that I had made the debian source package poorly. I redid it and it now builds fine.
