### ISSUE TITLE
[Not Needed] Always contact all trackers

### ISSUE THREAD

**Issue by vickyoo7** [arvidn/libtorrent#7667]
I'm not sure if it's possible or already available but I'd like to request the feature to always contact all trackers, currently only couple of trackers are being contacted and rest are in not contacted state even after force announcing trackers are not contacted

**Comment by vickyoo7** [comment]
Not needed

**Comment by arvidn** [comment]
for reference, the way you do this is to enable `announce_to_all_trackers` and `announce_to_all_tiers`, see https://libtorrent.org/reference-Settings.html#announce_to_all_trackers
