### ISSUE TITLE
qbittorrent不支持ipv6的tracker服务器，提示skipping tracker announce (unreachable)，不知道是不是libtorrent核心的问题

### ISSUE THREAD

**Issue by 1265578519** [arvidn/libtorrent#7679]
qb 4.6.4 lt2 qt6
![J9JFQR 45M`$QOIC9L6XMTS](https://github.com/qbittorrent/qBittorrent/assets/6442439/0a463829-709e-4216-b485-f644f39be30e)

qbittorrent不支持ipv6的tracker服务器，大量的ipv6 tracker在qb上无法正常工作，提示skipping tracker announce (unreachable)
已经确保高级设置相关的两个勾选已经打开
![image](https://github.com/qbittorrent/qBittorrent/assets/6442439/f2a8c035-a265-43c7-a052-71677e0b060c)

```
udp://tracker2.itzmx.com:6961/announce
udp://[2a01:4f8:c012:8025::1]:8080/announce
```
![image](https://github.com/qbittorrent/qBittorrent/assets/6442439/d62a7240-17fd-4ac5-a744-6bc782087f0e)

在比特彗星等其它bt的软件上，ipv6 tracker工作正常
![image](https://github.com/qbittorrent/qBittorrent/assets/6442439/7453a047-4571-4aaa-80d5-e9d60181b4d5)

wireshark信息，tracker服务器都可以正常返回udp数据包
![image](https://github.com/qbittorrent/qBittorrent/assets/6442439/df78732f-5740-4940-bbe5-2866e38ed87d)

相关：https://github.com/qbittorrent/qBittorrent/issues/20882

请参考bep15 BT协议规范，对ipv6 udp tracker进行修复：http://www.bittorrent.org/beps/bep_0015.html

**Comment by 1265578519** [comment]
我想我知道原因了，这就和DNS、CDN一样
用户电脑上请求8.8.8.8，但是实际上在谷歌DNS服务器远端节点后面使用其他不同的ip地址用于数据包传输
ipv6 tracker由于和请求相同的ip地址没有回复，回复时服务器使用了其它ip地址，就被qbittorrent与newTrackon判定“超时未响应” qbittorrent应当使用bep15检测收到的数据包transaction_id是否一致，
所以在比特彗星等其它BT客户端上，使用ipv6 udp tracker工作正常，在qbittorrent上不正常
这种现象存在tracker服务器拥有多个ipv6地址上发生，通过了与访问域名目标ip不同的其它ipv6地址回复引起的“超时未响应”

**Comment by 1265578519** [comment]
由于某人点了个emoji，爱修不修，不修拉倒，既然如此，懒得反馈bug了，我直接关了。

**Comment by shanmm** [comment]
同样的问题，ipv6很头疼，而且隔一段时间会掉ipv6,所以下载的时候只能看到ipv4在跑，完全没有ipv6,于是我添加了一个定时任务，十二小时重启一次qb,从而获取到ipv6
