### ISSUE TITLE
Can we get updated wheels on pypi?

### ISSUE THREAD

**Issue by Lord-Kamina** [arvidn/libtorrent#7683]
I don't want to be an ass but, what is wrong with the workflow that uploads releases to Pypi?
Pretty much all wheels hosted there are stale, and there are also no python 3.11 builds at all. D:

**Comment by cas--** [comment]
@arvidn Is this a manual step that you can run? I know it was created by @AllSeeingEyeTolledEweSew but I'm not sure about the publishing step

**Comment by xavier2k6** [comment]
@cas-- publishing to https://pypi.org/project/libtorrent/ is a manual step, the `cibuildwheel` action was broken for some time, upcoming PR that I linked to should be ready to go upon maintainers return.
