### ISSUE TITLE
`libdatachannel submodule` (`0.18.1`) is outdated - Update to latest

### ISSUE THREAD

**Issue by xavier2k6** [arvidn/libtorrent#7692]
**Please provide the following information**

libtorrent version (or branch):
`master`
platform/architecture:
N/A
compiler and compiler version:
N/A
please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

`libdatachannel submodule` (`0.18.1`) is outdated.

Latest is `0.21.1`
https://github.com/paullouisageneau/libdatachannel/releases

@paullouisageneau Can you create the relevant PR?

**Comment by paullouisageneau** [comment]
Yes, I'll update the library.

**Comment by xavier2k6** [comment]
Closed via 
- #7701
