### ISSUE TITLE
Block timeouts and peer snubs on libtorrent 1.1.0

### ISSUE THREAD

**Issue by tchoulihan** [arvidn/libtorrent#77]
Hey @arvidn 

For some reason, after I started using a newer version of jlibtorrent based on libtorrent 1.1.0, my torrents stopped downloading correctly. They were downloading correctly on 1.0.5.0 .

Going into the logs on both the seeding and leeching side, it appears the seeder receives a lot of `peer_disconnected` messages:
` PEER_DISCONNECTED - peer_disconnected_alert - my file peer (94.102.63.93:6881, libtorrent 1.1.0) disconnecting (uTP) [sock_read] [system]: Connection timed out (reason: 0)`

And the leeching side *successfully downloads a few blocks*, but then receives `block_timeout` and `peer_snubbed` messages: 
`02:46:05.145 [Session-alertsLoop] DEBUG c.t.client.LibtorrentEngine - PEER_SNUBBED - peer_snubbed_alert - my file peer (74.137.241.6:6881, libtorrent 1.1.0) peer snubbed
02:46:05.145 [Session-alertsLoop] DEBUG c.t.client.LibtorrentEngine - BLOCK_TIMEOUT - block_timeout_alert - my file peer timed out request ( piece: 492 block: 0)
`

My settings are the exact same as the were before using the new version.

After some looking, it might have something to do with ports? The ports appear to be different and lower than they used to be.

**Comment by arvidn** [comment]
it's definitely the seed that things the peer connection got stale and timed out. Do you have peer logs enabled? In 1.1.0 you don't need to rebuild libtorrent to enable verbose peer logging, they are alerts now that can be enabled with an alert mask flag.

Those logs should give you more hints on why the seed times out the downloader. The timeout and snubbed aren't messages, those are events that fire on the downloader indicating that it's waiting for the seed to send data, but nothing is sent. On the seed, given that it timed out the peer, presumably it receives REQUEST messages and at some point stops responding with PIECE messages back. the peer logs should show. (if you enable the peer log alerts, make sure to log them to a file and then user grep to filter out specific connections).

The fact that the timeout happens in the socket read function suggests that perhaps the timeout happened at the transport layer. You could try disabling uTP just to see if there's a problem introduced there.

**Comment by tchoulihan** [comment]
Thanks @arvidn

I've found some PeerLogAlert methods, including: `eventType`, `direction`, `getPeerId`, and `getPeerIP`.

@aldenml helped me turn on logging for it: 


Here's some logging (from the seeding machine) right after adding a torrent from a leeching machine.
https://drive.google.com/file/d/0B0PA7XM1BmLMLXNWUXlQNEZVdk0/view?usp=sharing

There's a ton of alert types, like: `INCOMING_CONNECTION`, `CONSTRUCT`, `ASYNC_READ`, etc.

The only messages I can really find is this one: `13:10:01.890 [Session-alertsLoop] DEBUG c.t.client.LibtorrentEngine - PEER_LOG - peer_log_alert - my_file [94.102.63.93:6881] *** ERROR [ Connection timed out in peer_connection::on_send_data ]`

or: 
`13:10:01.890 [Session-alertsLoop] DEBUG c.t.client.LibtorrentEngine - PEER_LOG - peer_log_alert - my_file3 [94.102.63.93:6881] *** CONNECTION_CLOSED [ op: 10 error: Connection timed out ]`


@aldenml One thing I'm noticing, is that even though I just set the port range using:
```java
		Pair<Integer, Integer> prange = new Pair<Integer, Integer>(49152, 65535);
		String iface = "0.0.0.0";
		session = new Session(new Fingerprint(), prange, iface, defaultRouters(), true);
```

It completely ignores that range and just uses port `6881` . I'm convinced that my IP may be blocking/throttling that port by default.

**Comment by aldenml** [comment]
Yes, the parameters are ignored in 1.1.0.3, that's fixed in master. Waiting for PR https://github.com/arvidn/libtorrent/pull/69 get merged to release 1.1.0.4.

**Comment by tchoulihan** [comment]
@aldenml Ah gotcha.

**Comment by arvidn** [comment]
what's being logged there? I was expecting to see the output from alert::message() (which prints out all information in the log on one line). I almost get the impression in that file that one log entry gets multiple lines, is that right?

**Comment by tchoulihan** [comment]
Yes thats correct, I forgot to mention those extra lines are printing out the `eventType`, `direction`, `getPeerId`, and `getPeerIP`. You can ignore them though because you're right the message is there too on the longer line.

**Comment by tchoulihan** [comment]
Either way, I'm fairly *fingers crossed* certain its a port issue. ISPs in the US don't typically like ports 6881-6889 , that its defaulting to right now.

**Comment by arvidn** [comment]
I see. this still seems like a uTP connection, did you try TCP to see if this is a uTP issue?

**Comment by tchoulihan** [comment]
I did not, but in the previous versions that didn't have this timeout issue, uTP was working fine.

**Comment by arvidn** [comment]
but there are lots of other things that have changed since 1.0.x too. I can't know where to look without some help from you.
If it is a uTP issue I would love to see a verbose uTP log (ideally with just one connection that times out). To enable, set TORRENT_UTP_LOG and TORRENT_UTP_LOGV defines to 1 at the top of src/utp_stream.cpp. That will write a utp.log in cwd.

**Comment by aldenml** [comment]
@arvidn Do you think it makes sense to add a bjam flag to enable this defines? something like <utp-stats>?

**Comment by arvidn** [comment]
well, it's not used very often..

**Comment by arvidn** [comment]
I could try to reproduce it, but I don't know what knobs to turn. There is a simulation of a uTP transfer that works very well

**Comment by tchoulihan** [comment]
@arvidn , @aldenml  Okay, I changed my mixed_mode_algorithm to prefer_tcp:

`sessionSettings.setInteger(int_types.mixed_mode_algorithm.swigValue(), bandwidth_mixed_algo_t.prefer_tcp.swigValue());`

But as far as I can tell, it seemed to do nothing, because the logs show that its still making uTP connections, and it also had no effect on the block_timeouts or download speed.

I should note that it still appears to force the download through even though its having block_timeouts. I thought it had something to do with this setting:
`sessionSettings.setUploadRateLimit(0);`

So I changed it to `sessionSettings.setUploadRateLimit(999999);`*~1MB/sec*

But it also made no diferent on the speed.

Since I don't know how to do uTP logging with jlibtorrent yet, I can at least provide (cleaned up) PEER_LOG 's from my seeding machine, although these look like the only important lines to me:

The full (grepped for lines of the file the machine is trying to seed) : https://drive.google.com/file/d/0B0PA7XM1BmLMaVZUOExHQzJqdHc/view?usp=sharing
```
17:37:28.984 [Session-alertsLoop] DEBUG c.t.client.LibtorrentEngine - PEER_LOG - peer_log_alert - my_file 3 [94.102.63.93:49152] >>> SEND_BUFFER_WATERMARK [ current watermark: 10240 max: 512000 min: 10240 factor: 50 uploaded: 0 B/s ]
17:37:28.986 [Session-alertsLoop] DEBUG c.t.client.LibtorrentEngine - PEER_LOG - peer_log_alert - my_file [94.102.63.93:49152] *** ERROR [ in peer_connection::on_receive_data_nb error: Connection timed out ]
17:37:28.986 [Session-alertsLoop] DEBUG c.t.client.LibtorrentEngine - PEER_LOG - peer_log_alert - my_file [94.102.63.93:49152] *** CONNECTION_CLOSED [ op: 10 error: Connection timed out ]

```

@aldenml If its necessary, could you show me how to set up and enable TORRENT_UTP_LOG 's in jlibtorrent?

**Comment by arvidn** [comment]
@tchoulihan in the meantime, do you also have peer logs for the downloader? it may reveal something more.

btw. to disable uTP you have to set enable_outgoing_utp = false and enable_incoming_utp = false.

**Comment by tchoulihan** [comment]
@arvidn Thanks! That did it, disabling uTP fixed the speed issue! Do you want me to do any logging with uTP settings on or off from the seeding or leeching machines?

**Comment by arvidn** [comment]
Typically the sending end is more interesting with uTP (since that's the end doing the congestion control). However, since this is a timeout, both ends would be really useful.

**Comment by tchoulihan** [comment]
@arvidn 

Okay, here's the logs, with uTP turned on(so its stalling):

seeding_log: https://drive.google.com/file/d/0B0PA7XM1BmLMLXFYbk9NWF9JeU0/view?usp=sharing

leeching_log: https://drive.google.com/file/d/0B0PA7XM1BmLMekpDZ3dpWWpaRmc/view?usp=sharing

I suppose you want to fix the uTP issues before closing this out? Just let me know whenever you'd like to test a change.

**Comment by aldenml** [comment]
@tchoulihan This PR https://github.com/arvidn/libtorrent/pull/83 will allow me to compile and distribute the library with TORRENT_UTP_LOG enabled. Let's see if it's accepted.

**Comment by arvidn** [comment]
One theory I explored was that this was caused by the vulnerability fix I applied in 1.0.6 (and master) a few weeks ago. Perhaps uTP no longer supported the sequence number wrapping around. However, I just completed a simulation of sending 100 MB over a uTP connection without any hickups (which should have made the 16 bit sequence number wrap).

**Comment by arvidn** [comment]
but one possible test would be to revert this patch and see if the uTP problem is still there. https://github.com/arvidn/libtorrent/commit/4d89c7da973298d30ce22972abc4a895e096f80b

(I wish I could reproduce it myself, at least if I figure it out I can make sure to cover it with a test)

**Comment by arvidn** [comment]
actually, one aspect of that patch is to make fresh uTP connections, that haven't received any ACKs for anything, will be terminated immediately on any timeout. Actually, as I look at this code, I don't think it's quite correct. and it might explain the timeout behavior tchoulihan is seeing.

**Comment by arvidn** [comment]
I've pushed a fix to RC_1_0 and master. please try with the latest version to see if this problem persists.

**Comment by tchoulihan** [comment]
@aldenml Let me know when you do another jlibtorrent release from libtorrent/master.

**Comment by aldenml** [comment]
@tchoulihan Check version 1.1.0.5 http://repo1.maven.org/maven2/com/frostwire/jlibtorrent/1.1.0.5/

It has the latest fix for uTP connections and if you want to enable full log of utp stream data, see https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/demo/DownloadTorrent.java#L25

**Comment by tchoulihan** [comment]
@aldenml @arvidn 

So I just tested out 1.1.0.5 , and it did not fix the uTP issue. I still get block and peer timeouts on the leeching machine with uTP turned on.

The UTP logs can become pretty big. I let my program sit for a few minutes, and they were 30 megs.

Here's the utp logs:
Seeding machine:
https://drive.google.com/open?id=0B0PA7XM1BmLMNmdoY3paUHY3Nk0
Leeching machine:
https://drive.google.com/open?id=0B0PA7XM1BmLMaXlfNk04OW5ySUU

**Comment by arvidn** [comment]
as far as I can tell. every single connection made from the downloader is closed immediately with close-reason 257, which means: close_invalid_info_hash.

This suggests that the info-hash is not know to the seeder. The seeder won't distinguish between a stopped/paused torrent an one that it has never seen. What were you seeing in the verbose peer logs during this run? I would expect them to reflect this too.

**Comment by tchoulihan** [comment]
@arvidn Yes I am seeing those errors too. Why would this error occur for uTP, but not when that's turned off though? And also I still do notice that uTP does start *initially* downloading, but then times out. I don't see how it would even be able to start the initial download if the info_hash was incorrect.

**Comment by arvidn** [comment]
In the uTP logs, I don't see _any_ actual payload being transferred. It just closes immediately. I did see payload being transferred in the previous verbose peer logs though. I did actually see another close-reason too (6), meaning upload-to-upload connection. Are you sure you didn't set the downloaders to seed-mode?

**Comment by tchoulihan** [comment]
I can create a new set of utp_logs if you like. I'm sure the downloaders weren't in seed mode, the only thing I changed were those 2 disallow uTP settings.

**Comment by arvidn** [comment]
please do. and can you provide the corresponding peer logs as well?

**Comment by tchoulihan** [comment]
Sorry for being so slow on this. It still showed the same behavior as above, it starts initially, but doesn't continue downloading(uTP turned on) .

Here's the peer / utp logs: 

https://drive.google.com/folderview?id=0B0PA7XM1BmLMfnJrZW1xbURpMFJnSE1lLXpxVHgzNlVCRHRjMFJWUVo4a1pRTFJJeFRWMmM&usp=sharing

**Comment by arvidn** [comment]
There must be something wrong with the peer logs. The peer_seed.log only contains a handful of PEER_LOG messages, whereas the peer_leeching.log has many more. Also, which IP is the seed? The downloading side of the peer log connects to multiple different IPs. The seeding log looks corrupt or truncated.

**Comment by tchoulihan** [comment]
Sorry, 74.xxx is the seed, 94.xxx is the downloader

**Comment by arvidn** [comment]
try to set the setting: settings_pack::utp_dynamic_sock_buf to false btw. it looks like this may be the culprit. What OS are you running the seed on?

**Comment by tchoulihan** [comment]
Linux  3.13.0-46-generic #79-Ubuntu SMP Tue Mar 10 20:06:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tchoulihan** [comment]
Do you want me to try that setting and report back?

**Comment by arvidn** [comment]
yes please. the utp log indicate that it caused the upper bound of your MTU to be set to 64k, sending packets way too large and the PMTU discovery mechanism doesn't seem to work very reliably. I should probably remove or disable this logic for now. I believe disabling that setting will make the MTU set to 1475 (or whatever).

**Comment by tchoulihan** [comment]
@arvidn That setting fixed the issue!

Here's the logs again(apologies for letting it run too long and their size) : https://drive.google.com/folderview?id=0B0PA7XM1BmLMfnY0eENQUG15Tzg5Y3drZ1FCTjN2VzVrRTR4YzVhWUctUHFEOWU5bzZBa28&usp=sharing

**Comment by aldenml** [comment]
@arvidn Do you recommend to set `settings_pack::utp_dynamic_sock_buf` to false as default in general?

**Comment by arvidn** [comment]
since I saw tchoulihan's logs, I think I would (assuming it fixes his problem). Either way, I'll probably remove this logic. Presumably it will not be a big deal to assume an initial MTU of 1500. The PMTU discovery doesn't work on OSX (I think it works on windows and linux though)

**Comment by aldenml** [comment]
Well, waiting for your PR to get merged

**Comment by arvidn** [comment]
I believe I merged this patch.
