### ISSUE TITLE
[request] Py3.12 wheel builds on pypi

### ISSUE THREAD

**Issue by zakkarry** [arvidn/libtorrent#7729]
libtorrent version (or branch): latest 2.0.x and 1.2.x at the time this is addressed

platform/architecture: All (specifically MUSL for my uses) for Python 3.12 - but should be built for all arch on 3.12

compiler and compiler version: python 3.12

---

https://pypi.org/project/libtorrent/#files contains wheel builds for py 3.10 - however, 3.12 is used in the Alpine images relevant to my uses.

I am a deluge team member and am trying to help get a container for libtorrent v1.2.x and deluge in cooperation with maintainers at https://linuxserver.io. Having a wheel built and provided for 3.12 via Pypi to install with pip would be ideal in this circumstance.

Since Alpine 3.18-3.19 are 3.11, and 3.20/Edge are on 3.12 - it would be nice to be provided with builds for libtorrent using Python 3.12

I'm not sure if someone is actively maintaining the Pypi builds or not, but if help is needed, given that Deluge is probably the main torrent client using the wheel builds - I would be willing to help out. You can check my github profile to show that I am not a complete random.

@AllSeeingEyeTolledEweSew since you are a maintainer on pypi as well.

**Comment by rdimaio** [comment]
Hi - this was closed as completed, but PyPI still has no 3.12 distribution. Is there anything we can do to help on this? Thanks.
