### ISSUE TITLE
File preallocation does not work after its priority is changed from "do not download"

### ISSUE THREAD

**Issue by HanabishiRecca** [arvidn/libtorrent#7732]
libtorrent version (or branch): 2.0.10
platform/architecture: Linux

File preallocation does not work after its priority is changed from "do not download".
It is reproducible if you try to download additional files on a partial torrent.

I see that `open_file_impl` intentionally checks for `dont_download` priority.

https://github.com/arvidn/libtorrent/blob/2ab8fedabb7716947edc77958da6d0b5e1040df9/src/mmap_storage.cpp#L899-L901

But the problem is, `set_file_priority` opens the file **before** updating the priority.

https://github.com/arvidn/libtorrent/blob/2ab8fedabb7716947edc77958da6d0b5e1040df9/src/mmap_storage.cpp#L164-L172

---

This patch fixes the issue:

```patch
--- a/src/mmap_storage.cpp
+++ b/src/mmap_storage.cpp
@@ -164,6 +164,7 @@ error_code translate_error(std::error_code const& err, bool const write)
 			if (old_prio == dont_download && new_prio != dont_download)
 			{
 				// move stuff out of the part file
+				m_file_priority[i] = new_prio;
 				std::shared_ptr<aux::file_mapping> f = open_file(sett, i, aux::open_mode::write, ec);
 				if (ec)
 				{

```

But I'm not sure how appropriate it is. What do you think, @arvidn?

**Comment by ValeZAA** [comment]
I had a torrent 100%, then swirched off file, then deleted file, then enabled file. It allocates 0 byte file on the disk with sparse metadata of correct size of that file.

Qbittorrent 5.0.0beta1 still has those issues: no rehashing of specific folders or files without full rehadhing, Tixati has it; issues with restarting torrents if you delete specific files without first disabling them...

**Comment by HanabishiRecca** [comment]
> It allocates 0 byte file on the disk with sparse metadata of correct size of that file. There is no bug...

I don't really get what are you trying to say. Preallocation is supposed to create a file with its full size. There is a bug and my patch fixes it.

**Comment by ValeZAA** [comment]
> Preallocation is supposed to create a file with its full size.

I am not sure such a mode makes any sense, but sure, if there is undefined behaviour where you first open file and the change open properties... Can you submit a patch? Fork this repo, click edit in the file in your repo, click pull request on this repo, submit changes.

**Comment by HanabishiRecca** [comment]
> I am not sure such a mode makes any sense

That's how it works right now. Add a new torrent (without checking or unchecking the files), start it, and you'll see that full-sized files are created on first access.

> Can you submit a patch?

Yes. I just waited for @arvidn's response on it. But I guess it could be reviewed as a PR.

**Comment by HanabishiRecca** [comment]
* #7733
