### ISSUE TITLE
Build fails on aarch64-linux-android

### ISSUE THREAD

**Issue by gen2brain** [arvidn/libtorrent#776]
**Please provide the following information**

libtorrent version (or branch):
1.1.0

platform/architecture:
android/arm64 (aarch64)

compiler and compiler version:
aarch64-linux-android-g++ (GCC) 4.9 20150123 (prerelease)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

    ./configure --host=aarch64-linux-android --prefix=/opt/android-toolchain-arm64 --with-openssl=/opt/android-toolchain-arm64 --with-boost=/opt/android-toolchain-arm64 --with-boost-libdir=/opt/android-toolchain-arm64/lib --enable-static --disable-shared --disable-pool-allocators --disable-deprecated-functions && make V=1 && make install

This is a build error:

    file.cpp: In member function 'int64_t libtorrent::file::readv(int64_t, const iovec_t*, int, boost::system::error_code&, int)':
    file.cpp:1827:18: error: '::preadv' has not been declared
       int ret = iov(&::preadv, native_handle(), file_offset, bufs, num_bufs, ec);
                      ^
    file.cpp: In member function 'int64_t libtorrent::file::writev(int64_t, const iovec_t*, int, boost::system::error_code&, int)':
    file.cpp:1885:18: error: '::pwritev' has not been declared
       int ret = iov(&::pwritev, native_handle(), file_offset, bufs, num_bufs, ec);
                      ^
    Makefile:970: recipe for target 'file.lo' failed

This same config works for arm-linux-androideabi . I tried to include sys/syscall.h manually, but same thing. TORRENT_ANDROID is defined.

**Comment by aldenml** [comment]
Are you using a package from the website? It's supposed to be fixed in the branch RC_1_1 (https://github.com/arvidn/libtorrent/commit/f23cf8466473de271f73541ac8e46e7e6ed77d39)

**Comment by gen2brain** [comment]
Full log https://justpaste.it/uw7b

**Comment by gen2brain** [comment]
I use tarball from releases https://github.com/arvidn/libtorrent/releases/download/libtorrent-1_1/libtorrent-rasterbar-1.1.0.tar.gz

**Comment by aldenml** [comment]
Can you test using the HEAD from RC_1_1 branch?

**Comment by gen2brain** [comment]
Same error with RC_1_1 branch. I can provide more details, just tell me what you need.

**Comment by aldenml** [comment]
Well, actually, I can't help you much more because I don't use "./configure". In the past it was such a headache that I moved to bjam. I'm using android NDK r11c gcc.

**Comment by gen2brain** [comment]
Ok, thanks, I will try with NDK r11c, and also with bjam.

**Comment by gen2brain** [comment]
Sorry, I made a mistake. It builds fine with RC_1_1, and I was already using NDK 11c.
 I am closing this issue. Thanks.
