### ISSUE TITLE
Question about listen_failed_alert and listen_succeeded_alert API

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#777]
libtorrent master

I was playing with these two alerts, and I felt something odd with having the field `endpoint` as a `tcp::endpoint` when the `socket_type_t` is `udp`. I know that it carries the same information than two separate fields (address and port). But I wonder which option is better design.

**Comment by arvidn** [comment]
yes, it is a bit odd. I imagine the alternative would be to either split it up into an address and port field, or have two separate alert types.

**Comment by arvidn** [comment]
I guess this has been addressed now
