### ISSUE TITLE
simple_test compilation issues

### ISSUE THREAD

**Issue by AlexandruCostache** [arvidn/libtorrent#79]
Hi,

Building the simple test from mainline using the generated Makefile in the examples folder fails on my side with:

    ../src/.libs/libtorrent-rasterbar.so: undefined reference to `boost::random::random_device::operator()()'
    ../src/.libs/libtorrent-rasterbar.so: undefined reference to `boost::random::random_device::~random_device()'
    ../src/.libs/libtorrent-rasterbar.so: undefined reference to `boost::random::random_device::random_device()'
    ../src/.libs/libtorrent-rasterbar.so: undefined reference to `boost::chrono::steady_clock::now()'

To build it I had to add these boost libs to the simple_client target in the Makefile so it looks like this:

	$(AM_V_CXXLD)$(CXXLINK) $(simple_client_OBJECTS) $(simple_client_LDADD) $(LIBS) $(BOOST_RANDOM_LIB) -lboost_chrono

I've configured it without any extra arguments on a Ubuntu 14.04 machine - ./configure && make && make install 

Was I doing something wrong or is it necessary to configure libtorrent with the examples option from the very beginning?

**Comment by arvidn** [comment]
would you mind putting that in a pull request? boost.random is a relatively new dependency in master. libtorrent hasn't been released stable since it was added.

**Comment by AlexandruCostache** [comment]
sure, I've added https://github.com/arvidn/libtorrent/pull/82

**Comment by arvidn** [comment]
I take in that fixes this issue
