### ISSUE TITLE
Got a (new) trace when running libtorrent

### ISSUE THREAD

**Issue by lfdversluis** [arvidn/libtorrent#794]
**Please provide the following information**

libtorrent version (or branch):

1.0.8

platform/architecture:

mac mini 2009
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Trace:

assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.0.8.0
bdce134

file: '../../src/torrent.cpp'
line: 6934
function: libtorrent::torrent_handle libtorrent::torrent::get_handle()
expression: m_ses.is_network_thread()

stack:
1: void boost::asio::detail::service_registry::init_keyboost::asio::detail::task_io_service(boost::asio::io_service::service::key&, boost::asio::detail::service_idboost::asio::detail::task_io_service const&)
2: boost::asio::io_service::service\* boost::asio::detail::service_registry::createboost::asio::socket_acceptor_service<boost::asio::ip::tcp >(boost::asio::io_service&)
3: boost::asio::asio_handler_is_continuation(...)
4: boost::asio::asio_handler_is_continuation(...)
5: boost::asio::asio_handler_is_continuation(...)
6: boost::asio::asio_handler_is_continuation(...)
7: boost::asio::asio_handler_is_continuation(...)
8: boost::asio::asio_handler_is_continuation(...)
9: boost::asio::asio_handler_is_continuation(...)
10: boost::asio::detail::socket_ops::getnameinfo_emulation(sockaddr const_, unsigned long, char_, unsigned long, char*, unsigned long, int, boost::system::error_code&)
11: boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lockboost::asio::detail::posix_mutex&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&)
12: boost::asio::detail::task_io_service::run(boost::system::error_code&)
13: boost::asio::io_service::run(boost::system::error_code&)
14: boost::asio::asio_handler_is_continuation(...)
15: boost::asio::asio_handler_is_continuation(...)
16: boost::asio::asio_handler_is_continuation(...)
17: boost::asio::asio_handler_is_continuation(...)
18: boost::asio::ip::operator!=(boost::asio::ip::basic_resolver_iteratorboost::asio::ip::tcp const&, boost::asio::ip::basic_resolver_iteratorboost::asio::ip::tcp const&)
19: boost_asio_detail_posix_thread_function
20: _pthread_body
21: _pthread_body
22: thread_start

**Comment by arvidn** [comment]
unfortunately this stack trace doesn't look right. fundamentally it looks like the hostname lookup thread end up calling a function that really should have been posted to the main thread. That shouldn't be possible though, the handlers should always be posted back to the main io_service. since the stack is corrupt anyway, perhaps it's the user/client thread somehow

**Comment by Falcosc** [comment]
@lfdversluis are you able to reproduce it or does it even occur multiple times?
