### ISSUE TITLE
High performance download/upload mode.

### ISSUE THREAD

**Issue by AndresGalaviz** [arvidn/libtorrent#799]
libtorrent version (or branch):

1.1.1

platform/architecture:

Windows/x64

compiler and compiler version:

msvc-14.0 address-model-64 release

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I did a BitTorrent client based on the provided examples however I'm trying to optimize it for very high throughput networks (10Gb/s) and sharing hundreds of very heavy files (~100 GB). Because the client should not consume the whole network and I/O time I have download/upload speed capped at 20 Mb/s for normal clients and unlimited upload speed for the initial seed. 

They are all connected through DHT: Each client and initial seed add all the other machines' IP addresses to the DHT.

My problem is that it takes a long time to reach the theoretical limit; it's similar to an acceleration behavior with speed increases up to a certain point followed by speed decreases to a "mid-point", this behavior is repeated until top speed is reached.

These are the settings I've been trying to tune for the Client:
 ```
    settingsPack.set_bool(lt::settings_pack::use_read_cache, true);
    settingsPack.set_bool(lt::settings_pack::enable_natpmp, false);
    settingsPack.set_bool(lt::settings_pack::enable_upnp, false);
    settingsPack.set_bool(lt::settings_pack::enable_dht, true);
    settingsPack.set_bool(lt::settings_pack::low_prio_disk, false);
    settingsPack.set_bool(lt::settings_pack::coalesce_reads, true);
    settingsPack.set_bool(lt::settings_pack::coalesce_writes, true);
    settingsPack.set_bool(lt::settings_pack::strict_end_game_mode, false);
    settingsPack.set_bool(lt::settings_pack::smooth_connects, false);
    
    settingsPack.set_int(lt::settings_pack::upload_rate_limit, 20 * 1024 * 1024);
    settingsPack.set_int(lt::settings_pack::download_rate_limit, 20 * 1024 * 1024);
    settingsPack.set_int(lt::settings_pack::local_download_rate_limit, 20 * 1024 * 1024);
    settingsPack.set_int(lt::settings_pack::local_upload_rate_limit, 20 * 1024 * 1024);
    settingsPack.set_int(lt::settings_pack::connection_speed, 200);
    settingsPack.set_int(lt::settings_pack::active_loaded_limit, 20);
    settingsPack.set_int(lt::settings_pack::cache_size, 2 * 1024);
    settingsPack.set_int(lt::settings_pack::min_reconnect_time, 10);
    settingsPack.set_int(lt::settings_pack::peer_connect_timeout, 10);
    settingsPack.set_int(lt::settings_pack::peer_timeout, 20);
    settingsPack.set_int(lt::settings_pack::request_timeout, 10);
    settingsPack.set_int(lt::settings_pack::inactivity_timeout, 20);
    settingsPack.set_int(lt::settings_pack::max_allowed_in_request_queue, 5000);
    settingsPack.set_int(lt::settings_pack::max_failcount, 2);
    settingsPack.set_int(lt::settings_pack::max_queued_disk_bytes, 1024 * 1024);
    settingsPack.set_int(lt::settings_pack::handshake_timeout, 6);
    settingsPack.set_int(lt::settings_pack::request_queue_time, 50);
    settingsPack.set_int(lt::settings_pack::max_out_request_queue, 5000);
    settingsPack.set_int(lt::settings_pack::send_buffer_low_watermark, 100 * 1024);
    settingsPack.set_int(lt::settings_pack::send_buffer_watermark, 1000 * 1024);
    settingsPack.set_int(lt::settings_pack::send_buffer_watermark_factor, 150);
    settingsPack.set_int(lt::settings_pack::dht_announce_interval, 60);
    settingsPack.set_int(lt::settings_pack::tick_interval, 150);
    settingsPack.set_int(lt::settings_pack::connections_limit, 2000);
    settingsPack.set_int(lt::settings_pack::predictive_piece_announce, 10);
    settingsPack.set_int(lt::settings_pack::network_threads, 5);
    settingsPack.set_int(lt::settings_pack::aio_threads, 5);
    settingsPack.set_int(lt::settings_pack::unchoke_slots_limit, 30);
    settingsPack.set_int(lt::settings_pack::choking_algorithm, lt::settings_pack::rate_based_choker);
    settingsPack.set_int(lt::settings_pack::seed_choking_algorithm, lt::settings_pack::fastest_upload);
	settingsPack.set_int(lt::settings_pack::mixed_mode_algorithm, lt::settings_pack::prefer_tcp);
```
For the initial seed box I use `high_performance_seed(settingsPack)` instead, although I'm not sure if I might need to have even higher settings for this machine as well.

Is there anything I should change in the settings to achieve these two scenarios? I was thinking of adding a `high_performance_client()` or something similar to the library as well.

**Comment by arvidn** [comment]
the best and most reliable approach is to profile. You can poll for session_stats (post_session_stats()) and log the session_stats_alert message() to a file. Polling once a second or so is reasonable. The resulting file can then be run through tools/parse_session_stats.py. It requires gnuplot and will generate graphs for the metrics.

intuitively I would be a bit worried about the rate limiter. It's not very sophisticated and there's a risk it's internal latency restricts bandwidth below the limit (when set high).

another limit to look at is the _incoming_ request limit on the downloaders. If they don't except a large enough request queue, you may not be able to fill the bandwidth delay product.

**Comment by AndresGalaviz** [comment]
I see, I will try profiling the sessions.

Yes, I've observed that the rate is sometimes significantly over or under the limit. I will have to find another of limiting the rate without introducing extra latency.
By the incoming request limit you mean _max_allowed_in_request_queue_ ? I have raised that number to 5000 and also had to raise some settings on the _high_performance_seed_, mainly because the settings stated in there don't particularly seem high performance now a days.

Any other recommendations you can think of?

**Comment by AndresGalaviz** [comment]
Also, I was reading these two articles you wrote:
http://blog.libtorrent.org/2012/12/swarm-connectivity
http://blog.libtorrent.org/2012/01/seeding-a-million-torrents/

They were very helpful but I was wondering if the behavior described in "swarm connectivity" is still present or did the inclusion of DHT mitigate this problem? A behavior like this will greatly impact our performance.

**Comment by arvidn** [comment]
> By the incoming request limit you mean max_allowed_in_request_queue ?

yes

> and also had to raise some settings on the high_performance_seed, mainly because the settings stated in there don't particularly seem high performance now a days.

Please issue a pull request if you think any of those presets should be changed!

> They were very helpful but I was wondering if the behavior described in "swarm connectivity" is still present or did the inclusion of DHT mitigate this problem?

That logic is still in effect. I don't understand how the DHT influences this. the DHT has been around for a lot longer.

> A behavior like this will greatly impact my performance as we want to join several thousands of machines into the DHT at the same time and as fast as possible so that they can all start sharing the torrent data.

Improved or deteriorated performance? Which mechanism, specifically, impacts performance? how and why? Is this a measured or assumed impact?

**Comment by AndresGalaviz** [comment]
I'll issue a pull request.

An unevenly connected swarm will result in deteriorated performance in both joining the swarm and piece distribution. This is an assumed but also observed behavior, I have yet to measure it strictly across all the nodes. This is also based on the findings of your article. 
If this logic is still in effect and this scenario is still present, are there any advances in implementing a better connection ranking function to achieve a more evenly connected swarm?

**Comment by arvidn** [comment]
the mechanism that's described in the swarm-connectivity post (and by [bep 40](http://bittorrent.org/beps/bep_0040.html)) makes the swarm evenly connected, not the opposite. It was designed to *improve* piece distribution and join performance.

> If this logic is still in effect and this scenario is still present, are there any advances in implementing a better connection ranking function to achieve a more evenly connected swarm?

By "this", are you referring to BEP40?

Are you saying that the connection ranking scheme described by BEP40 has some flaws?

**Comment by AndresGalaviz** [comment]
Yes, I know that it makes the swarm more evenly connected, what I was not sure was if your findings were solely theoretical improvements or were already implemented as a fix to the BitTorrent specification. I think I failed to explain what I meant. I was aware of the existence of the formula described in BEP 40 but wasn't sure if this exact formula was that optimization you described in swarm-connectivity or you were theorizing on a newer improvement.

No, I did not meant the ranking scheme had some flaws. 

Thanks!

**Comment by arvidn** [comment]
libtorrent implemented BEP40 a few versions ago. technically the bittorrent specification is unchanged, the BEPs are more like optional amendments to it.

If you want to seed torrents to a lot of peers, you should just make sure to set your peer limit very high. That way you're unlikely to ever run out of slots, at which point the peer prioritization logic won't affect you.

**Comment by AndresGalaviz** [comment]
I see, thanks for your input, it is greatly appreciated!

**Comment by arvidn** [comment]
if you want help interpreting stats logs, feel free to post them here
