### ISSUE TITLE
compact storage mode

### ISSUE THREAD

**Issue by gen2brain** [arvidn/libtorrent#801]
Hi,

I would like to try to keep and maintain a patch for compact storage mode, I need it for my app. It works great on android/fat32. So far I found commits fd4a46342fabc4e1dd08138986461d0ce9256701 f5c112eefc4ad76ded8e477404b319032178213a and e8693465a56b7305b6f168d58f04a6d2321c8827 , but I can't find where is the actual implementation removed. Can you please point me to it?

Thanks

**Comment by arvidn** [comment]
It was removed in the first AIO branch (back in the svn days). This branch was eventually merged and later removed. So, in git, only the merge commit is left, here: https://github.com/arvidn/libtorrent/commit/7351389ce8aee43059881b36bfd6247f75853db0

Now, there was a very good reason to remove this feature. It can't be parallelized in multiple I/O threads.
I'm convinced that what you're really looking for is some way of dealing with filesystems that don't support sparse files and background zero-filling. Another way of doing that is to create a piece affinity in the piece picker to not pick too far away from the highest piece we have in each file. (to rate limit the number of _new_ disk blocks that needs flushing)
