### ISSUE TITLE
Question about DHT extension API

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#805]
libtorrent master

I want to ask what are the advantages of having the current method (via `plugin::register_dht_extensions(dht_extensions_t&)`) versus having `plugin::on_dht_request(char const* query, int query_len, dht::msg const& request, entry& response)`.

I know that having the direct address of the functions to call could be a performance advantage, but isn't the "strcmp" performed anyway for each function registered (even if they are registered to the same query)?

What if I want to add a logging extension that needs to listen to all queries (but closer to the source than the alerts)? What if I want to implement custom analysis or security measures? It could be that I'm looking at the wrong place.

**Comment by ssiloti** [comment]
The motivation was to avoid making a virtual function call for every plugin, most of which do not implement any dht message handlers.

I would expect additional logging or security features to be implemented directly in libtorrent rather than as extensions, but it might depend on exactly what is being proposed.

**Comment by aldenml** [comment]
@ssiloti thank you for comment, now I remember a similar comment from arvin a while ago. I will think about it.

**Comment by aldenml** [comment]
@arvidn do you think I can use `plugin::implemented_features` to avoid the unnecessary virtual function call?

**Comment by aldenml** [comment]
@ssiloti do you think using `plugin::implemented_features` is a good idea? how does it affects you plugin?

**Comment by ssiloti** [comment]
I don't have a strong opinion about the use of `plugin::implemented_features`. A while ago I proposed splitting the plugin interface into finer grained classes[1] which I still think is a more elegant solution.

[1] https://github.com/ssiloti/libtorrent/commit/d3d30ef59dcafc2ed05b2e9a2fd2db4eff9957c9

**Comment by aldenml** [comment]
Thanks again. I agree with you that granular interfaces and "dynamic_cast" is more elegant. In this case I'm trying to stay away from rtti and so far it's possible with libtorrent. I will prepare a PR for review.

**Comment by aldenml** [comment]
Closed https://github.com/arvidn/libtorrent/pull/823
