### ISSUE TITLE
Question about flag_pinned and flag_merge_resume_http_seeds sharing the same value

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#807]
libtorrent RC_1_1

Hi @arvidn, in the code of `add_torrent_params` these flags share the same value, is that ok?

**Comment by arvidn** [comment]
hm.. that sounds wrong..

**Comment by arvidn** [comment]
maybe all deprecated flags should be moved to the bottom of that enum. in master ABI compatibility is not important, as long as there's reasonable API compatibility

**Comment by arvidn** [comment]
does this seem reasonable? https://github.com/arvidn/libtorrent/pull/810

**Comment by aldenml** [comment]
It LGTM in master. How you will handle it in RC_1_1?

**Comment by arvidn** [comment]
making any changes to the flag values in RC_1_1 would break the ABI. I suppose I could just disable the feature backed by the deprecated flag. Do you have any suggestions?

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/813

**Comment by aldenml** [comment]
Closing in advance
