### ISSUE TITLE
compilation error in bt_peerconnection.cpp

### ISSUE THREAD

**Issue by metamystical** [arvidn/libtorrent#808]
**Please provide the following information**

libtorrent version (or branch):
master branch, beginning with commit 0583394 on May 30

platform/architecture:
arch linux 64 bit

compiler and compiler version:
gcc version 6.1.1 20160501 (GCC)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
I tried to build the latest update in order to get the bug fix to the dht_nodes counter, but got these compiler errors:

  CXX      bt_peer_connection.lo
In file included from /usr/include/boost/config.hpp:61:0,
                 from ../include/libtorrent/config.hpp:40,
                 from bt_peer_connection.cpp:34:
/usr/include/boost/multiprecision/cpp_int.hpp:193:4: error: right operand of shift expression ‘(1u << 63u)’ is >= than the precision of the left operand [-fpermissive]
    BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));
    ^
/usr/include/boost/multiprecision/cpp_int.hpp:416:4: error: right operand of shift expression ‘(1u << 63u)’ is >= than the precision of the left operand [-fpermissive]
    BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));
    ^
/usr/include/boost/multiprecision/cpp_int.hpp:568:4: error: right operand of shift expression ‘(1u << 63u)’ is >= than the precision of the left operand [-fpermissive]
    BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));
    ^
Makefile:924: recipe for target 'bt_peer_connection.lo' failed

I traced the origin of the error to commit 0583394 on May 30:

"remove dependency on libtommath and use boost.multiprecision instead "

**Comment by arvidn** [comment]
does this help? https://github.com/arvidn/libtorrent/pull/811

**Comment by arvidn** [comment]
from this [GCC bug report](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68979), I get the impression that boost.multiprecision or GCC are the only ones who can fix this.

There's no flag to disable this locally around the boost include.

**Comment by arvidn** [comment]
according to this [bug report](https://svn.boost.org/trac/boost/ticket/12181) against boost.multiprecision it was fixed in boost git 5 weeks ago. boost-1.61 was released 4 weeks ago, so there's a chance this will work if you use the latest version of boost.

**Comment by metamystical** [comment]
Thank you for researching this. Arch Linux has boost-1.60, so I had to build v1.61 myself, and that required that I build python-3.5.1 also. But now I can compile the latest libtorrent and the dht.dht_nodes counter works again.
