### ISSUE TITLE
Inteligent files hooks. Related to qBt.

### ISSUE THREAD

**Issue by Misiek304** [arvidn/libtorrent#819]
**Please provide the following information**

libtorrent version (or branch):
1.0.9.0

platform/architecture:
Windows 7 x64, AMD64

compiler and compiler version:
Boost 1.60.0 (?)

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
In qBt 3.2.5 when I deleted any files from hard drive that there seeding or they where otherwise active qBt would marked them as "Paused" and let me delete the files without an issue. In 3.3.X era I can't delete those files because of "file in use" error in Windows. I have to manually stop them from seeding. I know it sounds like qBt problem but I was told that your libtorrent is responsible for files and folder management. Is there a way (maybe an advanced function) to disable file hooks (I was told that's the name of the problem) and let Windows delete files and mark torrent as "error: files missing"

There is also another issue that would fix this. When there is a torrent that is seeding, not actively seeding, just seeding I am able to delete the files without an error and when qBt wants to start actively seeding this torrent there is no "error: files missing" it marks them as "queued". It's really not efficient.

I would like to hear your thoughts about this problem.

**Comment by arvidn** [comment]
you could set your file-pool size to 0. that would make libtorrent close the file after every access. It's not going to be very efficient, but it seems like you think it's more important that qbt doesn't have the file open.

what's this "other issue" you're talking about? are you saying that you *are* able to delete those files? so in the first paragraph, you're strictly *only* talking about files that are actively being uploaded to other peers?

**Comment by Misiek304** [comment]
To clarify.
When the torrent is for example actively seeding/downloading there is no way Windows will let me to delete the files. "File in use" error. I have to manually stop qBt from seeding/downloading.

When the torrent is just in seeding status in most cases (not always) I'm able to delete the files but qBt marks them with status "queued" so they don't appear in "Error" category. It's like it doesn't realize that the files are gone.

So I would like it to let me delete those files no matter if they having status actively seeding/downloading or just seeding and return the torrents to "Error" category with massage that the files are gone or that they where deleted. Whichever you like better.  In 3.2.5 the where marked with status "Paused" so it would be just a status change. If that's too much work for you I would at least like to have an option to delete files of torrents that are just in "seeding" status.

I like the idea of "file-pool size to 0" you mentioned but can you tell me how inefficient exactly would that be? Also how do I do it? Can I do it myself or do I have to contact qBt developers to make some changes in the code?

**Comment by arvidn** [comment]
settings file-pool-size to 0 does not degrade performance as long as you don't have anti-virus installed (or anything else that hooks on file-open and file-close). However, if you *do* have anti-virus, performance could suffer significantly. at least it did for me before I introduced the file pool 10 years ago or so.

file_pool_size is a libtorrent setting, I don't know if or how qBT might expose that. I can't speak for qbt, just libtorrent. I also don't know what "3.2.5" means from my point of view. is that a different version of libtorrent? which version (of libtorrent) are you having this problem with?

**Comment by Misiek304** [comment]
No, sorry. 3.2.5 refers to qBittorrent, version 3.2.5.
About this anti-virus stuff. Are you referring to a specific one or anyone? 

Also where there any changes to libtorrent between 1.0.7.0 (used in qBt 3.2.5) and 1.0.9.0 (used in qBt 3.3.4) that would be responsible for this change?

**Comment by Falcosc** [comment]
I'm not sure how it was possible with 1.0.7, maybe you did had just luck to delete the file between the file access actions.
The point is during seeding we have to read the file. The read time get a little bit reduced by loading it into cache and close it after some parts got read into the cache. But you can't not prevent that the file got accessed in seeding state. You have to prevent it from going into seeding state if you want to get exclusive acces to the file.

You have several solutions to do this:
- use the torrent queue to limit the amount of open torrents
- use the qbittorrent web api to delete the files
- use other interfaces to communicate with qbittorent to tell that it should stop reading new blocks for incoming bittorent requests.

@Misiek304  What did you think about it? I would like to help you but I don't have any idea how to know when we have to prevent libtorrent from accessing the file if we are requested to read or write to the file. You need to tell libtorrent that you want to do something with the files.
