### ISSUE TITLE
How to configure connections limit?

### ISSUE THREAD

**Issue by Misiek304** [arvidn/libtorrent#839]
Hi,

Recently I upgraded my internet connection from 60/3 to 120/10. Until now I used the default settings in Settings > Connections > Connections limits in qBittorrent but now I think I should adjust them for higher speeds. My goal is to get the best efficiency with minimal waste of my internet connection. All the tutorials I could find where outdated or applied to lower speeds. Can you help me with that?

Thank you for all suggestions.

![](https://vpn.schendera.com/i/qbittorrent-proxy-settings.jpg)

**Comment by arvidn** [comment]
the short answer is: "try it out and let me know" :)

fundamentally this is a hard problem. It comes down to discovering the "market value" of upload bandwidth and make sure to increase the number of upload slots accordingly. i.e. don't spread your upload capacity too thin by opening up too many uplooad slots, and don't give away your capacity too cheaply by opening up too few. For details on this, you should check out the "BitTyrant" paper from 2006 (piatek & isdal). libtorrent implements a bittyrant unchoke algorithm, but it's not well tested. If you're up for it, you may want to give it a try. let me know what you find in that case.

**Comment by Misiek304** [comment]
Not really helpful :smile: 
How will I know if I spread my upload capacity to thin? Can't you really recommend any "base" settings from which I could start? I writing here because you're the libtorrent developer so you will know best how it's working.

**Comment by arvidn** [comment]
when your download rate decreases, you're either having too many upload slots or too few, you can find which one by searching. As I said, it's a hard problem, it's an optimization problem. There's not *one* answer, the answer is likely an algorithm, and possibly similar to bittyrant.

**Comment by Misiek304** [comment]
Lastest version of BitTyrant is from 2007. I don't like using an outdated software.

**Comment by arvidn** [comment]
I was referring to the paper, specifically the algorithm they propose

**Comment by arvidn** [comment]
maybe I'm misunderstanding your question. It sounds to me like you're asking for recommendations for "better" configuration options. all I'm saying is that: "it depends". you have to tweak and tune. the bittyrant paper describes clearly what the dynamics are, and it attempts to perform the search/optimization automatically.

**Comment by Misiek304** [comment]
Yes, I'm. Sorry for the confusion.
For now I doubled the default settings and used the 2 number as base.

Connections limits:
1024/256/16/8

and for queue:
8/8/16

I also have SQM-scripts for OpenWRT installed on my router to fix bufferbloat and I limited maximum speeds for download and upload in qBt to 8192/896. Hope this helps someone.
