### ISSUE TITLE
Set piece deadline not honored

### ISSUE THREAD

**Issue by jacobzelek** [arvidn/libtorrent#84]
I'm using the Python bindings for libtorrent in an application for streaming. In every possible combination of setting piece deadlines, along with piece priorities, the piece deadlines seem to be ignored. This happens with both sequential downloading and non-sequential downloading. As soon as I need a piece I set a piece deadline to a small amount (several hundred milliseconds) and only do it once. Is there something I'm missing about piece deadlines? Do I need to keep setting piece deadlines? Or is this a bug with the Python bindings?

**Comment by jacobzelek** [comment]
When I mean the piece is complete, I mean it returns true when I call have_piece(index) on the torrent handle. To my knowledge, a piece is complete when it has been written to the disk. Is it possible that the disk IO thread is taking it's time writing a piece I put under deadline?

**Comment by arvidn** [comment]
sequential download and piece- or file priorities are conflicting settings with piece deadlines. If you're streaming, you should not set any of those other things.

My guess is that you're not setting the piece deadline early enough. libtorrent will always try to keep its download pipe full. If you set a piece deadline, it will be the next thing stuffed down the pipe, but you'll also need to drain what's in there already first. And as soon as the time-critical piece is in the pipe, libtorrent will start stuffing other pieces down there. meaning, if you will need the next piece soon, you better tell libtorrent as early as possible, as not to waste bandwidth downloading other, unrelated pieces.

I'm not sure what you mean by your second comment. if you're using master, the hash check is no longer tied to the piece being flushed to disk, and can pass on pieces with lower latency, but in either case, set_piece_deadline() should post the piece to you (if you asked it to).

So, when you say set_piece_deadline() is not being honored, what's the symptom you see? What would you expect to see if it was honored?

**Comment by jacobzelek** [comment]
Thank you for clarifying the incompatibility between piece/file priorities and piece deadlines. I have removed all such priority calls. The piece deadlines seemed to be honored but they were not written to the disk and therefore handle.have_piece(index) returned false. I'm instead using the read_piece_alert to get the piece data instead of waiting until handle.have_piece(index) returns true. Thank you so much

**Comment by arvidn** [comment]
if you want the data as soon as possible, you can pass in a flag to set_piece_deadline() to indicate that, and as soon as the data is available (and hash checked) you'll receive a read_piece_alert with the data in it.

**Comment by jacobzelek** [comment]
That's what I ended up doing and it works great now.
