### ISSUE TITLE
Questions about two possible null pointer errors

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#85]
First point: https://github.com/arvidn/libtorrent/blob/master/src/peer_connection.cpp#L5092

Do you think that by any chance, the storage can be null? The if surrounding this line is: `if (t->seed_mode() && !t->verified_piece(r.piece))`

Second point: https://github.com/arvidn/libtorrent/blob/master/src/block_cache.cpp#L856
Since you are calling `ok_to_evict(true)` it will ignore the hash and my question is. Is it possible that the hash is already NULL?

**Comment by arvidn** [comment]
m_storage can definitely be null. It's null briefly before the torrent is fully constructed, and before the metadata has been downloaded (if it was added as a magnet link) and it's also null during shutdown.

**Comment by arvidn** [comment]
do you see m_storage be null on that line? I would be a little bit surprised, because there's a check at the beginning of the function, leaving if the torrent is shutting down.

**Comment by arvidn** [comment]
delete NULL; is not an issue, it's valid.

**Comment by aldenml** [comment]
Thanks. We have three errors that are related to the methods enclosing these lines, but no enough stacktrace, no way of replicating and a minimal rate of occurrence. Closing this.
