### ISSUE TITLE
fileop compile failed

### ISSUE THREAD

**Issue by k1988** [arvidn/libtorrent#850]
**Please provide the following information**

libtorrent version (or branch): RC_1_1

platform/architecture:
win10 x64

compiler and compiler version:
vc++ 2005

`struct fileop
{
virtual int file_op(int file_index, boost::int64_t file_offset, int size
			, file::iovec_t const* bufs, storage_error& ec) = 0;
}
`
declared in `include/libtorrent/storage.hpp`

but the implement in `/src/storage.cpp`  is 
`int file_op(int const file_index
			, boost::int64_t const file_offset
			, int const size
			, file::iovec_t const* bufs, storage_error& ec)`

I compile failed because the difference between them.

**Comment by arvidn** [comment]
what's wrong there? does visual studio consider the const applied to those ints as affecting the signature?

**Comment by k1988** [comment]
warning C4301: 'libtorrent::write_fileop::file_op': overriding virtual function only differs from 'libtorrent::fileop::file_op' by const/volatile qualifier
error C2259: "libtorrent::read_fileop" cannot instantiate abstract class

**Comment by arvidn** [comment]
this is fixed now, right?

**Comment by k1988** [comment]
Yes, the PR was megerd
