### ISSUE TITLE
Proxy settings have been merged

### ISSUE THREAD

**Issue by haarp** [arvidn/libtorrent#87]
Hey there.

Ever since upgrading my Debian box (Deluge-1.3.10 and libtorrent-0.16.18 (the current stable versions in Debian8)), Deluge can't contact trackers anymore. I have a proxy set for peer, webseed, DHT, but not tracker. This used to work well in the past.

http://forum.deluge-torrent.org/viewtopic.php?p=183779#p183779 pointed me in the right direction:
"If you are using libtorrent 0.16 then yes the proxy applies to all now."
and indeed, the libtorrent changelog states:
"* merged all proxy settings into a single one"

What is the reason for this change? My proxy is not set up to handle trackers, which explains why Deluge can't contact trackers anymore.

**Comment by arvidn** [comment]
what does it mean for the proxy to not handle trackers?

The main reason for the merge was that both trackers and peers (mostly) go over UDP these days, which means they use the same socket and the same proxy abstraction in libtorrent. On top of that, trackers normally assume that a peer can be contacted on the same socket that it announced on. Merging the proxy settings would make it much less likely to misconfigure a client to have that not be the case.

I would expect you to improve performance by proxying both tracker and peer traffic.

**Comment by haarp** [comment]
It's not a performance consideration tho. Some background: My ISP imposes a traffic limit on me, but traffic going through their (caching) proxy server does not count towards traffic. However, that proxy bans Bittorrent trackers. So the only way to get reasonable performance without eating up my volume within hours is to proxy peers, but to connect to trackers directly.

**Comment by arvidn** [comment]
fixed here: https://github.com/arvidn/libtorrent/pull/112

**Comment by haarp** [comment]
Very cool. Thanks a lot!
