### ISSUE TITLE
install issue with spaces in build path

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#88]
I don't remember seeing any issue last time I packaged libtorrent for the PPA (1.0.1) but it now seems with 1.0.6 spaces in the path generate the following error:

`libtool: install: /usr/bin/install -c .libs/libtorrent-rasterbar.so.8.0.0 /home/ubuntu/libtorrent/PPA Packaging/lt_1.0.6_rel/libtorrent-rasterbar-1.0.6/debian/tmp/usr/lib/libtorrent-rasterbar.so.8.0.0
/usr/bin/install: target `Packaging/lt_1.0.6_rel/libtorrent-rasterbar-1.0.6/debian/tmp/usr/lib/libtorrent-rasterbar.so.8.0.0' is not a directory`

I haven't investigate fixing it but I'm sure it's a trivial escaping of the supplied path.

**Comment by arvidn** [comment]
I don't think I've made any changes to the autotools build setup. Not deliberately at least. I'm sure you would be more capable of fixing it as well. If you figure out what the problem is, please submit a pull request!

**Comment by arvidn** [comment]
this is from invoking ./configure && make install?

**Comment by cas--** [comment]
Yes using autotools although specifically I was using the debian package builder at the time.

**Comment by arvidn** [comment]
the problem is if prefix has a space in it. I can't find an obvious fix to that. the layers of commands and bash scripts are quite impregnable.

**Comment by Falcosc** [comment]
Do we want to have a look on it with the current scripts or should it be enough to give the hint that we don't want to support spaces at certain places?

**Comment by arvidn** [comment]
in some sense it feels a bit like 1990 to not support spaces, but I don't really have the motivation to fully understand this

**Comment by Falcosc** [comment]
I guess we can't count the number of scripts out there which still doesn't have full space support today. That mean we are at least not worse than the others.
And I would guess if we fix this one we would still have other scripts in this project which does not have a 100% support for spaces. As long as we have more important things to do we should just tell that we like the 90’s ;)
