### ISSUE TITLE
escape_path on web seed single_file_request

### ISSUE THREAD

**Issue by yinzhigang** [arvidn/libtorrent#889]
libtorrent version (or branch):
1.1.0
platform/architecture:
OS X/x86_64
compiler and compiler version:
Apple clang 7.3.0

web_peer_connection.cpp line: 339-341

`		request += "GET ";
		// do not encode single file paths, they are
		// assumed to be encoded in the torrent file
		request += using_proxy ? m_url : m_path;`

not encode the m_path, why? which torrent will encode the filename or path?

I'm using Chinese torrents, no one torrent have encoded the filename or path

If you can, please add escape_path on single file request.

PS: multi file request is worked on Chinese torrents.

**Comment by arvidn** [comment]
the web seed specification [1] defines single file torrents to have a URL stored in the torrent file. It seems odd if that URL would be invalid, is it? If it needs encoding, how would one know whether to encode '/'or not?

[1] http://getright.com/seedtorrent.html

**Comment by yinzhigang** [comment]
gotcha.

but I'm using a normal torrent file without url-list field, and manual add url seeds to torrent_info.

and in web_peer_connection.cpp 246-262

```
		// handle .torrent files that don't include the filename in the url
		if (m_path.empty()) m_path += "/" + t->torrent_file().name();
		else if (m_path[m_path.size() - 1] == '/')
		{
			std::string tmp = t->torrent_file().files().file_path(0);
#ifdef TORRENT_WINDOWS
			convert_path_to_posix(tmp);
#endif
			m_path += tmp;
		}
		else if (!m_url.empty() && m_url[m_url.size() - 1] == '/')
		{
			std::string tmp = t->torrent_file().files().file_path(0);
#ifdef TORRENT_WINDOWS
			convert_path_to_posix(tmp);
#endif
			m_url += tmp;
		}
```

looking it read m_path from name, not url list, can you escape the name on this code?

and I mean escape not just symbol like '/', the Chinese filename also need encode to like '%e5%8c%97%e4'

hope you can understand, my english is not good.

**Comment by arvidn** [comment]
technically, you're still supposed to add *valid* web seed URLs. i.e. ones that conform to the specification I liked to. The piece of code you're hitting is a work-around to patch up invalid urls. does this fix your issue? https://github.com/arvidn/libtorrent/pull/892

**Comment by yinzhigang** [comment]
Yes, it's works, thanks for this support so quickly.
