### ISSUE TITLE
dh_auto_clean attempts to run b2 in python setup.py

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#89]
When packaging 1.0.6 libtorrent for ubuntu PPA, `dh_auto_clean` is attempting to run the `b2` command in `setup.py`. There was no issue with this in 1.0.1.

```
dh clean  --parallel --with python2,python3,autoreconf
   dh_testdir -O--parallel
   debian/rules override_dh_auto_clean
make[1]: Entering directory `/home/ubuntu/Documents/libtorrent/PPA Packaging/lt_1.0.6_rel/libtorrent-rasterbar-1.0.6'
rm -rf build build-py*
dh_auto_clean
BOOST_ROOT =
CXXFLAGS = -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security
LDFLAGS = -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed
OS = LINUX
warning: No toolsets are configured.
warning: Configuring default toolset "gcc".
warning: If the default is wrong, your build may not work correctly.
warning: Use the "toolset=xxxxx" option to override our guess.
warning: For more configuration options, please consult
warning: http://boost.org/boost-build2/doc/html/bbv2/advanced/configuration.html
error: Unable to find file or target named
error:     '/boost/python//boost_python'
error: referred from project at
error:     '.'


bjam boost=source link=static geoip=static boost-link=static release optimization=space stage_module --abbreviate-paths -j6
build failed
[30894 refs]
dh_auto_clean: python-dbg setup.py clean -a returned exit code 1
```

I found someone else ran into the same packaging issue and simply created the following packaging patch, it works but seems a bit crude.

```
--- a/bindings/python/setup.py	2015-07-15 00:45:38.780329367 +0200
+++ b/bindings/python/setup.py	2015-07-15 00:45:50.004570474 +0200
@@ -51,7 +51,11 @@
 ext = None
 packages = None
 
-if '--bjam' in sys.argv or ldflags == None or extra_cmd == None:
+if 'clean' in sys.argv:
+	#disable clean mode
+	print ('clean mode')
+
+elif '--bjam' in sys.argv or ldflags == None or extra_cmd == None:
 
 	if '--bjam' in sys.argv:
 		del sys.argv[sys.argv.index('--bjam')]
```

**Comment by arvidn** [comment]
what is "clean mode"?

I'd be happy to accept a patch, but I'm not all that familiar with python distutils.

**Comment by cas--** [comment]
Clean mode comes from running `python setup.py clean  -a` and is for cleaning up build files.

I think the actual issue is that the bjam section should be contained in a Build override class, something like this: https://github.com/deluge-torrent/deluge/blob/develop/setup.py#L170

**Comment by sledgehammer999** [comment]
@cas-- 
This may not help you but Debian already has a package in experimental. You may check how they did it.
Grab the source package from the side panel: https://packages.debian.org/experimental/libtorrent-rasterbar-dev
Or even browse the src: https://anonscm.debian.org/cgit/collab-maint/libtorrent-rasterbar.git/tree/?h=experimental

**Comment by arvidn** [comment]
allright. merged that patch.
