### ISSUE TITLE
cppint_import_export.hpp:224:33: error: 'msb' was not declared in this scope

### ISSUE THREAD

**Issue by tete1030** [arvidn/libtorrent#891]
**Please provide the following information**

libtorrent version (or branch):
master

platform/architecture:
CentOS Linux release 7.1.150/x86_64

compiler and compiler version:
g++ (GCC) 5.1.1

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.
```
./configure --with-python-binding
make CXXFLAGS=-std=c++11
```

```
bt_peer_connection.cpp:106:48:   required from here
../include/libtorrent/aux_/cppint_import_export.hpp:224:33: error: 'msb' was not declared in this scope
          unsigned bitcount = msb(val) + 1;
```

**Comment by arvidn** [comment]
I copied that header from a recent version of boost, to support older versions that don't have that functionality. which version of boost are you building against? perhaps it's no longer compatible

**Comment by tete1030** [comment]
My boost version is 1.53.0.

**Comment by arvidn** [comment]
I see. that's presumably too old then. continuous integration runs on 1.59 as the oldest version iirc. perhaps you could try to fish this function out of a newer version of boost and introduce it in this header if boost is too old to contain it. (pull requests are welcome)

**Comment by tete1030** [comment]
Thank you. After I updated boost, this error disappeared.
