### ISSUE TITLE
buffer overrun in client_test on windows for large console redraws

### ISSUE THREAD

**Issue by mlt** [arvidn/libtorrent#9]
This is a low-priority issue...just annoyance. While it would be nice to check whether `buf-buffer` is a couple of bytes below *buffer*'s size, just making buffer 10 times larger would minimize frustration until 4K monitors with 5pt font go mainstream.

**Comment by arvidn** [comment]
I think [6cf9965] fixes in in master. I don't have easy access to a windows machine so I haven't tested it yet.

**Comment by mlt** [comment]
*const* is missing in front of `char* start = buf` on line 275 that breaks compilation. Aside from that it works so far.

**Comment by arvidn** [comment]
thanks!

**Comment by mlt** [comment]
hm... I put const slightly to the left :-) I'll check

**Comment by mlt** [comment]
It does compile either way :-)
