### ISSUE TITLE
[wishlist] fine-grained anonymous mode settings

### ISSUE THREAD

**Issue by pitchforks** [arvidn/libtorrent#90]
This is related to https://github.com/qbittorrent/qBittorrent/issues/3648.

For now Anonymous Mode settings look like this:

```
[ ] include peerID in the user-agent string
[x] use trackers only if they are using a proxy server
...
```

and state of checkboxes can't be toggled.

Please split Anonymous Mode into multiple finer settings, so setups like:

```
[ ] include peerID in the user-agent string
[ ] use trackers only if they are using a proxy server
...
```

can happen.

**Comment by arvidn** [comment]
that second checkbox isn't actually what the (now removed) option "force_proxy" did. *force_proxy* made it an error if a proxy was configured and it failed to proxy, as opposed to falling back to circumventing the proxy (which I believe is behavior nobody wants)
