### ISSUE TITLE
Unable to validate version with Python after compiling and installing

### ISSUE THREAD

**Issue by nostyler** [arvidn/libtorrent#906]
**Please provide the following information**

libtorrent version (or branch):
master

platform/architecture:
Ubuntu 16.04 x64
compiler and compiler version:
GCC 5.3.1

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

Ran the following commands to compile and install:
./autotool.sh
./configure --enable-python-binding --with-libiconv --disable-deprecated-functions
adjusted configure.ac in line with #870 
make -j$(nproc)
make
ldconfig

Calling python -c "import libtorrent; print libtorrent.version"   returns:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'version'

**Comment by arvidn** [comment]
did you figure this out?

**Comment by nostyler** [comment]
I thought I did, because I hit a 'new' error. However, solving that one has brought me back at the one described in this issue. Is there any way to reopen it?

I am used to taking the RC_* branches and have not his this error before. However, this was the first time I was using '--disable-deprecated-functions'. I will clone RC_1_1 in order to test if this is contributing to what I am experiencing.

**Comment by arvidn** [comment]
my experience is that normally when this happens, it's because the python binding was built for a different python version than what's trying to load it. i.e. python 2 vs. python 3
iirc, python modules have different entry points in version 2 and 3

**Comment by nostyler** [comment]
That was what I figured first as well. The second change I made for my installation is that I moved from Debian to Ubuntu. 

I have compiled RC_1_1 in a VM with Ubuntu (#1) and in a VM with Debian (#2).

I notice some additional warnings on #1 that I do not see in #2 when running make. There is a difference in versions of GCC and Python:
#1 = GCC 5.4.0 and Python 2.7.12
#2 = GCC 4.9.2 and Python 2.7.9

#1 throws the same error
#2 to be updated (ongoing)

**Comment by nostyler** [comment]
OK.

It appears to be caused by using the '--disable-deprecated-functions' flag. 

I have now compiled and installed RC_1_1 on Ubuntu 16.04. I will spend some time later on to compile and install master to see how that works out.

That being said. In ..bindings/python/src/version.cpp there is some logic that acts when this flag is used. I am too tired (and prob. not experienced enough) to continue from there..

**Comment by nostyler** [comment]
OK closing this one.

When using the '--disable-deprecated-functions' flag, it sets __version__ instead of version.

Validate the installation with:
python -c "import libtorrent; print libtorrent.__version__"
Instead of:
python -c "import libtorrent; print libtorrent.version"

**Comment by arvidn** [comment]
Did you mean to say "version" in both cases?

**Comment by nostyler** [comment]
No. I mean to say the concatenation of __ version __

Somehow it is triggering some markup and I do not know how to circumvent

**Comment by arvidn** [comment]
I see. I imagine that underscore version is set in both cases, but the one without underscores is deprecated
