### ISSUE TITLE
libtorrent 1.1.0 post_torrent_updates binding needs a default value

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#907]
We have a pull request to start migrating the Deluge python code to use `1.1.0` which found that post_torrent_updates method now requires a flags value in python but a default is supplied in C++.

https://github.com/deluge-torrent/deluge/pull/105#discussion-diff-70293884

I think the following change (as yet untested) in bindings/python/src/session.cpp will fix it:

```diff
-    .def("post_torrent_updates", allow_threads(&lt::session::post_torrent_updates))
+   .def("post_torrent_updates", allow_threads(&lt::session::post_torrent_updates), arg("flags") = 0xffffffff)
```

This could also affect other bindings methods that have the potential for a default value.

**Comment by arvidn** [comment]
Thanks for the report. I'll push this fix to RC_1_1 shortly
