### ISSUE TITLE
lt 1.0.9 not checking global env vars INCLUDE or LIB for Windows builds

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#911]
Trying to build with openssl enabled I found I needed to copy the include and lib files for openssl into the VC directory. The last build I made was with libtorrent 1.0.6 and it searched the paths correctly.

These are the commands used:
```
set INCLUDE=C:\OpenSSL-Win32\include;%INCLUDE%
set LIB=C:\OpenSSL-Win32\lib;%LIB%
set BOOST_BUILD_PATH=C:\boost
set PATH=%BOOST_BUILD_PATH%;%PATH%
b2 boost=source libtorrent-link=static geoip=static boost-link=static release optimization=space encryption=openssl
```

**Comment by arvidn** [comment]
hm.. I don't think the Jamfile has ever taken those into account. The way I do this on appveyor I specify: "include=C:\OpenSSL-Win32\include linkflags=/LIBPATH:C:\OpenSSL-Win32\lib"
I would be open to improve this situation

**Comment by cas--** [comment]
I wonder if it's a boost change (now using 1.59) but it definitely used to work that way :)

I'm not going to spend much time investigating it and using boost b2 properties seems a simpler way to do it anyway.

**Comment by cas--** [comment]
Just for reference I did find these details on env vars in boost: http://www.boost.org/build/doc/html/bbv2/faq/envar.html
