### ISSUE TITLE
Listen with proxy force

### ISSUE THREAD

**Issue by WhiteTrashLord** [arvidn/libtorrent#915]
I tested the proxy function of Libtorrent. It seems to work perfectly. I want to try to forward the ports through my proxy server. But if I use force_proxy no socket will listen.

Would it be possible to make a new setting which will enable the socket to listen even if proxy force mode is enabled?

I think I found 1 line which would have to be changed to something like this:

bt_peer_connection.cpp Line 2179

if (   ( !m_settings.get_bool(settings_pack::force_proxy) ||  m_settings.get_bool(settings_pack::listen_proxy) )   && is_outgoing())
handshake["p"] = m_ses.listen_port();

**Comment by arvidn** [comment]
It would be possible, but wouldn't it be a bit dangerous? the whole point of force_proxy is to fail closed in case any aspect of the proxy fails, including listening. I take it your proxy doesn't support listening, is that the case?
