### ISSUE TITLE
Can't to compile any example in Visual Studio 2015 Com.

### ISSUE THREAD

**Issue by taleh007** [arvidn/libtorrent#917]
I am trying to compile example from libtorrent path but I am getting one link error.

My steps:
1.Downloaded the latest version (1.10) of libtorrent from GitHub
2.Build Boost 1.61 with the following command "b2 --toolset=msvc-14.0  --build-type=complete stage -j4 " with success
3. Add BOOST_ROOT to "C:\boost_1_61_0" with the built file in "stage"
4. Build libtorrent with the following command  "b2 --toolset=msvc-14.0 link=static runtime-link=static"
5. Open Visual Studio 2015 and create NewProject->VC++->WIN32->ConsoleApplication (Empty project)
6. Add new .cpp file.
7. Copy source code from "simple_client.cpp" (.\libtorrent-master\examples) (Or from any other example)
8. Add BOOST_ROOT and .\libtorrent-master\include in Configur.Property->C\C++->General->AdditionalIncludeDirectories.
9. Add BOOST_ROOT\stage\lib and .\libtorrent-master\bin\msvc-14.0\debug\asserts-on\invariant-checks-on\link-static\runtime-link-static\threading-multi in Configur.Property->Linker->General->AdditionalLibraryDirectories.
10. Try to build solution........ and ta-ta-daaaam. Have errors:
    10.1)LNK2019	unresolved external symbol "struct libtorrent::storage_interface * __cdecl libtorrent::default_storage_constructor(struct libtorrent::storage_params const &)" (?default_storage_constructor@libtorrent@@YAPAUstorage_interface@1@ABUstorage_params@1@@Z) used in function  _main
    10.2)LNK2019	unresolved external symbol "public: void __thiscall libtorrent::settings_pack::set_str(int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?set_str@settings_pack@libtorrent@@QAEXHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) used in function  _main
.......
......
Other errors in attach text file
[erros.txt](https://github.com/arvidn/libtorrent/files/368217/erros.txt)

What's wrong?

p.s. This is my first experience using Boost and libtorrent, so can you explain more in detail?

**Comment by arvidn** [comment]
are you adding libtorrent and the boost libraries as link dependencies?
you could try building the examples with bjam (cd into the examples directory). If that works, build again with -an added to the command line. It will print out the commands to build rather than building, which you can use as hints of how to configure your project

**Comment by taleh007** [comment]
Yes, I was adding it at 9th step.
I already tried to build them with b2, and everything was good. Ok, I could try to do this, if this instruction help me, I will write, and if no too.
