### ISSUE TITLE
Added duplicate

### ISSUE THREAD

**Issue by Nick222** [arvidn/libtorrent#92]
When I download one torrent from web-page and add it in torrent client (which use libtorrent) and then - after few days (for example) - author of this torrent change it - and I download new torrent-file from this(!) web-page - I can add it in torrent client also.
It lead to conflict between this two torrents - because hashes are not the same - but hyper-links on torrent-pages in tracker are the same...

**Comment by arvidn** [comment]
what's the problem exactly? what would you expect libtorrent to do?

**Comment by Nick222** [comment]
Can libtorrent blocks adding torrent with same hyper-link or show message (with question, for example)?

**Comment by arvidn** [comment]
if you add both torrents by URL, in theory libtorrent could detect that there is a torrent with that URL already, but it's not at all obvious that one would want to block the second torrent. I can imagine, for instance, that when using a mutable torrent adding the second one is exactly what you want to do. This sound like a UX issue more appropriately handled in the client, which may have more information about what the user intends.
