### ISSUE TITLE
assertion failed in bt_peer_connection::write_bitfield()

### ISSUE THREAD

**Issue by jonathanmcdougall** [arvidn/libtorrent#923]
RC_1_1

I'm tripping the assert on `bt_peer_connection.cpp:2105`:

    // if we have not received the other peer's extension bits yet, how do we
    // know whether to send a have-all or have-none?
    TORRENT_ASSERT(m_state >= read_peer_id);

Simplified stack trace:

    bt_peer_connection::write_bitfield() Line 2105
    bt_peer_connection::on_metadata() Line 285
    peer_connection::on_metadata_impl() Line 698
    torrent::init() Line 1936
    torrent::set_metadata() Line 7912
    ut_metadata_plugin::received_metadata() Line 627
    ut_metadata_peer_plugin::on_extended() Line 423
    bt_peer_connection::on_extended() Line 1791
    bt_peer_connection::dispatch_message() Line 1965
    bt_peer_connection::on_receive_impl() Line 3544
    bt_peer_connection::on_receive() Line 2631
    peer_connection::receive_data_impl() Line 6207
    peer_connection::on_receive_data_nb() Line 6093

The `bt_peer_connection` at the start of the stack trace has `m_state == read_packet` and called into the `ut_metadata` plugin. The plugin then called `torrent::set_metadata`, which initialized the torrent, which loops through all the peers. However, all the other peers in the list have `m_state == read_protocol_identifier`. This is what trips the assert in `write_bitfield()`.

The assert has been introduced by a commit on June 7: [revert handshake round-trip optimization](https://github.com/arvidn/libtorrent/commit/5eaf713d1f2a893f8d4c9fac34e5c6b1bebe460d#diff-8583926df55348a458f0f9e1c4b34b86R2089).

**Comment by arvidn** [comment]
thanks for the report! does this patch fix it? https://github.com/arvidn/libtorrent/pull/925

**Comment by jonathanmcdougall** [comment]
Looks good, the assert doesn't fire anymore.
