### ISSUE TITLE
Remove methods load_asnum_db and load_country_db from python bindings in 1.1

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#927]
This [change](https://github.com/arvidn/libtorrent/commit/9c2472f7bbc35a33c5edda8e7d4dfab320dc663c) should have removed the methods in python bindings entirely as with geoip disabled clients were expecting that. In the current situation we are unable to fallback, i.e. determine if geoip is disabled as the methods permanently exist.

**Comment by arvidn** [comment]
The reason I left them in was to provide backwards compatibility with untouched older clients. I would suggest newer clients that want geoip would depend directly on it and not assume it's provided by libtorrent. If you need to know, you could base it on the libtorrent version

**Comment by cas--** [comment]
I understand that but clients in the old code still had to check in case libtorrent was built without geoip suport (the methods were removed) which is the case now so by leaving the stubs it's breaking compatibility.

**Comment by arvidn** [comment]
Ah, I see. I forgot that that used to be an option

**Comment by arvidn** [comment]
does this seem reasonable? https://github.com/arvidn/libtorrent/pull/930
