### ISSUE TITLE
Minimum boost version for libtorrent 1.1 should be v1.53

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#928]
I got the following error when building and found that boost 1.48 doesn't contain `boost-atomic` and apparently it was introduced in 1.53. 

`fatal error: boost/atomic.hpp: No such file or directory`

Also `boost-atomic` needs to be added to the configure checks.

**Comment by arvidn** [comment]
Is it not sufficient to check the boost version? or is there a library dependency for boost.atomic?

**Comment by cas--** [comment]
Yes there is a lib dependency on debian it's `libboost-atomic-dev` so got quite far into the build before that error was raised.

**Comment by arvidn** [comment]
as far as I can tell nobody has written an m4 script for boost.atomic. does libtorrent depend on anything in the library? (or just the headers?)

**Comment by arvidn** [comment]
well, this is the easy part. homebrew on osx does not seem to have a separate boost.atomic library. https://github.com/arvidn/libtorrent/pull/935

**Comment by cas--** [comment]
You might be right, likely just the headers required, I assumed `-dev` package was needed, obviously it would also install `libboost-atomic` with the required headers at the same time.

Did you see this commit for a possible m4 atomic script: https://github.com/openstreetmap/osm2pgsql/pull/355

**Comment by cas--** [comment]
From my testing I have found that need to also update [ax_boost_base.m4](http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_boost_base.m4) because it is failing to search in arch specific lib dirs so only `/usr/lib` and not also `/usr/lib/i386-linux-gnu/`.

**Comment by arvidn** [comment]
I believe this has been fixed now, right?

**Comment by cas--** [comment]
Yes everything fine with those changes from #937 applied.
