### ISSUE TITLE
DHT bootstrap attempted before routers resolve

### ISSUE THREAD

**Issue by jpetso** [arvidn/libtorrent#94]
When one adds a DHT router and then starts the DHT, the bootstrap might not occur until after a timeout because asio IP resolution is asynchronous and the `dht_tracker` class only receives the resolved IP after the bootstrap call has been placed. Quoting @arvidn from PR #46:

> I think it should probably be solved properly by postponing the bootstrap if there are outstanding hostname lookups for dht routers. Or perhaps by re-starting the bootstrap when the first router is added if the routing table is empty. (the latter is probably quite simple)

As of right now, there is neither an alert for IP resolution that an application could wait for, nor logic within libtorrent that would fix this issue transparently.

**Comment by arvidn** [comment]
what do you think about this? https://github.com/arvidn/libtorrent/pull/95

**Comment by jpetso** [comment]
Fixed by Arvid's PR #95, which is now in master.
