### ISSUE TITLE
Saving torrent in python doesn't work

### ISSUE THREAD

**Issue by tete1030** [arvidn/libtorrent#945]
**Please provide the following information**

libtorrent version (or branch):
master

platform/architecture:
X86_64

compiler and compiler version:
gcc 4.9.2

please describe what symptom you see, what you would expect to see instead and
how to reproduce it.

I was trying to save torrent file after receiving metadate_received_alert in python using following code.
```
torrent_handle = alert.handle
torrent_info = torrent_handle.torrent_file()
ct = libtorrent.create_torrent(torrent_info)
entry = ct.generate()
content = libtorrent.bencode(entry)
with open('test.torrent', 'wb') as f:
    f.write(content)
```

But the generated torrent file is always invalid because it's content is like this:
```
d13:creation datei1469416855e4:info0:e
```

I found that this problem came from
```
entry = ct.generate()
```

The returned `entry` is a dict as 
```
{
    'creation date': 1469416855,
    'info': None
}
```
and the value of `info` in this dict is `None`, which is not right. 

After digging into python binding code, I found the cause. The code in `bindings/python/src/entry.cpp` has defined to-python and from-python converters for `struct entry`. But it missed the entry type `preformatted_type` which is also the type of `info` field returned by `generate()` method. This caused to-python-converter returning `object()`. I guess an empty object means `None` in python.

I'm not familiar with boost-python, so I'm not sure how to fix this. Thanks

**Comment by tete1030** [comment]
The `info` field is actually formatted metadata. So currently my workaround is decoding metadata and filling decoding result into the `info` field. It works well.
```
torrent_handle = alert.handle
torrent_info = torrent_handle.torrent_file()
ct = libtorrent.create_torrent(torrent_info)
entry = ct.generate()
entry['info'] = lt.bdecode(ti.metadata())
content = lt.bencode(entry)
with open('test.torrent', 'wb') as f:
    f.write(content)
```

**Comment by arvidn** [comment]
ah, this is an oversight. Your workaround should work for 99.9% of torrents. Some torrents have invalid orders of fields, which makes decoding -> encoding alter the order and the info-hash. That's why preformatted exists.

**Comment by arvidn** [comment]
I believe this affects RC_1_1 as well

**Comment by tete1030** [comment]
Thanks for your tip.

**Comment by arvidn** [comment]
please try this patch. It's against RC_1_1, but I believe it applies cleanly against master too.
https://github.com/arvidn/libtorrent/pull/952

**Comment by arvidn** [comment]
it's been merged to RC_1_1

**Comment by tete1030** [comment]
Sorry for late reply. I tried this patch and it fixed the problem in master, thank you.
