### ISSUE TITLE
disk_buffer_pool.cpp gcc warning: ignoring return value of declared with attribute

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#954]
A trivial issue but I often end up staring at this gcc warning and I thought it worth logging it along with some research I did into it...

The solution is to cast to `(void)` the offending method calls in disk_buffer_pool.cpp, unless of course you feel some of the methods require the return value handled?

The only issue with using void is that gcc will then generate a different warning for this usage but at least the code is more correct than before. This gcc 'issue' was originally covered in [#25509](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=25509) but a more recent ticket [#66425](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66425) proposes properly addressing it so that future gcc versions will not warn about void usage.

Log snippet from gcc:
```
src/disk_buffer_pool.cpp: In member function 'void libtorrent::disk_buffer_pool::set_settings(const libtorrent::aux::session_settings&, boost::system::error_code&)':
src/disk_buffer_pool.cpp:463:28: warning: ignoring return value of 'int ftruncate(int, __off64_t)', declared with attribute warn_unused_result [-Wunused-result]
src/disk_buffer_pool.cpp:485:63: warning: ignoring return value of 'int ftruncate(int, __off64_t)', declared with attribute warn_unused_result [-Wunused-result]
src/disk_buffer_pool.cpp:495:30: warning: ignoring return value of 'int ftruncate(int, __off64_t)', declared with attribute warn_unused_result [-Wunused-result]
src/disk_buffer_pool.cpp: In destructor 'libtorrent::disk_buffer_pool::~disk_buffer_pool()':
src/disk_buffer_pool.cpp:126:28: warning: ignoring return value of 'int ftruncate(int, __off64_t)', declared with attribute warn_unused_result [-Wunused-result]
```

**Comment by arvidn** [comment]
yeah, all ftruncate() calls are best effort, they should be cast to void

**Comment by arvidn** [comment]
attempted fix here: https://github.com/arvidn/libtorrent/pull/971

**Comment by cas--** [comment]
Cool, I'll test that out tomorrow

**Comment by cas--** [comment]
Yep that's perfect, no warnings at all :)
