### ISSUE TITLE
Compilation hangs on Python Bindings build

### ISSUE THREAD

**Issue by RDgiuliom** [arvidn/libtorrent#966]
**Please provide the following information**

libtorrent version (or branch): 1.1.0 (tarball)

platform/architecture: armv7, LeMaker BananaPi

compiler and compiler version: gcc in standard Jessie repo.

Hi guys, I'm struggling to compile LibTorrent and the Make process always hangs at the same position. The compiler has been stuck at that point for more than 24hrs, I had memory fully occupied and almost all the swap file full so I decided to stop.

`/home/giulio/libtorrent-rasterbar-1.1.0/bindings/python/src/session.cpp: In function ‘void {anonymous}::start_upnp(libtorrent::session&)’:
/home/giulio/libtorrent-rasterbar-1.1.0/bindings/python/src/session.cpp:414:22: warning: ‘void libtorrent::session_handle::start_upnp()’ is deprecated (declared at ../../include/libtorrent/session_handle.hpp:1049) [-Wdeprecated-declarations]
         s.start_upnp();
                      ^
/home/giulio/libtorrent-rasterbar-1.1.0/bindings/python/src/session.cpp: In function ‘boost::shared_ptr<libtorrent::alert> {anonymous}::wait_for_alert(libtorrent::session&, int)’:
/home/giulio/libtorrent-rasterbar-1.1.0/bindings/python/src/session.cpp:429:50: warning: ‘std::auto_ptr<libtorrent::alert> libtorrent::alert::clone() const’ is deprecated (declared at ../../include/libtorrent/alert.hpp:274) [-Wdeprecated-declarations]
         return boost::shared_ptr<alert>(a->clone().release());
                                                  ^
/home/giulio/libtorrent-rasterbar-1.1.0/bindings/python/src/session.cpp: In function ‘boost::python::list {anonymous}::get_cache_info2(libtorrent::session&, libtorrent::sha1_hash)’:
/home/giulio/libtorrent-rasterbar-1.1.0/bindings/python/src/session.cpp:483:37: warning: ‘void libtorrent::session_handle::get_cache_info(const libtorrent::sha1_hash&, std::vector<libtorrent::cached_piece_info>&) const’ is deprecated (declared at ../../include/libtorre$
           ses.get_cache_info(ih, ret);
                                     ^
/home/giulio/libtorrent-rasterbar-1.1.0/bindings/python/src/session.cpp:487:20: warning: ‘libtorrent::time_point libtorrent::time_now()’ is deprecated (declared at ../../include/libtorrent/time.hpp:109) [-Wdeprecated-declarations]
        ptime now = time_now();
                    ^
/home/giulio/libtorrent-rasterbar-1.1.0/bindings/python/src/session.cpp:487:29: warning: ‘libtorrent::time_point libtorrent::time_now()’ is deprecated (declared at ../../include/libtorrent/time.hpp:109) [-Wdeprecated-declarations]
        ptime now = time_now();
                             ^
/home/giulio/libtorrent-rasterbar-1.1.0/bindings/python/src/session.cpp: In function ‘boost::python::api::object {anonymous}::pop_alert(libtorrent::session&)’:
/home/giulio/libtorrent-rasterbar-1.1.0/bindings/python/src/session.cpp:519:31: warning: ‘std::auto_ptr<libtorrent::alert> libtorrent::session_handle::pop_alert()’ is deprecated (declared at ../../include/libtorrent/session_handle.hpp:924) [-Wdeprecated-declarations]
             a = ses.pop_alert();
                               ^
/home/giulio/libtorrent-rasterbar-1.1.0/bindings/python/src/session.cpp: In function ‘boost::python::list {anonymous}::pop_alerts(libtorrent::session&)’:
/home/giulio/libtorrent-rasterbar-1.1.0/bindings/python/src/session.cpp:537:61: warning: ‘std::auto_ptr<libtorrent::alert> libtorrent::alert::clone() const’ is deprecated (declared at ../../include/libtorrent/alert.hpp:274) [-Wdeprecated-declarations]
             ret.append(boost::shared_ptr<alert>((*i)->clone().release()));`

I would like to understand if I'm doing something idiotic myself (can't say I'm an expert Linux compiler) or it's just my board that can't take it. 

If it's more likely to be the second case, is there a way to figure this out and let me compile lib torrent python bindings?

Thanks.

Bye.

**Comment by arvidn** [comment]
unless you are already, you really need to use a proper desktop for building (cross compiling).

**Comment by RDgiuliom** [comment]
Ok, I've setup a desktop machine and in fact the compilation is now much faster but I'm still having issues in compiling python bindings for Arm.

Now my problem is that even though I can correctly cross compile using 
`--host=arm-none-linux-gnueabi --target=arm-none-linux-gnueabi`

The python building is made only for `x86_64-linux`.

So when I install the .deb package created with Checkinstall, it is installed correctly but as soon as I try to import libtorrent in python I'm getting this error:

`mportError: /usr/local/lib/python2.7/dist-packages/libtorrent.so: wrong ELF class: ELFCLASS64`


I've tried to manually build the python package using

`python setup.py build --plat-name Linux-armv7l`

But I'm getting this error:

`error: --plat-name only supported on Windows (try using './configure --help' on your platform)`

Any suggestions?

**Comment by arvidn** [comment]
I'm not familiar with how or if distutils in python supports cross compilation. But it sounds like the python binding is not using the correct compiler. do you build it by manually invoking setup.py?

**Comment by rindeal** [comment]
Just FYI, native builds on headless arm boards are possible. I'm using Gentoo on them without any hassle.

**Comment by RDgiuliom** [comment]
@arvidn I've tried many setups:
- On arm board tried `./configure --enable-python-binding `--disable-debug` then `make` and `make install` or `checkinstall`. I've played around alot with -j and -l arguments of make but the compilation takes about 48hrs and then the OS kills it.

- On desktop system I've been able to compile in few minutes with the pyhton bindings enabled and then I've tried several options to get a correct python package:

1. Let `checkinstall` create an armhf package -> no success as mentioned above

2. Tried to manually invoke `python setup.py build --plat-name=linux-armV7l` -> no success, it says that the only architecture available is `linux-x86_64`

@rindeal I believe is possible but I think it depends on the specs of the board you're using to compile. I'm on a BananaPi having 1GB of RAM and a 1GHZ armv7 processor. What are you compiling on? Could you please share your setting?

**Comment by rindeal** [comment]
@RDgiuliom sure, the weakest hw I compiled it on is RPi B+ (512M RAM, armv6)

**Comment by RDgiuliom** [comment]
@rindeal did you also compiled the python bindings? It seems the hard part for the board is that.

Any suggestion on how to successfully compile libtorrent with pyhton bindings on my board?

**Comment by rindeal** [comment]
yeah, including the bindings, but I compiled it using Portage and not by hand. So you should just copy what Portage does and it should work. You can get some idea by reading https://github.com/rindeal/gentoo-overlay/blob/master/net-libs/libtorrent-rasterbar/libtorrent-rasterbar-1.1.0.ebuild and https://github.com/gentoo/gentoo/blob/master/eclass/distutils-r1.eclass

**Comment by RDgiuliom** [comment]
@rindeal thank you, I'm not sure I did it right but I've configured with most of the arguments I've seen [HERE](https://github.com/rindeal/gentoo-overlay/blob/master/net-libs/libtorrent-rasterbar/libtorrent-rasterbar-1.1.0.ebuild) even tough I found out that the 'mt' suffix in boost_system has been deprecated so I removed it. Is compiling for 3hrs now and going on...finger crossed. 

@arvidn If this should fail again, there's no way I can correctly cross compile the python package on the desktop linux?

Thanks for your support

**Comment by RDgiuliom** [comment]
No luck even with the @rindeal suggestions, actually with the arguments from Gentoo Portage, the compilation stops early.

Here the final part of the make output.

`CXX      torrent.lo
  CXX      torrent_handle.lo
make: *** wait: No child processes.  Stop.
Makefile:970: recipe for target 'torrent.lo' failed
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.
make[1]: *** [torrent.lo] Hangup
Makefile:970: recipe for target 'torrent_handle.lo' failed
make[1]: *** [torrent_handle.lo] Hangup
Hangup
Hangup`

**Comment by arvidn** [comment]
I would expect building with boost-build should let you correctly cross-compile everything. you would need to configure a gcc cross-compiler toolset in ~/user-config.jam (the .travis file does this when building and testing the arm target)

**Comment by arvidn** [comment]
also, for building on a small machine, I would imagine you want to build no more than one file at a time (i.e. -j1).

**Comment by arvidn** [comment]
@cas-- right now the makefiles simply invokes python setup.py (after building the main library), without passing on which compiler it's using. Can you think of a way to fix this?

For instance, in master right now, the python binding fails to build using autotools because it's not being built as c++11. Does it make sense to use the python distutils to build the python module still?

Perhaps the makefiles should just be extended to be responsible for building that as well.

I get the impression that perhaps there are other python package managers that may becoming more popular too.

**Comment by RDgiuliom** [comment]
@arvidn Thank you for your inputs, I'm trying to setup an armhf chroot right now and trying to cross compile there (seems easier for me since I don't have large experience in this field). If it fails I'm going to try building directly with Boost.

About the -j1 option, I've already tried it and it helps quite a lot for the standard libtorrent building but as soon as the seutp.py kicks in, the -j1 seems to be ignored and then the SBC resources gets completely dried out.

I've also tried to build the master branch but as you said, I get the error about the c++11.

**Comment by cas--** [comment]
As far as I am aware after much debate distutils is the defacto package manager. So I think it is correct to build in setup.py. There are improvements to be made to it though and perhaps compiler selection is possible. Since it has worked as is I was reluctant to change things ;-) 

@RDGIULIOM there is a -j option in setup.py you should modify.

**Comment by RDgiuliom** [comment]
@cas-- thank you, how do I apply it? Do I have to write it into the setup,py or pass the -j option as option to the main ./configure?

**Comment by cas--** [comment]
It would need manually changing but forgot it applies to boost build only: https://github.com/arvidn/libtorrent/blob/master/bindings/python/setup.py#L78

For autotools I don't believe that it does parallel builds in setup.py.

**Comment by RDgiuliom** [comment]
Not sure the compilation fails due to the parallel build...I just see it fails...

**Comment by RDgiuliom** [comment]
I finally did it! Compiled on an armhf emulated chroot on an amd64 machine. Worked just fine!

Thanks all for your suggestions.

**Comment by rindeal** [comment]
emulated? that must have taken a whole day to complete...

**Comment by RDgiuliom** [comment]
@rindeal considering that on the actual armhf board the last time it took about 32hrs and then failed, the compilation time is not a problem for me :-)

In any case I've compiled on my Work PC (while I was working) which is a Core i3 with 6GB of RAM on a VMWare Workstation Debian x64 virtual machine with 4 cores and 4GB of RAM, inside the emulated armhf chroot and it took about 4hrs, so a fairly small amount of time all considered.

**Comment by rindeal** [comment]
well, I just finished compilation on RPi B and it took 2,5 hours, so the emulation is still utterly slow. Those 32 hours must have been some recursion/loop bug.

**Comment by RDgiuliom** [comment]
I'm on a LeMaker BananaPi with Armbian installed. Different microcontroller, maybe less optimization...I don't know.

Did you compile with python bindings enabled?

In any case since it's a board related problem I think the issue could be closed.

Thank you all.

**Comment by rindeal** [comment]
yeah, always with the bindings because of deluge

**Comment by arvidn** [comment]
wow, 2.5 hours. I build all of libtorrent in 3 minutes or so.

**Comment by RDgiuliom** [comment]
Yeah on x86/x64 machines that's the amount of time needed 😁

**Comment by cas--** [comment]
Thought I should mention that if you are going to lengths of compiling on your desktop you should look into cross-compiling for arm cpu, likely require a bit more configuration but would be the fastest way to compile it for RPi. (minutes vs hours)

**Comment by RDgiuliom** [comment]
@cas-- Yes, that was my first try on desktop but I've run into a lot of dependency issues. I will probably try again in the next few weeks now that I've recovered my download server server and I have time to play around.

Thanks.

**Comment by arvidn** [comment]
@cas-- that's partly why I pinged you in this thread. The cross compilation failed (iirc) because setup.py ended up using the host compiler, rather than the one configured by autotools

**Comment by cas--** [comment]
While I remember distutils does have a `--compiler` option to pass to setup.py so I assume you can modify the bindings makefile like this: `$(PYTHON) $(srcdir)/setup.py build --compiler=$(CXX)`
