### ISSUE TITLE
Problem in piece_picker::priority_range

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#972]
libtorrent :  master

I recently saw a crash `signal 8 (SIGFPE)` in `piece_picker::add` and I think it's due to this line
```
else new_index = random() % (range_end - range_start + 1) + range_start;
```
I see `priority_range` has an `ASSERT` but that assert does not exist in release, my questions are:

1 - do you think `m_priority_boundries` could be mutated in the middle of `priority_range`?
2 - if 1) can happens, what can I do to avoid the crash?
3 - Is it really `boundries` or `boundaries`?

**Comment by arvidn** [comment]
(1) If you're getting division by zero, it certainly seems like the boundaries array can become corrupt somehow. It doesn't seem covered by the invariant check. It should be.
(2) when you say mutated, you mean have its invariant broken by a having a lower-index slot have a value greater than that in a higher-index slot, right? It isn't supposed to happen. I will add it to the invariant checks.
(3) it should be "boundaries".

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/pull/977

**Comment by aldenml** [comment]
Thanks, I will reopen in case the problem reappears.

**Comment by arvidn** [comment]
that patch doesn't attempt to fix the issue, just make it more likely to get caught earlier in debug builds

**Comment by aldenml** [comment]
yes, I know, but the crash was reported only one time in android developer console (out of many users) and it could even be memory corruption. Feel free to open if you feel it's necessary.

**Comment by aldenml** [comment]
Just to document that https://github.com/arvidn/libtorrent/pull/983 seems to point to the same invalid state

**Comment by arvidn** [comment]
I believe steven's patch will fix this in RC_1_1 https://github.com/arvidn/libtorrent/pull/987 and if all works out well, I will probably merge my forward-port + unit test into master https://github.com/arvidn/libtorrent/pull/989

**Comment by arvidn** [comment]
these have both been merged now
