### ISSUE TITLE
Upgrading from 1.0.7 to 1.0.9 not honouring session settings with python bindings

### ISSUE THREAD

**Issue by cas--** [arvidn/libtorrent#984]
With the latest release of Deluge I updated libtorrent to 1.0.9 and have users complaining about session settings no longer being set to their values and instead reverted to libtorrent default values.

http://dev.deluge-torrent.org/ticket/2863#comment:16

I cannot replicate myself yet but thought I would open an issue to see if you have any ideas of the changes from 1.0.7 to 1.0.9 that might affect this.

**Comment by arvidn** [comment]
if you save session state, settings are included in there as well, so you you load your own settings first and then load session state, yours will be overridden. Could that be it?

**Comment by cas--** [comment]
We load session state first so it's not that. Without more details to provide from users it's all just hypothetical, it was just odd that the change in libtorrent version coincided with reports of reset queue settings. I shall close this ticket for now.
